### ISSUE TITLE
CORS HTTP patch request is not working on IE10/11

### ISSUE THREAD

**Issue by tomchentw** [jquery/jquery#1684]
See https://github.com/jquery/jquery/issues/1684#issuecomment-65758579 for latest update.

**Comment by mzgol** [comment]
@tomchentw Could you check if this works fine for you with https://dl.dropboxusercontent.com/u/10200888/jquery/jquery-cors.js? I submitted a PR with such a patch: #2183.

**Comment by tomchentw** [comment]
Currently don't have an IE environment to test with...

**Comment by mzgol** [comment]
jsFiddle broke jQuery Edge URLs; apparently jQuery Compat Edge & jQuery Edge are swapped. :/ See https://github.com/jsfiddle/jsfiddle-issues/issues/600

It's better to use jsbin now.

**Comment by mzgol** [comment]
Closed via #2183, laded at 61f812b7e7b88dd6e0078c241e4c88905ea51562.
