### ISSUE TITLE
IE8 Selector Bug

### ISSUE THREAD

**Issue by vol7ron** [jquery/jquery#1687]
### Problem / Issue

There's a known issue with IE8 and HTML5, that when it clones/adds a *non-standard* element to the page, it adds a blank prefix to the tag (and includes the colon).  
_Note: "non-standard" is not exactly correct, there are standard, less common elements that this also happens to._

jQuery is not selecting those blank-prefixed elements when there's a multi-stage (combo) selector.  It works with `find()` and using the tagname without the prefix, but not when using a selector pattern like `$('<ancestor> <descendant>');`.  Refer to the example below, for a clearer understanding.

_Affected Browsers: I only know this applies to IE8.  I'm doubtful that it applies to other versions of IE, but I'm not able to test._

---
### Update

My statement above isn't exactly correct; `.find()` doesn't necessarily solve the issue.  You'll notice inconsistent behavior when you use pseudo-selectors, such as `:visible`.  The demo shows that the IE8 bug (prefixed colon) is not handled using jQuery, and using pseudo-selectors should at least be consistent with selecting by element tagname (whether it includes the prefixed elements, or not).  That is `$('some-element');` and `$('some-element:visible');` should return the same results, if there are no hidden `some-element`.

The behavior I found in IE8 is that `$('some-element:visible')` acts like `$('some-element:visible,\\:some-element:visible')`.  What I'm after is something to patch the IE prefix bug so that `$('some-element')` acts like `$('some-element,\\:some-element')`.

---
### Demo / Test Case

http://jsfiddle.net/vol7ron/9sverLdu/
http://fiddle.jshell.net/vol7ron/9sverLdu/show/  (for IE8 testing)

```
<some-element>
    <span>foo</span>
</some-element>



<script>
    // Add custom element to DOM for IE8
    document.createElement('some-element');


    jQuery(document).ready(function ($) {
        var $el = $('some-element');
        var $clone = $el.clone();

        // create a copy of the element after the original
        // IE8 should create an element with a blank prefix <:some-element>...</:some-element>
        $el.after($clone);

        // method 1
        outputLength( 
            "$('some-element span').length", 
            $('some-element span') 
        );

        // method 2
        outputLength( 
            "$('some-element').find('span').length", 
            $('some-element').find('span') 
        );

        // method 3
        outputLength( 
            "$('some-element span, \\\\:some-element span').length", 
            $('some-element span, \\:some-element span') 
        );


        // method 4
        outputLength( 
            "$('some-element:visible span').length", 
            $('some-element:visible span') 
        );

    });

    function outputLength(_label, _elems){
        var $label  = jQuery('<label />').html(_label + ' : ');
        var $value  = jQuery('<span  />').html(_elems.length);
        var $output = jQuery('<div />').append($label,$value);
        jQuery('body').append($output);
        console.log($output.html(), _elems);  // incase you prefer console
    }
</script>
```

**Comment by Basemasta** [comment]
I guess this jsbin output is clear enought : https://output.jsbin.com/fukasak

**Comment by gibson042** [comment]
You have run across a [very old non-jQuery bug](http://www.paulirish.com/2011/the-history-of-the-html5-shiv/), but the solution¹ is as simple as `document.createElement`: https://jsbin.com/hegapelado

¹ https://github.com/aFarkas/html5shiv

**Comment by Basemasta** [comment]
@gibson042 You are right. I was already using `document.createElement` but not inside the `<head>` tag.

**Comment by vol7ron** [comment]
I don't know why there is so much haste in closing an issue that you have not determined to be a non-issue.  The burden of proof was on me, I created an example.  Others confirmed it was an issue.

The burden of proof to close the issue should be displayed. Someone should say it's been patched and then we should be able to test against a patch.

I don't respond to these comments when they haven't contributed that information. The continual preemptive closing and lack of confidence that an issue exists (without testing it yourself) is also discouraging - it sends the message that we shouldn't report bugs and even further, maybe should stop using the library. Maybe that's the solution? - stop using a library. I don't want to support IE8, but I do because some people have no other option.  I invested time in reporting this big and following up with it for our users, not for me.  For it to be closed so quickly without the appreciation of my effort and time is disheartening.

I came to GitHub because

**Comment by jasper2virtual** [comment]
@vol7ron   I have the same problem as you, I have no option that some my users still using IE8. By the way, as far as I know today, I can only work around it by giving the non-standard element ID <id="foo" some-element>, and  selecting by ID . eg . $('#foo'). I agree with you, it is a Jquery bug, IE7 have no problem. IE9 has no problem. Why IE8.....
