### ISSUE TITLE
Download builder

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#1691]
Let's make one so people can't complain it's hard.

**Comment by dmethvin** [comment]
I don't think it's likely we'll get this out at the same time as the 3.0 release, but it's not strictly tied to a release.

**Comment by timmywil** [comment]
Closing in favor of tracking in the [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap).

**Comment by srahulprdxn** [comment]
Atleast if not a builder, jquery should be divided in libraries. For example, I just wanted to use the DOM manipulation part of jquery. I didn't want ajax included to increase the file size. Using a module like jquery/libs/core-dom would be great to reduce the file size.

**Comment by mgol** [comment]
@srahulprdxn You can use the AMD modules in `src/` for that purposes.

**Comment by srahulprdxn** [comment]
@mgol Thanks a lot for addressing. Exactly what I needed.
