### ISSUE TITLE
Make jQuery collections for-of-able

### ISSUE THREAD

**Issue by simevidas** [jquery/jquery#1693]
Chrome 38 added support for ES6 `for-of`. I'm proposing that jQuery collections are made compatible with this statement, which can be achieved with this line (from [discussion on Twitter](https://twitter.com/domenic/status/520384658555809792)):

```js
jQuery.prototype[Symbol.iterator] = Array.prototype.values;
```

**Live demo:** http://jsbin.com/movuxu/1/edit (view in Chrome)

**Comment by spicyj** [comment]
I'd love to see this. Would make using jQuery with Babel more palatable.

**Comment by timmywil** [comment]
You know, I'm not actually against this.

**Comment by mzgol** [comment]
It'd be cool to have this natively in 3.0; even if simple. :)

**Comment by mzgol** [comment]
The biggest problem is size, I guess. The following:
```js
if ( typeof Symbol !== "undefined" && Symbol.iterator ) {
	jQuery.fn[Symbol.iterator] = [][Symbol.iterator];
}
```
increases the gzipped size by 32 bytes. Other forms seem larger.

**Comment by mzgol** [comment]
Since there is no definite decision yet, let's reopen for now.

**Comment by jrencz** [comment]
The concept has already been described by @jakearchibald in Dec 2004 for NodeList: http://jakearchibald.com/2014/iterators-gonna-iterate/#nodelist-iteration

**Comment by mzgol** [comment]
We've decided we're going to do it in 3.0.0. Taking it.

**Comment by mzgol** [comment]
PR: #2369
