### ISSUE TITLE
Safari detected as IE < 8

### ISSUE THREAD

**Issue by tgfjt** [jquery/jquery#1701]
In case of `body {zoom: 1.2}` (or 1.1, 1.6) on Safari, get `div.offsetWidth === 3`, then body's zoom forcibly set 1 on this:
https://github.com/jquery/jquery/blob/master/test/data/jquery-1.9.1.js#L1519

Check this below.
https://gist.github.com/tgfjt/ce0d9e419036904649de

**Comment by mzgol** [comment]
Since we're not releasing `compat` and this fix depended on us dropping IE6-7 which is not happening in jQuery 1.12, I'm moving it to wontfix.
