### ISSUE TITLE
Remove sizzle expando after clone action

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1709]
Originally reported by Jogi: http://bugs.jquery.com/ticket/15104

Issue with space in selector with jquery 1.11.1 and Internet explorer.

exemple:

$(".testCls [name='blabla']")

cannot find anything when with older version, it work.

jsfiddle:  http://jsfiddle.net/kwfHZ/1/

**Comment by markelog** [comment]
@gibson042 please ping me up when you gonna update sizzle
