### ISSUE TITLE
width(), height(), etc. shouldn't round

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1724]
Originally reported by john at: http://bugs.jquery.com/ticket/9628
<p>
Right now we're rounding off the answers from width(), height(), etc. to the nearest pixel - this makes it hard to do good positioning of elements (especially for animations). For example if you have 3 items that are width 33% inside of a 100px element we're returning 33px for each element. Theoretically an animation method might be able to return a more interesting result if they know that there are extra fractional-numbers getting rounded off.
</p>
<p>
I got a report on this directly from Mozilla but I agree with them that this particular change makes it hard to get to good numbers.
</p>
<p>
See also: <a class="closed ticket" href="http://bugs.jquery.com/ticket/3239" title="bug: innerHeight/outerHeight does not round up (closed: fixed)">#3239</a>.
</p><p>Issue reported for jQuery 1.6.1</p>

**Comment by MarventusWP** [comment]
I would like to add, since I don't see it mentioned anywhere in here, that .css("height") and .css("width") are also rounding values. Here's a fiddle: http://jsfiddle.net/Marventus/L16gmjuz/
Hope this  helps.

**Comment by mzgol** [comment]
> I would like to add, since I don't see it mentioned anywhere in here, that .css("height") and .css("width") are also rounding values.

Yes, that's caused by the same code. `.css('width')` is going through a special hook instead of `getComputedStyle` so that it works on disconnected nodes, see:
https://github.com/jquery/jquery/blob/002240a6eb1cee2fcd886d5cf44893eb67f246f1/src/css.js#L71-L152
and:
https://github.com/jquery/jquery/blob/002240a6eb1cee2fcd886d5cf44893eb67f246f1/src/css.js#L353-L382

That's quite a lot of code, btw...

**Comment by AurelioDeRosa** [comment]
Hi guys. What's the state of this issue? Will it be fixed in jQuery 3?

**Comment by arthurvr** [comment]
@AurelioDeRosa Well, it's on the v3.0 milestone at least. :)

**Comment by AurelioDeRosa** [comment]
@arthurvr I saw the label as well but this doesn't reply to my question.

**Comment by mzgol** [comment]
@AurelioDeRosa It's planned for 3.0 and I'm assigned. I just need to get to it. :) I'll try to do it soon, I'd like it to land before we tag the first beta.

**Comment by mzgol** [comment]
PR: #2439. Feedback welcome.

**Comment by mzgol** [comment]
`compat` version of the PR: #2454.

**Comment by timmywil** [comment]
I've added a note to the blog post.

**Comment by mgol** [comment]
As reported in #2889, Chrome is deprecating `offsetWidth` & `offsetHeight` on SVG elements. We don't officially support them but it's good to know we buy more than just having fractional data by switching to `getBoundingClientRect()`.
