### ISSUE TITLE
jQuery.data first access performance very bad

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1728]
Originally reported by daliuskal@… at: http://bugs.jquery.com/ticket/14839
<p>
<a class="ext-link" href="http://jsfiddle.net/6DLSw/12/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/6DLSw/12/</a>
2s+ first time, ~50ms later on. The first run is extremely slow.
</p>
<p>
<a class="ext-link" href="http://jsfiddle.net/6DLSw/13/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/6DLSw/13/</a>
~50ms when jQuery.data(el) was already called (note that the key doesn't matter).
</p>
<p>
The bug seems to have started with version 2.0.2 or so, when the jQuery.data was rewritten.
</p>
<p>
Using 1.11.0 on first case takes ~190ms first time, other times it's ~60ms.
</p>
<p>
This is affecting jquery ui performance very badly, e.g. <a class="ext-link" href="http://jsfiddle.net/6DLSw/6/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/6DLSw/6/</a> - first red rectangle drop takes 2s+.
</p><p>Issue reported for jQuery 2.1.0</p>

**Comment by timmywil** [comment]
Related trac ticket moved to https://github.com/jquery/jquery/issues/1734 on github
