### ISSUE TITLE
SourceURL support for scripts loaded by domManip using XHRs.

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1733]
Originally reported by vsevik@… at: http://bugs.jquery.com/ticket/11484
<p>
This ticket is inspired by discussion in Chrome Developer Tools mailing group: <a class="ext-link" href="https://groups.google.com/group/google-chrome-developer-tools/browse_thread/thread/e22f4cb5b0685dbd" rel="nofollow"><span class="icon">&nbsp;</span>https://groups.google.com/group/google-chrome-developer-tools/browse_thread/thread/e22f4cb5b0685dbd</a>
</p>
<p>
SourceURL is a way to give a name to the script executed by eval() for debugging purposes. 
See <a class="ext-link" href="http://blog.getfirebug.com/2009/08/11/give-your-eval-a-name-with-sourceurl/" rel="nofollow"><span class="icon">&nbsp;</span>http://blog.getfirebug.com/2009/08/11/give-your-eval-a-name-with-sourceurl/</a>
</p>
<p>
Adding sourceURL to scripts loaded by domManip would make debugging easier.
example: $('head').append('&lt;script src="test.js'&gt;&lt;/script&gt;');
</p>
<p>
Similar (but different) request <a href="http://bugs.jquery.com/ticket/8292">http://bugs.jquery.com/ticket/8292</a> was closed as wontfix earlier, so some comments on the reasons mentioned there:
</p>
<blockquote class="citation">
<p>
This is a functionality that:
</p>
<ul><li>only developers will need while debugging
</li></ul></blockquote>
<p>
Yes, but is very valuable for developers and it comes with virtually zero cost for users.
</p>
<blockquote class="citation">
<ul><li>is only useful for Chrome users
</li></ul></blockquote>
<p>
sourceURL is supported by Firefox and WebKit (Chrome, Safari) which makes together more than 60% of browser market share.
</p>
<blockquote class="citation">
<ul><li>is of limited use as the names would need to be randomly generated
</li></ul></blockquote>
<p>
In the example mentioned above the url could and should be taken from the src attribute of the script tag. This is the same url the script was loaded from.
</p>
<p>
Vsevolod Vlasov, webkit reviewer
</p><p>Issue reported for jQuery 1.7.1</p>

**Comment by dmethvin** [comment]
Since we are not using eval for inline scripts after landing gh-1449, this ticket no longer applies.
