### ISSUE TITLE
Move element cache to the element[expando] to avoid cleanup and reduce code.

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1734]
Originally reported by john.david.dalton@… at: http://bugs.jquery.com/ticket/11570
<p>
Soo way back in 2005 Dean Edwards proposed an event system that slapped the listeners on the actual element. This allowed cache to be destroyed once the element was GC'ed.
<a class="ext-link" href="http://dean.edwards.name/weblog/2005/10/add-event2/" rel="nofollow"><span class="icon">&nbsp;</span>http://dean.edwards.name/weblog/2005/10/add-event2/</a>
</p>
<p>
Over the weekend Peter Michaux proposed a similar solution:
<a class="ext-link" href="https://twitter.com/#!/petermichaux/status/189012245483757568" rel="nofollow"><span class="icon">&nbsp;</span>https://twitter.com/#!/petermichaux/status/189012245483757568</a>
<a class="ext-link" href="https://github.com/petermichaux/evento/blob/bd065a9b254a8d14b956ec438dc06c29622c3ef6/src/eventTarget.js#L165" rel="nofollow"><span class="icon">&nbsp;</span>https://github.com/petermichaux/evento/blob/bd065a9b254a8d14b956ec438dc06c29622c3ef6/src/eventTarget.js#L165</a>
</p>
<p>
I noticed that jQuery supports events on vanilla objects too so this change would align elements and objects.
</p>
<p>
The gist is that since jQuery is already adding an expando for a UID they can just use that property as the actual storage for the element.
</p>
<p>
Then all the code to recursively clean .removed'ed elements event/custom data could be removed as when the element is GC'ed that data is destroyed.
</p><p>Issue reported for jQuery git</p>

**Comment by timmywil** [comment]
@rwaldron Where did you land on this? Do you think we should do it?

**Comment by timmywil** [comment]
Related: https://github.com/jquery/jquery/issues/1728

PR: https://github.com/jquery/jquery/pull/1428
