### ISSUE TITLE
Add hook to cleanData to allow cleanup

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1736]
Originally reported by T.J. Crowder <tj@…> at: http://bugs.jquery.com/ticket/12213
<p>
Just as jQuery itself needs to know when an element is cleaned up, plug-in code (and perhaps application/page code) sometimes needs this notification as well. The TinyMCE jQuery plug-in, for instance, monkey-patches jQuery to hook into <tt>empty</tt>, <tt>remove</tt>, etc. so it can clean up after itself. I was just doing a plug-in where each instance needs to respond to window resize, and try as I might, I can't come up with a way to do it that won't leave handler(s) lying around if the programmer using it doesn't call my "destroy" method -- and let's face it, that's pretty easy to fail to do.
</p>
<p>
Recommend adding a hook or event that plug-ins (and application/page code) can use, with the clearly-documented caveat that almost <em>any</em> other option should be used first because of the potential performance implications.
</p>
<p>
The performance cost in the normal case (when no one has hooked the event) looks trivially small: Looking at <tt>cleanData</tt> in the current dev source, it looks like it comes down to one extra property test just after <a class="ext-link" href="https://github.com/jquery/jquery/blob/9ecdb2472be7661477564e46bce51432d4a5a84e/src/manipulation.js#L742" rel="nofollow"><span class="icon">&nbsp;</span>line 742 in manipulation.js</a> (that line number will rot), e.g.:
</p>
<pre class="wiki">742: if ( data &amp;&amp; data.events ) {
New:   if ( data.events.destroy) {
New:     jQuery(elem).trigger("destroy"); // Or a more efficient way, of course
New:   }
</pre><p>
...which is pretty cheap. A quick test on my 2.4GHz machine with Firefox on 10,000 elements, 5,000 of which had <tt>data.events</tt> and one of which had <tt>data.events.destroy</tt>, the average time to clear the container was 124-126ms both with and without the above. The cost when someone has actually hooked the event, of course, will be higher but largely irrelevant; if they've hooked it, presumably they have a reason.
</p>
<p>
This would, of course, be a somewhat unusual event. My off-the-cuff is that it wouldn't bubble, and couldn't be cancelled. But there are other unusual events. :-)
</p>
<p>
I'm happy to get into the details of this and submit a pull request (with tests and documentation) if this suggestion has legs.
</p><p>Issue reported for jQuery 1.8rc1</p>

**Comment by timmywil** [comment]
I think this issue has lost sufficient animus to warrant leaving it open.

**Comment by San4es** [comment]
The trick with event special API is not correct, because $.off() method calling lead to teardown calling.
