### ISSUE TITLE
Improve module handling in testswarm grunt task

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1740]
Originally reported by gibson042 at: http://bugs.jquery.com/ticket/13061
<p>
<a class="ext-link" href="https://github.com/jquery/jquery/commit/ca26d45395c8a790027633dec5a2ebc15ce9149a" rel="nofollow"><span class="icon">&nbsp;</span>https://github.com/jquery/jquery/commit/ca26d45395c8a790027633dec5a2ebc15ce9149a</a> was a stopgap, but we really should have a more robust way to ensure that all QUnit tests are always sent to TestSwarm.
</p><p>Issue reported for jQuery 1.8.3</p>

**Comment by dmethvin** [comment]
We duplicate the module list in `package.json` to support commitplease, perhaps we could grab it from there? Even though that removes a bit of duplication, it's still error prone.

**Comment by timmywil** [comment]
commitplease components may not perfectly align with all QUnit modules. That seems more error prone than what we have currently. Besides, what we have seems to be working alright. Unless we can think of a specific solution that is better than what we currently have, I'm inclined to close this.

**Comment by dmethvin** [comment]
Yeah, it's one of those things we don't do often enough to get right the first time, but we don't add modules all *that* often.
