### ISSUE TITLE
focus event ignores additional data when triggered

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1741]
Originally reported by mail@… at: http://bugs.jquery.com/ticket/13428

<p>
<a class="ext-link" href="http://fiddle.jshell.net/rvX5Y/4/" rel="nofollow"><span class="icon">&nbsp;</span>http://fiddle.jshell.net/rvX5Y/4/</a>
</p>

<pre class="wiki">$('input').on('focus', function(event, extra, data) {
    console.log(extra, data);
});
$('input').trigger('focus', ['extra', 'data']);
</pre><p>
Works in version 1.8.3.
</p>

<p>
Does not work in version 1.9.0 and 1.9.1.
</p>

<p>
Expected behavior: Console shows "extra data"
</p>

<p>
False Behavior: Console shows "undefined undefined"
</p>

<p>
Browser: Firefox 18,
OS: OS X 10.8.2
</p><p>Issue reported for jQuery 1.9.1</p><p>Blocked by: #13353</p>

**Comment by netil** [comment]
For 'focus', 'blur' and 'click' events, it fires native event in certain condition and when
calling native event, currently there is no way to pass through trigger's data to event handler.

Well, is not the best solution but I though to use special event hook to handle that.
Need to modify trigger to hold the data, and add handle method to invoke event handler function
(obviously it can be generalized to cover other events too).

What do you think guys?

```js
		focus: {
			// Fire native event if possible so blur/focus sequence is correct
			trigger: function() {
				if ( this !== safeActiveElement() && this.focus ) {

					// Check if triggered with data
					if( arguments.length > 1 ) {
						jQuery.event.special.focus.triggerData = jQuery.makeArray(arguments).splice(1);
					}

					this.focus();
					return false;
				}
			},
			delegateType: "focusin",
			handle: function( event ) {
				var param = [ event ],
					data = jQuery.event.special.focus.triggerData;

				if( data ) {
					param = param.concat( data );
				}

				event.handleObj.handler.apply( this, param );
				delete jQuery.event.special.focus.triggerData;
			}
		}
```

**Comment by gibson042** [comment]
That solution is at risk for introducing strange behavior flips between the "no arguments" and "arguments" cases, and is not reentrant safe. I don't see us using such an approach.

**Comment by dmethvin** [comment]
Agreed. In retrospect, allowing users to pass data has caused a lot of issues and this is one of them. Focus management is highly flaky in browsers already, it doesn't take much to cause problems.

**Comment by mzgol** [comment]
@timmywil Do we still want it for 3.0.0? There wasn't a lot of progress and we need to cut corners.

**Comment by mzgol** [comment]
Moving to 3.1.0.

**Comment by scholtzm** [comment]
I'm dealing with the same situation as described in [this comment](https://github.com/jquery/jquery/issues/1741#issuecomment-59859974).

> ...
> My problem with using triggerHandler is that I am trying to avoid running the code in my 'focus' handler when setting focus programatically (with 'trigger').
> ...

Is there a proper way to solve this?

**Comment by obskyr** [comment]
Welp, I just ran into this. Tried to handle a `blur` event only if triggered with a certain parameter, but I guess they just don't get passed. There's a use case, at least!

**Comment by PurvaA** [comment]
@mgol 

There is an another way to show additional data when focus event triggered

Please check my fiddle - [](https://fiddle.jshell.net/426vdp05/)

I am attaching screen shot for same

![focus_issue](https://cloud.githubusercontent.com/assets/15212429/20558824/0228c7cc-b198-11e6-9317-3a1253501656.jpg)

**Comment by mgol** [comment]
@PurvaA You're not triggering the focus event by yourself in your fiddle and you don't pass any data so this doesn't seem relevant to this issue.

**Comment by PurvaA** [comment]
@mgol 
Okay.

**Comment by pushkin-** [comment]
This is still [broken](https://jsfiddle.net/bjj56eua/6/).  Is this issue being tracked in one of the future milestones?

**Comment by dmethvin** [comment]
Yes, the ticket is still [open](https://github.com/jquery/jquery/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue) and the milestone is [4.0.0](https://github.com/jquery/jquery/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0.0), scroll to the top of this ticket and it should say that. If you'd like to submit a PR we can review.
