### ISSUE TITLE
Make unit tests work with selector-native.js

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1742]
Originally reported by dmethvin at: http://bugs.jquery.com/ticket/13537
<p>
It would be good to have the native selector engine run a clean subset of unit tests as a sanity check. It wouldn't hurt to wait on this until we get some user feedback though.
</p><p>Issue reported for jQuery 2.0b1</p>

**Comment by timmywil** [comment]
I can resolve this when I get to a bug with selector-native.

**Comment by mzgol** [comment]
Since we only have `master` now, I'm removing the `master-only` label, it's no longer useful.
