### ISSUE TITLE
Support ShadowRoot Nodes in Sizzle

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1748]
Originally reported by tj.vantoll at: http://bugs.jquery.com/ticket/14281
<p>
Currently ShadowRoot nodes cannot be used with Sizzle: <a class="ext-link" href="http://jsfiddle.net/tj_vantoll/5RBxm/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/tj_vantoll/5RBxm/</a>
</p>
<p>
ShadowRoots are DocumentFragments, but they have the additional methods so adding support for them might not be that bad: <a class="ext-link" href="http://www.w3.org/TR/shadow-dom/#elements-and-dom-objects" rel="nofollow"><span class="icon">&nbsp;</span>http://www.w3.org/TR/shadow-dom/#elements-and-dom-objects</a>
</p><p>Issue reported for jQuery 1.10.2</p>

**Comment by timmywil** [comment]
Fixed by 5c4be05d3b32456553dc944853b77fa96ae8b2b8
