### ISSUE TITLE
`.data()` doesn't handle the attributes with digits in the name well

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1751]
Originally reported by zerkms@… at: http://bugs.jquery.com/ticket/14376
<p>
version affected: any (1.10.1)
browser: any (chrome)
OS: any (windows 7 64bit)
</p>
<p>
For the following html 
</p>
<pre class="wiki">&lt;div data-foo-42="bar"&gt;&lt;/div&gt;
</pre><p>
and 
</p>
<pre class="wiki">var div = $('div');

console.log(div.data());
</pre><p>
javascript code I expect to see the object with one property.
</p>
<p>
Actual result: an empty object
</p>
<p>
jsfiddle: <a class="ext-link" href="http://jsfiddle.net/nWCKt/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/nWCKt/</a>
</p><p>Issue reported for jQuery 1.10.2</p>

**Comment by rwaldron** [comment]
@markelog what's up? I was following this, but there hasn't been any activity lately.

**Comment by timmywil** [comment]
I'll grab this for 3.0, if that's alright with Rick.

**Comment by rwaldron** [comment]
@timmywil sure, it shouldn't be too much work TBH. Mostly deleting code paths and associated tests. The tricky part is making sure that manipulation tests pass as well, since data tests exist there also
