### ISSUE TITLE
expose interface to .usedStyle and .rawComputedStyle once implemented

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1753]
Originally reported by mikesherov at: http://bugs.jquery.com/ticket/14407
<p>
<a class="ext-link" href="http://dev.w3.org/csswg/cssom/#the-getstyleutils-interface" rel="nofollow"><span class="icon">&nbsp;</span>http://dev.w3.org/csswg/cssom/#the-getstyleutils-interface</a> will help us fix a lot of the "auto/px/percent" issues we've cantfixed over the years
</p><p>Issue reported for jQuery 1.10.2</p>

**Comment by dmethvin** [comment]
Rather than leaving these open potentially forever, I've referenced them in the [roadmap[(https://github.com/jquery/jquery/wiki/Roadmap) and we can reopen if they ever become feasible.

**Comment by mzgol** [comment]
@dmethvin Please remember to remove a milestone & add a "wontfix" label when closing a bug as "won't fix" :)
