### ISSUE TITLE
Investigate implementing jQuery (specifically .init) as an Array subclass

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1754]
Originally reported by gibson042 at: http://bugs.jquery.com/ticket/14411
<p>
Inspired by an <a class="ext-link" href="https://github.com/madrobby/zepto/issues/820#issuecomment-25206786" rel="nofollow"><span class="icon">&nbsp;</span>interesting Zepto proposal</a> that seems to have legs for us: <a class="ext-link" href="http://jsperf.com/jquery-prototype-array/4" rel="nofollow"><span class="icon">&nbsp;</span>http://jsperf.com/jquery-prototype-array/4</a>
</p>
<p>
I suspect that it could reduce size as well, especially in 2.x.
</p><p>Issue reported for jQuery 1.10.2</p>

**Comment by timmywil** [comment]
Moving to [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap).
