### ISSUE TITLE
Add Vagrant Support or other lightweight server

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1755]
Originally reported by eric@… at: http://bugs.jquery.com/ticket/14488

<p>
The current unit test instructions advise developers to install some variant of *AMP, which is a heavy install to set up their development environment.  Adding a Vagrantfile and related configuration would allow the project to ship a portable server configuration along with the code, lowering the bar new developers have to clear in order to run and contribute to unit testing.
</p>

<p>
An example Vagrantfile is available in this pull request: <a class="ext-link" href="https://github.com/jquery/jquery/pull/1410" rel="nofollow"><span class="icon">&nbsp;</span>https://github.com/jquery/jquery/pull/1410</a>
</p><p>Issue reported for jQuery 1.10.2</p>

Related: https://github.com/jquery/jquery/issues/1999

**Comment by dmethvin** [comment]
@jaubourg how far did you get on the node server in New York. It would be another way of solving this problem and probably a better one than Vagrant.

**Comment by jaubourg** [comment]
I didn't work on this as much as I intended/wanted but all that's needed is some express routes and rewiring to those routes in the unit tests. The hard part is to actually determine what the unit tests are actually testing so as to simplify them and not have the node server code become a mess.

Should come soon(ish).

Once I have the unit tests rewired, I'll pass the ball to @gnarf (I guess) to see how to integrate the node web server in the testing infra.

**Comment by mgol** [comment]
I think this is handled by our new Karma setup. While it can be improved (AMD support, jQuery modules support, etc.) we don't need a meta-issue for that anymore.
