### ISSUE TITLE
Problem with the context when loading a script in an iframe

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1757]
Originally reported by jjgcastela@… at: http://bugs.jquery.com/ticket/14568
<p>
When you create a script node and append it to a head or a body of an iframe, the code is evaluated in the main window (where the jQuery was loaded) instead of in the window of the iframe.
I have been able to solve it adding the desired 'document' as the second argument of the 'globalEval' function this way:
</p>
<pre class="wiki">globalEval: function( code , doc) {
	var script,
	indirect = eval;
	code = jQuery.trim( code );
	if ( code ) {
		// If the code includes a valid, prologue position
		// strict mode pragma, execute code by injecting a
		// script tag into the document.
		if ((doc &amp;&amp; doc != document) || code.indexOf("use strict") === 1 ) {
			if(!doc) doc = document;
			script = doc.createElement("script");
			script.text = code;
			doc.head.appendChild( script ).parentNode.removeChild( script );
		} else {
			// Otherwise, avoid the DOM node creation, insertion
			// and removal by using an indirect global eval
			indirect( code );
		}
	}
}

</pre><p>
And then in the 'domManip' function, adding this parameter in the call to 'globalEval':
</p>
<pre class="wiki">jQuery.globalEval( node.textContent.replace( rcleanScript, "" ), doc );

</pre><p>Issue reported for jQuery 2.0.3</p>

**Comment by peyerluk** [comment]
Here's an updated version of the current `globalEval` with a second param `context` analogouous to [jQuery.parseHTML()](http://api.jquery.com/jquery.parsehtml/):

```js
globalEval: function( code, context ) {
  context = context || document;
  var script = context.createElement( "script" );

  script.text = code;
  context.head.appendChild( script ).parentNode.removeChild( script );
}
```
