### ISSUE TITLE
textbox not responding to keyup event in IE11

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1758]
Originally reported by sylvain courcoux at: http://bugs.jquery.com/ticket/14595
<p>
Hi,
</p>
<p>
I have a select element and a textbox element. The textbox is wired with a keyup event handler that checks if the input is numeric using a Regex and clears any non-numeric characters. The textbox is also wired to a focus event handler to check if the value of the select element is numeric and if it's not then blur the textbox. Basically, the functionality is to enter phone numbers.
</p>
<p>
The problem is that in IE11, non-numeric characters go through whereas is Chrome and Firefox the non-numeric characters are deleted as expected. Not sure if it's a jQuery or an IE11 problem.
</p>
<p>
The jsFiddle is here: <a class="ext-link" href="http://jsfiddle.net/R2Axp/2/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/R2Axp/2/</a> 
</p><p>Issue reported for jQuery 1.10.2</p>

**Comment by dmethvin** [comment]
I'm closing this ticket because there's no workaround we can do from within jQuery core that fixes the problem of the focus event being asynchronous in IE.  It has to be anticipated and handled at the application or widget level. See also [Trac 13026](http://bugs.jquery.com/ticket/13026).
