### ISSUE TITLE
removeAttr("selected") should not set property to false

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1759]
Originally reported by wchen@… at: http://bugs.jquery.com/ticket/14633
<p>
<a class="ext-link" href="http://jsfiddle.net/b85D4/5/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/b85D4/5/</a>
</p>
<p>
In Firefox the selected value is 1. In Chrome the selected value is 2.
</p>
<p>
removeAttr has special handing for boolean attributes to set the corresponding DOM property to false: <a class="ext-link" href="https://github.com/jquery/jquery/blob/master/src/attributes/attr.js#L86" rel="nofollow"><span class="icon">&nbsp;</span>https://github.com/jquery/jquery/blob/master/src/attributes/attr.js#L86</a>
</p>
<p>
Removing an attribute and setting the DOM property to false are very different. In this case, as specified (<a class="ext-link" href="http://www.whatwg.org/specs/web-apps/current-work/multipage/the-button-element.html#dom-option-selected" rel="nofollow"><span class="icon">&nbsp;</span>http://www.whatwg.org/specs/web-apps/current-work/multipage/the-button-element.html#dom-option-selected</a>), setting the property to false means setting the dirtiness to true. This changes how the option should react to "selected" attribute changes. In the test case, it means that adding the "selected" attribute at the end should not select the option.
</p>
<p>
Firefox respects the specified behaviour and does not select the second option.
</p><p>Issue reported for jQuery 2.0.3</p>

**Comment by AurelioDeRosa** [comment]
Will this change be landed in 3.0?

**Comment by bzbarsky** [comment]
@timmywil Is there an ETA on when this will actually appear in a jQuery release?  Right now doing this:

                $('#foo').removeAttr('selected');
                $('#foo').attr('selected', 'selected');

on an `<option id="foo">` will leave it unselected.  And people keep reporting this as a browser bug every so often...

**Comment by timmywil** [comment]
@bzbarsky That is a different issue. To set the dynamic selected state, use the property instead of the attribute. The selected attribute is used to set the default state for when the page loads.

```js
$("#foo").prop("selected", true);
```

**Comment by dmethvin** [comment]
I don't see a difference in behavior though: http://jsbin.com/lipunucamu/edit?html,js,output

**Comment by timmywil** [comment]
@dmethvin You can set the default state like that if the element hasn't been interacted with yet.

**Comment by bzbarsky** [comment]
@timmywil The issue with the code I quoted is that `removeAttr` sets both the default state _and_ the dynamic state.  But `attr` only sets the default state.  So the option ends up not selected. The fact that `removeAttr` sets the dynamic state is precisly what this issue is about, no?

**Comment by timmywil** [comment]
@bzbarsky It's expected behavior. Browsers may differ on when they consider the element to no longer be "fresh". I haven't checked them all. When the element is still fresh, setting the default state will set the dynamic state as well. But I can tell you that the proper way to set the dynamic state is with the property.

**Comment by bzbarsky** [comment]
You can tell _me_, but _I_ already know this.  From my point of view the proper way to set this state is without even involving jQuery at all.  The problem are the people who keep running into this inconsistency between `attr` and `removeAttr` and then filing bugs on browsers.

But I'm not even sure what we're arguing about here.  The fix for this issue makes the change I think should be made; I'm just asking when it's planned to ship.

**Comment by timmywil** [comment]
It will be shipped with the 3.0 release.

**Comment by AurelioDeRosa** [comment]
Should I open a ticket in the api repo to document this?

**Comment by mgol** [comment]
@AurelioDeRosa Yes, I think so. Most tickets with the `Behavior change` label need docs changes.

**Comment by dmethvin** [comment]
We should be able to take a lot of wording and generate issues from the upgrade guide which is currently a Google Doc.
