### ISSUE TITLE
.off() does not clean up empty cache entries

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1760]
Originally reported by psquared at: http://bugs.jquery.com/ticket/14674
<p>
Even if all event handlers are removed with <tt>.off()</tt>, an empty cache entry is left in <tt>data_priv</tt>.  Unfortunately, those empty cache entries remain if elements are removed using some method other than <tt>.remove()</tt>, causing a memory leak.
</p>
<p>
<strong>Test Environment</strong>: <br>
Chrome 31.0.1650.63, jQuery 2.0.3
</p>
<p>
<strong>Steps to Reproduce</strong>:<br>
</p>
<ol><li>Attach an event handler to an element (e.g. using <tt>.on()</tt>)
</li><li>Remove the event handler with <tt>.off()</tt>
</li><li>Remove the element with <tt>Node.removeChild()</tt>
</li></ol><p>
<strong>Expected Results</strong>:<br>
No memory leaks.
</p>
<p>
<strong>Actual Results</strong>:<br>
An orphaned cache entry remains in <tt>data_priv</tt>.
</p>
<p>
<strong>Example</strong>:<br>
<a class="ext-link" href="http://jsfiddle.net/Rx3v3/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/Rx3v3/</a>
</p>
<p>
<strong>Additional info</strong>:<br>
Modifying the last block of <tt>jQuery.event.remove()</tt> as below seems to alleviate the problem.
</p>
<div class="code"><pre><span class="c1">// Remove the expando if it's no longer used
</span><span class="k">if</span> <span class="p">(</span> <span class="nx">jQuery</span><span class="p">.</span><span class="nx">isEmptyObject</span><span class="p">(</span> <span class="nx">events</span> <span class="p">)</span> <span class="p">)</span> <span class="p">{</span>
    <span class="k">delete</span> <span class="nx">elemData</span><span class="p">.</span><span class="nx">handle</span><span class="p">;</span>
    <span class="nx">data_priv</span><span class="p">.</span><span class="nx">remove</span><span class="p">(</span> <span class="nx">elem</span><span class="p">,</span> <span class="s2">"events"</span> <span class="p">);</span>

    <span class="c1">// Clean up empty cache entries:
</span>    <span class="k">delete</span> <span class="nx">data_priv</span><span class="p">.</span><span class="nx">cache</span><span class="p">[</span><span class="nx">elem</span><span class="p">[</span><span class="nx">data_priv</span><span class="p">.</span><span class="nx">expando</span><span class="p">]];</span>
<span class="p">}</span>
</pre></div><p>Issue reported for jQuery 2.0.3</p>

**Comment by dmethvin** [comment]
Once the changes to `.data()` land, that would be a good time to circle back and see if we need to change anything here.

**Comment by timmywil** [comment]
Now that the data changes have landed, what needs to be done here?

**Comment by mzgol** [comment]
If you attach a couple of handlers to elements & then .off() them without removing elements then you still have a leak. This is way less serious now as removing elements makes the data go away but I'd say part of the issue is still applicable.

**Comment by dmethvin** [comment]
It looks like we take care of the no-more-events case now? https://github.com/jquery/jquery/blob/62d5579578109f1468a37e44f76af06f283a46ab/src/event.js#L220

**Comment by mzgol** [comment]
@dmethvin Indeed. It seems everything was done in https://github.com/jquery/jquery/commit/d702b7637a61e1973e08c27b8d8de2ed24a543e2. It would be good to have a test for that behavior, though, wouldn't it?

**Comment by timmywil** [comment]
@dmethvin @mzgol Not quite. compat also clears the expando.

**Comment by timmywil** [comment]
PR submitted.
