### ISSUE TITLE
Please provide a function for escaping special characters in selectors

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1761]
Originally reported by fejesjoco at: http://bugs.jquery.com/ticket/14692
<p>
I read this article: <a class="ext-link" href="http://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/" rel="nofollow"><span class="icon">&nbsp;</span>http://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/</a> .
</p>
<p>
It says plain and simple that a colon and a period must be escaped. And then the example code also escapes square brackets, so there's a problem already. In the future, you may add a new special character for a cool new selector feature, and that will be a breaking change.
</p>
<p>
I can see already how many bugs have been filed about special characters in selectors and then closed as being documented. I understand it completely. This is not a bug report, this is a feature request.
</p>
<p>
Please provide a function for escaping special characters in selectors. Benefits:
</p>
<ul><li>it's a very easy utility function to implement and useful in many cases
</li><li>all those people who never cared about such issues, will realize they should use this escaping mechanism
</li><li>all those people who used to run into problems with special characters before, used to file all those unnecessary bugs, now they will have an out-of-the-box solution instead
</li><li>if a spec changes or jQuery API changes, it won't be a breaking change because the updated escape function would handle the new cases too
</li><li>the quoted documentation suggests to copy-paste some code into my own JS, but jQuery is about helping eliminate those kinds of code pieces, it would be great to have it embedded
</li></ul><p>
I also realized there are much more characters which could need escaping if we're not just talking about the restricted ID's: <a class="ext-link" href="http://api.jquery.com/category/selectors/" rel="nofollow"><span class="icon">&nbsp;</span>http://api.jquery.com/category/selectors/</a> . This proposed escape function could handle that as well. I hope it's not a problem if it unnecessarily escapes characters in a selector in cases when it's not needed.
</p><p>Issue reported for jQuery 1.10.2</p>

**Comment by mzgol** [comment]
There hasn't been a lot of traction here recently and it's a new feature so I'm bumping the milestone to 3.1.0.

**Comment by dmethvin** [comment]
By our [general criteria](https://github.com/jquery/jquery/wiki/Adding-new-features) for adding new features it seems like this doesn't pass muster. We don't need it internally and it can easily be done as a plugin and the CSS.escape polyfill already exists. I'll close this but if someone has good reason to reopen we can always do that.

**Comment by mzgol** [comment]
@dmethvin Please apply the `wontfix` label if you're closing an issue as such.

**Comment by gibson042** [comment]
I reread the discussion, and am convinced by the arguments about escape functionality going hand-in-hand with the engine interpreting special characters, to maintain stability over time. This will be going in Sizzle, so might as well be documented/exposed in jQuery as well.

**Comment by timmywil** [comment]
I suggest `jQuery.escapeCSS`

**Comment by dmethvin** [comment]
It's just escaping the selector though, not a CSS rule or set of rules. Something like `escapeSelector` would be more descriptive although I admit it's pretty long. Just `escape` in the context of jQuery seems to ambiguous, although it's fine for Sizzle.

**Comment by timmywil** [comment]
It's escaping a CSS selector...

**Comment by timmywil** [comment]
Although I see your point. I was thinking `escapeCSS` to align more with `CSS.escape`.
