### ISSUE TITLE
.outerWidth( val ) doesn't handle selects properly

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1762]
Originally reported by scott.gonzalez at: http://bugs.jquery.com/ticket/14723
<p>
Broken: <a class="ext-link" href="http://jsbin.com/uyufEVAn/5/edit" rel="nofollow"><span class="icon">&nbsp;</span>http://jsbin.com/uyufEVAn/5/edit</a>
</p>
<p>
Explicitly setting <tt>box-sizing: content-box</tt> fixes it: <a class="ext-link" href="http://jsbin.com/uyufEVAn/7/edit" rel="nofollow"><span class="icon">&nbsp;</span>http://jsbin.com/uyufEVAn/7/edit</a>
</p>
<p>
See also <a href="http://bugs.jquery.com/ticket/4146">http://bugs.jquery.com/ticket/4146</a>
</p><p>Issue reported for jQuery 1.10.2</p>

**Comment by timmywil** [comment]
This is fixed in compat. http://jsbin.com/qoxobu/1/edit?html,js,output
