### ISSUE TITLE
Unable to trigger a checkbox click immediately after changing disabled to false

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1763]
Originally reported by danspamable@… at: http://bugs.jquery.com/ticket/14892
<p>
This bug occurs in Firefox but not Internet Explorer.
</p>
<p>
Code to reproduce:
</p>
<pre class="wiki">&lt;input id="chk" type="checkbox" disabled /&gt;
&lt;label for="chk"&gt;Checkbox&lt;/label&gt;
</pre><pre class="wiki">$('#chk').prop('disabled', false);
$('#chk').trigger('click');
</pre><p>
(or see <a class="ext-link" href="http://jsfiddle.net/kcLkZ/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/kcLkZ/</a>)
</p>
<p>
Expected results:
</p>
<p>
Checkbox is enabled and checked.
</p>
<p>
Actual results:
</p>
<p>
Checkbox is enabled but not checked.
</p><p>Issue reported for jQuery 1.11.0-rc1</p>

**Comment by dmethvin** [comment]
@miketaylr I can't believe I didn't ping you on this before. I can't find an existing ticket but this looks like a Firefox bug, see the [fiddles above](https://github.com/jquery/jquery/issues/1763#issuecomment-59861878).

**Comment by timmywil** [comment]
Is there anything we should do in Core or should we just push for a fix in Firefox? I don't think we should force clicking asynchronously internally.
