### ISSUE TITLE
IE 11 fullscreen inside iframe needs workaround

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1764]
Originally reported by christopher@… at: http://bugs.jquery.com/ticket/14903
<p>
IE 11 has a bug in its fullscreen support. If the element being made fullscreen is inside of an iframe, the values for offsetWidth/offsetHeight and the results of getBoundingClientRect are 100x too small.
</p>
<p>
Details of the issue are here:
</p>
<p>
<a class="ext-link" href="http://christophercurrie.github.io/technology/2014/03/20/internet-explorer-11-fullscreen-bug.html" rel="nofollow"><span class="icon">&nbsp;</span>http://christophercurrie.github.io/technology/2014/03/20/internet-explorer-11-fullscreen-bug.html</a>
</p>
<p>
It's also been noticed that click positions *may* be off by 100x in the opposite direction. I'll update the ticket if we find a repro for that issue as well.
</p><p>Issue reported for jQuery 2.1.0</p>

**Comment by Maluen** [comment]
Hello,

what about a workaround similar to https://github.com/videojs/video.js/issues/1333#issuecomment-51753454?

**Comment by dmethvin** [comment]
This problem seems obscure enough that we wouldn't attempt to fix it inside jQuery. Microsoft has been much more responsive recently, introducing fixes in slipstream updates. If you haven't reported this directly to Microsoft via https://connect.microsoft.com/ you should.

**Comment by AVGP** [comment]
I just had to fix this bug in our copy of jQuery UI and will try to

1. Create an isolated test case using latest jQuery UI
2. Create a minimal patch for it
3. Turn that into a pull request

Any objections?

**Comment by timmywil** [comment]
Sounds good to me!

**Comment by AVGP** [comment]
Right, the test case can be found here: http://codepen.io/AVGP/pen/jPBWje

**Comment by AVGP** [comment]
Argh, I just realised that part of the manifestation of the bug that I was fixing is actually jQuery UI using `offsetWidth` / `offsetHeight` directly, so I'll *also* open a pull request on jQuery UI regarding the droppable..

**Comment by AVGP** [comment]
Right, basically I was an idiot two weeks ago.
The test case from Christopher (christophercurrie.github.io/technology/2014/03/20/internet-explorer-11-fullscreen-bug.html) is the perfect test case.

Using that I have now written a small patch, but I wasn't able to construct a reasonable unit test for this :(

What do you think?

**Comment by mzgol** [comment]
I'll reopen this for now as IE11 is now frozen and we have a PR.
