### ISSUE TITLE
contents and children selectors can return elements out of order

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1766]
Originally reported by npben at: http://bugs.jquery.com/ticket/14960
<p>
This problem exists in version 1.11.0. 
</p>
<p>
I looked into source since the children and content selectors are just hardcoded not go into the logic that verifies uniqueness, it is probably just a situation that wasn't considered.
</p>
<p>
Examples are <a class="ext-link" href="http://jsfiddle.net/sfMr2/5/" rel="nofollow"><span class="icon">&nbsp;</span>here for children()</a> and <a class="ext-link" href="http://jsfiddle.net/sfMr2/6/" rel="nofollow"><span class="icon">&nbsp;</span>here for contents()</a>.
</p>
<p>
Removing these two tags from the guaranteedunique array fixes the issue, but I didn't make a patch because I'm not familiar with the source and there may be a better way to handle it.
</p>
<p>
Workaround: calling $().add(unorderedobject) causes the uniqueness check to sort the elements.
</p><p>Issue reported for jQuery 1.11.0</p>

**Comment by gibson042** [comment]
As discussed in the [meeting](http://irc.jquery.org/%23jquery-meeting/default_%23jquery-meeting_20150420.log.html#t09:17:23), sorting a guaranteed-unique collection doesn't seem to be of high enough value to justify degrading performance without a real-world use case.
