### ISSUE TITLE
$.show() can break responsive stylesheets

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1767]
Originally reported by sten_paa@… at: http://bugs.jquery.com/ticket/15037
<p>
When $.show() is called the <em>computed</em> display value is cemented as an inline style.  This can cause inconsistent behavior.
</p>
<p>
Fiddle: <a class="ext-link" href="http://jsfiddle.net/jinglesthula/ZttLJ/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/jinglesthula/ZttLJ/</a>
</p>
<p>
Note that in the fiddle I use JavaScript to change the 'layout'.  This simulates what would happen if the <tt>display: inline</tt> style were applied conditionally based on a responsive media query.  That is, a given block of code could produce different results based on something like the orientation of a device and when the device orientation (really, the viewport width) changed with respect to when the show/hide calls are made.
</p>
<p>
I understand that based on the fact that an inline style is applied at the point when .show() is called that the browser is rendering the styles properly.  The 'bug' I suppose comes in the fact that a dynamic computed value is assumed to be ok to translate to a more fixed inline style.
</p>
<p>
Resolution may involve finding a way to 'clean up' the inline style at the end of .show() and allow all styles not provided by jQuery to continue doing exactly what they were before show/hide were invoked.
</p><p>Issue reported for jQuery 1.11.0</p>

**Comment by jinglesthula** [comment]
On this page http://api.jquery.com/show/ a yellow Note callout was added indicating `show` can cause issues with responsive layout.  Now that 3.0 has been released and fixes the issue* I'm wondering if the note should be updated to indicate that <3.0 has the responsive issue, unless there are still other responsive layout issues with show even in 3.0.

\* at least in the fiddle above it fixed it when I switched it to 3.0 - I didn't do other testing regarding responsive layout + `show`/`hide`.
