### ISSUE TITLE
Fix release script

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1770]
Originally reported by dmethvin at: http://bugs.jquery.com/ticket/15078
<p>
This is a meta-ticket for the problems I encountered during the 1.11.1/2.1.1 release, some of these will be jquery-release issues and others with core's release.js script.
</p>
<ul><li><strike>The 1.x release tries to update jquery.js and jquery-latest.js on the CDN and <a class="ext-link" href="http://upload.wnd8.com/grab/fc4dcf.png" rel="nofollow"><span class="icon">&nbsp;</span>fails</a>, we if we're not going to update these anymore and freeze them at 1.11.1 we can just remove that from core's release.js.</strike> Fixed in c34ed46eee12c92cb050a53eb62daf9e1258caf9 and other branches
</li></ul><ul><li>I've now had <tt>npm publish --tag</tt> fail on me in two different releases. It worked for the 2.x but <a class="ext-link" href="http://upload.wnd8.com/grab/3d36ff.png" rel="nofollow"><span class="icon">&nbsp;</span>failed</a> on 1.x. As a result I ended up doing the subsequent steps manually there. (Note that <tt>npm publish --tag 1.x</tt> worked fine manually both times!) Since npm is independent from the later steps there should be an idea of "error but you can continue" in jquery-release to simplify error recovery and minimize the mess.
</li></ul><ul><li>The CDN zip files created by release.js were empty (0 bytes) for the 2.x release. I didn't get that far with 1.x because of the npm error.
</li></ul><ul><li>The build script never came back to a shell prompt even after I got the <a class="ext-link" href="https://github.com/jquery/jquery-release/blob/705bcf6b850f3c4537e9bff44dfabebf396459e7/release.js#L12" rel="nofollow"><span class="icon">&nbsp;</span>"complete" message</a>; perhaps related to why the zip files were empty.
</li></ul><ul><li>The version for <tt>package.json</tt> didn't seem to happen on master so I <a class="ext-link" href="https://github.com/jquery/jquery/commit/568f3dd84693629768b40e7b5cf4c60e0c57c4d4" rel="nofollow"><span class="icon">&nbsp;</span>did it manually</a>.
</li></ul><ul><li><strike>The version <a class="ext-link" href="https://github.com/jquery/jquery/commit/2f46ac8091d8b2612c56280e7a5626f9142bb1cf" rel="nofollow"><span class="icon">&nbsp;</span>wasn't updated</a> in <tt>bower.json</tt> either, it was in the old non-semver format as well. Does this need to be in the repo full-time, or can it just exist in the tagged release?</strike> See gh-1673 for this issue.
</li></ul><p>Issue reported for jQuery 1.11.1</p>

**Comment by timmywil** [comment]
This is now split up into separate issues that I'll tackle.
