### ISSUE TITLE
Chrome Sandboxed App: "Unload is not available in packaged apps"

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1772]
Originally reported by solgar at: http://bugs.jquery.com/ticket/15127
<p>
Hi,
I have discovered that in the latest version of jQuery (2.1.1), I receive an error when I attempt to load it inside a sandbox in a Chrome App.
All that needs to be done to replicate it is to include jquery 2.1.1 inside the sandbox in the chrome app. 
I have created an example app to replicate:
<a class="ext-link" href="https://github.com/solgarius/jquery-chrome-sandbox-unload-issue" rel="nofollow"><span class="icon">&nbsp;</span>https://github.com/solgarius/jquery-chrome-sandbox-unload-issue</a>
</p>
<p>
The error appears to be related to some code that designed to apply for IE11.
</p>
<p>
As far as I can tell, this issue only generates the error when the app is loaded and it does not appear to affect my application. All jQuery seems to still behave correctly inside (and outside) the sandbox.
</p>
<p>
I do not have this issue in chrome itself, only when it is inside the sandbox of a chrome app.
Furthermore, the issue is not in version 2.0.3 of jQuery, so it was likely added in the 2.1.* strain.
</p>
<p>
 
</p><p>Issue reported for jQuery 2.1.1</p>

**Comment by mzgol** [comment]
@gibson042 This was added by you in https://github.com/jquery/sizzle/commit/36973e9340b9e072a2077125cfc442dc6a42b926; could we test for `document.documentMode` instead of `addEventListener`?

It'd be good to make sure it's fixed in Edge so that we don't have to apply an even more hacky workaround soon...

**Comment by mzgol** [comment]
Not sure what we can do about `beforeunload` as this hook is really needed everywhere. @monteslu is the error harmless for you or does it cause any issues?

**Comment by monteslu** [comment]
Not actually breaking anything, just looks awful.

**Comment by gibson042** [comment]
> @gibson042 This was added by you in https://github.com/jquery/sizzle/commit/36973e9340b9e072a2077125cfc442dc6a42b926; could we test for `document.documentMode` instead of `addEventListener`?

We still need the `addEventListener` test for IE11+, but could use `document.documentMode` as an additional restriction (beyond `parent !== parent.top`) on when to register. I'm not thrilled about it, but it will work.

**Comment by mzgol** [comment]
This is just waiting for the Sizzle update now, right?

BTW, we need to get this issue into changelog, @timmywil, and it seems it's not mentioned anywhere as fixed in commit messages. Should we add such a commit when importing latests Sizzle?

**Comment by timmywil** [comment]
Yea, the "Update Sizzle" commit should include all of the pertinent Sizzle issues.

**Comment by timmywil** [comment]
This was fixed in the latest [Sizzle update](https://github.com/jquery/jquery/commit/3a0dd5a3d3a23e81dfb32af2871fab6be4619434#diff-544a2d53484ff0d7d64f8355fb52b254R509).

**Comment by mzgol** [comment]
This had to be reverted because the workaround is still needed in Edge. We'll be able to put it back when Edge fixes the bug. See #2390 for more details.

**Comment by gibson042** [comment]
I think this can be fixed in Sizzle by only registering the onunload handler on non-preferred windows. Fix to come shortly.

**Comment by mzgol** [comment]
Since we only have `master` now, I'm removing the `master-only` label, it's no longer useful.

**Comment by mzgol** [comment]
Since this is only waiting for a Sizzle update now, I'm moving it back from `3.0.1` to `3.0.0`.

**Comment by timmywil** [comment]
Fixed by 5c4be05d3b32456553dc944853b77fa96ae8b2b8
