### ISSUE TITLE
Mixing delegated and direct click handlers behaves differently on IE on Windows phone

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1777]
Originally reported by amasniko at: http://bugs.jquery.com/ticket/15171
<p>
I have got a fixed positioned overlay with a direct click handler attached to it and on the top of it an absolutely positioned element with a delegated click handler. On every browser I have tried clicking on the absolutely position element invokes its delegated handler except on Windows phone (OS version 8.0.10517.150) where the overlay handler is called.
</p>
<p>
Try clicking on "Click me" text on the following example:
</p>
<p>
<a class="ext-link" href="http://jsbin.com/makeyico/1" rel="nofollow"><span class="icon">&nbsp;</span>http://jsbin.com/makeyico/1</a>
</p><p>Issue reported for jQuery 1.11.0</p>

**Comment by dmethvin** [comment]
I'm closing this for lack of information, if anyone thinks this is jQuery-related or jQuery-fixable please post more info.
