### ISSUE TITLE
Basic Authentication does not work with JSONP

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1781]
Originally reported by driz at: http://bugs.jquery.com/ticket/15189

<p>
When sending Basic Authentication credentials with an jQuery AJAX request like so:
</p>

``` js
$.ajax({
    type: 'GET',
    url: ' http://domain.com',
    beforeSend : function(xhr) {
        var credentials = btoa(username + ':' + password);
        xhr.setRequestHeader("Authorization", "Basic " + credentials);
    },
    dataType: 'jsonp',
    success: function(data) {
        console.log(data);
    },
});
```

<p>
It doesn't work because the dataType is JSONP. Changing the dataType to JSON works.
</p>

<p>
However if you need to use JSONP for CORS, you have to do the following workaround:
</p>

``` js
$.ajax({
    type: 'GET',
    url: ' http://username:password@domain.com',
    dataType: 'jsonp',
    success: function(data) {
        console.log(data);
    }
});
```

<p>Issue reported for jQuery 1.11.1</p>

**Comment by Narendranath1054** [comment]
HI All,
I have tried JSONP with Basic Authentication in IE browser , it's not working at all but it works in Chrome & Firefox, please find the code below:

$.ajax({
	                type: 'GET',
	                url: 'http://user:password@XXXX:8071/App/servlet/rest/rdc/contexts',
	                crossDomain: true,
	                async: false,
	                jsonpCallback: 'jsonpCallback',
	                dataType: 'jsonp',
	                    success: function(data) {        
		                alert('Status: ok');
		             });
	                },
	            
	            });
Thanks i  Advance
please help us
