### ISSUE TITLE
Disable failing tests in Android 2.3, e.g. failures in appending checked radios

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1785]
Originally reported by m_gol at: http://bugs.jquery.com/ticket/15202
<p>
Currently almost all Android 2.3 failures concern appending checked radio buttons, see:
<a class="ext-link" href="http://swarm.jquery.org/result/1992038" rel="nofollow"><span class="icon">&nbsp;</span>http://swarm.jquery.org/result/1992038</a>
</p>
<p>
Fixing that should make the Android 2.3 test run almost green (there's only one other issue left)
</p><p>Issue reported for jQuery 2.1.1</p>

**Comment by mzgol** [comment]
It was decided we're only going to fix it on `compat` (if ever). Hence the `compat-only` label.

**Comment by mzgol** [comment]
Since this has been broken for a long time I think it might as well wait for 3.0.1.

**Comment by mzgol** [comment]
Since we're not going to release the Compat line after all, I'm closing this as "Won't fix".

**Comment by mzgol** [comment]
Those failures are still on `1.12-stable` & `2.2-stable` so I'm reopening it with a proper milestone.

We may decide it's a wontfix but then we should perhaps disable those tests in Android 2.3 to have a clean build.

**Comment by mgol** [comment]
@jquery/core I've added the "Needs review" label since we're releasing soon and need to decide on that. I think this is wontfix at this point but we should at least blacklist those tests in Android 2.3 then to make the build pass. Thoughts?

**Comment by markelog** [comment]
You know where i stand on this

**Comment by mgol** [comment]
Tests have been blacklisted in 1a9c9b079177a1d6420efb876e8e66bf1fb4cbe2 & 27325311db4807f52d66e592d832c55ab0a203df for `2.2-stable` & in 704de8180f220afa1efd7bd65e9aeb9007a4f238 for `1.12-stable`. Closing the issue.
