### ISSUE TITLE
No way to globally clean up data

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1787]
Originally reported by m_gol at: http://bugs.jquery.com/ticket/15205
<p>
When an element data is leaked (for example because it was detached/off-DOM and we lost reference to it) there is no way to get rid of its data. This matters in tests run in watch mode as leaks can accumulate &amp; crash the browser.
</p>
<p>
The only alternative now seems to be initializing jQuery from scratch when we desire a clean environment. This is a little difficult now due to the fact that jQuery doesn't expose any initializing function so the lib would have be loaded once again (which, again, is not so easy/natural in many test frameworks).
</p>
<p>
Angular 1.3 betas were recently switched to use jQuery 2.1 instead of 1.x and this problem has arisen; see:
<a class="ext-link" href="https://github.com/angular/angular.js/issues/8532" rel="nofollow"><span class="icon">&nbsp;</span>https://github.com/angular/angular.js/issues/8532</a>
</p><p>Issue reported for jQuery 2.1.1</p>

**Comment by timmywil** [comment]
Since data is attached to nodes now, should we close this? I think the angular case would no longer be an issue.

**Comment by mzgol** [comment]
Yep, we can close it now.
