### ISSUE TITLE
$.getJSON treats request as JSONP when URL contains ?? (two question marks)

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1791]
Originally reported by Stijn at: http://bugs.jquery.com/ticket/15216
<p>
Similar to <a href="http://bugs.jquery.com/ticket/8417">http://bugs.jquery.com/ticket/8417</a> and its duplicates, but they're all about the data parameter, not the URL parameter.
</p>
<p>
Happens with current stable and with edge. Fiddle: <a class="ext-link" href="http://jsfiddle.net/r5zcw6wx/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/r5zcw6wx/</a>
</p>
<p>
Code:
</p>
<pre class="wiki">$.getJSON("http://date.jsontest.com/")
$.getJSON("http://date.jsontest.com/?foo")
$.getJSON("http://date.jsontest.com/??foo")
</pre><p>
Requests:
</p>
<pre class="wiki">GET http://date.jsontest.com/
GET http://date.jsontest.com/?foo
GET http://date.jsontest.com/jQuery2129957077760988448071399739372034175163514043816_1408610547781foo?_=1408610547782
</pre><p>
Of course we shouldn't be making requests with two question marks (naive string concat on our side), and this could be a dupe of the mentioned ticket, but I figured this was worth reporting anyway.
</p><p>Issue reported for jQuery 2.1.1</p>

**Comment by mzgol** [comment]
Moving to 3.0.1

**Comment by markelog** [comment]
@dmethvin, @jaubourg and me for close it as notabug, so if no one objects, will do that tomorrow

**Comment by mzgol** [comment]
@markelog No objection from me.

**Comment by markelog** [comment]
Closing as non-valid
