### ISSUE TITLE
Question mark is replaced by 'jQuery1520046861610282212496_1411972375451'.

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1799]
Originally reported by wjj871125 at: http://bugs.jquery.com/ticket/15249

<h2 id="Codeasfollows:">Code as follows:</h2>

``` js
var content = document.getElementById("content").value;
jQuery.ajax({
    type:'post',
    url:'add.php',
    data:"content=" + content, // value is '?'
    dataType : "json",
    success:function(response){
        alert('success:'+response.msg);
    },
    error: function(msg){
        alert(msg);
    }
});
```

<h2 id="Codeends.">Code ends.</h2>

<p>
When the parameter 'content' value is '?' or '??', its content is replaced by similar content as 'jQuery1520046861610282212496_1411972375451'.
</p>

<h2 id="jQuerycode">jQuery code</h2>

``` js
data = data.replace( jsre, replace );
```

<h2 id="jQuerycodeend.">jQuery code end.</h2>

<p>
These codes maybe need to optimize.
</p><p>Issue reported for jQuery 1.5.2</p>

**Comment by timmywil** [comment]
After further review, I don't think we want to break the ability to promote `json` requests to `jsonp`. We may just want to document that you can set contentType to avoid this?

**Comment by timmywil** [comment]
Opened docs issue: https://github.com/jquery/api.jquery.com/issues/878.

**Comment by mgol** [comment]
This will be fixed in jQuery 4 by the removal of the JSON-to-JSONP auto-promotion logic; the replacement will only be triggered if `dataType` is set to `"jsonp"`. See issue #3376 & PR #4754.
