### ISSUE TITLE
.css method return wrong value for negative percent margin

### ISSUE THREAD

**Issue by deneb7000** [jquery/jquery#1815]
.css method return wrong value for margin on an hidden element if it is specified as negative percent.
the value of width is returned instead.

examples:
$("&lt;div/&gt;").css({'margin': '-2%'}).css("marginTop"); // return "auto" - WRONG: expected "-2%"

$("&lt;div/&gt;").css({'margin': '-2%', 'width': '60%'}).css("marginTop"); // return "60%" - WRONG: expected "-2%"

$("&lt;div/&gt;").css({'margin': '2%'}).css("marginTop"); // return "2%" - CORRECT

$("&lt;div/&gt;").css({'margin': '-2px'}).css("marginTop"); // return "-2px" - CORRECT

**Comment by mzgol** [comment]
The patch restoring the `marginRight` hack on Android 4.0-4.3 has landed on `master` so now this problem will reappear in these browsers there.

So we'll most likely need to mark it as wontfix and add a note to the docs.

**Comment by mzgol** [comment]
#1842 has landed and it includes a support test for the `pixelMarginRight` workaround so it seems all we can do here is to make it clear in the docs that the Android Browser suffers from this issue?

**Comment by timmywil** [comment]
@mzgol agreed.

**Comment by timmywil** [comment]
Moved to docs issue: https://github.com/jquery/api.jquery.com/issues/865
