### ISSUE TITLE
IE8 iframe memory leak with non-detached click event

### ISSUE THREAD

**Issue by SergioMorchon** [jquery/jquery#1840]
If you load jQuery 1.X (i'm testing with edge) inside an iframe, alone, and reload the content (eg. by submiting a dummy form), you could see a memory leak under IE8 (not IE10+ with IE8 compat, no. A really production IE8 legacy enterprise browser).

The bad lines are:

``` javascript
if ( div.attachEvent ) {
    div.attachEvent( "onclick", function() {
        support.noCloneEvent = false;
    });

    div.cloneNode( true ).click();
}
```

By changing them for something like the following...:

``` javascript
if (div.attachEvent) {
    function cloneTest() {
        support.noCloneEvent = false;
    }
    div.attachEvent("onclick", cloneTest);
    var div2 = div.cloneNode(true);
    div2.click();
    div.detachEvent("onclick", cloneTest);
    div2.detachEvent("onclick", cloneTest);
}
```

... the memory leak dissapears, and the test continues working as espected.

(- sorry about my non-linted code -)

One of the known solutions for the well-known issues with iframes, memory leaks, events and IE8 is to detach all the events before the garbage collection.

**Comment by svenmeier** [comment]
Just as a note: this regression was caused by #1518
