### ISSUE TITLE
Hidden filter incorrectly includes visible elements

### ISSUE THREAD

**Issue by FesterCluck** [jquery/jquery#1855]
https://github.com/jquery/jquery/blob/master/src/css/hiddenVisibleSelectors.js

All versions seem to get this wrong for inline elements. For example, anchors with images inside them on Chrome return an offsetWidth and offsetHeight of 0. This is likely because offsetWidth/Height are based on a Working Draft Spec: http://dev.w3.org/csswg/cssom-view/#dom-htmlelement-offsetwidth which does not yet define a CSS Layout Box well ( http://dev.w3.org/csswg/cssom-view/#css-layout-box ) and when it does, only includes elements whose 'display' property that is 'table-column' or 'table-column-group'.

Since current implementations of offsetWidth/Height on most browsers are much more performant than getClientRects/getBoundingClientRect ( http://jsperf.com/offsetwidth-vs-getclientrects-vs-getboundingclientrect ), it makes since to use them, but only when they return non-falsy values.

A performant version of this function should be run:

    function (elem) {
    
        //Expand list of displays as spec is finished, is window.getComputedStyle needed here?
        var hasLayoutBox = ['table-column', 'table-column-group'].indexOf(elem.style.display) > -1; 
    
        return (
            !elem.offsetWidth &&
                (hasLayoutBox || !elem.getBoundingClientRect().width)
        ) || ( 
            !elem.offsetHeight && 
                (hasLayoutBox || !elem.getBoundingClientRect().height)
        );
    }

**Comment by FesterCluck** [comment]
Since #2227 has been closed (being accepted into 3.0.0) it seems appropriate to close this issue as well. I'll leave it open for another week for comment or objection (to be closed Sept 27, 2015).

FWIW: I'm glad this issue received the attention it deserved. As far as I can tell most of the other use cases were the same as mine, regarding setting tab order to only visible elements. The new method (offsetWidth/offsetHeight/getClientRects) seems to work extremely well in modern browsers. Thank you for your hard work.

**Comment by timmywil** [comment]
Closing per OP's evaluation. See #2227 for more info.
