### ISSUE TITLE
Make event triggering a separate module

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#1864]
If a custom build doesn't need manually triggered events, it could save a bunch of bytes by removing `jQuery.event.trigger()`, `jQuery.event.simulate()`, `jQuery.fn.trigger()`, and `jQuery.fn.triggerHandler()`. This would mostly be useful for the 2.x (now 3.x-master) branch because the 1.x (3.x-compat) branch relies pretty heavily on manually triggered events to fix up IE8. On master, manual triggering is used to create bubbling focusin/out events and fire ajax events, but there are other approaches devs can use for both situations.

**Comment by mzgol** [comment]
@timmywil @dmethvin Moving to 3.1.0 as it won't be a breaking change and so doesn't have to go in 3.0.0. Revert the change if you disagree.

**Comment by dmethvin** [comment]
@timmywil I can grab this if you want.

**Comment by timmywil** [comment]
@dmethvin Feel free!
