### ISSUE TITLE
CustomEvent `detail` property not copied to Event object

### ISSUE THREAD

**Issue by remko** [jquery/jquery#1867]
According to [the documentation](http://api.jquery.com/category/events/event-object/) (or at least how I interpret it), the `detail` property is copied to the event object when it is present (i.e. when the event is a `CustomEvent`). However, this does not seem to be the case (I tried accessing it, and i don't see any reference to `detail` in the code either, it's not listed in any `props` list in `event.js`).

My workaround is to go through `originalEvent.detail`, but it would be nice if jQuery copied this property.

**Comment by amakhrov** [comment]
Any chance to get this fix in the stable branches?

**Comment by dmethvin** [comment]
Is there a problem using `event.originalEvent.detail` instead?

**Comment by amakhrov** [comment]
Not really - just have to make sure we always use jquery for attaching events.
