### ISSUE TITLE
.Animate does not on ipad after sleep/resume

### ISSUE THREAD

**Issue by shchukax** [jquery/jquery#1877]
This issue is present on ipad with ios 8.1 in an app that uses jquery 2.1.1 (latest).

`.animate` is used for position transition and `fadeIn`/`fadeOut` is used to show/hide content. When the app is run from a homescreen icon, animation runs as expected after the app start.  If the ipad is put to sleep using the power button and then woken up from sleep, animation doesn't run any more, although no errors are reported.

For example, in this code, `.animate` does nothing after sleep/resume on ipad.

    $in = $('#newdiv');
    $in.css({position: 'absolute', left: "1024px", top: "0px"});
    $in.removeClass('hidden');
    $in.animate({left: tx, top: ty}, 400);

The same happens to the fadeIn/fadeOut animation.

Here's a [very simple jsfiddle](http://jsfiddle.net/qs4x6eyd/) demonstrating the problem.

Again, this only seems to affect the app when running from home screen icon - when run inside safari, everything works as expected.

**Comment by Jayflux** [comment]
I Just tested this out (@shchukax's test case) on my iPad Mini, iOS 8.3 and it works fine here.
Looks like something has fixed it at some point.

**Comment by dmethvin** [comment]
Closing as it seems like this was fixed by Safari and probably never was a fixable jQuery issue.
