### ISSUE TITLE
data-URI scripts insertion

### ISSUE THREAD

**Issue by rhyzx** [jquery/jquery#1887]
``` js
var s = document.createElement('script')
s.src = 'data:,console.log(1)'

document.body.appendChild(s)
// output 1
```

but if insert this script by jQuery: `$('body').append(s)`, it will be get an error.

---

this is due to jQuery execute script by ajax of `script[src]`, 
and jQuery will append extra query params `_=xxxx` to prevent script cache by default.
https://github.com/jquery/jquery/blob/2.1.1/src/manipulation/_evalUrl.js#L9

fix this is simple, just set `cache=true`… may i pull a PR for this?

---

by the way, anyone knows why jQuery set `async=false` for inserted scripts?
this is inconsistent with browser's default behavior

**Comment by Manoj-Roy** [comment]
var s = document.createElement('script');
var minS = s.src = 'data:console.log(1)';

document.body.appendChild(s);
// output 1


GET data:console.log(1) net::ERR_INVALID_URL

**Comment by Manoj-Roy** [comment]
or u can try it

var s = document.createElement('script');
 s.src = 'https://code.jquery.com/jquery-2.1.4.min.js';

document.body.appendChild(s);
