### ISSUE TITLE
Remove context and selector properties

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#1908]
Originally reported for jQuery 2.0.3 by anonymous at http://bugs.jquery.com/ticket/14341

> I was lurking a few months ago and just remembered now, but it looks like both these properties are still present.

> Selector has been deprecated since 1.7, and context since 2.0. Can they be removed now? I'd attempt myself however I am not able to sign the CLA due to weird moonlighting policies of my employer.

> http://bugs.jquery.com/ticket/9469 http://bugs.jquery.com/ticket/13801

Both properties have been deprecated since 1.10/2.0, the former courtesy http://bugs.jquery.com/ticket/13801
* http://api.jquery.com/context/
* http://api.jquery.com/selector/

3.0 strikes me as the right time. Pre-1.10 #1249 probably can't be applied _directly_ anymore, but I'll bet it's pretty close.

**Comment by dmethvin** [comment]
Ref https://github.com/jquery/jquery-migrate/issues/79

**Comment by thdoan** [comment]
How can we get the original selector string that was used to invoke a plugin from within the plugin? Example:

```
(function($) {
  $.fn.plugin = function() {
    // This no longer works in jQuery 3.x
    console.log(this.selector);
    return this;
  };
}(jQuery));
```

**Comment by dmethvin** [comment]
A closed ticket isn't the right place to look for support, but in general there is no string that represents the collection a plugin receives, e.g. `$(this).plugin()` or `$("p").children("span").plugin()`.
