### ISSUE TITLE
Cannot get mouse position in dragover event

### ISSUE THREAD

**Issue by ocerman** [jquery/jquery#1925]
I cannot get mouse position via e.pageX and e.pageY in dragover event in recent version of jQuery.
However, same code is working in jQuery 1.6.4

Example code: http://jsfiddle.net/blacksvk/qnbc80xy/1/

**Comment by gtristan** [comment]
The above patch fixes dragstart,drag,dragend,dragover,dragenter and dragleave

However it does not fix the drop event.

I admit to not being a regexpert, but this adjustment fixes it for me:

    rmouseEvent = /^(?:mouse|pointer|contextmenu|drag)|drop|click/,

**Comment by dmethvin** [comment]
@gtristan thanks for the note, new issue has been created
