### ISSUE TITLE
jQuery 1.11.1 - "Attribute Starts With Selector" - "unrecognized expression"

### ISSUE THREAD

**Issue by spullumhc** [jquery/jquery#1935]
I was building a web form where if a user clicked on a text box or check box it would check a box marking the record selected. I was using the "Attribute Starts With Selector" '^'.

In Chrome it worked.
In Safari 8.0.2 and Firefox Developer Edition 36.0a2 the error log contained this:

Firefox:
Error: Syntax error, unrecognized expression: [id^='f_attending_radio' jquery-1.11.0.js:1471

Safari:
[Error] Error: Syntax error, unrecognized expression: [id^='f_attending_radio'
    error (jquery-1.11.0.js, line 1471)
    tokenize (jquery-1.11.0.js, line 2085)
    select (jquery-1.11.0.js, line 2473)
    Sizzle (jquery-1.11.0.js, line 880)
    find (jquery-1.11.0.js, line 2684)
    init (jquery-1.11.0.js, line 2801)
    jQuery (jquery-1.11.0.js, line 75)
    (anonymous function) (show, line 22)
    dispatch (jquery-1.11.0.js, line 4624)
    handle (jquery-1.11.0.js, line 4292)

I tested in jQuery 1.11.1 and 1.11.0
http://fiddle.jshell.net/spullumuci/aa8fv33c/

OS/browser environment:
OS X 10.10
Safari 8.0.2 and older (original user report came from older Safari in OS X 10.8)
Firefox Developer Edition 36.0a2 (2014-12-16)
Chrome 39.0.2171.95 (64-bit)

**Comment by ashishjp** [comment]
Thank You...
