### ISSUE TITLE
.html(value) doesn't work in Firefox when working with the same element

### ISSUE THREAD

**Issue by devantoine** [jquery/jquery#1956]
Hi,

I think I've found a weird bug using latest Firefox. The simple test case is here: http://jsfiddle.net/ku26kaq3/

If I set some random html it works. If I try to switch the script tag to a div one, it's the same behavior.

It's only failing under Firefox (tested under IE, Chrome, Safari).

Weirdest thing: cloning the element (var $tpl = $('#tableProductTemplate').clone().html();) is doing the exact same behavior.

The only workaround I've found is directly using innerHTML.

**Comment by devantoine** [comment]
@dmethvin Yes, it's working using .text() insteand of .html(), and it makes more sense.
But I think we still have an issue here because usng .html() doesn't have the same behavior between browsers.

@gibson042 I don't remember what I exactly did, I'll try to digg into the issue.

**Comment by dmethvin** [comment]
@devantoine Saying "set the inside of this script tag to this HTML" seems wrong doesn't it? There is usually script or some other non-HTML content inside a script tag, and even when it is HTML-like you wouldn't want it to be parsed before it's placed into the tag. I don't think we need to ensure that works consistently across browsers, and we can document that `.text()` should be used.

**Comment by devantoine** [comment]
@dmethvin You're right. Seems good to me.

**Comment by dmethvin** [comment]
Moved to https://github.com/jquery/api.jquery.com/issues/618
