### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#1965]
Evaluate and prototype implementation of code coverage tool. Maybe not even on Core at first, Sizzle?

/cc @timmywil, @mzgol, @gibson042, @jaubourg, @dmethvin

**Comment by listepo** [comment]
+1

**Comment by stevepeak** [comment]
> Full disclosure I'm the founder of Codecov

We would love to see jQuery use [Codecov](https://codecov.io) as its coverage provider. I would love to share about the many reasons why I believe Codecov are great fit and industry leading in code coverage. Anything I can do to help this transition I would make myself very available. Thank you!

**Comment by gnarf** [comment]
> Anything I can do to help this transition I would make myself very available.

Help implement it in a PR and I'm sure we can work together on it!  A couple of questions:

* What does it take for us to use it? (we don't use travis)
* Can we use it in the jenkins / testswarm / qunit setup that we have?
* Do you have some example reports to look at, could you run it against jQuery yourself and link us to a report?

I'm sure others will have some more questions :)

**Comment by stevepeak** [comment]
> What does it take for us to use it? (we don't use travis)

Any CI method works. We have two primary uploading methods for javascript: the [native method](https://github.com/cainus/codecov.io) and the [global method](https://github.com/codecov/codecov-bash). I'll look into creating a pull request, I'll mention you when I create it. Thank you @gnarf

> Can we use it in the jenkins / testswarm / qunit setup that we have?

Jenkins: yes. Qunit: yes. Testswarm: should (I have not used this before). We do merge coverage reports automatically and keep record of each one. [See here for example](https://codecov.io/gh/pyca/cryptography) (Click on the **Unified** dropdown).

> Do you have some example reports to look at, could you run it against jQuery yourself and link us to a report?

I can reference our customer repos, but I have not yet ran coverage against jQuery yet. I will try to attempt this during my pull request.

> I'm sure others will have some more questions :)

I'm very happy to help out!

**Comment by gnarf** [comment]
> I'm very happy to help out!

Feel free to ping me (gnarf) in freenode IRC #jquery-dev with any questions/help you'd need from me here.

**Comment by timmywil** [comment]
Closing in favor of tracking in the [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap).
