### ISSUE TITLE
Simplify XHR detection

### ISSUE THREAD

**Issue by FarSeeing** [jquery/jquery#1967]
This is the `XMLHttpRequest` object detection code:

https://github.com/jquery/jquery/blob/master/src/ajax/xhr.js

``` javascript
jQuery.ajaxSettings.xhr = function() {
    try {
        return new XMLHttpRequest();
    } catch ( e ) {}
};
...
xhrSupported = jQuery.ajaxSettings.xhr();
...
support.cors = !!xhrSupported && ( "withCredentials" in xhrSupported );
support.ajax = xhrSupported = !!xhrSupported;
```

`support.ajax` is used nowhere in the code and is not documented, `XMLHttpRequest` object is supported in all modern browsers (including Android 2.3, iOS 6.1, Opera 12 and IE 9 — [caniuse.com](http://caniuse.com/#feat=cors)).
Why not remove `xhrSupported` variable together with `support.ajax` and `try-catch` block?

**Comment by timmywil** [comment]
We'll investigate further for 3.1.0.

**Comment by mgol** [comment]
`jQuery.support.ajax` & `jQuery.support.cors` have been removed in #4347 and will not be defined in jQuery 4.0. The remaining part is the try-catch around `jQuery.ajaxSettings.xhr` which I'm removing in #4467.
