### ISSUE TITLE
$('html /deep/ paper-toast') doesn't work in firefox or ie

### ISSUE THREAD

**Issue by lext-7** [jquery/jquery#1979]
$('html /deep/ paper-toast') doesn't work in firefox or ie, but document.querySelector('html /deep/ paper-toast') works. And $('html /deep/ paper-toast') works in  chrome;
In firefox or ie, a error : 'Error: Syntax error, unrecognized expression: html /deep/ paper-toast' is caught

**Comment by mzgol** [comment]
The spec has changed `/deep/` to `>>>` (see http://dev.w3.org/csswg/css-scoping-1/#deep-combinator). That only makes me more sure in our decision to not jump the ship and implement support for these selectors until it's available in more than one browser.

We wouldn't like to need to support obsolete versions of the API and once we made something like that available, we'd need to support it.
