### ISSUE TITLE
jQuery 2.x $.ajax Does Not Fire Success On Same Origin Non CORS Requests In Internet Explorer 9 - 10

### ISSUE THREAD

**Issue by phistuck** [jquery/jquery#1992]
Internet Explorer 9 - 10 have issues with the "load" event on XMLHttpRequest, on which jQuery 2.x relies in order to call the success callback.
See -
https://connect.microsoft.com/IE/feedback/details/1025304/regression-xmlhttprequest-onload-never-fires-breaks-ajax-in-jquery-2-x

The workaround is to revert back to listening for onreadystatechange.

**Comment by markelog** [comment]
Judging by the conversation in the ticket, this issue is hard to reproduce, i also can't see the problem.

Could you please post the link with the jQuery-code that shows the bug?

**Comment by dmethvin** [comment]
We'd definitely want a repro. If the solution for some rare case requires going back to polling, then the easiest solution would be to use jQuery Compat. That is the case for local file access via XHR in IE10 for example.

**Comment by phistuck** [comment]
Looks like it was an issue with websites that use some protection mechanism that overrides XMLHttpRequest in Internet Explorer that identifies itself as Internet Explorer (11 and later do not). Sorry for the mess!
