### ISSUE TITLE
The data-URI append(<script>) test is flakey

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1993]
The test sometimes fails on iOS/Opera; I'll attach a link next time I see it.

**Comment by mzgol** [comment]
One example: http://swarm.jquery.org/result/2267177

**Comment by mzgol** [comment]
Safari 7 seems to fail it a lot: http://swarm.jquery.org/project/jquery

**Comment by markelog** [comment]
Can't seems to repo it, could you try? If you will have the same fate, i propose to fly blind and increase the timeout.

**Comment by mzgol** [comment]
I can't reproduce it locally, it happens from time to time on TestSwarm so it seems to require an enough large sample (but enough for us to hit it since we test so much).

We can try increasing the timeout and see what happens. I don't like when we cannot control the test fully. :(

**Comment by markelog** [comment]
> I don't like when we cannot control the test fully. :(

Yeah

/cc @dmethvin

**Comment by markelog** [comment]
Commited only in the `compat` at the moment, not gonna close this until fix will be verified.

**Comment by markelog** [comment]
It seems timeout increase did help, committing to `master`
