### ISSUE TITLE
$.parseHTML( "" ) should not return null

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#1997]
This behaviour has been there since the version version (e2497c682f26b7916d76cb2896c6fe621b376d82) but I'd like to propose changing that.

The method is [documented](https://api.jquery.com/jQuery.parseHTML/) as taking a string (of HTML) and returning an Array. Having it return null for non-string input is fair, but for empty strings it should probably return an empty array (or maybe array with empty text node).

**Comment by arthurvr** [comment]
testcase: http://jsfiddle.net/vga4eqw9/

**Comment by timmywil** [comment]
I like the empty array idea. It would be the same behavior as parsing natively with `createHTMLDocument`, and it shouldn't affect `jQuery("")`.

**Comment by arthurvr** [comment]
Empty textnode would be inconsistent with browser' behaviour, so an empty array seems like a nice solution.
