### ISSUE TITLE
Resize event is not fired in certain situations in Internet Explorer 10

### ISSUE THREAD

**Issue by dpedu** [jquery/jquery#2001]
To reproduce:

- Use Internet Explorer 10 (NOT 11 or newer emulating 10, multiple IE hacks, etc. I used windows 7 in vmware, unsure if OS matters)
- Open javascript console (Not necessary for this bug to occur, but the demo uses console.log to show what's wrong)
- Clear cache and view either test page
- While the large image on the page is loading, resize the browser window.
- No text will be logged from the resize listener. However, the "ready 1" and "ready 2" lines will be printed, these surround the call to add the resize listener, to confirm that adding the listener has executed
- After the page and all assets are fully loaded, future resize events fire fine, but ones that were missed are simply lost.

After the image finishes loading, everything works as expected. The plain-html resize is not triggered under the same conditions either, so I think this is a case of jQuery not shimming in a spot where it needs to.

Demo links:

jQuery 1.11.2: http://198.27.127.96/ie10.html
jQuery 2.1.3: http://198.27.127.96/ie10_2.html

Demo code:

```html
<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>IE10 pls</title>
    <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
          console.log('<div>ready 1: ' + $(window).width() + '</div>');
          $(window).resize(function(){
            console.log('<div>resize: ' + $(window).width() + '</div>');
          });
          console.log('<div>ready 2: ' + $(window).width() + '</div>');
          setTimeout(function(){
              console.log('<div>timeout: ' + $(window).width() + '</div>');
          }, 100)
        });
    </script>
</head>
<body onresize="console.log('natural html resize');">
    <img src="http://giant.gfycat.com/EmbellishedAcceptableAfricanporcupine.gif?x=1" alt="" />
</body>
</html>
```

**Comment by dmethvin** [comment]
> The plain-html resize is not triggered under the same conditions either

If that is the case, how should jQuery detect that we should simulate the `resize` event? This is a pretty rare case. Perhaps a workaround (if an app desperately needs it) would be to use a timer to check the size of the window and manually trigger the event?

**Comment by dmethvin** [comment]
Given the reported case, I don't think this is something we should work around in core.
