### ISSUE TITLE
Simplification of manipulation wrappers

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2002]
Talking about [those](https://github.com/jquery/jquery/blob/8e738f0aa89ca333dac61a1d1d0c4964762464c1/src/manipulation.js#L49-56).

We can remove most of the wrappers for `col` element (effectively removing it entirely) from `master` and `compat` and remove `area` and `legend` wrappers, since they was needed for IE6-7 only.

PR tomorrow.

**Comment by dmethvin** [comment]
Would definitely like to see this in 3.0 if it can be done.
