### ISSUE TITLE
Improve tag name related regexes

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2005]
<a href="https://github.com/jquery/jquery/pull/1988">See</a> discussion in related pull, specifically @gibson042 <a href="https://github.com/jquery/jquery/pull/1988#issuecomment-69500885">comment</a>.

**Comment by markelog** [comment]
@LeonardoBraga interested in providing fix for it?

**Comment by LeonardoBraga** [comment]
@marklog - Yes, definitely. Will work on the PR ASAP.

**Comment by mzgol** [comment]
@LeonardoBraga Still interested?

**Comment by LeonardoBraga** [comment]
@mzgol Sure. I'll work on it over the weekend and send the PR. Thanks.

**Comment by dmethvin** [comment]
@LeonardoBraga just pinging to see if you're going to send a PR. We'd love to have your contribution!

**Comment by LeonardoBraga** [comment]
@dmethvin I'm sorry for the delay on sending the PR. Should I also apply the same changes to other branches and send additional PRs?

**Comment by gibson042** [comment]
No need; this is easy to cherry pick.
