### ISSUE TITLE
jquery load and ajax does not follow redirect to crossdomain in chrome

### ISSUE THREAD

**Issue by Thaina** [jquery/jquery#2007]
I have my site hosted in one domain and I write IIS to return 301 redirect to static content in another domain

something like www.xxx.com/index.txt
will 301 redirect to yyy.s3.com/index.txt

Then I use jquery code like this
body.load("www.xxx.com/index.txt")

It could redirect to yyy.s3.com/index.txt and load properly in firefox but not in chrome

**Comment by markelog** [comment]
Sounds like https://code.google.com/p/chromium/issues/detail?id=162183, what version of Chrome did you use?

Could you create a jsfiddle example? Or even try it with native xhr?

**Comment by Thaina** [comment]
I used Chrome 39.0.2171.95 m. In that like said it fix from 36 so I think it not related

But it does fail with XmlHttpRequest

**Comment by markelog** [comment]
Could you please provide code example? On http://jsfiddle.net or http://jsbin.com

**Comment by mzgol** [comment]
@Thaina Hey, just checking up again. Would you be able to provide a test case on http://jsbin.com as @markelog asked?

**Comment by alokrajiv** [comment]
Is this issue still open?

**Comment by dmethvin** [comment]
There's a green "Open" above so yes. The comment above yours asks for a test case. Can you make one?
