### ISSUE TITLE
jQuery 1.11.1 selector to find empty inputs not working

### ISSUE THREAD

**Issue by msh-odoo** [jquery/jquery#2008]
Affected jQuery version: 1.11.1

I have code to find empty inputs(consider the case if you having form with blank inputs)
$("input[type=text][value='']").css('border-color', 'red');

But what I found code is working fine with jQuery 1.8.3 but does not seems to work with 1.11.1

Expected: It should set border color of all empty inputs

Current behaviour: It fails to find empty inputs

**Comment by dmethvin** [comment]
Sounds like you are trying to use a selector to get the current `value` property rather than the `value` attribute. Lacking any example, that is my guess. Please ask for help on StackOverflow.

**Comment by msh-odoo** [comment]
Thanks Dave for attention on this, I am having scenario where I want to select all inputs which does not having value and I want to achieve this using selector, is there a way to find such elements.

With version 1.8.3 same code is working

**Comment by timmywil** [comment]
The code is actually broken in 1.8.3. The value property represents the current value; the value attribute does not. Try this instead...

```js
$('input[type=text]').filter(function() { return this.value === ''; });
```
