### ISSUE TITLE
Progress doesn't fire after .then() for resolved promises

### ISSUE THREAD

**Issue by homm** [jquery/jquery#2013]
Suppose we have the Deferred object and try to set handlers on progress for both `.promise()` and `.then()` objects:

```js
var d = $.Deferred().notify();
d.promise().progress(function(){ console.log('promise') });
d.then().progress(function(){ console.log('then') });
```

This works as expected, both progress handlers will fire. But if we try to set progress handlers for resolved Deferred, the result will be different:

```js
var d = $.Deferred().notify().resolve(); // Look there, I'm resolved.
d.promise().progress(function(){ console.log('promise') });
d.then().progress(function(){ console.log('then') });
```

Only first handler will fire. The problem in [tuples order](https://github.com/jquery/jquery/blob/ab20d9d24f0a95df382c02e9ef3dcc4adb86e4f1/src/deferred.js#L12-L14). `Progress` tuple come last, and therefor, when [newDefer.notify()](https://github.com/jquery/jquery/blob/ab20d9d24f0a95df382c02e9ef3dcc4adb86e4f1/src/deferred.js#L39) is called, newDefer is already resolved and doesn't accept notifying.

This bug is similar to https://github.com/jquery/jquery/issues/1894, but slightly different.

**Comment by dmethvin** [comment]
I think this a dup of #2010 but I'll let @gibson042 make the final call. 

I would say that this may not work in the near future with `.then` if we make it strictly Promise/A compatible, and you'd need to use Deferred-specific methods. Again, that hasn't been decided but as best practice it would be good to expect standard behavior from standard names.

**Comment by gibson042** [comment]
Extremely similar, but not quite a duplicate... @homm, would you like to submit a PR? Both the code and new tests should be straightforward.
