### ISSUE TITLE
web-based chat

### ISSUE THREAD

**Issue by tomByrer** [jquery/jquery#2017]
> [btw, i guess github is now a replacement for #jquery-meeting channel huh :-)](https://github.com/jquery/jquery/issues/1862#issuecomment-63110406)

HipChat seems good, as there are many [alternatives](https://github.com/cjbarber/hipchat-alternatives).  We use [Gitter for jsDelivr](https://gitter.im/jsdelivr/jsdelivr) (public & private).  Nice to have nice linking to GitHub & Markdown.  It is handy, eats CPU though.

**Comment by arthurvr** [comment]
Nah. That one time was exceptional and it wasn't really our intention to have a 'meeting' in there, I think we all still like IRC. Also we have our nice [docs](http://irc.jquery.org/irc-help/), [community](http://irc.jquery.org/) and infrastructure on IRC.

**Comment by timmywil** [comment]
Thanks for opening an issue, but we won't be moving away from IRC anytime soon. It has been thoroughly integrated into pretty much every jQuery project.
