### ISSUE TITLE
Document references to PRs and Issues

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#2019]
When referring to Github tickets and PRs we use [the common `gh-` notation](http://contribute.jquery.org/commits-and-pull-requests/#references) for Github tickets and PRs. We want to avoid using `#` notatation entirely in commits and issues to avoid confusion between the two trackers and to avoid Github accidentally linking refs to our old tracker. In our meeting this week we had discussed using [trac-12344](http://bugs.jquery.com/ticket/12344) notation. For commits we can either use the short `trac-12344` notation or the full `http://bugs.jquery.com/ticket/12344` URL.

Ref https://github.com/jquery/contribute.jquery.org/issues/102

**Comment by timmywil** [comment]
Are there any line items for this issue and can it be closed? Was it just acting as a notification? If so, sounds good to me. :+1:

**Comment by dmethvin** [comment]
For linking tickets in GH issues and discussions, i like the cleanliness of the [trac-12344](http://bugs.jquery.com/ticket/12344) notation although we have to link it ourselves with Markdown. For Trac links in commits I'd lean towards full URLs in a `Ref: ` since they are unambiguous. Not really sure where to write down what we agree on so others can see it. Once https://github.com/jzaefferer/commitplease/issues/33 and https://github.com/jzaefferer/commitplease/issues/34 happen, it will be harder to break the rules whether you read them or not.

**Comment by mzgol** [comment]
This seems handled by https://github.com/jquery/contribute.jquery.org/issues/102 so I'll close this ticket.
