### ISSUE TITLE
SVG loaded from file after .fadeOut() and .fadeIn() loses it's properties?

### ISSUE THREAD

**Issue by stefek99** [jquery/jquery#2024]
I have observed a strange behaviour: http://plnkr.co/edit/JUQJG2BbiqyO0ODg8HNP?p=preview

```
<!DOCTYPE html>
<html>

  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>
      $(window).load(function() {
        
        $("#inline").find("path").attr({"stroke-width" : "15"})
        $("#inline").fadeOut();
        $("#inline").fadeIn();
        
        $($("#fromfile").get(0).contentDocument).find("path").attr({"stroke-width" : "15"})
        $("#fromfile").fadeOut();
        $("#fromfile").fadeIn();
        
      })
    </script>
  </head>

  <body>
    <h1>SVG inline</h1>
    <svg id="inline" width="190px" height="160px" version="1.1" xmlns="http://www.w3.org/2000/svg">
      <path d="M10 10 C 20 20, 40 20, 50 10" stroke="black" fill="transparent"/>
    </svg>

    <h1>SVG from file</h1>
    <object id="fromfile" data="svg-from-file.svg" type="image/svg+xml"></object>
    
  </body>

</html>
```

You can observe in the animated GIF that:
* there is stroke-width property
* fading in removes it (potentially some reload occurs)

![fadein](https://cloud.githubusercontent.com/assets/249703/5882119/8a6b75cc-a33e-11e4-8d08-f56c777e3ec4.gif)

When SVG is loaded inline that behaviour doesn't occur.

**Comment by dmethvin** [comment]
jQuery is an HTML DOM library. Some stuff happens to work in SVG but our main goal is to do no harm as long as you don't use jQuery itself to manipulate SVG. That alone can be difficult when the two are mixed in a single document!  See our [Won't Fix](http://contribute.jquery.org/wont-fix/) page.

That said, if you diagnose the problem and the fix is simple enough, we would consider it.

**Comment by stefek99** [comment]
Sure thing.

I read https://github.com/jquery/jquery/blob/master/CONTRIBUTING.md but not **won't fix**.

There is actually an easy fix in my code - animate opacity - so no worries.

(thank you for instant reply)
