### ISSUE TITLE
ajax: load page fragment from XHTML gives error because of DOCTYPE+XML declaration

### ISSUE THREAD

**Issue by fawzibr** [jquery/jquery#2025]
Trying to load a page fragment from a XHTML document fails giving a "SyntaxError: An invalid or illegal string was specified" (at least on Firefox). This happ

ens with the latest versions (1.11.2 and 2.1.3). It happens because the XHTML document has the XML declaration and the DOCTYPE. I think if a regular HTML file has the DOCTYPE it will also fail. If both are removed the XHTML fragment is loaded correctly. 

By changing a few lines in the buildFragment function the problem goes away (fix works on both versions):

Change:

tmp.innerHTML = wrap[ 1 ] + elem.replace( rxhtmlTag, "<$1></$2>" ) + wrap[ 2 ];

To:

// regex: first removes processing instructions, second the DOCTYPE
var rProcessingInstructions=/<\?(([\w:]+)[^>]*)\?>/gi;
var rDOCTYPE=/<!(?=DOCTYPE)((?:[^>])*)>/gi;
// 					
tmp.innerHTML = wrap[1] + elem.replace( rxhtmlTag, "<$1></$2>").replace(rDOCTYPE,"").replace(rProcessingInstructions,"") + wrap[2];

**Comment by dmethvin** [comment]
Can you provide a complete example? It sounds like you may be attempting to load a complete document (including doctype) using `.html()` or `$.load()`. If you read the [docs for $.load](http://api.jquery.com/load/) there's a warning related to this.

**Comment by fawzibr** [comment]
I uploaded a test at http://s000.tinyupload.com/index.php?file_id=19227498712864525930.

Simple XHTML 1.0 strict (validated) with 3 buttons:

Load HTML (load a fragment from a simple html file, not validated. load fragment works)
Load HTML with doctype (load a fragment from a html 4.01 strict file, validated. load fragment fails)
Load XHTML (load a fragment from a xhtml 1.0 strict file, validated. load fragment fails)

**Comment by markelog** [comment]
It mentioned it indirectly - 

> jQuery uses the browser's .innerHTML property to parse the retrieved document and insert it into the current document. 

As you probably figure out, host xhtml document is too restrictive to handle doctype markup. I'm afraid this issue is too much of an edge-case for us to handle :-(

**Comment by fawzibr** [comment]
That warning is just to state that some tags will be lost (html,title,...) when it is added to the document and the document wont be the same, not that it will fail to load a fragment from validated HTML/XHTML documents. 

I still think it should be fixed. It doesn't seem that that hard and it will make most valid HTML/XHTML documents work (well at least more than now).

**Comment by dmethvin** [comment]
If you want to load a full XML document, wouldn't you load it as XML and then pick out the part of the document you want to inject? Why are you trying to inject the whole thing?

**Comment by markelog** [comment]
@fawzibr 

> That warning is just to state that some tags will be lost (html,title,...)

Didn't talk about that part, meant

> jQuery uses the browser's .innerHTML 


@dmethvin 
> Why are you trying to inject the whole thing?

I think he expects <a href="http://api.jquery.com/load/#loading-page-fragments">this</a> to work.

**Comment by dmethvin** [comment]
Oh well I'm not convinced that it should. Browsers tend to be sloppy with plain old HTML and try to make sense of it even if it's not clear. If you decided to choose XHTML for a document type then you should not expect sloppy parsing and instead should be very specific about what you want to happen. The test case seems to want the sloppy "throw away anything that's inconvenient"  part, and the only thing the browser is unwilling to throw away is the doctype so it wants jQuery to remove it so the rest can be sloppy.

**Comment by dmethvin** [comment]
This definitely seems like too much of an edge case to handle in our normal processing. If the document is a complete well-formed XML document you could load it that way.
