### ISSUE TITLE
$.ajax with type as the first parameter

### ISSUE THREAD

**Issue by JJia-OOOO** [jquery/jquery#2034]
how about another overloaded version of the $.ajax function?
$.ajax( type, url[, settings ] )
where type is "POST" etc.

**Comment by zhanhb** [comment]
It seems a little hard to do that. For you will never know it is a url or a type.
the url parameter is leagacy for jquery@<1.5

**Comment by JJia-OOOO** [comment]
@zhanhb did you mean that the url version of $.ajax is obsolete?

**Comment by JJia-OOOO** [comment]
@zhanhb type & url are string, settings is object

**Comment by zhanhb** [comment]
NO NO NO, just the first parameter url
$.ajax([url, ]settings)
Here is the source code of jquery-1.11.2
Line 8946-Line 8953
	// Main method
	ajax: function( url, options ) {

		// If url is an object, simulate pre-1.5 signature
		if ( typeof url === "object" ) {
			options = url;
			url = undefined;
		}

**Comment by zhanhb** [comment]
And it's not deprecated now.

**Comment by JJia-OOOO** [comment]
ajax: function( type, url, options ) {
    if ( typeof type === "string" && typeof url === "string") {
        ...
    }
}

**Comment by dmethvin** [comment]
There is no reason to add another signature, it doesn't simplify usage.
