### ISSUE TITLE
.css("min-height") fails when css-display-property is set to table on IE9

### ISSUE THREAD

**Issue by delijah** [jquery/jquery#2035]
jQuery-Version: 1.11.2 and 2.1.3
Browser: IE9
OS: Win7 (modern.ie VirtualMachine)

I have a div, where i want to read the min-height, max-height, min-width and max-width css-style-properties with the "css"-function of jQuery.

This works well basicly, but if i define that div as a table ("display: table"), i cannot get reasonable values back anymore.

This only happens in IE9.
In IE8/10/11, Google Chrome 40 (Mac), Firefox 34 (Mac) and Safari 8 (Mac) there is no problem.

Example: http://jsfiddle.net/3o748vb3/2/embedded/result/

**Comment by dmethvin** [comment]
Screen shot of the IE9 console from running the fiddle:
![capture](https://cloud.githubusercontent.com/assets/157858/6181093/cbe58e44-b2fb-11e4-8048-0c1e24e82953.PNG)

**Comment by dmethvin** [comment]
Looks like `.getComputedStyle()` returns `0px` from the table-bending chicanery going on there. Not sure we can or should do much about it. Can you use a table instead?

**Comment by dmethvin** [comment]
This is sufficiently obscure and difficult to work around that I think we'll mark it wontfix. IE9 just doesn't like divs styled as table elements.
