### ISSUE TITLE
Feature request: parse url querystring

### ISSUE THREAD

**Issue by rasca** [jquery/jquery#2037]
I'm sure I'm not alone here, there are dozens of questions asking how to parse the url querystring with jQuery. There are a lot of answers but most of them don't accept multi valued keys or keys without values e.g. `?a=1&a=2&c&d`.

I end repeating code in several of my projects, I think this could be included in jQuery core.

**Comment by matryer** [comment]
Maybe embedding something like: https://github.com/stretchr/arg.js

**Comment by dmethvin** [comment]
This is a pretty simple plugin. Look at the size of arg.js, we definitely wouldn't want to increase the size of jQuery that much for something that already has a solution available for those who need it.
