### ISSUE TITLE
Issue with return of Sizzle.attr

### ISSUE THREAD

**Issue by brunobatista** [jquery/jquery#2040]
I get issue with return of `Sizzle.attr`, the message of error is:

```
Uncaught TypeError: undefined is not a function
```

```js
	return val !== undefined ?
		val :
		support.attributes || !documentIsHTML ?
			elem.getAttribute( name ) :
			(val = elem.getAttributeNode(name)) && val.specified ?
				val.value :
				null;
```

Version 2.1.3. Line [error here](https://github.com/jquery/jquery/blob/7602dc708dc6d9d0ae9982aadb9fa4615a9c49fa/external/sizzle/dist/sizzle.js#L892).

Any idea?

**Comment by dmethvin** [comment]
Please provide a test case.

**Comment by timmywil** [comment]
Thanks for opening an issue, but I think the best place to start would be the #jquery irc channel or stackoverflow.com.

**Comment by brunobatista** [comment]
Ok @timmywil, thanks!
