### ISSUE TITLE
An alias for jquery.clone

### ISSUE THREAD

**Issue by Mr21** [jquery/jquery#2044]
Hi :)

Why not to make an alias on:
`$.clone(object);` --> `$.extend({}, object);`
`$.clone(object, true);` --> `$.extend(true, {}, object);`
?

I found there is already a secret undocumented `jquery.clone` function used two times in the code but we can easily modify this, i think.

**Comment by dmethvin** [comment]
It would be confusing to have two methods named `.clone()` that did different things. The new proposed method isn't saving a lot of typing either. And, unlike the DOM `.clone()`, a clone on other objects can't support any of the magic that might occur in a constructor. It just copies properties. The `$.extend()` call is making that clear, since it's starting with a plain object.

**Comment by Mr21** [comment]
I don't think it's *two different things*:
`.each();` is a foreach for a DOM collection and `$.each()` is a foreach for basic array.
So I think it's intuitive to understand `.clone()` is for cloning DOM elements and `$.clone()` for cloning basic objects/array.

I am agree with you, it's not the best saving of typing of the year ^^ but it's more for the coherence of the code, i think it's better if we read `clone` instead of `extend` when the user is *cloning* something.

You're also right about the constructor etc. but I think nobody expect this comportement.
For example the `_.clone()` of the *underscorejs* doing the same thing of `$.extend({}, obj)`.

**Comment by dmethvin** [comment]
Your example is a great one. [`$.fn.each` is implemented using `$.each`](https://github.com/jquery/jquery/blob/087d280ad1160de53a45ea96184911194f7b46e0/src/core.js#L79-81). That would not be the case for `$.clone` vs `$.fn.clone`, they would "clone" different types of objects with very different semantics. 

In any case, you can easily do this with a plugin if you like the name.
