### ISSUE TITLE
Release: remove npm publish --tag beta for non-pre releases

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery#2046]
This is coming with the release changes.

**Comment by mzgol** [comment]
Why?

**Comment by timmywil** [comment]
Is there a reason why this is done for stable releases?

**Comment by timmywil** [comment]
It will still do `npm publish --tag latest`.

**Comment by mzgol** [comment]
The reason is that if the latest release is newer than the latest beta and we have a user that likes to be on a bleeding edge and uses:
```
npm install jquery@beta
```
they should get the latest release. We discussed it a while ago and this was added explicitly for this purpose.

**Comment by timmywil** [comment]
Ah, I see. I missed that conversation. It's not a beta release, but I guess that's fine in this case.
