### ISSUE TITLE
Simplification of native method signatures

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2047]
Prime candidates, at the moment, are `addEventListener ` third argument for `master` branch and second argument of `getComputedStyle` for both branches.

See https://github.com/jquery/jquery/pull/1842#issuecomment-72102266

**Comment by mzgol** [comment]
> `addEventListener ` third argument for `master`

Why just `master`? The only difference between branches is IE8 which obviously doesn't go through the `addEventListener` path.
