### ISSUE TITLE
Fix event delegation with selector-native

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery#2048]
When event delegation started using Sizzle's seed handling for scoped matches, it broke event delegation when selector-native replaced Sizzle. Worse comes to worse, we can just defer to matchesSelector and eat the scope issue.

**Comment by timmywil** [comment]
By the way, I was wrong about this being broken. I was thinking we weren't dealing with the `seed` argument in selector-native, but it turns out we were. There's still a behavior difference due to the nature of QSA's scoping problem, but that pretty much requires Sizzle to fix.

**Comment by mzgol** [comment]
> There's still a behavior difference due to the nature of QSA's scoping problem, but that pretty much requires Sizzle to fix.

...or the new @gibson042's in-jQuery implementation that borrows some ideas from Sizzle but only as much as needed (see https://github.com/jquery/sizzle/issues/293#issuecomment-154581860 for more info). But that's a plan for the next major.

**Comment by dmethvin** [comment]
At some point the [DOM `matches` and `findAll`](http://dev.w3.org/2006/webapi/selectors-api2/#interface-definitions) would help here, but nobody seems to be in a hurry to implement them.

**Comment by mzgol** [comment]
Until we drop IE 11 (which will happen once we conquer Mars) we need all this parsing logic anyway.

**Comment by timmywil** [comment]
> ...or the new @gibson042's in-jQuery implementation that borrows some ideas from Sizzle but only as much as needed (see jquery/sizzle#293 (comment) for more info). But that's a plan for the next major.

Or possibly later. Something I like about selector-native is that it doesn't even tokenize the selector, which would be required even in a streamlined engine. Rather than an in-jQuery implementation, I'd prefer to see a new version of Sizzle that drops all polyfills (for native selectors) and POS handling, and just manipulates the selector into something that can first go through qsa or matchesSelector, then filtered. Regardless, it won't be for 3.0, and it's something we can discuss later when the time comes.
