### ISSUE TITLE
.hide() stops event propagation

### ISSUE THREAD

**Issue by omuleanu** [jquery/jquery#2049]
you can see it here ( it has explanation )
http://jsbin.com/zabajetare/2/edit?html,js,output

Edit: looks like changing the css('display') property of the previous sibling of the target stops the propagation; calling .empty() on target's previous sibling has the same effect.

**Comment by dmethvin** [comment]
Hidden inputs can't contain the focus, that's not a rule jQuery can break for you.

**Comment by omuleanu** [comment]
@dmethvin I'm not trying to focus a hidden input, I'm clicking a visible textbox at the same time focusin event occurs and it's handler hides a sibling of the input, this prevents the click event to be propagated further.

here's another take on my demo: http://jsbin.com/yavomuvafa/4/edit?html,js,output 
I haven't used hide() this time I used empty() instead

**Comment by dmethvin** [comment]
I agree, I was confused and thought it was wrapped. However, this also happens with bare DOM as far as I can tell:

http://jsbin.com/ceqovimuji/1/edit

Does that look correct? If so I don't think there is anything we can do if the click isn't delivered.

**Comment by omuleanu** [comment]
@dmethvin yes, it looks correct, tried it in chrome and ie (in ff dom caption clearing doesn't work)

**Comment by dmethvin** [comment]
Removing the element above the text box moves it from underneath the mouse pointer. If you keep the mouse depressed and move it up to the box, the click appears.

**Comment by omuleanu** [comment]
ok, I guess for the click event to be considered, the mousedown and mouseup need to happen on the same target, the click happens on the same parent but because the child target moved, it's not considered a click anymore
 
have a look at this demo: http://jsbin.com/hagixugile/2/edit
I guess a workaround for this is to use mousedown instead of click, so the parent will get the mousedown and mouseup anyway
