### ISSUE TITLE
Drop support for Android < 4

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2050]
Android < 4 <a href="https://developer.android.com/about/dashboards/index.html">has</a> 8% of market share of all Androids.

Whereas Android, as platform, <a href="http://www.idc.com/prodserv/smartphone-os-market-share.jsp">takes</a> 85% of the mobile market share, which gives us ~6.8% of Android < 4 of whole mobile market share. 

If we would account desktop browsers in this calculations, we get super low percentage of Android < 4 of the whole browser market share.

Plus, i don't remember any tickets about old Android, except the ones that created by @mzgol, who added it to the testswarm and found bugs because of it.

Given all that, should we drop support for it?

I know you wanna :-).

**Comment by mzgol** [comment]
Mobile market share should be counted separately from desktop; otherwise we'd grt low values for almost everything.

6.8% of mobile devices is still a non-trivial amount. jQuery Mobile also needs support (cc @arschmitz). Besides, the real market share is most likely higher as the Android Dashboard counts people visiting the Google Play Store & more people on newer devices do it.

I don't think we should do it in 3.0.

**Comment by mzgol** [comment]
One thing we could do is introduce grades of support like Mobile has; we'd then make sure all the APIs work but we wouldn't care about 1 pixel differences in Android 2.3 etc. I know @rwaldron was against it, though.

**Comment by markelog** [comment]
> Mobile market share should be counted separately from desktop

Why exactly?

> otherwise we'd get low values for almost everything

Could you define "everything"? 

> Besides, the real market share is most likely higher as the Android Dashboard counts people visiting the Google Play Store & more people on newer devices do it.

Sorry, but this is a speculation. I think statistics above, is as close as we can get to the real data.

Couple years ago, Android < 4 was more then 50%, now it's only 6, its share is rapidly dropping, but it is giant pain to support it.

We might wait a little here or do it only for the `compat` branch which would make sense. But as i mentioned above, we didn't had real old Android issue. Which gives me a more optimistic attitude to this topic.

**Comment by arschmitz** [comment]
One additional thing to consider here is hybrid apps, One of the main uses for 2.x/3.x vs 1.x/compat, we have always said, was hybrid apps and similar. This is also one of the main ways jQuery Mobile is used.

If android < 4 is dropped, in the main branch, then you will no longer be able to use if for many hybrid apps that support android. Often the goal of hybrid apps is also the idea of a single code base. So this likely means in these cases, especially when using jQuery Mobile, that apps will start switching on other platforms like iOS as well, so as to be able to use the same version of jQuery everywhere. 

For those making apps on android 8% ( or 6.8% cross platform ), of the market is a huge number. I think this would decrease the usefulness of the main branch, and drive more people to have to use compat. Im not really sure thats what we want to do?

**Comment by arschmitz** [comment]
> One thing we could do is introduce grades of support like Mobile has; we'd then make sure all the APIs work but we wouldn't care about 1 pixel differences in Android 2.3 etc. I know @rwaldron was against it, though.

I would be ok with this however, I would say to be careful, this has been a little bit of a pain point over time and we are still trying to figure out the "right" way to handle this, in mobile.

**Comment by mzgol** [comment]
@markelog 
>> Mobile market share should be counted separately from desktop
>
> Why exactly?

Because people divide into ones using Firefox, Chrome, IE etc. but they don't divide into people using Android, IE, desktop Opera etc.; they use both a desktop browser and a mobile one if they have a smartphone; they just use the mobile one more rarely than the desktop one. But they do use it and conflating desktop & mobile browsers doesn't take that into account.

**Comment by mzgol** [comment]
> If android < 4 is dropped, in the main branch, then you will no longer be able to use if for many hybrid apps that support android. Often the goal of hybrid apps is also the idea of a single code base. So this likely means in these cases, especially when using jQuery Mobile, that apps will start switching on other platforms like iOS as well, so as to be able to use the same version of jQuery everywhere.

Actually, we officially don't support hybrid apps on the `compat` branch. So dropping Android 2.3 from `master` would mean we don't support Android 2.3 in hybrid apps at all.

**Comment by arschmitz** [comment]
That would put mobile in a really hard spot. It will force us to either drop support for 2.3 in hybrid apps, or recommend people never leave 2.x, if they need to support android. This would also make actually defining our core dependency kind of complicated.

**Comment by mzgol** [comment]
> That would put mobile in a really hard spot. It will force us to either drop support for 2.3 in hybrid apps, or recommend people never leave 2.x, if they need to support android.

Yup, that's yet another reason why dropping Android < 4 would be premature at this point. As long as Mobile supports it, we should, too.

**Comment by markelog** [comment]
> if they need to support android

You mean "if they need to support android 2.3"? Do they really need that? If this is a shared opinion, how about we keep this open so we could revisit it later.

@dmethvin?

**Comment by dmethvin** [comment]
Seems like there are still some reasonably big numbers for Android 2.3 so it would be a bad idea to just break outright on that platform. So for example, the `.apply(NodeList, ...)` issue, I think we are only keeping it in for Android 2.3 and PhantomJS at this point. But if we took it out the code would blow up and nothing would work at all.

**Comment by arschmitz** [comment]
@markelog no I meant if they need to support android as a whole. While this is a generalization, I am fully aware, many if not most apps written for android support the same versions of android currently supported by the app store, which is actually 2.2+. While i'm ok ignoring 2.2 because its numbers are SOOOOO low I think most devs are realistically are ignoring them as well. I don't think we can ignore 2.3.

**Comment by mzgol** [comment]
@arschmitz A while ago I've run our test suite on Android 2.2 via BrowserStack and it turns out we don't fail many more tests than on Android 2.3 currently so it should mostly work even if we don't test it. The difference between 2.3 & 4.0 is far greater.

**Comment by arschmitz** [comment]
@mzgol I'm aware, I just didn't bring it up, since I don't think anyone was advocating for us supporting 2.2. Yes in reality while its probably *fairly* safe to run on 2.2, we don't actually test so I would not recommend it to anyone.

**Comment by timmywil** [comment]
Given the current usage stats and the need for Android 2.3 support in mobile, I don't think we'll be dropping support for 2.3 just yet. But it's looking hopeful that we'll be able to drop support in a later version. We'll open a new issue when the time comes.

**Comment by arschmitz** [comment]
:+1: Trust me working on mobile I want to drop support more then anyone. I will cheer the day it happens, just cant be today :-(

**Comment by ximex** [comment]
i really think we could drop Android 2.3 now. Only 4.6% in the android statistics
