### ISSUE TITLE
removeAttr('onsubmit') not working in IE

### ISSUE THREAD

**Issue by ehrenwinterhof** [jquery/jquery#2051]
http://jsfiddle.net/ya7hvcmt/

Tested on IE 11 with developer tools disabled both submit functions will run. On Chrome or IE with developer tools open only the 2nd function will run. 

Bug occurs on jQuery 2.1,  edge, and compat edge.

**Comment by markelog** [comment]
See http://api.jquery.com/removeAttr/

> Note: Removing an inline onclick event handler using .removeAttr() doesn't achieve the desired effect in Internet Explorer 6, 7, or 8. To avoid potential problems, use .prop() instead

This note should include 9 and 11, but not 10 :-). IE is funny like that.
