### ISSUE TITLE
click not working with on and for an innerHTML changed

### ISSUE THREAD

**Issue by GearTheWorld** [jquery/jquery#2052]
// Click not working.  Probably because I change the innerHtml above but I don't understand why since I'm using JQuery on
    $(document).ready(function () {
        $(document).on("click", "#sap", function () {
            if (!ContentTransitionIsOn) {
                ContentTransitionIsOn = true;
                $(".Content").addClass("ContentTransition");
            } else {
                ContentTransitionIsOn = false;
                $(".Content").removeClass("ContentTransition");
            }
        });
    });

**Comment by GearTheWorld** [comment]
Here's the HTML 

<h1 id="sap" style="margin:auto;color:white;text-align:center;">SAP...</h1>

**Comment by GearTheWorld** [comment]
The div that contains the 'sap' element H1 has the innerHTML changed by javascript for language

**Comment by dmethvin** [comment]
Please ask for programming help on StackOverflow or the jQuery Forum.
