### ISSUE TITLE
Sizzle.attr TypeError

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [jquery/jquery#2055]
The code below throws an Uncaught TypeError Exception because Sizzle.attr tries to call getAttribute of a comment element but comments does not have this function.

```Javascript
$(function(){
    $('body').on('DOMNodeInserted', '*[data-test]', function () { 
		console.log(this); 
	}).append('<!-- new comment -->');
});
```

**Comment by gibson042** [comment]
Related: https://github.com/jquery/sizzle/pull/256#issuecomment-40119966

We could punt on this, but it's so small that we might as well come up with a valid test and cherry-pick fc2ba2e1361126c39f955437ee025cfca3bffa65 from `compat` (where it somewhat indirectly prevents this issue from surfacing).

**Comment by timmywil** [comment]
:+1: for nodeType check.

**Comment by timmywil** [comment]
It looks like we already cherry-picked that commit.

**Comment by timmywil** [comment]
9d820fbd
