### ISSUE TITLE
Don't expose jQuery.swap

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2058]
Even if we want/need `jQuery.swap` internally, we still shouldn't expose it, there is no reason to do it now that we have a robust modular architecture. The method is undocumented so technically we could stop exposing it whenever we want; no better moment to do it than the 3.0 release!

I didn't see it in the code but just to make sure: @scottgonzalez & @arschmitz, I assume UI/Mobile doesn't depend on it?

**Comment by scottgonzalez** [comment]
We definitely don't use it in UI.

**Comment by arschmitz** [comment]
I didn't even know it existed until i saw the related discussion. It's definitely not in mobile either.

**Comment by timmywil** [comment]
Sounds good to me! I think it was originally exposed so users could have control over when to retrieve useful values for hidden elements, but that use case is rare at best.

**Comment by mzgol** [comment]
OK then, assigning to myself!

**Comment by dmethvin** [comment]
If it turns out something needs it but we don't want it internally, we could put it in jQuery Migrate. I doubt it's used externally and we never documented it, plus it's really bad practice from a performance standpoint.
