### ISSUE TITLE
Find / Context performance weirdness

### ISSUE THREAD

**Issue by Znarkus** [jquery/jquery#2059]
Hi! I must be missing something big, but why is there such a big difference in performance between these?

```javascript
var has = $article.find('ins').length > 0;
var has = $(article).find('ins').length > 0;
var has = $('ins', $article).length > 0;
var has = $('ins', article).length > 0;
```

Number 2 and 4 are ~20 times faster. http://jsperf.com/jquery-find-vs-context-sel/116

**Comment by dcherman** [comment]
That's not a valid test.  Your `$article` variable contains every single `<article>` element on the page whereas `article` contains only a single one since you've indexed into it.

Use `article = $article.get()` for a valid comparison and you'll see they're equivalent.

**Comment by Znarkus** [comment]
Ah sorry, should have inspected the prep code more closely. Found the base test at https://github.com/airbnb/javascript/issues/58
