### ISSUE TITLE
Callback function not called on blur event

### ISSUE THREAD

**Issue by alexdmiller** [jquery/jquery#2065]
**Versions:** >= 1.8.3, >= 2.0.0
**Browser:** Chrome 40.0.2214.95

#### Steps to reproduce

1. Save the following HTML in a file:

      ```html
	<html>
	  <head>
	     <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js">
		   </script>
	  </head>
	  <body>
	    <div id="a" tabindex=0></div>
	    <script>
		$('#a').bind('blur', function() {
			console.log('blur');
		});

		$('#a').focus();
		// The call below should trigger 'blur' callback and print to the console.
		$('#a').blur();
	    </script>
	  </body>
	</html>
      ```
2. Open the file in Chrome and open the debug panel.
3. Click anywhere in the debug panel.
4. Refresh with `ctrl+r`.

#### Expected

The callback function should be called and `blur` should print to the console.

#### Observed

No output to the console.

#### Why this matters

The callback works as expected if you don't click on the debug panel, so it has something to do with the window being active (for some sense of the word "active" -- I can't tell if this bug is related to `document.activeElement`). The bug also occurs when using the [Karma test runner](http://karma-runner.github.io/0.12/index.html) with [Jasmine](http://jasmine.github.io/), making our tests involving `blur` fail for versions of jQuery >= 1.8.3.

#### Culprit

I suspect the problem has something to do with [`event.js:567`](https://github.com/jquery/jquery/blob/master/src/event.js#L567). After clicking on the debug panel, the call to `this.blur()` does not trigger the event callback.

**Comment by alexdmiller** [comment]
I should add that this is reproducible if the `<div>` is changed to an `<input>`.

**Comment by alexdmiller** [comment]
Looks like `focusin` and `focusout` don't have this issue.

**Comment by dmethvin** [comment]
Seems to work for me. http://jsbin.com/bakawi/1/

Take a look at the [fuzzy rules for focus](http://www.w3.org/TR/DOM-Level-3-Events/#events-focusevent-doc-focus) and try them with native methods. If jQuery is breaking something that works with the native methods, please provide a test case for it.
