### ISSUE TITLE
Can't import module with bower properly

### ISSUE THREAD

**Issue by andreyfomin** [jquery/jquery#2067]
I try to import this package with bower. Get error message
06 Feb 13:55:55 - [31merror[0m: [Error: Component JSON file "C:\dev\repos\spa-jsclient-javaserver\client\src\main\bower_components\jeditable\.bower.json" must have `main` property. See https://github.com/paulmillr/read-components#README]

**Comment by markelog** [comment]
jQuery have defined 'main' property in bower.json, it seems your issue is not connected to this project.
