### ISSUE TITLE
Chaining .submit to .add doesn't work on IE

### ISSUE THREAD

**Issue by danwalkerak** [jquery/jquery#2069]
The following syntax works on Safari (osx), Chrome (win/osx), and FireFox (win/osx) - but does NOT work on non-metro IE 11 (windows 8.1).

    var html = '<form id="theForm" name="theForm" action="/controller/action" method="POST">;
    html += '<input type="hidden" name="bob" value="-1" />';
    html += '</form>';

    //  I expect this to work in IE as it does in all other browsers.
    $(document).add(html).submit();

    // this also does not work in IE, but it does in all other browsers:
    $('BODY').append(html).submit();

    // This is the only thing I can get to work on IE - also works in other browsers.
    $('BODY').append(html);
    $('#theForm').submit();

**Comment by gibson042** [comment]
I'm not sure what you're expecting code like `$('BODY').append(html).submit()` to do, and therefore I also don't know what you mean by "work". What _I_ expect it to do is append a form to the body and then trigger a "submit" event on the body. Whereas something like `$(html).appendTo('BODY').submit()` would append and immediately submit a form.

**Comment by danwalkerak** [comment]
Ah.  I was expecting the submit to be triggered on the newly added html.

Apparently my understanding was incorrect.  Thank you.
