### ISSUE TITLE
Animated toggle() turns display:inline into display:inline-block

### ISSUE THREAD

**Issue by cburschka** [jquery/jquery#2071]
There's an example here: http://jsfiddle.net/cburschka/ve5fbujq/

The non-animated `toggle()` appears to work normally. An animation like `toggle('slow')` will put a `display:inline-block` property on the `<span>` element, which in the above example causes the red text to drop to a new line instead of wrapping normally.

This happens whether or not the span was explicitly set to display:inline earlier, or was just inheriting the default value.

This bug seems similar to #1774 (apparently closed prior to the release of 2.1.3), but isn't quite the same.

**Comment by dmethvin** [comment]
This looks correct to me. The `display: inline-block` is necessary to actually change the dimensions of the element during animation. The text wraps strangely because the `.hide()` animation changes the width, height, and opacity. When the width reduces to less than the length of the text, the text wraps.

What did you expect to happen?

**Comment by cburschka** [comment]
Basically, the problem is that calling toggle() twice doesn't leave it in the state it was before - it's permanently turned into an inline-block element, even after the animation is over.

It can be worked around by explicitly resetting the element back to inline after the animation is done, though.

**Comment by three3211** [comment]
@cburschka I am having the same issue. Whenever I call toggle, the hiding aspect works fine. However, when toggling back to show the hidden content, the inline style of `display:inline-block` is left and causes my content to appear not as it was originally.

As @cburschka, it can be worked around by explicitly resetting the element back to inline after the animation is done.
