### ISSUE TITLE
Add jQuery.deparam 

### ISSUE THREAD

**Issue by tjwudi** [jquery/jquery#2077]
jQuery has a nice method `$.param` for serializing object into string which can be used in query string. @AceMetrix offered [jquery-deparam](AceMetrix/jquery-deparam) for do things reversely, which is quite a common use case. I think it can be merged in jQuery.
Any thoughts?

**Comment by dmethvin** [comment]
Is there a problem with just using the plugin? If most people don't need it we'd be adding quite a few bytes for nothing.

**Comment by timmywil** [comment]
Agreed. Thank you for opening an issue, but I think this is best left as a plugin.

**Comment by smarts** [comment]
I agree w/ @tjwudi that this is a common case and should be included in the main jQuery package

**Comment by italomaia** [comment]
Well, why param() should not be a plugin and deparam() should?
