### ISSUE TITLE
native abort does not abort jqXHR in 2.1.x

### ISSUE THREAD

**Issue by salomvary** [jquery/jquery#2079]
If the native XMLHttpRequest is aborted (eg. calling abort(), suspending the computer or unloading the page) jqXHR does not fire any callbacks. Expected: fire error and complete callbacks.

Test code to reproduce:
```js
var wrappedXhr;
$.ajax({
    xhr: function() {
      wrappedXhr = jQuery.ajaxSettings.xhr();  
      return wrappedXhr;
    },
    url: '/echo/json/?delay=100',
    complete: console.log.bind(console, 'jQuery complete'),
    error: console.log.bind(console, 'jQuery error'),
    success: console.log.bind(console, 'jQuery success')
})
.progress(console.log.bind(console, 'jQuery progress'))
.fail(console.log.bind(console, 'jQuery fail'))
.always(console.log.bind(console, 'jQuery always'));
wrappedXhr.abort();
```

[Test code on jsfiddle](http://jsfiddle.net/salomvary/agg3ovxz/6/).

Note: the bug is **not** present in 1.11.x and 3.0 (master) versions.

**Comment by dmethvin** [comment]
Since 1.11.x polls it would seem to be okay, as you say. Not really sure why 3.0/master is okay though, seems like we would need an `onabort` hander to be notified of this. I'm not seeing any notifications if I change the version to master.

**Comment by timmywil** [comment]
Should we add an onabort handler in master?

**Comment by dmethvin** [comment]
Yes, it looks like we need to add one so that compat and master will have the same behavior.

**Comment by timmywil** [comment]
So, after digging into the issue, this isn't the blocker I thought it was. While we don't try to hide the native XHR, we don't encourage direct manipulation either. If you use jQuery's abort method instead, everything works fine: http://jsfiddle.net/timmywil/agg3ovxz/9/.

@dmethvin Do you think this is still worth a fix? One minor speedbump is that the status text for the OP's case in compat is "error" when it should be "abort", so fixing this requires changes on both branches and I'm not sure it's something we necessarily support.

**Comment by salomvary** [comment]
@timmywil using jQuery's abort method is not an option when the *browser aborts* the request for some reason (computer suspend for example).

**Comment by dmethvin** [comment]
So just to refresh myself without having to re-investigate, does this affect our current 3.0 master or 3.0 compat? The initial comment said it did not.

**Comment by mzgol** [comment]
@dmethvin It affects `compat` in a way that no handler fires at all. It affects `master` in a way that the `error` handler is fired instead of the `abort` one.

**Comment by timmywil** [comment]
Other way around.

**Comment by mzgol** [comment]
Ah, I confused this with #2413.
