### ISSUE TITLE
$.ajax(): settings.data is undefined in beforeSend when type=GET

### ISSUE THREAD

**Issue by staabm** [jquery/jquery#2081]
I would like to adjust/modify the values/data beeing sent with a ajax request in the beforeSend callback. 
Atm this seems only be possible for POST request, because `settings.data` is not defined in a GET typed request.

Is this intended behaviour?

see http://jsbin.com/juvarefubi/1/edit?html,js,output

**Comment by dmethvin** [comment]
The docs seem pretty clear on the purpose of `beforeSend`:

> A pre-request callback function that can be used to modify the jqXHR (in jQuery 1.4.x, XMLHTTPRequest) object before it is sent. Use this to set custom headers, etc. 

By the time it reaches that point, most of the other bookkeeping has already been completed. If you want to change the data you could do it in a [prefilter](http://api.jquery.com/jQuery.ajaxPrefilter/).

**Comment by staabm** [comment]
@dmethvin thanks for your anwser.

> Use this to set custom headers, etc.

I interpreted the `, etc.` that also `data` would be something which is allowed to modify.

**Comment by dmethvin** [comment]
That't not modifying the jqXHR though.

**Comment by staabm** [comment]
Is it somehow possible to use a `prefilter` for just one `ajax` call or is it just possible to register them globally?

**Comment by dmethvin** [comment]
If it's  just one ajax call, couldn't you just pass the data in the options or encode it in the URL before the call? (We're getting into forum/StackOverflow territory here, so you might want to start a thread there on the best way to deal with this use case.)

**Comment by staabm** [comment]
the data is already provided to $.ajax using `data` option by the lib I am using. The problem is, that I don't control the code their but only hook into the mechanics by a event fired their.
So I want to intercept to adjust the data beeing transmitted without modifying the lib itself.
