### ISSUE TITLE
empty() and remove() clear jquery data before focusout

### ISSUE THREAD

**Issue by djasper99** [jquery/jquery#2082]
jQuery version: Encountered in version 1.9.1, persists in 2.1.0
Browser: Chrome 40.0.2214.111 m
Operating System: Windows 7 Professional SP 1
JsFiddle: http://jsfiddle.net/zkdxLbgr/1/

The issue here:
Give an element with jQuery data focus.
Something causes the element to be removed from the dom, via .empty() or .remove().
empty() or remove() deletes the jQuery data for the element
empty() or remove() triggers a focusout event for the element
any focusout handlers that check the element's jQuery data are sorely disappointed that the data is no longer there

I would expect that the jQuery data would still be available for the element until it is actually removed from the dom.

My current workaround for the issue is to blur the focused element before calling empty() or remove().

**Comment by dmethvin** [comment]
The browser decides when to fire `focusout` when an element is removed from the DOM. It appears to do so after jQuery has removed data, but before the element is actually removed: http://jsfiddle.net/zkdxLbgr/3/

Focus management is flakey in general in many browsers, particularly in IE where blur is asynchronous. So for example in IE11 you don't even get the final `focusout` event:

![image](https://cloud.githubusercontent.com/assets/157858/6138005/96e22498-b14b-11e4-997f-3fe24f5f3abe.png)

There isn't a lot jQuery can do here. If you need to handle removing a focused element you should add logic in your own code.

**Comment by dmethvin** [comment]
Given the situation with this behavior, you should not depend on getting a focusout event from an element when it is removed. Explicitly set the focus to a visible element before removing the element that has focus. This is good practice anyway.
