### ISSUE TITLE
.css fails on elements with null ownerDocument.defaultView

### ISSUE THREAD

**Issue by andreifyodorov** [jquery/jquery#2086]
```
> doc = (new DOMParser()).parseFromString('<div>', 'text/html')
> doc.defaultView
null
> $(doc).find('div').css('')
jquery.js:6118 Uncaught TypeError: Cannot read property 'getComputedStyle' of null
```

**Comment by markelog** [comment]
I'm afraid it always fail in this case. Even if we would use `getComputedStyle` of the host window. 

I guess best we can do here is do the nop.

FYI: `css` method on detached nodes is always a bad idea.

**Comment by timmywil** [comment]
It's arguable that throwing an error is preferable. Even if we returned the style declaration, every value is empty string. I don't see a use case where retrieving styles this early is useful.

**Comment by mikesherov** [comment]
This stems from perf advice that is now no longer relevant about building your DOM detached to avoid layouts / paints.

But yeah, if a node is detached we should throw an error.

**Comment by dmethvin** [comment]
The current behavior seems fine to me unless there is a better use case showing this can commonly happen. Does it really help the caller to return empty strings for this case?

**Comment by timmywil** [comment]
Ok, it seems the team is in agreement. Thank you for opening an issue, but this is the desired behavior for retrieving styles on detached elements. I've opened a docs issue [here](https://github.com/jquery/api.jquery.com/issues/653).
