### ISSUE TITLE
Event handlers don't work like native ones

### ISSUE THREAD

**Issue by maciejmrozinski** [jquery/jquery#2094]
Event handler registered with addEventListener() can be instantly removed with removeEventListener(). on() and off() don't work like this. Example: http://jsfiddle.net/xf04www8/

**Comment by dmethvin** [comment]
I think you may be relying on undefined behavior. Chrome and Firefox don't show `b` but IE11 does. I didn't try other browsers. I can find a [spec reference](http://www.w3.org/TR/DOM-Level-3-Events/#event-flow) that says the event *path* should not change during delivery, and jQuery honors that. I didn't find a discussion about what should happen if a listener is removed in the midst of dispatch. Can you find one?

**Comment by maciejmrozinski** [comment]
I found something like this: http://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-EventTarget-removeEventListener

"This method allows the removal of event listeners from the event target. If an EventListener is removed from an EventTarget while it is processing an event, it will not be triggered by the current actions. EventListeners can never be invoked after being removed."

**Comment by dmethvin** [comment]
Yes, it does seem like the spec intended that behavior, and there is [similar language on MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget.addEventListener). Note that none of the three browsers seem to call an event listener that is added during the process of handling an event. http://jsfiddle.net/xf04www8/1/  This seems oddly asymmetrical but there doesn't seem to be a special case laid out in `addEventListener` the way it is in `removeEventListener`.

This is the classic "modifying a collection while it's being enumerated" dilemma. 
jQuery has a single DOM event listener for all the jQuery handlers on an element. It takes a snapshot of those handlers that exist at the time that the event arrives. If it tried to use the live collection it would need to guard against the case where an already-called handler was removed or it could skip a handler that was still attached. 

This is a lot of mess for a really rare edge case. jQuery event handler semantics don't match DOM event listeners exactly. The fact that not even all browsers do this consistently tells you how rarely people depend on it. My suggested resolution is just to add a sentence to the [.on() docs](http://api.jquery.com/on/) clarifying that the handler list for an element is set when the event is first delivered.

As far as what you wanted to do here, would something like `event.stopImmediatePropagation()` be a solution?

**Comment by maciejmrozinski** [comment]
The funny thing is that i'm not doing anything here with jQuery ;) I was just doing my own project and wanted to know how this case will work in native event handlers in browsers. Then i checked jQuery and found a mismatch.

I know and understand that making changes in part of code which is responsible for event handlers is not a good idea and will complicate it very much. I agree that this is a very rare case, which is proven by this, that i think, i am the first one who noticed that.

For me, adding notification to jQuery docs is sufficient and will do the job :)

**Comment by timmywil** [comment]
API issue opened: https://github.com/jquery/api.jquery.com/issues/665

**Comment by xoxulin** [comment]
Hi! http://codepen.io/xoxulin/pen/xGVjzP?editors=101 - I can't use `stopImeddiatePropagation` because exists third handler after current which must be invoked! I vote for W3C behaviour!

**Comment by DmitryBogomolov** [comment]
Hello.

+1 for `addEventListener`/`removeEventListener` behavior.
