### ISSUE TITLE
submit event triggered using enter keypress silents the first trigger event

### ISSUE THREAD

**Issue by gajus** [jquery/jquery#2095]
## To Reproduce

1. Focus the text input.
2. Press enter (keyboard key and not the submit input)

## Issue

First registered `blur` event does not have data describing the jQuery event (e.g. custom data or namespace).

## Demo

http://jsfiddle.net/gajus/Lrz5c7do/

## Markup and script required to reproduce the issue

```html
<form>
    <input type="text" class="address-input" />
    <input type="submit" value="Search" class="button-search" />
</form>
```

```js
$(function () {
    $('.address-input').on('blur', function (e, data) {
        console.log('OK', data);
    });

    $('.parameter.location')
        .find('form')
        .on('submit', function (e) {
            e.preventDefault();
    
            $('.address-input').trigger('blur', [{foo: 'bar 1'}]);
            $('.address-input').trigger('blur', [{foo: 'bar 2'}]);
            $('.address-input').trigger('blur', [{foo: 'bar 3'}]);
        });
});
```

Screenshot of the event log, https://www.dropbox.com/s/54aiue2zifdw8gq/jquery-bug.png?dl=0.

**Comment by dmethvin** [comment]
This is a dup of #1741.
