### ISSUE TITLE
Check document.readyState === "interactive" on $(document).ready

### ISSUE THREAD

**Issue by stackia** [jquery/jquery#2100]
https://github.com/jquery/jquery/blob/master/src/core/ready.js#L81

As the comment mentioned, IE9 will probably give an incorrect "interactive" readyState. But that only affects IE9. Should "interactive" be accepted on other browsers? I'm using require.js to load my scripts and exactly jQuery and many other scripts are loaded after DOMContentLoaded but before fully loaded. Scripts depending on $(document).ready have to wait until load event is triggered.

Currently I use <code>document.readyState === "interactive" ? init() : $(document).ready(init);</code> to get around this problem.

https://github.com/ded/domready/blob/master/src/ready.js#L16
This is another implementation of domReady which accept "interactive" readyState on browsers excluding IE.

Is there any reason why jQuery doesn't do that?

**Comment by dmethvin** [comment]
To recast the question in the form of a bug/feature, I think it would be whether jQuery should support being lazy-loaded so that it would run `.ready()` handlers before `window.onload` fires. You can read through http://bugs.jquery.com/ticket/10067 for background. It seems like we could use the `.doScroll` hack that domready uses.

**Comment by mzgol** [comment]
> It seems like we could use the `.doScroll` hack that domready uses.

What `doScroll` hack? ;) It was needed for IE<8, now the code looks [like that](https://github.com/jquery/jquery/blob/9368a8cd8ca81902b8359188668973e489fca6db/src/core/ready.js#L120-L126).

**Comment by mzgol** [comment]
FWIW, this is the mentioned hack (last commit before dropping IE<8): https://github.com/jquery/jquery/blob/a467f8653a6fab2903148df80ab0ce9f5f4fd04f/src/core/ready.js#L125-L152

**Comment by dmethvin** [comment]
I meant the check for `.doScroll()` they use in domready. It turns out that method went away in IE11, so by using that as an indirect feature check you only penalize IE9 and IE10. At  least that's what I think it would mean.

**Comment by mzgol** [comment]
Ah, the library domready, not our core/ready. ;) Sorry!

**Comment by timmywil** [comment]
@dmethvin To sum it up, we're thinking we could check if "interactive" as long as we use a scroll hack to determine interactive where not supported?

**Comment by dmethvin** [comment]
Even nicer now. If `document.body.doScroll` exists we assume that we are in IE8-10 and do not allow our `.ready()` to fire on `document.readyState === "interactive"` because those versions of IE don't work properly with it. In all other cases we allow interactive.

**Comment by mikesherov** [comment]
As the original author of the interactive check, there are other gotchas to consider here. There is also the case of flushed partial content creating an interactive state without the full html being loading. Whether that was oldIE only or not, I don't remember, but need to check that.

Also, there was the case where readyState interactive caused bottom of page scripts that accidentally relied on out of sync operations while combined with ready firing synchronously. Consider the following code:

```
<html>
<body>
<script>
var foo;

$(function() {
  alert(foo);
});

foo = 'hi';
</script>
```

This always alerts `hi` in current jQuery. When I implemented readyState == 'interactive', there were cases where `undefined` was being alerted. Now, this may no longer be a problem if `.ready()` always fires async, but at the time, jQuery deferred were synchronous.

Just food for thought, and edge cases to consider.

**Comment by dmethvin** [comment]
Thanks @mikesherov, fortunately I know we have at least one good unit test for this. The question is whether IE11 or Edge still has this bug, I believe those were the only places where `interactive` caused problems.

**Comment by dmethvin** [comment]
Just for reference, [the test](https://github.com/jquery/jquery/blob/0fb84fa8ccefcd07febf282fd7b80262ad70add7/test/unit/event.js#L2541-L2548) and [the iframe file](https://github.com/jquery/jquery/blob/0fb84fa8ccefcd07febf282fd7b80262ad70add7/test/data/event/syncReady.html). Whoa, was that really 2012? Time flies.
