### ISSUE TITLE
Add catch to promise objects

### ISSUE THREAD

**Issue by tracker1** [jquery/jquery#2102]
This relates to #1722 but a far simpler request...  given that the `.then` method matches the Promise spec (with the extra progress parameter), it would be nice that there be a compatible `.catch` method... (per @dmethvin) this could call and return `.then(null,fn)` as a passthrough.

**Comment by dmethvin** [comment]
I can see us creating `.catch(fn)` as an alias for `.then(null, fn)`. That is different than `.done(fn)` though because the latter adds a new handler to the existing Deferred.

**Comment by tracker1** [comment]
of course, this would need to be done with `['catch']` so as not to trigger reserved word treatment in older browsers.

**Comment by dcherman** [comment]
Giant +1 on this.  Since these Promises aren't based on a prototype, it's much easier for this to be supported internally rather than having to do something like wrap the constructor and decorate the returned promise.

**Comment by gibson042** [comment]
I updated the title for accuracy. Suggested implementation:

```js
"catch": function( fn ) {
	return promise.then( null, fn );
}
```

**Comment by markelog** [comment]
Sounds like a blocker to me
