### ISSUE TITLE
Add an $.Promise constructor function.

### ISSUE THREAD

**Issue by tracker1** [jquery/jquery#2103]
I would like to suggest adding a `$.Promise(handler)` constructor function to jQuery that works similar to the spec, in that it will return a `window.Promise` if such a function exists, or create a jquery deferred if it does not.

```js
$.Promise = function Promise(handler) {
  if (typeof w.Promise === "function") return new w.Promise(handler);
  var ret = $.Deferred();
  handler(ret.resolve, ret.reject, ret.notify);
  return ret;
}
```

This combined with the suggestion in #2102 will offer a decent compatibility layer with native Promises at least in terms of use.

**Comment by mzgol** [comment]
I'd be careful with that. Us exposing our shim of browser built-ins freezes makes it that much harder to remove it later if we want. People will also expect from us fixes making `jQuery.Promise` as close to native `Promise` as possible.

IMO it would make sense mostly if we wanted people to be able to provide their own `Promise` implementations by assigning to `jQuery.Promise`. I'm not sure how useful that would be.

**Comment by timmywil** [comment]
Given that jQuery promises can be wrapped by other promise libraries, and that jQuery Deferreds now consume standard thenables, there isn't as much of a need for this. Also, we're concerned about opening up the possibility of replacing our internal use of promises with any Promise implementation. It would add to the list of things we'd need to support. The cost vs benefit ratio just doesn't seem to be high enough.

**Comment by nyurik** [comment]
I think supporting standard `Promise(executor(resolve,reject))` pattern would be highly useful to the community, as it will allow developers to consistently use Promises regardless of the provider. It will encourage good coding practices.
