### ISSUE TITLE
Possible browser compatibility regressions

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#2104]
Due to impending purging of TestSwarm data (while we migrate the app to a new server), here's data about possible regressions found in the last 7 days.

I've let these failures re-run to filter out false negatives. Here's what's left:

### jQuery
![screen shot 2015-02-20 at 02 16 15](https://cloud.githubusercontent.com/assets/156867/6280517/78630868-b8a6-11e4-837e-09a5932c250d.png)
* IE8 started failing between 7cd9a36322 and 2380028ec4<br>&raquo; 255 test failures in effects module. All other modules passed.
* IE10 and IE11 started failing between 2380028ec4 and 9368a8cd8c <br>&raquo; 1 test failure in dimensions module. All other modules passed.

### jQuery Weekly
![screen shot](https://cloud.githubusercontent.com/assets/156867/6280307/c53c8546-b8a2-11e4-84d9-9bab65eaf82d.png)
* Android 4.3 started failing between 8b6aeae52d and f2ea60cfe8.<br>&raquo; the traversing module timed out repeatedly. All other modules passed.

**Comment by markelog** [comment]
Will check them out

**Comment by timmywil** [comment]
This issue is no longer necessary. We've had several runs since and should be keeping our eyes on swarm failures at all times. I'll keep a reminder in the meeting minutes and won't release until we've got all green. Thanks!
