### ISSUE TITLE
map vs each

### ISSUE THREAD

**Issue by CTAPbIuMABP** [jquery/jquery#2105]
in js [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
) and [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) has similar signatures

```js
[].map(callback(index, currentValue, array), thisArg)
[].forEach(callback(index, currentValue, array), thisArg)
```

but in jquery [map](http://api.jquery.com/jquery.map/) and [each](http://api.jquery.com/jquery.each/) has different

```js
$.map([], callback(elementOfArray, indexInArray))
$.each([], callback(indexInArray, value))
```

this leads to tons of stupid mistakes

i understand its kinda breaking change but you are going to release jquery 3 and its a good time to do breaking changes

**Comment by mattlunn** [comment]
To make it more confusing:

    jQuery.map(obj, callback(currentValue, index))
    jQuery.fn.map(obj, callback(index, currentValue))

;)!

**Comment by dmethvin** [comment]
I agree that, given a time machine, this is one of the first things I would do after I killed Hitler. By the time someone noticed these inconsistencies and suggested a fix back in 2007, it was decided that, *even back then*, it would break too much code.

Today, the ratio of jQuery `.each()` to native `Array.forEach()` on the web is probably hundreds to one. It doesn't make sense to create a backcompat nightmare to match the semantics of a different method used on different types of objects. 

If you want the exact arguments as the `Array.forEach()` method in jQuery, you can create a little plugin to implement it. That also means you haven't broken existing code that continues to use `.each()`, so you get to have it both ways.

**Comment by CTAPbIuMABP** [comment]
Dont touch Hitler, nobody knows how it could be without him. 

But here and now you can fix this, or spend next few years regreting about missing this opportunity, untill you have another chance to fix this in jquery4

**Comment by scottgonzalez** [comment]
"Fixing" this will be the regrettable action. `$.fn.forEach = [].forEach;` or equivalent is the way to solve this for those that want it.
