### ISSUE TITLE
Unexpected token: eof

### ISSUE THREAD

**Issue by sescobb27** [jquery/jquery#2106]
I'm trying to compress my assets with rails rake task `bundle exec rake assets:precompile` but there is an error in this file
https://github.com/jquery/jquery/blob/master/src/intro.js
Unexpected token: eof (undefined) (line: 46, col: 0, pos: 1394)

**Comment by timmywil** [comment]
The intro and outro files are syntactically incorrect, but this is purposeful for our build. They are each half of a wrapper around the built source and not standalone modules. I'm not sure what the assets task is doing, but I suspect it's attempting to concactenate all files in the src folder. If you're looking to build jquery yourself, there are custom build instructions in the README.
