### ISSUE TITLE
We should add new functionality

### ISSUE THREAD

**Issue by Mohance-k** [jquery/jquery#2107]
I had felt many time toggle the Boolean values and I wrote separate function on each time. My code is given below and we could called the function name is " toggleBoolean( state ) " . So could you add this new functionality ? I hope It'll help us

function toggleBoolean( state ) {
	var BooleanFormat = '{"0":"1","true":"false","yes":"no","1":"0","false":"true","no":"yes"}';
	var obj = JSON.parse(BooleanFormat);
	return obj[state.toLowerCase()];
}

**Comment by timmywil** [comment]
These kinds of utilities only make it into jQuery if they're used internally. Plugins, utility libraries, and your own code are the best ways to cover this use case.
