### ISSUE TITLE
~2.1 .css() converts percents to pixels

### ISSUE THREAD

**Issue by terion-name** [jquery/jquery#2110]
In JQ 2.13 this code:
```
$('#my_elem').css({marginLeft: '1%'})
```
Sets CSS property in pixels (e.g. 14px). In 2.1.0 it works correct.

And this:
```
$('#my_elem').css({marginLeft: '+=100%'})
```
Will add 100px, not percent (in both 2.1.3 and 2.1.0)

`.animate()` works correct in both versions

**Comment by gibson042** [comment]
The second issue will be resolved when #2011 lands, and the first appears to be working as expected: http://jsfiddle.net/r1Lva0yp/

If you can, please post a link and we'll reopen this.
