### ISSUE TITLE
.data incorrect work

### ISSUE THREAD

**Issue by PilgrimAlex** [jquery/jquery#2112]
I use jQuery v2.1.3
Chrome and FF

 div id="myDiv"
.....
$('#myDiv').data('zz', 1);
$('#myDiv').data('zz'); //return 1
$('div[data-zz=1]'); //return empty set
.......
$('#myDiv').attr('data-zz', 1);
$('#myDiv').attr('data-zz'); //return 1
$('div[data-zz=1]'); //return div
$('#myDiv').data('zz', 2);
$('div[data-zz=2]'); //return empty set

**Comment by mzgol** [comment]
From http://api.jquery.com/data/#data-html5:
"The data- attributes are pulled in the first time the data property is accessed and then are no longer accessed or mutated (all data values are then stored internally in jQuery)."

If you need to modify attributes, please use `.attr`.
