### ISSUE TITLE
Allow offset setter to throw when input is disconnected

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#2114]
Fallout from #2043: https://github.com/jquery/jquery/pull/2043#discussion_r25352005

Remove the [`|| { top: 0, left: 0 }`](https://github.com/NekR/jquery/commit/d0df2c6bcf5709bb0cdaf4dd547e88a2ec2f6381#diff-d38379d70ee2c5c5a0acb5b0f7acef8dL35) that was added to let `$disconnected.offset({ top: y, left: x })` continue proxying `.css({ top: y, left: x })`, along with any associated tests asserting the behavior.

**Comment by timmywil** [comment]
Just as a checkmark, this is already in the blog post.
