### ISSUE TITLE
Remove ownerDocument check in offset getter

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#2115]
Fallout from #2043: https://github.com/jquery/jquery/pull/2043/files#r23981494

Since all supported browsers have `getBoundingClientRect`, there's no reason not to just call the method right away, letting an exception throw if input is in fact not a DOM element.

The "object without getBoundingClientRect" test will have to go as well.

**Comment by dmethvin** [comment]
According to [#12536](http://bugs.jquery.com/ticket/12536) we had that guard in for browsers we no longer support, so that sounds good to me.

**Comment by mzgol** [comment]
Yes, we already have a couple of places where we stopped guarding against browsers with missing `getBoundingClientRect` so this one should go as well.
