### ISSUE TITLE
Add new closest relative selector

### ISSUE THREAD

**Issue by stiff** [jquery/jquery#2117]
I find myself quite often traversing dom like `$el.closest('.foo').find('.bar')`, and always thought it would be nice to have it in one string like `$el.find('..(.foo) .bar')` .

The main reason to have this in one string is to make it easier to navigate elements in reusable components with parameters passed via `data-` attributes. For example, here: https://github.com/nathanvda/cocoon#link_to_add_association it has quite a few options like `data-association-insertion-traversal` which are very long and somewhat confusing at first use.

I investigated source a little and it seems easy to add relative combinator `..` (or `^`?), but requires source modification because  `rcombinators` in Sizzle is inaccessible from outside.

If this idea have any chances to get merged I think could send a PR.

**Comment by timmywil** [comment]
Thank you for opening an issue, but we will not be adding any additional selector extensions to the core.
