### ISSUE TITLE
Return null from .attr when attributes don't exist

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#2118]
`.attr("nonexistent")` currently returns `undefined`, [probably](https://github.com/jquery/api.jquery.com/issues/523#issuecomment-49600962) from the days before `.prop`. But the native DOM `getAttribute` and `Sizzle.attr` both return `null` in such cases. Also, `.attr( name, null )` _removes_ attributes, and it would be very convenient to allow [universal round-tripping](https://github.com/jquery/api.jquery.com/issues/523#issuecomment-49554408).

Let's consider changing the return value to accommodate.

Note that _setter_ treatment of `undefined` is explicitly out-of-scope for this ticket, as are `.prop` and `.data` round-tripping, although those are certainly related topics.

**Comment by timmywil** [comment]
@dmethvin We're leaning towards doing this for beta. Do you know of a use case that would make this catastrophic?

**Comment by dmethvin** [comment]
It seems like returning `null` is a good idea, although who knows what it will break in the wild. The only way to find out is to change it! We should continue to return `undefined` for empty jQuery collections tho.

**Comment by gibson042** [comment]
> We should continue to return undefined for empty jQuery collections tho.

Thanks; that reminded me to create #2134.

**Comment by scottgonzalez** [comment]
> It seems like returning null is a good idea, although who knows what it will break in the wild.

Of course the answer turns out to be jQuery UI :-)

I'm working on updates right now.

**Comment by timmywil** [comment]
The team decided to revert this due to breakages in UI and mobile.

**Comment by dmethvin** [comment]
We backed this out for 1.12/2.2 which definitely seems right, but it's also excluded from 3.0. Should it be? That is, do we want a non-existent attribute to return `null` as proposed here? If not I want to remove the milestone and tag.

**Comment by mgol** [comment]
I removed the milestone due to the revert and opened the issue & added the "Needs review" label to account for the Dave's question.

**Comment by markelog** [comment]
> We backed this out for 1.12/2.2 which definitely seems right, but it's also excluded from 3.0. Should it be? 

I remember this discussion, we reverted cause it might be dangerous to do which proved the UI breakage, where is literally no gain from, except to align with standard, whereas behaviour in DOM spec is very questionable in the first place, since in all others API you get `undefined` value not `null` value
