### ISSUE TITLE
when jQuery encounters non-printable characters

### ISSUE THREAD

**Issue by JJia-OOOO** [jquery/jquery#2120]
```
    >> var str = "<div data-xx='{\"foo\":\"bar\"}'></div>";
    >> $(str).data("xx")
```

give me an object, and

```
    >> var str = "<div data-xx='{\"\foo\":\"\bar\"}'></div>";
    >> $(str).data("xx")
```

give me a string.
is it a normal result? or is it a bug of jQuery?

**Comment by timmywil** [comment]
Thank you for opening an issue. I agree that [according to our docs](http://api.jquery.com/data/#data2) this should work, but this is a very rare edge case and may not be worth the fix. What use case brought about discovering this behavior?

I created a test case [here](http://jsbin.com/kaluro/1/edit?js,console).

**Comment by dmethvin** [comment]
The second isn't valid json, the formfeed \f isn't allowed.  If you want to escape It you have to double up the backslashes.

**Comment by timmywil** [comment]
Duh, I was thinking it was already escaped. Dave is right. I shouldn't think things before 5am.

**Comment by JJia-OOOO** [comment]
i encounters this problem when i processes file paths of windows. i just want to make sure that this is a normal behaviour or not.
i understanded.
thank you very much!
