### ISSUE TITLE
.data(string) returning uncommon types like string

### ISSUE THREAD

**Issue by rentalhost** [jquery/jquery#2122]
If data attribute is set as a "uncommon data type", it is recognized as string, instead of correct type.

**For instance:**

    <div data-value="1.50"></div>

Will returns like "string" instead of "number" (float):

    jQuery.type(div.data("value")) === "string";

**[High Priority] It occur with float types:**

0. Float with zero on right side (1.50, -1.50...);
0. Float without integer (.5, -.5...);
0. Float without decimal (1., -1.);

In this cases, the more relevant is the first. `1.5` is converted to number, but `1.50` is not. Suggestion: use parseFloat() if detect a number like it.

**[Low Priority] Too occur with others numbers type:**

0. Exponential values (2e4, 2E4, 2e-4, -2e4...);
0. Hexadecimal values (0x10, -0x10);
0. Binary values (0b10, -0b10);
0. Octal values (0777, -0777);

Suggestion: use parseInt() for hexadecimal pattern (`0[xX]`). 
Others I don't know.

**[Low Priority] And undefined value type:**

0. Undefined value (undefined);

This last case seems Ok, for me, But I'm putting here to be avail with you. 
Suggestion: if attribute value is "undefined" returns `jQuery.undefined`.

**Test Case**

http://jsfiddle.net/o69j1t5b/3/

**Comment by rentalhost** [comment]
**For the float case:**

https://github.com/jquery/jquery/blob/master/src/data.js#L35

    parseFloat(data) === +data ? +data : ...

**Comment by rentalhost** [comment]
Seems like `Number(data)` is better. It fix almost everything, except to negative values (`-0x10`, `-0b10`) and octal.

**Comment by gibson042** [comment]
This behavior is [intentional](http://api.jquery.com/data/#data-html5):
> A value is only converted to a number if doing so doesn't change the value's representation. For example, "1E02" and "100.000" are equivalent as numbers (numeric value 100) but converting them would alter their representation so they are left as strings. The string value "100" is converted to the number 100.

See http://bugs.jquery.com/ticket/7579 for an explanation of why it was introduced. jQuery cannot infer intent from an opaque sequence of characters, but feel free to numeric-cast values yourself when you know that such an operation makes sense.

**Comment by rentalhost** [comment]
It make sense for me now, when we work with number with "separator". For instance, `100.000` can, on really, represents `100000` (integer) and not `100` (as float). Really it unfeasible a new behavior. And following logic, it can also affect the hexadecimal. The developer can expect the hexadecimal literally (`string "0x10"`), not their numerical conversion (`int 16`).

**Comment by rwaldron** [comment]
> it can also affect the hexadecimal.

But there is now way to disambiguate developer's intent—so it's safer to just assume that all values serialized to strings, should indeed be treated as strings. Let the developer be explicit. 

```html
<div data-value="1.50"></div>
```

FWIW, the HTML spec for `data-*` properties pretty clearly states that the value is always coerced to a string: http://www.w3.org/TR/html5/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes

> The dataset IDL attribute provides convenient accessors for all the data-* attributes on an element. On getting, the dataset IDL attribute must return a DOMStringMap object

And the relevant part of DOMStringMap: 


> To set the value of a new or existing named property name to value value, the algorithm for setting names to certain values must be run, passing name as the name and the result of converting value to a DOMString as the value.


To illustrate: 

```js
var div = document.createElement("div");
div.innerHTML = "<span data-bond='007'>007</span>";
console.log(div.childNodes[0].dataset.bond); // "007"
console.log(typeof div.childNodes[0].dataset.bond); // "string"
```

How would jQuery know what to do with that value? Is it the string "007"? Is it a legacy octal literal? If jQuery always returns it as a string, then the developer can do whatever they want with it.
