### ISSUE TITLE
trigger Event called native DOM event called twice

### ISSUE THREAD

**Issue by andycall** [jquery/jquery#2123]
Native DOM event with on prefix can be called twice when the trigger function is being called.

https://jsfiddle.net/h131rmck/

**Comment by dmethvin** [comment]
See [Trac #10168 ](http://bugs.jquery.com/ticket/10168) for background on this problem. The suggested fix in #2124 just trades one bug for another as far as I can tell, but a good set of unit test additions would confirm that.

**Comment by dmethvin** [comment]
Per the Trac bug, I think we should leave this a wontfix.
