### ISSUE TITLE
html() function does not return correct xhtml for legacy created html strings

### ISSUE THREAD

**Issue by deep42Thought** [jquery/jquery#2131]
According to my understanding of the HTML5 spec the disabled option being set is 'disabled="disabled"'

In old HTML and also as produced by some browsers direct innerHTML, and also anything that may be retrieved having been stored in a database or old email you can acquire strings like '<DIV><INPUT DISABLED></DIV>' capitalised and no value for the disabled attribute.

var htmlString = "<DIV><INPUT DISABLED></DIV>"

this was perfectly legitimate in old HTML

If you put this direct into jquery you get an old school solution - the input tag is not closed and the disabled attribute has the incorrect value "" rather than disabled

$(htmlString ).html() 
<input disabled="">

So for proper xhtml you need a / at the end of the input element and the value disabled in the disabled attribute.  

My own html cleaner can sort this
ydrDynamicLoad.load("cleanser").xhtml(htmlString).text
<div><input disabled="disabled"/></div>

In order to do this the cleanser has a small xml database of html tags and whether or not they are supposed to be contentless and loads of rules about how to clean up bad html.

**Comment by deep42Thought** [comment]
Fell foul of your weird formatting rules I guess - the htmlString was originally

<DIV><INPUT DISABLED></div>

**Comment by deep42Thought** [comment]
still didnt save it so try again using Server.HTMLEncode

htmlString was  &lt;DIV&gt;&lt;INPUT DISABLED&gt;&lt;/DIV&gt;

$(htmlString ).html()  was   &lt;input disabled=&quot;&quot;&gt;

cleanser string - ie as it should be was &lt;input disabled=&quot;disabled&quot;/&gt;

**Comment by deep42Thought** [comment]
so server HTML encoded strings get un-encoded and put back to their original - i'll try and remember that

**Comment by gibson042** [comment]
We're just preserving native browser behavior here: http://jsfiddle.net/cgasn63v/

What are you expecting?

**Comment by deep42Thought** [comment]
Hi thanks for the quick reply

 

W3C defines that the correct rendering of html for what once, years ago, were
valueless attributes should now have the attribute name as the value.  I.E.
disabled on its own is now deprecated.  Now $.html() is recognising that old
form and converting it to new but not to W3C standards

 

When you code a page under W3C HTML5 you are supposed to write
disabled="disabled"

 

The old code therefore indicates that the element is set to disabled, but the
.html() effectives has the opposite setting.

 

Also W3C states that tags that do not have content, e.g. INPUT, IMG, META etc,
should be contentless elements. Ie <META  . /> <INPUT .. /> and not just stand
alone tags

 

W3C expects properly formatted HTML to be readable in an XML parser, and what
comes out of .html() is not

 

I can see that $.html() returns native innerHTML but I was looking for jquery to
hide browser differences 

 

So I am looking for jquery to protect me from native browser variations and
return the W3C standard syntax.  I need standard W3C compliant as it is
transferred to the server and resent to other users.  So for predictable results
on the other machine I need the HTML rendered in exactly the same way for a
given ser of user key depressions regardless of browser.  It is also sent as
HTML email and if you have any nonstandard rendering in the email it generally
gets bounced by some ISP or another.

 

Real problem is not so much with own code generating HTML - it is strictly well
behaved and all HTML I issue from the server is strictly XML compliant.  But the
problem is with that which is created locally in e.g. a textarea that has
contentEditable and the app uses or allows the user to trigger execCommand()
(from native htmlclient javascript) to edit a document.  Execcommand can allow
paste from external applications, e.g. MS Word and so basically anything can
turn up.  That is the stuff that is a problem.

 

----

 

I deal with all that junk clean out the supplier dross that bloats copy and
paste but the client side app uses xml services which have been totally screwed
by Microsoft recently on Internet Explorer - until recent IE changes I could do
the job on any browser but it is a pain having to deal with Microsoft changes
all the time

 

Regards

 

 

 

 

 

 

 

Dr. Martin W. Baker

York Development and Research Limited

 <mailto:MartinWBaker@yorkdevres.co.uk> MartinWBaker@yorkdevres.co.uk
tel: + 44 (0) 1737 218044
mob: + 44 (0) 7986 297498
Skype: martinwbaker  <skype:martinwbaker?call> My status

 

 

****************************

Registered in England: no 1975973

Registered Office: North House, 198 High Street, Tonbridge, Kent, TN9 1DH

 

This email and any attachments are confidential and intended for the
addressee(s) only.  If you are not the named recipient, you should not use,
disclose, reproduce, copy or distribute the contents of this communication.  If
you have received this in error, please contact the sender and then delete this
email from your system.

 

****************************

 

  _____

**Comment by dmethvin** [comment]
> When you code a page under W3C HTML5 you are supposed to write
disabled="disabled"

Can you quote a spec for that? [The spec](http://www.w3.org/TR/html5/infrastructure.html#boolean-attribute) seems to contradict you.

**Comment by gibson042** [comment]
It sounds like you want to deal with XHTML, which—unlike HTML5—is guaranteed to be valid XML. As their names indicate, neither the native `innerHTML` property nor jQuery's `html` method make such guarantees.

I recommend using some code specific to this problem—a quick search on my part turned up [http://www.stevetucker.co.uk/page-innerxhtml.php](http://www.stevetucker.co.uk/page-innerxhtml.php), which seems to do exactly what you want.

At any rate, this is out of scope for existing jQuery methods.

**Comment by deep42Thought** [comment]
Richard

 

Wow your feed back is both so quick and so helpful

 

I am sorry that I did not land across this in my own research

 

Thanks so much I really appreciate your help.

 

-------------

 

I am new to query - only two weeks old.  Even in this time I am most impressed
at what you guys have achieved and the architectural elegance of the solution

 

Kind regards

 

Martin

 

 

 

Dr. Martin W. Baker

York Development and Research Limited

 <mailto:MartinWBaker@yorkdevres.co.uk> MartinWBaker@yorkdevres.co.uk
tel: + 44 (0) 1737 218044
mob: + 44 (0) 7986 297498
Skype: martinwbaker  <skype:martinwbaker?call> My status

 

 

****************************

Registered in England: no 1975973

Registered Office: North House, 198 High Street, Tonbridge, Kent, TN9 1DH

 

This email and any attachments are confidential and intended for the
addressee(s) only.  If you are not the named recipient, you should not use,
disclose, reproduce, copy or distribute the contents of this communication.  If
you have received this in error, please contact the sender and then delete this
email from your system.

 

****************************

 

  _____

**Comment by deep42Thought** [comment]
What you say is exactly correct and that is what all my own code does.  

 

You can get junk in your document e.g. by end user paste into a contentEditable
textarea element under javascript execcommand from another application native to
the machine on which the user is running.  

 

That it where the junk comes from and that is what needs cleaning up.  So I want
to get rubbish inhertited from outside my application up to W3C HTML5.

 

 

 

 

 

Dr. Martin W. Baker

York Development and Research Limited

 <mailto:MartinWBaker@yorkdevres.co.uk> MartinWBaker@yorkdevres.co.uk
tel: + 44 (0) 1737 218044
mob: + 44 (0) 7986 297498
Skype: martinwbaker  <skype:martinwbaker?call> My status

 

 

****************************

Registered in England: no 1975973

Registered Office: North House, 198 High Street, Tonbridge, Kent, TN9 1DH

 

This email and any attachments are confidential and intended for the
addressee(s) only.  If you are not the named recipient, you should not use,
disclose, reproduce, copy or distribute the contents of this communication.  If
you have received this in error, please contact the sender and then delete this
email from your system.

 

****************************

 

  _____
