### ISSUE TITLE
Synchronize use of document globals

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#2133]
Changes from 76df9e4e389d80bff410a9e5f08b848de1d21a2f (in particular, definition and use of the `document` and `documentElement` variables) never made it to the compat branch, introducing what I feel to be a needless divergence and source of merge conflicts.

@mzgol: agree?

**Comment by mzgol** [comment]
I mostly didn't backport it because this is only required for non-browser environments which we don't support in the compat line. But I have nothing against porting them if that makes cherry-picking easier.

Note, though, that on `compat` we have a different jsHint config that assumes the browser environment; the one on `master` only declares `window` & timer functions.

**Comment by mzgol** [comment]
I'll create a `document` variable as part of #2501 but `documentElement` doesn't seem worth it - on `master` it's mostly used in `selector-native` which is not supported on `compat` & support tests which use `document.body`, not `document.documentElement` on `compat`.

**Comment by mzgol** [comment]
> support tests which use `document.body`, not `document.documentElement` on `compat`.

BTW, it's worth checking if https://github.com/jquery/jquery/pull/1342#issuecomment-23911836 still applies or maybe we could switch from `body` to `documentElement` for support tests even on `compat`.

**Comment by mzgol** [comment]
It seems we can switch from `body` to `documentElement` on `compat`, support tests work fine in IE8 before doc ready. :) PR coming.

**Comment by mzgol** [comment]
PR: #2504.

**Comment by markelog** [comment]
Landed via https://github.com/jquery/jquery/commit/04ec688e806660107a0b5823fabe2fe213f63b92

**Comment by mzgol** [comment]
I'd rather not backport it to 1.12 as there is way more compat code there and it may pose problems for Node.js.

**Comment by mzgol** [comment]
This is a wontfix now since it was done in connection with https://github.com/jquery/jquery/issues/2501.

**Comment by markelog** [comment]
Since 1.12 will be released, i will remove `wontfix` label

**Comment by mzgol** [comment]
Last time I tried it it caused problems for IE<8. I'd rather it stayed wontfix unless we can verify IE 6-7 don't have problems with it.
