### ISSUE TITLE
$.post and $.get ignore type if no callback is provided

### ISSUE THREAD

**Issue by sanderkruger** [jquery/jquery#2135]
According to the documentation, all arguments to post and get aliases of the ajax function are optional. However, if you provide no callback, the type will be ignored. For example:
$.post('myserver.com/test.php', data, 'json').done(function(json) {});

In the code that defines the get and post functions, arguments get shifted *if* the second argument is a function. But not in any other case (such as if the third argument is a string).

**Comment by dmethvin** [comment]
I'm not a big fan of further parameter hockey here. Leaving out the callback is a pretty rare case and you can always use `$.noop` as a placeholder. As of jQuery 3.0 the signature [accepts an options arg](https://github.com/jquery/jquery/issues/1986) just like `$.ajax` and you can specify outlier cases to your heart's delight there. 

If everyone agrees it seems to make the most sense to clarify the docs.

**Comment by timmywil** [comment]
Agreed this is a docs issue.

**Comment by arthurvr** [comment]
I think we already have a docs issue. Isn't this the same as https://github.com/jquery/api.jquery.com/issues/351?

**Comment by timmywil** [comment]
Yup! Thanks @arthurvr
