### ISSUE TITLE
Trailing Ampersand causes Uncaught Error: Syntax error

### ISSUE THREAD

**Issue by DanWithams** [jquery/jquery#2136]
Issue: jQuery encounters a Syntax error on first load and fails to complete initialisation. (jQuery version 2.1.3)

How to reproduce;

1) Create a HTML page including jQuery 2.1.3 using a standard scrip> tag.
2) Request a URL with a trailing ampersand (e.g. www.example.com/?myVar=1& )
3) Check developer console for the following error message;

"Uncaught Error: Syntax error, unrecognized expression: &-tab". (Chrome)

Test in:

Chrome, Safari, Firefox.

Understandably, trailing ampersands are not useful in the slightest and your web application should be build to manage query parameters neatly, however jQuery probably shouldn't completely fall over because of this.

**Comment by gibson042** [comment]
Can you provide a demonstration? It seems to be working for me: http://jsfiddle.net/s2kqg1g9/

**Comment by DanWithams** [comment]
After additional testing and I am unable to reproduce the issue. I believe it may be related to AngularJS and route handling (specifically Angular UI state provider).

Closing bug report.
