### ISSUE TITLE
$.parse('') got an error in chrome , error message:"Uncaught SyntaxError: Unexpected end of input"

### ISSUE THREAD

**Issue by xcchcaptain** [jquery/jquery#2137]
in firefox got error "SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data" 
i know if the string has no charactor ,jquery has know idea which type to parse
but the error msg should be more descriptive and clear;
thanks

jquery version:jquery.1.11.1.min.js
chrome versioin:39.0.2171.95 m
firefox version:34.0.5
----------------------------------------------------
go beyond oneself,make perfection more perfect

**Comment by timmywil** [comment]
Thank you for opening an issue, but the error is being thrown by the browser – not by jQuery.

**Comment by xcchcaptain** [comment]
at chrome and firefox ,json parse used the native api of browser?
