### ISSUE TITLE
replaceWith doesn't work with latest Firefox

### ISSUE THREAD

**Issue by oliverhuynh** [jquery/jquery#2146]
I'm facing an issue that replaceWith method doesn't work properly in Firefox(latest 36.0.1). It removes src attribute out of img tag. This doesn't happen on Chrome. I inspected the element and found out that src is eliminated. I used safe mode of Firefox and tested on two machines.
Please check out this jsfiddle https://jsfiddle.net/6vgdLc27/4/ on latest Firefox and other browsers to compare.

**Comment by Macsch15** [comment]
Works fine for me.
![2015-03-16 14-54-37](https://cloud.githubusercontent.com/assets/1592053/6667467/78458550-cbec-11e4-8cab-bbfad278f29c.png)

**Comment by oliverhuynh** [comment]
Thanks mate. This is the screenshot of my safe browsing without addon. If you look at the source, the src attribute is missing.
![image](https://cloud.githubusercontent.com/assets/6909475/6668076/84f2a900-cbf0-11e4-9cf6-8d0b1b5f647b.png)

**Comment by dmethvin** [comment]
Working for me as well. Are you getting any errors on your console, for example about mixed content?

**Comment by oliverhuynh** [comment]
No, not an error or warning. As you see there is nothing to do with my network or code since I can open it normally via Chrome. My console looks like below
![image](https://cloud.githubusercontent.com/assets/6909475/6714177/22249d76-cd97-11e4-9e6f-b50e072842d2.png)

**Comment by dmethvin** [comment]
I don't know what to say, it's working fine for me. Whatever the problem is, it doesn't seem to be jQuery. 
![image](https://cloud.githubusercontent.com/assets/157858/6714353/301d854c-cd6e-11e4-8b9a-733f8d42f8a9.png)

**Comment by mzgol** [comment]
@oliverhuynh Please try on a fresh profile. It's possible some extension is messing with the code which would then be beyond our scope to fix.

**Comment by dmethvin** [comment]
BTW @oliverhuynh you say you have no plugins but it's clear Firebug is installed. That can often cause problems.

**Comment by mzgol** [comment]
> BTW @oliverhuynh you say you have no plugins but it's clear Firebug is installed.

Well, plugins !== extensions. Maybe he doesn't have any plugins installed. ;)

**Comment by Macsch15** [comment]
> BTW @oliverhuynh you say you have no plugins but it's clear Firebug is installed.

I think it is default firefox dom inspector.
I am wrong?

**Comment by mzgol** [comment]
> I think it is default firefox dom inspector. I am wrong?

It's not, look at the title of the window, the minimize/maximize/close buttons are also Firebug-specific.

You can see from the browser bar that @oliverhuynh has a lot of extensions installed, we need to see results with them all disabled.

**Comment by Macsch15** [comment]
Oh, I haven't seen this second screenshot before.

**Comment by oliverhuynh** [comment]
Hi guys, the last screenshot is when I run in normal mode to have a quick test. It has plugins/extensions. The issue is able to reproduce in any computer in my place. And I did the test in safe mode Firefox. That is what it is the first screenshot.

**Comment by oliverhuynh** [comment]
Nothing is related to plugins/extensions. The strange things are, other methods can work well. Should I look directly to the implementatian code of replacewith and investigate what the issue is?

**Comment by dmethvin** [comment]
Since nobody else can reproduce the problem, you will need to diagnose it further on your system.
