### ISSUE TITLE
$.siblings() of a set with length > 1 includes original members

### ISSUE THREAD

**Issue by Boldewyn** [jquery/jquery#2149]
See this [JSFiddle](http://jsfiddle.net/boldewyn/z9pgLvu9/). Consider a series of `<b>` elements, and a jQuery object, that contains _some_ of them:

    var $b = $('b:even');

The [documentation](http://api.jquery.com/siblings/) on `$.siblings()` says:

> The original element is not included among the siblings, which is important to remember when we wish to find all elements at a particular level of the DOM tree.

So the assumption is, that in this case `$b.siblings() == $('b:odd')`. However, jQuery does not test for each sibling, if it is contained in the original set, so we get:

    $b.siblings() == $('b');

Personally, I consider this a bug of the implementation of `$.siblings()`, but if it is intended behavior, at least the docs need to reflect this.

**Comment by scottgonzalez** [comment]
This is the union of all siblings of all elements in the collection. If there were only one `<b>` element per level of the DOM tree, then you'd get what you expect.  All jQuery methods work this way.

**Comment by Boldewyn** [comment]
Yes, fair enough. But then, it still would do no harm, if it were mentioned in the docs. The surprising case `$('b:even').siblings() != $('b:odd') for $('b').length > 2` should be worth a short notice.
