### ISSUE TITLE
jQuery 2.x (3.0) still support IE 6, 7 and 8

### ISSUE THREAD

**Issue by marcorra** [jquery/jquery#2150]
Hi

I noticed something strange. If you open up the source code for latest build for jQuery 2.x  (3.0) and search for **IE8**. A lot of hits.

See Line 1007. 

 Quote: " // Support: IE<8 "

Even compat branch are no longer support IE6 and 7 ?

Anyway. This is not correct with it's stated in the docs that the jQuery 2.x branch are not supporting older IE then 9.

**Comment by mzgol** [comment]
These comments come from [Sizzle](https://github.com/jquery/sizzle) which is the selector engine used by jQuery. Sizzle, as opposed to jQuery, has only one version and supports more browsers than jQuery itself: https://github.com/jquery/sizzle/wiki#browsers

Note that there's a plan to reduce that to browsers supported by jQuery Compat (current jQuery 1.x) i.e. IE8+, see https://github.com/jquery/sizzle/issues/294. This will happen in time for jQuery 3.0, the next version.

That will still mean even in jQuery version that doesn't support IE8 you'll still see some code that doesn't make sense for other browsers. Getting rid of that would require Sizzle to have two versions, though which is always a pain to maintain and gains wouldn't be large enough; there are not enough IE8-only workarounds in Sizzle to warrant a separete version.

Thanks for looking at our code and filing the bug, thought!

**Comment by marcorra** [comment]
@mzgol  Not all of this comments come from Sizzle.

Line 7466 - valHooks -  " // IE8-9 doesn't update selected after form reset (#2551) "

Line 8104 and line 8108  - ajax module - "// Support: IE8-11+ "

are a few examples from the jQuery Core

**Comment by mzgol** [comment]
> Line 7466 - valHooks - " // IE8-9 doesn't update selected after form reset (#2551) "
> 
> Line 8104 and line 8108 - ajax module - "// Support: IE8-11+ "

As you can se in the comments, both of these are needed for IE9 which we support. We don't delete info about older browsers if the code is still needed anyway.

**Comment by dmethvin** [comment]
All of those comments cover a browser that master supports though.
