### ISSUE TITLE
outerHtml

### ISSUE THREAD

**Issue by weitzhandler** [jquery/jquery#2151]
Please implement this function already, it's so compelling!

**Comment by dmethvin** [comment]
Doesn't `.replaceWith()` do what you want? If not, why?

**Comment by weitzhandler** [comment]
`replaceWith` is write-only. I'm looking for a read property.
Better said, a less verbose version of:

    $(this).prop('outerHTML');

**Comment by timmywil** [comment]
This idea was rejected 4 years ago. A lot can change in 4 years, but I'll just quote some of the pertinent comments from http://bugs.jquery.com/ticket/8142.

> So while it seems that people expect this, I tend to agree with jitter - the potential for abuse is simply enormous. So many people don't understand the concept of a DOM Element and think that they have to have the HTML to inject an element some place else. If we add outerHTML we're going to see a ton of stuff like: `$("ul").append( $("#thing").outerHTML() );`

– John Resig

> This is a classic example of "isn't it just as simple as..."? Theoretically, yes. However, jQuery is a public API. When new methods are released, that is a specific endorsement of an idea, and along with that comes support. Support means tests, tests mean bugs, bugs mean edge cases, edge cases mean hours of debug. It's never as simple as it seems.

> Also, the criticism that the reasons against implementing amount to "well if some idiot does something idiotic then he's going to get some idiotic results" is unfair. Here is a summary of the reasons given, plus one of my own:

> - easy to implement as a plugin
> - hazy interactions with tables (which is exactly what a few people are trying to use this for).
> - similar well-tested API methods do almost the exact same thing
> - how does this method handle data or events associated with the element being replaced?

– Mike Sherov

> Right on @mikesherov. This is easy to do if we ignore consistency and the details. And if we do that, there will definitely be plenty of tickets arriving here in the tracker to tell us how .outerHTML() is broken for their case.

> If the simple implementation above suits *your* needs, there is no problem at all with you using it.

– Dave Methvin

**Comment by timmywil** [comment]
By the way, the implementation has changed in the years since as all of our currently supported browsers – even in compat – support the `outerHTML` property.

**Comment by timmywil** [comment]
We discussed this in the meeting and we're leaning towards not adding this. `.prop('outerHTML')` is plenty short and we don't want to add support issues for a first-class outerHTML to the mix.

**Comment by weitzhandler** [comment]
Thanks for your update!
