### ISSUE TITLE
Why merge function should add the code "first.length = i" ?

### ISSUE THREAD

**Issue by gdut-zdc** [jquery/jquery#2155]
The length of first will increase automatically? Why merge function add the code "first.length = i"?

**Comment by Anshu-xLR** [comment]
As pointed out the code line `first.length = i;` was not necessary as the length parameter will automatically be updated to the new length. Removed the unnecessary code in the commit - ddb5420420c882f773aa20d0fc27479bccdfa809

**Comment by mzgol** [comment]
Internally we use `jQuery.merge` to merge jQuery objects which are array-like so they need to have `length` corrected. I see it's not documented at http://api.jquery.com/jQuery.merge/ so perhaps an API ticket is needed (cc @arthurvr)

**Comment by arthurvr** [comment]
Yup. A note in the documentation can't hurt. Will open an issue on the api site once I'm home.
