### ISSUE TITLE
`grunt npmcopy` is not a noop on master

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2160]
`grunt npmcopy` on master modifies Sinon fake timers heavily. Perhaps the `npmcopy` task wasn't run after one of recent Sinon updates?

**Comment by scottgonzalez** [comment]
See 91017047fc85cf634d9c7726901c250708f58731.

**Comment by mzgol** [comment]
@scottgonzalez Thanks. Maybe having `grunt npmcopy` as a `postinstall` script wouldn't be bad. I've heard `postinstall` scripts are discouraged although I don't know why.

**Comment by scottgonzalez** [comment]
That would potentially put you in a dirty state immediately though, right? That doesn't sound great.

**Comment by mzgol** [comment]
If you touch `package.json`, it's good that it gets you in a dirty state so that you don't forget to commit everything. If files match, this will be a noop.

**Comment by scottgonzalez** [comment]
Assuming the person making the change is manually changing `package.json` and then using `npm install`. If the changes are made with `npm install --save-dev some-package`, then the `postinstall` script won't run.

**Comment by timmywil** [comment]
A postinstall would help us remember, but we don't want users and one-time contributors to have to deal with it.

**Comment by mzgol** [comment]
> If the changes are made with npm install --save-dev some-package, then the postinstall script won't run.

Right. :/
