### ISSUE TITLE
Don't publish dist/cdn

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2164]
The `dist/cdn` directory shouldn't be published to npm/bower, it's meant just to generate files to send to various CDNs later on.

Refs #2161.

**Comment by timmywil** [comment]
I believe it was published by accident. Regardless, I've already taken care of this in the new release script.

**Comment by mzgol** [comment]
> I believe it was published by accident.

The real issue is we're using `.npmignore` instead of `files` in `package.json` so if the publishing person happens to have side-files in the `dist/` directory, they'd all get published. Is this handled by the release script? Possibly the easiest way to achieve that is to always publish from a fresh copy.

BTW, we'll most likely need `1.11.3`/`2.1.4` so we need to make sure it doesn't happen on the `1.11-stable` & `2.1-stable` branches either (and they won't use the new release script, will they?).

**Comment by timmywil** [comment]
We'll be using a separate repo to publish, so a `.npmignore` will no longer be necessary. I just made it so that `dist/cdn` does not get copied to the other repo.

As for `1.11.3/2.1.4`, I can make sure `dist/cdn` isn't in the distribution when publishing to npm manually (rather than do more updates to the old release stuff). I'll reopen as a reminder.

**Comment by mzgol** [comment]
> As for 1.11.3/2.1.4, I can make sure dist/cdn isn't in the distribution when publishing to npm manually (rather than do more updates to the old release stuff). I'll reopen as a reminder.

We can add `dist/cdn` to `.npmignore` & `bower.json/ignore` & no changes to the release script will be necessary (& you won't have to rememeber about it). I can submit a PR if that sounds OK.

**Comment by timmywil** [comment]
> I can submit a PR if that sounds OK.

Sure.

**Comment by mzgol** [comment]
PR: #2165

**Comment by mzgol** [comment]
Fixed by 136f1dc52bcb9db36122195401c692b26e21578a for `2.1-stable` & 4a704d1153e8591a566eb117ec5597fc19daac8e for `1.11-stable`.
