### ISSUE TITLE
.html() invoked on a shorthand tag will skip to the next closing tag and not generate the appropriate closing tag

### ISSUE THREAD

**Issue by paulbors** [jquery/jquery#2167]
Expected Behavior:
When invoking .html('<html code here>') on a shorthand closing tag, the function should generate the closing tag and leave intact any code outside the shorthand closed tag.

Actual Outcome:
If an element whose html code is to be replaced via .html() function is the shorthand form, the function will replace all the code up to the next closing tag even duh that closing tag belongs to a different node in the DOM.

Steps to Reproduce:
See the outcome of calling .html() to replace the html code of the full and short hand tags in this jsFiddle
http://jsfiddle.net/paulbors/m6ub6u9g/5/

**Comment by mzgol** [comment]
Your HTML is invalid. In HTML auto-closing tags are disallowed, `<span />` is actually interpreted as `<span>` without the closing tag. In your example `<span>` is auto-closed by the next closing `</p>`, you can see that without running your jQuery code it actually contains `] this won't show` and that's what you're replacing.

BTW,  nested `<p>` tags are disallowed, too, any opening `<p>` will close the previous paragraph.

**Comment by paulbors** [comment]
Be it invalid HTML, shouldn't an exception be raised rather than replacing the content?

**Comment by dmethvin** [comment]
That's not practical. We use the browser's parser via `.innerHTML`. To give detailed error messages we'd need to reimplement an HTML parser in JavaScript and embed it into jQuery. If you are using Internet Explorer 11 you will see HTML warnings on the console when you do things like this. Technically it is not an error because the HTML5 spec defines in pretty deep detail how to parse badly formed HTML.

**Comment by paulbors** [comment]
Fair enough

**Comment by mzgol** [comment]
It's not only not practical, it's impossible to do. We don't see the source HTML but the DOM the browser parses it into. In this case, the following HTML:
```html
<h3>
    <p>[<span id="full"><p>some html here</p></span>] this will show</p>
    <p>[<span id="short"/>] this won't show</p>
    <p>notice how '] this won't show' of the above paragraph is gone</p>
</h3>
```
will be serialized to the DOM that deserializes to the following HTML:
```html
<h3>
    <p>[<span id="full"></span></p><p>some html here</p>] this will show<p></p>
    <p>[<span id="short">] this won't show</span></p>
    <p>notice how '] this won't show' of the above paragraph is gone</p>
</h3>
```
As you can see, the `span` in the second paragraph is actually closed just before `</p>`. That's the only thing that jQuery sees.
