### ISSUE TITLE
jQuery with Angular requests assets multiple times when CORS is enabled on webserver

### ISSUE THREAD

**Issue by mikerandall** [jquery/jquery#2169]
Ok, this is a bit crazy and there are a few moving parts, but I'll try to give you what is happening as simply as I can. I have nginx running as localhost:8080 with CORS enabled. Separately, I have a django web app running on port 8000, serving the API. I use the CORS headers to access the API on the other port. Here's where things get weird:

When the page loads, all of the scripts are re-requested by jQuery, which breaks a bunch of things. Here are a couple pics of my console for reference:
![screen shot 2015-03-25 at 5 50 19 pm](https://cloud.githubusercontent.com/assets/224680/6836368/9db32572-d317-11e4-906c-c70deee8a9e6.png)
![screen shot 2015-03-25 at 5 50 33 pm](https://cloud.githubusercontent.com/assets/224680/6836371/a376eff2-d317-11e4-9273-c1ed8b42571f.png)

I've tracked it down here, on line 8549:

	`// Cross domain only allowed if supported through XMLHttpRequest`
	`if ( support.cors || xhrSupported && !options.crossDomain ) {`

It makes sense that the page would want to check to see if cors is enabled before trying to run again for all of the resources, but what I'm not understanding is why it's adding preflight if it is _NOT_ a crossDomain request? Isn't that the exact opposite of what we'd want? You'd want to add the preflight and other cors related request headers IF it's a cross domain request, not if it isn't. Perhaps this would be better:

        `if ( support.cors || xhrSupported && options.crossDomain ) {`

Does that make sense? Please let me know if you have any questions; perhaps I can take you through my local server to illustrate what is happening.

**Comment by dmethvin** [comment]
It's not clear which version of jQuery is being used or what the code looks like that makes the requests, but from the description you are trying to make a cross-domain request. The Django app hosting the page is on port 8000 and the ngnix server is on port 8080.  [Here's how an origin is defined](http://tools.ietf.org/html/rfc6454#section-5).

This is feeling like a StackOverflow question rather than a bug report, so it would be better to sort it out there and we can reopen if there is a specific problem identified.

**Comment by mikerandall** [comment]
It doesn't matter which version of jquery I'm using, version 2.1.3 and version 1.11.1 behave the same.

I understand what defines an origin.

While I am trying to do cross domain requests, the multiple requests I am referring to happen when the page is loaded. First the browser downloads the scripts (first pic), then jQuery sends out an XHR request for them again (second pic). I am not requesting the resources via any kind of ajax call or plugin, jQuery is just taking it upon itself to re-request the scripts. I have no idea why this is happening.

**Comment by mikerandall** [comment]
Yep, totally unrelated to jQuery. DOH LEVEL: 7
