### ISSUE TITLE
npm install error on windows 7

### ISSUE THREAD

**Issue by mrzzcn** [jquery/jquery#2170]
0 info it worked if it ends with ok
1 verbose cli [ 'd:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'd:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'contextify' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 silly cache add args [ 'contextify', null ]
5 verbose cache add spec contextify
6 silly cache add parsed spec { raw: 'contextify',
6 silly cache add   scope: null,
6 silly cache add   name: 'contextify',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed contextify@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'contextify', range: '*', hasData: false }
11 silly mapToRegistry name contextify
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/contextify
15 verbose addNameRange registry:https://registry.npmjs.org/contextify not in flight; fetching
16 verbose request uri https://registry.npmjs.org/contextify
17 verbose request no auth needed
18 info attempt registry request try #1 at 13:43:25
19 verbose request id 1885f698defad42c
20 verbose etag "4X2CJ5MY32D24KK87VPLL1IIT"
21 http request GET https://registry.npmjs.org/contextify
22 http 304 https://registry.npmjs.org/contextify
23 silly get cb [ 304,
23 silly get   { date: 'Thu, 26 Mar 2015 05:43:34 GMT',
23 silly get     server: 'Apache',
23 silly get     via: '1.1 varnish',
23 silly get     'last-modified': 'Thu, 26 Mar 2015 05:43:34 GMT',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"4X2CJ5MY32D24KK87VPLL1IIT"',
23 silly get     age: '0',
23 silly get     'x-served-by': 'cache-hkg6821-HKG',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1427348614.266142,VS0,VE646',
23 silly get     vary: 'Accept',
23 silly get     'content-length': '0',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose etag https://registry.npmjs.org/contextify from cache
25 verbose get saving contextify to F:\Users\JackZhang\AppData\Roaming\npm-cache\registry.npmjs.org\contextify\.cache.json
26 silly addNameRange number 2 { name: 'contextify', range: '*', hasData: true }
27 silly addNameRange versions [ 'contextify',
27 silly addNameRange   [ '0.0.2',
27 silly addNameRange     '0.0.3',
27 silly addNameRange     '0.0.4',
27 silly addNameRange     '0.0.5',
27 silly addNameRange     '0.0.6',
27 silly addNameRange     '0.0.7',
27 silly addNameRange     '0.1.0',
27 silly addNameRange     '0.1.1',
27 silly addNameRange     '0.1.2',
27 silly addNameRange     '0.1.3',
27 silly addNameRange     '0.1.4',
27 silly addNameRange     '0.1.5',
27 silly addNameRange     '0.1.6',
27 silly addNameRange     '0.1.7',
27 silly addNameRange     '0.1.8',
27 silly addNameRange     '0.1.9',
27 silly addNameRange     '0.1.10',
27 silly addNameRange     '0.1.11',
27 silly addNameRange     '0.1.12',
27 silly addNameRange     '0.1.13' ] ]
28 verbose addNamed contextify@0.1.13
29 silly addNamed semver.valid 0.1.13
30 silly addNamed semver.validRange 0.1.13
31 silly cache afterAdd contextify@0.1.13
32 verbose afterAdd F:\Users\JackZhang\AppData\Roaming\npm-cache\contextify\0.1.13\package\package.json not in flight; writing
33 verbose afterAdd F:\Users\JackZhang\AppData\Roaming\npm-cache\contextify\0.1.13\package\package.json written
34 silly install resolved [ { name: 'contextify',
34 silly install resolved     version: '0.1.13',
34 silly install resolved     description: 'Turn an object into a persistent execution context.',
34 silly install resolved     author: { name: 'Brian McDaniel', email: 'brianmcd05@gmail.com' },
34 silly install resolved     contributors:
34 silly install resolved      [ [Object],
34 silly install resolved        [Object],
34 silly install resolved        [Object],
34 silly install resolved        [Object],
34 silly install resolved        [Object],
34 silly install resolved        [Object],
34 silly install resolved        [Object],
34 silly install resolved        [Object],
34 silly install resolved        [Object],
34 silly install resolved        [Object],
34 silly install resolved        [Object],
34 silly install resolved        [Object] ],
34 silly install resolved     keywords: [ 'context', 'vm' ],
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'https://github.com/brianmcd/contextify.git' },
34 silly install resolved     main: './lib/contextify',
34 silly install resolved     scripts: { test: 'nodeunit test/', install: 'node-gyp rebuild' },
34 silly install resolved     engines: { node: '>=0.4.0' },
34 silly install resolved     licenses: [ [Object] ],
34 silly install resolved     dependencies: { bindings: '*', nan: '~1.5.0' },
34 silly install resolved     devDependencies: { nodeunit: '>=0.5.x' },
34 silly install resolved     gypfile: true,
34 silly install resolved     gitHead: '99f01df26b12f4d55440bc811ea8f4fada9b04c5',
34 silly install resolved     bugs: { url: 'https://github.com/brianmcd/contextify/issues' },
34 silly install resolved     homepage: 'https://github.com/brianmcd/contextify',
34 silly install resolved     _id: 'contextify@0.1.13',
34 silly install resolved     _shasum: '4ecac6abf6fd266aff1a7b5c4fcc902932cb4efe',
34 silly install resolved     _from: 'contextify@*',
34 silly install resolved     _npmVersion: '2.5.1',
34 silly install resolved     _nodeVersion: '0.12.0',
34 silly install resolved     _npmUser: { name: 'brianmcd', email: 'brianmcd05@gmail.com' },
34 silly install resolved     maintainers: [ [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: '4ecac6abf6fd266aff1a7b5c4fcc902932cb4efe',
34 silly install resolved        tarball: 'http://registry.npmjs.org/contextify/-/contextify-0.1.13.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/contextify/-/contextify-0.1.13.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install contextify@0.1.13 into F:\Users\JackZhang\AppData\Roaming\npm
36 info installOne contextify@0.1.13
37 verbose installOne of contextify to F:\Users\JackZhang\AppData\Roaming\npm not in flight; installing
38 verbose lock using F:\Users\JackZhang\AppData\Roaming\npm-cache\_locks\contextify-8a21c65e3cc51045.lock for F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
39 silly install write writing contextify 0.1.13 to F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
40 silly cache addNamed cb contextify@0.1.13
41 verbose unbuild node_modules\contextify
42 verbose gentlyRm vacuuming F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
43 verbose tar unpack F:\Users\JackZhang\AppData\Roaming\npm-cache\contextify\0.1.13\package.tgz
44 verbose tar unpacking to F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
45 verbose gentlyRm vacuuming F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
46 silly gunzTarPerm modes [ '777', '666' ]
47 silly gunzTarPerm extractEntry package.json
48 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
49 silly gunzTarPerm extractEntry .npmignore
50 silly gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
51 silly gunzTarPerm extractEntry README.md
52 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
53 silly gunzTarPerm extractEntry changelog
54 silly gunzTarPerm modified mode [ 'changelog', 420, 438 ]
55 silly gunzTarPerm extractEntry binding.gyp
56 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
57 silly gunzTarPerm extractEntry lib/contextify.js
58 silly gunzTarPerm modified mode [ 'lib/contextify.js', 420, 438 ]
59 silly gunzTarPerm extractEntry test/contextify.js
60 silly gunzTarPerm modified mode [ 'test/contextify.js', 420, 438 ]
61 silly gunzTarPerm extractEntry LICENSE.txt
62 silly gunzTarPerm modified mode [ 'LICENSE.txt', 420, 438 ]
63 silly gunzTarPerm extractEntry src/contextify.cc
64 silly gunzTarPerm modified mode [ 'src/contextify.cc', 420, 438 ]
65 silly gunzTarPerm extractEntry wscript
66 silly gunzTarPerm modified mode [ 'wscript', 420, 438 ]
67 info preinstall contextify@0.1.13
68 silly prepareForInstallMany adding bindings@* from contextify dependencies
69 silly prepareForInstallMany adding nan@~1.5.0 from contextify dependencies
70 silly cache add args [ 'nan@~1.5.0', null ]
71 verbose cache add spec nan@~1.5.0
72 silly cache add parsed spec { raw: 'nan@~1.5.0',
72 silly cache add   scope: null,
72 silly cache add   name: 'nan',
72 silly cache add   rawSpec: '~1.5.0',
72 silly cache add   spec: '>=1.5.0 <1.6.0',
72 silly cache add   type: 'range' }
73 verbose addNamed nan@>=1.5.0 <1.6.0
74 silly addNamed semver.valid null
75 silly addNamed semver.validRange >=1.5.0 <1.6.0
76 silly addNameRange { name: 'nan', range: '>=1.5.0 <1.6.0', hasData: false }
77 silly mapToRegistry name nan
78 silly mapToRegistry using default registry
79 silly mapToRegistry registry https://registry.npmjs.org/
80 silly mapToRegistry uri https://registry.npmjs.org/nan
81 verbose addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
82 verbose request uri https://registry.npmjs.org/nan
83 verbose request no auth needed
84 info attempt registry request try #1 at 13:43:29
85 verbose etag "2RVNOBUBIPFCFHXKKPTSTKGB8"
86 http request GET https://registry.npmjs.org/nan
87 silly cache add args [ 'bindings@*', null ]
88 verbose cache add spec bindings@*
89 silly cache add parsed spec { raw: 'bindings@*',
89 silly cache add   scope: null,
89 silly cache add   name: 'bindings',
89 silly cache add   rawSpec: '*',
89 silly cache add   spec: '*',
89 silly cache add   type: 'range' }
90 verbose addNamed bindings@*
91 silly addNamed semver.valid null
92 silly addNamed semver.validRange *
93 silly addNameRange { name: 'bindings', range: '*', hasData: false }
94 silly mapToRegistry name bindings
95 silly mapToRegistry using default registry
96 silly mapToRegistry registry https://registry.npmjs.org/
97 silly mapToRegistry uri https://registry.npmjs.org/bindings
98 verbose addNameRange registry:https://registry.npmjs.org/bindings not in flight; fetching
99 verbose request uri https://registry.npmjs.org/bindings
100 verbose request no auth needed
101 info attempt registry request try #1 at 13:43:29
102 verbose etag "5997G8NY1OJEMZ1HNHL7VBX5J"
103 http request GET https://registry.npmjs.org/bindings
104 http 304 https://registry.npmjs.org/bindings
105 silly get cb [ 304,
105 silly get   { date: 'Thu, 26 Mar 2015 05:43:35 GMT',
105 silly get     server: 'Apache',
105 silly get     via: '1.1 varnish',
105 silly get     'last-modified': 'Thu, 26 Mar 2015 05:43:35 GMT',
105 silly get     'cache-control': 'max-age=60',
105 silly get     etag: '"5997G8NY1OJEMZ1HNHL7VBX5J"',
105 silly get     age: '0',
105 silly get     'x-served-by': 'cache-hkg6822-HKG',
105 silly get     'x-cache': 'HIT',
105 silly get     'x-cache-hits': '1',
105 silly get     'x-timer': 'S1427348615.289422,VS0,VE611',
105 silly get     vary: 'Accept',
105 silly get     'content-length': '0',
105 silly get     'keep-alive': 'timeout=10, max=50',
105 silly get     connection: 'Keep-Alive' } ]
106 verbose etag https://registry.npmjs.org/bindings from cache
107 verbose get saving bindings to F:\Users\JackZhang\AppData\Roaming\npm-cache\registry.npmjs.org\bindings\.cache.json
108 silly addNameRange number 2 { name: 'bindings', range: '*', hasData: true }
109 silly addNameRange versions [ 'bindings',
109 silly addNameRange   [ '0.0.1',
109 silly addNameRange     '0.1.0',
109 silly addNameRange     '0.1.1',
109 silly addNameRange     '0.2.0',
109 silly addNameRange     '0.2.1',
109 silly addNameRange     '0.2.2',
109 silly addNameRange     '0.2.3',
109 silly addNameRange     '0.2.4',
109 silly addNameRange     '0.3.0',
109 silly addNameRange     '0.4.0',
109 silly addNameRange     '1.0.0',
109 silly addNameRange     '1.1.0',
109 silly addNameRange     '1.1.1',
109 silly addNameRange     '1.2.0',
109 silly addNameRange     '1.2.1' ] ]
110 verbose addNamed bindings@1.2.1
111 silly addNamed semver.valid 1.2.1
112 silly addNamed semver.validRange 1.2.1
113 silly cache afterAdd bindings@1.2.1
114 verbose afterAdd F:\Users\JackZhang\AppData\Roaming\npm-cache\bindings\1.2.1\package\package.json not in flight; writing
115 verbose afterAdd F:\Users\JackZhang\AppData\Roaming\npm-cache\bindings\1.2.1\package\package.json written
116 http 304 https://registry.npmjs.org/nan
117 silly get cb [ 304,
117 silly get   { date: 'Thu, 26 Mar 2015 05:43:35 GMT',
117 silly get     server: 'Apache',
117 silly get     via: '1.1 varnish',
117 silly get     'last-modified': 'Thu, 26 Mar 2015 05:43:35 GMT',
117 silly get     'cache-control': 'max-age=60',
117 silly get     etag: '"2RVNOBUBIPFCFHXKKPTSTKGB8"',
117 silly get     age: '0',
117 silly get     'x-served-by': 'cache-hkg6825-HKG',
117 silly get     'x-cache': 'HIT',
117 silly get     'x-cache-hits': '1',
117 silly get     'x-timer': 'S1427348615.283433,VS0,VE675',
117 silly get     vary: 'Accept',
117 silly get     'content-length': '0',
117 silly get     'keep-alive': 'timeout=10, max=50',
117 silly get     connection: 'Keep-Alive' } ]
118 verbose etag https://registry.npmjs.org/nan from cache
119 verbose get saving nan to F:\Users\JackZhang\AppData\Roaming\npm-cache\registry.npmjs.org\nan\.cache.json
120 silly addNameRange number 2 { name: 'nan', range: '>=1.5.0 <1.6.0', hasData: true }
121 silly addNameRange versions [ 'nan',
121 silly addNameRange   [ '0.3.0-wip',
121 silly addNameRange     '0.3.0-wip2',
121 silly addNameRange     '0.3.0',
121 silly addNameRange     '0.3.1',
121 silly addNameRange     '0.3.2',
121 silly addNameRange     '0.4.0',
121 silly addNameRange     '0.4.1',
121 silly addNameRange     '0.4.2',
121 silly addNameRange     '0.4.3',
121 silly addNameRange     '0.4.4',
121 silly addNameRange     '0.5.0',
121 silly addNameRange     '0.5.1',
121 silly addNameRange     '0.5.2',
121 silly addNameRange     '0.6.0',
121 silly addNameRange     '0.7.0',
121 silly addNameRange     '0.7.1',
121 silly addNameRange     '0.8.0',
121 silly addNameRange     '1.0.0',
121 silly addNameRange     '1.1.0',
121 silly addNameRange     '1.1.1',
121 silly addNameRange     '1.1.2',
121 silly addNameRange     '1.2.0',
121 silly addNameRange     '1.3.0',
121 silly addNameRange     '1.4.0',
121 silly addNameRange     '1.4.1',
121 silly addNameRange     '1.5.0',
121 silly addNameRange     '1.4.2',
121 silly addNameRange     '1.4.3',
121 silly addNameRange     '1.5.1',
121 silly addNameRange     '1.5.2',
121 silly addNameRange     '1.6.0',
121 silly addNameRange     '1.5.3',
121 silly addNameRange     '1.6.1',
121 silly addNameRange     '1.6.2',
121 silly addNameRange     '1.7.0' ] ]
122 verbose addNamed nan@1.5.3
123 silly addNamed semver.valid 1.5.3
124 silly addNamed semver.validRange 1.5.3
125 silly cache afterAdd nan@1.5.3
126 verbose afterAdd F:\Users\JackZhang\AppData\Roaming\npm-cache\nan\1.5.3\package\package.json not in flight; writing
127 verbose afterAdd F:\Users\JackZhang\AppData\Roaming\npm-cache\nan\1.5.3\package\package.json written
128 silly install resolved [ { name: 'bindings',
128 silly install resolved     description: 'Helper module for loading your native module\'s .node file',
128 silly install resolved     keywords: [ 'native', 'addon', 'bindings', 'gyp', 'waf', 'c', 'c++' ],
128 silly install resolved     version: '1.2.1',
128 silly install resolved     author:
128 silly install resolved      { name: 'Nathan Rajlich',
128 silly install resolved        email: 'nathan@tootallnate.net',
128 silly install resolved        url: 'http://tootallnate.net' },
128 silly install resolved     repository:
128 silly install resolved      { type: 'git',
128 silly install resolved        url: 'git://github.com/TooTallNate/node-bindings.git' },
128 silly install resolved     main: './bindings.js',
128 silly install resolved     bugs: { url: 'https://github.com/TooTallNate/node-bindings/issues' },
128 silly install resolved     homepage: 'https://github.com/TooTallNate/node-bindings',
128 silly install resolved     license: 'MIT',
128 silly install resolved     gitHead: 'e404152ee27f8478ccbc7122ee051246e8e5ec02',
128 silly install resolved     _id: 'bindings@1.2.1',
128 silly install resolved     scripts: {},
128 silly install resolved     _shasum: '14ad6113812d2d37d72e67b4cacb4bb726505f11',
128 silly install resolved     _from: 'bindings@*',
128 silly install resolved     _npmVersion: '1.4.14',
128 silly install resolved     _npmUser: { name: 'tootallnate', email: 'nathan@tootallnate.net' },
128 silly install resolved     maintainers: [ [Object], [Object] ],
128 silly install resolved     dist:
128 silly install resolved      { shasum: '14ad6113812d2d37d72e67b4cacb4bb726505f11',
128 silly install resolved        tarball: 'http://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz' },
128 silly install resolved     directories: {},
128 silly install resolved     _resolved: 'https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz',
128 silly install resolved     readme: 'ERROR: No README data found!' },
128 silly install resolved   { name: 'nan',
128 silly install resolved     version: '1.5.3',
128 silly install resolved     description: 'Native Abstractions for Node.js: C++ header for Node 0.8->0.12 compatibility',
128 silly install resolved     main: 'include_dirs.js',
128 silly install resolved     repository: { type: 'git', url: 'git://github.com/rvagg/nan.git' },
128 silly install resolved     scripts:
128 silly install resolved      { test: 'tap --gc test/js/*-test.js',
128 silly install resolved        'rebuild-tests': 'node-gyp rebuild --directory test' },
128 silly install resolved     contributors:
128 silly install resolved      [ [Object],
128 silly install resolved        [Object],
128 silly install resolved        [Object],
128 silly install resolved        [Object],
128 silly install resolved        [Object],
128 silly install resolved        [Object],
128 silly install resolved        [Object] ],
128 silly install resolved     devDependencies:
128 silly install resolved      { bindings: '~1.2.1',
128 silly install resolved        'node-gyp': '~1.0.2',
128 silly install resolved        tap: '~0.5.0',
128 silly install resolved        xtend: '~4.0.0' },
128 silly install resolved     license: 'MIT',
128 silly install resolved     gitHead: '28ea7e1b769f790c69deaf141b47e4d41e176e8b',
128 silly install resolved     bugs: { url: 'https://github.com/rvagg/nan/issues' },
128 silly install resolved     homepage: 'https://github.com/rvagg/nan',
128 silly install resolved     _id: 'nan@1.5.3',
128 silly install resolved     _shasum: '4cd0ecc133b7b0700a492a646add427ae8a318eb',
128 silly install resolved     _from: 'nan@>=1.5.0 <1.6.0',
128 silly install resolved     _npmVersion: '2.1.18',
128 silly install resolved     _nodeVersion: '1.0.3',
128 silly install resolved     _npmUser: { name: 'rvagg', email: 'rod@vagg.org' },
128 silly install resolved     maintainers: [ [Object], [Object] ],
128 silly install resolved     dist:
128 silly install resolved      { shasum: '4cd0ecc133b7b0700a492a646add427ae8a318eb',
128 silly install resolved        tarball: 'http://registry.npmjs.org/nan/-/nan-1.5.3.tgz' },
128 silly install resolved     directories: {},
128 silly install resolved     _resolved: 'https://registry.npmjs.org/nan/-/nan-1.5.3.tgz',
128 silly install resolved     readme: 'ERROR: No README data found!' } ]
129 info install bindings@1.2.1 into F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
130 info install nan@1.5.3 into F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
131 info installOne bindings@1.2.1
132 verbose installOne of bindings to F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify not in flight; installing
133 info installOne nan@1.5.3
134 verbose installOne of nan to F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify not in flight; installing
135 verbose lock using F:\Users\JackZhang\AppData\Roaming\npm-cache\_locks\nan-80df1128a96d50d0.lock for F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\nan
136 verbose lock using F:\Users\JackZhang\AppData\Roaming\npm-cache\_locks\bindings-b1e7d59b21868f56.lock for F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\bindings
137 silly install write writing nan 1.5.3 to F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\nan
138 silly cache addNamed cb nan@1.5.3
139 verbose unbuild node_modules\contextify\node_modules\nan
140 silly install write writing bindings 1.2.1 to F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\bindings
141 silly cache addNamed cb bindings@1.2.1
142 verbose unbuild node_modules\contextify\node_modules\bindings
143 verbose gentlyRm vacuuming F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\nan
144 verbose gentlyRm vacuuming F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\bindings
145 verbose tar unpack F:\Users\JackZhang\AppData\Roaming\npm-cache\nan\1.5.3\package.tgz
146 verbose tar unpacking to F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\nan
147 verbose gentlyRm vacuuming F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\nan
148 verbose tar unpack F:\Users\JackZhang\AppData\Roaming\npm-cache\bindings\1.2.1\package.tgz
149 verbose tar unpacking to F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\bindings
150 verbose gentlyRm vacuuming F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\bindings
151 silly gunzTarPerm modes [ '777', '666' ]
152 silly gunzTarPerm modes [ '777', '666' ]
153 silly gunzTarPerm extractEntry package.json
154 silly gunzTarPerm modified mode [ 'package.json', 436, 438 ]
155 silly gunzTarPerm extractEntry package.json
156 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
157 silly gunzTarPerm extractEntry README.md
158 silly gunzTarPerm modified mode [ 'README.md', 436, 438 ]
159 silly gunzTarPerm extractEntry include_dirs.js
160 silly gunzTarPerm modified mode [ 'include_dirs.js', 420, 438 ]
161 silly gunzTarPerm extractEntry README.md
162 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
163 silly gunzTarPerm extractEntry bindings.js
164 silly gunzTarPerm modified mode [ 'bindings.js', 420, 438 ]
165 silly gunzTarPerm extractEntry LICENSE.md
166 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 438 ]
167 silly gunzTarPerm extractEntry .dntrc
168 silly gunzTarPerm modified mode [ '.dntrc', 436, 438 ]
169 silly gunzTarPerm extractEntry appveyor.yml
170 silly gunzTarPerm modified mode [ 'appveyor.yml', 436, 438 ]
171 silly gunzTarPerm extractEntry nan.h
172 silly gunzTarPerm modified mode [ 'nan.h', 436, 438 ]
173 info preinstall bindings@1.2.1
174 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
175 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 436, 438 ]
176 silly install resolved []
177 verbose about to build F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\bindings
178 info build F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\bindings
179 verbose linkStuff [ true,
179 verbose linkStuff   'F:\\Users\\JackZhang\\AppData\\Roaming\\npm\\node_modules',
179 verbose linkStuff   false,
179 verbose linkStuff   'F:\\Users\\JackZhang\\AppData\\Roaming\\npm\\node_modules\\contextify\\node_modules' ]
180 info linkStuff bindings@1.2.1
181 verbose linkBins bindings@1.2.1
182 verbose linkMans bindings@1.2.1
183 verbose rebuildBundles bindings@1.2.1
184 info install bindings@1.2.1
185 info postinstall bindings@1.2.1
186 verbose unlock done using F:\Users\JackZhang\AppData\Roaming\npm-cache\_locks\bindings-b1e7d59b21868f56.lock for F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\bindings
187 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
188 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 436, 438 ]
189 silly gunzTarPerm extractEntry nan_new.h
190 silly gunzTarPerm modified mode [ 'nan_new.h', 436, 438 ]
191 silly gunzTarPerm extractEntry CHANGELOG.md
192 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 436, 438 ]
193 info preinstall nan@1.5.3
194 silly install resolved []
195 verbose about to build F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\nan
196 info build F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\nan
197 verbose linkStuff [ true,
197 verbose linkStuff   'F:\\Users\\JackZhang\\AppData\\Roaming\\npm\\node_modules',
197 verbose linkStuff   false,
197 verbose linkStuff   'F:\\Users\\JackZhang\\AppData\\Roaming\\npm\\node_modules\\contextify\\node_modules' ]
198 info linkStuff nan@1.5.3
199 verbose linkBins nan@1.5.3
200 verbose linkMans nan@1.5.3
201 verbose rebuildBundles nan@1.5.3
202 info install nan@1.5.3
203 info postinstall nan@1.5.3
204 verbose unlock done using F:\Users\JackZhang\AppData\Roaming\npm-cache\_locks\nan-80df1128a96d50d0.lock for F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify\node_modules\nan
205 verbose about to build F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
206 info build F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
207 verbose linkStuff [ true,
207 verbose linkStuff   'F:\\Users\\JackZhang\\AppData\\Roaming\\npm\\node_modules',
207 verbose linkStuff   true,
207 verbose linkStuff   'F:\\Users\\JackZhang\\AppData\\Roaming\\npm\\node_modules' ]
208 info linkStuff contextify@0.1.13
209 verbose linkBins contextify@0.1.13
210 verbose linkMans contextify@0.1.13
211 verbose rebuildBundles contextify@0.1.13
212 verbose rebuildBundles [ 'bindings', 'nan' ]
213 info install contextify@0.1.13
214 verbose unsafe-perm in lifecycle true
215 info contextify@0.1.13 Failed to exec install script
216 verbose unlock done using F:\Users\JackZhang\AppData\Roaming\npm-cache\_locks\contextify-8a21c65e3cc51045.lock for F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
217 verbose stack Error: contextify@0.1.13 install: `node-gyp rebuild`
217 verbose stack Exit status 1
217 verbose stack     at EventEmitter.<anonymous> (d:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
217 verbose stack     at EventEmitter.emit (events.js:110:17)
217 verbose stack     at ChildProcess.<anonymous> (d:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
217 verbose stack     at ChildProcess.emit (events.js:110:17)
217 verbose stack     at maybeClose (child_process.js:1008:16)
217 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
218 verbose pkgid contextify@0.1.13
219 verbose cwd f:\GitHub\jquery
220 error Windows_NT 6.1.7601
221 error argv "d:\\Program Files\\nodejs\\node.exe" "d:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "contextify"
222 error node v0.12.1
223 error npm  v2.5.1
224 error code ELIFECYCLE
225 error contextify@0.1.13 install: `node-gyp rebuild`
225 error Exit status 1
226 error Failed at the contextify@0.1.13 install script 'node-gyp rebuild'.
226 error This is most likely a problem with the contextify package,
226 error not with npm itself.
226 error Tell the author that this fails on your system:
226 error     node-gyp rebuild
226 error You can get their info via:
226 error     npm owner ls contextify
226 error There is likely additional logging output above.
227 verbose exit [ 1, true ]
228 verbose unbuild node_modules\contextify
229 info preuninstall contextify@0.1.13
230 info uninstall contextify@0.1.13
231 verbose unbuild rmStuff contextify@0.1.13 from F:\Users\JackZhang\AppData\Roaming\npm\node_modules
232 info postuninstall contextify@0.1.13
233 verbose gentlyRm vacuuming F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
234 silly gentlyRm purging F:\Users\JackZhang\AppData\Roaming\npm\node_modules\contextify
235 silly gentlyRm quitting because other entries in F:\Users\JackZhang\AppData\Roaming\npm\node_modules

**Comment by mzgol** [comment]
This is only part of the log, the end is more interesting.

Also, please provide your node & npm versions; you can check via:
```
node --version
npm --version
```

**Comment by mzgol** [comment]
Closing for lack of input; if you answer my question we can reopen.
