### ISSUE TITLE
$.fn.each fails when the argument is a Function class

### ISSUE THREAD

**Issue by soloproyectos** [jquery/jquery#2171]
The following code should print 'MyClass', instead of 'document':

```JavaScript
function MyClass() {};
$(MyClass).each(function () {
    console.log(this); // this command prints 'document'
});
```
Tested on jquery-2.1.3.min.js

**Comment by dmethvin** [comment]
Why do you think that? Is it documented in http://api.jquery.com/each/ for example?

**Comment by rwaldron** [comment]
When a function is passed to `$()`, the "ready" overload is used and the `this` value is a jQuery object containing a single item, which is the `document` object.

- http://api.jquery.com/jquery/#jQuery3
- https://github.com/jquery/jquery/blob/master/src/core/init.js#L99-L105

```js
$(function() {
  // document is ready
});

// Same as 
function ready() {
  // document is ready
}
$(ready);
```

**Comment by soloproyectos** [comment]
I thought that this was the default behavior, because the following script returns the instance itself. For example:
```JavaScript
var object = {one: 1, two: 2};
$(object).each(function () {
    console.log(this === object); // returns "true"
});
```
But the following script returns "false":
```JavaScript
var MyClass = function() {};
$(MyClass).each(function () {
    console.log(this === MyClass); // returns "false"
});
```

Also, I think that the function $.fn.each is not fully documented. Sometimes, I use it to iterate over a collection of items. Not necessarily over a jQuery object.

Sorry for my English :)

**Comment by dmethvin** [comment]
I think this is best posed as a StackOverflow question if you want further clarification.
