### ISSUE TITLE
Docs for getJSON() should specify under what conditions it is secure

### ISSUE THREAD

**Issue by davidwagner** [jquery/jquery#2173]
The documentation for getJSON() should mention the conditions under which it causes a XSS vulnerability, and describe what developers need to do to avoid introducing XSS when using getJSON().

In particular, `$.getJSON(untrusted_url, function(...) {...})` is unsafe, if `untrusted_url` comes from an untrusted source (e.g., from the attacker, from another user).  If the attacker controls `evil.com`, the attacker can arrange for `untrusted_url` to hold something like `http://evil.com/callback=?` and then arrange for `evil.com` to respond to that request with malicious Javascript.  JQuery's JSONP auto-detection will then eval the Javascript found in the response to that request, making the `$.getJSON()` call a XSS vulnerability.

This is a foot-gun.  It's not clear from the documentation for `getJSON()` that it can introduce this kind of vulnerability when part or all of the URL can be controlled by the attacker.  Documenting this more clearly would help developers avoid inadvertent XSS vulnerabilities in their code.

Apparently if the URL might be partially or completely under attacker control, the only safe way to fetch JSON from that URL is to use `$.ajax(url, {dataType: 'json', jsonp: false});`.  This fact is not apparent from the documentation -- it should be described in the documentation more clearly.

See http://stackoverflow.com/q/29022794/ for details.

**Comment by dmethvin** [comment]
See #2174, the docs tickets for both of these could be combined.
