### ISSUE TITLE
intro.js code is truncated

### ISSUE THREAD

**Issue by ncorison** [jquery/jquery#2176]
The intro.js code file appears to be truncated at line 45 after an opening bracket in line 38.

**Comment by dmethvin** [comment]
It's matched in outro.js.

**Comment by arthurvr** [comment]
That's intentional, [it's meant to be used as the start of the builded file](https://github.com/jquery/jquery/blob/6051609df35ef5e478c79c76534c03e4b46100bf/build/tasks/build.js#L28). Our build system handles that. There's also an `outro.js`. But thanks for reporting it :)

**Comment by arthurvr** [comment]
Ha, and @dmethvin was just a second quicker.
