### ISSUE TITLE
No error or other indication that getScript didn't execute script sent with MIME text/plain

### ISSUE THREAD

**Issue by dandv** [jquery/jquery#2178]
[This gist](https://gist.github.com/dandv/1dedcf57c28452224219) just makes an `alert()` call. I'm trying to run it with `.getScript()` ([jsbin](http://jsbin.com/puyuyi/2/edit?js,console)):

```js
$.getScript('https://gist.githubusercontent.com/dandv/1dedcf57c28452224219/raw/6b732b52adba49f8a2df755a47180c6b0fbb1c70/alert.js', function success(data, textStatus) {
  console.log('Script loaded:', data, textStatus);
});
```

The console dutifully shows "Script loaded", and the Network tab shows indeed that the request to gist.github.com returned the script. The problem is, the script won't ever execute.

Now we know that GitHub returns `Content-Type: text/plain` and sets `no-sniff`, so failure to execute isn't entirely surprising, but I think the fact that `success()` is called can be misleading.

`data` being undefined isn't an indicator, because `data` is undefined even if the script executes - [jsbin](http://jsbin.com/puyuyi/3/edit?js,console).

This raises a separate issue, what exactly is `data` supposed to contain? It's not the body of the script, nor its result apparently - the script called by the second JSbin returns `"finished"`, but the console still shows `undefined`.

**Comment by timmywil** [comment]
It seems the script is executing, but the illegal return statement is causing an error. 
https://www.dropbox.com/s/5jle55d6kurl9da/Screenshot%202015-05-05%2012.23.50.png?dl=0

Regardless, the script was retrieved and executed.
