### ISSUE TITLE
paste events do not work correctly with clipboardData

### ISSUE THREAD

**Issue by PalmerAL** [jquery/jquery#2186]
If I have html like this:

    <div contenteditable>content</div>

And I add a paste event like this using vanilla js:

    document.querySelector("div").addEventListener("paste", function(e) {
        alert(e.clipboardData);
    });

This will alert <code>[object DataTransfer]</code> when you paste text into the div. However, the equivalent jquery version alerts <code>undefined</code> when you paste text into it:

    $("div").on("paste", function(e) {
        alert(e.clipboardData);
    });

Tested in firefox 37 and safari 7
<a href="http://jsfiddle.net/frsdo9n7/">working</a> and <a href="http://jsfiddle.net/2kfy9924/">nonworking</a> jsfiddle.

**Comment by dmethvin** [comment]
In the jQuery case you are looking at the normalized `jQuery.Event` per the docs. Use `e.originalEvent` if you want the original native event.

**Comment by PalmerAL** [comment]
Thanks!
