### ISSUE TITLE
IE 11 

### ISSUE THREAD

**Issue by goosemanjack** [jquery/jquery#2188]
I am still working on a simplified sample, but in IE 11 when an IFrame includes the jQuery library it causes the following unhandled exception to throw:

0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'attachEvent'

This appears to happen only iFrames with IE 11. It may or may not be tied to "edge" mode.  It may or may not be tied to external libraries (underscore was also included in app where it repros).

The issue lies at line 1518 in jQuery source (jquery-1.10.1)

```
	// Support: IE>8
	// If iframe document is assigned to "document" variable and if iframe has been reloaded,
	// IE will throw "permission denied" error when accessing "document" variable, see jQuery #13936
	if ( parent && parent.frameElement ) {
		parent.attachEvent( "onbeforeunload", function() {
			setDocument();
		});
	}
```

The fix appears to be fairly simple. By changing the if check to also check for attachEvent it worked as expected and didn't throw

`  if (parent && parent.frameElement && parent.attachEvent) {

This is a re-opening of an old issue (14555) from the old bug system.
http://bugs.jquery.com/ticket/14555

**Comment by mzgol** [comment]
Try jQuery 1.11.2, this code doesn't exist there.

It's a good idea to test on the latest version before reporting a bug. There's a chance we might have already fixed it. :)

**Comment by laeeqwtb** [comment]
Yes, with latest version issue fixed.
