### ISSUE TITLE
Incorrect Object properties enumeration

### ISSUE THREAD

**Issue by amurchick** [jquery/jquery#2189]
Affects on http://code.jquery.com/jquery-2.1.3.js
When Object.prototype extended, some methods broken to work:

Try:
```Javascript
Object.prototype.forEach = function (fn) {
    if (typeof fn !== 'function') 
        throw 'Incorrect usage!';
};
$('body').css({display: 'none'});
```

To fix it, in function `jQuery.extend.access()` https://github.com/jquery/jquery/blob/10399ddcf8a239acc27bdec9231b996b178224d3/src/core/access.js#L15 replace this lines:
```javascript
for ( i in key ) {
    jQuery.access( elems, fn, i, key[i], true, emptyGet, raw );
}
```
on this:
```javascript
for ( i in key ) {
    if (key.hasOwnProperty(i))
        jQuery.access( elems, fn, i, key[i], true, emptyGet, raw );
}
```

**Comment by dmethvin** [comment]
Don't add enumerable properties to `Object.prototype`. 
http://contribute.jquery.org/wont-fix/#object-prototype-issues

**Comment by amurchick** [comment]
Thank you!
