### ISSUE TITLE
ajax()  calls the wrong callback caused by ajaxConvert() 's false return.

### ISSUE THREAD

**Issue by ThomasLau** [jquery/jquery#2190]
hi,jquery1.9.1, lately i wrote some code like this:

	$.ajax({
		url: url,
		dataType: "json",
		data:...,
		success: function(data){
			console.log("success");
		},
		error: function(data){
			console.log("error");
		}
	});

I found the conole always outputs  "error",even though this request's  http status code is 200.
as it to me, shouldn't it calls the success methord when the request is ok?

**Comment by mzgol** [comment]
I cannot reproduce it, either with jQuery 1.9.1 and the latest `compat`. Please make sure the issue exists in the latest version of jQuery (1.11.2) and create a test case at jsFiddle or jsBin.

**Comment by ThomasLau** [comment]
yes, the "issue" exists in  jQuery (1.11.2). sorry not founding how to simulate a ajax request, so i list my code here.

	<!DOCTYPE html>
	<html>
	<head><script src="http://code.jquery.com/jquery-1.11.2.min.js"></script></head>
	<body>
	<a id="suggest" href="javascript:;" />click here to see2</a>
	</body>
	<script>
	$( document ).ready(function() {
		$("#suggest").click(function(){
			//alert("hello");
			$.ajax({
				url: '/api/echo.json',
				dataType: "json",
				data:{dest:"hello"},
				success: function(data){
					console.log("success");
				},
				error: function(data){
					console.log("error");
				}
			 });
		});
		
	});
	</script>
	</html>

/api/echo.json:

	"("."{'key':'value'}".")"

this ajax request returns the wright data,even though it is not the wright json formate, but the output is "error",i think this confused me, because in the [jquery.ajax](http://api.jquery.com/jQuery.ajax/) document,it wrotes:
	success
	Type: Function( Anything data, String textStatus, jqXHR jqXHR )
	A function to be called if the request succeeds. The function gets passed three arguments: The data returned from the server, formatted according to the dataType parameter or the dataFilter callback function, if specified; a string describing the status; and the jqXHR (in jQuery 1.4.x, XMLHttpRequest) object. As of jQuery 1.5, the success setting can accept an array of functions. Each function will be called in turn. This is an Ajax Event.

**Comment by dmethvin** [comment]
For a `dataType: json` request, the data must be valid JSON or the request will fail and go to the error callback, even if the HTTP status was 2xx. It couldn't be otherwise, since jQuery is supposed to deliver the converted JSON to the success callaback as the `data` parameter in your example.

**Comment by ThomasLau** [comment]
ok, tks @dmethvin ,i'm a newer to jquery, when i read the document "A function to be called if the request succeeds.",i think the success methord will be called if this "request succeeds",which i take it as the http status code is 2xx
