### ISSUE TITLE
Element width is 0 when opening page in new tab in chrome on mac

### ISSUE THREAD

**Issue by oste** [jquery/jquery#2191]
I originally thought that this was just a Chrome bug, but the more I think about it this could be more jQuery related so I wanted to post here as well. I need to do further testing without jQuery as a dependency to be sure.

Using the following code will result in inconsistent behavior when opening the page in a **new tab** using target="_blank" for example. The width in the timeout is always correct, but the other output will be 0 **some of the time**.

```
  <div id="test"></div>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <script type="text/javascript">

    $(document).ready(function() {
        console.log($('#test').width());
        console.log(document.getElementById('test').offsetWidth);

        setTimeout(function() {
            console.log($('#test').width());
            console.log(document.getElementById('test').offsetWidth);
        }, 200);
    });

    </script>
```

Chromium issue for reference:
https://code.google.com/p/chromium/issues/detail?id=474315

**Comment by dmethvin** [comment]
Is the `.offsetWidth` incorrect and that happens even without jQuery in the test case? If so it sounds like a bug in Chrome.

**Comment by oste** [comment]
Unfortunately I have not had time to try without using jQuery for the $(document).ready features. This is the only place jQuery could be failing. Otherwise it would be a Chrome bug.

**Comment by timmywil** [comment]
Works for me. If a test case that can consistently reproduce becomes available, we can revisit. http://jsfiddle.net/timmywil/nohLe53k/show/

**Comment by oste** [comment]
@timmywil  your test is incomplete. You must open the link in a new tab using target="_blank"

**Comment by timmywil** [comment]
<a href="http://jsfiddle.net/timmywil/nohLe53k/show" target="_blank">link</a>

**Comment by mzgol** [comment]
jsFiddle is a poor site for such tests as it wraps everything in an iframe even in the "lite" mode. jsBin is better.

**Comment by oste** [comment]
I think its easy enough to reproduce on your own. Just create a simple html
file locally. It will fail.

On Thu, Apr 9, 2015 at 1:55 PM, Michał Gołębiowski <notifications@github.com
> wrote:

> jsFiddle is a poor site for such tests as it wraps everything in an iframe
> even in the "lite" mode. jsBin is better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jquery/jquery/issues/2191#issuecomment-91310087>.
>



-- 
Regards,
Mike

**Comment by mgol** [comment]
@oste Just to be sure I did create a local HTML file with the contents you provided and it works fine in Chrome 48.0.2564.97; I've tried multiple times.
