### ISSUE TITLE
Slidedown(), Slideup() help.

### ISSUE THREAD

**Issue by Copser** [jquery/jquery#2194]
I don't know is this the place to address this issue, but can anyone help me whit this question http://stackoverflow.com/questions/29506527/how-to-hover-change-toggle-a-picture-with-jquery/29508895#29508895, especially whit EDIT section.
I am trying to use jQuery's slidedown and slideup to animate mine hidden div image, you have a fiddle sample linked.
Thank you.

**Comment by dmethvin** [comment]
StackOverflow is the right place. This is for reporting jQuery bugs with a clear repro case.
