### ISSUE TITLE
`$.html` slower than `$.append` and `innerHTML`

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [jquery/jquery#2200]
Hello,

I made a jsperf testing the speed of DOM insertion operations and the results seemed strange to me.

`$.html` is 2 times slower than `$.append` and 3 times slower than innerHTML.

I tried to look at the code but I could no find out where this overhead come from. Any thoughts ? 

here is the jsperf : http://jsperf.com/creating-a-large-table-with-jquery

**Comment by dmethvin** [comment]
That's a pretty bogus jsperf. Don't do your own loops inside tests like that, jsperf does the looping for you to get a measurable test. Also there is a lot of code outside the actual `.append()` and `.html()` calls that could be taking time, for example the work to create the string. 

If you'd like to know more about jsperf or jQuery performance, post a question on our forum or on StackOverfow.
