### ISSUE TITLE
[FEATURE] Methods to 'submit' GET or POST to a page (no ajax)

### ISSUE THREAD

**Issue by JorisDebonnet** [jquery/jquery#2202]
I believe it should be possible to send GET or POST data to a page, and let the browser handle the response, as if it was a normal form submit (but without a pre-existing `<form>` tag). 

I feel like this would be a useful addition to the core, because many people expect it to already be available: many questions all over the internet are about "how to do this wih jQuery" (i.e. it's intuitively felt as if it should be doable without plugins). It's not ajax, but jQuery doesn't have to limit itself to usefulness in ajax applications, does it? I believe this makes sense because it's a pretty basic use-case. 

These methods might be called `.getPage` and `.postPage`, or `.formGET` and `formPOST`, or whatever would sound sensible. 

There are several ways to implement this; one is shown here:
http://stackoverflow.com/a/1876299/740813

**Comment by dmethvin** [comment]
Can't you just use `.serialize()` or `.serializeArray()`? I'm not sure why the StackOverflow answer is creating a form element in the first place.

**Comment by JorisDebonnet** [comment]
Well, it's meant for when you have data stored in javascript variables, but no `input` elements to work with. So I don't think `.serialize()` can be applied, since there are no elements to serialize. 

In any case, the challenge is not so much getting the string ready to send, but to actually send it in such a way that it's not handled as an ajax call, but as a 'real form submission'. I.e., the response will be an HTML page that will need to be rendered by the browser at whichever URL it's on. That's why that SO answer generates a form, in order to make the "native browser itself", rather than jQuery/javascript, send the data.

**Comment by dmethvin** [comment]
How would you say this scores against https://github.com/jquery/jquery/wiki/Adding-new-features ? It seems much more like a plugin.

**Comment by JorisDebonnet** [comment]
I see what you mean... it could certainly work as a plugin. Although it wouldn't cause harm in the core either, except I admit for a few hundred bytes (probably around 225 (minimized); not insignificant I know). I suppose the main question then is how generally useful it is. 

Let me go over the points on that page: 

It does not require access to jQuery internals, and I don't suppose jQuery itself can benefit from it (unless of course any future functionality would use it). It is sort of related to DOM operations (it actually acts as a way to yield form/data control from jQuery back to the DOM - if that makes sense). It's not currently served by an official plugin (although one could be made). It does not change any existing API, and doesn't go against best practice (afaik). 

I suppose the reason I came here is because it felt counter-intuitive that this functionality is so 'cumbersome' to achieve, by creating form and input elements and all that. But if there is no faster or cleaner way to do it within jQuery, I suppose it should just be a plugin.

**Comment by dmethvin** [comment]
Once it's inside a plugin, nobody sees that it's cumbersome. The people who need it can use the plugin, and the people who don't need it won't pay for it since we didn't build it in! :smiling_imp:
