### ISSUE TITLE
Stealth-empty input to replaceWith leaves content in place

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#2204]
e.g., `$collection.replaceWith([""])` is a no-op: http://jsfiddle.net/w03Lertu/

**Comment by markelog** [comment]
Is that a real use-case? Since in this docs i see - 

> May be an HTML string, DOM element, array of DOM elements

Since this would not be "array of DOM elements". What is byte-size and perf hit?

**Comment by gibson042** [comment]
This is necessary for gh-1747, because intercepted HTML can be replaced with an empty string.
