### ISSUE TITLE
edge case for self-closing tag detection

### ISSUE THREAD

**Issue by dgrad** [jquery/jquery#2205]
`element.html() ` automatically turns something like `<span />` into `<span></span>` before setting the html. this is broken if "/>" is found in an attribute (e.g. `<span data-foo="<test/>">example</span>` turns into `<span data-foo="<test></span>">example</span>`)

JSFiddle: https://jsfiddle.net/8oz5b4q5/

**Comment by gibson042** [comment]
This is a [known issue](http://bugs.jquery.com/ticket/14464), and will be addressable after #1747 is fixed. In the meantime, I recommend escaping `>` characters in attribute values as `&gt;`.

**Comment by timmywil** [comment]
gh-1747 has landed. https://jsfiddle.net/timmywil/84hu6cen/1/

**Comment by gibson042** [comment]
I'm unwilling to call this issue fixed while jQuery still does the wrong thing with such input.

**Comment by timmywil** [comment]
@gibson042 Good point.
