### ISSUE TITLE
jQuery.merge could be shorter

### ISSUE THREAD

**Issue by jfw10973** [jquery/jquery#2208]
it works good, but *might be* too long, use too much variable and cause so much loop if second is a big Array. 

*maybe* this is better: 

	 	var merge = function (first, second) {
			var tmp = [+first.length, 0];
	
			Array.prototype.splice.apply(first, tmp.concat(second));
	
			return first;
		}
do the same stuff and avoid  ["Array-like"#2155](https://github.com/jquery/jquery/issues/2155) puzzle, still maintain the first itself.

Or you guys have some other concern?

**Comment by gibson042** [comment]
It's a nice thought, but [doesn't appear to work](http://jsfiddle.net/zd8vayb8/) for Arraylike `second`, which is the very reason for having a merge function. Also, there's no avoiding a loop—this implementation actually incurs it _twice_, once in `concat` and once in `splice`.

**Comment by jaubourg** [comment]
How about using `push.apply`? Quick test seems to [work in Chrome](http://jsfiddle.net/jj7d61n1/). Unless I'm missing something of course.

**Comment by jaubourg** [comment]
As for `isArrayLike`, we may be able to rely on the VM by trying to `apply` using the object. Just a quick, untested, thought.

```js
function isArrayLike( object ) {
    try {
        jQuery.noop.apply( jQuery, object );
        return true;
    } catch( e ) {}
    return false;
}
```

**Comment by mzgol** [comment]
@jaubourg It's in the code, in a comment directly over `merge` definition.
;)

"push.apply(_, arraylike) throws on ancient WebKit"

**Comment by jaubourg** [comment]
The question is... how ancient? ;)

**Comment by dmethvin** [comment]
Not as bad as a year ago, but still over 6 percent of all Android. https://developer.android.com/about/dashboards/index.html

**Comment by mzgol** [comment]
Also, PhantomJS 1 which we're still trying to kind of support (hopefully we
can restrict it to v2 in jQuery 4).

**Comment by jaubourg** [comment]
*sob*

**Comment by jfw10973** [comment]
@gibson042 Thanks a lot, now I see you guys not just "How" but "Why" do this.
really appreciate your answer.
