### ISSUE TITLE
:depth selector

### ISSUE THREAD

**Issue by alexandernst** [jquery/jquery#2209]
After asking something similar [here](http://stackoverflow.com/questions/29627324/inserting-elements-without-affecting-children), I found [this](http://bugs.jquery.com/ticket/9391) bug report (feature request actually) back from 1.7 times. I'd like to reopen that issue for a discussion as I really think this would be useful.

**Comment by dmethvin** [comment]
We're not adding any new custom selectors to jQuery. For performance it's better to stay with the standard W3C CSS selectors. Also, as you can see from the discussion on the original ticket, there were no positive votes for the idea. However, if you are absolutely set on using this you can easily create a plugin for Sizzle that does it. https://github.com/jquery/sizzle/wiki#-pseudo-selectors-pseudos

**Comment by timmywil** [comment]
Thank you for opening an issue, but I think I can safely say that you'll get the same answers from the team. This is best done as a plugin and we do not want to add any more selector extensions to Sizzle that are not part of current or future Selector specs.

**Comment by timmywil** [comment]
@dmethvin jinx
