### ISSUE TITLE
Question about the behavior of `$()` wrapping a wrapped jQuery object.

### ISSUE THREAD

**Issue by cssmagic** [jquery/jquery#2214]
As a big fan and heavy user of jQuery, I got a question here.

(I've searched on StackOverflow, but found nothing helpful. Then I posted [my question](https://forum.jquery.com/topic/the-behavior-of-handling-a-jquery-object) on jQuery Forum, still got nothing.)

I noticed this paragraph in [jQuery's API doc](http://api.jquery.com/jQuery/#cloning-jquery-objects):

> #### Cloning jQuery Objects
> 
> When a jQuery object is passed to the `$()` function, a clone of the object is created. This new jQuery object references the same DOM elements as the initial one.

That means, if `$elem` is already a wrapped jQuery object, `$($elem)` will still unwrap-and-wrap the element(s) in `$elem` to create a new jQuery object, rather than returns `$elem` directly.

Initially, my workmates and I supposed that jQuery needed to re-query the selector of `$elem` to keep up with the modified DOM. Then we tried these codes:

```js
$wrapper.append('<p>test</p>')
var $elem = $('p')
$wrapper.append('<p>test2</p>')
var $elem2 = $($elem)
```

We found `$elem2` contained the same DOM element(s) as `$elem` did. That proved `$($elem)` didn't do any "re-query" thing.

So finally, we're confused about `$($elem)` -- why not return `$elem` directly when it's already a jQuery object. Any other purpose for creating (cloning) a new object?

**Comment by cssmagic** [comment]
BTW, we found [a related question on StackOverflow](http://stackoverflow.com/questions/24866923/jquery-object-constructor-optimization), and someone said,

> ... if I call a constructor, I simply expect to get a new object, and not get a reference to the one I pass in.

This answer sounds reasonable, but doesn't convince us, because we consider `$()` as not a constructor in a strict OO way, but a object wrapper (or an API entrance).

**Comment by dmethvin** [comment]
The set of elements in a jQuery object doesn't have any "memory" about the query that produced it, which is what the success of your example there would imply. 

> So finally, we're confused about $($elem) -- why not return $elem directly when it's already a jQuery object. Any other purpose for creating (cloning) a new object?

There are many things that could have been done there for example: explicitly say it's not supported, throw an explicit error, return the original object, or return a new set with the same elements. I don't  have a link to the original discussion on why the last option was chosen, but it seems like a perfectly cromulent choice.

This really is a forum or SO question since it's not a bug or feature request.

**Comment by scottgonzalez** [comment]
My understanding has always been that passing a jQuery instance has no special handling and is treated exactly the same as an array of elements.

**Comment by dmethvin** [comment]
I recall there being discussion at the time about whether passing in a jQuery object was valid and what it should do, I was talking more about the API behavior choice than the implementation.

**Comment by hax** [comment]
@dmethvin  I'm very curious about the rationales behind the choice. Especially Zepto seems choose diff behavior.

**Comment by cssmagic** [comment]
@dmethvin Thanks for your reply.

> This really is a forum or SO question since it's not a bug or feature request. 

Yes, it is. But only core development team here can answer this question. As I mentioned above, people out there ([jQuery Forum](https://forum.jquery.com/topic/the-behavior-of-handling-a-jquery-object) and [SO](http://stackoverflow.com/questions/24866923/jquery-object-constructor-optimization)) can only guess.

> ... I was talking more about the API behavior choice than the implementation.

No problem with current choice, it works fine. I just wanna known the reason to choose the current behavior.
