### ISSUE TITLE
Problem with animate(scrollTop) and css overflow-x hidden when body & html are both set to 100% width and height

### ISSUE THREAD

**Issue by rorykoehler** [jquery/jquery#2215]
Spent a few hours trying to get to the bottom of this before I figured out what is going on. I was trying to implement animated scroll with anchor links using animate(scrollTop) and the only thing that happened was the links broke completely. I found it strange as I was using previously functioning script (older version of jQuery) so I guess something broke in a recent update. The console shows no errors. I have tried many different versions of animated scroll so while I'm not 100% certain of my diagnosis I think I am in the right area. My coffeescript is something like this:

```
  $('a[href^="#"]').on 'click', (e) ->
    e.preventDefault()
    target = @hash
    $target = $(target)
    $('html, body').stop().animate { 'scrollTop': $target.offset().top }, 900, 'swing', ->
      window.location.hash = target
      return
    return
```

It works fine when the css is either:

````
html, body {
  overflow-x: hidden;
}
````

or

```
html, body {
  height: 100%;
  width: 100%;
}
```

but not when they are combined like this:

```
html, body {
  height: 100%;
  width: 100%;
  overflow-x: hidden;
}
```

This also happened when using 3rd party solutions [see here](https://github.com/kswedberg/jquery-smooth-scroll/issues/53).

**Comment by Mr21** [comment]
JSFiddle here: http://jsfiddle.net/Mr21/L7we5z72/

I like the way, you found a bug and you ask if it's the fault of the plugin you used.
After, you realize it's the fault of jQuery.
But... you have to continue and make an issue on Google Chrome directly :/
Because if you try to put: `document.body.scrollTop = 0;` it doesn't works neither.
And also because it's work on Firefox.

**But** this bug occurs only if the `html` **and** the `body` have the `overflow-x`, so you can just remove the `overflow-x` for the `html` and it's okay for you I think.

**Comment by rorykoehler** [comment]
You're right.  I've submited an issue through chrome. Closing issue here. Thanks

**Comment by mzgol** [comment]
> You're right. I've submited an issue through chrome.

Could you post a link to the issue here? Some people will be interested...

**Comment by rorykoehler** [comment]
I wish I could. I submitted through the browser "Help > Report an Issue..." menu and it didn't give me a url for issue tracking. I just checked and it's not on the Chromium bug list (the official build seems to be a separate repo). If and when I hear back I will update this thread. 

If you're interested you can have a look at this [stackoverflow thread](http://stackoverflow.com/questions/40703/where-can-i-find-and-submit-bug-reports-on-googles-chrome-browser) for more infos on google chrome bug tracking.

**Comment by mzgol** [comment]
> I wish I could. I submitted through the browser "Help > Report an Issue..." menu and it didn't give me a url for issue tracking.

That's why I generally prefer to submit bug reports manually at https://crbug.com. The built-in reporter is mostly useful to report bugs related purely to the official Chrome build and not Chromium; web-related issues generally concern the whole Chromium code base.

**Comment by sonus21** [comment]
Thank you I had same problem looking for a hour then  found this and solved finally.

**Comment by texelate** [comment]
It must be a webkit bug as it affects Chrome and Safari.

**Comment by mefynn** [comment]
it also effects firefox! even the fix with only setting overflow-x hidden on body (which fixed it for chrome an safari) doesnt work there

**Comment by ZombieProtectionAgency** [comment]
For anybody else curious about this issue I think this is the relevant chromium issue...
https://bugs.chromium.org/p/chromium/issues/detail?id=633573
