### ISSUE TITLE
for nested collapsible sets, the ui-collapsible-content div that is created also creates blank lines

### ISSUE THREAD

**Issue by rhysryan** [jquery/jquery#2216]
I have a button that brings up a popup containing a nest collapsible set.  All the code works properly except that there appears to be a blank line right beneath the header and list of items.

Here's my code:

    <div data-role="collapsibleset" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d" data-mini="true" style="margin:0; width:200px;">
        <div data-role="collapsible" data-inset="false">
            <h2>{Call Log Owner Actions}</h2>
            <ul data-role="list view">
                <li data-icon="false"><a href="javascript:(showUpdateCall('Left Word'));" class="ui-popup-actions-line">Left Word</a></li>
                <li data-icon="false"><a href="javascript:(showUpdateCall('Spoke in Person'));" class="ui-popup-actions-line">Spoke in Person</a></li>
            </ul>
        </div>

In my web inspector, I can see the blank lines right after the div is created, the one with the ui-body-inherit.  I'm not sure where these blank lines are coming from and want to make sure it isn't a bug somewhere.  Below is what the CSS looks like in my web inspector.

    <div data-role="collapsibleset" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d" data-mini="true" style="margin:0; width:200px;" class="ui-collapsible-set ui-group-theme-inherit ui-corner-all">
        <div data-role="collapsible" data-inset="false" class="ui-collapsible ui-collapsible-themed-content"> 
            <h2>heading</h2>
            <div class="ui-collapsible-content ui-body-inherit" aria-hidden="false">
            "         	"
            "         	     "
                <ui data-role="list view" class="ui-listview">

I truly believe this has to be something I'm doing wrong or missing.  Any help would be greatly appreciated.

**Comment by timmywil** [comment]
Please ask for help on the [forums](http://forum.jquery.com) or in the #jquery irc channel.
