### ISSUE TITLE
Self-closing tag inconsistency

### ISSUE THREAD

**Issue by pm-marcparmet** [jquery/jquery#2221]
`<div><img></img></div>` parses to `<div><img></div>`. That's ok.
`<div><input></input></div>` parses to `<div><input></div>`. That's ok.
`<div><br></br></div>` parses to `<div><br><br></div>`. Really? That's not ok.

https://jsfiddle.net/marcparmet/22h9zw87/1/

**Comment by motapc97** [comment]
I think that is the native behaviour

[https://jsfiddle.net/22h9zw87/2/](https://jsfiddle.net/22h9zw87/2/)

**Comment by timmywil** [comment]
`<br>` elements cannot have closing tags. https://developers.whatwg.org/text-level-semantics.html#the-br-element

**Comment by gibson042** [comment]
Correct. `br` are [void elements](https://html.spec.whatwg.org/#void-elements), and therefore _prohibited_ from having end tags.

**Comment by markelog** [comment]
@timmywil @gibson042 yeah, just like `input` and `img` elements but why `br` parses differently? 

In any case, this is incorrect html, so end result is unpredictable.
