### ISSUE TITLE
Do not expose jQuery.buildFragment method

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2224]
Since we will get this opportunity only i major version, marking it as a blocker

**Comment by justinbmeyer** [comment]
@dmethvin Was this removed in 2.2?  We were using this too.  Is there a list somewhere of any other privatized methods?

**Comment by dmethvin** [comment]
All the ones not documented at api.jquery.com are fair game. If you search for "do not expose" you can find them but the list i came up with earlier is  .dir, .sibling, .domManip, .buildFragment, .access, .swap

**Comment by justinbmeyer** [comment]
@dmethvin Yeah, I get that you can remove them all and be semver.  Thanks for the list.
