### ISSUE TITLE
Deprecate jQuery.unique

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#2228]
`jQuery.unique` is an [alias](https://github.com/jquery/jquery/blob/b561f5ab0a5e13f8203307016a02ee965a8be7d3/src/selector-sizzle.js#L9) to the better-named `Sizzle.uniqueSort`, and the fact that it sorts has [surprised even our own team members](http://irc.jquery.org/%23jquery-dev/default_%23jquery-dev_20150422.log.html#t08:50:51).

We should deprecate `jQuery.unique` in favor of `jQuery.uniqueSort` (which will need to be introduced).

**Comment by dcherman** [comment]
:+1:

Personally, all of my usage of `$.unique` has been for the side effect that it sorts the collection.  I usually end up doing `var sortByDomOrder = $.unique` to make that clear to people that aren't familiar with that side effect, so this name change will be nice.

**Comment by dmethvin** [comment]
SGTM too :+1:

**Comment by timmywil** [comment]
Woot! :+1:
