### ISSUE TITLE
Add catch to promise objects

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#2229]
Suggested implementation:

```js
catch: function( fn ) {
	return promise.then( null, fn );
}
```

**Comment by mzgol** [comment]
Dupe of #2102

**Comment by gibson042** [comment]
Agreed.

**Comment by mzgol** [comment]
@gibson042 I removed the milestone. Since GitHub issues don't distinguish between closed because it's been fixed and closed because it's invalid/duplicate/etc., we need to remove the milestone from all invalid tickets or they'll be incorrectly included in the changelog.
