### ISSUE TITLE
Selector ":not" for class does not working for parent element

### ISSUE THREAD

**Issue by stanekpa** [jquery/jquery#2230]
http://jsfiddle.net/u7n6xjrc/1/

**Comment by Florian-R** [comment]
No bug here. Your selector is inacurate. Fixed version : http://jsfiddle.net/ntronsya/

**Comment by stanekpa** [comment]
Fixed version is the same as mine.

**Comment by Florian-R** [comment]
Nope. Not the child selector `>`. Without this, every `.click` is cibled, because it descends (at least) from `.sandbox`, `html` and `body`

**Comment by stanekpa** [comment]
Thank You. Selector > works.

My selector was inaccurate as You wrote. Better selector is probably "div.click:not(.title .click)" because doesn't suppose direct descendants.
http://jsfiddle.net/u7n6xjrc/3/

Thank You for Your time.
