### ISSUE TITLE
IE9 pseudo selectors

### ISSUE THREAD

**Issue by mattgen88** [jquery/jquery#2231]
Under ie9, when using a pseudo selector library (http://www.appelsiini.net/projects/viewport) jQuery executes the selector on every element on the page, even though it was given an id for the element.

$('#id:in-viewport') causes :in-viewport to be executed on every element on the page
$('#id').is(':in-viewport'); obviously does not.

This is a huge performance issue under IE9. This does not happen under chrome and likely under other browsers.

I unfortunately do not have the expertise in jQuery to determine where exactly the issue lies so I cannot provide a patch at this moment. However, I would suspect that this would be a great performance optimization for older browsers where if the CSS selector is given an ID, it first searches by that instead of executing the pseudo selector code.

I tested this in IE9, windows 7. Also tested in Chrome 42 on GNU/Linux (arch). jQuery version 1.11.2. 

Yes I realize that I'm talking about a 3rd party add on for jQuery, I do not think it is the issue since the method defined for the :in-viewport ($.inviewport) is being called different numbers of times depending on browser version. In IE9, it gets called hundreds of times with elements that are not the one specified by ID. Under chrome it is just the element specified by ID. It appears to be how jQuery handles ID selectors.

The use case I have is a site with an infinite stream of items. I need to do something as the cards come into the viewport. I have a list of IDs for the cards so I iterate over the IDs and run the in-viewport pseudo selector on them. I have a list of 30 ids that gets pared down when each item has entered the view port. Under IE, performance was abysmal. running in-viewport 30 times shouldn't be too terrible, and indeed it isn't unless you're on IE9.

**Comment by gibson042** [comment]
> I would suspect that this would be a great performance optimization for older browsers where if the CSS selector is given an ID, it first searches by that instead of executing the pseudo selector code.

This is in fact what Sizzle, jQuery's selector engine, does. But unfortunately, the optimization is [disabled for IE<10](https://github.com/jquery/sizzle/commit/516a8ad630655d2cd8c67bf75ac2550b640dd5ee#diff-7d34356c0b7229dd5da8b6c7711b32b7) because those browsers have broken `getElementById` methods that return elements with _name_ attributes equal to the desired id. Still, the current behavior is probably excessive, and I just opened a [Sizzle issue](https://github.com/jquery/sizzle/issues/333) to address it.

**Comment by mgol** [comment]
@gibson042 Why the "Awaiting Sizzle Update" label? It's not fixed in Sizzle.

BTW, do we need to keep this ticket open here considering we don't know when we can get to it?

**Comment by timmywil** [comment]
"Awaiting Sizzle Update" doesn't mean it's fixed in Sizzle. It means it requires a fix in Sizzle.

However, I agree that we might as well close this. I see no solution right now and we can rely on Sizzle to address its own performance issues.

**Comment by gibson042** [comment]
FWIW, I just fixed this in Sizzle: https://github.com/jquery/sizzle/commit/6bc91da520a45d82d46d2796bb0ccacf3559cdb3

But I agree with keeping it closed here anyway.

**Comment by mgol** [comment]
The above Sizzle commit was included in Sizzle `2.3.1`. The Sizzle `2.3.1` update landed in 9526557e677abd237f8b299108b454a8532e7d5a which got into jQuery `3.1.1`. Let me set the milestone appropriately.
