### ISSUE TITLE
Multiple JavaScript errors in jquery.min.js and jquery.js

### ISSUE THREAD

**Issue by mmokrejs** [jquery/jquery#2236]
I enabled DEBUG output from seamonkey/firefox browser and here are a number of jQuery-related errors. It is a mix of version but some are for sure the current, 1.11.2 version.

<pre>
$ grep jquery /tmp/seamonkey.log| sort | uniq | sort
Document http://github.com/jquery/jquery loaded successfully
Document http://jquery.com/ loaded successfully
Error loading URL https://github.com/login?return_to=%2Fjquery%2Fjquery : 804b0002 (NS_BINDING_ABORTED)
JavaScript error: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 3: Error: Syntax error, unrecognized expression: [@name=username]
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 2: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 3: ReferenceError: reference to undefined property a.result
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 3: ReferenceError: reference to undefined property a[h]
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 3: ReferenceError: reference to undefined property d.attributes[c].expando
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 3: ReferenceError: reference to undefined property i.disabled
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 3: ReferenceError: reference to undefined property j.delegateType
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 3: ReferenceError: reference to undefined property m.event.triggered
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 3: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 3: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 4: ReferenceError: reference to undefined property a[v.status]
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 4: ReferenceError: reference to undefined property k.headers
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, line 4: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js, line 2: ReferenceError: reference to undefined property e[u]
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js, line 2: ReferenceError: reference to undefined property t[0]
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js, line 2: ReferenceError: reference to undefined property v.cache[e[v.expando]]
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js, line 2: ReferenceError: reference to undefined property v.event.triggered
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js, line 2: ReferenceError: reference to undefined property v.valHooks[this]
JavaScript strict warning: http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js, line 2: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://jquery.com/jquery-wp-content/themes/jquery/js/modernizr.custom.2.8.3.min.js, line 4: ReferenceError: reference to undefined property d.shivCSS
JavaScript strict warning: http://jquery.com/jquery-wp-content/themes/jquery/js/plugins.js, line 24: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://jquery.com/jquery-wp-content/themes/jquery/js/plugins.js, line 27: TypeError: variable b redeclares argument
JavaScript strict warning: http://jquery.com/jquery-wp-content/themes/jquery/js/plugins.js, line 29: TypeError: variable b redeclares argument
JavaScript strict warning: http://jquery.com/jquery-wp-content/themes/jquery/js/plugins.js, line 30: TypeError: variable b redeclares argument
JavaScript strict warning: http://jquery.com/jquery-wp-content/themes/jquery/js/plugins.js, line 7: TypeError: variable x redeclares argument
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 16: ReferenceError: reference to undefined property a.nodeType
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 16: ReferenceError: reference to undefined property a.selector
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 16: ReferenceError: reference to undefined property a[0]
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 16: ReferenceError: reference to undefined property a[f.expando]
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 16: ReferenceError: reference to undefined property f.event.triggered
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 16: ReferenceError: reference to undefined property f.valHooks[this]
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 16: ReferenceError: reference to undefined property f[0]
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 16: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 17: ReferenceError: reference to undefined property a.returnValue
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 17: ReferenceError: reference to undefined property a[d]
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 17: ReferenceError: reference to undefined property c.result
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 17: ReferenceError: reference to undefined property c[0]
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 17: ReferenceError: reference to undefined property i.sizcache
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 17: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 18: ReferenceError: reference to undefined property a.cache
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 18: ReferenceError: reference to undefined property d.queue
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 18: ReferenceError: reference to undefined property d.traditional
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 18: ReferenceError: reference to undefined property e.queue
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 18: ReferenceError: reference to undefined property f.ajaxSettings.traditional
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 18: ReferenceError: reference to undefined property h[j]
JavaScript strict warning: http://mbe.oxfordjournals.org/shared/js/jquery-min.js, line 18: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://oi-underbar.ifactory.com/underbar/js/jquery-ui.min.js, line 3427: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://oi-underbar.ifactory.com/underbar/js/jquery-ui.min.js, line 3430: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://oi-underbar.ifactory.com/underbar/js/jquery-ui.min.js, line 3433: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://oi-underbar.ifactory.com/underbar/js/jquery-ui.min.js, line 3436: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://oi-underbar.ifactory.com/underbar/js/jquery-ui.min.js, line 3439: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://oi-underbar.ifactory.com/underbar/js/jquery-ui.min.js, line 3452: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://portal.chmi.cz/portal/chmu/js/jquery.js, line 19: ReferenceError: reference to undefined property jQuery.cache[id][name]
JavaScript strict warning: http://portal.chmi.cz/portal/chmu/js/jquery.js, line 21: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
JavaScript strict warning: http://portal.chmi.cz/portal/chmu/js/jquery.js, line 24: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://portal.chmi.cz/portal/chmu/js/jquery.js, line 25: ReferenceError: reference to undefined property elem.nodeType
JavaScript strict warning: http://portal.chmi.cz/portal/chmu/js/jquery.js, line 25: ReferenceError: reference to undefined property p[i]
JavaScript strict warning: http://portal.chmi.cz/portal/chmu/js/jquery.js, line 25: ReferenceError: reference to undefined property ret[i]
JavaScript strict warning: http://portal.chmi.cz/portal/chmu/js/jquery.js, line 25: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://portal.chmi.cz/portal/chmu/js/jquery.js, line 26: ReferenceError: reference to undefined property event[expando]
JavaScript strict warning: http://www.chmi.cz/portal/chmu/js/jquery.js, line 19: ReferenceError: reference to undefined property jQuery.cache[id][name]
JavaScript strict warning: http://www.chmi.cz/portal/chmu/js/jquery.js, line 21: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
JavaScript strict warning: http://www.chmi.cz/portal/chmu/js/jquery.js, line 24: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://www.chmi.cz/portal/chmu/js/jquery.js, line 25: ReferenceError: reference to undefined property elem.nodeType
JavaScript strict warning: http://www.chmi.cz/portal/chmu/js/jquery.js, line 25: ReferenceError: reference to undefined property p[i]
JavaScript strict warning: http://www.chmi.cz/portal/chmu/js/jquery.js, line 25: ReferenceError: reference to undefined property ret[i]
JavaScript strict warning: http://www.chmi.cz/portal/chmu/js/jquery.js, line 25: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://www.chmi.cz/portal/chmu/js/jquery.js, line 26: ReferenceError: reference to undefined property event[expando]
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 2: ReferenceError: reference to undefined property a.nodeName
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 2: ReferenceError: reference to undefined property a[h]
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 2: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 3: ReferenceError: reference to undefined property a.result
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 3: ReferenceError: reference to undefined property d.attributes[c].expando
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 3: ReferenceError: reference to undefined property e[d]
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 3: ReferenceError: reference to undefined property i.disabled
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 3: ReferenceError: reference to undefined property j.delegateType
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 3: ReferenceError: reference to undefined property m.event.triggered
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 3: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 3: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js, line 4: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 2: ReferenceError: reference to undefined property a.nodeType
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 2: ReferenceError: reference to undefined property c[b]
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 2: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 3: ReferenceError: reference to undefined property a.result
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 3: ReferenceError: reference to undefined property l.delegateType
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 3: ReferenceError: reference to undefined property n.event.triggered
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 3: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 3: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 4: ReferenceError: reference to undefined property a.username
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 4: ReferenceError: reference to undefined property a[v.status]
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 4: ReferenceError: reference to undefined property k.traditional
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 4: ReferenceError: reference to undefined property n.ajaxSettings.traditional
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js, line 4: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js, line 5: ReferenceError: reference to undefined property e.uiBackCompat
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js, line 5: ReferenceError: reference to undefined property n[u]
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js, line 5: ReferenceError: reference to undefined property t[1]
JavaScript strict warning: https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js, line 5: ReferenceError: reference to undefined property this.timer
JavaScript strict warning: https://assets-cdn.github.com/assets/frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js, line 175: ReferenceError: reference to undefined property e.jquery
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery-ui-addons.js, line 12: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery-ui-addons.js, line 12: TypeError: variable a redeclares argument
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery-ui-addons.js, line 12: TypeError: variable b redeclares argument
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery-ui-addons.js, line 12: TypeError: variable c redeclares argument
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery-ui.js, line 5: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 2: ReferenceError: reference to undefined property a[f.expando]
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 2: ReferenceError: reference to undefined property a[j]
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 2: ReferenceError: reference to undefined property f.cache[a[f.expando]]
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 2: ReferenceError: reference to undefined property f.valHooks[this]
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 2: ReferenceError: reference to undefined property g.type
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 2: ReferenceError: reference to undefined property this[a]
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 2: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 3: ReferenceError: reference to undefined property a.returnValue
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 3: ReferenceError: reference to undefined property c.result
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 3: ReferenceError: reference to undefined property f.event.triggered
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 3: ReferenceError: reference to undefined property n.set[0]
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 3: ReferenceError: reference to undefined property s.delegateType
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 3: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 4: ReferenceError: reference to undefined property d.cache
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 4: ReferenceError: reference to undefined property j[k]
JavaScript strict warning: https://issues.adblockplus.org/chrome/common/js/jquery.js, line 4: SyntaxError: test for equality (==) mistyped as assignment (=)?
</pre>

**Comment by mzgol** [comment]
These look like linter errors. We have our code tested via jsHint, the warnings you pasted are just more restrictive than jQuery code base rules.

There is nothing wrong with jQuery here, applying custom restrictive linting rules may always report lots of warnings, in any project.

**Comment by mmokrejs** [comment]
Hmm, maybe the comment #1 from https://bugzilla.mozilla.org/show_bug.cgi?id=1158522 could be applied to your code? ;-)

**Comment by dmethvin** [comment]
Are you running jQuery in `"use strict"` mode? You should never force code into strict mode that wasn't  tested for it. jQuery [cannot run](https://github.com/jquery/jquery/blob/002240a6eb1cee2fcd886d5cf44893eb67f246f1/src/intro.js#L40-44) in strict mode, the same Firefox that is complaining there prevents it because of issues with strict/non-strict mixing.

**Comment by mmokrejs** [comment]
Don't know. I compiled seamonkey from sources with CFLAGS="$CFLAGS -DDEBUG -DNDEBUG" CXXFLAGS=$CFLAGS configure --disable-optimize ... ;)

Please could you answer the original bug report and suggest mozilla developers to drop this habit then?

**Comment by dmethvin** [comment]
This isn't a jQuery bug and I'm not even sure what we would report since we don't have a test case. jQuery is working properly in all the browsers we support. If a custom compiled SeaMonkey isn't working properly you'd need to debug that or report it to an appropriate place.
