### ISSUE TITLE
attr('checked') do not work anytime 

### ISSUE THREAD

**Issue by berlingofr** [jquery/jquery#2240]
To check a radio button from an external label tag object i am using " $("#motif").attr('checked', true)"
It work only the first time you click.
I have try removeAttr() before using attr() but it is the same.

But with JS code il work everytime.
document.getElementById('motif').checked=true;

See the demo of this probleme
https://jsfiddle.net/hvf8h077/

**Comment by markelog** [comment]
That's because you changing the attribute not the property of DOM element - use http://api.jquery.com/prop/

More info about it - http://api.jquery.com/attr/#entry-longdesc

**Comment by berlingofr** [comment]
Thanks a lot for this answer.
Now I know the difference between attr and prop.
It was very helpfull for me
