### ISSUE TITLE
jQuery already loaded

### ISSUE THREAD

**Issue by ikender** [jquery/jquery#2246]
at the beginning of the file, there should be a script that checks if jQuery is running, and if it is then write a console log "jQuery 1.10.1 instantiated already, you are trying to load jQuery 1.11.2"

this won't fix older versions, but it will help developers for the future

**Comment by timmywil** [comment]
Thank you for opening an issue. While multiple versions of jQuery on a page is not recommended, it is allowed. If you'd just like to see logs on which versions of jQuery are currently on the page, I think this is best done as a plugin. Something like...

```js
var tmp = jQuery;
var j = jQuery.noConflict(true);
while (typeof jQuery !== "undefined") {
  console.log(j.version);
  j = jQuery.noConflict(true);
}
window.jQuery = window.$ = tmp;
```
