### ISSUE TITLE
jQuery allows strings and objects as event handlers => error thrown

### ISSUE THREAD

**Issue by acasademont** [jquery/jquery#2248]
http://jsfiddle.net/t7da32og/

Click the button and that will make the browser throw an error. In the `on` function code is checked that the `fn` var is not `false` or whatever value the `if (!fn)` condition matches (0, null). But strings and objects are allowed and then the `handler.apply` function will of course fail.

My question is, is there a reason why these 2 types are not checked and the callback is not discarded? If not, I'll be more than happy to submit a PR to fix the issue!

**Comment by timmywil** [comment]
Thank you for opening an issue, but if passing `"click"` as the first argument, our [docs](http://api.jquery.com/on/) say that a handler function is required. Passing an object there is not supported.

**Comment by acasademont** [comment]
@timmywil  Yes I know that, but if there are guard checks for `false` `0` or `null` values why not for strings and objects? I'm seeing some random errors in my JS profiling tool caused by who-knows-what-random-external-code that could be avoided by these checks

**Comment by acasademont** [comment]
I'm talking about this https://github.com/jquery/jquery/blob/master/src/event.js#L820-L824

**Comment by acasademont** [comment]
IMHO a `typeof string || typeof object` check wouldn't hurt any performances as 99.99% of events are done right :)

**Comment by timmywil** [comment]
In this case, I'd actually prefer an error be thrown. Why make the call at
all if it's not going to do anything? Anyway, our general policy in these
cases is, invalid input will produce unexpected results.

**Comment by markelog** [comment]
@timmywil why do we check for falsy values? Perhaps we should remove that check?

**Comment by acasademont** [comment]
And I agree 100% with you but there are tons of 3rd party rubbish scripts that browsers embed as extensions (viruses/trojans/malware...) that cause our JS profiling tools (we are using errorception) to be filled with this "faux" errors caused by all sorts of external hacks. I'm afraid we really can't control that code :(

For example in the `addClass` code there's a guard check for a string value https://github.com/jquery/jquery/blob/master/src/attributes/classes.js#L13

Instead of the current code a check for `function` would come handy.

**Comment by acasademont** [comment]
instead of

```javascript
if ( fn === false ) {
    fn = returnFalse;
} else if ( !fn ) {
    return this;
}
```

this

```javascript
if ( typeof fn !== "function" ) {
    return this;
}
```
PS: still not sure why there's a separate case for `false`

**Comment by markelog** [comment]
@acasademont 

> A function to execute when the event is triggered. The value false is also allowed as a shorthand for a function that simply does return false.

From http://api.jquery.com/on/, there is couple use-cases for it.

**Comment by timmywil** [comment]
The point is to check for the presence of a function. `!fn` is just shorter than `typeof fn !== "function"`. We don't really care that it guards for `0` and `null`. That is just a side-effect and really supported either.

**Comment by acasademont** [comment]
I don't see it a terrible thing to lose 18 bytes in the minified version (a mere 4 bytes in the gzipped one) and polish some edge cases, there are already lots of  `typeof whatever` guard checks in the code. But that's your choice :)

Thanks for your time!

**Comment by scottgonzalez** [comment]
> I don't see it a terrible thing to lose 18 bytes in the minified version (a mere 4 bytes in the gzipped one) and polish some edge cases

Keep in mind that you would multiply that number by some fraction of the size of the public API. It's never just 4 bytes.

> there are already lots of `typeof whatever` guard checks in the code.

Most of these are not guards against invalid code, but rather support for public APIs where the's some parameter overloading.

**Comment by dmethvin** [comment]
The specific check for `false` is because the API supports that value as a shorthand for `function() { return false; })`. 

The check for not being a function is part of our past (perhaps ill-advised in retrospect) attempts to silently accept just about any invalid combination of arguments, making end-user debugging very difficult. 

> I'm seeing some random errors in my JS profiling tool caused by who-knows-what-random-external-code that could be avoided by these checks

Random errors are avoided in what way? The calls were clearly made for some reason, and this change would convert them to no-ops. But what were they trying to do that now isn't being done? The lack of error messages doesn't mean the page is working properly, and the error messages may be the only way of diagnosing what the code was trying to do.

**Comment by acasademont** [comment]
@dmethvin the thing is that the error is thrown when the event is fired, not when the event is binded. That makes it VERY hard to debug if you have tons of events,. You can't really know which event bind caused the bad param. And again, that's not even on my code but on a 3rd party script

I would be fine with an exception thrown if the `fn` param is not a function. Would that be ok instead of the silent fail there's now?

**Comment by dmethvin** [comment]
Having jQuery ignore the problem will not help you debug it. If you are wondering who sets the event on the element, set a conditional breakpoint in `.on()` that looks for a non-`function` `fn`.

**Comment by acasademont** [comment]
@dmethvin It's not in my code nor it's happening to me, can't do that. I am using a cool reporting tool (http://errorception.com) that catches all js errors our customers have.

Here you can see one of these stack traces I get. No clue in the stack about who bound that event and why. The stack only provides info of the calls that led to the fire event.

```
jQuery.event.dispatch@...jquery-2.1.3-custom-2.js:2537:15
jQuery.event.add/elemData.handle@...jquery-2.1.3-custom-2.js:2215:6
jQuery.event.trigger@...jquery-2.1.3-custom-2.js:2444:5
.trigger/<@...jquery-2.1.3-custom-2.js:3004:4
.each@...jquery-2.1.3-custom-2.js:374:14
jQuery.prototype.each@...jquery-2.1.3-custom-2.js:139:10
.trigger@...jquery-2.1.3-custom-2.js:3003:1
r/<@...common.381810d5.js:2:12495
jQuery.Callbacks/fire@...jquery-2.1.3-custom-2.js:1193:10
jQuery.Callbacks/self.fireWith@...jquery-2.1.3-custom-2.js:1305:7
done@...jquery-2.1.3-custom-2.js:6331:5
.send/callback/<@...jjquery-2.1.3-custom-2.js:6660:1
``` 

That's why I hate this error because I really can't do much about it. An error at the time of the event-binding would come very handy.

**Comment by dmethvin** [comment]
You're building a custom jQuery (which is great!) so you can add whatever you want. Just check for bad values and throw your own error. Also good that you're monitoring for errors. These are all best practices. jQuery discarding bad inputs is not, and we can't throw an error for every misuse of the API because it takes too many bytes.

**Comment by markelog** [comment]
okay, then, since *my* question wasn't answered and in order to clutter the discussion i just open a pull for my answer on the matter - https://github.com/jquery/jquery/issues/2249

**Comment by acasademont** [comment]
That's precisely what I'm trying to do, but I'm not a big fan of having custom-built libs when I can suggest these changes to upstream. But I understand your point, we can end the discussion here :=)

Thank you all again!

@markelog I'd be +1 on your change, it's consistent with the opinions posted here about the no-guards-if-not-absolutely-necessary policy (and that's 23 bytes less on the minified version :p)
