### ISSUE TITLE
jQuery.map is inconsistent with standard

### ISSUE THREAD

**Issue by ars265** [jquery/jquery#2253]
Currently jQuery.map takes a callback then when executing over the dataset the index is the first argument and the value is the second but per the JavaScript array prototype map function (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), these two are swapped. Is there a reason that jQuery is not consistent with the JavaScript standard?

**Comment by gibson042** [comment]
The first two arguments _are_ consistent: http://jsfiddle.net/kbpavofd/

You may be thinking of `jQuery.each` vs. `Array.prototype.forEach`, which is a known issue: #2105

**Comment by ars265** [comment]
@gibson042 Sorry for the confusion but I meant jQuery( selector ).map( fn ), not jQuery.map( array, fn ). As per the [jQuery documentation](http://api.jquery.com/map/).

**Comment by gibson042** [comment]
I see (and updated the description accordingly). That is quite unfortunate, but I still don't think we can do anything about it at this late juncture.

**Comment by ars265** [comment]
That is as I expected, but better for it to be known.
