### ISSUE TITLE
Only load the parts that are wanted.

### ISSUE THREAD

**Issue by IngwiePhoenix** [jquery/jquery#2256]
The typical component, or "require() what you need", model is becoming not just familiar, but it feels like as it is on its way of becoming a standard.

Current jQuery supports AMD and CommonJS. But what it lacks is the ability to be split. Let's say I know that the two jQuery plugins I need only require basic DOM manipulation (setting attributes) and eventing (click and keydown event). Then I would only need an approximately 1/10 of what jQuery offered.

When looking into 2.1.4's `src/` folder, I noticed that `jquery.js` actually uses `define()` to load dependencies.

My question is: If I re-wrote this file to my liking and only loaded the modules I wanted, would that result in a smaller jQuery footprint? 

I am currently using [WebPack](https://github.com/webpack/webpack) for my project, and already managed to bring Bootstrap down a couple KBs by excluding the features I did not want. Now I want to do the same to jQuery.

Especially with Bootstrap reduced, I realized that it also does not need the entire potential of jQuery. For instance, I see no where where Bootstrap would use the AJAX functionalities.

Kind regards, Ingwie.

**Comment by mzgol** [comment]
You can require individual modules from `jquery/src/**/*.js` in your app that you need and ignore `jquery/src/jquery.js` completely; WebPack (it does support AMD, doesn't it?) should then do its magic and ignore the modules that are outside of the dependency tree. Doesn't it work for you?

**Comment by IngwiePhoenix** [comment]
Indeed, WebPack supports AMD, CommonJS and the UMD format. Awesome, very godo to know! I will do that, then. :)

Thanks for your reply.
