### ISSUE TITLE
$.extend should concat arrays

### ISSUE THREAD

**Issue by steelbrain** [jquery/jquery#2258]
```js
$.extend({a: null}, {a:['a']}, {a:['b']}).a.length === 1; //should be two!
```

**Comment by rwaldron** [comment]
There is no way to define unambiguous semantics for that suggestion and the change would break all extant code relying on the documented behavior.

**Comment by steelbrain** [comment]
Does the current $.extend behavior feel right to you? because it clearly does not to me. $.extend should extend arrays, not replace them totally. the value of that `a` should be `['a','b']` after extending, not `['b']`.

**Comment by rwaldron** [comment]
Yes, it does. If you treat an Array as an object (because it is), then the index `0` is just a property, and the last property of that name will win. Look at it like this: 

```js
$.extend({ a: null }, {a: { 0: "a" } }, {a: { 0: "b" } });

// Result: 

{ 
  a: { 
    0: "b"
  }
}
```

**Comment by mzgol** [comment]
This is also what lodash's _.assign and ES6 Object.assign does. So this behavior is definitely right.

**Comment by rwaldron** [comment]
Yep, when I designed `Object.assign`, I used the cross section of all well known implementations :)

**Comment by mzgol** [comment]
> Yep, when I designed `Object.assign`

I shouldn't have jumped here before you! :)
