### ISSUE TITLE
$.html(htmlString) wrong parse

### ISSUE THREAD

**Issue by Selektor** [jquery/jquery#2263]
http://jsfiddle.net/xobcwufx/

In attached example, "div" should be inside "p".

**Comment by alburthoffman** [comment]
this is because p is inline element by default. And div is block element. 

The spec says a block element cannot be placed inside an inline element. 

So......

**Comment by yangjunjun** [comment]
it's **browser** not jQuery divide p tag to two element and it is a normal behavior, pls refer to [W3C specs] (http://www.w3.org/TR/html401/struct/text.html#edef-P)
>The P element represents a paragraph. It cannot contain block-level elements (including P itself).

**Comment by mzgol** [comment]
Yup. Opening a `div` implicitly closes the opened `p`. See also #2167, in particular the comment https://github.com/jquery/jquery/issues/2167#issuecomment-86195786.

**Comment by Selektor** [comment]
Thank you for the quick reply.
