### ISSUE TITLE
jQuery.fn.jquery might indicate `compat`

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2269]
To be in line with #1862, could `jQuery.fn.jquery` on `compat` be `3.0.0-pre+compat` instead of current `3.0.0-pre`?

**Comment by timmywil** [comment]
+1, we'll just need to drop the suffix during the release process.

**Comment by timmywil** [comment]
Actually, no we won't. :)

**Comment by timmywil** [comment]
I noticed that I had the tag suffix wrong in build.js. I've updated that too.

**Comment by mzgol** [comment]
We're not releasing `compat` anymore and this commit is irrelevant to 1.12 so I'm removing the milestone & adding the wontfix label.
