### ISSUE TITLE
I want to submit a Pull Request for a New Feature, but how?

### ISSUE THREAD

**Issue by cauerego** [jquery/jquery#2273]
I'm having trouble on finding what's [the proper process](https://github.com/jquery/jquery/pull/637#issuecomment-3122313). I did read a few docs [here](https://learn.jquery.com/contributing) and [there](http://contribute.jquery.org/commits-and-pull-requests), and still got no clue on how's better to proceed.

Just for context, [here's my proposal](http://stackoverflow.com/a/30089307/274502). But please do keep this issue on topic to help future people! ;)

**Comment by timmywil** [comment]
Well, opening an issue is a good start! However, I recommend editing this issue to be the actual feature proposal. If you'd like an issue to be open concerning the clarity of contribute.jquery.org on how to get involved, then I'd tell you to open an issue on that repo. Thank you for your willingness to contribute!

**Comment by cauerego** [comment]
I'd sure like an issue to be open about how not clear "contribute.jquery.org" was to me, but... I won't bother about it for now.

I just opened [a new issue](https://github.com/jquery/jquery/issues/2280) for my feature proposal then, and edited this one to remove it from here. :)

Thanks, @timmywil

**Comment by timmywil** [comment]
Ok, thank you @cauerego.
