### ISSUE TITLE
It is odd when using "attr" on checkbox, it works on the first time only

### ISSUE THREAD

**Issue by LeonLi0102** [jquery/jquery#2274]
<pre>
<textarea>

<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>Checkbox Test</title>
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script>
	$().ready(function(){		
		$("#checkControl").click(function(){			
			// It is odd it works on the first time whey you click 'All/None' only 
			 $("input[name='check_items']").attr("checked",this.checked);
			 
			// I know this will work, but still the code above is confused me.
			// $("input[name='check_items']").prop("checked",this.checked);
			 
		});		
	});		
	</script>
</head>
<body>
<input type="checkbox" id="checkControl" >All/None<br /><br />
<input type="checkbox" name = "check_items" >item1<br />
<input type="checkbox" name = "check_items" >item2<br />
</body>
</html>

</textarea>
</pre>

**Comment by alburthoffman** [comment]
this relates to difference between attr and prop. And I'm very confused!

I remember checked attribute only affects defaultChecked property. But checked property is the one showing it's checked or not.

**Comment by scottgonzalez** [comment]
Please read the documentation about boolean attributes on http://api.jquery.com/attr/.
