### ISSUE TITLE
:disabled selector inconsistent in different browsers

### ISSUE THREAD

**Issue by arschmitz** [jquery/jquery#2275]
When an input is disabled by its parent fieldset the `:disabled` selector behaves differently in IE ( any version ) then other browsers. In other browsers the `:disbaled` selector will indicated an input disabled by a parent fieldset, where in IE it will say it is not disabled.

http://jsbin.com/padopu/3/edit?html,js,output

My first thought was sizzle was falling back to QSA and the `:disabled` selector where available and this was not working correctly in IE, but QSA works correctly in IE9-Edge for this. 

There seems to also be a related documentation issue as the docs say this always checks the disabled prop. see jquery/api.jquery.com#734

**Comment by gibson042** [comment]
I've been hemming and hawing about jquery/sizzle/pull/283 for a while because of the size, but should probably just land it. What's going on is that IE's `:disabled` selector does not pick up the children of disabled fieldsets, but other modern browsers get it right except when selection goes through the Sizzle engine (as opposed to `querySelectorAll`), which has IE-like behavior relying solely upon the `disabled` property.

**Comment by arschmitz** [comment]
@gibson042 that does not seem to be the case if you look at that jsbin `querySelectorAll` works correctly with the `:disabled` selector for children for fieldsets in IE ( > 9 of course )

**Comment by arschmitz** [comment]
@gibson042 actually sorry the regular css selector `:disabled` does not work in IE for children of fieldsets, but `querySelectorAll` with `:disabled` does work correctly

**Comment by gibson042** [comment]
There's a bug in your jsbin. `document.querySelectorAll` returns a NodeList (which is always truthy); you want to check the `length` property: http://jsbin.com/xanukakofe/1/edit?html,js,output

**Comment by arschmitz** [comment]
ah your right sorry about that and sure enough that does fail in IE.

**Comment by timmywil** [comment]
Yea, I guess it's time. Grrrr @arschmitz!

**Comment by arschmitz** [comment]
Once that lands should probably address https://github.com/jquery/api.jquery.com/issues/734 as it will be extra wrong then. Some what related the documentation for `:disabled` does not consider `fieldsets` an element that can be disabled, and in IE the selector does not work on `fieldsets` . However it does work in other browsers @gibson042 will jquery/sizzle#283 address that as well?

**Comment by gibson042** [comment]
It will, and I just left a note to test that case explicitly.

**Comment by gibson042** [comment]
Fixed in [Sizzle v2.3.0](https://github.com/jquery/sizzle/commit/7999a01cf7bc92fb7d2951b4ad7442dbbd788e7f)

**Comment by timmywil** [comment]
Fixed by 5c4be05d3b32456553dc944853b77fa96ae8b2b8
