### ISSUE TITLE
[New Feature] [PR proposal] Tree Traversal: .below()

### ISSUE THREAD

**Issue by cauerego** [jquery/jquery#2280]
Here's my full proposal: http://stackoverflow.com/a/30089307/274502

In short, it would get the first element found below, in the DOM tree.

No, `.next()` and `.siblings()` or `.nextAll()` won't cut it. Nor will any other method under the [Tree Traversal category](https://api.jquery.com/category/traversing/tree-traversal/). And I do use this quite often so I suppose there might be a good use for having such feature... But I'm not sure how elegant it would be.

Javascript does have a similar function to work around this, `compareDocumentPosition` (found thanks to the other answer on that SO question), but it's not as compatible as using the universal selector with `.index()`.

I'm also pretty sure this isn't the best implementation for the need, but it works. I'd love to hear comments on how to improve it as well. :)

**Comment by timmywil** [comment]
My opinion here is that this would be best implemented as a plugin, at least for now. If it gains enough traction and we receive more requests to put it in core, then we would consider adding it. We're very wary about adding new methods to core at this point.

**Comment by arthurvr** [comment]
> My opinion here is that this would be best implemented as a plugin, at least for now. 

Same feeling over here.

**Comment by cauerego** [comment]
That'd be cool, I guess. I've never really used any plugins, let me go ahead and research on how [that](https://plugins.jquery.com/) would work...

**Comment by dmethvin** [comment]
Closed, since this should be done as a plugin first.

**Comment by cauerego** [comment]
From the SO's full proposal thread, I'd guess the plugin would have no traction anyway! ;P
