### ISSUE TITLE
css method returns incorrect background-color for select-box options in Firefox.

### ISSUE THREAD

**Issue by alfonsoGarnett** [jquery/jquery#2282]
In Firefox, jQuery's `css` method is not returning the correct `background-color` RGB value of options in a select box. It works as expected in Chrome. Obtaining the color via the native `elem.style.backgroundColor` property works in both browsers, though.

***Here's a jsFiddle:*** 
https://jsfiddle.net/pfe2utmq/12/

***Tested in:***
Chrome - Version 42
Firefox - Version 39 (Developers)

**Comment by dmethvin** [comment]
The `getComputedStyle` method seems to be returning the wrong value in Firefox: https://jsfiddle.net/pfe2utmq/15/

**Comment by gibson042** [comment]
It is inconsistent with other browsers (and worth filing a Mozilla issue for), but is it really wrong? I thought I remembered special rules for option elements, but can't find them now. What is the correct _computed_ style of an option element that is visible only by virtue of its selectedness, anyway? @mikesherov?

**Comment by dmethvin** [comment]
I agree that option elements are a bit of a strange thing to some extent. Just for further clarification, if you don't have an explicit style on the element but do have one in a style, that doesn't work either in Firefox. I'll put out the @miketaylr -shaped signal light for this one but don't think it's critical enough for a jQuery fix either.

**Comment by gibson042** [comment]
Agreed. There's nothing for jQuery to do here.
