### ISSUE TITLE
Effects: finish() should call progress(1)

### ISSUE THREAD

**Issue by Mr21** [jquery/jquery#2283]
Hi :)

On this [jsfiddle.net/Mr21/cr5391w2](http://jsfiddle.net/Mr21/cr5391w2/) we can see the difference between `.stop` and `.finish`. The darkest blue block is modified only with the `progress` callback.
But the callback `progress` is not called a last time with the value `1` when we force the end of the animation.

If you are agree on this problem, I found where we should put a line to fix this problem.

**Comment by dmethvin** [comment]
Since we're using a `jQuery.Deferred` for the animation we would need to call the deferred's `.notifyWith()` method which should do the rest for us, but I agree it seems like animations should do this on `.finish()` or `.stop(true)`.

**Comment by Mr21** [comment]
@dmethvin okay it's done :)
