### ISSUE TITLE
Remove deprecated event aliases

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2286]
`load`, `unload` and `error` - deprecated <a href="http://blog.jquery.com/2012/08/09/jquery-1-8-released/">since</a> 1.8. 

Ref http://bugs.jquery.com/ticket/11733

**Comment by markelog** [comment]
If we decide to do this, we also need a migrate and docs ticket

**Comment by dmethvin** [comment]
https://github.com/jquery/jquery-migrate/pull/94 takes care of the Migrate part.

**Comment by zowers** [comment]
[upgrade guide](https://jquery.com/upgrade-guide/3.0/) says 
>  If you need to attach **errors** by these names, use the .on() method

should be 

>  If you need to attach **events** by these names, use the .on() method

**Comment by mgol** [comment]
@zowers Thanks for the report, fixed!

If you find more mistakes, please report them at https://github.com/jquery/jquery.com/issues, this issue tracker is for the jQuery library.

The upgrade guide itself is written in Markdown in https://github.com/jquery/jquery.com/blob/master/pages/upgrade-guide/3.0.md.

**Comment by darwindlrd** [comment]
Now that I use function that allows do the same job?
