### ISSUE TITLE
Remove jQuery.support

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2289]
Deprecated <a href="https://api.jquery.com/category/deprecated/deprecated-1.9/">since</a> 1.9.

This object is used in our support tests, i wouldn't want to remove those, i think we need to figure out the way to remove it but leave the tests.

**Comment by mzgol** [comment]
For this to work jQuery UI & Mobile would need to create `jQuery.support` if it doesn't exist as they currently rely on it.

That said, :+1:. I didn't do it when I was breaking the support module into components mainly because we first need to figure out how to keep support tests running; this would most likely require testing the AMD support module instead of the built file.

**Comment by scottgonzalez** [comment]
Can you point to where you think we're using this in jQuery UI?

**Comment by mzgol** [comment]
Hm, last time we discussed removing jQuery.support there was an uproar that
we need to at least set it to an empty object since UI/Mobile attach their
support tests to jQuery.support.ui and assume jQuery.support exists. Do I
remember it wrong?

**Comment by timmywil** [comment]
No, that sounds very familiar to me too.

**Comment by scottgonzalez** [comment]
`jQuery.support.ui` has never existed. jQuery UI hasn't relied on `jQuery.support` existing in over a year.

**Comment by mzgol** [comment]
OK, maybe it was just about Mobile. See e.g.
https://github.com/jquery/jquery-mobile/blob/cb9112abb3acf73abc104051ac318647055b189c/js/support/orientation.js

**Comment by arschmitz** [comment]
Yeah we use it pretty extensively in mobile. However we just extend it with $.extend  in a single place so its as simple as changing `$.extend( $.support, {...} );` to `$.support = $.extend( $.support, { ... } );` so there is no worry on our part as long as we know in advance.

**Comment by mzgol** [comment]
Why the `Behavior Change` label? Other issues about hiding private methods don't share it, it seems we use it for public API changes only?

**Comment by markelog** [comment]
This is a documented property, and private or not it is a behaviour change i.e. not back-compat.

If we don't find a terrible complex of any way at all to test values of this property, i'd say we could document it as internal.

**Comment by mzgol** [comment]
Right, I forgot about http://api.jquery.com/jQuery.support/


-- 
Michał Gołębiowski

**Comment by mzgol** [comment]
One thing to keep in mind: working around test results in weird setups won't be possible after this change, see e.g. https://github.com/jquery/jquery/issues/1881#issuecomment-64149324 and discussions around `support.cors` in https://github.com/jquery/jquery/issues/1967.

**Comment by timmywil** [comment]
We discussed this in the meeting. We don't think it's worth the effort to remove it, and this property has some convenience. If someone feels inspired to open a PR for this, we'll consider it.

**Comment by mgol** [comment]
This was rejected, not fixed so I removed the `3.0.0` milestone.
