### ISSUE TITLE
Update requirejs dep when available

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2290]
Now it causes small issue with build version, but it has a danger of breaking things in the future, we should be aware of this issue and update "requirejs" accordingly 

Example, from

```js
// Support: Firefox 18+
// Can't be in strict mode, several libs including ASP.NET trace
// the stack via arguments.caller.callee and Firefox dies if
// you try to trace through "use strict" call chains. (#13335)
//"use strict";
```

to

```js
// Support: Firefox 18+
// Can't be in strict mode, several libs including ASP.NET trace
// the stack via arguments.caller.callee and Firefox dies if
// you try to trace through "use strict" call chains. (#13335)
//
```
Fix should have been ladnded in 2.1.17 but i still see the incorrect output.

Ref https://github.com/jrburke/r.js/issues/689
/cc @jrburke

**Comment by mzgol** [comment]
This is just a comment so it's not terribly important.

**Comment by timmywil** [comment]
I think all we need here is a comment saying r.js will strip "use strict"; if added.

**Comment by markelog** [comment]
> This is just a comment so it's not terribly important.

It might confuse people who would check out build source

> I think all we need here is a comment saying r.js will strip "use strict"; if added.

That sounds awkward :-(.

--

This issue might cause real failures, this ticket is created so we would be aware of it and fix it when appropriate fix will be landed.

**Comment by timmywil** [comment]
I'd rather not leave issues lying around as reminders. We can cross that
bridge if/when we come to it.

**Comment by timmywil** [comment]
Ok, I misunderstood the issue. I thought that latest requirejs would strip the "use strict". Since the action item is just to update requirejs, I'm all for that.
