### ISSUE TITLE
Document $.ready in 2.x and 1.x

### ISSUE THREAD

**Issue by benjamingr** [jquery/jquery#2293]
Hey, first of all let me thank you for the move in 3.0 to promises, it will be awesome! 

it would be really useful to document $.ready in 2.x and 1.x too, it seems like it's unlikely to change and it's very useful to use.

**Comment by markelog** [comment]
Thank you for opening this issue!

`$.ready` might be deprecated in the future, we might recommend this form instead - 

```js
jQuery(function() {});
```
It is better to create docs issues in appropriate <a href="github.com/jquery/api.jquery.com">repo</a>, although we have some useful information on it <a href="https://api.jquery.com/ready/">already</a>, we suggest though, to use `jQuery.prototype.ready`, not the "static" one.

**Comment by benjamingr** [comment]
I opened it here because I was interested in an API perspective, documenting it would mean adding it to the API surface. I can't find any information about getting a deferred/promise for the readiness of a document but it works and from what I can tell 3.0 also has a promise-backed version.

**Comment by mzgol** [comment]
> $.ready might be deprecated in the future

Where does that info come from? https://github.com/jquery/jquery/issues/1778#issuecomment-72764833 has no mention about deprecating $.ready, on the contrary.

How would you get ahold of the promise that resolves on ready otherwise?

**Comment by markelog** [comment]
> $.ready <b>might be</b> deprecated in the future.

That is what we will discuss at some point in the future, `jQuery.ready.promise` is not <a href="https://github.com/jquery/api.jquery.com/issues/205">documented</a>, status of `jQuery.ready` will yet to be determined.

**Comment by benjamingr** [comment]
Right, and what I'm asking for is discussion of `$.ready` in 1.x and 2.x since it's already there and likely won't be removed and it's useful so we might as well expose it.

**Comment by mzgol** [comment]
@benjamingr 
> Right, and what I'm asking for is discussion of $.ready in 1.x and 2.x since it's already there and likely won't be removed and it's useful so we might as well expose it.

Could you report an issue at https://github.com/jquery/api.jquery.com/issues/? This is where documentation issues should be discussed.

**Comment by benjamingr** [comment]
@mzgol sure, I was under the impression this is an API issue and not a documentation issue. I've opened one here: https://github.com/jquery/api.jquery.com/issues/739

Thanks.

**Comment by mzgol** [comment]
@benjamingr Thanks!
