### ISSUE TITLE
Custom queue: Animation promise is resolved before animation has run

### ISSUE THREAD

**Issue by hashchange** [jquery/jquery#2295]
A promise returned by jQuery.fn.animate does not work as expected when a custom queue is used. The promise is resolved before the animation even starts.

The following code

```js
$elem
  .animate( { whatever: value }, { queue: "custom" } )
  .promise()
  .done( cbDone )
  .always( cbAlways );
```

executes the `cbDone` and `cbAlways` functions immediately ([jsbin](http://jsbin.com/sidovih/1/edit?js,console,output)). Worse, they run if the custom queue is not even set in motion with an initial `dequeue()` call ([jsbin](http://jsbin.com/socihi/1/edit?js,console,output)).

With the standard `"fx"` queue, by contrast, things work as expected and the promise is resolved after the animation has completed ([jsbin](http://jsbin.com/dekeqo/2/edit?js,console,output)).

The bug is present in the latest versions of both branches (1.11.3, 2.1.4).

**Comment by gibson042** [comment]
`.animate` doesn't return a promise, it returns the context collection. And `.promise` is queue-dependent, [defaulting to "fx"](http://api.jquery.com/promise/). Invoke it against the custom queue and everything works as expected: http://jsbin.com/regerireya/1/edit?js,console,output

**Comment by hashchange** [comment]
Indeed. Thanks!
