### ISSUE TITLE
Events: originalEvent must not be an empty object

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery#2300]
Since https://github.com/jquery/jquery/commit/a873558436383beea7a05fd07db7070a30420100 we must make sure that all objects that are supposed to be events are events. Thus, code like [originalEvent: {}](https://github.com/jquery/jquery/blob/7855a1a7d8a5c959d4ef2f951b4eb971908ac96f/src/event.js#L619) must be replaced with ```originalEvent: new jQuery.Event()```

**Comment by timmywil** [comment]
I took the liberty of assigning you, @markelog. :)

**Comment by markelog** [comment]
@timmywil Sure thing,

> Since a873558 we must make sure that all objects that are supposed to be events are events.

Why?

**Comment by timmywil** [comment]
Because our simulated focus event doesn't have those methods.

**Comment by gabrielschulhof** [comment]
@gibson042 [mentioned](http://irc.jquery.org/%23jquery-dev/default_%23jquery-dev_20150512.log.html#t05:54:11) that we may be able to get rid of the fake ```originalEvent``` altogether.
