### ISSUE TITLE
Jquery 2.1.x + jquery-mask plugin error in Windows Phone

### ISSUE THREAD

**Issue by JonathasRodrigues** [jquery/jquery#2309]
Hello guys,

I have a problem when I use jquery-2.1.x + jquery-mask plugin.
Plugin: https://github.com/igorescobar/jQuery-Mask-Plugin
Problem:
When I add comment using .append() in html file
Test:
Windows Phone emulation on Internet Explorer
![2015-05-12_08h36_20](https://cloud.githubusercontent.com/assets/8070431/7586307/148f4240-f882-11e4-9c28-db3000ff3604.png)

Example:
Jsfiddle: http://jsfiddle.net/fb6qsr7s/

I created a sample html file, because jsfiddle have a problem with windows phone emulation.
File .html
```
<!DOCTYPE html>
<html>
	<head>
	   <title>Teste</title>
	</head>
  	<body>
	   <h1> Testando </h1>
	   <div id="teste">
		</div>

		<script type="text/javascript" src="jquery-2.1.4.js"></script>
		<script type="text/javascript" src="jquery.mask-1.7.7.js"></script>
		<script type="text/javascript">
		$( document ).ready(function(){
			$('#teste').append('<!-- teste -->');		
		});
		</script>		
	</body>
</html>
``` 
Function jquery-2.1.X
Values
elem = [object Comment]
name = *data-mask
```
Sizzle.attr = function( elem, name ) {
	    // Set document vars if needed
	 if ( ( elem.ownerDocument || elem ) !== document ) {
		  setDocument( elem );
	 } 

	var fn = Expr.attrHandle[ name.toLowerCase() ],
		// Don't get fooled by Object.prototype properties (jQuery #13807)
		val = fn && hasOwn.call( Expr.attrHandle, name.toLowerCase() ) ?
			fn( elem, name, !documentIsHTML ) :
			undefined;

	return val !== undefined ?
		val :
		(support.attributes || !documentIsHTML) ?
			elem.getAttribute( name ) :
			(val = elem.getAttributeNode(name)) && val.specified ?
				val.value :
				null;
};
```
and I added condition and works for me
```
Sizzle.attr = function( elem, name ) {
	    // Set document vars if needed
	 if ( ( elem.ownerDocument || elem ) !== document ) {
		  setDocument( elem );
	 } 

	var fn = Expr.attrHandle[ name.toLowerCase() ],
		// Don't get fooled by Object.prototype properties (jQuery #13807)
		val = fn && hasOwn.call( Expr.attrHandle, name.toLowerCase() ) ?
			fn( elem, name, !documentIsHTML ) :
			undefined;

	return val !== undefined ?
		val :
		elem.getAttribute &&  //CONDITION
		(support.attributes || !documentIsHTML) ?
			elem.getAttribute( name ) :
			elem.getAttributeNode &&  // CONDITION
			(val = elem.getAttributeNode(name)) && val.specified ?
				val.value :
				null;
};
```

**Comment by dmethvin** [comment]
The note in the [jQuery() method docs](http://api.jquery.com/jQuery/) regarding text nodes also applies in general to comment nodes:

> When passing HTML to jQuery(), note that text nodes are not treated as DOM elements. With the exception of a few methods (such as .content()), they are generally ignored or removed.

Looks like that should be added to the docs.

**Comment by timmywil** [comment]
Agreed. There's a PR open to adjust the docs on text nodes – making it more clear they are not supported in operations. I've added a note requesting comment nodes be included in those adjustments.
