### ISSUE TITLE
Event handler is called when it has already been detached

### ISSUE THREAD

**Issue by DmitryBogomolov** [jquery/jquery#2313]
Event handler is called when it has already been detached

Hello.

**Description**
There are two handlers both attached to document for some event (let's say 'click'). The first handler detaches the second. When click occurs both handlers are called though only the first is expected.

I have tested the same scenario using pure js `addEventListener`/`removeEventListener` and only the first handler has been called.
I have also tested 'mouseup' and 'mousedown' events - behavior was the same.

In IE11 with pure js second handler is called (not like in other browsers) - I suppose it is IE issue.

**Expected behavior**
Only the first handler is called.

**Steps to reproduce**
1. Open https://jsfiddle.net/xr1pc1gj/1/.
2. Click the inside the *Result* area.
3. See the output

**Demo**
Here is the link to the sample: https://jsfiddle.net/xr1pc1gj/1/.

**Tested versions**
2.1.0-4, 1.11.0-3

**Browsers**
IE 11.0
Chrome 42.0
Opera 29.0, 12.16, 12.17
Firefox 35.0, 37.0
Safari 5.1

**OS**
Windows 7, 8.1

Thanks.

**Comment by timmywil** [comment]
Thank you for opening an issue, but this is why `.stopImmediatePropagation()` exists. https://jsfiddle.net/timmywil/xr1pc1gj/2/

**Comment by mzgol** [comment]
It's a dup of #2094.
