### ISSUE TITLE
JQuery does not let certain element names in XML document

### ISSUE THREAD

**Issue by lykahb** [jquery/jquery#2316]
If you create an element with a name that does not match [\w:] regex, the operation will fail.

    $($.parseXML("<div/>" ).childNodes[0]).append("<hyphenated-element/>");
    Uncaught DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.

This happens because JQuery tries to set innerHTML to "\<hyphenated-element>\</hyphenated>". This line is constructed in buildFragment.

**Comment by dmethvin** [comment]
Are you still seeing this with http://code.jquery.com/jquery-git.js ?

**Comment by lykahb** [comment]
No, it works fine on it. I had the issue with the latest production version 2.1.4 and the versions earlier.

**Comment by dmethvin** [comment]
OK, just wanted to be sure. It was fixed in 85ffc6d973865a031ded170934e0acfc2e97cb11 and should be in the next major release.
