### ISSUE TITLE
Add support to grab div text

### ISSUE THREAD

**Issue by danielwheeler1987** [jquery/jquery#2318]
Hey, I would like to add support in jQuery to grab text from a div. Is this something that you all would be interested in? The coffeescript is below:

$.fn.selectText = ->
  $(this).each (index, el) ->
    if document.selection
      range = document.body.createTextRange()
      range.moveToElementText el
      range.select()
    else if window.getSelection
      range = document.createRange()
      range.selectNode el
      window.getSelection().addRange range
    return

**Comment by timmywil** [comment]
Thanks for opening an issue! I think what you mean is you'd like to get selected text. In which case, I think this is best left as a plugin. If you'd just like to get the text content, this can already be done using `.text()`.
