### ISSUE TITLE
Document "invocation correctness" development principle

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#2320]
Ref https://github.com/jquery/jquery/issues/2134#issuecomment-102510442

We now (modulo particularly hairy backwards compatibility issues) consider it safe to assume that all function input matches a documented signature, and therefore allow functions to throw exceptions rather than fail silently. This should be captured somewhere, and my first thought was [CONTRIBUTING.md](https://github.com/jquery/jquery/blob/master/CONTRIBUTING.md).

**Comment by timmywil** [comment]
That seems like a good place.

**Comment by markelog** [comment]
So boo plain objects, right?

**Comment by dmethvin** [comment]
I started a wiki page that we can use to iterate, it might be a little easier to do there than on a PR. Or maybe harder, I dunno, but you can just start editing with your ideas if you want. People don't generally read any of this, so usually it will be us linking to it to justify not changing (or changing) some reported behavior.

https://github.com/jquery/jquery/wiki/API-design-guidelines
