### ISSUE TITLE
Delete generated jsonp-callbacks

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2323]
Now we assign it to undefined when `undefined` when function is executed, we did this because we can't properly delete properties from the window objects on oldIE.

This issue still exist for supported IE8, but i think we should *discuss* using `removeProp` method in both branches instead.

**Comment by secrettriangle** [comment]
While `delete`ing the function makes more semantic sense, V8 will deoptimize any objects that have had properties `delete`d. Just something to keep in mind.

**Comment by markelog** [comment]
This is pure guessing, first of all, `window` object should be already deoptimized, since there is a lot of bounded properties, second, `window` is special host object so there might be another type of optimizations in play.

I wouldn't relay on those assumptions, until they proved by the performance benchmarking.

**Comment by markelog** [comment]
@timmywil, @dmethvin, @jaubourg need your opinions here.

Also, would like to know if our perception of the https://github.com/jquery/jquery/issues/2317 didn't change.

**Comment by dmethvin** [comment]
I agree that `window` is pretty magic and global so I doubt optimization comes into play here.

Would it make sense to create a single object on `window` at initialization and put all our JSONP callbacks there? That would work on IE8 too since we'd be `delete`ing the properties out of that regular object rather than on the global.

**Comment by markelog** [comment]
Which would mean we would expose three globals and as soon as IE8 dead we could eliminate it, cool.
Although, it seems we would need to do it only because of the one browser.

**Comment by timmywil** [comment]
I like the idea of using `removeProp`, which means we can delete in every browser except IE8 and IE8 receives no change.
