### ISSUE TITLE
.on('change', 'form') not firing when checkbox is checked indirectly via .prop('checked', true)

### ISSUE THREAD

**Issue by KroniK907** [jquery/jquery#2327]
Here is a JS fiddle Example: https://jsfiddle.net/so9guoe8/8/

Explanation:
When a checkbox is checked indirectly by calling .prop('checked', true) from some other location, a form change event does not fire. 

In the linked JSFiddle, clicking the gray divs do in fact check the input, however the hidden div at the bottom of the page does not appear as it does when checking the actual input boxes. 

This is also true for radio buttons.

**Comment by markelog** [comment]
It is not supposed to, events are fired by the browser only through direct user interaction with the elements.
