### ISSUE TITLE
Create e2e tests

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2329]
So we would stop using `dispatchEvent`, `createEvent` methods and such, like focus tests.

 - [ ]  focus tests - https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/test/unit/event.js#L2703, https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/test/unit/event.js#L2676

- [ ] isDefaultPrevented, stopImmediatePropagation - https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/test/unit/event.js#L375

**Comment by scottgonzalez** [comment]
See also https://github.com/jquery/qunit/issues/741

**Comment by markelog** [comment]
I'm gonna log in ticket desc what e2e-tests we need

**Comment by timmywil** [comment]
Closing in favor of tracking in the [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap).
