### ISSUE TITLE
Change licenses to license in package.json, follow the SPDX format

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2331]
npm 2.10.0 now warns when running `npm install` in the jQuery repo as the `licenses` field is deprecated:
```
$ npm i
npm WARN package.json jquery@3.0.0-pre No license field.
```

We should be using the `license` field in the SPDX format that npm has started to check recently; see: https://docs.npmjs.com/files/package.json#license

**Comment by mzgol** [comment]
@timmywil are there any changes necessary apart from modifying `package.json` so that it works with the release script?

**Comment by timmywil** [comment]
Nope, that should be sufficient. `package.json` is copied by the release script.

**Comment by SimenB** [comment]
(You have a PR for this https://github.com/jquery/jquery/pull/2330)
