### ISSUE TITLE
Different result of Jquery.map() executing in Chrome and Firefox

### ISSUE THREAD

**Issue by vkurkotov-softheme** [jquery/jquery#2333]
Tested in Firefox 38.0.1 and Chrome 42.0.2311.152 m

When I was developing some project , I noticed that executing Jquery.map() on object in different browsers gives different result.

**Steps to reproduce:**
1. Create javascript object as follows:
`var temp = { 1101: "team 1", 51476: "team 2", 51477: "team 3", 51478: "team 4", 57121: "team 5", 64463: "team 6", 0: "Empty"};` pay attention that `0: "Empty"` is on the last position. And that numbers are not 1 2 3 4 5 6 (with such numbers it works fine).
2. Execute Jquery.map:
`var someArr = $.map(temp, function (value, index) {return value;});`
3. Take a look at the `someArr`.

**Actual result:**
In FF: ` ["team 1", "team 2", "team 3", "team 4", "team 5", "team 6", "Empty"]`
In Chrome: `["Empty", "team 1", "team 2", "team 3", "team 4", "team 5", "team 6"]`

**Expected result:**
Behavior is the same for any supported browser.

http://jsfiddle.net/adnumumz/

**Comment by mzgol** [comment]
`jQuery.map` internally uses the `for ... in object` to iterate over an object. According to [the spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-ordinary-object-internal-methods-and-internal-slots-enumerate), the order of iteration over an object is not defined: "The mechanics and order of enumerating the properties is not specified but must conform to the rules specified below."

Therefore, you cannot rely on this order and jQuery can do nothing to help you with it.
