### ISSUE TITLE
Interference with window scroll

### ISSUE THREAD

**Issue by justinmedas** [jquery/jquery#2334]
commonly I leverage CSS to hide anything flowing outside of the body horizontally like so:

body { overflow-x :hidden; }

I noticed the entirety of my function that uses window scroll is negated by the above CSS property:

    /* ------------------------------------------------
       Sticky Header 
       ------------------------------------------------ */ 
    
    /* BIND DATA TO HEADER */
    $(function(){
    	$('header').data('size','big');
    });

    /* 
     * 'restickheader'
     * Rearrange DOM elements for a truncated header
     */
      	$.fn.restickheader = function () {	
        // BROAD ESSENTIALS
            $('header').data('size','small');
            
        // NEW CLASS ASSIGNMENT
            $('header').addClass('sticky-header');
            
        // DOM MANIPULATOIN
      
   	    
   	    } // ----end restickheader  

    /* 
     * 'unstickheader'
     * Arrange DOM elements back to where they were in the first place
     */

      	$.fn.unstickheader = function () {	
    			// BROAD ESSENTIALS
    		        $('header').data('size','big');
    		        
    		  // NEW CLASS ASSIGNMENT
            $('header').addClass('sticky-header');
            
    		  // DOM MANIPULATOIN
    		    
    	    }  // ----end unstickheader 

    /*
     * stickyheader function
     */
        var stickyheader = function() { 
          if($(document).scrollTop() > 0) {
            if($('header').data('size') == 'big') {
              $('header').restickheader();

            }
          }
          else {
           if($('header').data('size') == 'small') {
              $(window).unstickheader();
            }
          }
        }
      
    //Bind the stickyheader function to the scroll
      $(window).bind("scroll", stickyheader);

however if you are to change "scroll" to "click" I get a response from the browser.

**Comment by timmywil** [comment]
Thanks for opening an issue. Please provide a reduced test case on http://jsbin.com to help us assess the problem.

**Comment by dmethvin** [comment]
Since there hasn't been a reply I'm closing the ticket.
