### ISSUE TITLE
getStyles of an element inside the shadow dom

### ISSUE THREAD

**Issue by edoardocavazza** [jquery/jquery#2341]
Hi,

Using Polymer in my application, I have found out that the function 
```javascript
var getStyles = function( elem ) {
	// Support: IE<=11+, Firefox<=30+ (#15098, #14150)
	// IE throws on elements created in popups
	// FF meanwhile throws on frame elements through "defaultView.getComputedStyle"
	if ( elem.ownerDocument.defaultView.opener ) {
		return elem.ownerDocument.defaultView.getComputedStyle( elem, null );
	}

	return window.getComputedStyle( elem, null );
};
```

throws an exception when `elem` is a shadow dom element, because `elem.ownerDocument.defaultView` is undefined.

Adding the control, all works well.
```javascript
if ( elem.ownerDocument.defaultView && elem.ownerDocument.defaultView.opener ) {
```

**Comment by dmethvin** [comment]
@edoardocavazza Can you provide a relatively simple test case we could use to detect this? Ideally it should not include Polymer since our unit test will not use it. In what cases is your code trying to get styles on a shadow root?

**Comment by dmethvin** [comment]
We haven't heard back on this so I'm closing it. We'd need a test case and use case.
