### ISSUE TITLE
Extra parameters are not passed when triggering focus

### ISSUE THREAD

**Issue by widatama** [jquery/jquery#2342]
jquery version: 1.9.1 and up
OS: OSX Yosemite 10.10.3
Browser: Firefox Dev 39.0a2 (2015-05-11)

I am trying to do something like this

````
$(".textInp").on("focus", function(event, extraParam) {
  alert("focus " + extraParam);
});
````
But when calling `$(".textInp").trigger("focus", [123]);` the extra parameter is undefined.

Here is a fiddle http://jsfiddle.net/6ywvLems/2/

Is this an intended behavior? Other events passes the extra parameter just fine.

**Comment by gibson042** [comment]
It's not intended, but it is known. We haven't applied a fix yet for size and complexity out of proportion with the magnitude of the resolved issues: #1367

**Comment by dmethvin** [comment]
This is a dup of #1741, see also #1750 which has the same cause.

**Comment by Tomas-M** [comment]
Is this fixed in any jquery version?
