### ISSUE TITLE
IE 11 delegate vs direct radio click handlers behave differently

### ISSUE THREAD

**Issue by baronworks** [jquery/jquery#2343]
With IE 11 found a case where click handler on a radio input behaves differently when delegated vs directly-bound.  
```javascript
// delegated click handler, works when clicked but not when using arrows.
$('#testform').on('click', '.radios', function( e ) {
     console.log('delegated click handler', $(this).val() );
});
//directly-bound click handler, always works even when using arrows
$('.radios').on('click', function( e ) {
    console.log('direct click handler', $(this).val() );
});
```
jquery version: 1.11.* and  2.1.3, most testing done with 1.11.3
works in browsers: Firefox: 38.0.1, IE 9 & 10, Opera 27.0.1689.66, Chrome 42.0.2311.15
does not work in: IE 11 Version: 11.0.9600.17801
OS: Windows 7 64-bit 

Created a jsfiddle using jquery 1.11.0 at http://jsfiddle.net/damnmaudite/kt99moLf/24/
Note when actually clicking the radio option everything works, but when using arrows to select a value in IE-11 the delegated event is not triggered..

**Comment by dmethvin** [comment]
This arises from a combination of browser bugs and lies. We have some [code](https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/src/event.js#L430) to guard against a problem in Firefox regarding delegated *right*-click events that bubble as if they are `click`; TBH I am not sure Firefox still has this problem. 

But to make it worse, when you use the arrow keys in this example  in Firefox and Chrome the event says the left mouse button was clicked which is a lie. In IE it says no button was clicked (`-1`) which is true, but that triggers our Firefox bug check. I think we can fix this by changing `!event.button` to `event.button <= 1`. Or perhaps this guard can be removed completely if Firefox fixed the bug long ago.

BTW, I can't find where any standard defines what happens with the arrow keys on a radio button group.

**Comment by baronworks** [comment]
Thanks for the quick response.  Played with the code using ```event.button <= 1```, and everything appears to work as expected.  Will create a local patch for our purposes that overrides ```jQuery.event.handlers``` helper method until this is added to the 3.0 milestone.

**Comment by dmethvin** [comment]
It appears that Firefox hasn't fixed this bug, which is [14  years old](https://bugzilla.mozilla.org/show_bug.cgi?id=184051). So we should take the conservative approach and leave our guard in place, just modifying the `event.button` check.

**Comment by mzgol** [comment]
@dmethvin I marked [the issue you mentioned](https://bugzilla.mozilla.org/show_bug.cgi?id=184051) as one blocking our [jQuery meta-issue](https://bugzilla.mozilla.org/show_bug.cgi?id=968240).
