### ISSUE TITLE
Standardize the output of the .html() method (decoded)

### ISSUE THREAD

**Issue by LulzAugusto** [jquery/jquery#2346]
Hey guys, I found a discrepancy between browsers when using the `.html()` method today. While in the latest Chrome/Firefox I had the following output
```html
<input type="hidden" class="popover-value" name="value" value="<%- value %>" id="popover-<%- value %>">
```

In Safari 8.0.6 the html output had it's special characters encoded 
```html
<input type="hidden" class="popover-value" name="value" value="&lt;%- value %&gt;" id="popover-&lt;%- value %&gt;">
```
Actually this is not jQuery's fault, because I can see the same difference if I use the `innerHTML` property. 

So, what are your thoughts about the `.html()` __always__ return a decoded HTML string? Wouldn't it be good? If so, I'd be more than happy to implement this enhancement.

ps.: I'm talking about jQuery 2.1.4 here

**Comment by jckim0414** [comment]
I think be right Chrome/Firefox's case.
I think #.html()
means that include html tags. Then these values do not need to encoding.
What's your opinion???

I'm afraid my expressions may be rude or hard to read, because I'm not so good at English.
Thanks.

**Comment by gibson042** [comment]
Thanks for the report! Those examples are valid and semantically identical HTML5 (which allows quoted [attribute values](https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-value) to contain both character references and arbitrary characters—including unescaped less-than and greater-than). As such, and considering the cost in both performance and library size to parse and normalize, we won't be pursuing such an effort, any more than we'd try to force attribute values into a particular quoting style.

**Comment by LulzAugusto** [comment]
I understand. It makes sense to me. :)
