### ISSUE TITLE
JQuery trying to parse a 204 No content response

### ISSUE THREAD

**Issue by Hunsu** [jquery/jquery#2347]
When I do an Ajax request and the server return an 204 No content response JQuery (v1.11.3) try to parse the content and I get this error: `JQMIGRATE: jQuery.parseJSON requires a valid JSON string (json = "")`. I don't know if it's the cause but the response I got from the server does have:

    Content-Length: 4
    Content-Type: application/json
 
It's an error from the server but HTTP spec say that a 204 code mean that there's no content so JQuery mustn't try to parse a 204 response. 

Here's how I was used JQuery:                                                           
            
    $.ajax({
        url: 'myurl',                                                           
        type: 'DELETE',
        headers: {'Accept':'application/json'},                                              
    });

**Comment by timmywil** [comment]
Thanks for opening an issue. What if you drop the "Accept" header? Since a 204 has no content, I'm not sure why you'd need to set that.

**Comment by Hunsu** [comment]
I copied the code I used. In my case I must include the "Accept" header, that how the server work. It's not relevant for this issue.

**Comment by scottgonzalez** [comment]
> What if you drop the "Accept" header? Since a 204 has no content, I'm not sure why you'd need to set that.

The response may be conditional. It's entirely reasonable to have a request that returns either a 200 or a 204 on success, based on the original payload.

**Comment by timmywil** [comment]
> It's entirely reasonable to have a request that returns either a 200 (with data) or a 204 on success, based on the original payload.

Fair enough. However, I am unable to reproduce in jQuery git...

http://jsbin.com/yobanudoho/1/edit?js,console,output

**Comment by Hunsu** [comment]
Can you make the server return `application/json` as content-type header. It return `text/html`

**Comment by timmywil** [comment]
@Hunsu I'm not sure I can. Are you sure your server isn't returning some content with the 204?

**Comment by timmywil** [comment]
i.e. An empty string is still content. It should not have a message body.

**Comment by Hunsu** [comment]
How can I test that? Perhaps I can test it using Wireshark but I can't do it right now.

**Comment by Pumpuli** [comment]
> The response may be conditional. It's entirely reasonable to have a request that returns either a 200 (with data) or a 204 on success, based on the original payload.

However, if you do `Accept: application/json` you can't expect `HTTP 204` since empty string / no content would be invalid JSON.

So if the server responds with `HTTP 204` and some content (`Content-Length: 4` ?), it's doing something wrong. If the server responds with `HTTP 204` and no content but `Content-Type: application/json`, it's still doing something wrong (because no content is invalid JSON).

**Comment by Hunsu** [comment]
I have used wireshark to see the response of the server, and the server returned null in the request body that why the `Content-Length: 4`. I don't know why the JQuery error message says that it try to parse empty string.

 **@Pumpuli**: Yes the server is doing something wrong, the question is should JQuery try to parse content included in 204 No content response?

**Comment by mzgol** [comment]
204 means "No Content" and the browser is free to stop reading the response once the headers end, assuming there is no body. I didn't check but it may be happening before anything gets to jQuery.

It's definity incorrect to return 204 with a body. jQuery has an optimized workflow for correctly configured servers. For incorrectly configured ones you have to declare dataType: "text" and parse the response by yourself when you expect it to be JSON.

**Comment by Hunsu** [comment]
The problem that in my code I didn't ask JQuery to parse the response and it did it anyway.

**Comment by mzgol** [comment]
It parsed the response because the server told it it returns JSON. You need to either fix the server or enforce dataType: "text".

**Comment by Hunsu** [comment]
Is it correct to do that? The status say that it's a 204 Non content response so why parse the response?

**Comment by mzgol** [comment]
The response from your server is incorrect. We're assuming that
`Content-Type: application/json` means the response has a body that's valid
json. There may be a lot of invalid server configurations and we can't
workaround them all.

Your server has a bug, not jQuery. And you can easily workaround it
yourself as I wrote before.

**Comment by Hunsu** [comment]
The HTTP spec say that an HTTP 204 doesn't have a body so jQuery must not try to parse it. But if it's a feature I can live with it. It just jQuery doesn't respect the HTTP spec, that the problem.

**Comment by mzgol** [comment]
HTTP spec doesn't say anything about parsing the body at all as well so we might as well return text always. What we do is beyond the spec IMO.

Also, according to the spec at http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17:
"The Content-Type entity-header field indicates the media type of the entity-body sent to the recipient or, in the case of the HEAD method, the media type that would have been sent had the request been a GET."

That is, `Content-Type` should not be set if the response doesn't contain any data and the 204 response doesn't contain data by its definition. So I'd argue your server config is invalid and jQuery doesn't specify behavior for invalid input so anything may theoretically happen.

**Comment by dmethvin** [comment]
> The HTTP spec say that an HTTP 204 doesn't have a body so jQuery must not try to parse it.

The spec doesn't say that. However, [the spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) *does* say this:

> The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields.

**Comment by timmywil** [comment]
In this case, I think it was actually helpful that jQuery tried to parse the response and failed because it uncovered a server issue. We'll leave this as-is.
