### ISSUE TITLE
mouseout fired on tr when changing column

### ISSUE THREAD

**Issue by davesalomon** [jquery/jquery#2348]
I have a simple table where I change the row colour using jQuery when the user mouses over it.

    $('tr').on('mouseenter', function(){
        $(this).css({background:'#f00'});
    });
    $('tr').on('mouseout', function(){
        $(this).css({background:''});
    });

When the user moves the mouse from column A to column B (on the same row), the `mouseout` event is fired.

jsFiddle [here][1].

Test case: Move mouse over cell with 'Foo' in it. Move mouse right, to cell with 'Bar' in it. The row should remain red, but does not. Tested in IE11 and Chrome 42.0.2311.152m.

Workaround:
Apply the `mouseenter`/`mouseout` events to the `td`, and then use `$(this).parent().css({background:...});` instead. jsFiddle [here][2]

  [1]: http://jsfiddle.net/daveSalomon/8sy3L4jk/
  [2]: http://jsfiddle.net/daveSalomon/8sy3L4jk/1/

**Comment by mzgol** [comment]
You should use `mouseenter` with `mouseleave` and `mouseover` with `mouseout`. This works as expected.

**Comment by amanzyw** [comment]
```html
or you can use function hover
