### ISSUE TITLE
jQuery.off() is not working with document-delegated events in IE8

### ISSUE THREAD

**Issue by mnaoumov** [jquery/jquery#2350]
Open the following html file in IE8 (or at least in IE8 mode). You'll see that off() is not working as expected in IE8 and handler is still in

```html
<!doctype html>
<html>
<body>
    <input type=button value="Click me twice">
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script>
        $(document).on("click", "input", function handler() {
            alert("First time click is handled. You should not see this alert second time!")
            $(document).off("click", "input", handler);
        });
    </script>
</body>
```

P.S. I could not find any sandbox to put the example in. jsfiddle/jsbin/codepen don't support IE8

**Comment by mzgol** [comment]
> jsfiddle/jsbin/codepen don't support IE8

You can create a test case at jsbin.com and then remove the `edit` part from the URL, it should load in IE8. Example:
1. URL for editing (might break in IE8): http://jsbin.com/qefabu/1/edit?html,js,output
2. URL for viewing (should work in IE8): http://jsbin.com/qefabu/1/

**Comment by timmywil** [comment]
Thank you for opening an issue, but the problem is that named function expressions don't work in IE8. Place the function declaration before the binding and it works.

http://jsbin.com/fevovahupe/1/

**Comment by mnaoumov** [comment]
Just for completeness, I found an article which describes what exactly wrong with IE8 that creates this issue:

http://kangax.github.io/nfe/#example_3_named_function_expression_creates_two_distinct_function_objects

**Comment by dmethvin** [comment]
Also, this is a good place for the `.off( event )` signature, you don't need to know the function name or any of the details that way.

**Comment by mnaoumov** [comment]
@dmethvin I think you've meant events with namespaces? Like $(document).off("click.mynamespace")

**Comment by dmethvin** [comment]
Nope, I meant http://api.jquery.com/off/#off-event

**Comment by mnaoumov** [comment]
@dmethvin You suggestion unsubscribes from all handlers so in case if you will need to resubscribe them back this technique complicates things.

P.S. I explain why am I doing such sort of logic, maybe you'll suggest more elegant way to do this

```javascript
$(document).on("click", ".mybutton", function handler(e) {
    e.preventDefault();
    var promise = getSomePromiseThatRunsAsync();
    promise.then(function() {
        // here I need to "undo" e.preventDefault()
       // I need the native button click since it submits the form
       // and the POST action is handled on server-side

       $(document).off("click", ".mybutton", handler);
       this.click();
       $(document).on("click", ".mybutton", handler);
    });
});
```

Alternative way

```javascript
$(document).on("click", ".mybutton", function handler(e) {
    var $button = $(this);
    if ($button.data("bypassClickHandler"))
        return;
    e.preventDefault();
    var promise = getSomePromiseThatRunsAsync();
    promise.then(function() {
        // here I need to "undo" e.preventDefault()
       // I need the native button click since it submits the form
       // and the POST action is handled on server-side

       $button.data("bypassClickHandler", true);
       $button.click();
    });
});
```

**Comment by dmethvin** [comment]
> @dmethvin You suggestion unsubscribes from all handlers so in case if you will need to resubscribe them back this technique complicates things.

Do you have a test case for that? It should only remove the handler for that event but "the handler" might mean different things in your code.

So are you trying to inject your code into an existing page you don't control? That's the only reason I can think of for doing something like this.
