### ISSUE TITLE
If a callback throws an error all subsequent calls to fire are ignored

### ISSUE THREAD

**Issue by svenackermann** [jquery/jquery#2353]
See https://jsfiddle.net/mL8b3rvs/ (still exists in 2.1.4).
This is a similar problem as in #1823 except that it refers to the `Callbacks` API.

When using the `Callbacks` API, a callback added with `add` that throws an error on `fire` breaks all subsequent `fire` calls (and remaining listeners in the 1st `fire` call are ignored, too). Maybe you could introduce an option to control the exception handling (e.g. "onError: ignore|log|throw|throwCombined").
The current behavior completely breaks the `Callbacks` object, so at least the call should be surrounded with try/catch to cleanup before rethrowing (`firing=false;`).

**Comment by gibson042** [comment]
This is known issue, and at this point has been around for so long that it's arguably a feature (cf. @jaubourg's comments on http://bugs.jquery.com/ticket/11193 and related tickets). We _could_ now use `try`…`finally` like https://github.com/facebook/react/blob/master@%7B2014-04-02T00:05:09Z%7D/src/utils/Transaction.js#L230-L260 , but doing so would require careful consideration of the impact on an already-long list of options. I would consider a pull request, but am more inclined to direct everyone towards native Promises or full Deferreds, whose interoperable (as of jQuery 3.0) `.then` method does not exhibit such seizing behavior.

Is yours a case that can be handled by `.then`?

**Comment by timmywil** [comment]
IMHO, this is intended behavior in callbacks. To catch exceptions like this, I'd recommend using Deferreds or wrapping code in try/catch manually.

**Comment by svenackermann** [comment]
Sorry, but I'm not sure how to resolve my problem with Deferreds. They have the same problem, see https://jsfiddle.net/mL8b3rvs/2/
The 2nd callback function is not executed and the 2nd `notify` call has no effect.

I just used the `Callbacks` API to register some listeners that are called for specific events. I need that listeners to be called every time `Callbacks.fire` is called (not only the first time) and I also need all of the the registered listeners to be called (not only those which were registered before the one that throws errors). If one of them throws an error and `Callbacks.fire` rethrows that error, that's ok for me, but this should not have impact on the other listeners and subsequent calls to `fire`.
Wrapping each listener with a try/catch would be very ugly, cause there are a lot of them.

**Comment by gibson042** [comment]
> Sorry, but I'm not sure how to resolve my problem with Deferreds. They have the same problem, see https://jsfiddle.net/mL8b3rvs/2/
The 2nd callback function is not executed and the 2nd `notify` call has no effect.

Right, you need to specifically use the newly interoperable `.then` method: https://jsfiddle.net/mL8b3rvs/4/

> I need that listeners to be called every time `Callbacks.fire` is called (not only the first time) and I also need all of the the registered listeners to be called (not only those which were registered before the one that throws errors)
…
> Wrapping each listener with a try/catch would be very ugly, cause there are a lot of them.

jQuery 3.0 Deferreds will offer the above `.then` solution, which seems to fit that case perfectly, but `try` is your only option with a released version. It needn't be ugly, though... you could put it in a wrapper function like [`_.attempt`](https://lodash.com/docs#attempt):
```js
function redirectExceptions( fn, handler ) {
	return function() {
		try {
			return fn.apply( this, arguments );
		} catch( x ) {
			return handler( x );
		}
	};
}
…
callbacks.add( redirectExceptions(fn, logException) );
…
```
or even
```js
var safeAdd = function( callbacks, fn ) {
	callbacks.add(function() {
		try {
			return fn.apply( this, arguments );
		} catch( x ) {}
	});
}
…
safeAdd( callbacks, fn );
…
```

**Comment by dmethvin** [comment]
I feel like we should leave `jQuery.Callbacks` as it is, documenting the exception behavior if needed, and encourage the standards-based `.then` instead.

**Comment by svenackermann** [comment]
OK, thanks a lot. Now I understand what you mean. I wasn't aware that this requires jQuery 3.0.

I also thought about wrapping the callback function like you suggested, but that makes removing the callback (`Callbacks.remove`) very hard since I would have to remove the correct wrapper function, not the callback itself. So I would have to remember the wrapper for each callback function.

I think I can live without a "fix" for this, I justed thought this might be a problem you did not know about yet. But I understand that you have your reasons to leave this as is and appreciate that you would update the documentation.
Until 3.0, I think it's best for me to not use the `Callbacks` API but build sth. on my own.
