### ISSUE TITLE
In ie11 , when many dropdowns on a page, throwing out of stack error, related to caching

### ISSUE THREAD

**Issue by kriti-gupta** [jquery/jquery#2354]
Hi ,

Recently the document mode for our application has been upgraded  from IE8 to Edge.
This has been achieved with a simple change of content attribute for meta tag in _Head.cshtml..
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

The application is working as expected for most of the pages, but breaks where many dropdowns are rendered. The dropdown (Kendo UI Dropdown) lists the record, however, does not let the user to select a value.

In the console, you can find the error as: SCRIPT28: Out of stack space. This issue can be replicated for IE > 10.

There are three solutions which I came across, that allowed the application to run smoothly:
•	Keep the IE developer tool (F12) opened.
•	Uncheck option ‘Disable script debugging in IE’
•	Update the jQuery core library : jquery-1.11.0 at line 3857.
        elem = elem.nodeType ? jQuery.cache[elem[jQuery.expando]] : elem[jQuery.expando];
       with
        elem = elem[jQuery.expando];

With the first two options, the error still persists(in console). But the dropdown are working properly.

But with the last solution , the error goes away totally.

I have also tried updating the jQuery versions to 1.11.3 and 2.x, but nothing helped.

Please provide some technical assistance.

Regards,
Kriti

**Comment by timmywil** [comment]
Thank you for opening an issue, but I think this needs to be debugged further on the [forums](http://forum.jquery.com) or in the #jquery irc channel. If it is determined there is an issue in jQuery core, please open a new issue with a reduced test case from http://jsbin.com to help us assess any potential problems.
