### ISSUE TITLE
.selector removed since 1.9, or is it?

### ISSUE THREAD

**Issue by BramVanroy** [jquery/jquery#2355]
[Documentation](https://api.jquery.com/selector/) clearly states that `.selector` has been deprecated since 1.7 and removed since 1.9. However, [this fiddle](http://jsfiddle.net/BramVanroy/vz3xc3se/1/) proves otherwise. What am I missing here?

**Comment by mzgol** [comment]
Yeah, that seems incorrect, we'll only remove it in 3.0. Could you report an issue at https://github.com/jquery/api.jquery.com/issues/? This is documentation issue, not code issue.

**Comment by BramVanroy** [comment]
@mzgol Oh, my bad. Thanks. [Done](https://github.com/jquery/api.jquery.com/issues/746). Do you have any idea how long before 3.0? In other words, can I still use `.Selector` in current projects?

**Comment by arthurvr** [comment]
@BramVanroy It's anyways better to not use a deprecated feature. It's deprecated for a reason :)

**Comment by dmethvin** [comment]
In 1.9 we changed the behavior of `.selector` although it wasn't documented. It will be removed completely in 3.0, so don't use it. If you find yourself needing to use it for non-debugging purposes that generally means the API for your plugin needs to have a selector passed to it. There is no reliable way to know a string selector that represents the current set of elements in a jQuery set.
