### ISSUE TITLE
Deal with UA string of the Microsoft Edge

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2357]
As noted by the @dmethvin.

See https://msdn.microsoft.com/en-us/library/hh869301%28v=vs.85%29.aspx

Since our tests (mostly support tests) depends on that.

**Comment by mzgol** [comment]
Hmm, it seems I partially took care of it via https://github.com/jquery/jquery/commit/8e111df641cca3e1b75b31a1971bfc89014b4ded.

See also #2390 for a summary of where we're staying with MS Edge.

**Comment by mzgol** [comment]
I've search the code from `master` and, apart from `test/unit/support.js` the event `originalEvent` test is the only place where we sniff for Chrome. In other places we only sniff for:

1. Android
2. iOS
3. Firefox
4. Safari

No Chrome & IE. Therefore, the `originalEvent` test is the only place that's left to change (as you said, only the test description & message should be changed to include Edge).

That seems to be it.
