### ISSUE TITLE
Redundant 'cd jquery' command in README.md

### ISSUE THREAD

**Issue by elas7** [jquery/jquery#2359]
In line 169 of README.md, the following command is suggested to start 'grunt watch'

```bash
cd jquery && grunt watch
```

The `cd jquery` part seems to be redundant, considering that the previous command in the instructions is `npm install`.
Also, the only other part of README.md that uses `cd jquery` is when explicitly instructing to enter the jquery directory after cloning the jquery repo.

**Comment by Mr21** [comment]
+1
or maybe something like this:
``` bash
$> pwd
jquery
$> grunt watch
```

**Comment by markelog** [comment]
Thank you!
