### ISSUE TITLE
Remove or document jQuery.fn.{push,sort,splice}

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2365]
We should deprecate or document `jQuery.fn.{push,sort,splice}` as we do with most private stuff in 3.0.0. Currently those methods have a comment they're for internal use only.

Summoning @paulirish & @fitzgen as I believe at least Chrome DevTools are using a presence of `object.splice` (or sth other from the list?) as an indicator that the object is array-like which makes jQuery objects display a little nicer than regular objects.

**Comment by Krinkle** [comment]
> I believe at least Chrome DevTools are using a presence of object.splice (or sth other from the list?) as an indicator that the object is array-like

I imagine it would use `.length` for that purpose. Similar to jQuery's concept of isArrayLike.
Not a method like push, sort or splice.

Actually, you're right :satisfied:

It's triggered on objects having `.length` and `.splice`.
![screen shot 2015-06-01 at 19 45 20](https://cloud.githubusercontent.com/assets/156867/7920414/c4ad0d50-0896-11e5-8f10-65fbf9dd6011.png)

**Comment by timmywil** [comment]
In this case, I disagree. We shouldn't deprecate them for a couple reasons:

1. They're not part of the public API so there would be no need.
2. We shouldn't remove them because we've used them internally for a long (the whole?) time, and, as you've pointed out, they are used to qualify jQuery objects as arraylike, which is good.

And they shouldn't be documented because they are for internal use only.

Given that, I think we should leave these as they are.

**Comment by timmywil** [comment]
That said, I do agree that most methods that are for internal use only that can be moved from the jQuery object easily should be moved. I just think it's better to leave these particular ones.

**Comment by mzgol** [comment]
> They're not part of the public API so there would be no need.

We've been hiding a lot of methods that were exposed but not officially public in 3.0 - `swap`, `buildFragment`, `domManip` etc. I think it's worth hiding such things as otherwise people start using them and we end up in a situation where we have exposed untested code people rely on and if we change sth there it may break.

This situation doesn't seem different from the other ones, at least when it comes to this argument.

> We shouldn't remove them because we've used them internally for a long (the whole?) time

As we've done with `jQuery.swap`, `jQuery.buildFragment`, `jQuery.domManip` & others and yet we're hiding them now.

> and, as you've pointed out, they are used to qualify jQuery objects as arraylike, which is good.

This is my only doubt, really. But if it's just about Chrome then they can easily just check for the `jquery` property presence and it'll be backwards & forwards-compatible.

**Comment by timmywil** [comment]
> We've been hiding a lot of methods that were exposed but not officially public in 3.0 - swap, buildFragment, domManip etc.

Like I said, I'm not against hiding these. It's just not "deprecation". That only applies to documented APIs.

> I think it's worth hiding such things as otherwise people start using them and we end up in a situation where we have exposed untested code people rely on and if we change sth there it may break 3rd party code.

Let's make these the exception and agree to neither document nor remove them.

> As we've done with jQuery.swap, jQuery.buildFragment, jQuery.domManip & others and yet we're hiding them now.

True, but there is something to be said for the fact that no one has complained and they've been there the whole time.

> they can easily just check for the jquery property presence and it'll be backwards & forwards-compatible.

I don't feel comfortable asking them to do that. I'd prefer we fit into some broader rules to determine if objects are arraylike.

**Comment by mzgol** [comment]
>> We've been hiding a lot of methods that were exposed but not officially public in 3.0 - swap,
>> buildFragment, domManip etc.
>
> Like I said, I'm not against hiding these. It's just not "deprecation". That only applies to documented APIs.

Right, I should have said "Remove or document". Issue title updated.

>> As we've done with jQuery.swap, jQuery.buildFragment, jQuery.domManip & others and yet we're hiding them now.
>
> True, but there is something to be said for the fact that no one has complained and they've been there the whole time.

That's also the case for `buildFragment` & friends; we ourselves decided to hide them, we haven't had issues about that.

>> they can easily just check for the jquery property presence and it'll be backwards & forwards-compatible.
>
> I don't feel comfortable asking them to do that. I'd prefer we fit into some broader rules to determine if objects are arraylike.

From what I see neither Firefox nor Edge treats jQuery objects in any special way and displays them as regular objects so it's just Chrome & Safari. So it's not sth universal.

What do others think? cc @jquery/core

**Comment by mzgol** [comment]
BTW, we've been talking about making jQuery an Array sub-class; it hasn't been done mostly due to `length` handling being impossible to do correctly cross-browser (@gibson042 & @rwaldron might know more). So if we already define some array methods and we intended to make all of them available if it was possible, maybe we should just document those methods to be aliases of proper Array methods and be done with it?

I just don't like semi-private APIs, they're problematic.

**Comment by rwaldron** [comment]
Confirm. It will also never work correctly without the built-in subclassing semantics of ES6 classes.

**Comment by timmywil** [comment]
I guess I lean towards documenting if we have to choose one or the other.
But if we do document, I think there should be a note recommending other
methods like .add. This issue is minor enough it feels a little like
bikeshedding to me.

**Comment by gibson042** [comment]
I don't see us **ever** documenting these methods, because they mutate the context collection rather than creating a new one with `pushStack` (note that `slice` is *not* in the list—that's one that is public, and it returns a properly `end()`able jQuery object). Further, a cursory look doesn't reveal any actual use any of the three, although that could as easily be from an oversight on my part as from real abandonment.

If we ever do subclass from Array (which is [possible](https://github.com/jquery/jquery/issues/1754), but only with caveats), it will be for better size and/or performance, and will leave the public API unchanged so we reserve the freedom to later abandon such an implementation.

**Comment by timmywil** [comment]
I haven't looked for the other two, but `push` is used heavily by Sizzle.

**Comment by mzgol** [comment]
OK, if you think it's better to leave it as is then I won't push it further; it doesn't seem terribly important to me.

**Comment by gibson042** [comment]
> `push` is used heavily by Sizzle.

But only on `results`, which is usually (always?) an actual array instead of a jQuery collection. http://jsbin.com/pugamexeke/1/edit?html,js,console

**Comment by timmywil** [comment]
Yea, wow, looks like that was changed in 1.9.

**Comment by timmywil** [comment]
Now I wonder how that affected `.find` performance.

**Comment by timmywil** [comment]
Actually, we could avoid the double loop (pushStack + uniqueSort) by doing the pushStack beforehand.

**Comment by timmywil** [comment]
Looks like this commit changed it when experimenting with a quick unique check...https://github.com/jquery/jquery/commit/e8f91514a6f353e85d8117998087903dc7331210

**Comment by timmywil** [comment]
Yea, I'm inclined to change that back. I'm not surprised we didn't catch it.

**Comment by markelog** [comment]
I think those methods are useful and kind of cool :-). Because they can be useful, i think we should document them.

**Comment by mzgol** [comment]
Did we come to any conclusion here? I've added the "Needs review" flag so that sth's decided.

**Comment by timmywil** [comment]
After further discussion in the meeting, we've decided to leave this as-is. We want to avoid the appearance that using these methods is encouraged, but we don't want to remove them either.
