### ISSUE TITLE
Remove additional parameters of easings

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2367]
`jQuery.easing` is currently passed 4 arguments:
https://github.com/jquery/jquery/blob/0019a463bdcb81dc6ba3434505a45774ca27f363/src/effects/Tween.js#L35

@gnarf said it's a legacy behavior so maybe we should remove it?

Thanks to @Mr21 for digging in.

**Comment by markelog** [comment]
So this is exposed because we use it in the tests? 

Can't find any docs for it, so if jquery-ui/jquery-mobile doesn't use it, i think it is safe change.

/cc @scottgonzalez, @arschmitz

**Comment by Mr21** [comment]
@markelog nop on the contrary, mzgol said gnarf has added some tests for that recently ^^
I would love make a PR for that if you think we can remove it.

**Comment by markelog** [comment]
> @markelog nop on the contrary, mzgol said gnarf has added some tests for that recently ^^

Those tests are for `jQuery.animate` and `Tween`, but here we are talking about specific changes, about legacy behaviour.

> I would love make a PR for that if you think we can remove it.

I'd say if we okay with that, we would love you to send it, if @mzgol doesn't mind :-).

**Comment by arschmitz** [comment]
`$.easing` is not used in jQuery Mobile at all

**Comment by scottgonzalez** [comment]
It's been over three years since I rewrote all of jQuery UI's easings to only use one parameter. https://github.com/jquery/jquery-ui/commit/c0093b599fcd58b6ad122ab425c4cc1a4da4a520

**Comment by mzgol** [comment]
@Mr21 PR welcome. :)

**Comment by markelog** [comment]
I think @timmywil and @gnarf opinions could be interesting, so i would suggest to wait on the pull just yet.

**Comment by timmywil** [comment]
Just a guess, but I would imagine the jQuery.easing plugin still gets a lot of usage. I'd be concerned about that breakage. However, if it's not used, then I'm all for it.

**Comment by Mr21** [comment]
I contacted the guy already for that (one month ago) to find an answer on these mysterious arguments. But I think if we change this part he would update his plugin (It's just a copy/paste of jqueryui right?).

**Comment by scottgonzalez** [comment]
> But I think if we change this part he would update his plugin (It's just a copy/paste of jqueryui right?).

It's the opposite. jQuery UI used to import the easing plugin. But I rewrote all of the easings from scratch years ago.

**Comment by Mr21** [comment]
Yeah I know, I said that to upgrading easily the plugin, he just have to copy/paste your version.

**Comment by gnarf** [comment]
We could also detect the arity of the easing function in a "migrate" effects prefilter land and back-port the easing functions - provide a deprecation warning when using migrate.

**Comment by mzgol** [comment]
@gnarf Good idea.

**Comment by markelog** [comment]
@Mr21 it seems we all good on the change, pr is welcome!

**Comment by timmywil** [comment]
Yea, good idea @gnarf.
