### ISSUE TITLE
Traversing: use jQuery's push to avoid an unnecessary loop in .find

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery#2370]
See https://github.com/jquery/jquery/issues/2365#issuecomment-107726209

**Comment by gibson042** [comment]
@timmywil I think we need a jsPerf verifying performance impact before committing to this. I could easily see the improvement from doing less work in `pushStack` being overwhelmed by using Array methods on non-Arrays, and there's no reason to change back if it actually slows us down.

**Comment by timmywil** [comment]
Fair enough. I'll do a perf.

**Comment by mzgol** [comment]
@timmywil This seems like sth that can be done for 3.0.1. Please revert the milestone change if you disagree.
