### ISSUE TITLE
Could $.trim() regular expression be simple ?

### ISSUE THREAD

**Issue by FuDesign2008** [jquery/jquery#2371]
In `src/core.js` , I found that jQuery use the following regular expression to trim whitespace of string
```javascript
// Support: Android<4.1
// Make sure we trim BOM and NBSP
rtrim = /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,

```
In https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions ,  I found :
```text
`\s` Matches a single character other than white space. Equivalent to [^ \f\n\r\t\v​\u00a0\u1680​\u180e\u2000-\u200a​\u2028\u2029​\u202f\u205f​\u3000].
```
I think, the `\xA0` is equal to `\u00a0` which is contained in `\s` equivalent white-space characters, and 
the `rtrim` may can be simple:
```javascript
rtrim = /^[\s\uFEFF]+|[\s\uFEFF]+$/g,
```
Will it cause problem ?

Thank you.

**Comment by mzgol** [comment]
@FuDesign2008 Thanks for the analysis. Did you try this in Android 2.3 or 4.1? This code is mostly targetted at them.

In the `compat` branch it's needed for IE 8: https://github.com/jquery/jquery/commit/9e246dd7fa010f2b8e112ec5a57491167556c55a, maybe on `master` it's not.

**Comment by markelog** [comment]
> Android 2.3 or 4.1

I guess you mean less then 4.1?

**Comment by mzgol** [comment]
Yes, sorry, 2.3 or 4.0.

**Comment by markelog** [comment]
Just checking )

**Comment by FuDesign2008** [comment]
@mzgol  Thanks!

**Comment by dmethvin** [comment]
I don't think this is critical, it's a trivial change but still not clear whether we can apply it. I'll close this ticket but if we get a reply it can be reopened.
