### ISSUE TITLE
Click Event brick default Browser shortcuts behavior for link

### ISSUE THREAD

**Issue by porshkevich** [jquery/jquery#2372]
Middle-click work perfect (perhaps because it does not catch by default click event).

But as soon as everyone starts to hang handlers for the event click, together forget what is the behavior of the browser.

Behavior Examples:

|||
|----------------------|------------------------------------------|
| Open in Background Tab | Ctrl + Left-click or Middle-click |
| Open in Foreground Tab | Ctrl + Shift + Left-click or Shift + Middle-click |
| Open in New Window     | Shift + Left-click link  |

I suggest a default process events click OK in the browser, or to make it possible to switch off this behavior.

My example (it was used in the same project, so as not to rewrite all handlers)

```js
jQuery.event.special.click.preDispatch = function( event ) {
			return !(jQuery.nodeName( event.target, "a" ) && (event.ctrlKey || event.shiftKey));
		};
```

**Comment by dmethvin** [comment]
I am not sure what jQuery issue you are reporting. Can you post a code example at jsbin.com perhaps?

**Comment by porshkevich** [comment]
I wrote a small example

http://jsbin.com/vejoqupuka/1/

**Comment by dmethvin** [comment]
All of those links work identically for me in Chrome, Firefox, and IE11.

**Comment by porshkevich** [comment]
> All of those links work identically for me in Chrome, Firefox, and IE11.
Are you use the Shift and Ctrl softkey, as written in the link above in the description?

**Comment by dmethvin** [comment]
Yes, I used Ctri-Leftclick and Shift-Leftclick on each link.

**Comment by porshkevich** [comment]
I check this example in IE9, IE11, Firefox 37,38,40, Chrome 40, 42 in Windows 8.
Links dont work idenically, link with handler do not respond to clicks with softkeys.(though they should)

only IE11 Ctri-Leftclick work, but not Shift-Leftclick.

**Comment by dmethvin** [comment]
Nobody but the OP was able to reproduce this.
