### ISSUE TITLE
Refactor manipulation helpers

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2377]
Specifically, `domManip` and `buildFragment` they both has high cyclomatic complexity and long signature and we do stuff like this - https://github.com/jquery/jquery/blob/0019a463bdcb81dc6ba3434505a45774ca27f363/src/core/parseHTML.js#L39-41, which is also bad

**Comment by timmywil** [comment]
Closing in favor of tracking in the [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap).
