### ISSUE TITLE
CSS Layout and Container Sizing

### ISSUE THREAD

**Issue by ChrisBinge** [jquery/jquery#2379]
I am experiencing some strange behavior while I am trying to proportionally adjust font size to that of its parent container.

The issue is, when the function is called via document ready it does not compute accurately. When it resizes, after a few firings the function reaches an "equilibrium".

Here is a fiddle illustrating the issue: http://jsfiddle.net/nz7h2858/58/ you can also see the issue if you change the dimensions of the container and re-run the fiddle.

**Comment by mzgol** [comment]
I don't understand; you're reading the font-size and then modify it, why is it surprising that it may change?

**Comment by ChrisBinge** [comment]
The font-size does change, however the computed ratio on document ready is inconsistent. This leaves me with varying font sizes on page loads. 

According to the docs the jQuery ready() event shouldn't fire until the DOM is full constructed: "While JavaScript provides the load event for executing code when a page is rendered, this event does not get triggered until all assets such as images have been completely received. In most cases, the script can be run as soon as the DOM hierarchy has been fully constructed."

My question is why aren't the parent height and width being accurately measured on document ready?

**Comment by mzgol** [comment]
In your fiddle you're not executing anything on document ready but on
window load which is later.

Also, please try with the edge version. I can look into it further after
the weekend.

-- 
Michał Gołębiowski

**Comment by dmethvin** [comment]
It's unrelated to document ready: http://jsfiddle.net/nz7h2858/59/

I think you algorithm for fitting is having a problem but it's not jQuery.
