### ISSUE TITLE
Placeholder Problem on Filtered HTML

### ISSUE THREAD

**Issue by warkior** [jquery/jquery#2380]
Hello,

I *think* I've found a bug between how jQuery and IE11 interact with placeholders. First, see jsfiddle here:
http://jsfiddle.net/g0v1awvg/

You'll notice if you load the example in IE11 that the static placeholder text works properly, but the dynamically loaded placeholder stores the actual placeholder text in the textarea content.

The HTML is also being logged to the console, and you can clearly see that in the filtered result, the dynamic textarea content contains the placeholder text.

I believe this problem exists with both the .filter and .find jQuery methods.

James W.

**Comment by warkior** [comment]
Been doing more digging into this, and I think it may actually be an IE bug after all.
http://jsfiddle.net/vbsr2y66/3/

Apparently when running getElementById(), IE decides to dump the placeholder into the textarea content.

**Comment by dmethvin** [comment]
I still see the problem you describe on IE11 and also on the newer Edge 12. It isn't something jQuery can work around easily though. The quickest workaround at the app level would be to compare the actual text to the placeholder text and remove if they match.
