### ISSUE TITLE
Select-Element using .val() setting option to blank when wrong value passed

### ISSUE THREAD

**Issue by cyberhitesh** [jquery/jquery#2381]
As per the latest HTML5 specs it clearly stats that if the value setting to an select-element that does not exists than it should point to first option.

But after 1.9.1 release this behaviour is not working.

Latest HTML5 Specs Url: http://www.w3.org/TR/2014/REC-html5-20141028/forms.html#the-select-element

"If nodes are inserted or nodes are removed causing the list of options to gain or lose one or more option elements, or if an option element in the list of options asks for a reset, then, if the select element's multiple attribute is absent, the select element's display size is 1, and no option elements in the select element's list of options have their selectedness set to true, the user agent must set the selectedness of the first option element in the list of options in tree order that is not disabled, if any, to true."

There are older tickets related to this issue but they are marked closed stating 1.9.1 had inconsistent behaviour.

http://bugs.jquery.com/ticket/13514

jsFiddle Url: http://jsfiddle.net/ECFYX/9/

**Comment by timmywil** [comment]
Thank you for opening an issue, but the part of the spec that you quoted does not actually refer to programmatically setting the value. It refers to other cases. Specifically, adding/removing nodes (which doesn't apply), an option element asks for a reset (also doesn't apply here), or it's not multiple, the display size is 1, and no options are selected (this makes the browser responsible for setting the first option's selected state to true, but I believe this applies to default state, not dynamic state).

We are actually doing the right thing, as per another part of the spec:

> The selectedIndex IDL attribute, on getting, must return the index of the first option element in the list of options in tree order that has its selectedness set to true, if any. If there isn't one, then it must return −1.

This dictates that, programmatically, there are times when there is no selected option. When passing a value to `.val()` that is not present in the select element, we set selectedIndex to -1. More discussion was [here](https://github.com/jquery/jquery/pull/1191).
