### ISSUE TITLE
.width() and .height() return 0 after adding an element styled with DXImageTransform.Microsoft.gradient

### ISSUE THREAD

**Issue by benjamin-albert** [jquery/jquery#2385]
The company I work for has some web pages that use IE 8 compatibility mode.

After updating form jQuery 1.11.0 to 1.11.3 the .width() and .height() methods return 0 after adding an element styled with filter: progid:DXImageTransform.Microsoft.gradient.

If you call the method again one line after the first call it will return the correct width.

Run this HTML in internet Explorer 10 or 11 using IE 8 or 9 compatibility mode to reproduce and understand the issue:

	<html>
	<head>
	<script src='http://code.jquery.com/jquery-1.11.3.js'></script>
	<style>
	.ie-bug-example {
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#357ed9', endColorstr='#6ca1e5',GradientType=0 );
	}
	</style>

	<script>
	$(function() {
		// Replacing tf.offsetWidth with $(tf).width() produces 
		// the same results.
		var tf = $("#tf")[0];

		$("#button").click(function() {
			alert(tf.offsetWidth);

			$("body").append($( $("#template").html() ));

			alert(tf.offsetWidth);

			alert(tf.offsetWidth);
		});
	});
	</script>

	<script id='template' type='text/template'><span class='ie-bug-example' /></script>

	</head>
	<body>

	<input type='text' size='25' id='tf' />
	<input id='button' type='button' value='Display text field&#39;s width'></input>

	</body>
	</html>

In jQuery 1.11.0 the following test was performed:

	jQuery.cssHooks[ name ] = {
			get: function( elem, computed, extra ) {
				if ( computed ) {
					// certain elements can have dimension info if we invisibly show them
					// however, it must have a current display style that would benefit from this
	Calls elem.offsetWidth first time-->	return elem.offsetWidth === 0 && rdisplayswap.test( jQuery.css( elem, "display" ) ) ?
						jQuery.swap( elem, cssShow, function() {
							return getWidthOrHeight( elem, name, extra );
						}) :
			Calls elem.offsetWidth second time producing the correct result-->	 getWidthOrHeight( elem, name, extra );
				}
			},

In jQuery 1.11.3 the `elem.offsetWidth === 0` test was removed, which seems to cause the wrong result to be returned instead.

The issue only seems to appear in Internet Explorer 10 and 11 running in 8 or 9 (standards) compatibility mode.
The weird thing is that I cannot reproduce this in the real IE 9.

Unfortunately this bug prevents me from updating to the latest version of jQuery.
Thank you for your support.

**Comment by mzgol** [comment]
Thanks for the report but jQuery has never supported IE Compatibility Modes so some things may break. There are a lot of configurations here, basically every IE "X in IE Y mode" which is 6 cases. Now, we could decide some are more important (like IE11 in IE8 mode?) but this would still require additional work to make it happen.

The thing is we have a couple of breaking changes coming in jQuery 3.0.0 Compat (the continuation of jQuery 1.x that will support IE8+), e.g. Deferreds are now Promises/A+ compliant. How likely are you (or any other enterprise) to upgrade to jQuery 3.0 Compat when it comes out, taking into account that you might have to fix some code that breaks before of non-backwards compatible changes in jQuery? We're not developing jQuery 1.x line anymore so any new browser configuration to support would arrive only in jQuery 3.0 Compat. To make it happen we'd have to know that people will upgrade to this version and will use the fact we added support but that seems unlikely to me...

@benjamin-albert what are your thoughs to all that?

**Comment by benjamin-albert** [comment]
Thank you for your response.

I agree that supporting all the various compatibility modes of internet explorer is ridiculous.
In fact supporting just one configuration (IE 11 in IE 8 mode) drives me crazy.

If I had control over all the JavaScript code In our products I would not support IE 8 or 9 at all, most of our users are using IE 10 or 11 or they have Chrome installed.

This is not the only jQuery bug i've seen occurring only in IE 8 compatibility mode, and the reason I didn't report those bugs is because I agree that these are not jQuery bugs they are internet explorer X in mode Y bugs and usually I just work around those bugs.

The difference is that this bug is regression (as i've pointed out in the issue the exact same code worked in jQuery 1.11.0 and stopped working in 1.11.3).

I have no problem working around this bug, but because it used to work I thought it was more appropriate to report it and let you handle it.

With regards to jQuery 3.0.0 Compat I am excited and eager to try it out in our products.

Fortunately I have control over most of the code running jQuery in our products so
I'm sure I'll upgrade to jQuery 3.0.0 Compat as soon as it's released.

I cannot speak on behalf of other companies, but I know there is a lot of IE 8/9 dependent code (JavaScript, VBScript, ActiveX etc...)  in the enterprise (not just in our products) that also use jQuery and I believe they can benefit from new versions of jQuery.

They may not choose to upgrade immediately when jQuery 3 Compat is released but i'm almost sure they will want to down the road.

**Comment by mzgol** [comment]
> I know there is a lot of IE 8/9 dependent code (JavaScript, VBScript, ActiveX etc...) in the enterprise

That's the thing, if it's just IE11 in IE8 mode then we have one more thing to add, if it's also IE11 in IE9 mode, IE10 in IE9 mode, IE10 in IE8 mode etc. then it becomes way harder.

It seems that Microsoft is urging enterprises to update to IE11 and use the IE8 mode there in the transition phase but I wonder how many more configurations are there in the wild significantly often...

> I have no problem working around this bug, but because it used to work I thought it was more appropriate to report it and let you handle it.

Sure, it's good to know if there's the problem anyway!

> The difference is that this bug is regression (as i've pointed out in the issue the exact same code worked in jQuery 1.11.0 and stopped working in 1.11.3).

Technically speaking, a regression is only if in one version we work on a particular supported browser and in a new one doesn't. Unsupported configurations are not tested so may break any time.

BTW, I don't see the `offsetWidth` test being removed, the conditions have just been swapped.

1.11.0 code:
```js
if ( computed ) {
	// certain elements can have dimension info if we invisibly show them
	// however, it must have a current display style that would benefit from this
	return elem.offsetWidth === 0 && rdisplayswap.test( jQuery.css( elem, "display" ) ) ?
		jQuery.swap( elem, cssShow, function() {
			return getWidthOrHeight( elem, name, extra );
		}) :
		getWidthOrHeight( elem, name, extra );
}
```

1.11.3 code:
```js
if ( computed ) {
	// certain elements can have dimension info if we invisibly show them
	// however, it must have a current display style that would benefit from this
	return rdisplayswap.test( jQuery.css( elem, "display" ) ) && elem.offsetWidth === 0 ?
		jQuery.swap( elem, cssShow, function() {
			return getWidthOrHeight( elem, name, extra );
		}) :
		getWidthOrHeight( elem, name, extra );
}
```
so I'm not sure where the problem you experience really lies.

**Comment by dmethvin** [comment]
The IE8-like "Enterprise Mode" offered by IE11 is supposed to become the "standard" way for enterprises to execute legacy intranet apps that need IE8 functionality. As of early next year, the real IE8 will not be supported by Microsoft and there isn't much reason for anyone to test against real IE8 in *new development*.

If the target of your development is enterprises that use IE8 Enterprise Mode, those companies should be able to specifically turn IE8 mode on just for old sites that need that crutch. They shouldn't need to turn on IE8 mode for your new code using recent jQuery if you're writing it today, since you won't be using the legacy features that necessitated the IE8 mode in the first place.

All that said, can you clarify why you're testing a recent version of IE11 in IE8 mode? Does this site/code also need to run in recent Firefox/Chrome/Safari? If you are supporting ancient code bases you're probably better off using an older jQuery anyway.

**Comment by dmethvin** [comment]
This ticket has been inactive quite a while so I'm closing it.
