### ISSUE TITLE
add children nodes to DOM generating api as: $('<div/>', attrdict, children)

### ISSUE THREAD

**Issue by cailiang9** [jquery/jquery#2386]
So that we are possible to write very clean UI code together with coffeescript, (similar to jade page template).
I wrote 10 lines of code to achieve that: https://gist.github.com/cailiang9/8509291d29f3fcd7acad#file-plot-coffee-L7
please read create_table and create_gridtables function for usage. 

I think we can still simplify and I'm wondering if it is possible to be merged into jquery (the code amount is very small).

**Comment by gibson042** [comment]
Thanks for the suggestion, but `jQuery` already has too many signatures for our liking (considering only the first argument, behavior differs for functions, HTML strings, selector strings, Array-like objects, and other objects). Anything that can be handled by subsequent method composition is preferred, though you are free to continue extending functionality as you have shown above.
