### ISSUE TITLE
.on() vs .addEventListener(): multiple identical event listeners

### ISSUE THREAD

**Issue by EvgenyOrekhov** [jquery/jquery#2387]
If we attach the same event listener multiple times with jQuery's `.on()`, it will be attached multiple times.
If we attach the same event listener multiple times with the native `.addEventListener()`, it will be attached only once.
Demo: http://jsbin.com/ramaxayiwo/edit?js,console,output

I'd prefer jQuery's `.on()` to work as the native `.addEventListener()` and discard the subsequent attaches of the same event listener.

**Comment by timmywil** [comment]
Thank you for opening an issue, but we discussed this in the weekly meeting and decided this would cause too many breakages. We're closing for backcompat reasons. Also, we don't think the complication to the codebase is worth it as this is a case that is not encountered often and can be handled in user code.
