### ISSUE TITLE
Handlers: ability to specify order of execution

### ISSUE THREAD

**Issue by cezarykluczynski** [jquery/jquery#2388]
Some event systems, like ZF2 EventManager, have ability to specify order, or priority, of handlers execution. Currently, in jQuery, it's impossible to execute handlers in order different from the one they were attached in, without hacking the internals. Do you think order of execution is something that could land in jQuery? Without breaking BC, priority should be put before or after all arguments, so:

```javascript
$( "div" ).on( 100, "click", "a", data, handler );
$( "div" ).on( "click", "a", data, handler, 100 );
```

**Comment by timmywil** [comment]
Thank you for opening an issue, but this reflects the z-index problem in CSS. There's massive potential for abuse and it further complicates the `.on()` signature.
