### ISSUE TITLE
Microsoft Edge fails the focusin support test

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#2389]
In Microsoft Edge (from the newest Windows 10 build 10130) there is no `window.onfocusin` which makes our `focusin` support test to fail and use our polyfill for the `focusin/focusout` event in Edge.

It would be good to contact the MS team about this problem before Windows 10 arrives. (@dmethvin?)

**Comment by markelog** [comment]
Oh god, no, that is bad, i don't any good way to feature test it. Does it behave according to the specification? Or it follows Chrome style? 

As i said in the https://github.com/jquery/jquery/issues/2360#issuecomment-106876577 we need a reliable way to test it.

@jacobrossi could please help us out here?

**Comment by jacobrossi** [comment]
Let me look at the change we made specifically and I'll reply back with some details

**Comment by mzgol** [comment]
@jacobrossi Thanks!

**Comment by jacobrossi** [comment]
Update: we already have an internal bug tracking this since we run the jQuery test suite in our automation.  I reached out to the bug owner for details if this is something deliberate we changed or just a bug. I suspect we changed to match Chrome behavior.

**Comment by mzgol** [comment]
@jacobrossi thanks, looking forward to it. We'd love help with https://github.com/jquery/jquery/issues/2390 as well; we have a workaround for IE that sniffs for `documentMode` that now breaks.

**Comment by markelog** [comment]
@jacobrossi thank you for the replay. 

> I suspect we changed to match Chrome behavior.

Please don't follow chrome behaviour if it contradicts the specification, which it does in this case :(

**Comment by markelog** [comment]
We might switch to email conversation, but just in case -
/cc @reybango

**Comment by mzgol** [comment]
Do we still need this ticket? There's nothing else to do on our side so e.g. having a milestone seems wrong here.

**Comment by markelog** [comment]
Well, `onfocus(in | out)` still works correctly in Edge but now we can't check it, we might come up with different way to solve it or leave it as a remainder for us to bug Edge ppl :-).

Maybe @jdalton could shade some light on it? Like if this issue has different solution that we overlooked or if whenever or not it will be solved soon on the Edge end?

**Comment by mzgol** [comment]
Yes, but keeping it on the 3.0.0 milestone creates an impression we have more work to do for 3.0.0 than we really do and wer're trying to lower the number down currently.

So I'd like to at least remove the milestone.

**Comment by markelog** [comment]
Done :-)

**Comment by jdalton** [comment]
I've looked into this and haven't come up with a tiny snippet that doesn't require inserting into the dom. I'll keep kicking it around.

**Comment by timmywil** [comment]
I trust @jdalton has been thoroughly bugged about this. I've added a note to the [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap) for keeping in touch with Edge about focusin/out, but am closing this issue.

**Comment by jdalton** [comment]
Rock.

**Comment by phistuck** [comment]
@markelog -
> Please don't follow chrome behaviour if it contradicts the specification, which it does in this case :(
I do not see anything relevant filed on https://crbug.com - if no one hollers, there is less chance of them adding it...
