### ISSUE TITLE
Microsoft Edge fails the "Iframe dispatch should not affect jQuery (#13936)" test

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2390]
Microsoft Edge (from the newest Windows 10 build 10130) fails the "Iframe dispatch should not affect jQuery (#13936)" test with an error:
```js
{
  "description": "Permission denied",
  "message": "Permission denied",
  "name": "TypeError",
  "number": -2146828218
}
```
All others pass if you test modules individually. There are a couple of support tests that now pass (compared to IE11): `boxSizingReliable` (this one didn't pass in the previous build from April 29), `noCloneChecked`, `optSelected`, `radioValue`. The `focusin` test now fails, see #2389.

Interestingly enough, if you run the whole test suite it fails a lot more tests; most likely this one leaves the browser in a bad state.

Screenshot:
![screen shot 2015-06-14 at 02 02 37](https://cloud.githubusercontent.com/assets/1758366/8148543/55c52682-12a2-11e5-87ed-3de9395b9bb2.png)

**Comment by mzgol** [comment]
Note: I added MS Edge support test results in 8e111df641cca3e1b75b31a1971bfc89014b4ded & 546593bdd29752def705b172380b737ce8758ba9.

**Comment by mzgol** [comment]
Sizzle issue: https://github.com/jquery/sizzle/issues/339

**Comment by gibson042** [comment]
@jacobrossi Specifically, this would not be an issue if IE Edge didn't throw "permission denied" when accessing the document of an unloaded iframe; see https://github.com/jquery/sizzle/commit/a431c0254a1910a9a803539239e9b2954ffadf7d and http://bugs.jquery.com/ticket/13936 .

**Comment by mzgol** [comment]
> Specifically, this would not be an issue if IE Edge didn't throw "permission denied" when accessing the document of an unloaded iframe

Yup, especially that we cannot change the code of many older jQuery versions that live in the wild.

**Comment by mzgol** [comment]
For people following, there has been a discussion about that at https://github.com/jquery/sizzle/commit/28f4c67c508719cc76e2075dce0e4cbe0e325919.

**Comment by mzgol** [comment]
I'd mark it as a blocker; it's very simple to revert the additional check and it'd be good to have it in for an alpha.

That'd require a Sizzle update, though, so I'll leave it up to you.

**Comment by jacobrossi** [comment]
We're tracking fixing this.  Unfortunately there's a fairly gnarly issue related to iframe security features we have that make this quite the issue to fix.  We're working on stabilizing Edge for the first release, which means a massive change like this isn't appropriate at this time.  But we're going to look at fixing this nonetheless after we get the first version out the door.

**Comment by mzgol** [comment]
It's now fixed in Sizzle so I added the "Awaiting Sizzle update" label.
