### ISSUE TITLE
The build process requires no space between closing `}` and `)`

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2399]
Our build process requires no space between closing `}` and `)` for variable modules (i.e. those with paths containing `/var/`). This makes it impossible to follow our style guide and write those modules in this way:
```js
define( function() {
	/* code */
} );
```
instead of currently required:
```js
define( function() {
	/* code */
} );
```
There may be other cases like that in used regexes.

I'll assign this to @timmywil since it's his code. I hope you don't mind, Timmy. :-)

**Comment by timmywil** [comment]
Yea, I'll make it optional.

**Comment by mzgol** [comment]
Why wasn't this auto-closed?
