### ISSUE TITLE
Try to reuse div creation

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2405]
`div = document.createElement( "div" )` construction used in many places, we can try to modulize it

**Comment by Mr21** [comment]
Hi @markelog :)

if by *modulize it* you think about doing that:
``` javascript
define([
	"../var/document"
], function( document ) {
function createElement( nodeName ) {
	return document.createElement( nodeName );
}
return createElement;
});
```
It's save **-15** bytes by remove all the **16** occurences `document.createElement` in the code.
```
   raw     gz Sizes
255862  75752 dist/jquery.js
 84426  29376 dist/jquery.min.js

   raw     gz Compared to master @ 5fe76c663f8a4986af62edb434a1708c006d0b21
   -32    +15 dist/jquery.js
  -125    -15 dist/jquery.min.js
```

If you want I can make a PR with this: https://gist.github.com/Mr21/81a1c21e0cbf7136245a

**Comment by mzgol** [comment]
@Mr21 I believe it was more about re-using the test div itself, i.e.:
```js
define([
    "../var/document"
], function( document ) {
return document.createElement( "div" );
});
```
& similar for other types of test nodes that are created. If it helps with size, a separate `createElement` function could be created as well, I'd guess it won't save size, though (but feel free to check).

Please don't do anything for `compat`, though, before #2504 lands as it will change some test-related things.

**Comment by markelog** [comment]
> I believe it was more about re-using the test div itself

Yep

**Comment by timmywil** [comment]
Closing in favor of tracking in the [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap).

**Comment by mgol** [comment]
Not relevant anymore as `master` has almost no feature tests.
