### ISSUE TITLE
Reverse support.ownLast

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2406]
`jQuery.support.ownLast` is the only support test that's supposed to be `false` when it succeeds. It's confusing, we should reverse its value.

**Comment by mzgol** [comment]
PR: #2408

**Comment by mzgol** [comment]
Closed via #2408.

**Comment by mzgol** [comment]
Clearing the milestone as we're not releasing `compat` after all and this change won't be applicable to code that has to support IE6/7.

**Comment by markelog** [comment]
@mzgol fyi, since we are releasing another compat, `wonfix` removed

**Comment by mzgol** [comment]
Not compat, but regular 1.x. I added wontfix here because this issue doesn't matter for code soon to be dead. If it's included in your 1.12-stable branch, though, then removing wontfix is fine.

**Comment by mzgol** [comment]
But, if you're removing the wontfix label, please remember to open the issue and assign the proper milestone...

**Comment by markelog** [comment]
> Not compat, but regular 1.x.

It is just a name change, so for me, it is a same thing.

> But, if you're removing the wontfix label, please remember to open the issue and assign the proper milestone...

should be in general

**Comment by markelog** [comment]
> Not compat, but regular 1.x.

Apparently, for the team too, since we still use `1.x` label
