### ISSUE TITLE
Remove possible overmodulization

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2407]
We can identify places, like https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/src/ajax/var/location.js which could be considered as `overmodulization` since it increases the size and complicates the code.

**Comment by mzgol** [comment]
OTH, `document` being a variable helps with size so it's not always bad for size. With `location` removing it helps with size because you may just not use variable at all. In other cases I doubt removing a module would help too much.

**Comment by markelog** [comment]
This is why i used words like "possible", "identify" and "overmodulization" if modulization doesn't help, it should be removed if it does then it should stay.

Assumptions are bad when you can actually check stuff.

**Comment by timmywil** [comment]
Closing in favor of tracking this in our [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap). It is ongoing work that is not necessarily done after a single pass.
