### ISSUE TITLE
Possible simplification of support functions

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2409]
`jQuery.support` functions check environment invariants only, they could also check state properties of inconstant states too.

For example, <a href="https://github.com/jquery/jquery/blob/842958e7aecd0d75a7ee9e2aaec83457701aa2f3/src/css/curCSS.js#L30">here</a> we do 

```js
if ( !support.pixelMarginRight() && rnumnonpx.test( ret ) && rmargin.test( name ) ) {
```
Instead we could do 
```js
if ( !support.pixelMarginRight( ret, name ) ) {
```
Encapsulating and simplifying such conditions.

**Comment by markelog** [comment]
@timmywil, @dmethvin, @gibson042 @mzgol opinions?

**Comment by mzgol** [comment]
I think the example you provided is quite confusing as the test name says nothing about its parameters. Also, it's harder to verify if we didn't break the test with a code change if the function accepts parameters.

I'd prefer it to stay the way it is.

**Comment by gibson042** [comment]
At first glance, I agree with @mzgol. The support methods (formerly properties) are understandable as environment behavior descriptors, but would likely be more confusing as broader "extra work detectors".

**Comment by markelog** [comment]
It seems encapsulating should serve to test isolation and code simplification as postulated by the OOP model, it is many times were perceived that analogues to our `support` API is a `Modernizr` lib which doesn't employ such approach.

Is there any examples of such tactic anywhere else?

**Comment by markelog** [comment]
fyi, this -
```js
if ( !support.pixelMarginRight( ret, name ) ) {
// might as well looks like
if ( !support.areReturnCSSValuesReliable( ret, name ) ) { // or something like that
```

**Comment by mzgol** [comment]
We have the support object that has one and only one purpose - to verify if a specific engine supports something well or has a bug. That's it, it's hard to get simpler than that.

I really don't see the gain of the switch of the approach here.

**Comment by dmethvin** [comment]
Yeah, I'd prefer to keep the browser detection part pure. It's hard to see into the future, but by rolling the other logic into the `support` object it seems like we would be mixing two things. The `support` object is about whether the browser has a bug and the rest is more what we do about it.

**Comment by timmywil** [comment]
Sorry, @markelog. Don't want to stack on the pile against you, but I'm for keeping it the way it is.

**Comment by markelog** [comment]
Okay, lets table this discussion until i will became a ruler of the words!  :-)

Nevertheless, i'm glad we had this discussion, i just hope it is not because i'm have luck of persuasion skills :)
