### ISSUE TITLE
Latest jQuery is not xhtml-friendly in Internet Explorer 11

### ISSUE THREAD

**Issue by FuweiChin** [jquery/jquery#2411]
In my case the page index.xhtml was a hello-world page served as **application/xhtml+xml** and rendered with **xhtml 1.0 strict mode**.

When loaded jQuery 2.1.4, an error said <span style="color:#c00000">"XML5617: Illegal XML character. Line: 1, Column 105"</span> in Dev Tool Console, before any other script.

Here is the circumstance 
User Agent: `Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko`
Text file encoding: `determined from content UTF-8`
Content Type `Content-Type: application/xhtml+xml`
XML Declaration: `<?xml version="1.0" encoding="utf-8"?>`
Charset: `<meta charset="utf-8" />`

I tried several times in order to ensure that the problem was caused by jQuery:
<dl>
	<dt>case 1: No script</dt>
	<dd>No error shown</dd>
	<dt>case 2: Simple script alert("Hello world!");</dt>
	<dd>No error shown</dd>
	<dt>case 3: import jQuery 2.1.4</dt>
	<dd>An error said "XML5617: Illegal XML character. Line: 1, Column 105" in Dev Tool Console</dd>
	<dt>case 4: import jQuery 1.11.3</dt>
	<dd>An error same as case 3.</dd>
	<dt>case 5: import jQuery 1.7.1</dt>
	<dd>No error shown</dd>
</dl>

**Comment by gibson042** [comment]
This looks like a duplicate of gh-2411, which is noisy but harmless (and fixed in `master`). @FuweiChin, can you confirm that the problem doesn't exist if you load http://code.jquery.com/jquery-git.js instead of jQuery 2.1.4?

**Comment by FuweiChin** [comment]
The problem disappears when I load http://code.jquery.com/jquery-git.js (v3.0.0-pre 842958e7aecd0d75a7ee9e2aaec83457701aa2f3), according to your guide.
