### ISSUE TITLE
Illegal constructor on Chrome -- Requires new on FF

### ISSUE THREAD

**Issue by Gourm** [jquery/jquery#2412]
I'm trying to use jquery to create a fancy box, but i have an issue loading jquery's script. I tried different versions 1.x and 2.x. 

All return the same error, on chrome it's:

Uncaught TypeError: Illegal constructorj =>
Query.Callbacks.fire @ VM965 jquery.js:3148
jQuery.Callbacks.self.fireWith @ VM965 jquery.js:3260
jQuery.extend.ready @ VM965 jquery.js:3472completed 
@ VM965 jquery.js:3503

on Firefox:
TypeError: Constructor Document requires 'new'

This is the method related.
 for ( ; list && firingIndex < firingLength; firingIndex++ ) {
                    if ( list[ firingIndex ].apply( data[ 0 ], data[ 1 ] ) === false && options.stopOnFalse ) {
                        memory = false; // To prevent further calls using add
                        break;
                    }
                }

Any idea where could it comes from?

**Comment by timmywil** [comment]
Thank you for opening an issue, but you can find support on the [forums](http://forum.jquery.com) or in the #jquery irc channel.
