### ISSUE TITLE
empty attribute selector doesn't work since 1.11.1

### ISSUE THREAD

**Issue by kasanoppa** [jquery/jquery#2414]
empty attribute selector works at 1.11.0
$("a[href=]")

but it doesn't work since 1.11.1

**Comment by kasanoppa** [comment]
By document, (https://api.jquery.com/attribute-equals-selector/)

value: An attribute value. Can be either an unquoted single word or a quoted string.

I think it is correct implementation. isn't it?

**Comment by Aha00a** [comment]
https://api.jquery.com/attribute-equals-selector/ 
> value: An attribute value. Can be either an unquoted single word or a quoted string.

In my humble opinion, it's ambiguous. Please clarify for the empty string.

Thanks, and have a nice day.

**Comment by gibson042** [comment]
The empty string is not a word, so must be quoted. We used to be more lenient, but moved to align with the CSS specifications ([in which](http://www.w3.org/TR/css3-selectors/#attribute-selectors) the value must either be a quoted [string](http://www.w3.org/TR/CSS21/syndata.html#strings) or an unquoted [identifier](http://www.w3.org/TR/CSS21/syndata.html#value-def-identifier)). Check for yourself with e.g. `document.querySelector`.

**Comment by Aha00a** [comment]
I tested some css queries. It works correctly as you said.
http://jsfiddle.net/e9tpL4mc/

Thank you for your reply.
