### ISSUE TITLE
%svgElement%.getElementsByClassName is undefined in IE

### ISSUE THREAD

**Issue by extempl** [jquery/jquery#2415]
Previously I was using in my Rails project jquery-rails gem which used jquery 1.8.4 which has code:

            // Speed-up: Sizzle(".CLASS")
			} else if ( (m = match[3]) && assertUsableClassName && context.getElementsByClassName ) {
				push.apply( results, slice.call(context.getElementsByClassName( m ), 0) );
				return results;
			}

You can see, that there is `context.getElementsByClassName` is used in the `if` statement. In 1.11.2+ versions of jQuery there is `support.getElementsByClassName` is used, which is always `true` since it works well for HTML DOM elements.
Though, `querySelectorAll` is works well for svg elements.

P.S. this change was made in [1.11.2 version](https://github.com/rails/jquery-rails/commit/ff93f91b279a760472e459e8e4ad6cdf1cc5bcf4#diff-18de83a8bb7b63c7f40207000cf6984cL827)

**Comment by gibson042** [comment]
Thank you; this duplicates jquery/sizzle/issues/322 and will be fixed in jQuery 3.0 (it's already checked in).
