### ISSUE TITLE
.data() bug?

### ISSUE THREAD

**Issue by baijunjie** [jquery/jquery#2416]
// When the key is "xxx-xxx"
$div.data({"aaa-bbb": 1});
$div.data("aaa-bbb", 2); // Note that if you use this way to modify values
console.log($div.data("aaa-bbb")); //  output 1 (Should not to 2?)

$div.data({"aaa-bbb": 1});
$div.data({"aaa-bbb": 2});
console.log($div.data("aaa-bbb")); // output 2 (This is the right)

**Comment by mzgol** [comment]
Thanks for the report. Issues like that made us decide we want to go in the HTML5-like route, i.e. the keys are always camelCased. This fix is already present in the preview version and will be available in jQuery 3.0.0:
http://jsbin.com/zoqiyi/1/edit?html,js,console

See #2257 for more details.
