### ISSUE TITLE
jQuery.getJSON() fails silently if JSON cannot be parsed

### ISSUE THREAD

**Issue by rafaelcichocki** [jquery/jquery#2431]
In the jQuery.parseJSON function, there is the following code which throws an error when data cannot be parsed: 

    return window.JSON.parse( data + "" );

I don't quite follow at which point this is used in jQuery.getJSON(), but when first encountering this issue, it looked as if the getJSON() callback was simply not being called.

It would be nice if there is some kind of error propagation. (My error was `"Uncaught SyntaxError: Unexpected token ..."`)

**Comment by timmywil** [comment]
Thank you for opening an issue. Could you provide a reduced test case from http://jsbin.com to help us assess the issue?

**Comment by dmethvin** [comment]
The OP hasn't replied, but it sounds like this is correct behavior. jQuery doesn't try to catch errors like this.
