### ISSUE TITLE
feature request: jQuery(fn, arg1, .. argN )

### ISSUE THREAD

**Issue by neonics** [jquery/jquery#2435]
I'd like the method signature for jQuery(callback) changed to allow for optional parameters, which are passed to the callback function.

This will allow me to write:

              $(function($,script){
              },document.currentScript)
              
instead of

              (function(script) { $(function($) {
              })})( document.currentScript )

**Comment by mzgol** [comment]
The jQuery function has already [a lot of signatures](http://api.jquery.com/jQuery/) and it doesn't seem worth it to add another one, especially that the proposed API doesn't sound intuitive.

**Comment by neonics** [comment]
Thank you for having taken the time out of your undoubtedly busy schedule to take a look.

I must however point out that you have not understood my request, which is to consider  **modifying** the **existing** third signature to allow for optional parameters, **not** adding another one. This does away with the first part of your 'reason'. 
To be clear: the section on the page you reference (that I *did* consult prior to coming here) would then look like this:

        jQuery( callback [, args ] )
                jQuery( callback [, args ] )

Next, nothing about jQuery is intuitive; it is all made up: it merely follows design patterns, also made-up, which is why they have to be learned, like the jQuery API. However, I assume you are talking about 'the jQuery way', and in that light, I would have loved to have received a one-liner response from the 'masters' showing the 'proper' way to pass parameters to a callback function, rather than a "doesn't seem worth doing something *different* from what you said, especially because I don't understand what you *did* say".

However, I'll take the "no discussion" and leave you to more important matters.

**Comment by dmethvin** [comment]
Can't this be done without a change inside jQuery? I agree that the `$.ready` signatures are already pretty complicated, even if this is just talking about changing the args passed to the function. You can capture this information yourself and it would be more explicit what is happening. If we did change the signature you would be tied to jQuery 3.0+ and your code would potentially fail in older versions.

**Comment by mzgol** [comment]
We don't have the "no discussion" approach; however, there are a lot of requests to extend the jQuery API via various helpers and we have to consider a proposal very useful to get it included since everyone pays the price for the size of the addition, potential bugs that happen, etc. For a proposal to be included, we need to get convinced it'd be useful enough and that it wouldn't have too many drawbacks.

In this case, your original (slightly modified) proposal:
```js
jQuery( function( $, script ) {
    console.log( "script:", script );
}, document.currentScript );
```
instead of being written currently as:
```js
( function( script ) {
    jQuery( function( $ ) {
        console.log( "script:", script );
    });
} )( document.currentScript );
```
could be written in this way:
```js
jQuery( function( $ ) {
    var script = document.currentScript;
    console.log( "script:", script );
} );
```
It's cleaner, more understandable & doesn't require changes inside jQuery.

**Comment by neonics** [comment]
Hi, thanks again for your attention. I understand making changes to the API is not done lightly, and I merely wanted to raise this issue so that it can be considered, as well as for documentation purposes, given the relatively recent availability of `document.currentScript`.

You are right - the third snippet above is the most clean and explicit, and actually was my initial attempt. Unfortunately, it does not work. By the time the function is called, `document.currentScript` is `null`.

Alternatively, jQuery might provide a `.currentScript()` function sometime in the future that works in all contexts, but this approach is likely to have an even bigger impact.

**Comment by mzgol** [comment]
> By the time the function is called, document.currentScript is null.

Right, I didn't think about it, that makes it a little more ugly to deal with.

I'll reopen then; I'm still not sure we want to do it but let's hear the opinion of others.

**Comment by scottgonzalez** [comment]
Can't you just use `jQuery.proxy()` or `Function#bind()`? Not quite as clean, but still obvious and fairly short.

**Comment by neonics** [comment]
That works indeed and is a little cleaner than the IIFE:

          $(
            $.proxy(
              function() { console.log("script:", this ) },
              document.currentScript
            )
          );

**Comment by timmywil** [comment]
Thank you for opening the issue, but we've decided to close this and defer to other solutions, such as `$.proxy`.

**Comment by neonics** [comment]
I'm perfectly fine with that! Thanks for the feedback and the awesome library!
