### ISSUE TITLE
The event module is listed twice in the modules dropdown on the QUnit test page

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2437]
The event module is listed twice in the modules dropdown on the QUnit test page. This is probably because of https://github.com/jquery/jquery/blob/a44cfa00665d21c3197e25c2d63741dc15f6ffb9/test/unit/ready.js#L1.

@timmywil, any idea why it's written this way?

Screenshot: 
![screen shot 2015-06-30 at 16 18 16](https://cloud.githubusercontent.com/assets/1758366/8433049/d6dbd02e-1f43-11e5-89eb-efef456d152b.png)

**Comment by timmywil** [comment]
We can just call that the "ready" module; it needed to be separated because the ready tests need to load synchronously in AMD mode.

**Comment by mzgol** [comment]
> We can just call that the "ready" module

:+1:

**Comment by mzgol** [comment]
No matter which one of these `event` entries I choose, I still get the same `event` tests executed; the double entry doesn't appear in AMD mode, though. How is it all wired up?
