### ISSUE TITLE
Core: .eq( i, true) modulo feature

### ISSUE THREAD

**Issue by Mr21** [jquery/jquery#2443]
Hi :)

To day (at work) I had to quickly fix something and I wrote:
``` javascript
jqA = jqCollection.eq( ind++ % jqCollection.length );
jqB = jqCollection.eq( ind   % jqCollection.length );
```
For example, if `jqCollection.length` is `3` I wanted to get the `0,1` after the `1,2` and after the `2,0` and again the `0,1` etc. But if I wanted to go in the other direction it's more complex to write a negative modulo.

Why not integrate this modulo directly inside the `.eq` ?
Instead of the actual code :
``` javascript
eq: function( i ) {
	var len = this.length,
		j = +i + ( i < 0 ? len : 0 );
	return this.pushStack( j >= 0 && j < len ? [ this[j] ] : [] );
}
```
Maybe we can write :
``` javascript
eq: function( i, mod ) {
	var len = this.length;
	i = mod !== true ? +i : i % len;
	if ( i < 0 ) {
		i += len;
	}
	return this.pushStack( i >= 0 && i < len ? [ this[ i ] ] : [] );
}
```

Or maybe a new one methode :
``` javascript
eq: function( i ) {
	return i < this.length ?
		this.at( i ) :
		this.pushStack( [] );
},
at: function( i ) {
	var len = this.length;
	i %= len;
	if ( i < 0 ) {
		i += len;
	}
	return this.pushStack( len ? [ this[ i ] ] : [] );
}
```

**Comment by dmethvin** [comment]
A new method would definitely be a better way to do it, rather than adding a [boolean trap](http://ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html). In that case, though, you can just do a plugin.

**Comment by mzgol** [comment]
I agree introducing a boolean trap would be a bad idea. Also, what @dmethvin said - new methods are better to introduce as a plugin first, we don't want to increase our byte size too much.
