### ISSUE TITLE
No longer access to jQuery Custom Events using $({}) 

### ISSUE THREAD

**Issue by Roland1975** [jquery/jquery#2445]
The following snippet will output the **jQuery Custom Event object** using **jQuery 1.11.***
```
var o = {};
$(o).on('/done', function() {});
$(o).trigger('/done');
```
This will output:
```
Object.jQuery1113020498902583494782: { events:..., handle:..., toJSON:... }
```
From **version 2.* onward**, this is no longer the case. What a pity as that object provides an insight of the all the custom events.

Are you aware of that issue?

**Comment by mzgol** [comment]
The whole data module has been rewritten from scratch in jQuery 2.0 and events rely on it. What you're seeing is private data that shouldn't be relied on; in jQuery 2.0 it has been properly hidden but it was never guaranteed to be available.

There is no officially sanctioned API to get the list of all handlers attached to the element.

If you just need it for debugging purposes, you can use `$._data(o)`. Note that this is unsupported API and may disappear one day, similarly how the hack you described has disappeared in jQuery 2.0.

**Comment by mzgol** [comment]
Also, the triggering wasn't necessary in your snippet. It's just that `$(o).trigger('/done');` returns `$(o)` so that chaining is possible; you could have just written `$(o)` and it would return the same thing.

**Comment by dmethvin** [comment]
The jQuery event system is really optimized and intended for handing DOM event behavior. If you want something like pub/sub or reactive programming there are other JavaScript libraries that you can use to do that.
