### ISSUE TITLE
dataFilter should be invoked before error callback

### ISSUE THREAD

**Issue by onury** [jquery/jquery#2447]
`$.ajax` method's are invoked in this order:   

1. `beforeSend`
2. `error`
3. `dataFilter` **
4. `success`
5. _Promise callbacks_
6. `complete`

** `dataFilter` is invoked after `error` callback. 

To prevent JSON vulnerabilities, we return prefixed JSON for both error and success responses. But since the `dataFilter` is not invoked before `error`, we end up with `responseText` property only; and no `responseJSON` property that contains the parsed response object. For example:

```js
")]}',\n{\"error\":{\"message\":\"Invalid parameter\"}}" // ajaxError.responseText
```

`dataFilter` should be invoked before the `error` callback, so we can strip out the prefix and response is correctly parsed.

This is the case for the current versions: 1.11.3 and 2.1.4

**Comment by dmethvin** [comment]
This would be a significant change in behavior, wouldn't it? The `dataFilter` would not know whether the data was valid or not. If you need to massage the response for validity it would seem safest to not use jQuery's bult-in data conversion and instead do it yourself..

**Comment by dmethvin** [comment]
I don't think we can rearrange the documented callback order that we've been using for years. My recommendation would be to explicitly set `dataType: "text"` and process it yourself so that none of the vagaries of automatic conversions can affect you.
