### ISSUE TITLE
Code climate

### ISSUE THREAD

**Issue by maxnordlund** [jquery/jquery#2448]
I couldn't find any issues about this, but I was wondering if you could setup/integrate [codeclimate][1] to help with code review.

[1]: https://codeclimate.com/github/jquery/jquery

**Comment by FagnerMartinsBrack** [comment]
https://github.com/jquery/jquery/pull/1415#issuecomment-28456600

**Comment by markelog** [comment]
Since this was discussed previously, i'm gonna close it. Thank you though! 

@FagnerMartinsBrack
thanks for comment, it was very helpful.

**Comment by maxnordlund** [comment]
OK, I think I understand now. Thanks for your time.
