### ISSUE TITLE
Feature request: .parent(n)

### ISSUE THREAD

**Issue by adjohnson916** [jquery/jquery#2449]
It would be nice if the `.parent` and `.parents` function accepted an optional numeric parameter indicating how many levels up to go, or to start, respectively. The 2nd argument could then be the existing optional selector to further filter results. If the first argument is non-numeric, then original behavior would remain.

`.parent(2)` would get the great-grandparent (0 = parent, 1 = grandparent, 2 = great-grandparent) of an element.
`.parent(1, 'div')` would get the second parent (grandparent) of an element, but only if it matches the selector `'div'`.

`.parents(1)` would get all ancestors above/except the first/immediate parent.
`.parents(1, 'div')` would get the same except filtered by the selector.

https://api.jquery.com/parent/
https://api.jquery.com/parents/

If maintainers are open to this, I might submit a PR.

**Comment by FagnerMartinsBrack** [comment]
Wouldn't the code below do the same and be more readable without using unnamed arguments?

```javascript
element.parents( "div" )[ 0 ];
element.parents( "div" )[ 1 ];
```

**Comment by adjohnson916** [comment]
@FagnerMartinsBrack In some cases, I think you're right, it may be possible to accomplish the same thing using array operations. But still see the use of this.

What about when the jQuery set contains multiple elements to begin with? Then by `.parent(1)` I want to get a list of all the grandparents of the elements in the set, if they have any (i.e. are not `html`). But with `.parents()[1]`, I would only get the grandparent of the first element, if it has one, or worse, if any elements in the set prior did not have such an ancestor (we hit the top of the DOM tree), and so results were excluded at that index, then I might instead be getting the grandparent of a previous or subsequent element in the original set, or even `undefined` if we're at the end of the array.

A way to implement `.parent(1)` currently might be, e.g.:
```js
$('html,body>*:eq(0)').map(function(i,e){
  return $(e).parents()[1];
});
```
Which should return only a single `<html>` element, matching the second item, and nothing for the first.

Also, you might assume the `.parents(1)` case could be implemented as `.parents().slice(1)`, but again, this would not behave correctly if the original set had multiple elements, as the parents for each element are concatenated in the resulting array, so the results would include all parents for all but the first element, only correctly excluding the first/immediate parent of the first element.

I think perhaps `.parents(1)` could be implemented as e.g.:
```js
$('a').map(function(i,e){
  return $(e).parents()[1];
}).parents()
```

Which makes me think, perhaps if `.parent(n)` is implemented, then `.parent(n).parents()` would be sufficient in place of implementing `.parents(n)`.

**Comment by mzgol** [comment]
This is very similar to a [boolean trap](http://ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html), i.e. the parameter doesn't really say that it affects the depth of the searching process. I don't think it's a good idea with this name.

In most cases if you want to limit the searched nodes you just look for the first one in which case [closest()](http://api.jquery.com/closest/) is enough. If you have a really sophisticated use case, it's IMO best to achieve it via a plugin. A new name for such a function would be better anyway.

**Comment by adjohnson916** [comment]
@mzgol Thanks. I agree, a custom plugin would be able to provide this. The community may or may not find it useful as a supported feature by default. I've created a repo [adjohnson916/jquery-ancestors](https://github.com/adjohnson916/jquery-ancestors) where I may develop something like this.

For the record, it wouldn't have to be boolean trap-esque. It seems the jQuery API tends toward [method overloading](https://en.wikipedia.org/wiki/Function_overloading)<sup>[1](http://ejohn.org/blog/javascript-method-overloading/)</sup> and terse [fluent interfaces](https://en.wikipedia.org/wiki/Fluent_interface#), rather than, for example, passing options objects around, but the latter is always possible, if we can rely on type detection, e.g.:
```js
$('*').parent({up: 2});
$('*').parent('div', {up: 2});
$('*').parent({up: 2, selector: 'div'});
```

Feel free to close if you want.

**Comment by markelog** [comment]
As you can imagine, we are very conservative about new APIs, we usually ask for a plugin first.
Nevertheless thank you for reaching out @adjohnson916!
