### ISSUE TITLE
jQuery 1.x breaks Sinon.JS XHR mock

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#2453]
The following snippet passes with jQuery 2.x but is broken in jQuery 1.11.3 (using the same browser, latest Chrome).
```js

QUnit.test( 'request', function (assert) {
    this.server.respondImmediately = true;
    var i = 1;
    this.server.respondWith( /mode=api/, function ( request ) {
        request.respond(
            200,
            { 'Content-Type': 'application/json' },
            '{ "value": "' + (i++) + '" }'
        );
    } );
    
    $.ajax('/foo&mode=api')
        .then(function (data) {
            assert.equal(data.value, '1', 'response'); 
            return $.ajax('/bar&mode=api');
        } )
        .then(function (data) {
            assert.equal(data.value, '2', 'response'); 
            return $.ajax('/quux&mode=api');
        } )
        .then(function (data) {
            assert.equal(data.value, '3', 'response'); 
        } );
} );  
```

JSFiddle (jQuery 2.x): http://jsfiddle.net/zc7drrcb/
JSFiddle (jQuery 1.11.3): http://jsfiddle.net/en8pu6br/

When using jQuery 1.11, it is somehow unable to make the subsequent requests before the end of the test.

**Comment by dmethvin** [comment]
This doesn't seem to be a regression, it breaks with 1.9.1 as well. I haven't looked into the Sinon code but the 1.x branch uses polling on a timer rather than events to implement `$.ajax()` so that might be a factor.

**Comment by Krinkle** [comment]
Ah, that might be it. Sinon's XHR mock essentially mocks `xhr.send()` and then immediately provides a response.

Presumably jQuery isn't seeing that response until the first poll comes back?

**Comment by Krinkle** [comment]
So the problem is indeed in that area.

* jQuery sets `xhr.onreadystatechange` after calling xhr.send(). This means jQuery isn't listening when FakeXHR emits `readyStateChange(DONE=4)`.
* jQuery has a synchronous check for `xhr.readyState === 4` after calling `xhr.send()` to account for cases where a cached response is immediately returned. However it then proceeds to defer the callback using `setTimeout( callback );` instead of calling it immediately.

Changing the following line in a patched version of jquery-1.11.3.js made it work:
```diff

					} else if ( xhr.readyState === 4 ) {
-						setTimeout( callback );
+						callback();
					}
```

For now I'll try to work around it by setting up a fake timer in addition to the fake server. And perform a tick() before the end of each test.

**Comment by dmethvin** [comment]
I'm not sure how that change would affect our guarantees on `async: false`, although the request should still be completed when execution falls through the `$.ajax()` so anyone making that assumption should be good.

Your test seems broken because it's using `.then()` but not doing an async test?

**Comment by Krinkle** [comment]
I forgot about the new `.then()` being always async, I see how that makes my example confusing (even though this is about jQuery 1.x). The original code where I ran into this issue used `.done()`, though.

Regardless, I suppose it's appropriate to attach `assert.async()` to the end of the chain (or return the promise to QUnit.test) – which should solve this naturally.

**Comment by dmethvin** [comment]
The new jquery-compat Deferred will have a Promise/A-complant `.then` as well, so you would definitely want to assume it's async for reliable operation across versions.

I hear what you're saying about making the tests slower, but the world has spoken that the consistency of async triumphs and we must obey. :smiling_imp:

**Comment by heldinz** [comment]
I have a similar but different issue (described in cjohansen/Sinon.JS#792) where tests using Sinon's FakeXMLHttpRequest work with jQuery 2.x but break with 1.x. In essence, jQuery 2.x returns `new XMLHttpRequest()` which Sinon is mocking, but jQuery 1.x explicitly returns `new window.XMLHttpRequest()`, bypassing the mocking.

Is there a specific reason why `window` is necessary in the 1.x branch? If it can be removed, it would really help with testing via Sinon. If not, I have described my workaround in the linked issue.

**Comment by mzgol** [comment]
> Is there a specific reason why window is necessary in the 1.x branch? If it can be removed,

On the contrary - it's now included in jQuery 3.0 (a continuation of the 2.x line) as we support running jQuery in non-browser environments passing custom `window` implementation to the jQuery factory; we even have [tests for it](https://github.com/jquery/jquery/blob/2792845534e36c39dbb9c8369ed96aaefa560081/test/node_smoke_tests/document_passed.js#L10). Both branches use `window.XMLHttpRequest` now, we only assume JavaScript globals, not browser ones.

It surprises me, though, that it's a problem as we e.g. use `window.setTimeout` now (another change compared to jQuery 2.1.4), we [run effects tests with a Sinon mock](https://github.com/jquery/jquery/blob/2792845534e36c39dbb9c8369ed96aaefa560081/test/unit/effects.js#L11-L27) and it works just fine.

**Comment by dmethvin** [comment]
If the problem is that `window.XMLHTTPRequest` isn't being mocked, can you set it yourself to Sinon's stub? If that's the only issue it should fix the problem.

**Comment by dmethvin** [comment]
I don't think there are any issues left to resolve here? I'll close, but we can reopen if needed or open a more focused issue.
