### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'scrollTop' in undefined

### ISSUE THREAD

**Issue by Dreampie** [jquery/jquery#2456]
```coffeescript
$ ->
#scrollup
  $("#back-top").click ->
    $(window).animate scrollTop: '60px', 400, 'linear'

  $(window).scroll ->
    if $(window).scrollTop() > 200
      $('#back-top').fadeIn 200
    else
      $('#back-top').fadeOut 200
```

**Comment by mzgol** [comment]
Could you create a complete test case on http://jsbin.com or http://jsfiddle.net?

**Comment by Dreampie** [comment]
https://github.com/Dreampie/vue-demo source in here

**Comment by Dreampie** [comment]
i'm sorry ,i fix it   $('html,body').animate...

**Comment by mzgol** [comment]
There is a lot of code in there with hardly any instructions on how to run or reproduce the problem.

Could you create a minimal example on http://jsbin.com or http://jsfiddle.net? It's hard to debug a complete app.

**Comment by Dreampie** [comment]
thank you，i fixed it

**Comment by mzgol** [comment]
OK, I assume you mean a mistake was on your side. I'm closing the issue.
