### ISSUE TITLE
Load jQuery only if not present

### ISSUE THREAD

**Issue by KapusiCsilla** [jquery/jquery#2459]
I want to include the jquery in file, only if not included already in the page. For now, I inserted this if statement to the beginning of my minified jQuery file:

*if (window.jQuery === undefined)*

It would be nice, that jQuery would be able to detect if it's already defined and in that case wouldn't load again. With a warning or error on javascript console could indicate, if the loaded version is different.

(Sorry for my bad English)

**Comment by scottgonzalez** [comment]
Many sites load multiple versions of jQuery; see [`jQuery.noConflict()`](http://api.jquery.com/jQuery.noConflict/) for the supporting API, so that's not an option.

You should really manage your includes better to avoid this problem, or continue to just work around it yourself.
