### ISSUE TITLE
Tested latest development jQuery, breaks a plugin

### ISSUE THREAD

**Issue by energyuser** [jquery/jquery#2460]
So I tested the latest development version of jQuery (this one: https://code.jquery.com/jquery-git.js). So it appears that this breaks the following plugin: https://github.com/cameronmcefee/plax
This is just a bug report so that you guys can look into the error Firefox threw at me:
`TypeError: elem.getClientRects is not a function --File and Line/Column--  jquery.js:9372:8`
Still, is that a bug in jQuery or is it with the plugin? It works with http://code.jquery.com/jquery-2.1.4.min.js so this leads me to believe you broke something in the late revisions.

**Comment by timmywil** [comment]
Thanks for opening an issue. Please provide a small but complete test case from http://jsbin.com to help us asses the issue. Firefox supports `getClientRects` on elements, so my guess is there's some invalid input here.

**Comment by dmethvin** [comment]
If it helps to create your test case, that error is being thrown from `.offset()`. Mostly likely some element in the jQuery collection is either not a DOM element (e.g. a `window` or `document`) or not currently connected to the document. These have always been invalid inputs but just didn't throw errors in the past.

**Comment by energyuser** [comment]
@timmywil that is an example of how I use the plugin: http://codepen.io/anon/pen/MwGgxy this works because it uses jQuery 2.1.4
Want an example that uses the dev version? I tested in latest FF IE and Chrome and no luck so far...

**Comment by dmethvin** [comment]
In Chrome I get this:
`Refused to execute script from 'https://raw.githubusercontent.com/cameronmcefee/plax/master/js/plax.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

**Comment by energyuser** [comment]
That must be because I've linked the file from the git hub repo, can anyone host it on a server with the correct MIME type?

**Comment by mzgol** [comment]
You can just use rawgithub.com

-- 
Michał Gołębiowski

**Comment by energyuser** [comment]
@mzgol Thanks didn't know that, updated the pen
guys any progress so far?

**Comment by dmethvin** [comment]
My guess above was right, the plugin is asking for `$(window).offset()` which makes no sense. It should use `{ left: 0, top: 0 }` if there is no element.

**Comment by energyuser** [comment]
So I should change a code portion in the plugin? So that it works?

**Comment by dmethvin** [comment]
If the author isn't developing the plugin anymore, I'd recommend finding an actively developed one. I'm glad you pointed out this problem though, it's nice that people are trying the bleeding-edge builds with their code. That's how we can find out what we break!

**Comment by ned2** [comment]
Also worth noting that this issue of passing a Window to `offset` currently breaks some Jquery-UI code, but has been fixed in the master branch: b3a9b13a218cd90b7cf67be5d5f8ad6e76c557b0
