### ISSUE TITLE
ajax.error not fire when 404 since 1.10

### ISSUE THREAD

**Issue by arliweng** [jquery/jquery#2461]
the ajax.error event never fire when script content inside html parse by $().appendTo but that script file not exist(so 404 not found)
but fire @ version 1.9.1, look like bug @ line 9264:
response = ajaxConvert( s, response, jqXHR, isSuccess );
before if (isSuccess) check, 
example see https://jsfiddle.net/fedrteg3/

**Comment by dmethvin** [comment]
I think this is a dup of #2143 which we plan to fix before 3.0 final.

**Comment by dmethvin** [comment]
Closed as a dup of #2413
