### ISSUE TITLE
inconsistent casting w/ $.data()  ?

### ISSUE THREAD

**Issue by pointpointclick** [jquery/jquery#2462]
Given
```
<div data-thing="289658581140374016"></div>
<div data-thing="289658581140374100"></div>
```
and 
```
var things = $('div');
```
`typeof(things.eq(0).data('thing'))` returns string (as expected)
`typeof(things.eq(1).data('thing'))` returns number (wat?)

Does this seem off to anybody else? Seems to be values that values end in "00"?

Fiddle here: http://jsfiddle.net/eh1xxeu1/

**Comment by scottgonzalez** [comment]
From [the documentation](http://api.jquery.com/data/):

> Every attempt is made to convert the string to a JavaScript value (this includes booleans, numbers, objects, arrays, and null). A value is only converted to a number if doing so doesn't change the value's representation. For example, "1E02" and "100.000" are equivalent as numbers (numeric value 100) but converting them would alter their representation so they are left as strings. The string value "100" is converted to the number 100.

The first cannot be precisely converted, the second can.
