### ISSUE TITLE
jQuery not added to window when required using browserify

### ISSUE THREAD

**Issue by gonsfx** [jquery/jquery#2463]
When installing jquery via `npm` and requiring it with browserify, the `intro.js` sets `noGlobal` flag to true resulting in jQuery not automatically being added as a property to the window object.

A common way of loading jquery plugins that are not available as commonjs modules into a browserify stack is to shim them using `browserify-shim` and a configuration in the `package.json`, where jquery can be added as a dependency so whenever the plugin is required, jquery is required aswell:

```json
"browserify-shim": {
  "owl.carousel": {
    "exports": "$.fn.owlCarousel",
    "depends": [ "jquery" ]
  }
}
```

Most plugins will fail when required nevertheless, because they require `$` or `jQuery` properties on the window object which do not exist because `noGlobal` is set.

Whats the usecase of _not_ adding `$` and `jQuery` properties to the window object?
How can i solve this problem?

**Comment by dmethvin** [comment]
Isn't this a browserify-shim issue and not a jQuery one? [Have you set the config to define $ as a global?](https://github.com/thlorenz/browserify-shim/tree/master/examples/expose-jquery)

**Comment by timmywil** [comment]
Thank you for opening an issue, but I agree. This is a browserify config issue. We've had more requests to leave it off the global than to put it on.
