### ISSUE TITLE
Off method does not remove all handlers that where registered with a on method with multiple events

### ISSUE THREAD

**Issue by pabloaguayo** [jquery/jquery#2469]
If I use the on method with multiple events and a unique namespace, for example `.on("click.namespace, mouseenter.namespace")`,  when I use the off of that namespace, `.off(".namespace")`, it only removes the last event I setted up.

Example is here: http://jsfiddle.net/zaf3345x/

**Comment by dmethvin** [comment]
You put a comma there so your namespace is `.scope,` which doesn't match the `.scope` namespace.
