### ISSUE TITLE
Be honest this time.

### ISSUE THREAD

**Issue by dommmbie** [jquery/jquery#2475]
Thanks for your answer scott. Be honest this time. I really start to believe the blowjob option.

How many money/blowjobs did you get? Wasn't open source about being open? 

But if there's money involved you are doing secret. :-1: 

and stop talking about me on IRC I just wanted to have a serious conversation?

**Comment by mdevils** [comment]
@dommmbie stop trolling please

**Comment by timmywil** [comment]
If you wanted to have a serious conversation, you definitely went about it the wrong way.
