### ISSUE TITLE
catch property needs to be quoted in Android 2.3

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2478]
Apparently Android 2.3 doesn't like a `catch` property and so it fails deferred tests completely since 84ccf2606c6b97d5875774bf774f9f2aae950ae7. We need to quote it as on the `compat` branch.

Do we have any way to ensure we don't change it back without turning on the JSHint `es3` option? :/ Or maybe via JSCS? cc @rwaldron @markelog.

**Comment by mzgol** [comment]
Or maybe we should just turn on the `es3` option, preferably with a comment that Android 2.3 needs it.

**Comment by markelog** [comment]
Probably easier to left a comment in the source code? As inline rule or just as a warning?

**Comment by mzgol** [comment]
I'm concerned that since Android 2.3 chokes on it, there may be other
reserved words that don't work as property names. It would be safer to
switch es3 on (with a support comment that it's just for Android 2.3) and
be sure everything is quoted.

**Comment by markelog** [comment]
>  there may be other reserved words that don't work as property names

Is there? Every reserved word should trigger such error, if that the case, then we should enable es3.

**Comment by mzgol** [comment]
> Every reserved word should trigger such error

I didn't check all but at least `catch`, `class` & `else` trigger this error. They all work on Android 4.0.

**Comment by mzgol** [comment]
PR: #2481.
