### ISSUE TITLE
Drop iOS 6 & Safari 6 support

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2482]
According to the official Apple Dashboard:
https://developer.apple.com/support/app-store/
currently all iOS versions older than 7 (i.e. not just 6 but all of them) are at 2% or iOS market share (not mobile market share).

Besides, desktop Safari 6 is not possible to install in El Captain, Yosemite & Mavericks i.e. all OS X versions that will receive security fixes once El Captain is released this fall (if Apple continues its current strategy). Note that Mountain Lion can have Safari 6.1 installed which include the engine shared with Safari 7 - it appears in Mac App Store, alongside other system updates.

I don't think it's worth supporting such a browser. We'll already soon test on Safari 7, 8 & 9, that's three versions.

cc @arschmitz as we're talking about mobile browsers as well.

**Comment by arschmitz** [comment]
@mzgol I'm ok with this based on your numbers. I will check with the rest of the team at the meeting this week though.

**Comment by mzgol** [comment]
Sure, nothing urgent here. :) There weren't any significant issues with Safari 6 so this is mostly about reducing our test burden than anything else. If there is any reason to leave it for now, this will not bother me too much.

**Comment by mzgol** [comment]
Also, cc @scottgonzalez as this will affect jQuery UI support matrix as well.

**Comment by scottgonzalez** [comment]
I'm good with this.

**Comment by mzgol** [comment]
I removed these browsers from jQuery Core & UI TestSwarm and landed an update on the jquery.com's [jquery-3 branch](https://github.com/jquery/jquery.com/tree/jquery-3). I'm closing this issue as resolved.
