### ISSUE TITLE
Reduce Android 2.3 support on master (was: Investigate Android 2.3 support)

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2483]
### We're already not fully supporting Android 2.3

The hard truth is we've never fully supported Android 2.3. First of all, our unit tests don't pass there in a couple of modules: http://swarm.jquery.org/job/942. There are serious AJAX issues with error handling: #1786, #2458 (#2458 seems pretty serious, see https://github.com/jquery/jquery/pull/2458#issuecomment-119572119), there are manipulation issues with checked radios: #1785.

Even though most of the tests pass, we cheat a little by putting Android 2.3 in special paths in some of them:

1. https://github.com/jquery/jquery/blob/1c59b308d201d6dd0f0aed2ad0256d01b9f68047/test/unit/ajax.js#L1507-L1512
2. https://github.com/jquery/jquery/blob/1c59b308d201d6dd0f0aed2ad0256d01b9f68047/test/unit/event.js#L408-L413
3. https://github.com/jquery/jquery/blob/1c59b308d201d6dd0f0aed2ad0256d01b9f68047/test/unit/manipulation.js#L419-L426 & https://github.com/jquery/jquery/blob/1c59b308d201d6dd0f0aed2ad0256d01b9f68047/test/unit/manipulation.js#L440-L444
4. https://github.com/jquery/jquery/blob/1c59b308d201d6dd0f0aed2ad0256d01b9f68047/test/unit/support.js#L236-L254

### Maintenance cost

There are various problems that happen only on Android 2.3, e.g. now it turns out it doesn't allow unquoted reserved words as property names, exactly as our favorite IE8: #2478. It happens quite often that something just doesn't work, e.g. currently for some reason AJAX tests hang very near the beginning: http://swarm.jquery.org/result/479018. Surprisingly, it works on `compat`: http://swarm.jquery.org/result/479031. Lots of hours are being constantly put into making this browser work with our tests.

### Market share

When we released the last stable version of jQuery, 2.1 (I'm omitting patches) [a year and a half ago](http://blog.jquery.com/2014/01/24/jquery-1-11-and-2-1-released/), Android 2.3 still had a very large market share. Currently [Google stats](http://developer.android.com/about/dashboards/index.html) show it at 5.6% of all Android versions (this is not a mobile market share but Android market share). Real percentage might be a little higher as it's counted via Google Play Store but it's still not that large as it was back then.

### Size

Cutting Android 2.3 support ([see an experimental branch that does it](https://github.com/mzgol/jquery/tree/no-android2.3)) saves 186 bytes gzipped, most of which are the `reliableMarginRight` support test and a workaround. Making all tests pass would add more.

### Resolution?

There are a couple ways to solve the problem:

1. Don't change anything, try to make Android 2.3 finally pass & continue to suffer.
2. Drop support from `master` but keep it on `compat`; still suffer, although a little less (for some reason Android 2.3 problems happen more often on `master` than `compat`).
3. Support Android 2.3 only partially - ensure it parses jQuery correctly, run a few basic tests ensuring most important APIs work on most common inputs. Don't care for perfect compliance: less suffering but such smoke testing may not be effective; also, it's hard to draw the line what's important and what's not.
4. Drop support from both branches, redirect people still needing support to the 1.x & 2.x jQuery lines.

cc @jquery/core @scottgonzalez @arschmitz

**Comment by gnarf** [comment]
Just FYI - You can still walk into a store and buy a device with Android 2.3 on it.

**Comment by mzgol** [comment]
> Just FYI - You can still walk into a store and buy a device with Android 2.3 on it.

:(

**Comment by markelog** [comment]
Relevant - https://github.com/jquery/jquery/issues/2050

**Comment by mzgol** [comment]
Hah, I thought you created this issue way more in the past. I guess time with Android 2.3 flies slower...

**Comment by mzgol** [comment]
It seems to drop pretty quickly, though - it was 8% in February, now it's 5.6%.

**Comment by arschmitz** [comment]
Echoing @gnarf, despite very low usage numbers I feel like its hard to justify officially dropping support for something you can still buy new of the shelf. This is direct from Best Buy off their website who are the largest consumer electronics retailer in the US.
http://www.bestbuy.com/site/samsung-galaxy-note-4g-cell-phone-unlocked-blue/1883006.p?id=1219065988576&skuId=1883006

**Comment by mzgol** [comment]
As I wrote in the initial post, though, we've never fully supported this browser, we've always had lots of failures, for most of the life of jQuery we didn't even test on any Android in the CI. And while there are numerous Android 2.3-related issues that pop up from time to time, I don't remember *a single issue* reported from anyone outside of the jQuery team; it was mostly reacting to various problems that pop up in testing (some of which were waiting unresolved for a long time).

That's also why I wonder - if no one reports Android 2.3 issues then maybe we're fixing too much, writing workarounds for issues no one cares about and no one notices?

**Comment by mzgol** [comment]
@arschmitz @gnarf I'd like to discuss it at the next Core meeting, could you all be there? There are other options between dropping support and supporting fully, I'd love your input during the discussion.

@timmywil Just to make sure - you don't plan to skip the meeting next week, do you?

**Comment by arschmitz** [comment]
@mzgol i'm generally always there lurking, and will make sure I am at next one. Just caught me in the middle of setting up a new laptop this week.

**Comment by gnarf** [comment]
I'll be on an airplane but I trust @arschmitz to carry my viewpoint there.
No need to wait for me, as long as we are making responsible informed
choices, I'm game!
😉

**Comment by timmywil** [comment]
@mzgol yes, I plan on having the meeting. The only thing that I can foresee changing that would be the fact that I'm moving this weekend, but I don't plan on letting that interfere.

**Comment by mzgol** [comment]
Further thoughts - I think at least moving support to `compat`-only makes sense. Some bugs that appear were caused by the fact that many ES3-like workarounds are already on `compat` due to IE8 support, on `master` we discover them usually only when I look at one of recent Android 2.3 failures and discover that more things failed than usual (which is often not obvious). `compat`-only Android 2.3 support would be a little easier. Also, size difference between `2.1` & `1.11` is 50% larger than between current `master` & `compat` due to IE6-7 support removal, currently it's only 2KB gzipped: `master` weighs 29.4KB, `compat` - 32.2KB.

That's one thing; another is that I think we should restrict our Android 2.3 support slightly by saying that we won't fix non-critical bugs like sth being off-by one (a strategy we once applied e.g. to IE6 support). Note that some of the tests that currently fail on Android 2.3 look like significant breakages in some situations (like appended checked radios losing their state) and yet no one reports such things to us. I wonder if anyone noticed if we stopped working around unreliable margin right in Android 2.3.

Due to the fact that those devices are still on sale (which is so sad), I'd be ok with keeping `compat` work on Android 2.3 on a basic level - to at least ensure the library parses correctly and core APIs work, at least outside of various edge cases.

I'd like to note that Android 2.3 is broken on so many levels, many of which we cannot fix reliably that if a developer doesn't test their site on this browser, jQuery supporting it won't help; it will be broken anyway. It's easier with Android 4.0 or newer.

**Comment by arschmitz** [comment]
@mzgol based on previous discussions I don't think compat is a good option for 2.3 see https://github.com/jquery/jquery/issues/2050#issuecomment-72370916

**Comment by mzgol** [comment]
Hmm, right, I forgot about this use case.

**Comment by markelog** [comment]
> Echoing @gnarf, despite very low usage numbers I feel like its hard to justify officially dropping support for something you can still buy new of the shelf.

Well, you could still install IE 5.5, it doesn't necessary mean somebody do that. We should note that these 5.6% stats do not show browser market is it about os market meaning if ppl actually buying them, it doesn't mean they use default browser, in fact, it looks like this is primary clientele of opera mini. So we looking not at the 5.6% but on much lower percentage.

Plus, market share of 2.3 dropped by 2% in four months, we can extrapolated that data and if we assume same tendency, than in another four months share should 3% or lower, which is by any standart is pretty big argument for removal. 

And if you consider that this is only android, if you add to these numbers ios and ms browsers, it would be tiny, if you add desktop browsers to it, 2.3 share would practically be non-existent.

@mzgol and some other ppl from core spend a lot (lots) of time working on supporting that browser, whereas we're still nowhere near of green trunk with it, meanwhile users do not field bugs for it, not ever. 

Giving all above, even smoke testing seems really not necessary to me.

**Comment by mzgol** [comment]
I'm also concerned about cases where not regressing on Android 2.3 would mean worse experience for others. Fully supporting this browser could e.g. mean we'd have to revert #1449 which would be pretty sad and would cause other issues.

**Comment by timmywil** [comment]
After discussing this issue in the dev leads meeting, we realized something. Does anyone know of any issues with jQuery compat in hybrid apps? We've always recommended master because master didn't have the oldIE detritus, but I'm not sure we've ever actually checked to see if compat works. If it does, I think we can make Android 2.3 compat-only and recommend compat for anyone supporting 2.3 in hybrid apps.

**Comment by mzgol** [comment]
> Does anyone know of any issues with jQuery compat in hybrid apps?

There are a couple of issues:

1. We know that Windows Modern apps are more restrictive than general web content, compare e.g. [`master`'s manipulation/support.js](https://github.com/jquery/jquery/blob/d24275372624bac897c4131fd1507a58c09a1483/src/manipulation/support.js#L11-L17) with [`compat`'s](https://github.com/jquery/jquery/blob/9c373c31410deb8e4a11aa7ce226d5e9169c7852/src/manipulation/support.js#L30-L32).
2. [`master`'s JSHint settings](https://github.com/jquery/jquery/blob/d24275372624bac897c4131fd1507a58c09a1483/src/.jshintrc#L18) declare a `window` global but doesn't declare the browser environment which [we do on `compat`](https://github.com/jquery/jquery/blob/9c373c31410deb8e4a11aa7ce226d5e9169c7852/src/.jshintrc#L16).
3. We don't test anything in `compat` on Node.js, on `master` we have [basic compliance tests](https://github.com/jquery/jquery/tree/master/test/node_smoke_tests).
4. There's a possibility that some of the code tailored at IE8 will cause issues, unfortunately we don't have a good way to test it apart from waiting for bug reports. Some of IE8 support tests may require changes similar to ones I described in point 1.

Obviously, we can change all that, especially points 1-3 should not be that difficult; such a change would also fix #2133. I'd be up to making these changes if that meant we could drop Android 2.3 on `master`. :D But if we say Android 2.3 support is `compat`-only, I'd like to not do even basic smoke testing of Android 2.3 on `master`.

**Comment by gibson042** [comment]
I'd like to hold on to the Android 2.3 smoke testing in `master` so we can assert degraded support—as noted, it mostly just works and most of its specific bugs are edge cases found by us.

**Comment by arschmitz** [comment]
@gibson042 :+1:

**Comment by mzgol** [comment]
@gibson042 What do you mean by smoke testing, though? Keeping all existing tests except maybe the ones that are currently failing or just a small set of tests checking basic API behavior?

If this would mean keeping existing tests then I don't think making Android 2.3 support officially `compat`-only would buy us that much.

**Comment by gibson042** [comment]
Something like [ensure_iterability_es6.js](https://github.com/jquery/jquery/blob/master/test/node_smoke_tests/lib/ensure_iterability_es6.js)—load the library and use it for a handful of simple operations backed by required modules, explicitly avoiding edge cases. Support would be allowed to degrade, just not to the point where core functionality fails.

**Comment by mzgol** [comment]
I don't think that would buy people that much, I'd guess most of the code on the web relies on at least a couple of edge cases of the API. I wouldn't oppose it too much, though, maintaining that shouldn't be a lot of trouble except the time needed for choosing proper tests initially.

**Comment by gibson042** [comment]
Right, I'm acting on the assumption that websites will want to serve compat but native applications—or perhaps especially well-tested sites—may try master and report issues to us (a welcome change from adding code just to try fixing our unit tests).

**Comment by arschmitz** [comment]
The mobile team discussed and voted on this today and decided that in the upcoming 1.5 release we will only passively be supporting android < 4 meaning we will not remove any fixes in this version but will only be ensuring basic functionality.

**Comment by dmethvin** [comment]
Dropping Android 2.3 support won't help much unless we can also drop our super unofficial secret support for PhantomJS 1.x, since they share the same dumb limits. Can we do that yet?

Some sort of weakened Android 2.3 support as @gibson042 suggests might work, we'd just document the places where we punted because it was too hard or involved degrading support of newer and more popular browsers.

**Comment by mzgol** [comment]
@dmethvin
> Dropping Android 2.3 support won't help much unless we can also drop our super unofficial secret support for PhantomJS 1.x, since they share the same dumb limits.

IMO for PhantomJS 1 we mostly need workarounds for `push.apply(_, arraylike)` throwing but we need that for Android 4.0 as well anyway (it's fixed in Android > 4.0). So this needs to stay for now.

Apart from that, I don't see a lot of overlap.

> Can we do that yet?

We can't drop PhantomJS 1 yet because Mobile still relies on it; probably mostly because of https://github.com/ariya/phantomjs/issues/12948 which makes most wrapper tools still install v1.

As for Android 2.3 support itself, please see my initial post - it's not only about code size increase (although it'd be nice to rip out this ~160 bytes `reliableMarginRight` [test](https://github.com/jquery/jquery/blob/d24275372624bac897c4131fd1507a58c09a1483/src/css/support.js#L73-L99) and [workaround](https://github.com/jquery/jquery/blob/d24275372624bac897c4131fd1507a58c09a1483/src/css.js#L344-L351)) but mostly about:

1. Maintenance cost (which you might not notice because I'm usually the one to fight this stupid browser :P).
2. The fact that we've never passed the whole test suite and we do various workarounds **in tests** so that this browser more or less behaves, it's just so broken. We don't have those issues with Android 4.0+, they require some workarounds but only in source, they're able to pass the test suite which we're unable to make Android 2.3 do.

Also, fully supporting this browser could mean reverting useful changes like #1449.

**Comment by mzgol** [comment]
It was decided that:

1. We're adding support for non-browser environments to jQuery Compat: issue #2501, PR #2504.
2. We're cantfixing #1786 on both branches.
3. We'll try to fix #1785 on `compat` only.
4. We'll maintain only basic support for Android 2.3 on `master`, meaning special tests just for this browser that don't check edge cases.
5. We're removing the `reliableMarginRight` support test & workaround from `master`.

**Comment by mzgol** [comment]
BTW, [Android 2.3 market share](http://developer.android.com/about/dashboards/index.html) is down from 5.6% last month when I created this issue to 4.6%. It's going down at extreme speed, in half a year it will be almost non-existent if this trend continues.

**Comment by markelog** [comment]
Thats what i said! :-)

> Plus, market share of 2.3 dropped by 2% in four months, we can extrapolated that data and if we assume same tendency, than in another four months share should go down to 3% or lower, which is by any standart is pretty big argument for removal.

**Comment by ximex** [comment]
> Well, you could still install IE 5.5, it doesn't necessary mean somebody do that. We should note that these 5.6% stats do not show browser market, is it all about os market, meaning if ppl actually buying them, it doesn't mean they use default browser, in fact, it looks like this is primary clientele of opera mini. So we looking not at the 5.6% but on much lower percentage.

> Plus, market share of 2.3 dropped by 2% in four months, we can extrapolated that data and if we assume same tendency, than in another four months share should go down to 3% or lower, which is by any standart is pretty big argument for removal.

> And if you consider that this is only android, if you add to these numbers ios and ms browsers, it would be tiny (like really tiny), if you add desktop browsers to it, 2.3 share would practically be non-existent.

> BTW, Android 2.3 market share is down from 5.6% last month when I created this issue to 4.6%. It's going down at extreme speed, in half a year it will be almost non-existent if this trend continues.

because of that i think we should do one of these two thing:

> - Drop support from master but keep it on compat; still suffer, although a little less (for some reason Android 2.3 problems happen more often on master than compat).
> - Drop support from both branches, redirect people still needing support to the 1.x & 2.x jQuery lines.

i prefered the second one. all of them they still need Android 2.3 should remain on 1.x or 2.x. Let's push the web forward with a slim and easy lib.

**Comment by mzgol** [comment]
BTW, this is how an average Android 2.3 run looks like (before manually restarting jobs that timed out):
![screen shot 2015-08-18 at 13 14 28](https://cloud.githubusercontent.com/assets/1758366/9328703/4270d87e-45ab-11e5-9463-3f215fa6193c.png)
It's hard to not miss critical bugs when you're used to the fact half of the tests time out by default.

**Comment by mzgol** [comment]
Almost all is done; the latest part is in PR #2581.

**Comment by mzgol** [comment]
Everything planned has been done.
