### ISSUE TITLE
Incorrect the 'slideDown' method behavior with element with height 0

### ISSUE THREAD

**Issue by bset** [jquery/jquery#2488]
Here is an example of this issue. Steps to reproduce it:
1. Open example using link: http://jsfiddle.net/j53j1mLq/
2. Click on the 'Toggle' button (maybe several times)
3. As you can see, element with height 0 become visible for a short time and it's hidden after that
I'm waiting for no reaction method call because of element height.

Description: on every button click the 'slideDown' and the 'slideUp' methods are called for the 'box' element in rotation.

**Comment by gibson042** [comment]
This stems from a [rather curious height/width exception](https://github.com/jquery/jquery/blob/b3b2d6c3dd51fbdc69e1942e9af75cc99a1834c2/src/effects.js#L231), ultimately dating all the way back to [jQuery 1.0](https://github.com/jquery/jquery/commit/29a059142123a8bde16de2e579e7708a86a8de78#diff-3f7c2d96161eb7e4cf32df26fd18a923R246). I doubt it's still relevant, and would be comfortable removing it. Any objections, @jquery/core?

**Comment by gnarf** [comment]
Seems safe to remove to me - So long as IE whatever doesn't throw problems if we try to set width/height to 0 (but I think we were guarding that somewhere else anyway recently) -  Also, lol at that comment on that line back in 1.0 :)

**Comment by mzgol** [comment]
If it works fine in IE8 without this hack, :+1: for removing.

**Comment by gibson042** [comment]
Great, so who can identify what the problematic behavior actually was? "IE flicker" isn't quite precise enough for me.

**Comment by gnarf** [comment]
only @jeresig probably

**Comment by jeresig** [comment]
Lord knows - probably for IE 5 or something. Feel free to nuke if you can't reproduce!
