### ISSUE TITLE
Remove the unspecified-class .toggleClass signature

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#2491]
cf. jquery/api.jquery.com/issues/781

`.toggleClass( [boolean] )` is [inaccurately documented](http://api.jquery.com/toggleClass/#toggleClass-state), (probably) not working correctly, easy to manually implement by library consumers, and I can't even come up with a reasonable use case calling for removal/restoration of all classes.

**Comment by mzgol** [comment]
:+1:, even current described behavior when no switch is provided is very confusing & non-intuitive.

**Comment by arthurvr** [comment]
:+1: I don't think there's much use of that signature in the wild eighter.

**Comment by timmywil** [comment]
Good to remove, per meeting.

**Comment by mgol** [comment]
I removed the `3.0.0` milestone as it was backed out in the end.
