### ISSUE TITLE
Elements are not selected by ID if the ID contains a dot

### ISSUE THREAD

**Issue by JostBaron** [jquery/jquery#2492]
According to both the HTML 4 and the HTML 5 specifications, the ID-attribute may contain dots (but not as first character in HTML 4). However, if an ID contains a dot, jQuery does not select the element when doing `jQuery('#<id>');`.

I've tested this in Firefox 39.0 (Ubuntu version) and Chromium 43.0.2357.130 Ubuntu 15.04 (64-bit).

Test program that exhibits the buggy behavior:

    <!DOCTYPE html>
    <html>
        <head>
            <title>Test!</title>
            <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        </head>
        <body>
            <div id="te.st">foobar</div>

            <script type="text/javascript">
                jQuery(document).ready(function() {
                    alert('Content of div: ' + jQuery('#te.st').text());
                });
            </script>
        </body>
    </html>

Test program not using jQuery for selection, that does not exhibit the buggy behavior:

    <!DOCTYPE html>
    <html>
        <head>
            <title>Test!</title>
            <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        </head>
        <body>
            <div id="te.st">foobar</div>

            <script type="text/javascript">
                jQuery(document).ready(function() {
                    alert('Content of div: ' + document.getElementById('te.st').textContent);
                });
            </script>
        </body>
    </html>

**Comment by staabm** [comment]
you need to escape the dog, like `'#te\\.st'`

**Comment by gibson042** [comment]
"." is a special character and [must be escaped](http://api.jquery.com/category/selectors/). Use `jQuery('#te\\.st')` instead of `jQuery('#te.st')`.

**Comment by Mr21** [comment]
Try to not use `.` instead of escaping.
Where is the difference here:
```
<div id="a" class="b"></div>    $("#a.b")
<div id="a.b"></div>            $("#a.b")
```

**Comment by JostBaron** [comment]
@All: You are right of course, jQuery takes a selector, getElementById takes an ID. Dots in selectors are different then dots in IDs. Thanks for pointing it out, my fault.

@Mr21: Sometimes you can not not use a dot. For example if the ID is generated by PHPs `uinqid()` with `more_entropy` set to `TRUE`.
