### ISSUE TITLE
Table manipulation regression (XHTML)

### ISSUE THREAD

**Issue by anthonyryan1** [jquery/jquery#2493]
jQuery 3.0 introduced an XHTML regression in the appending and updating of table rows, it appears the outermost element in every `.append()`, `.html()`, `.load()`, etc gets removed and only the contents of that outermost element are actually appended or set as the innerHTML.

Simple test case (requires `Content-type: application/xhtml+xml; charset=utf-8;` to properly demonstrate the regression)

```html 
<!-- fill in doctype, html, head, body, etc. -->
<table>
<thead>
    <tr>
        <th>One</th>
        <th>Two</th>
        <th>Three</th>
    </tr>
</thead>
<tbody id="append"></tbody>
</table>
```

```javascript
$(document).ready(function(){
    $('#append').append('<tr><td>Four</td><td>Five</td><td>Six</td></tr>');
    $('#append').append('<tr><td>Seven</td><td>Eight</td><td>Nine</td></tr>');
});
```

In XHTML mode, the resulting DOM is the equivalent of:

```html
<table>
<thead>
    <tr>
        <th>One</th>
        <th>Two</th>
        <th>Three</th>
    </tr>
</thead>
<tbody id="append">
    <td>Four</td>
    <td>Five</td>
    <td>Six</td>
    <td>Seven</td>
    <td>Eight</td>
    <td>Nine</td>
</tbody>
</table>
```

I've also noticed the XHTML test harness is once again broken and likely how this regression occurred, but that's outside the scope of this issue.

**Comment by kishu1** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김태훈(kishu@navercorp.com) 님은 현재 부재중입니다.</br>
보내신 메일 <[jquery] Table manipulation regression (XHTML) (#2493)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김태훈(kishu@navercorp.com) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-07-23 10:00 ~ 2015-07-23 19:00 GMT +09:00]<br>개인 사유로 연차 중입니다. 급한 용무는 모바일(010-2940-0359)로 연락 바랍니다.
--------------------------------------------

**Comment by Mr21** [comment]
If I test this in chrome:
``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>

<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8"/>
<script src="https://code.jquery.com/jquery-3.0.0-alpha1.js"></script>

</head>
<body>

<table>
	<thead>
		<tr>
			<th>1</th>
			<th>2</th>
			<th>3</th>
		</tr>
	</thead>
	<tbody id="append"></tbody>
</table>

<script>

$( "#append" )
	.append( "<tr><td>4</td><td>5</td><td>6</td></tr>" )
	.append( "<tr><td>7</td><td>8</td><td>9</td></tr>" )
;

</script>
</body>
</html>
```
There is no problem.

We can't use `<meta>` with jsfiddle :(

**Comment by dmethvin** [comment]
The doc has to be served with the right `content-type` tho as @anthonyryan1 said, otherwise it won't be xhtml.

Looks like we can't do 0ea342a6a6dce793c1b0f14f051c2573f40f4e44 because of xhtml?
