### ISSUE TITLE
Consider using conventional-changelog to generate changelog or github release?

### ISSUE THREAD

**Issue by stevemao** [jquery/jquery#2495]
we have [conventional-changelog](https://github.com/ajoslin/conventional-changelog) or [conventional-github-releaser](https://github.com/stevemao/conventional-github-releaser) (there are also grunt/gulp tasks) to automate the process of writing the changelog. As you are using formatted commit messages so the logs can be generated well according to the parts of the message. We use handlebars for templating the logs. It can also ignore reverted commits. There are many other features. We have a jquery preset for people using jquery commit format.
The modules are actively maintained.

**Comment by stevemao** [comment]
Sample logs


### build

* correct paths so that archiving works. ([8ab32fe](https://github.com/jquery/jquery/commit/8ab32fe))
* switch from .min.gz to .zip format. ([5e8a5f4](https://github.com/jquery/jquery/commit/5e8a5f4))
* update release script to use nodejs archiver. ([eaee6ea](https://github.com/jquery/jquery/commit/eaee6ea))

### Build

* Update testswarm task to node-testswarm 1.x API ([8643ac7](https://github.com/jquery/jquery/commit/8643ac7))

### Travis

* Also install bower ([4228905](https://github.com/jquery/jquery/commit/4228905))

**Comment by arthurvr** [comment]
I'm afraid we can't do much with that. We have a very specific [release process](https://github.com/jquery/jquery-release), which generates changelogs and publishes them to the website. I don't see much of a reason to switch to an alternative solution, as `chagelogplease` is [doing fine](https://github.com/jquery/jquery-release/blob/master/lib/changelog.js).

**Comment by scottgonzalez** [comment]
I'm not sure there's much value in changing which tool we use. conventional-changelog looks decent, but it also has a ton of dependencies. Either way, this wouldn't be a change in jquery, it'd be part of jquery-release.

**Comment by yb66** [comment]
> which generates changelogs and publishes them to the website

Where?

Regards,
yb
