### ISSUE TITLE
using hasOwnProperty to check for a property that exists in the prototype

### ISSUE THREAD

**Issue by danielz000** [jquery/jquery#2496]
Hi,

It seems like jQuery is using hasOwn / hasOwnProperty to check for a property on an object. 

Where the property exists in the prototype of the object Chrome has started returning false as per the following post:

https://developers.google.com/web/updates/2015/04/DOM-attributes-now-on-the-prototype?hl=en

It seems that using the "in" operator may resolve this issue.

Here is an example of where the problem occurs in jQuery-2.1.4.js

line 4264-4269
trigger: function( event, data, elem, onlyHandlers ) {

	var i, cur, tmp, bubbleType, ontype, handle, special,
	eventPath = [ elem || document ],
	type = hasOwn.call( event, "type" ) ? event.type : event,
	namespaces = hasOwn.call( event, "namespace" ) ? event.namespace.split(".") : [];

which then causes an issue here

line 4283
	if ( type.indexOf(".") >= 0 ) {

Hope this makes sense.

Daniel

**Comment by dmethvin** [comment]
Do you have an example where this is failing?

**Comment by danielz000** [comment]
Sorry for the delay...
My code looks a bit like this:
function search_by_itemnumber(tmpValue, originField){	var transaction = pimsDB.transaction("drugs");	var objectStore = transaction.objectStore("drugs");	var request = objectStore.get(tmpValue);	request.onsuccess = function(e)	{		if (e.target.result == null)		{			search_by_popcode(tmpValue, originField);		}		else		{			var event = new CustomEvent('drugsearchcomplete', { 'detail': e.target.result });			$(originField).trigger(event);		}	}}
Inside of the jquery code there's the following (line 4264):
	trigger: function( event, data, elem, onlyHandlers ) {
		var i, cur, tmp, bubbleType, ontype, handle, special,			eventPath = [ elem || document ],			type = hasOwn.call( event, "type" ) ? event.type : event,			namespaces = hasOwn.call( event, "namespace" ) ? event.namespace.split(".") : [];
		cur = tmp = elem = elem || document;
		// Don't do events on text and comment nodes		if ( elem.nodeType === 3 || elem.nodeType === 8 ) {			return;		}
		// focus/blur morphs to focusin/out; ensure we're not firing them right now		if ( rfocusMorph.test( type + jQuery.event.triggered ) ) {			return;		}
		if ( type.indexOf(".") >= 0 ) {			// Namespaced trigger; create a regexp to match event type in handle()			namespaces = type.split(".");			type = namespaces.shift();			namespaces.sort();		}
hasOwn.call(event, "type") used to return true in Chrome, but since the change mentioned in the link I posted it returns false. The error then occurs at type.indexOf as "type" has become a type of CustomEvent and not a string as expected.
My understanding for why this is, is that the type property doesn't below to the event object, it belongs to the event prototype and so hasOwnProperty now returns false.
I have temporarily changed the jquery code to fix the application as follows:
type = ("type" in event) ? event.type : event,
For my application, this fixes the problem and doesn't cause any other issues but I can't be certain this would be the same for other applications.
Hope that makes sense?
Cheers,
Dan
Date: Fri, 24 Jul 2015 22:42:08 -0700

**Comment by mzgol** [comment]
Please provide a minimal but complete test case at http://jsfiddle.net or
https://jsbin.com

-- 
Michał Gołębiowski

**Comment by danielz000** [comment]
http://jsfiddle.net/8su2v06b/

**Comment by mzgol** [comment]
Thanks for the test case, it's exactly what I needed! :)

The behavior changes in Chrome are introduced to align its implementation with the standard and with what other browsers do, e.g. Firefox has behaved in this way for a long time; it's nothing new then. You can see your fiddle fails in Firefox as well.

I agree we should follow the prototype chain here.

**Comment by danielz000** [comment]
Your welcome, hope it helps :)

**Comment by mansisce** [comment]
Can you assign  me on this issue ? I want to start contributing into jquery?

**Comment by mzgol** [comment]
@mansisce You can just submit a PR. GitHub doesn't allow to assign issues to people that don't have commit access to the repository.

**Comment by markelog** [comment]
@mansisce also, check it out - http://contribute.jquery.org/ there is lots of useful info how to contribute to jquery.

If you have any questions don't hesitate to ask, preferable on irc channels. Thank you for you interest!

**Comment by dmethvin** [comment]
@danielz000 That's trying to trigger a native raw DOM `customEvent` using jQuery. That's [not a valid API input](http://api.jquery.com/trigger/). You can create a `jQuery.Event` or pass in your own custom event string like `"myNewEvent"`.

**Comment by dmethvin** [comment]
Just to further clarify, since a raw DOM event should never be passed, it's not important where the properties are on the raw DOM event object for this code. The check is on a `jQuery.Event` object.
