### ISSUE TITLE
Support non-browser environments in jQuery Compat

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2501]
Per today's meeting, we'll try to support non-browser environments in jQuery Compat.

**Comment by mzgol** [comment]
PR: #2504.

**Comment by markelog** [comment]
Landed via https://github.com/jquery/jquery/commit/04ec688e806660107a0b5823fabe2fe213f63b92

**Comment by mzgol** [comment]
I'd like to *not* backport it to 1.12.

**Comment by timmywil** [comment]
@mzgol I agree

**Comment by markelog** [comment]
Since 1.12 will be released, i will remove `wontfix` label

**Comment by mzgol** [comment]
I'd like it to stay wontfix. Supporting non-browser wnvironments requires some effort and IE<8-specific code can be problematic. I don't want to guarantee that 1.x is now good for non-browser, it better stay unsupported, it won't live much longer anyway.
