### ISSUE TITLE
Add basic tests for Android 2.3 on master, drop full support

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2505]
jQuery 3.0.0 will include only basic support for Android 2.3, bigger non-critical workarounds like `reliableMarginRight` will be `compat`-only.

Those tests need to be written.

To not create further divergence between `master` & `compat` test files, I propose to create a separate `android` "module" with those basic tests. Thoughts?

**Comment by gibson042** [comment]
> To not create further divergence between `master` & `compat` test files, I propose to create a separate `android` "module" with those basic tests. Thoughts?

I like the idea, but would rather see a name like "basic" or "minimal" so we're not tied to a given client—the same suite might apply to e.g. jsdom or PhantomJS.

**Comment by mzgol** [comment]
> I (...) would rather see a name like "basic" or "minimal" so we're not tied to a given client

Works for me. Good idea about jsdom & PhantomJS, btw, this might not be that hard to add once we have this.

**Comment by mzgol** [comment]
PR (in progress but I need feedback before I continue): #2509.

**Comment by mzgol** [comment]
This is not fixed until we reduce support as in the title. Only the first part (basic tests) have been finished.

**Comment by mzgol** [comment]
PR: #2581
