### ISSUE TITLE
Include color animations in core

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery#2508]
It's f***ing ridiculous that to this day, one still needs to use a plugin in order to be able to animate colors. It's about time (it's been for years) to have this functionality included into the core

**Comment by mzgol** [comment]
Please mind your language.

Nothing prevents you from using the `jquery-color` plugin. The code around that is pretty long, it's not a trivial task to animate across many possible syntaxes as you can see by looking at the size of the [jquery.color.js](https://github.com/jquery/jquery-color/blob/master/jquery.color.js) file. Including that into core would needlessly penalize users that don't need this functionality.

**Comment by teo1978** [comment]
It's a very basic and vital functionality.

> Including that into core would needlessly penalize users that don't need this functionality.

That argument applies to just about any functionality, so you could argue in favour of dismembering jquery into thousands of plugins and a minimal core that does almost nothing. 

What determines whether or not a functionality needs to be in the core is how vital it is and how large a proportion of users using jquery are likely to need it.

If needlesly having an additional few hundreds bytes of minimized code penalizes users who don't need that, having to include an additional plugin (for every superbasic functionality) penalizes those who do need it, a lot more. Note that the former is an almost negligible penalisation, while the latter is a true pain in the... (ops, sorry, I have to mind my language), so the trade off is definitely in favour of having it in the core unless a really VAST majority of users are not going to need animating colors, which I'm pretty sure is not the case.

**Comment by mzgol** [comment]
This is the first issue for a long time I remember that asks for inclusion of jquery-color into core. It doesn't seems there's a huge demand for this.

As for other features - if we implemented them today, some of them would most likely be plugins instead of parts of Core. But the ship has sailed, they're there and some plugins may depend on them being in Core.

**Comment by dmethvin** [comment]
I completely agree, our current code has several things that would better be done as plugins. It's easy to see your own needs as being universal but that's often not the case. Asking users to combine their own files or use a package manager is not a heavy burden. If that is too complicated they can use multiple script tags.

**Comment by teo1978** [comment]
It's not a matter of seeing one's need as universal. They obviously aren't.

What *is* a universal need is to not have to add a damn new plugin for every basic little trivial feature.
"Oh, sh* wait, I have to look for the plugin for that", every five minutes.

In the particular case of animating colors, being able to animate a width/height/position/opacity but not being able to animate a color is just ridiculous, it always was since the beginning (yes, I do perfectly understand why animating a color is much more convoluted, so what). 
You may argue that animate() itself should be a plugin: well, that at least would be consistent, provided that it included colors. Having animations as a whole in a plugin makes sense. Having them all in the core makes sense (though I'd consider that a very poor choice). Having animations in the core except for colors is inconsistent and ugly.

Another approach (consistent but INSANE) would be to have a plugin for every single animatable css property (or "set" of properties based on some criteria for grouping them). If that's the kind of approach you are going to take (obviously not for animations but as a general approach), well, that's really sad.

**Comment by tommiehansen** [comment]
Colors should be animated via CSS in the future and not js so the need for jquery.color should be sort of a non-issue in the future.
