### ISSUE TITLE
Don't expose jQuery.access

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2513]
`jQuery.access` is public & undocumented, is there a reason we should keep it that way? We removed `jQuery.swap` (#2058), `jQuery.buildFragment` (#2224) & `jQuery.domManip` (#2225).

See also #2512.

**Comment by mzgol** [comment]
PR: #2524

**Comment by milesj** [comment]
This was unfortunate. `$.access()` was great for building our own getter/setter combo methods.

**Comment by timmywil** [comment]
Sorry for the inconvenience! I'd be willing to consider exposing this method (and documenting it) for plugins, but we don't like having public methods that aren't documented.
