### ISSUE TITLE
.animate() doesn't do anything on apparently random page loads

### ISSUE THREAD

**Issue by drasnop** [jquery/jquery#2516]
Using jQuery 2.1.0 on latest Chrome and Firefox on Windows 8.1

This bug seems to happen randomly, maybe once every 30-50 times I reload my web app. It also happened on other people's browsers. 

I want to animate the width of element #a to a fixed value. I call `$("#a").animate({"width": "600px", 1000, callback)`, with the callback simply logging a success message in the console. Most of the time, it works perfectly fine.

But, on rare occasions, when I load my web app, this instruction doesn't do anything: 
* the width doesn't change
* the end callback is never called
* the element #a is never `:animated`

And this behavior remains the same until I reload the page, not matter how many times I try to call `$("#a").animate()`. However, I can still:
* change css properties of #a directly: `$("#a").css()`
* animate other elements: `$("#b").animate()`

Unfortunately, since this bug is not reproducible so I cannot provide a fiddle. I've only been able to investigate it because I saw it happen once, and dug down the issue with the console.

**Comment by timmywil** [comment]
Thank you for opening an issue, but without a reproducible test case, there's nothing we can do.
