### ISSUE TITLE
There should be a common event for any DOM Manipulation

### ISSUE THREAD

**Issue by sohan5005** [jquery/jquery#2517]
Hi, I'm looking for this for a long time. Currently there is no common event on DOM Manipulation. There should be an event which is fired on any of these function calls: https://api.jquery.com/category/manipulation/

The event can be fired on document or window so that any changes on DOM can be detected.

**Comment by timmywil** [comment]
Thank you for opening issue, but this is not something we can implement in jQuery and guarantee that it will work across browsers or be the source of unexpected behaviors.

**Comment by scottgonzalez** [comment]
@sohan5005 You probably want to look into [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver).
