### ISSUE TITLE
How to exclude a parameter from a get request?

### ISSUE THREAD

**Issue by cawa-93** [jquery/jquery#2522]
Example:
```javascript
var params = {
  str: 'String',
  lang: null
},
defParams = {
  lang: 'en'
},

getParams = jQuery.extend({}, defParams, params); // Object {lang: null, str: "String"}
jQuery.getJSON('http://exemple.com', getParams);
```
A get request is sent to the address:
```
http://exemple.com?lang=&str=String
```
But I need it to be:
```
http://exemple.com?str=String
```
The essence of the question: what should be the value of `params.lang`, that this option was completely removed from the URL address?

Test using jQuery.param:
```javascript
jQuery.param({
  str:'String',
  emp:'',
  undef: undefined,
  nl: null
});
// "str=String&emp=&undef=&nl="
```
As you can see all the empty values are present in the URL address of the request.

**Comment by FagnerMartinsBrack** [comment]
> As you can see all the empty values are present in the URL address of the request.

If you are providing empty values, you get empty parameters. If you don't want a parameter in the request, the expected would be to just remove the property from the Object Literal or not even declare it.

> what should be the value of params.lang, that this option was completely removed from the URL address?

You can't remove the parameter just by messing with the  `params.lang` property because you are extending both objects, you can remove the property from the `params`, `defParams`, or from the `getParams` Object in the end.

```javascript
var params = {
  str: 'String',
  lang: null
},
defParams = {
  lang: 'en'
};

delete params.lang; // < ===================================================
delete defParams.lang; // < ===================================================
    
getParams = jQuery.extend({}, defParams, params); // Object {str: "String"}

// ... or this
// delete getParams.lang;

jQuery.getJSON('http://exemple.com', getParams);
```

**Comment by cawa-93** [comment]
Maybe it makes sense not to include parameters with the value undefined to a string? Let me explain. I have the code like this:
```javascript
$.ajaxSetup({
	data: {
		lang: 'en',
		key: 'some_access_key'
	},
});

function CallApi (method, options) {
	jQuery.getJSON('http://exemple.com/' + method, options);
}
```
As used:
```javascript
// Everything is fine
// http://exemple.com/UserMessage?lang=en&key=some_access_key&messageCount=5
CallApi('UserMessage', {messageCount: 5});
// And here the problems begin. 
// Although the passed value and replaces the default value,
// but the parameter lang is still there in the address of the request.
// What the server returns incorrect data.
// http://exemple.com/UserLang?lang=&key=some_access_key
CallApi('UserLang', {lang: undefined});
```
The most obvious solution - add in CallApi condition:
```javascript
function CallApi (method, options) {
	if (method === 'UserLang') {
		delete jQuery.ajaxSettings.data.lang;
	}
	jQuery.getJSON('http://exemple.com/' + method, options);
}
```
But this approach causes a lot of problems and unnecessary steps;

**Comment by dmethvin** [comment]
Since this isn't a bug report, I'll close it. Programming help can be found at the jQuery Forum or StackOverflow.
