### ISSUE TITLE
jquery munges wheel event

### ISSUE THREAD

**Issue by twhitbeck** [jquery/jquery#2523]
`WheelEvent` has two properties `deltaX` and `deltaY` (see [mdn](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent)). Both of these properties are absent on event that jQuery provides for `wheel` event.

```js
$("#element").on('wheel', function(e) { console.log(e.deltaX); });
```

outputs `undefined`

**Comment by mzgol** [comment]
jQuery only copies most commonly used event properties and wheel isn't implemented in all browsers we support. You can still find them on `originalEvent` in browsers that support the event:
```js
$("#element").on('wheel', function(e) { console.log(e.originalEvent.deltaX); });
```

For full support for this event please use either [jquery-mousewheel](https://www.npmjs.com/package/jquery-mousewheel) (that exposes a `mousewheel` event but uses `wheel` under the hood if available) or, if you don't need to support older browsers (like IE8), you may try [jquery-wheel](https://www.npmjs.com/package/jquery-wheel).

**Comment by staabm** [comment]
see also http://api.jquery.com/category/events/event-object/
