### ISSUE TITLE
`getAttribute` call on `document-fragment`

### ISSUE THREAD

**Issue by pkaske** [jquery/jquery#2529]
**Hello jquery community,**

**First of all:**
Here's the [demo](http://pkaske.github.io/polymer-problems/jquery-event-delegation/index.html)

All relevant output show's up in the browser's console.
Here's a screenshot that shows the line in jQuery where the problem happens.
(You can see that `elem` is a `document-fragment`)
![selection_008](https://cloud.githubusercontent.com/assets/11567985/9084426/e9871192-3b73-11e5-8e19-7cd9f1b75dde.png)

**Source of the demo**
Can be found [here](https://github.com/pkaske/polymer-problems/tree/master/jquery-event-delegation)

**Situation**
You have a delegate click event handler that targets elements by a specific attribute
`$(document).on('click', '[some-attribute]', function() {...});`

You have a custom element that uses html5 templates to create a simple list of items.
Each item has a button to remove the parent item itself from the list.

**What happens**
The click on a items button removes the element before the event reaches the jQuery event handler. At the time the event arrives, the item has been removed and placed in a document fragment. Now jQuery tests the event selector on the document fragment and that fails of course.

I guess the fix would simply be to check if the element tested on the selector actually has a attribute api?

**Comment by gibson042** [comment]
I am unable to reproduce with your demo. Can you provide a reduced test case (e.g., without Polymer) against the [git build](http://code.jquery.com/jquery-git.js), preferably somewhere like [JS Bin](http://jsbin.com/) so it's easy for us to tinker with it?

**Comment by pkaske** [comment]
Haha, sorry. I accidentally uploaded my temp. workaround... (With is a timeout that waits till the event bubbled up and then remove the element).

Here is a demo on JS BIN:
http://jsbin.com/puvifoxebi/edit?html,console,output

Sorry, I didn't prepare a demo without Polymer, because my knowledge of HTML5 Templates is to narrow to set something like this up.

But I posted the same Issue at the polymer repository and got a explanation from them. This maybe provides you some clues on what's going on. There is also a better workaround for the problem in the conversion.

https://github.com/Polymer/polymer/issues/2210

**Comment by dmethvin** [comment]
Here's a simple repro: http://jsbin.com/bobuhovici/1/edit?html,js,output

**Comment by gibson042** [comment]
Looks like https://github.com/jquery/jquery/commit/fc2ba2e1361126c39f955437ee025cfca3bffa65 is needed in `master` as well (i.e., [we should have listened to @dcherman](http://bugs.jquery.com/ticket/13208#comment:9)).
