### ISSUE TITLE
Data: new data-as-expando implementation uses delete on DOM nodes

### ISSUE THREAD

**Issue by jbedard** [jquery/jquery#2530]
The jQuery3 data changes started doing `delete elem[ expando ]` similar to what jQuery1 originally did (see #1664). jQuery2 previously left the data property on the nodes and never deleted it so this wasn't an issue.

#1664 has the originally jQuery1 discussion. The jsperf mentioned there (http://jsperf.com/cleandata/4) still shows improvements using assign instead of delete with the latest Chrome.

**Comment by mzgol** [comment]
Fixed by 0e982433eb94391b3e9f6838d9b8fbf9bb31abf9, I forgot to add the "Fixes" reference.
