### ISSUE TITLE
npm shim module for jQuery 1.x compatibility build

### ISSUE THREAD

**Issue by kmck** [jquery/jquery#2531]
Hi there! Any chance to get the npm package for [jquery-compat](https://www.npmjs.com/package/jquery-compat) to have multiple releases tracking the non-beta 1.x versions?

Based on looking at [this thread](https://github.com/npm/npm/issues/5499), shim modules seem like the easiest way to get what I want for now. I'm using npm and browserify to bundle stuff and have reasons to use 2.x in certain bundles and 1.x in others. Basically something like the way I can have both [lodash](https://www.npmjs.com/package/lodash) and [lodash-compat](https://www.npmjs.com/package/lodash-compat) in the same package and require them as needed.

**Comment by timmywil** [comment]
Yes, we will be copying over the old 1.x tags before the final release of jquery-compat.

**Comment by kmck** [comment]
Cool! Thank you.

**Comment by mzgol** [comment]
@timmywil Note that it's not enough to copy tags - every one of them needs to get the name "jquery" in package.json/bower.json changed to jquery-compat; afterwards, every tag from 1.11.0 (but not older to be consistent with the main jquery package!) needs to be checked out and published to npm via "npm publish".

I'm not against it, I'm just pointing out that it's a little more involved than just copying tags.

**Comment by timmywil** [comment]
Good point, but I think it's still worth doing.

**Comment by timmywil** [comment]
This will no longer be necessary. There will only be one jQuery by the time 3.0 is released.


![](http://itbloodpressure.com/wp-content/uploads/2015/02/cat.jpg)

**Comment by mzgol** [comment]
@timmywil Please remember to always remove the milestone & add the `wontfix` label if you're closing the issue that's not getting fixed. Otherwise we'll have a mess of a changelog.
