### ISSUE TITLE
jQuery Truck Factor

### ISSUE THREAD

**Issue by gavelino** [jquery/jquery#2533]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **jQuery** and obtained a value of **4**.

The developers responsible for this TF are:

Timmy Willison - author of 34% of the files
jaubourg - author of 25% of the files
John Resig - author of 21% of the files
Michał Gołębiowski - author of 17% of the files

To validate our results, we would like to ask **jQuery** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **jQuery**?

(b) Do you agree that **jQuery** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **jQuery** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by dmethvin** [comment]
It looks like the TF you're calculating may weight "percent of the files" too highly versus contributions to individual files for example. Do you have some more detail on how you did this calculation? When new files are created (for example as a result of the reorg that was done when we switched to AMD) does that person now "own" all those files regardless of whether they wrote the code?

Also is this weighted in any way based on age of contributions? You can look at our [contributor graph](https://github.com/jquery/jquery/graphs/contributors) and see that some of the people mentioned have not made recent commits, but I don't think the project is in trouble as a result.

**Comment by jaubourg** [comment]
All-time percentages are properly not the right indicators here. Limiting to the last year would probably give a much more accurate result.

**Comment by mzgol** [comment]
I'm an author of 17% files mostly because of bbbdd947256a3fcd788fb9d4f306046082a1ef1f where I moved a lot of the code around. If you just see who's the latest author via `git blame`, you'll ignore all the wisdom that went into creation of these files & their evolution over time.

**Comment by timmywil** [comment]
I can appreciate the concept and effort you're putting into this project, but now that some suggestions have made it into the comments, I'm inclined to go ahead an close this to facilitate triage. Feel free to continue discussion in this ticket. It will just be closed.
