### ISSUE TITLE
Can't read transition with .css in Microsoft Edge

### ISSUE THREAD

**Issue by JemarJones** [jquery/jquery#2535]
Not sure if this has to do with more than just this case but it's illustrated here http://jsfiddle.net/69h99rec/ . In other browsers this would log the transition. In edge its just an empty string.

**Comment by dmethvin** [comment]
Are you seeing the value in IE11? I'm not, but it's possible to get the individual values:
http://jsfiddle.net/69h99rec/1/

**Comment by JemarJones** [comment]
Yeup you're right it's also not there on IE11 (on Windows 10). Is this the expected behavior?

**Comment by dmethvin** [comment]
Shorthand properties can be a little flaky in general and is [something jQuery can't control](http://api.jquery.com/css/). Setting via a shorthand usually works fine, but getting shorthand properties can be iffy. A good example is if you try to get the shorthand for `border` but the borders have been set uniquely for different sides.

**Comment by JemarJones** [comment]
I see, quite unfortunate that there are still browser specific quirks even within jQuery. Getting them individually will have to do then.
