### ISSUE TITLE
Scripts in inner html are not exectuted sequentially in order

### ISSUE THREAD

**Issue by junaidpv** [jquery/jquery#2538]
When inner HTML contains scripts, one external and other inline, are not executed sequentially in order.

Here is a sample demonstrating the issue: http://jsfiddle.net/8cqa7byq/2/

Above sample uses this as inner HTML: https://gist.githubusercontent.com/junaidpv/8027996b52d8446a7054/raw/e48d8abbea9808549960a84e747e7a58686d0b2a/html-with-script.html
Which contains an external script (twitter widget) and following inline script uses ```TWTR``` object from previous external script. In my project for @wickwood the inline script is generated dynamically, so I cannot put it on a separate file now.

If you run above fiddle you will get ```ReferenceError: TWTR is not defined``` on console.

While debugging, I see script tags are processed at https://github.com/jquery/jquery/blob/1.7.2/jquery.js#L6068
The scripts are considered in correct order, but for unknown reason external script is not get loaded till inline script is executed.

I did search to find if it is already reported and did not find it. Will it have a workaround?

Thanks

**Comment by gibson042** [comment]
```html
<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({ });
</script>
```

The remote script executes asynchronously, but the inline script executes synchronously. Given that we try to always run synchronously for backwards compatibility but cannot do so with cross-domain scripts, I don't see any options within jQuery. You should update the inline script to introduce a grace period for the definition of `TWTR`.

**Comment by dmethvin** [comment]
Even if we could run this sync, it would be a bad idea anyway. That would just perpetuate the bad practice of holding up the main thread. Really the best way to do this would be to use a `$.getScript()` and execute the initialization in a `.then()`. 

I suppose we could define all inline HTML script evaluation to be a chain of async Deferreds to make them seqential? The problem with that would be getting access to the end of the chain to know when it's ready. So many methods inject HTML. It also creates a Deferred dependency in manipulation where we don't have one today.

**Comment by gibson042** [comment]
See https://github.com/jquery/jquery/pull/2126#issuecomment-78762735 and https://github.com/jquery/jquery/pull/2126#issuecomment-79105443 .
