### ISSUE TITLE
Chrome (and FF?): <tr> position offset doesn't work correctly within <tbody> (v. 2.1.1)

### ISSUE THREAD

**Issue by arxpoetica** [jquery/jquery#2539]
This is the case when setting `position: relative;` on a `<tbody>` element following a `<thead>` element. I have to find the height of the `thead` element and subtract it to get an accurate top position:

```js
var actualTopPosition = $('tr:first-child').position().top - $('thead').outerHeight();
```

**Comment by dmethvin** [comment]
Can you provide a test case please?

**Comment by mzgol** [comment]
Also, try to test on jQuery 2.1.4 and the latest `master` from https://code.jquery.com/jquery-git.js

**Comment by codebhendi** [comment]
can you please explain your issue, I am unable to understand it ?

**Comment by arxpoetica** [comment]
Well...so I created this [Fiddle](https://jsfiddle.net/langbert/4oqqhg9s/1/), and it's working there, so it must have been something wonky w/ my own code. Closing this issue.
