### ISSUE TITLE
ReplaceWith time, P tags parsing error

### ISSUE THREAD

**Issue by jackzhaojun** [jquery/jquery#2544]
<div class="test">
        <div class="drag">
            <div class="view">
                <div>
                    <p><div>test</div></p>
                    <table class="table">
                        <tr>
                            <th>test</th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script>
        var $test = $('.test').clone(),
            $view = $test.find('.view');
        $view.closest('.drag').replaceWith($view.html());
        console.log($test.html());
    </script>
   
   // Error output

    <div>
        <p></p> // Wrong here
        <div>test</div>
        <p></p> // Wrong here
        <table class="table">
            <tbody>
                <tr>
                    <th>test</th>
                </tr>
            </tbody>
        </table>
    </div>

**Comment by gibson042** [comment]
`<div>` is not valid inside `<p>`, so the browser infers tag start and tag end. This is correct behavior (and independent of jQuery).
