### ISSUE TITLE
jQuery.when doesn't recognize solitary thenables

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#2546]
`jQuery.when( a )` does not look for a `then` method on its argument, which differs from its behavior in longer `jQuery.when( a, … )` invocations. It should treat non-`Deferred` thenables identically in both cases.

http://jsfiddle.net/0r62we79/9/

**Comment by marcandre** [comment]
And I thought I was going crazy...
```
var failed = new Promise(function(resolve, reject) { reject('fail!'); });
$.when(failed).then(function(){console.log('Should not be here')});  // Not ok
$.when(failed, failed).then(function(){console.log('Should not be here either')}); // Ok
```
 Currently outputs "Should not be here" to the console.
