### ISSUE TITLE
$(location).attr("href")

### ISSUE THREAD

**Issue by marceloodiniz** [jquery/jquery#2549]
Browser: IE7 (emulated from IE11)

When I call this function (below) on IE7, it throws an exception, saying there is no function or property called "getAttribute". All other browsers, it worked! 

$(location).attr("href")
$(location).prop("href")

**Comment by dmethvin** [comment]
https://www.google.com/search?q=location+attr+href

**Comment by marceloodiniz** [comment]
Your answer did not helped me.. I will change my code to user "location.href", but I believe jQuery have an inconsistency. That what I was trying to tell.

**Comment by mzgol** [comment]
@marceloodiniz Literally the first link from @dmethvin's Google:
http://stackoverflow.com/questions/5474121/location-attrhref-not-working
"Location is *not an element in the dom* thus jQuery can not select it."
