### ISSUE TITLE
Don't expose jQuery.acceptData

### ISSUE THREAD

**Issue by jbedard** [jquery/jquery#2555]
Similar to the other "don't expose" cases. Is there any reason for this to be exposed and undocumented?

**Comment by markelog** [comment]
Hm, i guess one might argue that this function could be useful to plugin writers, but it seems we just should stop exposing it instead

**Comment by timmywil** [comment]
@arschmitz @scottgonzalez Do you use this in mobile/UI?

**Comment by jbedard** [comment]
Another option is to still expose it but use the internal var instead of `jQuery.acceptData` to save some bytes and not support overriding it. Today it is also [copied into Data](https://github.com/jquery/jquery/blob/master/src/data/Data.js#L12), so overriding it would be buggy anyway.

**Comment by arschmitz** [comment]
@timmywil this is not used by either ui or mobile

**Comment by markelog** [comment]
> @timmywil this is not used by either ui or mobile

It seems we're good of stop exposing it, @jbedard would you like to send us a pr?

**Comment by mzgol** [comment]
> Another option is to still expose it but use the internal var instead of `jQuery.acceptData` to save some bytes and not support overriding it.

By "exposing" we mean putting it on the `jQuery` object so that it's accessible in the compiled version. If you just use AMD modules you can get to a lot of internal stuff already, we just don't guarantee the file hierarchy doesn't change: it might do even in a patch release.
