### ISSUE TITLE
Avoid unnecessary reflow&restyle for IE support check in non-IE browsers

### ISSUE THREAD

**Issue by joelrich** [jquery/jquery#2560]
I am trying to reduce the reflows and restyles of a web application to improve the rendering performance and found an unnecessary occurrence in jQuery 1.11: https://github.com/jquery/jquery/blob/1.11-stable/src/support.js#L46

This has already been removed in jQuery 2. Since it seems to be only relevant for IE, wouldn't it be possible to check for a legacy IE API (like attachEvent) and execute the test only in this case?

**Comment by gibson042** [comment]
We don't use browser sniffing or unrelated inferences; we use feature/behavior detection (of which this is an example). However, note that the offending reflow happens only once, and waits for DOM ready. But if even this is too much, you may be able to switch jQuery 2 (depending on your own browser support).

**Comment by gibson042** [comment]
My mistake; it's already been removed: https://github.com/jquery/jquery/commit/90d7cc1d8b2ea7ac75f0eacb42439349c9c73278

Expect to _not_ see it in jQuery Compat 3.0.

**Comment by joelrich** [comment]
Unfortunately, we cannot use jQuery 2 yet.

On the one hand, I understand that my suggestion is not pure. However, this code was specifically written for IE and it is very unlikely that another non-IE-based browser will ever have the same problem. Based on this assumption this code was also removed for jQuery 2/3 compat. Therefore, I do not really understand why this code cannot just be ignored for non-IE browsers at runtime. In the end, removing code because a certain browser is not supported anymore and checking in the code for a certain browser is not that different.

**Comment by mzgol** [comment]
@joelrich 
> Based on this assumption this code was also removed for jQuery 2/3 compat. Therefore, I do not really understand why this code cannot just be ignored for non-IE browsers at runtime.

As @gibson042 said, this test has been removed and will not be present in jQuery Compat 3.0.0 (it was possible as we've dropped IE6/7 support in jQuery Compat). jQuery Compat 3.0 will the continuation of jQuery 1.x, jQuery 3.0 will be the continuation of jQuery 2.x. There is no currently maintained code that contains this code so I'm not sure what you're asking for.

As for the remark in general, user agent strings are notoriously unreliable; they can be changed, some browsers are changing them for particular sites that present compatibility issues so if we started relying on them we'd be introducing code that may break in various circumstances. It's just not worth it.

In any case, the code mentioned is gone so there's nothing to do regarding this bug report.

**Comment by joelrich** [comment]
@mzgol my idea would have been to have this change in 1.11.4. Are there no further 1.11.x releases planned?

My suggestion was to check for an IE legacy API (like attachEvent), not user agent sniffing. Alternatively, it could also use IE's conditional comments as described here: http://stackoverflow.com/a/5574871/1367730

**Comment by mzgol** [comment]
@joelrich There are no further 1.11.x releases planned, except if something critically important is discovered [as it happened with 1.11.3](http://blog.jquery.com/2015/04/28/jquery-1-11-3-and-2-1-4-released-ios-fail-safe-edition/). You're welcome to test [jQuery Compat 3.0.0-alpha1](https://code.jquery.com/jquery-compat-3.0.0-alpha1.js) if you don't need to support IE6/7 (just don't put it in production yet, it's only an alpha).

> My suggestion was to check for an IE legacy API (like attachEvent), not user agent sniffing.

Opera 12.16 has `attachEvent` as well. Checking an unrelated API is dangerous so we do it only if there's no other option; this is not such a case.

**Comment by dmethvin** [comment]
I don't think there are any additional releases planned in the 1.x or 2.x lines. We have limited resources to maintain, support, and test multiple branches.

The problem with unrelated legacy APIs as feature inferences is that they often go bad. Given the age of those browsers they may not, but history has shown that it is risky.

Conditional comments are often eaten by source code processors, there are even some mobile carriers that use on-the-fly compression to remove comments. That makes them a maintenance headache for any library code that is potentially processed after it's published, like jQuery.

**Comment by joelrich** [comment]
Ok, thanks for the explanation. I will consider jQuery Compat 3.0 once it's ready.
