### ISSUE TITLE
.css() for 'animation-delay' attribute cannot be set with variable

### ISSUE THREAD

**Issue by macaroni92** [jquery/jquery#2561]
I cannot use a variable to change the 'animation-delay' css property.

Note: This will work for something like background color or other animation attributes. The animation-delay will also work with a string '10s' but not a variable--even when the variable is explicitly set to a string.

```
var animationDelayTime = '10s'  
$('.my-animation-class').css({  
  'animation-delay' : animationDelayTime  
})
```
The this other method also does not work:
```
$('.my-animation-class').css(  
  'animation-delay', animationDelayTime  
)
```

This currently works:
```
$('.my-animation-class').css({  
  'animation-delay' : '10s'  
})
```

**Comment by macaroni92** [comment]
Okay, this has been resolved.

**Comment by mzgol** [comment]
You can't delete an issue but you can close it, please do so in the future.

It's impossible that an API breaks only if you pass a parameter to it via a variable, this is pure JavaScript and jQuery has nothing to do with it.
