### ISSUE TITLE
jQuery + Angular + Edge - event.dispatch question

### ISSUE THREAD

**Issue by mfc-julius** [jquery/jquery#2565]
Our Angular app has jQuery included in the minified vendor file, but uses it only on one case inside the directive:

```
parent.animate({
  scrollTop: parent.scrollTop() + target.parents('.comment').offset().top - $('.navbar').height()
}, {
  duration: 'medium',
  easing: 'swing'
});
```

Basically we use it to animate scrolling to the element, when it is added on the DOM.

We have noticed error logs, which tell us not much but:

```
n.prototype.$digest
n.prototype.$apply
$$debounceViewValueCommit
$setViewValue
b.$setActive
_.event.dispatch
q.handle
```

This happens only on the Edge browsers, and the "event.dispatch" is only found in two places on jQuery's code.

The question is, might it be something to do with jQuery, or it's more of Edge/Angular issue?

jQuery used v2.1.4

**Comment by dmethvin** [comment]
There's really not much to go on here. Is the application working properly? Where do these error logs come from? Is the only thing they give that list you've mentioned? Is it a stack trace?

**Comment by mzgol** [comment]
I have a pretty big Angular app and it works fine in Edge so it's definitely not completely broken (more people would notice anyway). We don't use Angular's form validation there, though.

What you posted looks like an excerpt from a stack trace but there's no actual error message there; is that all you have? It'd be really hard to say anything with such scarce info.

Could you create a test case at https://jsbin.com or http://plnkr.co?

**Comment by mfc-julius** [comment]
Sorry, I forgot to include the error message: "[$rootScope:infdig] 10 $digest() iterations reached. Aborting!".

It might even be not a jQuery problem, that's why I'm wondering maybe someone somehow could tell me what's going on there.

The error is tracked by Opbeat, which for JS is experimental in gives only very limited information.

The worst thing is, I can't reproduce it (though I will try to do it with Windows Phone emulator using Edge).

Sorry, I will add more info, when I get, or close if I will be sure it's not jQuery's case.

**Comment by dmethvin** [comment]
Closed due to inactivity.
