### ISSUE TITLE
"=" where it looks like it should be "==" in sizzle

### ISSUE THREAD

**Issue by joshupetersen** [jquery/jquery#2570]
I was looking through the repository, trying understand something in JQuery for the site I'm working on, and I stumbled across this: 

In jquery/external/sizzle/dist/sizzle.js, line 228, there's an if statement where condition is checked using "=" instead of "==". General coding practice is variables aren't set in conditional statements except when some extreme optimization is going on. So it either looks like a common typo and is, or it looks like a common typo because there's no comment explaining that the developer was being clever.

**Comment by mzgol** [comment]
It's not a typo, our unit tests would definitely catch it. It's just a way to check for truthiness of `context.getElementById( m )` and at the same time assign it to the variable `elem`. This saves a little of space.

There are more pattern like that but if someone just wrote:
```js
if ( elem = context.getElementById( m ) ) {
```
then it wouldn't work, JSHint would should that there is an assignment in the check. Wrapping it in double parens make the error go away and we treat it as a developer hint that this assignment is intended.
