### ISSUE TITLE
Use dot notation for "throws" property 

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2571]
Ref http://bugs.jquery.com/ticket/12158
From there, (by @dmethvin) - 

> We'll leave this quoted fix in for 1.8 but will remove it in the next minor/major release.

Back then, YUICOMPRESSOR had version `1.4.7`, now it is `2.4.8`, will do with https://github.com/jquery/jquery/pull/2542, since jscs chokes on it

**Comment by mzgol** [comment]
I vaguely remember QUnit had to restore the `raizes` alias because of some problems with `throws`. Could you remind us what was that about, @jzaefferer?

**Comment by jzaefferer** [comment]
A little late, but: https://github.com/jquery/qunit/blob/1967b78eb8d9faba8091607b8bcc397aa014db2c/src/assert.js#L174-L179

Narwhal shouldn't matter, Closure Compiler might be okay with it by now, but I recommend testing with it.
