### ISSUE TITLE
Triggering jquery event is not working on firefox versions 39-42

### ISSUE THREAD

**Issue by iamwebdesigner** [jquery/jquery#2576]
I am triggering a new jQuery event on an jQuery element. Everything works fine on: chrome and opera, but when it comes to firefox it throws an exception like this:  
```
Empty string cannot be an argument for the method: getElementById().
```
jQuery version is: 1.11.1  
Line of the exception is: 2798.  
Browser: Firefox 39, 40, 42 alpha.

**Comment by mzgol** [comment]
Please provide a reproducible test case on https://jsbin.com or https://jsfiddle.net. Without code to look at there's nothing we can do.

**Comment by dmethvin** [comment]
Closing this ticket for inactivity. Usually these kind of problems are best triaged on a forum until it's clear there is really a bug.
