### ISSUE TITLE
Add git hook linter

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2577]
We could run linters triggered by the `git-commit` command, so any possible garbage would be caught in time. Maybe some smoke tests would also be appropriate.

I'm thinking https://github.com/tarmolov/git-hooks-js could do the job.

**Comment by markelog** [comment]
per meeting, decided to try it, if wouldn't be annoying, while linting only changed files

**Comment by rdquintas** [comment]
Hi, was wondering if I could help here.
Is this still an open issue ?

**Comment by markelog** [comment]
It sure is, what is your thoughts?

**Comment by rdquintas** [comment]
Hi @markelog 
To be honest... I have no idea. :o) 

All I know is, I know GIT, jQuery and JS pretty well... so I thought I could lend my brain and try to help solving this issue.

To start with, was thinking of installing git-hook-js and  and take it from there

What else do you recommend ?

**Comment by markelog** [comment]
Yeah, `git-hook-js` is good one plus i worked with it on other projects, but it seems [husky](https://github.com/typicode/husky) has better architecture and more popular.

Also note, it would be better to run linters only on changed files, so if we would change readme for example, so in that case `git commit` shouldn't try to do anything. Purpose of it, to make it less annoying, which is the biggest concern

**Comment by rdquintas** [comment]
Hi @markelog I've noticed jQuery already has jshint configured.
I'm guessing we could use the exact same config .jshintrc.
What do you think ?

Yeah, I like [husky](https://github.com/typicode/husky) too. Will try with that.

**Comment by jha-naman** [comment]
Hey the above commit makes sure linters are run on new files before a commit.
Uses husky and grunt-newer.
Smoke tests are not run because grunt-newer does not seem to handle task aliases.

Please tell if any changes are needed. I am new to this stuff but will be glad to chip in.

**Comment by timmywil** [comment]
@jha-naman Thanks for your help!

**Comment by markelog** [comment]
@jha-naman would you mind sending us a PR?
