### ISSUE TITLE
Data: Unused method

### ISSUE THREAD

**Issue by mixed** [jquery/jquery#2583]
I have a question. I found this code blocks in data.js.
```js
	// TODO: Now that all calls to _data and _removeData have been replaced
	// with direct calls to dataPriv methods, these can be deprecated.
	_data: function( elem, name, data ) {
		return dataPriv.access( elem, name, data );
	},

	_removeData: function( elem, name ) {
		dataPriv.remove( elem, name );
	}
```
The jQuery does not use it like comments. Is it going to remove in 3.0.0?

**Comment by dmethvin** [comment]
The difference between master and compat regarding the data implementation has always been a pain in the butt as far as cherry picking is concerned. It would be good if we could eliminate the diffs one way or another.

The use of `jQuery._data(elem, "events")` is still pretty common, I think both Firefox and Chrome now grope into that data to make their breakpoints fall on user code. That may make it hard to remove.

**Comment by mixed** [comment]
@dmethvin Thanks for taking the time to explain history. ^^

**Comment by mzgol** [comment]
Because external tools rely on these interfaces, we need to keep them in the foreseeable future. Just try to not use them in code on public websites and if you use them somewhere, don't depend on them not breaking even between patch releases, we give no guarantees.

**Comment by FarSeeing** [comment]
What about removing or deprecating it now?

**Comment by mgol** [comment]
@FarSeeing Nothing has changed with respect to external tooling relying on those interfaces. On the other hand, we plan a big event refactor to, among other things, make it possible to support passive event listeners so it's possible this method will change in the process (and maybe go away, who knows).
