### ISSUE TITLE
In AJAX response Content-Type: Detected Wrongly

### ISSUE THREAD

**Issue by indvinoth** [jquery/jquery#2584]
When a AJAX call is made to download an Excel file, the server responds with an Excel file and server sets the content type as below
`Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`
When jQuery reads the response it detects the content type as `xml` since in the content type contains the word 'xml' in `openxmlformats`. So jquery tries to  parse the binary file as xml and triggers error

The content type is wrongly detected in the following function
 `function ajaxHandleResponses( s, jqXHR, responses )` 

jQuery Version used: 1.11.3

**Comment by dmethvin** [comment]
I agree that's a pretty sloppy check. At this point I am concerned to think what will happen if we make the check more strict. The best solution for your case is to be explicit about the `dataType` and not let us use the infamous and misnamed "intelligent guess" algorithm, which in this case is not so smart. 

As for whether we can or will change the intelligent guess algorithm, that's a discussion we need to have.

**Comment by mzgol** [comment]
I added the "Needs review" label to discuss it at the meeting.

This sounds like a bug to me, IMO we should fix it for 3.0.0.

**Comment by jaubourg** [comment]
Out the top of my hat, I'd say replacing `/xml/` with `/\bxml\b/` should do the trick.

**Comment by markelog** [comment]
aam, what about `text/xml`? we should do it for the other types as well then

**Comment by jaubourg** [comment]
> aam, what about `text/xml`? we should do it for the other types as well then

You wouldn't catch stuff like `application/rss+xml`.

Anyway, we just need to make sure we don't catch xml as part of a word which `/\bxml\b/` ensures. All dataType detection regexps should follow the same pattern.
