### ISSUE TITLE
animate

### ISSUE THREAD

**Issue by TrailTrackers** [jquery/jquery#2585]
if there are no elements to perform the original animation on, the callback does not get called; it should at the very least get called once.
IE10
Windows7

**Comment by timmywil** [comment]
If there's no animation, then no animation completed. The complete callback should not be called.

**Comment by dmethvin** [comment]
As the docs say,

> If multiple elements are animated, the callback is executed once per matched element, not once for the animation as a whole. -- http://api.jquery.com/animate/

The `this` inside the callback is the element that just completed animation. What would that value be if no elements were animated?

If you need a completion for the entire animation, look into `.promise()`.

http://jsbin.com/kevorosapu/edit?html,js,output

**Comment by TrailTrackers** [comment]
I also just tried this:
        function hideAndShow($h, $s) {
            $h.animate({ opacity: 0 }, {
                duration: 300,
                easing: 'linear',
                always: function() {
                    $h.addClass('dhide');
                    $s.removeClass('dhide').animate({ opacity: 1 }, 300, 'linear');
                }
            });

            //            $h.animate({ opacity: 0 }, 300, 'linear', function() {
            //                    $h.addClass('dhide');
            //                    $s.removeClass('dhide').animate({ opacity: 1 }, 300, 'linear');
            //                });
        }

and that didn't work either. I've tried the 'complete', 'done' and 'always' according to the documentation. Shouldn't the 'always' property 'always' run? This is what "always" means doesn't it?

**Comment by dmethvin** [comment]
The question is into StackOverflow or forum territory at this point, please ask for help in one of those places.

**Comment by TrailTrackers** [comment]
OK, thanks anyway. I still think that if you're going to give the option of having an "always" option, then whatever the 'always' is should "always" happen regardless of what happens prior; which is a bug imho. But thanks again.

**Comment by dmethvin** [comment]
It's *always* called for each element on the collection. There are no elements on the collection. Use `.promise()` as mentioned above.
