### ISSUE TITLE
Offset: Fractions test fails in Chrome 45

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#2590]
Two days ago, TestSwarm updated the jquery-core browser set from Chrome 43/44 to Chrome 44/45.

This revealed a test failure.

<http://swarm.jquery.org/result/619430>:
> offset: fractions (see #7730 and #7885) (1, 1, 2)
> Check top
> Expected: 1000
> Result: 999.984375

Looks like Chrome 45 is more precise than our tests expect.

**Comment by mzgol** [comment]
Yeah, I've noticed it even before updating the browsers as I've seen it on Chrome locally but I wanted to be sure it's not just my machine. But thanks for the report anyway!

**Comment by mzgol** [comment]
Actually, it seems Chrome 45 is *less* precise than older versions. I'll need to investigate further, I don't want to just decrease the test expectation without making sure this output is acceptable.

**Comment by dmethvin** [comment]
@mzgol I'm going to take this one for a jqsummit project.
