### ISSUE TITLE
Event delegation, in firefox when target is inside a disabled element, event does not bubble

### ISSUE THREAD

**Issue by brunoscopelliti** [jquery/jquery#2592]
Hi,

I made this pen to reproduce the problem: http://codepen.io/brunoscopelliti/pen/dYGbWz .

This works properly on the desktop version of IE, Chrome, Safari, but not in Firefox...

I'm not sure this is the right place to post this issue cause i don't think this is really a problem of jQuery, rather than firefox... however i will post it anyway, because maybe someone can point me to an already existing firefox's issue. Moreover it seems to me, somehow correlated to #2558 ...

**Comment by mzgol** [comment]
This is caused by https://bugzilla.mozilla.org/show_bug.cgi?id=218093. To workaround it on the jQuery side we'd have to use the `capture` phase but that would cause a lot of issues for such common events as `click`. So I don't think we can do a lot here.

**Comment by brunoscopelliti** [comment]
Thanks @mzgol 
since the bug is a firefox problem i suppose we can close the issue here...

**Comment by timmywil** [comment]
Thanks @brunoscopelliti
