### ISSUE TITLE
json $.ajax post messed up post-content when ?? in content

### ISSUE THREAD

**Issue by kojicz983** [jquery/jquery#2595]
This issue reported before but closed because supposedly a duplicate of #1791.

However it's not. As opposed to what's desribed in #1791, not the URL gets damaged but the actual data content. That also means this can't be fixed by cleaner usage of jQuery by avoiding double questionmarks in URLs.

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script>
(function() {
	var data = '{"a": "aa??bb"}';
	$.ajax({
		'beforeSend': function() {
			alert('I passed into $.ajax the data value:\n\n"' + data + '"\n\nbut it is going to send\n\n"' + this.data + '"');
		},
		'type': 'POST',
		'url': 'http://localhost',
		'data': data,
		'dataType': 'json'
		})
})()
</script>

When you post ?? as part of an ajax request, the content gets damaged.
The code below demonstrates this.

Version of jQuery used: http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
but also the 1.11.x branch has this error. The problem is browser independent.

(function() {
var data = '{"a": "aa??bb"}';
$.ajax({
'beforeSend': function() {
alert('I passed into $.ajax the data value:\n\n"' + data + '"\n\nbut it is going to send\n\n"' + this.data + '"');
},
'type': 'POST',
'url': 'http://localhost',
'data': data,
'dataType': 'json'
})
})()

**Comment by mzgol** [comment]
Please don't create a new issue just because an older one got closed. We see your comments, if we think something is worth reopening, we'll reopen.

**Comment by kojicz983** [comment]
Thanks and apologies. We're "just" users if jQuery and not too familiar with reporting bugs
