### ISSUE TITLE
IE/Edge taking an unusually long time to create many elements.

### ISSUE THREAD

**Issue by bracketsage** [jquery/jquery#2597]
Update: [jsfiddle/v4][1]

One of my sites dissects text-input an tries to explain it. Depending on the length of text, you can end up with several thousand elements. This functions lightning-fast in Chrome and Firefox but IE stalls while trying to create the elements, when there are many of them. The problem isn't rendering the elements but the actual creation, as my demo will show. As, in all browsers, the two tests take comparable time per browser. 

As the limit of the loop approaches 10,000, Edge is more likely to stall out, which is what I'm seeing a lot of in my website. At 1,000, it just takes a few seconds. At 2000, Edge takes 16 seconds in each of the two tests. Chrome and Firefox handily 10,000 in ~ four seconds.

After more than five solid minutes of waiting on Edge for 10,000 passes, I closed the process where chrome did it in less than 5 seconds.

This is strange because Edge does many things much quicker than IE did. Frequently its speeds rival or exceed Chrome and Firefox.

A sample run across the browsers mentioned has these results. The first number is the test that renders to the screen, the second number populates a jQuery-created element.

    Browser:	To Screen	To jQuery-created element, not injected into DOM.
    IE/Edge:	Stalled out.
    Chrome:		4519		3757
    Firefox:	4032		4092
    Opera:		16925		16450

I experienced some crashes in these tests, because I don't think any browser likes tags nested 10,000 deep, but that's not at all what I'm actually doing anyway. I experienced no crashes with the test that writes to a jquery-created element, other than MS's browsers.

(jsfiddle/v4 code)

    $(document).ready(function () {
       $("#clk").click(function () {
           StartTime = new Date().getTime();
           var htm = $("<span>")
           for (var i=0; i<10000; i++) {
               htm = $("<span>").append(htm);
           }
           $("#recip").html(htm);
           EndTime = new Date().getTime();
           TotalTime = EndTime - StartTime;
           alert(TotalTime + "ms")
       });
       
       var $recip = $("<div>");
       $("#clk2").click(function () {
           StartTime = new Date().getTime();
           var htm = $("<span>")
           for (var i=0; i<10000; i++) {
               htm = $("<span>").append(htm);
           }
           $recip.html(htm);
           EndTime = new Date().getTime();
           TotalTime = EndTime - StartTime;
           alert(TotalTime + "ms")
       });
    });

  [1]: http://jsfiddle.net/7ccgaLuk/4/
  [2]: http://jsfiddle.net/7ccgaLuk/3/

**Comment by dmethvin** [comment]
Seems like this is probably a dup of #2563?

**Comment by bracketsage** [comment]
Is it? The issue there seems to be based on Edge's performance regarding regular expression, as that user's ticket to the MS Edge team states

    The regular expression is:
     /<(?:script|style|link)/i;
    The following has similar performance
     /<(script|style|link)/i;
    The following can be used instead with no performance issue
    /<script|<style|<link)/i;

**Comment by bracketsage** [comment]
I tried making the changes to the regex in jQuery and unfortunately there was no change.

**Comment by GreenCoder64** [comment]
Will see if I can provide a fix for this.

**Comment by GreenCoder64** [comment]
With reference to the jsfiddle, IE seems to stall out in the for-loop where the append() function is called, even before exiting that loop to execute the html() function. When I looked at append();
```javascript
append: function() {
		return domManip( this, arguments, function( elem ) {
			if ( this.nodeType === 1 || this.nodeType === 11 || this.nodeType === 9 ) {
				var target = manipulationTarget( this, elem );
				target.appendChild( elem );
			}
		} );
	},
```
, the culprit behind the performance deficit seems to lie in either the domManip() function or the native appendChild() Javascript function. Fixing the domManip() function seems unlikely as it might affect other parts of the code which also use it, while fixing appendChild() is impossible. Perhaps the rest would like to chip in for a workaround.

**Comment by marcelammerlaan** [comment]
Seeing a similar performance issue regarding appendChild when adding lot's of them. 500 is ok, 2000 is low. 10.000 takes minutes. It's both IE and Edge that are pathetically slow in this case when compared to chrome and firefox.

**Comment by timmywil** [comment]
Is there something we can do in jQuery? If this is a performance issue with native `.appendChild`, there's nothing we can do but suggest building all the html first and doing one call to `innerHTML`.

**Comment by marcelammerlaan** [comment]
It's the native appendChild (was just chiming in on the report as that left
the possibility open that is was not appendChild()). So IE/Edge appendChild
is slow and we need hacks again to work around these kind of deficiencies.

**Comment by staabm** [comment]
@marcelammerlaan is this perf problem already reported to IE dev team?

**Comment by timmywil** [comment]
Closing this issue as there doesn't seem to be anything we can do in jQuery. Please report the problem to the Edge team. @jdalton

**Comment by jdalton** [comment]
Thanks for the ping, yep we're aware of the performance issue. \@patrickkettner

**Comment by marcelammerlaan** [comment]
Feedback left on uservoice. Cannot seem to connect to MS Connect.
