### ISSUE TITLE
Allow jQuery.ajax.settings.beforeSend to handle async promises

### ISSUE THREAD

**Issue by pensierinmusica** [jquery/jquery#2600]
Hi,

Currently [`jQuery.ajax.settings.beforeSend`](http://api.jquery.com/jquery.ajax/) only works with sync code. It would be nice if it could support async code too.

Let's look at a code example. Imagine I need the value of `foo` to be added to all jQuery Ajax request headers in my app.

```js
$.ajaxSetup({
  beforeSend: function (req) {
    if (localStorage.foo) {
      // Sync version - "foo" is locally available
      req.setRequestHeader('foo', localStorage.foo);
    } else {
      // Async version - "foo" needs to be fetched from an API server
      return $.get({
        url: '/foo',
        beforeSend: null
      })
        .done(function (data) {
          localStorage.foo = data;
          req.setRequestHeader('foo', data);
        });
    }
  }
});
```

As the web is moving more and more to async operations, imho it would make sense to support this pattern in jQuery. Thoughts?

Thanks!

**Comment by markelog** [comment]
See https://github.com/jquery/jquery/issues/2532#issuecomment-138980727

Sorry

**Comment by dmethvin** [comment]
This doesn't need to be done (and IMO shouldn't be done) *inside* `$.ajax()`, just create your memoizing function and call that. Using `$.ajaxSetup()` is definitely a bad idea unless you have written and understand every ajax call that will be made through these new semantics.

**Comment by pensierinmusica** [comment]
> unless you have written and understand every ajax call that will be made through these new semantics.

@dmethvin, yep, that's exactly the case at hand. Anyways, this is what I ended up doing, although I wish jQuery Ajax could provide a better / async way to handle these situations:

http://stackoverflow.com/questions/32643469/jquery-how-to-make-ajaxsend-wait-for-another-ajax-response-before-proceeding

Cheers
