### ISSUE TITLE
Fire global function after the response is ready, but before callback function fires

### ISSUE THREAD

**Issue by VitoOu** [jquery/jquery#2603]
For user authentication, while using AJAX to make a request for an resource which can only be accessed by authenticated user, we can not redirect the user browser to login page if we can not find the authentication for current user. 

If we add the checking in callback function of every AJAX calling, it is verbose. However, if we can have a global function setting like $.ajaxStart, it is very help. 

It is do very helpful because I have already added it to my local jQuery file call $beforeCallback. Then I can specify my business code in the $.beforeCallback function.

**Comment by timmywil** [comment]
I'm confused. What is the issue?

**Comment by VitoOu** [comment]
In jQuery, we already have these global methods: "ajaxStart", "ajaxStop", "ajaxComplete", "ajaxError",  "ajaxSuccess", "ajaxSend".

I suggest to add one more called "ajaxBeforeCallback".
Then the global methods will become: "ajaxStart", "ajaxStop", "ajaxComplete", "ajaxError", "ajaxBeforeCallback", "ajaxSuccess", "ajaxSend".

Then we can set the "ajaxBeforeCallback" function.

When jQuery received the response from server, call the $ajaxBeforeCallback function if exists. After that call the callback function which input by the jQuery AJAX function such jQuery.post(url,data,callback).


When there is a "ajaxBeforeCallback" function, we can specify a global function to check something such as login status code before the callback function. By doing this, we do not need to add the checking code in every jQuery AJAX call.

**Comment by timmywil** [comment]
I believe this is a use case that can already be handled with http://api.jquery.com/jQuery.ajaxPrefilter/. This function makes it easy to evaluate and/or modify every ajax request before it is sent.

**Comment by VitoOu** [comment]
I am not meaning BEFORE sent. I mean AFTER sent and HAVE RECEIVED response from server.

**Comment by dmethvin** [comment]
There is already the `statusCode` object for that, which you can set globally if you like.

**Comment by VitoOu** [comment]
But where can I put the handling logic? If I put the logic into every AJAX callback function, it costs a lot of time and copy-and-paste work.

**Comment by dmethvin** [comment]
As I mentioned, you can set the options globally. The drawback of that is not all `$.ajax` calls may be expecting the global behavior that you apply, or may override the global behavior. You have to be in complete control of the page/app and understand all the code being run if you want to make these kinds of changes. The folks on the forums or StackOverflow can probably help more with an implementation.

**Comment by timmywil** [comment]
Ok, the name "ajaxBeforeCallback" confused me. If what you want is an entry point for handling responses to all ajax requests, you can use `$.ajaxSetup` (http://jsfiddle.net/timmywil/s0ktdcb2/1/). However, we don't usually recommend that because it applies to ALL ajax requests, which can cause unexpected behavior.

**Comment by timmywil** [comment]
Blitz, Dave

**Comment by dmethvin** [comment]
:smile_cat:

**Comment by VitoOu** [comment]
OK. Let me put my code below.  I add some lines in the jQuery.done method to deal with the problem that if the AJAX send back a specified string, then I can redirect the user to login page if I set the $ajaxBeforeCallback method in the page onload method. 

Any suggestion to handle the redirection based on the logic in the server side after the AJAX calls in the whole website?

Code:
           

                // Callback for when everything is done
                function done(status, nativeStatusText, responses, headers) {
                var isSuccess, success, error, response, modified,
				statusText = nativeStatusText;
                .
                .
                .
               // Get response data
                if (responses) {
                    response = ajaxHandleResponses(s, jqXHR, responses);
                }
               // Convert no matter what (that way responseXXX fields are always set)
                response = ajaxConvert(s, response, jqXHR, isSuccess);

                // If successful, handle type chaining
                if (isSuccess) {
                    .
                    .
                    .
                }
                // Set data for the fake xhr object
                jqXHR.status = status;
                jqXHR.statusText = (nativeStatusText || statusText) + "";

//****************Customized Code Start***************************************************
                // Call a customerized function when received respones.
                var isContinue = true;
                if (fireGlobals) {
                    isContinue = globalEventContext.trigger("ajaxBeforeCallBack",
					[jqXHR, s, isSuccess ? success : error]);
                    if (typeof (isContinue) == "undefined") {
                        isContinue = true;
                    }
                }
//****************Customized Code End***************************************************


                if (isContinue) {
                    // Success/Error
                    if (isSuccess) {
                        deferred.resolveWith(callbackContext, [success, statusText, jqXHR]);
                    } else {
                        deferred.rejectWith(callbackContext, [jqXHR, statusText, error]);
                    }
                }

                // Status-dependent callbacks
                jqXHR.statusCode(statusCode);
                statusCode = undefined;

                if (fireGlobals) {
                    globalEventContext.trigger(isSuccess ? "ajaxSuccess" : "ajaxError",
					[jqXHR, s, isSuccess ? success : error]);
                }

                // Complete
                completeDeferred.fireWith(callbackContext, [jqXHR, statusText]);
               .
               .
               .

            return jqXHR;
        },

**Comment by dmethvin** [comment]
The bug tracker isn't a good place for this. Ask for help on the forum or StackOverflow.

**Comment by VitoOu** [comment]
I am not asking for help here. I just want to make a request to see whether my suggestion can be accepted as part of the jQuery library. If it is the wrong place for place a request for contribution, where can I put my request?

**Comment by timmywil** [comment]
@VitoOu Your request needs to be fleshed out more before submitting a feature request/bug fix to jQuery core, which is why I'd echo @dmethvin's recommendation to ask on the forums or StackOverflow. It is perfectly fitting to ask for suggestions on how to handle something there.
