### ISSUE TITLE
minified jquery-1.11.3.min.js has syntax error causing hangs in the isArraylike function

### ISSUE THREAD

**Issue by uptoeleven** [jquery/jquery#2606]
The function `function isArraylike( obj )` contains the following code:
`var length = "length" in obj && obj.length,
		type = jQuery.type( obj );`
The minification reduces it to:
`function r(a){var b="length"in a&&a.length,c=m.type(a);`
The Firefox Javascript interpreter is misreading this and throwing the following:

`TypeError: invalid 'in' operand a
	

...]"]=b.toLowerCase()});function r(a){var b="length"in a&&a.length,c=m.type(a);ret...`

Can someone put a space in there between "length" and `in`.

Thanks :)

**Comment by mzgol** [comment]
You're most likely invoking `jQuery.each` or `jQuery.map` on a string, `null` or `undefined` which is not supported in this version; this is a duplicate of #2267. If a space was causing change of behavior this would mean a serious bug in Firefox parser.

If you have a test case, please share but I'll close it for now. As you can see at http://output.jsbin.com/zaluru, just loading jQuery doesn't cause any errors in Firefox.

**Comment by uptoeleven** [comment]
please don't close - please mark as a dupe of #2242 - it's the "isArrayLike" function.
