### ISSUE TITLE
$(document).ready waits all images to be download when script included with async=true

### ISSUE THREAD

**Issue by yuxel** [jquery/jquery#2611]
When you have a document.ready binding on an async script, it waits for all images/resources to be downloaded. 

Detailed description is in this url -> http://test.yuxel.net/docready-en/

It doesn't act like this when its loaded without async.

**Comment by dmethvin** [comment]
When you declare a script as `async`, the browser waits until after the document is ready before it loads and/or runs the script. At that point the DOMContentLoaded event has already fired, so jQuery uses the fallback of a `load` event on `window`. 

In any case, I am pretty sure you're describing #2100 so I'll close this as a dup.

**Comment by yuxel** [comment]
yes, i think checking "interactive" state will also fix this bug. thanks
