### ISSUE TITLE
jQuery's .data() method does not play nicely with Angularjs

### ISSUE THREAD

**Issue by ziomio** [jquery/jquery#2614]
Problem described here:
http://stackoverflow.com/questions/32782685/why-jquery-data-method-does-not-fetch-updated-value

**Comment by dmethvin** [comment]
The [docs for `.data()`](http://api.jquery.com/data/#data-html5) cover how it works. It fetches `data-` attributes once, the first time you ask for them, then uses its internal data from then on. If you want to set/get *attributes*, use `.attr()`. If some other code you are depending on is using the API incorrectly, report it to them.
