### ISSUE TITLE
css(): getting opacity value just after setting results in invalid value for iframe in Firefox

### ISSUE THREAD

**Issue by pmstss** [jquery/jquery#2622]
**Test**: https://jsfiddle.net/t7xsbe6o/

**Expected result**: alert with message "PASSED" (e.g. in Chrome)
Firefox 40.0.3 result: "Expected opacity value is 0, but returned value is: 1"

**jQuery versions**: 2.1.4, 2.1.3 and all other available at jsfiddle - result is the same

**OS**: Windows 7 x64

**Test details:**
Firstly opacity of the `#testDiv` element is set to 0 (`$testDiv.css('opacity', 0)`). Then value is received as `$testDiv.css('opacity')` - and it's not 0, which was set.

Didn't  try with another properties; tried only with opacity.

**Workarounds**:
it works fine in the following tests:
1) setTimeout before get call: https://jsfiddle.net/t7xsbe6o/1/
2) jQuery free test: https://jsfiddle.net/vgpavw9g/
3) iframe free test: https://jsfiddle.net/67oos5aj/

**Comment by pmstss** [comment]
have just updated Firefox to version 41.0, result is the same

**Comment by dmethvin** [comment]
Same failed result in Firefox 43.0a2 as well. Historically, manipulating an iframe with an instance of jQuery not in that iframe has been dicey and we don't have any unit tests to ensure that it works in the only case where it can, e.g. same-origin. Can you report this to Mozilla and link to it here?

**Comment by pmstss** [comment]
Thanks for feedback! But what exactly to report to Mozilla? Mentioned jQuery free test (https://jsfiddle.net/vgpavw9g/) works. What are the differences between that test and what happened inside jQuery (was going to investigate it later, but may be you can clarify this at once)?

**Comment by dmethvin** [comment]
Okay, sorry, missed that. What we're doing is [this code](https://jsfiddle.net/vgpavw9g/1/) with `window` because of the multiple-browser bugs described in [this file](https://github.com/jquery/jquery/blob/99e8ff1baa7ae341e94bb89c3e84570c7c3ad9ea/src/css/var/getStyles.js). Maybe Firefox has fixed their original bug and caused this in the process?

**Comment by pmstss** [comment]
It works with `elem.ownerDocument.defaultView`, mentioned in getStyles.js - see https://jsfiddle.net/vgpavw9g/3/ - but not with `window` (parent), like in your https://jsfiddle.net/vgpavw9g/1/ test. Though in Chrome it works in both cases, which is strange for me.

**Comment by dmethvin** [comment]
The code comment says "FF meanwhile throws on frame elements through `defaultView.getComputedStyle`" but the support mention is FF 30 so it's possible the bug was fixed sometime between then and FF 40. Or, it might work with the data URI you have there but still throw with content fetched remotely.

**Comment by pmstss** [comment]
But isn't getting proper window object like proposed in #2623 is better?

**Comment by pmstss** [comment]
still have no explanation why it works with mentioned setTimeout workaround

**Comment by dmethvin** [comment]
Just a guess, but mostly likely the two windows are separate threads. When it's in the same window the action happens synchronously with respect to the code here, otherwise not.

**Comment by timmywil** [comment]
Per meeting, pushing to 3.0.1.

**Comment by mgol** [comment]
CC'ing Mozilla folks: @miketaylr @digitarald @bzbarsky @annevk @kentuckyfriedtakahe @cyberdees

**Comment by annevk** [comment]
@dbaron can maybe help here and @zcorpan (Opera, btw) from the standards side.

The problem seems to be that using `getComputedStyle()` on elements from a (same-origin) document in a nested browsing context does not give the expected results.

(Is the "layout trigger" from `getComputedStyle` applied to the window the method is on?)

**Comment by annevk** [comment]
So yeah, this is https://bugzilla.mozilla.org/show_bug.cgi?id=1109033 it seems. We invalidate the "wrong" window and the specification may or may not be bogus here.

**Comment by annevk** [comment]
(@dmethvin FWIW, separate threads is not possible here, since otherwise you wouldn't be able to cross them that easily with JavaScript. 😊)

**Comment by bzbarsky** [comment]
What @annevk said.  Style is recomputed lazily, flushed when queried in Gecko.  For `getComputedStyle` the flush is done on the document whose rules are being used.  How inline style works is inconsistent across browsers and across whether the element has a CSS box and the spec says something that doesn't necessarily match reality very well and it's all generally broken-by-design, of course.  The upshot is that using `getComputedStyle` from one window on an element in another window is not reliable in any way and is best avoided if you have the option of doing so.

**Comment by dmethvin** [comment]
> using getComputedStyle from one window on an element in another window is not reliable in any way and is best avoided if you have the option of doing so.

In this case, someone is attempting to use the jQuery API to control another frame, but jQuery itself doesn't have a way to make that consistent. So the "if you have the option" admonition needs to go to the end-user and this ticket would be closed "can't fix" on the jQuery side. Thoughts?

**Comment by bzbarsky** [comment]
jQuery could get the `element.ownerDocument.defaultView`, but of course that can be null for elements in XHR/DOMParser result documents and the like.  Really, any time someone asks for computed style on an element from one document using `getComputedStyle` from another document, unless they are saying "I don't really care what the computed style is" unless they know for a fact that there are no CSS rules anywhere matching that element, given the current state of UAs and the spec around this stuff.  :(

**Comment by dmethvin** [comment]
People are [constantly trying](https://bugs.jquery.com/search?q=cross-frame&go=&ticket=on) to use the jQuery in one frame to remote-control the document in another frame, despite all the problems it raises. I wish they would stop too.

There has never been a convenient place to document all the limits of cross-frame jQuery usage, both the ones imposed by browsers and the ones created by jQuery's implementation. Given that many of them are browser-specific (and cross-origin-specific for that matter) it seems like the best thing to do is continue to say "use at your own risk".
