### ISSUE TITLE
Attribute selector  : add OR operand when evaluating attribute values

### ISSUE THREAD

**Issue by Simmoniz** [jquery/jquery#2626]
$('.message[type=comment][type=link][type=alert]').perfomSomething();

Would look like :

$('.message[type=comment|link|alert').doSomething();

or

$('.message[type="comment"|"link"|"alert"').doSomething();

That would also be awesome working with other attribute filters as well :

$('.logs[data-id^=ERR_|WARN_|NOTICE_').doSomething();
$('.item[data-item-keyword*=promo|winter').doSomething();

**Comment by timmywil** [comment]
Thank you for the suggestion, but we won't be adding any more selector extensions to jQuery.
