### ISSUE TITLE
$.param(undefined) - throws Cannot read property 'jquery' of undefined

### ISSUE THREAD

**Issue by MarkPieszak** [jquery/jquery#2633]
Using jQuery 1.11.3 in Chrome, I'm not sure if this is a bug or a "nice to have feature", but if you try to do a `$.param()` on something `undefined` it throws the error:

```
Cannot read property 'jquery' of undefined
```

This mainly happens when let's say your passing parameters into a function and sometimes you don't want/need to pass any:

```
function Example (parametersToPass) {
    $.param( parametersToPass );
}


Example(); // <-- will error out.
```

The easiest fix is to simply:

```
$.param( parametersToPass || '' );
```

**Comment by mzgol** [comment]
`$.param` [expects an object](http://api.jquery.com/jQuery.param/) which `undefined` is not so passing `undefined` is unsupported. I'll treat it as a feature request then and leave open for now so that others can voice their opinions.

We've recently made `$.map` & `$.each` accept `undefined`/`null` input so I'm not opposed to treating them lightly here. We should determine, though, how many more methods would have to get similar treatment.

**Comment by mcpDESIGNS** [comment]
Thanks, yeah I figured it's more of a "nice to have" feature, just wanted to get it out there just incase no one ran into it!

**Comment by dmethvin** [comment]
This is really easy to fix on the caller's side though. If you know the value may be undefined, use the `|| ""` trick to define it as an empty string. If we put a bunch of this inside jQuery itself, there is a good chance it will mask errors and make the API harder for people to use.

**Comment by mzgol** [comment]
@dmethvin You could say the same about `$.map`/`$.each`, though and yet we accepted to treat `null` & `undefined` differently.

**Comment by dmethvin** [comment]
I agree. If those weren't regressions (in undocumented behavior) I don't think we would have changed them. Or at least I wouldn't have been in favor of it. :smile:

**Comment by jaubourg** [comment]
I'd tend to think consistency trumps history in the matter and I'd be in favor of gracefully handling the nul/undefined case.

**Comment by dmethvin** [comment]
So is the suggestion to handle just `$.param(undefined)` here, or are we creating a bigger ticket to review all the APIs and allow null/undefined where possible? Will we update all the docs as well? The APIs have been around for almost a decade without someone needing this so I'm concerned we're moving into yak-shaving territory with so much else we have to do.

**Comment by mzgol** [comment]
I'm fine with having this ticket just about handling
$.param(null|undefined). We can wait for bug reports before thinking about
other ones.

**Comment by mzgol** [comment]
Should we treat it as a breaking change or a new feature? In the latter case this could be moved to `3.1.0`; I'd rather not add new issues to the `3.0.0` milestone at this point.

**Comment by gibson042** [comment]
Definitely a feature, since we're talking about expanding the signature.

**Comment by mzgol** [comment]
OK, moved to 3.1.0.

**Comment by jtrumbull** [comment]
_(Hopefully not too far off topic)_ Since a change is being considered to handle `null` and `undefined`, would it be a bad idea to also handle a function argument? Similar to how object iterator invokes attributes that are functions.

```javascript
$.param(function(){
  var params = {};
  // Build params
  return params;
});
```

**Comment by dmethvin** [comment]
I'm not a fan of adding more behavior to this API (and documenting it, don't forget). Unfortunately I suppose we've already crossed the Rubicon by calling functions at all, which prevent `$.param()` from being used as a way to passively serialize an object the way you would with JSON. But I'm still not a fan!

**Comment by jtrumbull** [comment]
@dmethvin I moved this question to [separate issue](https://github.com/jquery/jquery/issues/3008).
