### ISSUE TITLE
e.target while event-delegation

### ISSUE THREAD

**Issue by staabm** [jquery/jquery#2635]
I am using selectors like 

```
$("body").on("click", "a", function(e) {
    e.preventDefault();
    $a = $(e.target);
    console.log($a);
});
```

with the impression that `e.target` should always be the element which was selected by the given selector (in this case `a`). Is it intended behaviour that a nested element can also be provided in `e.target`?

Am I supposed to use `closest()` which needs to repeat the selector in such cases to get the element I initally wanted to be selected?

see fiddle http://jsfiddle.net/qtkkjvj0/1/

**Comment by codeclown** [comment]
This probably is intended behaviour. It can be useful in some cases to know the exact target element.

You can use `$(this)` to get the link-element, [jsfiddle](http://jsfiddle.net/qtkkjvj0/2/).

**Comment by dmethvin** [comment]
Yes, `e.target` should be the actual target. If you need to know where the event was handled you can use `this` or `e.delegateTarget`.
