### ISSUE TITLE
parseXML does not work on IE8 when ActiveX is blocked (via GPO)

### ISSUE THREAD

**Issue by cnsgithub** [jquery/jquery#2637]
Hi, i have this issue, described here: 

https://github.com/primefaces/primefaces/issues/757#issuecomment-146084776

It shows the important part of the jQuery (1.x) code where i have the problem. Since Microsoft.XMLDOM is not available it fails to parse.

Is it possible to avoid using ActiveX here? Maybe by using something like this
https://github.com/jindw/xmldom

**Comment by mzgol** [comment]
Thanks for the report.

If the polyfill is included before jQuery then `jQuery.parseXML` [will pick it up](https://github.com/jquery/jquery/blob/81b6e46522d8c680f6c38d5e95c732b2b47130b9/src/ajax/parseXML.js#L12-L14); I assume you write from perspective from a user that goes to a site that relies on `jQuery.parseXML` with ActiveX disabled and see it fail.

If we included it by default that'd mean every jQuery user has to download a 1.7 KB (after minifying & gzipping) polyfill most of them don't need, that seems to be a lot, especially that I don't think there are a lot of users disabling ActiveX in IE8 (mostly enterprise, I guess?). I'll leave it open for others to comment but I don't think we should do it.

Note, that IE8 loses upstream support on Jan 12, 2016 so you should migrate to a newer browser ASAP, even if that means using IE11 in Enterprise Mode.

**Comment by cnsgithub** [comment]
Hi, yea, its enterprise, and unfortunately you cant just tell customers to upgrade. e.g in Embedded scenarios, XP is still used a lot.  

You said something about the 1.7KB download. Where do i get it and can i just add it to my deployment (in addition to jQuery 1.x so it can work with ActiveX disabled on IE8? 

Thanks

**Comment by mzgol** [comment]
I just looked at the project you linked to, i.e. [xmldom](https://github.com/jindw/xmldom). :) I haven't tested it but if it's spec-compliant you should be able to just `npm install` it and include `./node_modules/xmldom/dom-parser.js` before jQuery.

Please let us know if that works for you or if there are any problems with such an approach.

**Comment by cnsgithub** [comment]
Hi, ive tried to run xmldom, jQuery picks it up, but probably it contains some performance problems because the site becomes unresponsive right after clicking, so right now im looking for an alternative lib - but it seems there aren't too many to choose from.

**Comment by mzgol** [comment]
I'm going to close it since there's not much we can do and if you can find a working polyfill it should be picked up automatically.

Write a comment if you have a more specific problems (like a polyfill not being picked up etc.) and we'll reopen.
