### ISSUE TITLE
About the return value of `eq` method

### ISSUE THREAD

**Issue by poppinlp** [jquery/jquery#2639]
- run `eq` with argument `undefined` return empty array
- run `eq` with argument `null` return the first element

This problem caused by `+undefined` and `+null` have different behavior in javascript, and in `eq` function this happen:

```js
j = +i + ( i < 0 ? len : 0 ); // i is the argument
```

I don't know whether it's what you want, but maybe it's confused for users.

If this is not an issue, sry for bother, just ignore me.

**Comment by gibson042** [comment]
http://api.jquery.com/eq/ documents that the argument must be an integer. Behavior for other input is unconstrained.

**Comment by yairEO** [comment]
Can you be kind enough to change it so `eq(null)` will return an empty set? 
I find it highly helpful in many cases when the index is dynamic and the expected result for `null` is an empty set and not the first element. 

Thanks!

**Comment by gibson042** [comment]
@yairEO: `.eq( NaN )` is guaranteed to return an empty collection.

**Comment by yairEO** [comment]
@gibson042 - indeed it does, but tons of code is already written with variables set as `null` so checking everywhere and manually setting to `NaN` is a huge hassle. can't jQuery check `null` internally and return an empty set? is there a reason why not to do so? it makes sense, isn't it?

**Comment by dmethvin** [comment]
Hold on @yairEO, you're right that tons of code is already written, but changing the behavior could break that code. Although the actual behavior of `.eq(null)` or `.eq(undefined)`  isn't documented we've learned that changing even undocumented behavior is dangerous. So even if we were to change this it wouldn't happen until jQuery 4.0 at some later time. Given how much code is already written I don't see the benefit of changing this.

**Comment by yairEO** [comment]
@dmethvin - indeed it seems to be a messy business, when a change makes sense but can't be make because it will most likely cause a "Kim Kardashian" situation.  I will wrap it in a hack-function like suggested by mr. gibson042
