### ISSUE TITLE
$.wrap on an element created

### ISSUE THREAD

**Issue by fpereira1** [jquery/jquery#2640]
Hi,

I was wondering if this code snippet should work as expected:

    $('<a href="#" />').html('link').wrap('<li />');

At the moment it returns `<a>link</a>`, in other words the wrap doesn't apply.

**Comment by campersau** [comment]
[jQuery.wrap](http://api.jquery.com/wrap/) does not return the wrapped elements:

> This method returns the ***original*** set of elements for chaining purposes.

**Comment by mzgol** [comment]
Yup, it works as expected; see the console, the element is wrapped correctly: http://jsfiddle.net/f4eu531f/
