### ISSUE TITLE
TypeError : Cannot read property 'open' of undefined.

### ISSUE THREAD

**Issue by livesankp** [jquery/jquery#2642]
Recently i updated my node version to v4.1.2 from v0.12.

I also updated jsdom and jquery node_modules and after that my node program stopped working. I am getting type error "Cannot read property 'open' of undefined".

My jquery node_module is 2.1.4 and jsdom is 6.5.1. All latest available versions.

This is sample code from my program look like.

```js
//jsdom dependancy of jQuery
var jsdom = require('jsdom').jsdom, document = jsdom('test');
global.window = document.defaultView;
var $ = require('jquery');
$.support.cors = true;
//here mygeturl is asp.net web api get action method
$.get( 'mygeturl' ).done(function( data ) {
    console.log("Data Loaded: " + data);
})
.fail(function( xhr, textStatus, errorThrown ) {
    console.log(textStatus);
    console.log(errorThrown);          
});
```
Ajax call is failing now. It was working before upgrade but not working anymore due to error.

**Comment by mzgol** [comment]
What is `document.defaultView` in your code? I've always used the `jsdom.env` API to create a `window` instance, see the [promises_aplus_adapter.js](https://github.com/jquery/jquery/blob/9748e436ad80d6a2e1661ba4cf8d7391ed87c3ad/test/promises_aplus_adapter.js#L5-L11) file for an example.

**Comment by mzgol** [comment]
Ah, OK, this is because jQuery is using the global `XMLHttpRequest` object which is not present on a global in your case.

We have a more robust Node+jsdom testing in jQuery 3.0, we never assume browser globals to be available as globals but always take them from `window` so it should work better once it's released; I've confirmed your script works fine with the jQuery 3.0.0 alpha. For now you'll have to add one more line to your script just before requiring `jquery`:
```js
global.XMLHttpRequest = window.XMLHttpRequest;
```

**Comment by livesankp** [comment]
Yes. Its look like working now. But When i add var signalr = require('./jquery.signalR-2.2.0.js'); which is signalr javascript file. I am getting $ undefined error which says jQuery is not defined. Not sure why ?
Where as $.ajax worked though. Can't i load it like that way? It was working before.

**Comment by mzgol** [comment]
You need to report such issues to the plugin author. Note that some plugins might look for `$` and others for `jQuery` so you might need to set both.

**Comment by zagannath** [comment]
I have tried with  ` window.document.XMLHttpRequest = window.XMLHttpRequest` and I'm getting same error with version 3.0.0-beta1 please help me.
error - 
Object {readyState: 0, responseText: undefined, status: 0, statusText: "TypeError: Cannot read property 'open' of undefined"}
