### ISSUE TITLE
Consistent swarm failures 

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2644]
Umbrella ticket - 

* [x] `offset` module in Chrome 45 - #2590
* [x] `support` module in Safari 7 - https://github.com/jquery/jquery/issues/2609
* [x] `selector` module in `Edge` - Waiting for Sizzle update (? /cc @gibson042)
* [x] `ajax` module in IE8-9 - caused by https://github.com/jquery/jquery/commit/b078a62013782c7424a4a61a240c23c4c0b42614

**Comment by mzgol** [comment]
The Chrome one is tracked in #2590.

**Comment by markelog** [comment]
Updated, thanks

**Comment by mzgol** [comment]
#2609 is now resolved, we've dropped Safari 7.0 testing.

**Comment by mzgol** [comment]
I've changed the list to checkboxes, it's easier to set them as resolved then.

**Comment by markelog** [comment]
@mzgol cool

**Comment by dmethvin** [comment]
Closed since #2590 landed.
