### ISSUE TITLE
$().prop("tabIndex") returns wrong value (JSBin example included)

### ISSUE THREAD

**Issue by aschmalzhaf** [jquery/jquery#2647]
Hello, 

$(...).prop("tabIndex") behaves differently in JQuery 1.11.3 and 2.1.4 when Internet Explorer 11 is used. 
This is true at least for images (dom nodes of type <img></img>) that doesn't have an attribute "tabindex" explicitly given. 

Please see also the playground example here: 
http://jsbin.com/herehipoke/1/edit?html,output

When changing the URL of the loaded jQuery version, you can see that the tabIndex is different ("0" vs. "-1"). 

This is because of changes in attributes/porp.js file...
The propHook for tabIndex is different: 

The current code line (master and 2.1 stable) show the code of propHooks - tabIndex as follows:
```javascript
get: function( elem ) {
return elem.hasAttribute( "tabindex" ) || rfocusable.test( elem.nodeName ) || elem.href ?
elem.tabIndex : -1;
}
```

1.11.1 looks like that:
```javascript
get: function( elem ) {
var tabindex = jQuery.find.attr( elem, "tabindex" );
return tabindex ?
parseInt( tabindex, 10 ) :
rfocusable.test( elem.nodeName ) || rclickable.test( elem.nodeName ) && elem.href ? 0 : -1;
}
```

I've seen that jQuery Compat 3.0 Alpha uses the 1.11 logic again. Maybe it would make sense to move that kind of logic also into jQuery 2/3 as Internet Explorers are still supprted (at least the newer ones starting from 9 upwards). 

Best regards, 
Alexander

**Comment by mzgol** [comment]
Thanks for the report!

jQuery Compat 3.0 is the continuation of the jQuery 1.x line so nothing changed here; jQuery 3.0 is a continuation of the jQuery 2.x line and the code there is the same as in 2.x.

It does seem the `compat` code is still needed on the main branch as IE 11 is still broken here. Fortunately it seems fixed in Edge 12.

We'll most likely not fix it in jQuery 2.1.x (there are many bug fixes people would like to have fixed there, we can't backport all of them) but it'd be good to fix it for 3.0.0.

**Comment by mzgol** [comment]
@aschmalzhaf Would you like to take a shot at a PR? jQuery Compat 3.0 alpha code lies on the `compat` branch, jQuery 3.0 alpha code lies on `master`; you'd need to backport the `compat` code into the `master` branch; it's in the [src/attributes/prop.js](https://github.com/jquery/jquery/blob/67b76f5986a78d868553b9aec0d0192f5259a078/src/attributes/prop.js#L55-L64) file.

**Comment by markelog** [comment]
@mzgol why this was ported to `compat` if there is `master-only` label?

**Comment by markelog** [comment]
Label removed

**Comment by mgol** [comment]
Only a test was added, nothing needed to be fixed in `1.x`. I'm adding the label again.
