### ISSUE TITLE
$.each don't work for array stored in object property

### ISSUE THREAD

**Issue by tsarma** [jquery/jquery#2649]
This works
```javascript
var o = {myArray : {}};
  o.myArray['one'] = '1';
  o.myArray['two'] = '2';
  jQuery.each(o.myArray, function(k,v){ console.log(k, v);});
```

But this does not
```javascript
var o = {myArray : []};
  o.myArray['one'] = '1';
  o.myArray['two'] = '2';
  jQuery.each(o.myArray, function(k,v){ console.log(k, v);});
```

**Comment by risan** [comment]
@tsarma Please try this one:

```
var o = {myArray : []};
  o.myArray['one'] = '1';
  o.myArray['two'] = '2';
console.log(o);
```

You will simply get:
```
Object {myArray: Array[0]}
```

It is because javascript does not support associative array.

Hope this help.

**Comment by dmethvin** [comment]
Right, as @risan says your second case is an array with no array elements, just two extra properties that you added to it. jQuery sees that it is an array (it has a `length` property) but since no elements were added to the array the length is 0. That's working the way it should for a JavaScript array. Here is an example: http://jsfiddle.net/h3pe4mpd/

**Comment by tsarma** [comment]
Thank you @risan, @dmethvin for explainations regarding javascript not supporting associative array and in my 2nd case I've just added two extra properties to existing empty array object.

According to the docs on $.each(), it reads:
```code
A generic iterator function, which can be used to seamlessly iterate over both objects and arrays. 
``` 
So if I added 2 properties to empty object (in my case an array), why didn't $.each worked?

**Comment by dmethvin** [comment]
If your object is an `Array` its numeric properties will be enumerated up to `length`.  If it is a plain `Object` its enumerable properties (including prototype ones) will be enumerated. It can't be *both*.

Please follow up to a more general programming forum such as StackOverflow if you have other questions, thanks.
