### ISSUE TITLE
document.ready waits for images when loaded in async

### ISSUE THREAD

**Issue by aaani** [jquery/jquery#2651]
When I load jQuery and other dependent scripts in async, document.ready event in dependent scripts doesn't fire until the images have finished loading.

Here is a demo I setup: http://jsbin.com/sijawujunu/edit?html,console,output 
Ignore the verbose head tag, it has inline code for yepnope loader. Later in the script tag I have loaded scripts in async - http://pastebin.com/raw.php?i=4gqiQWSh has a document.ready callback it's fired 5 seconds after because there is an image in the body that takes 5 seconds to load.

However if I load jquery in sync in a script tag above dependents, document.ready doesn't wait for the image to download before firing.

I tested in 1.9, 1.11 and 2.1 and saw this issue in all.

**Comment by dmethvin** [comment]
This is a dup of #2100, but I noticed we don't have that ticket assigned to a milestone. @timmywil you're listed as the owner, should this go into 3.0.0?
