### ISSUE TITLE
$.map do evil concat if each item is translated to an array

### ISSUE THREAD

**Issue by wonderbeyond** [jquery/jquery#2652]
Take underscore's map function for comparison:

```javascript
$.map(['a', 'b', 'c'], function(item) {
    return [item, item.toUpperCase()];
});
// res: ["a", "A", "b", "B", "c", "C"]

_.map(['a', 'b', 'c'], function(item) {
    return [item, item.toUpperCase()];
});
// res: [["a","A"],["b","B"],["c","C"]]
```

You see, jQuery's `map` do an extra `reduce` operation(concat) in a `map` function.

**Comment by scottgonzalez** [comment]
As the [docs](http://api.jquery.com/jQuery.map/) say:

> A returned array will be flattened into the resulting array.
