### ISSUE TITLE
Provide a slim custom build removing ajax and effects on the cdn

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery#2653]

**Comment by timmywil** [comment]
Should we also use selector-native in this "slim" build?

**Comment by mzgol** [comment]
I don't think so, as long as it has incorrect scoping rules. Cutting functionality is fine but I'd rather not change it.

**Comment by dmethvin** [comment]
I'd go with Sizzle as well. It's easier to explain when a particular API has been left out versus when an API behaves differently in some cases. Also easier to debug!

**Comment by timmywil** [comment]
Fair enough.
