### ISSUE TITLE
JQuery 2.1.1 stops in IE8

### ISSUE THREAD

**Issue by mmasm** [jquery/jquery#2655]
URI: http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js
===stop at:
function(b){__return__ H||(H=n.Deferred(),"complete"

reason: object dont support property or method
in: jquery.min.js, line 2 symbol 29694

**Comment by timmywil** [comment]
Thanks for opening an issue. Please ask for support on the [forums](http://forum.jquery.com) or in the #jquery irc channel.

**Comment by mmasm** [comment]
Здравствуйте, Timmy Willison.

Вы писали 18 октября 2015 г., 0:44:17:

> Thanks for opening an issue. Please ask for support on the forumsor in the #jquery irc channel.
> —

I realy sorry for spend your time, I don't know than JQ 2.x hasn't
support IE<9. It was included in demo for module with "all browser"
mark.



-- 
С уважением,
 Victor M. Blood  (MASM)                     mailto:dev@masm.elcom.ru

                 FTN: 2:5024/3.1@Fidonet.org
                 System Administrator, winNT/BSD.
                 ICQ #3567656
