### ISSUE TITLE
Only change `%20` to `+` for application/x-www-form-urlencoded 

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#2658]
This resurrects [trac-3400](http://bugs.jquery.com/ticket/3400) which has the argument for the change. Currently we *always* change encoded spaces (`%20`) to the plus sign (`+`) in `jQuery.param()`. That is only correct behavior for posted form data, but not other cases. The conversion should be moved to `jQuery.ajax()` and only be done when the method is POST.

**Comment by jaubourg** [comment]
The conversion should be moved to `jQuery.ajax()` and only be done when the method ~~is POST~~ has a body.

**Comment by gibson042** [comment]
Note that [form submission](https://html.spec.whatwg.org/multipage/forms.html#form-submission-algorithm) only converts spaces to plus signs in [`application/x-www-form-urlencoded` encoding](https://html.spec.whatwg.org/multipage/forms.html#application/x-www-form-urlencoded-encoding-algorithm), which is used by HTTP(S) [GET](https://html.spec.whatwg.org/multipage/forms.html#submit-mutate-action) and [POST](https://html.spec.whatwg.org/multipage/forms.html#submit-body) logic. Note also that the [_de_-coding algorithm](https://html.spec.whatwg.org/multipage/forms.html#application/x-www-form-urlencoded-decoding-algorithm) explicitly replaces plus signs with spaces immediately before unescaping percent-escapes, which means that it treats `+` and `%20` **identically**. So if we can't limit conversion specifically to `application/x-www-form-urlencoded`, a percent-encoding `jQuery.param()` would be a _very_ reasonable approximation.

**Comment by dmethvin** [comment]
Now that you've done all the hard work and set me straight on the details I will grab this ticket. Thanks!
