### ISSUE TITLE
Make jQuery.isNumeric consistent

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery#2662]
Some people understand `isNumeric` as, "can I do math on this thing?" Others are asking, "Is this actually a number?" Now that we have no internal usage of `jQuery.isNumeric`, I think we can choose one or the other and update the documentation. Right now, it is inconsistent and a confusing confluence of the two.

**Comment by timmywil** [comment]
@dmethvin, @gibson042 and I propose allowing all input and returning true for strings and numbers – whether primitive or object – that can be numeric.

**Comment by timmywil** [comment]
```js
jQuery.isNumeric = function( input ) {
  var num,
    type = jQuery.type( input );
  return ( type === "number" || type === "string" ) && ( input - parseFloat( input ) + 1 ) >= 0;
};
```

**Comment by dmethvin** [comment]
I added the behavior change tag since there's that one strange case with a custom `.toString()` that we will no longer handle. It can just be mentioned in the release notes.
