### ISSUE TITLE
Please add releases to the repo

### ISSUE THREAD

**Issue by ketamin** [jquery/jquery#2666]
https://api.github.com/repos/jquery/jquery/releases returns an empty array

We use the check against the github api to retrieve information of the latest release in our build-environment, these checks won't make sence against tags only.

**Comment by scottgonzalez** [comment]
> these checks won't make sence against tags only.

Why not? What exactly are you trying to do that you can't do with the tags?

**Comment by ketamin** [comment]
If I check against https://api.github.com/repos/jquery/jquery/tags I get a list of tags, where there isn't any information provided, which one is the latest stable. Ok, it is, if I parse the name and hope, that '*alpha*' and '*beta*' means not stable. Even so, I have to trust the order given in json, which may could change any time.

It would be a lot easier and more secure to have releases, which provide additional information about release-date and so on.

Especially the release-date is one part, we use to show in our build-environment, how long we didn't change, since it is released.

I hope this is a valid and reasonable use-case.

**Comment by scottgonzalez** [comment]
> If I check against https://api.github.com/repos/jquery/jquery/tags I get a list of tags, where there isn't any information provided, which one is the latest stable.

The releases API doesn't actually tell you that either. Project maintainers cannot mark a release as the latest, so GitHub can only make a guess based purely on date. This means that a patch release in an older version that was released more recently than the current stable version will be marked latest. You should rely on version sorting instead.

> Ok, it is, if I parse the name and hope, that 'alpha' and 'beta' means not stable.

It's not a hope. It's a guarantee. See http://semver.org/. If there's a hyphen, you know it's a pre-release.

> Even so, I have to trust the order given in json, which may could change any time.

Nope. You shouldn't trust the order of any of these APIs. You need to sort based on the version number. Semver defines a clear specification for doing so.

> It would be a lot easier and more secure to have releases, which provide additional information about release-date and so on.

> Especially the release-date is one part, we use to show in our build-environment, how long we didn't change, since it is released.

That information can easily be found today by following the link provided in the `commit.url` value from the tag.

> I hope this is a valid and reasonable use-case.

It's certainly a reasonable use-case, but the information you want is already available today, for all releases of jQuery.

**Comment by timmywil** [comment]
Thank you @scottgonzalez for the explanation.
