### ISSUE TITLE
Iframes that refuse to display still get load event.

### ISSUE THREAD

**Issue by programmin1** [jquery/jquery#2672]
In latest Chrome or Firefox, and jQuery 1.11, you will see the iframe loaded here even though it was blocked:

```jQuery('<iframe src="http://www.google.com">').load(function() {console.log(this); console.log('load!');}).appendTo('body')```

I see "Refused to display 'https://www.google.com/?gws_rd=ssl' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.", yet just below it I see the iframe element, and "load!"

Is there a way we can get a notification or error message when iframe isn't actually loading, so the web-app may intelligently fallback to opening in a new window or setting the toplevel window url?

**Comment by dmethvin** [comment]
The console message says that the frame isn't displayed, but doesn't say it hasn't been loaded. In any case, the browser is firing a load event so we deliver it. It doesn't seem there's a problem in what jQuery is doing here, so it's more of a how-to question and you might be able to get a solution on StackOverflow.
