### ISSUE TITLE
Compat ajax tests are failing on Chrome 46

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#2673]
http://swarm.jquery.org/result/728285

The issue identified in http://bugs.jquery.com/ticket/14683#comment:12 has apparently been resolved as of Chrome 46, so passing invalid URLs to `jQuery.ajax` now creates a state where no exception is thrown and our callback will never be invoked.

**Comment by gibson042** [comment]
Closed by 0a6e1c4b191f177fce2dac5fd3a17b76f853fd26.

**Comment by mgol** [comment]
@gibson042 I see this didn't make it into `1.12.0`. Is it no longer needed? If so, a milestone should be cleared & the issue marked as `wontfix`.

**Comment by gibson042** [comment]
0a6e1c4b191f177fce2dac5fd3a17b76f853fd26 is a cleaner approach and should have made it in, but if we're not failing tests then I guess it's no big deal.

**Comment by mgol** [comment]
Yeah, tests are passing. I'm clearing the milestone then.
