### ISSUE TITLE
Load into a Context

### ISSUE THREAD

**Issue by tkellehe** [jquery/jquery#2674]
Hello,
I had written my own ajax function when learning about how ajax requests work. Obviously, it did not have all of the amazing features that jQuery.ajax provides. So, I have been using this one for a decent amount of my projects. There was a component that I enjoyed from the one I wrote that allowed me to load js into a particular context. This allowed me to write libraries that when loaded would attach to the scope they were ran in, making it very useful when using third party libraries. Would it be possible to add an option such that I can provide another option to eval the js in?

```
    var context = {...};
    $.ajax({evalContext:context});
    // or
    $.ajax({loadContext:context});
```
The js I used to accomplish this followed along the lines of:

```
    var result = function(code) {
         return eval(code);
    }.call(context, code);
```
I do not know how feasible it is for jQuery or if it is something that jQuery can do already. But, from the API documentation it says that jQuery evals into the global space.

**Comment by markelog** [comment]
Sorry, `ajax` interface is already bloated as is, so we are trying to restrain ourselves on adding more options to it, besides, as you pointed out, it could be easily done in the user land already

**Comment by tkellehe** [comment]
Good point. Just thought I might ask:)
Thanks!

**Comment by markelog** [comment]
Sure, It does not harm to ask :-)
