### ISSUE TITLE
Accept 202 HTTP Header

### ISSUE THREAD

**Issue by LKay** [jquery/jquery#2677]
Currently jQuery.ajax only supports HTTP status 204 or 304 to not contain response contend but there are few more HTTP codes which might or might not contain response body such as 202 Accept status. When no body is found for any other responses codes than 204 or 304 jQuery.ajax expects content body and throws an exception `SyntaxError: Unexpected end of input at Object.parse (native) at jQuery.parseJSON` while trying to parse undefined content data. 

I think additional HTTP status codes should be included as optionally having no response body or it should depend on `Content-Length` header and not try to parse data when header is set to `Content-Length: 0`.

**Comment by dmethvin** [comment]
Did the response headers say that the content-type was JSON? That should be the only way you get to that error. If that was the case, then the response was incorrect since the response body did not contain JSON.

**Comment by LKay** [comment]
The same ruiny happens for `application/json` and `text/plain` Content tyle header.

**Comment by dmethvin** [comment]
`$.ajax()` tries to interpret your plain text as JSON? The only time I can think of that happening is if you force it with `dataType: "json"` or an incorrect content type. Can you provide a test case?

**Comment by LKay** [comment]
I'm using Backbone in my case. I have a request for fetching some data and on the first call it put an server action to the queue which is process asynchronously and if not processed straight awaya I return `Accept 202` status with no body and send the request again in interval which eventually returns `Success 200` with response body. Backbone `fetch()` method wraps `Backbone.sync()` method which is wrapper to `$.ajax` method.

**Comment by mzgol** [comment]
@LKay From what I see the parameters are passed from `fetch` to `sync` and later to `$.ajax

**Comment by mzgol** [comment]
@LKay You should still extract the test case if you want us to do anything, we can't debug your whole Backbone app. Just put a breakpoint on the rogue `$.ajax` call, see what parameters are passed, see what headers you get in the reponse and then you'll have a test case we can look at.

**Comment by LKay** [comment]
I have some custom wrapper to make `$.ajax` Promise A+ compatible which shouldn't matter as I get the same result when I use jquery `done()` and `fail()` methods.

```javascript
class AjaxError extends Error {
    constructor (jqXHR, textStatus, errorThrown) {
        super();
        this.name = "AjaxError";
        this.message = textStatus;
        this.jqXHR = jqXHR;
        this.errorThrown = errorThrown;
    }
}

function decorateAsJQuery (promise) {
    promise.done = (fn) => {
        return decorateAsJQuery(promise.then(fn));
    };
    promise.fail = (fn) => {
        return decorateAsJQuery(promise.then(null, fn));
    };
    promise.complete = (fn) => {
        return decorateAsJQuery(promise.then(fn, fn));
    };
    return promise;
}

let jqAjax = $.ajax;
$.ajax = function ajax () {
    let jqPromise = jqAjax.apply(this, arguments);
    let promise = new Promise((resolve, reject) => {
        jqPromise.then((data) => {
            resolve(data);
        }, (jqXHR, textStatus, errorThrown) => {
            reject(new AjaxError(jqXHR, textStatus, errorThrown));
        });
    });
    return decorateAsJQuery(promise);
};
```

My code basic looks like:
```javascript
return model.fetch({ 
    data : { 
        url
    },
    headers : {
        Authorization : "Bearer " + Auth.token // This is some authorization token (not important in this case)
    }
})
    .then(data => {
        // do sth on success
    })
    .catch(e => {
        // do sth on error
        // gets called when 202 status with no body comes back
    });
```

My request headers are:
```
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,ja;q=0.6,pl;q=0.4
Authorization:Bearer ToKen
Connection:keep-alive
Cookie:_hp2_id.2741578191=1639183513929145.3140611316.1201817262; JSESSIONID=4BB74DEC6F5376456A42E63215541F1D
Host:test.com
Referer:https://test.com/data?url=http%3A%2F%2Fdic.nicovideo.jp%2Fa%2F%25E3%2582%25AD%25E3%2583%25BC
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
X-FirePHP-Version:0.0.6
X-Requested-With:XMLHttpRequest
```

And response headers:
```
Cache-Control:public, max-age=0, no-cache
Connection:keep-alive
Content-Length:0
Content-Type:text/plain;charset=UTF-8
Date:Wed, 28 Oct 2015 14:05:48 GMT
Server:nginx/1.8.0
Set-Cookie:JSESSIONID=772F182DB56DCF50234501BC800A6309; Path=/; Secure; HttpOnly
```

**Comment by dmethvin** [comment]
From the code snippet we still don't know what was passed to `$.ajax()`, which is what we need to know.

**Comment by LKay** [comment]
This was the object, sent to the `$.ajax` method. 
```
cache: false
dataType: "json"
emulateHTTP: false
emulateJSON: false
error: (xhr, textStatus, errorThrown)
headers: Object
parse: true
success: (resp)
type: "GET"
url: " https://test"
```

Looks like Backbone is forcefully setting `dataType: "json"` so I had to change that to `dataType: "json text"` and this seems to work.

**Comment by dmethvin** [comment]
Great, thanks for letting us know.
