### ISSUE TITLE
[New Feature] Attributes: provide a list of classes when given a selector

### ISSUE THREAD

**Issue by Burke9077** [jquery/jquery#2681]
This is my first attempt at contributing to jQuery, apologies if I've missed a step. I've read over the contribution guidelines and I'd like to open a discussion on adding a jQuery.classList() function in the attributes module.

I assumed jQuery had a function to list all classes when given a selector until I needed the functionality this morning and stumbled upon this stackoverflow post:

http://stackoverflow.com/questions/1227286/get-class-list-for-element-with-jquery

This functionality would be easy to build in, and I believe it would add value to the users who for whatever reason need to loop through classes held by an object. I have some questions about what would be the most appropriate output.

Given a selector the function should return an array of classes for the attribute(s). 

1. Should the output array have duplicates removed?

    My feeling is that this would be more valuable than having duplicates. If a user wants to know what classes fall under a selector I doubt they would be using it for duplicate entries.

    Alternatively, they could use $.unique() to remove duplicate entries.

2. Should the output be sorted in any way?

Does this functionality seem valuable?

**Comment by dmethvin** [comment]
Our wiki has a description of the process we use to decide whether to add a feature: https://github.com/jquery/jquery/wiki/Adding-new-features

With those criteria in mind I don't think we'd add a feature like this directly to jQuery core, but it would be easy to implement via a plugin. That way the people who want it can use it, but the people who don't will not need to pay for it with increased file size.
