### ISSUE TITLE
:text does not support email fields

### ISSUE THREAD

**Issue by pronebird** [jquery/jquery#2683]
jQuery('#customer_email').is(':text') -> FALSE

for input `type = "email"` fields.

Should return TRUE

Same for "tel" and other kinds of text fields.

```
> jQuery.fn.jquery
> "1.11.3" = $2
```

**Comment by scottgonzalez** [comment]
Because those are not text fields, they're email and telephone fields, respectively. From [the documentation](http://api.jquery.com/text-selector/):

> `$( ":text" )` allows us to select all <input type="text"> elements.

**Comment by pronebird** [comment]
Looks like text field to me:

<img width="290" alt="screenshot 2015-11-01 13 08 08" src="https://cloud.githubusercontent.com/assets/704044/10868789/9de1ae26-8099-11e5-84fe-1f9e598861f6.png">

**Comment by scottgonzalez** [comment]
The visual representation may be the same, but that does not mean they *ARE* the same. If they were, surely you wouldn't be using the new types.

**Comment by pronebird** [comment]
I use them pretty much because of mobile Safari which uses input type to present the right keyboard to the user. In all other aspects they are text fields. Text fields support keyboard input and display entered information. Text field that has support for masked input is still a text field regardless its capability to format user input. So the problem is when I need to make a live validation I have to manually pick up all kinds of text fields including tel and email. This is when :text should help me, but it does not, so I cannot use it and I have to have a trail of selectors to find all text fields.

**Comment by gibson042** [comment]
The DOM doesn't tell us if an input is presented for keyboard input, it just tells us the `type`. `:text` matches only inputs with `type` absent/empty or "text", and can't be changed because doing so would break backwards compatibility. If your desired selection is too cumbersome, however, you could define and use a custom selector like `:freetext`.
