### ISSUE TITLE
CommonJS: avoid a global with a custom window passed to the factory

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2688]
In a CommonJS scenario [these lines](https://github.com/jquery/jquery/blob/769446c69775f6c44e35cee1bcdeccafba51be7b/src/intro.js#L26-L32) may result in one of 2 things:

1. `window` & `window.document` exists => the exported thing is a jQuery using `window`, the global is not set.
2. otherwise, when a custom implementation is passed to the factory: `require( "jquery" )( window )` the `noGlobal` flag is not passed => global is created.

I thought for a moment we might want to pass along the second parameter but IMO we should just set it to true in such a case without asking for anything. After all, if someone invokes:
```js
var $ = require( "jquery" )( window );
```
then it's trivial to attach it to the `window` by ourselves if needed. The fact that we behave differently in CommonJS based on the initial setup worries me.

**Comment by timmywil** [comment]
I can provide some history here. Due to http://bugs.jquery.com/ticket/13566, we concluded that browser emulators in Node need the global set, because while Node has a CommonJS-like environment, the environment in a browser emulator usually does not, and unfortunately some of Node's module handling leaked into the emulators. The browserify case is already covered because a window with a document will be present. If the most common use case for requiring jQuery in Node is still to use jQuery within an emulator *and* if emulators still allow Node's module variables to leak in, then I think we should leave it the way it is.

**Comment by mzgol** [comment]
We have 3 scenarios:

1. There's no `module.exports` => nothing is exported, a global is set
2. There's `module.exports` & `window.document` exists => jQuery is exported, a global is *not* set
3. There's `module.exports` & `window.document` doesn't exist => a factory accepting `window` as a parameter is exported, running it *does set* the global

I don't like that (2) & (3) diverge. This means that if you do:
```js
var window = setUpAWindowEmulator();
var $ = require( "jquery" );
// $ is now the jQuery object because it picks up the window from the previous line:
```
a global is set but when you do:
```js
var factory = require( "jquery" );
// A factory got exported as there's no window in scope.
var window = setUpAWindowEmulator();
var $ = factory( window );
```
a global is not set. This just looks like magic. Note that both scenarios may happen when used with browser emulators in Node, I think they should behave in the same way.

**Comment by timmywil** [comment]
Not quite. In order to pass scenario 2, you'd have to do

```js
global.window = setUpAWindow();
var $ = require( "jquery" );
```

And I would hope no one does that in Node.

**Comment by timmywil** [comment]
I actually think we're good with what we have.

**Comment by timmywil** [comment]
Also, given how finicky changes to the intro have been in the past, I don't want to make any changes until someone opens a ticket.

**Comment by mzgol** [comment]
@timmywil 
> Not quite. In order to pass scenario 2, you'd have to do
> ```js
global.window = setUpAWindow();
var $ = require( "jquery" );
```

Not really. [This line](https://github.com/jquery/jquery/blob/769446c69775f6c44e35cee1bcdeccafba51be7b/src/intro.js#L38) means that if the `window` variable is present in the scope it's picked up as `global` in the setup function and obviously `window.document` exists there. And yes, I verified it in a console.

**Comment by mzgol** [comment]
I was looking at `intro.js` to understand what's happening because of the reported issue #2686 where a person would like to have the global exported in a Node-like environment. So someone did, in fact, open a ticket. And then I've noticed this inconsistency.

**Comment by timmywil** [comment]
> And yes, I verified it in a console.

In a console, any variables created will be global, but in Node, everything is wrapped in closures.

**Comment by mzgol** [comment]
> In a console, any variables created will be global

Not `const` or `let` variables. I did verify it's not a global; also, please read my explanation - all is needed is `window` in scope.

**Comment by timmywil** [comment]
> I was looking at intro.js to understand what's happening because of the reported issue #2686 where a person would like to have the global exported in a Node-like environment.

I don't think that's a valid use case. Something is off with the way that user is using electron, or with electron itself. The global should be necessary in that case.

**Comment by timmywil** [comment]
> I did verify it's not a global; also, please read my explanation - all is needed is window in scope.

I did read the explanation, but I still don't see how the window would make it into jQuery's scope.

**Comment by timmywil** [comment]
It would have to be on the `global` that jQuery uses for jQuery to find it. The only way that would be possible is if Node had some wonky prototypical behavior in the way they work with their global.

**Comment by timmywil** [comment]
Actually, now that I think about it, I suppose it would work if the require is executed in the scope of the module requiring it, but that seems like it would have adverse side effects.

**Comment by timmywil** [comment]
I keep forgetting we're looking for a `window` before using `this`, but I'm still surprised. If you're right, though, I can see the argument.

**Comment by timmywil** [comment]
I just confirmed that it does not work the way you suspect. It will not be able to access that `window`.

**Comment by timmywil** [comment]
Which makes sense when you think about it. Modules in Node should not be able to leak into other modules, even modules they require. Rule of module encapsulation.

**Comment by mzgol** [comment]
Yeah, that looks funky... I've created two scripts, `util.js`:
```js
module.exports = function () {
	return typeof foo !== 'undefined' ? 'foo in scope!' : 'foo not in scope!';
};
```
and `test.js`:
```js
var foo = 'bar';
var util = require('./util');
console.log(util());
```
And when running `node test.js` it prints `foo not in scope!` as you expected. I get weirder results directly from the REPL, though:
```
> const foo = 'bar'
undefined
> foo
'bar'
> global.foo
undefined
> var util = require('./util')
undefined
> util()
'foo in scope!'
```

Maybe REPL just has too much magic inside of it...

**Comment by timmywil** [comment]
> Maybe REPL just has too much magic inside of it...

Yea, perhaps.

**Comment by timmywil** [comment]
Wrong button.

**Comment by mzgol** [comment]
In that case, I see your reasoning - if `global.window` exists we have the right to assume we're in an emulated browser environment. But if we're in such an environment and `module.exports` leaks to it then we hit [this line](https://github.com/jquery/jquery/blob/769446c69775f6c44e35cee1bcdeccafba51be7b/src/intro.js#L26) which means the global is *not set* contrary to the wish to have it set in such environments; it doesn't reach [the latter line](https://github.com/jquery/jquery/blob/769446c69775f6c44e35cee1bcdeccafba51be7b/src/intro.js#L31) which sets the global.

Do I not understand what's happening there?

**Comment by mzgol** [comment]
Ah, OK, we always set `window.jQuery` and not `global.jQuery` so if we do:
```js
require( "jquery" )( emulatedWindow );
```
then `emulatedWindow.jQuery` is set, not `global.jQuery`. We only do not set it in browser emulators where `global === window` so setting it on `window` would mean setting it on `global`.

The only question that remains and this is the one related to what was reported in #2686 is whether skipping setting a global `jQuery` in Browserify was a mistake. Maybe it was as it increases the logical complexity of everything there but I agree changing that now may be risky and the scenario presented in #2686 is not typical... And every choice here will make someone unhappy.

**Comment by timmywil** [comment]
> The only question that remains and this is the one related to what was reported in #2686 is whether skipping setting a global jQuery in Browserify was a mistake.

We used to export the global for the browserify case and we got multiple complaints. I'm inclined to leave that as-is. The case in #2686 is equivocal at best, so I'm more inclined to trust the past reports that the global was unexpected in that environment.

**Comment by mzgol** [comment]
Sounds good to me. Closing it as wontfix then. If someone disagrees, comments welcome, we can always reopen.
