### ISSUE TITLE
Types does not explain how named functions can be passed

### ISSUE THREAD

**Issue by Chealer** [jquery/jquery#2704]
According to http://api.jquery.com/Types/ "this page documents virtual types like Selectors, enhanced pseudo-types like Events and all and everything you wanted to know about Functions. "

http://api.jquery.com/Types/#Function mentions that "A function in JavaScript can be either named or anonymous." and provides examples of declarations:
`function named() {}`
`var handler = function() {}`

There is however not a word or example about passing named functions, which is supported by numerous jQuery functions such as .change(). The following discussion explains:
http://stackoverflow.com/questions/7963609/how-can-i-name-and-call-a-jquery-function

Note that there is no explanation there of how to read the description of functions which take Function arguments. For example, https://api.jquery.com/change/ says:
handler
Type: Function( Event eventObject )

What "Function( foo bar )" means should be specified somewhere.

**Comment by timmywil** [comment]
Thanks for opening an issue, but this is the wrong repo. Please open an issue at https://github.com/jquery/api.jquery.com/issues for review.
