### ISSUE TITLE
jquery cousins method by making dom tree as a table

### ISSUE THREAD

**Issue by joomlaA1** [jquery/jquery#2705]
\<div\>
    \<p id="click"\>Hello\</span\>
\</div\>
\<div\>
    \<p id="find"\>World\>\</p\>
\</div\>

("#find").cousins() would give p with id="click"

coding by: DOM tree tranform to table then get cousin based on table

(by side by side analysis, ie O-X-O, where O are elements, x indicates space because they're cousins), could be?

**Comment by markelog** [comment]
You should do it as a plugin first, if there isn't one like that already. If it will get some momentum we can consider adding it to the core, since we are pretty conservative with the new API.

Nevertheless, thank you for reaching out!
