### ISSUE TITLE
Include instruction for developing with amd 

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2714]
AMD mode in qunit test suite could be extremely useful when developing jQuery, i.e. without waiting on the `grunt watch` results on direct `grunt build` command.

I think we should include this in our README

**Comment by timmywil** [comment]
Good idea. Could be something like...

> When developing jQuery, it can useful to run tests in AMD mode so the distribution files do not need to be rebuilt for the test suite to reflect recent changes. When viewing the QUnit test page, click "Load with AMD".
