### ISSUE TITLE
Do not overwrite $.fn

### ISSUE THREAD

**Issue by webloft** [jquery/jquery#2715]
Not sure if it is open yet, but could you please do not dumb overwrite $.fn ?
It is very bad if the jQuery object gets overwritten and all registered plugins are gone.

Some CMS plugins using jQuery and they do not use $.noConflict() and maybe overwriting each other. For example they include code from a CDN and all registered plugins before are gone forever.

It's the user/developer problem, if the jQuery-object gets overwritten with another version, but losing plugins is unacceptable.

**Comment by mzgol** [comment]
We're not overwriting `$.fn` anywhere so I'm not sure what you're asking for. If you include two versions of jQuery on a site then by default the second one will overwrite the `jQuery` & `$` global variables which you can restore to its previous state if you use `jQuery.noConflict()` and all the plugins from the previous version will be available again.

Please provide a more specific description about your problem.

**Comment by webloft** [comment]
And what about: `jQuery.fn = jQuery.prototype ...` in the constructor? As you said,all objects will be overwritten. This workaround `jQuery.noConflict()` used in a CMS can be very difficult if you should not touch the developers CMS extension, for example.

So. Why do you not store the plugins globally too and re-include these in the constructor?

**Comment by mzgol** [comment]
This is setting `jQuery.fn` on a currently defined `jQuery` instance. Before this line is executed `jQuery.fn` doesn't exist. We're not overwriting anything except `jQuery` & `$` which you can restore. `jQuery.fn` is defined only once & never overwritten.

**Comment by webloft** [comment]
I mean overwriting = re-include script by anything. If the object exists, it will be overwritten. Instead of overwriting, log a warning message if possible and re-include already registered plugins, otherwise the user has a problem and does not know why at all.

It's not about an explicit object. Just think that anybody could coincidentally end with 2 or more includes by automatic configuration or whatever. The result is jquery is working, using of plugins throw an " x is not a function"-error.

In case of overwrite the object will be saved in `_jQuery`. So far as well. Just re-include now the plugins and it will be fine.

`jQuery.noConflict()` should be an explicit workaround, jQuery should serve an automatic solution if it gets more the one time included.

**Comment by mzgol** [comment]
> I mean overwriting = re-include script by anything. If the object exists, it will be overwritten. Instead of overwriting, log a warning message if possible and re-include already registered plugins

That would be a big compatibility break; the idea is that including jQuery more than once should result in two pieces of independent code. Hence, we can't just re-include the plugins, it might break other code that does not want to share them.

> Just think that anybody could coincidentally end with 2 or more includes by automatic configuration or whatever.

If someone does that, it's better that they see an error when they try to use the plugin & notice they're using two jQuery copies instead of one. Silent errors are the worst; in most cases using multiple jQuery copies should be avoided.

**Comment by mzgol** [comment]
> Some CMS plugins using jQuery and they do not use $.noConflict() and maybe overwriting each other. For example they include code from a CDN and all registered plugins before are gone forever.

Is the issue that you include jQuery & some plugins and then a CMS includes its own jQuery copy without using `jQuery.noConflict()` and you lose access to your plugins? It seems weird to me that you'd include jQuery & plugins before the CMS code; if you do it after that then you'll have access to your jQuery copy.

**Comment by webloft** [comment]
The best scenario would be everybody uses  `jQuery.noConflict()` and uses there own variables. But thats not gonna be happen. Just one faulty extension could stop the site from working.

The issue is that TYPO3 for example can include scripts in head, footer and also customized in headdata via TypoScript. The ordering is neither perfect nor fail safe for scripts. And some developer thinks it is a good idea to include jQuery in the footer again, maybe after mine script. Of course I'm using `jQuery.noConflict()` since I know that. But a random user does not.

But I do not understand your point of view. Why it is a bad idea to re-include plugins as default? They could be overwritten by plugin includes after the jQuery-Re-Include. And before that include, it doesn't matter?

**Comment by mzgol** [comment]
> Why it is a bad idea to re-include plugins as default?

Multiple jQueries on a site are usually a result of a couple of independent code parts that each uses its own jQuery and plugins. A particular plugin might not be compatible with a jQuery version used by another snippet, there might be logic in place that checks for a particular plugin and expects it to not be there etc. It's easier to reason about it if you can be sure no external code will attach some plugins for you.

> The issue is that TYPO3 for example can include scripts in head, footer and also customized in headdata via TypoScript. The ordering is neither perfect nor fail safe for scripts.

@fnagel Are you familiar with TYPO3? Would you be able to reply to that?

**Comment by scottgonzalez** [comment]
> But I do not understand your point of view. Why it is a bad idea to re-include plugins as default?

How about the fact that they could be completely broken with the newly loaded version of jQuery?

The scenario you've described is a really bad practice. Just because something bad happens in user land doesn't mean that something equally bad should happen inside jQuery. The current logic for multiple versions of jQuery is sound and is highly unlikely to ever change.

**Comment by timmywil** [comment]
Agreed. Feel free to discussion, but it's unlikely we'd make any changes here.
