### ISSUE TITLE
Android 2.3 basic tests time out

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2717]
Android 2.3 basic tests on master time out: http://swarm.jquery.org/job/1684. OTH, the jQuery 1.12/2.2 tests are mostly working: http://swarm.jquery.org/job/1685. This is even though we now no longer load other test files than `basic.js` when testing the `basic` module. Perhaps there's a problem with source.

When I joined the swarm with a local emulator running on x86 instead of the ARM emulator, it passed: http://swarm.jquery.org/job/1654. But that doesn't help maintaining it.

There are lots of problems with Android 2.3 testing and apparently even just running basic tests is problematic. Restarting those jobs doesn't help, they just don't work with the BrowserStack Android 2.3 version. I'd prefer to just drop Android 2.3 completely in jQuery 3.0.0 but since no one else except @markelog thinks the same (well, except Mobile folks that are dropping it completely; am I right, @arschmitz?), how about we remove it from the periodic run and just add a note to the release process at https://github.com/jquery/jquery/wiki/Release-process that before a release one has to fire up a local Android 2.3 emulator & run basic tests? The TestSwarm job is useless anyway as it stands.

**Comment by dmethvin** [comment]
Running it before a release is fine with me. It has gotten to the point where those CI tests are wrong so often that they are useless.

**Comment by timmywil** [comment]
+1

**Comment by mzgol** [comment]
The Basic test suite was disabled for master and I added info about manual Android 2.3 testing to [the wiki](https://github.com/jquery/jquery/wiki/Release-process). This is done, I'm closing the bug.

@timmywil We're not assigning milestones for bugs like that, are we? Without the milestone they're indistinguishable from invalid bugs that were closed but maybe that's not a big problem?

**Comment by timmywil** [comment]
Yea, these kinds of tickets don't quite fit into a milestone, but I'd probably set it anyway, just to enter it into the archive as something we did when working on 3.0.
