### ISSUE TITLE
Package Distribution Ignores Build Dependencies (.npmignore)

### ISSUE THREAD

**Issue by jbottigliero** [jquery/jquery#2727]
This may be an edge case issue, or a even non-issue, but I'd love to hear your thoughts!

Required build dependencies are being ignored based on the `.npmignore` file. The following commits contribute to this change: 35f8e15fd73256ec02397d7bf93893e38afc9bc9 and b04b3861802606a114c936e753c0f20da6e8b236.

Currently, I'm relying on the `npm` published package for a module. As it stands right now, the distributed package cannot be re-built (module exclusion) as the various required files are being ignored – I'm looking to make `grunt custom:-deprecated,-effects,...` a `postinstall` hook. 

It seems the current solution would be to include `jquery` as a `git submodule` and building, which _works_, it just feels a little dirty (...blame the package managers for this one. :wink:)

It's also worth pointing out that I'm bundling for the browser – so the exclusion of modules/file size has some effect.

Thanks!

**Comment by timmywil** [comment]
Correct. The src folder is included in the distribution not for building, but direct usage through AMD. To build jQuery, the git repo itself is required. Your solution combining a postinstall script with a git submodule isn't bad.

**Comment by dmethvin** [comment]
There was also some discussion in #1526 a while back regarding what we put into the tag. There is a tension between people who just want one file (the jquery.js or jquery.min.js file) and those who want to  do custom builds and possibly even unit test the result. If you need to do the latter the best approach is to check out the tag with all the files.
