### ISSUE TITLE
.attr() getter doesn't accept some characters in Firefox

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2730]
With the following HTML body:
```html
<h1 Ω="omega">Hello!</h1>
```
and the following code:
```js
var h1 = $('h1');
console.log(h1.attr('Ω'));
console.log(h1[0].getAttribute('Ω'));
```
the `h1.attr('Ω')` part prints `"omega"` in Chrome but undefined in Firefox. The `getAttribute` part prints `"omega"` in both browsers.

This has hit AngularJS, see https://github.com/angular/angular.js/pull/13318#issuecomment-157812532 for more info.

EDIT: @dmethvin says it works in IE 11.

**Comment by mzgol** [comment]
It worked in 1.6.4, hasn't been working since 1.7.0.

**Comment by mzgol** [comment]
Test case: http://jsfiddle.net/cz57ey00/

**Comment by mzgol** [comment]
@dmethvin discovered the culprit is `String#toLowerCase` which changes `Ω` to `ω`. `.getAttribute('ω')` works in Chrome but not in Firefox.

What does the spec say?

**Comment by mzgol** [comment]
So, the spec says that:

1. `getAttribute(name)` for non-`null` values returns an attribute value for name `name`: https://dom.spec.whatwg.org/#dom-element-getattribute
2. When getting the element name the `name` parameter is converted to ASCII lowercase: https://dom.spec.whatwg.org/#concept-element-attributes-get-by-name
3. Converting to ASCII lowercase means changing only the values between U+0041 to U+005A which is `A-Z`.

This means Firefox is right and we're wrong but... every other browser is wrong as well - Chrome 46, IE 9-11, Safari 9 and even the old Opera Presto 12.16 returns the attribute value for `getAttribute('ω')`.

@bzbarsky, should the spec be changed considering Firefox is the exception here?

**Comment by mzgol** [comment]
As for jQuery itself, @dmethvin suggested we could get rid of the [`.toLowerCase()` part](https://github.com/jquery/jquery/blob/47ccf3daadc4b312f850502300129952e70f9d9d/src/attributes/attr.js#L42) in 3.0.0 if it was only needed for old IE.

If it doesn't cause major problems for IE 6-8 we could try to use our own `toLowerCase` in 1.12 that would only transform `A-Z` to `a-z`.

**Comment by mzgol** [comment]
I'll set a milestone to 3.0.1 for now but if we could get to it before that'd be great.

**Comment by bzbarsky** [comment]
@mzgol Browsers used to do weird and inconsistent case folding here, that didn't all agree with each other.  The current spec text was a compromise everyone agreed on as something that was web-compatible, faster than the weirdness browsers were doing, and doesn't have weirdness like getAttribute doing case-folding for U+03C9/U+03A9 but not for U+0049/U+0131 or U+0130/U+0069 (check it in Chrome; it's not terribly consistent about which cases it does case-folding in).

So the spec we have now is the currently on compromise; browsers just need to actually implement what they all decided to implement.

**Comment by timmywil** [comment]
If all of our supported browsers take care of lowercasing themselves, we may as well remove our call to `.toLowerCase()` and let the browsers work this out.

**Comment by timmywil** [comment]
@bzbarsky Just out of curiosity, should the name `"AΩZ"` be converted to `"aΩz"` or stay the same since it contains at least one character that is not in the range A-Z?

**Comment by bzbarsky** [comment]
@timmywil It gets converted to `"aΩz"`.

**Comment by markelog** [comment]
> As for jQuery itself, @dmethvin suggested we could get rid of the .toLowerCase() part in 3.0.0 if it was only needed for old IE.

Is there more info about that? Link to the ticket for example?

**Comment by mzgol** [comment]
There is no additional info, we talked on IRC. But every conclusion is here.

-- 
Michał Gołębiowski

**Comment by dmethvin** [comment]
One from the past is http://bugs.jquery.com/ticket/11166 , @timmywil said there that we always use getAttributeNode but it looks like toLowerCase was added in ce8d9c0ca59a8f03e119c80ed29c7dbc65efdd85 to fix http://bugs.jquery.com/ticket/10429 .

**Comment by markelog** [comment]
Thank you @dmethvin, i'd say it seems easy enough to include to 3.0.0? If there is any complications we could table it though

**Comment by dmethvin** [comment]
This may just be a case of removing the `.toLowerCase()` from the code since we already have tests. The text in the unit tests made me laugh because it reminded me of this ticket. http://bugs.jquery.com/ticket/9619

**Comment by mzgol** [comment]
Yeah, should be easy in 3.0. We might try to fix it in 1.12/2.2 as well
although there it might require our own internal toASCIILowerCase function
that would only convert ASCII letters.

-- 
Michał Gołębiowski

**Comment by timmywil** [comment]
> We might try to fix it in 1.12/2.2 as well

I wouldn't worry about 1.12/2.2. It's been like that for a long time.

**Comment by markelog** [comment]
> 1.12

Still supporting oldIE

**Comment by timmywil** [comment]
> Still supporting oldIE

Sure, but this is an edge case that hasn't come up until now. `toLowerCase()` is still good for ascii names.

**Comment by markelog** [comment]
I'm meant it wouldn't be as easy to implement for oldIE, since for 3.0, we just need to remove one line

**Comment by dmethvin** [comment]
The way to put this into 1.12 would be to add a custom regex that only lowercased A-Z instead of `.toLowerCase()`. As long as it doesn't break anything I'm okay with that. Since the Angular folks are seeing this bug we may want to do it for them.

**Comment by markelog** [comment]
Angular folks i.e. @mzgol wanted to do it in 3.0.1 :-)

**Comment by markelog** [comment]
If that is easy like that, i'm good either way

**Comment by mzgol** [comment]
Yeah, I wanted `3.0.1` but it should be simple to do for `3.0.0`, I can do it before Monday. I wanted to try whether it'd be easy to fix for `1.12` but if the simple solution of just lowercasing `A-Z` would cause any problems for old IE then I wouldn't bother with it. But I definitely want to try.

We first need to get `1.12-stable` in the proper shape, though. :)

**Comment by timmywil** [comment]
@mzgol If you can't get to it, my backlog is empty.

**Comment by mzgol** [comment]
@timmywil If you have time before Sunday, go for it.

**Comment by TrejGun** [comment]
is `toLocaleLowerCase` same bad as `toLowerCase`?

**Comment by gibson042** [comment]
At least as bad for this application, and sometimes worse.

**Comment by mzgol** [comment]
@timmywil I won't have time for it before Thursday. Want to grab it?

**Comment by timmywil** [comment]
@mzgol Sure.

**Comment by Manoj-Roy** [comment]
Keep update your browser.

**Comment by mgol** [comment]
This has been backported to `1.12.0` & `2.2.0` so I changed the milestone (it used to say `3.0.0`).
