### ISSUE TITLE
selector with  two backslashes not working 

### ISSUE THREAD

**Issue by dassio** [jquery/jquery#2731]
form the documentation:
To use any of the meta-characters ( such as  !"#$%&'()*+,./:;<=>?@[\]^`{|}~ ) as a literal part of a name, it must be escaped with with two backslashes: \\

but i have this issue,two backslash not working:
`> msg = {"percentage": "100%", "video_id": "XMTM2NDQwNTI5Mg=="}
< {percentage: "100%", video_id: "XMTM2NDQwNTI5Mg=="} = $1
> $("#"+msg.video_id.replace(/[!"#$%&'()*+,.\/:;<=>?@[\\\]^`{|}~]/g, "\\\\$&"))
< Error: Syntax error, unrecognized expression: #XMTM2NDQwNTI5Mg\\=\\=
> $("#"+msg.video_id.replace(/[!"#$%&'()*+,.\/:;<=>?@[\\\]^`{|}~]/g, "\\$&"))
< m [<div id="XMTM2NDQwNTI5Mg==">] (1) = $2`

**Comment by dmethvin** [comment]
This doesn't sound like a bug report. Can you ask for help on the jQuery forum or StackOverflow? Thanks.
