### ISSUE TITLE
browserify-ed jQuery is exposing a buggy global $ object

### ISSUE THREAD

**Issue by hyperknot** [jquery/jquery#2733]
There are numerous guides on the internet that with recent versions of jQuery you can just use it in browserify-ed project like:

```
var $ = require('jquery');
```

However while this works within the bundled js environment, it produces a really weird bug:

1. It exposes a global $ function,
2. That $ function is buggy / non-functional.

**Demo**

main.js
```
var $ = require('jquery');

window.$fix = $;
```

command line (no package.json)
```
browserify main.js -o bundle.js
```

html
```
<!doctype html>
<html>

<head>
</head>

<body>
    <p>1</p>
    <p>2</p>
    <script src="bundle.js"></script>
</body>

</html>
```

Now inside a browser (latest Chrome), if you do `$('p')`, it'll return: 
```
<p>1</p>
```

You can get the real results by the using the manually attached version: `$fix('p')`:
```
[<p>​1​</p>​, <p>​2​</p>​]
```

I believe this bug might cause further bugs in plugins and anything which auto-detects jQuery.

**Comment by gkatsev** [comment]
A you running the `$('p')` in the console? because the console API has `$` and `$$` functions.
The console API defines `$` as `document.querySelector` and `$$` as `document.querySelectorAll`

**Comment by mzgol** [comment]
Yeah, what does `$ + ''` return?

**Comment by hyperknot** [comment]
Sorry, I've read about it and it seems that $ and $$ got introduced a few years ago in Chrome and Firefox, and they decided to make it work almost like jQuery's selector. Really confusing naming and functionality I'd guess. 

So it has nothing to do with either jQuery nor browserify.

@gkatsev, yes, from the browser console.

@mzgol, it returns `function $(selector, [startNode]) { [Command Line API] }`

**Comment by mzgol** [comment]
Yep, that explains everything; thanks for following!
