### ISSUE TITLE
Uncaught TypeError . This.get ( ... ) is not a function querySelectorAll from find function

### ISSUE THREAD

**Issue by winoth2004** [jquery/jquery#2738]
Getting an error as, Uncaught TypeError . This.get ( ... ) is not a function querySelectorAll from find function. 

This is an error message when trying to loop for..of with an non-iterator property why its an error i'm getting from jQuery find function

**Comment by mzgol** [comment]
Please provide a test case, we can't know anything about the problem if there's no code to look at.

**Comment by winoth2004** [comment]
I'm supporting a web application system, From the log report i get the stack trace for error is as follows

TypeError: this.get(...).querySelectorAll is not a function
at Object.u.fn.find (<anonymous>:8:1683)
at HTMLDocument.<anonymous> (<anonymous>:46:16)
at HTMLDocument.<anonymous> (<anonymous>:8:373)
at n.fn.extend.html

jQuery version used was 1.7

**Comment by dmethvin** [comment]
You should debug this, if there is a jQuery bug then you can report that.

**Comment by pifantastic** [comment]
@winoth2004 I've also seen these rather mysterious errors in our error reporting system. Any luck debugging them? I'm suspicious it may be browser extension shenanigans.

**Comment by enjikaka** [comment]
```
Object.t.location.href.match.t.top.t.self.o.fn.find@<anonymous>:1:1813
HTMLDocument.<anonymous>@<anonymous>:1:6020
HTMLDocument.<anonymous>@<anonymous>:1:503
```

We're getting this is our error reporting system. Seems to stem from jQuerys .find() function.
CC: @pifantastic @dmethvin @mgol @winoth2004

**Comment by dmethvin** [comment]
Yes but there is no indication (yet) that it's being caused by jQuery code, or if it is that it's present in the latest version of jQuery. In fact @winoth2004 reports the stack trace of `this.get(...).querySelectorAll` and there is no such usage inside jQuery itself. Go search your plugins and code for usages of `this.get` and see if any call `querySelectorAll` immediately afterwards.

Plus, he reported using *jQuery 1.7* which was released *5 years ago*. You need to debug this further to show that it's a bug inside the current version of jQuery itself and not just a misuse of the API. We can't even help you do that given the meager amount of information provided.

**Comment by enjikaka** [comment]
@dmethvin We have no querySelectorAll afterwards any .get() method in our code what I could find. The only .get I found associated selecting elements where in jquery.js:

```
jQuery.merge( this.get(), jQuery( selector, context ) )
```

**Comment by dmethvin** [comment]
Then it is most likely jQuery being used in a browser extension. As you've found, there's no use of it inside jQuery proper that could cause that stack.

**Comment by enjikaka** [comment]
Ok. We suspected an extension too. Thanks for you help.

**Comment by dmethvin** [comment]
If you can find a system where it fails, take a look in the extensions folder and search for `.get(0).querySelectorAll` in all subfolders. Most likely it's `.get(0)` based on the direct use of `querySelectorAll` afterwards.

**Comment by lukeapage** [comment]
We are getting this exact error in jQuery 2.1.3. 

Our full stack is
```
Error: this.get(...).querySelectorAll is not a function:
"TypeError: this.get(...).querySelectorAll is not a function\n    
at Object.a.fn.find (<anonymous>:1:1697)\n    
at HTMLDocument.<anonymous> (<anonymous>:1:9084)\n    
at HTMLDocument.<anonymous> (<anonymous>:1:387)\n
at HTMLParagraphElement.<anonymous> (compiled.js:124:4437)\n    
 - e.textContent
at Function.J.extend.each (compiled.js:122:27052)\n    
at J.fn.J.each (compiled.js:122:25026)\n    
at null.<anonymous> (compiled.js:124:4344)\n    
   - manipulation.js line 312
at J.access (compiled.js:123:21444)\n    
   - access.js line 7
at J.fn.extend.text (compiled.js:124:4280)\n    
   - manipulation.js line 310
at t.i.Controller.sub.updateColumnText (compiled.js:33:12388)",
```
the last thing within our code (and not <anonymous>), which happens to be jquery is is
```
this.textContent=e
```

So, its kind of like either the (a) browser (b) extension (c) other piece of code?? is running something when you set textContent and thats the bit causing `Error: this.get(...).querySelectorAll is not a function` ?

I cannot see anything suggesting it is jquery, I think the most likely is that it is some extension that is breaking the DOM :(

We are seeing the problem in chrome on windows/mac.

@winoth2004 what browser did you see it in?

**Comment by acasademont** [comment]
same here, this can't be jquery as we only see this error in chrome, it must be a rogue extension...the question is which one and how can we avoid this nasty error :(

**Comment by dmethvin** [comment]
I've already described [above](https://github.com/jquery/jquery/issues/2738#issuecomment-169754320) how to diagnose it. Often the error will include a path that points to the extension, e.g. [this one](https://twitter.com/davemethvin/status/700366296156917760).
