### ISSUE TITLE
The default - id selector (#) does`t work as expected in jquery 2.1.3 and 2.1.4.

### ISSUE THREAD

**Issue by Bjego** [jquery/jquery#2739]
The default - id selector (#) does`t work as expected in jquery 2.1.3 and 2.1.4.

Please fix this.

Here is the sample code: https://jsfiddle.net/wko6eg2v/1/

Code:
for(var i = 0; i<100;i++)
{
var dynamicContent = jQuery('

', {
id: 'dynamic[' + i+']' ,
});
dynamicContent.text(i);
$('body').append(dynamicContent);
}
alert("Jquery select: " + $('#dynamic[99]').text());
var myelement = document.getElementById("dynamic[99]");
alert("Default: "+$(myelement).text());

**Comment by mzgol** [comment]
You need to escape special characters in identifiers: https://jsfiddle.net/wko6eg2v/2/.
