### ISSUE TITLE
elem.find(">selector") adds id="null" to elem

### ISSUE THREAD

**Issue by evgeniymweb100** [jquery/jquery#2740]
elem.find(">selector") adds id="null" to elem
Reproduce steps:

- open FireFox, go to http://jquery.com
- open console in developer tools
- execute: $("html").find(">.zzz")
- go to inspector, look at root "html" node. It has id="null" attribute

In chrome id="null" is absent, but in developer tools "html" node blinks to indicate changes.

**Comment by mzgol** [comment]
Duplicate of #2620.
