### ISSUE TITLE
.html doesn't return dynamically created markup as expected

### ISSUE THREAD

**Issue by joshsalverda** [jquery/jquery#2742]
This seems like unexpected behaviour to me, but let me know if I'm mistaken:

http://jsfiddle.net/0986gj4h/

I traced it to a couple different things: The dynamically created markup ends up being an array of elements, then in .html `this[0]` is referenced, which only refers to the first element in the array, hence the inner html for only the first element is returned.

Seems like there are a few ways to fix this: check if this.length > 0 and then either return the outer html for each element in the array (not very nice), or create a fake element (div for example) append `this` to the element and return that inner html (nicer, but still not that great), or possibly something else I'm not thinking of? I'm not too familiar with all the code around this, so I'm sure I'm missing some edge case scenario.

I'm able to workaround this issue through other means, just thought it seemed odd.

**Comment by dmethvin** [comment]
The documentation is pretty clear on this though, it's the first element.

**Comment by joshsalverda** [comment]
Oh ok, good to know, didn't realize matched element = created element... my bad.
