### ISSUE TITLE
TypeError: n.easing[this.easing] is not a function

### ISSUE THREAD

**Issue by DesignPixelZ** [jquery/jquery#2748]
The code : 
`$(".black-out").fadeOut(function () {
            $(this).remove();
        }, 100);`

result : 
![buggy](https://cloud.githubusercontent.com/assets/11901639/11476653/9edf08dc-978c-11e5-929f-cca3beb396ef.gif)

I'm still learning jQuery and I don't know much, but, I believe this is a bug.

**Comment by timmywil** [comment]
Thanks for opening an issue. Please provide a reduced test case from http://jsbin.com or http://jsfiddle.net.

**Comment by DesignPixelZ** [comment]
@timmywil : http://jsbin.com/qexifariwu/edit?css,js,output

**Comment by timmywil** [comment]
@DesignPixelZ Ah, the argument order was swapped: http://jsbin.com/tosawa/1/edit?js,output

**Comment by Manoj-Roy** [comment]
$(".black-out").fadeOut(), 100;

Tri it...
