### ISSUE TITLE
outerWidth() documentation possibly incorrect

### ISSUE THREAD

**Issue by IanKemp** [jquery/jquery#2752]
According to [outerWidth docs](http://api.jquery.com/outerwidth/#outerWidth-includeMargin):

"The value reported by .outerWidth() is not guaranteed to be accurate when the element or its parent is hidden. To get an accurate value, ensure the element is visible before using .outerWidth(). **jQuery will attempt to temporarily show and then re-hide an element in order to measure its dimensions, but this is unreliable and (even when accurate) can significantly impact page performance. This show-and-rehide measurement feature may be removed in a future version of jQuery.**"

Looking at the jQuery 1.11.3 source, I see no specific show/hide behaviour for `outerWidth()`. Is that functionality still there, or has it been removed? My own tests suggest that this is not happening, but I wanted to check to make sure.

**Comment by markelog** [comment]
Nope, this is still works, if it didn't, you would [get](https://jsbin.com/siwilizowu/edit?html,output) `0` instead of ~`22`
