### ISSUE TITLE
.trigger( "multiple events triggering" )

### ISSUE THREAD

**Issue by Mr21** [jquery/jquery#2753]
Hi :)

We can do this :
``` javascript
$( "body" ).on( "mousedown touchstart", function() { /* ... */ } );
```

But not this :
``` javascript
$( "body" ).trigger( "mousedown touchstart" );
```

We have to call `.trigger` **N** times.
``` javascript
$( "body" )
    .trigger( "mousedown" )
    .trigger( "touchstart" )
;
```

Why not calling `.match( rnotwhite )` on the event string?

**Comment by markelog** [comment]
Big plus from me... as it was three years ago - http://bugs.jquery.com/ticket/12734 :-).

It was denied before, but maybe it is time to reconsider?

**Comment by Mr21** [comment]
Okay cool, I will write a PR asap for you to see.
Your link is throwing 502 :/

**Comment by markelog** [comment]
> Okay cool, I will write a PR asap for you to see.

I would suggest to wait, either until we would had discussion in this issue or in the meeting on next monday, i will put it on the agenda.

> Your link is throwing 502 :/

Yeah, it is our server, we aware of that, one of the reason why we switched bug tracker

**Comment by Mr21** [comment]
Yeah i understand the deal, but i know you are counting the bytes so maybe the number is important for your meeting.

**Comment by dmethvin** [comment]
I'm still meh on it. Do you have some use cases where you'd want to trigger several events with the same event object?

**Comment by Mr21** [comment]
I had this idea when I wrote some code like:

``` javascript

$( function() {

// Write the events :
jqElement.on( {
   eventA: function() {},
   eventB: function() {}
});

// First initialisation:
jqElement
    .trigger( "eventA" )
    .trigger( "eventB" )
;

});
```

But the first time I wrote `.trigger( "eventA eventB" )` because I knew that `.on( "eventA eventB" )` works.

**Comment by markelog** [comment]
Aside from usefulness (which i think is real), we can also find real life examples, like that - https://github.com/jquery/jquery-ui/blob/6c738d961d9918f75a3043a49ab21ac79bca45ae/tests/unit/accordion/options.js#L343-L344

**Comment by scottgonzalez** [comment]
> Aside from api consistency (which i think is important), we can also find real life examples

I would absolutely not use `.trigger( "custom1 custom2" )` in that code, even if it was supported.

**Comment by dmethvin** [comment]
Triggering an event is different from setting an event handler, so I don't really buy the "API consistency" argument. From the original above, the `mousedown` and `touchstart` events have different event objects when they're fired by the browser, so I'm not convinced that enough use cases would be served here. 

For custom events where bubbling is not desired or used, it would be  better to use `.triggerHandler()` which also allows you to have a return value and where it definitely doesn't make sense to have multiple events per call.

**Comment by markelog** [comment]
Discussed this on the meeting, sorry @Mr2, it seems as no go again :/, maybe we can revisit it after another three years :-)

**Comment by Mr21** [comment]
Oh understood, no problem :)
