### ISSUE TITLE
$.extend is not available, in require('jquery')

### ISSUE THREAD

**Issue by madhavan020985** [jquery/jquery#2758]
I am using jquery npm V2.1.4. In node 0.10, when i run,
````javascript
var $ = require('jquery')
var object = $.extend({}, { a : 1}, {b : 2})
````

But it throws error as,
`
TypeError: $.extend is not a function
    at repl:1:16
    at REPLServer.defaultEval (repl.js:248:27)
`

**Comment by gibson042** [comment]
jQuery requires a browser-like `window` to properly initialize. In environments where one is not present globally (including node.js), you get not the library but a _factory_ that takes in such a window and returns a `jQuery`. See [intro.js](https://github.com/jquery/jquery/blob/1823a715660a5f31dd7e05672e9ad020066256a9/src/intro.js#L20-L23) for implementation comments, but the short explanation is that you'll need to do something like `var $ = require('jquery')(window)`.

If all you want is `jQuery.extend` and similar utilities, though, you'd be better of with a utility library like [lodash](https://lodash.com/).

**Comment by madhavan020985** [comment]
I used `var $ = require('jquery')((require("jsdom").jsdom().defaultView))` and it works... thanks...
