### ISSUE TITLE
Typo of `if` in a few comments

### ISSUE THREAD

**Issue by Melluish** [jquery/jquery#2760]
Misspelled `if` in a few places:
https://github.com/jquery/jquery/search?utf8=%E2%9C%93&q=iff

**Comment by FagnerMartinsBrack** [comment]
That's intentional, it means [if and only if](https://en.wikipedia.org/wiki/If_and_only_if)

**Comment by FagnerMartinsBrack** [comment]
Duplicated of #2625

**Comment by Melluish** [comment]
In that case, I'm a diick :)

**Comment by FagnerMartinsBrack** [comment]
You are not, that's a common misconception that happens [with](https://github.com/jquery/jquery/pull/749/files#r718127) [everyone](https://github.com/jquery/jquery/commit/b0ea80e9fd35286c1cd68216c512712dff1f145d#commitcomment-1344436).

**Comment by markelog** [comment]
Either way thank you for keeping an eye on it!
