### ISSUE TITLE
ajax can't work with https in nodejs + jsdom

### ISSUE THREAD

**Issue by vontio** [jquery/jquery#2764]
Hi I am trying to use a browser lib with nodejs.
ajax http works fine but https can not work.

details in this link: 
http://stackoverflow.com/questions/34183739/jquery-ajax-in-nodejs-can-not-get-post-with-https

**Comment by timmywil** [comment]
Thank you for opening an issue, but this issue should first be fleshed out more on stackoverflow, in the [forums](http://forum.jquery.com), or in the #jquery irc channel to determine if this is actually a bug in jQuery Core.
