### ISSUE TITLE
the function of the position will return a wrong value when a negative value of marginTop or marginLeft

### ISSUE THREAD

**Issue by jeffers0054** [jquery/jquery#2765]
as title.
version 1.11.3

the parent offset is correct. and this offset is correct too.
but the marginTop and marginLeft is negative value.
the code as below:

line 10181:
return {
    top:  offset.top  - parentOffset.top - jQuery.css( elem, "marginTop", true ),
    left: offset.left - parentOffset.left - jQuery.css( elem, "marginLeft", true)
}

**Comment by timmywil** [comment]
Thanks for opening an issue. Please provide a reduced test case on http://jsbin.com or http://jsfiddle.net to help us assess the problem.

**Comment by jeffers0054** [comment]
http://jsfiddle.net/jeffers0054/nzzywzya/

**Comment by Manoj-Roy** [comment]
http://jsfiddle.net/manoj_roy/m8tz2ft2/1/

try it .

**Comment by timmywil** [comment]
Thanks for opening an issue, but this looks right to me. It looks like it is correctly subtracting the negative margin, effectively adding the margin, which is right.
