### ISSUE TITLE
7 Traversing Unit Tests, suddenly failing in Microsoft Edge.

### ISSUE THREAD

**Issue by AmazingJaze** [jquery/jquery#2767]
It appears something has changed in the master branch of JQuery, that is causing the following unit tests to fail when run in Microsoft Edge

*"traversing: find(String)"*
*"traversing: find(String) under non-elements"*
*"traversing: find(leading combinator)"*
*"traversing: find(node|jQuery object)"*
*"traversing: is(String|undefined)"*
*"traversing: is(jQuery)"*
*"traversing: is() with :has() selectors"*

All of the failures give the following message: `Died on test #1    at Global code (/jquery/test/unit/traversing.js:234:1): Permission denied`

When running tests for  **all modules** from the master branch in the last week of November, all of the above tests pass.

However, when running tests for **all modules** from the master branch on December 4th all of the above tests fail.

Both times I used the same build of Windows 10 and with the Same Build of Microsoft Edge, so the change appears to be coming from JQuery

**Note** that these tests do not fail when run in isolation, or when just running the "traversal" module. Instead it appears they are dependent on the failure of test:
*"selector: Iframe dispatch should not affect jQuery"* 

This test was failing previously in Microsoft Edge as well, however now when it fails, the traversing tests that follow it also fail as well.

**Comment by AmazingJaze** [comment]
updated above for clarity

**Comment by mzgol** [comment]
Which version of Edge? We run tests on Edge on TestSwarm and [all tests have passed](http://swarm.jquery.org/job/1825) on the latest commit (i.e. 1823a715660a5f31dd7e05672e9ad020066256a9).

Our CI uses Edge 12.

Make sure you run `grunt` before trying the test. Try to clear the browser cache as well.

**Comment by AmazingJaze** [comment]
Using Edge 25.11073.1006.0 with EdgeHTML 13.11073

As previously mentioned they passed until pulling again from the master branch.

**Comment by timmywil** [comment]
Thanks for opening an issue, but it works for us.
