### ISSUE TITLE
`$audio.trigger('play')` invokes `playCallback` twice

### ISSUE THREAD

**Issue by lzl124631x** [jquery/jquery#2769]
Reposted from [My stackoverflow post](https://stackoverflow.com/questions/33670514/why-audio-triggerplay-fires-playhandler-twice-while-audio0-play). There is no satisfactory answer and **I DO THINK THIS MAKES CODE BUG-PRONE** so I repost it here.

I used to think `trigger(play)` just fires the native `play` function of audio, but today I just noticed that there is a slight difference between these two methods. If you register a callback for `play`, e.g. `$('audio').on('play', function() { console.log('playing'); })`, the callback will be invoked twice if you use `trigger(play)` but only once when using `play()`.

* How come this discrepancy?
* Is this as expected? I expect `trigger('play')` to behave exactly the same as `play`.
* Is it possible to make `trigger(play)` only fires the `play callback` once, so as to keep potential bugs away?

[[demo]](https://jsfiddle.net/Richard_Liu/gttde0p0/)

---

In the demo, I call `trigger('play')` and `trigger('pause')` and then `play()` and `pause()`. The result is 

    // the following four lines are generated by trigger calls
    play 
    play
    pause
    pause
    // the following two lines are generated by native calls
    play
    pause
This demo could illustrate what I'm talking about.

This problem could be reproduced on:

* Chrome version 46.0.2490.86 m
* IE 11.0.9600.18053
* FireFox 42.0

---

One example problem is:
I want to `addClass` on a button in the `playCallback` and `removeClass` in the `playingCallback`. When the audio is already playing,
* If `audio.play()` is called, neither `playCallback` nor `playingCallback` will be invoked.
* If `$audio.trigger('play')` is called, the `playCallback` will be invoked ONCE and the `playingCallback` is not invoked. This is an unexpected behavior.

**Comment by dmethvin** [comment]
The StackOverflow answers explain it pretty well. It seems like you're using jQuery's `.trigger()` to *call* a method and that is not its main function. [The docs mention explain when a method is called](http://api.jquery.com/trigger/).

> Note: For both plain objects and DOM objects other than `window`, if a triggered event name matches the name of a property on the object, jQuery will attempt to invoke the property as a method if no event handler calls event.preventDefault(). If this behavior is not desired, use .triggerHandler() instead.

**Comment by lzl124631x** [comment]
Ok, thanks. I think using the native `play` function is a better choice.
