### ISSUE TITLE
jQuery.extend with deep=true causes unpredicted side effects

### ISSUE THREAD

**Issue by maciej-pawlisz** [jquery/jquery#2773]
There is a problem with deep extending - nested objects get overritten, which might be very confusing (example at: https://jsfiddle.net/4gpju44c/):
```javascript
var nested={x:1}
var obj={n:nested}
$.extend(true,obj,{n:{x:2,y:2}}) 
console.log(nested)
{x:2, y:2, } 
```
It is even worse, when `nested` will be a prototype - we can get very unexpected errors (I experienced it when using jquery.rest and I changed `verbs`)

In `jQuery.extend` function there is a comment, which suggests that this situation should be avoided :
```javascript
         // Never move original objects, clone them
        target[ name ] = jQuery.extend( deep, clone, copy );
```
but it is not working as the comment suggests. Maybe it should be replaced with:
```javascript
        target[ name ] = jQuery.extend( deep,{}, clone, copy );
```

**Comment by dmethvin** [comment]
This is [documented](https://api.jquery.com/jquery.extend/):
> On a deep extend, Object and Array are extended, but object wrappers on primitive types such as String, Boolean, and Number are not. Deep-extending a cyclical data structure will result in an error.

The `jQuery.extend` is definitely quirky by today's standards, but the behavior is potentially depended upon by millions of web sites and jQuery itself so changing it would cause a lot of trouble. If you require other behavior, take a look at `Object.assign()` in ES6 or use [lodash](https://github.com/lodash/lodash).
