### ISSUE TITLE
KeyboardEvent not fully supported

### ISSUE THREAD

**Issue by Mottie** [jquery/jquery#2774]
None of the versions of jQuery I tested (edge, down to v1.7.2) appear to support `KeyboardEvents` when using the [`event.getModifierState` function](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState) as follows:

\*Note\* [This demo](http://jsfiddle.net/fxa0z3f7/1/) currently only works in Firefox & MS Edge (not yet supported in Chrome; possibly targeted for Chrome v48)

```js
$( window ).on( 'keydown', function( event ) {
  var shift = event.getModifierState && event.getModifierState( 'Shift' );
  console.log( 'jQuery: Shift', shift );
});
```

If you press the <kbd>Shift</kbd> key, this appears in the console:

> jQuery: Shift undefined

With plain javascript:

```js
document.addEventListener( 'keydown', function( event ) {
  var shift = event.getModifierState && event.getModifierState( 'Shift' );
  console.log( 'JS: Shift', shift );
});
```

This is seen in the console:

> JS: Shift true

**Comment by dmethvin** [comment]
It's always good to provide a jsbin or jsfiddle to show what you mean. Remember that as documented though, the `event` object you get in a jQuery handler is a *subset* of the raw event object. There is no `.getModifierState` in the jQuery event object.  You can find that in `event.originalEvent`, **if** is is supported on the platform where you are running.

**Comment by Mottie** [comment]
Thanks! And I did provide a demo - the "This demo" link above - http://jsfiddle.net/fxa0z3f7/1/

**Comment by dmethvin** [comment]
Sorry I missed that, I went back to look for it and didn't see it!
