### ISSUE TITLE
Animate function doesn't work from "%" to "%"

### ISSUE THREAD

**Issue by BrodaNoel** [jquery/jquery#2775]
Hi all!
Please, check this jsFiddle: https://jsfiddle.net/1fxm1k2j/
As you can see when you click on the green box, the animation is not working

Using Firefox, In Windows. jQuery 1.11.0 (but still the same behavior in 1.11.3)

Thanks

**Comment by gibson042** [comment]
I see a smooth animation, and more to the point I see style properties incrementally approaching their target values in the developer console. Please try again in Private Browsing mode with all extensions disabled (in case they are interfering).

If you still experience problems, please report back here with a detailed explanation of "not working" that includes both what you experience and what you _expected_ to experience, and we'll either reopen the issue or do our best to provide an explanation.

**Comment by BrodaNoel** [comment]
@gibson042, I just restarted Firefox with no addons and I'm still seeing the same issue.
Chrome (latest) and IE11 are working well.
But the issue is related to Firefox 42.

In Firefox 42 I don't see the transition. It's like the div is hidden automatically when I do the click

**Comment by BrodaNoel** [comment]
I just updated firefox to Firefox 43 and I'm getting the same issue.

**Comment by BrodaNoel** [comment]
I'm trying with this Fiddle: https://jsfiddle.net/1fxm1k2j/3/

**Comment by BrodaNoel** [comment]
A video!: https://www.youtube.com/watch?v=X9lMKdH23mY

**Comment by dmethvin** [comment]
Yes, I can repro this on Windows 10 Firefox 42 as well.

**Comment by BrodaNoel** [comment]
I'm using Windows 7.
Thank you @dmethvin

**Comment by rwaldron** [comment]
@dmethvin @gibson042 check this out, if you inspect the element, then click on it, the animation executes correctly (in Firefox) https://www.youtube.com/watch?v=f8ORa_aNT0w

**Comment by BrodaNoel** [comment]
@rwaldron what about before inspect it?

**Comment by BrodaNoel** [comment]
Ok, I can't belive it.
It's working well when I open the native firefox inspector or Firebug

**Comment by rwaldron** [comment]
> what about before inspect it?

It repros the same as your video

**Comment by Manoj-Roy** [comment]
http://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_animation
You can try it .

**Comment by NoelBroda** [comment]
@Manoj-Roy, but, in that case, you are using `px` instead of `%`.

**Comment by BrodaNoel** [comment]
So, @gibson042, can you open it?

**Comment by gibson042** [comment]
I don't see anything we can do... if opening the Dev Console makes it work, then this is almost certainly a browser bug and should be reported to Mozilla. Does anyone disagree?
