### ISSUE TITLE
after add a function into Object.prototype, the ajax will return a "Error Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by jeffers0054** [jquery/jquery#2783]
version 1.11.3

Object.prototype.clone = function(){
         var newo = {};
    		this.each( function(v, k, self){
    			if( self.hasOwnProperty( k ) ){
    				this[k] = ( 'object' === typeof v || 'array' === typeof v )  ? v.clone() : v ;
    			}
    		}, newo );
    		return newo;
};

Array.prototype.clone = function(){
    		var newa = [];
    		this.each( function(v, k, self){
    			if( self.hasOwnProperty( k ) ){
    				this[k] = ( 'object' === typeof v || 'array' === typeof v )  ? v.clone() : v ;
    			}
    		}, newa );
    		return newa;
    	};

jQuery line 9098 to 9100
		// Convert data if not already a string
		if ( s.data && s.processData && typeof s.data !== "string" ) {
			s.data = jQuery.param( s.data, s.traditional );
		}

the jQuery.param will foreach the all properties from s.data

it will be a issue. Please check it.

**Comment by dmethvin** [comment]
Yes. Never modify `Object.prototype`. jQuery does not support it. https://contribute.jquery.org/wont-fix/#object-prototype-issues
