### ISSUE TITLE
can not select form when using context

### ISSUE THREAD

**Issue by vontio** [jquery/jquery#2785]
context is a html string. ctx = ```'<html><body><form name="myform"><input ... ></form></body></html>'```
I can use this syntax to select input $('input',ctx)
but select form always return length 0
$('form',ctx).length == 0

**Comment by gibson042** [comment]
jQuery expects HTML strings to represent document fragments, not entire documents. In particular, `<html>` and `<body>` are stripped by [`innerHTML` assignment](https://github.com/jquery/jquery/blob/99e8ff1baa7ae341e94bb89c3e84570c7c3ad9ea/src/manipulation/buildFragment.js#L42), leaving the form as the context element itself, in which there are no other forms.

Observe: https://jsfiddle.net/98cnorun/1/

**Comment by vontio** [comment]
Thanks for the detail explanation and the context switch trick.But why strip context to the form level ?

**Comment by gibson042** [comment]
We aren't—it's the native functionality to drop `<html>`/`<body>`/etc.
