### ISSUE TITLE
filter() method throws an error when the selector contains single quote (Uncaught Error: Syntax error, unrecognized expression:)

### ISSUE THREAD

**Issue by zdrawku** [jquery/jquery#2791]
Hello all,

I have noticed a bug in the new version of jQuery (1.11.3), the same is not reproducible with 1.10.0 for example.

Online example:
http://jsfiddle.net/1k1t2yh1/11/

**Comment by dmethvin** [comment]
The single quote in the middle of the expression wasn't escaped. ``"[data-value='\"Wilt\\'s\"3PL']"`

**Comment by zdrawku** [comment]
Yeah I know that, but previously with version 1.10.0 it was working despite of that, you can have a look at the online sample, just change the jQuery version to 1.10.0 and not 1.11.3

**Comment by dmethvin** [comment]
Sure, but it was wrong before so we fixed a bug. You can't have an unescaped quote in the middle of a string.

**Comment by zdrawku** [comment]
Okay, thank you for the explanation, I assumed that this was the reason on a first place.
Have a great day.
