### ISSUE TITLE
css('animation-iteration-count', 5) doesn't apply style to element

### ISSUE THREAD

**Issue by ufologist** [jquery/jquery#2792]
When I use ```css('animation-iteration-count', 5)``` I expect element has ```style="-webkit-animation-iteration-count: 5;"``` (this vendor prefix is just a example), but it doesn't.

So I debug jQuery.js, I found when I use ```css('animation-iteration-count', 5)``` actually become ```style[ 'WebkitAnimationIterationCount' ] = 5 + 'px'```.
Browser consider it a illegal value, because ```animation-iteration-count``` only accept ```infinite | <number>```, so this style don't have effect.

This is a [reproduceBug demo](http://output.jsbin.com/gupugawibe)

So that ```cssNumber``` shoud add ```animationIterationCount``` property to prevent automatically add "px" to the value.

**Comment by ufologist** [comment]
#2793

**Comment by mgol** [comment]
Reopening, this shouldn't have been closed.
