### ISSUE TITLE
MutationObserver fiering twice when using .html()

### ISSUE THREAD

**Issue by HansHammel** [jquery/jquery#2797]
I found the html method firing two MutationObserver Events. I think "cleanData" and/or "empty" are causing the first event on removal, and, the second event occures due to "append" and/or "innerHTML" beeing called!?

**I think this is undermining the MutationObserver's basic idea to have only ONE event when a bunch of DOM-changes take place, right!?**

Is is technically possible to do these actions in one go?

Architectural considerations: Well, I am inbetween two chairs. Personally, I need to hook into both, the add- and removal- event of a certain container, currently replaced by the html method. I was expection only one MutationObserver Event. I think technically it would be nice to distigusih between these actions. So, what's the current way to do so!? That is reliable? Are there any plans to make jquery distingush DOM add- and removal- events based on MutationObservers? As far as I can see, there are no MutationObservers used in jquery at all!?

Regards.
O.B.

**Comment by dmethvin** [comment]
Before we go any further, please provide a test case hosted on jsbin.com or jsfiddle.net. Thanks!

**Comment by HansHammel** [comment]
https://jsfiddle.net/aqjqvLzn/

**Comment by alecpl** [comment]
I see only one MutationRecord in console for both fiddles using recent Firefox.

**Comment by dmethvin** [comment]
I only see one MutationRecord in the latest Chrome and Safari. I see two records in Edge. It's not clear to me why two records would be considered "wrong" but it's not something jQuery controls.

**Comment by timmywil** [comment]
It could be that this is an Edge bug and should be reported there, but I'm not sure we can do anything in jQuery to work around it.

**Comment by dmethvin** [comment]
Just to be clear, I didn't see any browser that called the observer callback twice which is what the OP seemed to be claiming. Edge calls the observer callback once like all the others but with two records, which doesn't seem to be [against the spec](http://www.w3.org/TR/dom/#interface-mutationobserver) as far as I can tell. The first record has the results of the `.empty()` and the second is the `.append()`. From a synchronous logic standpoint it doesn't seem like two records vs one should make a difference if you are processing deletes before appends.

**Comment by HansHammel** [comment]
Confirmed. This is an Edge bug. Sorry.
