### ISSUE TITLE
val() doesn't update the value attribute

### ISSUE THREAD

**Issue by Risto-Stevcev** [jquery/jquery#2798]
The `.val('...')` function doesn't seem to be updating the `value` attribute, but `.attr('value', '...')` does. I can get the value I set with `.val('...')` using `.val()`, but it's different from `.attr('value')`. Is this the expected behavior for `.val()`?

http://plnkr.co/edit/WKBynrzxGDklYNWzHcRn?p=preview

The value attributes in the [API examples](http://api.jquery.com/val/) don't update either.

Running this on Firefox 43.0.1 and Chromium 47.0.2526.106

**Comment by mgol** [comment]
The `.val(name, value)` setter updates the `value` property of an input element, not an attribute. The attribute is only used by browsers to initialize the property, they get out of sync with further changes.

This works correctly.

**Comment by Risto-Stevcev** [comment]
@mgol Thanks for clarifying
