### ISSUE TITLE
$(window).scroll(function () { ... }) vs $(window).on('scroll', function () { ... }) are not equivalent

### ISSUE THREAD

**Issue by kand** [jquery/jquery#2801]
Contrary to what the [jQuery `.scroll()` documentation states](https://api.jquery.com/scroll/):
> This method is a shortcut for `.on( "scroll", handler )` in the first and second variations...

`$(window).scroll(function () { ... })` is not directly equivalent to `$(window).on('scroll', function () { ... }` as can be [seen in this jsfiddle](http://jsfiddle.net/ba58kL9j/6/).

The documentation should be updated with info on this edge case.

**Comment by dmethvin** [comment]
Take a look at the console. jQuery 1.5.2 was released 5 years ago and does not have `.on()`.

**Comment by markelog** [comment]
@dmethvin beat me to it :-)
@kand check this out - http://jsfiddle.net/6n3yd6x1/

**Comment by kand** [comment]
Ah, dumb mistake, thanks!
