### ISSUE TITLE
3.0.0-alpha1: $(window).offset() fails with an exception

### ISSUE THREAD

**Issue by dcherman** [jquery/jquery#2802]
https://jsfiddle.net/knfw5n1d/1/

This breaks some tested behaviors in jQuery UI

https://github.com/jquery/jquery-ui/blob/master/tests/unit/position/core.js#L165-L169

As a wise man once said,

> "Core ain't done till UI won't run"

**Comment by dmethvin** [comment]
I thought this was fixed in master though. Is this about #2310?

**Comment by dcherman** [comment]
That looks like the same thing I was reporting here.  From reading this, it looks like the plan is for UI to either push out 1.11.15 to support 3.0 or wait for 1.12.0 for official support.

Didn't find that when I searched, so it looks like this is already addressed.  Closing.
