### ISSUE TITLE
Missing bower.json in jquery 2.2.0

### ISSUE THREAD

**Issue by vmlf01** [jquery/jquery#2805]
I installed jquery with ```bower install jquery``` and it looks like the ```bower.json``` file is missing from the 2.2.0 release.

**Comment by timmywil** [comment]
Thanks for opening an issue, but it works for me. It might have something to do with the bower version (I think I remember a time when bower would remove it and just have a `.bower.json`), but it's definitely [in the repo](https://github.com/jquery/jquery-dist/blob/6fc01e29bdad0964f62ef56d01297039cdcadbe5/bower.json).

**Comment by dmethvin** [comment]
is it possible that bower is looking in /jquery instead of /jquery-dist?  @vmlf01 we'd need more info from  you about where it is looking.

**Comment by timmywil** [comment]
We did change the registered location in bower. Maybe you need a `bower cache clean`?

**Comment by vmlf01** [comment]
Just did bower install again on a different computer and it seems ok now, must have been the cache.
```
PS C:\Users\vmlf\Desktop\teste> bower install jquery --save
bower jquery#*              not-cached git://github.com/jquery/jquery-dist.git#*
bower jquery#*                 resolve git://github.com/jquery/jquery-dist.git#*
bower jquery#*                download https://github.com/jquery/jquery-dist/archive/2.2.0.tar.gz
bower jquery#*                 extract archive.tar.gz
bower jquery#*                resolved git://github.com/jquery/jquery-dist.git#2.2.0
bower jquery#~2.2.0            install jquery#2.2.0

jquery#2.2.0 bower_components\jquery
```

Thanks.

**Comment by timmywil** [comment]
Good to know. Thanks!
