### ISSUE TITLE
Zombie 2.5.1/JSDom 1.4.0 (last node 0.12 version) and jQuery 1.12

### ISSUE THREAD

**Issue by justinbmeyer** [jquery/jquery#2806]
jQuery 1.12 does not load in Zombie 2.5.1.

This is caused by:

```
support.createHTMLDocument = function () {
        if (!document.implementation.createHTMLDocument) {
            return false;
        }
        var doc = document.implementation.createHTMLDocument('');
        doc.body.innerHTML = '<form></form><form></form>';
        return doc.body.childNodes.length === 2;
    }();
```

The `doc` doesn't have a body, so `innerHTML` is set on `undefined`.  The fix would be to make sure there's a body.

I'm not sure if #2154 indicates this was purposeful or not.  We have a big matrix of tests for new and old versions of jQuery, along with build tools that need to work in a lot of different versions of node.

I wouldn't be able to use Zombie to verify CanJS + jQuery 1.12 in a node 0.12 environment.  Yeah ... an odd situation.  Please let me know what you think.  Thanks!

**Comment by mgol** [comment]
The last jsdom version supporting Node<4 is 3.sth.sth, not 1.4.0. Can you upgrade jsdom & try again?

**Comment by justinbmeyer** [comment]
@mgol I'm using Zombie (which bundles 1.4).  I suppose I could make a custom Zombie that points to 3.

**Comment by justinbmeyer** [comment]
Upgrading to zombe 3.X seems to work in node 12.  Closing.

**Comment by mgol** [comment]
Glad to know it's working. Perhaps you could submit a PR to Zombie so tgat they update their copy of jsdom?

**Comment by mgol** [comment]
Sorry, I didn't notice you mentioned upgrading Zombie, not jsdom. So all is fine.

Thanks for the info!
