### ISSUE TITLE
unquoted attr selector throws error

### ISSUE THREAD

**Issue by Billy-** [jquery/jquery#2811]
This line is throwing an error after updating from 2.1.4 to 2.2.0.

`$('a[href*=#]:not([href=#])');`

This is due to the attribute selector not being encased in quotes. i.e this fixes the error:

`$('a[href*="#"]:not([href="#"])');`

Not sure if this is expected but this is supposed to be a non-breaking release.

I do realize that the first example (which throws the error) is not correct syntax, based on [the jQuery docs](https://api.jquery.com/category/selectors/attribute-selectors/), but not sure if this is supposed to throw an error. I'm assuming a graceful degradation is preferred over an error which ultimately stops further Javascript execution.

**Comment by timmywil** [comment]
Thanks for opening an issue. If this were an issue about breaking documented behavior, we'd want to revert the change, but, as you pointed out, the former is not a valid selector. Yes, it used to work, but another thing is that it broke the QSA path and had to be handled manually in Sizzle anyway. The latter will go through QSA just fine. Given that, I'm inclined to leave the bug fix.
