### ISSUE TITLE
jQuery 2.2.0 has error from jQuery UI 1.11.4

### ISSUE THREAD

**Issue by East-of-Nowhere** [jquery/jquery#2814]
I have a web app that had jQuery 2.1.4 and jQuery UI 1.11.4 working fine. Updated jQuery to 2.2.0 and then I started getting errors like "datepicker is not a function" or "tabs is not a function".
Stepping thru in browser F12 I found the original JavaScript error in jquery-2.2.0.js

    var getStyles = function( elem ) {
		// Support: IE<=11+, Firefox<=30+ (#15098, #14150)
		// IE throws on elements created in popups
		// FF meanwhile throws on frame elements through "defaultView.getComputedStyle"
		var view = elem.ownerDocument.defaultView;
		if ( !view.opener ) { // Error thrown from HERE
			view = window;
		}
		return view.getComputedStyle( elem );
    };

elem is an &lt;a> tag, and its defaultView is null, so view.opener gives error **"Unable to get property 'opener' of undefined or null reference"**

Looking up the callstack, the top call is towards the beginning of jquery-ui.js, at `factory(jQuery);` so none of my web app's code is directly involved. No changes were made to my jQuery UI or jQuery Migrate libraries. Rolling back to jQuery 2.1.4 got rid of the error for me.

I can duplicate this error with this simple jsFiddle example https://jsfiddle.net/7Lmryjsx
The "Unable to get property..." error happens in Chrome and IE11.

**Comment by scottgonzalez** [comment]
This is an issue in jQuery Migrate, which was actually *just* fixed: https://github.com/jquery/jquery-migrate/issues/128

**Comment by dmethvin** [comment]
http://blog.jquery.com/2016/01/13/jquery-migrate-1-3-0-released/
