### ISSUE TITLE
Firefox: don't set e.relatedTarget to null on focusout

### ISSUE THREAD

**Issue by jlgrall** [jquery/jquery#2815]
On `focusout` event object, the `relatedTarget` property tells which element is obtaining the focus.
In Chrome, `relatedTarget === null` only when no other element obtains the focus (a click on the page background).

Firefox doesn't have a focusout event, so it is faked by jQuery. But the `relatedTarget` is not well set by jQuery: it is always set to `null`.

A better solution would be to set `relatedTarget` to:
- `null` only when we know that no other element obtains the focus
- `undefined` when we can't know if or which element obtains the focus

This way, when `relatedTarget === undefined`, we are either in an old browser that has not a complete implementation of the `focusout` event (like Safari 5.1), or we are in a faked event that cannot tell which element obtains the focus.
And when `relatedTarget === null`, we can be certain that a `focusout` event has happened but no other element is obtaining the focus.

JSFiddle where you can test the values of `e.relatedTarget`: [jQuery bug: focusout relatedTargetset to null](https://jsfiddle.net/jlgrall/eoa2bwcd/)

**Comment by dmethvin** [comment]
Can you provide a pull request?

**Comment by timmywil** [comment]
Thanks for opening an issue. Given that this will be inconsistent across browsers regardless, I'm inclined to leave this as-is. It seems like you're asking for this property to act as a feature-detect, effectively (by using `undefined` to signify that focusout wasn't native). If we started doing that, we'd have to change a lot of other properties to be consistent (something that's not so trivial all the time).

**Comment by timmywil** [comment]
That said, we'd be willing to review a PR and reopen.

**Comment by jlgrall** [comment]
After looking at the jQuery's code I found that jQuery doesn't change the `relatedTarget` property (well it seems that it could change it in jQuery 1.9.1, but I didn't investigate further. Current jQuery are 1.12.0 and 2.2.0). So I updated the JSFiddle to show this: [jQuery bug: focusout relatedTargetset to null](https://jsfiddle.net/jlgrall/eoa2bwcd/)

As you can see (and if jQuery doesn't modify the `e.originalEvent`), it is not jQuery, but Firefox that sets `relatedTarget` to null.

Conclusion: there is probably nothing we can do here. I will use `document.activeElement` instead. Thanks, and sorry for opening this issue.
