### ISSUE TITLE
intro.js source incomplete?

### ISSUE THREAD

**Issue by mmazo** [jquery/jquery#2819]
Hai guys,

contents of intro.js look incomplete (https://raw.githubusercontent.com/jquery/jquery/master/src/intro.js). Is this on purpose or this is a bug? Our project does not build because of the js syntax error caused by intro.js...

With best Regards,
Micha

**Comment by dmethvin** [comment]
intro.js is combined with outro.js during the build process, it's not a complete file by itself.

**Comment by mmazo** [comment]
Thank You,
dmethvin! This means, that we better get only complete jquery version out of the dist folder an let other stuff aside :)
