### ISSUE TITLE
ajax request on large content fails sometiems jquery-2.2.0

### ISSUE THREAD

**Issue by itree** [jquery/jquery#2820]
Hi guys, 

So I can't replicate this bug exactly yet.  However, under certain circumstances $.ajax request on large files fails on safari mobile.

The request gets send, but never comes back. And when I reduce the requested text, it works.   

The same request works just fine using XMLHttpRequest object.

**Comment by dmethvin** [comment]
We'd definitely need a test case. Be sure you are comparing apples to apples when you look at XHR vs $.ajax, for example if the $.ajax call has `dataType: "json"` the request would fail if the response was not valid JSON.

**Comment by itree** [comment]
dataType : 'text'

**Comment by markelog** [comment]
> dataType : 'text'

This is not a test-case though, we still need one

**Comment by nghi1129** [comment]
This is happening to me too.  My object is very large, JSON text length at 464806 char.  Failed to deserialize to a model for the .NET MVC Controller method's argument.  So I would get a null reference exception on the back end.

**Comment by dmethvin** [comment]
@nghi1129 I'm not even sure we're talking about the same problem. When you say "this is happening to me" do you mean (like the OP) that your page is only failing on mobile Safari and fails randomly on a *request* to *retrieve* a large amount of text *from* the server? You indicated that your *server* was encountering an error which does not seem like the same situation.

Between the two comments above, we don't yet even know the nature of the "failure" as in does it silently do nothing, throw an error, lock up the phone, etc. Again, a test case would help us to investigate.

**Comment by nghi1129** [comment]
Sorry I am trying to create a test case for you right now.  It is not easy to create a test object as big as one I see in production.  I came down to the fact that Knockout 3.4.0, ko.toJSON(obj) is producing a Json string that is not deserializable on the Controller side.  So this could be entirely Knockout and nothing with the .ajax call.  I switch ko.toJSON to using JSON.stringify and it is working fine.

**Comment by itree** [comment]
My apologies.  Got it resolved.  The problem is due to something else related to localstorage which max at certain limit.  jquery works!
