### ISSUE TITLE
Upgrade from 1.11.3 to 1.12.0 or 2.2.0 breaks jQuery UI Tooltip in all IEs

### ISSUE THREAD

**Issue by SimenB** [jquery/jquery#2828]
I reported  it in the bug tracker for jQuery UI, but it might be a bug in jQuery itself, so reporting here as well.

Bug report: https://bugs.jqueryui.com/ticket/14900

Summary: In IE 8 through 11, the placement of tooltips are wrong in 1.12.0, while they were correct in 1.11.3.

1.11.3:
![image](https://cloud.githubusercontent.com/assets/1404810/12325597/90f32b56-bacb-11e5-9cba-1526a5576a71.png)

1.12.0:
![image](https://cloud.githubusercontent.com/assets/1404810/12325602/97fc3de8-bacb-11e5-8ff5-a67d80d2828e.png)

JSBin: www.jsbin.com/menoxo

EDIT: Just tested in IE11 with the new 2.2.0 release of jQuery. Same error there

**Comment by dmethvin** [comment]
I would suspect gh-1714, can you remove those two lines and see if it gives correct results in IE11?

This seems to work correctly on Edge BTW.

**Comment by SimenB** [comment]
@dmethvin Yeah, then it works.

Changing
```js
// Add offsetParent borders
// Subtract offsetParent scroll positions
parentOffset.top += jQuery.css( offsetParent[ 0 ], "borderTopWidth", true ) -
  offsetParent.scrollTop();
parentOffset.left += jQuery.css( offsetParent[ 0 ], "borderLeftWidth", true ) -
  offsetParent.scrollLeft();
```

to
```js
// Add offsetParent borders
parentOffset.top += jQuery.css( offsetParent[ 0 ], "borderTopWidth", true );
parentOffset.left += jQuery.css( offsetParent[ 0 ], "borderLeftWidth", true );
```

fixes it in every IE

**Comment by dmethvin** [comment]
OK, thanks, good to know. There must be some quirk in IE offsetParent that we're not accounting for.

**Comment by Billy-** [comment]
I can see this change has been made on 1.12 and 2.2 stable, and so I have upgraded from 2.1.4 to 2.2.4 (latest 2.x release at the time of writing), however I am still experiencing this bug. I feel that issue #2897 better explains the bug; simply, when asking for `offset().top` from a hidden element, I am getting the scroll position returned, I would expect `0`. See [this jsfiddle] for replication (using 2.2.4).

**Comment by mgol** [comment]
@Billy- Your fiddle is using jQuery 2.2.3, I switched that to 2.2.4 in https://jsfiddle.net/xm3kpp25/1/.

This behavior is the same as in 2.1.4 (https://jsfiddle.net/xm3kpp25/3/) so nothing changed in 2.2.x.

Also, note that according to the API docs explicitly state hidden elements are not supported as an input to `.offset()`: https://api.jquery.com/offset/:

> **Note**: jQuery does not support getting the offset coordinates of hidden elements or accounting for borders, margins, or padding set on the body element.
>
> While it is possible to get the coordinates of elements with `visibility:hidden` set, `display:none` is excluded from the rendering tree and thus has a position that is undefined.
