### ISSUE TITLE
When calling .val() on a set of radios/checkboxes it should return the value(s) of :checked element(s)

### ISSUE THREAD

**Issue by PawelDecowski** [jquery/jquery#2831]
##### Radio buttons

```html
<input type="radio" name="rsvp" value="yes">
<input type="radio" name="rsvp" value="no">
<input type="radio" name="rsvp" value="maybe" checked>
```

Current behaviour:

```js
$('[name=rsvp]').val();
// "yes" (first matched element’s value is returned, regardless if it’s checked or not)
```

Proposed behaviour:

```js
$('[name=rsvp]').val();
// "maybe" (`:checked` element’s value is returned)
```

##### Checkboxes:

```html
<input type="checkbox" name="contact" value="email">
<input type="checkbox" name="contact" value="text" checked>
<input type="checkbox" name="contact" value="call" checked>
```

Current behaviour:

```js
$('[name=contact]').val();
// "email" (first matched element’s value is returned, regardless if it’s checked or not)
```

Proposed behaviour:

```js
$('[name=contact]').val();
// ["text", "call"] (list of `:checked` elements’ values is returned)
```

#### Rationale

It makes sense to unify the way the value of form elements can be accessed. This would allow to get a value of a form element without knowing what type the element is.

#### Interim solution

The below function can be used instead of `.val()`. All it does is add handling for checkboxes and radio buttons, as per description above.

```js
$.fn.value = function(val) {
    var $this = $(this);

    if (val) {
        return $this.val(val);
    }

    var radio_value = function($radios) {
        return $radios.filter(':checked').val();
    }

    var checkbox_value = function($checkboxes) {
        var vals = [];

        $checkboxes.filter(':checked').each(function() {
            vals.push($(this).val());
        });

        return vals;
    }

    var $first = $this.eq(0);

    if ($first.attr('type') == 'radio') {
        return radio_value($this);
    }

    if ($first.attr('type') == 'checkbox') {
        return checkbox_value($this);
    }

    return $this.val();
}
```

**Comment by dmethvin** [comment]
That would be a pretty big breaking change, right? Current code would be expecting to see a string and instead get an array. What if someone wanted the value of a checkbox element the way they get it today?

**Comment by PawelDecowski** [comment]
Yes, this is a breaking change.

But current behaviour makes little, if any, sense. How often do you select a set of radios/checkboxes, and call `.val()` on them to get the first one’s value, regardless whether it’s checked or not? What would be the use case?

**Comment by timmywil** [comment]
Thanks for opening an issue. I don't think we can or should change `.val()`. First, it's been that way for way too long. Second, the value of a an unchecked checkbox is still a valid value. You may not retrieve it often, but it is still a value that should be retrievable. I've written something very similar to your `value` method for myself in apps before, but it included special value retrieval for more than just checkboxes and radios. It's the kind of thing that would never be perfect or suitable for everyone's applications. I think this is best left to a plugin or to users themselves.

**Comment by PawelDecowski** [comment]
@timmywil 
I understand the point about it being a breaking change so why not consider it for 3.0?

The second point about unchecked values being valid and that it should be retrievable:

1. `$('select').val()` doesn’t return all possible values (or the first one), just the selected one(s). So implementing my proposal would bring `.val()`s behaviour in line with this.
2. You could still retrieve the unchecked values by `.prop('val')`.

**Comment by dmethvin** [comment]
We're not opposed to breaking changes, but they still need to be changes we think should be done.

In jQuery, with very few exceptions, a getter gets the information for the first element in a set. That's what `.val()` does today.

I am not sure what your point is about `$('select').val()`, it gets the value you would get if the first element in that set was submitted.

**Comment by dmethvin** [comment]
For some more background and a simple plugin to do what you want, see this thread:

https://forum.jquery.com/topic/jquery-val-and-checked

**Comment by gibson042** [comment]
This isn't a job for `.val()`, but is just a function call away from [`.serialize()`](http://api.jquery.com/serialize/) or [`.serializeArray()`](http://api.jquery.com/serializeArray/):

```js
// "rsvp=maybe"
$('[name=rsvp]').serialize()

// [ { name: "rsvp", value: "maybe" } ]
$('[name=rsvp]').serializeArray()

// "contact=text&contact=call"
$('[name=contact]').serialize()

// [ { name: "contact", value: "text" }, { name: "contact", value: "call" } ]
$('[name=contact]').serializeArray()
```

**Comment by PawelDecowski** [comment]
@dmethvin 

> In jQuery, with very few exceptions, a getter gets the information for the first element in a set. That's what .val() does today.

That may be what the documentation says but in the real world it’s actually used to get the *selected* (or entered) value of a field.

> I am not sure what your point is about $('select').val(), it gets the value you would get if the first element in that set was submitted.

My point was that `<select>`, just like `<input type="radio">` (or `checkbox`) is a control for selecting a value from a set of predefined values. So `.val()`’s behaviour should be consistent — return the _selected_ value(s).

I understand that `<select>` is a single element, parent of `<options>`’s, whereas `<input type="radio">` represents an option itself. But I don’t think that’s relevant. I think it’s jQuery’s job is to abstract away the underlying HTML structure and provide a consistent way of getting a form control’s _selected_ or entered value.

**Comment by PawelDecowski** [comment]
@gibson042 

> This isn't a job for .val()

I disagree. `.val()` does exactly that for all other form elements, but not for radio buttons or checkboxes.

> but is just a function call away from .serialize() or .serializeArray()

Sure. But that’s not the point. The point is for other form elements `.val()` returns the currently selected or entered value, but not for radios or checkboxes. It’s inconsistent.

**Comment by dmethvin** [comment]
It's not inconsistent. `.val` returns the value of the first element. What you're asking for is essentially, as @gibson042 the *serlialized* value. He's shown a way to do that. Or follow the forum link for yet another solution. What you're asking for is to make a breaking change, when there are better ways to do what you want without breaking other people's code.

**Comment by PawelDecowski** [comment]
> It's not inconsistent. .val returns the value of the first element. 

Like I said, I understand that the documentation says that; but the real world usage is to get the current selected or entered value of the element.

So yeah, it’s consistent _with the documentation_. But in my opinion it’s wrong. It would make so much more sense to be able to get a value of any form element, without knowing it’s type, by just doing:

```js
$('[name=my_element]').val()
```

Just like I can do for other types of `<input>` elements, as well as `<select>` and `<textarea>`.

> What you're asking for is essentially, as @gibson042 the serialized value.

Definitely not. I’m asking for the current selected values. It has nothing to do with serialization. Serialization transforms a form element into its query string or array representation.

I understand that I can use `.serialize()` to achieve what I want (with a little extra code). But that’s not the point. The point is it makes no sense to be able to get the current value of a form element using `.val()`, except for radios and checkboxes.

> He's shown a way to do that.

And so did I in the very first comment. That’s not the point. I’m not asking for a solution; I know how to do it. I’m saying it would make more sense to implement it in the core of jQuery.

> What you're asking for is to make a breaking change.

Sure, I understand that. So why not introduce an alternative method that does that? `.current_val()` I’m sure we can come up with a better name. Then _maybe_ default `.val()` to do that in jQuery 3.0?

I’ve given plenty of reasons above why it would make more sense.

**Comment by dmethvin** [comment]
> So why not introduce an alternative method that does that?

Someone already did that for you on StackOverflow. Use that plugin. There is no need for all the jQuery code you run to be in our repository.

**Comment by PawelDecowski** [comment]
@dmethvin 

I’m giving you reasons why I think it should be at least considered for the core. Why don’t you answer any of my arguments? All your replies are generic “go away”. Why don’t you answer to my specific points?

**Comment by dmethvin** [comment]
If others support it I'll let them speak up. I think we already provide enough ways to get this, including the short plugin I mentioned in the forum post.

**Comment by gibson042** [comment]
@PawelDecowski you appear to have confused a form element's [value](https://html.spec.whatwg.org/multipage/forms.html#concept-fe-value) with the [form submission process](https://html.spec.whatwg.org/multipage/forms.html#constructing-the-form-data-set), which _uses_ the value but skips elements that don't contribute to form data. Make no mistake, the value of a control is unaffected by disabledness or checkedness, but its participation in form submission is.

> the real world usage is to get the current selected or entered value of the element.

For the logic you describe, `.serialize()` and `.serializeArray()` really are the right methods. It just happens that radio buttons and checkboxes can be skipped by direct user interaction instead of only by being disabled (as is the case for text inputs, selects, and textareas).

> Definitely not. I’m asking for the current selected values. It has nothing to do with serialization. Serialization transforms a form element into its query string or array representation.

That's true, but it also skips unchecked elements, which is exactly the behavior you're looking for.
