### ISSUE TITLE
[2.2.0/1.12.0] parseHTML fails in zombie.js/jsdom

### ISSUE THREAD

**Issue by jeremyVignelles** [jquery/jquery#2839]
Hi,
I have automated tests with zombie.js and all my tests failed since the upgrade from 2.1.4 to 2.2.0 .

I stripped down the code to this code:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
</head>
<body>
    <div id="test">
    </div>
    <script type="text/javascript">
    document.getElementById('test').appendChild($.parseHTML('<span></span>')[0]);
    </script>
</body>
</html>
```
In chrome/firefox browser, nothing goes wrong, but when using zombie.js (based on jsdom), I have a WrongDocumentError with this code:
```node
var Browser = require('zombie');
var browser = new Browser();

browser.on('error', function(err) {
    console.log(err);
    console.log(err.stack);
    process.exit(1);
});

browser.visit('http://web/', function(err) {
    if(err) {
        process.exit(1);
    }

    browser.wait(function() {
        process.exit(0);
    })
});
```
[Stack trace](https://github.com/jquery/jquery/files/92113/stackTrace.txt)

Based on this answer https://github.com/tmpvar/jsdom/issues/717#issuecomment-31620260 , the issue seems to be on jquery's side : `document.implementation.createHTMLDocument( "" )` creates another document context and moving node from a document to another is disallowed by jsdom, to "follow the browser behavior".

The issue first happens in versions 1.12.0 and 2.2.0.

**Comment by timmywil** [comment]
Thanks for opening an issue, but we're not going to change our implementation to suit jsdom. `createHTMLDocument` is in the [DOM Standard](https://dom.spec.whatwg.org/#dom-domimplementation-createhtmldocument), all of our browsers support it, and jsdom should too. I'm not sure why jsdom is comparing points there. The spec does not prohibit nodes switching documents. From what I can tell, it should only throw a `WrongDocumentError` when calling `compareBoundaryPoints` or `comparePoints`, not when appending a node.

**Comment by dmethvin** [comment]
@jeremyVignelles I commented in that jsdom issue. It looked to me like jsdom should be adopting the nodes as the browsers do.

**Comment by dmethvin** [comment]
This should be fixed in the next jsdom release.

**Comment by jeremyVignelles** [comment]
Thanks for your great work @dmethvin, I'm waiting for the next jsdom release :-)
