### ISSUE TITLE
Drop support for jsdom on Node<4 completely

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#2841]
We currently have a [wonky logic](https://github.com/jquery/jquery/blob/fe05cf37ffd4795988f9b2343df2182e108728ca/Gruntfile.js#L18-L28) for installing a new jsdom and only testing on version 3 manually, if installed, on older Node.js (0.10 & 0.12). The problem is, jsdom has now bug that makes our whole DOM manipulation basically completely broken (see https://github.com/tmpvar/jsdom/issues/717) so it doesn't make much sense to test on it, even manually (especially that it's so easy to miss it before a release).

IMO we should drop support for old jsdom versions in 3.0.0.

**Comment by dmethvin** [comment]
This makes sense to me, I think we're talking about a small community there anyway and few of them should have logistical reasons for being stuck in old versions.

**Comment by timmywil** [comment]
Approved, @mgol
