### ISSUE TITLE
Ajax AMD module requires serialize module.

### ISSUE THREAD

**Issue by wisaac407** [jquery/jquery#2842]
I noticed when loading jQuery as separate AMD modules that the ajax module depends on the serialize module (for the jQuery.param function), however it's not listed as a dependency in the define call.
Is there a reason for it to be like this? Or is it just a bug?

**Comment by dmethvin** [comment]
You could definitely make a good case for adding it. This is another example of the problems of a big `$.ajax` method with a bunch of internal processing logic. We only need `$.param` for the case where someone passes a non-string as the `data` property so it seems like a shame to always pull in the whole module.

**Comment by mgol** [comment]
> We only need `$.param` for the case where someone passes a non-string as the data property so it seems like a shame to always pull in the whole module.

In that case we should get `$.param` into a separate `serialize/param` module and depend only on that instead of the full `serialize`.

**Comment by dmethvin** [comment]
In terms of lines it's more than half the module so further subdividing probably isn't useful. Someone who wants the other functions like `.serialize` will probably be calling `$.ajax` to send the data.

**Comment by timmywil** [comment]
Agreed, let's add serialize as a dependency. Thanks @wisaac407!
