### ISSUE TITLE
Ajax progress handler

### ISSUE THREAD

**Issue by fulapol** [jquery/jquery#2845]
There is a simple extension for jQuery to attach a function to the progress: https://github.com/englercj/jquery-ajax-progress

This can be usefull if integrated to the library.

**Comment by timmywil** [comment]
Thanks for opening an issue. We're very hesitant to add new features to jQuery, especially ones that are already covered by plugins. If the plugin were more popular, or we get more requests for this feature, we might consider making it a part of core.
