### ISSUE TITLE
Access to the `eval` global and other Firefox extension signing issues with 2.2.0

### ISSUE THREAD

**Issue by cr-nz** [jquery/jquery#2847]
I am getting a number of high severity warnings from jQuery 2.2.0 after submitting an extension to the Mozilla Addons site for signing.

[Validation Results.pdf](https://github.com/jquery/jquery/files/95214/Validation.Results.pdf)

*Text summary:*
```
Access to the `eval` global

Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.

Alternatives are available for most use cases. See https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School/Appendix_C:_Avoid_using_eval_in_Add-ons for more information.

Severity for automated signing: high
Suggestions for passing automated signing:

Please try to avoid evaluating strings as code wherever possible. Read over the linked document for suggested alternatives. If you are referencing the `Function` constructor without calling it, and cannot avoid continuing to do so, consider alternatives such as calling `Object.getPrototypeOf` on an existing function object.
js/vendor/jquery-2.2.0.js
319
320
321
var script,
 indirect = eval;
`setTimeout` called in potentially dangerous manner

Warning: In order to prevent vulnerabilities, the `setTimeout` and `setInterval` functions should be called only with function expressions as their first argument.

Severity for automated signing: high
Suggestions for passing automated signing:

Please do not ever call `setTimeout` or `setInterval` with string arguments. If you are passing a function which is not being correctly detected as such, please consider passing a closure or arrow function, which in turn calls the original function.
js/vendor/jquery-2.2.0.js
3562
3563
3564
// Handle it asynchronously to allow scripts the opportunity to delay ready
window.setTimeout( jQuery.ready );
`setInterval` called in potentially dangerous manner

Warning: In order to prevent vulnerabilities, the `setTimeout` and `setInterval` functions should be called only with function expressions as their first argument.

Severity for automated signing: high
Suggestions for passing automated signing:

Please do not ever call `setTimeout` or `setInterval` with string arguments. If you are passing a function which is not being correctly detected as such, please consider passing a closure or arrow function, which in turn calls the original function.
js/vendor/jquery-2.2.0.js
7051
7052
7053
if ( !timerId ) {
 timerId = window.setInterval( jQuery.fx.tick, jQuery.fx.interval );
}
`setTimeout` called in potentially dangerous manner

Warning: In order to prevent vulnerabilities, the `setTimeout` and `setInterval` functions should be called only with function expressions as their first argument.

Severity for automated signing: high
Suggestions for passing automated signing:

Please do not ever call `setTimeout` or `setInterval` with string arguments. If you are passing a function which is not being correctly detected as such, please consider passing a closure or arrow function, which in turn calls the original function.
js/vendor/jquery-2.2.0.js
7077
7078
7079
return this.queue( type, function( next, hooks ) {
 var timeout = window.setTimeout( next, time );
 hooks.stop = function() {
createElement() used to create script tag

Warning: Dynamic creation of script nodes can be unsafe if contents are not static or are otherwise unsafe, or if `src` is remote.

Severity for automated signing: medium
Suggestions for passing automated signing:

Please avoid using <script> tags to load scripts. For potential alternatives, please see https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School/Appendix_D:_Loading_Scripts
js/vendor/jquery-2.2.0.js
329
330
331
if ( code.indexOf( "use strict" ) === 1 ) {
 script = document.createElement( "script" );
 script.text = code;
```

**Comment by dmethvin** [comment]
Many of these seem like they would have been reported for jQuery 2.1.4 as well. Are you saying this is a change from 2.1.4? 

The Firefox tool is a static analysis tool so it is easily confused by code that is fine. For example, it complains about [this line](https://github.com/jquery/jquery/blob/c4d9eac930b86c192b0f96210d88bb7d91e697e1/src/effects.js#L610) as if `jQuery.fx.tick`may be a string, [but it is always a function](https://github.com/jquery/jquery/blob/c4d9eac930b86c192b0f96210d88bb7d91e697e1/src/effects.js#L576) and is defined just a few lines above.

Do you need the animation module? If not you could build a custom jQuery without the modules it is complaining about.

**Comment by cr-nz** [comment]
They seem new for us and introduced in jQuery 2.2.0. From adding extensions in v2.1.4 I never saw these errors.

> The Firefox tool is a static analysis tool so it is easily confused by code that is fine. For example, it complains about this line as if jQuery.fx.tick may be a string, but it is always a function and is defined just a few lines above.

Things like this you can fix trivially by doing:
```
if ( !timerId ) {
    timerId = window.setInterval(function() {
        jQuery.fx.tick();
    }, jQuery.fx.interval );
}
```

Would prefer to see the jQuery plugin fix these static code analysis issues. It is the most popular library and most extensions will include jQuery in their extension so they will see these warnings too.

**Comment by dmethvin** [comment]
Would you like to propose a PR? Ideally we should have test coverage on this, otherwise it will just regress the next time someone makes changes. That would require adding this tool and doing the scan as part of the build. Is that possible?

**Comment by timmywil** [comment]
I'm surprised you don't see warnings in 2.1.4. Some of that code is the same, other than using `window.setInterval` instead of `setInterval`. Regardless, I think we can safely say that while this Firefox extension is generating warnings, they are not errors, and we have good reasons for what we're doing. I don't think the fact that the extension can't tell that jQuery.fx.tick is always a function should be our problem. Wrapping it in a closure may prevent the warning, but there's no programmatic reason for doing that. It's only to shut up the warnings. Given that, I don't think we should change anything in the source. Warnings are ok, as long as they are deemed as such.

**Comment by dmethvin** [comment]
As I understood it, this is a pre-qualification tool that Mozilla runs on Firefox extensions to see if they have any dangerous code in them. Perhaps Mozilla could whitelist unchanged copies of jQuery for situations like this, if they agree the tool is misguided and they are not dangerous?

**Comment by cyberdees** [comment]
CC’ing Mozilla folks: @miketaylr @digitarald @bzbarsky @annevk @kentuckyfriedtakahe @cyberdees
