### ISSUE TITLE
.hide() on shadow dom element broken in 2.2.0

### ISSUE THREAD

**Issue by vincentwoo** [jquery/jquery#2852]
*May be related to #2341*

In 2.1.4, the following code works fine (in that it does not throw an error):

```js
$('<div/>').hide()
```

However post 2.2.0, this now throws: `TypeError: Cannot read property 'opener' of null` on latest Chrome for me.

This breaks some Rails UJS stuff where they try to create a form and hide it in one stroke, before appending it to the document: https://github.com/rails/jquery-ujs/blob/15515b20722b955224db00caffaa8f28ac845875/src/rails.js#L227

The error appears to come from https://github.com/jquery/jquery/blob/master/src/css/var/getStyles.js#L9 by way of https://github.com/jquery/jquery/blob/master/src/css/curCSS.js#L14, though I am not a jQuery expert and thus am not really sure what's changed post 2.1.

**Comment by timmywil** [comment]
Thanks for opening an issue. Please provide a test case from http://jsfiddle.net or http://jsbin.com to help assess the issue.

**Comment by vincentwoo** [comment]
Disregard, I am a moron, it was an old version of jq-migrate all along.

**Comment by dmethvin** [comment]
Oh shoot, I should have recognized that from what you reported.
