### ISSUE TITLE
Remove right-hand side specificity recommendation

### ISSUE THREAD

**Issue by dare05** [jquery/jquery#2856]
In http://learn.jquery.com/performance/optimize-selectors/ you say:

"Be specific on the right-hand side of your selector, and less specific on the left."

I've opened a thread on SO: http://stackoverflow.com/questions/34923710/selectors-be-specific-on-right-hand-side

and done some benchmarks. Basically, in modern browsers supporting queryselectorall, as far as I'm aware, the Sizzle engine is not used for processing the selector. And the way modern browsers, unlike Sizzle, evaluate selectors is left-to-right. Thus being specific on the right-hand side can hurt rather than help performance. The right-hand side should be treated with the same rules as the left-hand side, having less specificity.

Correct me if I'm wrong.

**Comment by timmywil** [comment]
Actually, browsers parse selector right-to-left as well, but the best place for this issue is actually the [learn.jquery.com repo](https://github.com/jquery/learn.jquery.com).

**Comment by dare05** [comment]
Timmy, can you please provide me with a reference on this (how modern browsers parse CSS selectors)? I haven't been able to find anything so far.
