### ISSUE TITLE
Right ALT key also triggers CTRL event on Windows

### ISSUE THREAD

**Issue by solusipse** [jquery/jquery#2859]
Hello.
I found out that on Windows (IE, Firefox, Chrome) there's a problem with right alt key, which seems to be detected both as ctrl and alt key. Left alt key works like suspected. My keyboard layout is Polish (Programmers). On Linux right alt never works. On OS X both alt keys work as expected.
```
<script src="https://code.jquery.com/jquery-git2.min.js"></script>
<script>
$(window).on('keydown', function(event) {
    if (event.which == 17) {
        alert("ctrl");
    }
    if (event.which == 18) {
        alert("alt");
    }
});
</script>
```

**Comment by mgol** [comment]
Thanks for the report. However, that's just how Microsoft implemented the "Polish (programmers)" keyboard as opposed to other systems; this is beyond the scope of jQuery.

For more details in an interested story about this very problem you may read https://medium.com/medium-eng/the-curious-case-of-disappearing-polish-s-fa398313d4df

**Comment by solusipse** [comment]
Thanks for clarification. Sorry for bothering you.
