### ISSUE TITLE
Document that $('.foo').append(document.createTextNode('bar')) is a supported use case

### ISSUE THREAD

**Issue by stanvass** [jquery/jquery#2870]
The documentation says append() accepts:

- string
- Element
- jQuery collection

The problem is there's no official way to append a text *node* in jQuery. Using append() with a text node works just fine, but Text is not an instance of Element, it's an instance of its parent prototype, Node.

This echoes in other tools and definitions like Definitely Typed's jQuery TypeScript .d.ts definition, where the TypeScript compiler throws an error when I'm appending a text node.

Please fix this in the documentation so it can trickle downstream into our tooling. Thanks :-)

**Comment by timmywil** [comment]
Thanks for opening an issue. However, documentation issues should go [here](https://github.com/jquery/api.jquery.com). Perhaps we should change Element to Node.
