### ISSUE TITLE
tooltip shouldn't show if another pop-up (e.g. autocomplete) is open

### ISSUE THREAD

**Issue by astromarshal** [jquery/jquery#2882]
If a popup (e.g. auto-complete window) is open, putting cursor on an adjacent object with tooltip will show the tooltip, obscuring the pop-up.

If any pop-up is open, tooltip should only show if the trigger element is a child of the pop-up

This is my current hack:

```
$.widget( "ui.tooltip", $.ui.tooltip, {
    _open: function() {
        pop = $('.pop:visible');
        if ((pop.length > 0) && ($(pop[0]).find(this.element[0]).length == 0)) {
          return false;
        }
      return this._superApply(arguments);
    }
});
```

There should also be a `ui-pop` class that's shared by auto-complete and other popup items (perhaps another bug report?)

**Comment by markelog** [comment]
Sounds like you wanted to open issue at the https://github.com/jquery/jquery-ui repo
