### ISSUE TITLE
What is the difference between $().attr() and DOM getAttribute ?

### ISSUE THREAD

**Issue by niknickolas** [jquery/jquery#2883]
&lt;div id="item" selected="123123" > text  &lt;/div >

 console.log( $('#item').attr('selected') );
 console.log( document.getElementById('item').getAttribute('selected') );

Why jquery method attr () does not do same as getAttribute() ?

**Comment by all3fox** [comment]
Hi, it looks to me that `selected` is [not a standard attribute](https://www.w3.org/TR/html5/grouping-content.html#the-div-element) for a `div` (the only standard attributes for a `div` are [the global attributes](https://www.w3.org/TR/html5/dom.html#global-attributes)). So, [here is a discussion](https://forum.jquery.com/topic/trouble-with-non-standard-attribute-using-v1-8) that says you should avoid non-standard attributes. Furthermore, AFAIK your second `console.log` is logging a *property* of a DOM object (I might be wrong here) which is not the same thing as an attribute.

For the difference between `.attr()` and `.prop()` and attributes and propperties in general, I suggest [reading this stackoverflow](http://stackoverflow.com/questions/5874652/prop-vs-attr).

**Comment by timmywil** [comment]
Works for me. https://jsfiddle.net/timmywil/z4eLpya0/1/

Please make sure you're using the latest version of jQuery suitable for your environment. That is, currently either 1.12.0 or 2.2.0.

**Comment by timmywil** [comment]
But @all3fox also makes a good point that `selected` is not a valid attribute for a `div`.

**Comment by markelog** [comment]
I'd like to clarify a bit here -

yeah @all3fox is correct here (almost actually), this is a basically a side-effect of our attribute check of whenever or not they are boolean (simple regexp), if it is, jQuery just return its name.

Bottom line - we do not guarantee any kind of behaviour with incorrect markup.

> Furthermore, AFAIK your second console.log is logging a property of a DOM Javascript object (I might be wrong here) which is not the same thing as an attribute.

In this case no, it is actually a property (this concept is really hard to grasp sometimes). `Element#getAttribute` always return a content property (aka DOM element property), it would return IDL property (aka JS representation of the DOM element) if you would do `document.getElementById('item').selected`. 

Some idl properties "sync" with content properties, if defined by the spec, and some do not, like "expandos" properties (aka undefined by the spec). With old IE (<9) it was a whole different story though -

```js
console.log(document.getElementById('item').selected) // 123123
document.getElementById('item').selected = 'test'
console.log(document.getElementById('item').getAttribute('selected')) // 123123
console.log(document.getElementById('item').selected) // still "test"

// but for <option id="item" selected> text </option>
console.log(document.getElementById('item').selected) // true
document.getElementById('item').selected = false
console.log(document.getElementById('item').selected) // false
document.getElementById('item').setAttribute('selected', true);
console.log(document.getElementById('item').selected) // true
```

The was the main reason for division of `prop` and `attr`.

**Comment by timmywil** [comment]
Don't want to confuse you even more, but the spec actually uses the word "attribute" for both, not property. It's either a "content attribute" or an "IDL attribute". We started referring to "content attributes" as attributes and "IDL attributes" as properties to make it easier to differentiate, as the IDL's were the ones we retrieved with property access.

**Comment by timmywil** [comment]
There's a good overview in the [spec](https://html.spec.whatwg.org/#reflecting-content-attributes-in-idl-attributes) on what @markelog is talking about.
