### ISSUE TITLE
Consider increasing modularization of test entities

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2886]
See https://github.com/jquery/jquery/pull/2810#discussion_r49638025

**Comment by dmethvin** [comment]
I agree we could use better correspondence between modules and have better focus with test markup. For a lot of the project we still use a big messy global document that is really hard to change because it risks breaking tests elsewhere. This would be a great PR for someone who wanted to learn about the jQuery project structure. It's mostly rearranging code but you'd learn a lot in the process.

**Comment by markelog** [comment]
I'd like to improve those show/hide tests, if that approach would be acceptable, we can consider writing tests like that from now on

**Comment by gibson042** [comment]
I'm already concerned that those highly related tests span 240 lines, and am not sure that separating them will help things. _However_, QUnit 1.20 supports [nested modules via callback to `module`](http://api.qunitjs.com/QUnit.module/), which would assuage those concerns. So... have at it!

**Comment by markelog** [comment]
> I'm already concerned that those highly related tests span 240 lines, and am not sure that separating them will help things.

It does for every other project, according to many books on the subject and well, other projects code. Also, i don't think it matter how many lines of code it has, i think it matters how well it could be understood and supported.

--

I would like to note, that this ticket not only proposes to rewrite some of the "bad" parts, but i also suggests to write in that manner for every new test.

**Comment by gibson042** [comment]
I would like to refer to https://github.com/jquery/jquery/issues/2880#issuecomment-177578378 as a distinct counterexample. It's fine if we're sufficiently [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), but it's a nightmare while we're not. The problem is "highly related tests" without sufficient abstraction, of which I'm guilty as recently as the tests in question here (but in my defense, we hadn't yet upgraded to a version of QUnit that encourages it).

**Comment by markelog** [comment]
> It's fine if we're sufficiently DRY, but it's a nightmare while we're not

So on one side of the spectre it is fine and on the other it is a nightmare :)

> The problem is "highly related tests" without sufficient abstraction

That an issue too, related, but a bit a different kind i'd say.

> The problem is "highly related tests" without sufficient abstraction, of which I'm guilty as recently as the tests in question here (but in my defense, we hadn't yet upgraded to a version of QUnit that encourages it).

Actually, you could do http://api.qunitjs.com/QUnit.module/#example-0 for long time now, new way is more convenient/explicit but seems it doesn't provide much more to existing functionality.

Just to be clear, that by creating this ticket i'm not pursuing the idea of blaming anyone on anything, Our tests are is the one of the oldest tests on js out there, it seems there is just came to time to update our ideals.

**Comment by mgol** [comment]
This seems to be more of a general guidance ticket rather than a concrete task, @timmywil has been consistently moving such things to the roadmap to not keep zombie tickets open for too long.

**Comment by dmethvin** [comment]
This does seem more like a roadmap item since it's non-specific.

**Comment by markelog** [comment]
I have said above - 

> I'd like to improve those show/hide tests, if that approach would be acceptable, we can consider writing tests like that from now on

so i would like to provide an example of how new tests could be structurized, then discuss in the pull if that approach is acceptable, if it is - land the new show()/hide() tests and maybe add a note to the docs, then close this ticket if it is not, then close this ticket nevertheless.

So i think this is not a zombie ticket, this is "need to find the time to do this" ticket :)

**Comment by timmywil** [comment]
I've waited on adding this to the Roadmap because I'd like to see an example before signing on to do this across all our tests.

**Comment by markelog** [comment]
Since show/hide not gonna change their logic there is no point for me to change it, since no one else seems to be interested in improving current state i'm closing it
