### ISSUE TITLE
Browser support for 4.x

### ISSUE THREAD

**Issue by franciscop** [jquery/jquery#2887]
I've seen there's a milestone for 4.0.0 set up and I would love to know the planned browser support. I've developed [Umbrella JS](http://umbrellajs.com/), a jquery alternative for fun and learning, and I would love to contribute to jquery some of the things that I learned.

One of jquery's main advantage and, in my opinion, handicaps is browser support since it makes the source code much bigger. While 3.0.0 Alpha was released in July 2015 and Beta just now in Jan 2016, **can I assume that version 4.0.0 wouldn't be ready for at least 1-2 years?**

If that is the case, seeing that [browser usage of IE10- halves every year](http://gs.statcounter.com/#desktop+mobile+tablet-browser_version_partially_combined-ww-monthly-201301-201601) and that [Microsoft dropped support for those browsers recently](http://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support), **I propose to make jQuery 4.x release support only IE11**.

This way a lot of modern features could be brought in and reduce greatly the browser-specific code and hacks. A simple example of the possible benefits can be seen in `.addClass()`. For modern browsers ([Umbrella JS](https://github.com/umbrellajs/umbrella/blob/master/src/plugins/addclass/addclass.js)) it can be reduced to this:

```js
u.prototype.addClass = function(){

  // Loop the combination of each node with each argument
  return this.eacharg(arguments, function(el, name){

    // Add the class using the native method
    el.classList.add(name);
  });
};
```

While right now [in jquery](https://github.com/jquery/jquery/blob/a4d16a26abe3ea36337f7bfc4d1bfe13b893cd17/src/attributes/classes.js#L15) it has to be handled manually, avoiding repeating classes and such:

```js
addClass: function( value ) {
  var classes, elem, cur, curValue, clazz, j, finalValue,
    i = 0;

  if ( jQuery.isFunction( value ) ) {
    return this.each( function( j ) {
      jQuery( this ).addClass( value.call( this, j, getClass( this ) ) );
    } );
  }

  if ( typeof value === "string" && value ) {
    classes = value.match( rnotwhite ) || [];

    while ( ( elem = this[ i++ ] ) ) {
      curValue = getClass( elem );
      cur = elem.nodeType === 1 &&
        ( " " + curValue + " " ).replace( rclass, " " );

      if ( cur ) {
        j = 0;
        while ( ( clazz = classes[ j++ ] ) ) {
          if ( cur.indexOf( " " + clazz + " " ) < 0 ) {
            cur += clazz + " ";
          }
        }

        // Only assign if different to avoid unneeded rendering.
        finalValue = jQuery.trim( cur );
        if ( curValue !== finalValue ) {
          elem.setAttribute( "class", finalValue );
        }
      }
    }
  }

  return this;
},
```

**Comment by mgol** [comment]
Thanks for the proposals. We don't yet know when we'll release jQuery 4.0.0 but the time that took us to get to 3.0.0 was too long, I expect we'll be releasing more frequently now (or at least we'll try). Once we get closer to 4.0.0, we'll decide the browser support strategy with the data we'll then have. For now, it's way too early; no need to guess what the landscape will be then.

A few observations:

1. Ember and Angular (even v2!) still support IE9+. We should be more conservative in dropping support for older browsers than them, not less.
2. Even if we dropped IE 9 & 10, we still wouldn't be able to use `classList` as it's not supported on SVG in IE (all versions) and we now support SVG class manipulation. We'd have to drop IE 11 and that surely won't happen for many years to come. Also, the snippets you posted are a little misleading - switching us to `classList` wouldn't remove that much code; you can see what would be the result in [my `jquery-classlist` plugin](https://github.com/mgol/jquery.classList/); e.g. this is its `addClass`:
```js
addClass: function (value) {
    var classes, elem;
    var i = 0;
    var len = this.length;
    var proceed = typeof value === 'string' && value;

    if ($.isFunction(value)) {
        return this.each(function (j) {
            $(this).addClass(value.call(this, j, this.className));
        });
    }

    if (proceed) {
        // The disjunction here is for better compressibility (see removeClass)
        classes = (value || '').match(rnotwhite) || [];

        for (; i < len; i++) {
            elem = this[i];

            if (elem.nodeType === 1) {
                elem.classList.add.apply(elem.classList, classes);
            }
        }
    }

    return this;
},
```
I don't think we'd be able to decrease the library size a lot by dropping IE9-10 only.

**Comment by mgol** [comment]
One more thing, referring to:

> I've developed Umbrella JS, a jquery alternative for fun and learning, and I would love to contribute to jquery some of the things that I learned.

We're open to any ideas about how to improve the jQuery code base so if you have some ideas, please report issues!

**Comment by franciscop** [comment]
I didn't know about SVG support, then that's completely true and such a pity, since that'd be the only problem with IE9-10. The thing is that there are many small things that add up, however it might be more trouble than what it's worth it for a many-people community such as jquery.

I'll try to compile a list later today when I'm able to analyze it in-depth, but from what I see for this particular example, the part where it could be improved best would be code/pattern reuse. The "check if fn then do X, otherwise loop over Y" is spread all over three different functions, and they are even looped in two different ways:

```js
return this.each(function (j) {
for (; i < len; i++) {
```

They could easily be generalized into a more generic function such as [`.eacharg()`](https://github.com/umbrellajs/umbrella/blob/master/src/plugins/eacharg/eacharg.js) for looping on each node-argument pair:

```js
// Definition
u.prototype.eacharg = function(args, callback) {
  return this.each(function(node, i){
    this.args(args, node, i).forEach(function(arg){
      callback.call(this, node, arg);
    });
  });
};

// Usage (['A', 'B', 'C'] could also be 'A B C' or 'A,B,C' or function(){ return 'A B C'; })
u(['a', 'b', 'c']).eacharg(['A', 'B', 'C'], function(minor, major){
  // a A, a B, a C, b A, b B, b C, c A, c B, c C
  console.log(minor, major);
});
```

Inside it, [`.args()`](https://github.com/umbrellajs/umbrella/blob/master/src/umbrella.js#L80) to parse the arguments and make them an array of valid strings:

```js
u.prototype.args = function(args, node, i){
  if (typeof args !== 'string') {
    args = this.slice(args).map(this.str(node, i));
  }
  return args.toString().split(/[\s,]+/).filter(function(e){ return e.length; });
};
```

And finally [`.str()`](https://github.com/umbrellajs/umbrella/blob/master/src/umbrella.js#L66) to make functions a string:

```js
u.prototype.str = function(node, i){
  return function(arg){
    if (typeof arg === 'function') {
      return arg.call(this, node, i);
    }
    return arg.toString();
  }
}
```

You can [then reuse each of these parts](https://github.com/umbrellajs/umbrella/search?utf8=%E2%9C%93&q=each&type=Code) so it all becomes much smaller.

**Comment by franciscop** [comment]
For instance, for your code:

```js
addClass: function (value) {
    var classes, elem;
    var i = 0;
    var len = this.length;
    var proceed = typeof value === 'string' && value;

    if ($.isFunction(value)) {
        return this.each(function (j) {
            $(this).addClass(value.call(this, j, this.className));
        });
    }

    if (proceed) {
        // The disjunction here is for better compressibility (see removeClass)
        classes = (value || '').match(rnotwhite) || [];

        for (; i < len; i++) {
            elem = this[i];

            if (elem.nodeType === 1) {
                elem.classList.add.apply(elem.classList, classes);
            }
        }
    }

    return this;
},
```

You could reduce it to something like this (untested), right?

```js
addClass: function (value) {
    var name = value, classes;

    return this.each(function(j){
        if (elem.nodeType !== 1) return;

        if ($.isFunction(value)) {
            name = value.call(this, j, this.className);
        }
        if (name && typeof name === 'string'){
            classes = (name).match(rnotwhite) || [];
            this.classList.add.apply(this.classList, classes);
        }
    });
```

**Comment by mgol** [comment]
I *think* (I'm not 100% sure) we don't use `this.each` there because it's an additional function call and this is a potentially hot path. It'd be good to have some benchmarks, though.

It's possible we could generalize some patterns & reuse them; if you find something, could you submit PRs for each correction?

Since we've resolved it's too early to assert browser support for 4.0 yet, I'm going to close this issue; we can continue the discussion, though.

Thanks!

**Comment by franciscop** [comment]
I see, so it's mostly a tradeoff between initial load (smaller) vs performance (faster). I'll be sure to add a performance benchmark for each PR; however I've found that [it's highly relative to each browser](https://github.com/jquery/learn.jquery.com/issues/697)

**Comment by dmethvin** [comment]
We're definitely interested in improvements, although 4.0 is far enough away that I don't think we can say what browsers or environments we'll support (remember people use jQuery in places like Chrome/Firefox plugins or node with jsdom as well). Some ideas about what might go into 4.0 are on the [roadmap](https://github.com/jquery/jquery/wiki/Roadmap).
