### ISSUE TITLE
Exception of width/height for oldIE removed incorrectly or/and unfinished

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2888]
Causing test faillure in IE9.

See https://github.com/jquery/jquery/commit/e04e246552c27e872bbf4ae00b55def02b197189
and http://swarm.jquery.org/result/1033320

/cc @timmywil @mgol

**Comment by markelog** [comment]
Can't repro, should fail on http://swarm.jquery.org/result/1084483, but doesn't (including in compat mode), via browserstack

<img width="720" alt="screen shot 2016-02-15 at 22 30 23" src="https://cloud.githubusercontent.com/assets/945528/13058363/d5ca0fac-d433-11e5-86db-29094145e40b.png">

Same thing with saucelabs - 

<img width="536" alt="screen shot 2016-02-15 at 22 34 34" src="https://cloud.githubusercontent.com/assets/945528/13058451/6906fe2e-d434-11e5-8755-798fced2373f.png">

-- 
@mgol could you check if correct browser is spawned in here? If it is, i think someone should verify absence of the failure on the real thing after which we would need to disable this test for ie9.

**Comment by mgol** [comment]
@markelog If it doesn't fail on the BrowserStack IE 9 version then it might be related to being run in an iframe. I'd rather not exclude this test but investigate what's the real reason of the failure as it's easy to mask a real bug in this way.

EDIT: I've joined the swarm manually from IE9 from BrowserStack and it fails, while it doesn't when run outside of TestSwarm.

**Comment by markelog** [comment]
Good catch @mgol! Will check it out

**Comment by markelog** [comment]
Loaded tests from an iframe, still no luck, don't remember how to do

> I've joined the swarm manually from IE9 from BrowserStack

"Joined the swarm", but don't remember what to do next :/. @mgol it seems you have better understanding on how to run this thing, would you mind?

**Comment by mgol** [comment]
When you join the swarm with a recognized (i.e. being in one of the tested browser sets) browser and then schedule a test run on TestSwarm, it will get picked up unless another identical browser gets picked up first. Your one has an advantage, though, of being already spawned. You can go to https://www.browserstack.com/automate and kill the other IE9s if they interfere & then restart the job.

So after joining the swarm you can go to http://swarm.jquery.org/project/jquery, log in (see https://github.com/jquery/infrastructure/wiki/TestSwarm#create-users for login details, this page is private) and restart the failing test. You should see your IE 9 getting the job, running it & failing.

I'm not sure if that's so easy to debug, though... Perhaps copying the HTML+CSS of the page you're on after joining the swarm and setting the iframe URL to the one running the tests for the effects module would reproduce it & give you a better starting point to further debug?... Just an idea.

Good luck! :) Ping me if it's still unclear.
