### ISSUE TITLE
Chrome is deprecating offsetWidth and offsetHeight

### ISSUE THREAD

**Issue by lekoaf** [jquery/jquery#2889]
Got these warnings today when working with my app.

> 'SVGElement.offsetWidth' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.

> 'SVGElement.offsetHeight' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.

They stem from the getWidthOrHeight function on row 5948 in v2.2.0.

**Comment by mgol** [comment]
Thanks for the report! I wasn't aware of these plans and while we don't officially support SVG in most APIs, we've recently switched to `getBoundingClientRect()`, see #1724. This will land in jQuery 3.0.0, you can test the beta at https://code.jquery.com/jquery-3.0.0-beta1.js. We did that mostly to avoid rounding `width`/`height` to integers but it's good to know it has other advantages.

**Comment by lekoaf** [comment]
Thank you for the quick reply. I'll take a look at 3.0.0. :)

**Comment by jeremywadsack** [comment]
This is also [an issue in 1.12 branch](https://github.com/jquery/jquery/blob/1.12-stable/src/css/hiddenVisibleSelectors.js#L27) if the `hidden` filter is applied to an SVG element.

**Comment by mgol** [comment]
@jeremywadsack This is harmless, `undefined < 0` is `false` so when these properties get removed, this method will automatically start using the `getClientRects().length` check.

**Comment by kjantzer** [comment]
This probably isn't the best solution, but it worked for me. I wanted a minimal change without having to affect all my other code and their dependencies.

I changed `$svg.width()` and `$svg.height()` just inside of `peity.register('bar'...`

```
# around line 330
...
, width = $svg[0].width.baseVal.value //$svg.width()
, height = $svg[0].height.baseVal.value//$svg.height()
...

**Comment by jlmakes** [comment]
Is this why `offsetLeft` and `offsetRight` return 0 and `offsetWidth` and `offsetHeight` return undefined on on `<g>` tags?

The "problem" I have with `getBoundingClientRect()` is that it includes CSS transforms in the returned coordinates, whereas offsets return values that ignore CSS transforms — which is essential for one of my projects.
