### ISSUE TITLE
npm package doesn't have any documentation

### ISSUE THREAD

**Issue by cageygee3** [jquery/jquery#2893]
I'm referring to the page here: https://www.npmjs.com/package/jquery

At the very least, there should be some example usage so people know how to import the library and use it. At the very _very_ least, show people this:

`import $ from 'jquery';`

**Comment by timmywil** [comment]
You make a good point. The distribution repo should have general information. I'd say the least would be a link to jQuery documentation, but we could also include information on the most common ways to include the library: es6 imports in environments that support it (which is none yet), es6 + babel, require in node, require + webpack, require + browserify, amd, and a script tag.
