### ISSUE TITLE
Upgrade from jquery 1.10 to 1.12 breaks bootstrap dropdowns

### ISSUE THREAD

**Issue by cullub** [jquery/jquery#2894]
The upgrade from jQuery 1.10 to 1.12 breaks bootstrap dropdowns.

**Comment by mgol** [comment]
How does it break? Please provide a more detailed explanation.

**Comment by dmethvin** [comment]
Most likely it's #2836 which has been fixed in master. I'll close it on that assumption, but if it's something else please provide a test case and we can reopen.

**Comment by cullub** [comment]
I'm sorry - I guess I didn't do my testing quite right :)  Evedently had simply typed the link to jquery 1.12 wrong.  Turns out it's a non-issue.  Thanks!!
