### ISSUE TITLE
SVGElement.offsetParent will be removed in Chrome around April 2016

### ISSUE THREAD

**Issue by agcolom** [jquery/jquery#2895]
Google Chrome says: 'SVGElement.offsetParent' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details."

This may have been on your radar already?... may also have implications over gh-1765

**Comment by mgol** [comment]
Thanks for the info. Related: #2889. I'm not sure if we support this scenario, our SVG support is very limited, basically only interoperability with HTML & class manip.

**Comment by agcolom** [comment]
For example, I'm getting the position of an svg element using position().left and position().top which works great, but apparently will stop working after Chrome removes SVGElement.offsetParent.

**Comment by mgol** [comment]
Yeah, but it seems there's no good replacement. Too bad they're removing an API without providing such a replacement; the Chrome status dashboard erroneously says `getBoundingClientRect()` is a replacement but it's not for `offsetParent`. I'd really like them to not remove it before a new API is ready.

See https://github.com/jquery/jquery/issues/1765#issuecomment-117898366; I didn't have time back then but maybe we should suggest sth to CSSOM that would fill in this role? Who would be best to pursue that? @kborchers, do you know?

Considering the Chrome team plans for M50 this seems pretty urgent. @paulirish, could you chime in?

**Comment by paulirish** [comment]
crbug: https://code.google.com/p/chromium/issues/detail?id=463116
blink-dev thread: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/JlAEmQpWMWA/63acYbmdDwAJ

i would suggest someone here chime in on the bug. and ask philip and boris about some of the jquery usecases and if gBCR can be used.

**Comment by dmethvin** [comment]
I've posted in the blink-dev thread.

**Comment by bzbarsky** [comment]
Note that `offsetParent` doesn't exist on SVG elements in Firefox and never has, for what it's worth.  So I doubt whatever @agcolom is doing actually "works great" unless we have different definitions of "great".

**Comment by dmethvin** [comment]
@agcolom can you post a minimal test case?

**Comment by foolip** [comment]
It's true that there's no replacement for `offsetParent`, may I ask to see the code that was using it? If it's deployed on the web, does it have another code path for Firefox?

**Comment by mgol** [comment]
In general you can find offsetParent usages in jQuery UI (
https://github.com/jquery/jquery-ui/search?utf8=%E2%9C%93&q=offsetParent),
the jQuery mousewheel plugin relies on it as well (
https://github.com/jquery/jquery-mousewheel/blob/b1c062e93b44f473022297c386d57fa7e58b6aae/jquery.mousewheel.js#L65).


This is a general usage, not SVG-specific, though.

**Comment by agcolom** [comment]
I tried to knock something up quickly and both Chrome and Firefox give me different results, so I need look into it a bit more and it may well be that my code "didn't work great" and was pure fluke that I was getting the correct results.... and I may have to go and hide in a cave ;-) 
I'll try to do this this afternoon (got to get ready and go to work now for some meetings).

**Comment by markelog** [comment]
> doesn't exist on SVG elements in Firefox 

It also shouldn't exist in IE too btw.

That is interesting though, judging by the this and previous discussion it seems we should consider changing our logic in `dimensions` module by try to not using offset* properties for 4.0, since it seems those properties on the road for removal for the HTMLElement too.

**Comment by mgol** [comment]
> since it seems those properties on the road for removal from the HTMLElement too.

I don't think this will ever happen. This would basically break all current jQueries in use and that's an extremely high number, no one would do such a thing.

**Comment by mgol** [comment]
(that doesn't change the fact that it's worth to stop using APIs considered deprecated & legacy, though)

**Comment by foolip** [comment]
Right, there is roughly zero chance that any browser will attempt removing offset* from HTMLElement. We measure usage of things before deprecation/removal in Blink, and these are certainly used *far* too widely.

**Comment by markelog** [comment]
Maybe i didn't articulate this right, but i didn't mean we should hurry up and do something ASAP. 

> We measure usage of things before deprecation/removal in Blink, and these are certainly used far too widely.

Aside from vendors measuring the usage some of constructions, some of the also integrated tests of the popular libs in their tests process and that behaviour in the spec.

So i'm sure no one will removed them tomorrow, but it seems it will be removed **eventually**,  since those properties already do not take into the account new features and new specs, they basically deprecated.

**Comment by markelog** [comment]
So i think it would be a good idea to consider changing API and behaviour for next major because of things i have mentioned above.

**Comment by mgol** [comment]
> but it seems it will be removed **eventually**

You're an optimist. :) Unless "eventually" means "in 15 years". But I agree we should switch the implementation anyway.

**Comment by bzbarsky** [comment]
No one is planning to remove offset*.  That said, switching away from it is a good idea anyway because it lies: the fact that it returns integer CSS pixels means it often gives incorrect answers in a world of high-dpi screens and subpixel text layout.

With my browser developer hat on, I would love to understand the exact use cases here so we can expose better APIs for accomplishing them.

**Comment by agcolom** [comment]
@bzbarsky @foolip My use case is as follows: I'm developing a tool for my students (to help them learn programming) that will draw a flow chart in svg that is a graphical representation of their code. I'm writing everything from scratch in JavaScript, and the output of that part is the flowchart composed on various svg elements (ellipse, text, rectangles, polygons, polylines). A statement for example is in this order: line down, polyline (to represent the arrow), retangle and text inside the rectangle. 

Until today, when I was drawing the end of an if/else statement, I would check whether there was already an arrow (which I draw using the polyline) at the end position of the longest branch. There was one if I had just closed another if/else statement (which I no longer have now so I no longer need to detect it). If there isn't one (always the case now hopefully), I drawn a line down before going horizontally to meet the other branch half-way between this branch and the other one. I could not use elementFromPoint for that because there was no guarantee that the element at that position will be in view (if it's in the hidden part of a div (i.e. you need to scroll to get to it), everything crashes). So instead, I checked the polyline positions compare it against the position at which I was about to draw. 

You are absolutely correct that ```position().top``` and ```position().left``` on the svg element return a different value (off by a few pixels) between Chrome and Firefox. Chrome gives me what I would expect (i.e. if I draw a line from (120, 80), the left and top positions will be those values). Firefox is off by a few pixels. However, if you get the position as a value from another element that you have on your page for reference, the difference between that and the position you are looking at seems to be consistent between both browsers, so you can use a "reference point".  

I have now changed this and no longer require to detect the svg element position. I will let you know if I get a new case where I require this. However, this may make you think of some other use cases... 

PS: In future, it would be nice to leave sarcasm out of github comments. This is not terribly useful and tends to drive people away from contributing to open source.

**Comment by bzbarsky** [comment]
@agcolom OK, so the specific use case here is to find the position of an element on the page in general, or relative to some other element?  Ignoring transforms for the moment (which should be OK, since offset* don't handle those anyway in any sane way), that would be covered by getBoundingClientRect.  If transforms are involved things get a bit more complicated, but there are APIs being added to handle that too.

Apologies for the perceived sarcasm.  That wasn't the intention at all; it was meant to be an acknowledgement of the fact that people do in fact have different definitions of what "works great" means, depending on their exact situations.  :(

**Comment by agcolom** [comment]
@bzbarsky Thank you :-) Yes, I was just trying to find whether there was a specific element at the position at which I was about to draw. I'd imagine that could be a common use case.

**Comment by foolip** [comment]
@agcolom 
> You are absolutely correct that `position().top` and `position().left` on the svg element return a different value (off by a few pixels) between Chrome and Firefox. Chrome gives me what I would expect (i.e. if I draw a line from (120, 80), the left and top positions will be those values). Firefox is off by a few pixels.

Hmm, does `position().top` return something useful in Firefox and Edge as well as Chrome, or was this for HTML elements? (I haven't looked at how jQuery implements `position()`, perhaps the answer lies within.)

**Comment by foolip** [comment]
jQuery maintainers, is this and https://github.com/jquery/jquery/issues/2889 the only issues you have heard about this deprecation? Based on the volume of feedback compared to other changes in the past, do you have any clue how painful an actual removal would be for users of jQuery?

**Comment by agcolom** [comment]
Ok, no wonder I was getting *very* confused. jQuery 1.12.0 and jQuery 3 alpha 1 do not give the same results for ```position().top``` and ```position().left```... I'll upload a very simple test case now

**Comment by agcolom** [comment]
http://jsbin.com/yifebunuqe/edit?html,js,console,output with jQuery 1.12.0
http://jsbin.com/gucuhoreli/1/edit?html,js,console,output with jQuery 1.3.0alpha1

**Comment by mgol** [comment]
The `.position()` changes are most likely #2828.

> jQuery 1.3.0alpha1

You mean 3.0.0-alpha1? :) BTW, 3.0.0-beta1 is out, a version with that one:
http://jsbin.com/qaxexe/edit?html,js,console,output

**Comment by Risingson** [comment]
i fixed in 2.1.0 via `if ( this instanceof SVGElement ) { var offsetParent = this.parentNode`
worked for me. no pro here though.

**Comment by mgol** [comment]
@scottgonzalez @arschmitz AFAIK UI uses `offsetParent`, could you present a couple of use cases so that we get a new appropriate API specced considering that `offsetParent` is now considered a legacy API?

**Comment by scottgonzalez** [comment]
The only uses are in draggable and sortable and those will be rewritten from scratch. I don't think any uses of `.offsetParent()` will persist through the rewrites.

**Comment by mgol** [comment]
It seems no one really needs an `offsetParent` equivalent in non-legacy APIs so I'll close this issue. We don't support SVG nodes with a few exceptions and since `offsetParent` was never implemented in every popular browser, no web-facing code should depend on it.

**Comment by idontusenumbers** [comment]
Are there plans to patch jquery so calling $('*:visible') wont crash in Chrome M50? I quickly slimmed through all these comments; it seems the determination is 'dont support offsetParent for SVGs'. Regardless of how many people want or dont want that support, jquery still shouldn't error when it encounters these elements.

**Comment by foolip** [comment]
@idontusenumbers, a crash, or even an exception, won't happen when these attributes are removed. What will happen is that if you're using jQuery older than 2.2.0, the `:visible` selector will match no SVG element and `:hidden` will match all SVG elements, i.e. SVG elements are always considered hidden.

With jQuery 2.2.0 (https://github.com/jquery/jquery/commit/79bcb291324167ab2d844027d0cdc6300613d010) this has been fixed and you shouldn't need to do anything at all.
