### ISSUE TITLE
Ignore Sizzle working with AMD modules

### ISSUE THREAD

**Issue by lagden** [jquery/jquery#2898]
Hi everyone!

I am using **jQuery** with **Requirejs(AMD)** and I just wanna use the Ajax module.
Everything is working fine, but I am obligated to config **Sizzle**.

Is there anyway to avoid or ignore **Sizzle** working directly with **AMD** modules?

Here is my lab: https://github.com/lagden/router5-playground/tree/jquery (`branch jquery`)

**config.js**
```javascript
define('config', function () {
	requirejs.config({
		baseUrl: '/',
		paths: {
			sizzle: '/sizzle/dist/sizzle.min',
			jquery: '/jquery/src'
		}
	});
});
```

**app.js**
```javascript
require(['./config'], function () {
	require(['jquery/ajax', 'jquery/ajax/xhr'], function ($) {
		var $out = $('#out');
		// Callback
		function cb(r) {
			$out[0].textContent = JSON.stringify(r);
		}
		// Test Ajax
		$.getJSON('http://randomuser.me/g/')
			.done(cb)
			.fail(err => {
				console.log(err);
			})
			.always(r => {
				console.log('sempre!!!');
			});
	});
});
```

Tks!

**Comment by timmywil** [comment]
I suppose we could hard code the path to sizzle, but given that sizzle is a separate module, we're it as a path that could be changed. Then again, we don't keep it in node_modules.

**Comment by mgol** [comment]
Would hardcoding the path to Sizzle prevent users from re-setting it to something else?

**Comment by lagden** [comment]
I believe the solution could be simple.
I just would remove the `src/selector.js` and leave the `src/selector-sizzle`.

If the guy wants to use the **sizzle** he does so:

**app.js** with **Sizzle**
```javascript
require(['jquery/core', 'jquery/selector-sizzle'], $ => {
	// Sizzle selector
	$result = $('body').find('> #result');
	console.log($result)
});
```

else use the own **jQuery** selector:

**app.js** without **Sizzle**
```javascript
require(['jquery/core'], $ => {
	// Default selector
	$result = $('body').find('> #result');
	console.log($result)
});
```

Totally modular and optional!

**Comment by timmywil** [comment]
Unfortunately, that solution won't work. We have an alternative selector engine that gets swapped in when sizzle is removed in a custom build. Also, we'd still have to hardcode the path to sizzle in selector-sizzle.

**Comment by timmywil** [comment]
@mgol To answer your question, the path to sizzle could be changed, but I think it would look like this...

```json
"sizzle/dist/sizzle": "another/path/to/sizzle"
```

**Comment by dmethvin** [comment]
It looks like the only reason ajax.js potentially needs the `jQuery()` constructor is for the one rare call related to `callbackContext`? According to the docs that must be a DOM object, so we're not even calling Sizzle for any supported case. It might be possible to avoid pulling in a selector engine with some refactoring.

**Comment by AutumnsWindsCat** [comment]
Good morning

**Comment by timmywil** [comment]
This turned out to be easier than I thought. I think I was originally thinking that the Sizzle position could change if we used it from bower or node modules, but given that Sizzle's position is static in our repo (the external folder), I think it's safe to use that path.

**Comment by lagden** [comment]
@timmywil But the `selector.js` is still forcing Sizzle!!!

Is it possible make as follows?

```javascript
// my app config
requirejs.config({
	config: {
		'sizzle': true
	},
	// continue...
});
```

```javascript
// ./selector.js
define(function (require, module) {
	var useSizzle = module.config().sizzle || false;
	if (useSizzle) {
		require('./selector-sizzle');
	} else {
		require('./selector-native');
	}
});
```

My only doubt is:
The option `config` is an AMD standard or is it only possible with RequireJS?

**Comment by timmywil** [comment]
@lagden That's a different issue. My plan was to fix having to specify the path for sizzle, and that's been done. Sizzle will continue to be the default selector engine (and it should be). `selector-native` is a module that is swapped in during build time. We want users to be very explicit about swapping that module, after having considered the dangers (no qsa bug fixes that still apply to modern browsers, no selector extensions, no fix for the qsa scope issue, etc).

That said, it's still possible to specify that you'd like to use selector-native instead of sizzle in AMD mode...

```
require.config( {
	map: {
		"src/selector": {
			"src/selector-sizzle": "src/selector-native"
		}
	}
} );
```

**Comment by lagden** [comment]
@timmywil wow!! much better! tks!
