### ISSUE TITLE
Focus in/out/blur Test Reliability

### ISSUE THREAD

**Issue by zackhall** [jquery/jquery#2904]
I'm seeing the following two test failures intermittently on Edge and Chrome. These tests have also been explicitly disabled for Firefox at [/test/unit/event.js#L2895](https://github.com/jquery/jquery/blob/master/test/unit/event.js#L2895) because they're unreliable.

Do you have recommendations for improving the reliability of these tests? I'd be happy to help out with a pull request.

```

1. event: Check order of focusin/focusout events (1, 1, 2)Rerun50 ms

     1.Expected 2 assertions, but 1 were run@ 50 ms
        Source: at Global code (http://.../TestContent/jquery/master/test/unit/event.js:2896:2)

```
 
```
2. event: focus-blur order (#12868) (2, 3, 5)Rerun161 ms
    1. text focus@ 105 ms
    Source:     at Anonymous function (http://.../TestContent/jquery/master/test/unit/event.js:2941:6)
    at o.event.dispatch (http://.../TestContent/jquery/master/dist/jquery.min.js:3:9551)
    at r.handle (http://.../TestContent/jquery/master/dist/jquery.min.js:3:7643)
 

    2. Expected 5 assertions, but 4 were run @ 160 ms
    Source: at Global code (http://.../TestContent/jquery/master/test/unit/event.js:2925:2)
```

**Comment by mgol** [comment]
You need to have the browser window (& the tab in which you run the tests) focused for the duration of the test; in that case we haven't noticed those tests to be flakey, our CI doesn't fail randomly on those tests (except in Firefox where even giving the window focus didn't always help so we disabled it). Do you have other observations?

**Comment by dmethvin** [comment]
I wish there was some way to make things more reliable, but I think we're just in a crazy edge case where the browser doesn't expect focus to be bouncing around inside the page while the browser window is in the background. If you're seeing failures while the browser is in foreground and you're not messing with the window during tests, then there may be something we need to investigate.

**Comment by markelog** [comment]
Introduction of intergration tests should fix these issues - https://github.com/jquery/jquery/issues/2078 they are also on our [roadmap](https://github.com/jquery/jquery/wiki/Roadmap) btw.

Feel free to explore it or provide alternative solutions.
