### ISSUE TITLE
Absolutely positioned inline elements become block-level after using hide() and show()

### ISSUE THREAD

**Issue by vibeke** [jquery/jquery#2905]
Test case: [http://codepen.io/anon/pen/rxqzKO](http://codepen.io/anon/pen/rxqzKO)

As the test case shows, even when an inline element has display: inline explicitly stated in the css, after using hide() before show(), jQuery sets it to display: block. This happens only on elements with position:absolute.

I reproduced the bug in the following environments:
Chrome 48.0.2564.97/OS X 10.11.3
Firefox 42/OS X 10.11.3
Firefox 44/OS X 10.11.3
Opera 35/OS X 10.11.3
Firefox 44/Windows 7
Edge 12/Windows 10

The bug did not occur in IE 9/Windows 7, IE 10/Windows 8, or IE 11/Windows 10 (I did not test any other Internet Explorer versions).

The bug also occured using jQuery Core 1.12.0.

**Comment by markelog** [comment]
Before jQuery hides something, it remembers the **computed** display, so when `show()` is called, it would set previous display.

Elements that has `position:absolute` or `fixed`, forces the `display` value, in this case (or pretty much any other case) computed property will have `block` value - https://www.w3.org/TR/CSS21/visuren.html#dis-pos-flo

**Comment by mgol** [comment]
An excellent bug report, with test cases and a clear description. :)

Note that we're changing the `show()`/`hide()` logic in jQuery 3.0.0; there are still some changes planned but you may check what's the current development version at https://code.jquery.com/jquery-git.js or the `3.0.0` beta at https://code.jquery.com/jquery-3.0.0-beta1.js. If you tried to use `show()`/`hide()` with those versions and checked if the behavior is fine or if you experience any problem with that, it'd be great!

**Comment by vibeke** [comment]
Thanks! I tried both versions, and the absolutely positioned span gets (what I now know to be) the correct `display` value of `block` the first time it's shown as well. So I guess the bug was just opposite of what I thought it was.
