### ISSUE TITLE
Add tests certifying offset isn't broken after a recent revert

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#2909]
Basically, we need tests certifying #2828 & #2836 work after the revert done in 49833f7795d665ff1d543c4f71f29fca95b567e9. We should land them on all 3 branches.

**Comment by markelog** [comment]
> We should land them on all 3 branches.

mm, doesn't seem worth it, but okay

**Comment by mgol** [comment]
Thanks. :)

**Comment by mgol** [comment]
@markelog Those tests are broken on all browsers, both [on `2.2-stable`](http://swarm.jquery.org/job/2281) and [on `1.12-stable`](http://swarm.jquery.org/job/2283). Could you fix? I'll reopen for now.

**Comment by mgol** [comment]
This seems to be caused by using `$` instead of `jQuery`. I'm surprised it works on `master`, is this test using a correct jQuery version?

**Comment by mgol** [comment]
Also, I've noticed this only now but the variable to which you assign `assert.async()` should be called `done`, not `stop`, to better align with other tests (in the previous nomenclature it would be called `start`, not `stop` so it was different than usual either way).

**Comment by markelog** [comment]
For some reason that does work with amd, that's reason i missed it.

> should be called done, not stop

I think it is fine as is.

**Comment by mgol** [comment]
> I think it is fine as is.

It's not stopping anything, it just notifies the test runner it's finished. It was called `start` in the old API as it was resuming the test suite (after calling `stop()` before).

It's also almost universally called `done`, both by other test runners and in our code that has switched to the new API. This is now the only place in the whole suite where it's called `stop`.

**Comment by markelog** [comment]
> it just notifies the test runner it's finished

And that whole process is called stopping, which is synonym of "finished".

I think we are free to choice the name of our variables as long as those names sufficiently reflects their purpose.
