### ISSUE TITLE
.each iterator skip the first element

### ISSUE THREAD

**Issue by alfredopacino** [jquery/jquery#2911]
I'm sure i'm messing something, but it's really strage, this is my code:
```
<form id="add_court1" data-method="async">
    <input type="button" value="add">
</form>
<br>
<form id="add_rcourt2" data-method="async">
     <input type="button" value="add">
</form>
```

```
$( document ).ready(function() {
    $('[data-method="async"]').each(function() {
        console.log($(this))
    });
});
```

The result is just 1 reference to the second form.
(jQuery v2.2.0)

**Comment by alecpl** [comment]
Works for me. What browser, could you create a fiddle at http://jsfiddle.net?

**Comment by alfredopacino** [comment]
https://jsfiddle.net/alfredopacino/vLpm8xzx/

**Comment by scottgonzalez** [comment]
The DOM is not what you expect in that fiddle. Nested forms are strange things and the second form (the first `<form data-method="async">`) is removed during parsing by the browser. You end up with two top-level forms, not two nested forms. Given the actual DOM structure, jQuery is behaving correctly.

**Comment by alfredopacino** [comment]
i'm sorry I didn't notice the DOM..ok thanks
