### ISSUE TITLE
jQuery.removeProp("disabled") does not enable input after disabling with jQuery.prop("disabled", true)

### ISSUE THREAD

**Issue by marques-work** [jquery/jquery#2913]
I recently upgraded to 2.2.0 from 1.9.1, and I noticed this change in behavior.

```javascript
var input = $("<input type='text'/>");
console.log(input.is(":disabled")); // false, as we would expect

input.prop("disabled", true);
console.log(input.is(":disabled")); // true

input.removeProp("disabled");
console.log(input.is(":disabled")); // expected: false, actual: true

// input.prop("disabled", false) or input.removeAttr("disabled") reenable the input
```

**Comment by dmethvin** [comment]
http://api.jquery.com/removeprop/

> Note: Do not use this method to remove native properties such as checked, disabled, or selected. This will remove the property completely and, once removed, cannot be added again to element. Use .prop() to set these properties to false instead.
