### ISSUE TITLE
e.preventDefault() is undefined

### ISSUE THREAD

**Issue by ryantse** [jquery/jquery#2917]
In commit b4be64dd9b3207e68ac5095389285f3538ed81a6, the check to ensure that `e.preventDefault` exists was defined was removed on line 691, I believe that though it may seem to be redundant guards, there are no checks in place to ensure that the original event is actually an event that conforms with the expectations of an event (namely, containing a `preventDefault` method) rather than just a JSON object that contains the bare minimum.

For example, a bare minimum `originalEvent` may look like this (pulled from jQuery Mobile's method):
````
popstateEvent = new $.Event( "popstate" );
popstateEvent.originalEvent = {
    type: "popstate",
    state: null
};
````

However, in the case that jQuery Mobile is used, a call to the jQuery.mobile.Navigator.go function creates a `jQuery.Event("popstate")` that has an `originalEvent` that does not contain a `preventDefault` method. Thus, when `jQuery.Event.preventDefault` is called, the `originalEvent` check fails to detect that the event does not in-fact have a `preventDefault` function.

This may be an issue that needs to be addressed on the jQuery Mobile side. But, I traced it back to here and, historically, the check existed which causes this issue to pop-up on newer versions of jQuery with jQuery Mobile.

**Comment by dmethvin** [comment]
If `originalEvent` was a `jQuery.Event` all would be fine. I'm not really sure what Mobile is trying to do by adding a plain-object property there, @arschmitz can you clarify?

**Comment by arschmitz** [comment]
this was a bug and fixed on our side 

see current code
https://github.com/jquery/jquery-mobile/blob/1.5-dev/js/navigation/navigator.js#L153-L154

**Comment by arschmitz** [comment]
for reference see
https://github.com/jquery/jquery/issues/2300
and
https://github.com/jquery/jquery/pull/2303

**Comment by dmethvin** [comment]
Oh yeah, I remembered that ticket vaguely but thought it was in the old tracker! Thanks.
