### ISSUE TITLE
Removing parent node during event bubbling doesn't have the same result as pure javascript code

### ISSUE THREAD

**Issue by Getfree** [jquery/jquery#2918]
In the following code, clicking the button triggers a form submission in Google Chome 48.
```html
<form>
	<button>ok</button>
</form>
<script>
$(function(){
	$('form').submit(false) ;
	$('button').click(function(){ $('form').remove() }) ;
}) ;
</script>
```
However, the same test case without using jQuery does not trigger a form submission.
```html
<form onsubmit="return false">  
    <button onclick="form.remove()">ok</button>
</form>
```

**What's the expected behavior?**
Both examples should be functionally equivalent.

**Browsers affected:** Google Chrome 48
**jQuery version tested:** jQuery 2.2

Also tested in Firefox 43, but the problem does not happen there.

**Comment by dmethvin** [comment]
For jQuery's code and for standard `addEventListener` the [UI Events spec](https://www.w3.org/TR/uievents/#event-flow) should apply.

> Event objects are dispatched to an event target. At the beginning of the dispatch, implementations MUST first determine the event object's propagation path. ... For DOM implementations, this applies even if an element in the propagation path is moved within the DOM **or removed from the DOM**.

The `onclick` attribute is part of the ancient DOM0 behavior from the 1990s and not covered by that standard. I don't know what it does when you pull the rug out from under it.

Can you clarify which case you consider to be the "problem" with an example on jsbin.com or jsfiddle.net?

**Comment by Getfree** [comment]
Inline event handlers don't follow the same specification as those attached with addEventListener?
Didn't know that.
My assumption was that both codes should be functionally equivalent.
But in light of what you've said, the jQuery-less version that's functionally equivalent would be more like this:
```html
<form>
	<button>ok</button>
</form>
<script>
document.querySelector('form').addEventListener('submit',function(){ return false }) ;
document.querySelector('button').addEventListener('click',function(evt){ evt.target.form.remove() }) ;
</script>
```
And this does indeed behave the same way as the jQuery version.
So, it's not a jQuery bug.

**Comment by mgol** [comment]
@Getfree Thanks for following up. I'm closing this ticket them.
