### ISSUE TITLE
$.ajax using 'context' settings sets Content-Type for GET requests

### ISSUE THREAD

**Issue by tuespetre** [jquery/jquery#2928]
Example:

```
$.ajaxSetup({
    statusCode: {
        401: function () {
            var $settings = this;
            var auth = $('link[rel~=authenticate]').prop('href');
            var opts = { xhrFields: { withCredentials: true } };

            $.ajax(auth, opts)
                .done(function () {
                    $.ajax($settings);
                })
                .fail(function () {
                    showErrorModalOrSomething();
                });
        }
    }
});

// This causes the statusCode handler above to trigger, which in turn
// sends the re-authentication request (which is successful) and then
// retries this same request. But when it retries this same request, 
// the Content-Type header for the GET request is set to 
// 'application-x-www-form-urlencoded' (due to the $settings object above),
// which has undesirable side effects with certain server-side frameworks

$.get(urlThatResultsIn401AtFirst, function (partial) {
    getModal().find('.modal-dialog').html(partial);
});
```

I would like to use this same handling across both GET and POST requests. I am open to workarounds if anyone has an idea.

**Comment by tuespetre** [comment]
Workaround that I have applied for now:

```
if ($settings.type == 'GET') {
    $settings.contentType = null;
}
```

**Comment by dmethvin** [comment]
This seems like a support request rather than a bug report or feature request. Can you start on StackOverflow and see if they can help?

**Comment by tuespetre** [comment]
@dmethvin no support needed; I already found a workaround for this issue. I did post with the primary intent of reporting the issue, and the secondary intent of "By the way, if you have thoughts on a temporary fix..."

The issue is that the second time around on the request, passing in the same AJAX settings used from the first request, the `Content-Type` header is being sent when it should not be.

**Comment by dmethvin** [comment]
To investigate we'd need a repro case, version of jQuery being used, etc. The code snippet above isn't enough for us to help you, or for you to help us if you feel that it needs to be addressed inside jQuery itself.

**Comment by tuespetre** [comment]
Will provide. Thanks

**Comment by tuespetre** [comment]
Here she is: https://github.com/tuespetre/jquery-2928

**Comment by dmethvin** [comment]
Looks correct to me, the `contentType` is set to its default since it wasn't specified in the original request, as mentioned in the `jQuery.ajax` [API docs](http://api.jquery.com/jquery.ajax/). If the server wants a different value you should set it in the options.

**Comment by tuespetre** [comment]
@dmethvin: that is fine if it is supposed to be the default value, but please consider:

- `Content-Type` makes virtually no sense on a `GET` request
- The current implementation is inconsistent. Why would the default header not be set for the first request, but be set on the options the second time around?
