### ISSUE TITLE
Add ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE files

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#2929]
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

To avoid cluttering the root of the repo, they also support a `.github` folder for this file. Should we take advantage of that?

Not sure what form the issue template should take, it would be good to look at some examples. I like the idea of a checklist.

I think the PR template can be really simple, asking people to reference any ticket and reminding them to sign the CLA.

**Comment by markelog** [comment]
> examples

From https://github.com/sindresorhus/generator-nm/issues/44#issuecomment-185402528,

dear-github/dear-github#125
https://github.com/nodejs/node/pull/5291/files
rails/rails#23738
https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md
https://github.com/capistrano/capistrano/pull/1583/files
https://github.com/rubinius/rubinius/pull/3621/files
https://github.com/ensime/ensime-server/pull/1301/files
https://github.com/thumbor/thumbor/pull/668/files
GoogleCloudPlatform/gcloud-common#96
dotnet/corefx#6167
https://github.com/summernote/summernote/pull/1694/files
golang/go#14365
https://github.com/Microsoft/TypeScript/pull/7120/files
https://github.com/chef/chef/pull/4590/files

**Comment by zenorocha** [comment]
https://github.com/devspace/awesome-github-templates ;)

**Comment by markelog** [comment]
@zenorocha Wow, nice, thank you!

**Comment by TalAter** [comment]
I've created a generator for issue and pull request templates. It asks you a few questions about your project, and creates templates customized to your project.

Might be helpful here.
https://www.talater.com/open-source-templates/

**Comment by markelog** [comment]
@TalAter not sure if we gonna use it, but that's so cool, really enjoyed reading it!
