### ISSUE TITLE
Figure out (and fix) why it is possible to use `$` variable 

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2930]
In master branch when builded.

And for all other branches when builded on the run with `amd`.

Such use should throw an error right away.

See https://github.com/jquery/jquery/commit/7dbf1c1b2b6fe524cbada15d2cd514bf3627fc26#commitcomment-16099036

**Comment by timmywil** [comment]
Maybe there's a supportjQuery global lying around?

**Comment by dmethvin** [comment]
I'm seeing it on master but only if used with AMD. I think what is happening is that in AMD mode [testinit.js still runs its global code synchronously](https://github.com/jquery/jquery/blob/12038c7234ed808b2116a9f03c448c139d5fb9ae/test/data/testinit.js#L13-L16) and then [jQuery loads async](https://github.com/jquery/jquery/blob/12038c7234ed808b2116a9f03c448c139d5fb9ae/test/jquery.js#L19-32), which then [adds back a `$`](https://github.com/jquery/jquery/blob/12038c7234ed808b2116a9f03c448c139d5fb9ae/src/jquery.js#L36).

**Comment by mgol** [comment]
Changing `jQuery` back to `$` in 7dbf1c1b2b6fe524cbada15d2cd514bf3627fc26 causes an error for me locally. Perhaps the variable is only available on TestSwarm?

**Comment by mgol** [comment]
> Maybe there's a supportjQuery global lying around?

It is, at least in AMD mode.

**Comment by timmywil** [comment]
I think @dmethvin nailed it. I'll take a look for 3.1.1.
