### ISSUE TITLE
.ajax() doesn't emit textStatus: 'timeout' error when a 504 Gateway Timeout occurred

### ISSUE THREAD

**Issue by LionNatsu** [jquery/jquery#2932]
When 504 error occurred, callback `error`'s parameter `textStatus` is just an **`'error'`**.
(prototype: ` error: function( jqXHR jqXHR, String textStatus, String errorThrown )` )

`textStatus` should be `'timeout'` according to the RFC2616's description for 504 error. Though there's some conflicts when I try to comprehend how jQuery.ajax() should do when there's a gateway timeout in [jQuery API documentation](http://api.jquery.com/jQuery.ajax/):
> #### error
> Type: Function( jqXHR jqXHR, String textStatus, String errorThrown )
> A function to be called if the request fails. The function receives three arguments: The jqXHR (...) object, **a string describing the type of error that occurred** and an optional exception object, if one occurred. Possible values for the second argument (besides `null`) are **`"timeout"`**, `"error"`, `"abort"`, and `"parsererror"`. When an HTTP error occurs, `errorThrown` receives the textual portion of the HTTP status, such as "Not Found" or "Internal Server Error." As of jQuery 1.5, ... . Note: This handler is not called for cross-domain ... .

`504 Gateway Timeout` error usually occurs when it use a long-time-pending request to wait for some events but there's a **proxy / reverse proxy**, especially reverse proxy such as *nginx vhost*. That means: once the proxy configuration of gateway set a smaller timeout limit than the browser or ajax's `timeout `option, never a `timeout` error can get.

Here's part of [RFC2616 Hypertext Transfer Protocol -- HTTP/1.1](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.5) for reference.
> ### 10.5.5 504 Gateway Timeout
> 
> The server, while acting as a gateway or proxy, did not receive a timely response from the upstream server specified by the URI (e.g. HTTP, FTP, LDAP) or some other auxiliary server (e.g. DNS) it needed to access in attempting to complete the request.
> 
>       Note: Note to implementors: some deployed proxies are known to
>       return 400 or 500 when DNS lookups time out.

**Comment by dmethvin** [comment]
The dilemma here is that the `jqXHR.statusText` of `"timeout"` is defined to be that the timeout period specified in the `$.ajax` request has elapsed. This would co-opt it to also mean that other components in the network chain are reporting their own timeout periods, independent of the one (if any) specified by the caller in their `$.ajax` call. So although this change seems almost trivial, it could easily have compatibility impacts.

How does it help your code to have `"timeout"` reported?

**Comment by LionNatsu** [comment]
I used `text == "timeout"` as the condition which cause ajax failed because time-out, but now have to code `text == "timeout" || xhr.status == 504` (AOSC-Dev/website-site-ng@2d36c254037f2df09e1d0ea6d31e66f4f83bd470). Then I realized I need `text == "timeout" || xhr.status == 504` everywhere to express the condition  that "the AJAX time-out".

At least, in implementation, event "upstream server was time-out" may caused by this two condition, and these cannot mean another thing except of "upstream server was time-out", one is "I said", the other is "the gateway said". So it may contain the later condition --- here's all of the chain.

On the opposite, as the RFC2616 says: *some deployed proxies are known to return 400 or 500 when DNS lookups time out.* However `400 Bad Request` and `500 Internal Server Error` is fuzzy and unclear, those cannot tell what (eg. timeout) exactly happened. `504 Gateway Timeout` is clear enough.

**Comment by dmethvin** [comment]
Since 504 is clear about what happened I would say that co-opting `"timeout"` is even less necessary. Just checking the status seems like the right thing to do. That way you separate a "timeout somewhere in the network" case from a "timeout locally waiting for the network" case.

**Comment by timmywil** [comment]
Discussed in the meeting. We don't want to make "timeout" be more ambiguous.

**Comment by LionNatsu** [comment]
Thanks. I suggest add some tips in docs, e.g. "Tip: An ajax time-out may be cause by proxies or other middlewares as a HTTP 504 error in the network chain earlier than $.ajax itself." :)
