### ISSUE TITLE
deep extend() overwrites good objects with null objects

### ISSUE THREAD

**Issue by alianos-** [jquery/jquery#2935]
I added the comments in the fiddle, but the bottom end is that while one array will extend the previous if possible, a null value will overwrite all previous effort with null. 

I would expect that behavior if suddenly we encountered an empty object in the place of an array, but it feels like null should behave like an empty array when an array is being extended, or like an empty object if an object is extended, and not erase all previous effort.

 https://jsfiddle.net/hozbv7fy/

**Comment by alianos-** [comment]
I "fixed" that by changing the `extend` function from:

    // Don't bring in undefined values
    } else if ( copy !== undefined ) {
        target[ name ] = copy;
    }

to:
    // Don't bring in undefined values
    } else if ( copy !== undefined ) {
        // Don't bring in null values either, if we already have non-null ones.
        if(copy===null){
            if(target[name] === undefined){
                target[ name ] = copy;    
            }
        } else {
            target[ name ] = copy;
        }					
    }

**Comment by gibson042** [comment]
Copying `null` is intentional; see http://api.jquery.com/jQuery.extend/ . The array weirdness I'll have to compare against past releases, but regardless of the outcome, you might be more satisfied with a customizable general-purpose library like [lodash](https://lodash.com/docs#mergeWith) for your use case.

**Comment by alianos-** [comment]
Are you sure it is intentional? I don't see it clearly in the documentation. It says "properties inherited from the object's prototype will be copied over" (which is fine when you copy null over undefined), but it also says "On a deep extend, Object and Array are extended". But which of those stands true when we already have an array and we extend it by null? 

I would expect to try and extend the existing array by null, which should give me the original array, but what happens is that the null property is just being copied over.

In any case, even if this is the intentional behavior it really looks like weird to me, because the end product is not the fully extended array that I would expect to have.

**Comment by alianos-** [comment]
Also if I can bring one more argument why this does not seem like intentional, as it is now the order by which objects changes the outcome. Extending obj1 by obj2 and obj3, is not the same as extending obj1 by obj3 and then obj2. To me it does not sound like this is what an extend should be doing.

**Comment by alianos-** [comment]
And as my final argument, take a look at that https://jsfiddle.net/4uyyaxop/

Would you ever expect that to be the result of a deep extend?

**Comment by gibson042** [comment]
> Are you sure it is intentional? I don't see it clearly in the documentation. It says "properties inherited from the object's prototype will be copied over" (which is fine when you copy null over undefined)

That line is immediately preceded by "Undefined properties are not copied", with the implication being that all other properties _are_.

> but it also says "On a deep extend, Object and Array are extended". But which of those stands true when we already have an array and we extend it by null?
> 
> I would expect to try and extend the existing array by null, which should give me the original array, but what happens is that the null property is just being copied over.

The deep-extend behavior only applies when data types match (array→array and object→object). Scalars overwrite non-scalars, non-scalars overwrite scalars, objects overwrite arrays, and arrays overwrite objects.

> In any case, even if this is the intentional behavior I can't see why it was intended, since the end product is not the fully extended array that one would expect.
> And as my final argument, take a look at that https://jsfiddle.net/4uyyaxop/
> 
> Would you ever expect that to be the result of a deep extend?

Yes. But if it doesn't fit your needs, then I again recommend the more customizeable [lodash `_.mergeWith`](https://lodash.com/docs#mergeWith).

**Comment by gibson042** [comment]
> The array weirdness I'll have to compare against past releases

The "deep-extend preserves array element index" behavior is identical all the way back to jQuery 1.6.4: https://jsfiddle.net/4uyyaxop/1/

Given just how counterintuitive _this_ is, I'll leave the ticket open. We should decide tomorrow whether to address it.

**Comment by alianos-** [comment]
👍

**Comment by dmethvin** [comment]
Any change here makes me nervous. I agree that if we were creating the API today it might be worthwhile to ignore `null` rather than replace the target array, but this behavior has been present for a long time.

**Comment by gibson042** [comment]
Turns out our behavior is standard.

**Comment by SimonHarte** [comment]
> Turns out our behavior is standard.

@gibson042 Could you elaborate on this comment with a reference or something? I myself still think it's strange that an array extend simply overwrites indexes instead of building an array with unique values.

**Comment by gibson042** [comment]
Standard in that it matches both ECMAScript `Object.assign` and Lodash `_.merge`: http://irc.jquery.org/%23jquery-meeting/default_%23jquery-meeting_20160222.log.html#t12:06:04
