### ISSUE TITLE
bugs.jquery.com down?

### ISSUE THREAD

**Issue by avindra** [jquery/jquery#2937]
I'm trying to view some tickets on `https://bugs.jquery.com` related to potential bugs we are seeing, but we are greeted with:

```
502 Bad Gateway

nginx/1.8.1
```

Is anyone working on restoring service?

**Comment by timmywil** [comment]
Thanks for the notice! We'll look into it.

**Comment by dmethvin** [comment]
Since we don't edit tickets there, the Google cached version should be complete.

**Comment by avindra** [comment]
Back up now. Thanks.
