### ISSUE TITLE
`http://code.jquery.com/jquery-latest.js` for v2.x.x ??

### ISSUE THREAD

**Issue by Martii** [jquery/jquery#2940]
So I was validating some of my documentation and it seems that http://code.jquery.com/jquery-latest.js is v1.x.x.

Is there a "latest" version link for version 2.x series? e.g. not specific like http://code.jquery.com/jquery-2.2.1.js

TIA

**Comment by dmethvin** [comment]
Links to the "latest" are not good practice, so there is not one for 2.x.

https://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/

**Comment by Martii** [comment]
> Links to the "latest" are not good practice, so there is not one for 2.x.

While it may not be good practice it's also not good document etiquette to do favoritism on a specific version.

Looks like jQuery has a bug then with this. Thank you for confirming that.

**Comment by dmethvin** [comment]
@Martii Did you *read* the blog post referenced there and see the chaos it caused? Your snide comment won't change anything.

**Comment by Martii** [comment]
It's not a snide comment. Your perception is skewed on that. The bug exists for http://code.jquery.com/jquery-latest.js based off what you said. Please refrain from snarky responses.

**Comment by Martii** [comment]
@dmethvin To further appease the bad maintainer response Cc: @mgol ... this is roughly how the documentation will be reading on this elsewhere:

> * For neutral documentation sake the latest version url is used, which is currently jQuery Core 1.11.1, however [some jQuery maintainers suggest that the latest version should not be used][jQueryDontUseLatest]. The meta link has not been updated to the actual latest jQuery Core 1.x series. This is possibly in part due to statistics gathering. Please follow the link for more specifics.
* Additional specific isolated versions may be found at their [CDN][jQueryCDN] including the most recent versions of 1.x and 2.x of the jQuery Core.

Please let the community know if jQuery is going to fix the bug of the url rewrite/route and/or remove it altogether. Thank you for a moment of your time from a realist who has been been in the industry for over three decades and doesn't appreciate being accused of being snide. :)

[jQueryDontUseLatest]: https://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/
[jQueryCDN]: https://code.jquery.com/

**Comment by dmethvin** [comment]
@Martii I think there may be a language barrier, so my apologies. I do not understand your response or request at all.

What is the bug?

What are you asking for us to do?

> Please let the community know if jQuery is going to fix the bug of the url rewrite/route and/or remove it altogether.

What bug?

**Comment by Martii** [comment]
> What is the bug?

> What are you asking for us to do?
&hellip;
> What bug?

&thinsp;
> ... the latest version url is used, which is currently jQuery Core 1.11.1...

Seems to me if the latest url isn't returning the actual latest of 1.x *(1.12.1)*... it should either be removed with the mod rewrite if Apache or change the redirect route if *node* *(or some other web server configuration)* to point to the latest 1.x. It seems to me like it's "strongly discouraged" from your response ... but latest 1.x is "presumed" for that link and it's ***not***.

I've done my best to keep our documentation as neutral as possible and I understand the link you referenced. I agree specific versions should always be used for maximum compatibility and minimal breakage... but documentation is tricky with Code examples to keep them neutral so we don't have to maintain them constantly by version bumping... I've added the "foot" notes [from above](https://github.com/jquery/jquery/issues/2940#issuecomment-187906550) to our docs to help alleviate confusion from our users and our community for the time being.

**Comment by dmethvin** [comment]
It seemed like the blog post was pretty clear. Don't use `jquery-latest.js`. Pretend that file does not exist. Ignore its suggestive name. The official word on it from this development team is that it should not be used. It is not part of our official documentation. The fact that you found the file on the CDN or made assumptions about it based on the name does not make it supported.

We can't update or change that file anymore because it will break lots of web sites on the Internet.  It is only there because it has been misused and we cannot remove it without punishing the users of sites with developers who made unfortunate decisions in the past, and whose sites may no longer be maintained. This is just another "don't break the web" decision that we all have to make on a regular basis.

If you need the latest version of the file and want to automate that process, you could get it from npm since we publish all releases there with versions tagged.

**Comment by Martii** [comment]
> Pretend that file does not exist.

LOL :)

> The official word on it from this development team is that it should not be used.

Hence the transformation of this issue from a simple question to a bug report. The footnotes and latest url will remain in our communities documentation until it is officially end-of-lifed **and removed** from the jquery.com domain. It is unfortunate that this development team doesn't accommodate for neutrality in Code samples but we can work around it with the footnotes.

>  It is only there because it has been misused and we cannot remove it without punishing the users of sites with developers who made unfortunate decisions in the past, and whose sites may no longer be maintained.

So deprecated or end of life?... using standard industry nomenclature here. **jQuery is supporting it in some fashion because the link is still around**. It's too bad I don't see an industry standard for http status codes for deprecation and end of life to let servers know in the 200/300 codes. :\ Perhaps if there is time and interest we'll get around to writing a RFC for adoption.

> We can't update or change that file anymore because it will break lots of web sites on the Internet. It is only there because it has been misused and we cannot remove it without punishing the users of sites with developers who made unfortunate decisions in the past, and whose sites may no longer be maintained.

Understandable minus the blame pointed out next... but jQuery is actively supporting it because it exists... active, deprecated and end-of-life are common terms... if I were to "presume" *(not assume there is a difference in the English language)* from your replies and that blog post it is in deprecation state... servers usually won't know this and may cause unnecessary maintenance in the work-flow.

> who made unfortunate decisions in the past

There's that unprofessional blame again from maintainers. Cc: @mgol

> The fact that you found the file on the CDN or made assumptions about it based on the name does not make it supported.

There's that blame again Cc: @mgol ... I didn't find it our communities did... it's been around pre-dating the blog post that you referenced and was in fact the defacto standard as described by the blog post until issues were raised... some pertaining to statistics gathering and CDN usage.

> and want to automate that process, you could get it from npm since we publish all releases there with versions tagged

Thanks for the reiteration of something I know already and use for *node* projects. :) **Most wiki's including *gollum* here on GH,  *allura* and sometimes MediaWiki don't have automation** hence why some external servers use a MOD of rewrite or *node* routing to point to other files and change http status headers. Adding another job task to determine the latest version in documentation is a waste of resources I believe.

Anyhow... if the bug doesn't want to get addressed then it doesn't *(I'm reading this as a WONTFIX)*... I would hope that a more positive role in the JavaScript community would want to be achieved by this project by doing something else for the latest url. I know that I'm discouraged by the initial tone which @dmethvin set, which has somewhat been rectified, and will dissuade me and my colleagues from contributing here.

**Comment by dmethvin** [comment]
> Most wiki's including gollum here on GH, allura and sometimes MediaWiki don't have automation hence why some external servers use a MOD of rewrite or node routing to point to other files and change http status headers. Adding another job task to determine the latest version in documentation is a waste of resources I believe.

Are you saying you want to automatically update jQuery on some sites on each release without testing? Please, don't automatically update things like that. It is exactly why jquery-latest was deprecated! Every update, even a patch release, is an opportunity for incompatibilities to creep in. We see it on every release, people depend on undocumented functionality or bugs and have their code broken by an update.

**Comment by Martii** [comment]
> Are you saying you want to automatically update jQuery on some sites on each release without testing?

Not quite...

> I've done my best to keep our documentation as neutral as possible and I understand the link you referenced. I agree specific versions should always be used for maximum compatibility and minimal breakage... but documentation is tricky with Code examples to keep them neutral so we don't have to maintain them constantly by version bumping... I've added the "foot" notes from above to our docs to help alleviate confusion from our users and communities for the time being.

Our communities prefer to remain neutral on which version is used *(including pushing v2.x.x over v1.x.x)*... as you pointed out with the abridged quote of:

> we cannot remove it without punishing the users of sites with developers ... and whose sites may no longer be maintained.

... we wish not to have automation of the process of updating our docs especially when those features don't exist in newer wiki software due to "dumbing down" for security reasons.

> Every update, even a patch release, is an opportunity for incompatibilities to creep in. We see it on every release, people depend on undocumented functionality or bugs and have their code broken by an update.

Speaking to the choir here as the aphorism goes. Actual usage in production I personally would discourage as well with the latest url... however favoritism on a specific version isn't recommended in **our communities documentation**. shields.io helps a great deal with *node* projects *(ex. ![jQuery](https://img.shields.io/npm/v/jquery.svg?style=flat 'jQuery latest'))* but when quoting a syntax in a working code snippet that is supposed to be neutral is technically impossible with *gollum* and related "markdown"ed software.

Example of a maintaince task for showing a html Code snippet with the more modern Media Type as per [RFC4329](http://tools.ietf.org/html/rfc4329)... this requires routine maintenance that can't be automated here in GH issue tracking and also *gollum* *(the GH wiki)*:
``` html
<script type="application/javascript" src="http://code.jquery.com/jquery-2.2.1.js" ></script>
```

**Comment by dmethvin** [comment]
It sounds like you're looking for something beyond the scope of this repository. In the past we tried the simple solution in `jquery-latest` and it failed horribly. You're welcome to come up with some other distribution mechanism beyond what we offer and distribute that. Between what we publish on npm and the tags available in Github it should be possible to automate.
