### ISSUE TITLE
Please demote @dmethvin for abusive maintainer behavior

### ISSUE THREAD

**Issue by Martii** [jquery/jquery#2943]
@mgol Cc: @scottgonzalez, @arschmitz and any other related Foundation board members.

The final reply during the abusive lock is:

Abridging here again...

**@dmethivin** [wrote](https://github.com/jquery/jquery/issues/2940#issuecomment-187961967):
> You're welcome to come up with some other...

``` html
<script type="application/javascript" src="http://code.jquery.com/jquery-latest.js" ></script>
<!--  For neutral documentation sake the latest version url is used, which is currently 
jQuery Core 1.11.1, however some jQuery maintainers suggest that the latest version
 should not be used as per https://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/.
 The meta link has not been updated to the actual latest jQuery Core 1.x series. 

Additional specific isolated versions may be found at their CDN at https://code.jquery.com/
 including the most recent versions of 1.x and 2.x of the jQuery Core. -->
```

... is our communities current solution for the bug of #2940.

This is all we have to professionally say. **@dmethivin** is asked to refrain from interacting with this issue as he has clearly proven to be abusive, unprofessional and fully documented. It is unfortunate that this poor behavior is tolerated by the other establishing owners especially from [an independent consultant](https://github.com/dmethvin) in MD that [incorrectly claims there is a language barrier](https://github.com/jquery/jquery/issues/2940#issuecomment-187910004) when there is not.

Thank you for a moment of your time and consideration.

**Comment by jaubourg** [comment]
Damn, I think you're lucky you had to deal with Dave on this matter.

If there was no language barrier then the self-entitled behaviour you exhibited could only be a sign of a complete lack of professionalism. Dave, being the nice guy that he is, just kept on giving you the benefit of the doubt where, quite franckly, no-one else would have tolerated your repeated and unwarranted attacks.

If you had a solution to the problem from the get-go, why didn't you say so in the description of the bug? It would have saved you, Dave and the ten of thousands of people following this repository from a one-sided "conversation" that clearly makes you look like an internet troll. 

So I suggest you tone down a notch on the operatics before this contributor feels obligated to report you for abuse.

**Comment by gnarf** [comment]
https://jquery.org/conduct/reporting/ -- this is not the right venue for this issue.
