### ISSUE TITLE
Stop modifying the value provided for boolean attributes

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#2946]
Similarly to how we stopped lowercasing attribute names (a workaround for IE<9) in #2914, we might want to stop [modifying the value provided for boolean attributes](https://github.com/jquery/jquery/blob/8a91f8442f4d31bdd4b43035ee88d40fbb116f64/src/attributes/attr.js#L107-L109) which was also AFAIK only needed by IE<9 and kept on the 2.x branch for API compatibility.

**Comment by timmywil** [comment]
Actually, this wasn't for IE<9. IE<9 required setting the property to a boolean. I'd like to continue doing this because although browsers may treat any value as true, I like that users can see the value that was set is always a truthy value regardless of what they passed. It is not only forcing values to comply with the spec, but it is educating our users on the fact that even if you set the string "false", it will still be treated as true.

**Comment by timmywil** [comment]
Woops.

**Comment by mgol** [comment]
If we wanted to educate users about the difference between boolean & non-boolean attrs, we might just set it to an empty string instead of the attribute name. This didn't work in IE<9 but now it does and this is how you'd normally specify a boolean attribute when writing HTML by hand - by not providing its value.

That is, unless we'd consider such a change too much of a breaking change as it would break cases where someone incorrectly retrieved the attribute value and checked for its truthiness. I doubt such code would actually do anything not already broken, though.

**Comment by timmywil** [comment]
What does the empty string provide that the attribute name does not?

**Comment by mgol** [comment]
Mainly the visual clue in Developer Tools.

1. After `$0.setAttribute('foo', 'foo')`: 
<img width="218" alt="screen shot 2016-02-24 at 18 13 50" src="https://cloud.githubusercontent.com/assets/1758366/13294052/85ffddc6-db22-11e5-8e77-c18374910a2b.png">
1. After `$0.setAttribute('foo', ''): 
<img width="171" alt="screen shot 2016-02-24 at 18 13 58" src="https://cloud.githubusercontent.com/assets/1758366/13294067/97fd605c-db22-11e5-976e-27a58cbc4181.png">

This is exactly how attributes natively reflected by property modifications behave, e.g. setting:
```js
div.hidden = true
```
results in an attribute `hidden` set to an empty string and represented like that: 
<img width="200" alt="screen shot 2016-02-24 at 18 18 58" src="https://cloud.githubusercontent.com/assets/1758366/13294188/190196dc-db23-11e5-91b4-69169bb93d60.png">

This makes the jQuery behavior closer to the native one which is what we've been recently trying to do more & more.

**Comment by mgol** [comment]
The visual clue in Developer Tools as well as being closer to standards.

1. After `$0.setAttribute('foo', 'foo')`: 
<img width="218" alt="screen shot 2016-02-24 at 18 13 50" src="https://cloud.githubusercontent.com/assets/1758366/13294052/85ffddc6-db22-11e5-8e77-c18374910a2b.png">
1. After `$0.setAttribute('foo', ''): 
<img width="171" alt="screen shot 2016-02-24 at 18 13 58" src="https://cloud.githubusercontent.com/assets/1758366/13294067/97fd605c-db22-11e5-976e-27a58cbc4181.png">

This is exactly how attributes natively reflected by property modifications behave, e.g. setting:
```js
div.hidden = true
```
results in an attribute `hidden` set to an empty string and represented like that: 
<img width="200" alt="screen shot 2016-02-24 at 18 18 58" src="https://cloud.githubusercontent.com/assets/1758366/13294188/190196dc-db23-11e5-91b4-69169bb93d60.png">

This makes the jQuery behavior closer to the native one which is what we've been recently trying to do more & more.

**Comment by markelog** [comment]
Is there any spec that says so? Being closer to browser behaviour sometimes is not a good idea, since jQuery tries to fix exactly that.

Not saying i'm against that or pro, but would be cool to see some doc that's says it.

**Comment by timmywil** [comment]
> The visual clue in Developer Tools as well as being closer to standards.

I can get on board with the first, but not the second. Both are standard.

**Comment by timmywil** [comment]
https://www.w3.org/TR/2008/WD-html5-20080610/semantics.html

> If the attribute is present, its value must either be the empty string or a value that is a case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

**Comment by timmywil** [comment]
Also, it's possible that using empty string will have issues in XHTML.

**Comment by markelog** [comment]
So it seems spec agrees with our behaviour and even though dev tools shows absence of the value, `innerHTML` shows it.

**Comment by dmethvin** [comment]
Also https://www.w3.org/TR/xhtml1/#h-4.5

**Comment by mgol** [comment]
OK, I forgot about XHTML. It seems it should stay as it is then.

**Comment by markelog** [comment]
> I forgot about XHTML

Well, it seems xhtml DOM behaves exactly as HTML i.e. as in https://github.com/jquery/jquery/issues/2946#issuecomment-188359847

And it seems it doesn't contradicts the XHTML spec either.

You sure you want to give up that easily? :)

**Comment by timmywil** [comment]
@markelog It does violate the XHTML spec tho, as @dmethvin pointed out, even if browser implementations don't care. Besides, I don't see that much gain from using empty string when we know that what we have works. I think we can leave this.

**Comment by markelog** [comment]
XHTML requires you to set a value in quotes, which what native behaviour does and which i believe was the point of the initial request. So nope, it doesn't violate it.

> I don't see that much gain from using empty string when we know that what we have works. I think we can leave this.

Just like i said, not oppose nor pro

**Comment by dmethvin** [comment]
> XHTML requires you to set a value in quotes, which could be an empty string,

I have tried to forget the horror of XHTML but a few years ago I seem to recall code breaking because it expected non-falsy attribute values and an empty string is falsy. It probably would have been in the 1.6 timeframe when @timmywil was doing the attributes refactor.

**Comment by markelog** [comment]
> few years ago 

More like five! :)

**Comment by timmywil** [comment]
> XHTML requires you to set a value in quotes, which could be an empty string,

Yea, I recall a time when setting to empty string ended up with no value specified in HTML, but that was probably the whole attroperties issue.

**Comment by mgol** [comment]
For those following, we revisited the decision made here and in jQuery 4.0 we're dropping special handling of boolean attributes. See #5388 for more information.
