### ISSUE TITLE
mouseenter & mouseleave events after setTimeout in callbacks are wrong

### ISSUE THREAD

**Issue by yairEO** [jquery/jquery#2947]
Here's an [**example page**](http://jsbin.com/lerogi/edit?html,js,output) which illustrates the issue with `mouseenter` event.

![gif](https://cloud.githubusercontent.com/assets/845031/13294580/4fcbb1ac-db2d-11e5-8c7c-046680d308dd.gif)

**Comment by dmethvin** [comment]
We can't  use the native `mouseenter` due to several browser bugs, so it is synthesized from `mouseover`. This could be fixed by making a new copy of the entire `jQuery.Event` object before it was delivered at each element as is bubbled, but that would be a horrible performance penalty. If you only need a few properties, just copy them so that they can be used by the setTimeout function.

**Comment by yairEO** [comment]
Thanks.  I've solved it by save it to a variable before calling the `setTimeout` 

    var ev = $.extend(true,{}, e);

**Comment by timmywil** [comment]
I agree with @dmethvin's assessment. I don't think we should make a change here.

**Comment by yairEO** [comment]
BTW, this is also like this on jQuery version `3`

**Comment by dmethvin** [comment]
> Thanks. I've solved it by saving the event to a variable before calling the setTimeout

Don't do that, a deep extend is extremely expensive! If you only need a few variables or the event type, just save them in their own variables.

**Comment by yairEO** [comment]
@dmethvin - yeah i thought about it a minute after and changed it :) see updated comment

**Comment by mgol** [comment]
> We can't use the native `mouseenter` due to several browser bugs

To be precise, none of browsers supported in jQuery 3.0 should experience this bug (the last one was Safari 7 which we dropped; we still support iOS 7 but I think there is no `mouseenter` there). The more important reason why we synthesize is to make event delegation work; see [this comment](https://github.com/jquery/jquery/blob/8a91f8442f4d31bdd4b43035ee88d40fbb116f64/src/event.js#L622-L624).

**Comment by dmethvin** [comment]
Yes, true. If you want to do delegated `mouseenter` that requires either deriving it from a bubbling `mouseover` or using a capturing `mouseenter` handler via a special event hook. We could try the latter in 3.x via an approach similar to [focusin/out](https://github.com/jquery/jquery/blob/8a91f8442f4d31bdd4b43035ee88d40fbb116f64/src/event/focusin.js#L21).

**Comment by dmethvin** [comment]
BUT...that would put it in the wrong event order so not a good idea.
