### ISSUE TITLE
Problem with SSL V3 Handshake

### ISSUE THREAD

**Issue by Schalueck** [jquery/jquery#2950]
Hi, we are using a proxy (McAfee Web Gateway) in our enterprise. Some external websites reference to https://code.jquery.com for fetching jquery code.
Then we get the message from the proxy: 
Host: code.jquery.com
Reason: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

The site should better switch to TLS v1.1 or above.

**Comment by dmethvin** [comment]
So have you switched to TLS v1.1 or above yet?

**Comment by Schalueck** [comment]
Yes, we did this already. At least our proxy supports TLS, but has problems about this specific type of SSL3, as my admin told me.

**Comment by dmethvin** [comment]
Could you create a ticket with more detail over at our CDN repo?
https://github.com/jquery/codeorigin.jquery.com/issues/new

To resolve this we will most likely need your network people talking to our CDN people, and much more information on the configuration.
