### ISSUE TITLE
width() outerWidth() innerWidth() sets incorrect value under certain conditions on webkit browsers

### ISSUE THREAD

**Issue by sqlmiles** [jquery/jquery#2951]
Hi.
I noticed this when td/th has border-width > 0 and is child of table with border-collapse: collapse then each .width(X)  sets width equal to (X - border-width) on webkit borwsers. This seems to appear in jQuery versions 1.8.0 and above. There is [JSfiddle](https://jsfiddle.net/qez9Lay3/) with code to reproduce bug.

**Comment by dmethvin** [comment]
This happens in Chrome, IE11, and Edge but not Firefox. Seems to be related to the subpixel values for borders. https://jsfiddle.net/qez9Lay3/4/

**Comment by dmethvin** [comment]
Update with the gBCR result as well: https://jsfiddle.net/qez9Lay3/5/

The `gBCR` includes both borders but the `gCS` result includes only one. At least that's my interpretation.

**Comment by dmethvin** [comment]
I'm tempted to say we should just document this. It's hard to say who collapsed borders belong to and shared custody doesn't work when it's used as a setter.

**Comment by timmywil** [comment]
@dmethvin Agreed. I'm not sure this is worth a feature test + workaround. If Firefox is the odd man out, perhaps they could simply align their behavior with the other browsers.
