### ISSUE TITLE
Cannot read property 'createElement' of undefined

### ISSUE THREAD

**Issue by mihai9112** [jquery/jquery#2952]
```
TypeError: Cannot read property 'createElement' of undefined
      at assert (file://jspm_packages/npm/jquery@2.1.4/dist/jquery.js:892:20)
      at eval (file://jspm_packages/npm/jquery@2.1.4/dist/jquery.js:2560:24)
      at eval (file://jspm_packages/npm/jquery@2.1.4/dist/jquery.js:2611:3)
      at eval (file://jspm_packages/npm/jquery@2.1.4/dist/jquery.js:34:3)
      at eval (file://jspm_packages/npm/jquery@2.1.4/dist/jquery.js:38:2)
      at eval (native)
      at SystemJSNodeLoader.__exec (node_modules/systemjs/dist/system.src.js:1400:16)
      at SystemJSNodeLoader.<anonymous> (node_modules/systemjs/dist/system.src.js:4094:20)
      at SystemJSNodeLoader.instantiate (node_modules/systemjs/dist/system.src.js:4346:28)
      at node_modules/systemjs/dist/system.src.js:338:33
      at run (node_modules/core-js/modules/es6.promise.js:104:47)
      at node_modules/core-js/modules/es6.promise.js:115:28
      at flush (node_modules/core-js/modules/$.microtask.js:19:5)
  	Evaluating file://jspm_packages/npm/jquery@2.1.4/dist/jquery.js
  	Error loading file://jspm_packages/npm/jquery@2.1.4/dist/jquery.js as "npm:jquery@2.1.4/dist/jquery.js" from file:///Users/Mihai/Projects/MariucaVarza/jspm_packages/npm/jquery@2.1.4.js
```

I am trying to load a module to test it using Mocha, Chai and Sinon. When loading the module I get the following error from jquery. Not really sure if this is a bug within jquery.

**Comment by mgol** [comment]
jspm manages dependencies for the browser; if you don't have `window.document` (that's what this error means), it sounds like you're trying to get it executed in Node where it requires an additional `window` implementation like the one provided by [jsdom](https://www.npmjs.com/package/jsdom). But even then it should fail earlier than that so your situation looks weird.

Which jQuery version? Also, we'd need a full example (perhaps a stripped-down version of a project) where we could reproduce the bug. It's hard to do anything just by looking at this error.

**Comment by mihai9112** [comment]
This is the code I am trying to run. It's basically a test that verifies if the module has been loaded. The module in question is used in an ejs page. I just wanted to test that module in isolation. I can add more details about the project, I also have it on github, but I haven't pushed this test recently.
```
import chai, {
    expect
}
from 'chai';
import sinon from 'sinon';
import sinonChai from 'sinon-chai';
import System from 'systemjs';
import '../public/config.js';

chai.use(sinonChai);

describe('helperModule', () => {
    let module;

    before(function () {
        return System.import('./public/js/helper.js')
            .then((mod) => module = mod);
    });

    describe('Module loading', function () {
        it('should load', function () {
            expect(module.default).to.not.be.undefined;
            done();
        });
    });
});
```

**Comment by dmethvin** [comment]
I think this is not a jQuery bug report. I don't even see jQuery in that code snippet.

**Comment by CrazyCompiler** [comment]
Just try importing react and component as :-
 
import React, { Component } from 'react';
