### ISSUE TITLE
jquery/src/intro.js file lacks end brackets

### ISSUE THREAD

**Issue by ninickname** [jquery/jquery#2953]
I'm new to jQuery , and to js in global , but as my IDE mentioned , there is missing a bracket to close what ever is going on there . 

jquery/src/intro.js 

I don't know if was caused by a bug in a recent commit , but as a programmer this code doesn't make sense to me .

**Comment by markelog** [comment]
Yeah, this is intentional, `intro.js` and `outro.js` are wrappers in which other modules are included when jQuery is builded

**Comment by alexdesi** [comment]
Hi, because of that "missing" bracket I (and many others) am getting error compiling the assets (in Rails) with Uglifier:
> vendor/assets/components/jquery/src/intro.js
> ExecJS::ProgramError: Unexpected token: eof (undefined) (line: 46, col: 0, pos: 1377)
any idea how to avoid that?
thanks!

**Comment by mgol** [comment]
@alexdesi From where are you getting this info? You shouldn't use this file, lint it etc.

BTW, this is already fixed on master where `intro.js` & `outro.js` have been collapsed into one file, [src/wrapper.js](https://github.com/jquery/jquery/blob/e5ffcb0838c894e26f4ff32dfec162cf624d8d7d/src/wrapper.js). jQuery 3.0.0 will be setup this way.

**Comment by alexdesi** [comment]
@mgol I got those by compiling manually that file with uglifier (the rails gem),
but I get same information precompiling this way: ` bundle exec rake assets:precompile RAILS_ENV=production`

I'm using jquery 2.2.3, probably required by boostrap using bower:
`  "dependencies": {
    "bootstrap": "~3.3"
  }`

You said that I should not use it. That is required by the rails assets (I am not explicitly requiring it), so probably the way to go is to exclute intro.js (in some way) from the asset compiling.

**Comment by mgol** [comment]
I don't know how the asset compiler got into this file but it definitely shouldn't have. `intro.js` was only referenced by the [build script](https://github.com/jquery/jquery/blob/2.2.3/build/tasks/build.js#L32-L33), the only other thing to get to it that I can think of is that it tries to compile every JS file inside the `src` directory but if it does that, it's incorrect.

This is the first report that I see about this problem, if it was breaking all Rails app we'd surely hear about it immediately. Are you sure you didn't put something that would make it try to compile all those files in your config?

I know nothing about Rails so you need to research it on your own a little.

**Comment by alexdesi** [comment]
@mgol I think you get the point, rails assets is trying to include every JS file. So I need to figure include only the necessary ones. Thanks for the advice!

**Comment by mgol** [comment]
I'm glad if I helped. :)
