### ISSUE TITLE
Error when compiled on Debian

### ISSUE THREAD

**Issue by BloodySucker** [jquery/jquery#2955]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild jquery@3.0.0-pre
6 info build jquery@3.0.0-pre
7 verbose unsafe-perm in lifecycle true
8 info jquery@3.0.0-pre Failed to exec build script
9 error jquery@3.0.0-pre build: `npm install && grunt`
9 error Exit status 1
10 error Failed at the jquery@3.0.0-pre build script.
10 error This is most likely a problem with the jquery package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     npm install && grunt
10 error You can get their info via:
10 error     npm owner ls jquery
10 error There is likely additional logging output above.
11 error System Linux 3.16.0-4-amd64
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
13 error cwd /root/jquery
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by markelog** [comment]
Try to remove your `node_modules` folder and execute `npm cache clean` command

**Comment by mgol** [comment]
Also, your Node.js instance is really old, please upgrade to at least 0.10.42 (if you have to stay on 0.10), or, if you can, upgrade to Node 4 or newer.

You can find a well-maintained repository for various Linux flavors including Debian at https://github.com/nodesource/distributions/.

**Comment by markelog** [comment]
Okay, ping us up, if you still facing this issue
