### ISSUE TITLE
keyup, keydown and keypress event does not fire in IE9 for programmatically created DOM elements

### ISSUE THREAD

**Issue by s-a** [jquery/jquery#2956]
Just testing my app down to IE9

Seems jQuery does not fire ```key*``` events in IE9.

jQuery version: 2.2.1

I try to bind events to DOM elemets created by handlebars.

Code to reproduce: 
```javascript
$(document).ready(function(){

		$( document ).on("keyup", ".incomplete_required", function() {
        console.log('keyed');   
    });

		$( document ).on("keyup", "#test", function() {
        console.log('keyed');
    });
    
    $("body").append($('<textarea class="incomplete_required"></textarea>'));
    $("body").append($('<textarea id="test"></textarea>'));
});
```

This was tested with IE11 emulator only. Maybe this affects only emulator? I wonder if jQuery does not contain unit test for this scenario.

**Comment by mgol** [comment]
Thanks for the report. Could you create a test case at https://jsfiddle.net/ or https://jsbin.com/ that we could reproduce?

**Comment by s-a** [comment]
https://jsbin.com/xozamo/edit?html,js,console,output

**Comment by dmethvin** [comment]
I can't get that jsbin to run in real IE9 on Browserstack, I get an error (see screenshot). In general, jQuery will forward on any event that the browser generates, but if the browser doesn't fire the event then we can't do much about it. The keyup/keydown events are pretty reliable on all platforms but keypress is not. Also, we only test on real IE9, never on the various compatibility view modes such as IE9 on IE10 or IE9 on IE11.

![capture](https://cloud.githubusercontent.com/assets/157858/13396045/697811c2-dec0-11e5-90a9-ab1aa83ab88b.PNG)

**Comment by s-a** [comment]
https://jsfiddle.net/00sa/jhf41Lhq/ So sorry for the noise. I guess I was confused this morning by the browser flood. I can confirm that key* events fire even on IE9. Thanks very much for your efforts.
