### ISSUE TITLE
Deprecate jQuery.proxy

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2958]
It seems their use is mostly fulfilled with `Function#bind` and other signatures has limited use

**Comment by r3wt** [comment]
It's used extensively to call prototype functions with context for event bindings in many jquery plugins, notably in bootstrap's plugins. In recent versions of jQuery i get the error `f.handlers.apply` is not a function, however writing my own proxy function worked:

```js
var proxy = function (c,f){
	return function(e){ return f.apply(c,[e]); };
};
```

**Comment by markelog** [comment]
Proposal here for deprecation only, not for removal, if it would be removed, it would happen in major version.

As you said you it is easy to supplement, which what [jquery-migrate](https://github.com/jquery/jquery-migrate) would do anyway

**Comment by timmywil** [comment]
It's small enough that if it's getting wide usage, I don't see the need for deprecation.

**Comment by mgol** [comment]
One thing that jQuery.proxy does and Function#bind doesn't is setting guid
on the bound function instances so that proxied event handlers can be
removed without storing the instance of the proxied function.

**Comment by markelog** [comment]
@timmywil would you recommend to use `jQuery#proxy` over `Function#bind`?

**Comment by timmywil** [comment]
@markelog I still use proxy over bind when I think it's cleaner to pass a function name rather than the function.

**Comment by markelog** [comment]
If we still recommend to use `jQuery#proxy` and not es6 version, that then this indeed should be closed.

But i don't think that refusal from deprecation should came from "used a lot" place, if that is the only reason, then we should discourage people from using it, which is what deprecation is, which doesn't mean we would need to remove it at 4.0, it could be the next or next after next.

**Comment by dmethvin** [comment]
Carrying over our discussion about breaking things from yesterday's meeting, it seems like there is not a lot of benefit from deprecating this or eventually removing it. It isn't a lot of code inside jQuery and removing it will just make someone rewrite code that works perfectly well today. That's in contrast to something like the Deferred changes which, although potentially more disruptive, are driven by our desire to align with Promise standards.

I started this wiki page that's similar to our Adding page where we can try to outline our practices.
https://github.com/jquery/jquery/wiki/Changing-existing-features

**Comment by jzaefferer** [comment]
Deprecating in favour `Function#bind` with no intention to remove seems like a pretty good idea. Pushing users towards standards if worth it.

**Comment by markelog** [comment]
> Pushing users towards standards if worth it.

Precisely

**Comment by dmethvin** [comment]
If we put a deprecation warning in Migrate about it, people will feel compelled to get rid of that warning or complain to us about it. If we have a schedule for removal that makes sense, but if it's eternal deprecation I don't know if it does.

**Comment by markelog** [comment]
> If we put a deprecation warning in Migrate about it, people will feel compelled to get rid of that warning or complain to us about it

Yeah, that would consequences of deprecation, also adding note about deprecation to the documentation. 

Frankly, i'm not sure why we wouldn't want to promote `Function#bind` over `jQuery#proxy` in the same way i don't think we would need to recommend `jQuery.now` over `Date.now`.

**Comment by jzaefferer** [comment]
Then don't put a warning in migrate.

**Comment by timmywil** [comment]
I only want to deprecate things that are slated for eventual removal. I'm fine promoting `bind` over `proxy`, but I think we should do it in documentation. Deprecation is not the right tool.

**Comment by markelog** [comment]
If no one would used because we discourage it, it would be logical to eventually remove it, besides definition of deprecation is - 

> Deprecation is the discouragement of use of some feature, design or practice

What term do you prefer?

**Comment by jzaefferer** [comment]
> I only want to deprecate things that are slated for eventual removal

Why? Also what Oleg said.

**Comment by r3wt** [comment]
@jzaefferer pushing users towards standards? what standard would that be? the standard of having your head up your ass?

**Comment by shanimal** [comment]
Im guessing Im not understanding something obvious, and this may be a really dumb question, but Im wondering if native bind can be used to stub $.proxy when it's available.

Calling proxied functions is roughly 80% slower than calling the same function using bind. In Firefox it was 114% slower.
https://jsperf.com/native-bind-vs-proxy

**Comment by dmethvin** [comment]
We've deprecated this method, so we aren't planning to do any other implementation.

**Comment by mgol** [comment]
@dmethvin Did you close it by accident? We haven't deprecated it yet so I'll reopen...
