### ISSUE TITLE
Deprecate jQuery.now

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2959]
It's already just a reference to `Date.now`

**Comment by mgol** [comment]
:+1:

**Comment by dustinpoissant** [comment]
Or `new Date().getTime();` or `Date.now()`. There is no need for this in jQuery.

**Comment by ShashankaNataraj** [comment]
@dustinpoissant @mgol Can do this and submit a PR?

**Comment by mgol** [comment]
@ShashankaNataraj Sure. Just remember to move `jQuery.now` to `src/deprecated.js` and change all current uses of `jQuery.now` to `Date.now`.

Note that we scheduled it for 3.2.0 and we'll most likely want to release 3.1.1 before that so your PR may not be immediately merged even if ready.

**Comment by markelog** [comment]
Also pr for doc changes to github.com/jquery/api.jquery.com would also be appreciated

**Comment by ShashankaNataraj** [comment]
@mgol @markelog Thanks! Will do!
