### ISSUE TITLE
Deprecate jQuery.isNumeric

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2960]
Was created for internal use, don't needed now

**Comment by mgol** [comment]
:+1: This API is not terribly intuitive, I'd expect people to just code sth like that themselves if they need it.

**Comment by dmethvin** [comment]
I think we have a strong position for deprecating this since what people mean by "numeric" seems pretty subjective and not very useful without further validation.

**Comment by ShashankaNataraj** [comment]
Can I take this up?

**Comment by markelog** [comment]
Sure, here is the link for reference - http://contribute.jquery.org/commits-and-pull-requests/

**Comment by ShashankaNataraj** [comment]
@markelog Correct me if Im wrong:

[x] The isNumeric function needs to be moved from `core.js` to `deprecated.js`
[ ] The usage within unit tests need not be changed as this function was meant to be used for unit tests from the beggining?

**Comment by timmywil** [comment]
@ShashankaNataraj I think tests can be changed later if we decide to remove isNumeric.

**Comment by mgol** [comment]
@timmywil I think it should be changed now, while closing this issue. We should aim at the slim build being able to pass as many tests as possible (with the exception of excluded modules) so I'd like not to go in the opposite direction. Also, that's the pattern we followed in the past, e.g. `bind`/`unbind`/`delegate`/`undelegate` tests are contained in `test/unit/deprecated.js`.

There are not many tests using `isNumeric` so it shouldn't be too hard to fix them.

**Comment by timmywil** [comment]
@mgol Yes, they should be moved, but I was talking about usage of `isNumeric` in the tests. We should continue testing the function itself until it's removed.

**Comment by markelog** [comment]
I think we should keep testing it, but if `isNumeric` used in different places it should be replaced

**Comment by mgol** [comment]
@timmywil I'm talking about that as well. If we just move `isNumeric` to `deprecated.js` but don't change the tests that were not testing this method but just using it then we'd introduce additional test failures when testing with the slim version.

**Comment by timmywil** [comment]
@mgol I'm proposing we replace stray uses of `isNumeric` that aren't directly related to testing `isNumeric`, move the tests that do directly test `isNumeric` to `test/unit/deprecated` (not remove them), and slim will be fine because it should not be testing against the deprecated module.

**Comment by timmywil** [comment]
@mgol By the way, the only place I can find where we use isNumeric that isn't related to testing `isNumeric` itself is in `test/unit/css.js`.

**Comment by mgol** [comment]
> @mgol I'm proposing we replace stray uses of isNumeric that aren't directly related to testing isNumeric, move the tests that do directly test isNumeric to test/unit/deprecated (not remove them), and slim will be fine because it should not be testing against the deprecated module.

That's what I meant as well. 😄 It seems we've had a misunderstanding.

**Comment by markelog** [comment]
Yeah, same here :)

**Comment by CrazyPython** [comment]
@ShashankaNataraj updates?
