### ISSUE TITLE
Deprecate jQuery.isArray

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2961]
Seems fulfilled with `Array.isArray`

**Comment by mgol** [comment]
:+1:

**Comment by tkdphoenix** [comment]
agreed

**Comment by FarSeeing** [comment]
I guess it's worth moving `Array.isArray` into `/var` and re-use:

```
   raw     gz Compared to master @ 44cb97e0cfc8d3e62bef7c621bfeba6fe4f65d7c    
  +601   +147 dist/jquery.js                                                   
   -60    -12 dist/jquery.min.js
```

**Comment by markelog** [comment]
Nice find, but with this ticket we would need to move it to `deprecated.js` module

**Comment by FarSeeing** [comment]
That's a calculation with the following code in `deprecated.js`:
```javascript
jQuery.extend( {
	isArray: isArray
} );
```

**Comment by markelog** [comment]
You mean gzip size will also change in identical manner if we move it to `deprecated.js` as if we moved to `/var`?

**Comment by FarSeeing** [comment]
That's the result of having both `/var` file creation for storing variable and moving declaration to `deprecated.js`.

**Comment by mgol** [comment]
Deprecation would mean that we:

1. Move `jQuery.isArray` to `deprecated.js`
2. Change all internal uses from `jQuery.isArray` to `Array.isArray`

so we can't have the `var` containing the old code here.

**Comment by FarSeeing** [comment]
Right, but as other built-in methods (`slice`, `concat`, `toString` etc) `isArray` could be stored in `/var`.

**Comment by mgol** [comment]
So you propose to put `Array.isArray` in a `var`-module, not `jQuery.isArray`? I understood it differently before.

**Comment by FarSeeing** [comment]
That's right. Sorry for not explaining that before.

**Comment by markelog** [comment]
I wouldn't want size to influence our file hierarchy, it would be pretty confusing, also all deprecated modules should be stored in `deprecated` module, since it would also confusing but now for users too who want to exclude or use deprecated stuff

**Comment by mgol** [comment]
@markelog I agree to an extent but @FarSeeing only proposes to put Arey.isArray in a var-module, not the soon-to-be-deprecated jQuery.isArray; see our last 2 comments.

**Comment by markelog** [comment]
Oh, i see, but i wouldn't do that too :), don't really see the point

**Comment by ShashankaNataraj** [comment]
Guys, is there a possibility of me submitting a PR for this?

**Comment by mgol** [comment]
@ShashankaNataraj Sure! Do you know what needs to be done?

**Comment by markelog** [comment]
I would wait until we would have discussion about this, it seems some team members feel "deprecation" process of core methods might be inappropriate.

**Comment by ShashankaNataraj** [comment]
@mgol @markelog Correct me if Im wrong, tasks for this issue are:
[] Move jquery.isArray to `deprecated.js`
[] Change all usages of `jQuery.isArray` to `Array.isArray`

**Comment by mgol** [comment]
Also, the third item - its unit tests have to be moved to jQuery.isArray as
well.

Also, if this hasn't been mentioned before - each deprecation, apart from a
jQuery PR and an API site issue needs a jQuery Migrate issue to polyfill
the API and warn against using it.


-- 
Michał Gołębiowski

**Comment by ShashankaNataraj** [comment]
@mgol Alright. Actually I have been raising [issues like this](https://github.com/jquery/api.jquery.com/issues/949) for every deprecation issue Im working on..

Raised one for this issue too.

**Comment by mgol** [comment]
> I understand unit tests need to be modified but jQuery.isArray tests need to be removed right?

Not removed but moved to `test/unit/deprecated.js`.

> Actually I have been raising issues like this for every deprecation issue Im working on..

I've seen them, thanks for that! I meant that apart from the API issue we also need an issue at https://github.com/jquery/jquery-migrate/issues about a need to restore the API (because people may exclude the deprecated module) with a warning against using it.

**Comment by nithmanoj** [comment]
@ShashankaNataraj seems not to be working on this. Can I please take this ?

**Comment by nithmanoj** [comment]
Correct me, for any changes
- [ ] Move `jquery.isArray` to `deprecated.js`
- [ ] Change all usages of `jQuery.isArray` to `Array.isArray`
- [ ] Create a jquery-migrate issue for `jQuery.isArray`

**Comment by Rikk** [comment]
Update Docs? http://api.jquery.com/jQuery.isArray/
