### ISSUE TITLE
e.stopPropagation is not a function in jQuery 2.2.x

### ISSUE THREAD

**Issue by martin-g** [jquery/jquery#2963]
Since jQuery 2.2.0 I experience the following problem:

```
Uncaught TypeError: e.stopPropagation is not a function
jQuery.Event.stopPropagation @ jquery-2.2.1-ver-1456907236000.js:5020
jQuery.extend.Event.stop @ wicket-event-jquery-ver-1456907236000.js:193
jQuery.extend.Ajax._handleEventCancelation @ wicket-ajax-jquery-ver-1456907236000.js:1941
(anonymous function) @ wicket-ajax-jquery-ver-1456907236000.js:1995
fire @ jquery-2.2.1-ver-1456907236000.js:3182
....
```

It appears that JQuery.Event's originalEvent is not a native event but jQuery object (i.e. `function(selector, context)`).

I wasn't able to reproduce it in JSFiddle but I've deployed a simple application at http://jquery220-mgrigorov.rhcloud.com.
To reproduce it:
* open DevTools/Firebug, Console tab
* click HERE to open a modal window
* click Close button

If I set a breakpoint at jQuery.js line 5020 it works correctly - the event is MouseEvent.
But if I set a conditional breakpoint (`!e.stopPropagation`) then I see that the event is jQuery object and it throws the exception.

There is no such problem with jQuery 2.1.3 and 1.12.1.

I hope the provided information and demo application are enough to debug it!
Please let me know if I can provide more information!

**Comment by dmethvin** [comment]
The error comes from this call inside Wicket:
```js
if (attrs.sp === "stop") {
	Wicket.Event.stop(evt);
```
At the point of error inside `jQuery.Event`, the event *seems* to be a native `MouseEvent` without a native `stopPropagation()` method. As of 1.12.0/2.2.0 we assume the native event always has that method.

The code for `Wicket.Event` calls several non-public APIs including `jQuery.event.fix()` and extends `jQuery.Event` so it's possible it is violating some assumption.

There is still a lot of code here. Can you simplify it a bit?

**Comment by martin-g** [comment]
Thanks for looking into this, @dmethvin !

I've tried to simplify it but it seems I'm missing something in the fiddle so it works just fine there.

`jQuery.event.fix()` is used to make sure that Wicket JS code always works with jQuery.Event, and not with native JS events.
`jQuery.Event` extension for `inputchange` custom event is not used in this demo application, so I think this could be ignored.
I'll debug it some more after work.

Do you have an idea why it doesn't fail when a normal (non-conditional) breakpoint is used? This makes me think it is some timing issue.

**Comment by dmethvin** [comment]
Any time you're messing with undocumented jQuery internals it's hard to predict what will happen. It should never be necessary for external code to call `jQuery.event.fix()`, especially for non-native events. I did get the error once or twice on your original case above but also didn't get it once or twice. I don't know why it is intermittent. 

I would say there's a jQuery problem here if there is a way to get a native `MouseEvent` from Chrome that doesn't have a `stopPropagation()` method. If it's due to Wicket changing the `MouseEvent` and then passing it to jQuery then it's a bug in Wicket.

**Comment by martin-g** [comment]
OK. I'll dig in this direction - remove usage of jQuery.Event.fix().
Thanks!

**Comment by martin-g** [comment]
The problem is in Wicket!
The difference comes from the different handling of normal events (like `click`, 'change`, etc.) and Wicket's special thingy called `domready`.
For normal events Wicket uses `jQuery.on()`, but for `domready` it uses `jQuery(handler)`, i.e. `jQuery.ready`. (see https://github.com/apache/wicket/blob/ffa34c6bfbd2ccd8340e23ff1601edd3e0e941d6/wicket-core/src/main/java/org/apache/wicket/ajax/res/js/wicket-event-jquery.js#L205).
For `jQuery.ready()` the first/only argument passed to the handler is the jQuery object.
Now I have to find why it wasn't breaking before 2.2.0 and fix it!
Thanks!
