### ISSUE TITLE
Custom easing no longer works

### ISSUE THREAD

**Issue by Beavykins** [jquery/jquery#2964]
Extended easing functions no longer work in the new Beta. From what I can tell there was a change in Tween.prototype

Replacing Tween.prototype with the one from Alpha 3.0 fixes the issue.

**Comment by Beavykins** [comment]
Looking at it a bit more to make it work without replacing the whole thing is to change..

this.pos = this.options.duration ?
			jQuery.easing[ this.easing ]( percent ) :
			percent;

to...

this.pos = this.options.duration ?
			jQuery.easing[ this.easing ]( percent, this.options.duration * percent, 0, 1, this.options.duration ) :
			percent;

**Comment by Beavykins** [comment]
Looking at it more you don't need to replace the whole thing, to make it work with the new format changing...

`this.pos = this.options.duration ?
			jQuery.easing[ this.easing ]( percent ) :
			percent;`

to...

`this.pos = this.options.duration ?
			jQuery.easing[ this.easing ]( percent, this.options.duration * percent, 0, 1, this.options.duration ) :
			percent;`

Fixes the issue.

**Comment by mgol** [comment]
The other parameters to easings were not used by any easings defined by jQuery or jQuery UI so we removed them in b7a7dea95f84d6d8e5a8186d4fb09a762baf79bb. Do you perhaps use some external libraries that still use those parameters?

Could you provide a test case at https://jsfiddle.net or https://jsbin.com?

**Comment by Beavykins** [comment]
Yes this doesn't break the core easing methods but does break custom extended ones.

You can see a fiddle https://jsfiddle.net/3r5nvue7/2/ , currently set to jQuery edge and doesn't work, changing it to Alpha 3.0 does.

If these parameters are removed from 3.0 will we still be able to extend the easing in a useful way?

Thanks.

**Comment by mgol** [comment]
We removed those parameters because they were redundant, all the necessary information needed for easing purposes is possible to get out of the first parameter.

Your example can be written in this way: https://jsfiddle.net/m_gol/3r5nvue7/3/. By the way, look how cleaner it is if you just use the first parameter!

**Comment by markelog** [comment]
Either way we should definitely mention this in our release notes, maybe somewhere else, as i have said [here](https://github.com/jquery/jquery-migrate/issues/111#issuecomment-177448908) this could be big :/.

/cc @timmywil @gnarf @Mr21 

@mgol it seems we can close this?

**Comment by Beavykins** [comment]
Thanks @mgol

I'm no expert in easing so didn't know how easy it would be to update them to work with the single parameter.

I agree that this should be documented but I assumed that would happen anyway at some point.

I look forward to somebody creating a new library of easing methods in the new format, I don't event want to attempt this

`easeInOutElastic: function (x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d/2)==2) return b+c;  if (!p) p=d*(.3*1.5);
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		if (t < 1) return -.5*(a*Math.pow(2,10*(t-=1)) * Math.sin( (t*d-s)*(2*Math.PI)/p )) + b;
		return a*Math.pow(2,-10*(t-=1)) * Math.sin( (t*d-s)*(2*Math.PI)/p )*.5 + c + b;
	},`

**Comment by markelog** [comment]
>  look forward to somebody creating a new library of easing methods in the new format, I don't event want to attempt this

It's just looks intimidating, in actuality, it is relatively easy, those params was really redundant, like [check out](https://github.com/jquery/jquery-ui/commit/c0093b599fcd58b6ad122ab425c4cc1a4da4a520#diff-9cd789a170c765edcf0f4854db386e1a) jQuery-ui commit when they were migrating from them.

**Comment by Beavykins** [comment]
That's really interesting, thanks @markelog

**Comment by mgol** [comment]
@Beavykins It's always possible to define new easings that would wrap these old ones:
```js
jQuery.easing.myNewEasing = function ( p ) {
    myOldEasing( p, p, 0, 1, 1 );
};
```

This snippet shows you can easily rewrite the old one, actually; e.g. in your example it would amount to find+replace the variables inside the code according to the pattern:

1. `x` - no changes
1. `t -> x`
1. `b -> 0`
1. `c -> 1`
1. `d -> 1`

I'll close this issue as there's a relatively easy migration path and we're allowed to introduce some breaking changes in 3.0.0. Feel free to comment if you have more remarks, though, @Beavykins. And thanks for spending your time to report it!

**Comment by Beavykins** [comment]
No problem, thanks for the detailed explanation.
