### ISSUE TITLE
[Question]: is it possible to monkey patch animate so you don't wait until the callback fires?

### ISSUE THREAD

**Issue by toranb** [jquery/jquery#2966]
I'm doing some testing and in some scenarios the callback of animate is harmful to the speed and reliability of the test suite so I was looking for ways to have it run synchronous instead of async (skipping the callback) and I'm curious if this is possible or how others have worked around this for testing.

Thank you in advance!

**Comment by markelog** [comment]
Check out how we test our animation module - https://github.com/jquery/jquery/blob/93a8fa6bfc1c8a469e188630b61e736dfb69e128/test/unit/animation.js. 

We [stub](https://github.com/jquery/jquery/blob/93a8fa6bfc1c8a469e188630b61e736dfb69e128/test/unit/animation.js#L18) the timers with sinon, and fake the passing of time, back when we used the real ones, animation suite was **much** slower. I believe that should solve your issue.

**Comment by toranb** [comment]
I also found this ... not sure it's still the recommended way to go but worth throwing out here

https://api.jquery.com/jquery.fx.off/

**Comment by markelog** [comment]
You would skip a lot of logic, can't check for state during the animation and it wouldn't be a simulation of real environment in which units supposed to run, plus that is changing the global state which is in impure.

But i suppose it could be relevant for some cases.
