### ISSUE TITLE
jquery.validation group of controls

### ISSUE THREAD

**Issue by CodersExpo** [jquery/jquery#2967]
If you have a group of controls to validate I suggest we change the jquery.validate.js checkForm: function to:

		checkForm: function() {
			this.prepareForm();
			for (var i = 0, elements = (this.currentElements = this.elements()) ; elements[i]; i++) {
			    var elementArray = this.findByName(elements[i].name);
			    if (elementArray.length != undefined && elementArray.length > 1) {
			        for (var count = 0; count < elementArray.length; count++) {
			            this.check(elementArray[count]);
			        }
			    }
                else
				    this.check( elements[ i ] );
			}
			return this.valid();
		}

Now I can and a name on my element and a unique id and when I submit I can do:

        $("form").validate({
            submitHandler: function () {
                self.save();
            },
            rules: {
                CustomerName: {
                    required: true,
                    maxlength: 30
                },
                PONumber: {
                    maxlength: 10
                },
                // The following required a unique Id be established 
                // and a code change to the jquery validate at the checkForm: function()
                ProductCode: {
                    required: true,
                    maxlength: 15
                },
                Quantity: {
                    required: true,
                    digits: true,
                    range: [1, 1000000]
                },
                UnitPrice: {
                    required: true,
                    number: true,
                    range: [0, 1000000]
                }
            }
        });

**Comment by mgol** [comment]
This is the jQuery bug tracker; you should report issues related to plugins to those plugins. In this case, the repo is at https://github.com/jzaefferer/jquery-validation/.
