### ISSUE TITLE
isPlainObject difference between v2.2.1 and v1.11.2

### ISSUE THREAD

**Issue by mitar** [jquery/jquery#2968]
It seems that there is a difference for the following object between v2.2.1 (it returns that it is the plain object) and v1.11.2 (it returns that it is not):

```javascript
var parentObj = {foo: "bar"};
var childObj = Object.assign(Object.create(parentObj), {bar: "foo"});
jQuery.isPlainObject(childObj);
```

I think that 1.11.2 is correct.

**Comment by mgol** [comment]
Confirmed. The [API page](https://api.jquery.com/jQuery.isPlainObject/) says:

> Check to see if an object is a plain object (created using "{}" or "new Object").

and the object presented here can't be created in this way.

The problem is present both on `master` and `2.2-stable` but not present on `1.12-stable` (so 1.12.1 is OK as well).

Thanks for the report!
