### ISSUE TITLE
Unintended/redundant onload event in 2.2/1.12

### ISSUE THREAD

**Issue by alecpl** [jquery/jquery#2977]
I migrated from 2.1.4 to 2.2.1 and found a strange issue. Sorry, I can't provide a simple code to reproduce, but maybe you'll find out what's going on. Steps:
1. Open a jQuery-UI (1.10.4) dialog with a few tabs.
2. In one tab I have an upload form with hidden iframe. In more detail, the iframe is created ad-hoc on "Upload" button click. Something like:
```
$('<iframe>').attr(...).appendTo(document.body).on('load', {some:data}, onload_fn);
$(form).attr({target: frame_name, ...}).submit();
```
3. When I click the "Upload" button the form is submitted and all is fine, but...
4. When I then select any other tab the onload_fn is executed once again. Only once, switching tabs does not execute the onload again... until I create another iframe.

What's more the redundant event is also executed when I just close the dialog, so tabs may be not required to reproduce the issue.

**Comment by alecpl** [comment]
Reproduceable with recent Firefox and Chromium, not tested other browsers. I can add that the event argument of the function looks the same, in Chrome it differs only in timeStamp value (in Firefox it's 0 for both).

**Comment by alecpl** [comment]
This happens also with 2.2.0 and 1.12. I can't test with 3.0 as it produces other errors (probably because of old jquery-ui).

**Comment by mgol** [comment]
jQuery UI 0.10.4 was released on January 17, 2014 so it may not work with recent jQueries. You should most likely first update jQuery UI first and only then try to update jQuery itself (jQuery UI supports many jQuery versions but it can't ensure compatibility for ones released after jQuery UI itself). You should read the [jQuery UI 1.11 upgrade guide](https://jqueryui.com/upgrade-guide/1.11/) and try to upgrade to UI 1.11.4. Is there anything blocking you from doing that?

**Comment by alecpl** [comment]
We still support IE7 in a way that we use older jQuery if IE7 is detected, but we use one jQuery-UI version for all browsers. I'll try to do a test with 1.11.

**Comment by mgol** [comment]
According to https://blog.jqueryui.com/2014/06/jquery-ui-1-11-0/:

> As of this release we are no longer accepting bug reports for IE7 issues. We have also removed IE7 from our testing infrastructure. The IE7 workarounds are still present in the code, but we will remove them for jQuery UI 1.12.

So there's hight chance UI 1.11.x should work in IE 7 since old workarounds haven't been removed.

**Comment by alecpl** [comment]
I confirm that the issue does not exist when using jQuery-UI 1.11.4. In case anyone wanted to dig deeper, here's the simple reproduction page (test.html):
```
<html>
<head>
<link rel="stylesheet" type="text/css" href="jquery-ui.theme.css"/>
<script src="program/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="jquery-ui.js"></script>
</head>
<body>
<div id="dlg">
  <form id="form" action="test.html">
    <input type="button" value="Click" id="button">
  </form>
</div>
<script>
$('#button').click(function() {
  $('<iframe>').attr({name: 'iframe'})
    .appendTo(document.body)
    .on('load', function() {
      console.log('onload');
    });
  $('#form').attr({target: 'iframe'}).submit();
});
$('#dlg').dialog();
</script>
</body>
</html>
```

**Comment by mgol** [comment]
Thanks for the update!
