### ISSUE TITLE
Cannot set `val()` for select options containing tabs (`\t`)

### ISSUE THREAD

**Issue by carols10cents** [jquery/jquery#2978]
I have a select element that contains options whose values contain tab characters. My original use case was a trailing tab (`string\t`), but I've also tested with leading tabs (`\tstring`) and tabs in the middle of non-whitespace (`str\ting`).

I called `.val('value with tab')` on the select element and expected the corresponding option to be selected since the values are identical, but no option is selected.

A few interesting observations:
- I can work around this issue for the leading and trailing cases by removing the leading or trailing tab characters from the string I pass to `.val()`, but this is unexpected since the values don't match exactly.
- Removing a middle tab character and passing that to `.val()` does not select the value, so there is no workaround for strings that have tab characters in the middle.
- The behavior is the same with jquery 2.2.1, 3.0.0-alpha1 and edge.
- With jquery 1.12.1, the leading and trailing tabs have the bug behavior but having a tab in the middle of the word and passing a matching string with a tab in the middle works as expected, so there was a regression at some point in this case.

JSFiddle: https://jsfiddle.net/onnucjx7/2/ You'll see in the console what I expect the behavior to be compared to what the behavior actually is. 

I searched for "tab" and "whitespace" and didn't see anything directly relevant; I did find this issue https://github.com/jquery/jquery/issues/1902 but it only mentions IE10 and I am seeing the unexpected behavior in Firefox 44 and Chrome 48.

**Comment by dmethvin** [comment]
Yeah, [this bug fix](https://github.com/jquery/jquery/blob/b43a3685b60b307d61f41f0c94412380ed46ab22/src/attributes/val.js#L85) seems responsible. [Here's the PR and discussion](https://github.com/jquery/jquery/pull/1531). If we pull out that fix it seems like the code you're trying to use may not work on IE9 or 10, but then again we seem to have broken it consistently everywhere with this.

**Comment by gibson042** [comment]
Actually, it looks to me like f6302b0b53d61dfe1adbfaf6612be5cbced5bbc1 was overzealous in expanding 541e7349b6533eb533c15d17e3e9e432e4a719ea to include trimming of _values_ rather than just text. I think a partial revert is in order.

**Comment by mgol** [comment]
Is it really broken, though? From what I see we do the same that Chrome/Firefox does with one exception that we return `null` when no value is selected instead of an empty string: https://jsfiddle.net/m_gol/onnucjx7/3/

**Comment by gibson042** [comment]
I think your fiddle is broken with respect to my comment (what's with the `val` attributes and replaced whitespace?). Focusing on `value`, I see the same behavior in Chrome, Firefox, and Edge: https://jsfiddle.net/onnucjx7/4/

All three are defining the [`value` IDL attribute](https://html.spec.whatwg.org/multipage/forms.html#dom-option-value) as a [stripped and collapsed whitespace](https://html.spec.whatwg.org/multipage/infrastructure.html#strip-and-collapse-whitespace) version of the content attribute, treating it like [`text`](https://html.spec.whatwg.org/multipage/forms.html#dom-option-text) instead of following the spec.
