### ISSUE TITLE
Chrome produces warning about SVG when not searching for SVG

### ISSUE THREAD

**Issue by starfishmod** [jquery/jquery#2980]
Please see fiddle https://jsfiddle.net/eq0xb5j5/11/ but make sure you have the dev window open first as the warning is displayed once and you need to refesh the page to see it again.

I have a selector of "input[requiredifvisible][type=checkbox]:not(:checked):visible,select[requiredifvisible]:visible"

In doing this it hits the jQuery.expr.filters.hidden on any embedded SVG elements (in fact it goes through this function for ALL elements) in doing so it throws the error:

'SVGElement.offsetWidth' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.

I know there has been previous discussion about SVG and not supporting the offsetWidth to check visible - note this is not what I'm concerned about I'm only searching for input in a document that happens to have SVG elements.

if I try the selector of $('input[requiredifvisible][type=checkbox]:not(:checked):visible') or $('select[requiredifvisible]:visible') separately I don't seem to trigger this warning.

This is on jquery 1.12.1 Chrome 49.0.2623.75 beta (64-bit) - I have not checked other browsers.

**Comment by mgol** [comment]
This is harmless; when those methods go away in Chrome 50, the warnings will disappear but the code will still work. See https://github.com/jquery/jquery/issues/2889#issuecomment-183242987 for more details.

**Comment by starfishmod** [comment]
Ok thanks, so I guess it is ok that a the selector match filter order works differently when searching for singularly vs when there are multiple selectors? And that it searches for all element visibility before it filters on tag? 
I would have thought it would be less processing power to check a tag name vs it's visibility.

**Comment by mgol** [comment]
jQuery (or, more precisely, [Sizzle](https://github.com/jquery/sizzle)) matches selectors from right to left similarly to how browsers behave. Maybe it'd be good to have an exception for custom filters but it'd require selector rewriting so it's not a trivial task to achieve in general. @gibson042 would know more about that.

Those selectors are slow so it's best to avoid them but if you have to use them, rewrite your selector to not include them and then filter over the result, i.e. change:
```js
$("input[requiredifvisible][type=checkbox]:not(:checked):visible,select[requiredifvisible]:visible");
```
to:
```js
$("input[requiredifvisible][type=checkbox]:not(:checked),select[requiredifvisible]").filter(":visible");
```

In this way the selector may go through `querySelectorAll` which is faster than Sizzle (in general).

In any case, these performance-related things are not related to the original report so I'll leave this closed. If you have some ideas how to improve the performance of such selectors, please open a new issue at https://github.com/jquery/sizzle/issues.

Thanks!
