### ISSUE TITLE
touchend delegated event handler reports wrong currentTarget

### ISSUE THREAD

**Issue by jlchereau** [jquery/jquery#2987]
To reproduce, use the following html on the latest versions of Windows browsers as of today.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-1.12.1.min.js"></script>
    <title>Title</title>
    <style>
        .container {
            position: relative;
            height:100px;
            width:500px;
            border:solid 1px black;
        }
        .delegate {
            position:absolute;
            height:40px;
            width:40px;
            border:solid 1px red;
        }
    </style>
</head>
<body>
<div>
    <ol>
        <li>With the mouse, try to drag the left block onto the right block (blocks won't move).</li>
        <li>With your finger on a touch screen, try to drag the left block onto the right block (blocks wont't move either).</li>
        <li>Look at the console logs and compare the currentTarget on mouseup and touchend.</li>
    </ol>
</div>
<div class="container">
    <div id="block1" class="delegate" style="top:30px; left:30px"></div>
    <div id="block2" class="delegate" style="top:30px; left:430px"></div>
</div>
<script>
;(function() {
    $(document)
        .on('mousedown touchstart', '.delegate', function(e) {
            console.log(e.type + ' on ' + $(e.currentTarget).attr('id'));
        })
        // .on('mousemove touchmove', function(e) {
        //    console.log(e.type + ' on ' + $(e.currentTarget).attr('id'));
        // })
        .on('mouseup touchend', '.delegate', function(e) {
            console.log(e.type + ' on ' + $(e.currentTarget).attr('id'));
        });


} ());
</script>
</body>
</html>
```

the result in chrome on Windows 8.1 (latest updates applied) is:

![image](https://cloud.githubusercontent.com/assets/2556751/13722300/b47b28cc-e838-11e5-9275-ff2f20e62095.png)

If this is by design, how to use touchend to get the destination block in order to draw a connection with the origin block as you would with mouseup?

**Comment by jlchereau** [comment]
The same in Internet Explorer 11:
![image](https://cloud.githubusercontent.com/assets/2556751/13722325/8ea10382-e839-11e5-880f-ea004142475a.png)

**Comment by jlchereau** [comment]
The same in Firefox:

- touchstart is reported as mousedown
- touchend is reported as mouseup on the right target!

![image](https://cloud.githubusercontent.com/assets/2556751/13722356/931d1e04-e83a-11e5-976f-08be7bafa2c9.png)

**Comment by dmethvin** [comment]
Can you move this example to jsbin.com or jsfiddle.net?

**Comment by jlchereau** [comment]
See https://jsfiddle.net/pchvc9p7/2/

**Comment by dmethvin** [comment]
Touch events are an Apple invention, they are being simulated on Windows. Chrome simulates them, Firefox does not, which explains the touch/mouse difference.

As for `currentTarget`, you are using jQuery delegated events. If you look at the native `e.originalEvent.currentTarget` it is the target where the event is being handled, which is `document` as the code requested. The `e.currentTarget` is set by jQuery to the element being handled, which seems correct. 

Do these values differ from ones that you are getting on iOS in some way? If so, how?

**Comment by jlchereau** [comment]
Touch events are tricky because some browsers convert touch interactions into mouse events and touch events are inconsistent with mouse events. Nevertheless, I have been able to get workarounds using ```elementFromPoint``` except for Internet Explorer.

Internet Explorer seems to convert touch interactions into mouse events, but lifting the finger from the touch surface does does not trigger a mouseup (see screenshot above).

**Comment by dmethvin** [comment]
jQuery should be passing through all the events that occur. Are you seeing a case where that does not happen? It does not sound like this is describing a jQuery bug.

**Comment by jlchereau** [comment]
My understanding was that jQuery made sure to abstract browsers and bring back consistency (see key events and e.which for example). There is one sure thing: this is totally inconsistent across browsers and workarounds require browser testing. Whether this is a jQuery bug or not relates to specs and design and I could not tell.

**Comment by dmethvin** [comment]
jQuery does not try to synthesize or normalize touch events they are not standard and not consistent across browsers. There are many cases where existing code attempts to use the presence or firing of touch events as an indicator that they are on a specific platform, and the code changes behavior accordingly. As a result, synthesizing or generating touch events can actually break a page. See [this blog post under Compatibility](https://blogs.msdn.microsoft.com/ie/2014/09/05/making-the-web-just-work-with-any-input-mouse-touch-and-pointer-events/) for example.

If you are looking for a cross-platform way to handle touch and mouse, take a look at pointer events [PEP](https://github.com/jquery/PEP).

**Comment by jlchereau** [comment]
Looks great.Thx!

**Comment by jlchereau** [comment]
For anyone's information, PEP won't solve the consistency issues I have been experiencing (although it might solve others). The actual solution, whether you are using PEP or not, consists in adding ```touch-action:none;``` to the CSS class of "touchable" elements. In the example above, this is the ```.delegate``` class. **So this is definitively not a jQuery defect.**

So the example that works consistently in all browsers (at least on Windows) is:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--script src="https://code.jquery.com/jquery-1.12.1.min.js"></script-->
    <script src="./src/js/vendor/kendo/jquery-1.12.1.min.js"></script>
    <title>Title</title>
    <style>
        .container {
            position: relative;
            height:100px;
            width:500px;
            border:solid 1px black;
        }
        .delegate {
            position:absolute;
            height:40px;
            width:40px;
            border:solid 1px red;
            touch-action: none;
        }
    </style>
</head>
<body>
<div>
    <ol>
        <li>With the mouse, try to drag the left block onto the right block (blocks won't move).</li>
        <li>With your finger on a touch screen, try to drag the left block onto the right block () blocks wont't move eiher.</li>
        <li>Look at the console logs and compare the currentTarget on mouseup and touchend.</li>
    </ol>
</div>
<div class="container">
    <div id="block1" class="delegate" style="top:30px; left:30px"></div>
    <div id="block2" class="delegate" style="top:30px; left:430px"></div>
</div>
<script>
;(function() {
    $(document)
        .on('mousedown touchstart', '.delegate', function(e) {
            console.log(e.type + ' on ' + $(e.currentTarget).attr('id'));
        })
        // .on('mousemove touchmove', function(e) {
        //    console.log(e.type + ' on ' + $(e.currentTarget).attr('id'));
        // })
        .on('mouseup touchend', '.delegate', function(e) {
            var changedTouches = e.originalEvent && e.originalEvent.changedTouches;
            var elem = changedTouches ? document.elementFromPoint(changedTouches[0].clientX, changedTouches[0].clientY) : e.currentTarget;
            console.log(e.type + ' on ' + $(elem).attr('id'));
        });

} ());
</script>
</body>
</html>
```
