### ISSUE TITLE
What is included in the slim version of jQuery?

### ISSUE THREAD

**Issue by BramVanroy** [jquery/jquery#2995]
I've seen the use of jquery.slim.js but I can't seem to find any documentation on it on the internet. Probably I'm simply searching with the wrong terms but still, I'd like to know.

**Comment by timmywil** [comment]
Thanks for opening an issue. Note that there hasn't been a final release of a slim build yet. We will include an explanation in the 3.0 final blog post (and we'll probably want to find a place somewhere on jquery.com). That said, it is a custom build of jQuery that excludes effects, ajax, and deprecated code.
