### ISSUE TITLE
`is("visible")`  doesn't work within a modal

### ISSUE THREAD

**Issue by lo-tp** [jquery/jquery#3001]
I use `$("selector").is(":visible")` to check the visibility of an element a lot.

However, when working with an element within a modal(bootstrap modal), this simply malfunctions.

Eventhough I find a way to use `$("selector").css("display")` as a makeshift, this is still a problem worth a solution.

Please, check this [jsiddle page][example] out to see more relevant infomations about this issue.

[example]:https://jsfiddle.net/jn111sum/2/

**Comment by dmethvin** [comment]
This is not a jQuery bug. Please ask for help with Bootstrap plugins on StackOverflow.
https://jsfiddle.net/jn111sum/3/
