### ISSUE TITLE
Internal use of jQuery.trim erroneously strips too much

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#3003]
All internal use of `jQuery.trim` should be replaced with the HTML [strip and collapse whitespace](https://html.spec.whatwg.org/multipage/infrastructure.html#strip-and-collapse-whitespace) operation, which only modifies a [small set of ASCII whitespace](https://html.spec.whatwg.org/multipage/infrastructure.html#space-character) characters.

Problem: https://jsfiddle.net/5Lhfgd3r/
Solution: https://github.com/jquery/jquery/pull/3002#issuecomment-197138246

**Comment by markelog** [comment]
I probably know answer to this, but do we want to expose it?

**Comment by markelog** [comment]
Also, i don't think you mean *All internal use*

**Comment by timmywil** [comment]
:+1: It might just be all internal uses, but we'll want to double check each one.

**Comment by gibson042** [comment]
I really do mean all internal uses: https://github.com/jquery/jquery/search?utf8=%E2%9C%93&q=trim+path%3Asrc&type=Code

**Comment by markelog** [comment]
So why we need to trim `dataType` ajax argument in way that is compatible with html spec?

**Comment by gibson042** [comment]
> So why we need to trim `dataType` ajax argument in way that is compatible with html spec?

CSS Selectors spec in that case, which fortunately [shares](https://www.w3.org/TR/css3-selectors/#selector-syntax) the HTML definition of whitespace. And it's not about what we need to do, but about what we need to _stop_ doing: https://jsfiddle.net/5Lhfgd3r/1/

**Comment by gibson042** [comment]
Oops, wrong example. https://github.com/jquery/jquery/blob/93a8fa6bfc1c8a469e188630b61e736dfb69e128/src/ajax.js#L532 should abandon `jQuery.trim` because we [document](http://api.jquery.com/jQuery.ajax/) "space-separated values", making it at best superfluous (and in fact, it looks to me like the call can be removed and replaced with nothing, since the subsequent `match` will ignore leading/trailing space anyway).

**Comment by dmethvin** [comment]
Agreed, there's no need to trim at all with that regex.

**Comment by mgol** [comment]
@gibson042 Do you want to take it? If you don't have time I can get it & #3072.
