### ISSUE TITLE
outerWidth/outerHeight does not return decimal values when it should

### ISSUE THREAD

**Issue by mlhDevelopment** [jquery/jquery#3004]
When using outerWidth and outerHeight in combination with subpixel rendering, the postion() properties return correct subpixel values but the outer* functions return incorrect values.

Consider this code snippet, with a full example [here](https://jsfiddle.net/mlhDevelopment/wekfwv0a/):

```
innerDiv.css({ left: 75.75, width: 175.75 });
innerDiv.position().left == 75.75; // returns true
innerDiv.outerWidth() == 175.75; // returns false
```

This happens in IE 11, FF 47.0a2, and Chrome 49.0.2623.87 m.

**Comment by timmywil** [comment]
Thanks for opening an issue, but this has already been fixed on master. https://jsfiddle.net/timmywil/wekfwv0a/3/

Duplicate of gh-1724.
