### ISSUE TITLE
$.param() returns "null" and "undefined" literal if attribute is function

### ISSUE THREAD

**Issue by jtrumbull** [jquery/jquery#3005]
```javascript
var param = $.param({
  a: function () {},
  b: function () { return null; }
});
```
Will result in `a=undefined&b=null`

[jsfiddle](https://jsfiddle.net/joeycakes/s3txrgfu/1/)

The `value == null` check on [Line 61](https://github.com/jquery/jquery/blob/master/src/serialize.js#L61) should happen after the ternary statement, since both `value` and the result of `value()` can be null. i.e.

```javascript
		add = function( key, value ) {

			// If value is a function, invoke it and return its value
			value = jQuery.isFunction( value ) ? value() : value;
			value = value == null ? "" : value;
			s[ s.length ] = encodeURIComponent( key ) + "=" + encodeURIComponent( value );
		};
```

**Comment by gibson042** [comment]
Makes sense to me. Would you like to submit a PR, @jtrumbull?

**Comment by jtrumbull** [comment]
@gibson042 Yeah, just wanted to confirm that there wasn't reasoning behind the current setup.

**Comment by dmethvin** [comment]
This is a breaking change so it either needs to land ASAP or wait for 4.0.

**Comment by mgol** [comment]
The PR looks good to me. Should we just land it?

**Comment by dmethvin** [comment]
:+1: from me

**Comment by gibson042** [comment]
I don't think this is a breaking change, since "the return value of a function is used instead of the function as a String" still holds (http://api.jquery.com/jQuery.param/ ). But please make an issue or PR in https://github.com/jquery/api.jquery.com if you disagree.

**Comment by mgol** [comment]
Hmm, OK. But maybe it's still best to not backport this to 1.12/2.2.

**Comment by gibson042** [comment]
I'm fine with that.

**Comment by dmethvin** [comment]
I see your point, let's call this a 3.0 feature/fix.
