### ISSUE TITLE
requestAnimationFrame isn't effective in compressed version

### ISSUE THREAD

**Issue by zcyzcy88** [jquery/jquery#3006]
![image](https://cloud.githubusercontent.com/assets/15178410/13839189/24a41df6-ec54-11e5-8eb4-ce82555eed5a.png)
Or it is Uglify's feature/bug?

**Comment by mgol** [comment]
rAF is used in the jQuery 3.0.0 beta, 1.x & 2.x lines don't utilize it. You'd see the same in the non-minified version.
