### ISSUE TITLE
Feature request: Allow $.param(function)

### ISSUE THREAD

**Issue by jtrumbull** [jquery/jquery#3008]
Would it be a bad idea for `$.param` to allow a function argument?

```javascript
var params = $.param(function(){
  var obj = {};
  // Dynamically build obj 
  return obj;
});
```

@dmethvin originally mentioned in https://github.com/jquery/jquery/issues/2633
> I'm not a fan of adding more behavior to this API (and documenting it, don't forget). Unfortunately I suppose we've already crossed the Rubicon by calling functions at all, which prevent $.param() from being used as a way to passively serialize an object the way you would with JSON. But I'm still not a fan!

Although I am suggesting additional functionality, I tend to agree with @dmethvin 's point of minimizing the behavior of this function (I am a fan of simple and strict rules).

My thought process being, that if it's allowed on an attribute level, it should certainly be allowed at the root. However, secondarily, I am suggesting that this should __only__ be allowed at the root, and to simply ignore method attributes (similar to `JSON.stringify`). _To me_, it would make more sense to pass a function that builds a dynamic object, than to pass an object that can build dynamic properties -almost seems like the tail is wagging the dog. A natural evolution might be to firstly allow this at the root, and to eventually phase out methods on an attribute basis.

**Comment by dmethvin** [comment]
If it's only for the top level couldn't you just do this already?
```js
var params = $.param((function(){
  var obj = {};
  // Dynamically build obj 
  return obj;
})());
```

**Comment by jtrumbull** [comment]
You can, and your example is essentially how I am handling it now. But I guess for the same reason you wouldn't want to do:
```javascript
var params = $.param({
  a: (function(){ return 1; })(),
  b: (function(){ return 2; })(),
  c: (function(){ return 3; })()
});
```
..more key strokes, more bytes, uglier code. Probably the most relevant reason (for me) is dealing with ambiguous variables.

Consider the following example (which happens frequently in my world):
```javascript
function Widget (options) {
  this.url = options.url;
  this.params = options.params; // Plain object -or method that returns object.
}

Widget.prototype.remoteFunction = function () {
  $.ajax({
    url: this.url,
    data: this.params // Could be object or method
  });
}
```
Simply invoking `this.params` would result in an error if an object was passed. So, I find myself adding abstraction:
```javascript
data: typeof this.params === 'function' ? this.params() : this.params;
```
_(might not seem like much, but this is repeated a few dozen times in each of my projects)_

This seems to break the model of library (most abstract) to plugin (less abstract) to implementation (most defined). And, in my opinion, the most natural place for an ambiguous entry point would be the library.

On a lesser note:

```javascript
function getParams () {
  return {};
}
$.ajax({ url: 'abc.php', data: getParams }); // Seems more intuitive than
$.ajax({ url: 'abc.php', data: getParams() });
```
Allowing a function argument would result in the same for both examples, but currently only the latter would work.

**Comment by gibson042** [comment]
I'm opposed to expanding the input signature in this way, and with @dmethvin on valuing consistency between `jQuery.param` and `JSON.stringify` (i.e., if we call _anything_ it should be as `toJSON` serialization methods). Come to think of it, I wonder how much of this we can deprecate in the 3.x release cycle.

**Comment by timmywil** [comment]
I agree with Dave and Richard.
