### ISSUE TITLE
jQuery 2.2.1 incompatibility with 2.1.4 selector

### ISSUE THREAD

**Issue by alexgurrola** [jquery/jquery#3009]
I'm getting an error with `$('a[href*=#]:not([href=#]):not([data-scroll="false"])')`.  This works perfectly with jquery 2.1.4, but 2.2.1 has broken compatibility when I attempted to switch to it.  The exception is as follows: `Uncaught Error: Syntax error, unrecognized expression: a[href*=#]:not([href=#]):not([data-scroll="false"])`.  Thanks for your assistance.

**Comment by dmethvin** [comment]
Sounds like you have some plugin that needs to be updated, see #2885 and #2824 .
