### ISSUE TITLE
jQuery 3.0 breaks the jQuery Easing plugin

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#3010]
The [jQuery Easing Plugin](http://gsgd.co.uk/sandbox/jquery/easing/) has been around since 2008 and seems to be [heavily used](http://trends.builtwith.com/javascript/jQuery-Easing). Even the [npm downloads](https://www.npmjs.com/package/jquery.easing) are pretty high. The changes we made in 3.0 break this plugin because the plugin (needlessly AFAICT) uses the deprecated/removed args.

There are several ways to address this but the easiest would be to [update the plugin](https://github.com/gdsmith/jquery.easing). @gdsmith would you accept a PR for this? 

Github repo: https://github.com/gdsmith/jquery.easing

**Comment by scottgonzalez** [comment]
Or just deprecate it and point to the easings in jQuery UI which are optimized for size.

**Comment by dmethvin** [comment]
Is there an npm module and cdn distro with just the easings?

**Comment by scottgonzalez** [comment]
No, we don't split out our module into separate releases.

**Comment by markelog** [comment]
> Or just deprecate it and point to the easings in jQuery UI which are optimized for size.

We also loosing on speed front, pretty heavily - https://greensock.com/js/speed.html.

If @gdsmith would help us to bring that speed goodness to core, was that proposed before?

**Comment by dmethvin** [comment]
@gdsmith you around? We'd like to fix this before a release.

**Comment by dmethvin** [comment]
This will be averted by gh-3064. @gdsmith we'd still like to get an update to jquery-easing.

**Comment by gdsmith** [comment]
Sorry guys, missed the boat on this, yes, I'd happily accept a PR

**Comment by dmethvin** [comment]
https://github.com/gdsmith/jquery.easing/pull/21
