### ISSUE TITLE
Revert Ajax behavior change in 1.12.2

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery#3011]
See https://github.com/jquery/jquery/issues/2432#issuecomment-199098662

This XSS update is a behavior change. We reverted in 2.2-stable, but not in 1.12-stable. It should stay in 3.0.

**Comment by mgol** [comment]
Closed by cfe830eefdd7f1e7cb87e9841d1d732d6d99ffae

**Comment by VanessaHenderson** [comment]
So are you leaving 1.12.0, 1.12.1, 1.12.2 with the fix despite it being a breaking change?

**Comment by dmethvin** [comment]
Once a version is released, we can't change it. We can only release new versions.
