### ISSUE TITLE
Adding Webpack & Bootstrap in the official docs

### ISSUE THREAD

**Issue by ev1stensberg** [jquery/jquery#3013]
Would be really nice for devs to have a webpack/npm/bootstrap section here:

https://jquery.com/download/

Thanks!

**Comment by timmywil** [comment]
Thanks for opening an issue. However, this is a duplicate of https://github.com/jquery/jquery.com/issues/122. webpack and bootstrap aren't ways to download jQuery, so we'll just be adding npm.

**Comment by timmywil** [comment]
That said, webpack usage instructions are included on the [npm package readme](https://www.npmjs.com/package/jquery#browserifywebpack). All of those usage options apply to bootstrap (depending on how you organize your code), so I don't think we need to mention that one.

**Comment by ev1stensberg** [comment]
Oh, okay! Well, thank you for the response!
