### ISSUE TITLE
replaceWith confusing behaviour with a jQuery set

### ISSUE THREAD

**Issue by yairEO** [jquery/jquery#3024]
// jQuery 2.2.2

    var set = $('<p></p><b></b><i></i>');
    set.filter('b').replaceWith('<a></a>');
    console.log( set );

I would expect `<b>` to be changed to an `<a>` element, but that is **not** the case.

How can one replace an element if not by using `filter` then `replaceWith` ?
Since `filter` creates a *new* jQuery Object, this creates a problem.

Sadly, this seems the awkward way of doing such a simple thing:
http://stackoverflow.com/a/36289638/104380

I suggest updating the API with some kind of a way to do such a replace more easily

**Comment by gibson042** [comment]
`replaceWith` is a DOM operation; it doesn't change the context collection, just ensures that it becomes detached with new content inserted into the DOM where its members used to be (cf. http://jquery.com/upgrade-guide/1.9/#after-before-and-replacewith-with-disconnected-nodes ). To modify the collection itself, follow the linked StackOverflow answer or [use `.map` as suggested later](http://stackoverflow.com/a/36288597).

**Comment by yairEO** [comment]
@gibson042 - using `map` with the `is` method inside it seems less performant than using the answer i've provided in this ticket, no? 

jQuery is a library of useful DOM functions, yet it doesn't do this most simple thing out-of-the-box. Any reason why not?

**Comment by gibson042** [comment]
I haven't checked, but I'd expect a proper `map` to be faster since no DOM manipulation is required (and note that the behavior you seek is _not_ a DOM operation). As for why `replaceWith` no longer manipulates the collection, refer to http://jquery.com/upgrade-guide/1.9/#after-before-and-replacewith-with-disconnected-nodes .

**Comment by yairEO** [comment]
@gibson042 - Actually map wouldn't work well since you will loose all the jQuery data and events bound on the element `<a>` which is to replace `<b>`.

you can't just do this:

    var set = $('<p></p><b></b><i></i>');

    var a = $('a').data('a', 111);
    a.on('click', ()=>{alert(1)})

    set = set.map(function(){
        return $(this).is('b') ? a[0] : this; 
    })

**Comment by dmethvin** [comment]
I don't think this is a common need, evidenced by the lack of complaints in the past 10 years.. What is the use case here?

jQuery is  primarily for selecting and manipulating DOM elements in a document. If you have a collection of DOM elements disconnected from a document, put them in a plain JavaScript array and manipulate them that way, then use `$(array)` to convert them to a collection.

**Comment by yairEO** [comment]
Maybe something like:

    var bar = $("<p>").data("a", 1); // whatever
    collection.replaceItem('.foo', bar); // find an item of the collection which is '.foo' and replaces it with bar.

I might just extend jQuery with such a thing for my own use..
