### ISSUE TITLE
Deprecate jQuery.fn.ready

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#3025]
Although [`jQuery.fn.ready`](https://github.com/jquery/jquery/blob/dabd5ba96c05279b3ffb052db5b8d17f75996694/src/core/ready.js#L10-L16) has the form of a method, it doesn't use context—the following are all equivalent, and specifically equivalent to `jQuery( fn )`:
* `jQuery().ready( fn )`
* `jQuery( document ).ready( fn )`
* `jQuery( "<img src='path/to/img'>" ).ready( fn )`
* `jQuery( document.body.lastChild ).ready( fn )`

We should deprecate it in favor of `jQuery( fn )` and/or [`Promise.resolve( jQuery.ready )`/`jQuery.when( jQuery.ready )`/etc.](https://github.com/jquery/jquery/pull/2891), furthering a trajectory that began with gh-2264.

**Comment by mgol** [comment]
We can do it in 3.1.0, can't we?

**Comment by dmethvin** [comment]
Yeah, we couldn't remove until 4.0 anywaybut I like the idea of deprecating soon.

**Comment by timmywil** [comment]
Fair enough, but let's not make source changes to deprecate right now (for instance, moving to deprecated.js). I'd like to leave that change for 3.1.0.

**Comment by billymoon** [comment]
I think that it's easier to understand what `jQuery( fn )` does when you can state it's a short form of `jQuery().ready( fn )`. There are countless code samples using different forms which would all stop working. Could this introduce a small barrier for people starting with jQuery?

**Comment by mgol** [comment]
Realistically speaking, we're not going to be able to remove it in any
non-distant future. For now it's just about stating our intent about some
forms of these APIs being confusing and hence discouraging their use.

**Comment by dmethvin** [comment]
I rewrote the API description in https://github.com/jquery/api.jquery.com/commit/ba2abaa99d0236e8360efe9e76e778984c91b715 to reflect several different things including the deprecations mentioned here.

**Comment by dmethvin** [comment]
Landed the docs change so I'll close this.
