### ISSUE TITLE
Not possible to remove "required" attribute in Chrome

### ISSUE THREAD

**Issue by Jpsy** [jquery/jquery#3027]
Current Google Chrome 49.0.2623.110 (64-bit)
jQuery 1.12.2
Tested on Mac OS X El Capitan and Windows 7

Fiddle example:
https://jsfiddle.net/tmb3hegb/

Problem:
Form with radio buttons that have required statements in HTML.
Require states are removed using jQuery.
Trying to submit the form fails – Chrome moans that the radios are still required.
Checking the DOM tree with Chrome Developer Tools shows that required is removed.
Multiple ways of un-requiring were tested (removing and setting to false, both with prop and with attr – see JS-code in Fiddle).

**Comment by gibson042** [comment]
This is not a jQuery issue; it manifests with plain Javascript: https://jsfiddle.net/tmb3hegb/1/

**Comment by Jpsy** [comment]
Correct, thanks!
I have filed a Chromium bug report:
https://bugs.chromium.org/p/chromium/issues/detail?id=599040

**Comment by mgol** [comment]
The issue has been fixed in Chrome 50 (current stable).
