### ISSUE TITLE
.contents() returns empty object for inaccessible iframes in Firefox

### ISSUE THREAD

**Issue by julmot** [jquery/jquery#3033]
Example HTML of a local file (`file:///`)

```html
<div class="iframes-inaccessible" id="iframes-inaccessible-target">
    <script>
        var target = document.getElementById("iframes-inaccessible-target");
        var iframe = document.createElement("iframe");
        iframe.src = "http://example.com/";
        target.appendChild(iframe);
    </script>
</div>
<script src="../vendor/jquery/dist/jquery.min.js"></script>
<script>
    $(function() {
        $("div iframe").on("load", function(){
            console.log($(this).contents());
        });
    });
</script>
```

Actually, this will throw an error in Chrome:

> Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "null" from accessing a frame with origin "http://example.com".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "http". Protocols must match.

This is as expected as I don't have access to different origins. However, in Firefox and in PhantomJS this will return an empty jQuery object
```Object { length: 0, prevObject: Object, context: <iframe> }```

I know that there are differences how strictly browsers have implemented the Same-Origin-Policy. However, from a user point of view an empty object does not fully indicate that it was impossible to read the iframe. I'm expecting an error. If Firefox doesn't throw errors but returns empty contents, errors should be thrown from the jQuery layer.

Tested with jQuery 2.2.2 in Firefox 45 and Chrome 49.

**Comment by timmywil** [comment]
Thanks for opening an issue, it works for me. http://jsbin.com/zudeta/edit?html,js,console,output

**Comment by julmot** [comment]
@timmywil Can you please describe what doesn't work for you?
I've viewed your JSBIN and it shows my issue (an empty object in FF):
![empty](https://cloud.githubusercontent.com/assets/8310677/14254468/1f205364-fa90-11e5-93fc-035d7c996b23.png)

Also, you have missed a point:

> Example HTML of a __local file__

JSBIN isn't local. Try this HTML file locally:
```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<title>Test</title>
</head>
<body>
	<div class="iframes-inaccessible" id="iframes-inaccessible-target">
		<script>
			var target = document.getElementById("iframes-inaccessible-target");
			var iframe = document.createElement("iframe");
			iframe.src = "http://example.com/";
			target.appendChild(iframe);
		</script>
	</div>
	<script src="https://code.jquery.com/jquery-2.2.2.min.js"></script>
	<script>
		$(function() {
			console.log("PARENT READY");
			$("div iframe").on("load", function(){
				console.log("LOADED");
				console.log($(this).contents());
			});
		});
	</script>
</body>
</html>
```

#### What you will see in Firefox:
![ff](https://cloud.githubusercontent.com/assets/8310677/14254264/407ea91c-fa8f-11e5-8ef0-04c81b39ceb4.png)

#### What you will see in Chrome:
![chrome](https://cloud.githubusercontent.com/assets/8310677/14254269/44f508d8-fa8f-11e5-8de2-c6ee7fa6db72.png)

#### What I expect
An error that is thrown regardless in which browser this file is displayed

**Comment by timmywil** [comment]
Oh, this is an only an issue when using the file protocol? That would mean this isn't an issue with production code. Regardless, if QSA doesn't select anything, I don't think there's anything we can do.

**Comment by julmot** [comment]
@timmywil 

> Oh, this is an only an issue when using the file protocol?

I'm answering this with a quote:

> I've viewed your JSBIN and it shows my issue (an empty object in FF):

Answer to your second statement:

> Regardless, if QSA doesn't select anything, I don't think there's anything we can do.

Well, what I currently do is detecting if `$iframe.contents()` has `.length === 0`. This will never be true if everything worked correctly, as an iframe will always have an `html, head, body` element. Therefore this check could be done in jQuery and an error could be thrown. If it is true we can assume that the browser wasn't able to read the iframe.

**Comment by timmywil** [comment]
> I've viewed your JSBIN and it shows my issue (an empty object in FF).

I don't see this.

**Comment by timmywil** [comment]
IMO, an error should be thrown (even though I see no error in FF 45.0.1 on mac), making what we do with it insubstantial.

**Comment by timmywil** [comment]
I see. You weren't talking about the iframe not being selected, you were talking about contents being empty. I was looking for something we could feasibly fix. Now that I understand your suggestion, I don't think we could reliably detect when an error should be thrown. Should we throw an error whenever origins are different? And `.contents()` is not the only method that throws an error in browsers. Should it be done when using other jQuery methods like attr or prop? There are exceptions that make answering those questions complicated. For instance, setting location on a cross-domain iframe is valid. I think it's best if we leave the error throwing up to the browsers. I agree the behavior difference is odd, but I would open a bug ticket on FF. They can fix it quickly enough that by the time we figured out the best way to add this error, it wouldn't be needed.

**Comment by julmot** [comment]
I've opened an issue on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1262167
Let's see what happens...

**Comment by bzbarsky** [comment]
Firefox is following the spec here (returning null `.contentDocument` in the cross-origin case).  WebKit does the same.  Chrome is violating the spec.

**Comment by timmywil** [comment]
Thanks @bzbarsky. Chrome bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=600744

**Comment by timmywil** [comment]
The relevant part of the spec, which apparently is under "Obsolete". https://html.spec.whatwg.org/multipage/obsolete.html#dom-frame-contentdocument

**Comment by bzbarsky** [comment]
That's for `.contentDocument` on a `<frame>` element, and it's under "Obsolete" because everything to do with the `<frame>` element is under "Obsolete".  The relevant part of the spec for `<iframe>` is at https://html.spec.whatwg.org/multipage/embedded-content.html#dom-iframe-contentdocument

**Comment by timmywil** [comment]
woops, thanks.
