### ISSUE TITLE
The IE (v: 11.162.x) triggers the wrong event

### ISSUE THREAD

**Issue by 00091701** [jquery/jquery#3036]
If I run my demo in the IE 11.162.10586.0 I get the alert dialog with "Problem". In all other browsers it work as expected.

http://jsbin.com/domopikafo/edit?html,output

Any ideas for a fix or a workaround?

**Comment by timmywil** [comment]
Thanks for opening an issue. I tested in IE 11 and it works as expected for me. If you need further assistance, please ask on the [forums](https://forum.jquery.com/) or in the #jquery irc channel.

**Comment by 00091701** [comment]
I made a screencast to show the problem.
http://screencast.com/t/RrHMleAVN3sj

**Comment by dmethvin** [comment]
You can see that the behavior is exactly the same without jQuery: 
http://jsbin.com/yavexecize/edit?html,output

This is not a jQuery bug and is not something we can work around.
