### ISSUE TITLE
Async ready event may let window.onload run before it

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#3040]
http://jsbin.com/mecowewibi/4/edit?html,output

This seems like it will cause trouble. Timmy's spidey sense was tingling on this one.

**Comment by timmywil** [comment]
It might be an issue, but I'd be okay with leaving it in for now.

**Comment by dmethvin** [comment]
i can work around it in the unit test and we can see if we get any complaints.

**Comment by dmethvin** [comment]
See https://github.com/jquery/jquery/commit/5cbb234dd3273d8e0bbd454fb431ad639c7242c1#commitcomment-16963004 , I have a PR incoming to fix this in a rather hacky way but still not sure of the implications for code in the field.

**Comment by dmethvin** [comment]
Closing for now, the unit tests no longer have the race condition and we can see if code expects this in the field.
