### ISSUE TITLE
Element which is not in page still :visible in IE8

### ISSUE THREAD

**Issue by RobertMe** [jquery/jquery#3043]
Hi,

I'm having an issue with the `:visible`/`:hidden` check giving the wrong result in IE8 when the element under test isn't in the page.

A simplified testcase is the following snippet: `$('<div>Test</div>').is(':visible')` In all browsers the result of this is `false` (because the element isn't in the page), except in IE8, for which it actually is `true`.

From what I've investigated it seems like the issue is the final return of the `filterHidden` function: https://github.com/jquery/jquery/blob/1.12-stable/src/css/hiddenVisibleSelectors.js#L19
I think this must check if the resulting `node` is a document fragment. If it is a fragment the element can't be visible, and the result must thus be `true`. And there may possibly be different node types which could be the parent while the element isn't actually in the page, for which the test also returns the wrong result.

**Comment by dmethvin** [comment]
Is this a regression? That is, did it work in a previous version of jQuery? The docs say this which seem to indicate the IE8 result is incorrect:

> Elements that are not in a document are considered hidden; jQuery does not have a way to know if they will be visible when appended to a document since it depends on the applicable styles.

I think we'd need to do a `jQuery.contains()` check to ensure it was disconnected.

**Comment by RobertMe** [comment]
Yes, I forgot to mention that. I'm currently using version 1.9.1 for which it does work as expected.

**Comment by timmywil** [comment]
Confirmed. Test case: http://jsbin.com/puwifu/edit?html,js,console

**Comment by mgol** [comment]
This was working fine in 1.11.3: http://jsbin.com/liziju/edit?html,js,console. Therefore, it's a recent regression.

**Comment by boonebgorges** [comment]
I was also experiencing this issue and bisected it to ecf52b948bcc7c9a28b5b2f93a0764868f09428e.

**Comment by timmywil** [comment]
Fixed in 1.12-stable. c43066c41ec84ac5e5fe7fb3e6cd3a912a395140
