### ISSUE TITLE
Exposing filter pseudo functions for use with elements directly

### ISSUE THREAD

**Issue by hexalys** [jquery/jquery#3046]
Very often I am wanting to get access to common pseudo methods such as:
`:focus`, `:selected`, `:checked` or `:empty` etc. for a single target element in an event callback.

For that, I currently have two options:

1. Either write my own code (duplicating jQuery's failsafe methods). Which seems redundant.
2. Wrap the element into jQuery and use the `$.fn.is(:peudo)` selector.

Both are however wasteful of resources. Given that those methods (taking a single element argument), are already in the code base. They have a legit case to be used directly. But they are not exposed...

Could they be exposed to an `$.is` set of functions as well. It would allow simple efficient checks like `$.is.focus(el)` without having to go through creating a new object and runs regex exprs needlessly?

**Comment by dmethvin** [comment]
The pseudo selectors are in `jQuery.expr.pseudos` so they're accessible and you can [add your own](https://github.com/jquery/sizzle/wiki#sizzleselectorspseudosname--function-elem--), we just haven't ever documented the specifics of which selectors might be there by default.  In reality I doubt that `$(elem).is(":even")` is any kind of performance bottleneck.

**Comment by hexalys** [comment]
@dmethvin Ah ok. I didn't realize they were accessible. Sorry for catching that.

And sure. It's not that it's are performance bottlenecks per se. It just feels silly to rewrite the same code if already available. In a vanilla js context having to use the wrapper outside of jQuery's scope is just unnecessary.

So it safe to write a plugin helper function using the $.expr.filters object?

**Comment by dmethvin** [comment]
For your own use? Probably so, but I'll let some others think about it. As a public plugin you'd need to think about things like whether people are using the alternate selector engine or whether some of the pseudos might be deprecated in the future.

**Comment by hexalys** [comment]
Yeah, for my own use. Given the extensible API. It's manageable, even if removed.
What I am getting at, is a simple syntactic sugar base along those lines:

```
$.is = $.has = function(elem, pseudo){
  $.expr.filters[pseudo](elem);
}
```
Which gives: `$.has(el, 'focus');` or `$.is(this, 'selected');` ('this' being event.currentTarget)
Not sure if that appeals to others, but I find this more elegant along with the associated perf benefits.

Also, there are 3 filter objects, which are essentially the same:
`:`, `pseudos` and `filters`

Any one best to use, for future-proof compatibility?

**Comment by mgol** [comment]
@hexalys See #2073. `pseudos` is the recommended one.

**Comment by hexalys** [comment]
Slightly as an aside to this, but on the same topic:

`jQuery.attr` being exposed as well. Why isn't `$.attr(this, name)` a recommended and/or documented method to simply read element attributes in a similar context?

**Comment by dmethvin** [comment]
Getting a DOM element into a jQuery object is one of the [fastest paths in the code](https://github.com/jquery/jquery/blob/ce6c83f710c28108ccb4d50a7b924baa890dc961/src/core/init.js#L99-102), just a couple of `if`s. IMO there's no reason to short circuit it further and clutter the docs to provide micro-optimizations.

Since `jQuery.expr.pseudos` is exposed I guess we can close this? I don't think there's anything to do on the code side at least.

**Comment by timmywil** [comment]
Agreed, I don't see us adding this to the API. However, this might be a good candidate for a plugin.
