### ISSUE TITLE
Jquery error on URL with #.

### ISSUE THREAD

**Issue by allencazar** [jquery/jquery#3048]
It seemed that Jquery crashes when the URL has a (#) hash sign followed by (.) period sign.

IE:
http://vicommerce.net/infographics-magento-multi-store-functionality/#.VwcZTmcCP98.twitter

> jquery.js:2 Uncaught Error: Syntax error, unrecognized expression: #.VwcZTmcCP98.twitterga.error @ jquery.js:2ga.tokenize @ jquery.js:2ga.select @ jquery.js:2ga @ jquery.js:2m.fn.extend.find @ jquery.js:2m.fn.init @ jquery.js:2e.fn.init @ jquery-migrate.min.js:2m @ jquery.js:2(anonymous function) @ collapse.js:475j @ jquery.js:2k.fireWith @ jquery.js:2m.extend.ready @ jquery.js:2J @ jquery.js:2
vicommerce.net/:150 WPP: OK. Execution time: 0.002101 seconds

I am using
-Windows 10
-Chrome Version 49.0.2623.87 m
-Firefox Developer Edition
-jquery.js?ver=1.11.3

**Comment by dmethvin** [comment]
From the error message this sounds like a dup of #2824 .
