### ISSUE TITLE
$.fn.append throws an Error when given some type of nested array

### ISSUE THREAD

**Issue by kt3k** [jquery/jquery#3050]
jQuery version: 2.2.3
browser: Chrome 51 (mac)

```js
$('<div/>').append(['foo', '<i>bar</i>'])
$('<div/>').append('foo', ['<i>bar</i>'])
$('<div/>').append(['foo', ['<i>bar</i>']])
```

The first 2 examples work as I expected. They create `<div>foo<i>bar</i></div>`.
The last example throws an error like the following:

```
Uncaught TypeError: html.replace is not a function
    at Function.htmlPrefilter
    at buildFragment
    at domManip
    at jQuery.append
```

I think throwing is not appropriate here and the thrown error doesn't seem deliberate one.

**Comment by dmethvin** [comment]
jQuery does not generally guarantee any specific behavior when passed invalid input. Why are you passing nested arrays, and what did you expect it to do?

**Comment by kt3k** [comment]
I was appending nested arrays of html strings with code like the following:

```
apiCall().then(categories => {
  $('<ul/>').append(
    categories.map(category => category.items.map(item => `<li>${item.title}</li>`))
  ).appendTo('#some')
})
```

and I expected every html string in arrays would be appended to the element.

I misunderstood the spec maybe because it already handles one level array of htmlString|jQuery.

```js
$('<div/>').append(['<div />']) // => <div><div></div></div>
$('<div/>').append([$('<div />')]) // => <div><div></div></div>
```

It seems like wrapping contents with array doesn't make difference. So I guessed wrapping the arrays with array is ok as well.

I found this comment in the source code `// Flatten any nested arrays` https://github.com/jquery/jquery/blob/master/src/manipulation.js#L120
It seems trying to flatten (at least one level) nested array.

I thinks it's natural and consistent with the current bahaviour & implementation if it flattens any depth of nested arrays.

**Comment by dmethvin** [comment]
The reason it flattens one level is that we get it for free via `Array.prototype.concat`. To allow an infinite number of levels we would have to traverse the entire set of nested arrays, which adds complexity for a rare case. If you have a data structure like that, traverse it and flatten it before trying to use `.append()`.

**Comment by kt3k** [comment]
OK. Makes sense. Thanks.
