### ISSUE TITLE
Wrap-inner method.

### ISSUE THREAD

**Issue by extempl** [jquery/jquery#3051]
I'd like to suggest new `wrap` method for situations like this:

    <div class="container">
      <div class="inner">Hello</div>
      <div class="inner">Goodbye</div>
    </div>

-> 

    <div class="container">
      <div class="new>
        <div class="inner">Hello</div>
        <div class="inner">Goodbye</div>
      </div>
    </div>

Which you can't achieve with `.wrap()` method.

But you can with something like this:

    var $container = $('.container')
    var $new = $("<div class='new'></div>")
    $container.append($new.append($container.children()))

It may be called something like `wrapInner`, I think.

**Comment by dmethvin** [comment]
Between a normal `.wrap()` and  [`.wrapInner()`](http://api.jquery.com/wrapinner/) and [`.wrapAll()`](http://api.jquery.com/wrapall/) I think we have all the cases already covered. If not, you can write a plugin.

**Comment by extempl** [comment]
Oh, yes, sorry, didn't saw those methods.
