### ISSUE TITLE
Click function toggle stopped working from jQuery 1.9.1

### ISSUE THREAD

**Issue by zwz123** [jquery/jquery#3053]
$(function () {
        $('tr').click(function (event) {
            if (event.target.type != "radio") {
                var that = $(this).find('input:radio');
                that.attr('checked', !that.is(':checked'));
            }
        });
    });

works until v1.9.1 worked on all pre versions and stopped working since this.
Example:
http://jsfiddle.net/KC4DK/
(in settings can toggle which jQuery to use)

**Comment by mgol** [comment]
Use `.prop()`, not `.attr()` for setting element state. See https://jquery.com/upgrade-guide/1.9/#attr-versus-prop- for more info. It works fine then: https://jsfiddle.net/KC4DK/44/.
