### ISSUE TITLE
[req] modify $.fn.eq() to also accept an array?

### ISSUE THREAD

**Issue by r3wt** [jquery/jquery#3058]

**Comment by dmethvin** [comment]
What would it do? [Here's the current docs.](https://api.jquery.com/eq/) Are you looking for `$(selection).is(Array)` maybe?

**Comment by r3wt** [comment]
say i have a collection, and it has 10 elements. based on some math i did, i would like to apply style to very specific elements in that collection. currently, have to call eq many times to do so. but if eq accept array i can do that easily.

**Comment by dmethvin** [comment]
This is more of a StackOverflow question so I'll let you take it there.

**Comment by r3wt** [comment]
how so? this is a request to make `eq` more powerful by being able to reduce to elements in an array which is more tedious to do manually

**Comment by dmethvin** [comment]
I'm not quite sure what you're asking for, so talking it over with some people on StackOverflow will help you to formulate a clear description of what you are looking for. Then you can make a request keeping our guidelines for [new features](https://github.com/jquery/jquery/wiki/Adding-new-features) in mind. Most likely this can be implemented by you (or a helpful StackOverflow answer) as a plugin.

**Comment by r3wt** [comment]
Yeah, i guess i'll just write my own plugin. not worth the trouble bickering

**Comment by mgol** [comment]
I think use cases for that don't meet our [new features](https://github.com/jquery/jquery/wiki/Adding-new-features) guidelines as writing a plugin that does that is easy and just passing an array would not cover all use cases anyway (say, you want to filter every 3rd element etc.).

In ES6 it's actually easy to do even without a plugin:
```js
$(selector).filter(i => [1, 3, 10].includes(i))
```

so i don't think this feature would bring a lot of value at this point.

**Comment by r3wt** [comment]
@mgol how long until ES6 is supported in all browsers? a long time probably. nonetheless, i just wrote myself a simple plugin, since i'm the only one to think the feature is useful.

```js
$.fn.eqMap = function( a )
{
	var c = $();
	if(a instanceof Array){
		for(var b=0;b<a.length;b++){
			c = c.add( $(this).eq( a[b]) );
		}	
	}
	return c;
};
```

thank you for your time.
