### ISSUE TITLE
Remove default Deferred callback context

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#3060]
I ran into an interesting obstacle when working on #3029: our longstanding behavior of using a default context for jQuery.Deferred callbacks (specifically, [the deferred's base promise](http://jsbin.com/tugocasose/edit?js,console)). It's not _necessarily_ a blocker, but it does make `$.when( $.Deferred().resolve() ).done( whatsMyContext )` very counterintuitive (in that I'm not even sure what to code for #3029). For sanity in that case—and for increased similarity with native Promises—I'd like to remove the default, making `*With` methods _required_ to provide a meaningful context. In other words, the preceding code would have either `undefined` or global object context, depending on whether or not it was executed in strict mode.

Any objections?

**Comment by dmethvin** [comment]
Reading through the issues you filed I agree, explicit `*With` seems like a reasonable requirement if you really want context.

**Comment by Krinkle** [comment]
For most code I can't imagine any useful purpose in having the promise available as this value. One would always chain on the promise directly, create a new one, or involve another code that produces a promise. One wouldn't call `then()` inside the then-callback for the same promise.

However there does appear to be one fairly common jQuery-specific use case, that applies to inside callbacks: `state()`.

```js
$.Deferred().reject().always(function () {
  console.log(this.state());
});
```
While I wouldn't expect this pattern in more advanced projects, I wouldn't be surprised to see this often in simple jQuery projects.

```js
/** @return {jQuery.Promise} */
function foo() { /* .. */ }

showSpinner();
foo().always(function () {
  hideSpinner();
  if (this.state() == 'resolve') {
    // Stuff...
  }
});
```

It seems awkward to have to store the promise in a variable for that.

**Comment by Krinkle** [comment]
The following use case was rather counter-intuitive to migrate when using only the text on <https://api.jquery.com/jQuery.Deferred/> and <https://jquery.com/upgrade-guide/3.0/>

```js
function postWithToken(type, params) {
  return api.getToken(type).then(function (token) {
    params.token = token;
    return api.post(params).then(null, function fail() {
      if ( code === 'expired' ) {
        return retryOnce(type, params);
      }
      // Let caller handle any other error
      return this;
    });
}
```

Initial attempt:

```diff
-    return api.post(params).then(null, function fail(err) {
+    return api.post(params).then(null, function fail(err) {
       // Let caller handle any other error
-      return this;
+      return err;
```

I tried this because I previously believed that a `then()` kept the current state if a non-promise is returned (plain value from resolved then is resolved, plain value from rejected then is rejected) - and that creating an explicit Deferred is only needed to change the type from resolved to rejected. However for this case, the following fix is needed:

```diff
-    return api.post(params).then(null, function fail(err) {
+    return api.post(params).then(null, function fail(err) {
       // Let caller handle any other error
-      return this;
+      return $.Deferred.reject(err);
```

This works but recording it here in case it helps someone else, and in case documentation can be improved.
