### ISSUE TITLE
.then improperly propagates progress from locked-in Deferred

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#3062]
When `.then` locks in a Deferred by rebinding to a thenable resolved by its base, progress context is inappropriately propagated as progress _data_, and progress data is in appropriately wrapped in an array. It's probably easier to explain in code than in natural language: https://jsfiddle.net/zwavzvpx/ .

This happens because `.notify` is used where `.notifyWith` belongs, at [deferred.js#L131](https://github.com/jquery/jquery/blob/055cb7534e2dcf7ee8ad145be83cb2d74b5331c7/src/deferred.js#L131).

**Comment by mgol** [comment]
We got an external report as well and as far as I understand it's a regression so I added the "Needs review" label as we might want that for 3.0.0.

**Comment by mgol** [comment]
PR: #3150. Please review, I want to get it in 3.0.0. And thanks @gibson042 for a clear description of the situation and the needed fix!
