### ISSUE TITLE
Specific table CSS style breaks `.is(':visible')`

### ISSUE THREAD

**Issue by webmandesign** [jquery/jquery#3065]
Hi guys,

Recently we stumbled upon a strange issue in WordPress which is related to jQuery version 1.12.0+ too.

Please read https://wordpress.org/support/topic/wp45-jquery-update-and-table-styles-issue for more info on problem and https://core.trac.wordpress.org/ticket/36533#comment:2 (and onward comments) for info on resolution. The issue is resolved in WordPress, but might be related to jQuery project, so that's why I'm reposting it here.

Regards,

Oliver

**Comment by Otto42** [comment]
Possibly related to #3043

**Comment by timmywil** [comment]
Thanks for opening an issue. #3043 only affects IE<9. Perhaps you could create a reduced test case on http://jsbin.com or http://jsfiddle.net to help assess the issue.

**Comment by webmandesign** [comment]
Honestly, I'm really short on replicating the issue on https://jsfiddle.net as I am not a JS developer.

A WordPress core developer could help here, especially someone who coded `wp-includes/js/media-views.js` or knows what the code does. (@Otto42, could you help here?)

If you want to experience the issue yourself, I have provided [instructions on how to replicate it](https://wordpress.org/support/topic/wp45-jquery-update-and-table-styles-issue?replies=9#post-8270285).

Sorry I can't help more!

**Comment by RobertMe** [comment]
> #3043 only affects IE<9.

That's not entirely true. I've also had that issue in other browsers, but this was indeed due to some CSS triggering a false-positive on the check whether to use the IE<9 or "default" logic (for the `jQuery.support.reliableHiddenOffsets()` test). So when you have some specific CSS jQuery will also run the IE<9 logic in modern browsers. And the issue will then thus be visible in more browsers than just IE<9.

**Comment by swissspidy** [comment]
I set up a reduced test case on JS Bin confirming the bug: http://jsbin.com/hopipejuve/1/edit?html,js,console

**Comment by webmandesign** [comment]
@swissspidy Thank you for creating this! It really seems it replicates the issue in a simple way :)

**Comment by radugroza** [comment]
I've also encountered this, it's not only related to creating `<table>` nodes - this one fails when creating a `<div>` node  - tested in Chrome
I've traced this back to 1.12.0 (not happening in 1.11.3).
Here's a fiddle: https://jsfiddle.net/pdqgdeeg/4/

**Comment by RobertMe** [comment]
@radugroza it isn't that the `:visible` check is broken just for `<table>`. But if you apply some form of styling to all tables (as you do in you're example) a feature detection test of jQuery fails. This in turn means a legacy code path (which is normally only run for IE<9) gets run for all the `:visible` tests. And this is what is broken (as described in #3043).

So there are two issues. The first one being that specifying styling on all `<table>`s breaks a test to check if the browser returns/calculates corrects sizes (only IE<9 should return broken sizes, but the CSS on the `<table>` means jQuery acts as if all browsers report the broken size). And the second issue being that the `:visible` check for this "legacy" code path is broken (which means `:visible` checks for all element (types) which aren't in the page will return true while they must be false).

**Comment by mgol** [comment]
It seems we have two issues here then, yikes! Scheduling it for `1.12.4/2.2.4`.

Thanks for the report!

**Comment by mgol** [comment]
I modified the @radugroza's jsbin to compare against 1.11 instead of 1.9 and to compare with the 2.x line. It's clear it only targets 1.12, 2.2 is fine: http://jsbin.com/wanovo/2/edit?html,js,console.

**Comment by timmywil** [comment]
Fixed in 1.12-stable. c41defb7f3813a5f5438534bda4864e46183eb7b

**Comment by webmandesign** [comment]
Thank you for fixing this! :)

**Comment by SlickRemix** [comment]
Yes, thank-you!
