### ISSUE TITLE
JS error is thrown on browser console when accessing UI JQuery code 

### ISSUE THREAD

**Issue by vullnety** [jquery/jquery#3066]
Hi,

As we were testing the UI code functionality for our system, I noticed one unusual JS error message on console log, while doing high level testing with Selenium and catching JS errors for Firefox browser. The error caught is the following:

**Source**: https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js;** Error Message**: Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead; **Line number**: 1;

When this error is thrown on console, it usually crash the Chrome browser, during Selenium testing, but Firefox is only recording this line on console, and test is passing.

Best regards,

Vullnet

**Comment by mgol** [comment]
Hi,

1.9.1 is a very old version of jQuery (3 years old!). We've since stopped appending the sourceMappingURL pragma completely.

In the future please upgrade jQuery & see if the problem still exists before reporting a bug.

Thanks!

**Comment by vullnety** [comment]
Thank you very much!

Will post this to our team and update the following.

Cheers!
