### ISSUE TITLE
:input[type!='hidden'] not working

### ISSUE THREAD

**Issue by AB-ISS** [jquery/jquery#3067]
The query

    $("#mydiv :input[type!='hidden']")

returns input elements with type `hidden`, whereas

    $("#mydiv :input").not("[type='hidden']")

does not.

The documentation states these two queries should return same results, which they don't.

**Comment by dmethvin** [comment]
To be sure it's clear, can you put together an example on jsbin or jsfiddle? Thanks.

**Comment by timmywil** [comment]
Works for me. http://jsbin.com/keduca/edit?html,js,console
