### ISSUE TITLE
Event handlers with invalid selectors should be caught at attach time

### ISSUE THREAD

**Issue by fsateler** [jquery/jquery#3071]
Otherwise, they become very difficult to debug.

See [this jsfiddle](https://jsfiddle.net/v4emgtLs/1/) for an example. Attaching an event handler with an invalid selector `div:not` causes an exception to be raised at event time. This makes it very difficult to debug, as the trace of the error will usually only include jquery code.

I suggest jQuery should throw an exception at attach time instead, which makes it fairly easy to detect the faulty code.

**Comment by gibson042** [comment]
I'm normally opposed to explicitly introducing exceptions, but eliminating this arbitrarily long delay between mistake and feedback seems really valuable. I recommend adding `if ( selector ) { jQuery.find.matchesSelector( elem, selector ); }` in [`jQuery.event.add`](https://github.com/jquery/jquery/blob/91850ecbbe04ad8f5d89dc050aa1d9002047c435/src/event.js#L120). @fsateler, care to submit a PR?

**Comment by markelog** [comment]
I think we already received similar issue before - @dmethvin?

I would tend to agree with assumption here though.

**Comment by fsateler** [comment]
@markelog Indeed, I searched but did not find it. I now see it here: https://github.com/jquery/jquery/issues/2720 

The consensus there seems to be that the check should not be added. A claim was made that the console has the erroneous selector. This is not the case if the selector instead triggers a null reference exception or other error in jquery code (as the `div:not` selector does, this is probably a separate bug that needs fixing). Moreover, if the event was supposed to catch a special condition and prevent navigation, debugging becomes doubly hard. 

Should I prepare and submit a PR?

**Comment by dmethvin** [comment]
I think it would be easier to see the advantages and drawbacks if there was a PR, so I wouldn't mind seeing a proposed solution with unit tests. One I can think of offhand is that custom selector extensions might not yet be in place, but that is probably rare.

**Comment by fsateler** [comment]
ok, will prepare a PR

**Comment by markelog** [comment]
@fsateler cool, check it out - http://contribute.jquery.org/

**Comment by fsateler** [comment]
Sorry for the newbie question, but... how do I run the testsuite? `npm test` does not appear to run the unit tests...

**Comment by mgol** [comment]
@fsateler You need to have a working Apache+PHP setup (see https://github.com/jquery/jquery#running-the-unit-tests) and one domain pointed at the jQuery repository. Then open http://your-jquery-domain/test in a browser you want to check.

**Comment by gibson042** [comment]
`grunt` runs a basic suite, and `grunt test` further includes Promises/A+ in Node.js (not affected here). But real proof of functionality takes place by loading our [QUnit suite](https://github.com/jquery/jquery/blob/master/test/index.html) in-browser. Since this issue is tightly scoped, you can use `?module=event` to speed things up, and even access directly from the filesystem if you don't want to set up a web server.

**Comment by dmethvin** [comment]
I'm labelling this as a behavior change since it has the potential to throw unexpected errors in the case where no event is delivered during a page's lifecycle. The PR looks good to me so I think we should land it in 3.0. Objections? If it lands I'll add a note to the upgrade guide.

**Comment by gibson042** [comment]
"Behavior Change" seems a bit much since this only affects invalid input, but I'm definitely in favor of including this fix in 3.0.

**Comment by dmethvin** [comment]
That's what we thought about `[href=#]` too. :cry: : The discussion there specifically pointed out they wanted to know cases where we start to throw and we didn't before, this is one of them. Better safe than sorry. I'll add a note in the upgrade guide too. Nobody should be complaining we changed behavior and didn't tell them!

**Comment by gibson042** [comment]
Definitely. :+1:
