### ISSUE TITLE
Get rid of excessive "use strict" pragmas in the built file

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#3077]
Since our AMD modules are now strict and we're not stripping the `"use strict";` pragmas when building, we have a lot of (harmless) excessive `"use strict";` statements in the built file. They all get stripped when minified so it's not a big deal, just slightly confusing to casual readers of the built file contents.

**Comment by markelog** [comment]
I wonder if there more tools like https://github.com/gfranko/amdclean out there

**Comment by mgol** [comment]
I have a PR for that that strips the pragma in non-hacky way: #3078.
