### ISSUE TITLE
issues using the map function with autocomplete

### ISSUE THREAD

**Issue by rwales10** [jquery/jquery#3083]
I have been using Jquery autocomplete successfully in the past.  Recently, I upgraded to new versions of jquery and jquery ui, and I am getting errors with the same code.

Working versions: jquery 1.8.2, jquery ui 1.8.24
Failing versions:   jquery 1.10.2, jquery ui 1.11.4

            $('#lakeId').autocomplete({
                delay: 1000,
                minLength: 0,
                source: function (request, response) {
                    $.ajax({
                        url: '@Url.Action("getLakes","BuoyJS")',
                        type: "GET",
                        dataType: "json",
                        data: { term: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { label: item.lakeId, value: item.lakeId };
                            }))
                        }
                    })
                },
            });

When it fails, I get a message indicating that a function is not found in the response $.map statement after a successful return from the server.  Here is a view of what comes back from the server (from Firebug):

![image](https://cloud.githubusercontent.com/assets/12501550/14851947/4668695c-0c51-11e6-8f68-1ff462ac57e7.png)

I spend some time trying to resolve the issue.  When I went back to previous versions of jquery and jquery ui it worked just like it always has for me.

I appreciate all your good work with Jquery.  I am using Jquery to provide rich, user friendly forms for my public service clients at the State of Maine.

**Comment by dmethvin** [comment]
Those versions of jQuery and jQuery UI are several years old. This is the bug tracker for the latest released versions. If you're unable to upgrade you can probably get help on StackOverflow.

**Comment by rwales10** [comment]
Thanks.

I just want to make sure it is clear that the later versions of Jquery are not working with my code, and the earlier versions are working.  I will put this on Stackoverflow.
