### ISSUE TITLE
Selecting anchor links using `href^=#` is broken as of jQuery 2.2

### ISSUE THREAD

**Issue by kimili** [jquery/jquery#3085]
**Description**

In trying to select anchor links on a page using an attribute starts with selector to target any links that have an href that begin with an octothorp, specifically:

```
$('a[href^=#]')
```

The selector is parsed as invalid in jQuery as of version 2.2 and an error is thrown. This is consistent in the latest versions of Safari, Chrome, Firefox and Opera.

Also, it seems that this issue is only problem when using `#` as the attribute value in the selector. Selecting something like `$('a[href^=foo]')` works as expected.

Here are the test cases I set up. The test code is the same in both. Only the version of jQuery differs:

- <https://jsfiddle.net/vh9m4h5r/2/> - Uses jQuery 2.1.4 (test passes)
- <https://jsfiddle.net/139916L6/1/> - Uses jQuery 2.2.3 (test fails)

**Comment by dmethvin** [comment]
Special characters must be quoted, see #3063 and others.
