### ISSUE TITLE
Incorrect `MouseEvent.pageX/pageY`

### ISSUE THREAD

**Issue by anseki** [jquery/jquery#3092]
Related to: https://github.com/jquery/jquery/issues/3080
Original comment: https://github.com/jquery/jquery/issues/3080#issuecomment-215337185

> `MouseEvent.pageX/pageY` also might be influenced.
> https://github.com/jquery/jquery/blob/9f268caaf43629addb9a1a2001ab341839300b14/src/event.js#L435
> If native `event` don't have `pageX/Y`, these are calculated using `clientLeft/clientTop`.
> 
> If `html` element has `border-width:10px` like the example above, in a browser that doesn't support `event.pageX/Y` and correct `clientTop/clientLeft`, jQuery returns `10,10` as `pageX/Y`, when mouse is positioned at left-top-corner of `body`. In a browser that returns correct `clientTop/clientLeft`, jQuery returns `0,0` as `pageX/Y`.
> 
> I feel that `10,10` is correct result.
> 
> But I don't know recent browser that doesn't support `event.pageX/Y`.

Since Firefox returns `0` as `clientTop/clientLeft` of `html` element always, `MouseEvent.pageX/pageY` might be incorrect.
When native `event` object doesn't have `pageX/Y`, `jQuery.event.mouseHooks.filter` calculates these using `document.documentElement.clientLeft/clientTop` (i.e. `border-width` of `html` element).
(But I don't know recent browser that doesn't support `event.pageX/Y`.)

Represent:
https://jsfiddle.net/rent9q5g/
This simulates a browser that doesn't support `event.pageX/Y`.

Chrome:
![m-ch](https://cloud.githubusercontent.com/assets/4763469/14910319/2a930df4-0e27-11e6-8f38-6ac58f389365.png)

IE:
![m-ie](https://cloud.githubusercontent.com/assets/4763469/14910321/33f3deb4-0e27-11e6-9c9a-2c4bf728a408.png)

Firefox:
![m-ff](https://cloud.githubusercontent.com/assets/4763469/14910328/3d939658-0e27-11e6-8e4a-8878a5864a9a.png)

incorrect result in Firefox by its bug, but I think `pageX: 10 pageY: 10` is correct result. That is, `jQuery.event.mouseHooks.filter` should not subtract `clientTop/clientLeft`.

**Comment by dmethvin** [comment]
It's possible we don't need that code at all in 3.x (maybe even 2.x) depending on where pageX/Y are provided. If https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageX is correct it seems we should be covered even for 2.x. Removing it would be better than fixing it!

**Comment by gibson042** [comment]
> Removing it would be better than fixing it!

Agreed.

**Comment by dmethvin** [comment]
I think we should remove the `pageX/Y` fill in 3.0, it seems to have full browser support. Let's discuss on Monday, I won't submit a PR now because it will conflict with @jbedard 's PR and we might as well create one on top of that.

**Comment by dmethvin** [comment]
Hey @anseki I just wanted to confirm that this problem does not exist in any of the `event.pageX` values that the browser calculates, correct? Once we remove our calculation as proposed in gh-3106 there should be no problem. (Unless the browser doesn't support `event.pageX`!)

**Comment by anseki** [comment]
I think that `pageX/pageY` of native event object are correct.
I updated the code above in JSFiddle.
https://jsfiddle.net/rent9q5g/2/
At least, `Native pageX/pageY` seem correct in current Firefox, Chrome and IE.

**Comment by dmethvin** [comment]
Awesome, thanks for the confirmation!
