### ISSUE TITLE
Ajax- status 200, without data, in response is NOT considered as request success

### ISSUE THREAD

**Issue by chiragmongia** [jquery/jquery#3098]
**Currently**,
In case of an Ajax request, if the server responds with status code 200 and do not send any data in response, it is considered as an ERROR.

**Expectation**
It should be considered as SUCCESS and trigger `done` handler of the ajax object.

**Comment by dmethvin** [comment]
What data type do you specify? The request is only a SUCCESS if the data can be converted. Please do answer the questions in the issue template in the future.

**Comment by chiragmongia** [comment]
@dmethvin I didn't specify a dataType. So, it should have picked the default value.
Also, there is no response data.
My rails server response looks like this- `head :ok`

So, here, I am sending an ajax request to save data and I'm not expecting anything in response except the headers

**Comment by dmethvin** [comment]
Your headers are probably specifying that the response is JSON or some other data type that needs to be parsed, and the parsing fails. But this is just a guess. Triage it on our forum or StackOverflow, if you actually determine it is a bug you can open a new ticket and fill in the information in the issue template.
