### ISSUE TITLE
Custom build with just ajax functionality

### ISSUE THREAD

**Issue by nodesocket** [jquery/jquery#3099]
I'd like to create a custom build using only the following modules with version `2.x` _(I need the fullest Internet Explorer support)._

    core
    selector
    ajax
    ajax/xhr
    ajax/script
    ajax/jsonp

Can anybody provide a working example of how to do this?

**Comment by timmywil** [comment]
Hi there. Firstly, this is not the right place for questions. The best place is in the [forums](http://forum.jquery.com) or in the #jquery irc channel. Second, version 2.x does not support IE<9. You'll need a custom build created with the latest 1.x. Third, custom build instructions are documented in the [README](https://github.com/jquery/jquery/blob/07f1502f4769dd7aa41e79730da25eecb5595af3/README.md#how-to-build-your-own-jquery).
