### ISSUE TITLE
Adding an element with name 'nodeType' using append() prevents subsequent elements being added to the parent

### ISSUE THREAD

**Issue by alistairjevans** [jquery/jquery#3101]
If I append an input element to a form using the append method, where the name of that new child element is "nodeType" (i.e. the same as the HTML element property indicating type), then no elements can be subsequently added to that parent. Subsequent append methods don't raise an error, it just never gets added to the DOM.

I have created a simple JsFiddle that demonstrates the issue: https://jsfiddle.net/vj952g91/3/

I have also created a version of the test case where the same elements are created, but using native JS methods rather than jQuery: https://jsfiddle.net/8yzq4zom/1/; the issue does not occur when using native code.

I have tried this using jQuery 1.12.2, 2.2.3 and 3.0.0 alpha.

I have reproduced this issue in Chrome (my version is 49.0.2623.112) and Firefox (41.0.1). The issue does _not_ occur in IE 11.

**Comment by markelog** [comment]
It never worked and never will be, sorry, naming node properties that already exist is never a good idea - https://bugs.jquery.com/ticket/11125#comment:7

**Comment by alistairjevans** [comment]
Okay, but I'm confused (most likely my fault) as to why setting an existing property ("name") equal to the name of another property on the node is the same as trying to re-use an existing property of the node for another purpose (i.e. action, to trigger)? 

Do some browsers turn the name attribute into an actual node property or something?

**Comment by markelog** [comment]
Oh, i have explained this so many times before on some many different occasions :).

Most recent on is here - https://github.com/jquery/jquery/issues/2883#issuecomment-176838065, although better to read the spec itself - https://html.spec.whatwg.org/#reflecting-content-attributes-in-idl-attributes

**Comment by alistairjevans** [comment]
Ok, thank you for the link. The basic rule then is never use a known IDL property name for the actual content attribute "name" of an element when constructing HTML.  Understood (sort of).

Cheers

**Comment by dmethvin** [comment]
See also https://kangax.github.io/domlint/ which explains and tries to detect the problems.
