### ISSUE TITLE
Jquery alpha1 is versioned as beta1

### ISSUE THREAD

**Issue by bdm4** [jquery/jquery#3109]
This is small but when I installed jquery via npm with "npm install jquery@3.0.0-alpha1"
The resulting version is "3.0.0-beta1"

jquery.js - line 77 is just mislabeled to be ...beta1...

**Comment by mgol** [comment]
Are you sure you installed it correctly? I see correct results.
```
$ npm install jquery@3.0.0-alpha1
$ cat node_modules/jquery/dist/jquery.js | grep 3.0.0
 * jQuery JavaScript Library v3.0.0-alpha1
	version = "3.0.0-alpha1",
```

**Comment by bdm4** [comment]
Ignore me. Tomorrow is Friday hooray.
