### ISSUE TITLE
[2.2.x] Regression with focusin handling on Firefox

### ISSUE THREAD

**Issue by avdv** [jquery/jquery#3111]
** Description**

The cursor is missing or misplaced in an input box with an focusin handler attached when returning `false` from the handler.

Affected is Firefox (I'm using 46.1).

See emberjs/ember.js#13112

** Link to test case **

Courtesy of @Serabe (https://github.com/emberjs/ember.js/issues/13112#issuecomment-217957434):

http://codepen.io/Serabe/pen/PNVXdd?editors=0010

This codepen uses jQuery 2.2.2 but it also breaks with 2.2.3. It works alright with jQuery 2.1.4

**Comment by mgol** [comment]
Confirmed.

**Comment by mgol** [comment]
Confirmed. Thanks for the report!

**Comment by mgol** [comment]
The test case using the dev version of jQuery 2.x: http://codepen.io/mgol/pen/JXzjJV?editors=0010

**Comment by mgol** [comment]
The first bad commit is 6df669f0fb87cd9975a18bf6bbe3c3548afa4fee (cc @markelog).

**Comment by mgol** [comment]
jQuery 1.12.x is fine: http://codepen.io/mgol/pen/ONqPyO?editors=0010

Perhaps we need to backport the workaround from 37c3d087824b51e742126252ced8be592858102d? We should test that as well.

**Comment by mgol** [comment]
(by `2.x-only` I mean it's broken on `master` as well: http://codepen.io/mgol/pen/zqbxrO?editors=0010)

**Comment by markelog** [comment]
Will check it out.

Sounds like a blocker?

**Comment by mgol** [comment]
Yeah, we should get that in 2.2.4 IMO.

**Comment by mgol** [comment]
@markelog Please mention gh-3111 in the PR description so that it's easy to go to the issue.

**Comment by markelog** [comment]
Currently, this fix landed only in master branch i.e. 3.x, not sure if this constitutes new 1.x/2.x release.

Marking it for 3.0 only for now

**Comment by timmywil** [comment]
While this should also be landed in master, this fix is mainly for the 2.x branch.

**Comment by markelog** [comment]
Landed in 2.x

**Comment by markelog** [comment]
I think `2.x-only` is confusing here though

**Comment by timmywil** [comment]
It's just to denote that it does not apply to 1.x. Maybe there's a better name for that, but soon we won't need the label at all.
