### ISSUE TITLE
Plugin for Age Verification Problems?

### ISSUE THREAD

**Issue by iaholyk** [jquery/jquery#3114]
The age verification plugin has the following problems.
When looking from a Mobile device the check box on your phones key board to finish and submit your age doesn't work
When you click the form fields to enter in an day or month of birth the actual form drop down below the screen so it is not accessible.

Here is what i mean, try to log in to my site www.nwweedfinder.com from a phone.

**Comment by dmethvin** [comment]
Hi! Can you help us understand how to improve our process? There was some text in the box that you just typed into. Did you read it? What would have helped direct you to the right place?

**Comment by iaholyk** [comment]
I read it, but it was kind of confusing because it had mark up on it.  I wasn't sure if that meant my comment had to have mark up to be seen.

**Comment by dmethvin** [comment]
Okay we'll need to work on that. The question you're asking doesn't have anything to do with this repo, it sounds like you need to find the owner of the age verification plugin and file an issue there. Or you could ask a question on StackOverflow.

**Comment by iaholyk** [comment]
Yea I had to remove it from my site completely because it doesn't work at all any more.  It was keeping people from logging on.  Every time you back out of your keyboard the age verification form drops until it is completely gone from view.
