### ISSUE TITLE
Bug: clone() not cloning textarea and select options in Firefox

### ISSUE THREAD

**Issue by baszero** [jquery/jquery#3115]
Although marked as CLOSED, it just doesn't work correctly in Firefox (v45).
Any comments on this?

**Comment by dmethvin** [comment]
Seems to be a well-known bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=230307

The reasons for not fixing it in jQuery are still valid, it's a lot of work for a rare case. I would comment on the ticket there to see whether it can be fixed. In the meantime it should be possible for you to copy the value over right?

**Comment by baszero** [comment]
It's just a hassle at the end. Is it only textarea and select or are there other situations where it doesn't work? I have chosen jQuery because I didn't want to deal with browser issues. At the end, jQuery is like javascript in the beginning, claiming that browsers should fix their problems... 

Seems there is no other way than making my own bugfix then.

**Comment by baszero** [comment]
But thanks for your quick answer! Highly appreciated!

**Comment by baszero** [comment]
Update: the Firefox guys say that they are waiting for a fix in jQuery: https://bugzilla.mozilla.org/show_bug.cgi?id=230307#c11

**Comment by mgol** [comment]
> Update: the Firefox guys say that they are waiting for a fix in jQuery: https://bugzilla.mozilla.org/show_bug.cgi?id=230307#c11

This is my comment and it doesn't say that at all, I just added the Firefox bug to the meta-bug collecting issues affecting jQuery.

**Comment by baszero** [comment]
Ok, but when I read "This issue gets reported to jQuery" I interpreted it as "jQuery has to fix it". However, I hope this gets fixed in jQuery as Firefox didn't make any progress on it since years... and jQuery wants to be the API for developers hiding all the browser specifics, no?

**Comment by miketaylr** [comment]
ps @baszero, 

> Why does it take to fix this so long? Reported in 2004 (yes, not 2014).... So please Firefox, fix this!!!!

These kinds of comments in bug trackers aren't constructive. Firefox is a large project with many thousands of open bugs. If you'd like to help contribute a patch to fix the issue, I'd be happy to help you get started. Send me an email to miket@mozilla.com, thanks.

**Comment by baszero** [comment]
Thanks, and agree, my comment was not constructive. I'd rather contribute to jQuery than Mozilla because I believe the fix belongs there.

**Comment by bzbarsky** [comment]
Note that per spec as currently written cloneNode() on a textarea is NOT supposed to copy the modified value.  Firefox and Safari are following the spec; Chrome and Edge are not.

See also spec issue at https://github.com/whatwg/html/issues/1233

**Comment by dmethvin** [comment]
That's even more of a reason to not change it. Since this ticket references all the appropriate external tickets and we don't plan on implementing a change that is counter to the spec, I'll close the ticket. If the spec agrees on a behavior and it makes sense to revisit, we can do so.
