### ISSUE TITLE
$.getJSON - 'Content-type' header missing - v1.9.1

### ISSUE THREAD

**Issue by DennisVM** [jquery/jquery#3119]
When trying to use '$.getJSON', it does not set the 'Content-Type' header (- e.g. ''Content-Type	application/json; charset=utf-8';').

At least when trying to invoke an ASP.NET ASMX/web service method, you receive a 500 error whereby the 'jqXHR.responseText' is set to 'Request format is unrecognized for URL unexpectedly ending in ...'; see also, related:  https://support.microsoft.com/en-us/kb/819267

I would expect that it if (in accordance with the not so clear HTTP RFC spec/s) it's not a bug of jQuery but a bug of Microsoft's ASP.NET, then ideally it would still be good to have the jQuery feature of also having the option of been able to pass a "settings" block instead, similar to the '$.get()' method:

    jQuery.get( [settings ] )

**Comment by dmethvin** [comment]
Hi @DennisVM, when you opened the issue there were some instructions. Were you able to see them?
