### ISSUE TITLE
http://code.jquery.com/jquery/ weirdness 

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#3120]
Not sure where to report about this, so posting here - 

On http://code.jquery.com/jquery/ page, there is two builds shown - 2.x/1.x git builds but no 3.x, not sure if 3.x is supposed to be here, but looks inconsistent.

Also those 2.x/1.x builds point to http://code.jquery.com/jquery-git1.js and http://code.jquery.com/jquery-git2.js which redirect to http://code.jquery.com/jquery-git2.js which is 3.x

**Comment by timmywil** [comment]
I think this should go [here](https://github.com/jquery/codeorigin.jquery.com).

**Comment by timmywil** [comment]
Added https://github.com/jquery/codeorigin.jquery.com/issues/27

**Comment by markelog** [comment]
thanks
