### ISSUE TITLE
Shim focusin/focusout in all browsers?

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#3123]
**Description**
If `focusout` & `blur` handlers are attached on one input and `focusin` & `focus` on the second one, the order of events fired by jQuery is:

1. `focusout`
2. `blur`
3. `focusin`
4. `focus`

The order mandated by [the spec](https://www.w3.org/TR/DOM-Level-3-Events/#h-events-focusevent-event-order) and followed by IE 11 is:

1. `focusout`
2. `focusin`
3. `blur`
4. `focus`

(The spec also mandates that focus is lost after `focusout` & before `blur` and gained after `focusin` but before `focus` event fires).

Chrome/Safari do the following:

1. `blur`
2. `focusout`
3. `focus`
4. `focusin`

Edge 13 does the following:

1. `focusout`
2. `blur`
3. `focus`
4. `focusin`

Firefox doesn't support those events yet but there's ongoing work in https://bugzilla.mozilla.org/show_bug.cgi?id=687787.

We're currently polyfilling this event everywhere except in IE. Since IE differs from our implementation and it's an obsolete browser it sounds bad to let it do its own thing different than what we have. Should we just shim everywhere?

**Link to test case**
https://jsfiddle.net/66znLhfw/2/

**Comment by markelog** [comment]
> Should we just shim everywhere?

i'm voting yes

**Comment by mgol** [comment]
Previous art with more links, including more comprehensive tests: https://gist.github.com/rodneyrehm/46e03d6e077257daa04c.

**Comment by mgol** [comment]
One problem (thx to @dmethvin) is that `focusin` & `focusout` in IE 11 fire synchronously and `focus` & `blur` asynchronously (contrary to the spec):
https://jsfiddle.net/66znLhfw/6/

This means if we shimmed `focusin` & `focusout` in IE, we'd change them from sync (as they should be) to async. :/

**Comment by dmethvin** [comment]
I'd rather have different event order than an async event.

**Comment by mgol** [comment]
In light of this information I tend to agree with @dmethvin. What a mess. :/

**Comment by cvrebert** [comment]
WPT: http://w3c-test.org/uievents/order-of-events/focus-events/focus-manual.html
(Currently lacks test for synchronicity)

**Comment by dmethvin** [comment]
Sad to think that even IE6 would get that test right, if it had `addEventListener`. :sob: 

Is there anything we can do here? If not we should close this ticket. Maybe Firefox can get everyone to agree on an order before doing their implementation. I kind of like the Edge order TBH.

**Comment by markelog** [comment]
> Is there anything we can do here? If not we should close this ticket.

I think we should at least put some comments in the source and document our sequence on api pages

**Comment by dmethvin** [comment]
How about if we documented that the order of these events is not well defined and code should not depend on it? If we document the actual order jQuery uses it seems like we are saying that order is supported and we would not be able to change it until a major version. Plus we can't make that order happen in IE without turning it all into async.

**Comment by mgol** [comment]
@dmethvin Sounds good. I'd just add that we do guarantee `blur` will happen before `focus` and `focusout` before `focusin` but that's the only contract we can promise.

**Comment by dmethvin** [comment]
Moved to https://github.com/jquery/api.jquery.com/issues/930

**Comment by markelog** [comment]
@dmethvin you are clever guy :)

**Comment by smaug----** [comment]
Could anyone from jQuery comment on https://github.com/w3c/uievents/issues/88 ?

**Comment by timmywil** [comment]
@smaug---- I've added it to the agenda for our next meeting. Though that doesn't prohibit anyone from commenting, I'm not sure what to recommend yet.

**Comment by timmywil** [comment]
If I had to comment now, I'd say that Blink changing order would not affect jQuery, since we have our own order (which also happens to be wrong, apparently). The async events in IE throw a wrench in this because we can't make them sync and guarantee behavior across browsers. Even if all the browses cooperated on order, we're still left with inconsistencies. In other words, I don't see changes made from https://github.com/w3c/uievents/issues/88 influencing much.

**Comment by mgol** [comment]
An update to my original post:

Edge 17 & newer now matches Chrome behavior. Firefox implemented that order as well. All dispatch the events in the following order:

1. `blur`
1. `focusout`
1. `focus`
1. `focusin`

IE 11 does what [the spec](https://www.w3.org/TR/uievents/#events-focusevent-event-order) mandates, i.e.:

1. `focusout`
1. `focusin`
1. `blur`
1. `focus`

The test case checking native behavior: https://jsfiddle.net/66znLhfw/15/
