### ISSUE TITLE
Bug: jQuery.data() read differs from .data() when using kebab-case and object-notation

### ISSUE THREAD

**Issue by fabsn182** [jquery/jquery#3124]
I am storing some data using the `$(element).data({})` syntax but after trying to overwrite and then read the same key, I get the initial set value:

`$(element).data({ 'in-view': true });`
`$(element).data('in-view', false);`

Now reading `data('in-view')` should return `false`, but in fact returns `true`

Using `jQuery.data($(element), 'in-view')` works fine!

Test case: https://jsfiddle.net/u0ersr5e/1/

**Comment by dmethvin** [comment]
This is fixed in jQuery 3.0 by dictating that everything is stored camelCase. https://jsfiddle.net/u0ersr5e/2/

https://jquery.com/upgrade-guide/3.0/#breaking-change-data-names-containing-dashes

**Comment by mgol** [comment]
Yup: https://jsfiddle.net/u0ersr5e/3/

The main issue: https://github.com/jquery/jquery/issues/2257
