### ISSUE TITLE
[new feature] jQuery less / sass src

### ISSUE THREAD

**Issue by ZiperRom1** [jquery/jquery#3131]
I didn't find issues tab in the jQueryUI github repository and I don't know where to post this so here it is.
Why not putting the less / sass src for theme generation in the github repository ? Using bower is great thing to get exactly what you need from js src files and users can then compile their own js using AMD module structure like requireJS in a project. But what if they also use a less / sass css build system ?
Including those src would allowed users to also compile their own less / sass and import the jQueryUI theme they want to => 1 css file for all and 1 js file for all.

**Comment by mgol** [comment]
The link to the jQuery UI bug tracker is mentioned in the [jQuery UI README](https://github.com/jquery/jquery-ui#jquery-ui---interactions-and-widgets-for-the-web). The address is https://bugs.jqueryui.com/.

jQuery UI doesn't use Sass or Less, though, its CSS is handwritten. You can see the source at https://github.com/jquery/jquery-ui/tree/master/themes/base.
