### ISSUE TITLE
Jquery.min File Use window.crypto Instead of Math.random

### ISSUE THREAD

**Issue by patrick5080** [jquery/jquery#3136]
Hello,
I have a request please. We are using HP Fortify for our code-base and Fortify reports security vulnerabilities in our jquery.min.js file because of using Math.random(). Is it possible to replace Math.random method with window.cyrpto.random method?

Thank you,
patrick

**Comment by Mr21** [comment]
If you want to have the same behaviour, it's really more complex than just `Math.random`.
I suppose that in your case you can overload the real Math function with something like :

``` javascript
Math.random = function() {
	var arr = new Uint32Array( 1 ),
		limit = Math.pow( 2, 32 );

	return function() {
		return crypto.getRandomValues( arr )[ 0 ] / limit;
	}
}();
```

**Comment by dmethvin** [comment]
@patrick5080 what is your tool trying to say? Is it warning against using `Math.random()` as a cryptography API? As to whether we could switch, the crypto API [isn't supported](http://caniuse.com/#feat=cryptography) by all of our browsers so if your tool is doing static analysis it would still find `Math.random()` in the file since it's got to be there as a fallback.

**Comment by timmywil** [comment]
Thanks for opening an issue. However, there's no need to use `crypto` as we are not trying to generate secure, random numbers. We only use `Math.random` to generate internal unique identifiers (for instance, in generating the property name to use when attaching data to an element). There is no security concern if this number accidentally collides with another. And while that theoretically could happen, it doesn't.

**Comment by patrick5080** [comment]
Thank you
 

    On Wednesday, June 1, 2016 2:26 PM, Timmy Willison <notifications@github.com> wrote:
 

 Thanks for opening an issue. However, there's no need to use crypto as we are not trying to generate secure, random numbers. We only use Math.random to generate internal unique identifiers (for instance, in generating the property name to use when attaching data to an element). There is no security concern if this number accidentally collides with another. And while that theoretically could happen, it doesn't.—
