### ISSUE TITLE
Bootstrap 3 unit test fail with SVG element

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#3137]
[This test](https://github.com/twbs/bootstrap/blob/f01f3e5f34c1acdd802cc61ea9aae9f9b14169c3/js/tests/unit/tooltip.js#L1042-1079) from Bootstrap 3 (the current version) fails on Chrome and Safari but passes on IE, Edge, and Firefox. Our [`getClientRects` call inside `.offset`](https://github.com/jquery/jquery/blob/73bf35ecf31867d7ed4662374121efa310cf9f8d/src/offset.js#L96-101) returns a length of zero on those browsers but `getBoundingClientRect` seems to work fine. 

It's a relatively edgy case and this unit test isn't present in Bootstrap 4, but given the way it fails it isn't something that can be easily worked around via Migrate for example. I'm also worried that other code may be expecting to get offsets on SVG elements, even though we've never officially supported it. Would it work to check whether the current element is SVG perhaps and avoid the check for that case?

**Comment by mgol** [comment]
If we avoid the check we'll make IE 11 throw on detached SVGs, won't we?

**Comment by dmethvin** [comment]
### `¯\_(ツ)_/¯`

I forget, why did this change from a `jQuery.contains` test?

**Comment by mgol** [comment]
Probably for performance reasons? If we were to change that back we'd have to change [css.js#L12](https://github.com/jquery/jquery/blob/73bf35ecf31867d7ed4662374121efa310cf9f8d/src/css.js#L127-L129) as well.

P.S. Please don't link to `master`, those links will become incorrect in the future. :)

**Comment by dmethvin** [comment]
Thanks for pointing it out, I had fixed their ref but not ours!

**Comment by timmywil** [comment]
In my experience, offset has never been that reliable with SVG elements. I used it for a while, and kept running into cases where it wasn't enough. I think we'll leave this the way it is. If we get enough complaints, we can revisit.

**Comment by yorrd** [comment]
complaint! 
I'm currently working with a lot of SVGs, this would make my life easier o.o

**Comment by cvrebert** [comment]
> and this unit test isn't present in Bootstrap 4

That's probably an oversight on our part. We haven't been great about syncing v3 fixes into v4.

**Comment by MiskaBalu** [comment]
Complaint!
Sorry, why was this entry closed?. My company is now forced to go back to a jQuery version before 3.0.
That the "offset has never been that reliable with SVG elements" is really a very weak argument for closing this entry. I would appreciate if the old behavior could be restored.

**Comment by mgol** [comment]
@MiskaBalu jQuery doesn't support most operations on SVGs with the exception of class manipulation, it's clearly documented on the [Contribute Won't Fix page](https://contribute.jquery.org/wont-fix/#svg-vml-or-namespaced-elements-bugs). Relying on that is similar to relying on private, undocumented APIs that may change any time. Since we don't support it, any change in other code might break something. Improving the logic or performance for regular HTML DOM is more important for us than trying to fix something we don't really support.

**Comment by MiskaBalu** [comment]
**@mgol** OK, many thanks for your reply!
