### ISSUE TITLE
`jQuery.Event( src )` cannot require `src.target`

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#3139]
If you construct a `jQuery.Event( src )` using something that has `src.type`, the 3.0 code will die if there is not an `src.target` property. jQuery Mobile uses a pattern where they construct an object and then set properties like `target` afterwards, which was allowed by 1.x/2.x, so we need to fix this as a regression.

**Comment by arschmitz** [comment]
@dmethvin ah thanks yeah i was having trouble figuring out exactly where this error was coming from
