### ISSUE TITLE
Add support for JSPM sfx bundles.

### ISSUE THREAD

**Issue by tcorral** [jquery/jquery#3145]
Feature Request:
**- Does it require access to jQuery internals?**
  - Yes it does. The problem seems to be in the way jQuery is exported.

**- Can jQuery itself benefit from the feature?**
  - Yes it does. jQuery can be used in more development and production environments.

**- Is the feature related to DOM operations?**
  - No.

**- Is the need already served by a plugin?**
  - No.

**- Does it change an existing API?**
  - No.

**- Does it support best practice?**
  - Yes.

### Description ###
In my project to create our widget bundles we are using:
- [jspm](http://jspm.io/docs/getting-started.html) - [jspm-cli](https://github.com/jspm/jspm-cli)

As they are widgets we want our code as isolated as possible, so we use jspm sfx bundles that you can create using:
```js
jspm bundle-sfx scripts/main dist/main.js
```

The problem is that if this packages doesn't add a ```define``` or  ```require``` to the global and when jQuery wants to export itself it decides that needs to be on the global.

Overwriting the jQuery we have in the page we have a lot of issues.

### Link to test case ###

https://jsfiddle.net/aptm7qxy/1/

If we use Webpack Dev Server it doesn't happens:

https://jsfiddle.net/2xua7b98/

**Comment by mgol** [comment]
I'm a little confused; jQuery exports itself via AMD/CommonJS/global depending on the detected environment; what changes would you like us to make?

**Comment by tcorral** [comment]
I have created an issue also in jspm-cli https://github.com/jspm/jspm-cli/issues/1890

**Comment by tcorral** [comment]
I have checked that and it only happens with jQuery's version 2.x.

It doesn't happens with version 1.x or 3.x

**Comment by tcorral** [comment]
After discussing that with jspm team, that problem can be solved adding the following snippet of code to the jspm/SystemJS config.
```js
meta: {
    'npm:jquery@2.2.0/dist/jquery.js': {
      format: 'cjs'
    }
  }
```

Thanks, for your time.
