### ISSUE TITLE
Sets of generic objects support in 3.x

### ISSUE THREAD

**Issue by marcandre** [jquery/jquery#3147]
It appears that the following is no longer supported in jQuery 3.0.0rc1:

    foo = {hello: 'world'}
    $([foo]).not([])  // => Returns $() and not $([foo])

I have no problem with this (assuming it is on purpose), but I'd recommend including a note in the release notes, as many people are relying on this (or did I miss it)?

In particular, see these 3 StackOverflow answers [here](http://stackoverflow.com/a/7726509/8279), [here](http://stackoverflow.com/a/26398304/8279) and [here](http://stackoverflow.com/a/15385871/8279)...

**Comment by dmethvin** [comment]
Plain objects were always documented as having limited support, and we have discussed dropping support completely. 

> At present, the only operations supported on plain JavaScript objects wrapped in jQuery are: .data(),.prop(),.on(), .off(), .trigger() and .triggerHandler(). -- http://api.jquery.com/jquery/

Other usage is far outside the purpose of jQuery as a DOM library. 

> but I'd recommend including a note in the release notes, as many people are relying on this 

We can add a note to the upgrade guide. When you say "many people" are there examples other than some StackOverflow answers? For example does some popular library use this?

**Comment by marcandre** [comment]
> we have discussed dropping support completely.

I understand that completely.

> are there examples other than some StackOverflow answers

Yeah, I'm ashamed to say I used it in Parsley. No idea about others, but an accepted answer with about 300 upvotes is not negligible on SO. No comment that this is undocumented anywhere, etc., oh wait, the 11th answer pointed out this is undocumented (I just upvoted it :smile:), so I think that a lot of people mistakenly think that it's ok to use that.

If not too difficult to do, maybe go to the trouble to output a deprecation warning (either in 2.x, or in 3.x and supporting it for another version)?

**Comment by dmethvin** [comment]
I don't think we'd add code to generate a deprecation warning inside jQuery itself. It's something we could do in jQuery Migrate but we haven't yet formally deprecated the use of plain objects. The way it was being used here was just a flat out misuse of the API, we'd need to add checks to all methods other than the ones listed in the docs to ensure that they were only being passed DOM elements or a `document` or `window`. That's a lot of checks!
