### ISSUE TITLE
Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

### ISSUE THREAD

**Issue by sathishkumar1911** [jquery/jquery#3155]
Getting below exception when running grunt test with PhantomJS

PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
  Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3
  at c:/dev/code/athena/public/bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.js:15

**Comment by kokspflanze** [comment]
bootstrap atm not support jquery 3
https://github.com/twbs/bootstrap/issues/16834
