### ISSUE TITLE
jquery 3.0.0 breaks jqueryui dialog with error jf.getClientRects is not a function 

### ISSUE THREAD

**Issue by JevW** [jquery/jquery#3157]
I have tried the latest jQuery 3.0.0 with jQuery UI. 
If i open a dialog i get the error "TypeError: f.getClientRects is not a function".

**Comment by JevW** [comment]
I am at work at the moment and it is not possible to create a test case in jsfiddle because of our firewall.
you can do downloading jqueryui and replace the jquery script with the newest version.

**Comment by iweindesmedt** [comment]
+1 same with ui-menu

**Comment by dmethvin** [comment]
As the [blog post](http://blog.jquery.com/2016/06/09/jquery-3-0-final-released/) mentioned, new compatible versions of UI and Mobile should be coming out soon. If you use jQuery UI with the jQuery Migrate plugin it should work fine.

**Comment by jibboo** [comment]
I am experiencing the same issue with jquery-3.0.0.min.js and jquery-ui-1.11.4.min.js ... hope they fix this soon .... guess I'll revert to jquery 2.11 until this is rectified.

**Comment by CaptainCannabis** [comment]
Same to me - jquery 3.0.0 | jquery-ui v1.10.3
Happens while opening up an dialog in an electron.js app.

**Comment by dmethvin** [comment]
And you've included jQuery Migrate 3.0.0 in your app?

**Comment by CaptainCannabis** [comment]
https://code.jquery.com/jquery-migrate-3.0.0.min.js fixed it - i didn't know that i need it in electron too :) Thanks!

**Comment by jibboo** [comment]
I didn't add jquery-migrate ... I have too many external files being added as it is ... just rolled back to jquery.2x until they get this fixed.

**Comment by vanderlee** [comment]
How are you supposed to actually use `.position()` in 3.0.0, because if I follow documentation, it fails.

**Comment by tyn520215** [comment]
thanks

**Comment by suny0508** [comment]
composer.json require  add  "bower-asset/jquery-ui": "1.12.1"
