### ISSUE TITLE
jquery-3.0.0, $(window).load() not work

### ISSUE THREAD

**Issue by tianyuanzhonglu** [jquery/jquery#3162]
latest firefox and chrome:

callstack:
TypeError: a.indexOf is not a function                   jquery.min.js:4:18684
r.fn.load()   jquery.min.js:4
<anonymous>  index.html:39

demo:
```
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Demo</title>

    <style>
a.test {
    font-weight: bold;
}
</style>
</head>
<body>

    <a href="http://jquery.com/">jQuery</a>
    <script src="jquery.min.js"></script>
    <script>
 
    // Your code goes here.

    $(document).ready(function() {
        console.log( "document loaded" );
    });
 
    $(window).load(function() {
        console.log( "window loaded" );
    });
    </script>
</body>
</html>
```

jquery-1.12.4 work correctly.

**Comment by dmethvin** [comment]
https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed

Please use jQuery Migrate 3.0 when upgrading your code, it would have told you about this if you prefer to read console messages instead of the upgrade guide.

**Comment by hcgernhardtiii** [comment]
The `.load()` method is still described as valid in the jQuery docs, though:  [https://learn.jquery.com/using-jquery-core/document-ready]  In what repo would I open a ticket for that?

**Comment by mgol** [comment]
@hcgernhardtiii Every site has a separate GitHub repo, just look for its name under the `jquery` GitHub account. For example, learn.jquery.com is at https://github.com/jquery/learn.jquery.com.

**Comment by hcgernhardtiii** [comment]
Thanks!

**Comment by nabeeltahir785** [comment]
After jQuery 1.8 released .load function deprecated.
We use jQuery .load() function previous version of jQuery 1.8

**Comment by nabeeltahir785** [comment]
http://api.jquery.com/category/deprecated/
