### ISSUE TITLE
Locking issues to comments is a bad practice

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery#3163]
For example at https://github.com/jquery/jquery/issues/3160#issuecomment-225445829

The last comment is:
> I don't think this discussion is going to resolve anything so I'll lock the thread. I've given the reasons why we don't provide detailed API violations and you disagree which is your right, but it won't change our [approach](https://github.com/jquery/jquery/wiki/API-design-guidelines).

 Locking the issue to comments was totally unnecessary or at the very least premature. The administrator here could have just made the same comment without locking the issue, so I could have asked him what part exactly of the API guidelines he linked to is supposed to back his point.

In general, locking an issue to comments is a very stupid thing to do. It should be a last resort in extreme cases.

**Comment by dmethvin** [comment]
Please review your comments and the use of things like "For god's f***ing sake", "stupid", "I thought it was obvious", "I can't believe", "the library is just unusable".  Those are *not* helping a productive discussion and I think the team deserves to be addressed with a little less of a negative tone.

Perhaps you do not think your comments were insulting but they appeared so to me. I tried to respond and explain why things work they way they do. However, I do not want to continue that discussion here, nor do I want to have your opinion on whether my reaction to your continuing negative tone was too harsh.
