### ISSUE TITLE
Document Safari Mobile support

### ISSUE THREAD

**Issue by HA-LO** [jquery/jquery#3164]
Now that jQuery 3 is out, I looked at the [browser support page](http://jquery.com/browser-support/) and saw that only the _Current_ and _Current - 1_ versions of Safari are supported (currently those should be 9.1.1 and 9.1 respectively).
Anyway, the Mobile section also mentions support for iOS: 7+. If I'm not mistaken, the first iOS 7 release came with Safari Mobile 6.1 preinstalled in late 2013.
Does this mean that Safari Mobile 6.1+ is actively supported by jQuery? Or does it mean that iOS 7 is only supported when Safari Mobile is updated to the almost latest version?
I'm sorry if this sounds like a silly feature request. I really wished those facts were better addressed by the documentation when reporting browsers versions and OS versions in the same list.

**Comment by timmywil** [comment]
Thanks for opening an issue. However, issues with jquery.com should be posted at https://github.com/jquery/jquery.com/issues.
