### ISSUE TITLE
Version 3.0 on nuget.org

### ISSUE THREAD

**Issue by cezarypiatek** [jquery/jquery#3166]
Hi 
Are you going to release jquery 3.0 on nuget.org? The newest version on nuget is still 2.2.3.
I would like to upgrade jquery in my project but I need to do that through nuget.
Thank for your help.

**Comment by mgol** [comment]
We only maintain the npm & bower jquery packages. For other package
managers you need to ask their maintainers.

-- 
Michał Gołębiowski
