### ISSUE TITLE
Offset: report offset for zero size elements

### ISSUE THREAD

**Issue by poppinlp** [jquery/jquery#3167]
### Description

In your document, i find:

> Note: jQuery does not support getting the offset coordinates of hidden elements or accounting for borders, margins, or padding set on the body element.

And in your code, it's:

``` js
// Make sure element is not hidden (display: none)
if ( rect.width || rect.height ) {
    ...
}
```

So how about element shown but with 0 width and height? Seems it's belong to hidden element in your code and get wrong offset value.
Is that a feature or issue? Since there may be some chance i need to know a element's offset which is shown but has no size.
### Link to test case

http://codepen.io/poppinlp/pen/gMMaEY

In this test case you will see element with no size get wrong offset.

**Comment by gibson042** [comment]
I believe we should report accurate offsets of visible but size zero elements.

**Comment by poppinlp** [comment]
I have open a PR for this issue.
Is that fix OK?
I haven't check `visibility` since it will get correct bounding rect.
