### ISSUE TITLE
Fail callbacks receive wrong argument if deferreds are already rejected when passed to $.when

### ISSUE THREAD

**Issue by hashchange** [jquery/jquery#3177]
Suppose a number of deferreds are passed to `$.when`, and these deferreds are, or will be, rejected. If a fail callback is added to `$.when`, it should receive the argument which had been passed to the first failed deferred.

That's the behaviour in jQuery 2, and that's how it works in jQuery 3 as well, with one exception: 

    var dfd1 = $.Deferred(),
        dfd2 = $.Deferred();

    // $.when is set up before the deferreds are rejected: 
    // works as expected
    $.when( dfd1, dfd2 ).fail( function() {
      console.log(arguments);
    } );

    dfd1.reject( "argument of failed deferred #1" );
    dfd2.reject( "argument of failed deferred #2" );

    // $.when is set up after the deferreds are rejected: 
    // wrong arg passed to callback (in jQuery 3)
    $.when( dfd1, dfd2 ).fail( function() {
      console.log(arguments);
    } );

In jQuery 3, the argument of the _last_ failing deferred is passed to the callback if `$.when` receives the deferreds by the time they are already rejected.

For a working example, including a comparison of jQuery 2 and 3, see http://jsbin.com/wuhesi/4/edit?html,js,console

**Comment by gibson042** [comment]
This is a behavior difference, but we never promised to consider the arguments in any particular order, just to "[reject the master Deferred as soon as one of the [input] Deferreds is rejected](http://api.jquery.com/jQuery.when/)". I'm personally disinclined to start enforcing a strict sequence, but would be willing to entertain arguments if someone has a compelling use case.

**Comment by dmethvin** [comment]
Note that in an asynchronous case, you can't depend on any particular Deferred arg rejecting in a multiple-rejection scenario. This example assumes things about the order that you probably don't want to assume. It's possible to determine whether the first Deferred is already rejected before calling the `$.when` so this behavior change doesn't prevent determining that if you need it. 

The question is whether it's common enough that we need to add a note to the upgrade guide. I think the documentation is already clear that it's not making guarantees.
