### ISSUE TITLE
jQuery.Deferred.exceptionHook breaks sourceMaps

### ISSUE THREAD

**Issue by pyalot** [jquery/jquery#3179]
### Description

Traceback reformatting breaks source-maps, it is unreadable compared to browser built in tracebacks, and it cannot be folded closed like browser built in tracebacks. Tracebacks are an essential development tool. Breaking traceback is not an acceptable way to write libraries.

Closing tickets pointing out that jQuery breaks tracebacks, does not fix tracebacks.

**Comment by dmethvin** [comment]
We still need a test case, preferably on jsbin.com or jsfiddle.net, that demonstrates the problem you are reporting. Your prior ticket was closed because it violated our code of conduct, not because of any technical merits.

**Comment by pyalot** [comment]
The test case is using tracebacks and source-maps. It seemed fairly obvious to me that people do that all the time sufficiently enough that no further explanation is required. Apparently I'm wrong, so there:

* Live test case: http://codeflow.org/issues/jQuery/tracebacks/
*  Archive of the test case attached [tracebacks.zip](https://github.com/jquery/jquery/files/318898/tracebacks.zip)

Screenshot with overall comparison:

![overall](https://cloud.githubusercontent.com/assets/592826/16125280/49e3cb3e-33f3-11e6-8beb-89e396d35262.png)

Functional examination of browser built in traceback.

![ua-traceback](https://cloud.githubusercontent.com/assets/592826/16126400/42964c80-33f8-11e6-870b-0d662cd2cd2c.png)

Functional failing of jQuery traceback

![jquery-traceback](https://cloud.githubusercontent.com/assets/592826/16126321/df1be0d4-33f7-11e6-8561-4fe40fd696df.png)

**Comment by dmethvin** [comment]
That's pretty much what we needed, thanks. Adding this line right below the jQuery script tag:
```js
<script>jQuery.Deferred.exceptionHook = function(e){ throw e; };</script>
```
Gives this result
![capture](https://cloud.githubusercontent.com/assets/157858/16129662/9deeaa16-33d3-11e6-80d8-501e7afb4864.PNG)

Of course this breaks Promise/A+ compatibility but I understand that it can be really handy for debugging, especially for all that legacy Coffeescript. If you threw a custom error subclass rather than `Error` you could narrow this down by [adding the subclass to the regex in the original](https://github.com/jquery/jquery/blob/58c6ca9822afa42d3b40cca8edb0abe90a2bcb34/src/deferred/exceptionHook.js#L10) but I'll leave that as an exercise.

**Comment by pyalot** [comment]
There's lots of trans/compilers that make use of source maps besides coffeescript, such as Dart, Typescript, Emscripten, Google closure compiler, etc. There's also lots of tools that concat/uglify/beautify/compress/etc. JS that use source-maps, the tools that compile jQuery itself among them.

Besides missing source-map support is but one of the many failings of the broken traceback that jQuery causes.

**Comment by dmethvin** [comment]
Can you let me know if this fixes your issue *in situ*? If so I'll close this ticket and we can look at some wording for the upgrade guide.

**Comment by pyalot** [comment]
It's pretty obvious this is an issue, that's not fixed. Breaking tracebacks and source-maps as an out of the box behavior not acceptable for any library, let alone one as widely used as yours.

**Comment by dmethvin** [comment]
I'm not sure why you are saying that is not fixed. Adding that one line gives a traceback that is very close to the one you had before. If we shipped it with that one line would you consider it fixed for your use case?

**Comment by pyalot** [comment]
I would consider it acceptable if jQuery was shipped with that fix.

**Comment by scottgonzalez** [comment]
@pyalot It has already been clearly stated that making such a change inside jQuery is not compatible with standards. We will not fight against the standards just because you're being pushy. Please refrain from restating your same opinion over and over as it is not helpful.

Please acknowledge whether that one line of user code that @dmethvin provided solves your problem of tracing the error through code that uses source maps.

**Comment by pyalot** [comment]
It does not solve the problem that jQuery breaks tracebacks and source-maps. I refuse to acknowledge that this would be any kind of "solution". If you can't ship that with your library, you will have to find other ways to fix the issue, including talking to the "standards body" in question, and talking to browser vendors to provide you the necessary abilities to fix it.

I advise you not to close this ticket again, it is not fixed, and you'd only prove my point that you don't care about getting it right.

**Comment by timmywil** [comment]
I think we all agree that respecting sourcemaps in the traceback is ideal. The problem here is that the solution is not compatible with the spec to which we must be compliant. If we have no suitable solution, we have to close the ticket because there's nothing more we can do. That said, Dave maintains a plugin that helps with debugging jQuery Deferreds (which is used in `jQuery.fn.ready`). If he knows that the solution he suggested works for you, he may be able to use that in the plugin. You could then use the plugin when debugging and we both follow standards *and* provide you with the best possible workaround.

Or, you can overwrite the default `console.warn` and throw instead in your own code with one line...

```js
jQuery.Deferred.exceptionHook = function(error) { throw error };
```

http://jsbin.com/minegi/1/edit?js,output

If you think of a solution that is compatible with Promises/A+, please comment here and we can reopen the ticket.

**Comment by scottgonzalez** [comment]
The thing is that the two cases you provided are not equivalent. Adding an event listener for the `DOMContentLoaded` is inherently different from adding a callback for the fulfillment of a promise. If you really want `DOMContentLoaded`, then you can still use jQuery to listen to that event. But if you want to extra sugar of a promise that will still invoke its callbacks even if they're added after the DOM is ready, then you're going to get the standard Promise behavior.

**Comment by pyalot** [comment]
There are clear avenues of investigation open to you such as talking to the standards committee that specifies promises, and talking to browser vendors about APIs that help you to fix this issue. You closed the ticket nevertheless.

Closing this ticket is a mistake that proves my point about a lack of commitment  to get things right. It's to the detriment of everybody who writes JS for this lackluster attitude to persevere. Setting an example in mediocrity to follow for many others. Hurting the ecosystems foundations upon which JS'es success is built. I cannot subscribe nor condone such a process and I find it abhorrent and repulsive.

**Comment by timmywil** [comment]
@pyalot We actually fought hard on this issue, but the battle is over. We lost. All we can do now is follow the spec because despite your fervor, you are in the minority.

**Comment by pyalot** [comment]
Then talk to browser vendors, as I've mentioned, multiple times, for the introduction of the necessary APIs that lets you fix tracebacks.

**Comment by mgol** [comment]
I reported it to Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=622227. Can we escalate it somehow? @paulirish?

**Comment by pyalot** [comment]
I'm talking to Kenneth Russel about this issue and a more fundamental solution. I have done some tests around in which circumstances Chrome does do the source-map translation (and URL shortening), but the prepending of jQuery's own error string to the front of the traceback breaks Chrome traceback parser. In any case, other browsers don't implement that, and it's still not a nice error display.

**Comment by dmethvin** [comment]
> the prepending of jQuery's own error string to the front of the traceback breaks Chrome traceback parser.

Can you propose a change that will make it better? We could do two separate statements if that helps.

**Comment by pyalot** [comment]
> Can you propose a change that will make it better?

Yes, don't modify the string you get from error.stack in any way. Any modification to it will break Chromes traceback parser.

I think it's futile to guess at what the error parser of chrome does, because its rules aren't standardized, and in any case, other browsers don't do it. And the error display isn't user friendly, because it's not styled like a normal error, and it can't be collapsed.

**Comment by dmethvin** [comment]
You can [see the code](https://github.com/jquery/jquery/blob/25d8ccd1112d75394b91071ff7eba13283aaf898/src/deferred/exceptionHook.js), it's not modifying error.stack. Rethrowing the error gets Chrome to show the stack formatted, but throwing at that point violates Promise/A+ so we can't do that as the  normal action.

**Comment by pyalot** [comment]
This is the bit that breaks chromes traceback parser:

> "jQuery.Deferred exception: " +

**Comment by mgol** [comment]
> This is the bit that breaks chromes traceback parser:

This is adding to `error.message`, not `error.stack`. At the issue https://bugs.chromium.org/p/chromium/issues/detail?id=622227#c3 I got a response that it's enough to `console.warn` the error and the stack will be available with properly applied source maps. @dmethvin: did you try it?

**Comment by pyalot** [comment]
Chromes generates its own error string (error.stack) and when you pass that to console.error/warn/log it re-parses its own error (and applies the appropriate source-map translation). This is undocumented behavior that was introduced in response to a ticket I wrote about that. The parsing chickens out if the format does not exactly conform to chromes undocumented error.stack format.

It's inappropriate to send errors to console.error/warn/log because that produces a bad error display that provides a worse UX (even if it works as expected), than the built-in error display (see screenshots).

It's also inappropriate to receive errors in an unstructured, undocumented format that varies from browser to browser.

It's inappropriate for browsers to re-parse their own errors they've just produced themselves, for exactly the above reasons.

The proper response to this whole thing would be to:

1. Introduce a standard stack format
2. Provide that standard stack format (lazily) on an error if asked to do so (like error.traceback getter), that does whatever the browser finds necessary to obtain that structured format.
3. Provide a console API to accept a standard stack format, such as console.traceback, which formats the standard stack traceback according to how the browser usually formats errors.

Javascript is among the only popular languages that does not have any kind of structured traceback handling. The introduction of error.stack was poorly conceived, the failure to standardize it was ill advised, the integration of promises into browsers was rushed and ill advised in face of a complete lack of proper error tooling, all these mistakes should not be compounded with the mistake of not fixing it now.

**Comment by mgol** [comment]
Let's revisit this for 4.0.0. PR: #5192.
