### ISSUE TITLE
Setting the selected option using prop() vs attr() in IE11

### ISSUE THREAD

**Issue by Lukapt** [jquery/jquery#3180]
Hi all,

I'm having a problem selecting options and reading when using both prop() and attr() methods. I reduced the problem to what could be seen in the following fiddler:
https://jsfiddle.net/kz3nskf6/1/

Basically after setting the property of all options to false I can't set a selected property using $.attr() method and then read the select value with $.val(). The problem only occurs in IE11 (I haven't tried other versions).

While this may seem an odd thing to do I got here since I'm using different jQuery plugins to enhance my selects (multiselect and picklist). I can't programatically clean all selected options by using the prop() method because later on the multiselect will not work anymore but I can't also just use the attr() method since the multiselect uses the prop().

I'm not sure if this is a bug or simply a browser limitation (or even the intended behavior). Chrome and Firefox seem to handle that just fine.

I tried several different jQuery versions but without luck.

Thanks in advance for your help.

**Comment by dmethvin** [comment]
Hi @Lukapt, the best place to get jQuery help is forum.jquery.com or stackoverflow.com. This is a bug tracker.

**Comment by dmethvin** [comment]
Hope this helps: Don't mix prop and attr like that. https://jsfiddle.net/kz3nskf6/2/

**Comment by Lukapt** [comment]
I was expecting this was a bug since I get different results from different browsers.

Since this is not a bug I will need to find an alternative solution if I want to continue using the same plugins (one of them uses prop and the other attr).

Thanks for your help.

**Comment by dmethvin** [comment]
Using .attr() is basically wrong for the dynamic state of a form element, as described in the [API docs](http://api.jquery.com/attr/). You can report a bug to the plugin that is getting it wrong, change their code so that it works, and use that copy.
