### ISSUE TITLE
jQueryUI 1.11.4 .position() fails with jQuery 3.0.0

### ISSUE THREAD

**Issue by vanderlee** [jquery/jquery#3181]
The `.position()` method of jQueryUI fails with jQuery 3.0.0

https://jsfiddle.net/xe95kx1b/

jQuery dumps an error to console: 'VM206 jquery-3.0.0.js:9779 Uncaught TypeError: elem.getClientRects is not a function'.

The problem seems to be with `window`, which does not have this function and is used as the default for the `within` property if the object passed to `.position()` does not provide a `within` property, where is is used in the jQuery 3.0.0 `.offset()` method.

It works okay if the 3.0.0 migrate plugin is loaded but this rather seems to be an incompatibility between the most recent jQuery and jQueryUI versions.

Using following:
- Chrome Versie 51.0.2704.103 m (64-bit) on Windows 10 (also seems to fail on FireFox).
- jQuery-3.0.0
- jQueryUI 1.11.4

**Comment by dmethvin** [comment]
See the [blog post](http://blog.jquery.com/2016/06/09/jquery-3-0-final-released/), or the [upgrade guide](https://jquery.com/upgrade-guide/3.0/#breaking-change-invalid-input-to-the-offset-method), or use [jQuery Migrate](https://github.com/jquery/jquery-migrate) and it should put a [warning message](https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnoffset-requires-a-valid-dom-element) on the console.

**Comment by vanderlee** [comment]
Yes, I know the `.offset()` is a backwards incompatibility, but surely current jQueryUI not working with current jQuery is a problem?

**Comment by dmethvin** [comment]
UI should work if you include Migrate, and for now you can tell your plugin users to use Migrate if the problem lies outside your plugin. The blog post specifically mentions the jQuery UI and Mobile situation:

> Compatibility with jQuery UI and jQuery Mobile
> While most things will work, there are a few issues that jQuery UI and jQuery Mobile will be addressing in upcoming releases. If you find an issue, keep in mind that it may already be addressed upstream and using the jQuery Migrate 3.0 plugin should fix it. Expect releases soon.
