### ISSUE TITLE
.offset() always returns [0, 0] for svg elements, this used to work before (3.0.0)

### ISSUE THREAD

**Issue by yorrd** [jquery/jquery#3182]
In the new release 3.0.0, whenever I try to get the .offset() of an svg element, it returns [0, 0] rather than the actual values. This is code which used to work in 2.x just fine, it broke with the update today.

Let me know if I can get you any more helpful information.

**Comment by dmethvin** [comment]
This is probably a dup of gh-3137 but we would need a test case to be sure. Can you put one together? The reason this "regression" occurred is that [we don't support SVG](https://contribute.jquery.org/wont-fix/#svg-vml-or-namespaced-elements-bugs) in general, so if there's no test it's likely to break.

**Comment by yorrd** [comment]
Yes, it's a dupe. Sorry I missed that. Please close this one, I'll comment below the main one
