### ISSUE TITLE
bug in jquery 3.0.0

### ISSUE THREAD

**Issue by StanPapusa** [jquery/jquery#3184]
example "09-sort-fruits-vegetables.html" (from chapter-05 of "jQuery UI In Action" of TJ VanToll, Manning Press) works with jquery.1.12.4.js, but gives you an error when run with jquery.3.0.0.js.
The browser is IE11

### Description ###
Here's the code calling jquery-1.12.4.js; replace jquery-1.12.4.js with jquery-3.0.0.js and you will stumble upon the error.

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Fruit & Vegetable Sorter</title>
	<link href="../css/jquery-ui-1.11.4.css" rel="stylesheet">

	<style>
		#fruits-container, #vegetables-container {
			width: 100px;
			float: left;
			margin: 0 10px;
		}
		#fruits, #vegetables {
			padding-left: 0.5em;
			min-height: 20px;
		}
		#fruits li:hover, #vegetables li:hover {
			cursor: move;
		}
		#fruits-container h3, #vegetables-container h3 {
			text-decoration: underline;
			margin: 0;
		}
		.sortable-placeholder {
			border: 2px dotted black;
			height: 18px;
		}
	</style>
</head>
<body>

<p>The fruits and vegetables aren't sorted correctly—rearrange them!</p>
<div id="game">
	<div id="fruits-container">
		<h3>Fruits</h3>
		<ul id="fruits"></ul>
	</div>
	<div id="vegetables-container">
		<h3>Vegetables</h3>
		<ul id="vegetables"></ul>
	</div>
</div>

<script src="../../../jquery-1.12.4.js"></script>
<script src="../../../jquery-ui-1.11.4.js"></script>

<script>
	var fruits = [ "Avocado", "Banana", "Apple", "Cherry", "Fig", "Grape",
			"Kiwi", "Lemon", "Olives", "Orange", "Pumpkin", "Tomato" ],
		vegetables = [ "Broccoli", "Carrot", "Celery", "Corn", "Garlic",
			"Green Bean", "Kale", "Lettuce", "Onion", "Pea", "Spinach",
			"Turnip" ];

	$.each( fruits.concat( vegetables ), function( index, item ) {
		var type = fruits.indexOf( item ) >= 0 ? "fruit" : "vegetable";
		
		if ( Math.random() < 0.6 ) {
			$( "<li data-type=" + type + ">" + item + "</li>" )
				.appendTo( Math.random() >= 0.5 ? "#fruits" :
				  "#vegetables" );
		}
	});

	$( "#fruits, #vegetables" ).sortable({
		connectWith: "#fruits, #vegetables",
		cursor: "move",
		helper: function( event, item ) {
			return $( "<div>", { text: item.text() } );
		},
		placeholder: "sortable-placeholder",
		stop: function() {
			if ( isValid() ) {
				$( "<div>" ).append( "<p>Correct! Refreshing game.</p>" )
					.dialog();
				setTimeout(function() {
					window.location = window.location; 
				}, 3000 );
			}
		}
	});

	function isValid() {
		var valid = true;
		$( "#fruits li, #vegetables li" ).each(function() {
			var item = $( this ),
				actual = item.parent()[ 0 ].id == "fruits" ? "fruit" :
				  "vegetable",
				correct = item.attr( "data-type" );

			if ( actual != correct ) {
				valid = false;
			}
		});
		return valid;
	};
</script>

</body>
</html>

**Comment by dmethvin** [comment]
Can you take the example and put it in jsbin.com or jsfiddle.net? Since this is using jQuery UI it's possible the error is a known one but since at this point it's just described as "an error" I am not sure.

**Comment by StanPapusa** [comment]
Here’s the code calling jquery-1.12.4.js. Replace jquery-1.12.4.js with jquery-3.0.0.js and you will stumble upon the error.

 

<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Fruit & Vegetable Sorter</title>
<link href="../css/jquery-ui-1.11.4.css" rel="stylesheet">

<style>
#fruits-container, #vegetables-container {
width: 100px;
float: left;
margin: 0 10px;
}
#fruits, #vegetables {
padding-left: 0.5em;
min-height: 20px;
}
#fruits li:hover, #vegetables li:hover {
cursor: move;
}
#fruits-container h3, #vegetables-container h3 {
text-decoration: underline;
margin: 0;
}
.sortable-placeholder {
border: 2px dotted black;
height: 18px;
}
</style>
</head>
<body>

<p>The fruits and vegetables aren't sorted correctly—rearrange them!</p>
<div id="game">
<div id="fruits-container">
<h3>Fruits</h3>
<ul id="fruits"></ul>
</div>
<div id="vegetables-container">
<h3>Vegetables</h3>
<ul id="vegetables"></ul>
</div>
</div>

<script src="../../../jquery-1.12.4.js"></script>
<script src="../../../jquery-ui-1.11.4.js"></script>

<script>
var fruits = [ "Avocado", "Banana", "Apple", "Cherry", "Fig", "Grape",
"Kiwi", "Lemon", "Olives", "Orange", "Pumpkin", "Tomato" ],
vegetables = [ "Broccoli", "Carrot", "Celery", "Corn", "Garlic",
"Green Bean", "Kale", "Lettuce", "Onion", "Pea", "Spinach",
"Turnip" ];

$.each( fruits.concat( vegetables ), function( index, item ) {
var type = fruits.indexOf( item ) >= 0 ? "fruit" : "vegetable";

if ( Math.random() < 0.6 ) {
$( "<li>" + item + "</li>" )
.appendTo( Math.random() >= 0.5 ? "#fruits" :
"#vegetables" );
}
});

$( "#fruits, #vegetables" ).sortable({
connectWith: "#fruits, #vegetables",
cursor: "move",
helper: function( event, item ) {
return $( "<div>", { text: item.text() } );
},
placeholder: "sortable-placeholder",
stop: function() {
if ( isValid() ) {
$( "<div>" ).append( "<p>Correct! Refreshing game.</p>" )
.dialog();
setTimeout(function() {
window.location = window.location; 
}, 3000 );
}
}
});

function isValid() {
var valid = true;
$( "#fruits li, #vegetables li" ).each(function() {
var item = $( this ),
actual = item.parent()[ 0 ].id == "fruits" ? "fruit" :
"vegetable",
correct = item.attr( "data-type" );

if ( actual != correct ) {
valid = false;
}
});
return valid;
};
</script>

</body>
</html>

**Comment by dmethvin** [comment]
Since it depends on local copies of files and I don't know if they've been changed, can you just include [jQuery Migrate](https://github.com/jquery/jquery-migrate#readme) in your local file and see if it gives you any messages? The [blog post](http://blog.jquery.com/2016/06/09/jquery-3-0-final-released/) mentions there are incompatibilities in the current jQuery UI and those should be fixed by Migrate.

**Comment by timmywil** [comment]
This sounds more like a support request. Please flesh this out further on the [forums](https://forum.jquery.com/) or in the #jquery irc channel.
