### ISSUE TITLE
.html() does not entity-encode greater-than character in attributes

### ISSUE THREAD

**Issue by tgr** [jquery/jquery#3186]
### Description ###
Per the WHATWG HTML5 spec, attributes cannot contain the greater-than ( > ) character: https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

jQuery's .html() method does not respect this:

    var $x = $('<span><a href="http://example.com">x</a></span>');
    $x.find('a').prop('title', 'a<p>b</p>c');
    $x.html() // <a href="http://example.com" title="a<p>b</p>c">x</a>

`<` and `>` should be changed to `&lt;` and `&gt;`, respectively. (For `<` that's actually not required by the standard but is more user-friendly.)

Tested on Chrome 50.0.2661.86 (64-bit), on Ubuntu 14.04.

### Link to test case ###

https://jsfiddle.net/ph3mvrsb/

**Comment by dmethvin** [comment]
It seems to do exactly what the native API does, which is our goal. https://jsfiddle.net/ph3mvrsb/1/

**Comment by mgol** [comment]
Interestingly, Safari 9.1 does escape those entities while Chrome & Firefox don't. What does the spec say and who's wrong here?

**Comment by dmethvin** [comment]
The example is setting the *property* which is then reflected to the *attribute*. It's possible that is bypassing some escaping that would normally be done. If the browsers aren't behaving consistently it's either behavior outside the spec or a bug in one or more browsers.
