### ISSUE TITLE
Ready is much too late.

### ISSUE THREAD

**Issue by JakeCigar** [jquery/jquery#3197]
I like the idea of deprecating .ready. But it is broken in 3.0.0. A simple demo shows it triggers much too late.

```
    <script>
    var now=$.now()
    $(function(){
        log("ready fired");
    });
    $(window).on("load",function(){
        log("load fired");
    });
    document.onreadystatechange = function () {
        log("readyState: "+document.readyState)
    }
    window.addEventListener('DOMContentLoaded', function(){
        log("DOMContentLoaded fired");
    });
    function log(s){
        console.log([$.now()-now,s])
    }
    </script>
```
Safari 10 shows…
[Log] [5, "readyState: interactive"] (2) (3-load.html, line 26)
[Log] [9, "DOMContentLoaded fired"] (2) (3-load.html, line 26)
[Log] [9, "readyState: complete"] (2) (3-load.html, line 26)
[Log] [11, "load fired"] (2) (3-load.html, line 26)
[Log] [625, "ready fired"] (2) (3-load.html, line 26)

The other browsers show the same order, but not as long a wait for ready.

**Comment by timmywil** [comment]
This is because the ready handler is now fired asynchronously. We did this so we can assure the user that all ready handlers will be called, even after a handler throws an exception. See https://github.com/jquery/jquery/issues/1823.

**Comment by dmethvin** [comment]
Why so late though? We don't do that via timeout.

**Comment by JakeCigar** [comment]
Doesn’t that mean that all pages that wait for ready will now wait a long time, and get fired before load?

It makes ready almost worthless.

**Comment by JakeCigar** [comment]
The test was done with Safari Version 10.0 (11602.1.32.7) first. It is beta, and could have some buggy code in it.

**Comment by JakeCigar** [comment]
Safari Technology Preview 9.1.2 gives me…
[Log] [1, "readyState: interactive"] (2) (3-load.html, line 26)
[Log] [3, "DOMContentLoaded fired"] (2) (3-load.html, line 26)
[Log] [3, "readyState: complete"] (2) (3-load.html, line 26)
[Log] [4, "load fired"] (2) (3-load.html, line 26)
[Log] [6, "ready fired"] (2) (3-load.html, line 26)

The wrong order, but not so much later.

**Comment by mgol** [comment]
> Doesn’t that mean that all pages that wait for ready will now wait a long time, and get fired before load?

No, they will get called as soon as `DOMContentLoaded` fires but always asynchronously. It will not wait until all images are loaded & stuff like that so most of the time it should fire before `load`.

I suspect that in your case there is nothing to be loaded so the `load` event fires quickly; in such cases it *may* fire before the jQuery ready callbacks. Try putting an image in the page and `load` should fire later then.

**Comment by dmethvin** [comment]
On a super small test file I think it's "okay" that ready handlers happen after load. The guarantee is that the document is ready and it is.

**Comment by JakeCigar** [comment]
> Try putting an image in the page and load should fire later then.

With one image,  the order is still off. 

[Log] [4, "readyState: interactive"] (2) (3-load, line 26)
[Log] [9, "DOMContentLoaded fired"] (2) (3-load, line 26)
[Log] [10, "readyState: complete"] (2) (3-load, line 26)
[Log] [12, "load fired"] (2) (3-load, line 26)
[Log] [16, "ready fired"] (2) (3-load, line 26)

**Comment by JakeCigar** [comment]
With an extremely large image from another site, I get normal numbers…

[1, "readyState: interactive"]
[6, "DOMContentLoaded fired"]
[14, "ready fired"]
[165, "readyState: complete"]
[167, "load fired"]

I guess I can live with ready being late on **silly** test pages.

**Comment by psaltelk** [comment]
Good day,

What can I do if I want the handlers to execute synchronously? The async execution is a problem for as I apply a third part control (Select2) in the ready handler and now in the latest version of Jquery my normal select control is shown just before the Select2 control is shown. This looks very unpreofessional for my applcation.
