### ISSUE TITLE
$("selector", data) from data loaded via ajax only works starting from one level of nesting

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery#3203]
Suppose you have this file called `loaded.html`:
```
<!DOCTYPE html>
<html>
<head>
<title>This is the loaded page's title</title>
</head>
<body>
<div id="test1">
	First level div, direct child of body. Can't be retrieved.
</div>
<div>
	<div id="test2">
	Second level div, i.e. nested within a div. Can be retrieved.
	</div>
</div>
</body>
</html>
```

Now from another file you do:
```
  $.ajax({
    url: 'loaded.html',
    success: function(data) {
      console.log($("#test1", data).length);
      console.log($("#test2", data).length);
    }
  });
```

**EXPECTED**: both lines should output **1**.

**OBSERVED**: the first outputs 0, the second outputs 1 as expected.

It seems that only nodes of a depth of at least 3 in the DOM tree of the loaded data  (where 0 is the `<html>` node itself, 1 is the body, and 2 would be a direct child of the body) can be retrieved. Not even direct children of body can, let alone the body itself, or the `<title>` etc., which by the way you should be able to retrieve too.
      
This is utter nonsense and is not even documented.

Simple test case: http://matteosistisette.com/test/stupidjquery/1/

**Comment by teo1978** [comment]
Not even this works as a workaround:
```
  $.ajax({
    url: 'loaded.html',
    success: function(data) {
      console.log($(data).find("#test1").length);
    }
  });
```

**Comment by mgol** [comment]
This is a misuse of the API. As [the docs state](https://api.jquery.com/jQuery/), the second parameter is a DOM Element, Document, or a jQuery object and not a string; you're passing a string there. If you turn it into a jQuery object you'll see why it's happening - you'll get a jQuery object containing a couple of nodes including the `test1` one and the div containing `test2`. The find is invoked for each element of the collection and the `test1` element obviously doesn't contain `test1` as its child so you won't get anything.

**Comment by teo1978** [comment]
> This is a misuse of the API. As the docs state, the second parameter is a DOM Element, Document, or a jQuery object and not a string; you're passing a string there. 

Wow, that's funny. I'm pretty sure I learnt this misuse of the API from some of the official tutorials. What is for sure is I didn't invent it, and I've seen in a lot of places (almost every example and every StackOverflow answer out there involving `$.ajax`).

Now, if that is not supposed to be done, then what's the correct way to scan the loaded document without misusing the API?

By the way:
> If you turn it into a jQuery object you'll see why it's happening - you'll get a jQuery object containing a couple of nodes including...

How is that expected behavior? Shouldn't you get a jQuery object containing one root node? Isn't that a bug in itself?

**Comment by mgol** [comment]
> Wow, that's funny. I'm pretty sure I learnt this misuse of the API from some of the official tutorials.

If you have such examples, please report them.

> Now, if that is not supposed to be done, then what's the correct way to scan the loaded document without misusing the API?

If you want to search in what you got you can always append it to a custom div and search there:
```js
var div = $('<div>').append($(data));
console.log(div.find('title'));
console.log(div.find('#test1'));
console.log(div.find('#test2'));
```

We're [using a div](https://github.com/jquery/jquery/blob/3.0.0/src/manipulation/buildFragment.js#L39) as a container for HTML to be processed and only the HTML root element (i.e. an element with the `nodeName` `"HTML"`) can contain the `body` and `head` elements, in `div` contents they're stripped out, the rest remains.

**Comment by mgol** [comment]
> How is that expected behavior? Shouldn't you get a jQuery object containing one root node? Isn't that a bug in itself?

That's exactly what the native APIs do to the `body` & `head` tags:
```js
var div = document.createElement('div');
div.innerHTML = `<html>
    <head>
        <meta charset="utf-8">
        <title>Foo</title>
    </head>
    <body>
        <div>Div contents</div>
        <span>Span contents</span>
    </body>
</html>`;
console.log(div.innerHTML);
```
You'll get:
```
    
        <meta charset="utf-8">
        <title>Foo</title>
    
    
        <div>Div contents</div>
        <span>Span contents</span>
    
```
