### ISSUE TITLE
Can't retrieve the <body> or <title>, etc.,  of a document loaded with $.ajax()

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery#3205]
As a corollary of bug #3203, you cannot retrieve the contents of the `<title>` tag of a document loaded with `$.ajax`.

```
 $.ajax({
    url: 'somePageWithATitle.html',
    success: function(data) {
      // NONE of these works:
      console.log("The title of the loaded page is (not): "+$("title", data).text());
      console.log("The title of the loaded page is (not): "+$(data).find("title").text());
    }
  });
```

You can't get the contents of the `<body>` either, nor the `<script>` or `<meta>` tags in the `<head>`, nor anything like that.

**Comment by mgol** [comment]
You're using the API incorrectly, see https://github.com/jquery/jquery/issues/3203#issuecomment-228609314.
