### ISSUE TITLE
Move the wontfix page from contribute.jquery.com

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#3206]
It makes more sense to have it in the repo.

**Comment by markelog** [comment]
You mean add it to wiki https://github.com/jquery/jquery/wiki ?

**Comment by dmethvin** [comment]
Yep, i plan to get to it soon.

**Comment by timmywil** [comment]
He said 11 days ago. ⭕ ⭕ ⭕ ⭕ h.

**Comment by dmethvin** [comment]
It's those lazy hazy days of summer!

**Comment by dmethvin** [comment]
Here's the first draft. I see a few small typos and formatting issues but I think it's better.

https://github.com/jquery/jquery/wiki/Won't-Fix

**Comment by dmethvin** [comment]
Still todo, replace https://contribute.jquery.org/wont-fix/ with a pointer to the wiki. I'll wait until a few people have reviewed the new wiki page.

**Comment by dmethvin** [comment]
The wontfix page at https://contribute.jquery.org/wont-fix/ was updated by https://github.com/jquery/contribute.jquery.org/commit/f81fbd58d94f25b943f2cfb9e5f91221a9665405, it's showing on stage but my pushed tag hasn't updated yet. I'll close this ticket, edit the wiki page as needed.

**Comment by markelog** [comment]
Yey!

**Comment by mgol** [comment]
The contribute site still hasn't got updated.

**Comment by dmethvin** [comment]
I pushed a new tag, it's finally updated.
