### ISSUE TITLE
Can we have drag event on element without draggable

### ISSUE THREAD

**Issue by Thaina** [jquery/jquery#3207]
For canvas element for example, I wish jquery could handle drag event and give us detail information such as position,direction,time on any element without changing position of the element itself. So we could handle these input into canvas logic

I wish jquery would have this functionality so it would support touch and multitouches on any device. And may handle this on any element. Such as input number box that could drag to increase/decrease number

**Comment by dmethvin** [comment]
This sounds like a plugin, so it wouldn't be put directly into jQuery core.
