### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by happyvig** [jquery/jquery#3209]
### Description ###

**jQuery v2.1.1 running in Samsung S2 (SPH-D710) Android 4.1.2 stock mobile browser**

User-Agent data : 
`Mozilla/5.0 (Linux; U; Android 4.1.2; en-us; SPH-D710 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 HClient/4.7.2 (Android, 4.1.2, samsung, SPH-D710)`

I am getting the following error in my minified JS file from my BackboneJS application :

**Uncaught TypeError: Cannot read property 'width' of undefined; URL:  http://mydomain.com/app/...../en.main.js; Line: 849**

The line number '849' specified in the the error trace directly points to a method 'Tween.prototype.run' in jquery.

The page this error happened has a jquery progress bar in it. 

Currently this app is in production and production monitoring environment error logs are get flooded with this error.

Please refer line : 6147 in the un-minified version of [Jquery 2.1.1](https://github.com/jquery/jquery-ui/blob/master/external/jquery-2.1.1/jquery.js) 

Request to resolve asap.

**Comment by dmethvin** [comment]
That isn't enough information to work on. Can you provide a reduced test case as requested in the issue template?

**Comment by timmywil** [comment]
We can reopen when there's a test case.
