### ISSUE TITLE
.load() as a shorthand for .on("load",...) shouldn't be deprecated

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery#3212]
I know it has been for a long time, but I have just found out because I have tried jQuery 3 where it has actually stopped working.

The deprecation of `.load()` as a short-hand of `.on("load",...)` is inconsistent. You haven't deprecated `.click()`, `.ready()`, etc., and you are not going to, are you? Until then, `.load()` shouldn't be deprecated either. It just create unnecessary inconsistency.

I do see the rationale behind it: it is ambiguous with the ajax `.load()` method. Discouraging its use is a good idea, but deprecating it and breaking it is going too far. **Unless** you do the same with all the event-binding shorthand methods such as `.click()`, `.keydown()`, `.ready()` etc. 
(Which wouldn't be such a crazy idea btw if it wasn't for backward compatibility: that has always been a bas API design from the beginning, sacrificing clearness for the sake of saving a few keystrokes in writing code.)

**Consistency** is a must in such a large API as jQuery's.

(by the way, it's ironic that with `.ready()` you did the opposite thing: keeping the `.ready()` method and deprecating `.on("ready")`; just one more inconsistency with even less reason to exist)

**Comment by gibson042** [comment]
"ready" isn't a DOM event (and is therefore irrelevant here), and the shorthand methods are just that—we don't provide them for every event (e.g., there are no `abort` or `reset` methods), and the joint removal of `load` and `unload` had no net effect on consistency as far as I can tell. Our decision to [deprecate](http://bugs.jquery.com/ticket/11733) and then [remove](https://github.com/jquery/jquery/issues/2286) `load` was indeed motivated by its ambiguity, and came with ample notice.

I don't see us adding back a `load` shorthand, but am in favor of deprecating all the remaining ones (and to be honest thought we already had, although that was just misremembering their [segregation into an `event/alias` module](https://github.com/jquery/jquery/commit/6f7b6915bf457c413476faefb2159df717c2c210)).

**Comment by gibson042** [comment]
Closing in favor of the more specific gh-3214.
