### ISSUE TITLE
Error when initializing dialog with jQuery 3.0.0 and jQuery UI 1.11.4

### ISSUE THREAD

**Issue by Lipata** [jquery/jquery#3217]
When initializing dialog, there is a console error: 

> TypeError: elem.getClientRects is not a function

This issue is related to the [following one](https://github.com/jquery/jquery/issues/2804).

The same error appears when the jQuery UI method [position()](https://api.jqueryui.com/position/) is used - specifically, when _within_ option is not set. Then jQuery 3.0.0 is evalutating the _elem_ as the Window obejct, which leads to error above.

Running that sample, will cause the error to appear in the console: [https://jsfiddle.net/dmkf9Leq/1/](https://jsfiddle.net/dmkf9Leq/1/)

**Comment by mgol** [comment]
See https://github.com/jquery/jquery/issues/3181#issuecomment-226964470.
