### ISSUE TITLE
jQuery 3.1.0 gets `option:disabled` and `option:enabled` wrong

### ISSUE THREAD

**Issue by acdcjunior** [jquery/jquery#3224]
### Description ###

Considering the spec (https://html.spec.whatwg.org/multipage/forms.html#concept-option-disabled), 2.2.4 is correct.

*  What do you expect to happen?
       * Native, 2.2.4 and 3.1.0 bring the same number of elements.
*  What acually happens?
       * 3.1.0 brings a different number.
*  Which browsers are affected?
       * Tested on Chrome 51@windows10 only.

### Link to test case ###

http://plnkr.co/edit/SaKHF3YxEQ9CcnH8Ri4z?p=preview

**Comment by gibson042** [comment]
Confirmed; looks like https://github.com/jquery/sizzle/commit/7999a01cf7bc92fb7d2951b4ad7442dbbd788e7f just flat-out got optgroup handling wrong.

**Comment by timmywil** [comment]
Was looking at this too, and I noticed that Chrome sees `<a disabled></a>` as still enabled, which caused the new feature test to fail. That said, I think Chrome's right, since the anchor element [does not have a disabled IDL](https://html.spec.whatwg.org/multipage/semantics.html#the-a-element).

**Comment by timmywil** [comment]
BTW http://jsbin.com/texafetaro/edit?html,js,console,output

Different results in Safari and FF than Chrome.

**Comment by gibson042** [comment]
> Chrome sees `<a disabled></a>` as still enabled, which caused the new feature test to fail. That said, I think Chrome's right, since the anchor element [does not have a disabled IDL](https://html.spec.whatwg.org/multipage/semantics.html#the-a-element).

Chrome is actually the reason for that content; `<a>` elements should never match "[:enabled](https://html.spec.whatwg.org/multipage/scripting.html#selector-enabled)".

**Comment by timmywil** [comment]
I see, so it shouldn't match either ':enabled' or ':disabled'.
