### ISSUE TITLE
.not(arrayLike) shouldn't restrict results to elements

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#3226]
As [reported](http://irc.jquery.org/%23jquery-dev/latest.log.html#t11:52:27) by @scottgonzalez, `.not( arrayLike )` started filtering out non-element items in jQuery 3: http://jsbin.com/yobuhucife/1/edit?html,js,output . This is inconsistent with `.not( singleNode )` and `.not( fn )`, and counter to the stated "not(Selector) excludes non-element nodes" goals of the commit that introduced it: 0e2f8f9effd2c95647be534bf9055e099aad7cfd.

We should restrict the additional filtering to selector input (i.e., `.not( string )`).

**Comment by dmethvin** [comment]
If this is a regression, we should update the [docs](http://api.jquery.com/not/) as well, in particular the part under "Removing Specific Elements", to clarify that non-Element nodes are passed through.

**Comment by nicklou** [comment]
How could I help on this fix? With a first glance, the code fix does not seem to be that big. Should I attempt for a PR?

**Comment by gibson042** [comment]
The process is pretty simple; see https://github.com/jquery/jquery/blob/master/CONTRIBUTING.md and https://contribute.jquery.org/commits-and-pull-requests/ . Make sure you've signed our [CLA](http://contribute.jquery.org/CLA/) and are using the same name in your commits, and submit a pull request including both relevant test suite and source code changes.

**Comment by dmethvin** [comment]
@nicklou if you need help just ask!

**Comment by huguoliang1314** [comment]
hello,Mr gibson042@gibson042,i think the first step is judge the element nodeType,
so, return  elem.nodeType === 1&&( indexOf.call( qualifier, elem ) > -1 ) !== not ;

**Comment by gibson042** [comment]
@huguoliang1314: `elem.nodeType === 1` is already there; we want to _skip_ it when the initial qualifier is not a string.
