### ISSUE TITLE
Remove `event.which` property fill

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#3235]
IE8 seems to be the last browser that didn't provide this natively. It's a bit tricky to test because it needs a real event and not a simulated one. 

https://github.com/jquery/jquery/pull/3233#discussion_r70875393

See also gh-2337, if we're not filling the property and just passing it on I don't know that we need to formally deprecate it in jQuery or generate a Migrate warning. If browsers ever tried to deprecate it via a console warning, the pass-through we do when copying the property would be the responsibility of the caller. If anything I'd say we add a note in our docs to use `event.button` or `event.buttons` where possible.

**Comment by mgol** [comment]
PR: #4765

**Comment by mgol** [comment]
Why is this marked as a behavior change if all the browsers already support it?

**Comment by mgol** [comment]
@dmethvin Sorry, I didn't notice this issue & your assignment before I made the PR. I reassigned the issue to myself.

**Comment by dmethvin** [comment]
@mgol No problem, thanks for doing it! Should just be a case of deleting the `which` entry in event.js, I wouldn't think it changes any tests.
