### ISSUE TITLE
JQM popup error with jQuery 2.2.4

### ISSUE THREAD

**Issue by blyonsebg** [jquery/jquery#3236]
jquery.min.js:3 Uncaught TypeError: a.preventDefault is not a function

I noticed a ticket for the same error in 2.2.0 but it's not fixed for 2.2.4

I'm also using JQM 1.4.5

I don't get this error in jQuery 2.1.4

**Comment by dmethvin** [comment]
Hi, just checking on whether our issue tracker is working properly. Did you see a template to be filled in when you created your issue? It should have asked you for a test case.

**Comment by jbarrio** [comment]
Hi,

I can try to provide more information for this bug:

Product versions used:

 - jQuery 2.2.4.
 - jQueryMobile 1.4.5.

Trying oficial JQM [popup basic demo](http://demos.jquerymobile.com/1.4.5/popup/#popupDemo) raises this error:

> jquery-2.2.4.min.js:3 Uncaught TypeError: a.preventDefault is not a function

I hope this clarifies the issue :_)
