### ISSUE TITLE
$.ajax(...).success is not a function

### ISSUE THREAD

**Issue by AdamHess** [jquery/jquery#3239]
### Description ###

Upgrading from jQuery 2->3 $.ajax.success no longer works (or is not well documented that it's a breaking change) 

## Example 

```
$.ajax("/SomeResource")
  .success(function (data) {
    //do stuff here. 
  });
```

**Comment by Florian-R** [comment]
See http://api.jquery.com/jQuery.ajax/ 

> Deprecation Notice: The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callbacks are removed as of jQuery 3.0. You can use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.

**Comment by dmethvin** [comment]
Also the upgrade guide:

https://jquery.com/upgrade-guide/3.0/#breaking-change-special-case-deferred-methods-removed-from-jquery-ajax

And the jQuery Migrate plugin:

https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqxhrsuccess-is-deprecated-and-removed
