### ISSUE TITLE
`grunt newer:eslint` & `grunt newer:eslint:dev` both lint all files

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#3246]
### Description ###
Run:
```
grunt newer:eslint:dev --verbose
```
and you'll see all files in the `dev` target are linted. Repeat it a few times - all files are still linted.

I thought the `newer` task doesn't work at all but it seems to work fine with `jsonlint`; running `grunt newer:jsonlint` lints no files the second time.

cc @markelog 

### Link to test case ###

N/A

**Comment by mgol** [comment]
This problem in particular means that the precommit hook is taking way longer than it needs to.

**Comment by markelog** [comment]
Well, that sucks :/
