### ISSUE TITLE
Move to a non-deprecated eslintrc format

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#3248]
### Description ###
See http://eslint.org/docs/user-guide/configuring#configuration-file-formats:

"Deprecated - use .eslintrc, which can be either JSON or YAML."

We should move to `.eslintrc.json`.

### Link to test case ###

N/A

**Comment by markelog** [comment]
Wow, news to me! How about I will fix this in https://github.com/jquery/jquery/pull/3247
