### ISSUE TITLE
Offset throws error when used with window

### ISSUE THREAD

**Issue by Tokimon** [jquery/jquery#3249]
### Description ###
`.offset()` throws an error on:

```
if ( !elem.getClientRects().length ) {
     return { top: 0, left: 0 };
}
```

when `elem` is window, since `getClientRects` is not defied on window.

Present in the latest build. Just looked it up on the master branch at:
`jquery/src/offset.js`

### Link to test case ###
http://codepen.io/anon/pen/AXdrBg
(check the console)

**Comment by mgol** [comment]
Please read the upgrade guide, especially [the `offset` section](https://jquery.com/upgrade-guide/3.0/#breaking-change-invalid-input-to-the-offset-method). This is an expected breaking change.

**Comment by Tokimon** [comment]
Ok. it just seemed odd to me that jQuery throws errors, normally it goes out of its way to handle errors silently.
But thank you for the answer.
