### ISSUE TITLE
jQuery.extend update objects references

### ISSUE THREAD

**Issue by zoubir** [jquery/jquery#3250]
To see this issue you can try the following code :

```
var STATIC_OPTIONS = {color : '#fff', radius : 100};
var static1 = STATIC_OPTIONS ; 
var settings = STATIC_OPTIONS ; 
var options = { id : '1',  radius : 200};
$.extend(settings, options);
console.log(static1); // This shouldn't be updated
console.log(STATIC_OPTIONS); // This shouldn't be updated
```

[Link to test case](https://embed.plnkr.co/UNUrX1zrIjzyDQs1F6ko/)

**Comment by dmethvin** [comment]
The documentation specifically explains this. http://api.jquery.com/jquery.extend/

Assigning an object to multiple variables does not copy its content. For more help you can ask on StackOverflow or the jQuery Forum.
