### ISSUE TITLE
1.12.4版本最新发布的这个版本，是否支持IE8，以及那些特性或者函数IE8用不了的，谢谢大神们的告知

### ISSUE THREAD

**Issue by Jerry-goodboy** [jquery/jquery#3252]
1.12.4版本最新发布的这个版本，是否支持IE8，以及那些特性或者函数IE8用不了的，谢谢大神们的告知

**Comment by mgol** [comment]
I don't really understand the ticket, even via Google Translate.

**Comment by ryanlin1986** [comment]
@Jerry-goodboy  首先最新版本是1.12.0，并不是你说的1.12.4， 你是指1.11.4？
根据1.12.0的日志说明，IE8-IE10还是可以用的，但是官方不再进行支持（但相关代码还没移除），到1.13.0版本会正式去掉相关的支持代码。
http://jqueryui.com/changelog/1.12.0/

**Comment by mgol** [comment]
@ryanlin1986 (as far as I understood from Google Translate) this is not a jQuery UI repository but a jQuery one. The latest jQuery 1.x is, indeed, 1.12.4; see: https://code.jquery.com/jquery/#jquery-all-1.x

**Comment by ryanlin1986** [comment]
@mgol  Sorry I made a mistake that I though Jerry is asking about jquery ui 1.12.0(cause I also track the jquery ui issues). Actually jerry is asking about if IE8 is supported, if not, what features is missing. As far as I know, The 1.x branch includes support for IE 6/7/8.

@Jerry-goodboy  1.x系列支持 从IE6起步哦。

**Comment by mgol** [comment]
> As far as I know, The 1.x branch includes support for IE 6/7/8.

Yes, that's correct (although we'll only fix critical issues on this branch, we're focusing on jQuery 3 from now on). Thanks for translating! :-)
