### ISSUE TITLE
Very slow listeners when filtering by selector.

### ISSUE THREAD

**Issue by vitaliylag** [jquery/jquery#3254]
This issue is about listeners with filtering by selector, not just usual listeners. For example:
```js
$('...').on('click', '.myClass', func);
```

Now jQuery is comparing all selectors each time the event occurs, but this is not optimal and take very long time, especially on mobile phones.

You should use this algorithm:

1. For example, let it be #id selector. Create object: key -> id, value -> handler.

2. When the event occurs do something like that:
   ```js
   if (elem.handlerById[elem.id]) elem.handlerById[elem.id]();
   ```
3. If you have more than one handler with the same selector filter then merge them into an array.

4. If you need keep order of calling then add counter to every handler and before calling put them all into array and sort by counter.

5. You can optimize many other selector. For example, for [attr=value] selector you need two nested object, first for searching by attr, second for searching by value, or just one object for searching by attr + "=" + value.

6. If you care about file size you can implement it as module and put link at the https://api.jquery.com/on/. When user requires module $.fn.on begins to work fast.

===

This algorithm works with O(1) speed. Here's example of short implementation that optimize #id selector only, can't work with data, doesn't split handlers by space and doesn't override $.fn.off:

```js
$.fn.on_original = $.fn.on;

$.fn.on = function(event, selector, handler) {
    if (typeof(selector) !== 'string' || !/^#[a-zA-Z0-9_\-]+$/.test(selector)) {
        return this.on_original(event, selector, handler);
    }
    
    for (var i = 0; i < this.length; i++) {
        var elem = this[i];
        
        if (!elem[event]) {
            elem[event] = {
                handlerById: {},
                handlerByClass: {},
                handlerByConcatAttrAndValue: {},
            };
            $(elem).on_original(event, DOMHandler); //Adding common listener without filtering
        }
        
        elem[event].handlerById[selector.substr(1)] = handler;
    }
};

function DOMHandler(e) {
    var handlerById = this[e.type].handlerById;
    var targetElem = e.target;
    
    while (targetElem !== this) {
        if (handlerById[targetElem.id]) {
            handlerById[targetElem.id].call(targetElem, e);
        }
        targetElem = targetElem.parentNode;
    }
}
```
Example of using:
```html
<!DOCTYPE html>

<div id="content">
    <div id="test10">
        <div id="fireMe"></div>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="jquery.fastOn.js"></script>

<script>
    var $content = $('#content');
    for (var i = 0; i < 100000; i++) {
        $content.on('myEvent', '#test' + i, logID);
    }
    
    var startTime = Date.now();
    
    // Logs "test10". Works 2500 ms without jquery.fastOn.js and 2 ms with it
    $('#fireMe').trigger({type: 'myEvent', value: true}); 
    
    console.log('time: ' + (Date.now() - startTime));

    function logID(e) {
        console.log(this.id);
    }
</script>
```

You can look at example here https://apii.ru/other/test/fastOn/

**Comment by timmywil** [comment]
Sizzle already has an algorithm to use fast paths for simple selectors, and we've done performance tests on event delegation (but jsperf.com is no longer available so I can't link them). The tests then looked just fine. Do you have a perf test to back up your statement that they take a very long time?

Besides that, I don't understand your algorithm. If you'd like to submit a PR, we'll happily take a look, but I'm not sure it would work the way you think it would.

**Comment by vitaliylag** [comment]
timmywil, on my mobile phone 1000 filters takes about 1 second for every trigger. On my computer about 60 msec. 1000 filters is not very much, I have real project with 200 filters.

What part you don't understand? I have my own implementation that overriddes $.fn.on and $.fn.off and works very fast but I don't think you merge it without code changing.

I can write pseudo code:
```js
$.fn.on_original = $.fn.on;

$.fn.on = function(event, selector, handler) {
    if (typeof(selector) !== 'string' || !selector.test(/^#[a-zA-Z0-9_\-]+$/)) {
        return $.fn.on_original(event, selector, handler);
    }
    
    for (var i = 0; i < this.length; i++) {
        var elem = this[i];
        
        if (!elem.handlerById) {
            elem.handlerById = {};
            $(elem).on(event, DOMListener);
        }
        
        elem.handlerById[selector.substr(1)] = handler;
    }
};

function DOMListener(e) {
    if (this.handlerById[this.id]) {
        var targetElem = calcTargetElem(......);
        this.handlerById[this.id].call(targetElem, e);
    }
}
```

This code is processing fast only #id selector and doesn't match docs but can be improved.

**Comment by vitaliylag** [comment]
@timmywil, I have added working implementation in the first comment and example of using. Of course real implementation with coveraging all cases will be more bigger, that it just example.

**Comment by timmywil** [comment]
I understand it now that I see the added code. We could check for re-bindings of the same handlers, but that would break existing code that relies on the same handler getting executed for each binding. That is [valid due to the possibility of side effects](http://jsbin.com/difaxi/edit?html,css,js,output) and makes this change impossible.

Also, we still do not have a real use case. I can't think of a good reason for having that many bindings of the same handler. This would indicate a problem with user code, not with jQuery. The first step is figuring out what the problem is, and that isn't done yet.

I don't foresee us making this change for the reasons above. You are free to put this optimization in your own code, but I suspect there's a more bulletproof way to restructure your code and still solve whatever use case you are addressing.

**Comment by vitaliylag** [comment]
«that would break existing code that relies on the same handler getting executed for each binding» — I didn't understand what you mean. Did you mean order of executing? For example if handlerA was binded before handlerB then it should be called first. If you did that's not a problem. You can keep any order that you want.

«we still do not have a real use case» — I have application with #content element but content is not defined before user do something. Content can be changed many times. When app is starting I add about 200 handlers on content. All this handlers works great and I don't need care about what content will be in #content. It's very convenient. But handlers work slow so I wrote my own implementation.

**Comment by dmethvin** [comment]
I think that approach is easy for very limited cases (for exampe, a single ID or CLASS selector and only listening on `document`)  but becomes large and difficult to manage when generalized to all the features jQuery supports for event handling.  

Give your ideas a try and run them against the unit tests. I think that will be easier than trying to describe all the difficulties we think are present. I think the code will end up being large, and we would be unlikely to land it in core directly. However, if you can identify simple hooks that allow you do do this as a plugin we could discuss adding those.
