### ISSUE TITLE
Event types colliding with Object prototype properties don't work

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#3256]
We use `event.type` [as a key](https://github.com/jquery/jquery/blob/305f193aa57014dc7d8fa0739a3fefd47166cd44/src/event.js#L294) to get the array of event handlers, which throws an exception when we instead receive an `Object.prototype` property and treat it like an array: https://jsfiddle.net/9t4kqaqr/

Our standard fix is appending a space (cf. [delegated selector match tracking](https://github.com/jquery/jquery/blob/305f193aa57014dc7d8fa0739a3fefd47166cd44/src/event.js#L370-L371) and [Sizzle `createCache`](https://github.com/jquery/sizzle/blob/582b63c607b344ce5838d89eaf57e693461948b2/src/sizzle.js#L349-L367)), but we should also consider `Map` for such purposes (ponyfilling as needed), especially if [Data.js](https://github.com/jquery/jquery/blob/305f193aa57014dc7d8fa0739a3fefd47166cd44/src/data/Data.js) can be updated accordingly—one of @rwaldron's original goals when creating it.

**Comment by mgol** [comment]
> but we should also consider `Map` for such purposes

Why not `Object.create(null)`? This one we wouldn't have to ponyfill.

**Comment by gibson042** [comment]
> Why not `Object.create(null)`?

I thought we still supported environments where that fails, but things look good! :+1:

**Comment by mgol** [comment]
Yup, and the changes required in that case will be smaller. :)

I'm only not sure if PhantomJS 1.x supports Object.create.

**Comment by PetarMax** [comment]
I've just rediscovered this bug. Is there a reason this hasn't been fixed yet?

**Comment by gibson042** [comment]
No one has yet gotten around to it. But a pull request would be welcome!

**Comment by timmywil** [comment]
I think we can implement the easy fix with spaces immediately, then consider using Map in 4.0.

**Comment by mgol** [comment]
PR: #4603. I also fixed similar issues in manipulation & data modules using `Object.create(null)`.

**Comment by rjaros** [comment]
In my opinion this is a breaking change that should not go into 3.5.0 minor upgrade version. It can break a lot of dependent projects, like this one: https://github.com/snapappointments/bootstrap-select/issues/2430

**Comment by mgol** [comment]
@rjaros Please submit a new issue with details.

**Comment by mgol** [comment]
I've changed the milestone from `3.5.0` to `4.0.0` since this was reverted in `3.5.1` as an unintended breaking change. The revert PR was #4666.
