### ISSUE TITLE
Callbacks not fired after 304 Not Modified

### ISSUE THREAD

**Issue by johntron** [jquery/jquery#3257]
**What do you expect to happen?**
Callbacks and promise steps fire when nesting `$.get()`/`$.when()`, even if second response is 304 Not Modified.

**What actually happens?**
First callback is fired, but others are not when second request receives 304.

**Which browsers are affected?**
Chrome 52 - worked fine in Chrome 51. Tested with jQuery 3.1.0, 2.2.4, and 1.1.5

**Example**
See https://twisty-braid.hyperdev.space/
Source: https://hyperdev.com/#!/project/twisty-braid

**Comment by dmethvin** [comment]
The "Source" link you posted is using jQuery 1.9.1. Can  you post a simplified test that doesn't include so much code?

**Comment by johntron** [comment]
I've removed everything that's unnecessary. Regarding the jQuery version, you may have thought it's 1.9.1 because you saw the `jquery-1.9.1.js` file - that wasn't being used and has since been deleted as well.

**Comment by dmethvin** [comment]
I don't understand the problem being reported here. In Chrome the console shows second, inner, outer and I think that is correct. The network shows two requests for /test, both reporting 200.

**Comment by johntron** [comment]
@dmethvin strange. I'm running Chrome 52.0.2743.82 (64-bit), and if we're running the same version, unfortunately, I don't really know what else to try. If the second request is reporting 200, then ETags seems broken on your machine. For this request your browser should send `If-Not-Modified` with the ETag provided by the response to the first request. The server is written in such a way that it will return a 304 and empty body for requests with this header (this mimics the Rails server our product uses).

I know it doesn't help, but four people here at work gets the behavior I've described - on Mac and Windows, at different offices/states, in Incognito mode and not, before/after clearing cache, with cache enabled/disabled, with/without extensions, etc. Nobody gets the behavior you see, which is how our product worked in Chrome 51 before everybody was automatically upgraded. This affected many of the requests our product sends, so we had to set `cache: false` globally to avoid side affects like missing page content. It's possible this is a browser bug, but – at least with older versions of jQuery – the library claimed to handle 304's with empty bodies gracefully.

**Comment by dmethvin** [comment]
I ran on another PC with Windows 8 and saw what you described. Then I restarted the system where I couldn't repro and now I can. So I guess something didn't get updated before?

Now, it seems like Chrome 52 returning a 304 is a change from Chrome 51 which pulled the result from the cache and returned it with a 200, as does Firefox for example.

**Comment by dmethvin** [comment]
I'm seeing jQuery make the second xhr request but not getting a completion event of any kind.

**Comment by dmethvin** [comment]
Trying to create a simple non-jQuery equivalent to see if there are missing events, this is as far as I can go for now. @johntron can you take a look? Seems like this is creating a 304 for the second request but showing 200. https://hyperdev.com/#!/project/plaid-boar

**Comment by johntron** [comment]
@dmethvin ah ok. I thought I remembered reading that jQuery has custom behavior to make 304's work like 200's (by caching response for the initial request), but I guess that's browser behavior. I'll definitely help creating a native example (and create a bug report for Chrome), but it looks like the link you posted was blocked:

```{"status":"Error","statusCode":403,"statusDetail":"Blocked Due to Blacklisting"}```

<img width="498" alt="screen shot 2016-08-02 at 2 58 32 pm" src="https://cloud.githubusercontent.com/assets/131961/17343078/9ceb98fa-58c1-11e6-93c1-26313194661c.png">

By the way, do you know if there are any specs regarding this behavior in the client? I checked [2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.5) and [this proposal](https://tools.ietf.org/html/draft-ietf-httpbis-p4-conditional-26#section-4.1), but this only describes server (and proxy) behavior – nothing for clients. I'm trying to determine if Chrome's change is for a reason, or a regression. It seems like a lot of applications could break.

**Comment by dmethvin** [comment]
Yeah, for some reason it's block that one and I don't have a copy :crying_cat_face:  It shows it as owned by me but seems to think there's something wrong with that example.

Basically my example just made an XHR request with logging for onload, onerror, onreadystatechange, and onabort, each time logging the event and the current xhr.status. On page load I made one request and then set a timeout for 500ms for a second request. 

I looked at the Chrome 52 release notes briefly and didn't see anything obvious. They added XHR breakpoints (which came in handy here) and I can see it's making both requests.  This is the closest I saw and it claims it only happened for sync xhr: https://bugs.chromium.org/p/chromium/issues/detail?id=570622

**Comment by johntron** [comment]
Yeah, I think I'll submit a bug report to Chrome. Here's the native proof: https://hyperdev.com/#!/project/twisty-braid. Thanks for the help @dmethvin - I really appreciate it :)

**Comment by dmethvin** [comment]
@johntron post a link back here to the Chromium ticket when you have it, thanks!

**Comment by johntron** [comment]
Here's the bug report for Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=633696

**Comment by NekR** [comment]
I think it might be somehow related to ServiceWorker, I don't see any other reason right now for chrome team to touch XHR code and produce new bugs.

**Comment by vimmerru** [comment]
Hi All,

I see similar problem not only for 304 response, but also for 404 response in Chrome 52. No callback for second xhr request to same url that returns 404. Probable it is related to races in Chrome CORS functionality. In case of break in debugger for few seconds after xhr request performed callback is called.

**Comment by Chexpir** [comment]
Defect fixed in Chromium.
https://bugs.chromium.org/p/chromium/issues/detail?id=633696#c36

The fix is included in:
53.0.2785.101 or later
54.0.2840.0 or later
55.0.*
Not included in:
53.0.2785.89

**Comment by mgol** [comment]
Thanks for following up. It seems we can close it.
