### ISSUE TITLE
TypeError: a.indexOf is not a function

### ISSUE THREAD

**Issue by sharewiz** [jquery/jquery#3258]
### Description ###

In Firefox 47.0 on Ubuntu 16.04.
Running jquery v3.1.0
Trying to run the little program below, I get the following error 

TypeError: a.indexOf is not a function

r.fn.load()
 jquery.js:4:18715
<anonymous>

I expect all images besides the 1st one to be hidden.  This does not happen.

### Link to test case ###
```js
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>Test</title>
  <script type='text/javascript' src='jquery-3.1.0.min.js'></script>
  <script type='text/javascript'> 
$(window).load(function(){
  $(function() {
    $('#fader img:not(:first)').hide();
  });
});  
  </script>
</head>
<body>
  <div id="fader">
    <img src="http://dummyimage.com/600x400/000/fff.png&text=Image1"/>
    <img src="http://dummyimage.com/200x400/f00/000.jpg&text=Image2"/>
    <img src="http://dummyimage.com/100x100/0f0/000.png&text=Image3"/>
    <img src="http://dummyimage.com/400x400/0ff/000.gif&text=Image4"/>
 </div>
</body>
</html>
```

**Comment by dmethvin** [comment]
> `$(window).load( ...`

https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed

This is also warned and filled by jQuery Migrate.
