### ISSUE TITLE
jQuery 1.12.x line breaks compatiblity with Firefox 5 or older, Netscape and Konqueror 

### ISSUE THREAD

**Issue by PascalReintjens** [jquery/jquery#3259]
When I tried to update from 1.11.3 to 1.12.4 I noticed that the latest releases broke a lot of old browser versions. Not only did jquery stop working, it totally broke javascript in some of these browsers

I looked into some of the error messages and found solutions:
1. getComputedStyle() always needs to have a pseudo element in older browsers: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle
2. addEventListener() always needs to have set useCapture explicitly to false in older browsers: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
3. removeEventListener() always needs to have set useCapture explicitly to false in older browsers: 
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener

Setting a few null / false was not much, but had a huge impact. After adding these, in no browser jquery broke javascript completely and some of the browsers now worked totally fine. But sadly in some old browsers there is still one problem which doesn't break javascript but some of the jquery behaviour. This gives of the error message:
"div.getClientRects is not a function"

Since this worked before, I think there should be a way to fix this. How did jquery handle this before 1.12?

And my second question: Why did jquery 1.12 suddenly have these "bugs" on some places of the code? Was it decided to drop support for these old browsers, or was that a regression introduced by code rewriting?

Thanks :)

**Comment by dmethvin** [comment]
We haven't supported browsers that old for a very long time,. Since we don't test on unsupported browsers we don't know when we make changes that might break on them, and we may actively remove workarounds we no longer need to make our supported browsers work.

Is there a reason why you need to support browsers that old? If so I would stay with older versions of jQuery.

**Comment by PascalReintjens** [comment]
Yes, I'm programming a webpage for someone with very high demands to browser compatibility, and while it's totally fine that some things a limited in these versions, Jquery breaking Javascript completely is not so great. If there's no other possibility I will stay at 1.11.3, but that would be my last choice. If I'd make a pull request to add these parameters, would that pull be rejected or is there a possibility for me to fix these problems even though the browser versions are officially unsupported?

**Comment by dmethvin** [comment]
If we don't test those browsers, we don't support those browsers. Even if you submitted patches it would only be a short time before some change broke them again.

**Comment by PascalReintjens** [comment]
I totally understand that this could be could be broken again like 10 minutes later, but as you said that these browsers aren’t supported anymore since a very long time, and they only got broken very recently, I still see a chance that the fixes would hold up for a while. And even if not, the time needed to fix these few problems isn’t that high, so I wouldn’t mind that much if it breaks shortly after the pull. So from my perspective it basically comes down to the question if such a pull would be allowed or rejected.

Thanks for your patience :)

**Comment by mgol** [comment]
I'm not very enthusiastic to such PRs as we may very well break it in the next patch release, seeing another issue like that reported again. If we don't test an environment and at the same time it's very rarely used, it seems to me that the tradeoff is too big.

Note that we removed those additional optional parameters knowing that it will break very old Firefox versions; us removing handling of `-moz-box-sizing` was done with the same knowledge (box-sizing handling is then broken in jQuery in Firefox older than 29). We've decided that's OK.

In this case, if you do want to support Firefox 5 even though jQuery you're using doesn't (we've been always only supporting last two Firefox releases) you can monkey patch those few APIs by yourself before loading jQuery, making sure that the final parameter is always passed. An untested monkey-patch example:
```js
if (typeof EventTarget !== 'undefined' && EventTarget.prototype &&
        EventTarget.prototype.addEventListener) {
    var origAddEventListener = EventTarget.prototype.addEventListener;
    EventTarget.prototype.addEventListener = function () {
        return origAddEventListener.call(this, arguments[0], arguments[1],
            arguments[2] || false);
    };
}
```

**Comment by mgol** [comment]
I'd be open to supporting Firefox ESR releases if some people demanded it (we haven't seen much demand so far, though), especially that we've been sort-of supporting old Chrome versions via Android 5.0 testing. But it would still only be Firefox ESR (currently at version 45) but not Firefox 5 which is more than 5 years old. (imagine all the known security holes this browser has)

**Comment by dmethvin** [comment]
If supporting old browsers is a super high priority, the best strategy would be to use an older version of jQuery and stay with it. It's really rare for newer browsers to break something in an old jQuery. I definitely don't think we should try to support browsers that are now unsupported by their own maker. As @mgol says I suppose we could support Firefox ESR but since it's a pretty recent browser it wouldn't help with Firefox 5 support.

**Comment by PascalReintjens** [comment]
Okay, thanks for the responses
