### ISSUE TITLE
Serialize of a disabled form.

### ISSUE THREAD

**Issue by JakeCigar** [jquery/jquery#3263]
3.1.0 returns an empty string in Chrome/Opera and IE. With older (1.x.x) jQuery or other browsers it works fine.

### Description ###

Previously a form that is disabled ( actually works in IE, but not others) could still be serialized. Now I get an empty string. I would just chalk this up to something crazy that should have never worked, but on the forum this came in as a question… https://forum.jquery.com/topic/2-2-0-to-3-1-0-upgrade-selector-change .

### Link to test case ###

http://home.jejaju.com/ser <-- demo
[ser.html.zip](https://github.com/jquery/jquery/files/404863/ser.html.zip)

**Comment by dmethvin** [comment]
Since forms don't have a `disabled` attribute/property it seems like this is a bug. Our disabled test is catching forms when we really only wanted fieldsets.

**Comment by JakeCigar** [comment]
It seems that microsoft believes that forms can have a disabled property.  https://msdn.microsoft.com/en-us/library/ms535249(v=vs.85).aspx .

**Comment by dmethvin** [comment]
The standard says they don't: https://html.spec.whatwg.org/multipage/forms.html#the-form-element

IE8-11 does disable some elements when you set `form.disabled=true` but Edge does not: http://output.jsbin.com/gohefunako

Since IE truly does disable forms, the current behavior is probably the best thing to do for cross-browser consistency. People should *not* be setting the `disabled` property/attribute on forms, right? How did you run into this @JakeCigar, was it reported on the forums?

**Comment by mgol** [comment]
@dmethvin IE is even funnier there. If you "disable" the form in this way,
all inputs look like disabled (they're grayed out) and the checkbox is not
clickable but the regular input accepts keyboard input; you can see that in
your jsbin. What a mess!

**Comment by JakeCigar** [comment]
It came from the forum. It took me a while to figure out that he was actually disabling the form. I never thought it would work anywhere, until I did the tests. The forum link is up top.

I don’t care which way this is resolved, as the OP has a several enough workarounds.  You can just document that jQuery won’t support disabling forms, or you can patch it to return "" in all browsers or a correct string.  Older versions returned a correct string.

**Comment by jtara** [comment]
The link below seems to say that form controls can **inherit** the disabled attribute. So, it seems to me they could inherit it from a form - or, for that matter, any parent, say, a <fieldset>, a <div> within the form, or a <div> enclosing the form, etc. etc.

This is for HTML4:

https://www.w3.org/TR/html401/interact/forms.html#disabled

However, HTML5 has a bit different language. It only permit inheritance from a <fieldset>.

https://www.w3.org/TR/html/sec-forms.html#enabling-and-disabling-form-controls-the-disabled-attribute

**Comment by JakeCigar** [comment]
A "form control" is not a <form>.  It is an element used in a form.

**Comment by jtara** [comment]
Yes, I know that a form control is not a form. The first link enumerates the form control explicitly:

> The following elements support the disabled attribute: BUTTON, INPUT, OPTGROUP, OPTION, SELECT, and TEXTAREA.

But, the, how are we to interpret the next sentence?

> This attribute is inherited but local declarations override the inherited value.

Maybe the only possible inheritance is select > optgroup > option. Or maybe it is from any parent. The documentation is not explicit.

**Comment by JakeCigar** [comment]
Since things inherit from their parent, " select > optgroup > option " explains what they are writing about. 

No mention of a form being able to be disabled.

**Comment by Kaelum** [comment]
Hey All,

As the person who first brought this issue up to JakeCigar, this used to work across IE, Firefox, and Chrome.  As stated above, IE still supports this, and I believe that Chrome does too, but it looks like Firefox either no longer inherits this value, or it ignores the inherited value, and I don't know about any other browsers.  So, to keep this as simple as possible, I believe that the changes in 3.x.x need to be listed as breaking changes, even though it may not have been an intended (hidden) feature.

Then a Feature request could be created to allow the disabling, and re-enabling, of form input objects (that would affect serialize() in the same way) via a container, which could possibly be the form itself (if all browsers would support it), or some other container (child or parent), to allow for this functionality.  If a configurable modal screen (optional) is placed over the container, all the better.

How does that sound?
-Will

**Comment by dmethvin** [comment]
> I believe that the changes in 3.x.x need to be listed as breaking changes, 

When semver refers to *breaking changes*, it is referring to breakage of the *documented API*. When garbage goes in it's very possible for garbage to come out. As you notice from the IE example, a form is in a rather bizarre state when it is disabled so I am not sure why you would want to intentionally cause that.

Also, I'm not yet convinced that setting a `disabled` property/attribute on a form has any useful effect and/or is documented by standards. 

Here is what I see for a disabled form: http://jsbin.com/mikoxotuwe/1/edit?html,output

Taking jQuery out of this equation, what effect should disabling a form have? What was the code trying to accomplish by disabling the form?

**Comment by Kaelum** [comment]
@dmethvin This used to work across multiple browsers as I had described, and would prevent users from making any changes, or producing additional events (especially "click" events).  The specs have obviously changed over the years, and this no longer works as expected.  The bottom line is that we need a reliable way to disable the changing of field values, and their events, while still being able to serialize those values for AJAX calls.  How this is done doesn't really concern me at this time, as long as it is cross-browser safe.

Maybe we need **data-serialize-default** (on serialize() object), and **data-serialize** (on value fields) attributes with  **true/false/always** values (default true = current functionality), or something else for the serialize() method.  I'll leave that up to you guys, as you have your eyes on the bigger picture.

**Comment by dmethvin** [comment]
> The bottom line is that we need a reliable way to disable the changing of field values, and their events, 

Right now the way to do that would be by enumerating the fields and setting them to `disabled`, since there is no standard form-wide mechanism to disable them. I suppose another way would be to put some kind of modal overlay on the form to prevent people from interacting with it, but in general that is tricky due to keyboard interactions for example. Either of those solutions would be plugins.

> while still being able to serialize those values for AJAX calls. 

For that, it's a question of whether jQuery should pay attention to the `disabled` property on a form. It's not supposed to be there according to standards, so to me it's a coin toss. Given the way IE behaves nobody should be setting that property. This part is a Sizzle issue and @gibson042 opened https://github.com/jquery/sizzle/issues/387 to track it.

**Comment by Kaelum** [comment]
@dmethvin I trust that you guys will come up with something workable.  However, there is one more wrench that that needs to be considered.  There will be times where specific fields will be marked as disabled, and that state needs to be preserved during this "protection" period, and after it is removed, which makes using the "disabled" property on individual fields rather tricky.  I suppose that we could use a data- attribute on fields to filter out fields when adding/removing this protection.

For now, I think I'll work on something related to my last thought (above), as that appears to be the way that have envisioned it working.  Thanks!

**Comment by gibson042** [comment]
Paying attention to `disabled` on non-fieldset ancestors was an oversight that has now been corrected. Note, however, that the descendant elements will still match `:disabled` in IE, because they truly _are_ disabled there—and our advice is still to avoid using the property except where it is valid (e.g., on fieldsets).
