### ISSUE TITLE
$.fn.filter() drops Elements with customed "async" attribute

### ISSUE THREAD

**Issue by TechQuery** [jquery/jquery#3270]
### Description ###

`$.fn.filter()` drops Elements with **customed "async" attribute** which match `[async="false"]` selector.

It occurs at Chrome, Firefox and IE in Windows 7 (maybe more).

### Link to test case ###

https://jsbin.com/rewurikedu/edit?html,console,output

**Comment by gibson042** [comment]
jQuery inserts special handlers to enforce the specified behavior of [HTML boolean attributes](https://html.spec.whatwg.org/multipage/infrastructure.html#boolean-attributes) like [`async`](https://html.spec.whatwg.org/multipage/indices.html#attributes-3) (that their values MUST be either empty strings or case-insensitively identical to their names), and those handlers disrupt the non-native selector processing used by `.filter` and some other calls. Please use [`data-*` attributes](https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes) such as `data-async` to associate custom data with elements.

**Comment by TechQuery** [comment]
@gibson042 
I think that `false` is an acceptable value, because of https://wiki.whatwg.org/wiki/Dynamic_Script_Execution_Order

**Comment by gibson042** [comment]
@TechQuery There is an important [distinction](https://html.spec.whatwg.org/multipage/infrastructure.html#terminology) between element content attributes (which appear in HTML source like `<element attribute="value"/>`) and element IDL attributes (which appear in DOM bindings such as Javascript, where they are properties of [`Element`](https://dom.spec.whatwg.org/#interface-element) objects like `element.attribute`), and it is particularly relevant in the case of [boolean attributes](https://html.spec.whatwg.org/multipage/infrastructure.html#reflecting-content-attributes-in-idl-attributes) like `async`:
> If a reflecting IDL attribute is a `boolean` attribute, then on getting the IDL attribute must return true if the content attribute is set, and false if it is absent. On setting, the content attribute must be removed if the IDL attribute is set to false, and must be set to the empty string if the IDL attribute is set to true. (This corresponds to the rules for boolean content attributes.)

In fact, "false" is specifically noted as a disallowed value for [boolean \[content\] attributes](https://html.spec.whatwg.org/multipage/infrastructure.html#boolean-attribute):
> _The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether._

**Comment by TechQuery** [comment]
@gibson042 Thanks for your detailed answer !

But in my opinion, `async` is only an **boolean IDL attribute** of `<script />`. If I write in any other HTML tags, it's just a **customed content attribute**.

So, **Ordinary Element with an attribute of `async="false"`** should be selected by `$.fn.filter()` literally according to HTML code and CSS selector, just as what `jQuery()` and `Element.prototype.querySelectorAll()` do.

**Comment by dmethvin** [comment]
I won't address the specific code behavior but I do have a serious concern about the way this markup is written.

When you use standard attributes like `async` for custom purposes, it creates a future hazard in the case where the standard decides to use it. If your code is not very important, the standard uses `async` on `<select>` elements and your code is broken. If it breaks important web sites, the standard must work around this and the entire web has to use a different name because your code stole it. 

The HTML standard provides [data attributes](https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes) for exactly the purpose you are using `async` here. Just use `data-async` for your custom data .

**Comment by gibson042** [comment]
> But in my opinion, `async` is only an **boolean IDL attribute** of `<script />`. If I write in any other HTML tags, it's just a **customed content attribute**.

That's true, but a) it makes your document [non-conforming](https://html.spec.whatwg.org/multipage/dom.html#semantics-2), and b) addressing such edge cases within jQuery would add too much size, complexity, and potentially performance degradation. Just use `data-*` attributes.

**Comment by TechQuery** [comment]
@dmethvin @gibson042 Thanks for your patience and advices !

But **`data-*` attribute** in my SPA engine is used as **Arguments for building Query String of HTTP API**...

I want to extend **the semanteme of HTML standard attributes** (some frequently-used) to all kinds of HTML Tags, conform to **the coding habit of traditional non-SPA Web Page**. (Naming is a kind of headache for coders, so I prefer to use existing semanteme for similar purposes... (⊙﹏⊙)b )

On the other hand, in the future, when I use **Web Component Standard** to develop a **Custom HTML Tag**, I can also define a **content/IDL attribute** with the same name of HTML Standard to implement similar function, such as loading resource or media asynchronously (or not).

(I'm reading the book named _Learning Web Component Development_, and thinking about **the best practice of [SPA developing](https://github.com/TechQuery/EasyWebApp.js/tree/Component)**...)

**Comment by gibson042** [comment]
> But **`data-*` attribute** in my SPA engine is used as **Arguments for building Query String of HTTP API**...

Given the general-purpose nature of `data-*` attributes, it would be bad form to assume that every one appearing on your custom element is intended for one particular use. I would instead introduce namespacing, e.g. `data-techquery-urlparam-foo`.

> I want to extend **the semanteme of HTML standard attributes** (some frequently-used) to all kinds of HTML Tags, conform to **the coding habit of traditional non-SPA Web Page**. (Naming is a kind of headache for coders, so I prefer to use existing semanteme for similar purposes... (⊙﹏⊙)b )

> On the other hand, in the future, when I use **Web Component Standard** to develop a **Custom HTML Tag**, I can also define a **content/IDL attribute** with the same name of HTML Standard to implement similar function, such as loading resource or media asynchronously (or not).

That's fine; just be aware that jQuery has some rather indiscriminate code for handling any attribute sharing a name with a standardized boolean attribute.
