### ISSUE TITLE
event namespacing broken

### ISSUE THREAD

**Issue by standus** [jquery/jquery#3274]
Hi,

I tested jQuery 3.1.0 with code:
testFn() {
	console.log('test');
}
jQuery( document ).ready(function() {
    jQuery(window).on('load.mynamespace', function(event){ testFn();  });
});
And event is not fired.

Tested on Windows 10 Home, Chrome 52.0.2743.116 m (64-bit).
This code : jQuery(window).on('load', function(event){ testFn();  }); is OK, Also jQuery 2.2.0 is OK.

**Comment by dmethvin** [comment]
Don't attach a load event in a ready handler. Attach it outside the ready handler.

**Comment by standus** [comment]
Yes it works, but my code works too in FF but not in Chrome.

**Comment by dmethvin** [comment]
Can you create an example on jsbin.com or jsfiddle.net? The template should have asked for one, was it missing?

**Comment by standus** [comment]
I tried it on testing webs, but it is impossible, its with error or work normal.

**Comment by dmethvin** [comment]
Okay, well all I can say is that this code is incorrect and may work unreliably depending on the browser and size of the page:
```js
jQuery( document ).ready(function() {
jQuery(window).on('load.mynamespace', function(event){ testFn(); });
});
```
if you did this instead it should work, assuming the code is loaded before the `window.onload` event fires and not dynamically:
```js
jQuery(window).on('load.mynamespace', function(event){ testFn(); });
jQuery( document ).ready(function() {
   // nothing
});
```
