### ISSUE TITLE
Security Error in Chrome when use contents()

### ISSUE THREAD

**Issue by guzich** [jquery/jquery#3275]
### Description ###
Using of method "contents()" on page with iframes from remote domain causes fatal error in Google Chrome:
Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://example.com" from accessing a frame with origin "https://www.youtube.com".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "https". Protocols must match.

To prevent errors when using "contents()"  maybe should:
replace 
`return elem.contentDocument || jQuery.merge( [], elem.childNodes );`
by
```
try {
	return elem.contentDocument || jQuery.merge( [], elem.childNodes );
} catch (e) { 
	return false;
} 

```
or add checking that elem is not iframe from remote domain before expression 
`elem.contentDocument `

**Comment by mgol** [comment]
The template asked you for a test case, can you construct one? Note that cross-origin document access is not supported by browsers unless CORS is enabled so errors may happen; you shouldn't try to access data you're not allowed to access.

**Comment by mgol** [comment]
Closing because of lacking information. If you provide the test case we can reopen.
