### ISSUE TITLE
Update fro version 2.2.2 to 3.1.0 generate this error

### ISSUE THREAD

**Issue by yourchoice** [jquery/jquery#3276]
Update fro version 2.2.2 to 3.1.0 generate this error:

> jQuery.Deferred exception: Cannot read property 'indexOf' of undefined TypeError: Cannot read property 'indexOf' of undefined
>     at r.fn.load 

> jquery-3.1.0.min.js:4 Uncaught TypeError: a.indexOf is not a function

**Comment by mgol** [comment]
We need a test case without external libraries at jsbin or jsfiddle, just
an error message doesn't tell us much.

Also, are you using Migrate? If so, please update it as well.

-- 
Michał Gołębiowski

**Comment by mgol** [comment]
We still need a test case on jabin or jsfiddle. Also, does it happen in every browser or just some of them?

**Comment by alecpl** [comment]
https://jsfiddle.net/1bohp1dc/ The same error in Firefox 48 and Chromium 51.

**Comment by dmethvin** [comment]
Reports like this are super frustrating for us. Major-version releases have breaking changes by the definition of semver. We write up extensive documentation and even provide a plugin to help people with the processes, and mention those endlessly each time we release new versions. Yet it seems some people just drop the new version into existing code and are puzzled when it doesn't work.

Please read the documentation and use jQuery Migrate.

https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed

https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnload-is-deprecated

**Comment by naturefreak** [comment]
Thanks for including the link that explains how the load method was removed from jquery 3.x. In my case, I wasn't upgrading from a previous version, I was just starting a new project. I looked at the jquery documentation and found the .load event handler (http://api.jquery.com/load-event/) but didn't see any notes that it was removed.

Also, do you have any control over what error message displays, for example, in the Firefox debugger? For jquery newbies, the error wasn't all that helpful. Or, is that totally out of your control?

**Comment by mgol** [comment]
@naturefreak On the right side of the page you linked in the black header saying `.load( handler )` there's a note: `version deprecated: 1.8, removed: 3.0`.

Maybe this note is too easy to skip? We have an issue on the API repo to make it clearer: https://github.com/jquery/api.jquery.com/issues/971.

**Comment by mgol** [comment]
@naturefreak 

> Also, do you have any control over what error message displays, for example, in the Firefox debugger? For jquery newbies, the error wasn't all that helpful. Or, is that totally out of your control?

We don't handle this scenario at all. The main problem is that we used to have two methods named identical and doing different things; [one](https://api.jquery.com/load-event/) or [the other](https://api.jquery.com/load/) would be dispatched depending on arguments passed. We've removed one of them so if you use `.load()` you'll always get the second one dispatched. If you pass parameters that it doesn't expect, anything can happen, including an error in a random line of jQuery code.

**Comment by mgol** [comment]
See also: https://github.com/jquery/api.jquery.com/issues/976.

**Comment by naturefreak** [comment]
Thanks for the explanation of the error and describing where to look for
the "removed" bit for the method. I'll be on the lookout for that in the
future. I agree that it would be good to make that stand out more for
removed items, since the error messages might not be of much use.

Jack
