### ISSUE TITLE
JSONPath Support?

### ISSUE THREAD

**Issue by t3dodson** [jquery/jquery#3280]
### Description ###
Does anyone think that JSONPath should be accepted by jquery as a first class feature? It seems like a failry primitive operation something like

$.JSONPath({books: [{name: "Moby Dick"}]}, '$.books[0].name'); // "Moby Dick"

I see a project which hasn't got much traction https://github.com/wilhelm-murdoch/jQuery-JSONPath

**Comment by dmethvin** [comment]
jQuery is a DOM library and this seems outside its core competency. There's no benefit of including it in the jQuery file other than publicizing it, which I'm sure that project would like but anyone who wants to use it can always include it themselves.
