### ISSUE TITLE
excluding exports/global not working on build

### ISSUE THREAD

**Issue by axten** [jquery/jquery#3281]
### Description ###
i tried to make a custom build without exports/global but its not working (jQuery 3.1)

run:
grunt custom:-exports/global

the problem is that the include of global is hard coded:
https://github.com/jquery/jquery/blob/master/build/tasks/build.js#L42-L45

**Comment by timmywil** [comment]
This has been fixed in master: 52e24471c89b80e6208b4987bb76994e64c1e489.
