### ISSUE TITLE
bug: Datepicker alternate field, un-populate

### ISSUE THREAD

**Issue by Ruth-Cantoni** [jquery/jquery#3282]
### Description ###
Datepicker, use of an alternate field.
When a date is chosen, the alternate date field is populated.
When the date field becomes empty (by clicking into the text input, selecting its whole text value and deleting it) then the alternate date field retains its previous value.
I would expect it to become empty too.
The browsers I've used to test are Safari 9.1.1 and Chrome  52.0.2743.116 (64-bit) on mac os x 10.10.5

### Link to test case ###
https://jqueryui.com/datepicker/#alt-field

**Comment by mgol** [comment]
Thanks for the report. However, this is the jQuery bug tracker, not jQuery UI. Issues with the latter should be reported at https://bugs.jqueryui.com/.
