### ISSUE TITLE
load javascript with .html() truncated

### ISSUE THREAD

**Issue by jechox** [jquery/jquery#3283]
### Description ###

- Version: jquery-3.1.0.js
- Agent: Chrome v51

I'd like to use .html() to load a pice of javascript and run it dynamic.
But if the pice contains '&lt;tr&gt;', then the entire javascript just gone.
Please find a simple test case below, thank you!

### Link to test case ###
http://jsbin.com/jahaxiweki/edit?html,output

**Comment by ktajpuri** [comment]
## Why cant we just do this
```
<script type="text/javascript">
	
var dom = document.createElement('script');
var str = 'var a = "<tr>"; testFunc(a);';

dom.innerHTML = str;
$("#out1").text(dom.outerHTML);

$("#out2").text('<script>var a = "<tr>"; testFunc(a);<\/script>');



</script> 
```

[http://jsbin.com/xizubiweti/edit?html,output](http://jsbin.com/xizubiweti/edit?html,output)

**Comment by timmywil** [comment]
Thanks for opening an issue! However, from the jQuery documentation:

> To set the content of a <script> element, which does not contain HTML, use the .text() method and not .html().
