### ISSUE TITLE
`jQuery.param()` can result in collisions.

### ISSUE THREAD

**Issue by nathanhammond** [jquery/jquery#3286]
The current implementation of `jQuery.param` is lossy:
```javascript
decodeURIComponent(
  $.param(
    { b: {'a][something': 'collision', 'a': {something: 'collision'}}}
  )
);
// => b[a][something]=collision&b[a][something]=collision
```

I consider this a bug but I'm unsure what the consequences would be to fix it. Essentially all sub-keys need to be double encoded to guarantee non-collisions.

**Comment by nathanhammond** [comment]
Bonus round!
```javascript
decodeURIComponent(
  $.param(
    { b: {'': 'oops'}}
  )
);
// => b[]=oops
```

**Comment by dmethvin** [comment]
I agree that looks wrong. To me the entire premise of serializing complex data structures this way is wrong but it's probably beyond trying to take anything back now. We can only either add to the mess in the name of repair or say it won't be fixed and point people to JSON.

It seems like there would be compat issues with double-encoding, including possible impacts with interpretation on the server side? If so, any change would have to wait for 4.0. Past experience has shown we're not very good at predicting when people are using strange things.

**Comment by timmywil** [comment]
Thanks! This sounds like a wontfix, but we would consider patches.

**Comment by nathanhammond** [comment]
I have a blog post on what the correct behavior should be complete as of yesterday and have colleagues reviewing it today. It's absurdly long (~10k words) and unfortunately complicated but I'll link it back here once published. The short version is that the solution for this problem required writing an entire spec and test suite, reverse-engineering 20-some-odd libraries, and identifying the intersecting successful behavior.

This is the future home of the spec, which hasn't yet been extracted from the blog post: https://github.com/nathanhammond/query-string-spec

This should guarantee interop with as many things as possible, meanwhile setting us in a good direction for the future. And yes, I've seen [XKCD 927](https://xkcd.com/927/). 😜
