### ISSUE TITLE
calling jQuery.holdReady(false) without jQuery.holdReady() will trigger jQuery.ready() without DOMContentLoaded

### ISSUE THREAD

**Issue by stevemao** [jquery/jquery#3287]
### Description ###

I have an app that assuming `jQuery.holdReady()` is called. So I can call `jQuery.holdReady(false)` whenever I'm ready. The problem is `DOMContentLoaded` is probably not triggered yet. Do you guys consider this as a bug? Also `readyWait: 1,` as a initially value is probably not intuitive. If we treat this as a bug I think the code would look better without this magic number :)

Bug Reports:
  Note that we only can fix bugs in the latest (1.x, 2.x, 3.x) versions of jQuery.
  Briefly describe the issue you've encountered
  *  What do you expect to happen?

Calling `jQuery.holdReady(false)` without calling `jQuery.holdReady()` should not trigger `jQuery.ready()` if dom is actually not ready.
  *  What acually happens?

Calling `jQuery.holdReady(false)` without calling `jQuery.holdReady()` triggering `jQuery.ready()` and jQuery actually think dom is ready.
  *  Which browsers are affected?
  Provide a *minimal* test case, see https://webkit.org/test-case-reduction/
  Use the latest shipping version of jQuery in your test case!
  We prefer test cases on https://jsbin.com or https://jsfiddle.net

I was going backward and forward whether I should open an issue. But I can totally provide a test case for this.

**Comment by gibson042** [comment]
http://api.jquery.com/jQuery.holdReady/ is pretty clear on `jQuery.holdReady` being an advanced feature, and on proper use consisting of `jQuery.holdReady( true )` followed by `jQuery.holdReady( false )`. Not only that, but we have decided to [deprecate](https://github.com/jquery/jquery/pull/2850#issuecomment-173315469) it entirely as suggested in https://github.com/jquery/jquery/issues/1778#issuecomment-72764833 .

I'm closing this for now, but if anyone considers it a mistake please post here and we'll consider reopening. But regardless, I recommend replacing uses of the functionality with `jQuery.when( jQuery.ready, jQuery.Deferred( waitForMyDependencies ) )` as suggested in https://github.com/jquery/jquery/pull/2850#issuecomment-173272471 .

**Comment by stevemao** [comment]
Sounds good. Thanks @gibson042 :)
