### ISSUE TITLE
Deprecate jQuery.holdReady

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#3288]
Suggested in https://github.com/jquery/jquery/issues/1778#issuecomment-72764833 and decided in https://github.com/jquery/jquery/pull/2850#issuecomment-173315469 . Gap noticed in #3287.

**Comment by dmethvin** [comment]
Added to the API list as well.

**Comment by nithmanoj** [comment]
I want to work on this issue, please inform me what to do of `test/data/readywaitloader.js` & `test/data/readywait.html`. The checklist of me goes like this - 

- [ ] Move `jQuery.holdReady()` from `src/core/ready.js` to `src/deprecated.js`
- [ ] Remove `jQuery.holdReady()` from `src/core/ready-no-deferred.js` & `test/data/jquery-1.9.1.js` 
- [ ] Open a migrate issue

**Comment by gibson042** [comment]
test/data/jquery-1.9.1.js should be left alone, as should the other test files. Other than that, :+1:.
