### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Tokimon** [jquery/jquery#3291]
### Description ###
When trying to get value by a number, it throws an error:

```javascript
$(1).val() // Throws error: Cannot read property 'toLowerCase' of undefined
```
Normally this should either return the number or nothing.
The error is thrown is because it assumes that the entry in the jQuery obejct array is a DOM element and tries to read `nodeName` of what is in this case a Number.

**File:** jquery/src/attributes/val.js
**Line:** 20

**Comment by mgol** [comment]
Passing a number to jQuery is not supported. For supported signatures please consult with the docs: https://api.jquery.com/jQuery/.
