### ISSUE TITLE
Error on Android native browser 4.x

### ISSUE THREAD

**Issue by kennyhk** [jquery/jquery#3293]
i am using Webpack + babel6, every thing is OK with jQuery v2.2.x; 

when update to jQuery v3.0.0 or v3.1.0, a browser run time error will throw on Android 4.x.
 I have no idea what is the detail of problem because it is hard t trace the compiled code on Android.

case 1 :  Android Simulator,  native browser / WebView  :

`Uncaught TypeError: Illegal constructor`

case 2:   Real device , native browser / WebView : 

`Uncaught ReferenceError: __WEBPACK_AMD_DEFINE_ARRAY__ is not defined`

case 3 :  Real device, Chrome standlone 

no error

**Comment by mgol** [comment]
This is not enough detail for us to work with, unfortunately. Could you
construct a minimal project example that exhibits the problem and share it?

-- 
Michał Gołębiowski

**Comment by kennyhk** [comment]
yes, but may be later.

**Comment by timmywil** [comment]
Thanks for opening an issue. Closing until we have more info.

**Comment by kennyhk** [comment]
minimal project example is here :
[jquery-test.zip](https://github.com/jquery/jquery/files/439017/jquery-test.zip)

please see read me for detail, thank you

**Comment by pwaldhauer** [comment]
Could someone reopen this issue? I have exactly the same problem.

**Comment by dmethvin** [comment]
This seems like a debugging-Webpack thing and not a jQuery bug, but someone with more of a stake in the outcome can diagnose and let us know if there is anything we need to change in the way we build jQuery. This may help:

https://webpack.github.io/docs/shimming-modules.html
