### ISSUE TITLE
Fix double occurence of "the" in "https://github.com/jquery/jquery/blob/1.4.4/jquery.js#L1870" file.

### ISSUE THREAD

**Issue by ashishdalvi** [jquery/jquery#3294]
### Description ###
Fix double occurence of "the" in below mentioned file.
[https://github.com/jquery/jquery/blob/1.4.4/jquery.js#L1870](https://github.com/jquery/jquery/blob/1.4.4/jquery.js#L1870)

### Link to test case ###
[https://github.com/jquery/jquery/blob/1.4.4/jquery.js#L1870](https://github.com/jquery/jquery/blob/1.4.4/jquery.js#L1870)

**Comment by mgol** [comment]
This is a very, very old version of jQuery. The issue template says:
> Note that we only can fix bugs in the latest (1.x, 2.x, 3.x) versions of jQuery.

Did it not display to you?

**Comment by ashishdalvi** [comment]
Sorry I missed that note. 

Thank you.
