### ISSUE TITLE
Use native mouseenter/mouseleave Events

### ISSUE THREAD

**Issue by HolgerJeromin** [jquery/jquery#3295]
Right now jQuery simulates the nice event [mouseleave](https://api.jquery.com/mouseenter/) by itself. 

This event is native since [2013 in chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=236215), [2012 in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=432698), bugfree in Safari since Version 8, since forever (Version 	5.5) in IE.

I think its time to reduce the code overhead by relying on the browsers.

**Comment by dmethvin** [comment]
I don't think we can use them because of the need to handle delegated events--mouseenter/mouseleave don't bubble. If you find an approach that does reduce code overhead we'll accept a PR though.

**Comment by mgol** [comment]
Yup, this reason is also clearly stated in the comment above the implementation: https://github.com/jquery/jquery/blob/3.1.0/src/event.js#L643-L645.

**Comment by mgol** [comment]
(for the same reason we shim `pointerenter` and `pointerleave`)
