### ISSUE TITLE
V3.1.0 ajax call with cache=false and prior '_' qparam in url is generating malformed url

### ISSUE THREAD

**Issue by mprobus** [jquery/jquery#3297]
### Description ###

Due to some code changes apparently introduced in ajax.js between 3.0.0-alpha1 and 3.0.0-beta1, calls to ajax with a url containing an anti-cache query param can get broken apart and reassembled into a malformed url.

`$.ajax({ url: '/myapp/?_=1472073761152&nextPage=2', cache: false})`

changes the url around before sending.  Older versions replaced the anti-cache param in place.  The newer versions remove the prior param and then tacks on a new param at the end.  The actual url requested in this case comes out as

` '/myapp/&nextPage=2?_=1472073761268'`

### Link to test case ###

[See jsfiddle example](https://jsfiddle.net/L14kr5sy/2/)

**Comment by dmethvin** [comment]
This was fixed by gh-3253. There's a spurious `&` but that shouldn't bother anything.
https://jsfiddle.net/L14kr5sy/4/

**Comment by mgol** [comment]
Since it's fixed I'm closing the issue.
