### ISSUE TITLE
End of Support enquiry

### ISSUE THREAD

**Issue by choonyong** [jquery/jquery#3301]
Hi,

Is there any end of support deadline for jQuery version 2.2.4?

Thanks,
Choon Yong

**Comment by mgol** [comment]
We're now focusing on jQuery 3.x. We'll only fix critical issues in jQuery 1.x/2.x, other issues are out of scope for those versions.

Generally, I wouldn't expect new releases of jQuery 1.x/2.x unless a really troublesome bug appears. Please consult [the upgrade guide](https://jquery.com/upgrade-guide/3.0/) and [jQuery Migrate](https://www.npmjs.com/package/jquery-migrate) to make upgrading to jQuery 3.x easier.

**Comment by choonyong** [comment]
Hi.

Notes with thanks.
