### ISSUE TITLE
$.ajax() cache parameter substitution works incorrectly

### ISSUE THREAD

**Issue by ssg** [jquery/jquery#3303]
jQuery 3.1.0:

    $.ajax("http://testurl?_=<randomnumber1>&p=2", { cache: false })

actually requests:

    http://testurl&p=2?_=<randomnumber2>

but should request:

    http://testurl?p=2&_=<randomnumber2>

I'll add a test case later if needed.

**Comment by dmethvin** [comment]
This sounds like gh-3229 and should be fixed in version 3.1.1 which will be out soon. You can check the [git builds](http://code.jquery.com/jquery/) to see if it's fixed for a specific case.

**Comment by ssg** [comment]
Thanks! I had already checked open issues but didn't see that one.
