### ISSUE TITLE
For null/undefined item in $.each() callback this=window

### ISSUE THREAD

**Issue by alecpl** [jquery/jquery#3309]
...when using version of callback function without arguments. It looks to me like a bug.

Documentation says: "The value can also be accessed through the this keyword, but Javascript will always wrap the this value as an Object even if it is a simple string or number value."

https://jsfiddle.net/8zy75pxr/

Tested with Firefox and Chromium.

**Comment by gibson042** [comment]
That's just an inherit aspect of legacy Javascript function invocation. Observe what happens in strict mode: https://jsfiddle.net/8zy75pxr/1/
