### ISSUE TITLE
JQuery autocomplete performance problem

### ISSUE THREAD

**Issue by WickedDevils** [jquery/jquery#3310]
I used the code from site http://jqueryui.com/autocomplete/#combobox and noticed a significant performance issue on my page.  My list has ~3000 options in the combobox.  I noticed that most of the time it was stuck in the in the jquery js file within this set of code:

`	indexOf = function( list, elem ) {
		var i = 0,
			len = list.length;
		for ( ; i < len; i++ ) {
			if ( list[i] === elem ) {
				return i;
			}
		}
		return -1;
	},`

Even though my list object was only expected to be ~3000 rows, it was actually significantly higher.  Here is my stacktrace:

`indexOf (jquery-1.12.4.js:644)
hasDuplicate (jquery-1.12.4.js:1375)
Sizzle.uniqueSort (jquery-1.12.4.js:1518)
processClassString (jquery-ui.js:510)
_classes (jquery-ui.js:523)
_toggleClass (jquery-ui.js:549)
_addClass (jquery-ui.js:537)
refresh (jquery-ui.js:5249)
(anonymous function) (jquery-ui.js:144)
_suggest (jquery-ui.js:6100)
(anonymous function) (jquery-ui.js:144)
__response (jquery-ui.js:6043)
(anonymous function) (jquery-ui.js:144)
_superApply (jquery-ui.js:133)
__response (jquery-ui.js:6229)
(anonymous function) (jquery-ui.js:144)
(anonymous function) (jquery-ui.js:6027)
proxy (jquery-1.12.4.js:529)
_source (combobox.html:108)
(anonymous function) (jquery-ui.js:144)
proxy (jquery-1.12.4.js:529)
_search (jquery-ui.js:6019)
(anonymous function) (jquery-ui.js:144)
search (jquery-ui.js:6011)
(anonymous function) (jquery-ui.js:144)
(anonymous function) (jquery-ui.js:5992)
handlerProxy (jquery-ui.js:621)
`

In processClassString it does line:

`current = $( $.unique( current.get().concat( options.element.get() ) ) );`

The current list is my 3000 or so rows initially, and then it adds the elements back into that list making it roughly 6000 rows.  Depending on how the user is interacting with the page (clicking the dropdown icon multiple times, typing into the textbox for the filter and then deleting the text, etc), it will keep adding to itself.  At one point I had almost 200,000 rows in my 'list' variable.

I was able to reproduce this by stepping through the code using Chrome developer tools on http://jqueryui.com/autocomplete/#combobox .

**Comment by gibson042** [comment]
This is the jQuery core repository; issues with jQuery UI should be reported at [https://bugs.jqueryui.com/](https://bugs.jqueryui.com/).
