### ISSUE TITLE
Why dataFilter() of $.ajax() can't be applied to non-XHR request ?

### ISSUE THREAD

**Issue by TechQuery** [jquery/jquery#3311]
In many cases, especially **SPA development**, We need to preprocess **Data Structure of Response JSON**, such as:

```JavaScript
{
    code:       0,     //  > 0 while error occurs
    message:    'Success',
    data:       { }    //  Useful Data for Business Code
 }
```
Moreover, many **Open HTTP API** have only **JSONP** to support Cross Domain...

---

There's [a solution](http://stackoverflow.com/a/9478670) on the Internet, but I don't agree with it.

Because, I want to **Filter the Data**, not *Convert the Data from one Data-Type to another*, it'll be the same type forever~

---

So, I'm so **Confused** about [this four-year old ticket](https://bugs.jquery.com/ticket/11967#comment:7)...

**Comment by timmywil** [comment]
Without knowing more of the specifics, I think the solution you found is the right one. A custom convertor gives you fine-grained control over how your data is parsed.
