### ISSUE TITLE
Can't set Breakpoint for $.fn.load() script directly in Web Debugger

### ISSUE THREAD

**Issue by TechQuery** [jquery/jquery#3312]
`debugger;` statement may be kind of solution, but it fails in `require.js` and old IE, let alone how boring to write it anywhere I want to stop... ([Related Issue](//git.oschina.net/Tech_Query/EasyWebApp/issues/11))

So, we need a `<script src="" />` for **AJAX HTML Loading**, no matter that source of the script is same or cross domain, `$.fn.load()` will have the same behavior.

---

In the end, I agree with the opinion of @rwaldron :
 - https://github.com/jquery/jquery/pull/1051/files#r3664819
 - https://github.com/jquery/jquery/pull/1051/files#r3665451

If there are problems related with "Synchronous Script" in **jQuery UI**, I think we need _Event Callback_ or _Promise Object_ to resolve them.

**Comment by timmywil** [comment]
Thanks for opening an issue! The pull comments you linked from @rwaldron were more about adding "private, but not really" methods to jQuery. There is still a difference between a synchronous ajax request and adding a script tag to the DOM. This is a bug in the developer tools you are using if there's no way to add a breakpoint.

**Comment by TechQuery** [comment]
@timmywil 

I can set Breakpoints in all kinds of browsers with my `$.fn.load()` implement.

**Comment by timmywil** [comment]
@TechQuery It seems like the developer tools prefer a script tag, but my comment still stands.
