### ISSUE TITLE
Selecting elements with a list of IDs is orders of magnitude slower than selecting them individually

### ISSUE THREAD

**Issue by JoolsCaesar** [jquery/jquery#3314]
### Description ###
There isn't a significant benefit to using `$(document.getElementById('firstID'))` over `$('#firstID')`, but using `$('#firstID,#secondID')` is several thousand times slower than `$([document.getElementById('firstID'), document.getElementById('firstID')]); `
This affects all the browsers I've tested: Chrome, Firefox, IE11, Edge

### Link to test case ###
https://www.measurethat.net/Benchmarks/Show/129/3/element-by-id-fetching-javascript-vs-selectors
See the final test case '2 divs with single jquery selector'.

**Comment by mgol** [comment]
The thing is `$('#firstID,#secondID')` is not equivalent to `$([document.getElementById('firstID'), document.getElementById('firstID')])`, it runs via `querySelectorAll`. The non-trivial part is that you're passing a single string with a comma; we'd need to tokenize it first which is non-trivial work. This will always be slower.

If you want to have an equivalent of running `getElementById` twice, you'll have to write:
```js
$('#firstID').add('#secondID');
```

**Comment by JoolsCaesar** [comment]
I'd always expected it to be slower, I was just surprised to see that it's two thousand times slower. I guess it's more of a problem with the browser implementation of `querySelectorAll` than jQuery. I'm quite surprised that they don't optimise for this. 

I knocked together an over-simplified parser (splitting on commas, checking IDs) and it came out a bit slower than $().add(). I'll probably stick to the array notation though, as I have quite a few IDs to deal with and it seems a fair bit faster than creating a jQuery object for each one.
https://www.measurethat.net/Benchmarks/Show/164/17/queryselectorall-vs-simple-parse-vs-individual-selector

**Comment by mgol** [comment]
Big difference in performance doesn't always mean the slower solution is the worse one. It only matters if it's fast enough. I have to admit ~300 ops/s seems slow. On the other hand, do you really have 100,000 divs on your page? That seems like a lot, even Gmail has only about 5000 of them.

**Comment by JoolsCaesar** [comment]
There are edge cases where it's currently possible.
```
>$('*')
jquery-3.0.0.js:2676 Uncaught RangeError: Maximum call stack size exceeded(…)
>$(document.querySelectorAll('*'))
jQuery.fn.init[77406]
```
Reducing the potential size of the DOM is certainly high on the to-do list, but it is also non-trivial (there are already optimisations to bring that number down and out of the millions), so we're coming at it from as many angles as possible.

**Comment by dmethvin** [comment]
It sounds like this page is into a super edgy territory if it has hundreds of thousands of elements.

> `$('#firstID,#secondID')`

This creates a jQuery set that guarantees the elements are in document order. If `#secondID` comes before `#firstID` in the document, they will appear in that order in the collection. The sort operation might be expensive.

> `$([document.getElementById('firstID'), document.getElementById('firstID')]);`

This creates a jQuery set out of whatever you give it with very little verification and no sorting. (They might not even be DOM elements.) Cheap, but it provides no guarantees about the set.

**Comment by JoolsCaesar** [comment]
General usage is more like 5-10,000, but we're looking at how well we can replicate it within a same page, without using iframes, so the numbers can get pretty extreme. iframes haven't been ruled out, but they are on the list of "avoid if possible".

Thanks for the extra info! Good to know about the sorting, but it shouldn't be an issue in our case. Generally speaking if we know the ID, we know the position and node type etc. I certainly have no intention of monkey patching jquery's default behaviour or anything, as that would be, as you said, cheap but very dangerous when dealing with external code and elements. I just aim to be mindful of it in the areas where we select multiple IDed elements, because there may be a not insignificant benefit to using an alternative method.
