### ISSUE TITLE
ajax: REST responses problem with json and empty responses (like 201)

### ISSUE THREAD

**Issue by extempl** [jquery/jquery#3317]
So, the problem is, when `contentType` set to `json` and there is `201 empty` response (without content-type) I getting response in the errorHandler due to fail JSON parsing. But I know and understand, that this is, actually, success response. And it is correct. 
So I need something like `contentType: 'json any'` (tried to achieve so with `accepts: {any: '*/*'}` key with no luck) so if json parse fails it will return empty success response. 
Any thoughts? Maybe it is possible to workaround (without checking `xhr.status` to be correct (200<=x<400) in error handler (wtf?)) and, still, get correct-typed response (in my case, if `contentType` is not specified I getting xml by default, but 201 is success then. Not the solution).

**Comment by dmethvin** [comment]
If you get varied content type, as you do here (sometimes JSON, sometimes nothing) then set datatype to `text` and parse the response yourself based on whatever criteria you'd like including the HTTP response code or the appearance of the text. 

This isn't a bug report so it would be better to ask these questions on StackOverflow or the jQuery Forum.
