### ISSUE TITLE
$([]).toggle() fails when an array of elements is passed

### ISSUE THREAD

**Issue by brianfreud** [jquery/jquery#3319]
I am seeing this with Chrome on Linux for every version of jQuery at least through 3.1.0.

I've received three different errors from this same pattern, all of which trace to the same cause:

Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

Uncaught TypeError: Cannot read property 'display' of undefined

Uncaught TypeError: Cannot read property 'defaultView' of undefined

Directly using show() and hide() works fine.  But when you try to do $([]).toggle(), you run into these errors.  

https://jsfiddle.net/odrmhh4y/1/

**Comment by dmethvin** [comment]
To toggle the visibility we need to determine whether an element is currently visible or not so we can change it to the opposite.

To determine whether an element is currently visible, we need to consider the stylesheets of the document the element is contained in.

Those elements are not in a document. 

What result do you want to achieve?

**Comment by brianfreud** [comment]
The element in a fragment still has an inherent visibility, wherein were it to be appended to the body, and nothing existing in the body/etc were to be otherwise changing the visibility of that element, then that element either would, or would not be, visible.

In other words:

$('<span>')
.text('I am visible')
.hide()
.text('and now I'm not.');

In any case, that seems an already decided question:

var $foo = $('<div>');
$foo.hide();
$foo.show();
$foo.toggle();
...all work, no errors.

Problem is:
.hide(), .show(), and all three .toggle() work when we're not dealing with an array of jQuery objects.
.hide() and .show() both work on an array of passed elements... but .toggle() throws an error:

var $foo = $('<div>');
$([$foo]).hide(); // no errors, works
$([$foo]).show(); // no errors, works
$([$foo]).toggle(); // ERROR.

**Comment by dmethvin** [comment]
Oh, I missed that it was an array of *jQuery* objects. That's not a supported or documented API signature. If it's an array it should contain DOM elements, there is no checking done on the contents of the array to ensure that each element is valid or convert its type.
