### ISSUE TITLE
Uncaught RangeError: Maxium Call Stack Size Exceeded

### ISSUE THREAD

**Issue by wpgbrown** [jquery/jquery#3320]
I encountered a jquery error when I was writing some code using the children() and arguments, then firing an event on that selected element, but if I use find() instead of children(), it works the same as children(). I found out that on Chrome 53.0.2785.113 this error occurs, also in Internet Explorer 11.494.10586.0 with out of stack space, in Firefox, the error changes to, to 'too much recursion' and the call stack seems to go on and on, repeating itself. And also in Edge 25.10586.0.0 and EdgeHTML of 13.10586 with 'out of stack space' error. All of these browsers are on windows and I cannot test Linux or Mac (and iOS) as I do not have a Mac or machine running Linux

### Link to test case ###

The Link is: [https://jsfiddle.net/92j49726/](https://jsfiddle.net/92j49726/)

 Below is the full stack trace on Firefox:

too much recursion
ArraySpeciesCreate()
self-hosted
concat()
self-hosted
.map()
jquery.min.js:2
r.fn[a]()
jquery.min.js:2
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()
jquery.min.js:4
.trigger/<()
jquery.min.js:4
.each()
jquery.min.js:2
r.prototype.each()
jquery.min.js:2
.trigger()
jquery.min.js:4
window.onload/</<()
show:53
r.event.dispatch()
jquery.min.js:3
r.event.add/q.handle()
jquery.min.js:3
.trigger()

**Comment by dmethvin** [comment]
Please ask for help on the jQuery Forum or StackOverflow.

**Comment by A** [comment]
+1 from me. I guess you should take a look on it, because it happens not at one site but on many
