### ISSUE TITLE
jQuery IntelliSense integration in Visual Studio 2015: Why do I need to reference jquery.js but not jquery.intellisense.js?

### ISSUE THREAD

**Issue by SetTrend** [jquery/jquery#3323]
I'm not sure if this is the right place to ask my question, but as the `jquery-*.intellisense.js` file is getting published along with jQuery someone here may know the answer:

In this [ASP.NET forum thread](https://social.msdn.microsoft.com/Forums/vstudio/en-US/67069b51-78df-4308-9518-cdac58619d4a/vs20153-how-can-i-get-javascript-intellisense) I am wondering why I need to reference `jquery-*.js` although it doesn't contain any IntelliSense information at all. But when I'm referencing `jquery-*.intellisense.js`, however, I don't get any IntelliSense whatsoever.

What mechanism is used here? Why do I need to reference `jquery-*.js` when the information is stored in another file? Where is this behaviour documented? What's the reasoning behind it?

**Comment by mgol** [comment]
> I'm not sure if this is the right place to ask my question, but as the `jquery-*.intellisense.js` file is getting published along with jQuery

Where is that coming from? We don't publish such a file in any package.

**Comment by SetTrend** [comment]
It's included with the [jQuery NuGet package](https://www.nuget.org/packages/jQuery/).

**Comment by mgol** [comment]
We only maintain the [npm](https://www.npmjs.com/package/jquery) and bower packages for `jquery`. You should report issues with the NuGet package to its maintainers.
