### ISSUE TITLE
error parse String object instance to html

### ISSUE THREAD

**Issue by DragorWW** [jquery/jquery#3324]
### Description ###
Functionl htlm to dom not work with String object, only work with string literal.

version: 2.x, 3.x;
test Browser: last Google Chrome;

expample:
```
// string literal:
console.log($.('<div></div>')); // [<div></div>]
```
```
// string object:
console.log($.(new String('<div></div>'))); // ["<", "d", "i", "v", ">", "<", "/", "d", "i", "v", ">"]
```
### Link to test case ###
https://jsfiddle.net/7v0dt0h6/2/

**Comment by gibson042** [comment]
This is intentional:
* https://bugs.jquery.com/ticket/4533#comment:2
* https://bugs.jquery.com/ticket/5319
* https://bugs.jquery.com/ticket/12538#comment:4
* https://bugs.jquery.com/ticket/12605#comment:2

However, it's definitely not well-documented. I'll open a ticket.
