### ISSUE TITLE
Deferred "then" not firing immediately on already resolved promise.

### ISSUE THREAD

**Issue by MerickOWA** [jquery/jquery#3325]
### Description ###
Browser: Chrome 53.0.2785.116 m
Version: JQuery 3.1.0

When calling `.done(...)` callback on a $.Deferred promise which is already resolved, the callback is invoked immediately as expected.

When calling `.then(...)` on an already resolved $.Deferred promise, the callback is **not** immediately invoked as expected.

It appears to actually be delayed until some later point via [setTimeout call here](https://github.com/jquery/jquery/blob/master/src/deferred.js#L228).

### Link to test case ###

https://jsfiddle.net/b23rcc92/

Expected output:
> Done callback
> Then callback
> All done

Actual output:
> Done callback
> All done
> Then callback

**Comment by jbedard** [comment]
That is part of the definition of the `then` method: https://promisesaplus.com/#point-34

**Comment by dmethvin** [comment]
If you don't want the standard behavior you can use `.done()`. This is covered in the upgrade guide: 
https://jquery.com/upgrade-guide/3.0/#deferred

**Comment by MerickOWA** [comment]
Thanks, my fault, I completely missed this change.
