### ISSUE TITLE
when to promote a ajax to jsonp request

### ISSUE THREAD

**Issue by pslean** [jquery/jquery#3328]
$.ajax({
	type: 'put',
	url: '/test',
	data: JSON.stringify({
		desc: "ls??",
		id: 698,
		text: "flow8"
	}),
	headers: {
		"Content-Type": 'application/json',
		"User-Id": 4,
		"AuthDate": 1474730987738,
		"Authorization": "BCDAE 7ef63480e6e39d91011a:Ms8LZlGJq1/OS7Is1Swg79plppg="
	},
	dataType: 'json'
}).done(function(result) {
	console.log(result);
});
Like above, when I setting the "Content-Type": "application/json" in the headers, but not setting contentType to "application/json", the ajax is promoted to jsonp request.

**Comment by timmywil** [comment]
Thanks for opening an issue! However, before we can accept the PR, we need a test case that demonstrates the problem.

**Comment by pslean** [comment]
@timmywil What info do you need to be provided?

**Comment by timmywil** [comment]
@pslean We need a way to reproduce the problem in live code with as little code as possible. This is usually done with jsbin.com or jsfiddle.net. If you prefer to write the test in jQuery's ajax tests, that would also work.

**Comment by timmywil** [comment]
Will reopen when we have a test case. Thanks!

**Comment by pslean** [comment]
@timmywil Sorry, I have been very busy recently. The example you need is as below.
1. This is the problem, you can see the error in the consol of chrome. The request is promoted to jsonp, but it is not. Link: [js bin](http://jsbin.com/mejarajuro/edit?html,js,console)
2. Then when you add (contentType: 'application/json') to the ajax option, you can remove the annotation in the js bin, the you can get response data from the post api. 
Please help me reopen the issue and verify it.

**Comment by mgol** [comment]
@pslean The URL you're using there is in your private network so we can't see the result of this fiddle. Use https://httpbin.org/ to mock backend requests for test purposes.

**Comment by pslean** [comment]
@mgol I have changed the js bin link to the newest. Please check.

**Comment by pslean** [comment]
@timmywil @mgol [http://jsbin.com/mohubalozu/edit?html,js,console](http://jsbin.com/mohubalozu/edit?html,js,console)

**Comment by pslean** [comment]
@mgol @timmywil help me.
