### ISSUE TITLE
Can't Get User Input Content with .text()

### ISSUE THREAD

**Issue by HechenHu** [jquery/jquery#3330]
When I'm trying to get user input content,I use **.text()** but unable to do so. But with html native **document.getElementById().value**,the code works.

>$('#Submit').on('click',
> 	function()
> 	{
>	//var inputText = $('#UserInput').value();
>	//$('#Output').text(inputText);
>	$('#Output').text(document.getElementById('UserInput').value);
>	}
>	);

'**UserInput**' is the id of \<input\>.'**Output**' is the id of \<p\>.'**Submit**' is the id of my submit button(using **semantic-ui**) .
I also try replacing the **3.1.0** version of **jquery.min.js** with **2.1.1** and that works. I guess the issue only exists in version  **3.1.0**.

**Comment by HechenHu** [comment]
Update: It still not working when I try **html native \<input\> tag** instead of **\<div class="ui input"\>** in **Semantic-ui**.

**Comment by dmethvin** [comment]
Please ask for help on StackOverflow.
