### ISSUE TITLE
Getting element width after applying a class returns it's width before font-family is applied

### ISSUE THREAD

**Issue by DaGLiMiOuX** [jquery/jquery#3334]
## Description

I have an anchor/button that has an onclick function to add elements into a webpage. In this case, I'm adding buttons that you can drag and resize with jQuery UI.

I've added this function into jQuery to retrieve the element minimum width, which is its text width:
```
$.fn.textWidth = function(classname) {
    if (!$.fn.textWidth.fakeElement) {
        $.fn.textWidth.fakeElement = $(document.createElement('span'));
    }
    $.fn.textWidth.fakeElement.addClass(classname || this.attr('class') || '').html(document.createTextNode(this.val() || this.text())).css({
        position: 'absolute',
        width: 'auto',
        height: 'auto',
        boxSizing: 'content-box',
        whiteSpace: 'nowrap'
    }).appendTo(document.body);
    var width = $.fn.textWidth.fakeElement[0].getBoundingClientRect().width;
    $.fn.textWidth.fakeElement.removeClass().remove();
    return width;
};
```
Now I should be able to put the minimum width for jQuery UI resizable, but actually I'm getting a wrong width.

After a couple of days investigating why it is giving different values, I've found that this happens because the **CLASS** attribute that I've defined for buttons has a config like `color: rgba(169,170,165,1); font: normal 22.22222328186035px/1.3em open sans,sans-serif;` and when I get the text width it retrieves the element width **BEFORE** the `font-family` is applied.

With the class configuration I've mentioned before, which is the main configurations for my buttons, I get in console a width value of `58.0625px` and a width value of `62.71875px` if I add a timeout function  with 0s delay, before removing the element. Font families are included from external sources and they are working when the function is called on runtime (when clicking the "Add" button), so the problem is not that the page is not loaded or font families weren't loaded.

For standard button, without changing its class name, the expected/correct value is the second one (`62.71875px`). I hope it is clear enough to understand.

Thanks in advance.

Best regards.

## Additional info

- Version: jQuery 1.11.1
- Agent: Chrome 53.02785.116m

**Comment by timmywil** [comment]
Thanks for opening an issue! However, I'm not sure this is an issue with jQuery. Please provide a reduced test case so we can determine any issue in jQuery and we can reopen.

**Comment by DaGLiMiOuX** [comment]
Ye. It's something related to CSS.

In jsFiddle works perfectly, but I don't know why in our project it's giving 58px and then 62px. I'm going to be crazy with this, because I'm doing some breakpoints that shows when it has `width: 58px` and after  execution it shows `width: 62px`, but CSS properties are exactly the same. I don't know what's going on.

Anyway, sorry for posting a wrong issue
