### ISSUE TITLE
webpack_amd_define_arr is not defined

### ISSUE THREAD

**Issue by fengxinming** [jquery/jquery#3335]
use webpack to build javascripts in my project, open local website on Android's brower, it open a alert about "webpack_amd_define_arr is not defined", jquery3.0 is applied on my local weisite

**Comment by timmywil** [comment]
Thanks for opening an issue. However, you can find support on the [forums](http://forum.jquery.com/), the #jquery irc channel, or in the [jquery gitter channel](https://gitter.im/jquery/jquery).
