### ISSUE TITLE
IMPORTANT CORE BUGFIX SEE BELOW - TAKE IN NEW VERSION PLEASE. 

### ISSUE THREAD

**Issue by mindcatch-com** [jquery/jquery#3336]
`
/**
 * Load a url into a page
 */
jQuery.fn.load = function( url, params, callback ) 
{
	var selector, type, response, self = this;

	// BUGFIX A. MEHRRATH 2016-09
	var off = -1;
	if (typeof url === 'string') {
		var off = url.indexOf( " " );
	} 
`

**Comment by dmethvin** [comment]
The [documentation](http://api.jquery.com/load/) says `url` should be a string so here is no need to check.
