### ISSUE TITLE
Unresponsiveness in jquery-1.11.2.js

### ISSUE THREAD

**Issue by sanchigirotra10** [jquery/jquery#3337]
I am using jquery-1.11.2.js in our application and its in some pages giving unresponsiveness. Refer below Screenshot :-
![image](https://cloud.githubusercontent.com/assets/3404429/18911914/33b3f18a-859d-11e6-8559-c2f396643ec3.png)
****

Please suoggest how to fix this issue.

**Comment by dmethvin** [comment]
Use the browser's dev tools to determine where it is spending the time, and ask for help on StackOverflow.
