### ISSUE TITLE
Easy post form data

### ISSUE THREAD

**Issue by dbol55** [jquery/jquery#3339]
As far as I am concern there is no easy way of posting form data with Jquery? But I would like to have a function for this such as:

$.easypost('url', { inp1 : "", inp2: ""});

And this is not a AJAX call with callback, it should work just as a traditional form submit, instead of have to write my html markup.

**Comment by timmywil** [comment]
Thanks for opening an issue. Form data can be posted in several ways, but if ajax is not an option, you have to have an HTML form to post (even if created with JS). Creating one for you is outside the purview of jQuery. It could be a plugin, but there are so many options when creating a form that it's probably best to write it yourself.
