### ISSUE TITLE
Tag script is double added in the head context

### ISSUE THREAD

**Issue by EldegarThundertale** [jquery/jquery#3340]
I've notice, a problem with the Module jQuery for NodeJS. It doubles the tag script when I add a new element script in the head context.

This is the [function](http://prntscr.com/cnr9vj) that adds script element to head, and this the [test code](http://prntscr.com/cnrft0).

And this is the [output](http://prntscr.com/cnrfei) of the generated page.

**Comment by timmywil** [comment]
Thanks for opening an issue, but it works for me. http://jsbin.com/zikezu/edit?html,js,output

My guess is that your function is getting called twice somehow. Please refer to StackOverflow, the [jQuery forums](http://forum.jquery.com/), or the #jquery irc channel for support.
