### ISSUE TITLE
[IOS 10 / Desktop/Mobile Safari] - scrollTop broken

### ISSUE THREAD

**Issue by Wade-BuildOtto** [jquery/jquery#3341]
This had been working on previous versions but I noticed that when I updated to IOS 10 it stopped working.

[Update]
I checked it on Chrome and Safari 10 on the desktop as well it works fine on Chrome but not Safari desktop as well as Safari mobile.

$('.container').scrollTop(100);

The regular scrolling with touch still works. 
css
  overflow: scroll;
  -webkit-overflow-scrolling: touch;

**Comment by dmethvin** [comment]
Can you provide some more information?

**Comment by Wade-BuildOtto** [comment]
If you div with overflow-y:auto and using something like touchSwipe to allow touch scrolling of that div then you are not longer able to adjust the scroll position by using scrollTop().

I estimate that mobile safari changed its api to affect scrolling of objects to allow for new things like 3d touch maybe? But I would have to dig further.

**Comment by Wade-BuildOtto** [comment]
I previously had position:relative; on the scroll container which was working fine, but now it mandatory to have position:fixed; in order to allow overflow-scrolling to work.

**Comment by eb-jennz0r** [comment]
I'm having a similar issue. scrollTop of the document, window, html, or body all produce a result of 0. I'm unable to find a work around.
