### ISSUE TITLE
Polymer build complain when uglifying intro.js

### ISSUE THREAD

**Issue by miguelamello** [jquery/jquery#3342]
warn:    Unable to uglify file /home/miguel/github/diretonamao/portal/www/bower_components/jquery/src/intro.js
debug:
{ message: 'Unexpected token: eof (undefined)',
  filename: 0,
  line: 45,
  col: 0,
  pos: 1376,
  stack:}

**Comment by dmethvin** [comment]
Not sure why you're trying to run a single file through uglify. Use jquery's build script.

**Comment by miguelamello** [comment]
Read carefully this issue title. Cheers.

**Comment by mgol** [comment]
If your Polymer setup is blindly uglifying all the JS files in its dependencies, regardless of them being actually used or not, then either your setup or Polymer have a bug here, not jQuery.

Also, note that we've been receiving bug reports like that for some time so we've changed that and jQuery 3 doesn't have the `intro.js` & `outro.js` files but a correct JavaScript [`wrapper.js` file](https://github.com/jquery/jquery/blob/3.1.1/src/wrapper.js). Upgrading to jQuery 3 should resolve your issue. then but I still recommend you to fix your build to not touch unrelated files.

**Comment by miguelamello** [comment]
Hi mgol,

Thank you for replying. I see, but I could not find a entry in polymer.json to exclude JS in dependencies, indeed. I will search more. I will upgrade to JQuery 3, thank you. 

Cheers.
