### ISSUE TITLE
Polymer build complain when uglifying outro.js

### ISSUE THREAD

**Issue by miguelamello** [jquery/jquery#3343]
warn:    Unable to uglify file /home/miguel/github/diretonamao/portal/www/bower_components/jquery/src/outro.js
debug:
{ message: '\'return\' outside of function',
  filename: 0,
  line: 1,
  col: 7,
  pos: 7,
  stack:}

**Comment by dmethvin** [comment]
Not sure why you're trying to run a single file through uglify. Use jquery's build script.

**Comment by miguelamello** [comment]
Well, I'm running "polymer build"... I'm just trying to help. Cheers.
