### ISSUE TITLE
jQuery 3.x ajax .load() function breaks existing code

### ISSUE THREAD

**Issue by tangrl** [jquery/jquery#3346]
We have some code calling ajax .load() function to update web pages, with the following signature:

.load( url , data , complete  )

Before jQuery version 3.0, when the callback function (complete) is called, the web page is guaranteed updated and all html elements are ready to be processed/updated in the callback function.

After version 3.0, we are getting "null jQuery object" error because the callback function is always called before the html elements are created.

We have two workarounds:
1. Delay 1 or 2 milliseconds in the callback function before do any work.
2. Cal setInterval and check the availability of certain html elements before do any work.

Both are not very satisfactory to me and we have so many places to change the code. Right now we have to stay on jQuery 2.2.4.

Can someone suggest a better/cleaner solution?

Thanks!

Richard

**Comment by dmethvin** [comment]
Can you post an example that shows the problem? As you might guess, it's very difficult for us to diagnose the problem with just the description you've provided. I'm not even sure what is being reported here, the error message "null jQuery object" isn't the *literal* error is it?

**Comment by sessionliang** [comment]
I get this error too.
![qq 20161102110424](https://cloud.githubusercontent.com/assets/12078007/19915290/4a683aca-a0ec-11e6-81b1-bff591cd92b3.png)

**Comment by mgol** [comment]
@sessionliang You're not using the AJAX `load` but the load event which we removed in 3.0 precisely because people were confusing the two. Please read the upgrade guide, it contains all that info (this one is described at https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed).

**Comment by mgol** [comment]
Since we haven't got a specific example when it breaks, I'm going to close the issue. @tangrl if you construct such a minimal example, post it here & we can reopen.
