### ISSUE TITLE
Is it possible to support native custom event handlers?

### ISSUE THREAD

**Issue by kt3k** [jquery/jquery#3347]
### Description ###

jQuery doesn't seem supporting native custom event handlers. For example, in the following code, the event handler doesn't run:

```
document.body.addEventListener('custom-event', function () { console.log('native custom-event handler'); })
$(document.body).trigger('custom-event') // This doesn't fire the above handler.
```

The above behavior seems a bit strange to me because if I attach to the event like `$('body').on('custom-event', ...)`, then it just works.

I'm curious whether it's possible for jquery to support the above situation.

### Link to test case ###

https://jsfiddle.net/kt3k/og4cu6sm/

**Comment by dmethvin** [comment]
Yes, jQuery doesn't trigger native events, only the ones that it tracks. Native events don't provide a way to determine when they're attached.

**Comment by dmethvin** [comment]
For more discussion see gh-2476

**Comment by kt3k** [comment]
Thanks for clarification!
