### ISSUE TITLE
ajax.load running inline javascript twice

### ISSUE THREAD

**Issue by JamesBradley86** [jquery/jquery#3349]
### Description ###
This is a repeat of this bug from four years ago, marked as "wont fix" presumably because it was viewed as an edge case, but I'm seeing the same thing happen in 2016 on the latest version of Chrome.

 https://bugs.jquery.com/ticket/13051 

Loading a html snippet via ajax.load will run any inline javascript (in the snippet) twice, and will also load and run any linked javascript files (from the snippet) twice.

**Comment by dmethvin** [comment]
I doubt it is the exact same bug since that was an IE bug, although it might exhibit similar behavior. Are you saying the test case in that ticket exhibits the same behavior in modern Chrome?

**Comment by JamesBradley86** [comment]
Not sure - I don't think their test case is showing the same behaviour, in chrome. We're going to just move the javascript out of the included snippet as it's probably not best practice, anyway!

**Comment by timmywil** [comment]
Thanks for opening an issue. Without a test case to investigate, it would be hard to pin down an issue inside jQuery. We can reopen if such a test case is produced.
