### ISSUE TITLE
Separate camelCasing logic between Data & CSS

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#3355]
### Description
`jQuery.camelCase` contains a CSS-only quirk that replaces `-ms-` to `ms-`. This quirk is needed only in the CSS module and yet the data module uses it as well, making `elem.data('-moz-a', 'b')` create an `MozA` key and `elem.data('-ms-a', 'b')` - an `msA` key. Those use cases should be separated.

Due to needed breaking changes this is 4.0 material.

P.S. It would be best to resolve #3384 first.

EDIT: Description edited as part of this ticket has been separated to #3384.

### Link to test case
https://jsfiddle.net/zmfvwak7/1/

**Comment by markelog** [comment]
This is a core method, if it requires changes in others places you don't really need other labels to it, I would argue that would be more confusing and unconventional

**Comment by markelog** [comment]
Also, did you create corresponding issues in docs and migrate repos?

**Comment by mgol** [comment]
@markelog This issue is not only about hiding jQuery.camelCase but also about fixes in camelCase handling in the data module so IMO it makes sense to double-label. Maybe the Effects label is not needed here.

**Comment by mgol** [comment]
I haven't reported those issues yet. I'll do it later.

**Comment by markelog** [comment]
Sounds like two issues to me – one for hiding another to fix... aaaam something, so i'm like not sure what you want to fix

**Comment by markelog** [comment]
Another argument for dividing those issue is that it would be easier for external contributors, so they could handle a hiding thing hence my reminder about creating other issues, whereas "fixing"... something doesn't have a really clear sequence of actions, at least to me

**Comment by mgol** [comment]
Sure, I can separate them. Just not right now. ;)

**Comment by markelog** [comment]
cool, thanks

**Comment by mgol** [comment]
@markelog Done.

**Comment by mgol** [comment]
PR: #4365
