### ISSUE TITLE
.on("hover") stop working after version 1.7

### ISSUE THREAD

**Issue by nkarmi** [jquery/jquery#3357]

**Comment by dmethvin** [comment]
https://jquery.com/upgrade-guide/1.9/#quot-hover-quot-pseudo-event

**Comment by mgol** [comment]
@dmethvin BTW, I'm not seeing the note at https://api.jquery.com/hover/. Are we missing docs updates here?

**Comment by dmethvin** [comment]
It's only the "hover" pseudo-event not the .hover() shorthand. I don't think it was ever formally documented, just mentioned in a blog post.

**Comment by dmethvin** [comment]
BTW the .hover() method is being deprecated as of 3.2, its docs are covered by https://github.com/jquery/api.jquery.com/issues/972 though.

**Comment by mgol** [comment]
Ah, I collapsed those two things in my mind, my bad.
