### ISSUE TITLE
When to promote a ajax to jsonp request

### ISSUE THREAD

**Issue by pslean** [jquery/jquery#3361]
$.ajax({
type: 'put',
url: '/test',
data: JSON.stringify({
desc: "ls??",
id: 698,
text: "flow8"
}),
headers: {
"Content-Type": 'application/json',
"User-Id": 4,
"AuthDate": 1474730987738,
"Authorization": "BCDAE 7ef63480e6e39d91011a:Ms8LZlGJq1/OS7Is1Swg79plppg="
},
dataType: 'json'
}).done(function(result) {
console.log(result);
});
Like above, when I setting the "Content-Type": "application/json" in the headers, but not setting contentType to "application/json", the ajax is promoted to jsonp request.
js bin: [http://jsbin.com/mohubalozu/edit?html,js,console](http://jsbin.com/mohubalozu/edit?html,js,console)

**Comment by timmywil** [comment]
Thanks for opening an issue. We plan on removing the jsonp promotion in 4.0. See https://github.com/jquery/jquery/issues/3376
