### ISSUE TITLE
Password Input Values

### ISSUE THREAD

**Issue by juninhodeluca** [jquery/jquery#3363]
### Description ###
Is this the right behavior for input type password?
```
<input type="password" id="password" />
<input type="text" id="showPassword" />

    $('#password').change(function(e){
        $('#showPassword').val($('#password').val());
    });
```
I mean... I can't copy and past from inputs of type password into a notepad, but jQuery can show it.
I know about security issues in this case, but the point is... should jQuery handle password values?

Sorry my bad english and sorry if is a idiot point.

Regards.

### Link to test case ###
https://jsfiddle.net/hLz169fg/4/

**Comment by dmethvin** [comment]
This is a StackOverflow question.

**Comment by juninhodeluca** [comment]
You think? Lol maybe my bad english has hindered understanding what I meant. It was a rhetorical question. I know the answer.
