### ISSUE TITLE
Event not registered if <map> on a different level than <img> (image map)

### ISSUE THREAD

**Issue by thdoan** [jquery/jquery#3364]
### Description ###
Given the following code:
```
$('#container').on('mousemove', function() {
  console.log('mousemove');
});
```
The `mousemove` event is only registered when the `<map>` element is on the same level as the `<img>` element:
```
<div id="container">
  <img id="sample-map" src="searchengines.png" alt="Sample image map" usemap="#image-map">
  <map name="image-map">
    <area href="https://www.google.com/" alt="" title="Go to Google" shape="rect" coords="0,0,240,99">
    <area href="https://www.yahoo.com/" alt="" title="Go to Yahoo!" shape="rect" coords="0,100,240,179">
    <area href="http://www.bing.com/" alt="" title="Go to Bing" shape="rect" coords="0,180,240,264">
  </map>
</div>
```
The `mousemove` event fails to register when `<map>` and `<img>` are on different levels:
```
<div id="container">
  <img id="sample-map" src="searchengines.png" alt="Sample image map" usemap="#image-map">
</div>
<map name="image-map">
  <area href="https://www.google.com/" alt="" title="Go to Google" shape="rect" coords="0,0,240,99">
  <area href="https://www.yahoo.com/" alt="" title="Go to Yahoo!" shape="rect" coords="0,100,240,179">
  <area href="http://www.bing.com/" alt="" title="Go to Bing" shape="rect" coords="0,180,240,264">
</map>
```
Since image maps are linked by the `usemap` value, there should not be an arbitrary dependency on the image and the image map being on the same DOM level.
### Link to test case ###
http://codepen.io/thdoan/pen/jrZybY

**Comment by dmethvin** [comment]
Are you saying this works differently than if you used the native `.addEventListener()` interface? Or simply that you didn't expect the behavior you saw?

**Comment by thdoan** [comment]
@dmethvin It turns out this is not a jQuery issue but an `addEventListener()` issue. But still, this was not a behavior that I was expecting -- who can I bring this issue up with if it's related to native functionality?
