### ISSUE TITLE
Serialize() should output values of type=submit buttons during form submission

### ISSUE THREAD

**Issue by nickshanks** [jquery/jquery#3368]
When a form is being submitted (i.e. within its `onsubmit` event) the submitting button, if any, should be included in the `serialize()` output.

See http://jsfiddle.net/om16j7m4/

[The documentation](http://api.jquery.com/serialize/) states ‘No submit button value is serialized since the form was not submitted using a button.’ — This is currently correct when stating that no submit button value is serialized, but can be incorrect in its assumption that the form is not being submitted due a button being triggered.

**Comment by dmethvin** [comment]
If your code is running and knows that a specific button was used to trigger the code that calls `.serialize()`, it can add the button to the serialized string. The `.serialize()` method, however, doesn't have a reasonable way to know that the form it is serializing is being serialized because a specific button was pressed.

**Comment by gibson042** [comment]
Every time I see one of these tickets, I wonder if we should add a special-case for submitter elements in the context collection so e.g. `$submit.serialize()` returns the [form data set](https://html.spec.whatwg.org/multipage/forms.html#constructing-the-form-data-set) that would be submitted by activating `$submit`.

**Comment by dmethvin** [comment]
Having the caller explicitly specify the submitting control should work, although I don't really like the idea of using the collection to specify it. You could always add an arg to `.serialize()` that specifies the submit button but it's easy to write that code yourself anyway.

A bigger problem is determining which button (if any) was pressed to submit the form, if you try to determine that in the submit handler. 

http://stackoverflow.com/questions/2066162/how-can-i-get-the-button-that-caused-the-submit-from-the-form-submit-event

**Comment by gibson042** [comment]
I'm definitely not in favor of _guessing_ the submitter, just of making it possible to serialize those that are explicitly specified. I would expect such calls to be made from handlers bound to submit buttons.
