### ISSUE TITLE
Ajax call is not working over Secured WiFi in IE, Chrome

### ISSUE THREAD

**Issue by rangakore** [jquery/jquery#3373]
### Description ###
Hi Team,

My team is using Jquery-2.2.4 minified version to make ajax calls. All ajax calls are working with LAN, but not over wifi. We've contacted several alternatives. We couldn't find solution.

Here I'm keeping the code that we are building. Please suggest

Any suggestion would help us.

$.ajax({
			method: "POST",
			url: "......",
			contentType: "application/json; charset=utf-8",
			data: JSON.stringify(obj),
			timeout: 65000,
			headers: {...
,,,
....}
		}).done(function(data) {
			......
.....
......
..
		}).fail(function() {
			....
....
		});

**Comment by bendahrooge** [comment]
If you're viewing the webpage locally (as in viewing in file:// rather than using a server on http://localhost) then it is probably a CORS issue. Trying making your server append this header to the javascript file you are trying to request:
`Access-Control-Allow-Origin: *`

**Comment by timmywil** [comment]
Thanks for opening an issue. However, you can find support on [stackoverflow](http://stackoverflow.com), the [jQuery forums](http://forum.jquery.com), or in the jQuery [gitter](https://gitter.im/jquery/jquery).
