### ISSUE TITLE
jquery-3.1.1type, It's '%'ruture numbers a wrong,    if    x=5;y=x%z;   it ruture nerver y;but z=x  this time it reture0;

### ISSUE THREAD

**Issue by qq1572841726** [jquery/jquery#3375]

**Comment by qq1572841726** [comment]
jquery-3.1.1type, It's '%'ruture numbers a wrong, if x=5;y=x%z; it ruture nerver y;but z=x this time it reture0;

**Comment by timmywil** [comment]
Thanks for opening an issue. You can find support on the [forums](http://forum.jquery.com).
