### ISSUE TITLE
Deferred chain very slow

### ISSUE THREAD

**Issue by davhdavh** [jquery/jquery#3378]
The use of setTimeout in the deferred causes massive slow down when using deferred heavily in chains.

https://jsfiddle.net/1axxtxgf/6/

##What actually happens?##

Just 100 deferred in chain takes ~500 msec due to the 4ms min delay in setTimeout.

##What do you expect to happen?##

It would be much better to use setImmediate (Promise section 2.2.4 requires it MUST be done in a new context, so cannot just run it), or an implementation that uses the sendMessage API to emulate same.

As shown in the test, this drops the runtime to ~8msec, a speed up of 62x.

**Comment by davhdavh** [comment]
NB. The library used in the test does not override setTimeout for IE since that already implements setImmediate. So IE does not show a speedup

**Comment by gibson042** [comment]
`setImmediate` is unavailable in the latest Chrome, Firefox, and Safari releases, as well as IE9, and emulating it would almost certainly increase the file size by an unpalatable amount. If you need fast performance from chaining "just" 100 deferreds, then I would recommend a more specialized library like [Bluebird](https://github.com/petkaantonov/bluebird).

That said, I could definitely see abstracting our use of `window.setTimeout( fn )` in a way that takes advantage of `setImmediate` where available.

**Comment by dcherman** [comment]
@gibson042 What about exposing something like `jQuery.Deferred.nextTick` that defaults to `setTimeout`?

You'd easily be able to bower install something like `asap` and do `jQuery.Deferred.nextTick = asap` in order to speed up your jQuery promises without bloating the core library at all.

**Comment by dmethvin** [comment]
Our Deferred implementation isn't meant to be a competitor for native Promise. The most common internal use is with ajax or animations where any chain will be short and the time it takes for the ajax or animation will dominate by far. It's easy to convert Deferred to Promise if you don't need cross-platform compatibility. 

My concern with some global hook like `jQuery.Deferred.nextTick` is that we'll introduce cross-platform differences that will be difficult to debug, especially for those who didn't know they were being opted in to a change by some other code on the page.

**Comment by davhdavh** [comment]
It doesnt need to actually implement setImmediate, just use it if it is available.
IE (window.setImmediate || window.setTimeout)(process) or something like that

**Comment by davhdavh** [comment]
I updated example with native Promise support: https://jsfiddle.net/1axxtxgf/7/

**Comment by gibson042** [comment]
Like I said above, I could definitely see abstracting our use of `window.setTimeout( fn )` in a way that takes advantage of `setImmediate` where available. A PR would be fairly considered.

**Comment by jaubourg** [comment]
> Like I said above, I could definitely see abstracting our use of `window.setTimeout( fn )` in a way that takes advantage of `setImmediate` where available. A PR would be fairly considered.

IIRC, that was the original plan. The idea was to introduce `jQuery.later` and use that internally (having it in the public API would have allowed to override it in envs with better alternative implementations like `nextTick` in node). Hell if I remember why we went another way.

**Comment by fabien** [comment]
@gibson042 I was in the process of updating a Deferred-heavy set of components to v.3, and stumbled upon this issue as well, things slowed down to a crawl. I included `replaceSetTimeout.min.js` which gave an immediate improvement. Which solution would you recommend?

**Comment by jsearles** [comment]
I too have run into this upgrading to JQ3, noticing performance degradation. I think a good resolution would be to queue the resolutions. That way you could keep them asynchronous as the spec defines, but run all pending resolutions in a single timeout.

**Comment by jsearles** [comment]
Actually just noticed #3227 which looks to leverage this technique.
