### ISSUE TITLE
$.getJSON downgrades https to http

### ISSUE THREAD

**Issue by chalbersma** [jquery/jquery#3382]
Bug Reports:
  Note that we only can fix bugs in the latest version of jQuery.
  Briefly describe the issue you've encountered
  * Using .getJSON() should utilize the current protocol. Instead it sometimes uses https and sometimes doesn't. It's based on wether or not the link ends with a `/`
  *  What acually happens?
`.getJSON("/my/link", function(){})` fails
`.getJSON("/my/link/", function(){})` succeeds
  *  Which browsers are affected?
Noted in the latest browsers available for Ubuntu 16.10 including firefox and crome.

I upgraded to the latest version of jquery 3.1.1

**Comment by mgol** [comment]
Please provide a test case on https://jsbin.com or https://jsfiddle.net. The code is not doing anything at random here so if you see different behavior something must be different on the sites you test.

**Comment by pankajpatel** [comment]
The Example can be seen here: http://jsbin.com/vofipib/edit?js,console

**Comment by timmywil** [comment]
Thank you for opening an issue, but I'm not seeing the downgrade behavior. https just responds faster because http is redirecting to https, so the order of logs might be confusing.
