### ISSUE TITLE
.css('margin') and .css('padding') return empty string in Firefox

### ISSUE THREAD

**Issue by thdoan** [jquery/jquery#3383]
### Description ###

`.css('margin')` and `.css('padding')` return empty string in Firefox (tested in v49.0.2 and Nightly v52.0a1). Chrome returns the expected result (see test link below).

### Link to test case ###

http://codepen.io/thdoan/pen/LRwbGM

**Comment by dmethvin** [comment]
Looks to be consistent with `getComputedStyle`: http://codepen.io/anon/pen/VmwPxv

The docs warn about using shortcut properties, they're not all that useful since they may be wrong.
