### ISSUE TITLE
Deprecate jQuery.camelCase, hide in 4.0

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#3384]
### Description ###

We should hide `jQuery.camelCase`. It's an undocumented, private method which doesn't make sense to be available externally as it contains a CSS-only quirk that replaces `-ms-` to `ms-`. Rather than fixing it it's better to just remove it.

Theoretically we could do it in any minor release but since it's been semi-public for so long it's better to wait, especially that code around it will have to change in 4.0 anyway because of #3355.

### Link to test case ###
N/A

**Comment by niltoncsr** [comment]
I'm starting to contribute and I'd like to help on this one :smile: 
Do you think it's a good choice to move the function to `src/var/` in its own module and import it wherever is needed, @mgol?

**Comment by mgol** [comment]
PR in progress is at #3604.
