### ISSUE TITLE
height() & outerHeight() returns undefined for $('.no-result-selectors') in 3.1.1

### ISSUE THREAD

**Issue by benxshen** [jquery/jquery#3386]
Hi team,

I got the return value undefined of height() / outerHeight() for the $('.no-result-selectors') in 3.1.1
The same in the 2.1.4 returns 0.

This breaks my calculation for some dynamic heights as the result is NaN.

Is this changed in 3.x? or is this an issue? (I feel 0 is reasonable return value when $() selects empty result)

Thank you.

**Comment by dmethvin** [comment]
https://jquery.com/upgrade-guide/3.0/#breaking-change-return-values-on-empty-sets-are-undefined

Our logic here is that the offset of nothing is nothing, not zero. You can easily add `|| 0` to your expression if you want the old behavior.
