### ISSUE TITLE
No way to abort Ajax request

### ISSUE THREAD

**Issue by AlexandraK** [jquery/jquery#3387]
### Description ###

jQuery.ajax does not return a jqXHR object anymore so there's no way to abort a ajax request like in 2.x jQuery

**Comment by dmethvin** [comment]
It still returns an object.

**Comment by AlexandraK** [comment]
It returns a promise, not jqXHR! The abort() method is missing now (jQuery 3.1.1)

**Comment by dmethvin** [comment]
Please add a link to a test case.

**Comment by AlexandraK** [comment]
https://jsfiddle.net/rzdk4umt/

**Comment by dmethvin** [comment]
You've saved the result of the `.then()`, not the `.ajax()`. The `.then()` returns a `Deferred`, not a `jQXHR`.
