### ISSUE TITLE
Drop `toggleClass(boolean)` and `toggleClass(undefined)` signatures

### ISSUE THREAD

**Issue by silverwind** [jquery/jquery#3388]
Can we evaluate if these signatures can be dropped? Here's a few arguments:

- It can mask bugs when the first argument inadvertently evaluates to `undefined`, which results in all classes being removed the first time it is called.
- It's badly documented (https://github.com/jquery/jquery/issues/1696) and because of that, probably not well-known.
- The way it saves a `__className__` data seems like a bad practice.
- For custom builds, it creates a otherwise unnecessary dependency for `attributes/classes` towards `data`.
- It would allow the following savings for full builds:

````
   raw     gz Compared to master @ 5b4cb0d33731a58384e02ad51e703e7dcb00e424
  -701   -230 dist/jquery.js
  -168    -61 dist/jquery.min.js
````

**Comment by silverwind** [comment]
Looks like I missed that the boolean signature was already [deprecated](http://api.jquery.com/toggleclass/#toggleClass-state) in 3.0. I assume this means the undocumented `undefined` is also included?

**Comment by timmywil** [comment]
@silverwind yes, removal would be in 4.0

**Comment by timmywil** [comment]
And thanks for offering!

**Comment by silverwind** [comment]
Ok, I'll close this as I'm sure you have that planned. If you want to keep it as a reminder for removal, feel free to reopen.

**Comment by mgol** [comment]
I think it's good to have it as a reminder, we already have some issues created for 4.0.0 (https://github.com/jquery/jquery/milestone/7) but this one was missing.

**Comment by mgol** [comment]
Thanks for the report!

**Comment by mgol** [comment]
PR: #4766
