### ISSUE TITLE
hoos.stop is never called before is is delete(#7518)

### ISSUE THREAD

**Issue by SABERYJS** [jquery/jquery#3393]
with the lastest JQurey and i find a bug(though it is not serious),code is below(#7518):
`jQuery.fn.delay = function (time, type) {
        time = jQuery.fx ? jQuery.fx.speeds[time] || time : time;
        type = type || "fx";

        return this.queue(type, function (next, hooks) {
            var timeout = window.setTimeout(next, time);
            hooks.stop = function () {
                //alert("stop has been called");
                window.clearTimeout(timeout);
            };
        });
    };`
hooks.stop is never called before it is delete from hooks

**Comment by mgol** [comment]
Could you provide a test case on https://jsfiddle.net showing where do you think it breaks? You focused on internals and we need to know how you use jQuery that you're seeing an error.

Also, what's that #7518 referrence?

**Comment by SABERYJS** [comment]
Test case is as below:
$("#di").slideDown(2000).delay("1000").slideUp(2200);
$("#di") display a  div.
Now,back to JQuery core api,at jQuery.fn.delay(line 7518)
jQuery.fn.delay = function (time, type) {
    time = jQuery.fx ? jQuery.fx.speeds[time] || time : time;
    type = type || "fx";

    return this.queue(type, function (next, hooks) {
        var timeout = window.setTimeout(next, time);
        hooks.stop = function () {
            //alert("stop has been called");
            window.clearTimeout(timeout);
        };
    });
};

we know,this.queue() push function into queue relateted to a jQuery.fn Object, the item pushed is the second argument,in theory,hooks.stop should be called in jQuery.dequeue() and before delete
hooks.stop;
question is JQuery.dequeue() function,code is below:
if (fn) {

    // Add a progress sentinel to prevent the fx queue from being
    // automatically dequeued
    if (type === "fx") {
        queue.unshift("inprogress");
    }

    // Clear up the last queue stop function
    delete hooks.stop;
    fn.call(elem, next, hooks);
}
 delete hooks.stop is called,but hooks.stop is never called.

**Comment by SABERYJS** [comment]
Test case is as below:
$("#di").slideDown(2000).delay("1000").slideUp(2200);
$("#di") display a  div.
Now,back to JQuery core api,at jQuery.fn.delay(line 7518)
jQuery.fn.delay = function (time, type) {
    time = jQuery.fx ? jQuery.fx.speeds[time] || time : time;
    type = type || "fx";

    return this.queue(type, function (next, hooks) {
        var timeout = window.setTimeout(next, time);
        hooks.stop = function () {
            //alert("stop has been called");
            window.clearTimeout(timeout);
        };
    });
};

we know,this.queue() push function into queue relateted to a jQuery.fn Object, the item pushed is the second argument,in theory,hooks.stop should be called in jQuery.dequeue() and before delete
hooks.stop;
question is JQuery.dequeue() function,code is below:
if (fn) {

    // Add a progress sentinel to prevent the fx queue from being
    // automatically dequeued
    if (type === "fx") {
        queue.unshift("inprogress");
    }

    // Clear up the last queue stop function
    delete hooks.stop;
    fn.call(elem, next, hooks);
}
 delete hooks.stop is called,but hooks.stop is never called.

**Comment by SABERYJS** [comment]
the purpose of using hook.stop is  clearTimeOut(timeId) when current item executed finsihed and before next item start execute,i think this is why code(delete hooks.stop) is called,right??

**Comment by ouhsub** [comment]
`js`

**Comment by Varunram** [comment]
@SABERYJS 
The clearTimeout() method in hooks.stop clears the timer set by setTimeout() whereas delete hooks.stop clears the last queue stop function. When we do deletion, we clear the method followed by the hook itself as given by stop(gotoEnd);

**Comment by markelog** [comment]
Since there was no test-case presented for quite some time, i'm closing this, please ping us up if you want to continue this discussion
