### ISSUE TITLE
Invalid Regular Expression 

### ISSUE THREAD

**Issue by DaGLiMiOuX** [jquery/jquery#3395]
I'm having some troubles with jQuery and jQuery UI. I have a jQuery UI slider that throws:

    jquery.js:4430 Uncaught SyntaxError: Invalid regular expression: /(^|\.)slider56(\.|$)/

It happens when I'm trying to slide the bubble that I have for sliding. The error happens in this fragment of code (Between # Error tags).

    // Remove matching events
        origCount = j = handlers.length;
        while ( j-- ) {
                handleObj = handlers[ j ];

                if ( ( mappedTypes || origType === handleObj.origType ) &&
                        ( !handler || handler.guid === handleObj.guid ) &&
                         # Error
                        ( !tmp || tmp.test( handleObj.namespace ) ) &&
                        # Error
                        ( !selector || selector === handleObj.selector || selector === "**" && handleObj.selector ) ) {
                                handlers.splice( j, 1 );

                                if ( handleObj.selector ) {
                                        handlers.delegateCount--;
                                }
                                if ( special.remove ) {
                                        special.remove.call( elem, handleObj );
                                }
                }
         }

**Comment by dmethvin** [comment]
Please link to a test case at jsbin.com or jsfiddle.net.

**Comment by DaGLiMiOuX** [comment]
I'm sorry, but I don't think I could give a test case because it's not happening in other sliders. My case is that I have an insert image button that inserts an Image into a Div. I also have a panel configuration for that Div to change it's background color etc. When the image is inserted into the Div it shows an option in my configuration panel in execution time and enables it as a slider. Only that slider introduced in execution time is failing.

My question is if you have noticed something related or if you know how could I find that error (probably an error in my code).

Here is my slider code:

    '<div class="image-opacity-slider"></div>' +
    '<input type="text" name="opacity-spinner" class="image-opacity-spinner"/>' +
    '<input type="hidden" name="opacity"/>' +

Here are the slider and the spinner codes (its an slider with an spinner "linked"):

    $('.config-panel).find('.image-opacity-slider').slider({
        range: "min",
        value: _this.elImage.opacity,
        min: 0.1,
        max: 1,
        step: 0.1,
        slide: function(event, ui) {
            $('.config-panel).find('input[name=opacity-spinner]').spinner('value', ui.value);
        },
        change: function( event, ui ) {
            $('.config-panel).find('input[name=opacity]').val(ui.value).change();
        }
    });

    $('.config-panel).find('.image-opacity-spinner').spinner({
        min: 0.1,
        max: 1,
        page: false,
        step: 0.1,
        stop: function(event, ui) {
            $('.config-panel).find('.image-opacity-slider').slider('value', $(this).spinner('value'));
        }
    }).val(this.Image.opacity).unbind('keydown').bind('keydown', function (e) {
        e.preventDefault();
    });

I'm using Chrome Version 54.0.2840.71 m

If you need more information or to explain something, please let me know.

Thanks in advance.

**Comment by dmethvin** [comment]
It's pretty hard to debug without a test case. We can fix reported bugs but can't fix them unless we know what the bug is. The region of code where the bug occurs indicates to me that it's with a delegated event.
