### ISSUE TITLE
jQuery 3.1.1 outerHeight() returns undefined instead of null

### ISSUE THREAD

**Issue by saurabh-sharma** [jquery/jquery#3396]
### Description ###
jQuery 3.1.1 `$("").outerHeight(true);` or `$("").outerHeight();` is returning `undefined` instead of `null`.

As per the documentation [here](http://api.jquery.com/outerheight/) it should return the value as `null` if called on an empty set of elements. but in case when an element is passed it works as desired.

### Link to test case ###

Here's the fiddle with jQuery 3.1.1: https://jsfiddle.net/xgvdnygn/
And same example with jQuery 2.2.4: https://jsfiddle.net/xgvdnygn/1/

**Comment by gibson042** [comment]
`undefined` is correct per gh-2319. I'll update the documentation.
