### ISSUE TITLE
jQuery-UI doesn't recognize HTML5's hidden attribute

### ISSUE THREAD

**Issue by pvermees** [jquery/jquery#3398]
### Description ###

Using plain Javascript, it is easy to hide a select-menu option using HTML5's hidden attribute. But when I want to stylise the selectmenu using the jQuery-UI, the hidden attribute is ignored. For example, define two selectmenus:

```
<select id="one">
  <option>option 1</option>
  <option>option 2</option>
  <option hidden>hidden option</option>
  <option>option 4</option>
</select>

<select id="two">
  <option>option 1</option>
  <option>option 2</option>
  <option hidden>hidden option</option>
  <option>option 4</option>
</select> 
```

Here's the Javascript/jQuery:

```
$(function(){            
  $('#one').selectmenu();
}); 
```

When you run this example, the third item is hidden in the second selectmenu, but not in the first. It seems that jQuery-UI has disabled the hidden attribute.

### Link to test case ###

http://jsfiddle.net/pvermees/xa4219ya/1/

**Comment by mgol** [comment]
Thenks for the report. However, jQuery UI bug tracker is located at https://bugs.jqueryui.com/; this one is just for jQuery itself.
