### ISSUE TITLE
Allow "custom cache token" for ajax

### ISSUE THREAD

**Issue by movedoa** [jquery/jquery#3399]
It would be very useful to have te ability to set a custom "cache token" in jquery.
At the moment when you set cache: false in ajax requests, jQuery appends a timestamp to the request so the browser doesn't use a cached version of the file (for example http://localhost:8080/test/Test.js?_=1479310654949 )

I would like the ability to set a custom value that is then appended instead of the timestamp.

For example if you want to clear the cache after every update you could use an internal version number.
The user would get the cached version if nothing changed and if you update, the version number changes so the user would get the new version.

**Comment by dmethvin** [comment]
For GET requests you can do that by adding a parameter in `data`, or in any type of request by appending to the URL yourself. There isn't a lot of value in providing, coding, and documenting a redundant way to do this.

**Comment by movedoa** [comment]
That solution is very error-prone.
If you forget to add to token an it goes in production like this, it would be very hard to fix.
This would just be a nice clean and save way to control caching.
