### ISSUE TITLE
jQuery.ajax(cache=False) for script and jsonp when cache=False is inherited from a parent resource

### ISSUE THREAD

**Issue by drzraf** [jquery/jquery#3400]
### Description ###

When a resource, fetched using `$.ajax({cache: False})`, contains subresources, these are fetched with a cache-buster, even if there are of the text/javascript type. 

### Sample ###
* `a.html` calls `$.ajax({ url: "b.html", cache: False});`
* `b.html` contains `<script type="text/javascript" src="foo.js"></script>`

### Actual result ###
foo.js is given a cache-busting suffix (`?_=`) and fetched as `foo.js?_=123456789`

### Expected result ###
* Given that `foo.js` is `text/javascript` (type=script)
* And given that cache=False was only "inherited" from parent call,
I would expect foo.js to be fetched as if cache=True, ie without the query-string

Or at the very least I'd like to be given some control over whether sub(static)resource are fetched cached or not.

**Comment by dmethvin** [comment]
Can you provide a complete test case?

**Comment by drzraf** [comment]
Rather than a test case, a use-case?
PrestaShop 1.6, in its backoffice product page loads tabs which are
loaded with cache=False to avoid outdated data.
But these tabs relies upon static assets.
Currently these assets are forcefully loaded with a cache-buster
query-string.

**Comment by dmethvin** [comment]
No, I'd like to see a test case using just jQuery, showing what you've described.

**Comment by markelog** [comment]
Since there was no response from the owner, i'm closing this, please ping us up if you want to continue this discussion
