### ISSUE TITLE
one("webkitAnimationEnd animationend") fires more than once.

### ISSUE THREAD

**Issue by wisniewskit** [jquery/jquery#3406]
If an element is animated twice, the following code will fire twice:
```
$(elem).one("webkitAnimationEnd animationend", function(evt) {
  alert(evt.type)
});
```

The first time, an animationend is fired, and the second time a webkitAnimationEnd is fired. Here is a [jsfiddle](https://jsfiddle.net/1533ouya/) for quick confirmation.

jQuery Mobile 1.3 used this approach, causing a recent [webcompat.com report](https://github.com/webcompat/web-bugs/issues/3670), and jQuery 1.12.4 still triggers this issue (I tried it in Chrome and Firefox), so it's likely worth investigating.

**Comment by dmethvin** [comment]
This seems to be consistent as far as the `.one()` method and jQuery's event handling is concerned--**if the browser fires both events.**

As the docs for `.one()` say, "Event handlers will trigger once per element per event type." That example has one element and two event types.
