### ISSUE TITLE
Feature request: Allow jQuery.param() to accept a URLSearchParams as first argument

### ISSUE THREAD

**Issue by FuweiChin** [jquery/jquery#3410]
### Description ###
URLSearchParams is a WHATWG living standard and latest CH,FF support it.  

Will jQuery.param() allow jQuery.param() to accept a URLSearchParams as first argument?  such that
`jQuery.param(new URLSearchParams("foo=1&bar=2"))` will be "foo=1&bar=2"

### Link to test case ###
Here is a patch implementation I want to express:
```js
(function($){
	var $param=$.param;
	$.param=function(a,b){
		if(a&&typeof a.getAll=="function"&&typeof a.get=="function"){
			//assuming `a` is a native or polyfilled URLSearchParams
			return a.toString();
		}
		return $param.apply($,arguments);
	};
}(jQuery));
```

**Comment by dmethvin** [comment]
When would this be useful? Internally we can't depend on it existing so it only adds more cases to cover. Note that `(new URLSearchParams("foo=1&bar=2")).toString()` is also `"foo=1&bar=2"` so  if you need to pass `URLSearchParams` to jQuery methods there is already a way to do this.

**Comment by markelog** [comment]
Since there was no response from the owner, i'm closing this. Please ping us up if you want to continue this discussion
