### ISSUE TITLE
shortcut for .attr('id') -> .id()

### ISSUE THREAD

**Issue by arLevi** [jquery/jquery#3413]
### Description ###
For years I keep checking in Google & jQuery docs if jQuery created the shortcut for extracting the object's attribute `id` - as the jQuery lib grows ...

Instead of writing:
`$(obj).attr('id')`

Can we simply write -
`$(obj).id() `
?

### Link to test case ###
See just how many users are looking for it:
http://stackoverflow.com/questions/3239598/how-can-i-get-the-id-of-an-element-using-jquery

**Comment by dmethvin** [comment]
It's really short already, there's no reason for another method just to get one property, along with the code and documentation for it. There was a `.id()` method in jQuery around the 1.0 time frame and it was removed to keep the API simple.
