### ISSUE TITLE
onHide and onShow events

### ISSUE THREAD

**Issue by netfox01** [jquery/jquery#3416]
it would be convenient if jQuery has onHide and onShow events which will be fired when the element css display has been changed with  $(..).hide(), $(..).fadeOut(), $(..).show(), $(..).fadeIn() or even $(..).css('display', 'none') ...

usage :
```javascript

$(..).on('hide', function () {
    // element is hidden
})

$(..).on('show', function () {
    // element is visible
})

$(..).hide()

$(..).css('display', 'block');

````

**Comment by dmethvin** [comment]
This would be expensive to implement. If you know that you want to track specific animations, just add a complete handler to them or use `.promise()` to get a promise for them.

**Comment by rugglcon** [comment]
Is this going to be revisited?
