### ISSUE TITLE
emprovement in css function

### ISSUE THREAD

**Issue by publicocean0** [jquery/jquery#3418]
possibility to add multiple css attribute with same name 
elem.css(height,['95%','fit-content'])

**Comment by netfox01** [comment]
Hi, can you be more specific with details for your example, and i think you forgot quotes for height.

**Comment by publicocean0** [comment]
i notified not a bug. 
in css , designers use multiple assignment for the same property.

example:

.class{
height:95%;
height:fit-content;
}

it is a trick for be sure that a feature works also in old browsers

**Comment by markelog** [comment]
You already can do this with `$(something).css("height", "95%").css("height", "fit-content")` should work in all browsers

**Comment by publicocean0** [comment]
No I tried else I d be not here

**Comment by mgol** [comment]
@publicocean0 You'd have to explain your problem in more detail since what @markelog posted works for the scenario you described so far.
