### ISSUE TITLE
replaceClass() function

### ISSUE THREAD

**Issue by netfox01** [jquery/jquery#3419]
many times we replace an element class with another one like so : 
```javascript
element.removeClass('class1').addClass('class2');
```
instead it should be 
```javascript
element.replaceClass('class1', 'class2');
```

**Comment by mgol** [comment]
Thanks for the report.

The API you propose doesn't save a lot of code so I don't think it's worth adding it. AFAIK there is also no native equivalent in the `classList` API and no one has asked about it before. If you want you can always define a plugin yourself.

**Comment by chocolateboy** [comment]
@mgol

> AFAIK there is also no native equivalent in the classList API 

FYI: there is a [`replace`](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/replace) method in the [DOMTokenList API](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList). Looks like it was [added](https://github.com/whatwg/dom/issues/28) in November 2015.
