### ISSUE TITLE
Apply same fix to radio buttons as for checkbox

### ISSUE THREAD

**Issue by mbest** [jquery/jquery#3423]
See https://bugs.jquery.com/ticket/3827 and https://github.com/jquery/jquery/commit/1fb2f92c357b985a5ba18d0938edd27b5f64d8c3

This fix should also include `radio` buttons. Currently if you use jQuery to trigger a click on a radio button, event handlers get called before the `checked` state is updated. The [release notes for 1.9.1](http://jquery.com/upgrade-guide/1.9/#checkbox-radio-state-in-a-trigger-ed-quot-click-quot-event) when the above change was included say it was changed for radio buttons even though it wasn't.

**Comment by gibson042** [comment]
Yes, we appear to have a problem in https://github.com/jquery/jquery/blob/f18ca7bfe0f5e3184bf1ed55daf1668702c5577a/src/event.js#L477
using `this.type === "checkbox"` instead of `rcheckableType.test( this.type )`.

**Comment by markelog** [comment]
Hi there.

I think we understand what you mean, but would you mind providing a test-case on http://jsbin.com/ or on similar resource? So it would be clear what behaviour you expect

**Comment by gibson042** [comment]
Such test case will also be necessary for a PR. Would you like to work on this, @mbest?

**Comment by mbest** [comment]
Here is the jsbin that was linked in the Knockout issue: http://jsbin.com/yinare/4/edit?html,js,output

**Comment by timmywil** [comment]
This will be backed out due to the regression seen [here](https://github.com/jquery/jquery/issues/3579). We will re-land with a fix for that regression in 3.3.

**Comment by timmywil** [comment]
Also see https://github.com/jquery/jquery/pull/1367

**Comment by mbest** [comment]
Seems the same issue would apply to `trigger('click')` on checkboxes (code that has existed since 1.9.1).

**Comment by timmywil** [comment]
Right, but that's not a regression since 3.1.1. We plan to address that as well in 3.3.

**Comment by timmywil** [comment]
@gibson042 is working on this, but it will not make it in the 3.3 release.

**Comment by mgol** [comment]
PR: #4279
