### ISSUE TITLE
Confusing code, global object vs. DOM window vs. fake DOM window

### ISSUE THREAD

**Issue by david-mark** [jquery/jquery#3426]
### Description ###

Starting at the beginning, what is this code from wrapper.js supposed to do?

```javascript
// Pass this if window is not defined yet
} )( typeof window !== "undefined" ? window : this, function( window, noGlobal ) {
```

In browsers it will pass a reference to the global `window` object, which is a host object that is often the same (or at least closely mimics) the global object. In NodeJS, a reference to a module object will be passed. And in any other ECMAScript environment that lacks a global `window` object, the global object will be passed.

Also, not sure what the "yet" in the above comment is supposed to mean. Moving on to the start of the function:

```javascript
( function( global, factory ) {

	"use strict";
```

Note that the first function argument is called `global`, which is quite confusing as it may well reference the `window` host object or a NodeJS module. In other environments it will reference the global object.

The code continues:

```javascript
if ( typeof module === "object" && typeof module.exports === "object" ) {

		// For CommonJS and CommonJS-like environments where a proper `window`
		// is present, execute the factory and get jQuery.
		// For environments that do not have a `window` with a `document`
		// (such as Node.js), expose a factory as module.exports.
		// This accentuates the need for the creation of a real `window`.
		// e.g. var jQuery = require("jquery")(window);
		// See ticket #14549 for more info.
		module.exports = global.document ?
			factory( global, true ) :
			function( w ) {
				if ( !w.document ) {
					throw new Error( "jQuery requires a window with a document" );
				}
				return factory( w );
			};
	} else {
		factory( global );
	}
```

This line:

```javascript
module.exports = global.document ?
```

Checks for the global `document` object (as in browsers), which implies that `global` is a reference to the global object; however, we've seen that `global` may reference one of three types of objects: the `window` object in browsers, some sort of module object in NodeJS (which will surely not have a `document` property) or the global object in some unspecified environments. The comments are of little help as they imply that `global` references a `window` object.

It's all quite confusing and there is an inconsistency at the end:

```javascript
        else {
		factory( global );
	}
```

All we know at this point is that there is no `module.exports` object. What we *don't* know is whether this `global` object has a `document` object. If it does not, then jQuery will fail as soon as it references `window.document` (the argument name is `window` in the core, which adds additional confusion).

I've cleared most of this up in these three files:

https://github.com/david-mark/jquery/blob/master/src/wrapper.js
https://github.com/david-mark/jquery/blob/master/src/exports/global.js
https://github.com/david-mark/jquery/blob/master/src/.eslintrc.json

Haven't even bothered to run it as not sure if I am wasting my time here. All need to understand what these changes accomplish and offer feedback before proceeding (or not). I've done about as much as I'm going to do at this point.

But there are bigger issues that require more changes. We really should allow passing *both* the global object reference *and* the `window` object to the `factory` function. If only the global object is passed, then the `window` object can be found as a property of that object. I've made this possible in wrapper.js, but the additional argument should also be added to the core script. An example where it should likely be used:

```javascript
var

	// Map over jQuery in case of overwrite
	_jQuery = window.jQuery,

	// Map over the $ in case of overwrite
	_$ = window.$;

Query.noConflict = function( deep ) {
	if ( window.$ === jQuery ) {
		window.$ = _$;
	}

	if ( deep && window.jQuery === jQuery ) {
		window.jQuery = _jQuery;
	}

	return jQuery;
};

// Expose jQuery and $ identifiers, even in AMD
// (#7102#comment:10, https://github.com/jquery/jquery/pull/557)
// and CommonJS for browser emulators (#13566)
if ( !noGlobal ) {
	window.jQuery = window.$ = jQuery;
}
```

That is a case that would seem to call for the global object, not whatever is passing for the `window` object. Just so happens that, in browsers, the two are usually equivalent. Not so in other environments.

### Link to test case ###

There's no test case. The changes I am suggesting should not change the behavior, so the current unit tests will suffice.

**Comment by david-mark** [comment]
Have tested in NodeJS and see what the "yet" was referring to in the comment. Obviously depends on the order of `require` calls.

Works as expected.

If there is a *global* `window` object at the time `require` is called, then there is no chance to augment either `window` or the global object as the `noGlobal` flag is always set. Not sure if that is what was intended, but that's the way it has always been.

If there is a no *global* `window` object at the time `require` is called *and one is created before calling the exported factory function*, then there are two possibilities:

1. Can simply pass a fake `window` object and it is augmented with `$` and `jQuery` as before.

2. Can pass the global object reference and it is augmented with `$` and `jQuery`, which makes a lot more sense to me. Then they are global and can be referenced as any other global variables by the calling module.

Finally, if there is a fake window object that is *not* global, it can be passed to the exported factory function *or* both the global object and the window can be passed. Results correspond to the two above; the only difference is *two* arguments must be passed to get the second outcome.

That seems to cover every previous possibility and adds several more; of particular interest is the ability to augment the global object of the calling module with `$` and `jQuery`, which allows the script to reference them just as in a browser. And the code makes a lot more sense now as `window` and the global object are separate, which reflects the fact that they will not be the same object in *every* environment.

Clearly, this should all be thoroughly documented.

**Comment by gibson042** [comment]
Thank you for providing your full thought process. I agree that the wrapper.js parameter is poorly named—`windowOrGlobal` would be more accurate, and separate `window` and `global` parameters might be even better. I'd happily accept a behavior-preserving PR to clean that up. And regarding the behavior, I can see where the code leads you astray:

<blockquote>
This line:

```javascript
module.exports = global.document ?
```

Checks for the global `document` object (as in browsers), which implies that `global` is a reference to the global object; however, we've seen that `global` may reference one of three types of objects: the `window` object in browsers, some sort of module object in NodeJS (which will surely not have a `document` property) or the global object in some unspecified environments. The comments are of little help as they imply that `global` references a `window` object.
</blockquote>

In the primary use case, `global` will be a window object (again, it is poorly named right now). And that line is intended to detect a `document` property on _`window`_, not on the global object (i.e., if the parameter were split as I suggested above, it would be `module.exports = window && window.document ?`).

<blockquote>
It's all quite confusing and there is an inconsistency at the end:

```javascript
        else {
		factory( global );
	}
```

All we know at this point is that there is no `module.exports` object. What we *don't* know is whether this `global` object has a `document` object. If it does not, then jQuery will fail as soon as it references `window.document` (the argument name is `window` in the core, which adds additional confusion).
</blockquote>

This is actually the primary use case I mentioned, and I'd like to see that made explicit in any wrapper.js refactor. But regardless, that lack of `module.exports` means that we are definitely not engaged in a CommonJS/Node.js initialization, and therefore `global` MUST be a window object if we are to succeed.

<blockquote>

But there are bigger issues that require more changes. We really should allow passing *both* the global object reference *and* the `window` object to the `factory` function. If only the global object is passed, then the `window` object can be found as a property of that object. I've made this possible in wrapper.js, but the additional argument should also be added to the core script. An example where it should likely be used:

```javascript
// Expose jQuery and $ identifiers, even in AMD
// (#7102#comment:10, https://github.com/jquery/jquery/pull/557)
// and CommonJS for browser emulators (#13566)
if ( !noGlobal ) {
	window.jQuery = window.$ = jQuery;
}
```
</blockquote>

I strongly disagree. Refer to the `var jQuery = require("jquery")(window)` example in our wrapper.js comments—that call can and does add `jQuery` and `$` properties to the provided window object, but SHOULD NOT affect its context environment. Anyone _wanting_ to do so is free to make a call like `this.jQuery = this.$ = require("jquery")(window)` or (if the context object was not initially window-like but now is) `requiredJQuery(this)`.

The bottom line is that, despite the naming flaws in wrapper.js, initialization is working as intended:
* non-CommonJS browser environment: attaches a `jQuery` function (and `$` alias) to the global `window`
* CommonJS: exports a `jQuery` function associated with the global `window`, but does not attach it
* Node.js: exports a factory function that returns the `jQuery` function resulting from executing non-CommonJS browser initialization on a provided window

Those have developed somewhat organically as people wanted jQuery in new environments, sometimes in the form of multiple coexisting instances (and even multiple versions). Changes are not out of the question, but proposals _would_ have to be very clear and consider backwards compatibility.

All that said, do you have a proposal for changing initialization behavior?

**Comment by david-mark** [comment]
> Thank you for providing your full thought process. I agree that the wrapper.js parameter is
> poorly named—windowOrGlobal would be more accurate, and separate window and global
> parameters might be even better. I'd happily accept a behavior-preserving PR to clean that up.

Did you look at the three files I changed. The changes do not add an extra argument to the initial function call, but do add one to the factory function. The initial call always gets the global object and the argument is now called `global`. At the moment, even `windowOrGlobal` would be inaccurate (e.g. in NodeJS).

> And regarding the behavior, I can see where the code leads you astray:
> ...
> In the primary use case, global will be a window object (again, it is poorly named right now).

Yes, obviously and *in browsers* it is virtually identical to the global object. That's why you can get a reference to `document` on the global or `window` object. I wasn't led astray by this, but the code is massively confusing.

>  But regardless, that lack of module.exports means that we are definitely not engaged in a
> CommonJS/Node.js initialization, and therefore global MUST be a window object if we are to > succeed

It can be the global object as well as it and `window` are virtually identical (if not the same object) in browsers. Have a look at my code as I covered everything. My point is (and it is covered in the linked code) that there is a missing `throw` in the event that something *else* is passed that does not *at least* have a document property.

> I strongly disagree. Refer to the var jQuery = require("jquery")(window) example in our
> wrapper.js comments—that call can and does add jQuery and $ properties to the provided
> window object, but SHOULD NOT affect its context environment.

I covered that case in my code. Tested it in NodeJS as well. Also created the *option* to pass the global object in NodeJS, which makes it work exactly like browsers. Currently there is an asymmetry between the behavior in NodeJS and that in browsers.

> The bottom line is that, despite the naming flaws in wrapper.js, initialization is working as
> intended:

> non-CommonJS browser environment: attaches a jQuery function (and $ alias) to the global
> window

It augments the *global object* in an odd, indirect way using the `window` host object. This is the conflation I am addressing.

> CommonJS: exports a jQuery function associated with the global window, but does not attach > it

As written, this is the case for any environment with `module.exports` that has a global `window` object with a "truthy" `document` property. In this case, I think it makes far more sense to augment the *global* object. Understand that even though we are *currently* augmenting `window` in browsers, it has the same effect as augmenting the global object. The end result is correct, but it is an odd way to get there.

> Node.js: exports a factory function that returns the jQuery function resulting from executing > non-CommonJS browser initialization on a provided window

This is the issue: the provided `window` is *not* the global object in this scenario, so this third case has very different (and very odd) behavior. However, I did *not* change this behavior one bit. I just added support for passing the global object (`global`) in NodeJS, which makes all three cases behave the same (without the caller having to do anything special). They simply pass the global object instead of (or in addition to) the `window` object (which is *not* the global object in this case). If they pass the fake `window` as before, then nothing changes. This is the big win-win here.

The simplest way to understand the problem is to realize that though the first two cases are augmenting an object called `window`, it has the same effect as augmenting the global object (and this is very similar to declaring `$` and `jQuery` global variables).

> Those have developed somewhat organically as people wanted jQuery in new environments, > sometimes in the form of multiple coexisting instances (and even multiple versions). 

I understand that and when things grow organically like that, they sometimes grow asymmetrically (as is the case here).

> Changes are not out of the question, but proposals would have to be very clear and consider
> backwards compatibility.

I highly recommend that everyone with a stake in this review the linked *code changes*. I think they are very clear and are backwardly compatible. Just made things much easier to follow and added some new wrinkles in NodeJS that weren't possible before.

**Comment by gibson042** [comment]
You seem convinced that jQuery should attach itself to the global object, which is not our goal. It attaches itself to a window, which just happens to correlate with a global in browsers. We have no need to even care about such an object except for getting a window.

**Comment by david-mark** [comment]
Quoting myself here:

> If there is a global window object at the time require is called, then there is no chance to
> augment either window or the global object as the noGlobal flag is always set. Not sure if that > is what was intended, but that's the way it has always been.

I further assert that this is not how it should be (though have done nothing to change it as of yet).

The problem here is that there's no easy way to write code that works in both browsers and NodeJS.

For example, if I create a global `window` object to mimic browsers:

```javascript
if (typeof global != 'undefined') {
    global.window = window; // add window from node-jsdom or whatever
}

And *then* require jQuery like this:

```javascript
require("jquery")(global);
```

The `noGlobal` flag will have been set, so *nothing* gets augmented with `$` and `jQuery`.

Currently must do something like this:

```javascript
var jQueryFactory = require('./jQuery.js');

global.window = window;

jQueryFactory(window);
```

...which augments the `window` object as before.

Or to augment the global object:

```javascript
var jQueryFactory = require('./jQuery.js');

global.window = window;

jQueryFactory(global);
```
 
The latter case does differ from browsers in that the calling module can then reference jQuery as: `$` or `jQuery`, as well as through properties of the global object, but *not* as `window.$` and `window.jQuery`. Don't see this as a problem as it will not be the case in the first, backward compatible example where `window` is passed instead of the global object.

As a side note, it would have been much better if node-jsdom left out the window object and simply used the global object for properties that make sense in NodeJS (e.g. already has setTimeout, clearTimeout, etc.) As the `window` is virtually identical (or actually the same as) the global object in browsers (which have windows), NodeJS should simply use the global object and add a global `document` property to it. NodeJS scripts don't have windows, so the abstraction would make more sense as well.

**Comment by david-mark** [comment]
> You seem convinced that jQuery should attach itself to the global object, which is not our goal. 

Our goal? Isn't the goal to make jQuery as flexible as possible and ideally make it work in browsers as closely as it does in browsers? Or at least provide for that *option*, without breaking past use cases. That's all I've done here.

> It attaches itself to a window, which just happens to correlate with a global in browsers.

You do understand that it augments the global object, which has very specific ramifications? Doesn't make one bit of difference that you happen to be doing it slightly off-kilter in browsers by using their `window` object. The result is the same in that `$` and `jQuery` become part of the global scope, which is *clearly* the goal of the related lines in the core (not just to add properties to the `window` object).

> We have no need to even care about such an object except for getting a window.

Have no idea what that means. Anyone else care to chime in here?

**Comment by mgol** [comment]
> As the `window` is virtually identical (or actually the same as) the global object in browsers (which have windows), NodeJS should simply use the global object and add a global `document` property to it. NodeJS scripts don't have windows, so the abstraction would make more sense as well.

jsdom doesn't automatically create any globals and *that's good*. You can use jsdom to create a fake `window` instance that you can put in a variable and then pass to the jQuery factory; again, with no globals involved.

It's not just about the `document` property; we also use `getComputedStyle`, `location`, `requestAnimationFrame`, `DOMParser`, `XMLHttpRequest` etc. It would be against the Node.js philosophy if jsdom put them all on the global object so it's good it's not doing that.

We also use `setTimeout`, `setInterval` etc. from `window` and not the global object since in some environments the global versions are disallowed (see #3201). Any refactoring of the wrapper code has to take that into account and has to preserve the behavior @gibson042 described in https://github.com/jquery/jquery/issues/3426#issuecomment-264649345. I'd also add that we shouldn't require people to pass the `global` object to the factory as we don't need it in jQuery.

I sympathize with the concern about a confusingly named `global` variable and I'm not sure if we're actually using the passed `this` value if `window` is not defined but any changes must take the mentioned restrictions into account. I looked at the code but it doesn't pass our tests (just invoke `npm test` and you'll see) so it's hard to see what works and what doesn't in your version of the wrapper.

**Comment by david-mark** [comment]
> jsdom doesn't automatically create any globals and that's good. You can use jsdom to create a > fake window instance that you can put in a variable and then pass to the jQuery factory; again, > with no globals involved.

I am aware of that and did nothing to break this use case.

> It's not just about the document property; we also use getComputedStyle, location,
> requestAnimationFrame, DOMParser, XMLHttpRequest etc.

Yes, those are all properties of the `window` object (fake or not). Though `getComputedStyle` is an ill-advised shortcut for `document.defaultView.getComputedStyle`.

> It would be against the Node.js philosophy if jsdom put them all on the global object so it's
> good it's not doing that.

It's beside the point, but I think it would have been a very good *option* at least.

> We also use setTimeout, setInterval etc. from window and not the global object since in some > environments the global versions are disallowed (see #3201)

I have no problem with that and did nothing to affect it.

> Any refactoring of the wrapper code has to take that into account and has to preserve the 
> behavior @gibson042 described in #3426 (comment).

I didn't break any existing behavior; just added some additional flexibility for those who might want it.

> I'd also add that we shouldn't require people to pass the global object to the factory as we
> don't need it in jQuery.

Nor did I *require* passing the global object to the exported factory function. I simply gave them the option to do that and thus make their NodeJS environment more in line with browsers (e.g. can reference `$` and `jQuery`).

> I sympathize with the concern about a confusingly named global variable and I'm not sure if > we're actually using the passed this value if window is not defined but any changes must take > the mentioned restrictions into account

I took everything into account.

> I looked at the code but it doesn't pass our tests (just invoke npm test and you'll see) so it's
> hard to see what works and what doesn't in your version of the wrapper.

I would prefer discussing the code and any concerns that arise from the *logic* before subjecting it to integration and unit tests. You ran it and I assume received some sort of integration error (not surprised as I probably left something out of the lint directives).

I'll create a pull request so I can see the integration results myself. Please don't close it while I am monitoring the results. :)

**Comment by david-mark** [comment]
Bunch of trailing whitespace and a few tabs inserted by GitHub editor. Fixed all of that. One issue left related to the newly introduced globalObject argument passed to the core. Claims it is never used. Checking on that...

**Comment by david-mark** [comment]
Not sure what it is blithering about with regard to `"use strict"` as I didn't remove or change any of those directives.

But I am definitely a bit confused as to where to put the new argument `globalObject`, which is passed to the core after `window` and `noGlobal`. In global.js it shows `noGlobal` after a `jQuery` argument, which doesn't make any sense to me. Don't pretend to understand what all of these machinations do, but am quite clear on how I want the built script to end up.

**Comment by david-mark** [comment]
This is why I wanted to finish the discussion before even moving on to integration testing; regardless, this is the error message that seems to be the root of the problem (again, no idea why it is complaining dozens of times about `"use strict"`).

"66:80  error  'globalObject' is defined but never used  no-unused-vars"

Obviously something silly (e.g. need to put that newly introduced variable in some other file). Not afraid to admit I have *no clue* what that's about. Sure that should be trivial to solve if we are collaborating here. Simply running the tests and indicating they don't work is not what we need.

See my last update and it should be immediately apparent to anyone with experience building this thing. Should be quite clear what I'm trying to accomplish with regard to `globalObject` and how to fix it.

But it's fairly irrelevant until we all understand my proposed changes and agree that they make sense. They are extremely brief, so shouldn't take long to wrap up the discussion of the logic and the merits of the changes. Otherwise I'm just wasting my time fooling around with these integration tests. Same for unit tests as they may well be rigged to sniff out something I am proposing as a useful addition.

**Comment by david-mark** [comment]
Installing all the dependencies locally so I can play around with it, but would prefer not to guess. The issue with the "unused" variable should be obvious to anyone experienced with building this thing.

**Comment by david-mark** [comment]
All set. Test away.

PS. Can't believe we are using tabs instead of spaces for indentation. Must ask why that is.

**Comment by david-mark** [comment]
> It would be against the Node.js philosophy if jsdom put them all on the global object so it's
> good it's not doing that.

I looked into the philosophical part of this and it seems Node changed their philosophy back around 2012 when they made `global` accessible to *all* modules. Not saying I think that's a good thing, but it is what it is. Prior to that the `global` variable was per module (which makes more sense to me).

Regardless of that or which version of Node the app is using, the changes in the PR allow the calling module to more closely mimic a browser/jQuery environment *if it so chooses*. All of the unit tests passed, so assuming they are comprehensive, we should be all set.

On the unit tests, I had to change one error message to match what the test expected (node_document_missing). Would much prefer to split that test in two. One to check when `window` is missing (which will also cause jQuery to fail) and the other for `document`. As it is, the error message is confusing when `window` (self-referencing) is missing from the passed object.

Good luck!

**Comment by timmywil** [comment]
Thank you for thinking through all of this, but we won't be considering changes to this code for the time being. We'd like to focus on more pressing issues and this conversation has been quite the time sink. Please feel free to tackle an existing issue.

**Comment by david-mark** [comment]
> Thank you for thinking through all of this

You're quite welcome. Guess we will have to agree to disagree on this one. Not nearly as concerned about this as other issues (whether they've been reported or considered yet or not).

Hopefully some lessons have been learned in the process, primarily that augmenting the - window - object in browsers is done strictly for the side effect of augmenting the global object (and hence adding `$` and `jQuery` to the global scope). In other words, nobody references those as properties of the `window` object. And as we've seen, this side effect is not available in non-browser environments (e.g. NodeJS), creating an asymmetry across platforms (i.e. they augment a fake DOM `window`, which requires referencing `$` and `jQuery` as properties of that object).

In closing, a larger related issue to consider is that jQuery references the object it exports, which is a performance penalty and allows outside scripts to affect the module. Will create a new issue for that in future.

**Comment by david-mark** [comment]
I've started making these adjustments in my fork. Obviously, you aren't going to like them as virtually every module has to be changed. `jQuery` is the global exported constructor/namespace and `_jQuery` is now the reference shared by the core modules.

But here's the thing: they all have to be changed anyway. Opening a new issue related to calling methods on an exported objects; defeats the whole purpose of using modules.
