### ISSUE TITLE
jQuery 3.1.1 regression: Anchor not working in Chrome

### ISSUE THREAD

**Issue by stonezhong** [jquery/jquery#3432]
### Description ###
There are few criterias to trigger the issue
* PageA have a link `<a href="pageb#foo">pageb</a>`
* PageB uses jQuery 3.1.1
* PageB dynamically create an element with id foo opon document ready
* You open PageA with latest google chrome (I am using 54.0.2840.100 (64-bit) on Ubuntu 16.04)
click the link pageb, it brings you to pageb, but not scroll the element with id "foo" to the viewport in pageb

If you repeat step 1 to 5, but replace jQuery with 2.2.4 in step 2, the issue does not happen.

Here are the code to repro the problem:

Code for pageB:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <script
        src="https://code.jquery.com/jquery-3.1.1.js"
        integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
        crossorigin="anonymous"></script>
    <!--<script
        src="https://code.jquery.com/jquery-2.2.4.js"
        integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
        crossorigin="anonymous"></script>-->
    <script>
        $(function() {
            $('body').append('<h1 id=\'foo\'>foo</h1>');
        });
    </script>
    <title>jQuery Example 001</title>
</head>

<body>
    <h1>Good morning</h1><h1>Good morning</h1><h1>Good morning</h1><h1>Good morning</h1>
    <h1>Good morning</h1><h1>Good morning</h1><h1>Good morning</h1><h1>Good morning</h1>
    <h1>Good morning</h1><h1>Good morning</h1><h1>Good morning</h1><h1>Good morning</h1>
    <h1>Good morning</h1><h1>Good morning</h1><h1>Good morning</h1><h1>Good morning</h1>
    <h1>Good morning</h1><h1>Good morning</h1><h1>Good morning</h1><h1>Good morning</h1>
</body>
</html>
```

Code for pageA:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
  <title>Examples</title>
</head>

<body>
    <ul>
      <li><a href="example-001/index.html#foo">example-001</a></li>
    </ul>
</body>

</html>
```

**Comment by dmethvin** [comment]
This is somewhat related to gh-2679. It's a question of when the browser scrolls to `:target` in its initialization sequence and there is no consistent standard across browsers. Did you only test Chrome? What does it do on Firefox, Edge, or Safari?

**Comment by dmethvin** [comment]
Also since you're expecting code to run on page load, you might as well scroll to the element in your own code which should work in all browsers.

**Comment by stonezhong** [comment]
Issue does not happen when:
* jQuery 2.2.4 + Firefox 50.0.2
* jQuery 2.2.4 + Chrome 54.0.2840.100
* jQuery 3.1.1 + Firefox 50.0.2

Issue does happen when:
* jQuery 3.1.1 + Chrome 54.0.2840.100

The sample code is just a demonstration, I am not creating dynamic element directly, I am using AngularJS 1.x which create dynamic elements indirectly.

**Comment by mgol** [comment]
It might be that jQuery 3 ready callbacks fire a little later as we changed the Deferreds implementation a lot. I think @dmethvin is right and even though it worked fine for you with jQuery 2, it might have been just a coincidence; maybe for other people it didn't work even then.

I think you need wait for the element to appear and then use the Angular's [$anchorScroll](https://docs.angularjs.org/api/ng/service/$anchorScroll) service to scroll to the proper element.

**Comment by stonezhong** [comment]
Interesting. By definition, browser is suppose to scroll to the element represented by the fragment identifier after the document is loaded. However, how to decide "when" can we tell a document is loaded is not well defined cross browser (at least I didn't see it). It seems this "when" happens after 'DOMContentLoaded' events, however, seems things changed in jquery 3.

Yes I agree even in jQuery 2, we cannot safely say this "when" is after $(document).ready -- I saw in jQuery 2 there might be change the ready function could be triggered in a timer).

So the solution is to allow the application to handle the  fragment identifier instead of rely on the browser's behavior which is inconsistent.

So I won't call this "regression" anymore.

**Comment by mgol** [comment]
If you want to programatically scroll to a specific element you can use the popular [jquery.scrollto](https://www.npmjs.com/package/jquery.scrollto); I don't think we need it in Core, it would be too much code.

In this case, since you're using Angular, the [$anchorScroll](https://docs.angularjs.org/api/ng/service/$anchorScroll) service would be a better solution.

Because of the above I'm going to close this issue. Please see https://github.com/jquery/jquery/wiki/Adding-new-features for how we decide whether to include something in Core or not.

Thank you for your time!

**Comment by Emil-A** [comment]
Not sure if this is the right place to post.. sorry if it's not.
But stumbled upon this when I had this issue with jQuery 3+ re-loading to top when linking to anchor tag id, as mentioned above. I understand it's closed but thought this could maybe help as a solution just using Core. 
```
$(document).ready(function($){
  var url = window.location.href;
  if(url.includes('#')) {
    $("html, body").animate({ scrollTop: $('#'+url.split('#')[1]).offset().top }, 0);
  }
});
```
Sorry again, I couldn't find a SO thread, just hoping to quickly help anyone who has the same issue!

**Comment by dmethvin** [comment]
I don't know the answer offhand based on the code snippet, if you could create a new ticket with jsFiddle or jsbin per the issue template that would be great.
