### ISSUE TITLE
Mouseenter/leave changing to mouseover/out

### ISSUE THREAD

**Issue by markgoho** [jquery/jquery#3433]
I can't tell if this is JQuery or a Browser issue. Forgive me if it's not JQuery.

It looks like browsers are changing the mouseenter and mouseleave event handlers to mouseover and mouseout. It looks like there is a section of the JQ library that calls for this, but only in Safari 7. However, it's being done in all browsers.

Go to http://api.jquery.com/mouseenter/ and view the event handlers on the bottom examples. The left div should be mouseover/mouseout and the right div should be enter/leave, but they're being replaced with mouseout/over.

If I comment the code out in the library, this issue doesn't happen.

In 3.1.1, the lines of code in question are 5526 to 5560.

**Comment by mgol** [comment]
Thanks for the report. It's not just For Safari; the first part of a comment applies to all browsers: https://github.com/jquery/jquery/blob/3bbcce6/src/event.js#L662-L664

> // Create mouseenter/leave events using mouseover/out and event-time checks
> // so that event delegation works in jQuery.
> // Do the same for pointerenter/pointerleave and pointerover/pointerout

See also #3295.
