### ISSUE TITLE
Stop calling methods of an exported object

### ISSUE THREAD

**Issue by david-mark** [jquery/jquery#3440]
### Description ###

Should not be calling methods of an exported object. We currently add `jQuery` (and another reference to it called `$`) to the global scope, but core modules continue to call methods on the same object. This defeats the purpose of using modules as any outside code can change the methods, potentially breaking code in the core modules.

Sample line:

```javascript
var ret = jQuery.merge( this.constructor(), elems );
```

Unless overwritten (or deleted), that function looks like this:

```javascript
merge: function( first, second ) {
		var len = +second.length,
			j = 0,
			i = first.length;

		for ( ; j < len; j++ ) {
			first[ i++ ] = second[ j ];
		}

		first.length = i;

		return first;
	}
```

Note that there is no reference to `this`, so the function doesn't need to be called as a method at all. The extra reference to the jQuery object and dot operation are not only unsafe, but a self-imposed performance penalty. One of *hundreds*.

Line that makes this unsafe:

```javascript
if ( !noGlobal ) {
	window.jQuery = window.$ = jQuery;
}
```

Also note the contradiction in terms (and objects). If "no global" then abstain from augmenting the `window` host object. One of several places where the terms "window" and "global" are used interchangeably; sometimes in the same line.

Any outside script can simply do something like this:

```javascript
$.merge = function() {
   window.alert('I left my wallet in El Segundo!');
};
```

Related ticket:

https://github.com/jquery/jquery/issues/3426

In particular, see my last few comments.

Related pull request:

https://github.com/jquery/jquery/pull/3428

### Link to test case ###

No test case. Should be clear that deleting or overriding methods of the exported `jQuery` may cause code inside the core modules to break.

**Comment by gibson042** [comment]
jQuery has historically exposed its guts and allowed spies/mocks/etc., but some undocumented methods have already been made actually private. An explicit design decision on this point would be valuable, if only a little.

**Comment by david-mark** [comment]
> jQuery has historically exposed its guts and allowed spies/mocks/etc., but some undocumented methods have already been made actually private.

And of late it is jumping through hoops to work with modular frameworks. Exposing itself in this way renders such modularity moot. Developers may think they are creating apps safe from meddling when in fact the (basement) door is wide open.

I don't personally care one way or the other as I don't rely on such frameworks personally and don't see any way to make browser scripts 100% immune to meddling from the outside, particularly if they rely on the DOM. It's just ironic to see jQuery paired with such things as AngularJS.

**Comment by timmywil** [comment]
`jQuery.merge` is a [public function](http://api.jquery.com/jquery.merge/). I don't see the need to privatize it or to call a privatized version. We haven't experienced many problems with this design decision.

**Comment by gibson042** [comment]
Resolved on https://github.com/jquery/jquery/wiki/API-design-guidelines

**Comment by david-mark** [comment]
> jQuery.merge is a public function. I don't see the need to privatize it or to call a privatized version. We haven't experienced many problems with this design decision.

Once again, you've completely missed the point and closed an issue prematurely. Suggest you read the issue again as everything you "export" is public, but that doesn't mean you have to reference the functions in a way that defeats the purpose of using modules.

If that is unclear, I suggest you ask questions, rather than simply closing the issue (a recurring theme here).

**Comment by david-mark** [comment]
> Resolved on https://github.com/jquery/jquery/wiki/API-design-guidelines

If you think so. :)
