### ISSUE TITLE
Remove mystical incantations related to selectedIndex

### ISSUE THREAD

**Issue by david-mark** [jquery/jquery#3441]
### Description ###

This line is an example of programming by mystical incantation:

```javascript
// Accessing this property makes selected-by-default
// options in Safari work properly
if ( elem.parentNode ) {
    elem.parentNode.selectedIndex;
}
```

And there is at least one more just like it. Logically, the expression is a no-op. The comment indicates that somebody once saw it cause some side effect in an unspecified version of Safari. 

For this reason, no lint will pass such a line. This comment confirms that our lint was forced to ignore the transgression.

```javascript
// eslint rule "no-unused-expressions" is disabled for this code
```

If a fuse blows, you don't put tinfoil between the contacts; it's trying to tell you that something is wrong.

Furthermore, what makes us think that the parent of an `OPTION` will be a `SELECT`? Could be an [`OPTGROUP`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup).

As this issue has the potential to foul up form input, it should be given a high priority.

I'll leave the solution to this one as an exercise for the moment. A solution was given to Resig several years ago and discussed in the old jQuery forum, as well as on Usenet. He mentioned something about not wanting to add an extra line and confirmed that he couldn't find a browser that "proved" it didn't work (i.e. show me where it fails). Hint: the no-op line has the answer and discards it. ;)

### Link to test case ###

No test case. Not known for sure where or when it might fail. Do know that `SELECT` elements without at least one `OPTION` containing a `SELECTED` attribute are vulnerable (as that creates an *implicitly* selected `OPTION`).

Likely not an issue once the page is loaded, but without reviewing the DOM standards, can't say for sure when browsers are required to set the `selected` property to reflect an implicit selection. Instead of worrying about that (or testing), let's just fix the logic.

PS. There is an attempt at a feature test that sets a flag that isn't checked in relation to the above line, but it is checked in other areas of the code with similar lines:

```javascript
var input = document.createElement( "input" ),
		select = document.createElement( "select" ),
		opt = select.appendChild( document.createElement( "option" ) );

	...

	// Support: IE <=11 only
	// Must access selectedIndex to make default options select
	support.optSelected = opt.selected;
```

One problem with that test is that it is testing a *disembodied* `SELECT` and there's certainly no guarantee that it will pass based on any standard that I know of (again, would have to consult the specifications). So false positives for this "problem" will likely occur, adding additional no-op execution for no reason at all. I know that jQuery is supposed to work with document fragments, but the `SELECT` tested is without even that.

Another problem is it doesn't test the assumed solution to see if it improves the situation, only that there may be a problem. Again, this will result in no-op execution without any reason to expect it will do anything useful.

A third problem is that the name of the flag (`optSelected`) is not very descriptive of what it is supposed to mean. If it wasn't tacked on to this `support` object, we could make the name as long as we want as the minification process would reduce it. Regardless, saving a few bytes at the expense of clarity is a bad trade (not to mention that HTTP compression will likely end up saving the bytes anyway).

If we just fix the logic for the half dozen related lines then we don't need this test at all. And BTW, what does "Support: IE <= 11 only" imply? See similar comments throughout and they don't make a lot of sense to me.

**Comment by dmethvin** [comment]
These lines have been around for a LONG time and I can remember at least once trying to remove it and finding out that the current Safari or Webkit still needed it. Can you review the blame for that file and determine its history? There are probably a few related tickets, but they will be several years old and may take some time to find. As the person advocating a non-essential change it's up to you to show that this is safe to do.

**Comment by david-mark** [comment]
> These lines have been around for a LONG time and I can remember at least once trying to remove it and finding out that the current Safari or Webkit still needed it.

I am aware they've been around a LONG time (and please don't shout). I posted a solution several years ago on Usenet, which was then relayed to Resig, who decided not to use it. Though, as a result, he did add an extra line to try to support `OPTGROUP` in a different are of the code:

```javascript
var parent = elem.parentNode;
			get: function( elem ) {

			/* eslint no-unused-expressions: "off" */

			var parent = elem.parentNode;
			if ( parent && parent.parentNode ) {
				parent.parentNode.selectedIndex;
			}
			return null;
		},
		set: function( elem ) {

			/* eslint no-unused-expressions: "off" */

			var parent = elem.parentNode;
			if ( parent ) {
				parent.selectedIndex;

				if ( parent.parentNode ) {
					parent.parentNode.selectedIndex;
				}
			}
		}
```

Look carefully and there's a bug in there in that the getter and setter are not in agreement in how they implement the no-op hack.

So we've established that they are *old* mystical incantations. As for "needing" them, that's incorrect.

> Can you review the blame for that file and determine its history? There are probably a few related tickets, but they will be several years old and may take some time to find.

No need. I've provided enough information in the post to fix the code (and without going back and searching for the original proposed answer). Will provide it again if nobody comes up with it. Hint: the solution is not to simply delete the no-op lines (though they certainly vanish along with the indirect feature test).

Pulling back a bit from the posted snippet to see its context provides another clue:

```javascript
"selected": function( elem ) {
			// Accessing this property makes selected-by-default
			// options in Safari work properly
			if ( elem.parentNode ) {
				elem.parentNode.selectedIndex;
			}

			return elem.selected === true;
		}
```

Again, we have a terse and ambiguous comment (and a bit oddly stated as well). What does it mean by "makes selected-by-default options in Safari work properly"?

> As the person advocating a non-essential change it's up to you to show that this is safe to do.

Once the answer is posted, it will be clear that no such assurances are needed. This is a basic logic problem; as is usually the case in browser scripting, it's not about gathering empirical evidence as such evidence proves nothing (and certainly not when we are talking about an unevenly applied mystical incantation).

Testing comes after the logic is clearly fixed and I have to figure there are existing unit tests for this. If not, they should be added. But I'd bet my house they won't be needed. ;)

**Comment by david-mark** [comment]
Anyone? Anyone know the effects? :)

**Comment by dmethvin** [comment]
Sorry but let me repeat. You're asking because you want to make changes to code with no bugs currently open against it. Please do the homework to go back and look into the browser bugs that caused those seemingly meaningless lines to be put into the source. If they're no longer needed because the browsers they occurred in are no longer supported, we can remove them. Otherwise, check out the list of bugs reported by users of the library and see if you can help there.

**Comment by david-mark** [comment]
> Sorry but let me repeat. You're asking because you want to make changes to code with no bugs currently open against it.

You aren't listening. Analysis trumps evidence gathering (i.e. don't release code that seems to work by coincidence). Customers don't want to be guinea pigs and can't be relied upon to report every odd quirk they encounter.

> Please do the homework to go back and look into the browser bugs that caused those seemingly meaningless lines to be put into the source.

You already said that and I responded that the solution is not to remove the lines, but to replace them with logic that makes sense. You need to do your homework on this as I posted the solution (and it was discussed in your forums) several years ago.

> If they're no longer needed because the browsers they occurred in are no longer supported, we can remove them.

Wrong end of the stick. This is not how browser scripting is done; have to proactively anticipate issues as they tend to come and go as browsers create and then fix inconsistencies.

> Otherwise, check out the list of bugs reported by users of the library and see if you can help there.

That's the treadmill this project has been on for a decade and a big reason the code is in the state that it is.

**Comment by markelog** [comment]
There is no 
```js
if ( elem.parentNode ) {
    elem.parentNode.selectedIndex;
}
```
in our current code base, there is only this [bit](https://github.com/jquery/jquery/blob/1754e315f8a7760bcdc162712d2be7fee058fdc2/src/attributes/prop.js#L92-L126) which has clear explanation why and what.

Thanks for the analysis though, would help if you wouldn't that verbose next time though :)

**Comment by david-mark** [comment]
> in our current code base, there is only this bit which has clear explanation why and what.

Not sure when you deleted the other occurrence as it is certainly present in my fork (which is less than a month old). But that's irrelevant.

The code you linked to is the same nonsense that I discussed with Resig and others several years back. Nothing has changed, although if you look *carefully*, it's not even applied evenly (as I mentioned above).

> Thanks for the analysis though, would help if you wouldn't that verbose next time though :)

Most of the "verbosity" in this issue comes from repeatedly explaining the same thing as the responses repeatedly missed the point (as did this one).

Again, the code is complete nonsense (regardless of attempts to rationalize it). The correct solution was posted several years ago and dismissed because it might have added a line or two. In all the responses here, nobody has addressed that point at all.

**Comment by david-mark** [comment]
Guess I have to spell out the answer (again).

Q. What are we trying to fix here?

A. Here is an example:

```
<select>
<option>Test 1</option>
<option>Test 2</option>
</select>
```

Q. What's missing?

A. None of the `OPTION` elements have `SELECTED` attributes, so the first `OPTION` is *implicitly* selected.

Q. What's the issue with that?

A. Some browsers have been known to delay setting the `selected` property of the *implicitly* selected `OPTION`. It's a very old problem and typically isn't an issue unless trying to reference this property before the document is ready.

Q. So what should we do about it?

A. First of all, lose the indirect feature test as it is using a disembodied `SELECT`. Second, get rid of the `set` hack as once we set the property, it is clearly no longer an issue. And third, get rid of the `get` hack as well as it simply discards the answer.

Finally, in the `attr` (and/or `prop`) method, change the way you check whether an `OPTION` is selected. As hinted above, the hack references and then throws away the `selectedIndex` property. That property *is* the answer to the problem of determining whether an `OPTION` is selected or not.

```javascript
var isOptionSelected, elSelect = elem.parentNode;

if (elSelect.tagName.toLowerCase() == "optgroup") {
    elSelect = elSelect.parentNode;
}

isOptionSelected = elem === elSelect.options[elSelect.selectedIndex];
```

See how that makes logical sense, deducing the `selected` value by using the `selectedIndex` property of the `SELECT`, as opposed to throwing it away? This is the correct solution as long as the `SELECT` does not have the `MULTIPLE` attribute.

Regardless, neither "solution" makes sense for a multi-select as there are no *implicitly* selected options for those controls. Will leave the check for that as an exercise.

**Comment by markelog** [comment]
> Just guessing that is what is meant by the "not in our current codebase" remark.

It is what i meant and this is still not a sizzle repo. Sizzle and jquery are different projects, these differences are important, in this case this is important because we are planning to remove sizzle dep entirely.

> Some browsers have been known to delay setting the selected property of the implicitly selected OPTION. It's a very old problem and typically isn't an issue unless trying to reference this property before the document is ready.

You should start from that, but with the test-case on jsbin/jsfiddle that's what others were trying to tell you.

> First of all, lose the indirect feature test as it is using a disembodied SELECT. Second, get rid of the set hack as once we set the property, it is clearly no longer an issue. And third, get rid of the get hack as well as it simply discards the answer.

And that's what you should do in pull requests with new tests and without falling old tests.

> the code you linked to is the same nonsense that I discussed with Resig and others several years back (and cited here again). Nothing has changed, although if you look carefully, the hack is not even applied evenly (as I also mentioned above)...

And that's what should be avoided. Since important information tend to get lost if you supply it with philosophy, unrelevant stories and etc.

See more on https://contribute.jquery.org/

**Comment by david-mark** [comment]
> It is what i meant and this is still not a sizzle repo. Sizzle and jquery are different projects, these differences are important, in this case this is important because we are planning to remove sizzle dep entirely.

That's a ticket I definitely planned to create (dump Sizzle). That will eliminate the obvious problem I raised about them not being in sync.

> You should start from that, but with the test-case on jsbin/jsfiddle that's what others were trying to tell you.

You aren't following at all. The logic I am replacing makes no *sense*.

> And that's what you should do in pull requests with new tests and without falling old tests.

The ticket was closed because nobody seemed to understand the issue (thought I was saying to just remove the hack). Once it is closed *nobody* is going to work on it (including me).

> And that's what should be avoided.
