### ISSUE TITLE
empty when resolves with 1 undefined argument in jQuery 3 (was 0 arguments in jQuery 2)

### ISSUE THREAD

**Issue by i23098** [jquery/jquery#3442]
### Description ###
I use dynamic array of deferreds to load 0 to N things and then loop through the arguments in the done callback. Upgrading to jQuery 3.1.1 from 2.2.4 and now my code breaks :(

### Link to test case ###
Minimal test case is call $.when with no arguments, so it should resolve with no arguments too...

2.2.4 - https://jsfiddle.net/nuzy6b43/ - This will correctly have 0 arguments in the done callback
3.1.1 - https://jsfiddle.net/4qys5duk/ - This will incorrectly have 1 argument in the done callback

**Comment by gibson042** [comment]
Nice catch. Thanks, @i23098!
