### ISSUE TITLE
Deprecate isArrayLike

### ISSUE THREAD

**Issue by david-mark** [jquery/jquery#3443]
### Description ###

Think the code and comments say it all:

```javascript
function isArrayLike( obj ) {

	// Support: real iOS 8.2 only (not reproducible in simulator)
	// `in` check used to prevent JIT error (gh-2145)
	// hasOwn isn't used here due to false negatives
	// regarding Nodelist length in IE
	var length = !!obj && "length" in obj && obj.length,
		type = jQuery.type( obj );

	if ( type === "function" || jQuery.isWindow( obj ) ) {
		return false;
	}

	return type === "array" || length === 0 ||
		typeof length === "number" && length > 0 && ( length - 1 ) in obj;
}
```

There has been at least one known issue with iOS and we had to bend our own rules to handle IE. Quite predictable when it comes to these sorts of methods.

Clearly would be much cleaner to avoid this thing and would save time dealing with obscure issues. It's not as if jQuery needs an `isArrayLike` method as it has nothing to do with the DOM. *Certainly* we don't need to call it in the core.

There are only three methods that call this: `makeArray`, `each` and `map`. Clearly they each have specific needs and the latter two have "internal use only" arguments.

In the middle of dealing with similar issues related to `isPlainObject`, which was simple enough to untangle. This one should be even easier and then we can avoid the sort of issues that have dogged this similarly ill-advised method.

Solid ECMAScript code should not rely on such "crutch" functions and history shows they are nothing but trouble, particularly when they try to deal with *both* host and native objects.

See here:

https://github.com/jquery/jquery/issues/3430

Should be reopened as there were bugs discovered during the investigation and refactoring that must have been missed when it was prematurely closed.

When we get done with that one, I'll untangle this one in similar fashion.

### Link to test case ###

No test case required.

**Comment by gibson042** [comment]
Optimizations are always considered, but I see no need to keep this issue open because there is no external demand necessitating a change.

**Comment by david-mark** [comment]
Shouldn't need to wait for user complaints to make improvements. And this one is more about getting rid of an inappropriate, overly complicated and obviously trouble-prone function. Such motivation needs to come from within.

Understand that time is limited due to a never-ending stream of bugs, but stopping for a moment to consider and deal with root causes will pay dividends by preventing future issues.
