### ISSUE TITLE
Redo jQuery.extend for clarity, safety and performance

### ISSUE THREAD

**Issue by david-mark** [jquery/jquery#3444]
### Description ###
Here is the new `jQuery.extend`:

```javascript
// We shouldn't call jQuery.extend from inside the core (outside code could change or delete it)
// Extra dot operations affect performance as well
var extend;

extend = jQuery.extend = jQuery.fn.extend = ( function() {

	/* eslint-disable eqeqeq */
	// Extra "=" makes no sense when both sides are always the same type
	// TODO: Adjust lint rules so this is required only when it makes sense for clarity

	// jQuery.isPlainObject is deprecated
	function isPlainObject( obj ) {
		var proto;

		if ( toString.call( obj ) == "[object Object]" ) {
			proto = getProto( obj );

			// Objects foolish enough to have prototypes with their own - hasOwnProperty - property are not supported
			return !proto || proto.hasOwnProperty( "hasOwnProperty" );
		}

		return false;
	}

	return function() {
		var source, name, sourceProperty, targetProperty, clonedTargetProperty,
			target = arguments[ 0 ],
			i = 1,
			length = arguments.length,
			deep = false;

		// Handle a deep copy situation
		if ( typeof target == "boolean" ) {
			deep = target;

			// Skip the boolean and the target
			target = arguments[ i ];
			i++;
		}

		// Extend jQuery itself if only one argument is passed

		if ( i == length ) {
			target = this;
			i--;
		}

		// Loop through n objects
		for ( ; i < length; i++ ) {
			source = arguments[ i ];

			// Only deal with non-null/undefined values
			// NOTE: How was the previous source != null getting away with loose comparison?
			// In any event, it is obfuscating to do loose comparison to null
			if ( source !== null && source !== undefined ) {

				// Extend the base object
				for ( name in source ) {
					targetProperty = target[ name ];
					sourceProperty = source[ name ];

					// Prevent infinite loop
					if ( target !== sourceProperty ) {
						if ( deep && sourceProperty ) {
							clonedTargetProperty = null;

							if ( Array.isArray( sourceProperty ) ) {
								clonedTargetProperty = targetProperty &&
									Array.isArray( targetProperty ) ?
									targetProperty : [];
							} else if ( isPlainObject( sourceProperty ) ) {
								clonedTargetProperty = targetProperty &&
									isPlainObject( targetProperty ) ?
									targetProperty : {};
							}

							target[ name ] = clonedTargetProperty ?
								extend( true, clonedTargetProperty, sourceProperty ) :
								sourceProperty;

						// Don't bring in undefined values
						} else if ( sourceProperty !== undefined ) {
							target[ name ] = sourceProperty;
						}
					}
				}
			}
		}

		// Return the modified object
		return target;
	};
} )();

```

Much easier to read, module-safe and certainly a bit faster. Lessons learned in this refactoring will apply to much of the rest of the code.

Let's go over it bit by bit.

```javascript
// We shouldn't call jQuery.extend from inside the core (outside code could change or delete it)
// Extra dot operations affect performance as well
var extend;

extend = jQuery.extend = jQuery.fn.extend = ( function() {
```

As noted, it is unsafe (and a drag on performance) to call `jQuery` methods from inside the module. The object is "exported" by tacking it onto the `window` object, which adds it to the global scope. See here:

https://github.com/jquery/jquery/issues/3440

So we create a local `extend` function for the recursive calls. Another issue should be created to address all of the other references to `jQuery.extend`.

```javascript
/* eslint-disable eqeqeq */
// Extra "=" makes no sense when both sides are always the same type
// TODO: Adjust lint rules so this is required only when it makes sense
```

ESLint is simply misconfigured as the extra `=` is redundant in cases where both sides of the comparison are the same type. Furthermore, it is inconsistent as the loose *inequality* operator is used throughout jQuery without any warnings or disabling of the lint (e.g. `!= null`).

```javascript
// jQuery.isPlainObject is deprecated
function isPlainObject( obj ) {
	var proto;

	if ( toString.call( obj ) == "[object Object]" ) {
		proto = getProto( obj );

		// Objects foolish enough to have their own - hasOwnProperty - property are not supported
		return !proto || proto.hasOwnProperty( "hasOwnProperty" );
	}

	return false;
}
```

This was the *last* function to reference the now deprecated `isPlainObject`. So moved a slimmed down version of it to this function. Some parts of the original are redundant for its use in `extend`, so were thrown out. See here:

https://github.com/jquery/jquery/issues/3430

Note that objects passed to `extend` that are foolish enough to have a custom `hasOwnProperty` property on their constructor's prototype are not supported. If squeamish about that, we can change to (or add) another method to this check. Also note that the function is no longer susceptible to meddling with `constructor` properties or outside changes to the `jQuery` object (e.g. overriding the `isPlainObject` method). And finally note that the use of `hasOwn` instead of the `hasOwnProperty` method of the prototype would be redundant here. Already checked that the object has a prototype and custom `hasOwnProperty` properties are explicitly disallowed (behavior for such prototypes is undefined).

```javascript
return function() {
	var source, name, sourceProperty, targetProperty, clonedTargetProperty,
		target = arguments[ 0 ],
		i = 1,
		length = arguments.length,
		deep = false;
```

We return the inner function to create a closure containing the now "private" `isPlainObject` function. Note that `target` was originally assigned:

```javascript
target = arguments[ 0 ] || {}
```

This made no sense. The [documentation for this method](https://api.jquery.com/jquery.extend/) indicates that the first (or second on "deep" usage) is to be an *object*. For example, the original assignment would allow for `false`, in contradiction with this admonition in the documentation:

> Warning: Passing false for the first argument is not supported.

Furthermore, passing an empty string, the number `0` or `null` for this argument would have the same undocumented effect. The behavior for all of these cases should be undefined (i.e. pass nonsense at your own risk and expect exceptions). The best way to help users more quickly identify such missteps is with "scaffolding" code that can be removed for production builds:

```javascript
// Example only
if ( typeof target == "number" ) {
    throw new Error( "Please pass objects, not numbers!" );
}
```

Leave that for a future issue as AFAIK, the "compiler" has no such capabilities at this time.

On this subject, this bit was removed:

```javascript
// Handle case when target is a string or something (possible in deep copy)
	if ( typeof target !== "object" && !jQuery.isFunction( target ) ) {
		target = {};
	}
```

How did we figure that was possible for the "deep" use case? The two recursive calls pass only objects (`Object` objects or `Array` objects to be specific). Anyway, one less `isFunction` call, which is good as it will be deprecated in future as well. Like `isPlainObject` and `isArrayLike`, it's simply an overly generalized crutch that encourages poor designs and has suffered from documented issues related to our own poor design decisions in trying to handle both host and native objects with a single function. But I digress, just trying to put all of these suggested changes into context as part of a unified vision that takes into account best practices for ECMAScript and browser scripting (as well as the history of issues with this project).

The rest of the modifications are mostly renamed variables, simplified structures, performance improvements and the aforementioned banishment of the "exported" `jQuery` object.

Not impossible that I could have missed something as this was some seriously obfuscated (and under-commented) code; however, it passed all the unit tests on the first try. So if there is something wrong with the refactoring then the unit tests are insufficient. In either case, *something* needs to change.

All of these changes are in [my fork](https://github.com/david-mark/jquery), which is starting to diverge considerably from the trunk. I advise that we allot time from the day-to-day issues to concentrate on improvements that make the code easier to follow and are therefore likely to help prevent future issues. The fact that we have perpetual issues over a decade indicates that we need to take a step back and look at the bigger picture.

We are on a treadmill due to ill-advised design decisions that date back a decade, unclear code (some of which should not be getting past ESLint) and under-documented, overly complicated features. This all leads to users finding bugs and either creating issues here (or simply guessing how to get around them), which continues the cycle of confusion and busywork.

These problems weren't considered to be critical during the ascent of this library as the average Web developer had no clue how to deal with difference between the old IE versions, which had varying degrees of deviation from DOM standards. Furthermore, alternative solutions were minimal and usually featured many of the same mistakes. Those days are long gone and this library is very clearly in (much-deserved) decline. If we don't clean up our act now, it will be *gone* in a few years. Not gone from the Web of course; that will take ages, but certainly considered an irrelevant waste of time and mostly harmful (which it is in its present state).

### Link to test case ###

Behavior unchanged, other than performance. Mostly about clarity.

**Comment by gibson042** [comment]
This seems to be bundling together many opinionated changes, but I am interested in reviewing the core of it. Please submit a pull request without the `isArray`/`isPlainObject` reference changes and strict→loose comparison changes.

**Comment by david-mark** [comment]
> This seems to be bundling together many opinionated changes, but I am interested in reviewing the core of it. Please submit a pull request without the isArray/isPlainObject reference changes and strict→loose comparison changes.

As noted, this one is directly related to this prematurely closed issue:

https://github.com/jquery/jquery/issues/3430

Part of the rewrite involves embedding a slimmed down version of `isPlainObject`, which was the last barrier to deprecating that method.

And what about `isArray`? I neither mentioned it, nor changed the extant calls to that method.

**Comment by gibson042** [comment]
> Part of the rewrite involves embedding a slimmed down version of `isPlainObject`, which was the last barrier to deprecating that method. That was the main point of it.

That may have been your motivation, but embedding vs. referencing extant is an independent change. We may very well choose to accept `jQuery.extend` changes without doing anything regarding `jQuery.isPlainObject`.

> And what about `isArray`? I neither mentioned it, nor changed the extant calls to that method. To my surprise, it was already using the `Array` method for those (expect that's why jQuery.isArray has been deprecated).

Indeed; that was my mistake and no action is required there.

**Comment by david-mark** [comment]
> That may have been your motivation, but embedding vs. referencing extant is an independent change. We may very well choose to accept jQuery.extend changes without doing anything regarding jQuery.isPlainObject.

I agree that they could be separated, but not in my fork as it would be backtracking. Should also see that the changes I made to `isPlainObject` are for the better (deprecated or not).

**Comment by gibson042** [comment]
Closing per @david-mark's comments.

**Comment by david-mark** [comment]
> Closing per @david-mark's comments.

Simply said that I wasn't backtracking in *my* fork. Clearly you are free to do what you want in the trunk (or not).
