### ISSUE TITLE
"Ready" Callbacks Should Not be Deferred

### ISSUE THREAD

**Issue by david-mark** [jquery/jquery#3447]
### Description ###

Hard to imagine a more critical requirement than running `ready` callbacks as fast as possible and in the right order (for apps disorganized enough to require more than *one*) in relation to each other, as well as to any *other* calls intended to happen *after* the last `ready` callback runs. For example, there could very well be mashups out there that assume that `load` listeners are guaranteed to run *after* the `ready` "event" fires. We know that was never true, but now we've added all sorts of new and bizarre possibilities.

```javascript
// Catch cases where $(document).ready() is called
// after the browser event has already occurred.
// Support: IE <=9 - 10 only
// Older IE sometimes signals "interactive" too soon
if ( document.readyState === "complete" ||
	( document.readyState !== "loading" && !document.documentElement.doScroll ) ) {

	// Handle it asynchronously to allow scripts the opportunity to delay ready
	window.setTimeout( jQuery.ready );

} else {

	// Use the handy event callback
	document.addEventListener( "DOMContentLoaded", completed );

	// A fallback to window.onload, that will always work
	window.addEventListener( "load", completed );
}
```

Would also seem critical not to break compatibility with previous jQuery versions with regard to this behavior.

In short, this operation needs to be kept as simple as possible. The implementation in jQuery 3 fails this requirement; in other words, it's asking for (and causing) trouble on multiple levels:

```javascript
// The deferred used on DOM ready
var readyList = jQuery.Deferred();

jQuery.fn.ready = function( fn ) {

	readyList
		.then( fn )

		// Wrap jQuery.readyException in a function so that the lookup
		// happens at the time of error handling instead of callback
		// registration.
		.catch( function( error ) {
			jQuery.readyException( error );
		} );

	return this;
};
```

Use of the very complicated `Deferred` object perpetually causes unit tests to fail due to operations failing to complete on schedule. Should be hint enough not to tangle up `ready` callbacks with that code. Furthermore, `Deferred` callbacks are wrapped in timeouts with *unspecified* delays.

This is all just begging for trouble; no amount of testing can prove that the scheme will work as expected, *every time* in all browsers. And as we already know how to very simply make the `ready` callbacks run in the correct order every time in all browsers, can't imagine any rationalization for introducing the slightest bit of uncertainty, added complexity or incompatibility.

I'm not saying that one of the browsers alleged to be "supported" in 3 can be easily coaxed into running the callbacks in the wrong order. The point is that no browser (buggy or not) will *ever* run the callbacks in the wrong order if timeouts are *not* used. Using timeouts for this is just pointless and ill-advised.

Then we throw exceptions in *another* timeout:

```javascript
jQuery.readyException = function( error ) {
	window.setTimeout( function() {
		throw error;
	} );
};
```

This is doubling down on the pointlessness.

Furthermore, all these unneeded, ill-advised timeouts are absolute *poison* for debugging; in the event of an exception, it's obviously best to break on the line that failed (with an intact aftermath environment to inspect), not in a timed anonymous callback. In short, we are just getting in the way of debugging for no good reason.

Think of the debugger as a cop. It's always better to catch the perpetrator of a crime (an unexpected occurrence causing an exception) at the scene so that evidence can be gathered *immediately*. Catching an exception and re-throwing it after a delay is like reviewing a tape of the crime and filing a report about it later (after the scene has been long since contaminated). Sometimes the perp strikes again in predictable fashion and sometimes they don't; best to catch them the *first* time.

Finally, there's the obvious fact that this very critical behavior has been wildly changed from what would have been expected in previous versions (themselves no great examples of consistency in this department).

I read the brief attempt at an explanation for this decision in the issue created for the debugging issues (revisited here). I'm not buying the "consistent interface" line; don't even understand what it means. It's neither consistent with previous jQuery versions, nor with what browsers are expected to do with code like this:

```javascript
document.addEventListener('DOMContentLoaded', function() {
    ...
});

document.addEventListener('DOMContentLoaded', function() {
    ...
});
```

Not that I think it's good form to use two such listeners, but they should be expected to be called in the correct sequence and *nothing* will happen in between the two calls. On the other hand, if timeouts are thrown into the mix:

```javascript
document.addEventListener('DOMContentLoaded', function() {
    window.setTimeout(function() {
        ...
    }, 1);

    window.setTimeout(function() {
        ...
    }, 1);
});

```

...it opens up the possibility of the browser handling asynchronous events in between the two calls. This second example is similar to what jQuery is now doing. I say similar as there is also the extra complexity of the Promise-like `Deferred` behavior. And, of course, delays are unspecified in jQuery, presumably to save the extra two bytes. :(

Would take a much better explanation to rationalize this very clearly wrong move. Haven't bothered going back to ready the related discussions as know from experience that no rational explanation is possible.

Please don't take my word alone on this one. Ask around in any reputable forum for ECMAScript and browser scripting. Ask anybody with experience going back to last decade if they've ever heard of weird things happening related to timeout ordering or if wrapping callbacks in try-catch (or throwing exceptions in timeouts) should be expected to improve or degrade the debugging experience.

### Link to test case ###

No test case needed. Don't need to go looking for trouble in such a case.

**Comment by gibson042** [comment]
> Haven't bothered going back to ready the related discussions

Please do so, as this was an explicit design decision. #1823 is a good starting point.

**Comment by david-mark** [comment]
> Please do so, as this was an explicit design decision.

I know it was, but it was an ill-advised decision for sure. There's really no justifying something like this, but I'll glance at the linked issue.

**Comment by david-mark** [comment]
I looked at it and, as expected, still *thoroughly* disagree. Once a "ready" callback throws an exception, all bets should be off. No more callbacks, period.

At that point, we have no idea what the state of the application or document is and the developer should be in the debugger looking at the stopped code, traversing the stack trace, looking at variable values, etc. to determine what went wrong. More callbacks will just muddy the waters.
