### ISSUE TITLE
Offset Module: Get Rid of getWindow Function

### ISSUE THREAD

**Issue by david-mark** [jquery/jquery#3449]
### Description ###

Working on deprecating `isWindow`, I ran into this internal function in the offset module:

```javascript
/**
 * Gets a window from an element
 */
function getWindow( elem ) {
	return jQuery.isWindow( elem ) ? elem : elem.nodeType === 9 && elem.defaultView;
}
```

The comment is incorrect. It returns a reference to `window` if passed a reference to a `window` or `document` node, but it returns `false` if passed a reference to an element node.

As a side note, it seems very odd to try to derive a `window` reference at all, considering that many methods simply reference the `window` that is passed to the core during initialization.

For example:

```javascript
// Miscellaneous
"target": function( elem ) {
	var hash = window.location && window.location.hash;
	return hash && hash.slice( 1 ) === elem.id;
}
```

Or perhaps that's just a bug. Do see that some methods at least attempt to work with multiple windows. But I digress.

The inappropriately named `getWindow` function is used in two places. As always, if we can reduce that number to one, we can get rid of the function (and the costs associated with calling it).

First one is in the `offset` method:

```javascript
doc = elem.ownerDocument;
win = getWindow( doc );
```

So that obviously reduces to:

```javascript
doc = elem.ownerDocument;
win = doc.defaultView;
```

The other is here:

```javascript
// Create scrollLeft and scrollTop methods
jQuery.each( { scrollLeft: "pageXOffset", scrollTop: "pageYOffset" }, function( method, prop ) {
	var top = "pageYOffset" === prop;

	jQuery.fn[ method ] = function( val ) {
		return access( this, function( elem, method, val ) {
			var win = getWindow( elem );

			if ( val === undefined ) {
				return win ? win[ prop ] : elem[ method ];
			}

			if ( win ) {
				win.scrollTo(
					!top ? val : win.pageXOffset,
					top ? val : win.pageYOffset
				);

			} else {
				elem[ method ] = val;
			}
		}, method, val, arguments.length );
	};
} );
```

That confirms the function is expected to return a "falsey" value when passed an element reference. Something like this should replace the `getWindow` call:

```javascript
var win;
			
if ( elem.window === elem ) {
	win = elem;
} else if ( elem.nodeType == 9 ) {
	win = elem.defaultView;
}
```

...and then that function can be deleted.

One less `isWindow` call in the bargain as well. As that one is public, it will have to be deprecated rather than deleted. That's next.

HTH

PS. Consider that a large number of issues are related to the ill-advised design of the object model, which tries to deal with elements, documents and windows (among other things) using a *single* constructor. It's an awkward interface for users as well. Was a similar mistake with `attr`, which tried to deal with both (HTML) properties and (XML) attributes using a single function.

### Link to test case ###

No test case needed. Simply restructuring.

**Comment by gibson042** [comment]
I agree with the proposed changes to eliminate `getWindow`. Pull request welcome.

**Comment by david-mark** [comment]
Not sure how to do that with my fork in its current state. Would have to create another fork I expect. This change came about while eliminating the bigger issue of `isWindow` and there are a dozen other changes in my fork at this point.

Might be easier for somebody else to fix this based on my suggestions. As was the case with this one (which was closed due prematurely for same reason):

https://github.com/jquery/jquery/issues/3444

**Comment by ztwoem** [comment]
good idea, i like them

http://www.ztwshop.com

<a href="http://www.hobbywingstore.com">hobbywing ESC </a>
<a href="http://www.sunraysat.com/zgemma-star-h-2s-satellite-receiver.php" >Zgemma star H.2S</a></p>
<a href="http://www.keruistore.com">kerui alarm </a>
<a href="http://www.sunraysat.com/vu-plus-solo-4k-twin-2x-dvb-s2-linux-satellite-receiver.php" alt="Vu Solo 4K with Twin Tuners">Vu Solo 4K </a>
<a href="http://www.keruistore.com">kerui alarm Store </a>
 <a href="http://www.hikvisionstores.com">Hikvision Store </a>
<a href="http://www.sunraysat.com/vu-solo-4k-2x-dvb-s2-tuners-1x-dvb-c-t2-tuner-satellite-receiver-with-1tb-hdd.php" alt="Vu+ Solo 4K with 4 Tuners" title="Vu+ Solo 4K with 4 Tuners">Vu+ Solo 4K </a>
<a href="http://www.sunraysat.com/vu-solo2-vu-plus-solo-2-vusolo2-twin-tuner-linux-reciever-3f-wifi-iptv-enigma2-satelllite-receiver.php" alt="Vu+ Solo 2 with Twin Tuners" title="Vu+ Solo 2 with Twin Tuners">Vu+ Solo2 </a>
<a href="http://www.sunraysat.com/vu-duo2-duo2-2-dual-dvb-s2-tuners-satellite-receiver-full-hd-satellite-receiver.php" alt="Vu Duo2 with Twin Tuners" title="Vu Duo2 with Twin Tuners">Vu Duo2 </a>
<a href="http://www.sunraysat.com/dm800-hd-se-satellite-receiver-wifi-with-sim-2.2-dvb-s-satellite-receiver.php" alt="DM800 HD SE V2" title="DM800 HD SE V2">DM800 HD SE V2</a>
<a href="http://www.sunraysat.com/dvb-dm500-hd-sim2.10-card-enigma2-linux-set-top-box-satellite-receiver.php" alt="DM500 HD" title="DM500 HD">DM500 HD</a>
<a href="http://www.sunraysat.com/vu-solo2-solo2-2-snow-white-hd-twin-tuner-750-gb-hdd.php" alt="VU+Solo2 White IPTV Linux Receiver" title="VU+Solo2 White IPTV Linux Receiver">VU+Solo2 </a>
<a href="http://www.sunraysat.com/vu-solo-se-v2-dvb-s2-pvr-iptv-linux-enigma2-satellite-receiver.php" alt="VU+Solo2 White IPTV Linux Receiver" title="VU+Solo2 White IPTV Linux Receiver">VU+Solo Se V2</a>
<a href="http://www.sunraysat.com/vu-solo-pro-dvb-s2-s-enigma2-linux-hd-pvr-satellite-receiver.php" alt="VU+Solo Pro V3" title="VU+Solo Pro V3">VU+Solo Pro V3</a>
<a href="http://www.sunraysat.com/mag-254-iptv-3d-hd-with-wifi-tvbox.php" alt="Mag254 IPTV Box" title="Mag254 IPTV Box">Mag254 </a>
<a href="http://www.sunraysat.com/herobox-ex4-hd-dvb-s2-t2-c-3-tuners-satellite-receiver.php" alt="HeroBox EX4 HD with 3 Tuners" title="HeroBox EX4 HD with 3 Tuners">HeroBox EX4 </a>
<a href="http://www.sunraysat.com/herobox-ex3-hd-dvb-s2-t2-c-3-tuners-satellite-receiver.php" alt="HeroBox EX3 HD with 3 Tuners" title="HeroBox EX3 HD with 3 Tuners">HeroBox EX3 </a>
<a href="http://www.sunraysat.com/herobox-ex2-hd-dvb-s2-tuners-linux-enigma2-satellite-receiver.php" alt="HeroBox EX2 HD " title="HeroBox EX2 HD ">HeroBox EX2 </a>
<a href="http://www.sunraysat.com/sunray-solo-3-hd-pvr-enigma-2-linux-satellite-receiver.php" alt="X Solo Mini 3 Receiver" title="X Solo Mini 3 Receiver">X Solo Mini 3</a>
<a href="http://www.sunraysat.com/zgemma-star-h-2s-satellite-receiver.php" alt="Zgemma Star H.2S BOX" title="Zgemma Star H.2S BOX">Zgemma Star H.2S</a>
<a href="http://www.sunraysat.com/zgemma-star-h-2h-decoder-satellitare-s2-t2-enigma2-linux-hd-ip-tv-zgemma-star-h2-satellite-receiver.php" alt="Zgemma Star H.2H Box" title="Zgemma Star H.2H Box">Zgemma Star H.2H</a>

  <p><a href="http://www.sunraysat.com/zgemma-star-2s-twin-dual-dvb-s2-Tuner-satellite-receiver.php" alt="Zgemma Star 2S BOX" title="Zgemma Star 2S BOX">Zgemma Star 2S </a></p>
 <a href="http://www.keruistore.com">kerui alarm </a>
<a href="http://www.sunraysat.com/vu-plus-solo-4k-twin-2x-dvb-s2-linux-satellite-receiver.php" alt="Vu Solo 4K with Twin Tuners">Vu Solo 4K </a>

<a href="http://www.xtrons-store.com">Headrest DVD player  </a>
<a href="http://www.keruistore.com">kerui alarm Store </a>
<a href="http://www.projector-store.com">DLP HD projector </a>
<a href="http://www.hikvisionstores.com">Hikvision Store </a>
<a href="http://www.naviskautostore.com">Naviskauto Headrest DVD</a>
<a href="http://www.hikvisionstores.com">Hikvision Ip camera </a>
<a href="http://www.sunraybox.com">SunrayBox </a>
