### ISSUE TITLE
Don't Use Computed Styles to Get Inner/Outer Element Dimensions

### ISSUE THREAD

**Issue by david-mark** [jquery/jquery#3450]
### Description ###

Just the tip of the iceberg on the height/width/innerHeight/innerWidth/OuterHeight/OuterWidth functions, which suffer from the usual problems of trying to deal with elements (both HTML and XML), documents and windows with a single interface.

```javascript
return value === undefined ?

// Get width or height on the element, requesting but not forcing parseFloat
jQuery.css( elem, type, extra ) :

// Set width or height on the element
jQuery.style( elem, type, value, extra );
```

Using the outrageously complicated `css` method to get element dimensions is inefficient and simply begging for trouble, considering that it relies *multiple* calls to the also outrageously complicated (and occasionally buggy) `getComputedStyle` DOM method provided by browsers. See here for issues related to `left` and `top` styles:

https://github.com/jquery/jquery/issues/3448

And not at all clear what this comment is supposed to mean:

```javascript
// Get width or height on the element, requesting but not forcing parseFloat
```

Digging deeper, here are the "hooks" for computing the various flavors of height and width to the pixel:

```javascript
jQuery.each( [ "height", "width" ], function( i, name ) {
	jQuery.cssHooks[ name ] = {
		get: function( elem, computed, extra ) {
			if ( computed ) {

				// Certain elements can have dimension info if we invisibly show them
				// but it must have a current display style that would benefit
				return rdisplayswap.test( jQuery.css( elem, "display" ) ) &&

					// Support: Safari 8+
					// Table columns in Safari have non-zero offsetWidth & zero
					// getBoundingClientRect().width unless display is changed.
					// Support: IE <=11 only
					// Running getBoundingClientRect on a disconnected node
					// in IE throws an error.
					( !elem.getClientRects().length || !elem.getBoundingClientRect().width ) ?
						swap( elem, cssShow, function() {
							return getWidthOrHeight( elem, name, extra );
						} ) :
						getWidthOrHeight( elem, name, extra );
			}
		},

		set: function( elem, value, extra ) {
			var matches,
				styles = extra && getStyles( elem ),
				subtract = extra && augmentWidthOrHeight(
					elem,
					name,
					extra,
					jQuery.css( elem, "boxSizing", false, styles ) === "border-box",
					styles
				);

			// Convert to pixels if value adjustment is needed
			if ( subtract && ( matches = rcssNum.exec( value ) ) &&
				( matches[ 3 ] || "px" ) !== "px" ) {

				elem.style[ name ] = value;
				value = jQuery.css( elem, name );
			}

			return setPositiveNumber( elem, value, subtract );
		}
	};
} );
```

On a side note, we should simply throw an exception for disembodied elements or those with a `display` style of `none`. It's never been a good idea to try to show the latter, measure and then re-hide. As the documentation alludes to, it may not even "work" (not even sure what working would imply for such elements).

> jQuery will attempt to temporarily show and then re-hide an element in order to measure its dimensions, but this is unreliable...

No kidding, considering it arbitrarily decides on `block` for the temporary display style, in some cases:

```javascript
// Swappable if display is none or starts with table
// except "table", "table-cell", or "table-caption"
// See here for display values: https://developer.mozilla.org/en-US/docs/CSS/display
rdisplayswap = /^(none|table(?!-c[ea]).+)/,
cssShow = { position: "absolute", visibility: "hidden", display: "block" }
```

And can't tell at a glance (or from the "support" comment) what is supposed to happen with elements without parents (or that are part of document fragments). Nothing good I expect, but I digress (do that a lot with such stuff as every issue seems to lead to a half-dozen more).

Regardless, such results are *less* than meaningless if the element had the display style of `none`; they are completely confusing. Best to get rid of all that junk as the documentation also alludes to:

> This show-and-rehide measurement feature may be removed in a future version of jQuery.

So deprecate the practice immediately (e.g. log a warning that it is going away in the future, preferably the very near future).

Drilling down again, here is the `getWidthOrHeight` function:

```javascript
function getWidthOrHeight( elem, name, extra ) {

	// Start with offset property, which is equivalent to the border-box value
	var val,
		valueIsBorderBox = true,
		styles = getStyles( elem ),
		isBorderBox = jQuery.css( elem, "boxSizing", false, styles ) === "border-box";

	// Support: IE <=11 only
	// Running getBoundingClientRect on a disconnected node
	// in IE throws an error.
	if ( elem.getClientRects().length ) {
		val = elem.getBoundingClientRect()[ name ];
	}

	// Some non-html elements return undefined for offsetWidth, so check for null/undefined
	// svg - https://bugzilla.mozilla.org/show_bug.cgi?id=649285
	// MathML - https://bugzilla.mozilla.org/show_bug.cgi?id=491668
	if ( val <= 0 || val == null ) {

		// Fall back to computed then uncomputed css if necessary
		val = curCSS( elem, name, styles );
		if ( val < 0 || val == null ) {
			val = elem.style[ name ];
		}

		// Computed unit is not pixels. Stop here and return.
		if ( rnumnonpx.test( val ) ) {
			return val;
		}

		// Check for style in case a browser which returns unreliable values
		// for getComputedStyle silently falls back to the reliable elem.style
		valueIsBorderBox = isBorderBox &&
			( support.boxSizingReliable() || val === elem.style[ name ] );

		// Normalize "", auto, and prepare for extra
		val = parseFloat( val ) || 0;
	}

	// Use the active box-sizing model to add/subtract irrelevant styles
	return ( val +
		augmentWidthOrHeight(
			elem,
			name,
			extra || ( isBorderBox ? "border" : "content" ),
			valueIsBorderBox,
			styles
		)
	) + "px";
}
```

Consider this comment:

```javascript
// Some non-html elements return undefined for offsetWidth, so check for null/undefined
// svg - https://bugzilla.mozilla.org/show_bug.cgi?id=649285
// MathML - https://bugzilla.mozilla.org/show_bug.cgi?id=491668
if ( val <= 0 || val == null ) {
```

Nowhere does it check for the value of the `offsetWidth` property (nor do properties return anything). And if expecting an `undefined` value, why does the subsequent check test for negative numbers, zero, `null` *and* `undefined`?

Furthermore, XML elements (other than XHTML, which jQuery has never supported) aren't expected to have `offsetWidth` properties (which aren't checked here in any event). Do see calls to [`getClientRects`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects) [`getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect), both of which work with XML elements.

Continuing on to what happens if any of the above conditions are true:

```javascript
// Fall back to computed then uncomputed css if necessary
val = curCSS( elem, name, styles );
if ( val < 0 || val == null ) {
	val = elem.style[ name ];
}
```

An "uncomputed" style is clearly not an appropriate fallback for a computed style.

There's more intrigue in the `augmentWidthOrHeight` function, but I think the point is made.

Have to stop at this point and ask how any of this code is ever maintained with even the slightest degree of confidence? Can only figure that gathering evidence through testing is the only confirmation that updates to the logic make sense, but such evidence proves *nothing* in browser scripting as browsers are perpetually updated (almost constantly these days), old bugs fixed, new bugs introduced, etc.

Anyway, enough of all *that*; let's start with `innerWidth` (`innerHeight` is the same story of course). According to the documentation:

> Description: Get the current computed inner width for the first element in the set of matched elements, including padding but not border.

Use of the term "computed" (as in computed styles) is confusing as it would imply a string with units, but it goes on to say:

> This method returns the width of the element, including left and right padding, in pixels.

So combining the information in the two statements, can ascertain it returns a number of pixels, including any padding, but not the border. In other words, for *HTML* elements:

```javascript
return elem.clientWidth;
```

Seems really silly to jump through all of the previous hoops to try to deal with XML elements in the same function; but, in any event, it would be much easier to figure out what sort of element we are dealing with (HTML or XML) and act accordingly. They simply require different approaches. Realize that much of the hoops described above are actually specific to HTML elements as - for example - SVG elements (the most common XML elements found in HTML DOMs) have no CSS padding or borders to add or subtract.

Moving on to outerWidth, which is documented as:

> Returns the width of the element, including left and right padding, border, and optionally margin, in pixels.

In other words, unless the margin is requested:

```javascript
return elem.offsetWidth;
```

As far as the optional margin for the "outer" methods, that was clearly a design mistake. Doesn't necessarily require computing styles either, but would require some additional hoops to figure reliably without it. I'd deprecate that option as well and can't imagine a practical use case for it in any event. See the proposed solution to this issue:

https://github.com/jquery/jquery/issues/3448

For HTML elements, those two one-liners have been the standard in MSHTML since 1997 (IE 4). For other rendering engines, it's been the standard since around the turn of the century. For XML elements, a completely different approach is required and it won't resemble anything in the existing code. Would have been a much better idea to have a separate constructor (i.e. "subclass") for XML elements (as well as windows and documents).

The current design, which dates back to 2006, is the cause of many of the seemingly never-ending issues with jQuery. A proper design simply wouldn't be susceptible to many of the issues I see created here year after year and the situation won't change until the design problems are addressed. Starting from the inside is the only way to go at the moment as new constructors will require a complete reboot (would be jQuery in brand name only).

Also note that setting a dimension and then calling the same method without a dimension may well return a different number. But not even going to get into the "setter" bit at this point.

### Link to test case ###

No test cases required. Logic is clearly wrong and documentation confirms the code doesn't always work as advertised.

**Comment by gibson042** [comment]
Please provide either a test case demonstrating a bug, or a _concise_ description of the requested change, free of side notes and historical references. But note that [we try to return subpixel values when applicable](http://api.jquery.com/innerWidth/), so `clientWidth`/`offsetWidth`/etc. are insufficient.

**Comment by david-mark** [comment]
> Please provide either a test case demonstrating a bug, or a concise description of the requested change...

This isn't a bug, though there have clearly been issues over the years, including some that still exist and are mentioned in the documentation.

> or a concise description of the requested change

The only prolonged bits here is the code, which is a *big* part of the described problem.

> , free of side notes and historical references

They are for your benefit. There is a recurring theme to the issues I've opened over the last two weeks. In a nutshell, trying to deal with bugs is taking up time that would be better used analyzing what causes the perpetual presence of bugs.

> But note that we try to return subpixel values when applicable, so clientWidth/offsetWidth/etc. are insufficient.

The linked reference for `innerWidth` says nothing about subpixel values and I'd argue that trying to return such values would only make an already muddled interface even worse. Much worse.

And even if we did want to add yet another wrinkle involving possible subpixel dimensions, the bulk of the arguments here are still valid. Should really read this again, including the notes and historical context. Or wait until I update my fork with the related changes. ;)

**Comment by gibson042** [comment]
> There is a recurring theme to the issues I've opened over the last two weeks

Yes, and it's disincentivizing us to consider them but I'm offering you a remedy.

> For example, what's the point of having a `width` method that returns the same value as `css("width")`?

It doesn't always return the same value, because `.css("width")` ignores `border-box`.

**Comment by david-mark** [comment]
> Yes, and it's disincentivizing us to consider them but I'm offering you a remedy.

Which is completely backwards. Do you think I really care whether you actually use any of this stuff? The idea is that by considering what I'm saying and implementing the recommended changes, *you* will benefit in the long run. If not, you will remain on the bug fix treadmill.

> It doesn't always return the same value, because .css("width") ignores border-box.

If it does, it's self-imposed and a misstep so profound that it dwarfs everything in *this* issue. In short, the computed width is the computed width, regardless of the box model. This is why discussions are helpful as they can bring out related issues.

Come to think of it, I recall in a review about 7-8 years ago that I saw Resig subtracting the padding and border manually to try to "fix" the computed width in IE quirks mode or IE 5 or something. Or maybe he was confused by the `box-sizing` options, but there's no way in hell *that* logic should still be in there or that such behavior should be expected.

I see another ticket in our future. :)

**Comment by dmethvin** [comment]
> The idea is that by considering what I'm saying and implementing the recommended changes, you will benefit in the long run. If not, you will remain on the bug fix treadmill.

The bugs that matter the most are the ones that users of the library have reported. [They're over here.](https://github.com/jquery/jquery/issues) We'd appreciate help on those.

**Comment by david-mark** [comment]
> The bugs that matter the most are the ones that users of the library have reported. They're over here. We'd appreciate help on those.

I'm sure you would, but we have different agendas at the moment. Doesn't it stand to reason that if we clean up the code and fix things that have the potential to create bugs (and make fixing bugs more precarious and time-consuming) then we'll see a gradual decrease in the number of bugs reported (and less cases where bug fixes lead to new issues).

And granted, I'm not a user of the library, but most of *my* reports do indeed contain bugs. The trouble is that some of them are getting closed before the bugs are even discussed, let alone understood. Are they lesser bugs because I, a non-user, reported them? :)

Anyway, if we never set aside time to deal with the bigger issues, then the smaller issues become more plentiful and eventually overwhelm us (as they seem to be doing now). I know it's a quandary and I'm trying to help you understand (and fix) the big picture. Have been doing this a long time. ;)

**Comment by dmethvin** [comment]
> Are they lesser bugs because I, a non-user, reported them? :)

Actually yes! As soon as they actually impact someone using the library we'd look at the pain they were causing and determine their priority and impact on compatibility.

**Comment by dmethvin** [comment]
> Anyway, if we never set aside time to deal with the bigger issues, then the smaller issues become more plentiful and eventually overwhelm us (as they seem to be doing now).

That's not quite a fair assessment, one person is overwhelming the bug tracker at the moment so it's a manufactured situation. Fewer than 100 open bugs for a project with the installed base of jQuery is pretty darned good.

**Comment by david-mark** [comment]
> Actually yes! As soon as they actually impact someone using the library we'd look at the pain they were causing and determine their priority and impact on compatibility.

A bug is a bug, regardless of who reports it. Isn't it better to squash it before it bites others (assuming it hasn't already). Realize that many bugs go unreported as users simply go around them after getting "try this!" replies on StackOverflow or by random experimentation.

And I'm discussing far more than present bugs here, I'm talking about profound (and easily correctable mistakes) that can inhibit fixing present bugs, as well cause future bugs. Furthermore, I'm actually presenting solutions in most of the cases. In code. ;)

**Comment by david-mark** [comment]
> That's not quite a fair assessment, one person is overwhelming the bug tracker at the moment so it's a manufactured situation.

You've got the wrong end of the stick there. I was certainly not referring to *my* reports, rather all of the *rest* of them that are asserted to be taking up so much time that there's no time left to discuss anything else.

If you really think that I am "overwhelming" the bug tracker, then simply ignore my tickets. Wouldn't that beat all. :)

> Fewer than 100 open bugs for a project with the installed base of jQuery is pretty darned good.

Now you are dreaming (and perhaps think this is some sort of contest). This project has been going around in circles for ten years and many of the problems are self-imposed. How many new features introduced over the course of the decade? It looks like the same old thing to me and the idea that such a project should have perpetual bugs for ten years is completely ludicrous. At the very least, it should be a clear signal that you are doing something wrong. Much too ambitious, perhaps? But that's not really it; as alluded to repeatedly, it's poor design decisions that date back a decade causing it to run into issues that could easily have been avoided. Expect you have insufficient experience with *successful* browser scripting projects, so don't have enough data to make a reasonable comparison.

Do you really believe that if My Library had been marketed to the general public and had millions of users that it would suffer these sorts of issues *today* (if ever?) Virtually everything I'm posting here is an issue that was purposely avoided there; because I had the experience of making all the same mistakes long *before* I designed the thing. Are you oblivious to the fact that it was able to run outrageous cross-browser demos (as well as production sites) during the whole IE 6->7->8->9->etc. progression without anyone even touching the code? That was no accident and a million more users would have changed little (if anything).

For example, did the number of users break `jQuery.attr`? Did they help clue you in that something was very wrong with its *design*? And did the *lack* of My Library users cause similar functions to work virtually flawlessly across far more browsers without the slightest bit of attention on my part? I'm sure you remember the very extensive test page for that as Resig once famously tried to copy it, but the point is that it was the *code* that mattered, particularly the poor decision to have just `attr` when clearly both `attr` and `prop` were needed.

It took five years of near constant criticism for you to accept that simple fact and change your interface (mostly) accordingly. And years later, I still see odd bugs related to those functions, so should have copied a bit better I suppose. Still don't understand what `removeProp` was (is?) supposed to be, but I digress. If you'd have heard what I was saying in 2007 regarding `attr` (covered the basics in the very first Usenet review), you could have avoided five plus years of misery (and a near revolt when you finally announced the mistake and changed the design). Still wish you would have simply *deprecated* the old `attr` and added two new functions (another recurring theme here).

Do you remember all of the other upheaval jQuery went through during the same period? And do you really think that had anything to do with the number of users (as opposed to code that was married to the specific IE versions and simply unable to deal with changes in the next versions?) It's all documented history, so all I can tell you is to review it if unfamiliar with the code changes of that period. Today, it only needs to work in a handful of strictly standards-based browsers (at least in 3, no idea what is going on with the legacy versions or how they fit in here) and still the bugs keep coming due to poor design decisions that date back to the beginning. I suggest you read my posts very carefully. Can hardly blame *me* if you fail to listen once again. I suggest that the consequences of adopting the wrong attitude once again are already in the wind and will be much worse than a few disgruntled die-hards whining about sudden `attr` changes (majority of the users were clueless about that anyway).

I'm not saying *any* of this to hurt you (though have been subject to numerous personal attacks from your camp over the years) or to turn this into a debate about whose library is "best" (as much as such a point can be settled, it was settled years ago for anyone paying attention). I'm telling you that you don't understand a thing I've said (and that *will* hurt you). Furthermore, many of the things I am bringing up were brought up almost a decade ago (and not understanding them then *has* hurt you). It's been documented pretty clearly, on Usenet and now here. Ignore the history at your own expense (another recurring theme).

Anyway, I *do* have experience with successful browser scripting projects, with a lot more cross-browser ambitions than this thing, and can tell you that even if you had a *trillion* users, there's no way jQuery should be perpetually plagued by the sort of issues I see coming up year after year. Have been doing this since late last century, long before there was such a thing as jQuery. And like many other experienced JS developers back in 2006, I saw the obvious design mistakes for what they were and I see that virtually none of them have been corrected *to this day*. Also see how they are directly or indirectly responsible for documented issues (and not all documented by *me*).

You certainly don't have to take my word for it, as *anyone* with browser scripting experience (outside of jQuery) can confirm this. Furthermore, I've got plenty of experience dealing with projects that use jQuery and have seen it screw up enough times on things that should have been settled years ago that my standard prescription is to nuke the miserable thing. Take note that the rest of the world is definitely starting to take the same dim view (several years too late of course). Do you think I'm posting all this stuff for my health? Am I inventing the documented bugs out of thin air? No, I'm actually trying to help you at a time when you most need it (as unexpected as that may be).

Can see I'm likely wasting my time here, but will continue to work on my fork as that's what I want to do at the moment. I've got my own reasons, but there's no reason you can't benefit as a result. Or not, it's up to you to set your emotions aside and think clearly. Resig never could, but he was just a kid. What's your excuse?

**Comment by david-mark** [comment]
I see what to do to straighten out this mess and remove the odd caveat regarding the `width` and `height` methods from the documentation. Methods like these should be simple enough not to require such asides.

It starts with making `width` and `height` simply parse the number from string returned by the `css` function for the corresponding styles. As for the inner/outer varieties, there's no way those should even involve fractions of pixels. As mentioned, that should be left to the `css` function. Should also realize that fractions of pixels only matter in odd cases where calculations may lead to rounding errors (with a ceiling of a single pixel). It's not worth making every dimension-related function slow and complicated (and issue-prone) just for the sake of fractions of pixels.

Instead of requiring the user to perform additional calculations with the `width` and `height` results when using the border box model (as is currently documented), they can either use box models as intended or do the math with the `css` results when going against the grain (e.g. trying to find the `outer` width of an element that uses the content box model). Clearly if the user doesn't know what box model they are using and its implications, there the results of these functions won't have much meaning anyway.

Will demonstrate in my fork. Will have to deprecate some existing methods and add others (the usual way to preserve compatibility while correcting long-standing design issues). Or may just break compatibility as I know that these changes aren't going to get merged as is anyway.

Certainly calling `getBoundingClientRect` and then parsing, converting and subtracting computed border widths is a non-starter. Similar scenarios exist for the rest of them and the numbers just won't add up.

To demonstrate trying to simulate the `content-box` box model for a `DIV` without padding:

```javascript
var el = document.createElement('div');
el.style.width = '100.33px';
el.style.height = '200px';
el.style.borderLeft = 'solid 12.67px';
document.body.appendChild(el);
console.log(parseFloat(document.defaultView.getComputedStyle(el)['width']));
console.log(el.getBoundingClientRect().width - parseFloat(document.defaultView.getComputedStyle(el)['borderLeftWidth']));
```

The results always differ by weird fractional values in Chrome (as might be expected). Trying to calculate sub-pixels by subtracting parsed `border` and `padding` styles from `getBoundingClientRect` is simply not useful.

**Comment by mgol** [comment]
> As for the inner/outer varieties, there's no way those should even involve fractions of pixels. As mentioned, that should be left to the css function.

That's your personal opinion but there are people that need subpixel values and it's only slightly slower than the integer ones so we're not going to give up on that, that's already been decided.

**Comment by kyletheninja** [comment]
As a regular professional user of the library, I have to mention that I would rather have $elem.innerWidth() work in firefox than return subpixel values. As of now I have to use $elem[0].clientWidth to ignore the scrollbars in firefox. Maybe that is a complaint I should take up with Mozilla, but for now I wanted to put in my two cents.
