### ISSUE TITLE
Restting file input for IE 10-

### ISSUE THREAD

**Issue by FuweiChin** [jquery/jquery#3454]
### Environment ###
IE 10
jQuery 3.1.1

### Description ###
I have a file input element with a file selected. neither setting its value to "", nor reseting its form, can reset the file input(empty its value, and files).
```js
var file=document.querySelector('form input[type="file"]');
file.value="";
file.form.reset();
console.log(file.value=="");//IE 10 outputs false
console.log(file.files.length==0);//IE 10 outputs false
```
There is <a href="http://stackoverflow.com/questions/20549241/how-to-reset-input-type-file#answer-35323290" target="_blank">a solution</a> from Maxmaxmaximus(see link below) can do the trick

Since this is a IE10 bug, but MS won't maintain old IE10- anymore, so I think, jQuery will handle it.

### Link to test case ###
<a href="https://jsfiddle.net/g955g17o/1/" target="_blank">Issue test case</a>

**Comment by dmethvin** [comment]
This seems like a "can't fix" from our side. @FuweiChin did you have some idea of how it could be fixed?

**Comment by timmywil** [comment]
The suggested solution of resetting type works, but considering you can't reset a form element using the jQuery API (usually done natively), I don't think we can cover this in jQuery. The only solution we were thinking of was adding a reset in a `.val` hook, but that's a big side effect when you're just setting the value. I think your solution of a plugin is best. Other jQuery plugins that deal with forms should be aware of this bug and address it there, but I don't think this is something to address in core.
