### ISSUE TITLE
Calling `.width()` returns the percentage width instead of pixel width.

### ISSUE THREAD

**Issue by RehanSaeed** [jquery/jquery#3455]
When calling `.width()` I expect to get back the width in pixels but I get back the width as a percentage. This seems to effect all browsers and the latest version of jQuery.

I can workaround the problem by using a `setTimeout` and getting the `.width()` again at a later time and it does actually return the pixel width. Using the DOM ready event seems to have no effect.

I've tried to create a simple JSFiddle from my complex page but I've been unable to reproduce the problem so far. See also the comments on the top answer in [this](https://stackoverflow.com/questions/17305707/assigned-width-in-percentage-but-want-to-get-it-in-pixels) StackOverflow question where others are having the same problem.

**Comment by markelog** [comment]
Without reproducible test-case there is nothing we can do, unfortunately.

Note though, that if your node is hidden `width` might return incorrect result, see additional notes in http://api.jquery.com/width/ docs – 

> The value reported by .width() is not guaranteed to be accurate when the element or its parent is hidden. To get an accurate value, ensure the element is visible before using .width(). jQuery will attempt to temporarily show and then re-hide an element in order to measure its dimensions, but this is unreliable and (even when accurate) can significantly impact page performance. This show-and-rehide measurement feature may be removed in a future version of jQuery.
