### ISSUE TITLE
Inconsistent event namespace property.

### ISSUE THREAD

**Issue by dmckenna-gumgum** [jquery/jquery#3457]
### Description ###
The event.namespace property is only available for custom events.  For namespaced standard events it must be accessed via event.handleObj.namespace.  This seems weirdly inconsistent and I can't tell if it was an oversight or the intended behavior.

```javascript
$(document).on('testing.test', function(evt) { console.log(evt.namespace); })
$(document).trigger('testing.test');
//returns 'test'

$(document).on('click.test', function(evt) { console.log(evt.namespace); })
//returns undefined

$(document).on('click.test', function(evt) { console.log(evt.handleObj.namespace); })
//returns 'test'
```

### Link to test case ###
http://codepen.io/anon/pen/PbXEKL

**Comment by dmethvin** [comment]
The `event.namespace` is the namespace used to `.trigger()` the event, [documented here](http://api.jquery.com/event.namespace/). An event originated by the browser never has a namespace. The `event.handleObj.namespace` is the namespace given to the event handler when it was attached by `.on()`. 

If you're looking at this information as part of an application, you're probably too deep into jQuery implementation details. Namespaces are most useful as a way to selectively detach events without interfering with other handlers on the same element. It's rarely useful to inspect or discriminate by namespace while native events are being handled.
