### ISSUE TITLE
JQuery selector current event lose the "checked" property on checkbox input

### ISSUE THREAD

**Issue by p4535992** [jquery/jquery#3466]
### Description ###
JQuery selector current event  (event.currentTarget) on a checkbox input "lose" the checked property, or at least i don't find a way to retrieve the boolean value of the checked property with jquery. 

### Link to test case ###
https://jsfiddle.net/4535992/cqqek4sq/24/

**Comment by mgol** [comment]
In jQuery properties of objects are retrieved via `elem.prop(propertyName)`, not via `node[propertyName]` ad in the bare DOM. Read https://api.jquery.com/prop/ for further info.
