### ISSUE TITLE
statusCode parameter to $.ajax doesn't work with 302 responses

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery#3467]
```
$.ajax({
  		url: 'redirect-me.html', // server responds with a 302 redirect
  		statusCode: {
  			'302': function() {
	  			console.log("302 response!");
	  		}
	  	}
  	});
```
Expected: should print "302 response".
Observed: NOTHING. The response is actually a 302 (it can be observed in the Network tab), but nothing happens. The handler doesn't seem to be triggered

```
$.ajax({
  		url: 'redirect-me.html', // server responds with a 302 redirect
  		statusCode: {
  			'302': function() {
	  			console.log("302 response!");
	  		}
	  	}
	  	success: function() {
	  			console.log("Success!");	  	
	  	}
  	});
```
Expected: The documentation is awfully unclear about the interaction between `statusCode` and `success` (and `error`) if both are defined, but one of the following behavior could be expected (and should be documented): either only the handler for 302 is called, or both one after the other (as two requests are actually made), or an API could be defined so that if the 302 handler returns false the redirect is not followed, otherwise it is, or an additional setting for whether to follow redirects or not. 
Observed: None of the above. Only the success handler is called.

Adding `return false` at the end of the 302 handler changes nothing in both cases.

**Comment by teo1978** [comment]
I see that the browser automatically follows the redirect and jQuery kind of cannot do anything about it (except there seems to be a new `fetch()` API as of 2016). But then, I wonder why the heck the docs say this:

> If the request is successful, the status code functions take the same parameters as the success callback; if it results in an error **(including 3xx redirect)**, they take the same parameters as the error callback.

if that cannot ever possibly happen.

**Comment by Krinkle** [comment]
According to <http://stackoverflow.com/a/343359/319266> XMLHttpRequest will follow redirects transparently in most cases, as such jQuery cannot see those and will instead see the response and status code of the redirect destination.

However the spec also says that redirect following is limited:
> If the origin of the URL conveyed by the Location header is same origin with the XMLHttpRequest origin and the redirect does not violate infinite loop precautions, transparently follow the redirect while observing the same-origin request event rules.

So perhaps if the origin differs or if it might be an infinite loop, then the redirect status code would be exposed?

**Comment by timmywil** [comment]
Closed in favor of docs issue: https://github.com/jquery/api.jquery.com/issues/1022
