### ISSUE TITLE
Feature detection strategy is ill-advised

### ISSUE THREAD

**Issue by david-mark** [jquery/jquery#3474]
### Description ###

Historically, type converting host object methods has led to problems and the strategy was dismissed as unviable almost ten years ago. The issue is summed up here:

https://gist.github.com/david-mark/bc0c303a52957dba427239b02e5c99c9

Searching for "[native" in the serialization of a function is also ill-advised as there's nothing beyond the observations of "current" browsers to imply that its presence can be counted on. For  one example, what if "native" is localized?

### Link to test case ###

No test case needed. This is a matter of what *may* fail in the future (and certainly did in the past). Cross-browser scripting often requires anticipating what future browsers may do, rather than just observing patterns that occur in a narrow set of browsers today.

**Comment by mgol** [comment]
There is no concrete issue reported here. If you want us to look at it,
please point out examples of pieces of jQuery code that you consider to be
incorrect with succint explanations why they're wrong in each case.

**Comment by david-mark** [comment]
Was looking at the distributed version of jQuery 3.1.1, which contains Sizzle, which contains:

```javascript
rnative = /^[^{]+\{\s*\[native \w/
```

And every single instance of feature detection uses it. For example:

```
// Support: IE<9
support.getElementsByClassName = rnative.test( document.getElementsByClassName );
```

I linked to a rehash of the history of feature detection and the first few paragraphs address the issue of type conversion. In short, history shows it's a bad idea and history is all we have to enlighten us on such issues.

Regardless of the fact that Sizzle originates from another repository, this should be addressed. After all, it makes up the lion's share of jQuery. I know there is talk of eliminating it in future, but that doesn't help present jQuery users. Feel free to address it wherever it makes the most sense.

Did you really not know what I was referring to? Could have saved time by just moving the issue to wherever Sizzle is maintained. Sorry for any confusion. :)

**Comment by markelog** [comment]
Feature detection has their drawbacks and sometimes just browser detection in a hat, but it's the best strategy we have
