### ISSUE TITLE
Deprecate jQuery.nodeName, remove in 4.0

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#3475]
### Description ###
`jQuery.nodeName` is another undocumented utility function that's exposed on the jQuery object. We should remove it (probably in 4.0 as it's been there for a long time).

### Link to test case ###
https://jsfiddle.net/o648k3ga/1/

**Comment by timmywil** [comment]
If we want to remove it in 4.0, we should deprecate in 3.2.

**Comment by mgol** [comment]
We can't deprecate something that's not documented. :) It's more than deprecated.

**Comment by timmywil** [comment]
@mgol I'd still like to give notice. We're doing the same for other undocumented functions that we plan on removing.

**Comment by karan-96** [comment]
Hello . i think ,to fix up this issue, jquery.nodeName function should be removed from src/core.js and added to src/deprecated.js. Correct me if i am wrong or if i am missing something.Can i take up this issue and work with this approach?

**Comment by timmywil** [comment]
@karan-96 That would be great! You'll find information on how to contribute [here](http://contribute.jquery.org/), with info on commits and PRs [here](http://contribute.jquery.org/commits-and-pull-requests/). As far as the required work for this issue, that should be all the work needed for jQuery core. We'll also want to add a warning to the [jQuery migrate plugin](https://github.com/jquery/jquery-migrate/issues/246).

**Comment by dmethvin** [comment]
Just to clarify what has to be done here, I know it's got a PR at gh-3505 but we have to eliminate internal calls in order to warn about it in jQuery Migrate.

- [ ] Create an internal `nodeName` and put it in src/var/nodeName.js
- [ ] Change all internal calls to `jQuery.nodeName` to our new `nodeName` function
- [ ] Expose the internal `nodeName` as `jQuery.nodeName` in deprecated.js

Does that sound right to everyone?

**Comment by mgol** [comment]
@dmethvin yes, that's exactly what I said in https://github.com/jquery/jquery/pull/3505#issuecomment-273482957 a few days ago. :)

**Comment by mgol** [comment]
(although it seems it doesn't have to be a var-module in case of an exported function)

**Comment by dmethvin** [comment]
@mgol oh sorry, I missed that!
