### ISSUE TITLE
Using window.setInterval to unceasingly call API of context.find will result in glint of Element panel of Chrome dev tool 

### ISSUE THREAD

**Issue by liangklfang** [jquery/jquery#3476]
The main javascript code as follows:
` function IFrameResize() {
      	 	 var container=$('div[class*="current"]');
		      var mainFrame=container.find('iframe[name="mainFrame"]')[0];
		  }
      	 window.setInterval("IFrameResize()", 140);`
and you can see this in jsfiddle https://jsfiddle.net/liangklfang/1v03ot34/ . Open the chrome dev tools of Element panel ,you will find element of 'div.iframe-container.current' is blinking unceasingly. But , using  API of children to replace find will solve this problem. You can also see it in next png image. Thx 
<img width="367" alt="2016-12-28 3 59 20" src="https://cloud.githubusercontent.com/assets/12906688/21517046/9fbc9c4a-cd16-11e6-92ab-9d589f678035.png">

**Comment by liangklfang** [comment]
If we break on this element, we can see a id of "sizzle1482911067232" is added on it ,but actually,we dont need the id at all

**Comment by gibson042** [comment]
You are just experiencing Chrome Dev Tools behavior. jQuery adds the transient id to make sure that selection works properly.
