### ISSUE TITLE
caching for camelCased strings?

### ISSUE THREAD

**Issue by zspitzer** [jquery/jquery#3477]
Every time a data attribute or dataset is accessed, jQuery.camelCase is called
https://github.com/jquery/jquery/blob/master/src/data/Data.js#L74

Adding a cache of camel cased strings would avoid running two regular expressions
https://github.com/jquery/jquery/blob/master/src/core.js#L289

I am seeing a decent performance improvement after adding a simple cache in an webapp which somewhat abuses data calls

**Comment by gibson042** [comment]
Extremely-high-frequency `.data( key )` is not an intended use case, and I don't foresee us memoizing `jQuery.camelCase` calls. However, no-argument `.data()` gives you the data object directly, upon which you can get and set whatever properties you like without worrying about string manipulation.

**Comment by mgol** [comment]
Just remember that if you modify the object directly and still want to be able to access it via the official API in some less performance-intensive parts of the code you need to use camelCased key names for direct manipulation.
