### ISSUE TITLE
find() breaks for some simple queries on parsed HTML unless ghost div is used

### ISSUE THREAD

**Issue by figuernd** [jquery/jquery#3481]
### Description ###
To query an element in a string of HTML, the solution recommended on StackOverflow is to use parseHTML() and $() to create a jQuery object to execute find() against. However, find() will not work for certain queries or HTML strings that do work on elements that a part of the DOM. e.g. some descendant queries. 
A workaround is to append the parsed elements to a ghost DIV, but this should not be necessary. See example jsfiddles below.

### Link to test case ###
Expected to show "The stuff I am looking for", but find() returns nothing: http://jsfiddle.net/ykwd8d01/ 
Workaround by adding ghost div: http://jsfiddle.net/g9d81y1x/

Use case discussed here:
http://stackoverflow.com/questions/11047670/creating-a-jquery-object-from-a-big-html-string

**Comment by mgol** [comment]
Thanks for the report.

The observed behavior is expected. The jQuery object you create represents the outer `div`; it doesn't contain another `div` and if you invoke `$jQueryObject.find("div > p")`, all the parts of the selector need to lie inside the element. This is different to how `querySelectorAll` works.

If you think the documentation at https://api.jquery.com/find/ is not clear enough, please open an issue and/or a pull request at https://github.com/jquery/api.jquery.com/issues.
