### ISSUE TITLE
.size() method is removed in jQuery 3.0 but wasn't included in the upgrade guide

### ISSUE THREAD

**Issue by ronaldsuwandi** [jquery/jquery#3482]
### Description ###
As per title, in the API doc `size()` is removed 

![image](https://cloud.githubusercontent.com/assets/4120788/21599700/baf2dca6-d1ab-11e6-88db-1937db7b0ecb.png)

But there is no mention in the [upgrade guide](https://jquery.com/upgrade-guide/3.0/)

**Comment by mgol** [comment]
Thanks for the report. However, it's the docs issue so it should be reported at https://github.com/jquery/jquery.com/issues; could you re-report it there?

Would you like to prepare a pull request? The relevant file is at https://github.com/jquery/jquery.com/blob/master/pages/upgrade-guide/3.0.md.

**Comment by ronaldsuwandi** [comment]
Thanks! Will do
