### ISSUE TITLE
TypeError: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by jameslmoser** [jquery/jquery#3485]
When calling a jQuery function on an element (i.e. element.toggle(false)) inside a template created by document.createElement("template") I get an exception. I'm using 1.12.4, and this seems to be an easy fix by changing the following line (1316):

		var adown = a.nodeType === 9 ? a.documentElement : a,
to:

		var adown = a.nodeType === 9 && a.documentElement ? a.documentElement : a,
or possibly even to:

		var adown = a.documentElement || a,

If there is a reason the code is like this and I am doing something wrong (which very well may be possible) please let me know.

**Comment by gibson042** [comment]
We are no longer supporting 1.x releases... if your problem still exists in the 3.x line, please provide a live test case (e.g., with [JSFiddle](https://jsfiddle.net/) or [JS Bin](https://jsbin.com/?html,output)) to help us diagnose the issue.
