### ISSUE TITLE
Browser compatibility issue for .css() function.

### ISSUE THREAD

**Issue by connorHe** [jquery/jquery#3492]
Hi,
I found a browser compatibility issue for .css() function.
As you can see, this is what happens in Chrome:
![issue_in_chrome](https://cloud.githubusercontent.com/assets/5494350/21842700/e78213a4-d822-11e6-98ca-8c1679ca3f14.png)
And this is what happens in Firefox:
![issue_in_firefox](https://cloud.githubusercontent.com/assets/5494350/21842714/f80fafce-d822-11e6-9006-94d632720cc4.png)

I wander why I run the same code in the console, however I get 'undefined' from chrome and 'block' from firefox.
I used jquery-1.12.4 and tried multiple versions of these two browser.
Looking forward your replay.

**Comment by dmethvin** [comment]
In that example, you are asking for a style property of an element that is not in any document. What value would you expect? It can't know what rules may apply once the element is inserted into a document, since there may be different cascading rules depending on where it's inserted.

**Comment by dmethvin** [comment]
See also https://bugs.webkit.org/show_bug.cgi?id=14563 but I think this is sufficiently ambiguous that it should be "solved" by the browser and people should not make assumptions about detached elements.

**Comment by connorHe** [comment]
Hi dmethvin,
I got your point and I support your option: **people should not make assumptions about detached elements**. https://bugs.webkit.org/show_bug.cgi?id=14563 also do me a great favor. 
After all, I don't think this is a bug for Jquery because we should not coding like that.
Thanks for your help!
