### ISSUE TITLE
$.when will incorrectly resolve instantly when a 1-length array is passed

### ISSUE THREAD

**Issue by cervengoc** [jquery/jquery#3493]
I'm trying to use `$.when` with a dynamically managed array of one or more deferred. However, I've found that when I pass an array which has only one deferred, `$.when` will resolve it immediately.

Expected behavior: I'd expect jQuery to base the master deferred to that one element of the array.

Here is a fiddle representing the issue with jQuery 3.x. https://jsfiddle.net/q2j18ay8/

**Comment by fastfasterfastest** [comment]
Per https://api.jquery.com/jquery.when:

> If a single argument is passed to jQuery.when() and it is not a Deferred or a Promise, it will be treated as a resolved Deferred and any doneCallbacks attached will be executed immediately.

Your example does exactly that, it passes a single argument, an array containing an object which happens to be a Deferred, thus the doneCallback will be executed immediately.

It sounds like you may want to use $.when.apply

**Comment by cervengoc** [comment]
Oh I apologize, I've misread the signature. Thank you for your help.

**Comment by richseviora** [comment]
@fastfasterfastest  I'm wondering if there might be an opportunity for a document clarification. I ran into the same problem as @cervengoc for the same reason (calling `$.when(array)` not `$.when.apply(array)`). 

I think it'd be helpful to see that a mention like:

> If a single argument is passed to jQuery.when() and it is not a Deferred or a Promise, it will be treated as a resolved Deferred and any doneCallbacks attached will be executed immediately. This includes arrays of Deferred/Promise objects (call jQuery.when.apply(array).

**Comment by fastfasterfastest** [comment]
If it was documented the way Mozilla documents things, it would be:
`jQuery.when([promise1[, ...[, promiseN]]])`

I think that probably would be clearer.  The same applies to other jquery api calls as well and it may not be a trivial update to make such a documentation change.  In any case, I think the proper venue to discuss this may be https://github.com/jquery/api.jquery.com/issues
