### ISSUE TITLE
Catch "Not enough storage" exceptions when reading responseText (IE)

### ISSUE THREAD

**Issue by Logic-32** [jquery/jquery#3499]
### Description ###
This exclusively affects IE.  Basically what happens is, when you try to read the `responseText` from an AJAX request that contains several MB worth of data, you can occasionally get an exception that says "Not enough storage is available to complete this operation".  When using any version of jQuery however, that exception becomes unhandelable because the error callback isn't called when it happens.

From the callback function in `jQuery.ajaxTransport`:
```javascript
callback = function( type ) {
	return function() {
		if ( callback ) {
			callback = errorCallback = xhr.onload =
				xhr.onerror = xhr.onabort = xhr.onreadystatechange = null;

			if ( type === "abort" ) {
				xhr.abort();
			} else if ( type === "error" ) {

				// Support: IE <=9 only
				// On a manual native abort, IE9 throws
				// errors on any property access that is not readyState
				if ( typeof xhr.status !== "number" ) {
					complete( 0, "error" );
				} else {
					complete(

						// File: protocol always yields status 0; see #8605, #14207
						xhr.status,
						xhr.statusText
					);
				}
			} else {
				complete(
					xhrSuccessStatus[ xhr.status ] || xhr.status,
					xhr.statusText,

					// Support: IE <=9 only
					// IE9 has no XHR2 but throws on binary (trac-11426)
					// For XHR2 non-text, let the caller handle it (gh-2498)
					( xhr.responseType || "text" ) !== "text"  ||
					typeof xhr.responseText !== "string" ?
						{ binary: xhr.response } :
						{ text: xhr.responseText }, //// ISSUE IS HERE.
					xhr.getAllResponseHeaders()
				);
			}
		}
	};
};
```

From that code you can see, if we fail to read `xhr.responseText` then `complete()` never gets called and it becomes impossible to handle the exception (outside of an 'onerror' handler).

### Link to test case ###
From my research, this issue is notoriously difficult to reproduce.  It involves loading several MB of data over AJAX and possibly requires some memory fragmentation in the browser.  For me, once it starts happening I can almost always get it to happen.  But sometimes it goes away.  If I reduce the response size of my AJAX request enough then it definitely goes away.

Relevant other instances of people experience the issue (in general, not particularly with jQuery):
http://stackoverflow.com/questions/27405826/internet-explorer-11-not-enough-storage-error
https://connect.microsoft.com/IE/feedback/details/1053110/not-enough-storage-is-available-to-complete-this-operation-8007000e-error-when-trying-to-get-a-response-around-100mb-via-ajax

### Proposed solution ###
This is a solution I'm proposing.  I would do a pull request but would prefer if somebody on the team could polish it up and get it in.  If not, I'll look into doing a pull.
```javascript
// Callback
callback = function( type ) {
	return function() {
		if ( callback ) {
			callback = errorCallback = xhr.onload =
				xhr.onerror = xhr.onabort = xhr.onreadystatechange = null;

			if ( type === "abort" ) {
				xhr.abort();
			} else if ( type === "error" ) {

				// Support: IE <=9 only
				// On a manual native abort, IE9 throws
				// errors on any property access that is not readyState
				if ( typeof xhr.status !== "number" ) {
					complete( 0, "error" );
				} else {
					complete(

						// File: protocol always yields status 0; see #8605, #14207
						xhr.status,
						xhr.statusText
					);
				}
			} else {
			    try {
					complete(
						xhrSuccessStatus[ xhr.status ] || xhr.status,
						xhr.statusText,

						// Support: IE <=9 only
						// IE9 has no XHR2 but throws on binary (trac-11426)
						// For XHR2 non-text, let the caller handle it (gh-2498)
						( xhr.responseType || "text" ) !== "text"  ||
						typeof xhr.responseText !== "string" ?
							{ binary: xhr.response } :
							{ text: xhr.responseText },
						xhr.getAllResponseHeaders()
					);
				} catch ( e ) {
					complete( 0, "error", e ); // This would require further change
				}
			}
		}
	};
};
```
Note: all I did was add a `try` in the `else` block.  Since I want the exception passed into `complete()` that would also require changes to the `done()` function in `ajax` along with API/backwards compatibility considerations.  So I'm leaving that as optional and up to the powers-that-be.  But I think it would be good to include it so we can tell what the error was not simply that there was an error.

**Comment by dmethvin** [comment]
I see the dilemma for sure. We've generally worked very hard not only to avoid try/catch but to eliminate it where possible from the codebase because it often catches things that it shouldn't.

Although we made our `Deferrred.then()` implementation compatible with Promise/A the `jQuery.ajax()` method still can throw errors that aren't catchable by a chain like `jQuery.ajax(...).catch(...)`. Ideally we'd have any ajax errors thrown inside the method just reject and you could `.catch()` them, but I know for sure a lot of existing `.ajax()` code doesn't use `.catch()` or the two-arg `.then()`.

So I dunno, maybe the try/catch is the least painful of all the pains.

**Comment by Logic-32** [comment]
I'm out of practice, I didn't even know about `catch()` :)  To the point of catching things that you shouldn't: I had a thought over the weekend.  I'd like to update the proposed solution to the following so that it only catches the error I'm concerned about and not issues with `complete()` itself (since I'm pretty sure that would catch errors in done/fail callbacks as well).  More thought should probably be given to the appropriate place(s) to put a try/catch to ensure the appropriate callbacks are called but this is a start.

Given that this callback is evaluated at the top of the stack and not in the middle of the chain I'm sure you can make a strong argument for the need of the try/catch; particularly revolving around the fact that a user can't do so in their own code.  IMO, this also breaks the contract of the promises used by AJAX because it doesn't call the fail callback as a result of the error.  The request literally disappears.  Which, if you have a system where you need to reliably track what requests have actually finished for any particular reason (e.g. metrics/onunload handlers?) then you can't.  And that creates on very obscure bug; the only work-around for it being to manually handle AJAX requests instead of using jQuery.

```javascript
// Callback
callback = function( type ) {
	return function() {
		if ( callback ) {
			callback = errorCallback = xhr.onload =
				xhr.onerror = xhr.onabort = xhr.onreadystatechange = null;

			if ( type === "abort" ) {
				xhr.abort();
			} else if ( type === "error" ) {

				// Support: IE <=9 only
				// On a manual native abort, IE9 throws
				// errors on any property access that is not readyState
				if ( typeof xhr.status !== "number" ) {
					complete( 0, "error" );
				} else {
					complete(

						// File: protocol always yields status 0; see #8605, #14207
						xhr.status,
						xhr.statusText
					);
				}
			} else {
				var response = null;
				try {
					response = typeof xhr.responseText !== "string" ?
							{ binary: xhr.response } :
							{ text: xhr.responseText };
				} catch ( e ) {
					complete( 0, "error", e ); // This would require further change
					return;
				}

				complete(
					xhrSuccessStatus[ xhr.status ] || xhr.status,
					xhr.statusText,

					// Support: IE <=9 only
					// IE9 has no XHR2 but throws on binary (trac-11426)
					// For XHR2 non-text, let the caller handle it (gh-2498)
					( xhr.responseType || "text" ) !== "text"  ||
					response,
					xhr.getAllResponseHeaders()
				);
			}
		}
	};
};
```

**Comment by dmethvin** [comment]
Yeah, the `complete( 0, "error", e )` is problematic. Somehow the detail has to worm its way out of there where it could be acted upon, or at least logged by the caller.

**Comment by Logic-32** [comment]
I agree.  While ideal it would be problematic.  I could probably do a pull request and drop the passing of the exception but I'm hoping somebody more familiar with the internals of jQuery would be willing to pick this up and do that.  Because it'd be awesome.

**Comment by timmywil** [comment]
We may not get to this for 3.2, but we're open to a PR.

**Comment by chinhodado** [comment]
@Logic-32 When this happen, does it actually throw an exception?

**Comment by Logic-32** [comment]
It does throw, yes.  JQuery just doesn't catch it at the right time currently.  You can see in the sample code in my post that a try-catch would resolve the issue.  I just haven't had the time to work on a PR personally.

**Comment by Logic-32** [comment]
Apparently I'm never going to find the time to work on this and IE is long dead so there's probably not much point unless Edge has this issue.  Which it probably won't.  Closing.
