### ISSUE TITLE
Properly detect attachment of Shadow DOM elements

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#3504]
There are a few places where we check document attachment with `jQuery.contains( elem.ownerDocument, elem )` (`isHiddenWithinTree` for show/hide, `curCSS` for inline style fallback, `buildFragment`/`domManip`/`remove`/`jQuery.clone` for managing script evaluation during DOM manipulation), all of which [fail inside Shadow DOM](https://github.com/jquery/jquery/issues/2854#issuecomment-272604563):
> `$.contains(document, elem)` will return false when elem is shown in a shadow dom.
change to `elem.getRootNode({composed: true}) === elem.ownerDocument` works.

We should investigate the cost of a remedy (e.g., a Shadow-DOM-compatible `isAttached( elem )` function).

**Comment by timmywil** [comment]
Yes to going forward and investigating, but we may scrap it later depending on how involved this gets.

**Comment by gibson042** [comment]
As noted in the meeting, we'd probably benefit from an internal `isAttached` even if it doesn't handle shadow DOM, because it better communicates intent.
