### ISSUE TITLE
RangeError: Maximum call stack size exceeded when using recursive animate while in another tab

### ISSUE THREAD

**Issue by Anorionil** [jquery/jquery#3507]
We've used this code. The code works, but if you open the page and switch to another tab in 3 seconds, an infinite loop occurs. You can see this if you have developer console open. This happens in Chrome. (in Firefox it also seems to happen, but less brutal)

https://jsfiddle.net/c41bgs24/12/

It looks like .animate is completed **instantly** when called if the tab is not active, regardless of the duration. The callback is also called.

**Comment by markelog** [comment]
Yeah, this kinda, sorta by design – https://github.com/jquery/jquery/pull/1578#r12712029

/cc @dmethvin, @scottgonzalez

**Comment by markelog** [comment]
Let's move this discussion to https://github.com/jquery/jquery/issues/3507
