### ISSUE TITLE
jqXHR.getResponseHeader(key) crashes if key isn't passed

### ISSUE THREAD

**Issue by stelovsky** [jquery/jquery#3508]
### Description ### 

  *  What do you expect to happen?

1) Graceful return when 'key' parameter is missing.
2) Documentation should mention that 'key' is required and what are possible values.
Note that any value that is not 'legal' will cause a crash.
3) Decent, consistent attributes of jqXHR argument passed to .fail(), even better: informative values of textStatus and errorThrown arguments.

  *  What actually happens?

Exception thrown - see Description below

  *  Which browsers are affected?

All

stack at exception:

> jquery-3.1.1.js:8912
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.getResponseHeader (jquery-3.1.1.js:8912)
    at onFail (js.ChildShow.js:137)
    at Object.<anonymous> (js.ChildShow.js:74)
    at fire (jquery-3.1.1.js:3305)
    at Object.fireWith [as rejectWith] (jquery-3.1.1.js:3435)
    at process (jquery-3.1.1.js:3658)

at line 8912 in code:

> // Builds headers hashtable if needed
				getResponseHeader: function( key ) {
					var match;
					if ( completed ) {
						if ( !responseHeaders ) {
							responseHeaders = {};
							while ( ( match = rheaders.exec( responseHeadersString ) ) ) {
								responseHeaders[ match[ 1 ].toLowerCase() ] = match[ 2 ];
							}
						}
						**match = responseHeaders[ key.toLowerCase() ];**
					}
					return match == null ? null : match;
				},
				

Obviously, key isn't defined and is required, but then the documentation should mention that a key is needed and what keys are feasible. (Maybe a jqXHR.keys() function?)
Even then there should be a test and 'null' should be returned if key is null/undefined to gracefully handle the case. (When using minified version, the bug is untraceable.)
Also, there is getResponseHeaders() (with 's' at the end that isn't documented, but should if there is no mention about a required key in getResponseHeader().

BTW: In general, the .fail(jqXHR, textStatus, errorThrown) is deficient, e.g., when there is cross-origin issue, we get '' as textStatus and 'error' as errorThrown which is pretty useless.
Also, why there is no mention of .fail() in the documentation of when()?
Even more general, the arguments passed to .fail() are terrible: the textStatus and errorThrown are ofter useless, and sometimes jqXHR has a 'message' attribute, sometimes a 'responseText' (as an html page), sometimes there is 'stack', sometimes none of these, ... I'd challenge anyone to try to have a decent error popup dialog that shows the pertinent info ...

### Link to test case ###
None should be needed.

**Comment by gibson042** [comment]
We take a general stance that "[undocumented inputs result in unpredictable output]()", and in particular do not prioritize adding code to handle invalid input. Moving to https://github.com/jquery/api.jquery.com/issues/1019 for improving the documentation, though.
