### ISSUE TITLE
UC Browser mobile slideToggle(); method doesn't working in v.3.1.1

### ISSUE THREAD

**Issue by gandharthakar** [jquery/jquery#3511]
I am testing my website in UC browser while testing i found the bug in slideToggle();

**What i want expect to happen?**
I created the menu for mobile and one button and i was expecting that if i click on the button then menu will be appears with slide-down effect and again i am click on the same button the menu will be disappear with slide-up effect.

**What actually happens?**
The menu doesn't appears also i am done to check with CSS end like i increase the z-index property of CSS but it's not work for me. So i can change the version of jquery latest (v.3.1.1) to version 1.12.0 and it will work for me but do guys something about this.

**Which browsers are affected?**
UC Browser in android v.11.2.0.915

**Comment by mgol** [comment]
Please provide a test case on jsfiddle.net or jsbin.com; we can't do anything based on such a short description.

**Comment by gandharthakar** [comment]
https://jsfiddle.net/gandhar/5v3xykpa/

**Comment by markelog** [comment]
@mgol made you an assignee, since given discussion at the meeting you have better understanding what to do :)

**Comment by mgol** [comment]
@gabrielschulhof I don't have an easy way to get ahold of a UC Browser now. @gandharthakar is this still an issue in the latest jQuery 3.3.1 & the latest UC Browser version?

**Comment by gandharthakar** [comment]
@mgol i'll checked my fiddle in latest android UC browser and latest jquery v3.1.1 and it's works fine thank you so much

**Comment by mgol** [comment]
@gandharthakar Thanks for confirming!
