### ISSUE TITLE
Parameters in GET body

### ISSUE THREAD

**Issue by plk** [jquery/jquery#3512]
Feel free to delete this if it has been frequently asked.

Using Jquery AJAX calls, it seems impossible to pass body parameters with GET calls. This is in fact allowed by the HTTP specs, particularly if one is developing internal APIs where one also controls the server and backend code etc. It is necessary to be able to to do this in many enterprise APIs which need to send complex queries to decide what to GET (Elastic Search does this a lot, for example). Other current clients like Perl Mojolicious allow this without problems. Not being able to pass body parameters in GET calls forces one to use POST/PUT in situations where it really shouldn't be used and makes one of the HTTP verb slots for an API endpoint useless in some cases.

I have come across this problem which developing several internal enterprise APIs and it makes using jquery on the client side really difficult.

Please consider allowing body parameters for GET calls (in the same request as any query or path params, naturally).

**Comment by dmethvin** [comment]
For special needs like that, you can roll your own from XHR and use jQuery's helper methods like `$.param` to do the heavy lifting.
