### ISSUE TITLE
$.map(undefined) should return undefined but returns []

### ISSUE THREAD

**Issue by wojciechbulaty** [jquery/jquery#3513]
### Description ###
* I expect `$.map(undefined)` to return `undefined`
* Instead is returns an empty array `[]`
* I have tested this in Chrome 55 and JQuery 3.1.1

I expect it to return `undefined` (or optionally blow up) instead of doing "magic" and translating it to an empty array `[]`. I am also happy to be educated why is turning `undefined` to an empty array OK. 

Thanks!

### Link to test case ###
https://jsbin.com/qaficukepa/edit?html,console

This might be related to #2395

**Comment by dmethvin** [comment]
The docs say it returns an array, and that it takes two arguments. The first argument is either an array or an object; `undefined` is neither of those. The second argument is the callback function. Calling a method with invalid inputs has undefined results in any case. Note that if a callback was provided and that callback returned `undefined`, it would be removed from the resulting array. 

http://api.jquery.com/jquery.map/
