### ISSUE TITLE
$.data values differ between dashed and camel cased named variables

### ISSUE THREAD

**Issue by usermax83** [jquery/jquery#3515]
### Description ###
Happens in jquery version 2.2.4
Doesn't happen in jquery version 3.1.1

Removing data with removeData('foo-bar moo-bar') should remove fooBar and mooBar as well.
But after removing and setting again through dashed names, camel cased variables take precedence, and the removed values returned instead of fresh ones.

All browsers are affected.

### Link to test case ###
https://jsfiddle.net/eafkfjrm/

**Comment by mgol** [comment]
Have you read the issue template? It states:

> Note that we only can fix bugs in the latest version of jQuery.

Therefore, if a problem only exists in jQuery 2.x and not in the latest 3.1.1, there is nothing for us to do here. Just update jQuery and the problem will disappear.

**Comment by usermax83** [comment]
Ok, I just thought you are still maintaining 2.x...
This bug gave us a headache in production for a few days, since it wasn't that easy to reproduce.

**Comment by mgol** [comment]
> Ok, I just thought you are still maintaining 2.x...

Was the note unclear or did it just not stand out enough? I'm just trying to figure out whether the message is clear enough or if we should improve it somehow.

Note that even if we were maintaining 2.x, issues like that were precisely the reason why we simplified the `.data()` logic in jQuery 3.0 but that required a breaking change so we couldn't have backported the change to the 2.x line as we now follow semver - it would fix your issue but might break others' sites.

Thanks for the report anyway!

**Comment by usermax83** [comment]
I saw the comment, but i thought 'latest version' means latest in 3.x and latest in 2.x.

**Comment by mgol** [comment]
I see. We were trying to put up a message that doesn't have to be updated each time we release a new major version but maybe the current one is not clear enough. Thank you for your input.
