### ISSUE TITLE
events improvement  in jquery adding priority

### ISSUE THREAD

**Issue by publicocean0** [jquery/jquery#3517]
i suggest to add a new feature on bind/on method 

like this example

`$('body').click(function(){...},{priority:0})`

where priority is a number. 
Then user clicks in a target .... jquery order all callbacks to be executed for this target, ordering before by priority. 
In this way i can decide the order in executing events, i can decide if a event has to to executed always before for specific needs for example.

**Comment by mgol** [comment]
Thanks for the suggestion. However, we're now planning to utilize the native `addEventListener` for event scheduling instead of using our own event queuing so we can't add support for things like that that don't exist in the native APIs.

**Comment by publicocean0** [comment]
i will pass suggestion in w3c :)
