### ISSUE TITLE
Xbox - MS Edge - Jquery On Event Handler not supported.

### ISSUE THREAD

**Issue by Langerz82** [jquery/jquery#3519]
### Description ###
Xbox - MS Edge - Jquery On Event Handler not supported

It throws an error:
Object does not support property or method 'on'
800a01b6

**Comment by mgol** [comment]
Please provide a test case on http://jsfiddle.net or https://jsbin.com

**Comment by Langerz82** [comment]
You can test with running the follow game on Xbox Edge. http://www.maearth.com

**Comment by Langerz82** [comment]
I just realised I was using an older require-jquery version which it was looking for the function. I'll try again with the updated jquery, thanks.

**Comment by Langerz82** [comment]
Working, was outdated jquery version thanks and close.
