### ISSUE TITLE
Maximum call stack size exceeded: parents call with non-lowercase selector

### ISSUE THREAD

**Issue by jorupp** [jquery/jquery#3521]
### Description ###
Infinite recursion when running: `$("#elem").parents("div[Disabled]");` on 1.12.4 and 2.2.4.  Works on 3.1.1.

Chrome logs this:

>`Uncaught RangeError: Maximum call stack size exceeded
>    at attrHandle.(anonymous function) (https://code.jquery.com/jquery-2.2.4.js:7228:31)
>    at Sizzle.attr (https://code.jquery.com/jquery-2.2.4.js:1455:4)`

`$("div[Disabled]")` and `$("#elem").find("div[Disabled]")` work fine.  As does `$("#elem").parents("div[disabled]");`

In the code near the recursive call, I see a note about saving and restoring the attribute getter, but it doesn't use the .toLowerCase() version of the attribute name, while the thing it calls does.

### Link to test case ###
JSFiddle: https://jsfiddle.net/mdvv4c2j/3/

**Comment by mgol** [comment]
We only support the latest jQuery version (currently 3.1.1) so if it works there there's nothing for us to do.
