### ISSUE TITLE
selected <option> not rendered in a <select> above v1.8.3

### ISSUE THREAD

**Issue by bum2** [jquery/jquery#3525]
**Description**

With versions higher than jquery 1.8.3, when you manipulate the selections in a <select> options, they just work few times displaying the modified select, and then stop rendering the html behind.

So the html keeps updating but the form select stops displaying the correct option and shows always the first one.

That happens to me with Firefox ESR 45.5.1 and also in Chrome 50.0.2661.102 (64-bit) in a debian8 machine.

In the fiddle i've placed an easy example of what i mean: with 1.8.3 it works good 'always', but with higher jquery versions, it works only a first times and fails: (just click the links to change the select option and see)... 

I have not found any clue about this behavior, and i have tried many forms of the 'selected' attribute, etc, an explanation and a fix will be appreciated.

**Link to test case**

https://jsfiddle.net/3d83b65r/

**Comment by mgol** [comment]
It works fine for me in the latest jQuery 3.1.1 (and we only support the latest version).

However, this is misuse of the API; you should use `prop` for changing dynamic state, not `attr`, it works fine then:
https://jsfiddle.net/3d83b65r/2/

Please read the jQuery 1.9 migrate guide, in particular: https://jquery.com/upgrade-guide/1.9/#attr-versus-prop-
