### ISSUE TITLE
Display 01 Oct 2017 day  mismatch in two system, why? 

### ISSUE THREAD

**Issue by A-Rana** [jquery/jquery#3526]
![issue 1](https://cloud.githubusercontent.com/assets/13313249/22537153/f8d8929c-e92d-11e6-95ba-4bb1e7dfacd8.png)
![issue 2](https://cloud.githubusercontent.com/assets/13313249/22537154/f8dd495e-e92d-11e6-960c-df55d1d00dd6.png)

### Description ###
Hi, 
Here I attach the two screenshot in which you can see for 1 Oct 2017 show different day, why, is this jquery date picker issue or something else.
use the latest version of jquery and jqueryUI, but a result is same

**Comment by mgol** [comment]
jQuery UI bug tracker is at https://bugs.jqueryui.com/ so issues with UI should be reported there. 

However, here I suspect it's just a question of having a different date locale set as in some countries Sunday is considered the first day and in others Monday.
