### ISSUE TITLE
[iOS] scrollTop value while animation is jumping in $(window).on('scroll') Listener

### ISSUE THREAD

**Issue by wexstorm** [jquery/jquery#3528]
When using the scroll Listener on the $(window) Object on iOS 10 and Scrolling via animate Function, the value for scrollTop jumps back and forth. Sometimes it seems to reset to a previous value.

In my particular example I can read values like:
[Log] 646 (script.js, line 340)
[Log] 756 (script.js, line 340)
**[Log] 988 (script.js, line 340)
[Log] 1211 (script.js, line 340)
[Log] 988 (script.js, line 340)**
while scrolling.

In the TestCase I get values like these:
[Log] 783 (jq, line 17)
[Log] 909 (jq, line 17)
[Log] 1052 (jq, line 17)
[Log] 1203 (jq, line 17)
**[Log] 1383 (jq, line 17)
[Log] 1382 (jq, line 17)**
[Log] 1582 (jq, line 17)
[Log] 1755 (jq, line 17)
[Log] 1920 (jq, line 17)

Test-Case:
https://jsfiddle.net/bplutka/um5hh81s/3/
Version for using directly in iOS Safari (activated Developer Console in Safari on Mac):
http://www.bit-storm.de/jq/

**Comment by timmywil** [comment]
Thank you for opening an issue, but I can't think of anything we can do in jQuery. We are simply binding to the native scroll listener and reporting the value. Keep in mind that console.log often logs asynchronously and when each log shows up is dependent on several factors, most of which are not under jQuery's control.
