### ISSUE TITLE
Disabled button still fires click event for jQuery.fn.click()

### ISSUE THREAD

**Issue by cobexer** [jquery/jquery#3531]
A disabled button still receives the click event if it is triggered using the click() method without arguments.

jQuery version: 3.1.1, we also use jQuery UI 1.12.1 but that is not required to trigger this bug (the real use case uses a jQuery UI Button).

Expected: calling .click() on disabled elements should do nothing - consistent with user clicks on disabled elements.
Actual: .click() triggers the event handler, whereas user clicking does not.
Browsers Tested: Internet Explorer 11, Firefox 51, Chrome 56

Minimal Test Case: https://jsfiddle.net/28ow69kw/3/

```html
<button id="btn" disabled>Test Button</button>
<span id="result"></span>
```

```javascript
var $r = $('#result');
$('#btn').on('click', function() {
  $r.text('FAILED;' + $r.text());
});

$('#btn').click();
$r.text($r.text() ? $r.text() : 'SUCCEEDED');
```

I searched the old tracker, this tracker and the forums but could not find any mention of this inconsistency so I hope this has not been filed before.

**Comment by dmethvin** [comment]
A script is allowed to do things to the user interface that a user cannot. Note that it's also legal in the bare DOM API to fire an event at a disabled button. 

https://jsfiddle.net/dmethvin/28ow69kw/4/

To avoid having code click on a disabled button, check whether it is disabled before running the code.
