### ISSUE TITLE
Pass array of classes to `.addClass()`, `removeClass()`, and `toggleClass()` 

### ISSUE THREAD

**Issue by t-kelly** [jquery/jquery#3532]
### Description ###
It would be great if these examples:
```js
var class1 = 'class-one';
var class2 = 'class-two';

$('.element').addClass(class1 + ' ' + class2);
$('.element').addClass(class1).addClass(class2);
$('.element').addClass([class1, class2].join(' '));
```

could instead be written like:
```js
var class1 = 'class-one';
var class2 = 'class-two';

$('.element').addClass([class1, class2]);
```

**Comment by timmywil** [comment]
For the most part, we're not looking to add signatures or new features to jQuery, but I don't hate this. It has parody with libraries like React and Angular.

**Comment by timmywil** [comment]
Also, we long to be a "parody" of everything. Sigh...edited.

**Comment by dmethvin** [comment]
Note that this can already be done by `$('.element').addClass([class1, class2].join(" "));` which isn't that burdensome. It will take more bytes than that to do this inside jQuery.

**Comment by mgol** [comment]
@dmethvin It's true but it's also uglier. :) I like it because:

1. We don't currently accept arrays as any parameter to class methods so there should be no confusion. Because of that, it shouldn't also add _that much_ code to jQuery.
2. Accepting classes will align us more with the classList standard and aligning with standards is A Good Thing.
3. It will allow to pass unprocessed class arrays to jQuery from other libraries/frameworks that use the array syntax.
4. (This one is a bit of a stretch, but...) If we ever drop IE and start using classList instead of classNames everywhere, this would be a more natural signature and the space-separated values would be the ones that requires more pre-processing.

**Comment by niltoncsr** [comment]
I'd like to contribute and get this one! :smiley:
What do you think, @timmywil?

**Comment by RUPOJS** [comment]
Hi @timmywil, is this already assigned to someone ? I wan to take this up.

**Comment by Jacabola** [comment]
Hi @timmywil, I want to take this up.

**Comment by jbedard** [comment]
Should this add support for arrays (`addClass(["a", "b"])`) or multiple arguments (`addClass("a", "b")`), or both?  The multiple arguments one is more like the [classList methods](https://developer.mozilla.org/en/docs/Web/API/Element/classList#Methods) so that would be my vote.

**Comment by t-kelly** [comment]
Multiple arguments might conflict with `.toggleClass()`'s second boolean argument 🤔

**Comment by jbedard** [comment]
Seems like `classList.toggle` doesn't support multiple classes, only add/remove support it. I still vote to do the same as `classList` and don't support it with `toggleClass`...

**Comment by mgol** [comment]
@jbedard We've discussed it already (you were present :)), accepting positional parameters would require way more code and would align _worse_ with the standard because of funkiness like `.addClass('a b c', 'd')`; the discussion can be seen at https://gitter.im/jquery/meeting/archives/2017/02/06.

**Comment by jbedard** [comment]
That was a long time ago! That info should be put in this ticket for those wanting to pick it up...

**Comment by faisaliyk** [comment]
If no one has worked on it, can I take a stab at it?

**Comment by timmywil** [comment]
Anyone who would like to submit a PR for this, please feel free. Our [contributing guidelines](http://contribute.jquery.org/) should answer any questions you might have about contributing to jQuery. Specifically, I suggest having a look at the [Commits and PR guidelines](http://contribute.jquery.org/commits-and-pull-requests/) and [JS style guide](http://contribute.jquery.org/style-guide/js/).

**Comment by faisaliyk** [comment]
Working on it.
