### ISSUE TITLE
slideToggle and mobile compatible page resizing

### ISSUE THREAD

**Issue by mgelfman1** [jquery/jquery#3534]
### Description ###
slideToggle is not effected by display:inline-block when the page is resizable. The image, div, etc. slides off the screen when the divisions are meant to be mobile compatible (width/height are percentages, display:inline-block, etc.). To get around this, using float with set widths and heights can solve the problem. This is not technically a bug for slideToggle but since it is a common issue scenario for mobile applications, I thought I would post it here to add to tutorials or whatnot. Also, I figured that since some applications require display:inline-block instead of float, this information would be useful.

PROBLEM
NOTE: In both examples, some parent has declared a width and a height as 100%
NOTE: Both code examples display exact height and width to show how they do not effect the result.
script
jQuery(document).ready(function() {
  jQuery( "#flip" ).hover(function() {
    jQuery( "#flipFront" ).slideToggle();
    jQuery( "#flipBack" ).slideToggle();
  });
});
/script

div style="**display: inline-block;** height: 270px; margin: 5px;"
div id="flip" class="flip" style="height: 270px; width: 270px;"
div id="flipBack" class="back" style="display: none; height: 270px; width: 270px; background-color: #0077bb; color: #ffffff; box-shadow: 4px 4px 4px #333333; vertical-align: top; padding: 5px;"
h4 Text Here /h4
/div
div id="flipFront" class="front" style="display: contents; height: 270px; width: 270px;"><img id="imgFlipFront" style="box-shadow: 4px 4px 4px; width: 270px; height: 270px;" src="images/flip.jpg" /
/
/div
/div
/div

SOLUTION
script
jQuery(document).ready(function() {
  jQuery( "#flip" ).hover(function() {
    jQuery( "#flipFront" ).slideToggle();
    jQuery( "#flipBack" ).slideToggle();
  });
});
/script

div style="**float: left;** height: 270px; margin: 5px;"
div id="flip" class="flip" style="height: 270px; width: 270px;"
div id="flipBack" class="back" style="display: none; height: 270px; width: 270px; background-color: #0077bb; color: #ffffff; box-shadow: 4px 4px 4px #333333; vertical-align: top; padding: 5px;"
h4 Text Here /h4
/div
div id="flipFront" class="front" style="display: contents; height: 270px; width: 270px;"><img id="imgFlipFront" style="box-shadow: 4px 4px 4px; width: 270px; height: 270px;" src="images/flip.jpg" /
/div
/div
/div

### Link to test case ###
http://www.melissabehrends.com/

**Comment by gibson042** [comment]
http://www.melissabehrends.com/ appears to be running jQuery 1.12.4. If you are experiencing the problem in a supported version, please provide a live test case (e.g., with [JSFiddle](https://jsfiddle.net/) or [JS Bin](https://jsbin.com/?html,output)).
