### ISSUE TITLE
extend bug for reference type

### ISSUE THREAD

**Issue by jiangshanmeta** [jquery/jquery#3536]
### Description ###

Here are my code
```
var arr = ["a","b","c"];
var obj = {
	a:"a",
	b:"b"
}

var extendObj1 = {
	"arr":arr,
	"naive":"young",
	"obj":obj
}

var extendObj2 = {
	"arr":['d','e','f'],
	"simple":"too simple",
	"obj":{
		"a":"a2",
		"b":"b2"
	}
}


$.extend(true,extendObj1,extendObj2);

console.log(extendObj1);
console.log(arr);
console.log(obj)
```

I use the utility extend in jQuery. The variable ```extendObj1```  is what I want,but variable ```arr``` and 
variable ```obj``` changed after extend.Variable ```arr``` became ```['d','e','f']```,but I don`t want it to be changed,it should be ```['a','b','c']``` as original.Same situation for variable  ```obj```.

After read the original code,I think code responsible for this situation is

```
if ( deep && copy && ( jQuery.isPlainObject( copy ) ||
	( copyIsArray = jQuery.isArray( copy ) ) ) ) {

	if ( copyIsArray ) {
		copyIsArray = false;
		clone = src && jQuery.isArray( src ) ? src : [];

	} else {
		clone = src && jQuery.isPlainObject( src ) ? src : {};
	}

	// Never move original objects, clone them
	target[ name ] = jQuery.extend( deep, clone, copy );

// Don't bring in undefined values
} 

```

And in my opinion ,the right code is:

```
if ( deep && copy && ( jQuery.isPlainObject( copy ) ||
	( copyIsArray = jQuery.isArray( copy ) ) ) ) {

	if ( copyIsArray ) {
		
		clone = src && jQuery.isArray( src ) ? src : [];

	} else {
		clone = src && jQuery.isPlainObject( src ) ? src : {};
	}

	// Never move original objects, clone them
	target[ name ] = jQuery.extend( deep,copyIsArray?[]:{} ,clone, copy );
	copyIsArray = false;
// Don't bring in undefined values
}
```

### Link to test case ###

[minimal case](https://jsbin.com/qugobe/edit?html,js,console,output)

**Comment by mgol** [comment]
Thanks for the report. However, this behavior is expected as we don't want the deep extend to swap values in sub-objects. This is also how other libraries implement the deep extend a.k.a. merge (e.g. lodash). So I don't think we want to change it.

In your case, if you don't want any sub-objects to be modified, add an empty object as the first argument:
```js
$.extend(true, {}, extendObj1, extendObj2);
```

If you think documentation is unclear, please post your proposal on how to improve it to https://github.com/jquery/api.jquery.com/issues/.

**Comment by mgol** [comment]
BTW, that bug report was done in a very good way with lots of details, thanks for that!
