### ISSUE TITLE
dropdown selection broken on Firefox after prepending new option

### ISSUE THREAD

**Issue by jaspervries** [jquery/jquery#3539]
### Description ###
In Firefox, when using .prepend() to add a new `<option>` to a `<select>`, the resulting dropdown will not allow the user to select a value from the list and instead return the first value from the original option-set on any clicked option from the select-element.
This only happens when the new `<option>` is added via .prepend() as HTML with both attributes _selected_ and _disabled_ set (i.e. `.prepend('<option id="optp" value="" disabled="disabled" selected="selected">(inserted option)</option>'`. When either attribute is omitted, the dropdown works as expected. When either is omitted, but subsequently set via .attr() method, it also works as expected.

I could only reproduce this behaviour in Firefox. It works fine in Internet Explorer (11) and Chromium (48). I am using Firefox 51.0.1 (64-bits) on Windows 7. I must add that I am not sure whether the problem is with Firefox or with jQuery, but decided to report it here. If you can estabish the problem is not with jQuery, then please let me know and I will pass it on to Mozilla. 

### Link to test case ###
https://jsfiddle.net/afxn9sxg/2/
* Select "Option 2" from the dropdown. It will return Option 1 instead. Now select "Option 3" from the dropdown and it will return Option 2. From this point you can select anything and it will work as expected.
* Run Fiddle again. Now select "Option 3". Again it will return Option 1, but now you can select "Option 3" and it will return the correct value.

**Comment by gibson042** [comment]
I am unable to reproduce, but this is not a jQuery problem (which you should be able to confirm at https://jsfiddle.net/afxn9sxg/4/ ). Have you tried in Private mode without extensions?

**Comment by jaspervries** [comment]
Thank you for your quick reply. I was still able to reproduce with Firefox in safe mode and private mode. But then also occurs with the two other insert methods you provided in https://jsfiddle.net/afxn9sxg/4/ .
Therefore I agree this is NOT a jQuery problem.
Thank you for providing this improved test case that allows me to try and reproduce it on other computers.
