### ISSUE TITLE
jQuery 3.1.0 bug

### ISSUE THREAD

**Issue by wajdijurry** [jquery/jquery#3543]
### Description ###

When try to use $('#textarea').val(), it removes all email from text extracted from the textarea element.

### Link to test case ###
I tested it on my local host, I integrated a minified library of jQuery 3.1.0, then I tried to get textarea value by $('#textarea').val(). When the value contains one or more email addresses, it retrn the value without any email address.

Check the attached photo please.
![screenshot-192 168 6 25 8133-2017-02-15-17-20-30](https://cloud.githubusercontent.com/assets/25797257/22980775/25991b1a-f3a3-11e6-9f8a-e2b1b1b4193f.png)

![screenshot-mail google com-2017-02-15-17-24-52](https://cloud.githubusercontent.com/assets/25797257/22980962/b0836960-f3a3-11e6-9987-3263058ca160.png)

**Comment by mgol** [comment]
As the issue template asked, we need a test case on jsfiddle.net or jsbin.com. A screenshot is not enough for us to tackle the problem.

**Comment by cataclysm1987** [comment]
Can you at least post your code if you want help? You don't necessarily need to post your jsfiddle but we have to see the code.
