### ISSUE TITLE
jQuery.extend - bug

### ISSUE THREAD

**Issue by bvellacott** [jquery/jquery#3546]
I think there is a bug in core.js lines 174 and 175 with the extend function:

```js
if ( deep && copy && ( jQuery.isPlainObject( copy ) ||
	( copyIsArray = Array.isArray( copy ) ) ) ) {
```
the bug is this: if ```jQuery.isPlainObject( copy )``` evaluates as true, then ```copyIsArray = Array.isArray( copy )``` won't get evaluated and the code will continue execution with a stale value. 

Should obviously effect all browsers.

**Comment by mgol** [comment]
Could you share a test case at https://jsfiddle.net or https://jsbin.com that will show clearly on what input you expect a different output (and what should be different)?

**Comment by bvellacott** [comment]
I'll give it a shot

**Comment by luis140219** [comment]
This is the fixed code:
`if (deep && copy && (jQuery.isPlainObject(copy) ? (!(copyIsArray = false)) : (copyIsArray = Array.isArray(copy)))) {`

**Comment by mgol** [comment]
No test case has been provided for almost two weeks so I'm closing the issue. If a test case is added we can reopen.

**Comment by bvellacott** [comment]
@mgol had a play and realised that I made a mistake with $.isPlainObject(). I thought it was returning true for arrays in my tests. There must have been something else wrong. Sorry about that
