### ISSUE TITLE
ToggleClass bug

### ISSUE THREAD

**Issue by xahon** [jquery/jquery#3549]
ToggleClass with *undefined* second parameter toggling class. Looks like a bug, after all it should be ignored, shouldn't it __?__

[JsFiddle demo](https://jsfiddle.net/x8sd35cm/)

**Comment by dmethvin** [comment]
If the behavior isn't defined by the documentation, what should it do? It's undocumented so it might do anything. If it does something specific, then it should be documented. The [docs say](http://api.jquery.com/toggleclass/) that `state` is "A Boolean (not just truthy/falsy) value to determine whether the class should be added or removed." Those values are not Boolean.

**Comment by timmywil** [comment]
Agreed, because of the multiple signatures, I don't think we can assume that `undefined` is always the same as false.
