### ISSUE TITLE
Hidden input with no "value" attribute in IE11 has value="" created when cloned 

### ISSUE THREAD

**Issue by deadbeef404** [jquery/jquery#3550]
The `.clone()` function seems to work differently in IE11 than other non-IE browsers.

The following code appends input fields to the `<body>` tag:

https://jsfiddle.net/deadbeef404/uwu1ntL5/

Inspector for the following browsers on OSX 10.11.6

- Chrome Version 56.0.2924.87 (64-bit),
- Safari, Version 9.1.2 (11601.7.7),
- Firefox 51.0.1 (64-bit)

Show:
```
<input type="hidden" id="test">
<input type="hidden" id="test">
```

IE11 on windows shows:
```
<input type="hidden" id="test"></input>
<input type="hidden" id="test" value=""></input>
```

As a sidenote, my team noticed this is an issue because a selector of `[value]` on the end was returning an empty array for everything except IE11.

**Comment by dmethvin** [comment]
In the IE11 DOM inspector I don't see the screwy closing input tag, but I do see that the empty `value` attribute appears. This is due to [another workaround we do here](https://github.com/jquery/jquery/blob/ac9e3016645078e1e42120822cfb2076151c8cbe/src/manipulation.js#L123) where we set `defaultValue`. That's all the time I have right now but the next step would be look at the blame to see if we can remove this workaround or remove it for certain types of inputs.

**Comment by timmywil** [comment]
Let's do an audit of the `fixInput` function that @dmethvin linked. Setting `defaultValue` may still be necessary, but if not, great!

**Comment by mgol** [comment]
I've already done a review of [`fixInput`](https://github.com/jquery/jquery/blob/ac9e3016645078e1e42120822cfb2076151c8cbe/src/manipulation.js#L114-L125) when I was removing support from IE 9-10 on `master`; the comment next to the [line linked by @dmethvin](https://github.com/jquery/jquery/blob/ac9e3016645078e1e42120822cfb2076151c8cbe/src/manipulation.js#L123) is incorrect as it refers to other workarounds that were already removed.

My PR resulted in a change from [this `fixInput` usage](https://github.com/jquery/jquery/blob/ac9e3016645078e1e42120822cfb2076151c8cbe/src/manipulation.js#L257) to an [inlined workaround for `textarea`](https://github.com/jquery/jquery/blob/79b74e043a4ee737d44a95094ff1184e40bd5b16/src/manipulation.js#L232-L237) which is still needed in IE 11 but only for a `textarea`. Is there anything left we can do here? If not, we should close this issue; if we think this may not be necessary even in IE 9 we could potentially look at it for `3.4.2`.

Thoughts?

**Comment by timmywil** [comment]
I agree we can close this issue, but I don't think the selector issue (i.e. #4435) is yet addressed.

**Comment by mgol** [comment]
Removing the milestone since there's nothing we plan to do for this issue and certainly not for 3.x.

@timmywil please reopen if I missed anything.
