### ISSUE TITLE
On Method Adds Multiple Instances of Event Handlers

### ISSUE THREAD

**Issue by bfailing** [jquery/jquery#3552]
Fiddle showing issue: https://jsfiddle.net/ghgphbhg/1/
Fiddle showing expected behavior: https://jsfiddle.net/2cevL2hm/1/

Using the on() method, a mouseenter-mouseover event combination attaches two instances of the mouseover event handler.  No instances of the mouseenter event handler are attached.  Expected behavior is attaching of only one instance of the mouseover event handler and one instance of the mouseenter event handler.

Using the on() method, a mouseleave-mouseout event combination attaches two instances of the mouseout event handler.  No instances of the mouseleave event handler are attached.  Expected behavior is attaching of only one instance of the mouseout event handler and one instance of the mouseleave event handler.

This was only tested with JQuery 3.1.0.  Browsers tested were latest Firefox and latest Chrome running on Windows 10 desktop (standard, non-touch monitor).

**Comment by mgol** [comment]
We have to emulate mousenter/mouseleave via mouseover/mouseout. See #3295 for more details.
