### ISSUE TITLE
Type checking support for Array Iterator

### ISSUE THREAD

**Issue by danahartweg** [jquery/jquery#3553]
### Description
When using Babel, specifically with array polyfills for iterator support, all array prototypes are modified for that support. Therefore, ```toString.call(obj)``` reports as ```[object Array Iterator]``` instead of simply ```[object Array]```, which jQuery has no awareness of in the ```class2type``` map. The goal would be to update the ```class2type``` map for that support so these arrays report themselves as arrays instead of objects.

I know there has been some contention with this type checking in the past, specifically around the ```Error``` object, so I decided to open an issue for discussion before submitting a PR with the changes proposed below.

### Proposed changes
Not sure the best way to provide a test case for this. Instead,  [this is the code change](https://github.com/danahartweg/jquery/commit/a6bf56006dd21604e45850d314251db64ac856d1) I had in mind.

**Comment by mgol** [comment]
Could you provide an example? This is the first time I hear about it; I've tried it in a simple Babel repl and it works fine:
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=ie%209&builtIns=false&experimental=false&loose=false&spec=false&playground=false&code=console.log(Object.prototype.toString.call(%5B1%2C%202%5D))%3B%0A

**Comment by danahartweg** [comment]
I'll definitely work on getting an example together / tracking down the exact part of Babel that is causing the problem. Things have been crazy since I submitted this issue originally.

**Comment by danahartweg** [comment]
Very sorry for the additional delay, but I've finally been able to do some digging. It appears that this is an issue specifically when using the ```babel-transform-runtime``` plugin instead of ```babel-polyfill```.

**Comment by mgol** [comment]
@danahartweg could you provide a simple example project where it fails?

**Comment by danahartweg** [comment]
@mgol I was unable to reproduce the failure in a clean project with the exact same dependencies from the project I initially noticed the issue. Given the size of the main project, there is obviously some other condition causing ```babel-transform-runtime``` to pollute the Array prototypes.

Sorry for taking up your time with this. I'm going to close the issue until I can (if ever) nail down the exact condition babel is hitting.

**Comment by mgol** [comment]
Thanks for an update! Let us know if you ever manage to reproduce it in a minimal project.

**Comment by bvarga** [comment]
Just a note. 

[Here](https://github.com/babel/babel/issues/5518) you can find a detailed description of the problem.
Mainly you need an old 1.7.0 prototype.js to break things. however It's fixed in 1.7.3.

regards
Balazs
