### ISSUE TITLE
Exceptions from .trigger("remove") are silently swallowed

### ISSUE THREAD

**Issue by tim-janik** [jquery/jquery#3554]
Users can't see exceptions thrown by erroneous remove handlers, example:
~~~~
$('<i/>').appendTo(document.body).on('remove', function() { console.log('remove:'); throw "some bug"; }).remove()
~~~~

Observed:
~~~~
remove:
~~~~

Expected:
~~~~
remove:
Uncaught "some bug"
~~~~

Fix:
~~~~
diff --git jquery-ui-1.12.1.js jquery-ui.js
index 0213552..32c6865 100644
--- jquery-ui-1.12.1.js
+++ jquery-ui.js
@@ -48,12 +48,12 @@ $.cleanData = ( function( orig ) {
 
                                // Only trigger remove when necessary to save time
                                events = $._data( elem, "events" );
-                               if ( events && events.remove ) {
-                                       $( elem ).triggerHandler( "remove" );
-                               }
-
                        // Http://bugs.jquery.com/ticket/8235
                        } catch ( e ) {}
+                       if ( events && events.remove ) {
+                               $( elem ).triggerHandler( "remove" );
+                       }
+
                }
                orig( elems );
        };
~~~~

**Comment by mgol** [comment]
I can't confirm that: https://jsfiddle.net/w975uww4/1/.

Note that `.trigger('remove')` is not the same as `.remove()`.

**Comment by tim-janik** [comment]
@mogl you are testing the wrong thing.

Note that .trigger('remove') is *not* the same as .remove(). The bug is not in jquery 'tirgger()', but in the jqueryui implementation of cleanData which is called upon remove().
Please take a look at cleanData in:
  https://github.com/jquery/jquery-ui/blob/master/ui/widget.js

**Comment by scottgonzalez** [comment]
The jQuery UI bug tracker is at https://bugs.jqueryui.com. I have already fixed this by removing the try/catch since it was only there for old versions of jQuery which we no longer support. See https://github.com/jquery/jquery-ui/commit/1f2011ece3fe6847874677e9a8210fa202498ccb
