### ISSUE TITLE
Golfing 21 bytes

### ISSUE THREAD

**Issue by luis140219** [jquery/jquery#3555]
### Description ###
jQuery and Sizzle follow the byte-wasting practice of using "true" instead of "1" in constant arguments to for in loops, such as following:
```javascript
// Add button/input type pseudos
for ( i in { radio: true, checkbox: true, file: true, password: true, image: true } ) {
	Expr.pseudos[ i ] = createInputPseudo( i );
}
for ( i in { submit: true, reset: true } ) {
	Expr.pseudos[ i ] = createButtonPseudo( i );
}
```

This could be rewritten as:
```javascript
// Add button/input type pseudos
for (i in {radio: 1, checkbox: 1, file: 1, password: 1, image: 1}) {
	Expr.pseudos[i] = createInputPseudo(i);
}
for (i in {submit: 1, reset: 1}) {
	Expr.pseudos[i] = createButtonPseudo(i);
}
```

The 21 bytes only include changing "true" to "1".

### Link to test case ###

This is not a bug.

**Comment by dmethvin** [comment]
Usually Uglify does this for us. We prefer clarity in the non-minified source. Are you not seeing this transform in the minified file? What version?

**Comment by mgol** [comment]
Uglify is AFAIK not detecting that values are not used here so it leaves them as `!0`. As for clarity, `true` isn't very clear either, it's just a hack due to not having `for-of` in ES5.

**Comment by luis140219** [comment]
Note: `1` is shorter than `!0` and results in 7 bytes of savings in the minified version, as well as cleaner code in the non-minified version

**Comment by dmethvin** [comment]
Sounds fine to me then, I see your point!

**Comment by mgol** [comment]
> Note: 1 is shorter than !0 and results in 7 bytes of savings in the minified version, as well as cleaner code in the non-minified version.

Yup, that was my point. :) @luis140219 running `grunt` before & then after the change should show you the minified & gzipped version, not just minified and we mostly care about the size after gzip. What's the difference there?

**Comment by markelog** [comment]
Sounds good to me also, pr welcome :)

**Comment by markelog** [comment]
Although this is more like sizzle issue, which has a different repo - https://github.com/jquery/sizzle, 

I can see though how this could improve things in css module - https://github.com/jquery/jquery/blob/ac9e3016645078e1e42120822cfb2076151c8cbe/src/css.js#L189. But `cssNumber` is external and documented property - https://api.jquery.com/jQuery.cssNumber/. 

Pretty much the same story with `event` module, could be done for `manipulation` though - https://github.com/jquery/jquery/blob/ac9e3016645078e1e42120822cfb2076151c8cbe/src/traversing.js#L18

**Comment by mgol** [comment]
Good findings @markelog. I'd be careful to not touch objects that are public APIs like `jQuery.cssNumber` but changing the others should be fine.

**Comment by mgol** [comment]
@luis140219 would you like to submit a PR?

**Comment by luis140219** [comment]
I'll do it.

**Comment by luis140219** [comment]
The PR is here: jquery/sizzle#401.

**Comment by timmywil** [comment]
See https://github.com/jquery/sizzle/pull/401
