### ISSUE TITLE
Feature request: return state boolean from toggleClass

### ISSUE THREAD

**Issue by jamieide** [jquery/jquery#3556]
Feature request: Make toggleClass return a boolean state value that indicates if the class was added (true) or removed (false). I think there are many use cases for this but the one I have at the moment is that I'm using toggleClass to toggle Bootstrap's hidden class on a spinner and I also need to disable form elements. It would be handy to have a value I could provide to .attr("disabled", bool) without having to call .hasClass.

For consistency, I also propose changing addClass and removeClass to return a boolean indicating if the class was actually added or removed, respectively.

**Comment by dmethvin** [comment]
These methods are already documented to return the current set for chaining. (Note that the [API page](http://api.jquery.com/toggleclass/) says `Returns: jQuery`) We can't change that. You can chain a `.hasClass()`  after the operation.

**Comment by jamieide** [comment]
Sorry to waste your time, fortunately this was the dumbest thing I did that day.
