### ISSUE TITLE
suggestion for enhancement in jquery 

### ISSUE THREAD

**Issue by bawasaab** [jquery/jquery#3563]
am using <a href="https://nwjs.io/">nwjs</a>. i want to handle post data of form on submit using jquery as like in php $_GET or $_POST array or object. plz provide the same functionality if possible.

yes i know the jquery works on frontend client side.

for example:<br>

let us have a form with employees data. on submit i get

array(
name => abc
)

array(
0 => array(
name => abc
)
)

there should be a method to get the object like above said format.

in case of serialize object as well  as serialize array it over writes the keys in case of same name[], multiple check boxes, radio buttons and do not append the 0, 1 and so on. now am using a script as i mentioned below but it handles it on at one level i.e. 0 level

but i need more than 0 level. it would be great help. thanx

<h1>get serializeObject</h1>
<pre>
$.fn.serializeObject = function() {
	var data = {};
	$.each( this.serializeArray(), function( key, obj ) {
		var a = obj.name.match(/(.*?)\[(.*?)\]/);
		if(a !== null)
		{
			var subName = new String(a[1]);
			var subKey = new String(a[2]);
			if( !data[subName] ) {
				data[subName] = { };
				data[subName].length = 0;
			};
			if (!subKey.length) {
				subKey = data[subName].length;
			}
			if( data[subName][subKey] ) {
				if( $.isArray( data[subName][subKey] ) ) {
					data[subName][subKey].push( obj.value );
				} else {
					data[subName][subKey] = { };
					data[subName][subKey].push( obj.value );
				};
			} else {
				data[subName][subKey] = obj.value;
			};
			data[subName].length++;
		} else {
			var keyName = new String(obj.name);
			if( data[keyName] ) {
				if( $.isArray( data[keyName] ) ) {
					data[keyName].push( obj.value );
				} else {
					data[keyName] = { };
					data[keyName].push( obj.value );
				};
			} else {
				data[keyName] = obj.value;
			};
		};
	});
	return data;
};
</pre>

<h1>get serializeAssoc</h1>
<pre>
$.fn.serializeAssoc = function() {
	var data = {};
	$.each( this.serializeArray(), function( key, obj ) {
		var a = obj.name.match(/(.*?)\[(.*?)\]/);
		if(a !== null)
		{
			var subName = a[1];
			var subKey = a[2];

			if( !data[subName] ) {
				data[subName] = [ ];
			}

			if (!subKey.length) {
				subKey = data[subName].length;
			}

			if( data[subName][subKey] ) {
				if( $.isArray( data[subName][subKey] ) ) {
					data[subName][subKey].push( obj.value );
				} else {
					data[subName][subKey] = [ ];
					data[subName][subKey].push( obj.value );
				}
			} else {
				data[subName][subKey] = obj.value;
			}
		} else {
			if( data[obj.name] ) {
				if( $.isArray( data[obj.name] ) ) {
					data[obj.name].push( obj.value );
				} else {
					data[obj.name] = [ ];
					data[obj.name].push( obj.value );
				}
			} else {
				data[obj.name] = obj.value;
			}
		}
	});
	return data;
};
</pre>

thanx
with regards,
deepak bawa

**Comment by mgol** [comment]
I'm not sure what you're asking for. PHP is on the backend side, jQuery works on the frontend site. Could you be more precise in your request?

**Comment by neu5** [comment]
@bawasaab probably jQuery have provided this functionality already.
Check this out:
https://api.jquery.com/serializeArray/

**Comment by bawasaab** [comment]
hi i have ipdated my request plz hav a look thanx

**Comment by neu5** [comment]
@bawasaab can you please provide the simplest example with HTML and jQuery code using e.g.:
https://jsfiddle.net/

**Comment by mgol** [comment]
Just use `foo[]` instead of `foo` as name of the repeated inputs: https://jsfiddle.net/r1p5xprq/.

It's unlikely we'd modify the current method as it may cause compatibility issues. Creating a new one would be best done in a plugin.

**Comment by bawasaab** [comment]
i have created a js fiddle plz hav a look
https://jsfiddle.net/deepak_bawa/wbp5da4a/

**Comment by mgol** [comment]
You need to look for external jQuery plugins if you need that. Maybe https://github.com/macek/jquery-serialize-object would work for you.

**Comment by bawasaab** [comment]
its better if jquery provide it default

**Comment by bawasaab** [comment]
i have updated the js fiddle again plz hav a look
https://jsfiddle.net/deepak_bawa/wbp5da4a/

**Comment by mgol** [comment]
This would be an entirely new method (and quite a big one at that) which every jQuery user would have to download even if they don't need it.

Therefore, I don't see it included in jQuery.

Please read https://github.com/jquery/jquery/wiki/Adding-new-features, in particular the following point:
> **Is the need already served by a plugin?** If there is a jQuery plugin that already does the job well, there is little reason for us to add duplicate functionality inside the library. Simply use the plugin.

**Comment by bawasaab** [comment]
dear mgol plz look the updated fiddle

**Comment by dmethvin** [comment]
@bawasaab You're making a lot of demands here. I agree with @mgol. Use a plugin or use StackOverflow to ask for help on building what you want.

**Comment by bawasaab** [comment]
sorry for above said.
i need only a method to get the submitted form data easily without any third party plugin. if its not possible i will do it my self
