### ISSUE TITLE
Uncaught TypeError: elem.getClientRects is not a function using .offset()

### ISSUE THREAD

**Issue by kaluabentes** [jquery/jquery#3564]
Hello everyone, i'm getting Uncaught TypeError: elem.getClientRects is not a function when i'm using .offset()

`$(window).scroll(function(){
        console.log($(window).offset());
 });`

Console output:

`Uncaught TypeError: elem.getClientRects is not a function
    at jQuery.fn.init.offset (jquery.js:9960)
    at script.min.js:1
    at dispatch (jquery.js:5201)
    at elemData.handle (jquery.js:5009)`

Anyone can see this?

**Comment by mnn** [comment]
I am getting this error too, how did you solve it?
