### ISSUE TITLE
Test for dimensions intermittently aborts early in Chrome

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#3570]
### Description ###
<http://swarm.jquery.org/result/2019677>
<img width="561" alt="screen shot 2017-03-16 at 14 55 24" src="https://cloud.githubusercontent.com/assets/156867/24020259/9d98daa8-0a58-11e7-9148-585969d049ee.png">

Strangely, it is aborting without actually timing out or showing any kind of error. It stops immediately.

This is the before last time it times out on.

18. dimensions: allow modification of coordinates argument (gh-1848) [Passes]
19. dimensions: outside view position (gh-2836) [Running]
20. dimensions: width/height on element with transform (gh-3193) [Scheduled/Invisible]

**Comment by timmywil** [comment]
Thanks! We'll try to track this down along with #3571. If it's intermittent, it might be difficult to address, but we'll make sure the tests pass before releasing.
