### ISSUE TITLE
$.holdReady is broken in 3.2.0

### ISSUE THREAD

**Issue by San4es** [jquery/jquery#3573]
The "$.holdReady is not a function" error occurs after the update to jQuery 3.2.0.

To reproduce the issue, see https://jsfiddle.net/4ocpkd69/ (see browser console) and compare results with jQuery 3.1.1 in https://jsfiddle.net/4ocpkd69/1/

**Comment by mgol** [comment]
It was moved erroneously to `jQuery.fn.holdReady` in bd984f0ee2cf40107a669d80d92566b8625b1e6b. Marking as a blocker for 3.2.1.

**Comment by mgol** [comment]
It was moved erroneously to `jQuery.fn.holdReady` in bd984f0ee2cf40107a669d80d92566b8625b1e6b. Marking as a blocker for 3.2.1.

Thanks for the report!

**Comment by mgol** [comment]
This only shows we should have explicit tests for any API that we deprecate, even if there weren't any due to legacy reasons.

**Comment by timmywil** [comment]
Oof. How did we not catch this.

By the way, temporary workaround:

```js
jQuery.holdReady = jQuery.fn.holdReady;
```

**Comment by timmywil** [comment]
I think making the necessary adjustments to [this PR](https://github.com/jquery/jquery/pull/3331) and landing it will give us the test coverage we want for this issue.

**Comment by Krinkle** [comment]
It's been failing for several weeks in Jenkins/TestSwarm:
<http://swarm.jquery.org/project/jquerymigrate>
<img width="582" alt="screen shot 2017-03-17 at 12 05 15" src="https://cloud.githubusercontent.com/assets/156867/24058883/fb8b024c-0b09-11e7-96fa-22c76035b9d2.png">
<img width="951" alt="screen shot 2017-03-17 at 12 05 30" src="https://cloud.githubusercontent.com/assets/156867/24058884/fb8bc02e-0b09-11e7-9fa7-a451a0aed209.png">

**Comment by timmywil** [comment]
Well, that's jQuery migrate, not jQuery core, but I'm surprised no one said anything.

**Comment by mgol** [comment]
Perhaps looking at Migrate test results should be added to the release
instructions in our  Wiki. Currently only regular Core & periodic test
results are mentioned.
-- 
Michał Gołębiowski

**Comment by timmywil** [comment]
This seems like a rare case, and it will be fixed when we land the PR I mentioned. I would like to ensure that reviewing core tests is sufficient for releasing core and reviewing migrate tests sufficient for migrate.
