### ISSUE TITLE
easily discoverable changelog?

### ISSUE THREAD

**Issue by ashleygwilliams** [jquery/jquery#3574]
### Description ###

hi! thanks for `jquery`, it's lovely. i would like to request an easier way to find the CHANGELOG from github or npm. When I get a Greenkeeper PR to update my `jquery` i'd like a quick way to know what changed.

when i looked at the README on the npmjs site, the landing page for the jquery docs, and the github repo and wiki, i couldn't find the CHANGELOG.

eventually i just did a google search for "jquery changelog" and i found your release notes on your blog. perhaps you can link to your blog from your README and note that the CHANGELOG is there.

anyways, i'm happy to make a PR but i figured ya'll probably want to decide what the best solution is. that or i have missed the obvious simple way to find your changelog since i am still on my first cup of coffee. either way~ lemme know! and thanks for working on open source <3

<hr/>

edit: i did find this view: https://github.com/jquery/jquery/compare/3.1.1...3.2.0 but it's still a lil inaccessbile IMO

**Comment by timmywil** [comment]
Great idea, @ashleygwilliams! I think a link to the latest changelog in the README makes sense.

**Comment by timmywil** [comment]
The next release will include the blog post link in the jquery-dist repo and in npmjs.org readme.

**Comment by ashleygwilliams** [comment]
yay! thanks :)
