### ISSUE TITLE
trigger() function not pass extraParameters when trigger click event of a radio element (Only jQuery 3.2.0)

### ISSUE THREAD

**Issue by GrayYoung** [jquery/jquery#3579]
```
$(document).on('click', '#tab-type .list-choice :radio', function(event, isSimulated) {
	// Prescription Type
	var pstType = $(this).val(), $colADD = PS.$tabs.eq(3).find('.col-add');

	if(PS.isSingleVision(pstType)) {
		$colADD.find('.form-control').val(PS.data.ADD.defaultValue).valid();
		$colADD.addClass('hidden');
	} else {
		$colADD.removeClass('hidden');
	}
	if(isSimulated !== true) { 
		if(PS.isNonRX(pstType)) {
			PS.$tabs.eq(3).removeClass('active');
		} else {
			// VWC-1075
			PS.$tabs.eq(3).addClass('active').find(':input:visible:first').focus();

			$modal.scrollTop($modal.scrollTop() + PS.$tabs.eq(3).offset().top);
		}
	}
	PS.data.prescriptionType = pstType;
	$btnNext.removeClass('hidden');
});

// In another function
PS.$tabs.eq(2).find(':radio').filter(function() {
	if(this.value === data.prescriptionType) {
		return true;
	}
	if($(this).closest('label').text().trim() === data.prescriptionType) {
		return true;
	}

	return false;
}).trigger('click', [true]);
```

**isSimulated** is undefined, it should be _true_.

**Comment by mgol** [comment]
Could you create a test case without external libraries on https://jsfiddle.net or https://jsbin.com?

**Comment by mgol** [comment]
...actually, this seems like https://bugs.jquery.com/ticket/13353 (also relevant: #1741). I'm closing this one as a duplicate; I assume your issue is not isolated to jQuery 3.2.0 but also happens in older versions.

**Comment by GrayYoung** [comment]
But when I switch the version to 3.1.1, the code work fine.

**Comment by mgol** [comment]
OK, please provide a test case on https://jsfiddle.net or https://jsbin.com then and we'll have a look.

**Comment by GrayYoung** [comment]
https://jsfiddle.net/kzg5o5pa/5/

I finally have done the test case, trigger function with passing extraParameters not work on radio element, but button element. It is so strange.
Tested the case use jQuery 3.2.0 and jQuery 3.1.1, only not work when use jQuery 3.2.0 .

**Comment by mgol** [comment]
I can confirm the behavior. A simplified test case: https://jsfiddle.net/kzg5o5pa/7/.

This is a regression from 3.1.1.

Thank you!

**Comment by mgol** [comment]
The regression was introduced in b442abacbb8464f0165059e8da734e3143d0721f.

**Comment by gibson042** [comment]
> The regression was introduced in b442abacbb8464f0165059e8da734e3143d0721f.

And as such, is actually a "fix" to a _consistently_-broken state.

**Comment by timmywil** [comment]
We're going to back out this change and take closer look at https://github.com/jquery/jquery/pull/1367 for 3.3.
