### ISSUE TITLE
About the width of element in a hidden div

### ISSUE THREAD

**Issue by yevon-cn** [jquery/jquery#3580]
### Description ###
When I use `$("#input1").width()` to get the width of input1, I get `-16px` on chrome(56.0.2924.87 64-bit) & firefox(51.0.1 32-bit), get '0px' on IE11,  I don't know why, is this right ?

```html
<div id="result1"></div>
<div style="display: none;">
  <input type="button" id="input1" value="input1" >
</div>
```

### Link to test case ###
https://jsfiddle.net/30fy38L5/

**Comment by dmethvin** [comment]
The [docs for .width()](http://api.jquery.com/width/) say:

> The value reported by .width() is not guaranteed to be accurate when the element or its parent is hidden. To get an accurate value, ensure the element is visible before using .width(). jQuery will attempt to temporarily show and then re-hide an element in order to measure its dimensions, but this is unreliable and (even when accurate) can significantly impact page performance. This show-and-rehide measurement feature may be removed in a future version of jQuery.
