### ISSUE TITLE
jquery-migrate "effects: jQuery.easing" test failing

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#3583]
jQuery 3.2.0 -> 3.2.1 reduced jQuery Migrate unit test failures from **2** to *1**, but one still remains (albeit with a different failure now).

http://swarm.jquery.org/job/5003
http://swarm.jquery.org/result/2033369

<img width="695" alt="screen shot 2017-03-20 at 12 47 05" src="https://cloud.githubusercontent.com/assets/156867/24118522/58c77a7c-0d6b-11e7-83fd-f1d59d2b66b4.png">

I suspect may be be indirectly caused by `width()`/`height()` no longer having fractions for inline elements per 473d2ea7d5e4ef0a5b8e0305197f483c136ee4ab (#3571).

**Comment by timmywil** [comment]
Thanks for report! I think this failure is expected and can be addressed by migrate.

**Comment by timmywil** [comment]
It's not related to width/height. It has to do with the first value reported to an easing function, which is now something relevant rather than zeros.

**Comment by timmywil** [comment]
The point of those tests in migrate is to ensure easing still works given the different signature, which seems to be fine.

**Comment by timmywil** [comment]
Take that back. It is related to the width/height change, but it is also related to the progress tick change in effects. That said, this failure is still expected and should be handled by migrate.
