### ISSUE TITLE
Ajax request timeout doesn't trigger fail() or always() in Safari

### ISSUE THREAD

**Issue by eriklax** [jquery/jquery#3586]
Ajax request timeout (due to server being offline) doesn't trigger fail() or always() in Safari (macOS) in latest jQuery. In jQuery 1.x timeout errors trigged both fail() and always().

"Failed to load resource: The request timed out."

And then this script stops.

```
function ping()
{
        $.get("?action=ping")
        .fail(function(jqXHR, textStatus, errorThrown) {
                console.log('fail');
        })
        .always(function() {
                console.log('always');
                setTimeout(ping, 1000);
        });
}
ping(); // and reboot the webserver
```
This shows the console in Safari.

![console](https://cloud.githubusercontent.com/assets/275758/24198647/f37a7e9c-0f06-11e7-8a3b-ac5b69e7872f.png)

**Comment by dmethvin** [comment]
The default in all versions of jQuery is no timeout. Where did you set the timeout? I have a feeling that a complete example might show some other cause.

**Comment by dmethvin** [comment]
Oh, but this timeout is coming from Safari? It would definitely be useful to see a running example to understand what is happening. Is it only Safari?

**Comment by eriklax** [comment]
Yes, this timeout is coming from Safari (I guess some sane default xhr request timeout). It works as you would expect in Chrome (as shown in the screenshot) and Firefox.

Trying the same code with jQuery 1.x (in Safari, same browser) the timeout "Failed to load resource" is caught and triggers the callbacks, which makes me think it's jQuery related and jQuery could catch it in 3.x as well.

![chrome](https://cloud.githubusercontent.com/assets/275758/24238343/492cbf0a-0faa-11e7-943e-1aad5f8ae6c7.png)

**Comment by dmethvin** [comment]
We still don't have a complete code example so we can't debug it.

**Comment by eriklax** [comment]
Here is a test case. For me, it takes about 80 seconds minute until the timeout is triggered in Safari.

Doesn't work:

```
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
<script>
function ping()
{
        $.get("http://8.8.8.8") // or any other host causing a timeout
        .fail(function(jqXHR, textStatus, errorThrown) {
                console.log('fail');
        })
        .always(function() {
                console.log('always');
                setTimeout(ping, 1000);
        });
}
$(function() {
 ping();
});
</script>
```

It works with
```
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
...
```

**Comment by eriklax** [comment]
This patch seems to solve this issue.

https://github.com/jquery/jquery/compare/master...eriklax:patch-1

**Comment by dmethvin** [comment]
Interesting! It seems our assumption might have been that the underlying XHR never had a timeout, I wonder if this is specific to Safari?

**Comment by mgol** [comment]
Interesting... That would mean Safari has extracted timeout handling from `xhr.onerror` to `xhr.ontimeout`.

@eriklax Would you like to prepare a PR? I wonder how to test it; we have a [native abort test](https://github.com/jquery/jquery/blob/master/test/unit/ajax.js#L511-L528) but that can be triggered via `xhr.abort()` and timeout won't have such an API available...

**Comment by eriklax** [comment]
@mgol How about settings timeout to 1ms and use the wait url?

**Comment by dmethvin** [comment]
Seems to me that Safari is violating the [XHR spec](https://xhr.spec.whatwg.org/) if they have a default timeout:

> The timeout attribute must return its value. Initially its value must be zero. ... When set to a non-zero value will cause fetching to terminate after the given time has passed. When the time has passed, the request has not yet completed, and the synchronous flag is unset, a timeout event will then be dispatched, or a TimeoutError exception will be thrown otherwise (for the send() method).

**Comment by mgol** [comment]
@eriklax Good idea. We can't test the native timeout happening after a long wait, that would take too long but if we correctly hook up to the `ontimeout` handler this gets resolved automatically.
