### ISSUE TITLE
on method cannot capture img's load event on body, but with addEventListener, it can capture on body.

### ISSUE THREAD

**Issue by Nomia** [jquery/jquery#3592]
### Description ###
I want to listen the load event of any img that's on the page or will be inserted to the page, I expect jquery's `on` method to listen that, like code below:
```
$('body').on('load', 'img', function(e) {
console.log('event occurs');
});
```

the `event occurs` never print on the console.
but when I use the code below, the `event occurs` will print on the console

```
document.body.addEventListener(
    'load',
    function(event){
        var tgt = event.target;
        if( tgt.tagName == 'IMG'){
            console.log('event occurs');
        }
    },
    true
)
```

I test these two block code on the same page, with the same step: insert img, change img url. jQuery's on method cannot capture the `load` event, I don't know why.

some reference, please see the second answer with 29 upvotes:
http://stackoverflow.com/questions/14983988/is-bubbling-available-for-image-load-events

**Comment by Nomia** [comment]
```
document.body.addEventListener(
    'load',
    function(event){
        var tgt = event.target;
        if( tgt.tagName == 'IMG'){
            console.log('event occurs');
        }
    },
    true
)
```

Is idea in `on` method to capture event different with above code

thank u

**Comment by mgol** [comment]
Thanks for the report.

jQuery doesn't support attaching event handlers in the capture phase, only in the bubble phase so you can't write such an event handler with a jQuery API.

We're planning an event subsystem refactor in a major version, maybe 4.0.0 to support passive event listeners (#2871); we might be able to add support for the capture phase then (but we can't promise anything at this point).

I'll close this issue now as there's nothing we can do here short-term but we'll have that in mind when designing the new event subsystem.
