### ISSUE TITLE
jQuery core functions are failing with custom jQuery build without Sizzle engine in some cases

### ISSUE THREAD

**Issue by kolardavid** [jquery/jquery#3593]
### Description ###
In **manipulationTarget()** in jQuery library, there is expression searching for tbody tag inside table using code **jQuery( ">tbody", elem )**. This works fine with full jQuery library, however, when Sizzle selector engine is stripped (in custom builds), this statement fails, because it is jQuery specific selector.

My proposal is to change this statement to **jQuery(elem).children( "tbody" )**.

### Link to test case ###
Test case wouldn't show this bug, because it has to be made with custom jQuery build without Sizzle engine.

**Comment by timmywil** [comment]
Yup! This used to be a native call to `getElementsByTagName`. I've added a note to run tests for custom builds to the release checklist.

**Comment by timmywil** [comment]
Fixed by https://github.com/jquery/jquery/pull/3916
