### ISSUE TITLE
id selector not being parsed for some valid HTML id formats

### ISSUE THREAD

**Issue by stevenganz** [jquery/jquery#3595]
According to the [HTML spec](https://www.w3.org/TR/REC-html40/types.html#type-name):

> ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").

The following are examples for which rquickExpr.exec fails to parse the id selector (the first with an error):
```
$("#x.");
$("#x.z");
$("#x:z");
```

I ran these on chrome.

This seems different from issue #2824.

**Comment by dmethvin** [comment]
These are CSS selectors, you  need to look at the CSS spec. `#a.b` is an element with ID a that has class b. For more information search/ask on StackOverflow.

**Comment by stevenganz** [comment]
Yes, of course.  I hadn't realized that that further limits choice of characters in HTML ids, which are quite restricted already.

**Comment by Krinkle** [comment]
@stevenganz If for some reason these characters are required (or preferable) for other reasons (e.g. more readable url hashes or some such), then they can still be selected by other means. For example, by using an attribute selector (`[id=""]`), by escaping the characters, or by avoiding the selector problem and passing the raw string directly to `document.getElementById`, which has none of these ambiguities.

**Comment by dmethvin** [comment]
Pretty much https://www.google.com/search?q=jquery+special+characters+in+id

**Comment by stevenganz** [comment]
Thanks, guys.  In this case, I wanted something I could use as a delimiter between segments that might include some of the other characters.
