### ISSUE TITLE
Deferred: filtering reject value does not work

### ISSUE THREAD

**Issue by drscre** [jquery/jquery#3599]
Reject value filtering example from https://api.jquery.com/deferred.then/ does not work:

https://jsfiddle.net/oyn7ttco/

The promise resolves successfully, while it should not:

https://jsfiddle.net/2d2ckeLw/

**Comment by mgol** [comment]
Thanks for the report!

This is an intended breaking change in jQuery 3.0 to make Deferreds compatible with the Promises/A+ spec, more about that in the upgrade guide: https://jquery.com/upgrade-guide/3.0/#breaking-change-and-feature-jquery-deferred-is-now-promises-a-compatible

You've found a bug in the API docs then; they should indicate the behavior changed in 3.0. Could you open an issue at https://github.com/jquery/api.jquery.com/issues/? This repo is for the jQuery library, not for the API documentatation page.

Thanks!
