### ISSUE TITLE
Regression: Inline width returns 0 on Android 4

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#3602]
### Description ###

Unit test `dimension: width/height on an inline element with no explicitly-set dimensions (gh-3571)` has been broken on all Android 4.x versions since it was added in c4598da429 (gh-3571).

### Test case ###

Before:
* <http://swarm.jquery.org/job/4974>
* Commit f8faf1489e (jQuery Periodic; 18 March 2017)

<img width="974" alt="screen shot 2017-04-01 at 12 41 21" src="https://cloud.githubusercontent.com/assets/156867/24581871/87d8d72c-16d8-11e7-992b-5b475639d7ab.png">

After:
* <http://swarm.jquery.org/job/5006>
* Commit c1c549793a (jQuery Periodic; 21 March 2017).

<img width="965" alt="screen shot 2017-04-01 at 12 39 42" src="https://cloud.githubusercontent.com/assets/156867/24581862/507d29cc-16d8-11e7-9041-a30179f9db74.png">

### [Commits f8faf1489e...c1c549793a](https://github.com/jquery/jquery/commits/c1c549793a) 
* c1c549793a Tests: Fix incorrect assert name (@Krinkle)
* 473d2ea7d5: Dimensions: fall back to offsetWidth/Height for inline elems gh-3571 gh-3577 (@timmywil)
* c4598da429 CSS: retrieve inline style before computed (@timmywil)

**Comment by timmywil** [comment]
You're right about the failure. I'm not sure how the commit you linked is related, unless Android 4 has the opposite issue of Firefox making it so you can't access inline style before computed for some odd reason.

**Comment by mgol** [comment]
We should fix that before the next release, tagging with 3.3.0.

**Comment by Krinkle** [comment]
>  I'm not sure how the commit you linked is related

Aye, yeah, filtered a bit too much between in the affected commit range. c4598da (CSS) was in the range but probably unrelated indeed. 473d2ea (Dimensions) is more likely. I added it to the list now.

**Comment by Krinkle** [comment]
Confirmed. This fixed the Dimensions tests for Android 4.

The only exception is Android 4.0, which is consistently failing (timing out) on all jQuery test suites (including Dimensions, but likely unrelated). Most likely something in the setup code of either jQuery or the testrunner is throwing it off.

<http://swarm.jquery.org/job/5883>

I'll file a separate issue for that.
