### ISSUE TITLE
Browser's process memory continues to increase when creating a large number of DOM elements

### ISSUE THREAD

**Issue by pmgmendes** [jquery/jquery#3603]
### Description ###
_What do you expect to happen?_
append() method usage should allow the browser to successfully garbage collect any of the child elements created. 

_What actually happens?_
Chrome's tab process memory is not being freed. The memory continues going up until the tab crashes.

_Which browsers are affected?_
Chrome current stable 57.0.2987.133, current beta 58.0.3029.41-1 and current unstable 59.0.3053.3-1

There's is also a reported Chromium bug.
[Process memory continues to increase when recycling a large number of DOM elements](https://bugs.chromium.org/p/chromium/issues/detail?id=707544)

### Link to test case ###
https://jsfiddle.net/pmendes/wLu6kj1b/

**Comment by mickmcgrath13** [comment]
FWIW:

Here is a very small non-jQuery example that leaks like crazy in Chrome 57 but is stable in 56:
http://jsbin.com/bihuca/1/edit?html,js,output

The key is the line `elem.getElementsByTagName('script' || '*');`. Removing that gets rid of the leak.

The jQuery path through this is:

append:5924
domManip:5732
buildFragment:4834
getAll:4732

**Comment by mickmcgrath13** [comment]
Looks like this is getting fixed on the Chrome side: https://bugs.chromium.org/p/chromium/issues/detail?id=707544#c35

**Comment by pmgmendes** [comment]
Being a specific Chrome issue and being solved there I guess it makes sense to close this issue, right?

**Comment by timmywil** [comment]
@pmgmendes Agreed. I don't see a workaround on our end anyway.
