### ISSUE TITLE
Deprecate jQuery.type

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#3605]
### Description ###
`jQuery.type` is insufficient to deal with the ever-increasing list of @@toStringTag values (cf. gh-3553, gh-3600). But since it is intended for internal use anyway, so we should treat it just like [`jQuery.isNumeric`](https://github.com/jquery/jquery/issues/2960), [`jQuery.proxy`](https://github.com/jquery/jquery/issues/2958), [`jQuery.now`](https://github.com/jquery/jquery/issues/2959), and [`jQuery.camelCase`](https://github.com/jquery/jquery/issues/3384) by removing it from the public API.

**Comment by ShashankaNataraj** [comment]
PRs accepted? I'd like to contribute to this!

**Comment by timmywil** [comment]
@ShashankaNataraj absolutely!
