### ISSUE TITLE
a memory problem  about deferred in 3.x

### ISSUE THREAD

**Issue by houfeng0923** [jquery/jquery#3606]
### Description ###

When our project upgraded to jQuery3.2.1 (from 2.2.4),  we found a memory leak about `Deferred` in jQuery3.x .  the  `promise.then` method  does not release the handler & handler Closure . 
it work well in jQuery2.x and native Promise in chrome .

look at the following case：

### Link to test case ###

http://plnkr.co/edit/DpMkLV2mqzwlX4Ruuk7i

![image](https://cloud.githubusercontent.com/assets/1825420/24588814/72b9b1d8-1802-11e7-866a-a498236ef5e5.png)

![image](https://cloud.githubusercontent.com/assets/1825420/24588850/fcc4fbc6-1802-11e7-955c-5bb8dd71b33b.png)

**Comment by jbedard** [comment]
Here's a version with non-minified jQuery: https://plnkr.co/edit/SE4DMFg8g3SGqDdhxCXx

![big-deferred](https://cloud.githubusercontent.com/assets/89246/25690801/f5a56858-3049-11e7-8070-8f8cafdfe4d4.png)

**Comment by guylando** [comment]
After upgrading to 3.3.1 the memory leak still happens and even worse, changing : https://github.com/GulajavaMinistudio/jquery/commit/a4beceb936a896049e8a3dd6b7de55fc7f7a36be
does not help anymore.
Previously using 3.2.1 together with that change prevented the memory leak but not anymore.
