### ISSUE TITLE
$("form").postAsJSON()

### ISSUE THREAD

**Issue by dbol55** [jquery/jquery#3608]
Request for a method that posts a html form, as PROPER JSON, that handles types etc correct.
Or atleast serializeJSON.

As far as I belive I could not find this functionallity build into jQuery.

And no we dont want this as a plugin, it is far to prioritezed area and besides that there are to many attempts out there...

**Comment by dmethvin** [comment]
What is wrong with the plugins you've found?

**Comment by googabeast** [comment]
What do you mean you don't want this as a plugin? JQuery is nothing more then sets of plugins that have been combined and chained together to form a function library. Extending the library with a plugin is the correct way to do it.

Take a look at the below and maybe you can customize that to meet your needs.
https://github.com/macek/jquery-serialize-object

**Comment by timmywil** [comment]
Thanks for opening an issue, but we still think this is best done with plugins. Personally, I don't use a plugin. I construct the JSON object I want from the form and post by setting `contentType`, but I like more control over how the object is constructed. There are different ways it could be done and none may suit your preferences.

**Comment by dbol55** [comment]
> What is wrong with the plugins you've found?

The first problem is that there is too much information out there. Just image if you had 200+ versions of your ajax function... If you know any decent plugin please inform me.

> 
> Take a look at the below and maybe you can customize that to meet your needs.
> https://github.com/macek/jquery-serialize-object

This plugin does not even parse numbers....?

As said, it is too much attempts out there and I belive jQuery should set the standard including proper JSON folloewd by html post form method.

> Manually

Shure no problem, I can even use plain old JavaScript for the whole process. However I dont think the majority would like to parse html forms days in and out. I mean image all people would like to manually hand craft a normal form...? I mean it would be just as normal form post, but it will be translated to modern JSON, nothing more or nothing less.

However I hope you consider this in the long term... I think it will boost jQuery a lot.

Thank you!
