### ISSUE TITLE
Deprecate jQuery.isFunction

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#3609]
### Description ###
Everything must go! https://github.com/jquery/jquery/issues/3600#issuecomment-290998590
* jQuery.camelCase: gh-3384
* jQuery.isNumeric: gh-2960
* jQuery.now: gh-2959
* jQuery.proxy: gh-2958
* jQuery.type: gh-3605

**Comment by akihikodaki** [comment]
How could the internal implementation of jQuery (`jQuery.Deferred`, which I'm concerning, for example) be after deprecating `jQuery.isFunction`?

**Comment by mgol** [comment]
@akihikodaki We can move it to an internal AMD module and still use it but it would no longer be a public API after the deprecation period ends.

**Comment by akihikodaki** [comment]
@mgol That does not solve #3596. `jQuery.Deferred` could not recognize some functions because of `jQuery.isFunction`. I think @gibson042 is intended to solve also the problem by this deprecation.

**Comment by gibson042** [comment]
I expected #3601 to fix the issue underlying your Deferred problem, it just needs an adjustment. This is a separate issue, intended to put jQuery.isFunction on the path towards becoming a purely internal API.

**Comment by akihikodaki** [comment]
> This is a separate issue, intended to put jQuery.isFunction on the path towards becoming a purely internal API.

Opened #3601 for the problem causing the Deferred flaw.
