### ISSUE TITLE
Internal API succeeding to jQuery.isFunction

### ISSUE THREAD

**Issue by akihikodaki** [jquery/jquery#3610]
### Description ###
`jQuery.isFunction` is being deprecated as a public API in #3609. We should consider an internal API succeeding to `jQuery.isFunction` because it is also used in the internal.

Simply moving `jQuery.isFunction` to an internal AMD module doesn't make sense because the current behavior is considered undesirable in #3596. Some change has been proposed to fix;

* Use `instanceof` and complement with `typeof`

Proposed at #3601 by me. @gibson042 pointed out some problems:
> `instanceof` goes too far; it would falsely reject functions from other realms (e.g., iframes) and probably also some host-object functions

* Use `typeof` and complement with `nodeType` test to exclude DOM elements

Proposed at https://github.com/jquery/jquery/pull/3601#discussion_r109311504 by @gibson042. I'm not sure making such an exception in this generic function is appropriate. Expectations of other exceptions could emerge in the future, and this solution may not be long-term.

**Comment by akihikodaki** [comment]
In my opinion, removing `isFunction` is fine because of the preference for `typeof` operator. Testing whether it is a DOM element should be done in individual functions rather than in the generic `isFunction`.

**Comment by akihikodaki** [comment]
I had a quick look at `jQuery.isFunction` usage in the internal.

In most cases, putting elements in variables tested with `jQuery.isFunction` results in an error or they will be silently ignored.

However, the other variables could be elements. `domManip` (used in `jQuery.fn.append`, `jQuery.fn.prepend`, `jQuery.fn.before`, and `jQuery.fn.after`), `jQuery.fn.wrapAll`, `jQuery.fn.wrapInner`, `jQuery.fn.wrap` have behaviors specific to elements and users would expect elements will be treated accordingly even if they are functions. They require additional checks if they are elements.
The usage in `winnow` (used in `jQuery.fn.filter`, `jQuery.fn.not`, and `jQuery.fn.is`) is similar to those cases, but it doesn't need additional checks because it have already tested whether the variable is an element.

`jQuery.data` is different from the above patterns. It passes the given value to `access` function and `access` function tests the value is a function. If it is a function, it would be called and the returned value would be stored. The difference from the other functions using `access` function is that the type of the value is not limited; `jQuery.data` takes [anything](http://api.jquery.com/Types/#Anything). [The behavior that the `jQuery.data` tests the given value with `jQuery.isFunction` is not documented](http://api.jquery.com/data/).

Considering that, I do not think `jQuery.isFunction` is necessary even for the internal use. I also think `jQuery.data` needs to be modified to remove the feature to call the given function because:
* we may know DOM elements (and possibly other functions) should not be treated as values rather than functions, but we do not know other cases dependent on other libraries, etc. Moreover, such objects may appear in the future and need updates.
* If you want to store functions, you need to wrap it with another function returning the value. That is troublesome.

**Comment by gibson042** [comment]
It may be troublesome, but it is the nature of our polymorphic library. Objects with nonnegative numeric `length` get the same special treatment as arrays where applicable, and objects with `nodeType` are treated as DOM nodes which under **no** circumstances should be invoked as functions. Remember too that we're cross-browser, and imagine the chaos of trying to debug [`$el.append( document.createElement("object") )`](https://jsfiddle.net/5jo5jfd1/).

**Comment by akihikodaki** [comment]
Is that so important that requires additional checks even if such a situation is not realistic? Another example is `PlainObject`. Some variables documented as `PlainObject` do not enforce they are really "plain", but I think that is completely fine if those variables could not be other types in usual use cases.
I agree the case of `jQuery.fn.append` is problematic without `nodeType` checks. The type checks should be strictly enforced if the same variable could be functions and other non-primitive types and the semantics could differ in the two cases.

My opinion in summary:
* If that really matters, do test whether it is other non-primitive types such as DOM node.
* If that doesn't really matter, do not test.

**Comment by timmywil** [comment]
We'd be happy to look at a PR, but until we actually see the effects of changes to `isFunction` in our tests, we're unlikely to decide to make those changes. Frankly, I don't want to spend too much time on this. My general philosophy in utility functions like this is that we obviously can't guard against everything, but we can guard against some of the most common cases. If there's a case that just isn't that common anymore (or never was that common), we can remove it and simplify, but the best way to convince is with code. Given that, I'm inclined to close this issue and reopen if a PR comes along.

It's probably worth noting that, many times, utility function simplifications like this get into the codebase when we're fixing a larger issue that uses that function.
