### ISSUE TITLE
getting sometimes non zero values for width and height for hidden elements issues

### ISSUE THREAD

**Issue by omuleanu** [jquery/jquery#3614]
I noticed that jquery now gives height and width for hidden elements, sometimes.
So before, for hidden elements I was expecting to get zero for height and width,

now if the element has `display:hidden` (instead of a parent having `display:hidden`) you'll get the 'correct' value, however if a parent is hidden you'll get zero

so now I have to write stuff like this:
 `x.height() + (y.is(':visible') ? y.height() : 0 ) + ... `

this is because jquery changes the display to block in the process and than reverts it, this is also causing issues for android chrome 
https://bugs.chromium.org/p/chromium/issues/detail?id=707888

**Comment by dmethvin** [comment]
You said "now", did behavior change recently?

**Comment by omuleanu** [comment]
@dmethvin using jquery-1.12.4 I noticed this, but I don't know the version when this was introduced

**Comment by timmywil** [comment]
The behavior looks right to me.
