### ISSUE TITLE
get data(key) for data-* JSON ignores dynamic content?

### ISSUE THREAD

**Issue by EricBalingit** [jquery/jquery#3615]
When dynamically changing a data-* attribute with a JSON string, new calls to .data(name) do not fetch the updated data-* object.

Please pardon my ignorance, but is this the expected behavior?

Here is an example:

``` js
var test = $ ( '#test' );

test.attr ( 'data-test', JSON.stringify ( { to: 'test1' } ) );
test.data ( 'test' );
test.attr ( 'data-test', JSON.stringify ( { to: 'test2' } ) );

alert ( test.data ( 'test' ).to ); // test1
```

and a [fiddle](https://jsfiddle.net/52hnshtc/)

**Comment by mgol** [comment]
From https://api.jquery.com/data/#data-html5:
> The data- attributes are pulled in the first time the data property is accessed and then are no longer accessed or mutated (all data values are then stored internally in jQuery).
