### ISSUE TITLE
Chrome 57 making .data() not work well

### ISSUE THREAD

**Issue by vascofernandes** [jquery/jquery#3616]
Problem is as reported here:

http://stackoverflow.com/questions/43129799/chrome-57-making-data-not-function-well

Using $('some_selector').data('key', value) to store the data and later retrieve it with $('some_selector').data('key'), **might** return undefined.

**Comment by timmywil** [comment]
We attach data directly to elements. If the data is somehow getting garbage collected, I don't think there's anything we can do in jQuery.

**Comment by omuleanu** [comment]
@timmywil is there any difference in `.data()` between jQuery `1.12.4` and `2.2.4` ?
because I'm getting this problem with `2.2.4` but not in `1.12.4`

**Comment by omuleanu** [comment]
@vascofernandes which jQuery version were you using when you got this problem ?

**Comment by vascofernandes** [comment]
@omuleanu it is 3.1.1.

Regards

**Comment by omuleanu** [comment]
@vascofernandes can you try `1.12.4`

**Comment by timmywil** [comment]
@omuleanu I think the main difference between `1.12.4` and `2.2.4` is that we started attaching data directly to elements. In `1.12.4`, we attached a key to the element and stored the data in memory in an internal object. If the string is not also getting garbage collected, why does a string stick around and not an object?

**Comment by timmywil** [comment]
It just sounds like Chrome's garbage collector is being a little too aggressive in some cases.

**Comment by omuleanu** [comment]
@timmywil that would be a question for the chrome devs, 
I noticed that when the system memory is at about 50% (or more) objects that have been attached using `.data` and don't have any other references, get removed
