### ISSUE TITLE
Row selection of List  not working properly after upgrade from 1.8.3 to 1.12.3 version  

### ISSUE THREAD

**Issue by ankitacroit09** [jquery/jquery#3618]
What actually happens? 
 - After upgrading  jquery 1.8.3.min to 1.12.3.min version ,the Row selection of List is not working 
    properly.
In list 'ul' ,the selection of item is happening for the first time and after next time it is not able to select the same item again.
please have a look this issue.

   What do you expect to happen?
   -I want to select the same row again and it should be behave acc. to how we select the new row in list.

   Which browsers are affected?
   -All

**Comment by ankitacroit09** [comment]
Please help us as soon as possible.

**Comment by dmethvin** [comment]
Please ask for help on StackOverflow. It sounds like you should use jQuery Migrate to look for upgrade issues, and read the jQuery 1.9 upgrade guide.  https://jquery.com/upgrade-guide/1.9/

**Comment by ankitacroit09** [comment]
I am not able to find the upgrade guide for each version only 3.X and 1.9 guide avaliable
