### ISSUE TITLE
Support ES6's arrow function?

### ISSUE THREAD

**Issue by AtalisasOwen** [jquery/jquery#3620]
### Description ###
For example,can I transform test1() to test2()?
function test1() {
            $("img").mouseenter(function(e) {
                $(this).css("opacity", 0.5);
            }).mouseout(function(e) {
                $(this).css("opacity", 1.0);
            });
        }

function test2() {
            $("img:odd").mouseenter(e => {
                $(this).css("opacity", 0.5);
            }).mouseout(e => {
                $(this).css("opacity", 1.0);
            });
        }

**Comment by mgol** [comment]
Arrow functions don't have their own `this` binding so it's technically impossible to use the `this` binding jQuery provides with an arrow function.

**Comment by scottgonzalez** [comment]
You can use `event.target` (or based on the code above, `e.target`), instead of `this` though.
