### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by bartoszkp** [jquery/jquery#3623]
### Description ###

There seems to be no clear explanation on what is the licensing model wrt. to commercial applications. The [LICENSE.txt](https://github.com/jquery/jquery/blob/master/LICENSE.txt) file in this repository is clear about it, however it is different from the license presented [here](https://js.foundation/pdf/ip-policy.pdf), where both the http://jquery.org/license/ URL and the "License" link from the [NuGet package page](https://www.nuget.org/packages/jQuery/) redirect.

Do I understand correctly, that the LICENSE.txt file in this repository is the "alternative license" mentioned in the first paragraph of https://js.foundation/pdf/ip-policy.pdf ? 

Even if yes, I cannot be sure that this file is the same that applies to the distribution from NuGet. The distribution from NuGet, namely the main source file header (jquery-3.1.1.js) points back to http://jquery.org/license, which redirects to https://js.foundation/pdf/ip-policy.pdf so there seems to be no "license file for the applicable Project" in this case (i.e. the NuGet distribution case). The confusion stems from the fact that the relation between the NuGet distribution and this repository is only by name - so perhaps it would be better if the NuGet "License" link pointed to the LICENSE.txt file here (same in the case of the source file header)?

Also, the mentioned header (jquery-3.1.1.js) states that it is released under the MIT License. However it seems that the LICENSE.txt is not a MIT License, strictly speaking. 

Perhaps I'm overcomplicating things, but I'm not a lawyer (as, I presume, most of developers) - could you please make the usage conditions more clear? The explanations related to licensing in the context of contributing to jQuery are very clear, but the 3rd-party usage licensing explanations seem to be lacking in this context.

**Comment by mgol** [comment]
@kborchers @scottgonzalez @dmethvin Could one of you comment on that?

**Comment by scottgonzalez** [comment]
I'd love to, but I'll let the paid legal counsel give an answer.

**Comment by StevenAyr** [comment]
@bartoszkp Many thanks for the feedback here. It would appear that in the transition from the jQuery Foundation to the JS Foundation and from one primary foundation website to the other, there were some unintended consequences with link re-directs that need to be cleaned up. The IP Policy that is now linked to is the Foundation's overall IP policy, which as you point out, isn't particularly helpful when determining how any particular project is licensed.

In any event, jQuery 3.1.1 is licensed under MIT as described in the LICENSE.txt file. To the extent there are additions to the standard MIT language in that license file, they're just to make clear that external libraries, as always, are subject to their own licenses. The MIT license allows for both commercial and non-commercial use on the same terms, all that is required is attribution and reproduction of the permission notice from the license in any distributions.

Thank you again for the feedback, happy to answer any other questions you may have on this.

**Comment by bartoszkp** [comment]
@StevenAyr  Thank you very much for your explanation. Should I create a more focused issue to ask for fixing the link at the project's NuGet page (and/or the redirect from http://jquery.org/license)? Or perhaps there is a better place to report this mild inconsistency?

Also, thank you all for your prompt reaction.

**Comment by timmywil** [comment]
@StevenAyr when you say redirects need to be cleaned up, what do we need to do, specifically? Should http://jquery.org/license be restored to linking to MIT?

**Comment by kborchers** [comment]
The problem was http://jquery.org/license didn't link to just the MIT license, it linked to a page with more info, for good reason, because it explained some of the policies around the different licenses used in different situations.

My recommendation would be for projects currently linking to jquery.org/license in their license headers should change those links to either the LICENSE file in the project repo or the CLA page for that particular project's org. The CLA system requires org/repo in the link so it's probably best to use the "main" repo for a project if it has multiple. So for jQuery that would look like https://cla.js.foundation/jquery/jquery

**Comment by timmywil** [comment]
@kborchers btw, I just noticed a markdown link in that page that wasn't translated to HTML. Still, I think it makes sense to link to the LICENSE file in the repo from jquery.js, but would like legal to confirm.

**Comment by kborchers** [comment]
Thanks @timmywil that issue was pointed out over the weekend and is being tracked in an issue on the js.foundation repo.

@StevenAyr can you confirm a link to the LICENSE file in the jQuery distribution file header is adequate to replace the links to the old jquery.org/license page?

**Comment by arschmitz** [comment]
One problem with just re linking to the repo is it fixes new releases but every version of every one of the libraries that have used this link will still have the link which improperly redirects. Seems like new versions should change their link but that we still should have content at http://jquery.org/license indicating MIT

**Comment by kborchers** [comment]
@arschmitz that is a good point. If someone could update the content on https://github.com/jquery/jquery.org/blob/master/pages/license.md to be more specific to the projects that link to that page rather than a foundation-wide statement, I would be happy to review the changes and then we could then just remove the redirect so those old releases have an accurate link.

**Comment by timmywil** [comment]
@kborchers probably need you to make that PR.

**Comment by kborchers** [comment]
@timmywil Let me know if https://github.com/jquery/jquery.org/pull/131 works for you and then I'll merge and remove the redirect

**Comment by timmywil** [comment]
@kborchers I like it! Thanks for doing that.

**Comment by bartoszkp** [comment]
@kborchers  Does this fix concern also the jquery.org/license link (I'm guessing not, from its contents and because this link still points to ip-policy.pdf)? Or this is what you meant by saying you'll remove the redirect? (Sorry if this is a stupid question)

**Comment by kborchers** [comment]
@bartoszkp definitely not a stupid question. This does fix that concern as soon as we fix the redirect which will happen this week.

**Comment by bartoszkp** [comment]
Works great, thanks again!
