### ISSUE TITLE
Sizzle: remove test meant for non-supported browsers (IE < 8, Opera < 9.50a1)

### ISSUE THREAD

**Issue by faliure** [jquery/jquery#3624]
### Description ###
Sizzle attempts to match the simplest cases before attempting more complex matching. For ids it uses getElementById, and then tests that the matched element actually has the given id, to avoid cases where getElementById matches by name instead. This behaviour was fixed in IE8 and Opera 9.50a1, the browsers that used to present the issue (both by design).

References:
  IE<8: https://msdn.microsoft.com/en-us/library/ms536437(v=vs.85).aspx
  IE8+: https://msdn.microsoft.com/en-us/library/cc288667(v=vs.85).aspx
  Opera: https://www.quirksmode.org/bugreports/archives/2005/09/documentgetElementById_may_return_element_with_a_n.html#c8231 (see Opera dev Gérard Talbot's comment)

(I'm sending a merge request in a few minutes with the change)

**Comment by mgol** [comment]
See https://github.com/jquery/jquery/pull/3625#issuecomment-294438223.
