### ISSUE TITLE
AJAX calls my error handler with no error message, 0 status code, no feedback...

### ISSUE THREAD

**Issue by AlexisWilke** [jquery/jquery#3627]
I am using jQuery 1.12.4 and compared the AJAX code to the latest, 3.2.1, and it is pretty much the same thing so I would imagine the problem still exists in the latest version.

I am using SeaMonkey and Firefox, but my customers may be using Firefox, IE, Chrome, you name it... I also tested the same problems on IE and Android ("Internet" [a Safari clone], Chrome, Firefox) and no luck on my end. Once in a while, though, the customers get an AJAX error, which comes out as `"no error"` (at least, no error messages whatsoever, `status` is `0` and the `statusText` is `""`.) So far, I have not been able to reproduce it.

I am wondering whether the following snippet (from 1.12.4) could be the culprit. As we can see, the transport object will actually send the request. If that fails and the low level JavaScript implementation of XHR throws, could it be throwing an [`Error()` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)?

    try {
      state = 1;
      transport.send( requestHeaders, done );
    } catch ( e ) {
      if ( state < 2 ) {
        // Propagate exception as error if not done
        done( -1, e );
      } else {
        // Simply rethrow otherwise
        throw e;
      }
    }

As we can see, you call `done( -1, e );` and _if_ `e` is an `Error()` object, it may be better to use:

    done( -1, e.message );

We also have access to a `fileName` and `lineNumber` or the `toString()` function, which may format the message according to the browser in use including even more information.

    done( -1, e.toString() );

The `done()` second parameter is expected to be a string and not an `Error()` object.

Note that since I cannot currently reproduce the problem on my own systems, I do not know whether this is required or not. Often, an object `toString()` function is automatically called when you do something such as `e + ""` (which happens in the `done()` function.)

One of the affected browsers is Chrome on iPhone, although I'm not totally sure that the browser is the culprit in itself. That is, in most cases things, including AJAX requests, just work.

I will be providing a modified version to my clients using `e.message` and see what happens, but maybe you know better how/what would be happening in that situation?

**Comment by AlexisWilke** [comment]
Okay so I added my own `throw Error("some message");` to verify my theory. Using just `e` works as expected on SeaMonkey, Firefox, Chrome, "Internet" (the default Webkit based browser on Android), IE 10, and that on Linux, Android, and MS-Windows. In all cases, I would get the error as expected. In other words, the `toString()` function gets called automatically. So that is not the problem in itself. I still have that one case that I still cannot reproduce where my customers once in a while get an error without any kind of text feedback.

**Comment by dmethvin** [comment]
Once you can reproduce and demonstrate that it's jQuery you can open a ticket with a more specific description. Keep in mind that browser plugins can cause all sorts of problems.
