### ISSUE TITLE
bad date + .val() returns empty string after type attribute change from datetime-local to text with .get(0) in Edge

### ISSUE THREAD

**Issue by Vlczech** [jquery/jquery#3633]
### Description ###
Bad date and time (current instead of value from value attribute) is shown and .val() returns empty string after type attribute change from datetime-local to text with .get(0) in Edge. 

Firefox, Opera, MS IE is OK, but Edge not, but only with type datetime-local. If there is type="date" only, everything in Edge is OK also. If I change .get(0) to first(), everything in Edge is OK also.

HTML:
`<input name="fromGet" class="form-control datetime-local" type="datetime-local" placeholder="21. 4. 2017 9:31" value="2017-02-20T16:30:00">`

jQuery failing code:
```
$(function() {
  var $inpFrom = $('input[name="fromGet"]');
  console.log($inpFrom.val());   // this gets "2017-02-20T16:30:00"
  $inpFrom.get(0).type = 'text';   // this is a problem - see next row + bad (current) date and time is shown in appropriate input (if is changed to first(), everything is OK)
  console.log($inpFrom.val());   // this gets empty string
  console.log($inpFrom.attr('value'));   // this gets "2017-02-20T16:30:00"
});
```

### Affected versions ###
jQuery version: 3.2.1
Edge version: Microsoft Edge 38.14393.0.0 / Microsoft EdgeHTML 14.14393

### Link to test case ###
https://jsfiddle.net/qdqc12bj/

### Screens from test case ###
* for example from Opera:
![image](https://cloud.githubusercontent.com/assets/10884140/25272054/a64e5264-2686-11e7-8e58-de27e234ab1b.png)

* and the same code from Edge:
![image](https://cloud.githubusercontent.com/assets/10884140/25272124/fde90aa0-2686-11e7-88b4-68e01aa3518c.png)

**Comment by gibson042** [comment]
This is [native browser behavior](https://jsfiddle.net/qdqc12bj/1/), and not surprising given the historical problems that Internet Explorer had with [changing input types](http://api.jquery.com/prop/#prop-propertyName):
> Attempting to change the `type` property (or attribute) of an `input` element created via HTML or already in an HTML document will result in an error being thrown by Internet Explorer 6, 7, or 8.

**Comment by Vlczech** [comment]
@gibson042: As you can see, everything is OK in IE 11.953.14393.0:
![obrazek](https://cloud.githubusercontent.com/assets/10884140/25314021/9ff23e9c-283b-11e7-8418-13dba3f2b843.png)

Some workaround is remember value before change type and then apply value again. Is it possible to include this to jquery?

**Comment by gibson042** [comment]
It isn't possible for us to detect when other code changes the `type` property, and we're not going to add special-case code in `.attr` or `.prop` because that's precisely the kind of thing that proves problematic in the long run. Changing the `type` of input elements has never behaved reliably.
