### ISSUE TITLE
Basic authentication don´t work

### ISSUE THREAD

**Issue by macsarena** [jquery/jquery#3634]
Hello together,

I already created an issue regarding this topic for some days. 
The member mgol gave me the advice, that the error occurs because of CORS.
After reading all about CORS and spending much more time in this issue, it´s still not solved :-(

I am trying to consume a json service, which is running on my IIS Server 7.
Everything works until I activate the baisc authentication in IIS.
I am new in the web development, so please explain it me for noobs :-)

This is my request:

		var xhr = new XMLHttpRequest();
		xhr.open('GET', url, true);
		xhr.withCredentials = true;
		xhr.onreadystatechange = handler;
		xhr.setRequestHeader("Authorization", "Basic " + btoa(username + ":" + password));
		xhr.send();

![response](https://cloud.githubusercontent.com/assets/26833512/25276392/4efb78d4-269a-11e7-9086-bf76998ef99c.jpg)

This is the error message:
![error](https://cloud.githubusercontent.com/assets/26833512/25276411/6828e1ac-269a-11e7-8fb8-663a0bca687c.jpg)

If I would exclude the line "xhr.setRequestHeader("......)", a prompt appears and after entering user and password everything works.

**Comment by dmethvin** [comment]
This is the bug tracker for jQuery, and you're not reporting a bug. Since you're new to web development I strongly suggest you get to know StackOverflow.com where you can ask questions and get programming help.
