### ISSUE TITLE
Upgraded to jquery-2.2.4, when set defaultdebugmode to false in combres eval function not working properly 

### ISSUE THREAD

**Issue by ashlogica** [jquery/jquery#3636]
Using combres for bundling/minification of js and css files. When set defaultdebugenabled=false in combres then jquery eval() function not working as expected.

Case1- when  defaultdebugenabled=true
 then - eval(expressionHolder + ".SetText(self.GetJson());");  is working fine.

Case2-when  defaultdebugenabled=false
then - eval(expressionHolder + ".SetText(self.GetJson());");  is not working and code breaks as SetText is undeined.
the same expression when breaks eval- 
        var control = eval(expressionHolder);
        control.SetText(self.GetJson());    is working fine.

**Comment by mgol** [comment]
I don't see any jQuery in your code samples. `eval` is not a jQuery function but a regular JavaScript one.
