### ISSUE TITLE
[Regression] Task "promises_aplus_tests:when" failing

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#3640]
Jenkins is consistently failing task `promises_aplus_tests:when`.

* <http://jenkins.jquery.com/job/jQuery%20Core/1703/console>
* <http://jenkins.jquery.com/job/jQuery%20Core/1702/console>

```
17:33:19 + export COMMIT=a16339b8933f115da3661f3d3f64854c3fa60bdc
17:33:19 + node --version
17:33:19 v4.4.5
17:33:19 + npm --version
17:33:19 2.15.5
17:33:19 + npm install
...
17:36:11   871 passing (17s)
17:36:11   1 failing
17:36:11 
17:36:11   1) 2.2.6: `then` may be called multiple times on the same promise. 2.2.6.2: If/when `promise` is rejected, all respective `onRejected` callbacks must execute in the order of their originating calls to `then`. `onRejected` handlers are called in the original order even when one handler is added inside another handler already-rejected:
17:36:11      Uncaught AssertError: expected handler1, handler2, handler3 to be called in order but were called as handler1, handler2
17:36:11       at Object.fail (node_modules/sinon/lib/sinon/assert.js:90:29)
17:36:11       at failAssertion (node_modules/sinon/lib/sinon/assert.js:51:24)
17:36:11       at Object.assertCallOrder [as callOrder] (node_modules/sinon/lib/sinon/assert.js:118:21)
17:36:11       at null._onTimeout (node_modules/promises-aplus-tests/lib/tests/2.2.6.js:249:42)
```

The same test is passing fine in Travis CI (also Node v4).

It last passed with 1d2df772b4d. Suspected commit(s):
* a16339b8933f115da3661f3d3f64854c3fa60bdc Core: Update isFunction to handle unusual-`@@toStringTag` input (@gibson042)

**Comment by gibson042** [comment]
I can't reproduce locally, even with node v4.4.5 and npm 2.15.5. :\ Does anyone else want to try?

**Comment by Krinkle** [comment]
Yep, me neither. Tried the following on Travis:
<https://github.com/Krinkle/jquery/blob/e9f173139312fc26db804a55c2165c28dda543b7/.travis.yml>
<https://travis-ci.org/Krinkle/jquery/builds/225414496>

And also passed.

I triggered the job for a third time on Jenkins after upgrading some internal Jenkins plugins and it seems to pass now.
<http://jenkins.jquery.com/job/jQuery%20Core/1704/console>

Never mind for now, I guess :man_shrugging:
