### ISSUE TITLE
Jquery serialize bug 

### ISSUE THREAD

**Issue by otaviobarreto** [jquery/jquery#3644]
### Finally I solved the problem, I had 3 forms with ids: #form1, form2, #form3 but I was sending via jquery 2 forms only

```
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <button class="btn btn-primary" id="sendforms">submit</button>
             <div id="result"> </div>
            <script type="text/javascript">
            $(document).ready(function () {
              $("#sendforms").click(function() {
                       var combinedFormData = $("#form1,#form3").serialize();
                     $.post(
                            "ok.php",
                            combinedFormData
                     ).done(function(data) {
                            //alert("Successfully submitted!");
                            $("#result").html(data);
                     }).fail(function () {
                              //alert("Error submitting forms!");
                     })
              });
            });
        </script>
```
The order of the form in html is:

`<form id="form1"><!--form content here --></form>`
Here was the error in the second form

`<form id="form2"><!--form content here --> `
Form 3

`<form id="form3"><!--form content here --></form>`
The second form there was not a close tag but is very weird **jquery.serialize** Behave this way because the **#form2** has nothing to do with the other forms and the jquery code, the jquery was send just the **#form1** and **#form3** so the **#form2** has nothing to do with the forms was serialized and posted, ###

**Comment by dmethvin** [comment]
This is not part of jQuery Core, it is a plugin. The error in your markup made the page invalid anyway.

**Comment by dmethvin** [comment]
Correction, `.seralize()` is part of core. Since your markup wasn't valid the behavior is undefined.
