### ISSUE TITLE
`cleanData` performance issues

### ISSUE THREAD

**Issue by baptistebriel** [jquery/jquery#3655]
Hi there,

I came across a huge performance issue with using jQuery and Backbone: on the `destroy` function, Backbone calls `this.$el.remove()` to remove the view element from the DOM.

Nothing crazy here, only the `remove` function from jQuery will call `cleanData`. This function seems to be querying all child elements, and then calling `removeChild()` for all of these elements.

![screen shot 2017-05-03 at 12 40 13 pm](https://cloud.githubusercontent.com/assets/2464663/25678631/3a8171f6-2fff-11e7-8201-de94ea741d63.png)

![screen shot 2017-05-03 at 12 40 40 pm](https://cloud.githubusercontent.com/assets/2464663/25678648/50652d64-2fff-11e7-8a7f-0d83f41c7389.png)

In my case, it will call `removeChild` on 286 elements:

![screen shot 2017-05-03 at 12 41 36 pm](https://cloud.githubusercontent.com/assets/2464663/25678643/4a28127c-2fff-11e7-8d88-2a5aab53c492.png)

I wanted to understand why jQuery is actually calling this `cleanData` function, and why is it removing all child nodes while I just wanted to remove the parent element (`this.$el.remove()`) ?

If anyone has any ideas, would be much appreciated.
Thanks!

**Comment by dmethvin** [comment]
As you might guess from its name, `jQuery.cleanData()` cleans out the data on elements that have been added by calls to jQuery's `.data()` method, including any event handlers attached by `.on()` which uses jQuery's data functionality internally.  When you remove a large DOM subtree, jQuery has to go through it to free up any data that may be stored on elements in the subtree and call any custom event teardown handlers that may have been set for the element. That can take quite a bit of time. Given a random point in the DOM tree, jQuery doesn't have a way to know whether the elements in that subtree contain custom event handlers or data that must be explicitly removed.

If you know for sure that none of the descendants of `this.$el` contain any jQuery data, you could do something like `this.$el[0].innerHTML = "" ; this.$el.remove()` to avoid searching the subtree for data and events. Be careful though, if you are incorrect about that knowledge the result will be memory leakage and/or event handlers that may incorrectly fire and cause unpredictable behavior. 

These pictures don't indicate which version of jQuery is involved, and things work differently from jQuery 1, 2, and 3. All of them require inspecting the subtree to some extent.
