### ISSUE TITLE
script error within angular template

### ISSUE THREAD

**Issue by qqsea** [jquery/jquery#3663]
### Description ###
I am import java script lib for some certain html view of angularjs, but always error. I debug error and find it is the Jquery error: _**TypeError: Cannot read property '*' of undefined**_

The whole process is as below,
 I add <script> within html template, and then jQuery find that "_hasscript_" and then it will call ajax method:
jQuery.ajax({
url: node.src,      // the whole path of javascript file
type: "GET",
dataType: "script",
async: false,
global: false,
"throws": true
});

after some processing, it goes to 
jqXHR.setRequestHeader(
"Accept",
s.dataTypes[ 0 ] && s.**_accepts_**[ s._**dataTypes[0]**_ ] ?
	s.accepts[ s.dataTypes[0] ] + ( s.dataTypes[ 0 ] !== "*" ? ", " + allTypes + "; q=0.01" : "" ) :
	s.accepts[ "*" ]
);

since  s.**_accepts_** is undefined and s._**dataTypes[0]**_ is '*', then the error happen.

So what is the problem here? Is there anything wrong with the JQuery under angularjs or I am missing something?

Thank you very much!

**Comment by dmethvin** [comment]
Since there's no test case I'll close this. A test case should just include jQuery (the latest 3.x version) and not Angular. You might try asking for debugging help on StackOverflow.
