### ISSUE TITLE
Delegated click handler is not called when non-button target is disabled

### ISSUE THREAD

**Issue by russplaysguitar** [jquery/jquery#3664]
### Description ###

If a non-button target element of a delegated click handler is disabled by `$.prop()`, the handler is not called. I expected the handler to be called because the element does not support the `disabled` attribute, 

Reproduced the issue in Chrome and Firefox. 

I believe that this is the problematic line: https://github.com/jquery/jquery/blob/master/src/event.js#L382

Example: 
```
<!--- html --->
<a id="link" href="#">click me twice</a>
```
```
// js
$(document).ready(function() {
  $('body').on('click', '#link', function() {
    alert('clicked');
    $('#link').prop('disabled', true);
  });
});
```

### Link to test case ###

jQuery: https://codepen.io/anon/pen/KmZaOp?editors=1010
Zepto: https://codepen.io/anon/pen/rmpyBW?editors=1010 (for comparison)

**Comment by dmethvin** [comment]
I looked about a year ago and browsers still weren't consistent about propagating clicks on disabled buttons/links. You can see all the ticket references there. Is there a reason why you're setting a property on elements that has a defined meaning on other elements? Or did you just happen to pick that name because it was short and meaningful for your custom need?

**Comment by russplaysguitar** [comment]
I set the `disabled` property on some links out of habit (since it works on buttons). Only afterwards did I realize that it shouldn't disable the click handler, since the property is not supported on links. This is certainly not a critical issue for me, I just make it a habit to report potential bugs to open source projects that I use.

**Comment by timmywil** [comment]
We talked it over and there are so many things you can break with invalid HTML. We deemed the possible solutions here not worth it.

**Comment by russplaysguitar** [comment]
That's fine, thanks for considering it. I just thought I might as well get this situation documented in case anyone else runs into it.
