### ISSUE TITLE
Can somebody explain in detail $(window).scrolltop() NOT AN ISSUE

### ISSUE THREAD

**Issue by MandarSant** [jquery/jquery#3665]
I posted siilar Q on 

> **Stackoverflow** and **Jquery forum** 

but nobody answered

I am learning parallax scrolling using jquery and there is statement 

`$(window).scrolltop() `

can somebody explain in detail how it works dynamicaly 

```
$(window).scroll(function(){

  var wScroll = $(this).scrollTop();

  if (wScroll <= pContainerHeight) {

    $('.logo').css({
      'transform' : 'translate(0px, '+ wScroll /2 +'%)'
    });

    $('.back-bird').css({
      'transform' : 'translate(0px, '+ wScroll /4 +'%)'
    });

    $('.fore-bird').css({
      'transform' : 'translate(0px, -'+ wScroll /40 +'%)'
    });

  }
```

**Comment by mgol** [comment]
This is a jQuery bug tracker, not a support forum. The fact no one answered to you in other places is not an excuse to look for help here.
