### ISSUE TITLE
Strange values of $(window) outer dimensions

### ISSUE THREAD

**Issue by lucas-viewup** [jquery/jquery#3667]
Hello, I noticed strange values of $(window) outer dimensions, the width and height are different from vanilla javascript, look below:

<img src="http://i.imgur.com/SnNeBHs.png" />

Here's the codepen sample, https://codepen.io/lucasviewup/pen/RVMgKG, hope it helps,
regards,

**Comment by fastfasterfastest** [comment]
Per http://api.jquery.com/outerheight:
> This method is not applicable to window and document objects; for these, use .height() instead

And per http://api.jquery.com/outerWidth:
> This method is not applicable to window and document objects; for these, use .width() instead
