### ISSUE TITLE
event.which may need to be updated soon

### ISSUE THREAD

**Issue by thdoan** [jquery/jquery#3668]
### Description ###

According to the [jQuery docs](https://api.jquery.com/event.which/):

> The event.which property normalizes event.keyCode and event.charCode.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent), both `event.keyCode` and `event.charCode` are deprecated:

> This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Avoid using it and update existing code if possible.... Be aware that this feature may cease to work at any time.

The suggested replacement for these is `event.key`, which returns the key label (e.g., "Escape") instead of key code (e.g., 27), so I guess it won't be a suitable replacement for jQuery's `event.which`. I'm not sure what jQuery is planning to do with this, but it would be nice to have a version of `event.which` that returns a key label instead of key code.

**Comment by timmywil** [comment]
Thank you for opening an issue, but we'd like to avoid copying too many properties (unless they need normalizing) for perf reasons. See issues https://github.com/jquery/jquery/issues/3235 and https://github.com/jquery/jquery/issues/2337 for discussions on where to go after deprecating `event.which` in jQuery.

**Comment by thdoan** [comment]
Thanks for the links -- issue #2337 was very informative.
