### ISSUE TITLE
.always parameters

### ISSUE THREAD

**Issue by dbol55** [jquery/jquery#3670]
Please do not mix parameters in always function.

**Comment by mgol** [comment]
Unfortunately, this behavior has long history and changing that would be too big a breaking change right now. We document the issue at https://api.jquery.com/deferred.always/:

> Note: The deferred.always() method receives the arguments that were used to .resolve() or .reject() the Deferred object, which are often very different. For this reason, it's best to use it only for actions that do not require inspecting the arguments. In all other cases, use explicit .done() or .fail() handlers since the arguments will have well-known orders.
