### ISSUE TITLE
event.pageY is browser dependend

### ISSUE THREAD

**Issue by cmb69** [jquery/jquery#3676]
### Description ###

`event.pageY` is browser dependent if there is a `margin-top` set for the `<html>` element. While on most browsers I've tested (Chrome 58.0.3029.110, Firefox 53.0.2 and Edge 38.14393.1066.0) it takes into account the `margin-top`, it doesn't do so on IE 11.1198.14393.0. I would expect the behavior to be consistent.

### Link to test case ###

https://jsfiddle.net/5a1536bq/

Open the console to see the debug values. Both should be roughly the same, but on IE they're not.

PS: to see the debug output, you have to click on "foo".

**Comment by dmethvin** [comment]
This is a long-standing problem with margins on the html or body elements. There are comments already for [`.offset()`](http://api.jquery.com/offset/) and [`.position`](http://api.jquery.com/position/) in the documentation about this issue and it's from the same cause.

Most CSS resets explicitly set margin and padding on html and body to 0 which would solve the issue. Is that something you can do?

**Comment by cmb69** [comment]
We use the margin-top in a CMS to add a menu at the top of the viewport, pushing down the rest of the theme, and not setting margin-top respectively would cause a lot of other issues. I can work around this issue, though.

Anyhow, after some further testing, this is obviously a bug in IE, since event.clientY reports an expected value, see https://jsfiddle.net/5a1536bq/6/.

**Comment by timmywil** [comment]
Thank you for opening an issue, but we're not likely to make changes here.
