### ISSUE TITLE
Differing results for .height() when zoom is set to a non 100% value and has padding with box-sizing set to border-box

### ISSUE THREAD

**Issue by cuzzins** [jquery/jquery#3681]
### Description ###
Differing results for .height() when zoom is set to a non 100% value (actually seems to be specific to 110% in Chrome) and has padding with box-sizing set to border-box.  The results in latest jQuery differ from what was returned in 2.x.

Div 400px high with 25px padding all around:

* With box-sizing: border-box at 100% zoom the result is 350 in both latest jQuery and 2.2.4 (so subtracted padding)

* With box-sizing: border-box at 110% zoom the result is 400 (so no padding subtracted) in latest jQuery and 350 in 2.2.4 (so subtracted padding)

* Without border box both zoom levels give 400 in both versions so no padding subtracted.

Inner and Outer heights also seem to be broken, am seeing heights of 450 returned when the element is 350 + (25*2)

I would expect the result with border-box to be consistent at all zoom levels as it is without border-box. I believe this is different from #3193 as that seems to involve transforms (however not sure if Chrome handles zoom internally as a form of transform, so may be related)

Have only tested this so far in Google Chrome: Version 58.0.3029.110 (64-bit)

### Link to test case ###
https://jsfiddle.net/8kdca607/2/

**Comment by dmethvin** [comment]
The [docs for .height()](http://api.jquery.com/height/) say:
> dimensions may be incorrect when the page is zoomed by the user; browsers do not expose an API to detect this condition.

Is that consistent with your experience?

**Comment by cuzzins** [comment]
If jQuery will never or cannot support browser inbuilt zoom I think that should be a standard caveat.  

One thing I will point out is that my use case showed this working in 2.x and failing in 3.x - I cannot stop our users switching their zoom levels from 100% and this breakage appears to be specifically for 110% in Chrome.  Am assuming that something between 2.x and 3.x has changed how height(0 is calculated in this respect as this break did not occur in 2.x.

If zoom is not supported by jQuery should we assume our best approach is to move away from jQuery into another library or pure JS if that is a requirement for these specific cases?  In our case the issue was fixed by subtracting the calculate padding for top and bottom from the calculated height. but that is based on very specific CSS

**Comment by dmethvin** [comment]
> If jQuery will never or cannot support browser inbuilt zoom I think that should be a standard caveat.

It is a standard caveat. That phrase I quoted is in [every dimension-related API page](https://www.google.com/search?q=dimensions+may+be+incorrect+when+the+page+is+zoomed+site%3Aapi.jquery.com). 

> If zoom is not supported by jQuery should we assume our best approach is to move away from jQuery into another library or pure JS if that is a requirement for these specific cases?

If you can solve a particular case by writing your own code, do it. That's often possible when you can narrow the scope of the problem by using things you know about invariants in the layout. If there is "another library or pure JS" that solves this general problem, let us know.

**Comment by cuzzins** [comment]
So the fact this used to work and broke between 2.x and 3.x does not matter? Am concerned as it may inadvertently affect other aspects of dimensions when zoom is involved.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dmethvin** [comment]
It's not uncommon for cases that we document are unsupported to change their behavior across versions. We can't test this, so yes it may change. The browsers don't give consistent results for zoomed dimensions. As you mentioned you've only tested this on Chrome so far, so imagine trying to test this on all the browsers we support when there is no programmatic way to zoom the page the same way the user can. 

Is there some simple solution we're missing?

**Comment by cuzzins** [comment]
Maybe I need to delve in to the code to try and work out why the code was changed in a breaking way. Am not against the change but it it breaks our code in a way that I need to find it a solution for. That way seems to be to avoid jquery for dimension related code, my fear is how much other code may broken. Kinda been happy with jquery for this, but not sure why this change happened In such a way that broke things.  Most of our users in this case use Chrome, will start testing zoomin other browsers but not sure it matters if unsupported

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dmethvin** [comment]
It's no doubt a change in the math that we do in calculating dimensions. It's possible this will change again if/when we fix gh-3611 or land things like gh-3656 .
