### ISSUE TITLE
Done and Then callback are not called in the same order

### ISSUE THREAD

**Issue by npiron** [jquery/jquery#3684]
### Description ###
On resolved deferred, **done** callback are immediatly invoked unlike **then** callback that will wait for the scope end.
The first argument of Then is done callback. I thought that the behavior would be identical 
Is this normal ?
### Link to test case ###
https://jsfiddle.net/btksmm3w/

**Comment by mgol** [comment]
This is intended; see https://jquery.com/upgrade-guide/3.0/#callback-invocation
