### ISSUE TITLE
[Feature Request] jQuery Group

### ISSUE THREAD

**Issue by lucas-viewup** [jquery/jquery#3685]
Hi folks,

__If this feature already exists, please close this issue.__

* Does it require access to jQuery internals? 
No
* Can jQuery itself benefit from the feature?
Yes, because can avoid repetitive tasks like:
```javascript
   ...
   $elem1.addClass('my-class');
   $elem2.addClass('my-class');
   $elem3.addClass('my-class');
   ...
```
* Is the need already served by a plugin?
I didn't found a plugin to do this, but it's not a bad idea to make a plugin too.

* Does it change an existing API?
No

* Does it support best practice?
Yes, because follows DRY concept.

I was thinking about this:
```javascript
$.group([ $elem1, $elem2, $elem3 ...], function($elem){
   $elem.addClass('my-class');
});
```

Here the codepen as example: [https://codepen.io/lucasviewup/pen/PjoPgr](https://codepen.io/lucasviewup/pen/PjoPgr)

Regards,

**Comment by scottgonzalez** [comment]
You're not going to find a plugin for that because it's literally just `Array#forEach()`. If for some reason you still want to support old browsers, you can use `jQuery.each()` or `jQuery.map()` if you don't want the index first.

**Comment by lucas-viewup** [comment]
Ok, but the main idea was merge the element variables in only one and then do some action with it. Example:
```
var $elem3 = $elem1 + $elem2; //just to show the example of merge
$elem3.addClass('my-class');
```

then, both $elem1 and $elem2 would have the class 'my-class'

**Comment by scottgonzalez** [comment]
Why does that matter? The end result is exactly the same. Also, your `+` example is just the existing `.add()` method.

**Comment by lucas-viewup** [comment]
@scottgonzalez, many thanks, exactly what I meant!
