### ISSUE TITLE
Synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by DifficultPhil** [jquery/jquery#3686]
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

line 9425
`xhr.open(`
version: 3.1.1

this is hard warning?

**Comment by mgol** [comment]
This warning is generated by the browser, not jQuery. It's best to avoid synchronous XHR.
