### ISSUE TITLE
$.param({ key: <64bitslongvalue> }) corrupts the value

### ISSUE THREAD

**Issue by OzoneGrif** [jquery/jquery#3690]
Tested with JQuery version 3.2.1 on Chrome 58 and FireFox 53.

Try in the console : `$.param({test:72058158960299766});`

It returns : `"test=72058158960299760"` (note the 60 instead of 66)

https://www.w3schools.com/code/tryit.asp?filename=FGE6LEUSOJ2E

**Comment by OzoneGrif** [comment]
Nevermind :

> In JavaScript, all numbers are 64 bits floating point numbers. This means you can't represent in JavaScript all the Java longs. The size of the mantissa is about 53 bits, which means that your number, 793548328091516928, can't be exactly represented as a JavaScript number.

More JS crazyness...

**Comment by rwaldron** [comment]
> More JS crazyness... 

https://en.wikipedia.org/wiki/IEEE_floating_point

**Comment by OzoneGrif** [comment]
The crazyness is to use floats by default for everything.
