### ISSUE TITLE
IE9 and the incredible shrinking scrollboxes

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#3699]
80f1c8239e9d5f793f3e54e0cb8d7bd0747e4856 worked everywhere except IE9: http://swarm.jquery.org/result/2255930

Investigation traced the root cause to a mishandling by that browser of `box-sizing: content-box`, particularly in combination with `overflow: scroll`... specifically, `getComputedStyle` seems to always report content box dimensions, even for border-box elements, and the lack of accounting for scrollbars means that round-trip set operations shrink such elements: https://jsbin.com/zotomuqoho/edit?html,css,js,output

**Comment by mamieS99** [comment]
I have to look at video again this looks different  and i get confused of the step, will have to come back. Cant do it yet. #

**Comment by Krinkle** [comment]
While now fixed in IE 9, the fix subsequently broke IE 10/11. https://github.com/jquery/jquery/issues/3731
