### ISSUE TITLE
jQuery Data cache may be memory leak

### ISSUE THREAD

**Issue by zzuligy** [jquery/jquery#3703]
### Description ###

On a long run web app,There are so much event add and remove.but the event's remove only use this this.cache[ unlock ] = {};
In the end,there will be  hundred thousand long cache Array.
In the chrome profiler tool,this cache occupy a lot of memory.as the time go on ,the situation is more worse.

**Comment by timmywil** [comment]
Thanks for opening an issue. However, we need issues with test cases to demonstrate and reproduce the problem so that we can work on it. Please provide a test case and we can reopen.
