### ISSUE TITLE
$("*") fails with Maximum call stack size exceeded

### ISSUE THREAD

**Issue by NN---** [jquery/jquery#3704]
Open this html file.

https://mega.nz/#!qphByIrJ!72ksYS6ceoQw8KYUwKjb03K2DiMfKjQNh6HKYoAuKJQ

Simple code of $("*") fails with:

```
jquery-3.2.1.js:2704 Uncaught RangeError: Maximum call stack size exceeded
    at Sizzle.select (jquery-3.2.1.js:2704)
    at Function.Sizzle [as find] (jquery-3.2.1.js:884)
    at jQuery.fn.init.find (jquery-3.2.1.js:2922)
    at jQuery.fn.init (jquery-3.2.1.js:3032)
    at jQuery (jquery-3.2.1.js:98)
    at jqqs.html:15
```

While document.querySelectorAll("*") works as expected.

**Comment by dmethvin** [comment]
> While document.querySelectorAll("*") works as expected.

However, `[].push.apply([], document.querySelectorAll("*"))` dies in the same way on Chrome. 

On Edge it takes 2 minutes 15 seconds to give an answer, but it does return. On Firefox it runs almost instantaneously.

Seems like this is an issue independent of jQuery?

**Comment by NN---** [comment]
Jquery should not fail with stack exceeded at least.
The function should be rewritten to not use recursion.

**Comment by dmethvin** [comment]
Look at the repro case I gave above. This fails in Chrome as well, no jQuery at all. Type it into your console. 

`[].push.apply([], document.querySelectorAll("*"))`

**Comment by timmywil** [comment]
However, this seems to work...

```js
var elems = document.querySelectorAll('*');
var arr = [];
for (var i = 0, len = elems.length; i < len; i++) {
  arr.push(elems[i]);
}
```

Let's talk in the meeting.

**Comment by timmywil** [comment]
We're going to try dropping `push.apply` and just use the for loop (which is already in Sizzle as a IE<9 fallback). If perf isn't an issue, code will end up being shorter.

**Comment by timmywil** [comment]
Moved to Sizzle issue: https://github.com/jquery/sizzle/issues/403

**Comment by docluv** [comment]
Using apply creates new arguments, which eventually exceed the size of the stack. The for loop does not place the results in the argument list and thus keeps the stack smaller :)
