### ISSUE TITLE
Create a wiki page with steps for deprecation

### ISSUE THREAD

**Issue by ShashankaNataraj** [jquery/jquery#3706]
https://github.com/jquery/jquery/pull/3702 has some important information that is being repeated by maintainers when guiding people who are new to contributing to this repo.

It would be good if new contributors had a central place where all the steps and pitfalls to deprecate an existing method were documented.

**Comment by ShashankaNataraj** [comment]
@timmywil Im unable to create a new wiki page maybe because:

`By default, only collaborators on your repository can make changes to wikis, but you can configure this to be enabled for all users on public repositories.` as stated in https://help.github.com/articles/about-github-wikis/

Any pointers on how I could go about creating this wiki page?

**Comment by timmywil** [comment]
I've created https://github.com/jquery/jquery/wiki/Helpful-Tips-for-Contribution and opened up wiki editing. That might be temporary depending on whether we get spam.
