### ISSUE TITLE
commitplease error message during `npm install`

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#3708]
### Description ###
Invoke the following on Node.js `8.1.3` with npm `5.0.3` (the default included version):
```
git clone git@github.com:jquery/jquery.git
cd jquery
npm install
```
You'll see the message printed in red:
```
The following hook already exists:
/Users/mgol/Documents/projects/public/jquery/jquery-copy/.git/hooks/commit-msg
Remove it and install this package again to install commitplease properly
```
This is a fresh clone so no git hooks were present before running `npm install` and the message suggests they were.

cc @all3fox 

### Link to test case ###
Embedded in the description.

**Comment by all3fox** [comment]
Thanks for the report! I've compared the results of `process.cwd()` call on node `7.10.0` and node `8.1.2` --- it returns different values. That is important because `getOptions()` uses `process.cwd()` to find `package.json` and configure how to install commitplease. Let me think a bit more.

**Comment by all3fox** [comment]
Ok, I've taken a look at `process.cwd`, `process.env` and `process.argv`. The only reliable way I know to find out the path to the `package.json` of a project that is trying to install `commitplease` is to rely on the fact that `npm` will inject a path ending in `commitplease/node_modules/.bin` into the `PATH` of `process.env`. So, one could find this path by this suffix, chop it off and use the prefix to get to `package.json`. Anyone know a less hacky approach?

**Comment by jaubourg** [comment]
`require( "commitplease/package.json" );` doesn't work ?

**Comment by all3fox** [comment]
That gives the `package.json` of `commitplease` but that is not what I need. What I need is `package.json` of the project that is installing `commitplease` (in this case `jquery`) because that `package.json` contains settings like "do not install the hook" which are project-specific.

**Comment by jaubourg** [comment]
My bad.

**Comment by all3fox** [comment]
For some reason specifying:

```
"commitplease": "git://github.com/jzaefferer/commitplease.git#8176be13e329ed064aa76515b92486c3e459001a"
```

or


```
"commitplease": "git://github.com/jzaefferer/commitplease.git#fix-3708"
```

in `package.json` for `jquery` does not download the github version of the code (if I look inside the `node_modules/commitplease/index.js`, it is the old one), so I did not test that. I did however test with `npm install ../commitplease` from inside `jquery` directory and it worked.

**Comment by all3fox** [comment]
Correction: installation works but actual message linting does not. Looking into that.

**Comment by all3fox** [comment]
Nice (sarcasm). Now `argv` has changed. It is now empty and does not contain the path to commit message, as before. That was important to commitplease because that was used to distinguish between:

1. Being run as a hook (then go and fetch the `.git/COMMIT_EDITMSG`)
2. Being run as a global script (then use `.git` and `Git` js lib to do other checks)

Sorry, a new way to distinguish between a global and a hook is needed and I do not have ideas right now. /cc @jzaefferer

**Comment by timmywil** [comment]
I don't think there's anything jQuery can do here. Let me know if that's not the case.

**Comment by all3fox** [comment]
This problem is fixed in https://github.com/jzaefferer/commitplease/pull/98 but not merged it yet.

@jzaefferer please let me know what you think of that PR so we can merge and release it.
