### ISSUE TITLE
"fatal: BUG: initial ref transaction called with existing refs" during git clone

### ISSUE THREAD

**Issue by 4z5lz** [jquery/jquery#3709]
During git clone I receive this error:

> $ git clone https://github.com/jquery/jquery.git
> Cloning into 'jquery'...
> remote: Counting objects: 42161, done.
> remote: Compressing objects: 100% (2/2), done.
> remote: Total 42161 (delta 1), reused 0 (delta 0), pack-reused 42159
> Receiving objects: 100% (42161/42161), 26.66 MiB | 405.00 KiB/s, done.
> Resolving deltas: 100% (29816/29816), done.
> fatal: BUG: initial ref transaction called with existing refs
> Unlink of file 'jquery/.git/objects/pack/pack-ae403ff23e4282f3e2bacd5cb2bd7fc906f1c7de.idx' failed. Should I try again? (y/n) y

git version 2.10.0.windows.1

**Comment by mgol** [comment]
Does this happen on every clone attempt (after you remove the `jquery` directory)?
