### ISSUE TITLE
IE BUG: jQuery resizable doesn't work if the element has a iframe sibling.

### ISSUE THREAD

**Issue by gurumvg** [jquery/jquery#3711]
### Description ###
The resizable method doesn't work in IE11 & EDGE if the resizable element has an iframe next to it.
In the below example, resize the element to the right horizontally towards the iframe - the resize handle drops visually as soon as the cursor enters iframe region. However, when you resize left the resize handle surfaces back.

### Link to test case ###
https://jsfiddle.net/dfqtt/283/

**Comment by Johann-S** [comment]
It seems JQuery UI has it own bug tracker here : https://bugs.jqueryui.com/
IMO you should post your issue in this bugtracker

**Comment by gurumvg** [comment]
Thanks @Johann-S for pointing me to right forum, created one there.
https://bugs.jqueryui.com/ticket/15215
