### ISSUE TITLE
$.ajax: How to disable parsing?

### ISSUE THREAD

**Issue by hardhub** [jquery/jquery#3712]
I want to parse result from ajax manually. So I need only responseText...
If I will use "done" callback then I will get data already parsed (as first parameter).

I do not see any options to disable it. Have I misunderstand something? Or can it be CR?

**Comment by dmethvin** [comment]
This is a question better answered on StackOverflow. See the `dataType` property and post followup questions there.

**Comment by hardhub** [comment]
I think you mean dataType: "text".
It was not very obvious since JSON is always text:

JSON is text, written with JavaScript object notation (https://www.w3schools.com/js/js_json_intro.asp).
