### ISSUE TITLE
AMD require jquery with other module name failed.

### ISSUE THREAD

**Issue by godtail** [jquery/jquery#3718]
### Description ###

In my h5 project, i use a module 'lib' to process the dom, ajax...， zepto and jquery is always same, so i want change the 'lib' module dynamic , if i use jquery features, 'lib' will be jquery, else keep small and use zepto. 

Here is my code.
```javascript
// require config
require.config(
{
        paths: {
            'lib': 'zepto' // or jquery
        },
    };
)

// use
require(['lib'], function($) {
    console.log($); // undefined
})
```

I search the jquery src and found code in [src/exports/amd.js](https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/src/exports/amd.js)

```javascript
define( "jquery", [], function() {
     return jQuery;
 });
```
**I moved module name 'jquery', and it works, so what about remove the module name for flexible use?**

**Comment by dmethvin** [comment]
The comment in that file points to https://github.com/jrburke/requirejs/wiki/Updating-existing-libraries#wiki-anon

**Comment by timmywil** [comment]
Thanks for opening an issue, but this is a question better suited for stackoverflow, or you should be able to find what you need on requirejs.org.

**Comment by godtail** [comment]
@dmethvin @timmywil Thanks, My fault, didn't pay attention to comments. 

I will search it from google and stackoverflow.

**Comment by TechQuery** [comment]
@godtail What you need is [`map` option](http://requirejs.org/docs/api.html#config-map)~
