### ISSUE TITLE
Do not include `src` directory into npm package

### ISSUE THREAD

**Issue by KELiON** [jquery/jquery#3719]
`jquery` npm package uses only `dist` directory, so `src` directory could be excluded from npm build by adding it to `.npmignore`.  It can reduce `jquery` package size after installation with `npm install` by 548kb.

**Comment by dmethvin** [comment]
The `src` directory is the AMD modules so they have to be published.

**Comment by timmywil** [comment]
Thanks for opening an issue, but 2 things.

1. We want the `src` directory included for those that prefer to include individual modules.
2. We do not publish to npm from this repo. The build scripts push relevant files to the jquery-dist repo and publish to npm from there.
