### ISSUE TITLE
Feature request:  delay on .blur() 

### ISSUE THREAD

**Issue by DanAtShenTech** [jquery/jquery#3721]
I just tried the following and it does not work:
input.val('5%').blur();

It also does not work if the blur() is moved to a separate line.  It DOES work if the .blur() is wrapped in a setTimeout.  It would be useful if a parameter for delaying the execution of the .blur() command by a certain number of milliseconds could be implemented.  It might be even better if a delay was built-in as a default with the ability to change the delay via the parameter.

**Comment by dmethvin** [comment]
As the template for the issue requested, we would like to see a test case and also a clearer description of "work" -- although that might be totally clear once there is a test case.

**Comment by DanAtShenTech** [comment]
Tried repeating in [this fiddle](https://jsfiddle.net/vqvho4br/16/), but cannot reproduce as it was occurring in our code.  Closing this issue.
