### ISSUE TITLE
PhantomJS 1.x failure

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#3726]
I've been investigating why there are multiple failures in the jQuery Migrate unit tests, only on PhantomJS. Even a simple test like `jQuery( document.body ).append( document.createElement("p") );` throws an error. 

I  bisected it down to a16339b8933f115da3661f3d3f64854c3fa60bdc and [this line](https://github.com/jquery/jquery/blob/a16339b8933f115da3661f3d3f64854c3fa60bdc/src/core.js#L220) in core.js:

`return typeof obj === "function" && typeof obj.nodeType !== "number";`

Unfortunately, `getAll` returns a NodeList that looks like a function but doesn't have a `nodeType` property so that fails the `isArrayLike` test when it shouldn't.

Do we want/have to support PhantomJS 1.x in jQuery 3.x? If so I think we'd need to fix this.

**Comment by mgol** [comment]
We've never officially supported PhantomJS (any version). I think it's fine if we just start testing on 2.x if it helps.

**Comment by dmethvin** [comment]
Yeah I don't really *want* to support PhantomJS 1.x in jQuery core but then again I don't *want* to redo the whole unit test and code coverage setup in Migrate either. 😸 I would just patch around this to keep things going but `isFunction` isn't exposed anymore and it's called from within `isArrayLike` which is also well protected. Let me see what it will take to get Migrate working with PhantomJS 2.x, maybe it's not bad.

**Comment by mgol** [comment]
Upgrading to PhantomJS v2 should be simple... (famous last words, I know)

**Comment by dmethvin** [comment]
I upgraded jQuery Migrate to PhantomJS 2 and can't get it to work on Windows, but Travis seems to dig it and we have only one failure that I'm looking into.

**Comment by dmethvin** [comment]
I think we're good on this, it would be good in the release notes/blog to remind people that we don't support PhantomJS 1.x when we do the next release since this will break it and can't easily be fixed from the outside.

**Comment by timmywil** [comment]
Will do.
