### ISSUE TITLE
$.fn.scrollTop question

### ISSUE THREAD

**Issue by heqh** [jquery/jquery#3728]
### Description ###

In firefox    $('body').scrollTop();  is does not work 
![image](https://user-images.githubusercontent.com/10557075/28311761-37db1d92-6be3-11e7-9faa-d0e03d2ca9fb.png)

### Link to test case ###
if( elem.tagName == 'BODY' ){
    elem = window;
}
var win = getWindow( elem );

I don't know whether it is reasonable or not

**Comment by mgol** [comment]
This is expected; read https://dev.opera.com/articles/fixing-the-scrolltop-bug/ for more information.
