### ISSUE TITLE
Regression: Dimensions tests broken in IE 10 and IE 11

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#3731]
8 test failures with IE 10 and IE 11 in the `dimensions` module.

Traced to: https://github.com/jquery/jquery/commit/3fcddd6e72e7e318c0b062e391d60867732318ae and issue #3699.

TestSwarm job: http://swarm.jquery.org/job/5741

It seems this commit fixed 12 test failures from IE 9, but in return broke 8 tests in IE 10 and IE 11.

<img width="687" alt="screen shot 2017-07-18 at 14 37 44" src="https://user-images.githubusercontent.com/156867/28336215-aefc5610-6bc6-11e7-9286-f8216a25aaf8.png">

**Comment by gibson042** [comment]
Noted, and should be fixed by https://github.com/jquery/jquery/commit/20cdf4e7de60f515a7acf6c70228c52668301d9b. :crossed_fingers:

**Comment by Krinkle** [comment]
Fixed.

**Comment by gibson042** [comment]
I'm calling it good, the only failures were Chrome focus issues: http://swarm.jquery.org/job/5791
