### ISSUE TITLE
Regression: Event tests failing in Chrome 58+

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#3732]
The last remaining test failure for jQuery core in TestSwarm is in `events`. Affects Chrome 58 and higher. It seemed to pass in Chrome 57 at the time (since then we updated CI to test in Chrome 58 and Chrome 59 only, which both fail.)

**Traced to**: https://github.com/jquery/jquery/commit/36389288e8c7f2538b5ae7dd6877e81a9a76c644

**TestSwarm job**: <http://swarm.jquery.org/job/5626>

**Problem**:

The test suite for `events` consistently times out in Chrome around this test:

> **event: preventDefault() on focusin does not throw exception**

<img width="678" alt="screen shot 2017-07-18 at 15 53 39" src="https://user-images.githubusercontent.com/156867/28339299-4e6cf88a-6bd1-11e7-9b6e-cf29d25404ce.png">

While it passes consistently in Chrome 58 and 59 from BrowserStack API in TestSwarm, it does pass when I try it manually in BrowserStack Live, as well as when I try it locally on my own machine.

Fails:
* Chrome 58 (BrowserStack API): `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36`
* Chrome 59 (BrowserStack API): `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36`

Passes:
* Chrome 59 on Windows 8.1 (BrowserStack Live): `Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36`
* Chrome 59 on Windows 8 (BrowserStack Live): `Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36`
* Chrome 59 on Windows 7 (BrowserStack Live): `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36`
* Chrome 59 (Mac OS X): `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36`

**Comment by jbedard** [comment]
What would `Deferred` even be used for when running the `events` suite? Weird... 🤔

**Comment by mgol** [comment]
36389288e8c7f2538b5ae7dd6877e81a9a76c644 is most likely unrelated. If I remember correctly when I noticed the tests were failing after I changed Chrome 57/58 to 58/59 and a TestSwarm job has started I restarted one older job in Chrome 58 & 57 to ensure it was fine then and the v57 one passed while the v58 one failed. So it seems (if my memory doesn't fail me) that:

1. Chrome 58 has changed something so that the test now breaks.
2. It used to work even in Chrome 58 for some time so most likely something changed on the BrowserStack side.

**Comment by gibson042** [comment]
Sorry about all the noise; CI-sensitive issues are always the hardest to fix. However, we are now _finally_ back to passing: http://swarm.jquery.org/job/5817

If anyone would like to perform a post-hoc review, here is a comprehensive view of the changes: https://github.com/jquery/jquery/compare/d9a099a58e1bb1f158ea66ec55534770be442907%5E...d65bdd5fc8edf390211ed2223a03c6a00a41c649 (and also one [ignoring whitespace](https://github.com/jquery/jquery/compare/d9a099a58e1bb1f158ea66ec55534770be442907%5E...d65bdd5fc8edf390211ed2223a03c6a00a41c649?w=1)).
