### ISSUE TITLE
Add unit test for $.getScript signature that accepts the options object

### ISSUE THREAD

**Issue by oriadam** [jquery/jquery#3736]
### Description ###
Unit test needed for the $.getScript options signature.
See PR https://github.com/jquery/api.jquery.com/pull/1054/

jQuery 1.12.0 added a signature for passing an options object to $.getScript.
This signature cannot be documented before a unit 
This signature is a blessing, allows an easy way to cancel the anti-cache like this:
```
 $.getScript({
        url: "foo.js",
        cache: true
    })
```

### Link to test case ###
https://jsfiddle.net/oriadam/h0b26L1a/

**Comment by mgol** [comment]
Thanks for the report!

**Comment by timmywil** [comment]
Looking over our unit tests again. It seems many of our ajax tests have been using this signature for a while now. See [this line](https://github.com/jquery/jquery/blob/master/test/data/testinit.js#L204) of the `ajaxTest` function.

**Comment by timmywil** [comment]
And of course when I close it, I realize this is specifically for `getScript`.
