### ISSUE TITLE
Calling "css" with "undefined" results in unfriendly error

### ISSUE THREAD

**Issue by WasabiFan** [jquery/jquery#3737]
### Description ###

When calling `css` with `undefined` as the only parameter, it throws the following error:
```js
$('div').css(undefined);
```

> Unable to get property 'replace' of undefined or null reference

I would expect it to be a silent no-op. In my case, I have a component which is passed an optional property for CSS on an icon -- it would be helpful if I could pass this value directly to jQuery and have it handle the situation where the property wasn't specified. I don't believe this behavior would interfere with other uses of the method.

### Link to test case ###
https://jsfiddle.net/9acdd3dz/

**Comment by mgol** [comment]
We've been going in the opposite direction recently - to not guard against undefined input and let it fail as it may mask errors. Sometimes it's better to have an error and avoid the bug.

In your case it should be simple to fix; just wrap the declaration with an `if` statement.

**Comment by WasabiFan** [comment]
That's a reasonable design choice. If the error is an expected behavior, that should be made explicit by detecting the case and throwing an error that mentions invalid arguments.

**Comment by dmethvin** [comment]
@WasabiFan That's not practical. There are a infinite number of invalid arguments. The API documentation makes it clear what is valid (or if it doesn't please make a PR to clarify them). jQuery's size would be extremely large if we had code inside it to check for every possible bad argument. If you're interested in catching these earlier in your development process, look into using TypeScript. There are DefinitelyTyped definitions for jQuery's API.

**Comment by WasabiFan** [comment]
> That's not practical. There are a infinite number of invalid arguments. The API documentation makes it clear what is valid (or if it doesn't please make a PR to clarify them).

The docs to not explain this behavior (which is easily fixable); they do, however, explain that this check is already implemented if you pass a function that returns your properties map:

> > Note: If nothing is returned in the setter function (ie. function( index, style ){} ), or if undefined is returned, the current value is not changed. This is useful for selectively setting values only when certain criteria are met.

Adding a check to no-op with an undefined parameter would make this behavior more consistent with the existing logic and wouldn't grow its size.

> If you're interested in catching these earlier in your development process, look into using TypeScript. There are DefinitelyTyped definitions for jQuery's API.

I am currently working with TypeScript. Unfortunately, TypeScript doesn't help in cases such as the one discussed here where you pass `undefined`.

**Comment by mgol** [comment]
> Unfortunately, TypeScript doesn't help in cases such as the one discussed here where you pass `undefined`.

It should work in strict null checks mode which is a good setting to enable. I haven't checked if the DefinitelyTyped jQuery definitions are compatible with that, though.

**Comment by WasabiFan** [comment]
Haha, although I agree that strict null checks are a good way to go, that'd cause some problems for me... this is a pretty large codebase with an unfortunate amount of legacy code :laughing:

**Comment by mgol** [comment]
As for the function signature, TBH I'm not a fan of those, IMO they mostly complicate the API. In case of `.css()` they even cause layout thrashing by design! But we have what we have and removing them now would be a big breaking change.

When someone uses such an API, migrating it away from a special `undefined` handling would be harder. With a non-function argument it comes down to changing:
```js
elem.css(data)
```
to:
```js
if (data) {
    elem.css(data);
}
```
If you use:
```js
elem.css(fn);
```
there's no direct equivalent.
