### ISSUE TITLE
$.type!!  Chinese can't get the right result.

### ISSUE THREAD

**Issue by dengzhiqiang** [jquery/jquery#3739]
`    //  I use Google browser
    //  Chinese can't get the right result
    //  jquery/3.2.1/jquery.min.js

    var name = {sex: '男'};
    console.log($.type(name)); // string  （Excuse me, why is the string output here?）
    console.log($.type({sex: '男'})); // object （But this way output object）
    console.log(typeof name); // string （Excuse me, why is the string output here?）`

**Comment by mgol** [comment]
If you're invoking this in a global context you're just overwriting `window.name` which is always casted to a string. Avoid writing code in a global context to avoid it.

**Comment by dengzhiqiang** [comment]
I see. Thank you very much
