### ISSUE TITLE
jquery 3.x  ajax  does not work async  = false

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [jquery/jquery#3740]
### Description ###
I updated jQuery from 2.2.4 to 3.2.1 and it stopped working properly with ajax parameter async = false.
How can I solve this problem?

**Comment by mgol** [comment]
Did you read the issue template? It asked for a test case. With such a short report there's nothing we can do.

**Comment by mariuszkrzaczkowski** [comment]
3.2.1: https://jsfiddle.net/5jmprj0x/
3.2.1: https://jsfiddle.net/4ngd9g4n/1/

The result should be that
1111
2222
33333

**Comment by mgol** [comment]
This is not the AJAX call that's asynchronous in your example but the invocation of the handler attached via `.then()`; they're always asynchronous now.

See https://jquery.com/upgrade-guide/3.0/#callback-invocation for more information, in particular:
> Another behavior change required for Promises/A+ compliance is that Deferred `.then()` callbacks are _always_ called asynchronously. Previously, if a `.then()` callback was added to a Deferred that was already resolved or rejected, the callback would run immediately and synchronously.

**Comment by mariuszkrzaczkowski** [comment]
Would you help with the improvement of this code?

**Comment by mgol** [comment]
Synchronous AJAX is generally a bad idea but a quick fix would be to switch from `.then` to `.done`.

**Comment by mariuszkrzaczkowski** [comment]
Thanks, it works
