### ISSUE TITLE
fixHooks usage exploration

### ISSUE THREAD

**Issue by brendon** [jquery/jquery#3748]
### Description ###

Per: https://jquery.com/upgrade-guide/3.0/#breaking-change-jquery-event-props-and-jquery-event-fixhooks-removed I'm opening this issue as a way of showing how `fixHooks` is being used in one particular project.

I didn't write the code, but am interested in making it compatible with both jQuery 3 and 1 & 2.

```
// If we're on a touch device, then wire up the events
// see http://stackoverflow.com/a/8456194/1316086
$.each("touchstart touchmove touchend".split(" "), function(i, name) {
    $.event.fixHooks[name] = $.event.mouseHooks;
});
```

https://github.com/isocra/TableDnD/blob/master/js/jquery.tablednd.js#L94
https://stackoverflow.com/a/8456194/129798

The intent seems to be to allow touch events to act like mouse events. Is this no longer a problem in jQuery 3?

**Comment by dmethvin** [comment]
Well it's not quite a test case and I don't know exactly what features that code may use, but most likely it is not needed in jQuery 3 at all now. Remove it and see if the code still works on a touch device.

**Comment by dmethvin** [comment]
If the code still needs to support both old and new jQuery, only run that code if jQuery.event.fixHooks exists.

**Comment by brendon** [comment]
Thanks @dmethvin, it seems to work fine on a touch device without the hack mentioned. I'll try to find out why it was originally added to determine if it's still needed.

**Comment by dmethvin** [comment]
Good to hear. Before jQuery 3, you could use code like that so that jQuery treated Pointer or Touch events like Mouse events and normalized their event objects. Because of changes in supported browsers and a different approach to normalizing event objects in jQuery 3, it shouldn't be needed. If you want to support all versions you could add `if ($.event.fixHooks) { ... }` around that code.

**Comment by brendon** [comment]
Thanks @dmethvin. That makes sense to me. We actually figured out that the code was superfluous in this case because the original problem was fixed in another way at another point in time (they needed to get the X and Y of the touch on the screen), so without the hack it still works in jQuery < 3.
