### ISSUE TITLE
Trigger click event with specific namespace on checkboxes trigger click

### ISSUE THREAD

**Issue by Curlyman** [jquery/jquery#3751]
### Description ###
The triggering of a specific namespace like "click.namespace1" on an input of type checkbox raise the "click" event and then all namespace "under" the click event.

### Link to test case ###
https://jsfiddle.net/eLr0pmov/

**Comment by gibson042** [comment]
This is another part of the #3423/#3579 cluster.

**Comment by mgol** [comment]
PR: #4279
