### ISSUE TITLE
passive listener for all 

### ISSUE THREAD

**Issue by frankl7800** [jquery/jquery#3752]
Pleas use passive listeners on all addEventListener:

```
if ( elem.addEventListener ) {
  elem.addEventListener( type, eventHandle );
}
```
```
if ( elem.addEventListener ) {
  elem.addEventListener( type, eventHandle, false );
}
```

### Description ###

npm jquery 3.2.1
node_modules\jquery\dist\jquery.js (line 5062)
node_modules\jquery\dist\jquery.slim.js (line 5062)
node_modules\jquery\src\event.js (line 194)

**Comment by mgol** [comment]
That's not possible as some people do want to call `preventDefault()`.

#2871 tracks adding support for passive event listeners in jQuery 4.0. Unfortunately this requires a significant refactor of our event subsystem so it can't happen before that.
