### ISSUE TITLE
jQuery.ready() calls method named "catch" without quotation

### ISSUE THREAD

**Issue by MaceWindu** [jquery/jquery#3753]
I think `.catch` call should be replaced with `['catch']`.
Now it fails script file parsing in old browsers like IE8 or Safari 5. Even if jquery doesn't support such browsers, it could break application's fallback functionality, delivered in the same file.

**Comment by mgol** [comment]
Lack of support means also lack of support for parsing. If you include jQuery as a separate file, it will not affect other files. If you combine various files into one and you want to support older browsers you need to transpile it down to ES3.
