### ISSUE TITLE
Reserve window.jquery together with window.jQuery & window.$

### ISSUE THREAD

**Issue by PaulMaly** [jquery/jquery#3754]
I know that it's a controversial question, but it'll simplify the definition of this library for different environments and different modules systems.

```
// es6 we use 'jquery'
import $ from 'jquery';

// commonjs we use 'jquery'
const $ = require('jquery');

// amd we use 'jquery'
define(['jquery'], function($) {});

// script tag we use jQuery, why?
(function ($) {

})(jQuery)
```

**Comment by timmywil** [comment]
Thanks for opening an issue, but the first 3 environments you mentioned don't require a global. Globals are case-sensitive, and we don't want to pollute the global namespace more than we have to.
