### ISSUE TITLE
Tests: pathname parsing breaks tests when hosted on URLs that include the string "test"

### ISSUE THREAD

**Issue by jobeland** [jquery/jquery#3756]
As per https://github.com/jquery/jquery/blob/master/test/jquery.js#L5 which is used in _test/index.html_, it tries to load _/test/unit/ready.js_ and _/dist/jquery.min.js_ dynamically, but since it is just splitting on the string _"test"_ in the pathname and grabbing the first instance, hosting on any url where _"test"_ is located earlier (e.g. _mydomain.com/testcontent/jquery/test/index.html_) incorrectly calculates the path to _mydomain.com/test/unit/ready.js_ instead of _mydomain.com/testcontent/jquery/test/unit/ready.js_ for those resource files and breaks the test. 

Would you be open to me submitting a PR for a fix? Just wanting to change the line in question:
`var path = window.location.pathname.split( "test" )[ 0 ],` 
to 
`var path = window.location.pathname.substring(0, window.location.pathname.lastIndexOf("test")),`

**Comment by mgol** [comment]
Thanks for the report.

Sure, PRs are welcome!
-- 
Michał Gołębiowski-Owczarek
