### ISSUE TITLE
jquery not working in node.js

### ISSUE THREAD

**Issue by Wunder-Wulfe** [jquery/jquery#3762]
i installed jquery into node with 
```
npm install jQuery --save
```
and its in my package.json but when i use
```node.js
const $ = require('jQuery');
```
it creates an error:
```
Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
```

**Comment by mgol** [comment]
The package is named `jquery`, not `jQuery`. Package names using capitalized letters are deprecated and the `jQuery` package is deprecated itself. You should have seen the deprecation message during the install process, haven't you?
