### ISSUE TITLE
Standardize keyboard event "key" property

### ISSUE THREAD

**Issue by alexturpin** [jquery/jquery#3764]
### Description ###
According to MDN, [`KeyboardEvent.which` and `KeyboardEvent.keyCode` are both deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent). The recommendation is to use `KeyboardEvent.key` instead. However, `KeyboardEvent.key` has some inconsistencies across browsers. One such example is for the arrow keys: for example the up arrow key shows up as `"ArrowUp"` in modern browsers, but as `Up` in IE9+.

Here is the spec for `KeyboardEvent.key`: https://www.w3.org/TR/uievents-key/

### Link to test case ###
https://jsfiddle.net/c26juan5/1/

Focus in the text box and press any arrow key on your keyboard to observe the value. Result in modern Chrome / Firefox differs from IE9+.

**Comment by timmywil** [comment]
Thanks for opening an issue. However, we're moving away from messing with any properties on event objects unless absolutely necessary. I think the best we can do is get out of the way of properties like `key`. In other words, I think `which` will remain the most consistent until we drop IE9.
