### ISSUE TITLE
Failed at the husky@0.14.3 install script

### ISSUE THREAD

**Issue by abadagada2** [jquery/jquery#3765]
### Link to test case ###

Here is the full output when I run 'npm run build':
> jquery@3.2.2-pre build /home/spikeadmin/jquery
> npm install && grunt

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
 
> husky@0.14.3 install /home/spikeadmin/jquery/node_modules/husky
> node ./bin/install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
 
> husky@0.14.3 uninstall /home/spikeadmin/jquery/node_modules/husky
> node ./bin/uninstall.js

sh: 1: node: not found
npm WARN continuing anyway husky@0.14.3 uninstall: `node ./bin/uninstall.js`
npm WARN continuing anyway Exit status 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN deprecated tough-cookie@1.2.0: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! husky@0.14.3 install: `node ./bin/install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the husky@0.14.3 install script.
npm ERR! This is most likely a problem with the husky package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls husky
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.11.0-parrot6-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/spikeadmin/jquery
npm ERR! node -v v4.8.4
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN optional dep failed, continuing fsevents@1.1.2
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

> commitplease@2.7.10 install /home/spikeadmin/jquery/node_modules/commitplease
> node install

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> commitplease@2.7.10 uninstall /home/spikeadmin/jquery/node_modules/commitplease
> node uninstall

sh: 1: node: not found
npm WARN continuing anyway commitplease@2.7.10 uninstall: `node uninstall`
npm WARN continuing anyway Exit status 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN package.json form-data@0.0.3 No license field.
npm WARN package.json mime@1.2.7 No license field.
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/spikeadmin/jquery/npm-debug.log
npm ERR! not ok code 0

npm ERR! jquery@3.2.2-pre build: `npm install && grunt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jquery@3.2.2-pre build script.
npm ERR! This is most likely a problem with the jquery package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && grunt
npm ERR! You can get their info via:
npm ERR!     npm owner ls jquery
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.11.0-parrot6-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! cwd /home/spikeadmin/jquery
npm ERR! node -v v4.8.4
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/spikeadmin/jquery/npm-debug.log
npm ERR! not ok code 0

**Comment by mgol** [comment]
Node.js 4 has shipped with npm 2. How did you get npm 1 there? I expect a
lot of things to fail with npm 1.

Make sure your environment is correct (with a more modern npm), remove
node_modules & .git/hooks and try "npm install" again.
-- 
Michał Gołębiowski-Owczarek

**Comment by timmywil** [comment]
We can reopen with more info.
