### ISSUE TITLE
$('.overflowedElement').width() return incorrect value

### ISSUE THREAD

**Issue by seeker5084** [jquery/jquery#3770]
I want to get overflowed element's width.
but `$('.overflowedElement').width()` return incorrect value.
[Like this question](https://stackoverflow.com/questions/10277323/get-real-width-of-elements-with-jquery).

Could anyone fix this issue?

**Comment by dmethvin** [comment]
The StackOverflow answers it well. The container is 200 pixels but the content is visually overflowing the page. jQuery is returning the correct value.
