### ISSUE TITLE
Trigger event with jQuery collection, listener gets DOM element and not jQuery collection

### ISSUE THREAD

**Issue by yairEO** [jquery/jquery#3772]
# Question (maybe bug):

## [Demo page](http://jsbin.com/lalenum/edit?html,js,output)

```
$(window).on('foo', function(e, $elm){
  console.log( $elm, $elm instanceof jQuery )
})

$(window).trigger('foo', $('*') )
```

The printed result will not be an instance of *jQuery* but a DOM element (`<html>` in this case).
Why can't the jQuery collection be passed as an argument?

-----

Tested on version `3.1.0`

**Comment by dmethvin** [comment]
Here are the docs: http://api.jquery.com/trigger/

You should be passing an array or plain object. Wrap your jQuery object in an array.
