### ISSUE TITLE
Latest Version does not load on Windows 10

### ISSUE THREAD

**Issue by ArgoPete** [jquery/jquery#3784]
![capture](https://user-images.githubusercontent.com/31938784/30403306-5c97600a-9924-11e7-9449-6e8db466009b.PNG)
Specifically line 3887 of jquery-3.2.1.js has an error on line 3887
Char 4
Error Expected identifier
code 800A03F2
Microsoft JScript Compilation error
		// registration.
		.catch( function( error ) {
			jQuery.readyException( error );
		} );
apparently .catch is an invalid method. I am new to JQuery and cannot find it in a manual

**Comment by dmethvin** [comment]
jQuery works just fine on Windows 10, From the error message I think you are trying to run a JavaScript file on Windows 10 as a command line script using WScript or via a file association. You cannot do that. Try asking for help on StackOverflow.
