### ISSUE TITLE
Is http://code.jquery.com down?

### ISSUE THREAD

**Issue by yanyu0517** [jquery/jquery#3785]
I can't load js from http://code.jquery.com. And I found the jquery.com also can't load js from code.jquery.com

![image](https://user-images.githubusercontent.com/5326851/30490810-b51e444c-9a6d-11e7-9fc6-f1d76004f695.png)

**Comment by mgol** [comment]
Where do you live? I've tried that from Poland and it works correctly for me.

**Comment by yanyu0517** [comment]
China Mainland.
Can you try again after clear the browser cache?

**Comment by mgol** [comment]
@aulvi @gnarf does any of you know what should be done in response to reports like that? I think you've dealt with a few of them in the past.

**Comment by mgol** [comment]
@yanyu0517 it works fine for me regardless of the browser cache. The problem must be isolated to your location or config. Can you try in another browser?

**Comment by gnarf** [comment]
I just cc'ed MaxCDN support on this one.  Not sure how to follow up/test this.

**Comment by 76creates** [comment]
We have tested this and found no issues on multiple location/ISP in China with an exempt of Hangzhou/Telecom where I got DNS failure, we cannot affect this one tho. Can we get additional info @yanyu0517 like what city/ISP you make requests from, if on Linux/Mac run `dig +short code.jquery.com` and `curl -I code.jquery.com`? Dusan MaxCDN

**Comment by dmethvin** [comment]
If this was really common I have to think we would have gotten a lot more reports by now. Your ISP or country must be blocking it either intentionally or through misconfiguration. As a workaround you can host jQuery on your own server.
