### ISSUE TITLE
JQuery 3.2.1 issue in "deferred" method

### ISSUE THREAD

**Issue by Solotov** [jquery/jquery#3787]
### Description ###
I detected a problem in **JQuery 3.2.1** in the function "`deffered`" in 3 minute freeze my web page,
in Chrome[ _version 61.0.3163.79 (Build oficial) (64 bits)_ ] 
and Firefox [ _version 55.0.3 (64-bit)_].

### File: jquery-3.2.1.js  line: 3695

```javascript
window.setTimeout(process); 
```
For my case,i solved(temporarily) this issue,adding 90 ms to delay parameter :
```javascript
window.setTimeout(process,90);
```
 
### Exceptions stack:  in **Chrome**

- [Violation] 'setTimeout' handler took 170ms
- [Violation] 'setTimeout' handler took 170ms
- 18:07:02.938 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 57ms
- 18:07:03.478 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 60ms
- 18:07:03.848 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 55ms
- 18:07:25.004 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 50ms
- 18:07:28.807 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 67ms
- 18:07:29.170 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 50ms
- 18:07:29.738 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 58ms
- 18:07:30.210 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 80ms
- 18:07:32.026 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 75ms
- 18:07:34.375 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 56ms
- 18:07:36.880 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 58ms
- 18:07:37.401 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 73ms
- 18:07:37.888 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 60ms
- 18:07:38.400 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 62ms
- 18:07:38.898 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 61ms
- 18:07:40.384 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 78ms
- 18:07:40.752 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 68ms
- 18:07:41.366 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 86ms
- 18:07:41.811 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 64ms
- 18:07:43.318 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 64ms
- 18:07:43.738 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 99ms
- 18:07:44.322 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 85ms
- 18:07:44.806 jquery-3.2.1.js:3655 [Violation] 'setTimeout' handler took 74ms
- ...

> sorry for my ugly english

**Comment by mgol** [comment]
We can't do anything if we don't have a test case. There are millions of reasons why this problem may occur and many of them would be cause by code external to jQuery.

Can you provide a test case?

**Comment by Solotov** [comment]
you're right, this issue comes from another component [datatable.net](https://datatables.net/)
I'm still looking how to fix it. 

thanks
