### ISSUE TITLE
$(window).height() sent wrong value

### ISSUE THREAD

**Issue by amirhoseinBK** [jquery/jquery#3788]
### Description ###
i used of $(window).height() for found my page height and resize my tables width and height 
 but when page smaller then 400px this metod sent a big confused wrong number 

this problem happen in Chrome and Firefox but does not happen in IE

finally i used of   window.innerHeight() and problem solved

### Link to test case ###
[html.txt](https://github.com/jquery/jquery/files/1309265/html.txt)

**Comment by mgol** [comment]
Can you provide a test case on https://jsfiddle.net/ or https://jsbin.com/?

**Comment by amirhoseinBK** [comment]
https://jsbin.com/bediqimene/1/edit?output

test this code in PC and resize your browser

**Comment by timmywil** [comment]
There's a lot going on in that example. I've reduced the test case to just `$(window).height()`, and it seems to work fine.
