### ISSUE TITLE
Password validation expression in jquery

### ISSUE THREAD

**Issue by DhanasekaranGit** [jquery/jquery#3789]
### Description ###
I have used the latest jquery version 1.4.5.
But i'll check the password regular expression in my website.

**Password mandatory is:**
Password must be 8 char,It must be combination of uppercase,lowercase,alphanumeric special characters.

Give me the password validation check expressions .

**Comment by dmethvin** [comment]
This is not related to jQuery core. Perhaps you could ask for help on StackOverflow?
