### ISSUE TITLE
Remove package-lock.json?

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#3792]
### Description ###
npm 5, even the version included in the latest Node.js 8.5.0 re-generates `package-lock.json` on each install. And when it does on a system that doesn't support all the optional dependencies that are supported on the OS where the lockfile was generated, it removes those optional deps from the lockfile.

The effect is that everyone firing `npm install` on our repo on any OS other than macOS will immediately get a dirty state of the repo as the `fsevents` dependency subtree gets removed from `package-lock.json`. That's a really bad experience.

**Comment by timmywil** [comment]
hmm, it shouldn't regenerate the lockfile. Otherwise, what's the point of a lockfile. Has this been reported to npm?

**Comment by mgol** [comment]
It seems to be https://github.com/npm/npm/issues/18135, open since August 10. No feedback from the npm team so far.

**Comment by dmethvin** [comment]
Interesting that `yarn` does install everything and has an opposite problem: https://github.com/yarnpkg/yarn/issues/4190
