### ISSUE TITLE
jQuery 3.0 ie8?

### ISSUE THREAD

**Issue by a51764579** [jquery/jquery#3793]
Hi, 
   Can   jQuery 3.0  support ie8? If jQuery3.0 can support ie8,how can do I?

**Comment by nebrot** [comment]
jQuery 3: Internet Explorer: 9+
See browser support here http://jquery.com/browser-support/

**Comment by a51764579** [comment]
@nebrot 
             Has the way to support ie8 dependency jQuery3.0?

**Comment by nebrot** [comment]
If you need to support such old browsers like IE 8, use [jQuery 1.12](https://code.jquery.com/jquery/#jquery-all-1.x).

**Comment by mgol** [comment]
No, there's no way to make jQuery 3.0 & newer work on IE 8. As https://jquery.com/browser-support/ says:
> If you need to support older browsers like Internet Explorer 6-8, Opera 12.1x or Safari 5.1+, use <a href="https://code.jquery.com/jquery/#jquery-all-1.x">jQuery 1.12</a>.
