### ISSUE TITLE
jquery3.1.0 new bug about $.ajax

### ISSUE THREAD

**Issue by longzhou0508** [jquery/jquery#3795]
### Description ###
3.1.0 版本，当发送ajax请求，字段中如果含有 "??" 提交的时候会出现？？被 jquery版本信息代替

**Comment by dmethvin** [comment]
No URL submitted to `jQuery.ajax` should contain `??` because the fields should be URL-encoded via `URIEncodeComponent` or similar. If you are encoding the URL and still seeing this then please submit a test case as requested in the issue template.
