### ISSUE TITLE
Uploaded Documents :: Issues in Viewing document

### ISSUE THREAD

**Issue by Dhanasekaranjones** [jquery/jquery#3796]
I have upload the one document or image

 Click to view the uploaded document. It will display the document in Document Preview popup.

**Right click and click to open image in the new tab** and throw the error message for 

```
Error as 404 - File or directory not found in new tab. (Image: Error In New Tab)
```
After this, click to save image as option. File not properly downloaded. (Images: File Not Proper 1 & File Not Proper 2)

Need to display image properly in new tab and need to save file properly.

Note: If we save image before open it in new tab, then it is working fine.

**Note: Right click the image to open when throw the error message.**

**Comment by dmethvin** [comment]
This is not a jQuery bug report.

**Comment by Dhanasekaranjones** [comment]
Oh! Then how to solve the bug.

Any idea?

**Comment by dmethvin** [comment]
No, this is not a support forum. Please ask on StackOverflow or somewhere else.
