### ISSUE TITLE
Password regex javascript 

### ISSUE THREAD

**Issue by Dhanasekaranjones** [jquery/jquery#3797]
What is the password regex javascript for,

The password must be of minimum length 8 characters and one uppercase and one lowercase and one special characters and one alphanumeric values.

```
Note: The password must be of minimum length 8 characters and 1 uppercase and 1 lowercase and 1 special characters and 1 alphanumeric values.
```

Pls given the password regex code.

**Comment by dmethvin** [comment]
Do not open any more tickets in jQuery repos. Ask for help on StackOverflow.
