### ISSUE TITLE
Infinite loop with MutationObserver, select and option:checked

### ISSUE THREAD

**Issue by Taeon** [jquery/jquery#3799]
### Description ###

I set up an MutationObserver on a select element, which calls a listener function. Within the listener function is a call to jQuery (to check for selected options).

If the listener function is called immediately after the MutationObserver is set up, jQuery gets stuck in an infinite loop. Obviously this should not happen.

I've tried replacing jQuery with Zepto, and the infinite loop does not occur.

Tested on Windows Chrome (60.0.3112.113) and Firefox (55.0.3)

### Link to test case ###

I've set this reduced test case up to abort after 100 iterations, to avoid crashing the browser (you should see an alert).

https://jsfiddle.net/rcf1a71b/

**Comment by dmethvin** [comment]
Current DOM APIs do not provide any way to do a correctly rooted query from an arbitrary element. That is, `root.querySelectorAll(selector)` doesn't always return the expected results vs. `jQuery(root).find(selector)`. For example, if there is a `div` ancestor *above* the root element the expression `root.querySelectorAll("div p")` always returns all `p` elements below the root! jQuery only returns `p` elements below a `div` in the root.

To work around this problem, jQuery temporarily adds an `id` attribute at the root and that is what triggers the mutation observer. If there is already an `id` on the root element jQuery will use that. So you should either add an `id` to the select or avoid using `jQuery.fn.find`.

**Comment by Taeon** [comment]
Yep OK, that would explain it.

I worked around it by temporarily disconnecting the observer before calling find(), then calling observe() again. Using an ID wouldn't really be appropriate here, so I think that's probably the best solution for my case, short of manually enumerating the children of the select and looking at each one's :checked status.

**Comment by mgol** [comment]
@Taeon I just landed a PR that achieves what we need via different means for most selectors: #4454. This will land in jQuery 4.0.0 and maybe we can do it in 3.4.2 as well.
