### ISSUE TITLE
Condition not working properly

### ISSUE THREAD

**Issue by Dhanasekaranjones** [jquery/jquery#3800]
I have used the jquery to check the if condition for my application

my code:
```
if($("#...").val() <= 0){

}
```
Thus the purpose of the condition input field value doesn't allow the zero values.

I have give the value for 0 to show the alert for **zero not allowed**.

But i have change the input value for 0 to 10.

Then show the same alert for zero not allowed.

pls give the example of if condition code.

**Comment by dmethvin** [comment]
This is not a help forum, please try StackOverflow.
