### ISSUE TITLE
Non-passive even listener violation

### ISSUE THREAD

**Issue by neutralboy** [jquery/jquery#3804]
[Here's the link to the picture on how it looks](https://i.imgur.com/7Djcxy7.png)

Im using Jquery with UIkit and it threw me this error when I used a side nav.
It also throws a google chrome error to [this link.](https://www.chromestatus.com/feature/5745543795965952)

**Comment by mgol** [comment]
jQuery doesn't support passive event listeners yet; this is planned for 4.0 and tracked in #2871. I'm closing it as a duplicate.
