### ISSUE TITLE
A missing closing square bracket in attribute selector doesn't throw error in all browsers except Safari

### ISSUE THREAD

**Issue by sakshamsaxena** [jquery/jquery#3806]
### Description ###
My concern, when googled up, returned this StackOverflow question which hasn't gained attention. I'm going through the EXACT same problem. 

For example, ```$("input[name='email'")``` works FINE in ALL browsers except Safari which politely throws and error and reminds you of your silly mistake. Should this not be thrown in ALL the browsers? Why does this work ?

### Link to test case ###

[https://stackoverflow.com/questions/45108076/](https://stackoverflow.com/questions/45108076/)

**Comment by dmethvin** [comment]
I've posted the answer in that SO thread. The only way we could throw an error in every browser would be to fully parse every selector in JavaScript, that isn't going to happen for performance reasons. 
https://bugs.jquery.com/ticket/15199
