### ISSUE TITLE
IE/Edge - Submitting a form using jQuery's .submit() causes the submit handler on other forms to detach when using beforeunload

### ISSUE THREAD

**Issue by Antimony51** [jquery/jquery#3809]
### Description ###
In the below examples I have two forms. The first form, Foo, is submitted through js by a button outside the form. The second form, Bar, is submitted by a submit button within the form. Bar also has an event handler on the submit event, this handler will disable the beforeunload confirmation dialog so that Bar can be submitted without asking the user to confirm. When you submit Foo, the confirmation dialog displays and you can choose to stay on the page. The page should remain unaffected as if the button was never pressed. This works fine in pure js, but when using jQuery in IE or Edge choosing to stay on the current page causes the onsubmit handler of Bar to become detached somehow, so it doesn't run when Bar gets submitted. In this case that just means that the user gets another annoying dialog, but it can cause more severe problems if there is some processing that needs to happen in that handler before the form is submitted.

I've worked around this in my own code by just calling submit on the raw form element. It can also be solved by attaching the event handler using pure js, or using pure js entirely.

### Tested on: ###
IE 11.540.15063.0 (fail)
Edge 40.15063.0.0 (fail)
Firefox 55.0.3 (pass)
Chrome 61.0.3163.100 (pass)

All tests were run on Win10

### Link to test cases ###
[jQuery](https://jsfiddle.net/Antimony51/du8bzr6x/)
[Native](https://jsfiddle.net/Antimony51/nwvp8cog/)

To reproduce the issue:
1. Submit Foo
2. Click "Stay on current page"
3. Submit Bar

Pass when:
The form just submits

Fail when:
The confirmation dialog shows

**Comment by gibson042** [comment]
If you check the console, you'll see Edge generate exceptions in both versions. jQuery can't be expected to resolve that.
