### ISSUE TITLE
New element creation from raw HTML string not working as expected

### ISSUE THREAD

**Issue by ArturBaybulatov** [jquery/jquery#3810]
### Description ###

Example (run in console):

```javascript
$.fn.jquery
// => "3.2.2-pre 90bac40a5123038c94a6fd8c1fde7fbe758b08c7"

$('<button>', {text: 'Hello', attr: {disabled: true}}).prop('outerHTML')
// => "<button disabled="disabled">Hello</button>" // <------------- OK

$('<button disabled>', {text: 'Hello'}).prop('outerHTML')
// => "<button disabled=""></button>" // <------------- Expected to have the text
```

Link to documentation: https://api.jquery.com/jQuery/#jQuery-html-attributes

### Link to test case ###

https://jsbin.com/qowikagene/1/edit?html,js,console

**Comment by mgol** [comment]
Why would you expect the attribute to have a non-empty value when you set it that way yourself? I see no jQuery issue here.

**Comment by ArturBaybulatov** [comment]
No, I don't expect the `disabled` attribute to have a text, I expect the button to have a text (caption)

**Comment by mgol** [comment]
Ah, I see, I misread, sorry.

**Comment by mgol** [comment]
From the API page you linked to:
> **Important:** If the second argument is passed, the HTML string in the first argument must represent a simple element with no attributes.

So this seems to be documented. I'm not sure what's the reason for this restriction, though, any ideas, team?

@ArturBaybulatov note that the docs explicitly discourage using this pattern:
> While the second argument is convenient, its flexibility can lead to unintended consequences (e.g. `$( "<input>", {size: "4"} )` calling the `.size()` method instead of setting the size attribute).

You'd be better off using the `text` method explicitly which always works:
```js
$('<button disabled>').text('Hello')
```

**Comment by dmethvin** [comment]
It's just the way the "logic" worked when this feature was put in long ago. If the code fell into the simple `createElement` path (just a tag with nothing else) it looked at the second argument for a list of attributes. Otherwise the second argument is an element creation context. The documentation tries to warn people away from this method signature entirely as you noticed, don't use it.

**Comment by mgol** [comment]
Ah, right, it's a clash with the `jQuery( html [, ownerDocument ] )` signature.
