### ISSUE TITLE
$.ajax interprets webserver error-document as valid javascript

### ISSUE THREAD

**Issue by EelcoV** [jquery/jquery#3811]
When $.ajax is called with dataType 'script', then the received document is always interpreted as javascript, even when it actually is a 404-error document.
Expected behavior: evaluate the received document only when the webserver returns 200-OK.

Small example:
```
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $.ajax({
        url: 'doesnotexist.js',
        dataType: 'script'
    });
</script>
</head>
<body></body>
</html>
```
In Firefox this shows a message in the console 

> SyntaxError: expected expression, got '<'

as it tries to execute the HTML document received from the webserver.
Expected behavior is that the $.ajax call above is functionally equivalent to
> <script src="doesnotexist.js"></script>
meaning that non-existing resources on the webserver should give an error message in the console log, but not syntax errors.

**Comment by dmethvin** [comment]
The `dataType` says, "I don't care what the server returns as a `Content-type` header, it is this data type and jQuery should interpret it that way." If the server returns different types as it does in this case and you don't trust the server's content type, you can call it `"text"` and manually inspect or decode it when the request is complete.
