### ISSUE TITLE
Using SlideUp on a page's inner element makes the whole page scroll instead

### ISSUE THREAD

**Issue by TechnoGilles** [jquery/jquery#3812]
### Description ###

In the test case provided below, you can see that upon arriving on the page, the items in the green column are regularly sliding up. To be precise, the topmost item is being slideUp, making all items underneath slide up as well. The topmost item is then moved down the green column where it re-appears. In this case, everything looks good.

But as soon as you start scrolling down the "page", to see more items of the yellow column or to read the text in the red column, you see that now every time a green item slides up, the whole page slides up as well. So in effect, you see that the yellow and red column look like they are going back up until they reach the top of page, at which point the green column resumes the intended motion.

### Link to test case ###

https://jsfiddle.net/107rzrdo/7/

**Comment by timmywil** [comment]
I might not be understanding correctly, but if you're concern is that the elements below move up when the element's height is reduced, that's completely normal and just how layout works. However, could you reduce the test case? It's a bit large. A smaller test case would help us understand the issue. Thanks.

**Comment by TechnoGilles** [comment]
Just to be sure : the bug is seen only on Chrome.
The problem occurs when you scroll down the page at which point the green column stops moving and the page scrolls back up.
Gilles

      De : Timmy Willison <notifications@github.com>
 À : jquery/jquery <jquery@noreply.github.com> 
Cc : TechnoGilles <GillesJrBissonComm@yahoo.ca>; Author <author@noreply.github.com>
 Envoyé le : lundi 16 octobre 2017 12h11
 Objet : Re: [jquery/jquery] Using SlideUp on a page's inner element makes the whole page scroll instead (#3812)
   
I might not be understanding correctly, but if you're concern is that the elements below move up when the element's height is reduced, that's completely normal and just how layout works. However, could you reduce the test case? It's a bit large. A smaller test case would help us understand the issue. Thanks.—

**Comment by TechnoGilles** [comment]
Repro steps:

1) Use Chrome to visit the link : https://jsfiddle.net/107rzrdo/7/
2) When you arrive on the page, see how the green items are cycling up properly (this is the intended behavior)
3) Scroll down the page to bring Item F or G near the top
4) Notice now that the green column has stopped and instead, the whole page is scrolling back up. This is the problem.

**Comment by gibson042** [comment]
The behavior about which you are complaining is coming from Chrome, not jQuery: https://jsfiddle.net/107rzrdo/8/

It seems to be related to scroll anchoring. You can probably simplify down to a single operation and submit an issue at [bugs.chromium.org](https://bugs.chromium.org/p/chromium/issues/list), but there doesn't seem to be anything for us to do.

**Comment by TechnoGilles** [comment]
Thanks for your time and inputs. I will continue investigating and see if I can pin-point the exact problem.

**Comment by TechnoGilles** [comment]
As a conclusion : the problem was indeed caused by scroll anchoring. And the CSS style overflow-anchor: none; applied to my first column in my example solves the issue.
