### ISSUE TITLE
attr("rowspan") should return a number

### ISSUE THREAD

**Issue by xiaodun** [jquery/jquery#3813]
Hello,I have a suggestion,should return a number  When attribute values can be converted to numeric values,sush as rowspan...

**Comment by dmethvin** [comment]
The DOM returns attribute values as [strings that must represent integers](https://w3c.github.io/html/tabular-data.html#attributes-common-to-td-and-th-elements). I don't think we want to get into the business of trying to determine whether specific attributes are proper numbers and converting them. We have done similar things in the past (for example,. `.data()`) and regretted it.
