### ISSUE TITLE
Parsing HTML with `tr` with `table` child throws error

### ISSUE THREAD

**Issue by biziclop** [jquery/jquery#3823]
### Description ###
`$.parseHTML('<tr><table></table></tr>');` throws exception instead of properly parsing the unusual HTML string. The documentation also doesn't seem to mention usage of 'impure' HTML.

  *  What do you expect to happen?
The HTML string properly parsed OR null returned OR proper console message OR proper description in the docs.
  *  What actually happens?
Exception is thrown.
  *  Which browsers are affected?
Mac Firefox 56.0 (64-bit)
Mac Safari Version 11.0 (11604.1.38.1.7)
  *  Which jQuery versions are affected?
jQuery 1 - jsfiddle's latest jQuery JavaScript Library v3.2.2-pre 50e3395e7e25d3286ed3daa17ee5ae4d862b0602

### Link to test case ###

https://jsfiddle.net/7511qv7v/

**Comment by gibson042** [comment]
I'm strongly disinclined to work around this native behavior. Would you be willing to submit a documentation pull request at https://github.com/jquery/api.jquery.com ?
