### ISSUE TITLE
Error installing jquery on mac via terminal

### ISSUE THREAD

**Issue by marcomorettim** [jquery/jquery#3832]
Marcos-MacBook-Pro:~ marcomoretti$ npm install jquery
marcomoretti@1.0.0 /Users/marcomoretti
├── jquery@3.2.1 
└── UNMET PEER DEPENDENCY popper.js@^1.12.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: graceful-fs@^4.1.2 (node_modules/less/node_modules/graceful-fs):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EACCES: permission denied, mkdir '/Users/marcomoretti/.npm/graceful-fs/4.1.11'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mkdirp@^0.5.0 (node_modules/less/node_modules/mkdirp):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EACCES: permission denied, mkdir '/Users/marcomoretti/.npm/mkdirp/0.5.1'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mime@^1.2.11 (node_modules/less/node_modules/mime):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EACCES: permission denied, mkdir '/Users/marcomoretti/.npm/mime/1.4.1'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request@2.81.0 (node_modules/less/node_modules/request):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EACCES: permission denied, mkdir '/Users/marcomoretti/.npm/request/2.81.0'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: source-map@^0.5.3 (node_modules/less/node_modules/source-map):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EACCES: permission denied, mkdir '/Users/marcomoretti/.npm/source-map/0.5.7'
npm WARN bootstrap@4.0.0-beta.2 requires a peer of popper.js@^1.12.3 but none was installed.
npm WARN marcomoretti@1.0.0 No description
npm WARN marcomoretti@1.0.0 No repository field.

**Comment by mgol** [comment]
This is unrelated to jQuery, other packages are causing these errors. The `jquery` package doesn't have any dependencies or peerDependencies.
