### ISSUE TITLE
add the "main" key in the file .bower.json

### ISSUE THREAD

**Issue by AlexanderKositsyn** [jquery/jquery#3833]
### Description ###
I noticed that performing command for bower-wiredep plugin nothing happen in html file. So I entered in .bower.json and fixed it like in the picture below:

![bower json - about_page - visual studio code 2017-11-01 13 35 00](https://user-images.githubusercontent.com/28633471/32271471-12730738-bf0b-11e7-9d41-c9c7ce0f9529.png)

Can you please fix it.

**Comment by mgol** [comment]
This entry is already there: https://github.com/jquery/jquery-dist/blob/3.2.1/bower.json#L3

`jquery-dist` is the repo via which we publish to npm & bower, not this one.
