### ISSUE TITLE
replaceWith method bug on fall creator update Edge browser

### ISSUE THREAD

**Issue by EFSYS** [jquery/jquery#3834]
Hello all,

Using EDGE (16.16299, fall creators update) and this html page the global javascript code is executed two times when dynamically adding javascript, but working fine on HTML.

[HtmlPage1.zip](https://github.com/jquery/jquery/files/1434176/HtmlPage1.zip)

Thanks, 

Stéphane

**Comment by timmywil** [comment]
Thanks for opening an issue. However, please create a test case on https://jsfiddle.net or https://jsbin.com, which is much more convenient for debugging.

**Comment by EFSYS** [comment]
Here is a test case:

   https://jsfiddle.net/ft3sw6us/

**Comment by timmywil** [comment]
This might need to be fixed in Edge. I'd like to dig further and make sure it's not taking a different code path than other browsers.

**Comment by gibson042** [comment]
Confirmed that it is not a jQuery issue—Edge ignores [SVG script content type](https://www.w3.org/TR/SVG11/script.html#ScriptElementTypeAttribute) and evaluates everything as ECMAScript, breaking the [mechanism](https://github.com/jquery/jquery/blob/731c501155ef139f53029c0e58409b80f0af3a0c/src/manipulation.js#L62) we use to suppress early evaluation: https://jsfiddle.net/ft3sw6us/1/

Edge bug report: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14762816/

**Comment by EFSYS** [comment]
Thank you for investigating!
