### ISSUE TITLE
mouse wheel  event  e.originalEvent.offsetY bug

### ISSUE THREAD

**Issue by JasonCSharpCoder** [jquery/jquery#3835]
### Description ###
Hi, when I use 
` $('.scheduleOpertion').bind('mousewheel', function(e){
            var wheelScrollheight = e.originalEvent.offsetY;
}` 
I find that the mouse wheel scroll down , the value has been set , but scroll up neither, is that a bug?

**Comment by mgol** [comment]
Please create a test case on jsFiddle or JSBin that will show the issue.

**Comment by JasonCSharpCoder** [comment]
hi, when i use lasted version jQuery, this is not happened
