### ISSUE TITLE
tooltip doesn't work when assigned in a function

### ISSUE THREAD

**Issue by Rc85** [jquery/jquery#3837]
Not sure if this is a bootstrap issue or jquery issue.

I have a function that creates some divs that appends inputs. Example

    function createStuff () {
        $('<div>').append(
            $('<input>').addClass('form-control').attr({'data-toggle': 'tooltip', 'title': 'this is a title', 'type': 'text'})
        )
    }

This is placed in a js called functions.js and in my body.js I have

    $(document).ready(function() {
        $('[data-toggle="tooltip"]').tooltip({
            trigger: 'hover'
        })
        createStuff();
    });

In my HTML head, I have

    <script src='/js/functions.js'></script>
    <script src='/js/body.js'></script>

The title is showing as normal title, bootstrap tooltip is not showing. I've tried moving the tooltip initializer to the very top of functions.js and wrapped in in a $(document).ready, still nothing.

**Comment by Johann-S** [comment]
You're on jQuery's Github, not Bootstrap's Github please open an issue here : https://github.com/twbs/bootstrap

**Comment by mgol** [comment]
Not a jQuery issue, closing.
