### ISSUE TITLE
AJAX Post network errors not returned

### ISSUE THREAD

**Issue by obermillerk** [jquery/jquery#3839]
### Description ###
Using ajax to post does not propagate network errors to callback.
This can be replicated by using the following code:
```
$.ajax('<some bad url that won't resolve>', {
    method: 'POST',
    error: (jqXHR, status, err) => alert('Error: ' + err.toString())
});
```
This results in a blank error (empty string).  I see the same behavior when there is no internet connection, post fails but I get no error back (empty string).  These errors appear in the console but I can't do anything with the error myself.

I'm using chrome.

**Comment by dmethvin** [comment]
Can you create a jsfiddle that shows what a bare XHR does?

**Comment by dmethvin** [comment]
an example not using jQuery. Does it do the same thing?

**Comment by obermillerk** [comment]
https://jsfiddle.net/ewtny24a/

I'm seeing the same behavior here, so I guess that the issue is not actually with the jQuery library but the underlying XHR.  I tried looking at the error event also but it doesn't provide the error either, so it seems that this problem is unsolvable alas...
