### ISSUE TITLE
Wrong link description for type definitions

### ISSUE THREAD

**Issue by pavilion** [jquery/jquery#3845]
### Description ###
When you add type definitions to VSCode and you want to call a jQuery method, the link description that redirects you to the official jQuery website is wrong. 

### Link to test case ###
![image](https://user-images.githubusercontent.com/3165436/32817140-26f88f30-c9b4-11e7-8bf6-2c940466cbe5.png)

Notice the "}" at the end of @link

**Comment by mgol** [comment]
We don't maintain the TypeScript definition file, that's done in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jquery. You should report any issues to that repo or to VS Code, depending on where is the bug.
