### ISSUE TITLE
Importing jquery to electron applications

### ISSUE THREAD

**Issue by arjunchanduvely** [jquery/jquery#3846]
I tried to import jquery in my electron application like usual
<script src="foreign_modules/jquery.js"></script>

But nothing happened, therefore I searched online and found a solution in stackoverflow

Add the below script at the beginning, before importing jquery. 

<script>if (typeof module === 'object') {window.module = module; module = undefined;}</script><script src="foreign_modules/jquery.js"></script>

**Comment by mgol** [comment]
Use `require` to import jQuery in Electron. See #2686 & #2688 for more details.
