### ISSUE TITLE
[Suggestion] rename isArraylike function or add a comment in it

### ISSUE THREAD

**Issue by Akiq2016** [jquery/jquery#3850]
### Description ###
Hi, when I read [core.js](https://github.com/jquery/jquery/blob/master/src/core.js) yesterday, I was confused because `map` used `isArrayLike`, but it was not a real `isArrayLike` function, this was only used for checking `if it is object or dense array`, but not `if it is an array like`. I also find duplicate issues reported bugs like 
```
Uncaught TypeError: Cannot use 'in' operator to search for '' in ‘’
```
And yeah I find out the owner replied, saying it was clear in the document that the type passed in should be array or object. So that was users fault that did not read the document, but it is still unreasonable for you to use the name of `isArrayLike`. 

Would you add a comment to the function or rename this function?

**Comment by timmywil** [comment]
`isArrayLike` determines if an object can be treated as an array. How it determines that across browsers can be tricky and confusing sometimes. However, the purpose aligns with its name. Also, it is an internal/private function so as long as you understand `map` and what can be passed, I think we're good.
