### ISSUE TITLE
Errors in FF 57 Quantum 

### ISSUE THREAD

**Issue by stvowi** [jquery/jquery#3853]
I get in the web console following messages after loading of JQuery v3.2.1:

- SyntaxError: test for equality (==) mistyped as assignment (=)? [Weitere Informationen] jquery3.js:8070:5
- ReferenceError: reference to undefined property "delegateType" [Weitere Informationen] jquery3.js:5035:4
- ReferenceError: reference to undefined property "nodeType" [Weitere Informationen] jquery3.js:4023:2
- SyntaxError: test for equality (==) mistyped as assignment (=)? [Weitere Informationen] jquery3.js:8070:5
- ReferenceError: reference to undefined property "delegateType" [Weitere Informationen] jquery3.js:5035:4
- ReferenceError: reference to undefined property "focusout" [Weitere Informationen] jquery3.js:4094:52
- ReferenceError: reference to undefined property "nodeType" [Weitere Informationen] jquery3.js:4023:2
- ReferenceError: reference to undefined property "triggered" [Weitere Informationen] jquery3.js:5013:12
- ReferenceError: reference to undefined property "offsetTop" [Weitere Informationen] jquery3.js:4291:9
- ReferenceError: reference to undefined property "triggered" [Weitere Informationen] jquery3.js:8128:1
- ReferenceError: reference to undefined property "result" [Weitere Informationen] jquery3.js:5223:3
- ReferenceError: reference to undefined property "type" [Weitere Informationen] jquery3.js:7934:5
- ReferenceError: reference to undefined property "uniqueID" [Weitere Informationen] jquery3.js:2286:7
- ReferenceError: reference to undefined property "traditional" [Weitere Informationen] jquery3.js:9040:4
- ReferenceError: reference to undefined property "username" [Weitere Informationen] jquery3.js:9459:1
- ReferenceError: reference to undefined property 0 [Weitere Informationen] jquery3.js:8623:10
- ReferenceError: reference to undefined property 200 [Weitere Informationen] jquery3.js:8977:8
- ReferenceError: reference to undefined property "altKey" [Weitere Informationen] jquery3.js:5297:8
- ReferenceError: reference to undefined property "start"[Weitere Informationen] jquery3.js:7141:1
- ReferenceError: reference to undefined property "disabled"[Weitere Informationen] jquery3.js:5250:32

**Comment by dmethvin** [comment]
How could we possibly debug this with no test case and just a copy/paste of information from the Firefox console? I'll close this but please do create a new issue after following the instructions in the issue template.

**Comment by stvowi** [comment]
P.S.: It's only in the Firefox Quantum for Ubuntu - Firefox for Windows say nothing
--

**Comment by stvowi** [comment]
It's maybe a browser bug or option. Thanks for the answer.
