### ISSUE TITLE
Jquery Multi Select Issue

### ISSUE THREAD

**Issue by Divya-Aggaarwal** [jquery/jquery#3859]
Hi,
I need to use jQuery-Plugin-For-Multi-Select-List-with-Checkboxes-MultiSelect but my application is on IE 8 and this plugin is not supporting IE8. Please help.

Below is the code snippet
@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE html>
<html>
<head>

    @*<link href="css/jquery.multiselect.css" rel="stylesheet" type="text/css">*@
    <link href="~/Content/jquery.multiselect.css" rel="stylesheet" />
</head>

<body>

    <h2>A demo of using multi-select with checkboxes</h2>
    <select name="multicheckbox[]" multiple="multiple" class="4colactive">
        <option value="AK">Alaska</option>
        <option value="WY">Wyoming</option>
    </select>

    <script src="~/Scripts/jquery-1.7.2.min.js"></script>
    <script src="~/Scripts/jquery.multiselect.js"></script>
    <script>
$('select[multiple]').multiselect({
    columns: 1,
    placeholder: 'Select options'
});
    </script>
</body>
</html>

Thanks,
Divya
[jQuery-Plugin-For-Multi-Select-List-with-Checkboxes-MultiSelect.zip](https://github.com/jquery/jquery/files/1499163/jQuery-Plugin-For-Multi-Select-List-with-Checkboxes-MultiSelect.zip)

**Comment by mgol** [comment]
This is a jQuery repository, not jQuery Multiselect repository. You should report all issues about the plugin to the plugin authors.

Also, jQuery no longer supports IE 8 in version 3.x and we no longer provide support for older versions.
