### ISSUE TITLE
Edge 16 fails "attributes" test (flaky)

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#3867]
_See also https://github.com/jquery/jquery/issues/3866_

-------

Since we started testing in Edge 16, the "attributes" often fails, but not always.

First seen in <http://swarm.jquery.org/job/6327> (18 Oct 2017)

<img width="997" alt="screen shot 2017-11-28 at 10 57 18" src="https://user-images.githubusercontent.com/156867/33338423-ebe3a25a-d42a-11e7-963b-0051847e716d.png">

Still there in <http://swarm.jquery.org/result/2531185> (today)

<img width="900" alt="screen shot 2017-11-28 at 10 58 00" src="https://user-images.githubusercontent.com/156867/33338466-05aa9dba-d42b-11e7-8d8f-8022280f64e7.png">

**Comment by markelog** [comment]
Progress update.

Set up the Edge local, seeing the failures, will investigate further
