### ISSUE TITLE
DOM inserted scripts should support script type module

### ISSUE THREAD

**Issue by tbepdb** [jquery/jquery#3871]
### Description ###
I'm using JQuery version 3.2.1 in Chromium 62+  and I'm trying to use es6 native modules.
When i use code like that
```
$('selector').html('<script type="module" scr="PATH/file.js"></script>')
```
jquery has not execute that script.

### Link to test case ###
[test case](https://plnkr.co/edit/3zyk4CenvlTFbPh9Qx2x?p=preview)

**Comment by timmywil** [comment]
Thank you for opening an issue! We agree this is an issue worth addressing, but we need a test case that will actually pass once we do address it.

**Comment by tbepdb** [comment]
Excuse me i don't have expirience with "plunker" service. I forgot "freeze" test case

**Comment by gibson042** [comment]
https://jsbin.com/guburotala/edit?html,js,console,output
