### ISSUE TITLE
jQuery.param improvement

### ISSUE THREAD

**Issue by rbrundritt** [jquery/jquery#3880]
Using the[ jQuery.param function](https://github.com/jquery/jquery/blob/a6b0705294d336ae2f63f7276de0da1195495363/src/serialize.js) with some libraries I've noticed that it can throw errors if the input object has functions which expect input values. For example, lets say a library extends the string class and adds the following prototype to the string class in an application:

String.prototype.hasCharacter = function(char){
        if(!char){
             throw 'char expected';
       }
	var idx = this.indexOf(char);
	return (idx >= 0);
}

They have added some code to verify if the input value is defined and throw and error so that higher up functions can handle it. This is fairly normal and I have seen this behavior in a ton of code over the years.

If you then pass a string into the jQuery.param function it will try to run this function without passing in a value using when it processes this line of code:

`var value = jQuery.isFunction( valueOrFunction ) ? valueOrFunction() : valueOrFunction;`

I just spent half a day helping someone track down a bug in their app which came to this situation. 

To make the jQuery.param function more robust I see two possible solutions:

- Wrap valueOrFunction() with try/catch.
- Later in the code when looping through the prefix values, use a proper for loop instead of a foreach, at least for string values. This would reduce the number of iterations in the loop, thus making it faster, and would also prevent this error from occurring. 

I don't use jQuery that often so I'll leave it to the community to decide the best approach to improve this.

**Comment by dmethvin** [comment]
Extending prototypes you don't "own", particularly the builtin ones, is a very bad practice. If you must do that, you can use `Object.defineProperty` and set `enumerable: false`.

**Comment by rbrundritt** [comment]
Actually it isn't, it is fairly common, especially in libraries that fill feature gaps in older browsers, but that isn't the point of this thread. The point is that if you pass in any object that has a function into the jQuery.param function and it throws and error because no input values are passed into that function, the param function will fail. Wrapping valueOrFunction() with a try/catch would handle this situation and make the param function more bullet proof.

**Comment by gibson042** [comment]
We _want_ `jQuery.param` to throw exceptions when we can't serialize the input, because that signals to developers that they are doing something wrong (or in this case, two things wrong—modifying built-in prototypes, and passing a string where [documentation](http://api.jquery.com/jQuery.param/) indicates the need for "an array, a plain object, or a jQuery object").
