### ISSUE TITLE
issue with outerHeight() / outerHeight(true) on jquery 3.2.1 (possibly 3.x)

### ISSUE THREAD

**Issue by daflip** [jquery/jquery#3881]
Hi

Strange one. I was using jQuery 3.2.1. I have two machines, both are running Linux, using Chrome on both. I had/have an issue with outerHeight calculation on jQuery on just one of these machines. The element height was 36px as set in the CSS, and also showed as being 36px in the element inspector of both chrome instances however jQuery 3.2.1 returns an incorrect outerHeight and outerHeight(true) on one of these machines.  A lot of head scratching and comparing things and I eventually realised the issue was with the latest version of jQuery, possibly with the 3.X branch. In any case, I rolled back to jQuery 2.2.4 and both machines are now reporting the correct value for outerHeight and outerHeight(true).    

This seems like a pretty clear regression to me.

Let me know if I can be of any help

Regards
Jerry

**Comment by timmywil** [comment]
Thanks for opening an issue. However, we need a reduced test case from https://jsfiddle.net or https://jsbin.com in order to assess any issues.

**Comment by serbanghita** [comment]
@daflip This is because of `Breaking change: .outerWidth() or .outerHeight() on window includes scrollbar width/height` [0]

[0] https://jquery.com/upgrade-guide/3.0/#breaking-change-outerwidth-or-outerheight-on-window-includes-scrollbar-width-height

**Comment by daflip** [comment]
Super helpful! Thanks @serbanghita

**Comment by daflip** [comment]
Actually that's not it. The breaking change only applies to window.. but I'm performing outerHeight on a div element. I will attempt to create a reproducible version - problem is it's also got something to do with the machine so if you're not using a machine it happens on you won't be able to reproduce it!

**Comment by serbanghita** [comment]
In that case share a piece of code, I have some tests suites that I did manually that I want to check this against.

**Comment by timmywil** [comment]
Can be reopened with a test case.
