### ISSUE TITLE
unable to set opacity css property with Chrome 62+

### ISSUE THREAD

**Issue by atoy40** [jquery/jquery#3882]
### Description ###

using $(elm).css("opacity", value); doesn't work in chrome (at least 62 and 63)

The problem is in the part of the jquery code checking opacity support.
The test is : style.opacity === "0.5"
But in my case (chrome with **french** locales), the value of opacity is "0,5" but not "0.5" (note the comma instead of a point). So jquery use the opacity workaround and only set "zoom: 1;" to style.

May be it can be a Chrome bug instead ?

Thanks
Anthony.

**Comment by gibson042** [comment]
What version of jQuery are you using? Please provide a test case on jsFiddle or similar.

**Comment by timmywil** [comment]
Can be reopened with a test case.
