### ISSUE TITLE
jQuery.parseJSON error on empty string

### ISSUE THREAD

**Issue by eywenn** [jquery/jquery#3889]
### Description ###
When calling the jQuery.parseJSON function with an empty string as argument, it crashes. This is probably due to changes on the JSON.parse function.
Tested in Chrome v62.0.3202.94 64bit

### Fix ###
```
jQuery.parseJSON = function (data) {
    if (data)
        return JSON.parse(data);
    else
        return undefined;
};
```

### Link to test case ###
https://jsfiddle.net/pgzyjqdp/

**Comment by mgol** [comment]
This is intended; `jQuery.parseJSON` is supposed to work exactly as `JSON.parse`. Besides, it's deprecated now, you should just use `JSON.parse`.

**Comment by eywenn** [comment]
@mgol I found this issue when recieving an empty response from an ajax POST, since it tried to parse the empty response, it crashed the function. I'm new to reporting issues on GitHub, so maybe this wasn't the right approach to reporting this issue. I'll look into it some more tomorrow and if I can pinpont a scenario where this issue is reproducable I'll post that.

**Comment by dmethvin** [comment]
@eywenn Given your description though I think it is this, and is not a bug.
https://jquery.com/upgrade-guide/1.9/#jquery-ajax-returning-a-json-result-of-an-empty-string

StackOverflow should be your first stop for these questions:
https://www.google.com/search?q=stackoverflow+jquery+json+empty+string

**Comment by eywenn** [comment]
@dmethvin should I return a success message from the server instead of nothing then?

**Comment by dmethvin** [comment]
Again, StackOverflow should be your first stop. The Google search I have there leads to this post, with the highest ranked answer telling you the shortest valid JSON strings.
https://stackoverflow.com/questions/30621802/why-does-json-parse-fail-with-the-empty-string

**Comment by eywenn** [comment]
I removed my fix from the js file and am now returning an empty, valid JSON instead. Thanks for the feedback
