### ISSUE TITLE
Connecting SVG shapes example not working

### ISSUE THREAD

**Issue by smaameri** [jquery/jquery#3890]
Have tried the latest 2016 example from your blog post about [connecting svg elements together](https://blog.jsplumbtoolkit.com/posts/connecting-svg-shapes-updated.html), but it is not working. 

You can see the Endpoint dots are showing on the SVG elements, but they are not connected together, and if you click on the Endpoints, they both disappear.

<img width="447" alt="screen shot 2017-12-13 at 5 16 07 pm" src="https://user-images.githubusercontent.com/1417939/33940811-eb1eef90-e029-11e7-8fc4-74c22df44051.png">

Any ideas why it is not working. Do the offsetCalculators and sizeCalculators need updating?

Thanks,

**Comment by mgol** [comment]
This is a jQuery bug tracker, we don't have anything in common with https://blog.jsplumbtoolkit.com.

**Comment by smaameri** [comment]
Ys, sorry posted this on the wrong repo. Thanks for checking..
