### ISSUE TITLE
jquery width() function converting 100% to 100px

### ISSUE THREAD

**Issue by bharatnishad** [jquery/jquery#3908]
### Description ###

I have seen that I am getting width value as 100 for calculating my tab width which would be nearly browser width. when I deeply gone then figure out it is converting value 100% as 100. it is taking value from getComputedValue from styles(computed). it is getting as 100%. by that time offsetWidth is 0.
 using jquery2.1.1
PFA: screenshots

### Link to test case ###

<img width="628" alt="jquery100 prob1" src="https://user-images.githubusercontent.com/3088442/34371863-a23b9d78-eaf6-11e7-85c8-7670e340f9a5.PNG">
<img width="638" alt="jquery100 prob" src="https://user-images.githubusercontent.com/3088442/34371864-a26407e0-eaf6-11e7-8dce-72b33a738855.PNG">

**Comment by mgol** [comment]
Please provide a test case on JSFiddle or JSBin, we cannot guess what the issue is just by looking at the screenshots.

Also, you wrote the issue description in an HTML comment so it's invisible. Please edit it and move the description outside of a comment.

**Comment by timmywil** [comment]
Can be reopened with a valid test case.

**Comment by bharatnishad** [comment]
what testcase you want? As you can see clearly 100% is converting 100 using parsefloat.  This issue use to come when it check width using clientWidth then it goes to getComputedStyle and get width as 100% which later convert into 100 as px.

**Comment by mgol** [comment]
@bharatnishad A JSFiddle or JS Bin that we can run and clearly see what you expect and what you get. A screenshot of the middle of the execution doesn't really help much as we don't know how the code is getting there.

**Comment by bharatnishad** [comment]
See that is very weird situation, it use to come in middle of  execution of our functionality. ok what we are doing, we are converting xml into html previously we kept that element as display none. then on event handler file execute then we make it as true. but when we try to compute width of browser from jquery we get 100 for 1st two time when it goes jquery width() function after that we get browser width 90% time and 10% we can get 100 always. So  I can not produce any of jsFiddle or any online where you can see this issue. 
So what I think, by that time  elem.offsetHeight does not populate and that is why it try to take width from computed style.
val = name === "width" ? elem.offsetWidth : elem.offsetHeight,
		styles = getStyles( elem ),
	if ( val <= 0 || val == null ) {
		// Fall back to computed then uncomputed css if necessary
		val = curCSS( elem, name, styles );

then it try to get from getStyles

var getStyles = function( elem ) {
		return elem.ownerDocument.defaultView.getComputedStyle( elem, null );
	};



function curCSS( elem, name, computed ) {
	var width, minWidth, maxWidth, ret,
		style = elem.style;

	computed = computed || getStyles( elem );

...........

I have seen  elem.ownerDocument was having style attribue width: "100%" and that was taking value
ret = computed.getPropertyValue( name ) || computed[ name ]; as ret. 

Now I don't know how it is setting here 100%. and which width  window.doucment take as style(width) attribute.

I hope I gave you enough information. if you want  live demo, then we can arrange any video call, I can show you.

**Comment by gibson042** [comment]
We volunteer our time on this project, and lack the capacity to debug full application code, especially over a video call. If you cannot provide a succinct test case demonstrating the problem, then we don't have enough information to even verify that there _is_ one.
