### ISSUE TITLE
New method to bind listener

### ISSUE THREAD

**Issue by Zack-Bee** [jquery/jquery#3912]
### Description ###
     function f() {console.log(1);}
     $(document).on("click", f);
     $(document).on("click", f);

When you click the document, 1 will appear twice.

     function f() {console.log(1);}
     document.addEventListener("click", f);
     document.addEventListener("click", f);

In this way, just once. So i am thinking about adding new method, like this
`$(document).onOnce("click", f)`. The method only binds the callback function when it doesn't exist
in the queue of callback functions.

**Comment by mgol** [comment]
Thanks for the proposal.

Such an API is too close to the core `on` and we wouldn't want to end up with lots of very similar APIs doing the same thing in a slightly different way.

Such a method can be written as a small jQuery plugin but I don't see it happening in Core.

**Comment by Zack-Bee** [comment]
Thank you for your prompt reply.

2017-12-28 19:18 GMT+08:00 Michał Gołębiowski-Owczarek <
notifications@github.com>:
