### ISSUE TITLE
Can't download jquery

### ISSUE THREAD

**Issue by kdehuff** [jquery/jquery#3913]
I cannot download and install the newest version of jQuery. When I install the software ( the uncompressed, development jQuery 3.2.1) I am greeted with an error like the one shown in the attachment.

![jquerysnippett](https://user-images.githubusercontent.com/34898364/34463436-a3efd2d4-ee10-11e7-9be8-9559e4b0bde8.JPG)

Thank you for your consideration.

- Kevin

**Comment by dmethvin** [comment]
This error message says that you are trying to execute jQuery using Windows Script Host. It is not meant to be run that way, you should include the downloaded file in an HTML page and open the HTML page in a browser.

**Comment by kdehuff** [comment]
So, I save the downloaded file as an html file?


- Kevin
