### ISSUE TITLE
grunt commands `karma:chrome` & `karma:firefox` do not work

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#3921]
After executing commands mentioned in the header tests do not run.

/cc @Krinkle

**Comment by timmywil** [comment]
I think we can merge this ticket with #3922. We need to do an inventory of all the grunt (and npm) commands that we want to be user-facing and ensure they all work.

**Comment by markelog** [comment]
You wish is my command – just updated the description of the #3922 ticket
