### ISSUE TITLE
Deferred#fail throwing Uncaught (in promise) on Chrome

### ISSUE THREAD

**Issue by soundasleep** [jquery/jquery#3924]
I'm having a very odd behaviour with jQuery#ajax interactions between Deferred#fail and Deffered#catch, on Chrome (but not Firefox).

When I am writing a callback like so:

```js
$.ajax({ ... }).done(doneFunction).fail(failureFunction)
```

If the AJAX call fails with a 400, the `failureFunction` is called (expected), but another error is thrown in the Browser: `Uncaught (in promise)`, shown here in the inspector tools:

![chrome jquery bug](https://user-images.githubusercontent.com/3889656/34595515-7e8e4f3a-f23d-11e7-9f57-fa5fdbc6b8d9.png)

But if I change the behaviour to:

```js
$.ajax({ ... }).done(doneFunction).catch(failureFunction)
```

Then the `failureFunction` operates as expected, and there are no uncaught promise errors. I can also do this, and `failureFunction` executes twice:

```js
$.ajax({ ... }).done(doneFunction).fail(failureFunction).catch(failureFunction)
```

From what I understand (and from the docs), it appears that Deferred#fail and Deferred#catch should both be doing the same thing (they are both documented as "Add handlers to be called when the Deferred object is rejected."). Is there a subtlety between the two methods that I'm missing?

Even the docs themselves suggest using #fail is the correct behaviour with #done: http://api.jquery.com/deferred.fail/

In the meantime, replacing #fail with #catch seems to be solving this issue.

**Comment by mgol** [comment]
Thanks for the report. Please provide a test case on JSFiddle or JS Bin that will show the issue.

**Comment by timmywil** [comment]
Can be reopened with a test case.
