### ISSUE TITLE
jQuery 3+ breaks droppable/draggable with subpixel width/height

### ISSUE THREAD

**Issue by jkorff** [jquery/jquery#3926]
### Description ###
Issue:
When using jQuery 3+ with draggable elements which have a width or height that has subpixels (e.g. by using em or rem units) the draggables fly back to their source position even when configured to snap and stay on the target.

Expected behaviour: snap and remain on target.

Browsers affected: All recent (Chrome 62, Firefox 52, IE Edge/11)

### Link to test case ###
Minimal test case: https://jsfiddle.net/bv3ddrjx/7/

To reproduce:
1) Drag the white boxes onto the drop targets => they'll bounce back (the bug)
2) In the CSS, remove the subpixels in line 35 and 36 => it works as expected
3) Leave the subpixels, but swap the jQuery library (first HTML lines) to 2.2.4 => it works with subpixels

Use different values of subpixels to get different failures (no draggable works, just one works etc.)

**Comment by dmethvin** [comment]
This seems like a jQuery UI bug and not a jQuery one? Subpixel values are becoming more important with high-resolution displays so it seems like we wouldn't want to "fix" the UI bug by truncating the values.

**Comment by jkorff** [comment]
If it was a jQueryUI bug, why does reverting to the previous jQuery library fix it? And, yes, I agree that truncation wouldn't be a solution.

**Comment by dmethvin** [comment]
The reason we had a major version bump was to make changes that added things that could potentially break code, that's what semver intends for it to signal. Fractional dimensions were [documented in the migration guide](https://jquery.com/upgrade-guide/3.0/#breaking-change-width-height-css-quot-width-quot-and-css-quot-height-quot-can-return-non-integer-values).

**Comment by jkorff** [comment]
Thank you. I've [posted it](https://zohodiscussions.com/jquery/topic/jqueryui-and-droppable-draggable-do-not-work-with-subpixel-width-height) over at the jQueryUI forum.
