### ISSUE TITLE
Jquery to create html graph

### ISSUE THREAD

**Issue by Ashissh021** [jquery/jquery#3930]
Hi Team,

I am very new to Jquery and i want good document to learn but i am not getting it.
Actually I want to display an html bar chart which takes input from excel sheet and generate the graph (bar chart) and display in html, So each time when i open the html it should read the excel sheet and generate the graph but i am facing lot of issue as I am not able to read the data and plot a graph.

Please help me  or direct me where i can get the knowledge how to read or any demo example to understand how its should work.
Thanks
Ashissh

**Comment by timmywil** [comment]
Thanks for opening issue. However, this repo is for bug tickets and feature requests. You can find support on stackoverflow.com or the [jQuery gitter](https://gitter.im/jquery/jquery)

**Comment by Ashissh021** [comment]
@timmywil - Thank you for guiding and redirecting me .
