### ISSUE TITLE
$.add is tooo sloooooow

### ISSUE THREAD

**Issue by sdav** [jquery/jquery#3933]
### $.add is very slow ###

This happens when adding a lot of elements to a previous selection.

The problem can be fixed in many ways, also stupid ways give super results; this is really frustating in Chrome (latest version 63) and IE10; Firefox is slower but responds in a good manner.

### Check this link ###

In this sample I'm adding 10000 rows to other 10000 rows; it takes more than 10 seconds... so wait a bit for the result (alert)

My stupid 1 second fix respond istantly (it is not the cache, you can comment the first part if you want)

[jsFiddle](https://jsfiddle.net/dwabeLaw/3/)

**Comment by timmywil** [comment]
The difference is that `.add` also does a uniqueSort, ensuring that all elements are unique and sorting them by dom order. This obviously takes time on 20,000 elements. Your solution is exactly what I would recommend on a learning site, but we can't remove `uniqueSort` from `.add`.

**Comment by sdav** [comment]
Thanks, You should report in the jquery doc imo 😉Ciao, Davide-------- Messaggio originale --------Oggetto: Re: [jquery/jquery] $.add is tooo sloooooow (#3933)Da: Timmy Willison A: jquery/jquery CC: sdav ,Author The difference is that .add also does a uniqueSort, ensuring that all elements are unique and sorting them by dom order. This obviously takes time on 20,000 elements. Your solution is exactly what I would recommend on a learning site, but we can't remove uniqueSort from .add.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jquery/jquery","title":"jquery/jquery","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jquery/jquery"}},"updates":{"snippets":[{"icon":"PERSON","message":"@timmywil in #3933: The difference is that `.add` also does a uniqueSort, ensuring that all elements are unique and sorting them by dom order. This obviously takes time on 20,000 elements. Your solution is exactly what I would recommend on a learning site, but we can't remove `uniqueSort` from `.add`."}],"action":{"name":"View Issue","url":"https://github.com/jquery/jquery/issues/3933#issuecomment-356951359"}}}
