### ISSUE TITLE
jQuery doesn't optimize identifier with backslash

### ISSUE THREAD

**Issue by NN---** [jquery/jquery#3937]
jQuery doesn't optimize selector "#\\:x" to document.getElementById(":x").

The problem is with this regex which doesn't recognize backslashes escape character:

```js
// Easily-parseable/retrievable ID or TAG or CLASS selectors
rquickExpr = /^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,
```

**Comment by dmethvin** [comment]
We intentionally leave the more complex cases alone because we don't want to reimplement the escaping logic there. Are there situations in real code where the lack of optimization makes a difference? Typically the examples that are given show some sort of tight loop selecting things 20,000 times or similar, which aren't realistic.

**Comment by NN---** [comment]
Yes, it is real word scenario.
I need to use selector with id containing colon ':'.
In such case a simple getElementById about 100 times faster than jQuery, and btw than querySelectorAll.

I don't think the logic will be too complex.
There are also many CSS selectors parsers which can be used for inspiration.

**Comment by dmethvin** [comment]
If you know you want something with literal characters that would need to be escaped in CSS, just use `$(document.getElementById("idWith:Colon"))`.

**Comment by NN---** [comment]
It is a solution, but it means that I need to parse the selector by myself and make optimization path, and this is exactly what jQuery should do.

**Comment by timmywil** [comment]
Thanks for opening an issue. The idea behind `rquickExpr` is to catch the most common cases. It's not meant to get overly complicated. This is not one of the most common cases and is fast *enough*.

**Comment by NN---** [comment]
Actually Sizzle already has the right regexp here: https://github.com/jquery/sizzle/blob/8bda6c95617777ea596bf54636b27548af69d086/src/sizzle.js#L110

What is the reason jQuery doesn't use Sizzle implementation for this ?
What do I miss ?

Thanks.

**Comment by timmywil** [comment]
Again, `rquickExpr` is not meant to catch every selector. It is just a quick pass to make some of the most common selectors like ID and class a bit faster. Sizzle handles the rest and has much more complicated regex patterns that are meant to match the selector spec.

**Comment by NN---** [comment]
@timmywil What about small addition for handling escaping: "\\." ?
Will it be small enough ?

**Comment by NN---** [comment]
Instead of /^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/
Will be /^(?:#(?:([\w-]|\\.)+)|(\w+)|\.((?:[\w-]|\\.)+))$/

**Comment by NN---** [comment]
Please review a new PR with smaller change.
