### ISSUE TITLE
off() does not support object as selector

### ISSUE THREAD

**Issue by SailorMax** [jquery/jquery#3941]
### Description ###
`on()` support object as selector, but `off()` does not.
``` js
// successfully setup event handler
$(document).on('selectstart dragstart', document, function(e) {
  e.preventDefault();
});

// unsuccessfully remove event handler
$(document).off('selectstart dragstart', document);
```

Looks like the problem in second argument. `off()` work only if it is a string...

### Link to test case ###
https://jsfiddle.net/xyw1t5oe/

**Comment by dmethvin** [comment]
The problem isn't with `.off()`, it's with what you're passing to `.on()`. What are you trying to do?

**Comment by SailorMax** [comment]
I trying to remove an event handler.

**Comment by dmethvin** [comment]
What are you expecting the `.on()` to do? It looks to me like a delegated event handler that is both attached at and delegated from `document`. Why do that?

**Comment by SailorMax** [comment]
the `on()` turn off possibility to select text on the page
the `off()` turn on possibility to select text on the page

**Comment by dmethvin** [comment]
Yes, but why a delegated handler? Why not this?
```js
$(document).on('selectstart dragstart', function(e) {
  e.preventDefault();
});

$(document).off('selectstart dragstart');
```

**Comment by SailorMax** [comment]
Actually I don't know :) Source was taken from here:
https://github.com/ivoviz/feedback/blob/master/stable/2.0/feedback.js#L550

I just think, if work
``` js
$(document).on('mouseenter', '.feedback-helper', function(){...});
$(document).off('mouseenter', '.feedback-helper');
```
then
``` js
$(document).on('selectstart dragstart', document, function(){...});
$(document).off('selectstart dragstart', document);
```
have to work also.

**Comment by dmethvin** [comment]
No it doesn't work that way. You can probably get more help on StackOverflow since this isn't a bug.

**Comment by SailorMax** [comment]
So then may be remove support of
``` js
$(document).on('selectstart dragstart', document, function(){...});
```
?
