### ISSUE TITLE
$.ajax will change URL

### ISSUE THREAD

**Issue by sebst** [jquery/jquery#3944]
Consider the following $.ajax request:

```
$.ajax({url: "/rate",
            method: "POST", success: function(results){console.log(results)}})
```

This will call the correct URL like: `http://<hostname>/rate`.

Now, consider this request:

```
$.ajax({url: "/rat/1",
            method: "POST",success: function(results){console.log(results)}})
```

Again, as expected, the URL `http://<hostname>/rat/1` is called.

Now, the strange behaviour:

```
$.ajax({url: "/rate/1",
            method: "POST",success: function(results){console.log(results)}})
```

will call `http://<hostname>/rate` instead of the expected `http://<hostname>/rate/1`

Not sure, whats happening there.

I tried these `url`-settings:

Working:

- `/myendpoint`
- `/myendpoint/1`
- `/rate`
- `/rate/`
- `/rate/e`
- `/rat.e/1`
 `/rate/e`

Not working (leading to a call to just `/rate`:

- `/rate/1`
- `/rate/2`

**Comment by sebst** [comment]
JQuery 2.2.1

**Comment by sebst** [comment]
This might actually be a chrome bug, since this
```
r = new XMLHttpRequest()
r.open("POST", "/rate/1", true, undefined, undefined)
r.send(null)
```
will also call the wrong url: `/rate`

**Comment by RinkAttendant6** [comment]
Have you filed this bug on the Chrome issue tracker? I can't reproduce it using the XMLHttpRequest example and I'm using Chrome 63 on Linux (Mint).
