### ISSUE TITLE
Cannot get image dimensions from new created element

### ISSUE THREAD

**Issue by anewway** [jquery/jquery#3945]
### Description ###
I want to create a new image element and get its dimensions information. It fails on jQuery but works on JavaScript. I wonder why I can't get this information in jQuery, or is there any improper usage in code?
```javascript
var src = 'https://www.w3schools.com/howto/img_fjords.jpg';

// jQuery (Fail case to get image dimensions)
var img1 = $('<img/>', { src: src });
img1.bind('load', function(){
	console.log('jQuery', img1.width(), img1.height());
}); // output: jQuery 0 0
```
```javascript
// JavaScript (This result is what I expect)
var img2 = new Image()
img2.src = src;
img2.addEventListener('load', function(){
	console.log('JavaScript', img2.width, img2.height);
}); // output: JavaScript 600 400
```
I run the code on Chrome and Firefox but both of them fail in the first (jQuery) case.

### Link to test case ###
https://jsfiddle.net/anewway/etnap0ss/

### Testing environments ###
- jQuery 3.2.1
- Ubuntu 16.04 (x64)
- Firefox 57.0.4 (64-bit)
- Chrome 61.0.3163.100 (64-bit)

**Comment by dmethvin** [comment]
These elements are not in the document, thus they don't have a measurable width or height. For example, consider if the document has a CSS rule of `img {width: 120%; height 120%}`, the actual width and height in the document would not match the natural dimensions of the image. If you want the value that the browser provides in those properties, use `.prop("width")` and `.prop("height")`. https://jsfiddle.net/etnap0ss/1/
