### ISSUE TITLE
Exception thrown and not caught jquery 3.2.1 with Bootstrap 4

### ISSUE THREAD

**Issue by GearTheWorld** [jquery/jquery#3948]
I have an MVC 5 app with bootstrap 3.3.7 and JQuery 3.2.1
When I use Nugget to update to bootstrap 4.0.0 the application crashes immediately with the error

**Exception thrown and not caught**

When I downgrade the Bootstrap to 3.3.7 everything works perfectly.  Is there something I don't understand or there's definitely something wrong between JQuery 3.2.1 and Bootstrap 4.0.0 ?

**Comment by dmethvin** [comment]
There were some things the issue template asked for that are not on this ticket. Can you provide a test case?

**Comment by GearTheWorld** [comment]
What is a test case

**Comment by dmethvin** [comment]
A test case is the simplest possible set of code that shows the problem. From the meager information above it sounds like the new Bootstrap 4 isn't compatible with jQuery 3.2.1. However, if you have a huge app with lots of code it could be due to anything. The goal of a test case is to help identify the problem. Without one, we can't do much.

**Comment by GearTheWorld** [comment]
Can I just give you the exact place in JQuery where it crashes ?  I think this would be the shorter and faster way to give you what is wrong else I will give you a repro with the minimum as requested.

**Comment by dmethvin** [comment]
That probably isn't going to help. We'd need to know how it got there. We might want to see the effect of changing jQuery versions or Bootstrap versions or trying other browsers.

**Comment by GearTheWorld** [comment]
Ok I'll get back to you.  I assume I can just attach the repro to this issue ?

**Comment by dmethvin** [comment]
As the template said, we'd like to have the case on a site like jsfiddle.net or jsbin.com so we can easily try and share it.

**Comment by GearTheWorld** [comment]
Ok

**Comment by Johann-S** [comment]
FYI in Bootstrap 4 documentation we use jQuery 3.2.1 (slim version) and everything is fine.

And in this CodePen I use the latest BS 4 with jQuery 3.2.1 (full version) and it's fine too : https://codepen.io/Johann-S/pen/goqdwe

**Comment by GearTheWorld** [comment]
I have Bootstrap switches and Bootstrap 3 Datetimepicker and many other things so I'm sure Bootstrap 4 and JQuery 3.2.1 are fine for a project with absolutely nothing however it's not the case of 93.54% of the world.

I will do a repro as soon as I can

**Comment by mgol** [comment]
If you're getting an error when you updated Bootstrap, it looks like any issue you have lies in Bootstrap, not jQuery (at least that's the default position). That said, we could look at a test case.

**Comment by timmywil** [comment]
Can be reopened with a test case.
