### ISSUE TITLE
Wrong instanceof check in jQuery.fn.init?

### ISSUE THREAD

**Issue by John-Blair** [jquery/jquery#3958]
In jQuery.fn.init: 

Is the test for instanceof jQuery correct, when there is no new jQuery() call anywhere in the library?

i.e. the code is below:
 context = context instanceof jQuery ? context[0] : context;

The jQuery constructor function does a new jQuery.fn.init() call not a new jQuery()

Thanks.

**Comment by dmethvin** [comment]
If you think there's a bug, follow the issue template and post a test case showing that it's broken. If you want help on how jQuery works it's probably best to ask on StackOverflow.
