### ISSUE TITLE
css() relative modifiers do not work as expected

### ISSUE THREAD

**Issue by e-compton** [jquery/jquery#3959]
### Description ###
When calling .css() using the relative (-= or +=) syntax twice in a row the second call is ignored.
```js
$('.thing').css('height', '+=100px');
$('.thing').css('height', '-= 50px'); // this line seems to be ignored
```
this is different behaviour from when using normal absolute notation:
```js
$('.thing').css('height', '200px');
$('.thing').css('height', '150px'); // this line is run
```

Has been observed in Safari, iOS Safari and Chrome on jQuery 1/2/3 and jQuery slim

### Link to test case ###
https://jsfiddle.net/arkticpanda/xk69odzh/3/

**Comment by mgol** [comment]
You have an extra space after `-=` which makes the value invalid. Use `'-=50px'` instead of `'-= 50px'`.

**Comment by e-compton** [comment]
Thanks for the correction, so now instead of ignoring the second command it ignores the first:
```js
$('.thing').css('height', '+=100px'); // doesnt happen
$('.thing').css('height', '-= 50px'); 
```
https://jsfiddle.net/arkticpanda/xk69odzh/6/

The div shrinks down to 50px, instead of increasing to 150px

**Comment by mgol** [comment]
Thanks for the updated reproduction. Reopening.

**Comment by gibson042** [comment]
This behavior is caused by the CSS transition: https://jsfiddle.net/xk69odzh/26/

And I would say it's expected, because the target value of a relative adjustment is determined right away. You set CSS to stretch out height adjustments over time, then set the height, then immediately adjust it before the first animation completes, which makes the adjustment relative to an intermediate value.

**Comment by e-compton** [comment]
Ok, I think I get it. So when there is a transition on a property that property won't change instantly, its just aiming for some target.

```js
$('.thing').css('height', '+=100px');
// at this point .thing still only has height 100px, but will become 200px
$('.thing').css('height', '-=50px'); 
// on this call jQuery reads the height as 100px, subtracts 50px and sets it to 50px.
```
To solve this you wait until the transition finishes before you set the second value

```js
$('.thing').css('height', '+=100px').on('transitioned', () => {
  $('.thing').css('height', '-=50px');
  $('.thing').off('transitioned');
});
```
Although I think it would make more sense if the `+=` and `-=` operators read from its target instead of its current value.

https://jsfiddle.net/xk69odzh/30/

**Comment by mgol** [comment]
> Although I think it would make more sense if the `+=` and `-=` operators read from its target instead of its current value.

There's no API to read the final value so we don't really have a choice.
