### ISSUE TITLE
feature: adding key code filter directly to all keyboard events

### ISSUE THREAD

**Issue by eisbehr-** [jquery/jquery#3963]
In the most cases, whenever keyboard events like `keydown`, `keyup` or `peypredd` are used, devs write a single `if` inside the handlers and do the work inside of it. So this is very often seen out there:

```JS
$('input').keyup(function() {
    if (event.which == 13) {
        // do something
    }
});
```

My idea was, that it would be really helpful and nicer to write, if there would be an optional parameter on these events, that could be a single integer, or an array of integers, representing the `key codes`, that will be used as filter for the event trigger.

The example above could look somehow like this then:

```JS
$('input').keyup(13, function() {
    // do something
});
```

Or an example with more key codes:

```JS
$('input').keyup(function() {
    if (event.which == 13 || event.which == 27 || event.which == 10) {
        // do something
    }
});

$('input').keyup([13, 27, 10], function() {
    // do something
});
```

This would produce way less code to write, if often used, is easy to understand and would be compatible to the current api, if I'm not wrong.

**Comment by timmywil** [comment]
Thank you for opening an issue. This is not a bad idea, but we're moving away from event aliases and promoting `.on` to more closely match native and possibly take advantage of new event APIs in 4.0. For now, I think this is best implemented in a plugin.
