### ISSUE TITLE
Faster DOM element creation

### ISSUE THREAD

**Issue by SteveTheTechie** [jquery/jquery#3965]
### Description ###
My understanding is that we can use either `$('<div />', plainObject)` or `$(document.createElement('div')).attr(plainObject)` to create a new `<div>` with attributes set, but we cannot use `$(document.createElement('div'), plainObject)`, which I would expect to be a bit faster than either of the currently valid approaches.   Is there some reason the latter approach cannot be supported?  When I look at the code, I do not see a reason it could not be supported... it looks like it would be a minimal code size impact.  (But maybe I am missing something.)  Thanks!

**Comment by dmethvin** [comment]
The `$(x, plainObject)` case is just a more convoluted way to call the jQuery methods in the plainObject, or if they're not methods then set them as attributes. The [documentation](http://api.jquery.com/jQuery/#jQuery-html-attributes) explains more. I'd actually prefer to deprecate it. What makes you think it would be faster? Is the speed of `.attr()` causing issues in your code?

**Comment by timmywil** [comment]
Thank you for opening an issue. However, this looks like a micro-performance optimization where the existing API is *fast enough*. Yes, you can always make things faster by going native, but you lose some convenience without actually making a difference in speed that is noticeable to humans.
