### ISSUE TITLE
`.change()` not working correctly on radio buttons

### ISSUE THREAD

**Issue by leonixyz** [jquery/jquery#3970]
Listening for changes on radio buttons seems not fully working: I expect the event to be triggered also when the radio gets unchecked. 

The event listener works pretty fine for checkboxes, where the user has to click to uncheck, but for some reason radio buttons works differently.

If the user selects a radio button A, and afterwards selects radio button B, part of the same group, the `change` event is not triggered for A.

Try code below: I am never able to log "myRadio1 has been unchecked" in the console

edit: tested on Firefox 59, Chrome 63, on Mac OS 10.13.3

~~~
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div>
        <input type="radio" name="myRadio" value="1" id="myRadio1" checked> Option 1<br>
        <input type="radio" name="myRadio" value="2" id="myRadio2"> Option 2
    </div>
    <div>
        <input type="checkbox" value="1" id="myCheckbox1" checked> Option 1<br>
        <input type="checkbox" value="2" id="myCheckbox2"> Option 2
    </div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <script>
    	$(function() {
    		$('#myRadio1, #myCheckbox1').change(function() {
                    let who = $(this).prop('id');
                    let checked = $(this).prop('checked') ? 'checked' : 'unchecked';
                    console.log(who + ' has been ' + checked);
    		});
    	});
    </script>
  </body>
</html>

~~~

**Comment by timmywil** [comment]
Thank you for opening an issue. However, this is default browser behavior and unrelated to jQuery. Note that if you bind to both radio inputs, the one that was checked gets the change event. https://jsbin.com/zetuvuv/1/edit?js,console,output

Please refer to stackoverflow.com for further support.
