### ISSUE TITLE
AJAX response with empty body runs error function instead of success function.

### ISSUE THREAD

**Issue by JHorvath-MaxetaTech** [jquery/jquery#3973]
Given the following ajax request:

          $.ajax({
            type: 'POST', 
            url: service,
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify(whatever),
            success: function(data, textStatus, jqXHR) {
              //if body has valid json we end up here
              console.log('success');
            },
            error: function( jqXHR, textStatus, errorThrown) {
              //if body is empty we end up here
              console.log('error');
            }
          });

This was encountered this when returning a 201 with an empty body from a REST API, which seems like a legitimate scenario. It appears that no body is treated as an error case since there is no JSON to process, given that the errorThrown is:

        SyntaxError: Unexpected end of JSON input
            at parse (<anonymous>)
            at Ut (jquery-3.3.1.min.js:2)
            at k (jquery-3.3.1.min.js:2)
            at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2)

This also occurs for XML, however perhaps the case should be that no root element is actually valid, and JSON/XML parsing should be held off in such a case.

* Current workarounds are to return an empty object from the REST API so the success block is hit as expected, or to change the dataType expected to 'text' so no automatic parsing is done and manually handle for when a body is not empty (which if using this pattern, should only be in error situations, and thus handled in the error function).

**Comment by dmethvin** [comment]
Your request says `dataType: 'json'` which describes the value that must be returned from the request. An empty body is not valid JSON.

**Comment by JHorvath-MaxetaTech** [comment]
I disagree, in my scenario one of two things will happen when hitting my API endpoint:

1. The POST request generates a resource server side and responds with a 201 containing a proper Location header identifying the URL for the resource and no body (none is necessary).

2. The POST generates an error in which case a JSON object containing the error information is returned.

Why should it be required to send back an empty object just to get JQuery to post process a "successful" request? Handling the error case manually by using dataType: 'text' is do-able, but requires much more work to handle for endpoints which potentially return multiple data formats (i.e. XML or JSON).

**Comment by dmethvin** [comment]
If you asked for JSON and didn't get it, the request has failed. The HTTP status may be 2xx but the other constraint you put on the request (`dataType: 'json'`) was not met. 

Your endpoint should consistently return JSON if your client expects it. If you don't control the endpoint and it sometimes returns JSON and sometimes doesn't, then getting the data as text and sniffing its type probably the best bet.

**Comment by mgol** [comment]
@JHorvath-MaxetaTech If your server is well behaving and always returns data with correct `Content-Type` you may omit the `dataType` option and jQuery will listen to what server claims it returns - this may e.g. be `application/json` for responses with data and `text/plain` for responses with empty bodies.

If your server returns a 201 with empty body and a JSON `Content-Type` then it's broken and you have to rely on `dataType: 'text'` and manual parsing.

**Comment by JakenVeina** [comment]
This behavior was previously marked as an enhancement and added in 2011. See https://bugs.jquery.com/ticket/5156 and related tickets. A behavior that is previously documented and then suddenly disappears sounds like a bug to me.

For anyone else who thinks it's rather normal to have an API method that may or may not return a JSON body, the workaround is quite simple.

```csharp
$.ajaxSetup({
    converters: {
        "text json" : function(response) {
            return (response == "") ? null : JSON.parse(response);
        },
    },
});
```
