### ISSUE TITLE
JQuery 3.1.1 vs 2.2.4 change in behavior appending rows to a table

### ISSUE THREAD

**Issue by rmacfadyen** [jquery/jquery#3976]
The following code:

$('&lt;TABLE />').append('&lt;TR>&lt;TD>1&lt;/TD>&lt;/TR>').appendTo('BODY');
results in slightly different DOM structures.

Under 2.2.4 you get &lt;TABLE>&lt;TBODY>&lt;TR>...

Under 3.1.1 you get &lt;TABLE>&lt;TR>...

(one has a TBODY and one does not)

This causes problems if you later have selectors like #id TBODY TR (to get all the body rows, and no header rows).

I've reviewed the jQuery Core 3.0 Upgrade Guide and can't see anything that might be related.

So my question is... is this expected behaviour or a bug in JQuery?

(from stackoverflow question: https://stackoverflow.com/questions/48658605/jquery-3-1-1-vs-2-2-4-change-in-behavior-appending-rows-to-a-table and forum question https://forum.jquery.com/topic/jquery-3-1-1-vs-2-2-4-change-in-behavior-appending-rows-to-a-table#14737000007604149)

**Comment by gibson042** [comment]
The behavior is expected; we included a fix for #1835 in 3.0.0 but failed to mention it in the upgrade guide (probably because the fix was first included in 2.2.0 and then immediately reverted as an accidental breaking change for 2.2.1, disrupting our milestone tracking).

**Comment by JakeCigar** [comment]
I see a problem that
        $("<table><tr><td>3.3.1foo</td></tr></table>").appendTo("body")
adds a **<tbody>** and 
        $('<table>').append('<tr><td>3.3.1bar</td></tr>').appendTo('body')
does **not**.

**Comment by timmywil** [comment]
@JakeCigar That's the browser behavior. jQuery is not adding the `tbody` there.

**Comment by JakeCigar** [comment]
I know the browser does. And I think jQuery should too.  Lots of people use  the tbody for CSS.

**Comment by JakeCigar** [comment]
And…
```javascript
        $('<table>').append("<tbody>").append('<tr><td>STRANGE</td></tr>').appendTo('body'); // broken
```
Might be expected to append 2 children. It does not.

Either tbody is just a node or it is special. It should not be both ways.

**Comment by rmacfadyen** [comment]
> fix for #1835 in 3.0.0 but failed to mention it in the upgrade guide 

Any thoughts on what else might be affected by this breaking change?

How/where can I refile this issue such that the upgrade guide gets updated with this breaking change?

**Comment by dmethvin** [comment]
@rmacfadyen the upgrade guide is at https://github.com/jquery/jquery.com/blob/master/pages/upgrade-guide/3.0.md , you can file a ticket and PR at that repo. It would be great if you or @JakeCigar could propose a description for this, it would be a new item in Manipulation near https://jquery.com/upgrade-guide/3.0/#breaking-change-wrapall-function-only-calls-the-function-once . Generally you'd want to succinctly describe the change and  propose an alternate solution.

The behavior of tbody in tables has always been strange in browsers. There can be multiple tbody elements in a table which makes it even stranger. If there is already a tbody you can select that one and insert rows there or create a new one. Until 3.0 jQuery had a bunch of fiddly logic about it which is why we wanted to remove it. The person inserting the markup knows best where it should go.

**Comment by JakeCigar** [comment]
Do you want me to document how jQuery  is broken, with regard to the tbody tag? Even in 3.3.1
Native code like this gives the table 2 children…
```js
var table=document.createElement("table"),
    tbody=document.createElement("tbody"),
    tr=document.createElement("tr"),
    td=document.createElement("td");
td.textContent="OK"
tr.appendChild(td);
table.appendChild(tbody);
table.appendChild(tr);
document.body.appendChild(table);
```
but jQuery code like…
 ```js
$('<table>').append("<tbody>").append('<tr><td>STRANGE</td></tr>').appendTo('body');
```
has one child under the table.

**Comment by JakeCigar** [comment]
Maybe we should say. "Sometimes jQuery running in some browsers will give you a tbody, other times not. If you care about getting a tbody, make sure you code for it." Followed by some ways to make sure you get a tbody.

**Comment by rmacfadyen** [comment]
@dmethvin I've added issue https://github.com/jquery/jquery.com/issues/171, thanks for pointing me to the right spot.

I haven't done a PR because I'm pretty uncertain that I understand the scope of the breaking change, and I'm really not sure what the document should say about it either.

**Comment by JakeCigar** [comment]
@timmywil jQuery is involved. manipulationTarget does appends under a tbody when the user specifically asks to append under the table. If a tbody  is present.

I could be happy with it completely one way or the other. I like the idea of being less kind.

**Comment by timmywil** [comment]
@JakeCigar That's not what I meant. We no longer insert a tbody at all. It's the browser doing it natively. `manipulationTarget` is there to help prevent the creation of invalid tables, which your example actually demonstrates and is an argument for it rather than against it.

**Comment by dmethvin** [comment]
As far as I can tell, the reason why I haven't come across this difference in any code that I write is that I inject the HTML I expect to see. It seems like as long as you do this there are no problems. Appending a TR to a TABLE shouldn't be done. I completely agree that it's a behavior change and that it should be mentioned in the upgrade guide.
