### ISSUE TITLE
jQuery on Node.js can't be used as a dependency

### ISSUE THREAD

**Issue by BurkovBA** [jquery/jquery#3979]
What's the status of jquery in node.js environment?

One of the modules, my node.js project imports, is a jquery plugin and requires jquery as a dependency. When I try to initialize it, I get an error that `$.fn` is `undefined`, thus plugin can't attach to it.

Turns out, jquery can't properly initialize without a `window` object.

`console.log(require("jquery").toString());` returns: 

`function ( w ) { if ( !w.document ) { throw new Error( "jQuery requires a window with a document" ); } return factory( w ); }`

I can't just initialize `jquery` manually, passing `jsdom` as a `window` object substitute:

```js
const jsdom = require("jsdom");
const { window } = new jsdom.JSDOM(`...`);
var $ = require("jquery")(window);
```

because `require('jquery')` is executed in a plugin code, that I can't modify.

[StackOverflow question](https://stackoverflow.com/questions/1801160/can-i-use-jquery-with-node-js/40656811#40656811) has an overwhelmingly large number of recent answers, so, I suppose many people have recently encountered a similar problem.

What do I do?

Thank you, 
Boris.

**Comment by dmethvin** [comment]
You're not using a plugin in your code snippets shown there. Please provide a complete test case as asked for in the issue template.

**Comment by BurkovBA** [comment]
Ok, here is a minimal, complete and isolated test case to reproduce this issue:

`testJquery.js`
```js
(function (global, factory) { // this is a UMD wrapper around the plugin
  if (typeof define === "function" && define.amd) {
    define(['jquery'], factory);
  } else if (typeof exports !== "undefined") {
    factory(require('jquery'));
  } else {
    var mod = {
      exports: {}
    };
    factory(global.jquery);
  }
})(this, function (_jquery) {
  'use strict';

  var _jquery2 = _interopRequireDefault(_jquery);

  function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
      default: obj
    };
  }

  var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
    return typeof obj;
  } : function (obj) {
    return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj;
  };

  function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
      throw new TypeError("Cannot call a class as a function");
    }
  }

  var TestJQueryPlugin = function($) {
    console.log(require('jquery').toString());     // try importing jquery and printing the results

    var testJQueryPlugin = function() {};
    testJQueryPlugin.prototype.init = function () {};

    $.fn['TestJQueryPlugin'] = testJQueryPlugin; // THIS WILL FAIL, $.fn does not exist
    return testJQueryPlugin;
  }(_jquery2)
});
```

If you run it with `node testJquery.js`, you get:

```
function ( w ) {
				if ( !w.document ) {
					throw new Error( "jQuery requires a window with a document" );
				}
				return factory( w );
			}
/home/burkov/Documents/Projects/BurkovBA.github.io/testJquery.js:42
    $.fn['TestJQueryPlugin'] = testJQueryPlugin;
                             ^

TypeError: Cannot set property 'TestJQueryPlugin' of undefined
    at /home/burkov/Documents/Projects/BurkovBA.github.io/testJquery.js:42:30
    at /home/burkov/Documents/Projects/BurkovBA.github.io/testJquery.js:44:4
    at /home/burkov/Documents/Projects/BurkovBA.github.io/testJquery.js:5:5
    at Object.<anonymous> (/home/burkov/Documents/Projects/BurkovBA.github.io/testJquery.js:13:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

**Comment by dmethvin** [comment]
I'm not sure where you got that code from, it also seems like you're not sure based on the "I assume" comment which is where the problem begins. It looks like that is assuming Babel compilation which you're not doing here.

If you run `node --inspect-brk testJquery.js` you'll be able to step through the code and see why it fails. The command will print out a URL that explains how to attach a debugger.

**Comment by BurkovBA** [comment]
@dmethvin Hi, Dave. Thank you for the link to node debugger.

This code is what Babel with UMD preset generates from `import {$} from jQuery` with

`.babelrc`
```js
{
  "presets": [
    ["env"]
  ],
  "plugins": [
    ["transform-es2015-modules-umd", {
      "globals": {
        "jquery": "jQuery"
      }
    }]
  ]
}
```

So, with debugger I get the error - jQuery fails to initialize because of lack of window object:

```
$ node --inspect-brk testJquery.js 
Debugger listening on ws://127.0.0.1:9229/fb14e6ab-f3cd-4e9f-a1cc-fd3b8fdafa61
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
function ( w ) {
				if ( !w.document ) {
					throw new Error( "jQuery requires a window with a document" );
				}
				return factory( w );
			}

/home/path/to/project/testJquery.js:42
    $.fn['TestJQueryPlugin'] = testJQueryPlugin;
                             ^

TypeError: Cannot set property 'TestJQueryPlugin' of undefined

```

I slightly modified it to handle default and global jQuery correctly, so now it is as follows:

```js
(function (global, factory) {
  if (typeof define === "function" && define.amd) {
    define(['jquery'], factory);
  } else if (typeof exports !== "undefined") {
    factory(require('jquery'));
  } else {
    var mod = {
      exports: {}
    };
    factory(global.jQuery);
    global.metisMenu = mod.exports;
  }
})(this, function (_jquery) {
  'use strict';

  var _jquery2 = _interopRequireDefault(_jquery);

  function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
      default: obj
    };
  }

  var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
    return typeof obj;
  } : function (obj) {
    return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj;
  };

  function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
      throw new TypeError("Cannot call a class as a function");
    }
  }

  var TestJQueryPlugin = function($) {
    console.log(require('jquery').toString());

    var testJQueryPlugin = function() {};
    testJQueryPlugin.prototype.init = function () {};

    $.fn['TestJQueryPlugin'] = testJQueryPlugin;
    return testJQueryPlugin;
  }(_jquery2.default)
});
```

**Comment by dmethvin** [comment]
I think it's safe to say that at this point you're debugging something other than an issue in jQuery. Would you agree? All the plumbing around JavaScript can be a pain to get right for so many cases (CommonJS, Native ES Modules, Babel, Webpack loading, AMD, script tags).  I have sympathy, but not the time to help you remotely debug this. StackOverflow is probably a good place to ask, but once again you will have to provide to them a complete example including your build steps if they're required.

**Comment by BurkovBA** [comment]
@dmethvin 
Dave, I solved all my practical issues, I don't need jquery in node.js for myself.

But again, please, take a note that jquery itself fails to initialize in node.js: 

```
function ( w ) {
				if ( !w.document ) {
					throw new Error( "jQuery requires a window with a document" );
				}
				return factory( w );
			}
```

Take note that other people run into [the same problem on StackOverflow](https://stackoverflow.com/questions/1801160/can-i-use-jquery-with-node-js). As of 2017 jquery can't be used in node.js side as a dependency (you have to explicitly initialize `jsdom` and pass its `window` to `jquery` upon `jquery` initialization).

**Comment by dmethvin** [comment]
Yep, you definitely need a `window` as you mentioned in your original issue. The part I missed was *"because `require('jquery')` is executed in a plugin code, that I can't modify"* which would probably be true if you are using Babel to turn ES module declarations into CJS requires. You would need to do your own require.
