### ISSUE TITLE
SVG Data URI breaks with jQuery

### ISSUE THREAD

**Issue by saschanaz** [jquery/jquery#3980]
### Description ###

The following code breaks data URI on jQuery 3.3.1:

```js
$(`<img alt="this is an svg" src="data:image/svg+xml,<svg%20xmlns=&quot;http://www.w3.org/2000/svg&quot;/>" width="961" height="315">`)[0].src

// URI breaks:
// data:image/svg+xml,<svg%20xmlns="http://www.w3.org/2000/svg"></svg%20xmlns="http:>
```

### Link to test case ###

https://codepen.io/SaschaNaz/pen/eVGQWE

**Comment by dmethvin** [comment]
The `alt` attribute should have any `<` chars as `&lt;`, if you do that in your example it seems to work identically with the bare DOM one. The reason jQuery changes the HTML is that it sees the nested `<svg` as a new tag and tries to change it. Per the [documentation](https://api.jquery.com/jQuery.htmlPrefilter/) you can disable or modify this by changing the `jQuery.htmlPrefilter` method but it seems easier and more correct to just change the string.
