### ISSUE TITLE
Don't fill jQuery.cssProps if mapping isn't needed

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#3986]
While working on https://github.com/jquery/jquery-migrate/pull/291 the tests failed indicating that we are using `jQuery.cssProps` still in a [somewhat insidious way](https://github.com/jquery/jquery/blob/4a2bcc27f9c3ee24b3effac0fbe1285d1ee23cc5/src/css.js#L66). Each time someone accesses a CSS property we're populating it with properties like `{ width: "width" }`. That makes it hard for Migrate to warn since just about anything can end up there through no fault of external code. For now I won't land this warning and leave https://github.com/jquery/jquery-migrate/issues/283 open until we can change the logic to only populate `jQuery.cssProps` when it needs to actually change the property name.

**Comment by dmethvin** [comment]
Fixing this is messier than I'd like because we have a [unit test](https://github.com/jquery/jquery/blob/4a2bcc27f9c3ee24b3effac0fbe1285d1ee23cc5/test/unit/css.js#L1031-L1046) making some pretty crazy assertions. I'm not certain that aliasing one standard CSS property to another was the intended use case but that's what we're up against. Just a thought for 4.0.0, do we even need the mapping to vendor-specific properties at that point?

**Comment by mgol** [comment]
@dmethvin The unit test is just checking the mapping, I wouldn't expect anyone in real life aliasing `top` to `left`.

We need the mapping to cache vendor prefixed values which are still used by browsers, although not really for new APIs. There are lots of prefixed properties in IE 9+ and I think it's useful we handle it for users.

What we could do is to introduce another internal object that would be consulted if there is no match in `jQuery.cssProps`; we'd write vendor-prop resolved values to this separate object. This would influence the size slightly negatively but hopefully not too much?

Another solution: IIRC Migrate used to differentiate between user calls & jQuery internal ones by setting a certain flag at the beginning of a method that uses the deprecated thing and resetting it at the end (I don't remember what it was). Wouldn't something like that work here?
