### ISSUE TITLE
JQuery issue with autocomplete

### ISSUE THREAD

**Issue by Panda-Srujan** [jquery/jquery#3987]
Hi all,

I've been working on a MVC project where I've come across the situation to use a textbox with autocomplete feature included in it with ajax call to retrieve the data from the database.

I've used the following JQuery scripts for the requirement.

    <script src="~/Scripts/JQuery-3.3.1.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <link href="~/Scripts/jquery-ui.min.css" rel="stylesheet" />

Everything seems to be fine, while I've been writing the code, the intellisense automatically shows the autocomplete feature in my Visual Studio 2015.

But while executing, I'm facing an exception that states - autocomplete is not a function.

**Additional information:** 

1. I've placed these scripts in my Layout page. And I've tried placing these in my Views as well, where I've been facing the same issue.
2. I've placed the scripts in the same order as mentioned above.
3. I've swapped the scripts to fix it, but nothing worked for me.
4. This has been the case in all the browsers.

Please help me fix this issue.

Thanks in advance.

**Comment by dmethvin** [comment]
This is more of a StackOverflow thing, it's not a bug report.
