### ISSUE TITLE
In Latest version of JQuery, jQuery(<a text node>).html() is undefined

### ISSUE THREAD

**Issue by mertdeg2** [jquery/jquery#3993]
I have discovered this issue while upgrading to Angular 1.6 from Angular 1.5.

But I assume this is a breaking change in JQuery that was ported to JQLite?

**Comment by timmywil** [comment]
Thanks for opening an issue. However, as the issue template you used noted, a test case is required to evaluate issues. See https://jsbin.com or https://jsfiddle.net.

**Comment by dmethvin** [comment]
This may be related to something like https://github.com/angular/angular.js/issues/2002 which was filed in the jQuery 1.9 days at https://bugs.jquery.com/ticket/13265 . We don't really support manipulating text nodes in a collection, they are not elements and don't have all the same behavior. And `jQuery(<a text node>).html()` flat out doesn't make sense, you can't put HTML into a text node.

**Comment by timmywil** [comment]
Dave makes a good point. Can be reopened with a test case.
