### ISSUE TITLE
When jqXHR.abort(), don't respond the callback of ajax.fail() and ajax.always()

### ISSUE THREAD

**Issue by xjArea** [jquery/jquery#3995]
I use the ajax() to get the new page content, and I found sometimes I need to abort() the request, and at this time, will respond the callback of ajax.fail() and ajax.always(), I have to write this in the callback to prevent the ajax.fail() : `if(errorMsg == 'abort'){ return };`, and the ajax.always(), I can't let it stop...

So my mine is when use the abort(), let we can ctrl respond the callback or no, like this : `abort('myAbort', false);`

Emm...i try to use the plugin's way to extend the new abort function, but it seem to hard if don't touch the origin source...

Or can i user other way to prevent the callback function when i use the abort() ? if anyone know how to do, please tell me, thank you so much.

that's all...

**Comment by dmethvin** [comment]
Please post questions like this on StackOverflow. This is the bug tracker.
