### ISSUE TITLE
Deferred.notify does not invoke notification handler in $.when(...)

### ISSUE THREAD

**Issue by Legends** [jquery/jquery#3997]
### Description ###
jQuery v3.3.1
Chrome v64
Win 10 x64

I have an example where I call:
```
 var dfd = jQuery.Deferred();
  dfd.notify( "working... " );
```
but the notifiction handler never gets invoked:

```
// Attach a done, fail, and progress handler for the asyncEvent
$.when( asyncEvent() ).then(
  function( status ) {
    alert( status + ", things are going well" );
  },
  function( status ) {
    alert( status + ", you fail this time" );
  },
  function( status ) {
   alert("notfied"); // $( "body" ).append( status );
  }
);
```

**What I expect?**
That ` alert("notfied");` is executed, because `dfd.notify( "working... " );` is the first call.
### Link to test case ###
[Demo](https://codepen.io/Legends/pen/ZrZzBx?editors=0010#0)

**Comment by dmethvin** [comment]
As of jQuery 3.0, `jQuery.when() returns a `Promise` which does not support notification pass-through. I seem to recall it wasn't that reliable previously anyway. This change is [mentioned in the upgrade guide](https://jquery.com/upgrade-guide/3.0/#breaking-change-jquery-when-progress-notifications).
