### ISSUE TITLE
When right clicked on spinner, the value increments or decrements automatically.

### ISSUE THREAD

**Issue by Reflex-Gravity** [jquery/jquery#3999]
### Description ###
When the jQuery UI spinner is right-clicked, the value gets incremented and decremented automatically. This issue is faced on Mac OS and Linux and on Chrome browsers. 

### Link to test case ###
https://jqueryui.com/spinner/

**Comment by mgol** [comment]
This is the jQuery bug tracker, not a jQuery UI one. You want https://bugs.jqueryui.com/.
