### ISSUE TITLE
vulnerability in jquery 3.1.0.min.js

### ISSUE THREAD

**Issue by ankitacroit09** [jquery/jquery#4000]
### Description ###
I have done the brup scan for my app which is actually using the Jquery version 3.1.0.min 
And its found its having the Link manipulation (DOM-based) vulnerability.

Please let me know the vulnerability status for version 3.1.0.min 

### Link to test case ###
https://portswigger.net/kb/issues/00501000_link-manipulation-dom-based

**Comment by timmywil** [comment]
Thank you for opening an issue. jQuery is a lower-level API for DOM manipulation. It's the user's responsibility to sanitize input and avoid dynamically setting URLs when possible.
