### ISSUE TITLE
XML pretty-print is broken if used in browser extension content scripts

### ISSUE THREAD

**Issue by varjolintu** [jquery/jquery#4001]
### Description ###
Pretty-printing XML files fail if jQuery is used as a content script in a browser extension.
If XML and XSD files are excluded from the contect scripts in manifest.json it works, but then files without .xml/.xsd filename ending still print XML files wrong. I have confirmed that this is related to jQuery because removing it from the contect scripts resolves the issue.

Also, please see related issues:
https://github.com/keepassxreboot/keepassxc-browser/issues/50
https://github.com/smorks/keepasshttp-connector/issues/32

### Link to test case ###
Quite simple test page: [https://www.w3schools.com/xml/simple.xml](https://www.w3schools.com/xml/simple.xml) which can be used with for example KeePassXC-Browser or KeePassHTTP-Connector browser extensions.

**Comment by timmywil** [comment]
Thank you for opening an issue, but you'll need to be more specific and create a test case in https://jsbin.com or https://jsfiddle.net demonstrating an issue in jQuery.

**Comment by varjolintu** [comment]
Doing a test case with those sites is not possible. You cannot include a XML file inside an iframe so those kind of tests could be done.

To be more specific you can test this in the following way:
1) Download the browser extension sources from [https://github.com/keepassxreboot/keepassxc-browser](https://github.com/keepassxreboot/keepassxc-browser)
2) Open `manifest.json` file and remove `exclude_matches` part under `content_scripts`
3) Open Firefox and add the extension manually via `about:debugging` and choose `Load Temporary Add-on`
4) Go to [https://www.w3schools.com/xml/simple.xml](https://www.w3schools.com/xml/simple.xml) and you can see the XML file is converted to a text file.

**Comment by timmywil** [comment]
I understand that you're saying excluding jQuery fixes the issue, but that could not be less specific. What is jQuery doing to cause the problem? We are all volunteers and even if we had the time to help debug this issue, it may still lead to the discovery that jQuery is working as intended.

**Comment by varjolintu** [comment]
I understand it's not an easy process. If any of the volunteers could help and maybe give some points where to start looking at the issue, then I could try to find the exact point by myself.

**Comment by dmethvin** [comment]
jQuery can manipulate an XML document and can run in an XHTML document but it's not meant to be included into an XML document directly. I'm not very familiar with Firefox plugins but [this page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts) seems to indicate the script is being *injected* into the plain XML page. That is not a scenario I'd expect to work at all.

**Comment by varjolintu** [comment]
Yes. The script is injected to the content. It's not a new thing to include jQuery and jQueryUI as a content script. Maybe I need to look for alternative methods to do modal dialogs.
