### ISSUE TITLE
position() gives incorrect position of an element in relation to its parent

### ISSUE THREAD

**Issue by nitinsbuzz** [jquery/jquery#4002]
*  What do you expect to happen?

Position() should give the position of the clicked object in relation to its parent. $(this).position() is working in v3.0.

  *  What actually happens?

It seems position() is returning the position of the first matched element of a certain class. $('.className').position() instead of $(this).position(), which is wrong, tested in v3.3.1.

Browser: Firefox

**Comment by dmethvin** [comment]
Please provide an example from jsbin.com or jsfiddle.net, as requested in the issue template. There is not enough information here.

**Comment by timmywil** [comment]
Can be reopened with a test case.
