### ISSUE TITLE
Automatically create object from html5 template tag

### ISSUE THREAD

**Issue by tschallacka** [jquery/jquery#4004]
Currently to make a jquery object from a [template ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) one has to do 

     $(document.importNode($('template#productrow').prop('content'), true));

This way the template document-fragment is cloned, added to the document in detached state and the clone is returned and wrapped in a jquery instance.

Would be nice to have a core function that implements this feature that does the 3 steps above with the given template selector.

```
$.fn.appendTemplate = function($selector, callback) {
      if(!($selector instanceof jQuery)) {
              $selector = $($selector);
      }
      var content = $selector.prop('content');
      var $template = $(document.importNode(content, true));
      if(typeof callback === 'function') {
           callback($template);
      }
      this.append($template);
}
```

So you can do code like this, to append code from a template

```
$('#producttable thead').appendTemplate('template#productrow',function($content){
    $content.find('td.record').text('foo');
    $content.find('td:not(.record)').text('bar');
});
```
https://jsfiddle.net/04fop28n/6/

And the plugin I use personally
https://github.com/tschallacka/jquery-template-support

**Comment by timmywil** [comment]
Thank you for opening an issue, but I think this is best left as a plugin, at least for now.
