### ISSUE TITLE
Changing DOM jquery

### ISSUE THREAD

**Issue by toderesa97** [jquery/jquery#4006]
### Description ###
The idea was to create a sort of paginator of questions comprised by a ``p`` and ``buttons``. When a user clicks on whatever the button is, the next question appears. Our approach (@victcebesp and I) was to modify the question and its answer using JQUERY. Both question and answer are within a ``div`` with an ID. The buttons has two classes ``btn btn-primary`` (the ones provided by bootstrap).

### Problem
When a button is clicked, the content changes once!. Our gut feeling is that jquery is not keeping track of changes of the DOM after having loaded them. We are using version 3.2.1.

### Code ###

```
var json = {
    1 : {"pregunta" : "¿Sufre de insuficiencia cardiaca?", 
               "opciones": ["Si", "No"]
    },
    2 : {"pregunta" : "¿Sufre de hipertensión arterial?", 
               "opciones": ["Si", "No"]
    },
    3 : {"pregunta" : "Seleccione su rango de edad", 
               "opciones": ["Menor de 65 años", "Entre 65 y 74 años", "Mayor de 75 años"]
    },
    4 : {"pregunta" : "¿Tiene usted diabetes?", 
               "opciones": ["Si", "No"]
    },
    5 : {"pregunta" : "¿Ha pasado por un ictus transitorio?", 
               "opciones": ["Si", "No"]
    },
    6 : {"pregunta" : "¿Tiene alguna enfermedad vascular periférica, coronaria o aórtica?", 
               "opciones": ["Si", "No"]
    },
    7 : {"pregunta" : "Sexo", 
               "opciones": ["Hombre", "Mujer"]
    }
};

var currentValue = 0;
var question_module = $('#question-module')
var index = 1;
    
$('.option').click(function(){
    currentValue += parseInt($(this).attr('id'));
    $('#index').text(index);
    index++;
    var options = "";
    json[index].opciones.forEach(function(option){
        options += `<div class="option">${option}</div>`;
        
    });
    var content = `<p id="question">${json[index].pregunta}</p>
                            ${options}`;
    console.log(content);
    $('#question-module').html(content);
});

```

and the HTML

```
<h4>Step <span id="index"></span> of 7</h4>
<div class="flex-vertical" id="question-module">
           <p id="question"></p>
           <a class="btn btn-primary option" id="0" href="final_calculador.html">Hombre</a>
           <a class="btn btn-primary option" id="1" href="final_calculador.html">Mujer</a> <!-- Solo contabiliza con otro factor -->
       </div>
```
(First question is hardcoded).

**Comment by mgol** [comment]
Please provide a test case on [JSFiddle](https://jsfiddle.net/) or [JS Bin](https://jsbin.com/) as the issue template requested. It takes more time to follow the code if we cannot see it working live.

**Comment by toderesa97** [comment]
Hello @mgol,

 [Fiddle](https://jsfiddle.net/5ywgq8oL/9/). As you might be able to see, the DOM is changed only once. 

Let me know  either if we're doing something inappropriate or if you need further information!

Thank you in advance,
TDRS.

**Comment by smisra3** [comment]
Hi @mgol ,
What you are doing incorrectly is that you are binding the click handler incorrectly. For the first time the event is binded but when the new question is loaded , the newer options does not have event binded to them. Hence the click handler won't work. Solution would be to use the power of event delegation. Bind the event to the question container and delegate to your options . Following is the correct way of binding the event in your case.

question_module.on( 'click', '.option', function(){
....
});

This will work perfectly.

**Comment by mgol** [comment]
Closing then.
