### ISSUE TITLE
jQuery .find in documents with xml namespaces fails in iOS 9

### ISSUE THREAD

**Issue by daniel-keller** [jquery/jquery#4012]
### Description ###
To search in a jquery document that contains xml namespaces you need to escape the colon
`$(document).find('namespace\\:Tag')`
however this does not work in Safari on iOS 9.8.3
jQuery claims to supports [safari on iOS 7+](http://jquery.com/browser-support/)

### Link to test case ###
In the following jsfiddle I have a simple xml document of with three "tourml:Stop" elements. I search for the three elements and print the number of elements found.

When viewed in Safari iOS 10+ three "tourml:Stop" elements are found 
When Safari iOS 9.8.3 no "tourml:Stop" elements are found.

https://jsfiddle.net/77g41ycf/14/

**Comment by dmethvin** [comment]
Probably related to https://github.com/jquery/jquery/wiki/Won't-Fix#svg-or-vml specifically https://bugs.jquery.com/ticket/4208 ?

**Comment by daniel-keller** [comment]
Yep that seems to be the issue. Thanks for the help.
