### ISSUE TITLE
Inconsistent data() results if data comes from DOMStringMap

### ISSUE THREAD

**Issue by sgreiner** [jquery/jquery#4016]
### Description ###
Depending on how the data attribute was set, jQuery returns a parsedJSON or a string.
If data-foo was set by a HTML attribute, it returns a parsed JSON.
If data-foo was set by jQuery it returns a string.

### Link to test case ###
Please look at this example:
https://codepen.io/sgreiner/pen/BrWKLr

**Comment by dmethvin** [comment]
If you set a string using the API it returns a string, even if the string happens to "look like JSON". jQuery doesn't try to parse the string passed through the API as JSON. If you know it's JSON thenparse the JSON in advance and pass that to the API.

If the documentation seems unclear you can submit a pull request to clarify, but the example seems clear to me that it only applies to `data-` attributes inside HTML.

http://api.jquery.com/data/#data-html5
https://github.com/jquery/api.jquery.com/

**Comment by sgreiner** [comment]
Regardless of the documentation, I think that the jquery API is a bit inconsistent here.

If you get data from a DOM node with the data API you can't know, wether it was set by $("#ele").data("foo", "val") or it was noted in the DOM like this <div id="ele" data-foo="val"></div>.

The return value in both cases should be the same, because using the same ele.data() method call can either returns a string or a parsed version of that string.

Now, as a developer you need to guess what you might receive.
If you get an object because it was an HTML5 data attribute and you wanted a string, you need to JSON.stringify().
If you get a string because it was set via .data( key, value ) and wanted an object you need to parse it.

So many "if else" only because .data( key )'s output depends on how the data was set.

But I guess, no discussion about that is wanted...

**Comment by dmethvin** [comment]
It's more that it's doing what it's documented to do, and changes to make it do something else will break a lot of code. I actually think that parsing the data was the wrong idea (that is, it should always return a string), but I can't change the API to make it not parse the data for the same reason.
