### ISSUE TITLE
Make jQuery.fx.interval use private

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#4018]
Migrate has to make some shaky assumptions about the implementation of core's animations in order to warn about `jQuery.fx.interval`. It would be simpler if we used a private value for the interval value (basically just hard-code the default `13`) so that *any* use of `jQuery.fx.interval` could be indentified as deprecated. There is a slight risk that someone might be changing that value but it seems unlikely since we are already ignoring it except for two rare-ish cases: 1) IE9 always, 2) browsers when the document is hidden.

In addition, per some discussion on https://github.com/jquery/jquery-migrate/pull/298 we may want to change from `document.hidden` to `document.visibilityState` since the standard has changed. From looking at caniuse.com it seems like IE10/IE11 support `rAF`  and `document.hidden` but not  `document.visibilityState` so I am not sure that is possible until we drop their support.

**Comment by mgol** [comment]
What caniuse.com entry? https://caniuse.com/#feat=pagevisibility shows full IE 10+ support, the [MDN entry](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState) also claims IE 10 supports it. It seems that support is identical to `document.hidden`, isn't it?

**Comment by dmethvin** [comment]
When I go into the console debugger in IE11 I see `document.hidden -> false` but `document.pageVisibility -> undefined` so they must have been going by the older spec.

**Comment by mgol** [comment]
You're right. It seems both MDN & Can I Use are out of date here.

**Comment by dmethvin** [comment]
The problem seems to be that this is "Page Visibility 2" which had a first draft in March 2016. The previous "Page Visibility" is what IE10/11 use. The references don't seem to distinguish the two. The [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) mentions `visibilityState` but doesn't call it out in the browser support matrix.

**Comment by markelog** [comment]
Yeah, I think I might have considered `visibilityState` (remember considering a lot of things). But don't remember the details.

> When I go into the console debugger in IE11 I see document.hidden -> false but document.pageVisibility -> undefined

`document.pageVisibility`? Perhaps, you meant `document.visibilityState`? I do see it returning meaningful values in IE10/11.

If we do consider it, we should be really careful and like do some extensive testing I would suggest. I.e. just to see our test suite pass is not enough I think

**Comment by mgol** [comment]
Ha, I do see `document.visibilityState` in IE 11 & 10. Where did `document.pageVisibility` come from? :)

**Comment by dmethvin** [comment]
Oh duh, I got the property wrong! Nevermind.

**Comment by timmywil** [comment]
Simplified this ticket and just made it about privatizing our use of `interval`. The potential switch to `document.visibilityState` is a separate issue and I think those kind of what-if ideas are best tracked in the Roadmap.

**Comment by mgol** [comment]
I missed it but we already removed `jQuery.fx.interval` in #5017.
