### ISSUE TITLE
Transfer jquery-datepicker npm package namespace

### ISSUE THREAD

**Issue by cmswalker** [jquery/jquery#4020]
### Description ###

Hello, I created [this npm package](https://www.npmjs.com/package/jquery-datepicker) back before there was a decoupled version of jquery-datepicker that could be consumed w/ bundlers and esmodules. 

I was happy to see that [jquery-ui-datepicker-with-i18n](https://www.npmjs.com/package/jquery-ui-datepicker-with-i18n) is now available + it has the i18n files which are easy to resolve. I was actually about to update mine with the i18n files but came across this first and it works wonderfully!

I'd like to transfer ownership of the `jquery-datepicker` package namespace on npm to y'all in favor of the the `jquery-ui-datepicker-with-i18n` package contents. Can we coordinate this? Also, I think a readme for the new package would be a valuable addition.

**Comment by mgol** [comment]
Hi! The [jquery-ui-datepicker-with-i18n](https://www.npmjs.com/package/jquery-ui-datepicker-with-i18n) package is not maintained by jQuery or jQuery UI teams but by a separate person so I'm not sure if we can do anything here. AFAIK the team only maintains the [jquery-ui](https://www.npmjs.com/package/jquery-ui) package.

In any case, this is the jQuery bug tracker and jQuery UI has a separate repository & team, UI-related issues should be reported at https://bugs.jqueryui.com/. Thanks!
