### ISSUE TITLE
jQuery.type error for AsyncFunction

### ISSUE THREAD

**Issue by Zhang-Wei-666** [jquery/jquery#4027]
!function(){

    var toString = {}.toString,
          asyncFn = async function asyncFn(){/* ... */};

    console.log( typeof( asyncFn ) );// function
    console.log( jQuery.type( asyncFn ) );// object
    console.log( toString.call( asyncFn ) );// [object AsyncFunction]

    // class2type[ "[object AsyncFunction]" ] = "function";

}();

**Comment by mgol** [comment]
Thanks for the report. However, we've deprecated `jQuery.type` in 3.3.0 so we don't plan to fix edge cases in its behavior. There's an open API ticket to document that deprecation: https://github.com/jquery/api.jquery.com/issues/1076.

**Comment by Zhang-Wei-666** [comment]
but ...

$( async function(){
    // This callback is not run ...
})

**Comment by gibson042** [comment]
Such callbacks have been invoked [since version 3.3.0](https://github.com/jquery/jquery/commit/a16339b8933f115da3661f3d3f64854c3fa60bdc): https://jsfiddle.net/p7k1yzoq/2/

**Comment by Zhang-Wei-666** [comment]
@gibson042 O Thanks,  i'm wrong, I'm allways use for version 3.1.0
