### ISSUE TITLE
Invalid support.scrollboxSize() function result

### ISSUE THREAD

**Issue by isukces** [jquery/jquery#4029]
`support.scrollboxSize()` returns sometimes `true` and sometimes `absolute` value depending on browser zoom. 

Problem was found on:
* jquery 3.3.1,
* Chrome 64bit ver. 64.0.3282.186 and 65.0.3325.181,
* Windows 10 operating system, resolution 1920x1080, normal system font (100%),
* Browser zoom : 90% and 110%.

![chrome-jquery-problem](https://user-images.githubusercontent.com/6094336/38128881-d2167d3e-33fc-11e8-902a-afc679b39cf6.gif)

```
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    var sbs = $.support.scrollboxSize();
    var text = sbs==='absolute' ? "WRONG": "OK";
    alert("support.scrollboxSize() returns " + sbs + " so its " + text + ".");
});
</script>
</head>
<body>
    <p>Change font size in chrome with ctrl+wheel and reload page.</p>
</div>
</body>
</html>
```
Originally problem was found on Serenity framework https://github.com/volkanceylan/Serenity/issues/3412 .

**Comment by gibson042** [comment]
Confirmed. Similarly to #3808, zoom can apparently mess with offsetWidth even though it's not supposed to.
