### ISSUE TITLE
Store dist output from Travis CI

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#4031]
I am sometimes less than certain that a fix actually resolves a reported issue, due to environmental issues like OS dependence or browser zoom (cf. #4029). We should be able to direct issue reporters to the files built by recent PR CI jobs for confirmation, as we have with [jquery-git.js](http://code.jquery.com/jquery-git.js) and [Jenkins](http://builds.jenkins.jquery.com/jquery/73d7e6259c63ac45f42c6593da8c2796c6ce9281/test/jquery.js) for commits in the master branch.

However, since the files contain arbitrary user code, we should make sure that they aren't available from a commonly-trusted domain like jquery.com. Options that come to mind:
* Register a new domain.
* Push to GitHub.
* Push to S3/file sharing service/etc.
* Persuade Travis CI to store them.

**Comment by timmywil** [comment]
I like this idea, but moved this issue to the [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap).
