### ISSUE TITLE
on() with not a function

### ISSUE THREAD

**Issue by matrix0123456789** [jquery/jquery#4033]
When you try to run code like this:
`    $(document).on('click','div',undefined);`
or
`$('div').click({})`
this line of code passes without any exceptions. but when you click on div there is error in JS console, that is verry difficult to diagnose

VM627 jquery-1.8.3.js:3058 Uncaught TypeError: ((jQuery.event.special[handleObj.origType] || {}).handle || handleObj.handler).apply is not a function

I think jQuery should check typeof and throw exception when it is not a function.

**Comment by mgol** [comment]
jQuery generally doesn't validate user input, it'd make the library way bigger than it is. You need to use the parameter types that match what's in the API docs (https://api.jquery.com/on/). If you want to have parameter validation, consider using TypeScript together with the [@types/jquery](https://www.npmjs.com/package/@types/jquery) package.
