### ISSUE TITLE
Memory leak in IE 11 (Screens loaded in iFrame)

### ISSUE THREAD

**Issue by sandeepbyathagururajarao** [jquery/jquery#4034]
### Description ###
We are using JQuery v3.3.1 with migration script.
As per discussion with Microsoft support team. They are guessing some IE browser memory leak in the screens loaded in iframe due to circular reference in the UI elements and jquery. Please find the reference image URL. https://imgur.com/1ej9Lb7 and https://imgur.com/nwQ6Gnr. They are suspecting that JQuery is holding the handle to these orphan DOM and IFrame Window references.

**Comment by dmethvin** [comment]
It's not possible to run a screenshot in the debugger. However, from the screenshot it looks like the references are coming from some code that isn't jQuery core. Do you have a test case that only uses jQuery core?

**Comment by dmethvin** [comment]
Can be reopened with a test case that only uses jQuery core.
