### ISSUE TITLE
SPA in jquery

### ISSUE THREAD

**Issue by lakinmohapatra** [jquery/jquery#4036]
Can we expect a future version of jquery which will allow to develop single page apps using jquery syntax?
This will be helpful for lots of jquery developers.

**Comment by dmethvin** [comment]
People develop SPAs in jQuery all the time. A large SPA usually needs more structure than jQuery alone can provide. Do a [Google search](https://www.google.com/search?q=spa+jquery) for more information.

**Comment by lakinmohapatra** [comment]
If this is the case, jquery can't compete with angular , react etc. 
It's gonna die soon.
