### ISSUE TITLE
Feature request: Warn when selector returns zero matches

### ISSUE THREAD

**Issue by ericnewton76** [jquery/jquery#4037]
### Feature request: ###
jQuery should warn when a selector returns zero matches somehow.    I ask mostly because typically the selector statement is the start of a chain:

This statement ends up being a no-op when an element with id=elementid doesn't exist (for whatever reason, document not ready, server didnt emit it, etc)
```
$("#elementid").on("click", function(e) { console.log("click!"); });
```

Problem is, that no-op is subtle, and difficult to log.  You can test for it first, but this breaks the chain
```
if($("#elementid").length==0) {
  console.log('didnt find #elementid');
} else {
  $("elementid").on("click", function(e) { console.log("click!"); });
}
```

I suppose you could extend jquery, but this particular implementation breaks the chain.
```
jQuery.fn.exists = function () {
    return this.length !== 0;
}
```

Perhaps switching the implementation allows for chaining, but now requires inserting "exists" into all jQuery code:
```
jQuery.fn.exists = function () {
   if(this.length == 0) console.warn("jQuery warning: selector '%s' found zero items.", this.selector);
   return this;
}

$("#elementid").exists().on("click", function(e) { console.log("click!"); });
```

### Testing ###
1. Start with an empty DOM, 
2. `var $result = jQuery(".definitelyNoClassDefined")`
3. `assert.that($result.length.is(0))`
3. check that console.log is invoked with "jQuery warning: Selector '.definitelyNoClassDefined' returns zero items."

I feel like this could easily be plugged into all patch releases since its not a breaking change.

EDIT: this started with https://stackoverflow.com/questions/49803687/can-jquery-generate-warning-when-a-selector-finds-nothing-when-chaining

**Comment by dmethvin** [comment]
It's completely normal for a selection to return nothing. You can use this to your advantage, for example to chain operations on a selection that may not be there. It actually is nicer in the no-elements case since you don't need extra logic to handle it.

If you need to be sure a selection matched something you can check the `.length` property.  People would definitely be annoyed by a console message for a condition that is not an error. You could do it as a plugin if you like:

```js
jQuery.fn.warnIfEmpty = function( msg ) {
  if ( this.length === 0 ) {
    console.warn(msg || "jQuery selection is empty");
  }
};

$(".nosuchthing").warnIfEmpty().addClass("notthere");
```

**Comment by mgol** [comment]
@dmethvin A small correction:
```js
jQuery.fn.warnIfEmpty = function( msg ) {
  if ( this.length === 0 ) {
    console.warn(msg || "jQuery selection is empty");
  }
  return this;
};

$(".nosuchthing").warnIfEmpty().addClass("notthere");
```
:)

**Comment by dmethvin** [comment]
haha yes!
