### ISSUE TITLE
jquery breaks when running $(window).text() while an iframe with different doamin exist on the page.

### ISSUE THREAD

**Issue by adi-darachi** [jquery/jquery#4038]
When running $.text() on window, while there are cors iframes on the page throws an exception.

STR:
1. Open a page with that have at least one iframe from a different domain.
2. run $(window).text() . 

 *  What do you expect to happen?
> Return empty string/undefined
*  What actually happens?
> Throws exception (cors/security 18)
 *  Which browsers are affected? 
> (WebKit/gecko based at least)

minimal testcase -> https://jsfiddle.net/xpvt214o/127474/

* why is it happening? 
> 
a. it seems that Sizzel.getText function assumes that if the parameter sent have no .nodeType property, it must be an array, so it's start iterating the element indexes,
b. when adding iframes to the document there is a reference also on the window object
window[0...n] (n - the number of frames on the page)

so when sending the window object, it iterates also the inaccessible windows and try to access their .nodeType prop which throws an exception.

**Comment by adi-darachi** [comment]
It's not my application.
Our client have the following line on every event executed from jQuery:
$(this).text()
And his application works fine.
When he itegrate my company code, which adds and iframe from other origin the same function break.

**Comment by mgol** [comment]
jQuery doesn't validate user input, it's expected that only supported method signatures will be used (according to what https://api.jquery.com returns), behavior for other inputs is undefined.

jQuery would get much larger were we to add input validation, it'd also slow down the library. If you want your input validated, consider using TypeScript which includes jQuery type definitions in the `@types/jquery` package.

You need to tell your client to change the invalid code.
