### ISSUE TITLE
The callback function parameters changes position when [].map is called

### ISSUE THREAD

**Issue by pfncfen** [jquery/jquery#4042]
### Description ###
![image](https://user-images.githubusercontent.com/3774176/38924448-8f309896-432f-11e8-875b-13d6ce26de33.png)

It may caused by 
`	map: function( callback ) {
		return this.pushStack( jQuery.map(this, function( elem, i ) {
			return callback.call( elem, i, elem );
		}));
	},`
the callback.call( elem, i, elem ) may be callback.call( elem, elem, i ) to make the map function act the same when called from different method.

**Comment by dutchenkoOleg** [comment]
See description in api  

http://api.jquery.com/jQuery.map/  
__Description:__ _Translate all items in an array or object to new array of items._

http://api.jquery.com/map/  
__Description:__ _Pass each element in the current matched set through a function, producing a new jQuery object containing the return values._


It's not same

**Comment by dmethvin** [comment]
Yep, it's an unfortunate but documented inconsistency in those two APIs. It's been that way for too long to change.

**Comment by pfncfen** [comment]
thank you for ur explanation. sry for the inconvenience caused.
