### ISSUE TITLE
rtagName wrong regular expression

### ISSUE THREAD

**Issue by youen123** [jquery/jquery#4047]
### Description ###
I think the regular expression in src/manipulation/var/rtagName.js has some problems. it should return the first html tag, but it failed.
```
var res = /<([a-z]+[^\/\0>\x20\t\r\n\f]*)/i.exec('<b>low</b>')  // null
```
### Link to test case ###
```
var res = /<([a-z]+[^\/\0>\x20\t\r\n\f]*)/i.exec('<b>low</b>')  // null
```

**Comment by mgol** [comment]
This is internal jQuery code. What's the actual bug you're experiencing? Could you provide a test case on JS Bin or JSFiddle?

**Comment by youen123** [comment]
Actually, it may not be a bug. 
`$.parseHTML('<h1>123</h1>')` and `$.parseHTML('<p>123</p>')` both return a correct value. But  Execute to `tag = ( rtagName.exec( elem ) || [ "", "" ] )[ 1 ].toLowerCase();`(in buildFragment.js)，`<h1>123</h1>` will return `h1`,  but `<p>123</p>` will return `null`, not `p`.

And maybe there is a tag with only one letter which also needs a warp in future, but `rtagName` can't get it.

**Comment by dmethvin** [comment]
Since this is internal code and no bug is exposed I think it's safe to close.
