### ISSUE TITLE
Ready is no longer executing synchronously

### ISSUE THREAD

**Issue by psaltelk** [jquery/jquery#4048]
Good day,

I have realized that Ready is no longer executing synchronously and  from what I gather this was done so that all handlers can be executed even when one fails. I have one handler and would like to execute it synchronously as I want the load to only execute after my handler in Ready is done. Is there a work around to get the described behavior?

**Comment by dmethvin** [comment]
Yes, `$(document).on("DOMContentLoaded", ... )` should work, assuming you attach it before the event fires.  Followups to StackOverflow please, since this is not a bug report.
