### ISSUE TITLE
Remove deprecated methods in 4.0.0

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#4056]
### Description ###
We've deprecated some methods in 3.x (like `jQuery.camelCase`), we should remember to remove them all in 4.0. Looking at `deprecated.js` should be a good start; other APIs to remove:
- [ ] `jQuery.cssProps`.
- [x] `jQuery.cssNumber` (removed in #4055).

**Comment by ShashankaNataraj** [comment]
@mgol I want to submit a PR for this.. Is this issue still relevant?

**Comment by mgol** [comment]
@ShashankaNataraj It is, though we're not working on jQuery 4.0 yet. You can submit a PR, though. You'd need to look at each of the deprecated APIs; some are in `deprecated.js`, some are only deprecated in docs: [3.0](https://api.jquery.com/category/deprecated/deprecated-3.0/) & [3.3](https://api.jquery.com/category/deprecated/deprecated-3.3/) and some may only have an API issue created but the deprecations are not documented yet: https://github.com/jquery/api.jquery.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+deprecate.

For ones that have API docs tickets, we should first document the deprecation before we remove it on `master`; we're a little understaffed when it comes to content sites (like api.jquery.com) so especially there help would be appreciated. Thanks!

**Comment by mgol** [comment]
PR: #4364
