### ISSUE TITLE
Memory leak issue in .html() with injected inline script elements.

### ISSUE THREAD

**Issue by apjquery** [jquery/jquery#4065]
jQuery Version : 1.11.4(currently we are used) and 3.3.1

Forum Link:
https://forum.jquery.com/topic/memory-size-is-keep-on-increased-in-every-navigation-of-jquery-ajax-call.

The injected inline scripts by .html(), should be GCed.
The injected inline scripts by .html() are not GCed because the script elements has root as global.
Browsers tested: Edge, Chrome.

Steps to Reproduce:
1. Open the URL in Edge browser [Fiddle](https://jsfiddle.net/5w8zc7tb/6/).
2. Run the demo fiddle. 
3. Open F12 Developer tools and select Memory Tab.
4. Start the Profiling session.
5. Take initial heap snapshot.
6.  Press Action One button and Take another heap snapshot.
7.  Press Action two button and take another heap snapshot.
8.  Repeat step 6 and 7.
9.  Compare the last snapshots.

As shown below screen shots.
1.
![memory leak 1](https://user-images.githubusercontent.com/38877074/39465018-8f1017f6-4d3e-11e8-855b-b425306dc9ed.png)

2. 
![memory leak 2](https://user-images.githubusercontent.com/38877074/39464947-1e118d8c-4d3e-11e8-951e-abafa5e42af1.png)

Demo Files:
[demo.zip](https://github.com/jquery/jquery/files/1963200/demo.zip)

**Comment by gibson042** [comment]
The leak stems from your own code defining new global functions. Observe this reduction of your fiddle in which scripts are still evaluated but do not affect global state: https://jsfiddle.net/5w8zc7tb/10/
