### ISSUE TITLE
Npm install contents are wrong

### ISSUE THREAD

**Issue by colinalford** [jquery/jquery#4068]
### Description ###
Whenever I run `npm install jquery`, there is no dist file available. The contents of my node_modules folder look nothing like what I would expect.

These are the contents of the folder.

<img width="427" alt="screen shot 2018-05-06 at 2 03 02 pm" src="https://user-images.githubusercontent.com/7810527/39676318-8bb49bf8-5136-11e8-848e-8f8d234aa7e1.png">

I also tried running "npm run build", but because there is no gruntfile (I see a bower file instead?), it just errors. 

Am I missing something?

**Comment by dmethvin** [comment]
When I run `npm install jquery` I see the dist directory. So, what version of npm and node do you have installed?

**Comment by colinalford** [comment]
npm: 5.6.0
node: 10.0.0

**Comment by dmethvin** [comment]
This is what I get, Windows 10 with msysgit. There's nothing wrong with npm or the version of jquery that is on npm as far as I can tell, so it must be some sort of local config issue or antivirus.
```bash
$ ls
$ npm -v
5.6.0
$ node -v
v8.11.1
$ npm install jquery
npm WARN saveError ENOENT: no such file or directory, open 'C:\wamp\www\xjunk\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\wamp\www\xjunk\package.json'
npm WARN xjunk No description
npm WARN xjunk No repository field.
npm WARN xjunk No README data
npm WARN xjunk No license field.
+ jquery@3.3.1
added 1 package in 1.042s
$ ls node_modules/jquery/
AUTHORS.txt  LICENSE.txt  README.md  bower.json  dist  external  package.json  src
$ ls node_modules/jquery/dist
core.js  jquery.js  jquery.min.js  jquery.min.map  jquery.slim.js  jquery.slim.min.js  jquery.slim.min.map

```

**Comment by colinalford** [comment]
@dmethvin I had some coworkers confirm that `npm install jquery` works as expected for them as well. Wondering if, like you said, I have some local config issue causing the problem.
