### ISSUE TITLE
error in the npm instalation

### ISSUE THREAD

**Issue by SimonLopezJara** [jquery/jquery#4071]
![image](https://user-images.githubusercontent.com/35228419/39791002-ae7363b2-52fe-11e8-92e1-f0a86379cad9.png)

this issues is in the json of the npm instalation

**Comment by SimonLopezJara** [comment]
![image](https://user-images.githubusercontent.com/35228419/39791002-ae7363b2-52fe-11e8-92e1-f0a86379cad9.png)
this is the image, correct

**Comment by dmethvin** [comment]
I just installed jQuery myself on Windows 10 yesterday while triaging gh-4068 and it worked fine. Can you seek help on StackOverflow, and examine your npm debug log?
