### ISSUE TITLE
'd' is null or not an object  , missing object 

### ISSUE THREAD

**Issue by hebiao6446** [jquery/jquery#4072]
IE 8   ,  yes ,   Windows 7    
jquery-3.3.1.min.js  , error at line 296  ,  info ： 'd'  is empty or not an object .

**Comment by dmethvin** [comment]
IE8 is not supported by any version of jQuery under development. Ask for help on StackOverflow.

**Comment by hebiao6446** [comment]
Thinks， I have done ...  
I got a jQuery code  from www.baidu.com (The biggest Chinese search net  )  ;
perfected .....
