### ISSUE TITLE
Add render function to elements

### ISSUE THREAD

**Issue by bbreukelen** [jquery/jquery#4074]
### Description ###
Requesting for a "render" function on elements.
From time to time I run into a situation where I need to apply several changes to a DOM element but I need the browser to render the first change before applying the next.
For this I add a render function to jQuery like this:

`jQuery.fn.extend({
  render: function() {
    this[0].offsetHeight
    return this;
  }
});`

Then I can use it like this:
_$("#progressIndicator")
    .css({ transition: "width 0s", width: "0%" })
    .render()
    .css({ transition: "" });_

In this example, it disables the CSS transition animation while resetting the progressBar and when done, it re-enabled the transition for the next change.

Calling an element's offsetHeight forces the browser to render the changes and execute the rest of the code after rendering. Adding the render function allows for easy chaining.

I'm thinking it would be beneficial for others to add this render function by default. I notices that there are many questions asked and articles written to get around the issue of rendering changes which could all be solved easily this way.
Thanks

**Comment by timmywil** [comment]
Thanks for opening an issue. However, I think this is a good candidate for a plugin.
