### ISSUE TITLE
$("<body><div></div></body>") not work

### ISSUE THREAD

**Issue by GeassCoder** [jquery/jquery#4077]
### Environment: ###
chrome 66
jQuery 3.3.1

### Test Cases: ###
* normal case 1
```javascript
var a = $("<div><div></div></div>");
console.log(a[0]);
// <div><div></div></div>, as expected
```
* norml case 2
```javascript
var b = $("<body></body>");
console.log(b[0]);
// <body></body>, as expected
```
* buggy
```javascript
var c = $("<body><div></div></body>");
console.log(c[0]);
// <div></div>, but expected to see <body><div></div></body>
```

**Comment by dmethvin** [comment]
This is documented and is expected behavior unfortunately. jQuery is not intended to create whole documents or document bodies.

http://api.jquery.com/jQuery/#jQuery2

> When passing in complex HTML, some browsers may not generate a DOM that exactly replicates the HTML source provided. As mentioned, jQuery uses the browser's .innerHTML property to parse the passed HTML and insert it into the current document. During this process, some browsers filter out certain elements such as <html>, <title>, or <head> elements. As a result, the elements inserted may not be representative of the original string passed.

Notice it has nothing to do with jQuery, here is a plain DOM example:
http://jsbin.com/tituluz/edit?html,js,console
