### ISSUE TITLE
prev().hide issue on jQuery slim

### ISSUE THREAD

**Issue by Chiarucia** [jquery/jquery#4078]
Here is a simple code where I notice issue on jQuery slim (https://jsfiddle.net/Chiarucia/st825n9r/ )
(actually this is example from http://api.jquery.com/hide/).
**1. What I expect to happen:**
a) By clicking "Hide" button last span child starts to hide, the previuose and so on. 
b) By pressing "Show" - all spans appears slowly.
**2. What actually happens:**
a) By clicking "Hide" button last span child hides.
b) By pressing "Show" - last span child shows (fast).

Here is the same code that runs perfect on jQuery (edge) (https://jsfiddle.net/Chiarucia/6ypjt24f/).

Simplified code https://jsfiddle.net/Chiarucia/nhwer8st/ ,where I expect hiding or showing slowly - on **jQuery slim** outputs **fast**. On **jQuery 3.3.1** or else is working perfect.
Browser - google Crome (Version 66.0.3359.13)

Is it a bug on jQuery slim? 
(i am brand new to codding world, so can't figure out more)

_**Links to test code:**_
jQuery slim not working perfect https://jsfiddle.net/Chiarucia/st825n9r/
jQuery (edge) working perfect https://jsfiddle.net/Chiarucia/6ypjt24f/

**Comment by dmethvin** [comment]
jQuery Slim does not include the effects module, which is needed to do animations. It still works to hide and show elements but it happens immediately.
