### ISSUE TITLE
Lowercasing empty elements

### ISSUE THREAD

**Issue by LHdT** [jquery/jquery#4085]
### Description ###

When I try to get val() from an undefined property as a coder I spect something like "cannot obtain value from undefinde propertes"

When trying to get the value of an undefined propertie I got problem of lowercasing instead of null pointer JS equivalent, it seems it need a validation earlier procesing.

I've only tested chrome and Edge, iexplore doesn't even load my views so i cannot properly test this case

Thanks so much for your work

### Link to test case ###
Havent upload anything, just get some descriptive screenshots

![image](https://user-images.githubusercontent.com/13876611/40352434-1bf3645e-5daf-11e8-954c-5aa6de75913f.png)

![image](https://user-images.githubusercontent.com/13876611/40352491-39e793cc-5daf-11e8-9a5e-7849be02c7c0.png)
![image](https://user-images.githubusercontent.com/13876611/40352684-bf9cd112-5daf-11e8-86a3-ed693dc11fd6.png)

**Comment by dmethvin** [comment]
This doesn't sound like a bug in jQuery, and the report doesn't provide the information requested by the issue template. See if you can get assistance at StackOverflow.

**Comment by LHdT** [comment]
I'm a bachellor degree in computing with 10 years of experience coding back-end, when you try to aply a function to something ( sth.val()), and you get an exception related to an lowercase error from a function which doesn't check if income is apropiate for subfunction (toLowerCase) is oviously a bug, still i rather ejoy your bugs instead of trying to convince someone about a bug that is obviously a bug instead of the point of being a random feature without control.
