### ISSUE TITLE
Bug Request in version 3.3.1

### ISSUE THREAD

**Issue by Piyush3079** [jquery/jquery#4088]
### Description ###
I have a form with a submit button. I want to prevent the default submit event of the form to make an ajax request. I have used this function.
`$(document).on('submit', '#dbStatsForm', function (event) {
         event.preventDefault();
         console.log('event fired');
});`
But it is not working for me.

`$('#dbStatsForm').on('submit', function (event) {
      event.preventDefault();
      console.log('Event fired');
});`
It is working fine for me.
Is the above method is deprecated in new version.
My current version is 3.3.1

**Comment by dmethvin** [comment]
Please ask for help on StackOverflow.
