### ISSUE TITLE
What is the meaning of the "using" key in the offset object?

### ISSUE THREAD

**Issue by 1Jesper1** [jquery/jquery#4090]
https://github.com/jquery/jquery/blob/3d732cca6b5076a9d13eee98e2b075b37384cd91/src/offset.js#L63

**Comment by dmethvin** [comment]
Looks like it was added 9 years ago in  daffb954e397bd5d9f8e9aaedab6c0baa9609e1e to support jQuery UI's extended `.position()` features. I wouldn't use it directly since it's not documented.

https://github.com/jquery/jquery-ui/blob/74f8a0ac952f6f45f773312292baef1c26d81300/ui/position.js#L313

**Comment by 1Jesper1** [comment]
Ah! Thanks for the clarification!
