### ISSUE TITLE
.filter() in slim version 3.3.1 works abnormally

### ISSUE THREAD

**Issue by mmhuang** [jquery/jquery#4091]
I was using a slim version in a project.  not sure if this is the right place to report this bug.
https://code.jquery.com/jquery-3.3.1.slim.min.js
here is the screenshot in ie-edge console:
![image](https://user-images.githubusercontent.com/1270508/40882716-1cc0c706-671d-11e8-938a-32a2b2431af2.png)

it seem that the filter function not work in slim version.
when I switch to other version,  https://code.jquery.com/jquery-1.12.4.min.js. It works as expected.

**Comment by timmywil** [comment]
Thank you for reporting an issue. However, it works for me. https://jsfiddle.net/zjhjvnvk/1/

**Comment by mmhuang** [comment]
thanks for the feed back. sorry to reply late. As I had used the full version to solve my problem.

And I could not repeat the issue in the pure jQuery environment either. Maybe there is some conflict in my environment. 

anyway, I would update you if I can repeat the error.
thanks for your time.
