### ISSUE TITLE
position: relative being added to elements when calling .offset() with arguments

### ISSUE THREAD

**Issue by will-e-yams** [jquery/jquery#4092]
### Description ###
When calling `.offset` with arguments, `setOffset` is called which will set the position to 'relative' if the element either has no position or has `position: static`.

Is there a reason that the position is not reverted to the previous state before exiting the function?

Seems like it should collect the current style here
```
	// Set position first, in-case top/left are set even on static elem
	if (position === "static") {
		elem.style.position = "relative";
	}
```
and set it back after calculations.

### Test case ###
Exposed when using affix plugin for Bootstrap 3.3.7

### Workaround ###
Set style in css with `position: fixed !important`

**Comment by timmywil** [comment]
Thank you for opening an issue. However, this is intended behavior because setting an offset requires a non-static position. This is documented [here](https://api.jquery.com/offset/#offset2).

**Comment by will-e-yams** [comment]
@timmywil, sure, but `elem.style.position` only reads inline styles not styles resulting after CSS. Because of this any styles set in CSS are ignored. Meaning that in order to set any positional offset on anything where the position is defined in CSS the CSS will require `!important` just to override this behavior.

From a developer's perspective, given that it's not immediately apparent **what** is setting the inline style to relative and therefore overriding the CSS, I still think it reasonable to reset the inline style to the initial value.

**Comment by timmywil** [comment]
I don't want to make developers search long for the source of the style setting. However, it doesn't seem to me that it would be hard to guess because `.offset` just set top and/or left in the style attribute as well. And even if it was, the best we can do is document the behavior. I don't see a use case for setting an offset that doesn't work. And as you point out, there is an easy workaround.
