### ISSUE TITLE
Seirous bug with jquery acessing window

### ISSUE THREAD

**Issue by batata004** [jquery/jquery#4093]
Hi,

For long time I use the "disable-web-security" flag when launching my Chrome so I can open windows (using javascript) in different domains and still being able to access the window's content.

This is for testing/debugging purposes and LOTS of devs use this "disable-web-security" flag from Chrome to do all sorts of tests. It's a very important feature.

HOWEVER, even if the browser ALLOWS external domains access to iframes/windows in different domains for some weird reason JQUERY 3.x shows an error when trying to access these iframes/windows. JQUERY 1.12.4 didnt have have this problem.

You can check this bug very easily: 

1) first close all chromes windows/instances on your computer and then relaunch it using the disable-web-security flag, something like the code below:

start "Chrome" "chrome.exe" --disable-web-security 

2) after that acess this jsfiddle -> http://jsfiddle.net/36sewf1p/1/   -> this fiddle will simply open a window (with an external domain) and after 5 seconds will try to access its content.

3) check your browser console (in the jsfiddle tab) and you will see this error:

Blocked a frame with origin "http://fiddle.jshell.net" from accessing a cross-origin frame.
    at http://fiddle.jshell.net/_display/:34:24

**Comment by mgol** [comment]
This has nothing to do with jQuery so your jQuery 1.12.4 code must have been doing something differently: https://jsfiddle.net/36sewf1p/4/

Also, I don't recommend using `--disable-web-security` with few exceptions, it shouldn't be a norm. In particular, this flag should never be used with the default user profile or with any profile logged in to any service on any webpage; always specify user profile via the `--user-data-dir` option in tandem with the `--disable-web-security` flag.
