### ISSUE TITLE
a feature Request: build a Jquery Module to a plugin 

### ISSUE THREAD

**Issue by scil** [jquery/jquery#4106]
The slim version is wonderful, but sometimes I need animate which is not included in jquery.slim.js.

I found that I can build a custom jquery, but I wonder whether there's posibility to build a jquery module into a jquery plugin?

I think it would be an great another feature following jquery.slim.js.

**Comment by timmywil** [comment]
Thanks for opening an issue. The effects module can already be imported using AMD, but we have plans on our [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap) to switch the module format to es6 and transpile to other formats.
