### ISSUE TITLE
Case insensitive attribute selection does not work with filter(), find() etc.

### ISSUE THREAD

**Issue by expressiveco** [jquery/jquery#4111]
Case insensitive attribute selection works fine with $() but it does not work with filter(), find() etc. on Chrome 67.0.3396.87 (Official Build) (64-bit) for Windows.
- The error is; Syntax error, unrecognized expression: div[name='a' i]
- Even $() does not  work on Firefox and IE.
- It seems Sizzle could not fall back to document.querySelector() always.

```
<body>
  <div name=A>AA</div>
  <div name=B>BB</div>
</body>

$("[name='a' i]").each(function(){
  console.log($(this).html());
});
$("div[name='a' i]").each(function(){
  console.log($(this).html());
});
$("div").filter("[name='a' i]").each(function(){
  console.log($(this).html());
});
$("body").find('div[name=a i]').each(function(){
  console.log($(this).html());
});
$("body").find("div[name='a' i]").each(function(){
  console.log($(this).html());
});

```

**Comment by alecpl** [comment]
I don't think it supports CSS4 at all. See https://github.com/jquery/sizzle/issues/237.

**Comment by timmywil** [comment]
Indeed, Sizzle doesn't support that selector. However, @gibson042 is planning a rewrite of the native selector engine in jQuery for an upcoming major version (either 4 or 5) that would not rely on Sizzle at all. Selectors like this would then be supported. In the meantime, you can use a function in `.filter` that uses the native `.matches` directly.
