### ISSUE TITLE
Issue with hover

### ISSUE THREAD

**Issue by trivia21** [jquery/jquery#4112]
### Description ###

var userInfoBoxHovered=this._$userInfoBox.is(":hover")  

Syntax error, unrecognized expression: unsupported pseudo: hover

Was working in JQuery1.8.2, not working with JQuery1.11.1

Can you suggest what got changed.

**Comment by dmethvin** [comment]
The template requested a test case. Only jQuery 3 is supported. For other questions please ask on StackOverflow.
