### ISSUE TITLE
Invalid encoding of %20 char sequence in $.ajax post, put body

### ISSUE THREAD

**Issue by ermouth** [jquery/jquery#4119]
### Description ###
Seems that jQuery 3 replaces `%20` char sequence to `+` in a request body during PUT and POST. A request like 
```javascript
$.ajax({
  method: 'put', 
  url: '/test/doc', 
  dataType: 'json',
  headers: {'content-type':'application/json'},
  data: JSON.stringify({val:'%20'})
})
```
actually sends `{"val":"+"}` in 3.2.1 and 3.3.1, both with Migration tools. 

jQuery however 2.x behaves correctly.

Update. Seems the reason is this block https://github.com/jquery/jquery/blob/master/src/ajax.js#L617-L621. It assumes `s.contentType` is the only source of `Content-Type` header, but there can be `s.headers['content-type']`, which later (https://github.com/jquery/jquery/blob/master/src/ajax.js#L648-L650) overrides `s.contentType` value.

**Comment by dmethvin** [comment]
I agree with your analysis! If we're letting the header override the setting I guess we should honor both. Would you like to file a pull request?

**Comment by ermouth** [comment]
Yes, but it may take a time to read all community guides. However hope a fix for this is not urgent )

**Comment by Gomathy97** [comment]
Hi, is there any update on this?

**Comment by mgol** [comment]
@Gomathy97 The summary is in https://github.com/jquery/jquery/pull/4123#issuecomment-404341143 & https://github.com/jquery/jquery/pull/4123#issuecomment-404722799. We welcome PRs, that's the easiest way to make the fix be available sooner.

**Comment by wenz** [comment]
I've sent a PR that implements the functionality as suggested in the #4123 discussion; based on the research and code by @ermouth

**Comment by mgol** [comment]
The mentioned PR by @wenz: #4650.
