### ISSUE TITLE
jquery.js:4745 Uncaught TypeError: Cannot read property 'createDocumentFragment' of undefined

### ISSUE THREAD

**Issue by xulayen** [jquery/jquery#4120]
My File looks like this,i know is load() throw error 'Cannot read property 'createDocumentFragment' of undefined',but i do not kown why

import jQuery from 'jquery';
(function ($) {

.....

 $("#sidebar-menu").append(_html);

......

     $(window).load(function () {
            window.setTimeout(function () {
                $('#ajax-loader').fadeOut();
            }, 300);
        });

....

})(jQuery);

**Comment by xulayen** [comment]
Okay! is version quesion !!!!  is used to lasted ,and use 2.2.0 is ok ！~~~~

**Comment by timmywil** [comment]
Support can be found on stackoverflow.com or the [jquery forums](https://forum.jquery.com).

**Comment by xulayen** [comment]
@timmywil thks
