### ISSUE TITLE
Custom self-closing element tags are being misidentified as the parent of following sibling elements

### ISSUE THREAD

**Issue by Colinh84** [jquery/jquery#4132]
### Description ###
When using custom-named self-closing element tags in a document, jQuery selectors such as `.prev()` and `.parent()` identify such tags as the parent element of following sibling elements, instead of correctly identifying them as siblings.

### Link to test case ###

https://codepen.io/Colinh84/pen/OwWGNp

**Comment by dmethvin** [comment]
The HTML parser agrees with us. Open DevTools and look. I won't look up the parser rules that give this result, but as far as jQuery is concerned it is reflecting what the browser parsed. Feel free to drop in a spec reference here.
