### ISSUE TITLE
npm install jquery-slim installs 3.0.0 instead of >=3.3.1

### ISSUE THREAD

**Issue by inoas** [jquery/jquery#4133]
Also: There are no instructions on how to install jquery-slim via npm on https://jquery.com/download/

**Comment by timmywil** [comment]
Thanks for opening an issue. jquery-slim on npm is not an official package and not managed by jQuery. The jquery-slim.js file you're looking for can be found in the dist of the official "jquery" package. Downloading is the same for both, but you'll need to reference the slim file instead.

```
$ npm install jquery
```

```
import jQuery from 'jquery/dist/jquery.slim'
```
