### ISSUE TITLE
css() function called with ";" added in the values did nothing

### ISSUE THREAD

**Issue by xxjapp** [jquery/jquery#4135]
### Description ###

This is the right way to call css().

```
object.css("border", "solid red 1px");
```

This is the wrong way to call css(). But It will be better to do the same thing as the first. Or to output a warning. Currently it will do nothing.

```
object.css("border", "solid red 1px;");
```

### Link to test case ###

https://jsfiddle.net/xpvt214o/480451/

**Comment by mgol** [comment]
Thanks for the report. There are a lot of possible CSS-like syntaxes you could want to have like `object.css("border: solid red 1px");` but we can't support them all. A semicolon is not part of a value so allowing it at the end might be confusing. I don't think we want to make the syntax more ambiguous than it already is.

**Comment by xxjapp** [comment]
@mgol, thanks for your answer. 
Then a warning on console will be appreciated for saving user’s time, maybe.

**Comment by timmywil** [comment]
Thanks for the issue. However, a warning like this would only be warranted if it happened A LOT, and maybe not even then. It would require parsing the value, which could slow things down significantly. A semi-colon is obviously not part of the value and I think the best we can do is document that. Honestly, the [border examples](https://api.jquery.com/css/#css-propertyName-value) should be sufficient.
