### ISSUE TITLE
Changes in How to Handle Anonymous Functions

### ISSUE THREAD

**Issue by qzoke** [jquery/jquery#4137]
Simple Eample Code . How it looks right Now : 

$(document).ready(function(){
    $("p").click(function(){
        $(this).hide();
    });
});

Mostly, it's a single function as a handler. So, if we can code jquery as java look alike functions that would be awesome. How it can be :

$.document.ready(){
    $("p").click(){
        $.this.hide();
    }
}

I am sure, it can be easily compiled where functions ready(){} will be changed to ready(function(){}); during compiling

Also, I have a second option but a little less human readable
$ready(document){
    $click("p"){
        $hide(this);
    }
}

Do let me know if its a good idea

**Comment by timmywil** [comment]
Thanks for your issue. However, this repo is not for support questions. You can find help at stackoverflow.com or on [gitter](https://gitter.im/jquery/jquery).
