### ISSUE TITLE
Too verbose reporting?

### ISSUE THREAD

**Issue by loldrup** [jquery/jquery#4142]
When comparing two non-equal objects that have the same prototype chain, it seems unnecessary to report all the properties on their prototype chain. This because we can know a priori that the difference between the two objects won't be found in their prototype object.
This behavior discourages test driven development, as having several failing tests quickly result in insurmountable amounts of lines being logged. Generating all that HTML slows down the browser.

This issue has two legs:
a. Should the `Diff`-section log all prototypal properties when we know that the difference between the objects can't reside among the prototypal properties?
b. Should qUnit log all prototypal properties when logging an object?

Example:
`a.deepEqual( new THREE.Vector3(1,2,3), new THREE.Vector3(2,3,4), "Bare bone test of excessive logging of prototype properties" );`

This test gives this output:

`Bare bone test of prototype comparison@ 80 ms
Expected: 	

{
  "add": function add( a, b ){
    [code]
  },
  "addScalar": function addScalar( a ){
    [code]
  },
  "addScaledVector": function addScaledVector( a, b ){
    [code]
  },
  "addVectors": function addVectors( a, b ){
    [code]
  },
  "angleTo": function angleTo( a ){
    [code]
  },
  "applyAxisAngle": function applyAxisAngle( a, b ){
    [code]
  },
  "applyEuler": function applyEuler( a ){
    [code]
  },
  "applyMatrix3": function applyMatrix3( a ){
    [code]
  },
  "applyMatrix4": function applyMatrix4( a ){
    [code]
  },
  "applyProjection": function applyProjection( a ){
    [code]
  },
  "applyQuaternion": function applyQuaternion( a ){
    [code]
  },
  "ceil": function ceil(){
    [code]
  },
  "changeBasis": function changeBasis( a, b, c, d ){
    [code]
  },
  "clamp": function clamp( a, b ){
    [code]
  },
  "clampLength": function clampLength( a, b ){
    [code]
  },
  "clampScalar": function clampScalar( a, b ){
    [code]
  },
  "clone": function clone(){
    [code]
  },
  "copy": function copy( a ){
    [code]
  },
  "cross": function cross( a, b ){
    [code]
  },
  "crossVectors": function crossVectors( a, b ){
    [code]
  },
  "distanceTo": function distanceTo( a ){
    [code]
  },
  "distanceToManhattan": function distanceToManhattan( a ){
    [code]
  },
  "distanceToSquared": function distanceToSquared( a ){
    [code]
  },
  "divide": function divide( a ){
    [code]
  },
  "divideScalar": function divideScalar( a ){
    [code]
  },
  "dot": function dot( a ){
    [code]
  },
  "equals": function equals( a ){
    [code]
  },
  "floor": function floor(){
    [code]
  },
  "fromArray": function fromArray( a, b ){
    [code]
  },
  "fromAttribute": function fromAttribute( a, b, c ){
    [code]
  },
  "fromBufferAttribute": function fromBufferAttribute( a, b, c ){
    [code]
  },
  "getColumnFromMatrix": function getColumnFromMatrix( a, b ){
    [code]
  },
  "getComponent": function getComponent( a ){
    [code]
  },
  "getPositionFromMatrix": function getPositionFromMatrix( a ){
    [code]
  },
  "getScaleFromMatrix": function getScaleFromMatrix( a ){
    [code]
  },
  "isVector3": true,
  "length": function length(){
    [code]
  },
  "lengthManhattan": function lengthManhattan(){
    [code]
  },
  "lengthSq": function lengthSq(){
    [code]
  },
  "lerp": function lerp( a, b ){
    [code]
  },
  "lerpVectors": function lerpVectors( a, b, c ){
    [code]
  },
  "manhattanDistanceTo": function manhattanDistanceTo( a ){
    [code]
  },
  "manhattanLength": function manhattanLength(){
    [code]
  },
  "max": function max( a ){
    [code]
  },
  "min": function min( a ){
    [code]
  },
  "multiply": function multiply( a, b ){
    [code]
  },
  "multiplyScalar": function multiplyScalar( a ){
    [code]
  },
  "multiplyVectors": function multiplyVectors( a, b ){
    [code]
  },
  "negate": function negate(){
    [code]
  },
  "normalize": function normalize(){
    [code]
  },
  "project": function project( a ){
    [code]
  },
  "projectOnPlane": function projectOnPlane( a ){
    [code]
  },
  "projectOnVector": function projectOnVector( a ){
    [code]
  },
  "reflect": function reflect( a ){
    [code]
  },
  "rejectOnVector": function rejectOnVector( a ){
    [code]
  },
  "round": function round(){
    [code]
  },
  "roundToZero": function roundToZero(){
    [code]
  },
  "set": function set( a, b, c ){
    [code]
  },
  "setComponent": function setComponent( a, b ){
    [code]
  },
  "setEulerFromQuaternion": function setEulerFromQuaternion(){
    [code]
  },
  "setEulerFromRotationMatrix": function setEulerFromRotationMatrix(){
    [code]
  },
  "setFromCylindrical": function setFromCylindrical( a ){
    [code]
  },
  "setFromMatrixColumn": function setFromMatrixColumn( a, b ){
    [code]
  },
  "setFromMatrixPosition": function setFromMatrixPosition( a ){
    [code]
  },
  "setFromMatrixScale": function setFromMatrixScale( a ){
    [code]
  },
  "setFromSpherical": function setFromSpherical( a ){
    [code]
  },
  "setLength": function setLength( a ){
    [code]
  },
  "setScalar": function setScalar( a ){
    [code]
  },
  "setX": function setX( a ){
    [code]
  },
  "setY": function setY( a ){
    [code]
  },
  "setZ": function setZ( a ){
    [code]
  },
  "sub": function sub( a, b ){
    [code]
  },
  "subScalar": function subScalar( a ){
    [code]
  },
  "subVectors": function subVectors( a, b ){
    [code]
  },
  "toArray": function toArray( a, b ){
    [code]
  },
  "transformDirection": function transformDirection( a ){
    [code]
  },
  "unproject": function unproject( a ){
    [code]
  },
  "x": 2,
  "y": 3,
  "z": 4
}

Result: 	

{
  "add": function add( a, b ){
    [code]
  },
  "addScalar": function addScalar( a ){
    [code]
  },
  "addScaledVector": function addScaledVector( a, b ){
    [code]
  },
  "addVectors": function addVectors( a, b ){
    [code]
  },
  "angleTo": function angleTo( a ){
    [code]
  },
  "applyAxisAngle": function applyAxisAngle( a, b ){
    [code]
  },
  "applyEuler": function applyEuler( a ){
    [code]
  },
  "applyMatrix3": function applyMatrix3( a ){
    [code]
  },
  "applyMatrix4": function applyMatrix4( a ){
    [code]
  },
  "applyProjection": function applyProjection( a ){
    [code]
  },
  "applyQuaternion": function applyQuaternion( a ){
    [code]
  },
  "ceil": function ceil(){
    [code]
  },
  "changeBasis": function changeBasis( a, b, c, d ){
    [code]
  },
  "clamp": function clamp( a, b ){
    [code]
  },
  "clampLength": function clampLength( a, b ){
    [code]
  },
  "clampScalar": function clampScalar( a, b ){
    [code]
  },
  "clone": function clone(){
    [code]
  },
  "copy": function copy( a ){
    [code]
  },
  "cross": function cross( a, b ){
    [code]
  },
  "crossVectors": function crossVectors( a, b ){
    [code]
  },
  "distanceTo": function distanceTo( a ){
    [code]
  },
  "distanceToManhattan": function distanceToManhattan( a ){
    [code]
  },
  "distanceToSquared": function distanceToSquared( a ){
    [code]
  },
  "divide": function divide( a ){
    [code]
  },
  "divideScalar": function divideScalar( a ){
    [code]
  },
  "dot": function dot( a ){
    [code]
  },
  "equals": function equals( a ){
    [code]
  },
  "floor": function floor(){
    [code]
  },
  "fromArray": function fromArray( a, b ){
    [code]
  },
  "fromAttribute": function fromAttribute( a, b, c ){
    [code]
  },
  "fromBufferAttribute": function fromBufferAttribute( a, b, c ){
    [code]
  },
  "getColumnFromMatrix": function getColumnFromMatrix( a, b ){
    [code]
  },
  "getComponent": function getComponent( a ){
    [code]
  },
  "getPositionFromMatrix": function getPositionFromMatrix( a ){
    [code]
  },
  "getScaleFromMatrix": function getScaleFromMatrix( a ){
    [code]
  },
  "isVector3": true,
  "length": function length(){
    [code]
  },
  "lengthManhattan": function lengthManhattan(){
    [code]
  },
  "lengthSq": function lengthSq(){
    [code]
  },
  "lerp": function lerp( a, b ){
    [code]
  },
  "lerpVectors": function lerpVectors( a, b, c ){
    [code]
  },
  "manhattanDistanceTo": function manhattanDistanceTo( a ){
    [code]
  },
  "manhattanLength": function manhattanLength(){
    [code]
  },
  "max": function max( a ){
    [code]
  },
  "min": function min( a ){
    [code]
  },
  "multiply": function multiply( a, b ){
    [code]
  },
  "multiplyScalar": function multiplyScalar( a ){
    [code]
  },
  "multiplyVectors": function multiplyVectors( a, b ){
    [code]
  },
  "negate": function negate(){
    [code]
  },
  "normalize": function normalize(){
    [code]
  },
  "project": function project( a ){
    [code]
  },
  "projectOnPlane": function projectOnPlane( a ){
    [code]
  },
  "projectOnVector": function projectOnVector( a ){
    [code]
  },
  "reflect": function reflect( a ){
    [code]
  },
  "rejectOnVector": function rejectOnVector( a ){
    [code]
  },
  "round": function round(){
    [code]
  },
  "roundToZero": function roundToZero(){
    [code]
  },
  "set": function set( a, b, c ){
    [code]
  },
  "setComponent": function setComponent( a, b ){
    [code]
  },
  "setEulerFromQuaternion": function setEulerFromQuaternion(){
    [code]
  },
  "setEulerFromRotationMatrix": function setEulerFromRotationMatrix(){
    [code]
  },
  "setFromCylindrical": function setFromCylindrical( a ){
    [code]
  },
  "setFromMatrixColumn": function setFromMatrixColumn( a, b ){
    [code]
  },
  "setFromMatrixPosition": function setFromMatrixPosition( a ){
    [code]
  },
  "setFromMatrixScale": function setFromMatrixScale( a ){
    [code]
  },
  "setFromSpherical": function setFromSpherical( a ){
    [code]
  },
  "setLength": function setLength( a ){
    [code]
  },
  "setScalar": function setScalar( a ){
    [code]
  },
  "setX": function setX( a ){
    [code]
  },
  "setY": function setY( a ){
    [code]
  },
  "setZ": function setZ( a ){
    [code]
  },
  "sub": function sub( a, b ){
    [code]
  },
  "subScalar": function subScalar( a ){
    [code]
  },
  "subVectors": function subVectors( a, b ){
    [code]
  },
  "toArray": function toArray( a, b ){
    [code]
  },
  "transformDirection": function transformDirection( a ){
    [code]
  },
  "unproject": function unproject( a ){
    [code]
  },
  "x": 1,
  "y": 2,
  "z": 3
}

Diff: 	

{
  "add": function add( a, b ){
    [code]
  },
  "addScalar": function addScalar( a ){
    [code]
  },
  "addScaledVector": function addScaledVector( a, b ){
    [code]
  },
  "addVectors": function addVectors( a, b ){
    [code]
  },
  "angleTo": function angleTo( a ){
    [code]
  },
  "applyAxisAngle": function applyAxisAngle( a, b ){
    [code]
  },
  "applyEuler": function applyEuler( a ){
    [code]
  },
  "applyMatrix3": function applyMatrix3( a ){
    [code]
  },
  "applyMatrix4": function applyMatrix4( a ){
    [code]
  },
  "applyProjection": function applyProjection( a ){
    [code]
  },
  "applyQuaternion": function applyQuaternion( a ){
    [code]
  },
  "ceil": function ceil(){
    [code]
  },
  "changeBasis": function changeBasis( a, b, c, d ){
    [code]
  },
  "clamp": function clamp( a, b ){
    [code]
  },
  "clampLength": function clampLength( a, b ){
    [code]
  },
  "clampScalar": function clampScalar( a, b ){
    [code]
  },
  "clone": function clone(){
    [code]
  },
  "copy": function copy( a ){
    [code]
  },
  "cross": function cross( a, b ){
    [code]
  },
  "crossVectors": function crossVectors( a, b ){
    [code]
  },
  "distanceTo": function distanceTo( a ){
    [code]
  },
  "distanceToManhattan": function distanceToManhattan( a ){
    [code]
  },
  "distanceToSquared": function distanceToSquared( a ){
    [code]
  },
  "divide": function divide( a ){
    [code]
  },
  "divideScalar": function divideScalar( a ){
    [code]
  },
  "dot": function dot( a ){
    [code]
  },
  "equals": function equals( a ){
    [code]
  },
  "floor": function floor(){
    [code]
  },
  "fromArray": function fromArray( a, b ){
    [code]
  },
  "fromAttribute": function fromAttribute( a, b, c ){
    [code]
  },
  "fromBufferAttribute": function fromBufferAttribute( a, b, c ){
    [code]
  },
  "getColumnFromMatrix": function getColumnFromMatrix( a, b ){
    [code]
  },
  "getComponent": function getComponent( a ){
    [code]
  },
  "getPositionFromMatrix": function getPositionFromMatrix( a ){
    [code]
  },
  "getScaleFromMatrix": function getScaleFromMatrix( a ){
    [code]
  },
  "isVector3": true,
  "length": function length(){
    [code]
  },
  "lengthManhattan": function lengthManhattan(){
    [code]
  },
  "lengthSq": function lengthSq(){
    [code]
  },
  "lerp": function lerp( a, b ){
    [code]
  },
  "lerpVectors": function lerpVectors( a, b, c ){
    [code]
  },
  "manhattanDistanceTo": function manhattanDistanceTo( a ){
    [code]
  },
  "manhattanLength": function manhattanLength(){
    [code]
  },
  "max": function max( a ){
    [code]
  },
  "min": function min( a ){
    [code]
  },
  "multiply": function multiply( a, b ){
    [code]
  },
  "multiplyScalar": function multiplyScalar( a ){
    [code]
  },
  "multiplyVectors": function multiplyVectors( a, b ){
    [code]
  },
  "negate": function negate(){
    [code]
  },
  "normalize": function normalize(){
    [code]
  },
  "project": function project( a ){
    [code]
  },
  "projectOnPlane": function projectOnPlane( a ){
    [code]
  },
  "projectOnVector": function projectOnVector( a ){
    [code]
  },
  "reflect": function reflect( a ){
    [code]
  },
  "rejectOnVector": function rejectOnVector( a ){
    [code]
  },
  "round": function round(){
    [code]
  },
  "roundToZero": function roundToZero(){
    [code]
  },
  "set": function set( a, b, c ){
    [code]
  },
  "setComponent": function setComponent( a, b ){
    [code]
  },
  "setEulerFromQuaternion": function setEulerFromQuaternion(){
    [code]
  },
  "setEulerFromRotationMatrix": function setEulerFromRotationMatrix(){
    [code]
  },
  "setFromCylindrical": function setFromCylindrical( a ){
    [code]
  },
  "setFromMatrixColumn": function setFromMatrixColumn( a, b ){
    [code]
  },
  "setFromMatrixPosition": function setFromMatrixPosition( a ){
    [code]
  },
  "setFromMatrixScale": function setFromMatrixScale( a ){
    [code]
  },
  "setFromSpherical": function setFromSpherical( a ){
    [code]
  },
  "setLength": function setLength( a ){
    [code]
  },
  "setScalar": function setScalar( a ){
    [code]
  },
  "setX": function setX( a ){
    [code]
  },
  "setY": function setY( a ){
    [code]
  },
  "setZ": function setZ( a ){
    [code]
  },
  "sub": function sub( a, b ){
    [code]
  },
  "subScalar": function subScalar( a ){
    [code]
  },
  "subVectors": function subVectors( a, b ){
    [code]
  },
  "toArray": function toArray( a, b ){
    [code]
  },
  "transformDirection": function transformDirection( a ){
    [code]
  },
  "unproject": function unproject( a ){
    [code]
  },
  "x": 21,
  "y": 32,
  "z": 43
}  `

**Comment by mgol** [comment]
It doesn’t look like a jQuery bug report. Did you mean QUnit?

**Comment by loldrup** [comment]
I totally meant qUnit
