### ISSUE TITLE
$.extend returns incorrect result if string as the 2nd parameters

### ISSUE THREAD

**Issue by aivannikov** [jquery/jquery#4144]
Here is the function call with bug

$.extend({ name: "John" }, "abc");

It returns the following:
{
    0: "a",
    1: "b",
    2: "c",
    name: "John"
}
but should return
{
    name: "John"
}

**Comment by mgol** [comment]
A string parameter is an incorrect input; all params need to be objects, the first one can also be `true`: https://api.jquery.com/jQuery.extend/

**Comment by aivannikov** [comment]
Yes, string parameter is incorrect, but instead of throwing an Error or just returning the first parameter - we have unpredictable result.
For example in this case  $.extend({ name: "John" }, true) - the method will return the first argument object - { name: "John" }
I think this should be fixed

**Comment by mgol** [comment]
jQuery doesn't validate input to its public API, it'd get much bigger & slower if it started doing that. If you care about such validation consider using TypeScript which has type definitions for jQuery and will throw an error if you try to use it incorrectly.
