### ISSUE TITLE
.height() can give a negative number

### ISSUE THREAD

**Issue by HolgerJeromin** [jquery/jquery#4145]
```html
<html>
	<head>
		<title>Negative height</title>
		<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
		</head>
		<body>
		<div style="display: none; height: 300px;">
			<div id="targetDiv" style="border: 8px solid red; top: 20%; bottom: 20%;"></div>
		</div>
		<script>
			const container = $('#targetDiv');
			const height = container.height();
			console.log(height);  // this is -16!
		</script>
	</body>
</html>
```

**Comment by HolgerJeromin** [comment]
The problem is here:
https://github.com/jquery/jquery/blob/c9aae3565edc840961ecbeee77fb0cb367c46702/src/css.js#L92-L95

`delta` is `0` at this point and `border-top/bottom-width` is `8`. So we get `-16`.

**Comment by gibson042** [comment]
From http://api.jquery.com/height/ :
> The value reported by <code>.height()</code> is not guaranteed to be accurate when the element or its parent is hidden. To get an accurate value, ensure the element is visible before using <code>.height()</code>.

**Comment by dmethvin** [comment]
Oh ha, I missed the display none. What @gibson042 says.
