### ISSUE TITLE
Added non-passive event

### ISSUE THREAD

**Issue by PabloDescomplica** [jquery/jquery#4147]
Hi, i'm deparated with the warning in chrome:

![image](https://user-images.githubusercontent.com/23645866/43662322-df2aaeb2-973b-11e8-88b2-39f239d9ad08.png)

I'm found this page,where has the instruction for solution:
https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners?hl=pt-br

The problem are in line 4592 on jquery version 2.2.0, i change for:
`
elem.addEventListener( type, eventHandle, {'passive' = true} );
`

Another problem is :
![image](https://user-images.githubusercontent.com/23645866/43662595-d91aa3e6-973c-11e8-88c0-48f8eca2ad6a.png)

set 
`return false`
before the preventDefault on line 5011

Need more test ... it's all

**Comment by dmethvin** [comment]
If a handler requires `event.preventDefault()` you cannot use passive listeners, and it appears slick.js is doing that. This is not a jQuery issue. For more background on passive listeners see #2871 but please do not add comments there.
