### ISSUE TITLE
Offset index returns in error.

### ISSUE THREAD

**Issue by ThaumicTom** [jquery/jquery#4148]
### Description ###

Selecting with :eq() and a variable inside can return in an error if you try to manipulate the values.

### Link to test case ###

https://jsfiddle.net/ThaumicTom/738eL6qm/45/

### What I except to happen ###

If the array is [1,4] I want to select the first .grid class and fourth .inner class inside the .grid class
Hence :eq starts from 0, I subtract the values of the array by one. If I don't, it selects the second .grid class and fifth .inner class inside the second .grid class. It's like the array was [2,5] while it isn't.

### What actually happens ###

Subtracting the array values by one returns in an error (Line 2). If you don't, everything is fine, but it selects the wrong one (Line 3).

**Comment by dmethvin** [comment]
Please ask questions on a forum such as StackOverflow. If they agree it is a bug you can make an issue here.

**Comment by ThaumicTom** [comment]
I never asked a question.

**Comment by dmethvin** [comment]
This is the place to report bugs in the jQuery library.  This does not look like a bug in the library so you should visit a forum where they can help you understand what is happening.

**Comment by ThaumicTom** [comment]
Okay.
