### ISSUE TITLE
position().top calculated incorrectly

### ISSUE THREAD

**Issue by alons1** [jquery/jquery#4149]
Since upgrading from 3.1.1 to 3.3.1 i'm having a lot of issues with .top values.

On many places in my web app this property now returns the top value from it's parent.
on 3.1.1 it returned for me (at least in some places) the top value from the top of the page. (nor the parent or the element that i'm testing have any position attributes or anything special).

I can't seem to understand the exact use case in order to create an example, but switching between 3.1.1 and 3.3.1 is definitely returning very different values for me in more than one place...
And the issue is cross browser.

**Comment by alons1** [comment]
Ok I am now able to reproduce it.
When the div that i am testing is inside a table, the 'top' value is returned as '1'.
When you remove the table, it is returned from the top of the page.

http://jsfiddle.net/sectioni/usd8rwLz/8/

**Comment by dmethvin** [comment]
This looks like the same issue as gh-4044 which is still open?

**Comment by timmywil** [comment]
Agreed, this should be addressed by gh-4044.
