### ISSUE TITLE
can only insert into the body a element by the .append() method.

### ISSUE THREAD

**Issue by Flcwl** [jquery/jquery#4153]
### Description ###
> The .append() method inserts the specified content as the last child of each element in the jQuery collection (To insert it as the first child, use .prepend()).

I can add any DOM elements as childs on either side of sub DOM "P", But only can insert into the body a element by this method.

[show-case.gif](http://chuantu.biz/t6/356/1533958522x-1404795780.gif)

By the pic, you can see I click the button three times. Can only be inserted inside the body element once. I'm not sure about it.

### Link to test case ###
[https://jsfiddle.net/flcwl/ad7uw6vc/10/](https://jsfiddle.net/flcwl/ad7uw6vc/10/)

**Comment by timmywil** [comment]
Thanks for opening an issue. However, `text1` and `text2` are actually references to particular elements that may or may not get cloned depending on the way the element gets appended. The example is not valid usage. The fact that `text1` shows up more than once is just a by-product of implementation. In other words, don't try to append the same element to multiple places. A new element must be created for each append/prepend. This is how you'd accomplish what you want: https://jsfiddle.net/ad7uw6vc/14/

**Comment by Flcwl** [comment]
@timmywil  
Thank your reply. 
look it.  https://jsfiddle.net/flcwl/ad7uw6vc/15/
I'm know  the `text1` and `text2` are references to particular elements. Now I remove all `.prepend() `methods. Why just can only one element be inserted into `body` by the `.append()` method yet, though I have pressed the button many times?

**Comment by dmethvin** [comment]
There are multiple `p`, but there is only one `body`. [The docs for `append()`](http://api.jquery.com/append/) say:

> Important: If there is more than one target element, however, cloned copies of the inserted element will be created for each target except for the last one.

This code is just moving the `text2` span around the body and never creates a clone.
