### ISSUE TITLE
Unable to query a form when it has input element with name="id"

### ISSUE THREAD

**Issue by sucom** [jquery/jquery#4156]
### Description ###
Unable to query a form when it has input element with name="id"

&lt;form id="testForm2"&gt;
  &lt;input type="hidden" name="id" value="123456"&gt;
&lt;/form&gt;

> $( "#testForm2" ) ==> returns the input element !!!

&lt;form id="testForm1"&gt;
  &lt;input type="hidden" name="eid" value="123456"&gt;
&lt;/form&gt;

> $( "#testForm1" ) ==> returns form (as expected)

### Link to test case ###

[jsFiddle](https://jsfiddle.net/sucom/b3ne6omk/)

used jQuery v 3.3.1 and tested on Chrome v 68.0.3440.106 on Windows 8.1

**Comment by sucom** [comment]
Also tested in 
- Chrome Version 68.0.3440.106 (Official Build) (64-bit) on MacOS High Sierra v10.13.6(17G65)
- Chrome Version 68.0.3440.106 (Official Build) (64-bit) on Windows 10

The same issue :-(

**Comment by timmywil** [comment]
Thanks for opening an issue. However, due to native browser behavior, this is not something we can fix. I recommend avoiding input names that may conflict with selectors as those input names become properties on the form element. You are replacing a native property (`"id"`) here, which is generally bad practice.

**Comment by sucom** [comment]
Hi, Thanks for the recommendation. Please note that the "name" property has the **value** "id" as the form will be serialized with that key to send to back-end. I'm not replacing a native property.

**Comment by dmethvin** [comment]
This is a tale as old as time @sucom and not jQuery's doing, see this page: https://kangax.github.io/domlint/

See also: #2755, #3691, #3101, and #4104

**Comment by sucom** [comment]
Thanks. Got it.
