### ISSUE TITLE
jQuery.ajax method removal not documented in final release note

### ISSUE THREAD

**Issue by KuromiAK** [jquery/jquery#4159]
### Description ###
In jQuery 3.0 Release, `success, error, complete` are removed from `jQuery.ajax`. This is not documented in the [final release note](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/). The only place I can find it mentioned is the [beta release note](https://blog.jquery.com/2016/01/14/jquery-3-0-beta-released/).
> ### Removed special-case Deferred methods in jQuery.ajax ###

Please add this change to the final release note. @timmywil

**Comment by timmywil** [comment]
The blog post only highlights the major changes. What constitutes a major change can be a matter of opinion, but the important part is that changes like the removal of the `success`, `error`, and `complete` methods from the Deferred returned by `jQuery.ajax` are clearly documented in the jQuery documentation. This change is highlighted in yellow on https://api.jquery.com/jQuery.ajax/. I think that is enough.
