### ISSUE TITLE
Why running `npm run build` results in an equivalent but different jquery.min.js file?

### ISSUE THREAD

**Issue by kiewic** [jquery/jquery#4160]
### Description ###

  *  What do you expect to happen?

I was hopping to run `npm run build` in a repo without making any change, and get the exact same *dist/jquery.min.js*

  *  What actually happens?

I am getting an equivalent *dist/jquery.min.js*, but with different variable names, different line separators in some cases, and some extra parenthesis. For example:

Checked-in *min* file:

```
globalEval:function(a){var b,c=eval;a=n.trim(a),a&&(1===a.indexOf("use strict")?(b=d.createElement("script"),b.text=a,d.head.appendChild(b).parentNode.removeChild(b)):c(a))}
```

Produced *min* file:

```
globalEval:function(a){var b,c=eval;(a=n.trim(a))&&(1===a.indexOf("use strict")?(b=d.createElement("script"),b.text=a,d.head.appendChild(b).parentNode.removeChild(b)):c(a))}
```

Notice how the new produced file has more parenthesis, and one less comma.

  *  Which browsers are affected?

None

Is there any other command that will give me the exact same minified version? I would like to make some changes, and use the official tools to minify the file, but I expected to get mostly the same output, which would make (private) code reviews easier to approve.

**Comment by timmywil** [comment]
Thank you for opening an issue. We use uglify to minify jQuery and this has to do with the way uglify mangles variable names to make the file as short as possible. Off the top of my head, I'm not sure how you could get a completely idempotent minification process, but I can point you in the right direction by telling you that you'll have to look at uglify's documentation and disable certain optimizations.

**Comment by kiewic** [comment]
Thanks for the quick response. 

Notice that if I run `npm run build` multiple times in a row, the output is always the same

Even if I run it in different computers (both pointing the same branch and commit), the output files are identical.

I was expecting that if I point to tag `2.2.4`, I should get the same output that was checked-in at that point and is available for download as *jquery 2.2.4*.

It seems the differences in my output file and the checked-in file are improvement to the minification process, like using less variables, as in the example I pasted above. But, where are these improvements coming from? Was the dist files produces with different npm packages? Or can this improvements be disabled with a command line option?

Thank you.

**Comment by dmethvin** [comment]
The files may not match if any of the dependencies (or *sub-dependencies*) used to build the minified files changed since the release but were still within the version range specified in `package.json`. Recent versions of `npm` generate a `package-lock.json` file that retrieves the exact versions used for that build, which increases the odds you'll get the same result. However, jQuery 2.2.4 is too old to have that file committed because the `npm` at the time of that release did not provide it.

**Comment by kiewic** [comment]
Git it, thanks for the clarification!

**Comment by mgol** [comment]
Perhaps it wouldn't be a bad idea to add `package-lock.json` only to tags? In this way people would be able to recreate our build, this may matter for people/orgs wanting to verify if nothing bad has sneaked into the compiled file.

**Comment by dmethvin** [comment]
Oh yeah, I'd forgotten about that whole mess. It does seem like it would be handy to have it in the tagged versions, along with a note in the [distribution repo](https://github.com/jquery/jquery-dist) explaining the upsides/downsides.

**Comment by timmywil** [comment]
Still, we can't guarantee that builds are idempotent, even if the package-lock is committed. That's up to uglify.

**Comment by mgol** [comment]
@timmywil True, but - as I understand - there is no randomness in Uglify here, it's just that the build on a tag will currently use a different version due to a lack of the lockfile.
