### ISSUE TITLE
use visualViewport's value for $(window).height() 

### ISSUE THREAD

**Issue by gulping** [jquery/jquery#4161]
### Description ###
In recent Chrome,`window.visualViewport` is available to get window size.
[Window.visualViewport - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/visualViewport)

This is the only value that can follow the address bar shrinking on mobile browsers.
`window.innerHeight`, `document.documentElement.clientHeight` don't work well.

So consider to use `window.visualViewport.height` for `$(window).height() `  if possible.

----

(Ditto for `width`.)

**Comment by dmethvin** [comment]
Right now it's only supported on Chrome-ish browsers so the behavior would be different across platforms. One problem I see is that the `visualViewport` fires a resize event (and I assume the `window` does not in the same case?) so in addition to using the viewport for `$(window).height()` the user would need us to use it for `$(window).on("resize")` as well in order for the charade to be effective.

**Comment by timmywil** [comment]
Thanks for the suggestion. We'll keep this in mind for now, but we'll refrain from using it until it propagates to more browsers.
