### ISSUE TITLE
$.each breaks on string

### ISSUE THREAD

**Issue by thany** [jquery/jquery#4163]
### Description ###

When calling $.each with jQuery 3.3.1 like so:
```javascript
$.each("woohoo");
```

**What actually happens**

It breaks with an error:
```
Uncaught TypeError: Cannot use 'in' operator to search for 'length' in woohoo
```

**What I expect to happen instead**

I think it should do either one of two things:
1) Loop through the string character by character.
2) Output a more sensible error, something like "incorrect parameter type string for jQuery.each"

**Browsers affected**

* Firefox and Chrome throw the error above
* Edge throws a different error `Invalid operand to 'in': Object expected` which means the same.
* Safari throws another different error `TypeError: obj is not an Object. (evaluating '"length" in obj')` which means the same again.

I suspect this problem affects every browser.

### Link to test case ###

https://jsfiddle.net/botp2fuL/1/

### Use-case ###

I was each-ing through an object that is expected to sit in a data attribute on an element. Somehow, because of undue circumstances let's say, that data attibute is no longer rendered by the server as valid json, and is therefor passed to my code as a string, throwing the error I describe here.

Novice developers might ignore this error for too long, because it doesn't look like an error in their code. This is no excuse, but I do believe clear error messages, or expectable behaviour when doing this on purpose, helps everyone.

**Comment by mgol** [comment]
One of jQuery's design decisions is not to validate input as it would otherwise get way larger & slower. If you want parameter validation consider using TypeScript which contains jQuery type definitions in the `@types/jquery` package - then your users don't pay the cost as type information disappears in compile time.

This has been raised repeatedly in the past, you can find duplicates of this request.

**Comment by thany** [comment]
I don't think that's a good design decision then. This error is too obscure not to fix.

If you don't want to add validation or better error messages, then `$.each` should loop over the input as expected. That is to say, loop over each character, just like the `for..of` loop would.

**Comment by mgol** [comment]
This is not just `jQuery.each` problem. There are lots of APIs that may behave unexpectedly or just blow up if you provide incorrect input to them. As I said, making them all fail with helpful error messages would increase the library size significantly, especially that some of jQuery's signatures are really dynamic and accept various parameter tuples.

As I said, TypeScript or Flow are your friends if you want to catch this type of errors earlier. Maybe there are some community linters that would catch it, I'm not sure. Whatever happens, we just don't want to send such code to end-users, it should be contained in developers' machines. I don't think we'll be able to work on anything like that in the foreseeable future.

**Comment by mgol** [comment]
> Keep it in the non-minified version then. That's a development version anyway.

Lots of people import jQuery from npm and bundle & minify themselves. I'm not a fan of making the production version different from the development one for that reason.

> You still haven't responded to my original alternate: have $.each loop over each character. How about that?

I think it's likely to mask errors when someone mistakenly provide a string instead of an array with one string. Also, is iterating over string letters that common a use case? I haven't found it useful too much.

**Comment by dutchenkoOleg** [comment]
@thany please read docs - https://api.jquery.com/jQuery.each/

> **Description**: A generic iterator function, which can be used to seamlessly iterate over both objects and arrays. Arrays and array-like objects with a length property (such as a function's arguments object) are iterated by numeric index, from 0 to length-1. Other objects are iterated via their named properties.

there no primitives, such as **strings**, only objects

**Comment by thany** [comment]
> Also, is iterating over string letters that common a use case? I haven't found it useful too much.

> there no primitives, such as strings, only objects

Fact of the matter is that strings *are* iterable. A simple `for..in` loop will prove this ;)

**Comment by thany** [comment]
I'm talking vanilla for-loops to demonstrate that strings are iterable, just like arrays.
On top of that, in the docs it clearly states:
> Arrays and array-like objects with a length property (such as a function's arguments object) are iterated by numeric index, from 0 to length-1.

That includes strings! Because strings are array-like, have a length property, and characters can be accessed by index.

If `$.each` isn't going to iterate strings, it should say in the docs:
> Arrays and array-like objects with a length property (such as a function's arguments object), **except strings**, are iterated by numeric index, from 0 to length-1.

--
PS, in my [previous comment](https://github.com/jquery/jquery/issues/4163#issuecomment-417587718) I meant to say `for..of` which *does* iterate over strings, whereas `for..in` won't (in the way that I meant to). Oops.

**Comment by robob4him** [comment]
I understand you're talking about altering how JQuery handles different types for $.each; might I offer that the gap between current functionality and the proposed functionality isn't large enough to warrant the overhead?

Your proposed functionality could be easily afforded (in ES6) with `$.each(..."woohoo")`. The overhead is negligible for the developer and significant for the library (due to error catching, type checking, etc) as previously noted.

(see: https://stackoverflow.com/questions/6484670/how-do-i-split-a-string-into-an-array-of-characters/38901550#38901550)

**Comment by dmethvin** [comment]
There is a cost to changing, testing, supporting, and documenting something. If that *something* makes sense then we might be agreeable. I just don't think it makes sense to iterate a string and in most cases where someone tries to do it in jQuery they've made a mistake. Sure we can make it do *something* and define what that is, but why? You can always split the chars to get an iterable array if that's what you really want.

**Comment by thany** [comment]
I think we're starting to repeat ourselves :)

@robob4him The point isn't to make `$.each` iterate over strings per se, but to make it *not break* in a horrific-looking way when a string is passed. Clarifying the documentation on which types are accepted exactly, would be a perfectly reasonable compromise.

**Comment by mgol** [comment]
@thany But the documentation does define which types are accepted... See https://api.jquery.com/jQuery.each/, it states only Objects and ArrayLikeObjects are accepted.

**Comment by thany** [comment]
A string is an array-like object ;)

**Comment by mgol** [comment]
@thany Our `ArrayLikeObject` is defined as:
> Either a true JavaScript Array or a JavaScript Object that contains a nonnegative integer `lengt`h property and index properties from `0` up to `length - 1`

There's a link to the type definition at the `jQuery.each` definition; it's at https://api.jquery.com/Types/#ArrayLikeObject.

**Comment by thany** [comment]
A string is a JavaScript Object that contains a nonnegative integer `length` property and index properties from `0` up to `length - 1`

The [documentation](https://api.jquery.com/Types/#ArrayLikeObject) should then be extended to say something like "but, well, except strings" in addition.

**Comment by mgol** [comment]
A string is not an object but a primitive.

**Comment by thany** [comment]
It depends who you ask.

There is definitely an object (some might call it a class) `String` with static and instance properties & functions. A string literal has properties & functions; you can definitely do stuff like `"foo".toUpperCase()` which is not typically possible with primitive values.

However it does not respond `true` to `"string" instanceof String`. One could reason that `String` just behaves weirdly because it doesn't inherit from `Object`, but that doesn't make it any less of an object, at least in my mind.

So yes, it depends how you look at it.

Some people might say "everything is an object", because javascript is a full OO language.
Some people might say "javascript has primitive values", because that's how programming languages have always worked.

**Comment by mgol** [comment]
The reason `"foo".toUpperCase()` works is auto-boxing - the method is not really invoked on the primitive `"foo"` but on its auto-boxed equivalent which is an object - an instance of `String`. This doesn't change the fact `"foo"` is not an object. I haven't heard primitives to be described as objects in JavaScript literature so I'm not sure where you take this definition from but it's incorrect.

**Comment by dmethvin** [comment]
Let's just amend http://api.jquery.com/Types/#ArrayLikeObject to say "Strings are not considered to be Array-like objects".  @thany you're welcome to file a PR to https://github.com/jquery/api.jquery.com to clarify.

**Comment by mgol** [comment]
@dmethvin Do we need a similar note on https://api.jquery.com/Types/#Object & https://api.jquery.com/Types/#PlainObject?

BTW, https://api.jquery.com/Types/#Object says "Everything in JavaScript is an object", an interesting twist in this discussion. 😆
