### ISSUE TITLE
No sourceMappingUrl since 3.0

### ISSUE THREAD

**Issue by santiagoarizti** [jquery/jquery#4166]
### Description ###

The minified files don't contain a **sourceMappingUrl** comment in them.

I looked in https://github.com/jquery/jquery/releases/tag/3.3.1
looked at the **dist/jquery.min.js** file and nothing.

I found about this because in this file from an old version you did include the **sourceMappingUrl** thing:
https://code.jquery.com/jquery-2.0.3.min.js
but in the newer versions the sourceMappingUrl is missing
https://code.jquery.com/jquery-3.3.1.min.js
and, the sourcemap actually exists at this address:
https://code.jquery.com/jquery-3.3.1.min.map

Are users who want the sourcemap supposed to edit the distributed minified file? Am I missing something?

### Link to test case ###

First couple of lines in **https://code.jquery.com/jquery-2.0.3.min.js**:
```
/*! jQuery v2.0.3 | (c) 2005, 2013 jQuery Foundation, Inc. | jquery.org/license
//@ sourceMappingURL=jquery-2.0.3.min.map
...
```
First couple of lines in **https://code.jquery.com/jquery-3.3.1.min.js**:
```
/*! jQuery v3.3.1 | (c) JS Foundation and other contributors | jquery.org/license */
...
```

**Comment by mgol** [comment]
We've removed the comment on purpose, see https://blog.jquery.com/2014/01/24/jquery-1-11-and-2-1-released/. There are many problems with including the comment, one of them being that different CDNs use different file names so the comment would have to be different for different CDNs and that kills security features like Subresource Integrity.

You can still attach the map manually via DevTools, at least Chrome supports that.

**Comment by santiagoarizti** [comment]
Thanks! I didn't know that about chrome, have a good day :)

**Comment by dmethvin** [comment]
Whoa, that just reminded me I never published that note about the incorrect map file. Just did that:
http://blog.jquery.com/2018/08/30/bad-map-file-for-jquery-1-9-1-in-the-jquery-cdn/
