### ISSUE TITLE
How to change JQuery language?

### ISSUE THREAD

**Issue by serdam55** [jquery/jquery#4168]
Hi there,

I developed a site using `ASP.NET Core` and I implemented the localization logic using [this](https://docs.microsoft.com/it-it/aspnet/core/fundamentals/localization?view=aspnetcore-2.1) documentation. I'm using `Bootstrap + JQuery` so I encountered a little problem on the localization, in particular, if I change the default language (italian) to english, I still get the validation message provided by `JQuery` in italian, and of course this is bad because the user has changed the language to english.
Is possible to tell to `JQuery` to use the english localization when the language change in someway? How can I do this?

I didn't found anything related on internet, I also opened a question [here](https://stackoverflow.com/questions/52126578/how-to-change-bootstrap-localization/52129137?noredirect=1#comment91208943_52129137) but still no good answers.

**Comment by mgol** [comment]
jQuery doesn't provide any localization features but it also doesn't display any messages to the user. Your issues must lie in different code.
