### ISSUE TITLE
The issue#8095 which was reported in version 1.4.4 doesn't fix in version 2.1.4

### ISSUE THREAD

**Issue by fishchenyu** [jquery/jquery#4169]
As issue#8095 declared, s.url could not be used as key to capture the value of 'Last-Modified' header. However, in version 2.1.4, it still use same way to capture the value of 'Last-Modified' header. Therefore, it caused ifModified caching functionality doesn't work if set "cache: false". Please help to check and revert it. Or, please tell me how does it work in proper way. Thanks for your effort to read my post anyway.

For your reference, here is the link for issue#8095, https://bugs.jquery.com/ticket/8095.

**Comment by dmethvin** [comment]
Can you provide a test case?

**Comment by fishchenyu** [comment]
I was trying to download javascript resource in ifModified caching mode by using following code block. However, it doesn't work in Chrome. Chrome will never send 'If-None-Modified'/'If-Modified-Since' header to server, and server always send back "200 OK" status.
jQuery.cachedScript = function( url, options ) {
  options = $.extend( options || {}, {
    	dataType: "script",
    	cache:false,
        ifModified:true,
    	async: false,
    	url: url
  });
  return jQuery.ajax( options );
};

$.cachedScript(url).done(function( script, textStatus ) {
	console.log( textStatus );
});

**Comment by fishchenyu** [comment]
Hi Guys, any update on above issue?

**Comment by timmywil** [comment]
Could you link the commit that changed the behavior for you in version 2.1.4? Afaict, the [test for this](https://github.com/jquery/jquery/blob/dfa92ccead70d7dd5735a36c6d0dd1af680271cd/test/unit/ajax.js#L1352) is passing and [the code is not using `s.url`](https://github.com/jquery/jquery/blob/master/src/ajax.js#L610) but `cacheURL`, which is the url without the cache buster.

I also created a fiddle and just requested a CSS file twice. Both headers are present on the 2nd request as fiddle sends etags. Note that jQuery saves lastModified and etag under the non-cached URL. https://jsfiddle.net/0br5ehxs/15/

Closing as worksforme until a more adequate test case proves there's an issue.
