### ISSUE TITLE
jQuery function filter with attribute name contains square bracket is not working

### ISSUE THREAD

**Issue by colandchan** [jquery/jquery#4170]
### Description ###
Select elements by name attribute, then use filter with selector.  If the selector contains square bracket, sometimes the filter did not work as expected.

In the test case, the first console.log returns 2 as expected.
The second console.log returns 0 which expected to be 1.

### Link to test case ###
http://jsfiddle.net/Lqv9yjn3/1/

**Comment by timmywil** [comment]
This seems valid. However, the easy workaround is to wrap your value in quotes. https://jsfiddle.net/Lqv9yjn3/10/

**Comment by dmethvin** [comment]
I know we've seen these reports before but I'm too lazy to look it up in closed issues. The CSS spec says:

> Attribute values must be identifiers or strings. - https://drafts.csswg.org/css2/selector.html#attribute-selectors

Identifiers don't have `]` in them but quoted strings can.

**Comment by timmywil** [comment]
Identifiers can have escaped characters. In this case, escaping the `]` should work.
