### ISSUE TITLE
Prevent mobile keypad when datepicker icon is triggered 

### ISSUE THREAD

**Issue by satishnani** [jquery/jquery#4171]
Hello Folks
I got an issue i think this is more like a bug. 
when i click on the datepicker icon mobile keyboard and date popup are appearing same time 

```
function addDatePickerMax(dateId, maxDays)
{ 
jQuery(dateId).datepicker({
maxDate: maxDays,
showOn: "button",
buttonImage: "static/shared/img/calendar.gif",
buttonText: "Select a Date",
buttonImageOnly: true
}); 
}
```

```
<Field component="input" type="text" id="postingDate" tabIndex="0" size="12" maxLength="10" name="postingDate"/>
<br />
mm/dd/yyyy
```
Expectation:
when click on icon only datapicker should appear mobile keyboard should be disabled.

**Comment by timmywil** [comment]
Thanks for opening an issue. However, this is better suited for the jquery datepicker plugin repo or stackoverflow.com.
