### ISSUE TITLE
jquery 3 ready function does not work correctly

### ISSUE THREAD

**Issue by planb1210** [jquery/jquery#4181]
Good afternoon!

I moved from jquery 1.11.1 to jquery 3.3.1. I have the following code on the page:
...
    <script type="text/javascript">
        function onJqueryLoad() {
            $(function () {
                console.log(document.readyState);
                 window.app = new App({
                    logsUrl: '3434'
                });
            });
        }
    </script>
    <script type="text/javascript" src="~/Scripts/jquery-3.3.1.js" defer onload="onJqueryLoad()"></script>
	...
	/// more scripts
	...
    <script type="text/javascript" src="~/Scripts/Common/App.js" defer></script>
...
In the console I see the following error:

interactive

jquery-3.3.1.js:3818 jQuery.Deferred exception: App is not defined ReferenceError: App is not defined
    
at HTMLDocument.<anonymous> (http://localhost:53228/:12:35)
    
at mightThrow (http://localhost:53228/Scripts/jquery-3.3.1.js:3534:29)
    
at process (http://localhost:53228/Scripts/jquery-3.3.1.js:3602:12) undefined

Uncaught ReferenceError: App is not defined
    
at HTMLDocument.<anonymous> ((index):12)
    
at mightThrow (jquery-3.3.1.js:3534)
    
at process (jquery-3.3.1.js:3602)

It turns out that the contents of $ (function () { were called before the App.js script was loaded, and the status of document.readyState was “interactive”.
But if you do not use “defer” when importing jquery:
<script type="text/javascript" src="~/Scripts/jquery-3.3.1.js" onload="onJqueryLoad()"></script>
then the console will have the status: “complete” and no problems will arise.
Description of the status document.readyState interactive (https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState):
"The document has finished loading and the document has been parsed, but sub-resources such as images, stylesheets and frames are still loading."
I failed to find more detailed information on whether the status “interactive” indicates that all scripts are loaded.
I checked it in the latest versions of chrome and firefox, but in Microsoft Edge no problem.
In the earlier version of jquery 1.11.1, there were no such errors.
Any thoughts?

**Comment by planb1210** [comment]
https://jsfiddle.net/uez1y7ft/2/ - if using without cash, the error appears from time to time.

**Comment by timmywil** [comment]
This issue is being tracked here: https://github.com/jquery/jquery/issues/3271
