### ISSUE TITLE
$.holdReady doesn't affect $(document).ready()

### ISSUE THREAD

**Issue by ajperez81** [jquery/jquery#4186]
Calling $.holdReady(true) doesn't have any effect, the ready event is firing anyway:

```
$.holdReady(true);
$(console.log('this should not happen')); // but it's happening anyway
```

Am I missing something, or is it a bug?

I'm using jQuery 3.3.1. Here is a jsFiddle to demonstrate the issue:  https://jsfiddle.net/ajperez81/pcsgbtk9/

**Comment by dmethvin** [comment]
It only holds off the ready event if it hasn't happened already. In the fiddle the code runs `onload` so the ready event has already passed.

**Comment by ajperez81** [comment]
Thank you Dave, you're 100% right. I didn't notice how the jsFiddle works, if I try it as a standalone HTML, it works as expected.
