### ISSUE TITLE
outerHeight() returning "NaNpx" for SVG elements

### ISSUE THREAD

**Issue by tiagofscoelho** [jquery/jquery#4189]
### Description ###
On Version 3.3.1, outerHeight() is returning "NaNpx" for `svg` elements. For other elements it is working as expected.

### Link to test case ###
On the code provided below, there are 2 labels where you can click. A `console.log` is called for each click.  When clicking in "Click on SVG" the output is "NaNpx". 

https://codepen.io/tiagofscoelho/pen/MPJgbx

**Comment by timmywil** [comment]
This is fixed in master https://codepen.io/anon/pen/RepOOw
