### ISSUE TITLE
$.offset() return wrong position when trying to scroll in safari

### ISSUE THREAD

**Issue by navalex** [jquery/jquery#4190]
### Description ###
When using `$.offset()` in a loop and try to scroll in no-scroll page, values are changing as if we were scrolling.
It seam that the Safari scroll move the document position even if there's no scroll.

Using `$.position()` can be a way to fix this problem temporaly.

**Comment by timmywil** [comment]
Thanks for opening an issue. Please provide a reduced test case from https://jsfiddle.net or https://jsbin.com to help us assess any issues.
