### ISSUE TITLE
htmlPrefilter() adds bogus element after self-closing tags

### ISSUE THREAD

**Issue by martinml** [jquery/jquery#4191]
Being `<x>` any valid element, using `htmlPrefilter()` to parse a `<br />` element inside an attribute of an `<x>` element adds a spurious `</x>` after it:

    $.htmlPrefilter('<x foo="<br />"></x>');

This returns `<x foo="<br ></x>"></x>` (note the extra `</x>` inside the `foo` attribute).

I browsed other issues and I saw that [a related one](https://github.com/jquery/jquery/issues/2221) was [marked as invalid because void elements must not have closing tags in HTML](https://github.com/jquery/jquery/issues/2221#issuecomment-94189174). This might be the same case, but [the docs](https://api.jquery.com/jQuery.htmlPrefilter/) say that "[htmlPrefilter] will greedily ensure that all tags are **XHTML-compliant**", and I understand that `<br />` is definitely valid XHTML (and this behavior ironically makes it invalid).

Is this a documentation thing, a bug (probably in the `rxhtmlTag` regex?) or am I missing something else?

**Comment by timmywil** [comment]
This issue and its workaround are documented here: [`jQuery.htmlPrefilter`](https://api.jquery.com/jQuery.htmlPrefilter/#jQuery-htmlPrefilter-html).

**Comment by gibson042** [comment]
XHTML is built upon XML, and XML does not allow `<` in attribute values (as you can see [in the W3C validator](https://validator.w3.org/check?fragment=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Cfoo%3E%0A%20%20%3Cbar%20baz%3D%22%3Cinvalid%3E%22%2F%3E%0A%3C%2Ffoo%3E)). It _is_ valid HTML5, though, and you can employ the documented workaround if you need to process such input (or if the greediness of our default processing, which doesn't exempt attribute values, interferes with your data).
