### ISSUE TITLE
Is code.jquery.com loading too slow in China

### ISSUE THREAD

**Issue by sixian67** [jquery/jquery#4194]
link: http://code.jquery.com/jquery.min.js

Can you increase the speed of this link in China?

![image](https://img30.360buyimg.com/jdsurvey/jfs/t27391/239/1229977505/123209/5da7d1d7/5bc48f2aN8c840c3f.jpg)

**Comment by dmethvin** [comment]
The jQuery CDN is a free service. If you have a business and it requires specific performance levels in China you should subscribe to a CDN that can provide performance and uptime guarantees.

**Comment by wxbug-cn** [comment]
But we have a website that has introduced your CDN. And we can't modify it. Could you send Chinese CDN to China and the cost will be provided by us?

**Comment by timmywil** [comment]
I don't think that's an option. Our CDN is generously provided by a third party and we don't control their operations. You should be able to switch to a CDN that has servers based in China.
