### ISSUE TITLE
$.show isn't working after update to 3.x for generated html not yet added to the page

### ISSUE THREAD

**Issue by bbarry** [jquery/jquery#4196]
### Description ###

Given:

```html
...
<style>
  div > div { display: none; }
</style>
...
<body>
<script>
  var t = $('<div><div>expect: display:block</div></div>');
  t.children().show();
  $('body').append(t);
</script>
</body>
```

`expect: display:block` should be displayed.

This was working in jquery 2.x  (tested in 2.2.4) but no longer works in 3.3.1

workarounds include:

* attach to page before showing (swap script lines 2 and 3)
* `t.children().css('display', 'block');`

### Link to test case ###

https://jsfiddle.net/5zm1gvpL/

**Comment by dmethvin** [comment]
We documented this in the upgrade guide: https://jquery.com/upgrade-guide/3.0/#breaking-change-show-hide-and-toggle-methods-now-respect-more-stylesheet-changes
