### ISSUE TITLE
jquery click function doesn't work on mobile websites

### ISSUE THREAD

**Issue by modiract** [jquery/jquery#4198]
It seems that the jquery click function doesn't work on mobile websites but the javascript click function does.

Let's take this website for example.  https://www.typeform.com/

Go into chrome to the mobile version: ( ctrl + shift + i ) then do,  ( ctrl + shift + m )

Add to the signup button on the website an id called "hi".

In the console now
```

$('#hi').click();  // this doesn't work

document.getElementById("hi").click(); //this does work
```

**Comment by timmywil** [comment]
Please ask for help on stackoverflow.com or [jQuery gitter](https://gitter.im/jquery/jquery).
