### ISSUE TITLE
:lt() Selector doesn't support big number

### ISSUE THREAD

**Issue by regseb** [jquery/jquery#4199]
### Description ###

_:lt() Selector_ doesn't support big number (like `Number.MAX_SAFE_INTEGER`). I think jQuery enters a loop the size of the parameter and the browser cuts off the execution because jQuery takes too long.

### Link to test case ###

https://jsbin.com/poxevawuzi/edit?html,output

```HTML
<p>Hello world !</p>
<script>
  $("p:lt(" + Number.MAX_SAFE_INTEGER + ")").map(function () {
      console.log(this.textContent);
  });
</script>
```

**Comment by mgol** [comment]
If you have that many elements on the page that you need to query `Number.MAX_SAFE_INTEGER` you have bigger problems than a crash from such a selector...

Do you have a real use case for that or were you just trying various things?

**Comment by regseb** [comment]
I have a real case where it extracts websites. We can limit the number of elements to be returned and by default I use `Number.MAX_SAFE_INTEGER` to return all the elements displayed on the page.

Roughly:

```JavaScript
class Scraper {
    constructor(size = Number.MAX_SAFE_INTEGER) {
        this.size = size;
    }

    extract() {
        return $("p:lt(" + this.size + ")");
    }
}
```

Real case:

- Module that reads the configuration: https://github.com/regseb/gout/blob/master/src/module/core/feed/script.js#L109
- Scraper that extracts the data: https://github.com/regseb/gout-scraper-regseb/blob/master/feed/leboncoin/script.js#L16

I can fix the problem with `$("p").slice(0, this.size)`. But jQuery must create an array with all the elements and then reduce the size. And I find it strange that jQuery is not limited to the number of elements in the page. In the example on JS Bin, jQuery always returns a single element, but the execution time increases by replacing `Number.MAX_SAFE_INTEGER` with:

- 1 : 8 ms;
- 100 : 9 ms;
- 10000 : 12 ms;
- 1000000 : 47 ms.

**Comment by mgol** [comment]
@gibson042 what are your thoughts?

**Comment by timmywil** [comment]
This is an extreme edge case. Rather than using a non-standard selector extension like `:lt` (adding on unnecessary parsing and evaluation), something like `.slice` is a much better option. I'd stick with that.

**Comment by regseb** [comment]
I proposed a pull request (https://github.com/jquery/sizzle/pull/429) to limit the size of the `matchIndexes` table. It uses the minimum between the `argument` and the number of HTML elements (`length`).

```JavaScript
"lt": createPositionalPseudo(function( matchIndexes, length, argument ) {
	var i = argument < 0 ? argument + length : Math.min(argument, length);
	for ( ; --i >= 0; ) {
		matchIndexes.push( i );
	}
	return matchIndexes;
}),
```

**Comment by timmywil** [comment]
Not trying to be negative, but I feel this amounts to iteration on a trivial feature that would be too underused.
