### ISSUE TITLE
Deprecate jQuery.inArray

### ISSUE THREAD

**Issue by KingSora** [jquery/jquery#4204]
If I'm not overlooking something this is fullfilled with [Array.prototype.indexOf()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf) and therefore it should be deprecated like https://github.com/jquery/jquery/issues/2961.

**Comment by mgol** [comment]
Thanks for the issue!

`Array#indexOf` is not that nice an API for this purpose as its intent is not clear. The true replacement is [Array#includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) but its browser support is not that great (that is, no IE support). Recently, we mostly deprecated APIs that had native equivalents in all supported browsers or that were too unclear had too many edge cases for us to handle (like [`jQuery.isNumeric`](https://github.com/jquery/jquery/issues/2960)).

That said, using `Array#indexOf` for this purpose is widespread so maybe it's OK. I don't have a definite opinion.

**Comment by timmywil** [comment]
We reviewed this in the weekly meeting. I agree the exact replacement doesn't have full support in our supported browsers. And `jQuery.inArray` is short and there's no rush to deprecate.

**Comment by edg2s** [comment]
>  The true replacement is Array#includes

By name, yes, but inArray is badly named in that it is actually returns an index, not a Boolean. So really indexOf is the correct replacement for current uses of inArray.

**Comment by mgol** [comment]
@edg2s Good point about the returned index. In that case, though, it'd be closest to [`Array#findIndex`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex) but that method doesn't support the `fromIndex` parameter unlike `Array#include`. So there's no perfect replacement but that would be the closest one.
