### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by vibhutitripathi12** [jquery/jquery#4205]
[This package](https://www.jsdelivr.com/package/npm/jquery?version=1.8.2) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by mgol** [comment]
We've taken over the `jquery` npm package starting with `1.11`/`2.1`. Older versions were published by another party and are not supported.
