### ISSUE TITLE
Removal of element resulted in detached DOM

### ISSUE THREAD

**Issue by brindhavenkatesan92** [jquery/jquery#4210]
I have written a component using jQuery library. While checking for possible memory leaks I came across following 2 problems.

1) Detached Fragments in jquery

[![enter image description here][1]][1]
In the above screenshot, the elements created using jquery are stored as fragments in jquery. Even when the elements are removed from the DOM using jQuery'a remove() method, the detached fragments exists.

2) Elements that are cached in jquery

[![enter image description here][2]][2]
I have removed the components using jQuery remove() method, but it appears as detached DOM since it is cached in jQuery.

Is there any way to prevent the above 2 memory leaks? I am not sure if this is because of jquery but this is what I came across. Please do guide me.

  [1]: https://i.stack.imgur.com/kVcvV.png
  [2]: https://i.stack.imgur.com/jFdYj.png

**Comment by mgol** [comment]
Can you provide a test case on [JSFiddle](https://jsfiddle.net/) or [JS Bin](https://jsbin.com/) as the issue template requested? Thanks!
