### ISSUE TITLE
`.ajax()` documentation is unclear about expectations/data type for `errorThrown`

### ISSUE THREAD

**Issue by GuyPaddock** [jquery/jquery#4211]
### Description ###
There is a seeming contradiction in the documentation for `$.ajax()`.

The docs for the `error` setting of this function indicate:
> ... The function receives three arguments: The jqXHR (in jQuery 1.4.x, XMLHttpRequest) object, a string describing the type of error that occurred and an optional exception object, if one occurred...

But later the same docs indicate:
> ... When an HTTP error occurs, `errorThrown` receives the textual portion of the HTTP status, such as "Not Found" or "Internal Server Error." ...

In addition, the docs indicate that the type of the parameter is `String`. But, based on the first sentence, it sounds like it can be either an object or a string; which is it?

Separately, it appears that the `errorThrown` will always be an empty string for HTTP errors that occur when using HTTP/2 (aka H2). This appears to be because `statusText` is always an empty string for an HTTP/2 request (more info: https://stackoverflow.com/questions/41632077/why-is-the-statustext-of-my-xhr-empty).

I'd love it for the jQuery team to weigh-in on both of these limitations in the current docs.

**Comment by timmywil** [comment]
Migrated to API repo. https://github.com/jquery/api.jquery.com/issues/1113
