### ISSUE TITLE
getResponseHeaders suffers from Object.prototype collisions

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery#4214]
Known issues: "constructor", "\_\_proto\_\_"

https://jsfiddle.net/0cj8y357/

_Originally posted by @gibson042 in https://github.com/jquery/jquery/pull/4173_

**Comment by timmywil** [comment]
Missed this connection in the commit, but fixed by https://github.com/jquery/jquery/commit/e0d941156900a6bff7c098c8ea7290528e468cf8
