### ISSUE TITLE
$.extend() has different behavior for empty array

### ISSUE THREAD

**Issue by Madyuskin** [jquery/jquery#4215]
$.extend(true, {a: 1, b: [1], c: [1]}, {a: 2, b: [], c: [3]})

returns

{a:2, b: [1], c: [3]}

whereas I expect property **b** to be overwritten the same way it has happened to properties **a** and **c**

**Comment by gibson042** [comment]
Providing `true` as the first argument performs a recursive (deep) merge, as [documented](https://api.jquery.com/jQuery.extend/#jQuery-extend-target-object1-objectN). Remove that to get a shallow merge.
