### ISSUE TITLE
Feature - .prop("disabled", true) for non-input elements

### ISSUE THREAD

**Issue by Xerotherm1c** [jquery/jquery#4216]
### Description ###

The modern web uses font icons (`<i class="fa fa-*"></i>`) or their parent `<div>` element, as well as many other "standard" html elements as buttons for the user to interact with. Personally, I prefer to use `<a>` or `<i>` tags for my buttons instead of using `<input>` or `<button>` tags because it feels dirty to have 5 to 10 `e.preventDefault();` statements, one at the top of each event handler - especially when we can just pick an element that doesn't come pre-loaded with some action(s) that we'll have to repeatedly prevent (so we do - `<a>`, `<i>`, etc.).

### An Elegant Solution ###

For numerous reasons* (see below), I will disable the button (or the element acting as a button) when clicked until the user should be allowed to use the button again. But because `.prop("disabled", true);` is not adding the `disabled` attribute to my `<i>` tag acting as a button, I have to either use `.attr("disabled", true);` which feels less clean, or resort to toggling a class name which feels comparably less elegant and less intuitive.

**`.prop("disabled, _bool_);` is just a beautiful and intuitive solution. Can we add support for it to work with non-input elements?**

Thank you for your time.

_* "For numerous reasons"_
1. Disabling a button gives good user feedback by updating the UI to reflect a button cannot currently be interacted with
2. Immediately upon a button click, exiting the function if it is disabled else setting it to disabled until the processing completes will prevent the user from accidentally triggering an event multiple times, which cuts down on unintentional (and unnecessary) server load

**Comment by timmywil** [comment]
Thanks for opening an issue. jQuery is just a JavaScript library and does its best to make working with the DOM easy, but has no control over what the browser can and can't do. `.prop` simply sets native properties on elements. The functionality corresponding to that property is not dependent on jQuery but the browser, which implements the [HTML Standard](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#enabling-and-disabling-form-controls:-the-disabled-attribute).

Also, I think you may need to have a look at the "Attributes vs Properties" section of https://api.jquery.com/prop/ to gain a better understanding of how these methods work and their purposes.

**Comment by dmethvin** [comment]
I agree, this isn't something that jQuery controls. The behavior of HTML elements is defined by the web platform standards.

Also, it is not a good idea at all to craft your own buttons or other semantic elements from elements that are not designed for that. The `<button>` element has specific *built-in* behavior that is understood by browsers and screen readers, for example tab order, focus, click activation on keyboard Enter, etc. Try using *only* a keyboard and screen reader with your handcrafted pseudo-buttons, or even better let a vision-limited person try your UI and see what kinds of issues it causes.

**Comment by Xerotherm1c** [comment]
@timmywil Ah, I didn't realize this was part of javascript's behavior (hence creating the issue in this repo). Thanks for the explanation.

@dmethvin The point about vision-limited users is a really good one. I just updated one page I'm working on to use `<button>` elements - I'm testing it and it seems you only need `e.preventDefault();` if the `<button>` element is inside a `<form>` element?
