### ISSUE TITLE
scroll-behavior: smooth is breaking simultaneous horizontal and vertical scrolling with .animate

### ISSUE THREAD

**Issue by tanyalaushkin** [jquery/jquery#4218]
### Description ###
I have an html page which has both horizontal and vertical scroll.
This html page has the css property:
scroll-behavior: smooth;
on the html element.

I try to scroll the page to a certain position, both horizontally and vertically at the same time, with the help of .animate, like this:
$("html, body").animate({ scrollTop: 5000, scrollLeft: 5000}, { duration: 1000 });
My expectation is that the page will scroll both horizontally and vertically.
The reality is that the page scrolls only horizontally.
When I try to swithch the scrollTop and scrollLeft, like this:
$("html, body").animate({ scrollLeft: 5000, scrollTop: 5000 }, { duration: 1000 });
What happens is that the page is scrolling only vertically.
When I try to call animate on one direction at a time, like this:
$("html, body").animate({ scrollTop: 5000 }, { duration: 1000 });
$("html, body").animate({ scrollLeft: 5000 }, { duration: 1000 });
What happens is that the page scrolls horizontally only.
Seems like only the last direction applied will be executed.

If the css property "scroll-behavior" is removed, the scrolling animation is happening as expected - the page scrolls both horizontally and vertically.

If I use the window.scrollTo function, like this:
window.scrollTo(5000, 5000);
with the css property 
scroll-behavior: smooth;
the page scrolls as expected, both horizontally and vertically.

This happens with the latest version of jquery (3.3.1), on chrome v. 70.0.3538.77 (Official Build) (64-bit),
and on firefox v.63.0.1 (64-bit)
This does not happen on IE, but the css property "scroll-behavior" is not supported in IE.

### Link to test case ###
https://jsfiddle.net/Lrhoba73/

**Comment by gibson042** [comment]
jQuery is setting the scrollTop and scrollLeft properties as requested, although the body element in your example isn't scrollable and therefore never keeps a nonzero value for either: https://jsfiddle.net/Lrhoba73/1/

It looks like you have an issue with the browsers implementations of smooth scrolling.
