### ISSUE TITLE
jQuery.parseJSON is missing from Deprecated 3.0 documentation page

### ISSUE THREAD

**Issue by TiTi** [jquery/jquery#4224]
### Description ###

[jQuery.parseJSON](https://api.jquery.com/jQuery.parseJSON/) is missing from [Category: Deprecated 3.0](https://api.jquery.com/category/deprecated/deprecated-3.0/)
(and also https://api.jquery.com/category/deprecated/)

milestone:3.0.0
#2800

### Link to test case ###

N/A

**Comment by mgol** [comment]
Moved to the API site repo: https://github.com/jquery/api.jquery.com/issues/1116.
