### ISSUE TITLE
.map() arguments should be switched to match $.map()

### ISSUE THREAD

**Issue by mirraj2** [jquery/jquery#4236]
### Description ###

$.map() correctly calls the callback with argument ordering of (element, index)
.map() calls the callback with argument ordering of (index, element)

.map() should be switched to match $.map() for both consistency's sake as well as to enable more concise ES6 arrow functions.  Because "this" doesn't work with ES6 arrow functions, it is more important that the "element" argument come first.

Current code:

`$("input").each((i, e) => $(e).val());`

Desired code:

`$("input").each(e => $(e).val());`

**Comment by mirraj2** [comment]
Also, hi Dave Methvin, I've worked with your son before :P

**Comment by timmywil** [comment]
We've discussed this before, but there's wayyyyyy too much code that relies on the current argument order.

**Comment by mirraj2** [comment]
@timmywil We could potentially make a new method, called like transform() or trans()

Isn't it better to make the library better than to worry about backwards compatibility?  If people don't want to use the newer, improved version of the library, they can keep using the old version.

**Comment by timmywil** [comment]
I don't think it's worth adding a new method, nor do I think the value is high enough to warrant the breaking change.

**Comment by dmethvin** [comment]
The great thing about jQuery is that you can create your own plugin that implements whatever feature you want. As @timmywil says it's just too late to "fix" this by changing the order of the arguments, We are always [hesitant to add new features](https://github.com/jquery/jquery/wiki/Adding-new-features) that users can add via their own plugins.  And hay @mirraj2, it's awesome to have @gmethvin carrying on the legacy!
