### ISSUE TITLE
`val()` returns incorrect value for changed radio button after page reload in Firefox

### ISSUE THREAD

**Issue by markparnell** [jquery/jquery#4239]
### Description ###
Firefox remembers form state when reloading the page so as not to lose user changes. In the case of radio buttons, this results in jQuery returning the incorrect value for `val()` - the returned value is based on the form default, not the actual current state.

Based on my (limited) testing, other types of form fields don't appear to be affected. E.g. checkbox state and text field value return the correct result.

Issue identified in Firefox 63.0.3 on OSX 10.13.6 (High Sierra) using jQuery 3.3.1 (earlier versions are also affected).

### Link to test case ###
https://sparkdev.com.au/jquery-radio-value-firefox.html
I wasn't able to set up a test case on jsFiddle or similar as they force the form to reload fully on each page load, overriding Firefox's native behaviour.

### Steps to reproduce ###
Using Firefox, change the radio button selection and reload the page.

Native JS reports the correct value for the selected radio button, while jQuery always returns `1` (default).

**Comment by timmywil** [comment]
Thanks for opening an issue. FF does seem to have some special behavior here, but it is unrelated to jQuery. Your native path is not doing the same thing as the jQuery path. Use the same selector as native and it the behavior will be the same: `jQuery('input[name=radio]:checked').val()`.
