### ISSUE TITLE
Dom bug

### ISSUE THREAD

**Issue by IvanDanilov** [jquery/jquery#4240]
### Description ###
If a text block (<script type="text/template">) is converted to DOM, and then try to get its content using $(...).html () - we get an empty string, through $(...).text() text only. Although in the inspector, the contents of the <script> element become a DOM.

The problem is only in Firefox (in Chrome everything seems to be all right).

User-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:64.0) Gecko/20100101 Firefox/64.0
Firefox v.64.0 (macOS)

### Link to test case ###
[See console] https://jsfiddle.net/xpvt214o/952780/

**Comment by gibson042** [comment]
Script elements are not permitted to contain child elements ([ref](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element)), so `.html()` cannot be expected to work (even though it does in some browsers). You should use the `text` or `textContent` properties of the element itself, or the jQuery `.text()` method: https://jsfiddle.net/ojaydk8z/
