### ISSUE TITLE
Bug in v3.3.1 url.indexOf

### ISSUE THREAD

**Issue by nsfrpm** [jquery/jquery#4241]
I'm using this:

    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>  

Chrome Ctrl + Shift + J says this:

jquery-3.3.1.js:9857 Uncaught TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (jquery-3.3.1.js:9857)
    at affiliations.aspx:5966
jQuery.fn.load @ jquery-3.3.1.js:9857
(anonymous) @ affiliations.aspx:5966

Note: affiliations.aspx is my page.

**Comment by gibson042** [comment]
We can't really help you without a demonstration of the problem, but that stack trace is indicating to me that you have likely invoked `load` without providing a string URL as the first argument, which is a [documented requirement](http://api.jquery.com/load/) of the method.

**Comment by nsfrpm** [comment]
Thanks Gibson for the quick reply. 

I'm not invoking the Load method at all. 

The way I read the error was that indexOf is not a function of url. That invocation appears on line 9857 of v 3.3.1

**Comment by gibson042** [comment]
```sh
$ curl --silent https://code.jquery.com/jquery-3.3.1.js | awk '
      NR>=9854 && NR<=9859 || $0 ~ /[.]load/ {
      gsub(/\t/, "    "); printf "%04d\t%s\n", NR, $0 }'
5298	            // Prevent triggered image.load events from bubbling to window.load
9854	jQuery.fn.load = function( url, params, callback ) {
9855	    var selector, type, response,
9856	        self = this,
9857	        off = url.indexOf( " " );
9858	
9859	    if ( off > -1 ) {
```
Something on your page is invoking `.load` without providing a string URL as the first argument, and it isn't jQuery itself. I'd start looking at line 5966 of whatever content is delivered to the browser as affiliations.aspx.

**Comment by nsfrpm** [comment]
My script isnt that long lol! But, thank you for taking a variable out of the equation. I'll keep looking.
