### ISSUE TITLE
Error Binding element that with template extending.chrome Version 70.0.3538.102 (Official Build) (64-bit)-macOS jquery-3.3.1.slim.min.js jquery-1.12.4.js

### ISSUE THREAD

**Issue by FwP-IDN** [jquery/jquery#4242]
### Description ###

Error Binding in base template 

### Link to test case ###

In a chunk of code

base.html
```
...
// linking to local javascript file
<a class="nav-link" href="#" id="subscriber_label">Subscriber Count: 0</a>
...
...
{% block content %}{% endblock %}
...
```

extended.html
```
{% extends "base.html" %}
{% block content %}
{% endblock %}
```

it works with this code in javascript file
```
document.getElementById("subscriber_label").innerHTML = "Subscriber Count: " + result.count;
```

but doesn't work if the code is
```
$("#subscriber_label").val("Subscriber Count: " + result.count);
```

**Comment by mgol** [comment]
From https://api.jquery.com/val/:
> The `.val()` method is primarily used to get the values of form elements such as `input`, `select` and `textarea`.

`.html()` is the equivalent of native `innerHTML`.
