### ISSUE TITLE
Use the "attr" method to get the "autoplay" attribute of any element, always returning "autoplay".

### ISSUE THREAD

**Issue by MarkingCode** [jquery/jquery#4244]
### Description ###
when I use the "attr"  method to get the "autoplay" attribute of any element ( div, span, i ....... ), always returning "autoplay". But use "getAttribute" can return the correct result.
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Demo</title>
    <script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
      $(function () {

        // Error ( always returning "autoplay" )
        console.log( $( "div" ).attr( "autoplay" ) );

        // Correct ( return "3000" )
        console.log( $( "div" ).get( 0 ).getAttribute( "autoplay" ) );
                
      })
    </script>
  </head>
  <body>

    <div autoplay="3000"></div>

  </body>
</html>
```

**Comment by timmywil** [comment]
Thanks for opening an issue. However, this is intended behavior because `autoplay` is a [boolean attribute](https://html.spec.whatwg.org/multipage/media.html#attr-media-autoplay), meaning values like `3000` are invalid.
