### ISSUE TITLE
test suite failing in Node.js smoke test suite on OSX 10.10 and 10.11

### ISSUE THREAD

**Issue by MylesBorins** [jquery/jquery#4247]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1655/nodes=osx1011/testReport/(root)/citgm/jquery_v3_3_1/

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1655/nodes=osx1010/testReport/(root)/citgm/jquery_v3_3_1/

Will dig in more after this current release to see if I can figure out what's going on

**Comment by mgol** [comment]
The links are asking for some GitHub permissions, is there something available publicly?

What Node.js version? What command exactly is failing?

OS X 10.10 & 10.11 are no longer supported by Apple. Are problems reproducible on newer macOS versions?
