### ISSUE TITLE
jQuery.ajax: make `dataType: "script"` not execute scripts on unsuccessful HTTP status

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#4250]
### Description ###

A followup of PR #4243 and an extension of issue #4126. We should stop evaluating scripts returned with an unsuccessful HTTP status when loaded via `jQuery.ajax` with `dataType: "script"`. The fix in #4243 only targets DOM manipulation.

**Comment by skrobinson** [comment]
I have a possible fix and a test case in commit 6716b75.

**Comment by mgol** [comment]
@skrobinson Your patch skips converters completely for unsuccessful responses; this is not right, it doesn't pass our test suite.

The proper fix will most likely require generalizing what was done in #4243 so that the logic is applied to all requests with `dataType: "script"`.

**Comment by skrobinson** [comment]
@mgol  Thank you for your feedback.  I've re-read #4243 and #4258 and tried again using the pattern in #4258.  I've also improved my testing and have a new attempt at a fix.

**Comment by mgol** [comment]
@skrobinson Let us know if you need any help/direction! (or if you don't have time to submit a PR so that we know we should look at it ourselves)

**Comment by mgol** [comment]
Landed, thanks @skrobinson for keeping up with our review comments!
