### ISSUE TITLE
draggable does not 

### ISSUE THREAD

**Issue by yahalom** [jquery/jquery#4260]
I use the latest jquery_ui code (1.12.1)
When dragging a draggable window in IE 11  there is a <div> that appears underneath with a bigger frame. The issue does not happen on Chrome. I attach a picture where you can see that when I drag there is extra div below.
![draggable](https://user-images.githubusercontent.com/1830859/50016939-a1684800-fff0-11e8-9058-26f849f5a940.png)

this is the code:
	dialog = document.body.appendChild(document.createElement('div'));
	dialogId = getDialogId(url);

	dialog.id=dialogId;
	iframe=dialog.appendChild(document.createElement('iframe'));
	iframe.id="frame" +dialogId;
	iframe.setAttribute('style','border-width:0');
	$("#" + iframe.id).attr('style', opt);
	$("#" +dialogId).dialog({
		width: 'auto',
		height: 'auto',
		modal: true,
		resizable: false,
		close: function () {
			$("#" + iframe.id).attr('src', "about:blank");
			$(this).dialog("close");
			var div=window.document.getElementById(window.dialog.id);
			var parentDiv = div.parentNode;
			parentDiv.removeChild(div);
		}
	});
	window.dialogArguments=arg;
	$("#" +iframe.id).attr('src', url);

**Comment by mgol** [comment]
This is a bug tracker for jQuery, not jQuery UI. Tickets for jQuery UI should be submitted at https://bugs.jqueryui.com/.
