### ISSUE TITLE
Please add console warning/error about this deprecated functionality

### ISSUE THREAD

**Issue by Bert-de-Jong** [jquery/jquery#4266]
The most recent jQuery (3.3.1) does not display a console warning/error about certain deprecated functionality.

This
`var result1 = $("select[name*='test']").attr("value");`
works with 1.6.4 but not with 3.3.1, and 3.3.1 does not give a warning or error in the console.

Both inputs show "2" with 1.6.4:
https://jsbin.com/donolageva/1/edit?html,css,output

Only the second input shows "2" with 3.1.0 and git (3.3.1+):
https://jsbin.com/tezewuneyo/1/edit?html,css,output
https://jsbin.com/nusanebuli/1/edit?html,css,output
With **no** warning/error messages on the console.

Here's the code again, in case you want to test locally:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>jQuery test</title>
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
</head>
<body>

<select name="test">
<option value="1">one</option>
<option value="2" selected>two</option>
<option value="3">three</option>
</select>
<input id="result1" type="text">
<input id="result2" type="text">

<script>
var result1 = $("select[name*='test']").attr("value");
$("#result1").val(result1);

var result2 = $("select[name*='test'] option:selected").val();
$("#result2").val(result2);
</script>

</body>
</html>
```

(Simply replace 3.1.0 with 1.6.4 to see the different - working - result.)

Please add console warning/error about this deprecated functionality.

**Comment by gibson042** [comment]
The details of this behavior are explicitly documented at http://api.jquery.com/attr/ :
> The difference between <em>attributes</em> and <em>properties</em> can be important in specific situations. <strong>Before jQuery 1.6</strong>, the <code>.attr()</code> method sometimes took property values into account when retrieving some attributes, which could cause inconsistent behavior. <strong>As of jQuery 1.6</strong>, the <code>.prop()</code> method provides a way to explicitly retrieve property values, while <code>.attr()</code> retrieves attributes.
