### ISSUE TITLE
Feature Request: Accordion not show panel

### ISSUE THREAD

**Issue by simon1tan** [jquery/jquery#4267]
It would be nice for the Accordion to not show the panel if desired. I am activating the Accordion with code and the panel opens automatically. I would like the header to be highlight but the panel not to open. When I click on the header, I would want the panel to open. I would be a nice feature to disable the panel if necessary.

**Comment by dmethvin** [comment]
jQuery core does not have an According. You might mean jQuery UI, or perhaps another jQuery accordion plugin. It would be better to ask a question like this on StackOverflow.
