### ISSUE TITLE
How use JQuery with types?

### ISSUE THREAD

**Issue by cawa-93** [jquery/jquery#4268]
### My code example ###
```js
/** @type {JQuery<HTMLBodyElement>} */
const $body = jQuery('body')
const firstAnchor = $body.find('a').first()
```
`firstAnchor` has `JQuery<HTMLBodyElement>`

![image](https://user-images.githubusercontent.com/1662812/50686682-ffec7900-1026-11e9-9727-b0e2a0682ef3.png)

And if I try change type then I get error:
```
Type 'JQuery<HTMLBodyElement>' is not assignable to type 'JQuery<HTMLAnchorElement>'.
  Type 'HTMLBodyElement' is missing the following properties from type 'HTMLAnchorElement': charset, coords, download, hreflang, and 20 more.ts(2322)
```
![image](https://user-images.githubusercontent.com/1662812/50686722-2a3e3680-1027-11e9-9cd5-03d05f608a73.png)

How do I specify the types for variables that do not cause errors?

**Comment by mgol** [comment]
jQuery doesn't maintain its own TypeScript type definitions, they're located in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jquery. Issues with them should be reported at the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository.

**Comment by cawa-93** [comment]
Moved to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31891
