### ISSUE TITLE
Open and scroll to an anchor link on a different page

### ISSUE THREAD

**Issue by LeChevalierDOr** [jquery/jquery#4271]
### I can't use the top proporties for open and scroll to an anchor link on a different page  ###

This is my actual code (Sorry I can use jsfield): 

```javascript
    <script>
    jQuery(function($) {
      $('a[href*="#"]:not([href="#"])').click(function() {
          var target = $(this.hash);
            $('html,body').stop().animate({
              scrollTop: target.offset().top - 120
            }, 'linear');   
      });    
      if (location.hash){
        var id = $(location.hash);
      }
      $(window).load(function() {
        if (location.hash){
          $('html,body').animate({scrollTop: id.offset().top -120}, 'linear')
        };
      });
    })(jQuery);
    </script>
```

I using jquery.min 3.3.1 and jquery-ui 1.12.0

Thanks you in advance.

**Comment by timmywil** [comment]
Thanks for opening an issue, but this is not a proper bug report. You can find help at https://stackoverflow.com or in the [jQuery gitter](https://gitter.im/jquery/jquery).
