### ISSUE TITLE
addEventListener is not supported by IE 9-11

### ISSUE THREAD

**Issue by IsibisiDev** [jquery/jquery#4273]
### Description ###
MDN reports that addEventListener is not supported by IE 9-11 (https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Browser_compatibility). It may not work from IE 9+ and should be fixed.

### Link to test case ###
https://jsfiddle.net/L1bcyh0u/

**Comment by dmethvin** [comment]
That's incorrect but you could ask more about it on StackOverflow.
