### ISSUE TITLE
Get rid of the last instance of .end()

### ISSUE THREAD

**Issue by biziclop** [jquery/jquery#4275]
I was wondering if I could get rid of the potentially memory leaking `.pushStack()`/`.end()` by neutering `pushStack`:

    jQuery.prototype.pushStack = function( elems ){
      return jQuery.merge( this.constructor(), elems );
    };

A quick search revealed that the last instance of `.end()` lives in `jquery/src/effects.js`:

	fadeTo: function( speed, to, easing, callback ) {

		// Show any hidden elements after setting opacity to 0
		return this.filter( isHiddenWithinTree ).css( "opacity", 0 ).show()

			// Animate to the value specified
			.end().animate( { opacity: to }, speed, easing, callback );
	},

Could be changed into:

	fadeTo: function( speed, to, easing, callback ) {

		// Show any hidden elements after setting opacity to 0
		this.filter( isHiddenWithinTree ).css( "opacity", 0 ).show();

		// Animate to the value specified
		this.animate( { opacity: to }, speed, easing, callback );

		return this;
	},

It's +4 bytes minified:

    function(i,t,e,n){return this.filter(f).css("opacity",0).show().end().animate({opacity:t},i,e,n)}
    function(i,t,e,n){return this.filter(f).css("opacity",0).show(),this.animate({opacity:t},i,e,n),this}

Thanks for considering it!

**Comment by mgol** [comment]
Thanks for the report.

Such changes are quite fragile as all changes without tests for them may not survive future refactors. Adding a test for that would be weird, though, as we'd sanction using jQuery with some functions overridden.

If all you care about is internal jQuery usage you could as well change `pushStack` to set skip setting `prevObject` unless a specific global flag is set which would be set at the beginning of `fadeTo` and reset at its end. You could also make `end` clear that property.

I don't think sanctioning such hacks belongs in Core...

As for size difference, we care about gzipped size which you'll get if you run `grunt` before & then after your changes.

**Comment by dmethvin** [comment]
Also, that use of `.end()` specifically doesn't leak, right? To retain an old collection you need to call `.pushStack()` without a corresponding `.end()`. Something like this at *global scope* or some other long-lived scope:
```js
var messages = $("#comments").find(".message");
```
It can be fixed by either one of these:
```js
// avoid .find()
var messages = $("#comments .message");
// create a new collection
var messages = $($("#comments").find(".message"));
```
Or you could create a plugin to walk back into the `.prevObject` references and remove them.

**Comment by biziclop** [comment]
Thanks to both of you for your detailed answers, I think I close this (non-)issue.

Good old times: https://bugs.jquery.com/ticket/30
