### ISSUE TITLE
CSP: Provide a way to pass nonce to $.globalEval

### ISSUE THREAD

**Issue by tandraschko** [jquery/jquery#4278]
In #3541 CSP support was introduced to not loose the nonce attribute of script tags when repacing/inserting DOM nodes.

Therefore DOMEval already has support for nonce.
As $.globalEval already uses DOMEval under the hood, it should be quite to allow to pass the nonce.

current scipt:
```
// Evaluates a script in a global context
globalEval: function( code ) { 
		DOMEval( code ); 
}
```

something like this should work:
```
// Evaluates a script in a global context 
globalEval: function( code, nonce ) { 
		DOMEval( code, null, { nonce: nonce }); 
}
```

Workaround:
```
        var script = document.createElement('script');
        script.setAttribute('nonce', 'myNonce');
        script.innerHTML = 'console.log("test")';
        document.head.appendChild(script);
```

**Comment by mgol** [comment]
Thanks for the report. PR: #4280.

**Comment by mgol** [comment]
@tandraschko The PR landed and it will be included in jQuery 3.4.0.

**Comment by tandraschko** [comment]
Great! Thank you!

**Comment by tandraschko** [comment]
When do you plan to release 3.4.0?

**Comment by mgol** [comment]
If we're lucky, somewhere between a week or two. But don't hold me to it, we're doing it in our free time so there may always be unexpected delays, sometimes even long ones.
