### ISSUE TITLE
.append not working in Safari 5 for desktop

### ISSUE THREAD

**Issue by jfoclpf** [jquery/jquery#4292]
### Description ###

The function .append does not work in Safari version 5 for desktop, and according to browser support ( https://jquery.com/browser-support/ ) it should work from version 1. 

I'm using jQuery v3.3.1

For example:

`$("#selectList").append(new Option("option text", "value"));`

or

```js
$('#mySelect').append($('<option>', {
    value: 1,
    text: 'My option'
}));
```

do not work in Safari 5, they crash

### Link to test case ###

After several tests on the site I'm in charge with ( autocosts.info ) , with different browsers, this line of jQuery crashes with Safari 5

https://github.com/jfoclpf/autocosts/blob/master/src/client/initialize.js#53

(line 53)

**Comment by mgol** [comment]
> The function .append does not work in Safari version 5 for desktop, and according to browser support ( [jquery.com/browser-support](https://jquery.com/browser-support/) ) it should work from version 1.

I think you're reading the page incorrectly. We only support last 2 versions of Safari which currently means 11 & 12.

**Comment by mgol** [comment]
BTW, if this is on Windows - please don't use Safari for Windows. It's a long dead browser with lots of security issues, no one should be using that.

**Comment by jfoclpf** [comment]
Thanks for the reply.

I'm concerned about this because users are saying that the site won't work on iOS Safari, and I used wine in Ubuntu to simulate Safari and have access to console and debugging features.

The problem is that it's not functioning in any Safari version, even for iOS. 

I will provide further testing and info for you to check it.

Thanks

**Comment by mgol** [comment]
> I'm concerned about this because users are saying that the site won't work on iOS Safari, and I used wine in Ubuntu to simulate Safari and have access to console and debugging features.

You can't debug Safari issues in this way, this has to be done on an Apple operating system. You either need to have a Mac, an iPhone or use a service like [BrowserStack](https://www.browserstack.com). Safari for Windows is basically useless at this point.

**Comment by jfoclpf** [comment]
>You can't debug Safari issues in this way,

Thanks for all the tips. Just a small question, if you could say, does BrowserStack allows debugging or it just emulates the iOS/Safari browser?

**Comment by jfoclpf** [comment]
and just FYI, I made a [small jsfiddle test with .append](https://jsfiddle.net/joao_pimentel/n8p0Lb4t/), and indeed it seems it works on iOS (I used [appetize.io](https://appetize.io/) to emulate it). So, my issues are elsewhere!

**Comment by mgol** [comment]
@jfoclpf BTW, while it's currently hard to find a WebKit-based browser on Windows, on Linux there's [GNOME Web](https://wiki.gnome.org/Apps/Web) (formerly known as Epiphany) and even the [WebKit Nightly downloads page](https://webkit.org/downloads/) links to it as a way to preview dev versions of WebKit so if you're on Linux you can use GNOME Web to debug Safari issues. While it will likely not render everything identical to Safari so you may need to use something like BrowserStack one day, I'd guess most of the layout/JS issues of Safari should be reproducible there.

**Comment by jfoclpf** [comment]
@mgol thanks. It's been a nightmare to write my test script in node, such that I can make several tests for different browsers. I will check your sources.
