### ISSUE TITLE
animate on gridTemplateAreas not working

### ISSUE THREAD

**Issue by zezto** [jquery/jquery#4295]
### Description ###
I am expecting the grid template area to change one grid to the left so I can place a menu but the gridTemplateAreas property doesn't respond. Nothing happens at all no errors are thrown nothing.  I'm running firefox Quatum 64

### Link to test case ###
https://codepen.io/anon/pen/ErEdmV

hopefully, it's just me typing something wrong

**Comment by mgol** [comment]
Animating only works with numeric values & a few others as documented at https://api.jquery.com/animate/#animation-properties.
