### ISSUE TITLE
Jquery regex replace function issue in mobile browser

### ISSUE THREAD

**Issue by Praneshjs** [jquery/jquery#4304]
I have raised a solution request in Stackoverflow describing the Issue with sample code and tested video log, 

https://stackoverflow.com/q/54866373/4425004

Video Log of Testing URL
https://vimeo.com/319472208

**Comment by timmywil** [comment]
Thank you for opening an issue, but I think stackoverflow is the right place for that question. Whatever is happening, I doubt this will prompt any changes to jQuery.  Note that the events are triggered asynchronously while the value is retrieved synchronously, which means it's probably a race condition. I'd be careful with input value replacement anyway as it has other implications. To see what I mean, try inputting a non-number in the middle of the value.

The best solution for these cases is not to edit as the user types, which no matter how thorough and well-written, never accounts for all of the edge cases, but to validate afterwards, letting the user know how to fix it. Also look into using a `type="number"` input, which takes advantage of native validation and brings up the number keyboard on a phone.
