### ISSUE TITLE
problem with onbeforeunload on IOS (Iphone)

### ISSUE THREAD

**Issue by zskiredj** [jquery/jquery#4306]
* OS : Ios (Iphone)
* Browser : chrome last version

I have a page with this body :
```
<body>
    <div class="loading">
            <div class="loader"></div>
    </div>
    <div class="site-content">
 [... all the content]
</div>
</body>
```

I am using this code to show / hide a spinner

```
function unLoader(e) {
    $(".site-content").hide();
    $(".loading").show();    
    }
   
   $(window).on('load', function() {
         $(".loading").hide();
         $(".site-content").show();
          window.onbeforeunload = unLoader;
     });
```

The problem is that the spinner works in desktop both PC and mac, on safari, firefox, chrome etc...

But it does not work on my Iphone.

On the other side, i am using the spinner for calls in ajax :

```
var $loading = $('.loading').hide();
$(document)
    .ajaxStart(function () {
        $loading.show();
    })
    .ajaxStop(function () {
        $loading.hide();
    });
```

But this time the spinner works in mobile device (iphone) !

How can I make the spinner work for the mobile devices in all my pages (using the code shown first) ?

I know the problem is from `onbeforeunload `event

Thanks in advance.

**Comment by timmywil** [comment]
Thanks for opening an issue. However, this is more of a support question than a bug report. Please ask for help on stackoverflow.com.
