### ISSUE TITLE
TypeError: Cannot read property 'createElement' of undefined

### ISSUE THREAD

**Issue by dblachut-adb** [jquery/jquery#4308]
In some circumstances when the jquery code is running early enough in Chromium browser I am getting the error from title.
`
function assert( fn ) {
    var el = document.createElement("fieldset");
`

The key point is that `window.document` is defined, but referencing to global document directly for some reason fails by returning `undefined` value.

Would it be feasible to change this single line fragment into `window.document` or `preferredDoc` variable?
This is trivial change that was somewhat already discussed in #3333, but the bug is already closed and I am unable to comment it. I can make a PR, but I would like to know your opinion first.

**Comment by dblachut-adb** [comment]
Oh I see this is probably a sizzlejs issue and the `document` is not a global but local variable. Looks like I have reported this bug too quickly. I will return with conclusions after some deeper analysis.

**Comment by dblachut-adb** [comment]
The Sizzle initialization in setDocument fails, due to lack of `documentElement` property on document (it is equal to null at that time).

**Comment by mgol** [comment]
@dblachut-adb The discussion from the #3333 still applies - to make a change we need to understand when an issue happens and write a test for that to make sure it's solved. So far, no one has prepared a reduced test case that'd show the issue so we cannot proceed.

**Comment by dblachut-adb** [comment]
@mgol Thanks for the reply, looks like I was wrong with some of my assumptions.
