### ISSUE TITLE
Signature for the each Function is incorrect in the definition file @types/JQuery@2.0.53 and @types/JQuery@3.0.29/v2

### ISSUE THREAD

**Issue by Davilink** [jquery/jquery#4309]
Bug Reports:
I expected to be able to use the `each` function of  `$` in typescript.
Here the typescript error :
![image](https://user-images.githubusercontent.com/1498932/53673364-fb25f900-3c54-11e9-814c-0b7d0c69310b.png)
After looking around i found that in the definition file:
![image](https://user-images.githubusercontent.com/1498932/53673380-1e50a880-3c55-11e9-96d1-cc31b30c0b73.png)

I use `JQuery 2.1.4` with `@types/JQuery@2.0.53`, but i look in the `@types/JQuery@3.3.29` (in the v2/ folder) the same TODO is there.

**Comment by timmywil** [comment]
Thanks for opening an issue, but we do not maintain the type definitions. Feel free to check the issues on the types repo https://github.com/DefinitelyTyped/DefinitelyTyped.
