### ISSUE TITLE
RangeError: Maximum call stack size exceeded on javascript concat method on large arrays

### ISSUE THREAD

**Issue by Spazierenman** [jquery/jquery#4319]
### Description ###
I ran into such a problem when parsing a large piece of JSON using jquery.tmpl.js. This error appears when handling large arrays with the concat() function. Here is a link to the problem: https://bugs.chromium.org/p/chromium/issues/detail?id=103583 The problem has not been solved since 2011. To solve it, accept please my pull request. 
We check if there is a flat() function in the browser's arsenal, for example, it has a chrome browser, and if there is - simply merge the data arrays - nothing more is needed. If not, the browser will go a slower path, but at least there will be no error.

**Comment by mgol** [comment]
Please don't open multiple issues for the same problem. You've already reported it in #4318 (remember to fill the issue template, though, including providing the test case) and there's more discussion in #4320.
