### ISSUE TITLE
Issue with Jquery DataTable LoadMore..

### ISSUE THREAD

**Issue by kargoms** [jquery/jquery#4321]
I have implemented jquery datatable serverside pagination with loadmore option, after loading 300 more records, we are facing a performance issue in dom loading.. we are using 'table.rows.add(result.data).draw();' to append the records to the existing datatable. Is there any other way to make the performance better while drawing the datatable. since the draw() is redrawing entire set of data.
Thanks,
Karthik

**Comment by dmethvin** [comment]
This isn't a bug report. You might try StackOverflow.
