### ISSUE TITLE
node.js $.each does not work

### ISSUE THREAD

**Issue by oom-** [jquery/jquery#4324]
### Current config ###
```js
"jquery": "^3.3.1",
"jsdom": "^14.0.0",
```
```dos
node --version
v8.11.2
```
###  What do you expect to happen? ###
 Iterate over a jQuery object, executing a function for each matched element.

### What actually happens? ###
The each fonction do the same that the map function.
The each fonction doesnt iterate the jQuery objects but the index of them in node.js.

### Code for test case ###
```js
var {window} = new JSDOM('<html><body><div><a href="/test">test</a></div><div><a href="/test2">test2</a></div><div><a href="/test3">test3</a></div><div><a href="/test4">test4</a></div></body></html>');
var $ = require("jquery")(window);
$('a').each(i => console.log(i));
```

Current output: 
```js
0
1
2
3
```

What should be:
```js
HTMLAnchorElement {Symbol(impl): HTMLAnchorElementImpl}
HTMLAnchorElement {Symbol(impl): HTMLAnchorElementImpl}
HTMLAnchorElement {Symbol(impl): HTMLAnchorElementImpl}
HTMLAnchorElement {Symbol(impl): HTMLAnchorElementImpl}
```

**Comment by mgol** [comment]
`jQuery.each` callback gets `value` passed as its second parameter, not the first one. See the docs:
https://api.jquery.com/jQuery.each/#jQuery-each-array-callback

**Comment by oom-** [comment]
I was testing this function on a website that overrided the function. My bad.
