### ISSUE TITLE
focusNode returns parent node when selection is between two elements

### ISSUE THREAD

**Issue by protoncito** [jquery/jquery#4326]
### Description ###
focusNode returns the text object where a text selection ends. However, if the selection includes the (invisible) line feed at the end of a p element, focusNode returns the parent node, instead of the text object.
This creates problems when used, e.g. in conjunction with parentNode.
I have the following code:
```
var selectedText = document.getSelection();
var selectedEndId = $(selectedText.focusNode.parentNode);

```
The HTML is:
```
 <body>
    <div id="div-001">
      <p id="p-001">1 Lorem ipsum</p>
      <p id="p-002">2 Lorem ipsum</p>
    </div>
  </body>

```

If I select some text, for example paragraph p-001, selectedEndId will return p-001, i.e. the ending element containing the text. However, if the selection includes the line feed at the end of p-001, it returns div-001 while focusNode points at p-002.
focusNode should always return the current text object, not its parent. This occurs in Safari (12.0.3), Chrome (72.0.3626.121) and Opera(58.0.3135.79), but not in FF (65.0.1 (64-bit)).

**Comment by dmethvin** [comment]
Can you post a jsbin or jsfiddle test case?

**Comment by protoncito** [comment]
I have created the following jsfiddle:
https://jsfiddle.net/protoncito/rsm365h9/2/

If you select any text and click meta+c it will give you the start and end
id's of the paragraphs containing the selected text. However, if the
selected text ends at the end of a paragraph, it will return undefined.

Cheers,

Leo

**Comment by dmethvin** [comment]
If the entire paragraph is selected, the `focusNode` is the `<p>` element and the `parentNode` is the `<div>` so it doesn't have an `id`. It may not be what you expected but it's what is passed to jQuery so it's not a jQuery API error.

**Comment by protoncito** [comment]
True, this is what is passed to jQuery. However, AFAIK this is not what
happens in FF and jQuery is supposed to present the same behavior across
all browsers. Therefore, wouldn't it make sense to change the value
returned by focusNode in this case so as to make it behave in a manner
expected by users?

**Comment by dmethvin** [comment]
By the time jQuery gets the information it's already wrong. How do we change `$(wrongNode)` to `$(rightNode)`? Put together a patch to do this if you can, that would help.

**Comment by protoncito** [comment]
I think I found a patch. Please try the following, selecting some text and
then expanding the selection by pressing the right arrow while holding the
shift key:

<div id="div1">
  <p id="p1">text 1</p>
  <p id="p2">text 2</p>
  <p id="p3">text 3</p>
  <p id="p4">text 4</p>
</div>
<div id=log></div>

<script>
  document.onselectionchange = function () {

    var sel = getSelection();
    var a = sel.anchorNode;
    var b = sel.focusNode;

    if (sel.focusOffset == 0) {
      var p = b.previousSibling.previousSibling;
      b = p.childNodes[0];
    }

    log.textContent = 'Selected: ' + (
      !sel.toString() ?
        'nothing'
        : a.nodeName + a.textContent.slice(-1) + ' - ' +
          b.nodeName + b.textContent.slice(-1)
    );
  };
</script>

**Comment by dmethvin** [comment]
There's no jQuery in that solution. If it gets the right node you can pass that to jQuery though.
