### ISSUE TITLE
Incorrect value returned by outerHeight for table with border-collapse.

### ISSUE THREAD

**Issue by urffin** [jquery/jquery#4330]
### Description ###
Some strange behaviour of `.outerHeight` method for table with `border-collapse`.

Starts from version 3.3.1 for table with `box-sizing: conten-box` (default value for Chrome) and `border-collapse: collapse;` value `table.outerHeight()` greater than sum of `row.outerHeight`.

In version 3.2.1 - we get same values for  `table.outerHeight()` and sum of `row.outerHeight`.

This for _Chrome 72.0.3626.121_ and _Chrome 73.0.3683.86_.

In Microsoft Edge 44.17763.1.0 difference more than pixels (1.8 for two rows)
and without  `border-collapse` differences in sub pixels (0.8 for two rows)

### Link to test case ###
https://jsbin.com/fijigamama/1/edit?html,css,js,output

**Comment by gibson042** [comment]
I don't think there's a guarantee that the sum of table row height equals the height of the table itself, even with `border-collapse: collapse`.

**Comment by urffin** [comment]
@gibson042 i'm try a few cases with `border-collapse`, and `box-sizing` combination. 

On layout tab in Chrome DevTools for `border-collapse:collapse` and `box-sizing:content-box` (default valuse for table in Chrome) - sum of table row height is equal height of table. You can see this in sample by link. And same for  `border-collapse:separate` and `box-sizing:content-box`.

For `border-box`, i not understand why, but height of the table always greater than sum of table row height.

**Comment by timmywil** [comment]
I'm not sure what changed, but 3.3.1/git are reporting exactly what the browser reports for the table using either `getBoundingClientRect` or `offsetHeight`. @mgol did notice that the `tbody` itself is 1 pixel different than the `table`, so the discrepancy may have something to do with that in earlier versions. Regardless, I think we want to stick with reporting what is reported natively.
