### ISSUE TITLE
jQuery 3.3.1 regression: .closest() not working as expected anymore

### ISSUE THREAD

**Issue by BananaAcid** [jquery/jquery#4336]
I used to do something like this, prior to v3.0.0 (not in 3.0.0 up to 3.3.1) :
```js
//HTML:   main > ul > li > a

$parent = $('main > ul');

$('li > a').on('click', function() {
  $(this).closest( '> li', $parent ).css('color', 'red');
});
```
`.closest( selector , context )` ... does not work anymore - i have to use `.closest( $('> *', $parent) )` 

JS Bin Example, with workaround: https://jsbin.com/zuvekay/edit?html,js,output

[jQuery docs: .closest()](https://api.jquery.com/closest/)

**Comment by mgol** [comment]
Thanks for the report. The attached JS Bin presents a working example, here's the one that doesn't work:
https://jsbin.com/paveyex/edit?html,js,console,output
Changing the version to 2.2.4 makes it work again:
https://jsbin.com/paqidiy/edit?html,js,console,output

**Comment by timmywil** [comment]
We discussed this in the meeting. Selectors requiring context such as leading combinators and positional selectors are too strange, especially when no context is passed in. We [opted not to support this](https://github.com/jquery/jquery/issues/2796) in `.closest`, but neglected to document it.

Migrated to API issue: https://github.com/jquery/api.jquery.com/issues/1134

**Comment by mgol** [comment]
Note that this change was intentional, see #2796 for more details.
