### ISSUE TITLE
Getting 'Uncaught TypeError: Cannot set property 'timestamp' of undefined' when using jQuery

### ISSUE THREAD

**Issue by vipera7** [jquery/jquery#4338]
I have an error which appear when I import jQuery lib only. I don't know what I can do. I know that it's coming from the file jquery.min.js.

Here is my simple page causing this error :

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

What I get from my console :

[![Console][1]][1]

  [1]: https://i.imgur.com/2FOJyCU.png

**Comment by vipera7** [comment]
It was an extension causing the problem (https://chrome.google.com/webstore/detail/speedtest-by-ookla/pgjjikdiikihdfpoppgaidccahalehjh). I removed it from Chrome and the error is gone

**Comment by mgol** [comment]
@vipera7 Thanks for following up. If an issue you had gets resolved, please close the issue so that we don't have to do it ourselves.
