### ISSUE TITLE
Animate step callback command order

### ISSUE THREAD

**Issue by KingSora** [jquery/jquery#4340]
If you use the `animate` function with a `step` callback, the animation change is fullfiled AFTER this callback. 
So you can't work with the changed animation values within the `step` callback function. This is not really a bug, but at this point I would expect the animation change to be fulfilled.

  *  What do you expect to happen?
The animation change should be already fulfilled before the `step` callback is called.
  *  What actually happens?
The animation change is fulfulled after the `step` callback.
  *  Which browsers are affected?
All

The code to change would be [here](https://github.com/jquery/jquery/blob/master/src/effects/Tween.js#L46). The if block where the `step` callback is called should be below the `set` block where the animation change is done.

**Comment by mgol** [comment]
Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by KingSora** [comment]
Yes, sorry! I've created a [fiddle](https://jsfiddle.net/sn5djztm/) as JSBin isn't available for me.

**Comment by mgol** [comment]
Thank you!

**Comment by dmethvin** [comment]
The [docs](http://api.jquery.com/animate/) say:

> `step` Type: Function( Number now, Tween tween )  A function to be called for each animated property of each animated element. This function provides an opportunity to modify the Tween object to change the value of the property **before it is set**.

So the function is documented to work that way. Unless I'm misunderstanding what you want?

**Comment by KingSora** [comment]
Whoops, you're right... seems like I've overread that part. In this case, is there any chance to implement a callback which is fired after the `set` (a callback called `stepped` or something like this)? Do you think this would make sense? 

A bit of background to my case:
I encountered this problem in my application, because I tried to use the animated value in the `step` callback to create other animations, but they didn't work out well because of this discrepancy (the animation was always a step behind).

**Comment by dmethvin** [comment]
Since it's been more than a decade and nobody has asked for this before, I doubt there are enough use cases to justify adding, testing, and documenting a new callback. If others have encountered this they have come up with other ways to deal with it. If you need both values to instantly be equal, you could set `#target`'s value in the `step` callback.

**Comment by KingSora** [comment]
Alright, thanks for your time!
