### ISSUE TITLE
Version 3.3.1 and unsafe inline style CSP

### ISSUE THREAD

**Issue by infmelon** [jquery/jquery#4343]
In jquery version 3.3.1 the following error is shown in the Chrome console:

`jquery-3.3.1.js:4773 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-ZOU9Cifcx5CbBqtaHmfTXDOiu98uFSKeaz2sWew9Qdw='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`

Sadly I have no pointers as to which part of my code calls that jquery function or why this line causes an inline style violation.

**Comment by mgol** [comment]
Thanks for the report. Unfortunately, we can't do anything without a test case, this error is too generic.

You might be happy to hear, though, that we've recently fixed a few CSP-related issues, so the upcoming jQuery 3.4.0 may work for you. You can try https://code.jquery.com/jquery-git.js (but don't use it in production, this version changes in every commit!).

**Comment by mgol** [comment]
Relevant issues: #3541, #4323.

#3969 is planned for jQuery 4.0.
