### ISSUE TITLE
Elect / Nominate representative(s) to the OpenJS Foundation CPC

### ISSUE THREAD

**Issue by jorydotcom** [jquery/jquery#4344]
## Context
As part of the new [OpenJS Foundation's bylaws](https://github.com/openjs-foundation/bootstrap/blob/master/artifacts/OpenJS-Foundation-Initial-Merged-Bylaws.pdf), the Cross Project Council (CPC) has been [chartered](https://github.com/openjs-foundation/bootstrap/tree/master/proposals/stage-2/CPC_CHARTER) to serve as the primary governing body for programs and regular support of Foundation projects. For example, it will be responsible for things like infrastructure, travel assistance, CoC support, accepting new projects into the foundation, and mentorship programs to name a few. It will also be responsible for electing board representative(s) to the OpenJS Foundation board of directors.

**Any interested person from our project communities can attend CPC meetings and volunteer to participate in tasks.** For most programs, the CPC is expected to operate on the consensus of OpenJS Foundation project members. Issues that require a vote - namely the election of Board representatives and accepting a new project - will be memorialized by a voting CPC membership comprised of up to 2 representatives from Impact level projects and 2 representatives from Growth and At-Large stages.

If you'd like more info/context on the governance of the OpenJS Foundation, please let me know or follow this repo. The main point I hope you take away is that the foundation is to be run by and for the projects, and to do that we need participants from the project community.

## Request
As an Impact level project, jQuery is expected to send up to two formal representatives to participate in CPC meetings in a voting capacity. We (the bootstrap CPC group) would like you to make this selection by May 1. You can do that in whatever fashion you would like (projects retain their [own internal governance](https://thumbs.gfycat.com/CraftyBoilingCornsnake-small.gif)).

We anticipate having our first 'official' CPC meeting on May 30 or 31 at the Collaborator Summit in Berlin (sidebar, you should come!). In the interim, we would love for jQuery project members to participate in the Bootstrap CPC meetings which are currently held on Mondays (watch [this repo](https://github.com/openjs-foundation/bootstrap/issues/150) for meeting details).

If this is not the correct forum to raise this, please let me know and I will close the issue and post it in the preferred channel. Note that I'm posting essentially the same message to all OpenJS Foundation project repos, because I want to get the word out and make sure we all have the same information. 

your pal,
Jory

**Comment by timmywil** [comment]
Thanks @jorydotcom! We discussed this a bit in the meeting. We have a few people interested, but those who are interested have limited availability. Could you clarify what participating in CPC meetings in a voting capacity involves? Would it mean attending meetings over VOIP on a regular basis? What time would those meetings be (asking mainly for our members in other timezones)? Thanks.

**Comment by jorydotcom** [comment]
@timmywil these are exactly the questions we would need the project to answer! so meeting times, etc would be shifted to suit. The Impact projects bear the responsibility of voting on the matters that require a vote - namely adding new projects and electing directors for the board. So there is an expectation that Impact projects will be involved in leading the CPC in a very direct way. I don't know exactly what the time commitment will look like on an ongoing basis but I would say that allocating 1-2 hours a week to participate is a smart move.

**Comment by jorydotcom** [comment]
Hi jQuery team (cc @timmywil & @dmethvin )! Any updates to share here? As an FYI, if you don't think this is something jQuery wants to commit to doing as an Impact project, we can always change status to At Large or Growth which do not have the same expectations for participation. LMK what you're thinking, if you want to chat sometime!

**Comment by timmywil** [comment]
I think @dmethvin and I will do this, unless there are any objections. @jquery/core

**Comment by mgol** [comment]
Sounds good to me.

**Comment by dmethvin** [comment]
Yep I can do that 😊

**Comment by jorydotcom** [comment]
Super! Thanks @timmywil & @dmethvin - I am adding ya'll to the representatives list on https://github.com/openjs-foundation/bootstrap/issues/152 🎉
