### ISSUE TITLE
jQuery website suggests v3.3.0 is the latest version!

### ISSUE THREAD

**Issue by davidenco** [jquery/jquery#4348]
The jQuery homepage and download page both state that version 3.3.0 is the latest version, not version 3.4.0.

![image](https://user-images.githubusercontent.com/11735630/55936245-a13e2900-5c2d-11e9-9a4b-71e006048e52.png)

![image](https://user-images.githubusercontent.com/11735630/55936257-aa2efa80-5c2d-11e9-9e34-600196ee9979.png)

**Comment by mgol** [comment]
Thanks for the report, we fixed it already.
