### ISSUE TITLE
ajax: Treat blank JSON responses as {}

### ISSUE THREAD

**Issue by mcandre** [jquery/jquery#4355]
Very performant microservices often respond with a 200 status, blank content in order to minimize bandwidth. So there is a case to be made for the utility of blank HTTP responses declared as JSON format, even if this doesn't technically qualify as a JSON document.

In any event, it is unreasonable to expect all website operators to strictly enforce a policy of returning a JSON document with the usual curly braces. There are just so many exceptions.

I see a number of posts complaining about this exact issue with how jQuery enforces too strict a requirement. Imagine a poor user attempting to make a call to a Web service that he or she has no control over, which is quite common!

I think it would be better for jQuery's `ajax()` method to expect this behavior, and automatically treat blank JSON responses as `{}` or `null` or some other reasonable value, so that jQuery can integrate better with real world Web services. What does the community think?

# Workarounds?

I am also trying to use a workaround like `dataType: 'text'` for my Web services. However, no matter how I try to arrange my `$.ajax(...) ... ;` syntax, jQuery never actually invokes `always()`, or `done()`, or `success()`, instead performing `error()` / `fail()` about three minutes after the request has completed, which is just an awful frontend experience.

**Comment by dmethvin** [comment]
Your workaround should be fine. If it's not working, please provide a test case. If the server says it's returning JSON it should return JSON.

**Comment by mcandre** [comment]
@dmethvin

No matter how I specify my handlers, nor how I configure the response data type, jQuery AJAX always exhibits the same behavior: It waits about five whole minutes and then finally calls error() / always() with a JSON parsing error.

The only workaround I can recommend is to wrap any and all Web services in another layer of Web services, explicitly checking for empty responses and emitting `{}` content. Nothing else seems to work. This is not how Web 2.0 was meant to behave.

**Comment by dmethvin** [comment]
Specifying `datatype: "text"` should prevent any problems that occur if the server doesn't return valid JSON. I'll close this for now, but if you have an example of that not working you can post it and if it's a bug we'll reopen.
