### ISSUE TITLE
Run tests on iOS 10.0 before the release

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#4359]
### Description ###

This issue is a reminder to run our test suite locally on iOS 10.0. When run on `3.4.0`, lots of tests are failing because iOS 10.0 has incomplete Shadow DOM support and we incorrectly rely on what's not present in that browser (see #4356) currently.

You can install an iOS 10.0 simulator via Xcode even in macOS Mojave & run tests there. I can do it before the release.

### Link to test case ###

N/A

**Comment by mgol** [comment]
@timmywil I verified manually commit 7dddb19ca4bca9685adb734c76dcf72c3f610007 passes all the tests in iOS 10.0 (at least in the simulator, I don't have a real device with that OS to check). A commit before that one fails most of the tests in that browser.

As long as we don't land anything else on `3.4-stable` before the `3.4.1` release, this ticket is done.

I'll leave it open so that you can check before the release whether any new commit has landed and whether another verification is needed because of that.

**Comment by timmywil** [comment]
Checked
