### ISSUE TITLE
Deprecate jQuery.trim?

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#4363]
### Description ###

[`jQuery.trim`](https://api.jquery.com/jQuery.trim/) was useful for IE <9 and later to workaround an old Android Browser issue but we don't support that browsers anymore on `master`. It also adds one niceity that it accepts a `null` value that it turns to an empty string but that's it. Should we deprecate it?

**Comment by timmywil** [comment]
> it accepts a null value

I think this might be a good enough reason to keep it. It'll be pretty small without the regex.

**Comment by mgol** [comment]
We've deprecated `jQuery.proxy` (#2958) even though it does a lot more than `jQuery.trim`. Plus, trimming is a pure JS thing & it doesn't have a lot in common with the DOM so it seems to fall a little outside of the scope of jQuery to me.

**Comment by timmywil** [comment]
Well, I was against deprecating that too. I wouldn't say it did *a lot* more than native `bind`, though.

**Comment by timmywil** [comment]
That brings up another point. `proxy` was deprecated with no intention of removal in 4.0, which I'm not really a fan of in general, but we should keep in mind that not all deprecations will get removed in 4.0. And whether it's semantic or not, I'm uncomfortable deprecating anything in a patch version, so I even if we agree to deprecate `jQuery.trim`, I'd want to wait until 4.0.

**Comment by mgol** [comment]
Semver mandates deprecations can only happen in minor or major bumps so it can only happen in 4.0.0 or 3.5.0 if we ever decide to release that.

**Comment by dmethvin** [comment]
I don't have a strong feeling either way on this. Removing it won't change the file size that much but I'd actually prefer that people used the built-in methods rather than our utilities. As @timmywil says we don't actually need to remove it but could signal there are alternatives by deprecating.

**Comment by gibson042** [comment]
I'm very much in favor of deprecating for the same reasons as @mgol and @dmethvin. Removal would be best, but even without it we should be discouraging use of nonstandard patterns where standard ones exist (especially when the don't pertain to the primary purpose of this library).

**Comment by ShashankaNataraj** [comment]
@mgol @dmethvin May I submit a PR for deprecating jQuery.trim() ?

**Comment by mgol** [comment]
@ShashankaNataraj Sure, PRs welcome!

**Comment by mgol** [comment]
Moving the milestone to `3.5.0` (deprecations can only happen in minor or major releases and previously we didn't plan a minor bump on the 3.x line); I cherry-picked changes from PR #4461 (with some necessary modifications) in 56e73e0c4ae908c853c986aadeda7cfcf2df4f6f.
