### ISSUE TITLE
jQuery.stop: Unnecessary conditional statement

### ISSUE THREAD

**Issue by wonseop** [jquery/jquery#4374]
### Description ###

I found strange code in line 545 of 'src/effect.js'.
The variable 'type' in this code can not be false.
Therefore, it would be better to modify the conditional statement.
```
	stop: function( type, clearQueue, gotoEnd ) {
		var stopQueue = function( hooks ) {
			var stop = hooks.stop;
			delete hooks.stop;
			stop( gotoEnd );
		};

		if ( typeof type !== "string" ) {    // <-- Valiable 'type' has a string value or 'undefined'
			gotoEnd = clearQueue;
			clearQueue = type;
			type = undefined;
		}
		if ( clearQueue && type !== false ) { // 'type !== false' is boolean check
                                                                           // It should be compared with 'string' type or 'undefined'
			this.queue( type || "fx", [] );
		}
```

### Link to test case ###
N/A

**Comment by mgol** [comment]
PR: #4375

**Comment by mgol** [comment]
Cherry-picked PR #4375 to `3.x-stable` in 30f5c6c3ee3a128c7b75a771d4cb8a5b750ae17d.

**Comment by alnzialiksav** [comment]
ااقفل��طل�وك��ك��خيل�
ك��بك��يب��ب�ك����جتيني���اف�Nليك��ن��ري��ا��بب�وي��ياء�ل��لع�قسم�Aول�F�لمك��ا���ين��ير�	�واقه��ي�كل��ه�P�ضع�ه����انه�ك��ن��ا���به��ان�قلع��بلت����لين��كي�	ه���2ش�N�الضبط�له�A�صل��ا�قبتك���53�لع��د����لاه�كل��ني��بي�ني��اف�ليني�قولي��فى��ل��مس��نون��ييل��طر�
وفتني�	�قيقه��اس�ك����يت��ال�قم��عه��بك�فت��جتك��ن	��لامات���ي��الف��غل�وشت��	��ادق����يب��ادي�m�وك��ى�
لاقات�ه��ان�ى��ك�-N��;��دنا�ك��ير�فاقد��يت�وق��ه��رار�لبك���ي��لتك��تفي�ل�&امك��ا�تجمع��وي�	�وشين��م�
والله�	�عطيه�ك�Y=ن���ه��ااترك��ي
�C>�بي��ويت��ار�فيني��طول�ي��ين��ي��ري���كله���ك���كان��	�gك�=
	�تكلم��م�فسي�	�دددي�ي��ا�لا�	�هههه�	�يييه�	�اتخذ��د�لتفت�له�	q	�عدين�ين��ع��حمه�وعه���),"\nمشتاق��دلعني��احظ��ب��ل��حث��طي�ينك�كون��ه�6�قصه�\t�جعني�😂���B<��S�����
