### ISSUE TITLE
when scanned with fortify scan, getting insecure randomness error for 3.4.0 version

### ISSUE THREAD

**Issue by karthikdav** [jquery/jquery#4376]

**Comment by mgol** [comment]
There are too few details in this report for us to be able to work on it. If I had to guess, the tool you're using is complaining about our use of `Math.random()` but we don't rely on it being cryptographically secure.

**Comment by karthikdav** [comment]
Math.random() is the function that the tool is reporting as insecure randomness, shouldn't it be cryptographically secure

**Comment by mgol** [comment]
That’s what I thought. Not every usage of randomness needs to be cryptographically secure. The problem is in the tool you use, not in jQuery.
