### ISSUE TITLE
NuGet package update to latest 3.4

### ISSUE THREAD

**Issue by Coding-Hen** [jquery/jquery#4377]
### Description ###
Update the nuget package 3.3.1 to 3.4 inline with current release.

https://www.nuget.org/packages/jQuery/

Appoligies if this is in the wrong place/format

### Link to test case ###

https://www.nuget.org/packages/jQuery/
![image](https://user-images.githubusercontent.com/8798074/56960400-926dd680-6b48-11e9-9a3c-87a9038b8c55.png)

**Comment by mgol** [comment]
We don't maintain the jQuery Nuget package, only the npm & Bower ones. You should contact the maintainer.
