### ISSUE TITLE
Errors when upgrading modernizr tests to jquery >= 3.3 

### ISSUE THREAD

**Issue by rejas** [jquery/jquery#4378]
When trying to update the Modernizr build pipeline to a newer version of jquery we get the following errors in our tests (https://github.com/Modernizr/Modernizr/issues/2406) Expected behaviour is of course that the tests runs through without errors.

```
Running "mocha:test" (mocha) task
Testing: http://localhost:9999/test/unit.html

  169 passing (6s)
  2 failing

  1) html5printshiv "before all" hook for "shivs the document":
     TypeError: 'undefined' is not a function (evaluating 'elem.getAttribute( "type" )')
      at disableScript (http://localhost:9999/node_modules/jquery/dist/jquery.js:5793)
      at http://localhost:9999/node_modules/jquery/dist/jquery.js:466
      at domManip (http://localhost:9999/node_modules/jquery/dist/jquery.js:5889)
      at http://localhost:9999/node_modules/jquery/dist/jquery.js:6076
      at http://localhost:9999/test/browser/src/html5printshiv.js:10
      at callFnAsync (http://localhost:9999/node_modules/mocha/mocha.js:5391)
      at http://localhost:9999/node_modules/mocha/mocha.js:5312
      at next (http://localhost:9999/node_modules/mocha/mocha.js:5876)
      at http://localhost:9999/node_modules/mocha/mocha.js:5880
      at timeslice (http://localhost:9999/node_modules/mocha/mocha.js:82)

  2) html5shiv "before all" hook for "shivs the document":
     TypeError: 'undefined' is not a function (evaluating 'elem.getAttribute( "type" )')
      at disableScript (http://localhost:9999/node_modules/jquery/dist/jquery.js:5793)
      at http://localhost:9999/node_modules/jquery/dist/jquery.js:466
      at domManip (http://localhost:9999/node_modules/jquery/dist/jquery.js:5889)
      at http://localhost:9999/node_modules/jquery/dist/jquery.js:6076
      at http://localhost:9999/test/browser/src/html5shiv.js:10
      at callFnAsync (http://localhost:9999/node_modules/mocha/mocha.js:5391)
      at http://localhost:9999/node_modules/mocha/mocha.js:5312
      at next (http://localhost:9999/node_modules/mocha/mocha.js:5876)
      at http://localhost:9999/node_modules/mocha/mocha.js:5880
      at timeslice (http://localhost:9999/node_modules/mocha/mocha.js:82)
```

as well as these:

```
649 passing (4s)
  3 failing

  1) iframe context "before all" hook for "is able to be loaded in an iframe":
     TypeError: 'undefined' is not a function (evaluating 'elem.getAttribute( "type" )')
      at disableScript (http://localhost:9999/node_modules/jquery/dist/jquery.js:5793)
      at http://localhost:9999/node_modules/jquery/dist/jquery.js:466
      at domManip (http://localhost:9999/node_modules/jquery/dist/jquery.js:5889)
      at http://localhost:9999/node_modules/jquery/dist/jquery.js:6076
      at http://localhost:9999/test/browser/integration/iframe.js:11
      at callFnAsync (http://localhost:9999/node_modules/mocha/mocha.js:5391)
      at http://localhost:9999/node_modules/mocha/mocha.js:5312
      at next (http://localhost:9999/node_modules/mocha/mocha.js:5876)
      at http://localhost:9999/node_modules/mocha/mocha.js:5880
      at timeslice (http://localhost:9999/node_modules/mocha/mocha.js:82)

  2) uncaught errors should not exist:
     Error: expected 'TypeError: \'undefined\' is not a function (evaluating \'elem.getAttribute( "type" )\')' to equal undefined
      at http://localhost:9999/node_modules/expect.js/index.js:102
      at http://localhost:9999/node_modules/expect.js/index.js:219
      at http://localhost:9999/node_modules/expect.js/index.js:69
      at http://localhost:9999/test/index.html:4
      at callFn (http://localhost:9999/node_modules/mocha/mocha.js:5342)
      at http://localhost:9999/node_modules/mocha/mocha.js:5334
      at http://localhost:9999/node_modules/mocha/mocha.js:5990
      at http://localhost:9999/node_modules/mocha/mocha.js:6143
      at next (http://localhost:9999/node_modules/mocha/mocha.js:5902)
      at http://localhost:9999/node_modules/mocha/mocha.js:5912
      at next (http://localhost:9999/node_modules/mocha/mocha.js:5817)
      at http://localhost:9999/node_modules/mocha/mocha.js:5880
      at timeslice (http://localhost:9999/node_modules/mocha/mocha.js:82)

  3) uncaught errors should not exist:
     TypeError: 'undefined' is not an object (evaluating 'fn.call')
      at callFn (http://localhost:9999/node_modules/mocha/mocha.js:5342)
      at http://localhost:9999/node_modules/mocha/mocha.js:5334
      at http://localhost:9999/node_modules/mocha/mocha.js:5990
      at http://localhost:9999/node_modules/mocha/mocha.js:6143
      at next (http://localhost:9999/node_modules/mocha/mocha.js:5902)
      at http://localhost:9999/node_modules/mocha/mocha.js:5912
      at next (http://localhost:9999/node_modules/mocha/mocha.js:5817)
      at http://localhost:9999/node_modules/mocha/mocha.js:5880
      at timeslice (http://localhost:9999/node_modules/mocha/mocha.js:82)

```

Still works with v3.2.1 but i cannot find anything in the changelog that might explain this new error. Maybe you got a hunch what changed so I might try to fix it on our side?

**Comment by mgol** [comment]
The error seems to be coming from this line:
https://github.com/jquery/jquery/blob/3.4.0/src/manipulation.js#L65
`disableScript` is only used here:
https://github.com/jquery/jquery/blob/3.4.0/src/manipulation.js#L161

It seems you have a script in your test that doesn't have the `getAttribute` method; that sounds weird.

It'd also help if you checked whether that issue appears if you use jQuery 3.3.1 for your tests or not (you mentioned trying with 3.2.1).

**Comment by mgol** [comment]
Also, are these tests run in Node or in a browser? Can you provide more info about the full environment, versions used etc.?

**Comment by rejas** [comment]
Thx for he quick reply. To answer your questions:
1) affects all versions after 3.2.1
2) the first two errors happen when mocha runs in the browser (phantom js), the other three errors appear when node tests are run

The branch where I test this is https://github.com/Modernizr/Modernizr/tree/update_jquery

I am trying slowly to get the test infrastructure of modernizr up-to-date alas there is already some bitrot due to an old grunt-mocha dependency that I cannot yet get rid of. Therefor the tests with jquery 3.2.1 only pass for me on my windows machine with node8 installed.

Maybe the old phantomjs (v1.9) from that grunt-mocha is part of the problem but as I said, I cannot yet get rid of that. Any idea what changed with v3.3.X that could cause this?

**Comment by mgol** [comment]
We've never actually run tests on PhantomJS (we now run some basic tests on Node.js with jsdom) but I'd expect recent jQuery versions to _not work_ at least on PhantomJS 1 (v2 should more or less work with jQuery 3.x, although we don't guarantee that). You might need to update to v2. In the long run it'd be better to upgrade to Chrome Headless, I think, as PhantomJS is no longer developed.

How do you run the Node tests? jQuery requires a DOM to work; it can work (at least partially) with a custom DOM implementation like jsdom but something is needed.

**Comment by mgol** [comment]
It'd help a lot if you could do `git bisect` on the jQuery repo, running `grunt dev` in every bisect stage and copying `dist/jquery.js` to where you're sourcing it from (somewhere in `node_modules`, I guess).

**Comment by rejas** [comment]
Bisecting comes to this conclusion:
```
C:\Projekte\jquery>git bisect good
a16339b8933f115da3661f3d3f64854c3fa60bdc is the first bad commit
commit a16339b8933f115da3661f3d3f64854c3fa60bdc
Author: Richard Gibson <richard.gibson@gmail.com>
Date:   Mon Apr 24 12:39:25 2017 -0400

    Core: Update isFunction to handle unusual-@@toStringTag input

    Ref gh-3597
    Fixes gh-3600
    Fixes gh-3596
    Closes gh-3617

:040000 040000 246bee0212ccac9979b6d5eec9a626ed82da0d34 57a77c7e7ae28a9e40f55e733bbb15875d1b56b4 M  src
:040000 040000 25eff73b8b038723ae10ed408caa1d7785933986 f67b9461cd8ab4bf6587676c7bb637f4f51a2bff M  test
```

**Comment by rejas** [comment]
node tests are run with [grunt-mocha-test](https://github.com/pghalliday/grunt-mocha-test) 
another library that I would love to replace with something more modern and stable :-(

**Comment by mgol** [comment]
If I understand correctly, `grunt-mocha-test` is mostly a wrapper around Mocha. What DOM implementation do you use, though? jQuery won't run in bare Node without a proper `window` object provided.

**Comment by dmethvin** [comment]
I'm pretty sure jQuery 3 isn't going to run with PhantomJS 1.x. There are several workarounds we took out like `.apply(this, nodeList)` and the `typeof` various builtins returning `"function"` when they are not.

**Comment by rejas** [comment]
@mgol I cant really answer that, since I dont have the big insights into the cod and how it works :-) Maybe some of the old folks from Modernizr could answer that but most of them already moved on :-( 
What possible DOM implementations are out there? Maybe I stumbled across one in the code ...
Anyway, seems like its time to replace grunt / phantomjs with something more maintained so that jquery can be upgraded too....

**Comment by mgol** [comment]
@rejas Two popular DOM implementations in Node.js are jsdom & domino. We run some basic tests in jsdom now.

**Comment by rejas** [comment]
@mgol thx for the info, alas none of these are in the code (or in the npm dependency tree). thanks anyway

**Comment by rejas** [comment]
@mgol closing this issue. started switching modernizrs test framework over to gulp/mocha/chome headless and upgrading jquery there doesnt trigger any errors.
