### ISSUE TITLE
Getting children of <object> tag with contents() not working correctly

### ISSUE THREAD

**Issue by patocallaghan** [jquery/jquery#4384]
### Description ###
**Version:** jQuery 3.4.1

Since https://github.com/jquery/jquery/commit/0ba8e38d0c4ab4a4fb9054e7a713630be9743aff it appears that using `contents()` to get the children of an `<object>` is not working as expected.

Taking this example HTML

```html
<object type="application/x-shockwave-flash" width="200" height="300" id="penguin">
    <param name="movie" value="flash/penguin.swf">
    <param name="quality" value="high">
    <img src="images/penguin.jpg" width="200" height="300" alt="Penguin">
</object>
```

I'd expect the following to happen

```js
jQuery(objectHtml).contents().length // => 3
```

But what actually happens is:

```js
jQuery(objectHtml).contents().length // => 0
```

This happens because on this line https://github.com/jquery/jquery/blob/110802c7f22b677ef658963aa95ebdf5cb9c5573/src/traversing.js#L148-L149 it only checks if `elem.contentDocument` is not  `undefined`. But in this scenario `elem.contentDocument` is `null` so the conditional is truthy and enters the `if` block and returns `null` for the contents.

If we change the conditional to be `elem.contentDocument != null` it works correctly.

### Link to test case ###
https://codepen.io/patocallaghan/pen/bybaWv?editors=0011

I have a PR to fix it but I wanted to open an issue first.

**Comment by mgol** [comment]
Thanks for the report! This is a regression from jQuery 3.3.1 so I added the 3.4.2 milestone.

**Comment by mgol** [comment]
PR: #4385
