### ISSUE TITLE
.clone() does not clone IntersectionObserver event handler

### ISSUE THREAD

**Issue by svivian** [jquery/jquery#4392]
### Description ###

If an element is cloned using `$('.example').clone(true, true)` it does not clone the IntersectionObserver handler on the element. In the example below I've set up basic image lazy loading using span tags that are replaced by images.

It then replaces each span with a clone of itself, but those clones no longer load the images when scrolled to.

I don't know if this is expected behaviour (it's unexpected to me). Maybe IntersectionObserver doesn't count as an event handler. I don't know if there's some other way to keep the IO handler besides re-adding it manually every time something is cloned.

### Link to test case ###

https://jsfiddle.net/tmb2eoL9/9/

**Comment by mgol** [comment]
jQuery only knows about event handlers it itself attaches. It won't even know about direct `addEventListener` calls, not to mention something more advanced like `IntersectionObserver`. There's no browser API to get that information so even if we wanted we cannot re-attach it.

**Comment by svivian** [comment]
Oh I see. Thanks anyway, I'll find a workaround.
