### ISSUE TITLE
The source file of jQuery.param function on github is different from what I have downloaded by npm install jQuery 1.7.4

### ISSUE THREAD

**Issue by Sara2009** [jquery/jquery#4398]
### Description ###
I run npm install jQuery.
In the node_modules file lib/node-jquery.js, the function jQuery.param will do the replace.
```
return s.join( "&" ).replace( r20, "+" );
```
But in the file https://github.com/jquery/jquery/blob/master/src/serialize.js 
jQuery.param just return `return s.join( "&" )` without the replace.

Why are they different from each other?

**Comment by mgol** [comment]
See the note at:
https://www.npmjs.com/package/jQuery

> This is deprecated. Please use 'jquery' (all lowercase).

**Comment by Sara2009** [comment]
> See the note at:
> https://www.npmjs.com/package/jQuery
> 
> > This is deprecated. Please use 'jquery' (all lowercase).

I run npm install jquery 3.4.1
```
import jquery from 'jquery'
jquery.param({a: 'It is a test'})
// => "a=It%20is%20a%20test"
```
But in https://api.jquery.com/, it loads https://code.jquery.com/jquery-1.11.3.js
I press F12 to open the console and run the same code
```
$.param({a: 'It is a test'})
// => "a=It+is+a+test"
```

Why are the two results different from each other?

**Comment by mgol** [comment]
Different jQuery versions may have different behavior in some cases.

**Comment by mgol** [comment]
This particular change is https://github.com/jquery/jquery/issues/2658.
