### ISSUE TITLE
A bit of advice on AJAX

### ISSUE THREAD

**Issue by lyf2nb** [jquery/jquery#4401]
First of all, my English is not very good, please forgive me.
ISSUES:
When I send the AJAX request all the parameters seem to be correct
For example: 
	$.ajax({
	    url: "test.do",
	    type: "POST",
	    data:  {'code':code,'status':status},   <---------------------- Here
	    contentType:"application/json",
	    dataType: "text",
	    success: function (data) {
		alert(data)
	    }
	})
But this is a problem, the server will return me 404, because the method doesn't recognize the JSON object (it only recognizes the JSON Sting object)
So I have to change it to: 
	$.ajax({
	    url: "test.do",
	    type: "POST",
	    data:  JSON.stringify({'code':code,'status':status}),   <---------------------- Here 
	    contentType:"application/json",
	    dataType: "text",
	    success: function (data) {
		alert(data)
	    }
	})
So I want to make further improvement. Please check my PR. Thank you

**Comment by dmethvin** [comment]
This is the bug tracker. You might try StackOverflow for advice?

**Comment by lyf2nb** [comment]
I know what it means, but why not have Jquery support JSON objects instead of serialized JSON strings

**Comment by timmywil** [comment]
Thanks for opening an issue. Objects passed to data are serialized to query strings by default. This is documented [here](https://api.jquery.com/jQuery.ajax/). If you just want to stringify the JSON, this can be done before passing the data to `jQuery.ajax` as you noted, or you can write a [prefilter](https://api.jquery.com/jQuery.ajaxPrefilter) to cover it for all your requests.
