### ISSUE TITLE
A bit of advice on AJAX

### ISSUE THREAD

**Issue by lyf2nb** [jquery/jquery#4403]
First of all, my English is not very good, please forgive me.
ISSUES:
When I send the AJAX request all the parameters seem to be correct
For example:
$.ajax({
url: "test.do",
type: "POST",
data: {'code':code,'status':status}, <---------------------- Here
contentType:"application/json",
dataType: "text",
success: function (data) {
alert(data)
}
})
But this is a problem, the server will return me 404, because the method doesn't recognize the JSON object (it only recognizes the JSON Sting object)
So I have to change it to:
$.ajax({
url: "test.do",
type: "POST",
data: JSON.stringify({'code':code,'status':status}), <---------------------- Here
contentType:"application/json",
dataType: "text",
success: function (data) {
alert(data)
}
})
So I want to make further improvement. Please check my PR. Thank you

**Comment by dmethvin** [comment]
This is the bug tracker. You might try StackOverflow for advice?
