### ISSUE TITLE
Support attr and prop with no arguments

### ISSUE THREAD

**Issue by Richienb** [jquery/jquery#4404]
### Description ###
`JQuery.attr` and `JQuery.prop` with no arguments should return key-value pairs of all the attributes or properties.

At the moment running `$(SELECTOR).attr()` just gives an error so I would be useful for it to do something. Implementing this probably won't break anything else.

Here's a quick example on how you would normally do this in vanilla JS:

```js
[].slice.call(el.attributes).reduce((curr, val) => {
    curr[val.name] = val.value;
    return curr;
}, {})
```

needs to be equalivent to `$(el).attr()`

**Comment by dmethvin** [comment]
Looking at how this stacks up against our guidelines for [adding new features](https://github.com/jquery/jquery/wiki/Adding-new-features), there doesn't seem to be a strong benefit  to putting this in core. In the case of `.prop()` there would be a huge number of properties enumerated for a DOM element, e.g., `children`, `onclick`, `outerHTML`, `getElementsByTagName`, etc. For attributes the most common need for enumeration might be when using `data-` attributes; developers shouldn't be creating arbitrary attribute names. jQuery already enumerates the `data-` attributes to load its internal data cache.

**Comment by timmywil** [comment]
I agree with Dave.
