### ISSUE TITLE
Internet Explorer 11 Browser Support

### ISSUE THREAD

**Issue by pradeepyadava** [jquery/jquery#4410]
Using jQuery 1.12.3

*Syntax Error*
1. a.querySelectorAll("*,:x")
2. s.call(a,"[s!='']:x")

I have attached screen-shots of bugs.
![Error 3](https://user-images.githubusercontent.com/17030949/58536532-7c6a3900-820e-11e9-8705-16f989b65635.JPG)
![Error 4](https://user-images.githubusercontent.com/17030949/58536533-7d02cf80-820e-11e9-9749-8ff15b8369db.JPG)

**Comment by mgol** [comment]
These errors are in try-catches (they're used for support tests) so they don't cause any real problems in running applications. You'll see them in Chrome as well & they come from [Sizzle](https://github.com/jquery/sizzle), jQuery selector engine.
