### ISSUE TITLE
jQuery 1.x/2.x patching

### ISSUE THREAD

**Issue by Specialist25B** [jquery/jquery#4412]
New to Git and am hoping to get some information. My company uses an application that uses JQuery 1.X/2.X and it has been flagged as a vulnerability due to its lack of patching and being EOL...the problem is that the vendor of the application we use (and rely on pretty heavily) is not supporting the updated versions of jQuery (currently). With these branches not being patched, can anyone provide a resolution to this conundrum ?

**Comment by timmywil** [comment]
Thank you for opening an issue. If the vendor does not support the updated versions, the responsibility falls to them to cover any vulnerabilities. However, most "vulnerabilities" in a low-level library like jQuery can be avoided with common security best practices.

**Comment by DanielRuf** [comment]
Hi @Specialist25B,

if needed you can still apply the backported patches from https://github.com/DanielRuf/snyk-js-jquery-174006

**Comment by Specialist25B** [comment]
> Hi @Specialist25B,
> 
> if needed you can still apply the backported patches from https://github.com/DanielRuf/snyk-js-jquery-174006

Hi @DanielRuf ,
                         Does this repository only cover the patch needed for the one mentioned CVE ?

**Comment by DanielRuf** [comment]
Hi @Specialist25B

> Hi @DanielRuf ,
> Does this repository only cover the patch needed for the one mentioned CVE ?

Yes, the patches only patch / fix this specific vulnerability.

**Comment by Specialist25B** [comment]
Are there any backported patch repositories for other known vulnerabilities or is this the only one ? I will certainly search the CVE database but figured I would ask.

**Comment by DanielRuf** [comment]
The people at Snyksec provide some backported patches for other libraries and projects but so far there is no central repository for such backported security patches (I'm working on such a concept with a friend to help developers and businesses to stay secure).
