### ISSUE TITLE
1.12.4 Prototype Pollution

### ISSUE THREAD

**Issue by coconuthk** [jquery/jquery#4413]
### Description ###
**Unsafe Object recursive merge**
`merge (target, source)`

`foreach property of source`

`if property exists and is an object on both the target and the source`

`merge(target[property], source[property])`

`else`

`target[property] = `source[property]`

**Property definition by path**
There are a few JavaScript libraries that use an API to define property values on an object based on a given path. The function that is generally affected contains this signature: theFunction(object, path, value)

If the attacker can control the value of “path”, they can set this value to _proto_.myValue. myValue is then assigned to the prototype of the class of the object.

### Link to test case ###

https://snyk.io/vuln/SNYK-JS-JQUERY-174006

**Comment by DanielRuf** [comment]
Hi @coconuthk, this is fixed in jQuery 3.4.0.

For previous releases please use the backported patches from https://github.com/DanielRuf/snyk-js-jquery-174006

**Comment by mgol** [comment]
We don’t maintain jQuery 1.x/2.x anymore and it’s fixed in 3.4 as @DanielRuf mentioned so I’m closing this issue.
