### ISSUE TITLE
jquery doesn't throw error / notice on some wrong codes

### ISSUE THREAD

**Issue by ya3ya6** [jquery/jquery#4416]
Most of the times jquery forgive wrong codes.

For example :

`toggleClass` expect second parameter to be Boolean or function, not Truthy. but this code doesn't throw any error or warn:

`$('.box').toggleClass('box',1)`

This level of forgiveness makes debugging alot harder, for example above code looks right, but it's not.
a code that looks working but it doesn't and doesn't throw any error or warning is so hard to debug.

so shouldn't jquery become less forgiving, at least print error with `console.warn` ?

**Comment by timmywil** [comment]
Thanks for opening an issue. Input sanitization can get out of hand very quickly. Besides, doing this at runtime is not the best way to ensure you're passing the right arguments. Type checkers were built for this purpose and work at compile time, allowing your application to be free of all the checks at runtime.

**Comment by dmethvin** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jquery
