### ISSUE TITLE
$(el).load('SOME_HTML_FILE') with more than 1 svg throws an error.

### ISSUE THREAD

**Issue by Pckool** [jquery/jquery#4419]
### Description ###
While using the latest public version of jQuery (3.4.1), if you try to use the 'load()' function on a html page with more than 1 svg, the parent document will throw an error.
![image](https://user-images.githubusercontent.com/10131267/59155604-11fd9800-8a5b-11e9-8f54-83dee1dcc338.png)
All things point to an error in syntax in jQuery, but I couldn't figure out what it was.

What I expect to happen is jQuery to fully load the html document, svg's and all.

The issue seems to affect chromium based browsers (google chrome, new edge, etc.) as well as firefox.

A test case is difficult to provide, seeing as codepen does not seem to allow .load() (probably due to it being embedded in an iframe? Not sure.)

**Comment by dmethvin** [comment]
It is most likely a result of the limitations we have in loading a *full* document. It's described [in the docs](https://api.jquery.com/load/):

> jQuery uses the browser's .innerHTML property to parse the retrieved document and insert it into the current document. During this process, browsers often filter elements from the document such as <html>, <title>, or <head> elements. As a result, the elements retrieved by .load() may not be exactly the same as if the document were retrieved directly by the browser.

**Comment by Pckool** [comment]
Is there any way to get around this or is it just something we must deal with?

**Comment by dmethvin** [comment]
It might be possible on modern browsers with a same-domain `<iframe>` or a `document.implementation.createDocument()`. At the moment we need compat back to IE9 and there may be some issues with old browers. It's tricky because the `jQuery.load()` method should really just be loading a piece of HTML that will be valid inside the element where it's dropped in the existing document. So there are plenty of edge cases here. I've never encountered the problem you're describing but without a test case on our side it is going to be easier for you to experiment and let us know what you find.

**Comment by mgol** [comment]
[JS Bin](https://jsbin.com/) allows a standalone where test case is a standalone HTML page and the JS Bin button is an iframe inside of that. Maybe a test case would work there.

**Comment by Pckool** [comment]
Unfortunately I don't think that's a possibility. I just tried to use `$('id').load('some_external_url');` on [JS Bin](https://jsbin.com/) and no dice. 
It doesn't seem to load the document. The best I can do is create a repo and give it to you guys as a test case. Of course, I will do some testing on my own to see if I can discover a workaround, but as of right now, I'm a bit stumped.

**Comment by mgol** [comment]
It's hard to try to debug something based on just a description, including your JS Bin issue. Please provide a JS Bin with your attempts and we can see why it didn't work for you.

**Comment by timmywil** [comment]
We can reopen with a test case.
