### ISSUE TITLE
Simplified if else function.

### ISSUE THREAD

**Issue by SamirMokiem** [jquery/jquery#4426]
So i have been working with jquery for a while and with javascript. 
Now my question/discussion/feature request:

Let's say for example i have this code:
`
if (condition) {
        doTrue();
    } else {
        doFalse();
    }
`

or simply this:

`condition ? doTrue() : doFalse();`

I would suggest if it doesn't exist already, or if it doesn't need to be added, something like a new function that handles conditions inside the function. Example:

`$('#element').if(condition, show(), hide());`

`var minified = true;`
`$('#minifyButton').if(minified, hide(), show());`
`//Button is hidden because minified is true. And that will run the first function hide()`

The show() and hide() are run on the $('#element')

this could be extended to 'else' and 'elseif'

What are your opinions?

**Comment by timmywil** [comment]
Thanks for opening an issue. Personally, I prefer the native if statement. But see https://github.com/jquery/jquery/wiki/Adding-new-features. IMO, the answer to all of these questions is no. However, a few lines would be all that's needed to add this to your own code.
