### ISSUE TITLE
Broken link on *Adding new features* wiki page

### ISSUE THREAD

**Issue by pzygielo** [jquery/jquery#4427]
### Description ###
On wiki page [Adding new features](https://github.com/jquery/jquery/wiki/Adding-new-features) current link to *The Pitfalls of Boolean Trap* 
(linked as *confusing Boolean traps*) results in 404.

Correct one:
- https://ariya.io/2011/08/hall-of-api-shame-boolean-trap 
(i.e. with no html extension).

**Comment by timmywil** [comment]
Thanks! Link fixed.
