### ISSUE TITLE
jQuery is available on PageCDN

### ISSUE THREAD

**Issue by praisedpk** [jquery/jquery#4428]
PageCDN uses **brotli-11** compression that reduces jquery.min.js size by few more KBs compared to other CDNs. In addition, **immutable caching** is enabled by default to optimize jQuery delivery a little more aggressively. [jQuery CDN on PageCDN](https://pagecdn.com/lib/jquery).

    27.65 KB   jquery.min.js 
    22.13 KB   jquery.slim.min.js 

jQuery file sizes comparison on all [jQuery CDNs](https://pagecdn.com/list/jquery-cdn).

Thanks.

**Comment by timmywil** [comment]
Cool! Thanks for letting us know.
