### ISSUE TITLE
Save action called after file is fully uploaded in the native file input

### ISSUE THREAD

**Issue by BerlyChristopher** [jquery/jquery#4430]
While uploading the file using HTML native file input with JavaScript XMLHttpRequest with delay (adding debugger) in the server-side executions, we are receiving full file size in the loaded argument of the progress event. If we didn’t make delay's (adding debugger) in the server end, it's working properly.
We have attached the sample for the server-side application and native file input sample below.

**Satackblitz sample**: https://stackblitz.com/edit/vbrhk1-dqvmqp?file=index.ts

**MVC Application**: https://github.com/BerlyChristopher/uploader-service

Can you please anyone of telling us that **how to call the save action method before uploaded file fully loaded in the file input**?

Replication procedure:

1.	Run the stackBlitz sample and the attached MVC application.
2.	Upload the sample using HTML 5 native file input.
3.	Placed the debugger in the Save action in the controller file.
4.	Once you chose the file for upload, save action in the controller will be called.
5.	Please check the console in your browser at that time. You can get the chosen file size in the progress event.

**Comment by timmywil** [comment]
I think the best place for this question is probably stackoverflow.com or some other help forum. The sample doesn't even have jQuery; it uses the native XMLHttpRequest. If I missed something, feel free to comment and we can reopen if we find there is an issue to be addressed in jQuery core.
