### ISSUE TITLE
core3.4.0 no longer works with jquery.panzoom.min.js 3.2.2 

### ISSUE THREAD

**Issue by HansHollebrandse** [jquery/jquery#4436]
Issue: 
Using jquery.panzoom.min.js 3.2.2  together with jquery core 3.3.1 all works fine but not with versions equal or higher than jquery core 3.4.0 

What happens: 
Using jquery.panzoom.min.js 3.2.2 together with jquery core 3.4.0 or 3.4.1 the:
- zoom function of jquery.panzoom no longer works
- dragging no longer works

Browsers: 
Issue occurs in Firefox, Chrome and IE

Test case: 
If the demo from https://jsfiddle.net/timmywil/sdok6rjp/ is taken and the jquery core library is set to 3.4.0 the demo no longer works.

**Comment by mgol** [comment]
Thanks for the report but this is too broad for us to investigate on our own. We need a test case that doesn't contain external libraries.

You can also open an issue in the jquery.panzoom repository as people involved in that project might know better what changed from the things they relied on.

**Comment by timmywil** [comment]
That's my plugin :) As the description says in the panzoom repo, panzoom is no longer being maintained in its current state. I'm working on a rewrite and will reopen issues when that is ready.

**Comment by HansHollebrandse** [comment]
Hi Timmy,

Thank you for your reaction anyway.

Met vriendelijke groet / Best regards,

Hans Hollebrandse
AA-AS/EDS-WIR2

Tel. +31 76 7112-784
