### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by jayh99** [jquery/jquery#4437]
Would it be possible to add a GET request to jquery.com that returns the latest version number?  Something like https://jquery.com/version that simply returns 3.4.1?

**Comment by timmywil** [comment]
It's possible, but I don't think it would be useful enough. If I'm wrong, we can see how many upvotes this issue gets.

**Comment by mgol** [comment]
You can get the version by running:
```
npm info jquery dist-tags.latest
```
in terminal or by checking the URL to which https://unpkg.com/jquery redirects at the moment (currently https://unpkg.com/jquery@3.4.1/dist/jquery.js), or by looking at the newest tag on the repository (e.g. at https://github.com/jquery/jquery/releases), or via many other ways. I don't think it'd bring much value to create yet another way to expose the version and we don't have lots of resources to spare.

**Comment by dmethvin** [comment]
I agree that the best approach here is to use one of the package managers. That works for any dependency rather than just jQuery.
