### ISSUE TITLE
$(html) get the error html structure

### ISSUE THREAD

**Issue by asdevo** [jquery/jquery#4439]
browser: all,
jquery version: all,

dom: 
```
<script type="text/html" id="tpl_button">
<div>
...
</div>
<script type="text/javascript">
    $(function(){
        if(1 > 2) {
            alert(333)
        }
    });
</script>

</script>
```

js:
```
var html = $('#tpl_button').html();
$(html).appendTo(container) //error happen
```

error:
VM7227:3 Uncaught SyntaxError: Unexpected end of input
    at eval (<anonymous>)
    at Function.globalEval (jquery.js:343)
    at domManip (jquery.js:5291)
    at jQuery.fn.init.append (jquery.js:5431)

possible reasons:
$(html)[1] 
// get the error html structure
"<script type="text/javascript">
    $(function(){
        if(1 ></script>"

**Comment by mgol** [comment]
When creating inline scripts you need to be careful about escaping contents. I don't know the exact reason for your failure as there's no executable test case but the problem most likely lies outside of jQuery.

For the future, please provide a test case at [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested.
