### ISSUE TITLE
How is support going?

### ISSUE THREAD

**Issue by Hubertnator** [jquery/jquery#4442]
Just curious; is there a planned date for a release? And is 3.4.2 getting nearer?

**Comment by timmywil** [comment]
Thanks for opening an issue. You can find the remaining issues for 3.4.2 [here](https://github.com/jquery/jquery/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.4.2). We don't have an exact date planned for release, just whenever we can get the remaining items done.
