### ISSUE TITLE
JQMIGRATE: jQuery.browser is deprecated

### ISSUE THREAD

**Issue by mreacway** [jquery/jquery#4443]
Bug Reports: jQuery.browser is deprecated on Google Chrome latest version. 

why is this occurring? we also get the same error on Microsoft Edge, version is 42 though. 

![Capture](https://user-images.githubusercontent.com/53499249/62175856-71549600-b382-11e9-8e0b-b65efd934588.PNG)

**Comment by timmywil** [comment]
jQuery migrate is a plugin that helps users migrate from older versions to newer versions. While it was built as a development-only tool, you'll find it's been deployed to production on some sites. This console warning is simply informing the user that `jQuery.browser` is being used in their code somewhere and they should migrate away from it.

**Comment by timmywil** [comment]
More info [here](https://github.com/jquery/jquery-migrate).

**Comment by dmethvin** [comment]
Also, it doesn't matter which browser the code is running on if the code uses `jQuery.browser`. It can be running on the latest Chrome. Something inside that site's own JavaScript is using it, and that is why the warning appears.
