### ISSUE TITLE
Clone method is breaking

### ISSUE THREAD

**Issue by viveknarkhede** [jquery/jquery#4444]
In Jquery 3.4.1 version, Clone method breaks with below error message on IE11.

Unable to get property 'nodeName' of undefined or null reference

Same clone method was working fine in Jquery 1.12.4 version.

**Comment by mgol** [comment]
Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by viveknarkhede** [comment]
Thanks for the reply mgol.
For the code please refer code snippet shown at https://jqueryui.com/sortable/#connect-lists
In the sortable's activate event, i am trying to clone the ui.item so that when i drop the current item on another sortable list it should not get removed from the source sortable list.

**Comment by mgol** [comment]
Still, we need a runnable test case, not just a link to the docs plus an explanation of modifications done. Also, it'd be ideal to have a test case without external (to jQuery) libraries but if it's just about calling `clone` manually then maybe it's fine to have UI there as a way to just prepare the environment.

**Comment by viveknarkhede** [comment]
Sorry, i do not have any test case. May be standalone clone method will execute as expected, but with this external library it is failing.

I have compared the unminified versions of 1.12.4 and 3.4.1, what i found is as below:

**jquery : 1.12.4 ==> clone function excerpt**
`			// Fix all IE cloning issues
			for ( i = 0; ( node = srcElements[ i ] ) != null; ++i ) {

				// Ensure that the destination node is not null; Fixes #9587
				if ( destElements[ i ] ) {
					fixCloneNodeIssues( node, destElements[ i ] );
				}
			}
`
**jquery : 3.4.1 ==> clone function excerpt**
`			for ( i = 0, l = srcElements.length; i < l; i++ ) {				
				fixInput( srcElements[ i ], destElements[ i ] );				
			}

`
Looks like in the latest version, destElements[ i ] is not checked before passing it to fixInput method. When i add the condition in my local copy, it worked.

**Comment by dmethvin** [comment]
bugs.jquery.com seems to be down, but the mentioned ticket is https://web.archive.org/web/20170909222753/https://bugs.jquery.com/ticket/9587 . The test case from that is http://jsfiddle.net/Mottie/zQxgH/ . Does that test fail for you on IE11? If not, maybe you can create one from it.

**Comment by mgol** [comment]
Closing as we have no test case. I tried the one @dmethvin posted but I don't see any error there; we also already have a test case added in #412 for that issue. I also tried to construct a test case based on what @viveknarkhede reported but I also see no error, either in IE 11 or even IE 9: https://output.jsbin.com/qisepur

@viveknarkhede We can reopen if you provide a test case that breaks in IE.
