### ISSUE TITLE
Destroy autocomplete causing layout thrashing

### ISSUE THREAD

**Issue by tamilarasan** [jquery/jquery#4449]
### Description ###

I have page which is having nearly 500 autocomplete instance, during destroy it's causing huge slowness because of layout thrashing.

*  What do you expect to happen?

   It should destroy autocomplete without any major delay.

*  What actually happens?

   It took nearly 11 seconds to destroy 500 autocomplete instance.

### Profile ###

<img width="1439" alt="Screen Shot 2019-08-06 at 2 57 58 PM" src="https://user-images.githubusercontent.com/309240/62529053-84bca100-b85b-11e9-9f3d-583f79d331fa.png">

### Link to test case ###

[https://jsbin.com/patoziqufo](https://jsbin.com/patoziqufo)

**Comment by dmethvin** [comment]
> I have page which is having nearly 500 autocomplete instance

Wow!

Autocomplete isn't part of jQuery core so I'll close this.
