### ISSUE TITLE
Selector for hidden option

### ISSUE THREAD

**Issue by mpeirone** [jquery/jquery#4463]
Hi, I'm trying to hide some options and than understand what is hidden and what is not but all these selectors retrive the same result which is wrong. Do you know why? Is this a bug?
Thank you 
Matteo

### HTML ###
```
<select id="idselect">
<option value="value1" id='option1'>HTML1</option>
<option value="value2" id='option2'>HTML2</option>
<option value="value3" id='option3'>HTML3</option>
</select>
```
### JS ###
```
$( document ).ready(function() {
    $("#value1").hide()
    var a=$("#option1").find('option:visible')
    console.log(a)
    var b=$("#idselect").find('option:not(:hidden)')
    console.log(b)
    var c=$("#idselect").find('option[hidden=false]')
    console.log(c)
    var d=$("#idselect").find('option:not([hidden=true])')
    console.log(d)
    $("#idselect").find('option').each(function(){
    	console.log($(this).prop('hidden'))
    })
});
```

**Comment by rajavardhan2geek** [comment]
@mpeirone 
you need to use #Id to hide elements.

**Comment by mgol** [comment]
Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? It should be clear from the test case what results you expect so that it's easy to compare what you get in a test case. Thanks!

**Comment by mpeirone** [comment]
https://jsfiddle.net/mpcom/6fcqu0k5/

The expected result:
1
1
1
2
false
true
false

**Comment by mgol** [comment]
Thanks for the test case. I assume where you put numbers in "expected result" you mean lengths of respective collections?

A few things here:
* The check for the `hidden` prop & the `hidden` attribute should return `false` as this prop is not set; `.hide()` works on the `display` CSS property, not on properties. That covers all the checks except for the first two and browsers are consistent here
* The remaining things are `:visible` & `:hidden` which are jQuery selector extensions defined in [src/css/hiddenVisibleSelectors.js](https://github.com/jquery/jquery/blob/3.4.1/src/css/hiddenVisibleSelectors.js). `:hidden` is defined as a negation of `:visible` so we can focus on the latter. And browsers differ here:
  * Chrome 76, Safari 12.1 & Edge 18 match 0 elements for `:visible`
  * Firefox 68 matches 2 elements. Its results for those two:
    ```
    offsetWidth: 39
    offsetHeight: 14
    getClientRects().length: 1
    ```
  * IE 11 matches 3 elements for `:visible`. The results are not affected by `display: none`:
    ```
    offsetWidth: 0
    offsetHeight: 0
    getClientRects().length: 1
    ```
    The rect returned by `getClientRects()` has all properties set to `0`.

It seems like an inconsistency that we should solve. I need to verify what the spec mandates but to me the Chrome behavior makes more sense - all the options are really hidden as they are displayed only when you activate a particular select.

The test case for the results I provided above: https://output.jsbin.com/bawosuv

**Comment by mgol** [comment]
From a quick look at [the CSSOM spec](https://drafts.csswg.org/cssom-view/), all three properties (`offsetWidth`, `offsetHeight` & `getClientRects`) are expressed in terms of [_CSS layout box_](https://drafts.csswg.org/cssom-view/#css-layout-box) which has a note in the spec:

> **ISSUE 1** The terms CSS layout box and SVG layout box are not currently defined by CSS or SVG.

That indicates we're in a gray area here.

**Comment by timmywil** [comment]
If the options take up space according to the layout box, perhaps the behavior should be left as-is. Otherwise, we'd be saying something is hidden in browsers where they technically are not, right?

**Comment by mgol** [comment]
API issue: https://github.com/jquery/api.jquery.com/issues/1149
Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1584752

I'm closing the issue per @gibson042's comment at https://github.com/jquery/jquery/issues/4463#issuecomment-529558196.
