### ISSUE TITLE
Inconsistent callback execution order

### ISSUE THREAD

**Issue by adriangodong** [jquery/jquery#4468]
### Description ###

`jQuery@3.4.1`

Code:
```
var deferred = $.Deferred();
deferred.then(function() { console.log("done"); });
deferred.always(function() { console.log("always"); });
deferred.resolve();
```

Output:
```
always
done
```

Expected:
`done` callback should be executed first and then `always` callback.

**Comment by tom-sherman** [comment]
This is how I would expect it to work too when comparing to native promises:

```javascript
Promise.resolve()
  .then(() => console.log('done'))
  .finally(() => console.log('always'))
```

Output:

```
done
always
```

**Comment by dmethvin** [comment]
The `.done`, `.fail`, and `.always` methods are synchronous, based on the original jQuery `Deferred` semantics. The `.then` and `.catch` methods are based on the standard `Promise` semantics and so they're async. Mixing them in the same chain is a sure-fire way to create confusing code. If you have suggestions on how to clarify this it would be great to propose wording over at https://github.com/jquery/api.jquery.com/ .

As for `.finally` in jQuery `Deferred`, see #4290.

**Comment by mgol** [comment]
Closing due to Dave's explanation.
