### ISSUE TITLE
About `fadeOut()` function.

### ISSUE THREAD

**Issue by BigCoke233** [jquery/jquery#4474]
> Don't worry. It's not a bug.

### Description ###
The function `fadeOut()` would hide the element after animation. But sometimes I want it not to do so.  I want elements just disapear like `visibility:hidden` and still occupy its space after animation. Maybe you can set a new function or set a new parameter for `fadeOut()`. I think it's useful for some developer.

### Link to test case ###
None.

**Comment by timmywil** [comment]
Thanks for opening an issue. It's hard to cover every use case when it comes to effects. `fadeOut` is meant to cover a common one. For something like what you're suggesting, it could be done with `animate` and made a plugin. It's unlikely we'd add something like this to core tho.
