### ISSUE TITLE
Make `.fadeIn()` and similar methods thenable

### ISSUE THREAD

**Issue by tom-sherman** [jquery/jquery#4476]
### Description ###

Make methods such as `.fadeIn()` that accept a done callback thenable. This would avoid callback hell when you have nested fadeIns for example. See below for the comparison in syntax

**Current**

```javascript
$('.foo').fadeIn(() =>
	$('.bar').fadeIn(() =>
		$('.baz').fadeIn() 
))
```

**Proposed**

```javascript
$('.foo').fadeIn()
	.then(() => $('.bar').fadeIn())
	.then(() => $('.baz').fadeIn())
```

### Link to test case ###

I've made a `deferredFadeIn` plugin which has a very naive implementation of the proposal above.

https://jsbin.com/sikajadosu/2/edit?html,js,output

**Comment by mgol** [comment]
Animation methods are chainable, they return the original jQuery object on which you can trigger further animations, e.g.:
```js
$('.foo').fadeOut().fadeIn();
```
Because of that, it's not possible to make them return a promise. Changing that now would be a big breaking change and I don't think it's worth it.

**Comment by tom-sherman** [comment]
Could we make the returned object "thenable" instead of returning a fully fledged promise? This is how my demo above works.

This would allow for both chaining use cases, as well as `await`ing the animation ([reference](https://www.stefanjudis.com/today-i-learned/await-in-async-functions-works-for-any-thenable/))

**Comment by dmethvin** [comment]
This sounds just like the `.promise()` method, does that work for you?
https://jsbin.com/tasuhaxigo/2/edit?html,js,console,output

**Comment by tom-sherman** [comment]
Yes this works perfectly thanks, even for multiple `then`s.

```javascript
$('.red').fadeIn().promise()
  .then(() => $('.blue').fadeIn().promise())
  .then(() => $('.green').fadeIn().promise())
  .then(() => $('.orange').fadeIn().promise())
})
```
