### ISSUE TITLE
CSP inline style violations

### ISSUE THREAD

**Issue by jezzsantos** [jquery/jquery#4477]
I am trying to apply a robust CSP policy to our app.
We are using jQuery 3.4.1 as a dependency of Bootstrap 3.3.7. (we don't call any jQuery directly).
We are using random nonces to bring the jquery script into our codebase, (either directly like below, or in a minified bundle).
```
<script type="text/javascript" src="/Scripts/jquery/jquery-3.4.1.js" nonce="SkpwbEc3bzF6SEx5akJ1STFYTks="></script>
```
We are experiencing a number of CSP violations that not even `'strict-dynamic'` and CSP 3.0 policy can accept.

How to apply a secure CSP policy to jQuery? 
(without bypassing my policy with `'unsafe-inline'`, which is not an acceptable solution)?

These are the 3 main offenders, that currently break our policy.

![jquery1](https://user-images.githubusercontent.com/3137590/64481694-d75ff300-d235-11e9-9153-68b020f3b164.PNG)
![jquery2](https://user-images.githubusercontent.com/3137590/64481695-d7f88980-d235-11e9-8d4e-baa6c475b293.PNG)
![jquery3](https://user-images.githubusercontent.com/3137590/64481696-d7f88980-d235-11e9-988d-9c85da5eb41d.PNG)

**Comment by dmethvin** [comment]
Bootstrap is injecting inline styles using jQuery. That's why jQuery shows up here. To avoid triggering CSP violations you would probably need to change the way Bootstrap injects styles.

**Comment by jezzsantos** [comment]
I'll investigate that. However, at the end of the day, jQuery is the one providing the abstraction that a consumer (Bootstrap in this case) is using to achieve something meaningful. It's jQuery's that has implemented the precise code that CSP cannot acccept.

**Comment by dmethvin** [comment]
If Bootstrap is injecting inline styles it would need to provide the nonce that you created for inline styles. jQuery doesn't know that nonce, it wasn't part of that transaction.
