### ISSUE TITLE
A question about the impact may be caused by table's clientWidth/Height behavior change of Chromium

### ISSUE THREAD

**Issue by joonghunpark** [jquery/jquery#4484]
### Description ###

* The original post for this subject is https://forum.jquery.com/topic/a-question-about-the-impact-may-be-caused-by-table-s-clientwidth-height-behavior-change-of-chromium.

Hi, I'm a contributor of Chromium Project.

I made a change of https://chromium-review.googlesource.com/c/chromium/src/+/1763510
which make table's clientWidth/Height match to its offsetWidth/Height.

The corresponding issue page for that change is https://bugs.chromium.org/p/chromium/issues/detail?id=978019.

In case of Firefox, its already has that behavior, and that is what we intend to introduce by the change above
(In perspective of interoperability, it would be good I think).

I got a positive feedback from David Grogan in Chromium Community to apply that change to Chromium repo,
and also heard from him that
"the client* properties are used in something like $("blah").outsideWidth or insideWidth or something."

So I wonder jQuery community could share with us about how much breakage the change might cause, whether jQuery would be ok if Chromium adopt the behavior above,
and if it's ok, how jQuery going to adapt to the change.

I'm not sure here is the right place to ask this question,
so if it's not, please let me know to correct the place of this question.

Thank you for your help:)
Joonghun Park

**Comment by mgol** [comment]
Thanks for the information! From what I see jQuery doesn't rely on `clientWidth`/`clientHeight` internally (with the exception of `document.documentElement`), only on `offsetWidth`/`offsetHeight`. Since your change changes the `client`-prefixed properties (am I right?) the change shouldn't affect us.

**Comment by davidsgrogan** [comment]
Ah, I thought it was used in https://github.com/jquery/jquery/blob/master/src/dimensions.js but on another look, that's only for the window and document elements?

**Comment by mgol** [comment]
@davidsgrogan Only documentElements, not even `window`.

**Comment by timmywil** [comment]
Looks like the change will be safe. Thanks for checking @davidsgrogan
