### ISSUE TITLE
Broken core.js file is dist packages

### ISSUE THREAD

**Issue by stof** [jquery/jquery#4489]
### Description ###

starting from 3.0.0-rc1, the jquery-dist repo contains a `core.js` file, which seems to be a copy of one of the source files. This file is not usable (it has AMD dependencies on other files which are not copied), so including it in the releases looks wrong.

**Comment by mgol** [comment]
Which AMD dependencies are not copied? The file should be usable.

**Comment by stof** [comment]
see https://github.com/jquery/jquery-dist/blob/3.4.1/dist/core.js

This files depends on a bunch of AMD dependencies which are not part of the distribution at all.

**Comment by stof** [comment]
files in `src` are fine. But this file is in the `dist` folder.

**Comment by mgol** [comment]
Ah, you're right! I don't know how that file gets there, there must be a bug in the release process. @timmywil any ideas?

**Comment by mgol** [comment]
It looks like it's enough to remove `src/core.js` from the `files` array as it was before. The version swapping should still work, I performed a test `jquery-release` run locally to confirm that.

PR: #4492
