### ISSUE TITLE
Table row height reported incorrectly in Edge

### ISSUE THREAD

**Issue by TPIvan** [jquery/jquery#4490]
### Description ###
When css height is specified on **`tr`** element (`<tr id="myrow" style="height:1px;">`) **`.height()`** returns this height instead of actual height.  The problem is present in **Microsoft Edge** (42.17134, 44.18362) but not present in Google Chrome ( 77.0.3865.90 ) and Mozilla Firefox (69.0.1). The problem is present since jquery 3.3.0 and was reproduced on earlier versions. And is present on current git version (4.0.0-pre 50871a5a85cc802421b40cc67e2830601968affe)

How to reproduce. Create a table with one row (`tr`) and one cell (`td`) with text in the cell. Set the row height to 1px (`style="height:1px;"`). JQuery .height() on the row should return at least font height but actually returns 1 in **Edge**.

### Link to test case ###
https://codepen.io/TPIvan/pen/aboxZaQ

**Comment by mgol** [comment]
Thanks for the issue & the test case! I recreated it on JS Bin as CodePen doesn't support IE: https://output.jsbin.com/xusurij/1.

The issue exists on IE 9-11 as well.

**Comment by mgol** [comment]
The issue is that `getComputedStyle` on a `tr` with height set via inline styles returns that inline style, disregarding the internal contents. `getBoundingClientRect` doesn't have that issue, neither does `offsetHeight`. In IE/Edge we seem to have a choice between occasionally incorrect height on table rows and losing fractional values on those rows.

**Comment by gibson042** [comment]
`getBoundingClientRect` is the wrong tool for the job of CSS box model introspection, and we were right to abandon it. But `offset{Width,Height}` seem like acceptable graceful degradations to use.

**Comment by hichemsmairia** [comment]
whats the problem here guys

**Comment by timmywil** [comment]
@hichemsmairia @mgol describes the issue above. IE10, 11, and Edge report the wrong value using `getComputedStyle` in this use case.

**Comment by zzz6519003** [comment]
Vue get crazy

**Comment by mgol** [comment]
PR for `3.x-stable`: https://github.com/jquery/jquery/pull/4503

**Comment by mgol** [comment]
Fix landed on `master` in 26415e081b318dbe1d46d2b7c30e05f14c339b75 & on `3.x-stable` in 6d31477a35bfa70d209522b5e8c7e948b6c4d599.
