### ISSUE TITLE
Publish a working version of jquery/PEP

### ISSUE THREAD

**Issue by bertho-zero** [jquery/jquery#4491]
There are 2 `const` in the PEP polyfill destined for old browsers, can you publish a new version with one of the 3 PRs that fixes this problem?

https://github.com/jquery/PEP

Issues:
- https://github.com/jquery/PEP/issues/384
- https://github.com/jquery/PEP/issues/385

Pull requests:
- https://github.com/jquery/PEP/pull/382
- https://github.com/jquery/PEP/pull/385
- https://github.com/jquery/PEP/pull/387

**Comment by mgol** [comment]
This is a jQuery repository, PEP is at https://github.com/jquery/PEP. I see you've already reported the issue at https://github.com/jquery/PEP/issues/390.

The teams for jQuery & other projects are separate, neither of us is working on PEP AFAIK.
