### ISSUE TITLE
.click() is calling callback function 3 times

### ISSUE THREAD

**Issue by matheusab** [jquery/jquery#4493]
### Description ###

When calling $(...).click() on a checkbox input that has an `onclick` property defined, its callback gets called three times.

Apparently this behavior was introduced on 3.4.0.

PS.: Tested on chrome 76

### Link to test case ###
The following scripts should append "1" to the body when clicking either the checkbox or the button

[jsfiddle: v3.4.1, broken](https://jsfiddle.net/matheusab/81d6gk9v/)
[jsfiddle: v3.3.1, working](https://jsfiddle.net/matheusab/81d6gk9v/1)

**Comment by dmethvin** [comment]
Inline event handlers are notoriously unreliable, and we don't have much if any test coverage for them as a result. They are on our [wontfix list](https://github.com/jquery/jquery/wiki/Won't-Fix#inline-event-handlers) for that reason. I'm guessing this is a side effect of #4279?

Other issues with inline handlers:
* https://github.com/jquery/jquery/issues/3660
* https://github.com/jquery/jquery/issues/3146
* https://github.com/jquery/jquery/issues/2918
* https://bugs.jquery.com/ticket/12899

**Comment by PachVerb** [comment]
The details of the discussion made me shocked and moved.

**Comment by mgol** [comment]
Closing per Dave's comment.
