### ISSUE TITLE
IE11 some events are not registered when added with the .html function. 

### ISSUE THREAD

**Issue by Xivilian** [jquery/jquery#4497]
### Description ###
There are several related problems, 
When you have in plain HTML a table tag and add a tr td and a button in the td with an on click event with the jquery html function, the click event does not get registered. 
For example https://jsfiddle.net/ft25m9y8/ (You have to retry this yourself in Internet Explorer 11, I couldn't find a fiddle equivalent that supports IE 11 unfortunately). 
My expectations are that the button will be clickable and that "foo" appears on the screen. However in IE11 the button is clickable but foo does not appear. 

Example 2: 
If you have in plain HTML a div tag and add a button in the div, the on click event on the button does not get registered. 
For example : https://jsfiddle.net/71urv6ga/ same thing, this does not work in IE, becuase fiddle does not work there, you have to produce it locally. 
I expect that foo shows up after the code runs in IE 11.
### Link to test case ###
https://jsfiddle.net/ft25m9y8/
https://jsfiddle.net/71urv6ga/

**Comment by mgol** [comment]
> I couldn't find a fiddle equivalent that supports IE 11 unfortunately

[JS Bin](https://jsbin.com) supports IE 9+. The issue template mentioned JS Bin explicitly, have you read it?

However, inline event handlers are discouraged; they're underspecified & behave differently than handlers added via `addEventListener` so they're on the jQuery Won't fix list: https://github.com/jquery/jquery/wiki/Won't-Fix#inline-event-handlers.
