### ISSUE TITLE
empty() method is not working for documentFragment DOM elements

### ISSUE THREAD

**Issue by webdeveloperukraine** [jquery/jquery#4502]
There is an issue with `empty()` method of jQuery containers. It is actually does not work for documentFragment elements. 
Example:
```javascript
var $fr = $(document.createDocumentFragment());
for(let i=0;i<5;i++){
    $span = $("<span>"+i+"</span>");
    $fr.append($span);
}
$fr.empty();
$('body').append($fr);
```
**Expected:** no new elements appeared in DOM
**Actual result:** 5 span elements appeared in DOM

**JSBin snapshot:** 
https://jsbin.com/vilefamiko/edit?html,output

And it works fine with jQuery 1.x version:
**JSBin snapshot:**
https://jsbin.com/patoqunire/edit?html,output

I was able to find the code that cause this issue:
If we will look into the **jQuery 3.4** source code:
```javascript
empty: function() {
    var elem,
        i = 0;

    for ( ; ( elem = this[ i ] ) != null; i++ ) {
        if ( elem.nodeType === 1 ) {

            // Prevent memory leaks
            jQuery.cleanData( getAll( elem, false ) );

            // Remove any remaining nodes
            elem.textContent = "";
        }
    }

    return this;
},
```
As we can see, the `empty` method affect only DOM elements with `nodeType === 1` (documentFragment has `nodeType` equal to 11)

But from the **jQuery 1.12** source code:
```javascript
empty: function() {
    var elem,
        i = 0;

    for ( ; ( elem = this[ i ] ) != null; i++ ) {

        // Remove element nodes and prevent memory leaks
        if ( elem.nodeType === 1 ) {
            jQuery.cleanData( getAll( elem, false ) );
        }

        // Remove any remaining nodes
        while ( elem.firstChild ) {
            elem.removeChild( elem.firstChild );
        }
        
        ...
        
    }

    return this;
},
```
We can see that after `// Remove any remaining nodes` placed out from `if ( elem.nodeType === 1 ) {` condition, and 
```javascript
while ( elem.firstChild ) {
    elem.removeChild( elem.firstChild );
}
```
allows us to remove all child elements from documentFragment either.

**Comment by mgol** [comment]
Wrapping document fragments with `jQuery` is unsupported, please see https://api.jquery.com/jQuery/#jQuery-element.
