### ISSUE TITLE
Fallback mechanism if an element is not found

### ISSUE THREAD

**Issue by catchmareck** [jquery/jquery#4514]
### Description ###

I was wondering why there is no built-in method that would allow us to select an element only if another element is not found. I'm thinking of some fallback mechanism, similar to JS's `||` operator:

```javascript
const $elem = $('#firstElem') || $('#secondElem');
```

Of course, this won't work for obvious reasons but I think there could be a method similar to the one proposed in this SO answer: https://stackoverflow.com/a/7190180/7080548

```javascript
jQuery.fn.fallback = function(elem) {
    return 0 < this.length ? this : $(elem);
};
```
and that could be used like this:

```javascript
const $elem = $('#raphael').fallback('#leonardo').fallback('#kilik');
```

Of course, it's easy to add those 3 lines of code to your project and use this plugin but you need to remember to paste the same piece of code in every project you need it in ;)

Is there a good reason for not having it as a built-in feature? (I'm sure there is but would like to know it)

**Comment by mgol** [comment]
Thanks for the report.

See https://github.com/jquery/jquery/wiki/Adding-new-features

In general, we're not looking to add many new APIs; the ones we add result from a concrete need, they are either needed to ease migration from a deprecated API or ones that fit really well to what we already do. The function you proposed would be best done in a plugin. Plugins are fine, not everything has to be in Core!

**Comment by catchmareck** [comment]
Sure, thanks for the explanation. Cheers!
