### ISSUE TITLE
jstree jquery search very slow

### ISSUE THREAD

**Issue by chinmaya312** [jquery/jquery#4521]
When using the Jquery Search to display the jstree its taking more than 10 mins for a very large sites of around 20000 records

var result = $('#treeAppletDiv').jstree('search', $('#search').val());

Is there any other alternate to speed up the search or any other suggestion.

As its creating lots of slowness issue for the users

**Comment by mgol** [comment]
Issues with jQuery plugins should be reported to plugin authors, not to jQuery itself.
