### ISSUE TITLE
Ensure .offset sends px-ed strings to .css()

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery#4525]
### Description ###

We deprecated passing numbers to CSS, which migrate warns about, but offset passes the numbers internally. Append the 'px' before passing to `.css()`.

**Comment by mgol** [comment]
Fixed for `3.5.0` in #4508 but we still need a fix for 4.0.

**Comment by mgol** [comment]
PR: #4651

**Comment by mgol** [comment]
We've decided to fix this on the Migrate side by not warning against properties from the whitelist that will still have `px` auto-appended. More details in https://github.com/jquery/jquery/pull/4651#issuecomment-608384853.
