### ISSUE TITLE
Textbox focus select is not working in 3.4.1

### ISSUE THREAD

**Issue by rahulg1001** [jquery/jquery#4527]
### Description ###
As you can see below, this code is to select entire textbox value on focus but it doesn't work in 3.4.1 which was working in 3.3.1.

 $('#textbox).focus(function () {
        $(this).one('mouseup', function (event) {
            event.preventDefault();
        }).select();
    });

**Comment by mgol** [comment]
Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by rahulg1001** [comment]
I have provided a snapshot. As per this demo, it doesn't work 1st time. However, it was working fine in 3.3.1.

https://jsbin.com/hovifil/1/edit?html,css,js,output

**Comment by mgol** [comment]
Thanks for the test case. I tried to reduce the example you provided but there are a few issues with it:

1. Inline event handlers are [not supported by jQuery](https://github.com/jquery/jquery/wiki/Won't-Fix#inline-event-handlers), please refactor the code to use regular jQuery APIs.
1. The `FocusText1` function attaches a new additional focus handler per each click on the input element. That leaks memory.
1. When I tried to reduce the test case, it doesn't work as you'd expect it to even in jQuery 3.3.1: https://jsbin.com/sawugoj/edit?html,js,console,output

Please provide a test case without these issues.
