### ISSUE TITLE
HTTP Parameter Override

### ISSUE THREAD

**Issue by zgosalvez** [jquery/jquery#4535]
ZAP Scanning Report flags `jquery-3.4.1.slim.min.js` with an HTTP Parameter Override vulnerability. It appears that the method to create a form is being picked up since it's a simple `<form></form>` insertion.

Medium (Low) | HTTP Parameter Override
-- | --
Description | Unspecified form action: HTTP parameter override attack potentially possible. This is a known problem with Java Servlets but other platforms may also be vulnerable.
 
URL | jquery-3.4.1.slim.min.js
Method | GET
Evidence | <form>
Instances | 1
Solution | All forms must specify the action URL.
Reference | http://download.oracle.com/javaee-archive/servlet-spec.java.net/jsr340-experts/att-0317/OnParameterPollutionAttacks.pdf
CWE Id | 20
WASC Id | 20
Source ID | 3

**Comment by mgol** [comment]
Thanks for the report.

The code you mentioned comes from a support test at:
https://github.com/jquery/jquery/blob/3.4.1/src/core/support.js#L15
The test creates a new document and puts two empty forms inside to check if parsing behaves correctly. Afterwards, the document is not used anymore and it's impossible to access it. Therefore, I think this security alert is incorrect.

BTW, in jQuery 4.0 this test will no longer exist but it's hard to tell when we'll be ready to release that version and that's not going to happen soon.
