### ISSUE TITLE
Configure sponsor on GitHub

### ISSUE THREAD

**Issue by vanillajonathan** [jquery/jquery#4539]
Configure jQuery on GitHub to display a sponsor button for the JS Foundation.

https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository

https://js.foundation/about/donate

**Comment by timmywil** [comment]
Thank you for the suggestion. There are legal issues around accepting donations and I think the safest action is to leave it alone for now. Also, the JS Foundation is now the OpenJS Foundation.

**Comment by vanillajonathan** [comment]
The jQuery website still mentions "JS Foundation" and have a donate link.

**Comment by timmywil** [comment]
True, some things are out of date. I'm sure donations made using that link would still go to good use, but we won't be adding a Sponsor button to that link.

**Comment by vanillajonathan** [comment]
Okay, can we get someone to update the website?
