### ISSUE TITLE
install via npm directly from github

### ISSUE THREAD

**Issue by alexey-sh** [jquery/jquery#4540]
### Description ###
I want to install the awesome jquery library via the following command
`npm i git+https://github.com/jquery/jquery.git`

but after that, there is nothing in the dist directory
```
ls node_modules/jquery/dist
ls: node_modules/jquery/dist: No such file or directory

```

**Comment by mgol** [comment]
Why do you want to install from GitHub? jQuery is published to npm, you can just run `npm install jquery`. You can also install from https://github.com/jquery/jquery-dist but that just contains what we have on npm so it doesn't bring lots of benefits.
