### ISSUE TITLE
Build: transpile ES modules to AMD

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#4545]
### Description ###

As of #4510, jQuery source is authored using ES modules. We still want to expose AMD modules, though, perhaps via an `amd` directory that gets automatically transpiled from `src` in the build process.

### Link to test case ###

N/A

**Comment by brettz9** [comment]
Will you also provide an ESM distribution, or at least point to a non-bundled entry point with `module` in `package.json` so bundlers like Rollup can discover it?

**Comment by mgol** [comment]
This issue was fixed by #4554.

**Comment by mgol** [comment]
@brettz9 We'll at least provide the `src` directory with ES module sources that you can consume. I'm thinking about exposing something via `package.json` but I haven't done the research yet. If you have suggestions on how to configure it so that it's as usable as possible, please submit an issue with suggestions!
