### ISSUE TITLE
Custom events - weird problem with iframe

### ISSUE THREAD

**Issue by insad** [jquery/jquery#4547]
I have a page (index.html) with an embedded iframe; on loading a second page (content.html) into this iframe, I capture a reference to the loaded document in the "load" event (in variable "doc").

The document loaded into the iframe (content.html) has an event listener for a custom event "myEvent".

When I trigger "myEvent" on the doc reference captured in the main page (index.html), nothing happens (event handler is never called in content.html).

However, I can manipulate the contents of the loaded document by the doc reference, so this reference must be ok!

Tested with FireFox 70.0.1 and Chrome 78.0.3904.97

Please find a test case:
https://gist.github.com/insad/595a154057af495417e917132a3a1a2f

**Comment by dmethvin** [comment]
The iframe element in the parent isn't the element that receives events from the iframe. Try the .document of that element. There should be plenty of examples on StackOverflow.
