### ISSUE TITLE
Does Node.js / npm used for build support LTS?

### ISSUE THREAD

**Issue by tcs1203** [jquery/jquery#4555]
Does Node.js / npm used for build support LTS?
If supported, could you write supported version to document?

**Comment by mgol** [comment]
Building jQuery is supported in all the versions of Node.js that are supported themselves. You can see the list of Node.js versions we test against at https://github.com/jquery/jquery/blob/master/.travis.yml and the Node.js support policy at https://github.com/nodejs/Release

**Comment by timmywil** [comment]
We could note that, but I think if any issues arise in any version of Node, users can submit an issue and we'll consider addressing it regardless. We'd don't get a lot of issues pertaining to an older version of Node that does not also affect the lts or latest versions.
