### ISSUE TITLE
Could you like to add https connection (git clone)?

### ISSUE THREAD

**Issue by tcs1203** [jquery/jquery#4556]
In https://github.com/jquery/jquery/blob/master/README.md

`git clone git://github.com/jquery/jquery.git`

Could you like to add the following sentence?

`git clone https://github.com/jquery/jquery.git`

It is helpful to write it for people who cannot use ssh connection.

**Comment by mgol** [comment]
If you have a suggested wording - it seems we should include both ways in README - we would be happy to evaluate a PR. Do you want to submit one?

**Comment by DanielRuf** [comment]
The current clones using Got, the https uses a different auth (form) and is often not the best solution.

You can see both in the clone button here on GitHub.

**Comment by ashwani99** [comment]
@mgol I would like to submit a PR on this.

**Comment by mgol** [comment]
We decided to use a different approach - to instead remove the current instructions and just link to the GitHub docs on cloning, see #4571.
