### ISSUE TITLE
Respect prefers-reduced-motion: reduce

### ISSUE THREAD

**Issue by CharlesBelov** [jquery/jquery#4557]
### Description ###

It is an emerging best practice for websites to respect prefers-reduced-motion: reduce, in which a site visitor has indicated in their operating-system preferences that they don't want animation. This could be because animation makes them sick (vestibular disorder), distracts them (hypervigilance and others), or simply slows them down (power user). Firefox, Chrome, and Safari support exposing this information to websites; Edge has proposed supporting it as well.

I am requesting that if prefers-reduced-motion is set to reduce, that jQuery .animate and scrolling commands respect this setting and not animate from one state to the other.

Additional information on prefers-reduced-motion can be found at [Responsive Design for Motion](https://webkit.org/blog/7551/responsive-design-for-motion/), and [Designing Safer Web Animation For Motion Sensitivity](https://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity) (**Warning:** Two commenters on that last article report that they found the (stationary) illustration at the top of the article triggering as a simulation of the disorder.)

For comparable programming discussions on the matter, [Bootstrap has issues concerning prefers-reduced-motion.](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue+reduced-motion).

If this is implemented, there may be a need for an additional parameter on .animation to indicate that a particular animation is essential. For instance, animation might be used to demonstrate a technique. If such an additional feature were added, the best practice would seem to be that it would not autoplay when prefers-reduced-motion: reduce applies.

**Comment by mgol** [comment]
Thanks for the report.

If I understand it correctly, `prefers-reduced-motion: reduce` means animations should be _reduced_, not _eliminated_ - and that such limitations essentially need to be context-aware and animations shouldn't be disabled completely in all places. This would suggest taking `prefers-reduced-motion` into account is more a job for UI libraries like jQuery UI or Bootstrap, not necessarily for jQuery Core that only provides animations APIs devoid of context. This is also why CSS transitions/animations as well as the Web Animation API don't take this setting into account as it's not their job.

What do you think?

**Comment by CharlesBelov** [comment]
I'll acknowledge that I'm not clear on the difference between jQuery Core and jQueryUI. My concern is that developers using jQuery not have to worry about prefers-reduced-motion except in the rare case that an animation is absolutely needed. That said, I filed this as a webmaster, not as a developer, and developers would understand the where-it-belongs issue more than I would. I suppose, based on what you say, though, that given that Bootstrap has identified this class of issue as belonging in Bootstrap that it would belong also in jQueryUI. The problem, though, is that developers use jQuery.animation directly and we folks who are discomfited by animation need to be protected.

As for whether reduce means fewer animations or no animation, there is extensive discussion on this. macOS calls the preference Reduce Motion, which implies some animation if it is turned on. Windows calls it Show animations in Windows, which implies no animation if it is turned off.

**Comment by dmethvin** [comment]
If someone wants to disable animations completely, there is [`jQuery.fx.off`](https://api.jquery.com/jquery.fx.off/). The pages you link specifically say that some "reduced" animation is often preferable to no animation at all, which would leave the jQuery library to somehow guess how much is not enough. That's a hard question and beyond the scope of a library that just is trying to provide basic animation primitives.

**Comment by timmywil** [comment]
jQuery UI could address this in more nuanced ways, but I don't realistically see any changes being made for this on that repo given the lack of maintainers. The core team is working on addressing compatibility issues in jQuery UI with newer core releases, but that's about all we have time for. If jQuery UI gets more supporters, I think we'd all be open to addressing this issue in more thoughtful ways, but for now, I think we'll leave it to the developer to disable animations using `jQuery.fx.off` if they so prefer.
