### ISSUE TITLE
ready depcerated, but multiple events needed

### ISSUE THREAD

**Issue by TZanke** [jquery/jquery#4560]
```
$(document).on('ready otherevent', function () {
    / *something */
});
```
how to replace with $() ready logic without overloading the code like this:

```
function abcFunction() {
    /* something */
}
$(abcFunction);
$(document).on('otherevent', abcFunction);
```

**Comment by mgol** [comment]
The ready event is deprecated as we don't consider it a good way to invoke code when document is ready. First of all, they don't really look like events you'd expect on specific nodes as they apply to the whole document. Secondly, an event fires once and if you attach some handler to it too late it will never get invoked. It's much safer to wrap a handler with the jQuery function which will fire it regardless of where you put that code.

If you have logic that you need to fire both on ready and as a response to some other event then abstracting it in a way you suggested is the proper way to do it.
