### ISSUE TITLE
error setting html attribute

### ISSUE THREAD

**Issue by paolobenve** [jquery/jquery#4561]
My js code has

`$(selector).attr("title", "s'a")`

The result isn't correct, the browser only show "s" as title.

Apparently is a jquery bug, missing a slashing command on the second argument of the attr() function.

_jQuery JavaScript Library v3.3.1-dfsg ubuntu 18.04._

**Comment by gibson042** [comment]
Works for me: https://jsfiddle.net/1mspwbrL/1/
