### ISSUE TITLE
Jquery 1.4.4 vulnerabilities

### ISSUE THREAD

**Issue by shreeshagundmi** [jquery/jquery#4562]
Hi Team,

We are using Jquery 1.4.4 and Through VAPT we found 3 vulnerabilities.

1. XSS with location.hash
2. Selector interpreted as HTML
3. 3rd party CORS request may execute

please suggest Jquery version we can with to fix these vulnerabilities

**Comment by mgol** [comment]
We only support jQuery 3.x so you'll need to update to 3.4.1 if you want to receive security updates. jQuery 1.4.4 was released 9 years ago!
