### ISSUE TITLE
Event listeners disappear when reusing a fragment

### ISSUE THREAD

**Issue by dvtan** [jquery/jquery#4564]
### Description ###
I'm trying to reuse fragments, but the event listener only works once and is no longer there when the fragment gets reused. The expected behavior is that the event listeners should follow the fragment around.

```
let $home = $(`
<div>
  <h1>Home page</h1>
  <button class="btn btn-primary">Go to another page</button>
</div>`);
let $another = $(`
<div>
  <h1>Another page</h1>
  <button class="btn btn-primary">Go back</button>
</div>`);
$("body").html($home);
$home.find('.btn').on('click', () => {
  $("body").html($another);
});
$another.find('.btn').on('click', () => {
  $("body").html($home);
});
```

### Link to test case ###
https://codepen.io/dvtan/pen/dyyGVKm
And another test case by mathheadinclouds, showing that it works as expected with vanilla Javascript, plus eliminating the theory that jQuery may be cloning the node: https://stackoverflow.com/a/59293454/4698922

**Comment by mathHeadInClouds** [comment]
I hereby endorse the issue.

**Comment by dmethvin** [comment]
The `.html()` method, as its name implies, [is for putting HTML *strings* into a document](https://api.jquery.com/html/#html2) but it will take DOM elements.  The docs say:
> When .html() is used to set an element's content, any content that was in that element is completely replaced by the new content. Additionally, jQuery removes other constructs such as data and event handlers from child elements before replacing those elements with the new content.

For the sake of clarity at least, the `.html()` method should only be used to insert HTML strings.
