### ISSUE TITLE
.val() returns empty string when non numeric text pasted into input type="number"

### ISSUE THREAD

**Issue by inDeev** [jquery/jquery#4589]
.val() returns empty string when non numeric text pasted into input type="number".
E.g. When I copy number with "-" symbols inside (978-80-7473-877-7) an paste it into numeric input, it works, but jquery .val() of this input returns an empty string. I am expecting to get original value although it is not a number. Tried in Chromium, Chrome, Firefox (all latest)

**Comment by mgol** [comment]
Unfortunately, It's not possible to achieve what you want. See:
https://jsbin.com/papamox/1/edit?html,js,output
If you ender bad input, you can only detect it by checking whether `input.validity.badInput === true`. But there is no API to retrieve the input content when it contains an invalid, non-number value.

I think that's a design mistake but there's nothing that can be done here. You'll need to convince browser vendors/standards bodies to add such an API.

In cases where getting the input value is absolutely necessary, the only solution is to use `<input type="text">` and do the parsing yourself.
