### ISSUE TITLE
version checking

### ISSUE THREAD

**Issue by mutantsausagedog** [jquery/jquery#4591]
minor feature query:

Could there be a URL that when called simply gives the current version of jQuery (as in just the version number?) For instance "3.4.0". I was looking at this and bumped into the situation with https://code.jquery.com/jquery-latest.min.js. I recognise that github can email alerts, to users, of new releases of jQuery.

And more minor: could if be worthwhile to add at the top of https://code.jquery.com/jquery-latest.min.js  a commented out link to the explanation at the URL https://forum.jquery.com/topic/what-happened-to-jquery-latest-min-js-on-code-jquery-com ?

I'm not a website/jQuery developer so apologies if this has been already suggested, I did try to find similar historic reports which was how I found the related article above from 2014.

**Comment by mgol** [comment]
Thanks for submitting an issue.

Your first request was already discussed in #4437.

About the second one: we'd rather not change published versions of jQuery as it may break techniques like subresource integrity. Also, I don't think links in minified files are a good way to communicate the staleness of a resource; people wouldn't really look at it anyway.
