### ISSUE TITLE
Using index() with a jQuery collection as its argument

### ISSUE THREAD

**Issue by o-alquimista** [jquery/jquery#4597]
### Description ###
`items` is a collection of 6 elements selected with jQuery.
`item` is a child of `items`, also selected with jQuery.

I need the index of a specific `item` in the context of `items`.

### Using a string selector

```
item.index('.items .item');
```

It returns the correct index of `item`.

### Using a jQuery collection
```
var items = $('.items .item');
item.index(items);
```

It returns `-1` for all items except the first, for which it returns a `0`.

The documentation tells me `index()` should accept a jQuery object as an argument too: https://api.jquery.com/index/#index-element, so why doesn't it work?

### JSFiddle link ###
Here's a test:
https://jsfiddle.net/hs21cfgv/1/

**Comment by mgol** [comment]
Thanks for the report with a test case.

From the [docs](https://api.jquery.com/index/#entry-longdesc):
> If a selector string is passed as an argument, `.index()` returns an integer indicating the position of the first element within the jQuery object relative to the elements matched by the selector. If the element is not found, `.index()` will return -1.

It constructs a collection using the passed selector & returns the position in that collection of the first element in the jQuery object you called it on - and your collection has only one element.

However:
> If `.index()` is called on a collection of elements and a DOM element or jQuery object is passed in, `.index()` returns an integer indicating the position of the passed element relative to the original collection.

Here the position of the _passed element_ in the jQuery object you call the method on is returned; the order is different in the string case. In your case, it's trying to find the first element from the `items` collection in the one-element `item` collection and it can't find one; you need to reverse the arguments:
https://jsfiddle.net/fsL5pek6/

The ordering in this API is quite confusing!

**Comment by o-alquimista** [comment]
Yes, it is confusing. Anyway, it works.
```
items.index(item);
```

Thank you!
