### ISSUE TITLE
Cannot read property 'trigger' of null

### ISSUE THREAD

**Issue by echonox** [jquery/jquery#4609]
Environment: Browser, Cordova
Platform: Android
Error Line: 8555
jQuery Version: 3.4.1

It was reported by our users, so we couldn't find a repro.
The error happens in this part of the code:
`
trigger: function( type, data ) {
		return this.each( function() {
			jQuery.event.trigger( type, data, this );
		} );
	},
`

**Comment by timmywil** [comment]
Thanks for opening an issue. Unfortunately, without a test case, there's not much we can do. If you are able to reproduce it in https://jsfiddle.net, we can reopen.
