### ISSUE TITLE
Sorry, issue resolved. Please close

### ISSUE THREAD

**Issue by yosimba2000** [jquery/jquery#4637]
### Description ###
When passing a JSON encoded multidimensional array to Jquery, with the dataType:"JSON" tag enabled, Jquery is unable to find the array or analyze it correctly. When alerting or console.logging the data, there is no output.

However, when changing dataType to datatype (case sensititve), then the multidimensional JSON array is console.logged/alerted successfully! Seems there may be an issue with Jquery implementation of dataType?

### Link to test case ###
Sorry, none of the preferred links allow PHP, so I will post the code here. It's not very long.

// this is PHP, and it creates a multidimensional array
$i=0;
while ($row = mysqli_fetch_assoc($findservice)) {
		$resultarray[$i] = array(
			'bn' => $row['bn'],   // bn value is text
			'bd' => $row['bd'],  //bd value is text
			'i0' => $row['image0']  //image0 value is text
		);
		$i++;
	}
	$jsonarray = json_encode($resultarray);
	echo($jsonarray);
--------------------------------------------------------------------------------

//this is Jquery.

$.post({
	url:"/search.php",
	processData:false,
	contentType:false,
	data:form,
	dataType:"JSON",  //alert (and console.log) don't return anything if using dataType, but do return if //using datatype
	success:function(data){
		alert(data);
	}
});

**Comment by yosimba2000** [comment]
Sorry, please close!

I found my issue. I was echoing some text, and in the next line also echoing my JSON array. 

Jquery grabbed the first echo and was trying to search thru that!

**Comment by mgol** [comment]
@yosimba2000 you can close your own issues by yourself, no need to ask us to do it.
