### ISSUE TITLE
Inline onclick of a checkbox input is executed multiple times when called via trigger

### ISSUE THREAD

**Issue by AdamW15234** [jquery/jquery#4638]
This is an issue that seems to only be in the 3.4.X version of jQuery. When you call ".trigger("click")"  on a checkbox input the onclick event is executed 3 times. 

Here is a jsfiddle that demonstrates the issue - [jsfiddle](https://jsfiddle.net/nr9bzxc7/).

**Comment by mgol** [comment]
See https://github.com/jquery/jquery/wiki/Won't-Fix#inline-event-handlers & #4493.
