### ISSUE TITLE
HTTP quick methods for put, patch, head, delete, options for Ajax

### ISSUE THREAD

**Issue by terremoth** [jquery/jquery#4639]
# Description ###
Create quick methods for the others HTTP verbs/methods:

```
jQuery.each( [ "put", "patch", "head", "delete", "options" ], function( i, method ) {
	jQuery[ method ] = function( url, data, callback, type ) {

		if ( jQuery.isFunction( data ) ) {
			type = type || callback;
			callback = data;
			data = undefined;
		}

		return jQuery.ajax({
			url: url,
			type: method,
			dataType: type,
			data: data,
			success: callback
		});
	};
});
```

Adding something like this will help a lot of people to write a clean code when we speak about ajax methods to make _great readable ajax code_.

It will look like this:

$.get(...),
$.post(...),
**$.put(...), 
$.patch(...),
$.head(...),
$.delete(...),
$.options(...),**

Version proposal: 4.0.0

**Comment by terremoth** [comment]
Is there any kind of specific problem with this issue? 
So is there not any plans to implement quick methods to make other HTTP verbs?

**Comment by terremoth** [comment]
@mgol

**Comment by mgol** [comment]
I don't have a definite opinion here. jQuery AJAX API would be easier if we didn't have these shortcuts at all but that ship has sailed. Adding a few more shortcuts to the list would be simple & it wouldn't increase complexity in a meaningful way.

On the other hand, jQuery is not just an AJAX library and we already have many APIs on the jQuery object, I'm not sure if we want to add more.

BTW, note there would be no `jQuery.options` API as `OPTIONS` requests are automatically sent by browsers where needed, not via JS.

@dmethvin I know you had an opinion about that in the past, what do you think?

**Comment by dmethvin** [comment]
I don't think it meets the Wiki criteria: https://github.com/jquery/jquery/wiki/Adding-new-features

You can easily write plugins for your own needs without having jQuery itself add the methods and document them. I've written lots of little one-or-two-line plugins to do this in the past.

**Comment by terremoth** [comment]
Ah, ok so. I think is just because a lot of people uses. But if not, I'll close the issue, there is not why stays open.
 
Thank you guys anyway.
