### ISSUE TITLE
Delegate handlers on ancestors are not called when handler on child disables button

### ISSUE THREAD

**Issue by sdegueldre** [jquery/jquery#4640]
### Description of the issue

When delegate handlers are attached at different levels of the DOM on a button (or link), if one of the lower level handlers disables the button, the handlers registered on ancestors of the lower level delegate target are not called. This is all while handling a single click event.

#### Expected behaviour

Delegate event handlers are called when clicking an enabled button, even if that button is disabled during the handling of that event. Events that fire on already disabled buttons are ignored.

#### Actual behaviour

Delegate event handlers registered on an element that is an ancestor of the element on which a disabling handler is registered are not called.

Delegate handlers registered on the same delegate target are all called.

#### Affected browsers

All

### Link to test case ###

https://jsbin.com/tecopoduno/edit?html,css,js,output

### Additional information

The line responsible for the behaviour is here: https://github.com/jquery/jquery/blob/9d76c0b163675505d1a901e5fe5249a2c55609bc/src/event.js#L377

That, and the fact that handlers are "computed" once per dispatch, which happens at every stage of bubbling.

### Proposed fix

Only check the disabled state once per event instead of checking it at every step of bubbling.

Let me know if there's anything missing for the report or if you think this is the intended behaviour.

**Comment by dmethvin** [comment]
The line above the one you referenced mentions several tickets from the old tracker, I'll link them here. 

https://bugs.jquery.com/ticket/6911
https://bugs.jquery.com/ticket/8165
https://bugs.jquery.com/ticket/11382
https://bugs.jquery.com/ticket/11764

I agree that it seems we could check this once and it would handle this edge case better. Would you like to submit a pull request?

**Comment by sdegueldre** [comment]
I would love to! However I might need some pointers. I was initially thinking of using a jQuery-instance wide event `Map`, however it seems that we need to support ie 9+ which doesn't implement `Map`. Is there anything already in jQuery that I could use to associate data uniquely with a given native event? If not, should I roll my own partial `Map` polyfill (I would only need `get`, `has` and `set`)?

Thank you for your time :)

**Comment by dmethvin** [comment]
So sorry about taking a long time to reply! I took another quick look at this and have some other thoughts.

To answer your question, there is a `jQuery._data(domElement)` method that gets the data we use for internal flags and event tracking. 

Looking at this a little more, I am not sure whether it is correct to change this. Here is what the DOM does when you attach two handlers where the first disables the button. The second one does not run. I think this is our current behavior?

https://jsbin.com/tupideguha/edit?html,js,output

**Comment by sdegueldre** [comment]
I'm not sure what you mean, for me your jsbin appends the text "jello world" on both firefox 73 and chrome 76 when clicking the button, I unfortunately do not have the ability to test this in edge or IE at the moment but I wouldn't expect them to be any different.

And this behaviour currently works the same way when registering the same handlers with jQuery's 'on' method.

The problem I'm describing only happens when an event bubbles up. Handlers are collected into a handlerQueue before any of them is ran, so all events that are registered on the same element as the handler that disables the button will be run, which is expected.

The unexpected behaviour occurs when the event bubbles up, if a delegate handler that was registered higher in the DOM tree than the disabling handler (using delegation), the handler does not run.

Here is a more complete comparison: https://jsbin.com/casofikehi/edit?html,css,js,output

As far as `jQuery._data(domElement)`, it would work to associate data uniquely with dom elements, but not for associating data uniquely with a native event, since it attempts to define a property on the owner object for the cache, but native events are immutable.

**Comment by dmethvin** [comment]
Yep, it works that way for me too. I think I must have managed to trigger the disabling of the button and then thought the second even handler wan't running. My mistake!

You can see by the long list of bugs linked in the comment above that users expected delegated events to not occur when the button was disabled. Now we can question this particular case when the button is disabled _during_ event delivery after things have gotten started. Given how widely reported this bug was that we fixed, I wonder if trying to fix this edge case will surprise people and break code that expects the old behavior. That's true even if browsers have consistent native behavior that's not the same. 

The other problem you've mentioned is exactly how to track this situation. Given how much of an edge case it is I suspect our file-size-increase budget for fixing it would not be very big. It might be possible to stuff a flag into `handleObj` which follows the object as it climbs the DOM tree. At the moment all jQuery events of a certain type (e.g. `click`) for a node are all multiplexed off the same single native handler.

At this point I'm inclined to leave this alone, since it has been a problem in the past.

**Comment by sdegueldre** [comment]
> At this point I'm inclined to leave this alone, since it has been a problem in the past.

After reviewing the situation, I have to agree. It's still possible to bypass this problem in user code by handling the delegation logic manually. Maybe the best course of action would simply be to document this behaviour somewhere?

**Comment by dmethvin** [comment]
It's really tough to document edge cases like this in the API docs. Quite often the best documentation ends up being in closed issues like this one, because that will be how most people find solutions anyway.
