### ISSUE TITLE
Text function does not work as in browser jQuery

### ISSUE THREAD

**Issue by Sarseth** [jquery/jquery#4644]
# Description ###
I've tried to use .text function based on this https://api.jquery.com/text/ to get text from DIV element. But I got nothing.
For example:
Page: https://marvel.fandom.com/wiki/Aleksei_Sytsevich_(Earth-616)
Run from console: 
`$("*[data-source='Aliases'] > .pi-data-value").text()`
result: "Aleksei Popov, Macha-Rhino, Alex O'Hirn[1]"

But when from node js app after downloading document:
`this.#jQuery.find("*[data-source='Aliases'] > .pi-data-value").text `(or [0])
undefined

and innerHTML from first element:
`"Aleksei Popov, Macha-Rhino, Alex O'Hirn<sup id="cite_ref-Incredible_Hulk_Vol_1_435_0-0" class="reference"><a href="#cite_note-Incredible_Hulk_Vol_1_435-0">[1]</a></sup>"`
is exactly the same as from browser jQuery.

**Comment by mgol** [comment]
Node.js doesn't have DOM so you need to use one of the DOM libraries to make it work there.

How do you run the code you mentioned from Node.js? We need more details.

**Comment by Sarseth** [comment]
Sure.
I'm using jsdom (16.2.1), like in this tests: https://github.com/Sarseth/MarvelCharacterAppearanceManager/blob/master/backend/test/characterPageModel.test.js 10-12 lines.

Then I'm passing window from that and initialize by `const jQuery = new JQuery(window).`

Then I'm calling on it: `jQuery.find("*[data-source='Aliases'] > .pi-data-value").text()`.

Some other calls can be find here: https://github.com/Sarseth/MarvelCharacterAppearanceManager/blob/master/backend/src/character/characterPageModel.js

**Comment by mgol** [comment]
Can you prepare an isolated test case? Diving into a full project requires too much time.

**Comment by Sarseth** [comment]
Sure thing, ready to test thing

```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const JQuery = require('jquery');
const assert = require('chai').assert;

describe("this", function () {
  it("this", async function () {
    this.timeout(30000);
    const dom = await JSDOM.fromURL("https://marvel.fandom.com/wiki/Aleksei_Sytsevich_(Earth-616)");
    const jQuery = new JQuery(dom.window);
    const nodeJQueryResultOfText = jQuery.find("*[data-source='Aliases'] > .pi-data-value").text;
    assert.equal(nodeJQueryResultOfText, "Aleksei Popov, Macha-Rhino, Alex O'Hirn[1]",
      "This is resolution in browser for: \"$('*[data-source='Aliases'] > .pi-data-value').text()\"");
  });
});
```

**Comment by mgol** [comment]
You're using `jQuery.find` which is not a public API and which doesn't return a jQuery object. Use the same API in Node as in the browser and it will work.

**Comment by Sarseth** [comment]
Damn, thanks. For some reason I have both usages. Thanks for clarifying!
Have a nice day!
