### ISSUE TITLE
Who's running BOINC?

### ISSUE THREAD

**Issue by mcandre** [jquery/jquery#4645]
Hi,

I'd like to plug BOINC for a moment. This is a hackathon anyone can join, no programming experience necessary. If you choose to volunteer your CPU time, we can synthesize a COVID-19 vaccine much faster.

https://boinc.bakerlab.org/

BOINC supports macOS, Windows, and Linux desktops, as well as Docker and Android.

**Comment by mgol** [comment]
Thanks but this is not a proper place to advertise unrelated projects.
