### ISSUE TITLE
Error importing jquery with sortable

### ISSUE THREAD

**Issue by davidmartinezros** [jquery/jquery#4653]
### Description ###
I use jquery in one of my component and jquery is generating an error when i publish on production the use of the component.

Here is the component: https://www.npmjs.com/package/app-draggable-portlets-template

### Link to test case ###

And here the test case: https://davidmartinezros.github.io/DraggablePortletsTemplateDemo/

**Comment by timmywil** [comment]
Thanks for opening an issue. Production-only cases can be hard to diagnose, but it sounds like you need to narrow down the issue before jQuery Core can decide to make any changes on our end.

If you can provide an editable test case from https://jsfiddle.net or https://jsbin.com, that would help us to triage more easily and we can reopen. Ideally, the test case would not include other plugins or components and would reproduce any issue in jQuery Core with minimal code.

**Comment by davidmartinezros** [comment]
Here there's a plunker: https://plnkr.co/plunk/23pMyrfUl6Wz7csD

**Comment by timmywil** [comment]
I tried loading the plunker in FF and Chrome and it looks like one of the assets returns a 404. If that's the error you're seeing, that's a problem with your build system. This still looks more like a support question to me. You will probably have more success on stackoverflow.com.
