### ISSUE TITLE
$.parseHTML doesn't parse certain anchors properly

### ISSUE THREAD

**Issue by nebez** [jquery/jquery#4659]
### Description ###

Cloned #4658

When attempting to `$.parseHTML()` on an anchor that:

1. is unquoted
2. targets an `href` that has a trailing slash
3. ends with that trailing-slash `href` as the last attribute

The parsing produces wrong results.

See test case below for 4 working cases and 1 broken case. Keep in mind that all 5 cases are **valid HTML5**. See section titled **Attributes** here: https://dev.w3.org/html5/html-author/Overview.src.html

The unquoted href's are produced by many popular HTML5 minifiers.

### Link to test case ###

https://jsfiddle.net/h6uo8k10/2/

**Comment by dmethvin** [comment]
Thanks for the report! This should be fixed in jQuery 3.5.0 which is coming out within a week. You can see it in this updated fiddle. https://jsfiddle.net/2ye54fxd/1/

**Comment by mgol** [comment]
For reference, this is an up to date spec text on this:
https://html.spec.whatwg.org/multipage/syntax.html#unquoted

Closing as it's already fixed on both `master` & `3.x-stable` branches.

**Comment by mgol** [comment]
jQuery 3.5.0 released: https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/
