### ISSUE TITLE
Avoid setting jQuery.expando on window object when using module bundlers like Webpack or rollup

### ISSUE THREAD

**Issue by tonix-tuft** [jquery/jquery#4662]
### Description ###
Nowadays, module bundlers like Webpack and Rollup are used to bundle JS code and avoid polluting the global namespace by creating properties on `window`.

When using ES6 code like the following:

```js
import $ from "jquery";

$(() => {
  let expandoProp = null;
  $(window).data("something", 1);
  for (let property of Reflect.ownKeys(window)) {
    if (typeof property === "string" && property.match(/jQuery[0-9]/)) {
      expandoProp = property;
      $("#root").append(`<div>${property}</div>`);
      break;
    }
  }
  console.log(window.jQuery, window[expandoProp]);

  $("#root").append(`<div>${JSON.stringify(window.jQuery)}</div>`); // undefined, not exposed
  $("#root").append(`<div>${JSON.stringify(window[expandoProp])}</div>`); // { "something": 1 }
});

```

jQuery sets `[jQuery.expando]` on `window`, though `window.jQuery` correctly remains `undefined`, because we are bundling our JS code.

Is there a way to avoid jQuery polluting the global object with its `jQuery.expando` property? If not, perhaps may I try to make a pull request which achieves it?

Thank you for your attention.

### Link to test case ###
https://codesandbox.io/s/react-example-ms50e

**Comment by mgol** [comment]
Thanks for the report.

These lines are responsible for the property:
https://github.com/jquery/jquery/blob/3.4.1/src/data/Data.js#L41-L44
In essence, we simulate a WeakMap here by setting a non-enumerable key on the data owner. For regular nodes it doesn't matter that much but for `window` it means it creates a global variable.

We could avoid this if we were using a true WeakMap. In fact, the jQuery >2.0.0 design by @rwaldron was meant to make it easier to migrate to a WeakMap in the future.

Unfortunately, jQuery 3.x (code on the [`3.x-stable` branch](https://github.com/jquery/jquery/tree/3.x-stable)) supports IE 9+ so we can't rely purely on WeakMaps. jQuery 4.0 (code on `master`) will only support IE 11 which supports that API but there might be bugs there that make it impossible to use it. This needs to be researched. Looking at what `core-js` does with the IE 11 WeakMap implementation might help us see if it's feasible to leverage WeakMaps. If it is, switching `Data.js` to use WeakMaps would be the solution to your issue.

If IE implementation of WeakMaps turns out to be too broken, we could optionally use WeakMaps in modern browsers & the existing implementation in IE. That would still create a global variable in IE, though, so I'm not sure if it would satisfy you here. Also, we care about jQuery size so it'd need to be done without increasing the gzipped size of jQuery too much.

For now, if you want to avoid global variables, avoid calling `.data()` on the global object.

**Comment by tonix-tuft** [comment]
Why not just add a special handling for `owner` when `owner === window` or `owner === document`, i.e. `owner` is an object reachable from the global `window` object (like `window.window` or `window.document`, `window.document.body`)?

```
define( [
	"../core",
	"../core/camelCase",
	"../var/rnothtmlwhite",
	"./var/acceptData",
        "./core/localGlobalOwner" // <--- E.g.: The local owner object would be defined here, essentially `localGlobalOwner = {}`, only jQuery can access it...
], function( jQuery, camelCase, rnothtmlwhite, acceptData, localGlobalOwner ) {

"use strict";

var refToLocalGlobalOwner = localGlobalOwner; // Local variable which only jQuery can access and modify.

...
				// Otherwise secure it in a non-enumerable property
				// configurable must be true to allow the property to be
				// deleted when data is removed
				} else {
                                        // Use a factory to determine which effective `owner` to use.
                                        // Just using a simple if for simplicity.
                                        var finalOwner = owner;
                                        if (owner === window || owner === document || owner === window.document.body) {
                                              finalOwner = refToLocalGlobalOwner; // = localGlobalOwner
                                        }
                                        // Use the finalOwner without polluting the global object.
					Object.defineProperty( finalOwner, this.expando, {
						value: value,
						configurable: true
					} );
				}
...
```

This is simplified, but you get the idea.

What do you think?

Thank you!

**Comment by mgol** [comment]
There may be more than one global object to deal with on pages with same-origin iframes. Keeping one object local to jQuery storing data for `window` is not enough.

**Comment by tonix-tuft** [comment]
You are right, but what about using a custom data structure to achieve the wanted behaviour? e.g.:

```html
<iframe id="first" width="100%" height="95%" src="//fiddle.jshell.net/Z5Lmn/"></iframe>
```

```js
function ReferenceArray() {
  this.refs = [];
}
ReferenceArray.prototype.get = function(ref, key) {
  for (var i = 0; i < this.refs.length; i++) {
    var elem = this.refs[i];
    if (elem.ref === ref) {
        return typeof key !== "undefined" ? elem.obj[key] : elem.obj;
    }
  }
  return void 0;
};
ReferenceArray.prototype.set = function(ref, key, value) {
  var obj = this.get(ref);
  if (typeof obj !== "undefined") {
      obj[key] = value;
  }
  else {
    var elem = {
      ref: ref,
      obj: {}
    };
    elem.obj[key] = value;
    this.refs.push(elem);
  }
  return this;
};

function iframeRef(frameRef) {
    return frameRef.contentWindow
        ? frameRef.contentWindow.document
        : frameRef.contentDocument
}

var sharedRefArray = new ReferenceArray(); // This would be shared across all jQuery modules, but local to jQuery in order to not pollute the global namespace.

$(document).ready(function() {
  var firstIframe = document.getElementById("first");
  firstIframe.onload = function() {
    var iframeDocument = iframeRef(firstIframe);
    iframeDocument.body.innerHTML = 'First iframe';
    iframeDocument.body.style.background = "red";
    var firstIframeWindow = firstIframe.contentWindow; 
		console.log(window === firstIframeWindow); // false
    sharedRefArray.set(window, 'abc', 123);
    sharedRefArray.set(firstIframeWindow, 'abc', 456);
    console.log(sharedRefArray.get(window, 'abc')); // 123
    console.log(sharedRefArray.get(firstIframeWindow, 'abc')); // 456
  }
});

```

You can check out this JSFiddle -> http://jsfiddle.net/Lgar8mjp/ and open your browser's console, you will see how for different window refs you lookup different values for the same key pretty easily. This example is very simple, but it could be a start.

The same would work for the `jQuery341...` expando key.

What do you think?

**Comment by dmethvin** [comment]
The problem we have generally faced with changing jQuery is that it *always* breaks something. So the question is whether this is really a problem in the first place and warrants breaking someone's code. Is it a problem to create this one item in the global namespace? If so, what issues does it cause?

**Comment by tonix-tuft** [comment]
@dmethvin No no, it's not a problem, I was just for not polluting the global object and exposing the property on `window`. What do you think of my proposed method? Could it work across the jQuery codebase? What if I try to submit a pull request for this? Will you review it so that I know that it is worth to spend time for this too? Thank you very much for your reply.

**Comment by dmethvin** [comment]
I'm not sure whether it will cause a problem or not. Quite often, even the core team is surprised when something breaks that we thought would be okay. People use jQuery in so many different ways and different environments. We have a pretty good understanding of the browser difference issue after 10 years, but much less about the way people use obscure features.

The other question is cost versus benefit. If it makes jQuery 200 bytes bigger to fix this, times the millions of downloads per day of jQuery, is it worth fixing something that nobody has reported as a true problem?

**Comment by tonix-tuft** [comment]
You're right, and I agree with you, closing this! Really, it's not an issue causing problems with the current implementation. Thank you for your reply!
