### ISSUE TITLE
Delegated event handlers with selector on window object do not trigger

### ISSUE THREAD

**Issue by smares** [jquery/jquery#4663]
### Description ###
I recently encountered a problem using delegated event handlers with a selector on the `window` object. It was my understanding that the selector passed to `.on()` works the same as if it was omitted and instead, `if ($(event.target).is(...)) { ... }` was being used in the event handler method body.

So basically, I thought these two were identical:

    $(window).on('click', '.my-class', event => {
      ...
    }

and

    $(window).on('click', event => {
      if ($(event.target).is('.my-class')) {
        ...
      }
    }

However, the first will never execute while the second does. I had people on IRC and Stackoverflow tell me that events don't bubble up to `window`, but then how come the second example above with an event handler for the `window` object without a selector is catches the click event and `event.target` has the correct reference to the element clicked?

What I do find strange, though, is that attaching the handler to `document` instead of `window` works. So this does not work:

    $(window).on('click', '.my-class', event => {
      ...
    }

But this does:

    $(document).on('click', '.my-class', event => {
      ...
    }

Is this a bug or am I missing something?

### Link to test case ###
https://codepen.io/smares/pen/rNOBZRK?editors=1111,

**Comment by dmethvin** [comment]
The [documentation](https://api.jquery.com/on/#on-events-selector-data-handler) seems pretty clear to me:

> The majority of browser events bubble, or propagate, from the deepest, innermost element (the event target) in the document where they occur all the way up to the body and the document element. ...(more detail)...

Many events do bubble to `window` but to achieve delegation you should attach to `document` and the documentation never says that `window` is an option.

**Comment by mgol** [comment]
From the implementation point of view, matching selectors is done in these lines:
https://github.com/jquery/jquery/blob/master/src/event.js#L388-L389
and the following:
```js
jQuery( window ).find( selector );
```
will return an empty collection for any possible selector. If you use selectors, don't go further up than `window`.

**Comment by smares** [comment]
So this has less something to do with events not bubbling up to `window`, because they do, but jQuery's inability to select any element when the root is `window`.

**Comment by dmethvin** [comment]
It's not a question of ability as much as validity;  `document` is the root of the document tree but `window` is not part of the document.
