### ISSUE TITLE
3.5 incompatible with FullCalendar 3

### ISSUE THREAD

**Issue by neroux** [jquery/jquery#4664]
I was just trying to upgrade from 3.4.1 to 3.5 when I noticed 3.5 breaks [FullCalendar](https://github.com/fullcalendar/fullcalendar) 3. Events are not properly displayed any longer.

I couldn't immediately spot a potential reason at https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/ and the browser console is not very chatty either I am afraid.

**The issue can be observed at https://jsfiddle.net/40a3hLcu/.** On the left side under "Resources" it currently includes both jQuery versions. **To test it, simply click the "Remove" link to remove a version and then click "Run". With 3.4.1 included, it will work. With 3.5, it will not.**

As far as I understand FullCalendar 3 is not supported any more, but I am still tagging the author of FullCalendar as well, @arshaw

**Comment by mgol** [comment]
Restoring `jQuery.htmlPrefilter` to the potentially insecure value from jQuery 3.4.1 solves the issue:
https://jsfiddle.net/m_gol/wof7p5m1/3/
so it must be using XHTML-style tags that are no longer supported.

See the blog post:
https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/
and the upgrade guide for more details:
https://jquery.com/upgrade-guide/3.5/

**Comment by mgol** [comment]
Closing as the change is intended and it needs to be fixed by FullCalendar or worked around via steps outlined in the upgrade guide.

**Comment by dmethvin** [comment]
Agreed, I'm pretty sure this is related to our security fix. Here are some cases in the plugin, I used the unminifed source and copied in lines:

```
 var el = $('<div><div/></div>')
 moreTd = $('<td class="fc-more-cell"/>').attr('rowspan', rowspan);
 return $('<a class="fc-more"/>')
 dayGridEl = $('<div class="fc-day-grid" />').appendTo(dayGridContainerEl);
 this.el = $('<div class="fc-popover"/>')
 this.contentEl = $("<div class='fc-view-container'/>").prependTo(el);
 newView.setElement($("<div class='fc-view fc-" + viewType + "-view' >").appendTo(this.contentEl));
 timeGridEl = $('<div class="fc-time-grid" />').appendTo(timeGridWrapEl);
```

You'd need to change `<div/>` to `<div></div>` and `<td />` to `<td></td>` etc. The general rule is, if the element *can* have content you cannot self-close it like that.

This usage of a single tag with no properties is okay because we special-case a single div:

>  moreWrap = $('<div/>').append(moreLink);

Sorry that we can't fix this without security issues, but the solution is relatively simple. I don't recommend

**Comment by neroux** [comment]
@dmethvin, thanks for digging out the lines in question, as evident from the link above I just created an issue at FullCalendar about this issue.

I have never been too familiar with self-closing tags (respectively "void tags" as their [official name](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) is) but just went through that specification and realised that only 14 tags actually allow for that.

With that background (and the mentioned "edge cases" in the version notes) I'd most likely also argue the change in 3.5 should be welcomed (I'd go further and say `<div/>` should never be accepted then), however there should be a **warning message issued in the browser console**, otherwise this is difficult to debug.

**Comment by mgol** [comment]
jQuery itself doesn’t print warnings but we’ll add a warning to jQuery
Migrate. Work in progress at
https://github.com/jquery/jquery-migrate/pull/338.
-- 
Michał Gołębiowski-Owczarek

**Comment by neroux** [comment]
@mgol, the issue here would be if one doesnt have jQuery Migrate but only the plain library and upgrades it, it will fail without any further information.

Now, if one isn't the author of any of the involved code (neither jQuery nor the third party library) it will be tricky to track down the reason, as in the case here.

**Comment by mgol** [comment]
We recommend using jQuery Migrate for jQuery upgrades as it will warn against bugs like this one. Once all warnings are fixed, Migrate can be removed.

We don’t add stuff like that to jQuery to save size. It’s only needed during upgrades & not in regular usage so it’d be wasteful to include it for everyone.

**Comment by neroux** [comment]
Alright, fair enough. Thanks.

**Comment by dmethvin** [comment]
The cases I mentioned above are not valid HTML, but in most cases the HTML5 parser in modern browsers will fix them up. For some of the more complex cases the browser's parser uses a different interpretation than previous versions of jQuery. We expect to release a new jQuery Migrate plugin soon that will help identify the specific uses that are causing the problem so that folks can fix their plugins.

**Comment by Sublime1** [comment]
If I understand this correctly, this would still be an issue in latest jQuery versions, is that right?

**Comment by mgol** [comment]
The fixes need to go into FullCalendar; behavior of jQuery 3.5 & later versions will be the same here.

**Comment by Sublime1** [comment]
@mgol Thank you!
