### ISSUE TITLE
Cannot use .on to bind `load`

### ISSUE THREAD

**Issue by DongyunLee** [jquery/jquery#4667]
### Description ###

JQuery version: 3.5.0 - compressed

Now I need to listen a event that if a <img> tag has loaded complete ,
but when I use `$("img").on("load",function(){ console.log(123) })`,
the callback handler was not run.

In the document, I found the `.load(handler)` has been deprecated from v1.8, 
and need to **`use .on( "load", handler )` instead of `.load( handler )`**

I test this case from v1.7.2 to v3.5.0, it works before v3.5.
I don't know what happened ,if something have been removed? Or maybe I missed something?

### Link to test case ###
HTML
```html
<img  src="http://ch4o5-assets.oss-cn-beijing.aliyuncs.com/images/blood-moon.jpg">

<script src="http://cdn.doylee.cn/js/jquery-3.5.min.js"></script>
```

JS
```javascript
$(function () {
    $("img").on("load",function (e) {
      console.log(e)
      // alert(123)
      console.log(123)
      addDom()
    })
  });
```

Thanks for any attentions!

---
### PS
What's the recommand way using JQuery to listen the state of background-image in css ?
Is to create a `img` tag with the url of background image, then listen the load state of `img` tag?
Thanks again !

**Comment by mgol** [comment]
Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by DongyunLee** [comment]
> Can you provide a test case on JS Bin as the issue template requested? Thanks!

Sorry, I found the reason, the cdn what I used is broken.
I download the file from [](jquery.com) and retry it , it works.
Thanks!

And another problem, why the version with [](code.jquery.com) 's git-build is v4.0.0-pre and the latest v3.x is v3.4, I cannot find v3.5.0 from there?
Is there any rules I don't know in [](code.jquery.com) ?

**Comment by mgol** [comment]
There are many ways to download jQuery 3.5.0, the ones we control are documented at https://jquery.com/download/.
