### ISSUE TITLE
Synchronous load re-executes document.ready handlers?

### ISSUE THREAD

**Issue by drauch** [jquery/jquery#4669]
I've run into https://github.com/jquery/jquery/issues/3975 by unintentionally returning the whole page to a `$(elem).load` call instead of only returning the HTML fragment. To my surprise this has not only loaded some stuff synchronously (hence the warning described in #3975) but also re-executed all my document.ready handlers - is this a bug or a documented behavior? I was puzzled why after a load() call all my handlers were registered twice. This is at least very surprising. Couldn't find anything in the docs, which is why I'm asking here.

Best regards,
D.R.

**Comment by mgol** [comment]
Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by drauch** [comment]
Due to CORS not really. Or is there a way to execute `load` with an URL of a different host?

**Comment by mgol** [comment]
Maybe try http://plnkr.co/ then? It allows to attach multiple scripts.

**Comment by drauch** [comment]
http://plnkr.co/edit/HReHGFyKShw8XlIT

Always click the top button and watch the console window. document.ready is called more than once.

**Comment by mgol** [comment]
You're loading the full page from that same page. That means on each load you're adding a copy of all the scripts on the webpage to your main page so on each `load` call all of them will be executed.

This is not the same script executing multiple times. These are _copies_ of the same script being inserted into the webpage. It doesn't matter they have the same contents.

**Comment by drauch** [comment]
I know, but why is a document ready handler of a loaded script called long after the ready event has fired?

**Comment by mgol** [comment]
The callback passed to `jQuery` will be invoked once when the document is ready. If it's already ready at the moment it's called, it will be invoked almost immediately. Please read https://api.jquery.com/ready/ for more details.

**Comment by drauch** [comment]
OK, thank you!
