### ISSUE TITLE
jQuery needs a .log() method.

### ISSUE THREAD

**Issue by Daemach** [jquery/jquery#4675]
It should be trivial to insert .log() at any point in a jquery chain to dump the current elements to the console.  Much easier than trying to wrap everything in console.log especially when working with a long chain, which requires setting intermediate variables and dumping them individually.

**Comment by timmywil** [comment]
Thanks for opening an issue. Something like this is out of scope for jQuery core, but would work very well as a plugin.

**Comment by dmethvin** [comment]
Definitely not a core thing. Some people may want something as simple as `jQuery.fn.log = function(){ console.log(this) }` but I can bet you that if we put it into core we would get weekly requests for enhancement.

**Comment by Daemach** [comment]
That is a bad excuse.  It's this simple, even as a plugin, and makes
troubleshooting jquery 1000 times simpler.  Why should I have to install or
maintain yet another plugin for what you could add in, what, 40 bytes?  And
how could you possibly enhance this?

You will get kudos for adding this functionality.  It's hard to believe
that it's not already there...

(function ( $ ) {
    $.fn.log = function() {
        console.log(this);
        return this;
    };
}( jQuery ));

**Comment by mgol** [comment]
If we kept adding “obvious” features people ask for, jQuery could quickly get unacceptably large. We have a checklist for accepting new features, this one doesn’t cut it:
https://github.com/jquery/jquery/wiki/Adding-new-features
