### ISSUE TITLE
change #3256 should be listed as breaking change in change log 

### ISSUE THREAD

**Issue by k2s** [jquery/jquery#4677]
In my opinion fix for #3256 should be listed as breaking change in change log.

Any code that is using `obj.hasOwnProperty(key)` instead of `Object.prototype.hasOwnProperty.call(obj, key)` will stop working with message `TypeError: obj.hasOwnProperty is not a function`.

**Comment by timmywil** [comment]
Thanks for opening an issue. We'll make this clear in the 3.5.1 blog post, which is where the changelog will go as well.

**Comment by mgol** [comment]
This is a duplicate of #4665 which was fixed in #4666.
