### ISSUE TITLE
jQuery et prototype

### ISSUE THREAD

**Issue by claudecnx** [jquery/jquery#4688]
when i use jQuery in prototype like this:
Object.prototype.doit = function(){
	$("p").css({
				marginTop : "1pt",
				font : "7pt arial, helvetica, sans-serif"
		});
	return false;
};
var i = {}.doit();
this generates error: too much recursion 
i use the last version at date jquery-3.5.0.js
and try this on chrome or firefox
why?

**Comment by dmethvin** [comment]
https://github.com/jquery/jquery/wiki/Won't-Fix#modifying-objectprototype
