### ISSUE TITLE
upgrade from 3.4.1 to 3.5.0.1 - Cannot find closing comment tag to match

### ISSUE THREAD

**Issue by tanasiciuc** [jquery/jquery#4693]
Hello,
I upgrade jquery nuget from 3.4.1 to 3.5.01 and our application doesn't work.
We use Durandal and knockout.js, and after upgrade most of binding doesn't work because of the error ex: "Cannot find closing comment tag to match: ko if:"
The problem is for html elements that doesn't have explicit close. Ex: if <div attr=""/> is used inside of knockout binding will failed. On previous version 3.4.1 and others, it's works.
If we update code to <div attr=""></div> it's works but it is very hard for us to change all the code, because button,select...all the code is impacted.
**Full example:**

    <div class="col-xs-3 " data-bind="text: Currency" />
     
that works util now, after upgrade must to be changed to:

    <div class="col-xs-3 " data-bind="text: Currency" ></div>

**Comment by mgol** [comment]
Thanks for the report. However, this change is intentional. See my replies in #4681 for more details.
