### ISSUE TITLE
$.param - cannot unambiguously serialize null relative to empty string

### ISSUE THREAD

**Issue by jayaddison** [jquery/jquery#4707]
### Description ###
In many application environments there is a distinction between the `null` value and the empty string value; it could be useful to provide an option to allow developers to serialize data via jQuery.param in a way that disambiguates between those two conditions.

No application-specific approach is suggested here, but as an example, an environment might wish to choose that `?x=1&y=&z` infers `x=1, y='', z=null`

Allowing serialization with abbreviated keys (i.e. `$.param({'x': null, 'y': 0}, ...) === '?x&y=0'`) would also allow some clients to save a marginal character in application environments where the server identifies query-string keys by splitting on ampersand (`&`) characters and already provides a default null/empty value.

### Link to test case ###
An illustrative test case is provided here:

https://github.com/jayaddison/jquery/blob/79825abf26c5430dbe27003dbc9bdc59be8dc78b/test/unit/serialize.js#L79-L80

### References ###
- https://bugs.jquery.com/ticket/8653#comment:3
- https://tools.ietf.org/html/rfc3986#section-3.4
- https://github.com/psf/requests/issues/2651
- https://bugs.python.org/issue18857
- https://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value
- https://github.com/sindresorhus/query-string#falsy-values

Edit: add reference to `sindresorhus/query-string`

**Comment by timmywil** [comment]
Thanks for opening an issue. The team decided not to do this at this time. We will reconsider if it makes it into a spec.
