### ISSUE TITLE
Problem of duplication element on self-closing <i> on jQuery 3.5.1 

### ISSUE THREAD

**Issue by Ppito** [jquery/jquery#4709]
Hello, 

I run into a bug while using the latest jQuery version: when creating a jQuery element from a html string and trying to use it within my code all self-closing <i> tags are duplicated inside all the present elements - which did not happen with the previous version. 
I am aware that using self-closing <i> tags is not recommended, and I did change my code accordingly but I still find this behaviour to be unexpected. 

Here is an example showcasing the two different jQuery versions as run on Chrome 81.0.4044.129.

3.5.1 : https://jsfiddle.net/wbmu4gad/
3.4.1 : https://jsfiddle.net/5zayfu0w/

Thanks,

**Comment by mgol** [comment]
Thanks for the report.

This is the same issue as #4681 and follows the native behavior, see that issue for more details.

Using formatting tags like `<i>` for non-formatting use cases like icons is not recommended.
