### ISSUE TITLE
If I use the "append" function my browser return warning 

### ISSUE THREAD

**Issue by xXConcasXx** [jquery/jquery#4713]
### Description ###

if I use the "append" function my browser return this: 

> jquery.min.js:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

### Link to test case ###

No link for test case, JQuery version is: 3.5.1

**Comment by dmethvin** [comment]
There is no test case, which was asked for in the report template. Based on the message I would say you are appending a script, which is synchronous. It's best to ask for help on StackOverflow since this isn't a bug.

**Comment by mgol** [comment]
See https://github.com/jquery/jquery/issues/1895 & https://github.com/jquery/jquery/issues/3969 for more details. This is currently planned for `4.0.0` but it requires some non-trivial work.
