### ISSUE TITLE
$().text() method has a bug

### ISSUE THREAD

**Issue by shijunsong** [jquery/jquery#4714]
when i used the $().text() method set a value, 
then after change the value and repeat set other value， 
the textarea value is not change, 
always is the value of after change value,  this is a bug?

**Comment by shijunsong** [comment]
$('#txtArea').text('value1');
do change after :  value11;
$('#txtArea').text('value2');

the textarea value is still 'value11'

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by dmethvin** [comment]
> The .text() method cannot be used on form inputs or scripts. To set or get the text value of input or textarea elements, use the .val() method.  -- https://api.jquery.com/text/
