### ISSUE TITLE
jQuery.extend: null is not always ignored

### ISSUE THREAD

**Issue by bean5** [jquery/jquery#4716]
At https://api.jquery.com/jQuery.extend/, documentation indicates that:
> Arguments that are null or undefined are ignored.

Later it clarifies:
> Undefined properties are not copied. However, properties inherited from the object's prototype will be copied over.

However, I think I found an unexpected edge case where null is not ignored.

|Code|Expected|Actual|Result|
|-------|-------------|--------|--------|
|$.extend({test: undefined}, {test: null});|{test: undefined}|{test: null}|Fail|
|$.extend({test: null}, {test: undefined});|{test: null}|{test: null}|Pass|
|$.extend({test: undefined}, {});|{test: undefined}|{test: undefined}|Pass|
|$.extend({}, {test: null});|{}|{test: null}|Fail|
|$.extend({}, {test: undefined});|{}|{}|Pass|

Since I do not know what the intended functionality would be, I cannot submit a change. But if you let me know, I would love to contribute, even in this small instance.

**Comment by bean5** [comment]
If this is intended functionality, we could probably clarify the documentation to indicate that `null` is not ignored if it can override `undefined`.

**Comment by dmethvin** [comment]
Those sentences are talking about two different things. In a call like `jQuery.extend({}, a, b, c)` the _arguments_ `a`, `b`, or `c` are ignored if they are `null` or `undefined`. However, the values of the _properties_ of the objects  `a`, `b`, or `c` are only copied over if they are not `undefined`.

There's nothing useful to be done with `null` as an argument so it makes sense to ignore it. In other places like JavaScript's `JSON.stringify()`, properties the values of `null` and `undefined` are treated differently so it's also consistent with that sort of usage as well.

I don't think there's anything to be done here. The docs do say what they intend and they match the behavior of the code.

**Comment by bean5** [comment]
@dmethvin Ah, arguments--not keys within arguments. Hmm. Interesting that I as I was learning about how it works I discovered that keys with undefined value are treated differently than keys will a null value assigned.

Any chance that could be documented (assuming it is intentional)?

**Comment by dmethvin** [comment]
It is documented. First sentence in the docs:

> When two or more object arguments are supplied to $.extend(), properties from all of the objects are added to the target object. Arguments that are null or undefined are ignored.

About four paragraphs down:

> Undefined properties are not copied. However, properties inherited from the object's prototype will be copied over. Properties that are an object constructed via new MyCustomObject(args), or built-in JavaScript types such as Date or RegExp, are not re-constructed and will appear as plain Objects in the resulting object or array.

What would you want to add, and where?
