### ISSUE TITLE
jQuery UI

### ISSUE THREAD

**Issue by rgrasby** [jquery/jquery#4717]
Now, this is not officially a jQuery issue, but there is no issue tracker on jQuery UI so I'm posting it here. I am unable to download a custom build for use in my project. I get an Error 502 from CloudFlare. This has been like this for the last two days.

**Comment by mgol** [comment]
Thanks for the report.

jQuery UI bugtracker is located at https://bugs.jqueryui.com/. The download site has a separate repo at https://github.com/jquery/download.jqueryui.com and this issue is already tracked there: https://github.com/jquery/download.jqueryui.com/issues/390.
