### ISSUE TITLE
Append: throw error on invalid HTML

### ISSUE THREAD

**Issue by applemonkey496** [jquery/jquery#4719]
## Feature Request

When I call JQuery's `append()` function, but the HTML is invalid, it doesn't append the content and what's more, it silently fails. My proposed solution is to simply throw an error instead of silently failing.

## Example

You can see it [here](https://codepen.io/applemonkey496/pen/bGVOEdw?editors=1011) on codepen.

**Comment by dmethvin** [comment]
We use the browser to parse these strings. The browser doesn't throw an error. The only way we would know any particular HTML string is well formed is to parse it ourselves in JavaScript. To complicate things further, there are many strings that people use daily that are not well formed yet still do what people expect, and it would be difficult to distinguish the harmlessly invalid from the frighteningly invalid or unexpectedly invalid.
