### ISSUE TITLE
Handle CSS Logical Properties

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#4722]
The regexp for `isAutoPx` doesn't take the new [CSS Logical Properties](https://www.w3.org/TR/css-logical-1/) into account. They already have [decent browser support](https://caniuse.com/#feat=css-logical-props) already.

**Comment by mgol** [comment]
Do we want to include them? To me the idea was catching properties where the current behavior is the most frequently used; ideally we’d get rid of it all but it might be too big a compatibility break.

**Comment by dmethvin** [comment]
Yeah, I suppose the real reason we had that at all was to prevent too much old code from breaking. With new properties they should follow the rules and it wouldn't break. With that in mind I'd be inclined to close it, but I'll wait for the meeting.

**Comment by timmywil** [comment]
Would like to discuss this more with @dmethvin. We're leaning towards not adding, but there's still the question of whether to document something that is not in recommendation status.

**Comment by dmethvin** [comment]
Sorry I missed the meeting today! I do agree that this is more of a compat thing, and since the logical properties are brand new we should encourage everyone to specify the units properly rather than letting a regex figure it out.

**Comment by timmywil** [comment]
Closing. We recommend specifying units in your strings, and then there won't be a problem.
