### ISSUE TITLE
code.jquery.com provides an expired cert (COMODO RSA Certification Authority)

### ISSUE THREAD

**Issue by gemal** [jquery/jquery#4726]
https://code.jquery.com/jquery-3.3.1.min.js signed with a expired cert

https://www.ssllabs.com/ssltest/analyze.html?d=code.jquery.com&s=2001%3a4de0%3aac19%3a0%3a0%3a1%3ab%3a1b&latest

![image](https://user-images.githubusercontent.com/69105/83384099-d20b8f80-a3e6-11ea-9109-9dc73b4437ca.png)

![image](https://user-images.githubusercontent.com/69105/83384079-c6b86400-a3e6-11ea-947d-b5f1288113e8.png)

**Comment by mgol** [comment]
See https://github.com/jquery/codeorigin.jquery.com/issues/59.
