### ISSUE TITLE
DOMEval creating a CSP violation

### ISSUE THREAD

**Issue by sagupta1001** [jquery/jquery#4727]
### Description ###

Seeing the following CSP violation when using a nonce based approach for script-src.
```
query3.source.js:124 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 
'nonce-3P91GM9LeLdZK2qOn+Sf3w=='". 
Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

DOMEval @ jquery3.source.js:124
globalEval @ jquery3.source.js:358
text script @ jquery3.source.js:9877
ajaxConvert @ jquery3.source.js:9013
done @ jquery3.source.js:9483
```

I would think that #4278 would have resolved the issue, but I am on Jquery version 3.4.1 and able to reproduce this issue.

Please advise.

**Comment by dmethvin** [comment]
There's no test case here.

**Comment by sagupta1001** [comment]
> There's no test case here.

I'm not sure how to provide a test case here. I can provide more context around the Web application setup, how the CSP is setup etc if that would help.

**Comment by mgol** [comment]
The most important point is what jQuery API you call & with what parameters; we can't guess that from the stack trace. That can be used to construct a test case, although I understand preparing a test case requiring a specific CSP setup might be tricky. But it should be possible to create a JS Bin with example code that triggers the CSP error & then separately describe the CSP setup.

**Comment by dmethvin** [comment]
I always hesitate to get into a guessing game with reports like this. For example, it seems like the most likely thing is that the code is injecting HTML that includes scripts, and we're executing those scripts.

**Comment by mgol** [comment]
Closing due to lack of information. If more details are provided, we can reopen.
