### ISSUE TITLE
fadeTo causes JQMIGRATE warning

### ISSUE THREAD

**Issue by goozak** [jquery/jquery#4736]
This line:
https://github.com/jquery/jquery/blob/3d62d5704989f17d3a20ae7521d52e9c8c60b4ee/src/effects.js#L496

causes jQuery Migrate to show this warning:
> JQMIGRATE: Use of number-typed values is deprecated in jQuery.fn.css

I'm using jQuery 3.5.1 with jQuery Migrate 3.3.0

**Comment by mgol** [comment]
Thanks for the report. This should already be fixed in https://github.com/jquery/jquery-migrate/pull/348, we just need a new Migrate release.
