### ISSUE TITLE
svg viewBox attribute and using arrow functions

### ISSUE THREAD

**Issue by khansikki** [jquery/jquery#4738]
i faced two issues with the new **3.5.1** please check them

1.  while adding viewBox attribute to svg element, jQuery is adding attribute as viewbox which is failing the svg from visible

2. while using the arrow function in jQuery unable to retrieve the value of button newly created 
eg: `
$(document).on('click','#btnValue',()=>{
      let value = $(this).val()
      console.log(value)
})
`

### Link to test case ###
[codepen link](https://codepen.io/khan_sikki/pen/vYLJaaW)

**Comment by dmethvin** [comment]
You're missing a test case. Can you provide one?

**Comment by khansikki** [comment]
> You're missing a test case. Can you provide one?
[codepen](https://codepen.io/khan_sikki/pen/vYLJaaW)

**Comment by dmethvin** [comment]
For 1, search "append svg jquery" which leads to https://stackoverflow.com/questions/3642035/jquerys-append-not-working-with-svg-element

For 2, search "arrow function jquery event" which leads to https://stackoverflow.com/questions/27670401/using-jquery-this-with-es6-arrow-functions-lexical-this-binding

**Comment by khansikki** [comment]
why the attribute is completely going to lowercase instead of viewBox in first case

**Comment by dmethvin** [comment]
The short answer is that HTML attributes are case insensitive. HTML DOM is not SVG DOM. The longer answer is not really appropriate for this bug tracker. jQuery didn't make the rules here, although I certainly agree they're confusing.
