### ISSUE TITLE
[New feature] Calling the method in a new way jQuery('.button2').click.call(jQuery('.button1'));

### ISSUE THREAD

**Issue by korenevskiy** [jquery/jquery#4743]
Please add the ability to run with new properties.
`jQuery('.button2').click.call(jQuery('.button1'));`
This opportunity to preserve the readability of the code, reduce duplicate code.

**Comment by mgol** [comment]
Thanks for submitting an issue. I don’t understand your example, though, could you elaborate more on what that code would do?

**Comment by korenevskiy** [comment]
> Thanks for submitting an issue. I don’t understand your example, though, could you elaborate more on what that code would do?

@mgol 
Call the function subscribed to button 2, passing the environment of button 1

**Comment by korenevskiy** [comment]
It is surprising that this was not previously possible.

**Comment by timmywil** [comment]
I'm also confused. Why not just bind the same click handler to button 1?

**Comment by timmywil** [comment]
Regardless, this looks more like something that should start out as a plugin. Thank you.
