### ISSUE TITLE
Add the Ajax function for selector.

### ISSUE THREAD

**Issue by korenevskiy** [jquery/jquery#4744]
Please add the Ajax function for selector.
```
jQuery('li').ajax(url,{.... settings})
.when((li)=>{...settings}) // handler for create settings ajax request
.done((data)=>jQuery(this).append(data)) //handler for every
.any(handler for first done)
.all(handler for all);
```
Where settings in `ajax` and in `when` values for ajax request.

An excellent idea was put into jQuery when the first versions appeared, the idea was taken from Linq C#.
Thanks to jQuery().ajax() will pursue his idea in format AJAX.
jQuery lost popularity due to weak AJAX support. AJAX is the default requirement of modern websites out of the box.
A small digression.
This functionality will solve the following problems:
- re-executing the code after loading.
-allows you to save the order of execution of multiple queries sequentially.
-slow loading of sites.
-allows you to control multiple queries of the same type.
-support for lazy loading.

**Comment by timmywil** [comment]
Thanks for opening an issue. I don't quite understand the request here, but `$.ajax` is already a behemoth that is unlikely to receive any more features. If you flesh this out as a plugin first and it gets traction, we can take a look.
