### ISSUE TITLE
Add a value binding variable

### ISSUE THREAD

**Issue by korenevskiy** [jquery/jquery#4745]
Add a value binding.
```
jQuery.event('title',function(e){ jQuery('#title').html('Title page: '+this)});
jQuery.event('title',function(e){ jQuery('#footer').html('Title page: '+this)});
jQuery.var('title','New Name Page');

jQuery.event('cost',function(e){ jQuery('#cost').html('Cost: '+this + ' $')});
jQuery.event('cost',function(e){ jQuery('#allcost').html('All cost for all products: '+this + ' $')});
jQuery.var('cost',500);

var cost = jQuery.var('cost');
var tax = 1.3;
jQuery.var('cost', cost * tax);
//After that, all price bindings will be updated automatically. 
//And all functions binded to this price value will be performed again.
```
This functionality will allow you to compete with React.
This functionality will allow you to take 30% of React users.
All programmers who need to solve a problem with 10 bindings will need only one jQuery library.
Those who already use jQuery will not need to add a new React library, since jQuery will support binding from the box.
**This will separate the business logic from the site layout.**

**Comment by korenevskiy** [comment]
Possible additional options.
`jQuery.event('cost', '#cost');` 
`jQuery.event('cost', '#allcost');`  - Values will be added to tags by a selector.

```
jQuery.event('title',{data:' 1 quantity'},function(e){ jQuery('#title').html('Title page: '+this + ' - ' + e.data)});
jQuery.event('title',{data:' 10 quantity'},function(e){ jQuery('#footer').html('Title page: '+this + ' -' + e.data)});
```
`jQuery.event('title',function(e){ e.onetime =true;  jQuery('#footer').html('Title page: '+this)});` - One-time binding. After that, it will be unbind.
`var eventsTitle =jQuery.event('title');` - get list all binding for one variable 'title' , allows you to delete the binding.

**Comment by korenevskiy** [comment]
Possible additional options:
jQuery.eventFormat('cost', 'Total amount: ${a * b} $.');

**Comment by korenevskiy** [comment]
Possible additional options:
`jQuery.event('title','funcTitle',{data:' 1 quantity'},function(e){  ... });` - Bind event with name funcTitle
`jQuery.event('title','funcFooter',{data:' 10 quantity'},function(e){  ... });` - Bind event with name funcFooter
`jQuery.event('title','funcFooter', fasle);` - Unbind event with name funcFooter

**Comment by korenevskiy** [comment]
**To create all possible variants (var,event), jQuery already contains everything that is required for this.
All that remains is to make features in the function . But after the functions are designed, jQuery can compete with any other framework.**

**Comment by korenevskiy** [comment]
Format fucntions:
`jQuery.data( var_name, [selector/funcName,] [data,] [handler/disable] );`
`jQuery.var(var_name, value, [format_string]);`
`jQuery.eventFormat(var_name, format_string);`
No comments

**Comment by timmywil** [comment]
Thanks for opening an issue. jQuery is a DOM library and is not looking to compete with React. That said, feel free to write a plugin implementing this feature and see how it goes.

**Comment by korenevskiy** [comment]
@timmywil But let me explain in my second comment how binding works with DOM.
