### ISSUE TITLE
Binding DOM element

### ISSUE THREAD

**Issue by korenevskiy** [jquery/jquery#4747]
Dear developers. Thank you for your efforts. Please do not rush to delete this ISSUE. We often write here. You have developed a habit of reading the first paragraph briefly and then deleting the ISSUE.
I developed my own plugin. But I don't ask him to add it. This is not necessary at all. I want to report a problem.
But I will tell you briefly about the plugin.
The jQuery plugin.event().
First we subscribe a function to a particular event.
`jQuery.event('xxx',function () {})`
Then we call `jQuery.var ('xxx', 365)`. And all events for the xxx variable get this value.
Don't rush to delete ISSUE!
The second function of the plugin is to work with DOM.
```
jQuery.event('name','#username');
jQuery.event('name','.widget_cart--user');
jQuery.event('name','.module_user--name');
```
We have binding DOM elements to a value.
Now we Give the signed functions a new value.
`jQuery.var('name','Maddona');`
Similarly, the second example.
```
jQuery.event('ammount','.ammount');
jQuery.event('ammount','.cart_cost');
jQuery.var('ammount',256);
```
.
I was surprised to find that these functions already exist in the basic version of jQuery. But not all of them.
My plugin works:
1. works with functions
2. works with DOM selectors.
I realized that half the functionality of my module is already implemented in jQuery.
JQuery already has the ability to execute functions **$.on()**, **$.bind()**, and **$.trigger()**.
These functions are necessary for working with binding and passing the value.
 **But jQuery can't work the same way with DOM. jQuery can't  binding DOM elemets.**
Look at these examples.

```
<span class='ammount'>0</span>
<span class='cart_cost'>0</span>
<span class='order_cost'>0</span>

jQuery.event('cost','.ammount');
jQuery.event('cost','.cart_cost');
jQuery.event('cost','.order_cost');

jQuery.var('cost',256);
jQuery.var('cost',42);
```
DOM selectors automatically get the value of the subscription variable.

**The magic of my plugin is that I can add formatting for a separate binding for DOMelement.**
```
jQuery.event('cost','.ammount','This is the total purchase amount {0} $');
jQuery.event('cost','.cart_cost','Amount {0} $');
jQuery.event('cost','.order_cost','{0} $');
```
When changing the amount, jQuery.var('cost', 256); we get the changed amount everywhere, depending on the widget or page block.
Isn't that magic?
I repeat, my plugin can work in 2 modes with DOM and with functions. But jQuery does the same thing but only with functions. jQuery is not able to do the same with the DOM.
.
I will briefly describe the format of my plugin for your testing.
You can view the test work on this page
**[https://explorer-office.ru/files/index.html](https://explorer-office.ru/files/index.html)** and **[https://jsfiddle.net/KoreshS/1e4vqcs5/](https://jsfiddle.net/KoreshS/1e4vqcs5/)**
**You don't have a Dom element binding to the trigger.**
I specified the format of my plugin below.
```
jQuery(1).event(variableName, DOMelement); 
jQuery(1).event(variableName, function(e){});
jQuery(1).event(variableName, false, DOMelement);  //bind for only onetime
jQuery(1).event(variableName, false, function(e){}); //bind for only onetime
jQuery(1).event(variableName, DOMelement, FormatString); //bind to DOMelement with FormatString
jQuery(1).event(variableName, DOMelement, function(e){}); //bind to DOMelement with FormatString returned from fucntion
jQuery(1).event(variableName, DOMelement, false); // Unbind DOMelement
jQuery(1).event(variableName, bindName, DOMelement);//bind DOMelement  with name for after unbindto
jQuery(1).event(variableName, bindName, function(e){}); //bind with name for after unbind
jQuery(1).event(variableName, bindName, false); // Unbind bindname
jQuery(1).event(variableName, false); //unbind all binders for one variable name
```
Where DOMelement - string css selector  

Format Function for bind in method EVENT():
```
function(e){
    e.unbind(); //Unbind this function.
    e.id; //element selector
    e.elements; //jQuery elements
    e.value; //The new value of the variable to get.
    this; //The new value of the variable to get.
    return false; //Unbind this function.
    return "Dier {0} my friend!"; //Return Formating string for apply in DOM element
    return 'String for show in DOM element'; // Return string  will be show in binding html elements
}
```
Please consider this new opportunity to work with DOM, the possibility of various bindings with DOM.
If you like it, please add the same to **jQuery.bind()**, **jQuery.unbind()**, **jQuery.on()**, **jQuery.trigger()**

**Comment by korenevskiy** [comment]
Add only what we had before jQuery the ability to bind to the DOM.

**Comment by dmethvin** [comment]
Is it possible to do this with a plugin? If so it seems like the best way to test demand for this feature.  https://github.com/jquery/jquery/wiki/Adding-new-features

**Comment by timmywil** [comment]
Thank you for your contribution. While this sort of binding is very useful, we believe it is out of scope for jQuery. Please note that closing an issue does not mean it can't be reopened in the future. If a plugin with an especially useful feature gains enough traction, and we can add it to jQuery without too large of a footprint, we will consider adding that feature to core.

**Comment by korenevskiy** [comment]
@dmethvin @timmywil 

Would you personally use this binding to html tags?

**Comment by korenevskiy** [comment]
Here plugin [https://github.com/korenevskiy/Events-plugin-for-jQuery](https://github.com/korenevskiy/Events-plugin-for-jQuery)
Please look.
@dmethvin @timmywil
