### ISSUE TITLE
Error in jQuery.extend = jQuery.fn.extend (jquery/scr/core.js line116) 

### ISSUE THREAD

**Issue by istomyang** [jquery/jquery#4748]
### Description ###
I read your codes, and find the codes of deep copy never runs for variable “deep” is always false!

When you use function like jQuery.extend( { /*liberal*/ } )  is OK! 
But if run jQuery.extend( myExendObjects ) and change myExendObjects's objects, Okey, it's the shortcoming of shallow copy.

**Comment by mgol** [comment]
I'm not sure what you mean exactly as you didn't provide a test case but we have tests for deep copy using extend so they work, one example: https://github.com/jquery/jquery/blob/39c5778c649ad387dac834832799c0087b11d5fe/test/unit/core.js#L991.

**Comment by istomyang** [comment]
@mgol  Well, we don't need a test case. arguments[0]: Boolean is right. But in API document, you can look at it. When you are in production mode and use external object variables as parameters, it will accidentally destroy the members extended to jQuery. I can give you a test case:

`var deep3 = { "foo": { "baz": true }, "foo2": [1, 2, 3] };`
`jQuery.extend(deep3);`
`deep3.foo1.push("I modify jQuery's members accidentally! ");`
`assert.deepEqual(jQuery.foo2, [1, 2, 3], "Check if modified: this must not be deep copy.")`


![unnamed](https://user-images.githubusercontent.com/67993732/87293347-c1495000-c534-11ea-9397-93773f165bcb.jpg)

**Comment by mgol** [comment]
Oh, I see, the docs don't mention that `jQuery.extend` with one parameter works differently. This API is a bit weird but it might be hard to change it at this point, we might just need the docs update.

Marking for team discussion.

**Comment by istomyang** [comment]
@mgol I also think it's OK to change the document. I suggest adding a sentence to the document: It is not recommended to use external object variables as parameters.

**Comment by mgol** [comment]
The problem exists only if you pass one object, if two or more are passed, the jQuery object is not getting extended.

**Comment by istomyang** [comment]
> The problem exists only if you pass one object, if two or more are passed, the jQuery object is not getting extended.

Yes, but many developers are used to using only one variable, not more than two.  Changing the document is equivalent to changing the API interface. Maybe we should change the code. I think its coupling is very low. Or I write one to give you.

**Comment by mgol** [comment]
This API has always behaved like that so no one could have depended on the existing behavior. Changing that behavior would be a breaking change while updating the docs would be just reflecting reality.

**Comment by istomyang** [comment]
@mgol Yes, I agree with you.

**Comment by timmywil** [comment]
We discussed in the meeting. It actually is documented already, but we're going to make it more clear and separate the signature with one arg from the signature with 2+ args.

**Comment by kswedberg** [comment]
Does it matter that the OP's code refers to `$.extend()` but the screenshot of the API is for `$.fn.extend()`? Those are two different methods, yeah?

**Comment by istomyang** [comment]
> Does it matter that the OP's code refers to `$.extend()` but the screenshot of the API is for `$.fn.extend()`? Those are two different methods, yeah?

![image](https://user-images.githubusercontent.com/67993732/87372585-87bb2800-c5ba-11ea-8614-d257b1fd1db4.png)

**Comment by kswedberg** [comment]
oh, right. my bad

**Comment by timmywil** [comment]
Yes, but the documentation pages are different. I think `jQuery.fn.extend` page is very clear about this behavior, while the `jQuery.extend` only mentions it as a possibility in a signature with multiple args.

**Comment by kswedberg** [comment]
> Yes, but the documentation pages are different. I think `jQuery.fn.extend` page is very clear about this behavior, while the `jQuery.extend` only mentions it as a possibility in a signature with multiple args.

Yeah, it all makes sense to me now. Sorry for the distraction. Carry on. 😄
