### ISSUE TITLE
[Feature request] Make it simple for the "resize" functionality in jquery-ui to not go below a minimum width/height of the parent div, and document it.

### ISSUE THREAD

**Issue by rubyFeedback** [jquery/jquery#4750]
Hey there jquery devs,

I have been using jquery since 2014 or so; am very happy with it (evidently my nick implies that ruby is my main
language and that is true).

Today I was looking at more jquery examples to pick up and I found the resizable action:

    https://jqueryui.com/resizable/

This is really cool. I actually begun to use jquery due to the draggable interface. I needed
to be able to drag about images, and jquery allowed for this.

Now to the topic of this issue request:

There is one problem I have with resize and that is that you can resize it below the minimum
size (the parent div or p tag).

I'd rather like to have an OPTION to not allow for a block (parent) element to go below a 
certain minimum size. I know some other users may want to retain the old behaviour so
I am NOT suggesting to change the default, per se. But rather, that it should be an
option.

Perhaps it could be possible to do something like this:

"if parent container has minimum size:
  respect this"

And enable it via some API call to .resizable or so. My javascript is too weak to suggest
how to use it.

By the way the examples are nice but it would be great if these could be extended
with specific examples how to do something. If it is not yet possible what I suggest,
then that is ok, but I think there are tons of things I don't know yet, and for people
like me, and others, it may be super-helpful if such custom solutions could be shown
right on the examples page. It is literally my first go-to target for jquery-related
stuff. :)

(If this is too difficult to code, or takes too much time or is too special, please just
feel free to close this. Not sure if jquery-ui should go into jquery here but jquery-ui
had no github issue, so I try here. :D )

**Comment by mgol** [comment]
Thanks for the report. However, this is a bug tracker for jQuery, not jQuery UI. Tickets for jQuery UI should be submitted at https://bugs.jqueryui.com/.

**Comment by mgol** [comment]
Please note, though, that UI is not in a very active development at the moment.
