### ISSUE TITLE
Security fixes for 2.2-stable

### ISSUE THREAD

**Issue by davidtong** [jquery/jquery#4751]
### Description ###
The latest security fixes in jQuery 3.5 are not back-ported to jQuery 2.2, leaving applications that cannot be upgraded to jQuery 3+ vulnerable.

**Comment by dmethvin** [comment]
Several of the security fixes in jQuery 3 are breaking changes that necessitated a semver-major bump. jQuery 3 *is* the security fix for jQuery 2.  We can't provide a secure-but-drop-in-and-nothing-will-break upgrade to jQuery 2. Some third parties have created versions that try to remove the issues but those are not supported by us.

To upgrade to jQuery 3, you can use the jQuery Migrate plugin.
