### ISSUE TITLE
upgraded jquery 3.5.1 but now $('form').validate().settings not working. Please provide solution

### ISSUE THREAD

**Issue by Tandulje** [jquery/jquery#4770]
Upgrade 2.1.4 to 3.5.0 now $('form').validate().settings.ruls not working....please please suggest me solution for same. Thank you.

**Comment by mgol** [comment]
jQuery doesn't have a `validate` method so I suspect you're using the jQuery Validation plugin, issues should be reported there. You'll need to provide a test case for anyone to fix anything, though.

**Comment by Tandulje** [comment]
> jQuery doesn't have a `validate` method so I suspect you're using the jQuery Validation plugin, issues should be reported there. You'll need to provide a test case for anyone to fix anything, though.

It works for jquery-v2.1.4 not  jquery-v3.5.1 that is issue.

**Comment by mgol** [comment]
I understand but that doesn't tell me much. If it's a jQuery Validation issue with newer jQueries, you should report it to that project. If it's a bug in jQuery, we need a test case without external libraries. Just saying that something doesn't work doesn't help.

**Comment by Tandulje** [comment]
Hi...i'am using jquery -v3.5.1 and jquery.validate -v1.9.2

My code is
var settings = $('form').validate().settings;
settings.rules['UserPrincipalName'].required = true;

it gives error
VM155:294 Uncaught TypeError: Cannot set property 'required' of undefined

When i was on older version jquey -v2.1.4 then it was working fine **but now not working with jquey- v3.5.1**

Please give some solution on it.
I go through lots of link but not getting related to this.
Please let me know how can i fix this issue.

**Comment by mgol** [comment]
As the issue template indicates, we need a runnable test case on a service like jsbin.com; the code you provided doesn't help us much as we can't run it.

But, also, as I already mentioned above, this needs to not include third party libraries, otherwise bug trackers of those libraries are a place to report the issue.
