### ISSUE TITLE
JSONP and parsing responseText upon 409 Conflict

### ISSUE THREAD

**Issue by fras2560** [jquery/jquery#4771]
Bug Reports:
  Unable to parse responseText of JSONP in a error handler.
  *  What do you expect to happen? Able to parse the JSON
  *  What actually happens? Get a parsing error
  *  Which browsers are affected - Chrome/Firefox?

Currently using Backbone and JQuery. Recently have upgraded from 3.3.1 to 3.5.1. Essentially, backbone is using a jsonp request to delete a model but expecting a 409 due to the model being unable to be deleted. It works as expected and end up in the error handler but the responseJson is not present. I have walked through the stack trace difference between 3.3.1 & 3.5.1. The reason seems to be a parsing error:

`error: Error: jQuery35109401972421271656_1597775421415 was not called at Function.error (3.5.1/jquery.js:334:9) at s.converters.script json (3.5.1/jquery.js:10232:12) at ajaxConvert (jquery/3.5.1/jquery.js:9260:19) at done (3.5.1/jquery.js:9736:15) at XMLHttpRequest.<anonymous> (3.5.1/jquery.js:10047:9)
message: "jQuery35109401972421271656_1597775421415 was not called"
stack: "Error: jQuery35109401972421271656_1597775421415 was not called
state: "parsererror"`

From walking through the stacktrace it seems related to - https://github.com/jquery/jquery/commit/50871a5a85cc802421b40cc67e2830601968affe

**Comment by mgol** [comment]
Thanks for the report.

We considered #4379 to be a bug fix but JSONP is a bit special, indeed - under the hood it's a script but it simulates JSON responses in an environment without a CORS setup and sending JSON payloads on error responses is quite typical there. Maybe we need to revisit the JSONP case.

It'd help if you could provide a minimal test case or - even better - a test case for the jQuery test suite, something like https://github.com/jquery/jquery/blob/82b87f6f0e45ca4e717b4e3a4a20a592709a099f/test/unit/ajax.js#L809-L922 but for JSONP & a different expected result. Would you want to try that?

**Comment by fras2560** [comment]
@mgol  Thanks for the quick response. I will give it a try to make a test case or at the very least a minimal test case. I hope I correctly described the situation but will confirm for sure (bit  complicated with Backbone, Server, and JQuery).

**Comment by mgol** [comment]
It’d help if the test case didn’t contain external libraries. If this is
just about JSONP in error scenarios, any 4xx or 5xx status code should work
for the test case.

Thanks!
-- 
Michał Gołębiowski-Owczarek

**Comment by fras2560** [comment]
@mgol  I think I have fix for the issue and wrote up a simple test. However, I am not too familar with PHP so I might need some help with this. I am not even sure how to run it locally. Also, need some help with response body

https://github.com/jquery/jquery/pull/4773

**Comment by Realtyepic** [comment]
@mgol https://javascripter.space/questions/accessing-data-from-another-domain-using-javascript-with-cross-origin-resource-sharing
