### ISSUE TITLE
$('htmlString) in version 3.5.1 returns different result compare to 3.3.1 with the same html string.

### ISSUE THREAD

**Issue by nuong** [jquery/jquery#4780]
### Description ###
I am using fullcalendar and found out that 
$('htmlString) in version 3.5.1 returns different result compare to 3.3.1 with the same html string.
this issue causes bug in our application recently. 
Please see Jsbin link demo for this issue
1. Using jquery 3.5.1 https://jsbin.com/coqexoj/2/edit?html,js,console,output
2. Using jquery 3.3.1 https://jsbin.com/pudosiv/2/edit?html,js,console,output

**Comment by mgol** [comment]
Please read the issue template carefully when reporting issues. It mentions the following:

Frequently Reported Issues:
  * Self-closing tags broken in jQuery 3.5.0 or newer: please read the [jQuery 3.5.0 blog post](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/) & the [upgrade guide](https://jquery.com/upgrade-guide/3.5/); see also issue #4681.

This is exactly what's happening here.
