### ISSUE TITLE
jQuery.parseXML should add detailed information about parse errors

### ISSUE THREAD

**Issue by MatthiasSchmalz** [jquery/jquery#4784]
### Description ###
If an invalid XML is passed to jQuery.parseXML, currently the thrown parse error only contain the input data but not the error reason.
However the internally created XML document contains the parser errors in the element parsererror as innerText and could be added. This is helpful for debugging errors in XML files

### Link to test case ###
https://jsfiddle.net/o678xuz3/

**Comment by mgol** [comment]
Thanks for the report. However, the test case attached doesn't work, it even doesn't include jQuery. Please share a test case where the issue and what you'd expect instead can be reproduced.

**Comment by MatthiasSchmalz** [comment]
I'm sorry I have not described the testcase properly.
It is using jQuery which is available implicitely and it uses the jQuery.parseXML. It logs the error message that is raised by the parser to the console.
Additionally it logs the error which the internally used XML parser produces and which should be returned.

**Comment by mgol** [comment]
What do you propose us to change? `jQuery.parseXML` returns the parsed XML and doesn't crash in case of errors. Do you propose that an error we log to the console contained contents of `xml.getElementsByTagName( "parsererror" )` as well?

**Comment by MatthiasSchmalz** [comment]
I propose to add the xml.getElementsByTagName( "parsererror" )[0].innerText to the text of the thrown Error.

**Comment by timmywil** [comment]
I like this idea. I'd much prefer to either show the parserror content (with provided snippet) or a generic message without trying to add the data to the string.

**Comment by mgol** [comment]
PR: #4816
