### ISSUE TITLE
Defining any property/function on Object.prototype will cause jQuery's addBack to throw error?

### ISSUE THREAD

**Issue by dotnetprono1** [jquery/jquery#4789]
I think this must be a bug of jQuery, a simple custom property/function definition on **Object.prototype** is just normal (and fairly common). That kind of action should not trigger any bug in any framework. But here it does cause a bug in the jQuery when we use _addBack_ **with filter (selector)**.

So here what I've done before detecting the issue:

    //define a simple dummy random property like this (before loading and running the jQuery code)
    Object.prototype.xyzxxx = "";

    $(function(){
         //just try a query with .addBack with selector
         $("div").addBack("div");
    });

Here is the error printed in the console:

    Uncaught TypeError: G[o].exec is not a function
    at se.tokenize (jquery-3.5.1.min.js:2)
    at se.compile (jquery-3.5.1.min.js:2)
    at se.select (jquery-3.5.1.min.js:2)
    at se (jquery-3.5.1.min.js:2)
    at Function.se.matches (jquery-3.5.1.min.js:2)
    at Function.S.filter (jquery-3.5.1.min.js:2)
    at D (jquery-3.5.1.min.js:2)
    at S.fn.init.filter (jquery-3.5.1.min.js:2)
    at S.fn.init.addBack (jquery-3.5.1.min.js:2)
    at HTMLDocument.<anonymous> (?editor_console=:111)

Note that the addBack without selector will not cause the error.
You can try out the fiddle here https://jsfiddle.net/v8hfmdn3/1/ for detailed error info.

**Comment by dotnetprono1** [comment]
So currently in my project I'm using **addBack** with selector (which is not a very common use case but I do need it) together with custom property/function defined on **Object.prototype** (this is just recently required) and boom, the issue popped out taking me several minutes to try to understand what was strangely going wrong before believing that it could be a bug in the jQuery library.

**Comment by dotnetprono1** [comment]
I've tried defining the custom property/function for **Object.prototype** the other way using **Object.defineProperty** and looks like it works fine without throwing the error. e.g: _Object.defineProperty(Object.prototype, "xyzxxx", { value: "" });_

**Comment by mgol** [comment]
Modifying `Object.prototype` is not supported. It’s generally a bad idea. See https://github.com/jquery/jquery/wiki/Won't-Fix#modifying-objectprototype
