### ISSUE TITLE
jQuery `DOMSubtreeModified` gets a Violation message in Google Chrome 

### ISSUE THREAD

**Issue by ayumi-cloud** [jquery/jquery#4791]
Using jQuery version: v3.4.0 and jQuery Migrate: 3.0.1 - yes I know old versions.

When I add the following code example:

```js
$('#element').on('DOMSubtreeModified', function() {
        // do something
});
```

I get the following Violation message in Google Chrome 87:

```
[Violation] Added synchronous DOM mutation listener to a 'DOMSubtreeModified' event. Consider using MutationObserver to make the page more responsive.
```

Is this a bug in the latest jquery v3.5.1

**Comment by dmethvin** [comment]
The warning is because your code used a deprecated event.  jQuery doesn't stop you from doing that. Consider using `MutationObserver` instead.
