### ISSUE TITLE
jQuery.isNumberic

### ISSUE THREAD

**Issue by lanweipeng** [jquery/jquery#4795]
### Description ###
jQuery.isNumberic(1000n)
error
cannot test bigint

**Comment by dmethvin** [comment]
https://api.jquery.com/jQuery.isNumeric/#jQuery-isNumeric-value

### **Note: This API has been deprecated in jQuery 3.3.**

> As of jQuery 3.0 $.isNumeric() returns `true` only if the argument is of type `number`, or if it's of type `string` and it can be coerced into finite numbers. In all other cases, it returns `false`.

**Comment by mgol** [comment]
It doesn't error for me, it just returns `false`:
https://jsbin.com/xumokoq/1/edit?html,js,output

As Dave mentioned, this method is deprecated so we're not looking into adding support for new primitives there. This API will be gone in jQuery 4.
