### ISSUE TITLE
Is "click" going to be deprecated?

### ISSUE THREAD

**Issue by paaresh** [jquery/jquery#4796]
I am migrating my website to use latest version of JQuery ( v3.5.1 ).
I attached "jquery-migrate" pluging ( https://github.com/jquery/jquery-migrate/ ) to see compatibility issue while migrating.
I got "_jQuery.fn.click() event shorthand is deprecated_" but on "click" documentation page ( https://api.jquery.com/click/ ), no such thing mentioned that it is going to be deprecated.
Same thing for "dblclick".
Is it really going to be deprecated?

**Comment by mgol** [comment]
Yes, shorthands are deprecated. We have an issue to document that that is still open: https://github.com/jquery/api.jquery.com/issues/972.

**Comment by paaresh** [comment]
> Yes, shorthands are deprecated. We have an issue to document that that is still open: [jquery/api.jquery.com#972](https://github.com/jquery/api.jquery.com/issues/972).

Actual documentation of shorthand does not contain deprecation related information so it creating confusion.
Ex: 
https://api.jquery.com/bind/ - in this documentation it is mentioned that  "_version deprecated: 3.0_"
https://api.jquery.com/click/ - in this documentation no such thing mentioned.

**Comment by mgol** [comment]
Yes, that’s what I meant: we need to document that, it hasn’t been done yet and we have an issue for it in the documentation repository. We accept PRs if you want to fix something in docs.
