### ISSUE TITLE
jQuery should not stop development

### ISSUE THREAD

**Issue by otengkwame** [jquery/jquery#4805]
Thank you to who ever will give me a sincere answer before deleting or closing this issue. 

It's still 2020 and jQuery is still under active maintenance. Whiles some people who hate jQuery (I'm a big fun and still using it seriously) keep on defaming it. I want to continue to talk about the good works of it. My question is will it be ever discontinued, I know I shouldn't be typing here but before you close it let me know. Because I want to start doing lot's of video tutorials on it to keep promoting it and the good team behind it. And I want this to come from the jQuery people with assurance because I have seen BootStrap 5 moving away from jquery.

Thanks so much in advance

**Comment by Johann-S** [comment]
Bootstrap 5 is compatible with jQuery but work without jQuery too 😉

**Comment by timmywil** [comment]
Thanks for opening an issue. There are no plans to stop maintaining jQuery. jQuery is still widely used and will need support for a long, long time.

**Comment by otengkwame** [comment]
Thanks so much @timmywil and @Johann-S that is all I wanted to hear. 

I have more plans for this project
