### ISSUE TITLE
'define' not declared

### ISSUE THREAD

**Issue by manang** [jquery/jquery#4806]
Hi,
I'm trying to use a js lib, that uses jquery as dependency, in my react library.
reactjs tells me that the variable 'define' is not used.
https://github.com/jquery/jquery/blob/d0ce00cdfa680f1f0c38460bc51ea14079ae8b07/src/exports/amd.js#L16

how can I solve this issue?
thank you very much

Angelo

**Comment by mgol** [comment]
`define` is an AMD function; jQuery uses AMD internally to manage its dependencies. You have two choices - either your tool needs to load the compiled jQuery version from the `dist` folder or you need to make it understand the AMD format.
