### ISSUE TITLE
modal function is not present in jquery?..how can i show bootstrap's modal using jquery(after an interval)?

### ISSUE THREAD

**Issue by jatin-karla11** [jquery/jquery#4809]
useEffect(() => {
      setTimeout(() => {
        // console.log('This will run after 1 second!')
         $('#exampleModal2').modal("show");
        // alert("helllll") 
      }, 10000);
      
    }, []);

**Comment by mgol** [comment]
jQuery doesn't have a `modal` function. This is not a good place to look for programming help.
