### ISSUE TITLE
$(document).ready() not firing in Firefox for Android 83

### ISSUE THREAD

**Issue by benediktcarda** [jquery/jquery#4812]
jQuery does not fire the $(document).ready() event listener in Firefox for Android. I am using Firefox version 83 and of course the latest jQuery version. This is only true for Firefox Android version. On the current desktop version (83 as well) it works as it should. 

Here is the test case:
https://jsfiddle.net/carda/bm019eyf/2/

**Comment by ygj6** [comment]
Very confused, I tested the above link with my Android phone and it works.

Android version: 9
Firefox version: 83.1.0

**Comment by ygj6** [comment]
Very confused, I tested the above link with my Android phone and it works.

Android version: 9
Firefox version: 83.1.0

**Comment by michaljusiega** [comment]
For me working to:

![Screenshot_20201130-053331_Firefox.jpg](https://user-images.githubusercontent.com/16488888/100569221-ad2ca200-32cd-11eb-972f-d73a9afb5c5d.jpg)
![Screenshot_20201130-053353_Firefox.jpg](https://user-images.githubusercontent.com/16488888/100569239-b584dd00-32cd-11eb-87ea-5e677e2b39a1.jpg)

**Comment by timmywil** [comment]
Thanks for opening an issue. Given the above comments, it's very unlikely this is an issue in jQuery.

**Comment by jbostoen** [comment]
Still seems to be an issue today (likely a FireFox one).
