### ISSUE TITLE
Syntax error on line 4073 in jquery-3.5.1.js

### ISSUE THREAD

**Issue by favigred** [jquery/jquery#4817]
My Adobe Dreamweaver CS4 told me about "Syntax error on line 4073 in jquery-3.5.1.js"

![jquery](https://user-images.githubusercontent.com/75994426/102093869-b6bc1b00-3e32-11eb-933a-3096a594bd8b.jpg)

**Comment by timmywil** [comment]
Thanks for opening an issue. However, there is no syntax error there so you may want to report this to Adobe Dreamweaver.
