### ISSUE TITLE
append script

### ISSUE THREAD

**Issue by wineSu** [jquery/jquery#4818]
```
<div class="test"></div>
<div class="test"></div>
<script type="text/javascript">
	$('.test').append('<script>alert(0)')
</script>
```
I want to pop it twice, but just once

**Comment by timmywil** [comment]
Thanks for opening an issue. This is intended behavior. It's usually a mistake to execute an appended script more than once.

**Comment by timmywil** [comment]
If you really want the script to execute more than once, you can use https://api.jquery.com/jQuery.globalEval/ directly.
