### ISSUE TITLE
Unintentional replacement of '%20' with '+' in ajax.

### ISSUE THREAD

**Issue by AsazuTaiga** [jquery/jquery#4820]
### Description ###

Current Specifications: If `'Content-type'` is `'application/x-www-form-urlencoded'`, `'%20'`s in form body are replaced with `'+'` [here](https://github.com/jquery/jquery/blob/a503c691dc06c59acdafef6e54eca2613c6e4032/src/ajax.js#L622).

And if a user use `'headers'` option instead of 'contentType' option to specify HTTP Content-type header, `'application/x-www-form-urlencoded'` is assigned to '`s.contentType`'.

This may be not a bug, but unintentional replacement of  `'%20'` with `'+'` may dissatificate users. (sorry poor English)

### Link to test case ###

N/A

**Comment by mgol** [comment]
You can read some backstory in https://github.com/jquery/jquery/issues/2658 & [trac-3400](https://bugs.jquery.com/ticket/3400) but yes, this is intended for that content type as that's how native forms behave which this content type is for.

The current HTML WHATWG spec covers it in:
https://url.spec.whatwg.org/#concept-urlencoded-serializer
https://url.spec.whatwg.org/#application-x-www-form-urlencoded-percent-encode-set

It's a bit easier to read in the old HTML 4.01 spec:
https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1
