### ISSUE TITLE
$( html ) cuts trailing text, not just white space

### ISSUE THREAD

**Issue by 5saviahv** [jquery/jquery#4821]
### Description ###
if I call `$('<p>foo<p>bar')`

I get two `<p>` elements but first has text, second one don't have text.

Is it intentional ?

If it is ? What is/was the reason ? There is comment to issue #11290, but I cant found it.

### Link to test case ###

`$('<p>foo<p>bar')`

**Comment by ygj6** [comment]
You can try `$.parseHTML`, it can correctly return two `<p>` elements that contain text.
```javascript
$("body").html($.parseHTML('<p>foo<p>bar'))
```

**Comment by 5saviahv** [comment]
true I can use `parseHTML`, I am simply curios maybe there has some reason.

I also went back in history and it seems to be with us at least from v1.2

**Comment by dmethvin** [comment]
> When passing HTML to jQuery(), note that text nodes are not treated as DOM elements. With the exception of a few methods (such as .content()), they are generally ignored or removed.

https://api.jquery.com/jQuery/
