### ISSUE TITLE
.animate({ }) can't handle the vh, vw, rem, em, css units in 'calc' values :(

### ISSUE THREAD

**Issue by nicerapp** [jquery/jquery#4829]
### Feature Request ###
i need the following feature please to keep my site responsive and up to date with the latest CSS standards.

### Description ###
.animate({ }) can't handle the vh, vw, rem, em, css units in 'calc' values :( 

### Link to test case ###
https://github.com/nicerapp/nicerapp_v2/blob/main/nicerapp/siteLogic/site.source.js

**Comment by nicerapp** [comment]
hey, i've found a way to get this done, in pure css3.
see
https://github.com/nicerapp/nicerapp_v2/blob/main/nicerapp/siteLogic/site.source.js
and
https://github.com/nicerapp/nicerapp_v2/blob/main/nicerapp/domainConfigs/localhost.v2/index.css #siteContent, @keyframes anim_siteContent_started

while this won't be supported in older browsers, i'm making my nicerapp_v2 for-current-browsers-only

it would be nice however, to see this functionality end up in a future version of jQuery, for those who are stuck supporting older operating systems and browsers.

**Comment by timmywil** [comment]
Thanks for opening an issue. The link to your JS file seems to 404. Perhaps it is private or gone. However, it would be great if you could make a working, reduced test case on https://jsfiddle.net or https://jsbin.com.

**Comment by timmywil** [comment]
Closing until we have a test case.
