### ISSUE TITLE
Add finally to jQuery.Deferred promise object

### ISSUE THREAD

**Issue by evgencode** [jquery/jquery#4831]
### Description ###

It would be nice to have a **finally**  method identical to **always** in promise object.
I could add it like this:

```
var def = return $.Deferred();
return def.promise({ finally: def.always.bind(def) });
```

but `then` method returns `jQuery.Deferred( function( newDefer ) { ... }).promise()`;
the same problem with `catch` callback.

`promise()` is without arguments returns local `promise` variable. `finally` function is lost.

But `done` and `fail` callbacks return full deferred object, with extended object.

**Comment by Krinkle** [comment]
See also https://github.com/jquery/jquery/issues/4290.

**Comment by timmywil** [comment]
Thanks for opening an issue. We can look into this and see what a PR might look like.

**Comment by Krinkle** [comment]
Merged into https://github.com/jquery/jquery/issues/4290.
