### ISSUE TITLE
Is there a jQuery.holdReady() alternative?

### ISSUE THREAD

**Issue by udidol** [jquery/jquery#4847]
### Description ###
`jQuery.holdReady()` was deprecated in v3.2.0.
I couldn't find a replacement.
What is the alternative to `jQuery.holdReady()`?

**Comment by mgol** [comment]
Hey, the alternative is explained in the docs of that method: https://api.jquery.com/jQuery.holdReady/

**Comment by udidol** [comment]
Hi @mgol  
I saw the documentation already, but it doesn't provide a real alternative.
I want to prevent other scripts outside of my code from running, who run on `jQuery.ready()`.
It is not possible to put external scripts inside a custom promise.

There is no solution for this use of `holdReady`?

**Comment by dmethvin** [comment]
Load those scripts in the ready handler.
