### ISSUE TITLE
hover() documentation and typescript types don't match

### ISSUE THREAD

**Issue by AcademyOfF** [jquery/jquery#4848]
In this documentation, I can't find any evidence that `hover` is deprecated: https://api.jquery.com/hover/

But, if you `npm install -D @types/jquery` (gave me version 3.5.5), the jQuery.d.ts file has this in it:

```
/**
     * Bind two handlers to the matched elements, to be executed when the mouse pointer enters and leaves the elements.
     * @param handlerIn A function to execute when the mouse pointer enters the element.
     * @param handlerOut A function to execute when the mouse pointer leaves the element.
     * @see \`{@link https://api.jquery.com/hover/ }\`
     * @since 1.0
     * @deprecated ​ Deprecated.
     *
     * **Cause**: The `.hover()` method is a shorthand for the use of the `mouseover`/`mouseout` events. It is often a poor user interface choice because it does not allow for any small amounts of delay between when the mouse enters or exits an area and when the event fires. This can make it quite difficult to use with UI widgets such as drop-down menus. For more information on the problems of hovering, see the \`{@link http://cherne.net/brian/resources/jquery.hoverIntent.html hoverIntent plugin}\`.
     *
...
```

But this documentation marks it as deprecated, and therefore, it looks like it shouldn't be used according to my IDE visual studio code. Is this function deprecated or not? Either the types or the documentation needs to change to match the other.

**Comment by timmywil** [comment]
Thanks for opening an issue. It is indeed deprecated, but the types are not managed by the jQuery team.

**Comment by AcademyOfF** [comment]
> It is indeed deprecated

Okay that means that the types are more up-to-date than the documentation. The issue is now that the documentation is out of date. Like I said above, `hover` is not deprecated in the documentation. `hover` is just an example. All of the ones mentioned here are not deprecated in the documentation even though they should be: https://github.com/jquery/jquery/issues/3214

In other words, this issue is (some?) deprecated methods are not mentioned as deprecated in the documentation.

**Comment by mgol** [comment]
It looks like we haven't actually deprecated `.hover()` properly, see my comment at https://github.com/jquery/api.jquery.com/issues/972#issuecomment-621324358. @timmywil can we add that deprecation to the 3.6 blog post? In code it has been in the deprecated module for a while and at least since 3.5.0 in its current form:
https://github.com/jquery/jquery/blob/3.5.0/src/deprecated/event.js

**Comment by AcademyOfF** [comment]
I decided to change the title of this issue to make it more relevant and general

**Comment by mgol** [comment]
@AcademyOfF The documentation repo is https://github.com/jquery/api.jquery.com, issues about missing docs for some APIs are better reported there. Please note, however, that many of those issues already exist, we're just lacking resources to finalize them promptly. PRs are very much welcome.
