### ISSUE TITLE
jquery-latest points to v1.11.1

### ISSUE THREAD

**Issue by hoodmane** [jquery/jquery#4849]
The URL https://code.jquery.com/jquery-latest.js sounds like it would point to the latest version of jquery. Instead, it points to version 1.11.1 released in 2014. Is this intentional? jquery-terminal suggests to load jquery using that url.

https://github.com/jcubic/jquery.terminal/issues/646

**Comment by dmethvin** [comment]
https://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/

**Comment by hoodmane** [comment]
Thanks, I will post that link over to the issue on jquery-terminal.

**Comment by hoodmane** [comment]
It would be extremely helpful if `jquery-latest` printed a `console.warn` message. I was running into problems because code using `jquery-latest` suggested by one person was copied into a project a second person. `jquery-latest` doesn't exactly look like a code smell. The only reason I noticed that there was a problem was that I switched to using the jsdelivr link https://cdn.jsdelivr.net/npm/jquery because jsdelivr serves files with `Cross-Origin-Resource-Policy : cross-origin`. I just thought jquery was very buggy.

**Comment by mgol** [comment]
Changing the file to print a warning would surely result in lots of reports about a sudden warning that lots of people didn’t want. Not to mention the file would get different from a regular 1.11.1 version. There’s some risk involved.

**Comment by hoodmane** [comment]
Yeah makes sense. I guess there's no winning in software maintenance.

**Comment by hoodmane** [comment]
Thanks again for your prompt response!
