### ISSUE TITLE
jQuery.ready()

### ISSUE THREAD

**Issue by udidol** [jquery/jquery#4851]
### Description ###
Since `jQuery.holdReady()` is being deprecated:
Are you going to be removing the `jQuery.readyWait` functionality from the `ready()` function? 
Or are you going to leave it for backwards compatibility?

**Comment by parthkapadia10** [comment]
jQuery.ready()

**Comment by timmywil** [comment]
Thanks for opening an issue. The functionality itself is deprecated. If you need to wait for something, it's better to wait for it explicitly with a Promise or jQuery.Deferred. https://api.jquery.com/jquery.holdReady/ has an example replacement that demonstrates waiting for two things, one of them being the `ready` event. As for whether it will be removed, I can't say for sure, but generally things that are deprecated could be removed in the future.
