### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by limonte** [jquery/jquery#4852]
https://github.com/jquery/jquery/releases/tag/3.6.0 doesn't have any release notes and the repo doesn't contain CHANGELOG.md

Where the release changes can be found? Thanks!

**Comment by campersau** [comment]
There is a blog post about it: https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/

**Comment by limonte** [comment]
Thank you @campersau!

**Comment by timmywil** [comment]
Added a link to the blog post in the GitHub release notes.
