### ISSUE TITLE
In jQuery 3.4.0+ in IE a focus-blur-focus sequence doesn't leave the element focused

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#4856]
### Description ###

Invoking:
```js
$( inputNode )
	.trigger( "focus" )
	.trigger( "blur" )
	.trigger( "focus" );
```
leaves input focused in all browsers except IE.

I discovered it while working to fix the remaining jQuery UI issues when tested against Core 3.6.0+. Interestingly, the relevant UI issue doesn't manifest itself in 3.4 & 3.5, I'm not sure why.

A relevant UI test run: http://swarm.jquery.org/result/3963629. That's the "dialog: core: focus tabbable" test.

### Link to test case ###

https://jsbin.com/zoyowez/1/edit?html,js,output

Changing the jQuery version to 3.3.1 makes it work again.

**Comment by mgol** [comment]
OK, the relevant UI test (dialog: core: focus tabbable):
https://builds.jenkins.jquery.com/jquery-ui/9ea690a0d9e645280dbb448579d2ac3babb510ed/tests/unit/dialog/dialog.html?nojshint=true&jquery=3.4.1&testId=a84fb0fe
does fail with jQuery 3.4+, it's just that in 3.4 & 3.5 it doesn't fail when run together with the rest of the dialog test suite.

**Comment by mgol** [comment]
That's the assertion code that's failing: https://github.com/jquery/jquery-ui/blob/e31cf579a0f3e64250af2e7269eef2e6c6e3d8fb/tests/unit/dialog/core.js#L121-L129

**Comment by timmywil** [comment]
We'll look at addressing focus issues in 3.6.1.

**Comment by mgol** [comment]
It looks like we can fix this via simulating the async `focus` & `blur` in IE via their bubbling but also synchronous equivalents: `focusin` & `focusout`. In other browsers, all those events are synchronous.

PRs for:
* jQuery 4.0: #5223
* jQuery 3.x: #5224

**Comment by mgol** [comment]
Fixed on `main` (future `4.x`) via #5223 and on `3.x-stable` via #5224.
