### ISSUE TITLE
Bug with Content Security Policy (CSP) : can't use strict style-src

### ISSUE THREAD

**Issue by jcvignoli** [jquery/jquery#4857]
### Description ###

The latest JQuery 3.6 is prevented from fully running when a strict CSP policy is implemented.

A CSP error is given if using nonces. If not using nonces and relaxing the policy (with unsafe-inline) no error is detected.

### Link to test case ###

https://wikileaks.jcvignoli.com

(I may relax the header (remove the nonces) in the course of the days, should you need the full example please let me know)

**Comment by mgol** [comment]
Thanks for the report. The test case you provided is a full site; can you prepare an isolated test case without unrelated code?

**Comment by jcvignoli** [comment]
Sorry for the lack of information. I don't exactly understand what you mean by "isolated test case"... but let me provide further info below. Should you need more, please explain how.

Should I visit the aformentionned site, the following CSP violation report is created:

> document uri: https://wikileaks.jcvignoli.com/?code=ouvretoi
> referrer:
> violated directive: style-src
> blocked uri: inline
> position: line 2 / column 65760
> source: https://www.jcvignoli.com/styles/jquery-latest.min.js

The following CSP headers are implemented:

`Content-security-policy: default-src 'none'; base-uri 'self'; connect-src *; form-action 'self' https://tpc.googlesyndication.com; frame-ancestors 'none'; img-src 'self' data: https://www.googletagmanager.com https://www.google-analytics.com https://pagead2.googlesyndication.com/pagead/ https://googleads.g.doubleclick.net/pagead/ https://www.gstatic.com; child-src 'self' https://www.google.com https://googleads.g.doubleclick.net/pagead/; frame-src 'self' https://tpc.googlesyndication.com https://googleads.g.doubleclick.net https://www.gstatic.com https://bid.g.doubleclick.net https://www.youtube.com https://www.google.com; script-src 'self' 'report-sample' 'unsafe-inline' 'nonce-$NONCE' 'strict-dynamic' https://www.google.com/pagead/conversion_async.js https://adservice.google.com https://www.googleadservices.com/pagead/ https://www.google-analytics.com/analytics.js https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js https://www.googletagmanager.com/gtag/js https://googleads.g.doubleclick.net/pagead/; style-src 'self' 'report-sample' 'unsafe-inline' 'nonce-$NONCE' https://www.jcvignoli.com/styles/; object-src 'none'; worker-src 'none'; font-src 'self' data: https://fonts.gstatic.com; upgrade-insecure-requests; 
`

**Comment by mgol** [comment]
By isolated test case I mean a separate small page created just to reproduce the issue, without any code not needed for this reproduction. A full website doesn’t fit this criterium.

usually we recommend JS Bin but here you need to set CSP headers so it wouldn’t work.

**Comment by mgol** [comment]
OK, Firefox doesn't provide a stack trace in CSP reports but Chrome does so I was able to have a look.

The problem is the following code:
```js
this.$queryInput.attr({
    style: "",
    placeholder: this.options.placeholder
});
```
Since you declare `style-src` with a `nonce`, setting the `style` attribute is disallowed. You'd get the same error in pure JS if you tried e.g.:
```js
document.body.setAttribute('style', '');
```
jQuery is not at fault here.
