### ISSUE TITLE
Useless/Suspicious code in jQuery 3.6.0 reported by Closure Compiler

### ISSUE THREAD

**Issue by bmt-systems** [jquery/jquery#4858]
jQuery 3.6.0 has ten locations with useless or suspicious code, as reported by the Google Closure Compiler. This can be verified by providing the uncompressed, development version of jQuery 3.6.0 to the public online compiler at [Closure Compiler Service](https://closure-compiler.appspot.com/home) using the default Simple optimization setting, and then reading the warnings when the compiler is finished.

jQuery 3.6.0 does compile successfully, but it reports the following instances of apparently useless or suspicious code (e.g., Boolean tests that always evaluate to truthy, making the test apparently unnecessary, etc.)  They are:

> JSC_USELESS_CODE: Suspicious code. The result of the 'getprop' operator is not being used. at line 737 character 42
>     arr[ preferredDoc.childNodes.length ].nodeType;
>                                           ^
> JSC_SUSPICIOUS_LEFT_OPERAND_OF_LOGICAL_OPERATOR: Left operand of && operator is always truthy. at line 1876 character 16
>                 ( pattern = new RegExp( "(^|" + whitespace +
>                 ^
> JSC_USELESS_CODE: Suspicious code. This code lacks side-effects. Is there a bug? at line 2199 character 12
>             if ( elem.parentNode ) {
>             ^
> JSC_USELESS_CODE: Suspicious code. The result of the 'getprop' operator is not being used. at line 2201 character 32
>                 elem.parentNode.selectedIndex;
>                                 ^
> JSC_USELESS_CODE: Suspicious code. This code lacks side-effects. Is there a bug? at line 8213 character 12
>             if ( parent && parent.parentNode ) {
>             ^
> JSC_USELESS_CODE: Suspicious code. The result of the 'getprop' operator is not being used. at line 8214 character 34
>                 parent.parentNode.selectedIndex;
>                                   ^
> JSC_USELESS_CODE: Suspicious code. This code lacks side-effects. Is there a bug? at line 8223 character 12
>             if ( parent ) {
>             ^
> JSC_USELESS_CODE: Suspicious code. The result of the 'getprop' operator is not being used. at line 8224 character 23
>                 parent.selectedIndex;
>                        ^
> JSC_USELESS_CODE: Suspicious code. This code lacks side-effects. Is there a bug? at line 8226 character 16
>                 if ( parent.parentNode ) {
>                 ^
> JSC_USELESS_CODE: Suspicious code. The result of the 'getprop' operator is not being used. at line 8227 character 38
>                     parent.parentNode.selectedIndex;
>                                       ^

**Comment by mgol** [comment]
A lot of those are needed to work around some browser bugs, usually IE ones. In IE accessing some properties has side effects and we need to do that so that IE updates it’s internal state properly.
