### ISSUE TITLE
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

### ISSUE THREAD

**Issue by nicerapp** [jquery/jquery#4862]
### Description ###

I've got an AJAX CMS platform that loads up large batches of javascript per content page.
I now get an error "[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience." for such loading of javascripts on a content page.

Setting async:true in jQuery's evalUrl() does not fix the problem, this results in faulty initialization of the loaded javascripts.

I can't make a minimal testcase for this severe problem because my CMS loads up content from various places.

I can however, point you to my live site, where the problem is clearly demonstrated. For your convenience, i've already modified jQuery's evalUrl() to use async:true

### Link to test case ###

Please click the bottom link ("blogging features") on the front page of https://nicer.app, and see the details in your browser's console.

**Comment by nicerapp** [comment]
i have modified evalUrl() to do the following : 
`jQuery._evalUrl = function( url, options, doc ) {
    $.holdReady( true );
	return jQuery.ajax( {
		url: url,

		// Make this explicit, since user can override this through ajaxSetup (#11264)
		type: "GET",
		dataType: "script",
		cache: true,
		async: true,
		global: false,

		// Only evaluate the response if it is successful (gh-4126)
		// dataFilter is not invoked for failure responses, so using it instead
		// of the default converter is kludgy but it works.
		converters: {
			"text script": function() {}
		},
        success : function (data, ts, xhr) {
            $.holdReady( false );
        },
		dataFilter: function( response ) {
			jQuery.globalEval( response, options, doc );
		}
	} );
};`

**Comment by nicerapp** [comment]
lastly, if you'd test async:false in evalUrl(), then everything works as expected.

now, you have to refresh the page to get it all to work :(

**Comment by mgol** [comment]
This is tracked in #1895. See also #2012 for more context.

**Comment by nicerapp** [comment]
it took a bit of reading, but i think i've found the answer on the pages that mgol pointed me to..

you change jQuery._evalUrl() to use async:true, and crossDomain:true

now my scripts work as expected again. thanks, mgol..
