### ISSUE TITLE
Bug with website, banner appears saying black lives matter is still showing

### ISSUE THREAD

**Issue by Matthew-Bonner** [jquery/jquery#4872]
Donations are clearly being used for fraud...
https://www.msn.com/en-gb/money/other/blm-founder-is-branded-a-fraud-after-buying-a-1-4-million-home/ar-BB1fv0Zw

**Comment by timmywil** [comment]
Thanks for your issue. The banner links to a long list of organizations. There are many to choose from that are doing good work and have nothing to do with the person in the article. Also, the movement is still important even if someone who helped found it does something morally suspect. But it's worth pointing out that the article you linked says that nothing is clear yet. If they did buy a house with donation money, you are right to be outraged, but that doesn't mean everyone should turn their backs on BLM. Regardless, issues related to the website do not go on this repo.
