### ISSUE TITLE
jQuery.each() cannot iterate through objects that contians a key named length.

### ISSUE THREAD

**Issue by timint** [jquery/jquery#4874]
jQuery.each() cannot iterate through objects that contians a key named length.

Identified to this line:

https://github.com/jquery/jquery/blob/a684e6ba836f7c553968d7d026ed7941e1a612d8/src/core.js#L242

Possible fix change to `length = Object.keys(obj).length;`

As mentioned in [StackOverflow](https://stackoverflow.com/questions/67051913/jquery-each-inside-jquery-each-iterator-doesnt-seem-to-work/67051967).

Reproduced by:

```
var json = {"weight":0,"weight_unit":"kg","length":0,"width":0,"height":0,"length_unit":"cm"};
$.each(json, function(key, value) {
  console.log(key, value);
});
```

**Comment by mgol** [comment]
That's by deign. From [the docs for `jQuery.each`](https://api.jquery.com/jQuery.each/):
> Arrays and array-like objects with a length property (such as a function's arguments object) are iterated by numeric index, from 0 to length-1. Other objects are iterated via their named properties.

**Comment by timint** [comment]
Are you telling me it was designed to cause this problem? What's the benefit in that?
I provided a fix, and you choose to keep the problematics. Maybe you can serve some logic because that's not making good sense?

**Comment by mgol** [comment]
If you look at [the docs for `jQuery.each`](https://api.jquery.com/jQuery.each/), it specifies the type of the input as [`ArrayLikeObject`](https://api.jquery.com/Types/#ArrayLikeObject) which is defined as:

> Either a true JavaScript Array or a JavaScript Object that contains a nonnegative integer `length` property and index properties from `0` up to `length - 1`. This latter case includes array-like objects commonly encountered in web-based code such as the `arguments` object and the `NodeList` object returned by many DOM methods.
>
> When a jQuery API accepts either plain Objects or Array-Like objects, a plain Object with a numeric `length` property will trigger the Array-Like behavior.

Your proposed change would break all that usage on array-likes like the `argument` object. Also, try your patch and you'll see it wouldn't even fix your test case as such objects would still be treated as array-likes; you'd just get a bigger length and more `undefined` values logged.

**Comment by timint** [comment]
By array-like objects, do you mean numerical keys/index?

> a plain Object with a numeric length property will trigger the Array-Like behavior.

So if I have a key/argument named length it will use a numerical index? I can't even get the function to iterate the first object:

```
  var json = {"weight":0,"weight_unit":"kg","length":0,"width":0,"height":0,"length_unit":"cm"};
  $.each(json, function(i, value) {
    alert('This part is never reached');
  });

```

Isn't there another way in javascript to count the number of properties inside an array/object without accidentally accessing a property named length?

```
if ("length" in obj) {
  ...
} else {
  length = obj.length;
}
```

**Comment by timint** [comment]
@mgol I compacted it down to the following:

```
    json = {"weight": 0, "length": 0, "width": 0, "height": 0}

    $.each(json, function(key, value) {
      alert('This is never reached');
    });
```

Are you saying this is the intended behavior, that nothing should be iterated?
And why is the behavior different if you set length to e.g. 999?

https://jsfiddle.net/xdabp5o2/

**Comment by mgol** [comment]
Yes, that's intended behavior. In the JS world there are many APIs that don't return arrays but instead array-likes: non-array objects that otherwise behave as arrays. Array-likes have a numerical `length` property and values under numbered indexes. There's no way to see whether a particular object was meant to use as an array-like or as a regular object, we use some heuristics; two of the requirements are having a numerical `length` property and a `length - 1` key present:
https://github.com/jquery/jquery/blob/a70274632dc19ff4a64d7bb7657a2cc647ff38b9/src/core.js#L401-L412

Similar approaches are also used by some other libraries like Lodash, though details may differ.
