### ISSUE TITLE
removeProp() is not removing the property completly if it is a native property like disabeld, checked or selected.

### ISSUE THREAD

**Issue by akshaygao** [jquery/jquery#4887]
### Description ###
Before I explain the issue let me tell you I am clearly aware that jQuery removeProp should be avoided on native properties such as disabled, checked, and selected. https://api.jquery.com/removeProp/

We upgraded the jQuery from 1.12.3 to 3.6.0. We used the JQuery migrate plug-in to identify compatibility issues and fix all the warnings generated in the console.

`$(“#x”).removeProp(“disabled”)` did work in 1.12.3 and stopped working after upgrading to the latest version (3.6.0). But we were not able to identify the issue unless we tested the pages manually. 

we did change the code `$(“#x”).prop(“disabled”, false)` to get it working.

The documentation says  _Do not use this method to remove native properties such as checked, disabled, or selected. This will remove the property completely and, once removed, cannot be added again to the element._  But in my case, it is not even removing the disabled property completely which is the desired use case because we do not want it to be added again to the element. 

`$(“#x”).removeProp(“disabled”)`  from 2.x does nothing. Doesn't remove the property completely nor gives a console error.

I just looked at the implementations in 1.12.x and 3.x. The difference is that 1.x did `this[name] = undefined` before deleting, while 3.x does only `delete this[name]`. 

### Link to test case ###
Working in 1.12.3 
https://jsbin.com/zudasupiqu/edit?html,js,console,output

Not Working in 3.6.0
https://jsbin.com/ligolebevu/edit?html,js,console,output

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by mgol** [comment]
(for reference, the change was done in PR #1227)

**Comment by akshaygao** [comment]
> Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

I have update the test case link for both jquery versions in the issue template

**Comment by akshaygao** [comment]
> (for reference, the change was done in PR #1227)

The simplification was done by combining lines 23 and 26. I am not able to understand how` this[ name ] = undefined;` was simplified there.

**Comment by timmywil** [comment]
I think this is just a docs issue. We should change that to say "This *can* remove the property completely or have no effect at all." I followed the code and it's just calling `delete`, which is the right thing. 1.x used to set properties to `undefined` for old IE, which is no longer necessary and technically invalid.

That said, this is somewhat moot. The reason needs updating, but the recommendation remains valid. There's no reason you should need to remove a native property (nor should you expect that to work–Blink is making it impossible anyway). It's not the same as removing a content attribute, which would actually set the corresponding property to `false`. Setting to `false` is the right thing here.

https://jsbin.com/puzuzos/1/edit?html,js,console,output

**Comment by akshaygao** [comment]
> I think this is just a docs issue. We should change that to say "This _can_ remove the property completely or have no effect at all." I followed the code and it's just calling `delete`, which is the right thing. 1.x used to set properties to `undefined` for old IE, which is no longer necessary and technically invalid.
> 
> That said, this is somewhat moot. The reason needs updating, but the recommendation remains valid. There's no reason you should need to remove a native property (nor should you expect that to work–Blink is making it impossible anyway). It's not the same as removing a content attribute, which would actually set the corresponding property to `false`. Setting to `false` is the right thing here.
> 
> https://jsbin.com/puzuzos/1/edit?html,js,console,output

Would have you any guidelines  to us to identify such wrong usage of jQuery functions  especially when migrating from 1.12.x to 3.x, and JQuery migrate plugin not being able to  provide any console warnings. This one occurrence has made us re-think on the approach of using jQuery migrate plugin to identify compatibility issues. Especially the code written to support old IE which was removed with latest version of jQuery but somehow managed to work in modern browsers though technically invalid.

**Comment by dmethvin** [comment]
> The documentation says Do not use this method to remove native properties such as checked, disabled, or selected. This will remove the property completely and, once removed, cannot be added again to the element. But in my case, it is not even removing the disabled property completely which is the desired use case because we do not want it to be added again to the element.

I think this is still a documentation problem. jQuery docs were trying to be helpful by describing what the browser does, but we don't control that behavior and it isn't specified by any standard. So whatever we say there is out of our control and it seems bad to describe browser behavior that might change. The title of this issue indicates that the documentation seemed to be making a promise that the property would be removed. jQuery can't guarantee that.

> Would you have any guidance to us to identify such wrong usage of jQuery functions especially when migrating from 1.12.x to 3.x, and JQuery migrate plugin not being able to provide any console warnings. This one occurrence has made us re-think on the approach of using jQuery migrate plugin to identify compatibility issues.

jQuery Migrate does not catch every problem, there are several that we can't identify at all, or at least without the risk of false positives. An imperfect tool is better than no tool.

> `$(“#x”).removeProp(“disabled”)` from 2.x does nothing. Doesn't remove the property completely nor gives a console error.

In this case yes, jQuery tries to remove the property on a form input element and the browser makes a decision to ignore that. Note that setting the value to `undefined` is not removing the property, so IMO it was correct to delete that line in #1227. If that element had been a `<div>` for example, the `disabled` property is not special and it would have been deleted.  There are many other things that are special with built-in properties, for example you can set `div.disabled = 5` and it will stay the number `5` but if you set `input.disabled = 5` it is coerced to boolean `true`.

It might be feasible to have a Migrate 1.x shim for `removeProp` that looked at each element, determined whether it had that property natively (by  `createElement` and checking for that property), then warning if there was one. That should give a warning on `$("input").removeProp("disabled")` but not `$("div").removeProp("disabled")`. So give that a try in a PR if you want, keeping in mind it has to work on all the supported browsers. Versions of Migrate past 1.x don't need to check for this since later jQuery code wouldn't have ever used it (since it wouldn't have worked).

**Comment by mgol** [comment]
> It might be feasible to have a Migrate 1.x shim for `removeProp` that looked at each element, determined whether it had that property natively (by `createElement` and checking for that property), then warning if there was one. That should give a warning on `$("input").removeProp("disabled")` but not `$("div").removeProp("disabled")`. So give that a try in a PR if you want, keeping in mind it has to work on all the supported browsers. Versions of Migrate past 1.x don't need to check for this since later jQuery code wouldn't have ever used it (since it wouldn't have worked).

@dmethvin We haven't maintained Migrate 1.x for some time; would you still consider another release?

**Comment by akshaygao** [comment]
> > It might be feasible to have a Migrate 1.x shim for `removeProp` that looked at each element, determined whether it had that property natively (by `createElement` and checking for that property), then warning if there was one. That should give a warning on `$("input").removeProp("disabled")` but not `$("div").removeProp("disabled")`. So give that a try in a PR if you want, keeping in mind it has to work on all the supported browsers. Versions of Migrate past 1.x don't need to check for this since later jQuery code wouldn't have ever used it (since it wouldn't have worked).
> 
> @dmethvin We haven't maintained Migrate 1.x for some time; would you still consider another release?

We haven’t used the 1.x migrate plugin because we were already on the latest 1.x version of jQuery and it was okay to use the 3.x migrate plugin directly.

**Comment by dmethvin** [comment]
@mgol Good point, we haven't made any code changes for almost 5 years so it probably doesn't make sense to do a release for that. Thinking about it now, it seems that it could be done with the latest Migrate version. However, it's not really a jQuery problem as much as a browser problem and so just a few words in the docs are probably enough.

**Comment by bernardcastle402** [comment]
@mgol https://stackdev.space/questions/using-jquery-to-eliminate-an-html-element-based-on-its-attribute
