### ISSUE TITLE
Append code AFTER an element or BEFORE the following element?

### ISSUE THREAD

**Issue by pstein** [jquery/jquery#4890]
Assume I have the following HTML code:

```
<table ... class="foobar">.....</table>
<p>....</p>
```

Now I want to add some text or code AFTER the element or - alternatively - before the following element.

The result should look like

```
<table ... class="foobar">.....</table>
additional text
<p>....</p>

```
How can I achieve this?

The following add the new text INSIDE the <table> element but unfortunately not AFTER

`$(.foobar).append("additional text");`

The following does not insert anything:

`$("additional text").prependTo($(".foobar").next());`

Any other solution?

**Comment by timmywil** [comment]
Thanks for opening an issue. However, this repo is mainly for bug reports. [gitter](https://gitter.im/jquery/jquery) is the right place for support questions. That said, the `append` and `prepend` methods add children to an element. I think [these methods](https://api.jquery.com/category/manipulation/dom-insertion-outside/) would better suit your use case.
