### ISSUE TITLE
on input event goes automatically after comming back to page

### ISSUE THREAD

**Issue by qadenza** [jquery/jquery#4896]
```
<input type='text' class='binp'>

$('.binp').on('input', function(){
    alert('lorem');
});
```

so I type something into .binp and go to another page
then go back using the browser's Go Back (history) button

and the alert lorem appears
and I must click on its OK button multiple times to close the alert

the alert should appear only if I type, or delete, or paste something into the input, and not after coming back to the page

**Comment by mgol** [comment]
The browser is most likely triggering the event by itself so there's not much we can do. Alerting on each `input` occurrence doesn't look like a real use case so it's hard to judge if it's bad from such an example.

In the future, please add a runnable test case as requested in the issue template.

**Comment by THEINSURRECTIONIST** [comment]
i have been working hard on studying xss-injection and how to best manipulate functions and more, if you can give me good repos to look into i would be grateful. ive been following you guys on here and your absolutely brilliant :)
question tho, when checking sites for vulnerabilities and bugs, do you always update the findings here?
