### ISSUE TITLE
undefined variable exception on Firefox within an hidden iframe

### ISSUE THREAD

**Issue by cyrillerougeau** [jquery/jquery#4900]
### Description ###
When using Firefox and Jquery within a hidden iframe, when the computeStyleTests() from the support.js file is triggered, the javascript execution is stopped due to an undefined variable exception.

This is due to the line 
		var divStyle = window.getComputedStyle( div );
which returns a null value on a hidden component in Firefox, leading to the exception on the line after 
		reliableMarginLeftVal = roundPixelMeasures( divStyle.marginLeft ) === 12;

**Comment by timmywil** [comment]
Thanks for opening an issue. We could fix the exception, but CSS methods won't work if gCS returns null.  Last I checked, this was [fixed a while ago in FF](https://github.com/jquery/jquery/issues/3514). I can't imagine you're using FF <62, but I wonder if FF has a regression. But, I did try to put together an example and it seems to work for me with jQuery 3.6.0. https://jsfiddle.net/vbeh72zr/

**Comment by cyrillerougeau** [comment]
Hi Timmywill,
