### ISSUE TITLE
ajaxStop execute after all ajax done callback methods have been executed

### ISSUE THREAD

**Issue by pei-han** [jquery/jquery#4909]

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by mgol** [comment]
Closing for lack of response. If you provide required details, we can reopen.

**Comment by goarblt** [comment]
hello
https://www.evil.com
