### ISSUE TITLE
Css dynamic load

### ISSUE THREAD

**Issue by RobertoMessaBrasil** [jquery/jquery#4917]
An equivalent to getScript to load css dinamically is urgently needed. We have to use workarounds like these

$.ajax({
        url: 'includes/page/message/index.css',
        dataType: 'text',
        success: () => {

            $("head").append("<link>");

            let css = $("head").children(":last");

            css.attr({

                rel: "stylesheet",
                type: "text/css",
                href: 'includes/page/message/index.css'

            });

        }
    });

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by timmywil** [comment]
Thanks for opening an issue. There are so many ways to load CSS dynamically these days, I don't think we need another in jQuery. If nothing else, use native JavaScript.
