### ISSUE TITLE
Event location property

### ISSUE THREAD

**Issue by AndyObtiva** [jquery/jquery#4921]
### Description ###

The jQuery event object provided in `keydown` events is missing the key `location` property that indicates whether the user hit the left (value 1) or right (value 2) shift button for example. 

Below is a test case that demonstrates how it is missing in jQuery but available in vanilla JS usage of events.

As such, it is expected that adding the Event `location` property to jQuery be a minimal change.

Here is more information about the aforementioned key `location` property:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/location

Here is the jQuery Event object API missing the `location` property:

https://api.jquery.com/category/events/event-object/

### Link to test case ###

Run this code and attempt to hit the left shift key and then right shift key. You should get location values 1 and 2 respectively in the "#vanilla-js-div" element but the location will be missing in the "#jquery-div" element.

```html
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $(document).on('keydown', function(event){
    $('#jquery-div').text("Key code: " + event.keyCode + " / location: " + event.location);
  });
  document.addEventListener('keydown', function(event) {
    $('#vanilla-js-div').text("Key code: " + event.keyCode + " / location: " + event.location);
  });
});
</script>
</head>
<body>
<div id="jquery-div"></div>
<div id="vanilla-js-div"></div>
</body>
</html>
```

**Comment by goarblt** [comment]
hello
https://www.evil.com
