### ISSUE TITLE
Some parts of the README require more clarity

### ISSUE THREAD

**Issue by 1407arjun** [jquery/jquery#4928]
### Description ###
1. The tagline in the heading feels incomplete without an article.

2. Grammatically I think that, "jQuery is supported by the following environments and browsers" sounds better than "jQuery supports environments and browsers, etc."

3. A git clone command to the README is missing, adding it might make it easier for the user when cloning the repo.
 
**I would like to make a pull request for addressing these grammatical issues.**

**Comment by mgol** [comment]
See my feedback in #4929; I don't think those changes are right or necessary.

**Comment by goarblt** [comment]
hello
https://www.evil.com
