### ISSUE TITLE
complete callback is not called when 404 Not found error occur

### ISSUE THREAD

**Issue by KES777** [jquery/jquery#4945]
### Description ###
I have $.ajax with next callback set:
```javascript
  let opts = {
    beforeSend : beforeSendAjax,
    success    : successAjax,
    error      : errorAjax,
    complete   : completeAjax,
  };
```

When I do request to page which does not exists I get `404 Not found` and `error` callback is called, but `complete` callback IS NOT called despite on it was documented as should

![image](https://user-images.githubusercontent.com/799021/135720261-c631eae0-301f-497e-8f51-0d5d7d2bb248.png)
my jQuery version is 3.6.0

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by KES777** [comment]
I did not notice that `error` callback was not finished properly, because of error at source code.

`Uncaught ReferenceError: extInfzo is not defined`

After fixing that, every thing working fine. Thank you.

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com
