### ISSUE TITLE
jQuery.attr: Don't stringify values as it breaks Trusted Types

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#4948]
_Originally posted by @koto in https://github.com/jquery/jquery/issues/4409#issuecomment-937872868_

I noticed one violation still in `jQuery.attr`, where the value of the attribute [is stringified](https://github.com/jquery/jquery/blob/de5398a6ad088dc006b46c6a870a2a053f4cd663/src/attributes/attr.js#L53) before calling `setAttribute`:

```
const policy = trustedTypes.createPolicy('a', {createScriptURL: s=>s})
jQuery(aScript, policy.createScriptURL('foo'));

Uncaught TypeError: Failed to execute 'setAttribute' on 'Element': This document requires 'TrustedScriptURL' assignment.
    at attr (jquery.js:6997)
    at access (jquery.js:3467)
    at jQuery.fn.init.attr (jquery.js:6955)
    at <anonymous>:1:6
```
There is a workaround via [`.attr` hooks](https://blog.rodneyrehm.de/archives/11-jQuery-Hooks.html), but it might be worth addressing nonetheless.

It seems like this was introduced in https://github.com/jquery/jquery/commit/ff7576755864193b4c1a00464bf0919bbbe96e8b, I suspect to workaround an [IE <= 9 bug](https://github.com/facebook/react/pull/19588/commits/064319ed217d66b9dd7df70395a9c69292010739), which incorrectly stringified objects passed to `setAttribute`.  

I'm not sure what the most elegant solution would be here, I guess it depends on whether jQuery 4 aims to support IE9. If not, it's safe not to stringify values (browser API would). If yes, then there's only a less-than-ideal option of testing for the bug? IIRC this would be a good test:

```
with (document.createElement('div')) {
  setAttribute('title', {toString:()=>''}); 
  getAttribute('title') === ''
}
```

**Comment by mgol** [comment]
A draft PR: #4949. Setting the attribute now works but the script will still be blocked. This is because in `domManip` scripts are not inserted directly but instead [first disabled](https://github.com/jquery/jquery/blob/de5398a6ad088dc006b46c6a870a2a053f4cd663/src/manipulation.js#L118) and then [their `src` attributes are read and inserted in fresh scripts](https://github.com/jquery/jquery/blob/de5398a6ad088dc006b46c6a870a2a053f4cd663/src/manipulation.js#L156-L159).

There's probably not much we can do when the scripts are deep inside of the inserted HTML string - natively scripts would not fire then but jQuery does execute them which will not work here. However, we could at least make `.append(scriptElem)` work by forking the code path and treating such top-level scripts independently.

I think we could land #4949 as-is, just without the part where it checks if the script was actually invoked and then we can tackle the remaining issue separately.

**Comment by mgol** [comment]
The fix has landed; I extracted the script execution issue to #4963.

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com
