### ISSUE TITLE
responseFields are not included  after a converter throw a error (better error handling, refactor conversion)

### ISSUE THREAD

**Issue by xethub** [jquery/jquery#4953]
responseFields are not included after a converter throw a error

### Description ###
responseFields that matching like on https://github.com/jquery/jquery/blob/a684e6ba836f7c553968d7d026ed7941e1a612d8/src/ajax.js#L212 should even be included if a converter fails

deferred logic is not completed in the converter logic see:
https://github.com/jquery/jquery/blob/a684e6ba836f7c553968d7d026ed7941e1a612d8/src/ajax.js#L272-L279

a finally would not work here too

### Link to test case ###
xhr/ajax/obvious

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com
