### ISSUE TITLE
Script error 3.6.0.min.js 

### ISSUE THREAD

**Issue by amnjazz** [jquery/jquery#4958]
1: object doesn't support property or method 'addEventListener'
2: The value of the property '$' is null or undefined

Here is my development code 

$(document).ready(function()
{
    document.body.onselectstart = function() {return false; }
});
give me you appropriate comments on this issue.

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com
