### ISSUE TITLE
Problem when updated the Jquery to latest version 3.6.0, AngularUI getting distorted.

### ISSUE THREAD

**Issue by TijoAbrahamXerox** [jquery/jquery#4960]
Hi All,

I have a problem with my project, when updating the Jquery libraries to latest version '3.6.0'.
Project is using AngularJS version 1.5.7, when updated the Jquery to latest version 3.6.0, AngularUI getting distorted.
Mainly Angular Grid showing issue. And it is working fine upto JQuery 3.4.1 versions, above this version showing issues(3.5.. & 3.6..).
I need to specifically use 3.5.. OR 3.6.0 to get the cross-site vulnerability issue fix on JQuery.

Could anybody please help me to resolve this issue?

Thanks in advance!

**Comment by mgol** [comment]
Closing for lack of response. If you provide required details, we can reopen.

**Comment by goarblt** [comment]
hello
https://www.evil.com
