### ISSUE TITLE
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

### ISSUE THREAD

**Issue by tukusejssirs** [jquery/jquery#4965]
### Description ###

Firefox (at least FF Nightly 96.0a1) logs the following warning:

```js
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.
```

Is there a way to use only _standard_ properties? Thanks.

**Comment by mgol** [comment]
We can't do much without a test case. But it looks like something you'd see only in jQuery 1.x that has been long unsupported.
