### ISSUE TITLE
jQuery triggering ESLint/security errors due to no-html-method

### ISSUE THREAD

**Issue by jennjxf** [jquery/jquery#4967]
### Description ###
jQuery triggering ESlint/security errors because it still uses html() method, and should use "document.createElement()" (or similar) instead.

jQuery version: 3.6.0

**Comment by mgol** [comment]
jQuery is wrapping a lot of DOM APIs so it’s natural & necessary it supports setting `innerHTML`. Nothing forces you to use the `html` method.

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com
