### ISSUE TITLE
jQuery ":even" & ":odd" filters are wrong since decades.

### ISSUE THREAD

**Issue by samarpw** [jquery/jquery#4969]
I got surprised that no one observed/countered/addressed this apparently simple bug.
<ul>
	<li>1</li>
	<li>2</li>
	<li>3</li>
	<li>4</li>
	<li>5</li>
</ul>
`
$('ul li:odd');  //it selects 2 and 4 li, which is wrong. It should select 1, 3, 5.

$('ul li:even');  //it selects 1, 3 and 5 li, which is also wrong. It should select 2, 4.
`

**Comment by dmethvin** [comment]
Items are numbered from `0` as documented since decades. https://api.jquery.com/even/

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com
