### ISSUE TITLE
Heap memory increasing issue..

### ISSUE THREAD

**Issue by jayanth558** [jquery/jquery#4970]
Recently we updated jQuery version 1 to version 3, suddenly we r getting heap memory exceeded errorr.

**Comment by jayanth558** [comment]
https://songslyrics.club/

**Comment by timmywil** [comment]
Thanks for opening an issue, but is more of a support request than a bug report. Best place to find support is on https://stackoverflow.com. If you can reproduce the issue in a small example on https://jsfiddle.net, we can take a look.

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com
