### ISSUE TITLE
Event triggering does not call native event handlers

### ISSUE THREAD

**Issue by mildred** [jquery/jquery#4975]
I was debugging an issue with https://github.com/davidstutz/bootstrap-multiselect and I was wondering why I could not catch the change event from this library. The problem lies in that bootstrap-multiselect is using jQuery to trigger the change event and it will not trigger the native event handlers:

https://github.com/jquery/jquery/blob/9bdb16cd19097da67950a707baac3980bda873f3/src/event/trigger.js#L108-L116

In this code, you look for an event handler using the `onEVENTNAME` property, but all the event handlers installed using `addEventListener` will not be triggered.

It goes right through.

**Comment by mgol** [comment]
Thanks for the report. This is an expected limitation of the jQuery event system, see the following comment for more details: https://github.com/jquery/jquery/issues/4815#issuecomment-736855180.

**Comment by goarblt** [comment]
hello
https://www.evil.com
