### ISSUE TITLE
Illegal DN in the source code

### ISSUE THREAD

**Issue by aleen42** [jquery/jquery#4980]
Recently, `blindsignals.com` has been found in the source code of jQuery, and it has not been trusted anymore when someone buys it for illegal purposes. Please remove them.

https://github.com/jquery/jquery/search?q=blindsignals

**Comment by mgol** [comment]
#4981 has more info so let's track it there

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com
