### ISSUE TITLE
src/intro.js is incomplete

### ISSUE THREAD

**Issue by cjlebel** [jquery/jquery#4982]
https://github.com/jquery/jquery/blob/acb7c49c8d42f601fa347661b1118959079f6b52/src/intro.js#L44

The end of the file is not completed, and is left with an open curly bracket

`// Pass this if window is not defined yet
}(typeof window !== "undefined" ? window : this, function( window, noGlobal ) {

// Support: Firefox 18+
// Can't be in strict mode, several libs including ASP.NET trace
// the stack via arguments.caller.callee and Firefox dies if
// you try to trace through "use strict" call chains. (#13335)
//"use strict";
`

**Comment by mgol** [comment]
This file is concatenated during the build process with the rest, it's not meant to be used on its own. Also, it's no longer used in jQuery 3.x and we don't maintain older versions anymore.

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com
