### ISSUE TITLE
Inexplicable "Access to XMLHttpRequest at ... from origin ... blocked by CORS policy" exception

### ISSUE THREAD

**Issue by Danny8bit** [jquery/jquery#5012]
### Description ###

On BitChute.com, where I've been volunteering as a coder for a couple years, we're experiencing a long standing issue with our jQuery Ajax (type: "post") call, where occasionally I get the "blocked by CORS policy" error posting longer comments, for example, which you can try on my video: https://www.bitchute.com/video/Ttv4AEfC1li3/

> Aaa aaa aaaaaa aaaaaaa aaaaaaaaaaaaa aaa aa aaaaa aaa, aaa aa aaa "Aaaaaaa" aaaaaaaa, aaaa aaa aaaaa aaa aaaaaa aaaaa, aaaa aa aaaaaa aaaaaaaa aaaaaaa, aaa aa aaa aaa aaa aaaaaaa aaaaaa aaa aaa aaaaaaa, aaaaa a aaaaaa aa aaa, aaa aaaaaa aaa aaa aaaaa aaaa Aaaaaaa aaaaaa aaaa aaaaa aaa aaaaaaaa, aaaa aaa aaaaaa aa aaaaaa aaaaaaa aaaaaaaa aa aaa aaaaa aaaa aaaa.
>
> Once you have enabled them, you will never have to manually refresh the page again (unless you are on a BitChute video, and your computer goes offline for over five minutes, e.g. you put your laptop to sleep on battery power), where changes to the comments will "automatically" appear, and for the Popular sort order, the order of the comments is maintained too!
>
> Enjoy, and if you are still having trouble, please let me know.

You'll note I attempted to use an RE to encode my actual example comment, but somewhat surprisingly, it's _very_ sensitive to even direct character replacements, where any further encoding of the characters avoids the error, i.e. I can't simplify the example comment any further.

You may note we're using an older version of jQuery on the site, which I thought was the issue, however, I was surprised to discover that the latest version, as indicated by _jQuery().jquery_, with a Chrome override (come on Firefox, get your act together! 😉), exhibits the same error, as with the following exception log, using the uncompressed jQuery source file (ignore jquery.min, where that's just because I'm overriding the site's minified file):

> Access to XMLHttpRequest at 'https://commentfreely.bitchute.com/api/update_comment/' from origin 'https://www.bitchute.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> jquery.min.js:10109          POST https://commentfreely.bitchute.com/api/update_comment/ net::ERR_FAILED 403
> send @ jquery.min.js:10109
> ajax @ jquery.min.js:9690
> putComment @ commentactions.js:46
> putComment @ comments.js:8
> proxy @ jquery.min.js:10780
> dispatch @ jquery.min.js:5430
> elemData.handle @ jquery.min.js:5234

**Comment by timmywil** [comment]
There's not much to go on here, but it doesn't look like this is a bug in jQuery. You might have better luck on stackoverflow.com.

**Comment by Danny8bit** [comment]
> There's not much to go on here, but it doesn't look like this is a bug in jQuery. You might have better luck on stackoverflow.com.

Was you at least able to recreate the exception?

**Comment by timmywil** [comment]
We usually require reduced test cases, showing a specific issue. A full website is just too much to sift through. This is more of a support request, which means it needs to be fleshed out more, and stackoverflow can be very helpful with that.

**Comment by Danny8bit** [comment]
I appreciate the response. What I did in the end was do a binary comparison of the main option data structure, between a unsuccessful and successful call, and I found, as you suggested, there was nothing untoward being passed to the BItChute server (only differences were essentially in a couple date values), so it does indeed appear to be a freaky issue on our end, which is being investigated.
