### ISSUE TITLE
Mouseup event doesn't fire when dragging starts from the top of another element

### ISSUE THREAD

**Issue by ecations** [jquery/jquery#5014]
### Description ###
I have a page with two divs. The second one has a "mouseup" event listener. The event listener stops working when the mouse button goes down on top of the first div, but only after the second time. This seems to happen in Chrome and Brave, but not in Firefox.

Expected behavior: The mouseup event always fires when the mouse is over the second div, regardless of where the dragging starts.

### Link to test case ###

https://codepen.io/noip/pen/VwrrLoL?editors=1111

**Comment by dmethvin** [comment]
Does the native mouseup behave the same way? From a quick test here it looks like it does, but it's probably better for you to write a test since you know what you're looking for. If the native event doesn't fire, ours won't either since we're just passing it through.

**Comment by ecations** [comment]
@dmethvin Could it be related to this?
https://stackoverflow.com/questions/41181372/chrome-mousedown-and-mouseup-events-no-longer-working-other-browsers-are-fine

Seems like Chromium has switched to pointer events from version 55 and up. I quick look at the jQuery source makes it seem like jQuery is still using the old mouse events. This would explain the issue.

**Comment by mgol** [comment]
That answer is definitely wrong. Chrome would never be able to just remove support for those events, this would break a huge amount of websites.

jQuery is not "using the old mouse events", it just uses the events that are requested from jQuery by the developer calling its APIs.

**Comment by ecations** [comment]
I don't mean that they removed support completely. I just suspect that this bug/behavior might be related to that decision the Chrome developers made, especially since the mouseup problem seems to happen only with Chrome and Brave (both Chromium based) and not with Firefox.

**Comment by ecations** [comment]
Thanks for the clarification! I didn't realize that I can use .on() for also pointerup.

I now did a vanilla js version of this and can indeed verify that this problem exists also with that:
https://codepen.io/noip/pen/BammGdw?editors=1111

I'm really surprised I haven't found any widespread discussion about this since it seems to me that detecting mouseup/pointerup events has become really unrealiable in Chromium based browsers. Just test for yourself by going to that codepen and dragging down from the upper div to the bottom div. You will have a console log message, then it stops working until you click on the cube, then you can get another console log.

**Comment by ecations** [comment]
Closing this now as it's not jQuery-related. What helped was adding the css-rule user-select: none; to the upper div.

**Comment by dmethvin** [comment]
One clue that I did notice is that Chrome gave the 🚫 ("you can't drag this") cursor the second time I did the mousedown-drag-mouseup. If Chrome thought an invalid drag operation was going on, it might not be generating mousedown/up events during that.
