### ISSUE TITLE
A little suggestion on error reporting

### ISSUE THREAD

**Issue by kaikaibenkai** [jquery/jquery#5031]
When using some functions of jQuery (such as "load"), errors (such as "the server responded with a status of 404") always **directly output error information to the console**.
But sometimes, you need to catch these errors. Because they are directly output to console, you can't use _"try...catch"_ block.
In future versions of jQuery, I hope to change _"output error message directly"_ to **_"throw exception"_** to execute different code.

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by kaikaibenkai** [comment]
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="description" content="For https://github.com/jquery/jquery/issues/5031">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>JS Bin</title>
    <script>
      //Connections sometimes time out or are considered malicious requests, and I need to capture them.
      //The current method is to send a request first and judge whether the request response is "200 OK", but this method often misjudges.
      ($("header")[0]).load("https://cdn.example.com/page/www/header");
      ($("body")[0]).load("https://cdn.example.com/page/www/footer");
    </script>
  </head>
  <body>
    <div id="app">
      <header><!-- Load header here --></header>
      <main>
        <p>Hello, world!</p>
        <!-- Write content here -->
      </main>
      <footer><!-- Load footer here --></footer>
    </div>
  </body>
</html>
```

**Comment by mgol** [comment]
404 errors are not logged by jQuery but by the browser. To my knowledge, there's no way to get rid of them, even if you attach an error handler.

As for handling errors, please read the docs for [`load()`](https://api.jquery.com/load/), they explain how to do it.

Closing since there's nothing actionable here.
