### ISSUE TITLE
The `focusin` does not work correctly inside the ShadowDom element

### ISSUE THREAD

**Issue by AlexKamaev** [jquery/jquery#5053]
## What do you expect to happen?

**jQuery version is 3.6.0.**

All buttons are inside ShadowDOM.
The `focusin` event handler should be called as expected when the handler is attached with jQuery.
See the following code:
```JS
// This does not work
$(btnJQuery).focusin(event => {
    event.target.style.outline = '5px solid red';
});
```

```JS
// However, this works
btnNative.addEventListener('focusin', event => {
    event.target.style.outline = '5px solid red';
});
```

###  What actually happens?
The `focusin` handler is not called if it's attached using jQuery.
###  Which browsers are affected?

Chrome

### Description ###

The `focusin` event handler is not called on ShadowDOM button element, if the handler is attached using jQuery. However, it is called if is attached without jQuery,

### Link to test case ###
Please refer to the following link to get full working example:
https://output.jsbin.com/cihiwigeli/1

Navigate between buttons using the `tab` key of just click on buttons.
The `jQuery` button will not have a red border as expected

**Comment by mgol** [comment]
Thanks for the report. This looks fixed in jQuery 4.0.0-pre:
https://output.jsbin.com/tefihev/1
but still broken on the `3.x-stable` branch:
https://output.jsbin.com/vawezif/1

**Comment by mgol** [comment]
We've removed a `focusin` polyfill on the `master` branch in #4362 which may be why it works in `4.0.0-pre`. I'm not sure if we can fix it on the `3.x-stable` branch that easily, PRs welcome if someone has an idea.

**Comment by timmywil** [comment]
Agreed. Now that IE is officially dead, we'll be focusing more on getting 4.0.0 released and less on fixing things in 3.x, but if someone wants to put together a patch, we'll happily consider it. Closing as patch welcome.
