### ISSUE TITLE
Connection refused to code.jquery.com

### ISSUE THREAD

**Issue by a-random-lemurian** [jquery/jquery#5055]
### Description ###
I cannot connect to `code.jquery.com`. It refuses my connection. Not sure how I would contact jquery, so I decided to ask here.

`curl: (7) Failed to connect to code.jquery.com port 443: Connection refused`

Why can't I connect to jquery?

It's also worth noting that I can connect to `jquery.com`, but not `code.jquery.com` (notice it says `code.`).

**Comment by kuohuanhuan** [comment]
hmm... Works on my side
Check your proxy settings?
Or try the Google Hosted Libraries:
```html
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> 
```

**Comment by a-random-lemurian** [comment]
> hmm... Works on my side (Arch Linux 5.18.2-arch1-1). Check your proxy settings may fix your issue. Or try the Google Hosted Libraries:
> 
> ```
> <script src="//ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> 
> ```

Unfortunately, the error happens on a website that I cannot control or modify, and it breaks the whole thing. By the way I am on Ubuntu 20.04. I've tried redirecting `code.jquery.com` to localhost in /etc/hosts but the website uses https, not http. The /etc/hosts workaround doesn't work on https only http.

As of June 11 8:46 PM UTC+8 I seem to be able to connect to the http site but I still get connections to the https site refused.

**Comment by kuohuanhuan** [comment]
I think it may be a DNS server issue...
Try set your DNS server to another one (instead of the default one).
e.g. `8.8.8.8` from Google or `1.1.1.1` from Cloudflare.

**Comment by a-random-lemurian** [comment]
> I think it may be a DNS server-side issue... Try set your DNS server to another one (instead of the default one). e.g. `8.8.8.8` from Google or `1.1.1.1` from Cloudflare.

Nope, does nothing. I tried the Cloudflare and Google DNS, still get connection refused.

**Comment by kuohuanhuan** [comment]
Hmm... Strange.
Some solutions I can provide is:
- Check firewall
- Clear cookie(s)

**Comment by a-random-lemurian** [comment]
> Hmm... Strange. Some solutions I can provide is:
> 
>     * Check firewall
> 
>     * Clear cookie(s)

Not sure how clearing cookies will help, I'm trying to access it via curl. But again, a game I want to play is trying to load jquery.

I'm also not sure if there's even a firewall running on my machine.

**Comment by a-random-lemurian** [comment]
P.S. here's the output of my attempt to `curl https://code.jquery.com/jquery-3.3.1.min.js -v`.

```
*   Trying 69.16.175.42:443...
* TCP_NODELAY set
* connect to 69.16.175.42 port 443 failed: Connection refused
*   Trying 69.16.175.10:443...
* TCP_NODELAY set
* connect to 69.16.175.10 port 443 failed: Connection refused
*   Trying 2001:4de0:ac18::1:a:3b:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:3b: Network is unreachable
*   Trying 2001:4de0:ac18::1:a:2a:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:2a: Network is unreachable
*   Trying 2001:4de0:ac18::1:a:1b:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:1b: Network is unreachable
*   Trying 2001:4de0:ac18::1:a:2b:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:2b: Network is unreachable
*   Trying 2001:4de0:ac18::1:a:1a:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:1a: Network is unreachable
*   Trying 2001:4de0:ac18::1:a:3a:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:3a: Network is unreachable
*   Trying 2001:4de0:ac18::1:a:3b:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:3b: Network is unreachable
*   Trying 2001:4de0:ac18::1:a:2a:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:2a: Network is unreachable
*   Trying 2001:4de0:ac18::1:a:1b:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:1b: Network is unreachable
*   Trying 2001:4de0:ac18::1:a:2b:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:2b: Network is unreachable
*   Trying 2001:4de0:ac18::1:a:1a:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:1a: Network is unreachable
*   Trying 2001:4de0:ac18::1:a:3a:443...
* TCP_NODELAY set
* Immediate connect fail for 2001:4de0:ac18::1:a:3a: Network is unreachable
* Failed to connect to code.jquery.com port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to code.jquery.com port 443: Connection refused
```

**Comment by kuohuanhuan** [comment]
On my side I got
```
*   Trying 69.16.175.42:443...
* Connected to code.jquery.com (69.16.175.42) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.jquery.com
*  start date: Jul 14 00:00:00 2021 GMT
*  expire date: Aug 14 23:59:59 2022 GMT
*  subjectAltName: host "code.jquery.com" matched cert's "*.jquery.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /jquery-3.3.1.min.js]
* h2h3 [:scheme: https]
* h2h3 [:authority: code.jquery.com]
* h2h3 [user-agent: curl/7.83.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x55a943ba4d70)
> GET /jquery-3.3.1.min.js HTTP/2
> Host: code.jquery.com
> user-agent: curl/7.83.1
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200 
< date: Sat, 11 Jun 2022 13:39:42 GMT
< content-length: 86927
< content-type: application/javascript; charset=utf-8
< last-modified: Fri, 20 Aug 2021 17:47:53 GMT
< accept-ranges: bytes
< server: nginx
< etag: W/"611feac9-1538f"
< cache-control: max-age=315360000
< cache-control: public
< access-control-allow-origin: *
< vary: Accept-Encoding
< x-hw: 1654954782.dop212.la3.t,1654954782.cds222.la3.hn,1654954782.cds106.la3.c
< 
/*! jQuery v3.3.1 | (c) JS Foundation and other contributors | jquery.org/license */
[CODE]
```

**Comment by kuohuanhuan** [comment]
Seems like the DNS resolving works correct, but error establishing a connection,

**Comment by dmethvin** [comment]
>The worst reason is that the site is unavailable on your network environment....

That is the most likely case. https://downforeveryoneorjustme.com/code.jquery.com

Your local network administrator may have blocked it in error. Try connecting from some other location and network entirely that is still in your area, such as a coffee shop. 

In some countries, the country firewall may be blocking it. What country are you in? Are there others nearby who are experiencing the same problem? If theirs works, are they resolving to the same IP?

**Comment by a-random-lemurian** [comment]
> > The worst reason is that the site is unavailable on your network environment....
> 
> That is the most likely case. https://downforeveryoneorjustme.com/code.jquery.com
> 
> Your local network administrator may have blocked it in error. Try connecting from some other location and network entirely that is still in your area, such as a coffee shop.
> 
> In some countries, the country firewall may be blocking it. What country are you in? Are there others nearby who are experiencing the same problem? If theirs works, are they resolving to the same IP?

I'm not on a company or school network. I'm on my home network and I am in the Philippines.

**Comment by kuohuanhuan** [comment]
Maybe try using a VPN service?

**Comment by a-random-lemurian** [comment]
> Maybe try using a VPN service?

I don't have a VPN subscription.

**Comment by kuohuanhuan** [comment]
> I don't have a VPN subscription.

Try [Proton VPN](https://protonvpn.com), it's free.

**Comment by RummanUK** [comment]
Proton VPN doesnt work properly, always getting server error!

**Comment by kuohuanhuan** [comment]
> Proton VPN doesnt work properly, always getting server error!

Then NordVPN or Surfahark are also some options. (30-day Trial)

**Comment by a-random-lemurian** [comment]
jQuery works for me now, it actually started working like 20 days ago so I'm gonna close this now
