### ISSUE TITLE
Cannot access a real data set again?

### ISSUE THREAD

**Issue by aleen42** [jquery/jquery#5072]
### Description ###

Recently I have found that when accessing the data set of a jQuery object, we can't get the real one after accessing it again.

### Test case ###

```js
($x => { $x.data(); $x.attr('data-x', 1); return $x.data(); })($('<div>')); // => {}, rather than {x: 1}
```

**Comment by dmethvin** [comment]
That is the way it's documented to work. Setting the attribute after data has been fetched. doesn't have any effect on the data object.

> Since jQuery 1.4.3, [data-* attributes](https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes) are used to initialize jQuery data. An element's data-* attributes are retrieved the first time the data() method is invoked upon it, and then are no longer accessed or mutated (all values are stored internally by jQuery).

https://api.jquery.com/data/#data-html5
