### ISSUE TITLE
Event "load" fires before or after event "ready". This is a little confusing.

### ISSUE THREAD

**Issue by Daijobou** [jquery/jquery#5075]
See this short example:
```
<script>
$(function() { console.log("Dom loaded"); });
$(window).on('load', function() { console.log("Window loaded"); });
</script>
```
You think "Dom loaded" coming always first? It does not. However, most people think it is. I learned from jquery doc https://api.jquery.com/load-event/
![image](https://user-images.githubusercontent.com/260343/180220640-a7719b77-b848-4528-8862-d2d83d76974b.png)
and overall on every tutorial about jQuery that window event "load" is **fired as last**, when all images loaded and Dom is ready.

Yes, the event "load" is called correctly when everything is ready. But it happens often enough that this event "load" is called before "ready". Probably because the graphics are already cached in the browser cache, that can lead to crazy results. Everyone assumes that this event will be executed **at the end**, always after event "ready".

Here should either:

A) the documentation in jQuery should be clearer, that "load" can also be called before "ready", because everything was already loaded, because it was in the browser cache or there were no elements to load.

or/and

B) it would make more sense (for me) to explicitly specify here or that I can say that events "load" should always be executed after all events "ready".

Currently on my project is one time event "ready" fired first, next page refresh its first event "load".

Someone mention this issue years ago on stackoverflow and the last answer after "UPDATE" is interesting https://stackoverflow.com/a/65898996/706420

**Comment by dmethvin** [comment]
Here is the current doc for `.ready()`:

https://api.jquery.com/ready/#ready-handler

There is a sentence in the docs:

>  Although handlers added by .ready() will always be executed in a dynamically loaded script, the window's load event has already occurred and those listeners will never run.

Perhaps this is clearer?

>  Although handlers added by .ready() will always be executed when they are attached, the window's load event may have already occurred so listeners attached after that will never run.

Or perhaps, something like:

> Handlers attached by `.ready()` may be called after handlers attached to a `load` event in some cases, and handlers attached to a `load` event will _never_ be called if they are attached after the page has already loaded. Code should not assume they fire in a specific order.

A more extensive rewrite might help, but IMO there are already more words in that description than most people can bear to read. You can make a pull request at https://github.com/jquery/api.jquery.com/ .

**Comment by mgol** [comment]
Closing as answered.
