### ISSUE TITLE
Google hosted jquery showing multiple errors in Chrome Developer tools Lighthouse Analysis 

### ISSUE THREAD

**Issue by jaredzimmerman** [jquery/jquery#5082]
### Description ###

Error: Syntax error, unrecognized expression: [tabat =] at se.error (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:13639) at se.tokenize (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:21650) at se.select (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:22477) at Function.se [as find] (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:7116) at S.fn.init.find (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:25047) at new S.fn.init (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:25536) at S (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:1051) at HTMLDocument.<anonymous> (https://www.jaredzimmerman.com/js/responsiveTabs.js:1:1304) at e (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:30038) at t (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:30340)

### Link to test case ###
https://jaredzimmerman.com - Site minified via cloudflare

**Comment by ThakurAnkur** [comment]
Not a jQuery bug. Have a look at code present in https://www.jaredzimmerman.com/js/responsiveTabs.js:1:1304, some variable is undefined which is resulting invalid selector.

**Comment by mgol** [comment]
Yes, this is an error cause by an invalid selector.
