### ISSUE TITLE
:is:contains throw error unsupported pseudo: is

### ISSUE THREAD

**Issue by amiad** [jquery/jquery#5083]
### Description ###
If I use selector `:is` with selector `contains` I get error:
`Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: is`

I checked it on Firefox and Chrome.

example: `$(':is(h2):contains(a)')`

### Link to test case ###
https://codepen.io/amiadb/pen/qBooYzm

**Comment by dmethvin** [comment]
jQuery tries to use the browser's native selector engine first. The browsers support `:is()` but not `:contains()` so they throw an error. jQuery then passes the selector to Sizzle which doesn't support `:is()` but does support `:contains()` so it throws the error you see there.

Also note that the string you are looking for in `:contains()` should be _quoted_.

As long as the entire selector can be parsed by either the browser or jQuery this will work. for example, try `$(':is(h2)').filter(':contains("a")').css('color', 'red');` The first selector is parsed by the browser, and the second by jQuery.
