### ISSUE TITLE
.css("--custom") throws TypeError: ret is undefined (3.6.0 → 3.6.1 regression)

### ISSUE THREAD

**Issue by andersk** [jquery/jquery#5105]
### Description ###

In jQuery 3.6.0, `$element.css("--custom")` correctly returned `undefined` for a custom property that isn’t set. But in jQuery 3.6.1, it crashes with `TypeError: ret is undefined`.

This breaks the Zulip settings dialog.

This was presumably introduced by #4930 (cc @fecore1 @mgol).

### Link to test case ###

https://codepen.io/anderskaseorg/pen/rNvNZWW

**Comment by mgol** [comment]
Thanks for the report. That said, I'm not sure the `undefined` return value was correct either. We are using `.getPropertyValue()` for custom property values and it returns an empty string for unknown CSS custom properties. We just then fallback to `computed[ value ]` which will be undefined. The logic is at:
https://github.com/jquery/jquery/blob/3.6.1/src/css/curCSS.js#L31

That said, for regular unknown properties that is the logic we are using. I guess we should discuss what's our goal here.

**Comment by andersk** [comment]
Yeah, jQuery has given `undefined` here for standard properties since 1.8.0, and for custom properties since they were first supported in 3.2.0. “Correct” or not, it seems to me that a patch release isn’t a good time to break this compatibility.

**Comment by mgol** [comment]
I agree with that but there’s also a case with a custom property set to an empty string or a whitespace-only string. IMO then we should return an empty string, not undefined. I’ll need to check if this is possible with the Web APIs we have.

**Comment by mgol** [comment]
Fix landed on `main` in ed306c0261ab63746040e5d58bb4477c3069a427 and on `3.x-stable` in c0db6d70320ad6fb29a6a89aae3811a81b5adedf.
