### ISSUE TITLE
Selector :has with :checkbox:checked is behaving inconsistent. It works fine when there are multiple records but not when there is only one record in the kendo grid 

### ISSUE THREAD

**Issue by praveenkra** [jquery/jquery#5124]

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by mgol** [comment]
Closing for lack of response. We can reopen if you provide required details.
