### ISSUE TITLE
Generic Object Injection Sink

### ISSUE THREAD

**Issue by clajara-pro-tel** [jquery/jquery#5127]
### Description ###

Bracket object notation with user input is present, this might allow an attacker to access all properties of the object and even it's prototype, leading to possible code execution.

        
      Severity: critical

        
      Confidence: unknown

        
      Location: [classes/dependencies/jquery_mobile/jquery.mobile-1.4.5.js:6533](https://github.com/enterprise/pro-tel/protelnet-source-2019/-/blob/master/classes/dependencies/jquery_mobile/jquery.mobile-1.4.5.js:6533)

Identifiers:

        
      [ESLint rule ID security/detect-object-injection](https://github.com/nodesecurity/eslint-plugin-security#detect-object-injection)

        
      [CWE-94](https://cwe.mitre.org/data/definitions/94.html)

Scanner:

        
      Name: ESLint

        
      Type: sast

        
      Status: success

        
      Start Time: 2022-09-26T00:44:58

        
      End Time: 2022-09-26T00:45:52

**Comment by mgol** [comment]
This is a repository for jQuery, not [jQuery Mobile](https://github.com/jquery-archive/jquery-mobile).

Note: jQuery Mobile is not maintained anymore. Please read [the project status blog post](https://blog.jquerymobile.com/2021/10/07/jquery-maintainers-continue-modernization-initiative-with-deprecation-of-jquery-mobile/) for more information.
