### ISSUE TITLE
Investigate vulnerability: Found fs.open with non literal argument at index 0

### ISSUE THREAD

**Issue by clajara-pro-tel** [jquery/jquery#5128]
### Description ###
A variable is present in the filename argument of fs calls, this might allow an attacker to access anything on your system.

        
      Severity: high

        
      Confidence: unknown

        
      Location: [classes/dependencies/jquery/jquery-3.6.1.js:10023](https://github.com/enterprise/pro-tel/protelnet-source-2019/-/blob/master/classes/dependencies/jquery/jquery-3.6.1.js:10023)

Identifiers:

        
      [ESLint rule ID security/detect-non-literal-fs-filename](https://github.com/nodesecurity/eslint-plugin-security#detect-non-literal-fs-filename)

        
      [CWE-22](https://cwe.mitre.org/data/definitions/22.html)

Scanner:

        
      Name: ESLint

        
      Type: sast

        
      Status: success

        
      Start Time: 2022-09-27T20:41:58

        
      End Time: 2022-09-27T20:43:45

**Comment by mgol** [comment]
There’s no `fs` usage in the linked filed. The listing error message is incorrect.
