### ISSUE TITLE
Lines 1384, 1419, 1438   SyntaxError

### ISSUE THREAD

**Issue by uniuuu** [jquery/jquery#5143]
### Description ###

How to reproduce:
Run Web Developer Tools in Firefox. Open Debugger and set breakpoints: Pause on exceptions; Pause on caught exceptoons.
![image](https://user-images.githubusercontent.com/26146469/196779096-3f6737b3-a0d7-419c-9704-1fcaac1bdc64.png)
Load jquery-3.6.1.js and start debugging.

![Exceptions](https://user-images.githubusercontent.com/26146469/196777948-d7c46fe2-b8b0-4fad-b85a-2565dadd156a.gif)

There are exceptions:
Line 1384 SyntaxError: `Element.querySelectorAll: '\' is not a valid selector`
Line 1419 SyntaxError: `Element.querySelectorAll: '*,:x' is not a valid selector`
Line 1438 SyntaxError: `Element.querySelectorAll: '[s!='']:x' is not a valid selector`

**Comment by mgol** [comment]
These are caught exceptions, they don't have any effect on the running app. Those are Sizzle support tests and it's expected some of them will throw.
