### ISSUE TITLE
Trusted Type Violation. Line 133

### ISSUE THREAD

**Issue by uniuuu** [jquery/jquery#5144]
### Description ###
Proposal to add TrustedScript  [MDN](https://developer.mozilla.org/en-US/docs/Web/API/TrustedScript)

Currently line 133 fails:

![image](https://user-images.githubusercontent.com/26146469/196788804-1deeb5ff-501d-4436-9b68-fe04c54b2f0b.png)

More on the topic: [Prevent DOM-based cross-site scripting vulnerabilities with Trusted Types](https://web.dev/trusted-types/)

**Comment by mgol** [comment]
jQuery 3.x is not adjusted for Trusted Types. We did some work to increase compatibility in #4409 & #4948; this will only land in jQuery 4.0.0. Note that scripts appended this way are still not running; they will never fully be but we're investigating some basic support in #4963.

I think that's all so I'll close this issue. If you think there's something else that hasn't been covered, please comment here and we'll reopen. Please provide a test case then, though, just a one-line summary & a screenshot of an error doesn't provide us a lot to work with.
