### ISSUE TITLE
Could a way to find an element with the exact text be added?

### ISSUE THREAD

**Issue by jgfmachado** [jquery/jquery#5145]
Pretty much as the title says, is there any chance that a way to find an element with the exact given text, instead of just containing it, be added to the project?

**Comment by timmywil** [comment]
Thanks for opening an issue. We would prefer not to add more selector extensions. This can be accomplished currently by adding a custom selector or by filtering after the selection.

**Comment by Krinkle** [comment]
**Beware:** This is an inherently slow approach and would not be advisable in important production contexts or contexts where the first selector (e.g. `div.example` or `h3` or `*`) has many thousands of matches. Having said that, it work for finding one of a small number of elements or for quick demos.

```js
$('div.example')
  .filter(function (i, element) { return element.textContent === 'Hello world'; })
  .addClass('example-found');
```

Example on https://jquery.com:
```js
$('h3')
  .filter(function (i, element) { return element.textContent === 'Cross-Browser'; })
  .css({color: 'red'});
```

<img width="747" alt="Screenshot 2022-10-24 at 17 12 54" src="https://user-images.githubusercontent.com/156867/197574416-c67c4f58-9a65-4b87-9358-c25fd6760505.png">
