### ISSUE TITLE
Safari 16 crashes on in-template DOM manipulation

### ISSUE THREAD

**Issue by jded76** [jquery/jquery#5147]
### Description ###
After the new IOS 16, Safari changed the behavior of  `document.adoptNode` when called on a template. It's not changing the ownerDocument any more. It leaves this on an empty document (about:blank).

This causing an error at the function contains at this [line](https://github.com/jquery/jquery/blob/d0ce00cdfa680f1f0c38460bc51ea14079ae8b07/src/selector/contains.js#L5), because the documentElement property is null on an empty document (about:blank).

If you change this [line](https://github.com/jquery/jquery/blob/d0ce00cdfa680f1f0c38460bc51ea14079ae8b07/src/selector/contains.js#L5) from
`var adown = a.nodeType === 9 ? a.documentElement : a, bup = b && b.parentNode;`
to
`var adown = a.nodeType === 9 && a.documentElement ? a.documentElement : a, bup = b && b.parentNode;`
it's working again.

More details can be found [here ](https://discourse.aurelia.io/t/any-issues-with-safari-16-0/4923/9) and aurelia/framework#1003.

### Link to test case ###
You can see the problem [in this fiddler](https://jsfiddle.net/oxn8t2uh/) if you try it with Safari 16+.
If you press "add" and then "remove" you get the error.

**Comment by jded76** [comment]
I made a [repository](https://github.com/jded76/Safari16-vanilla-js) if you like to test it without fiddler.

If you change this [line ](https://github.com/jded76/Safari16-vanilla-js/blob/299a5779791a32a7ed226b3423ac42ec2ac71e98/index.html#L7) to use the local jquery file `<script src="jquery-3.5.1.js"></script>` the error is gone.

**Comment by mgol** [comment]
Reopening until the fix lands in Sizzle and - then - on `3.x-stable`.

**Comment by mgol** [comment]
Landed on `main` in 3299236c898136dc1aa57dc5148811203e931895.

The `3.x-stable` part of the fix needs to first happen in Sizzle.

Sizzle PR: https://github.com/jquery/sizzle/pull/490
`3.x-stable` PR (will fail until the Sizzle upgrade is incorporated into it): #5159

**Comment by mgol** [comment]
Landed on `main` in 3299236c898136dc1aa57dc5148811203e931895 and on `3.x-stable` in a1b7ae3b3fb86b184bd50666c211f08bbc2ee686 (commit updating Sizzle, includes the fix from https://github.com/jquery/sizzle/commit/759acc72af1c8c3f4109816b0ca326151a2b8106) & 5318e3111afd4c307ad6851682620d7413824fc5. Closing.
