### ISSUE TITLE
Ignored attempt to cancel a touchmove event with cancelable=false

### ISSUE THREAD

**Issue by nfrance709** [jquery/jquery#5156]
### Description ###

I use https://report-uri.com/ to log CSP and the Reporting API https://developer.mozilla.org/en-US/docs/Web/API/Reporting_API and I'm getting a lot of Intervention Reports being sent with the following text when using version 3.6.1 of jQuery, older versions also have the same issue.

**"Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted."**

If line 665 of src/event.js is changed from 
`if ( e && !this.isSimulated ) {`
to
`if ( e && !this.isSimulated && e.cancelable ) {`

I no longer get the error.

Would you be able to updated jQuery to include the check to see if the event is cancellable before calling preventDefault() ? or is there a reason why making that change would cause an issue?

Happy to create a pull request for it.

**Comment by mgol** [comment]
Thanks for the report. As I understand, this warning would fire as well if you called the native `preventDefault()`. It’s a hint to the developer that their call is being ignored and they should stop calling it. Why would jQuery avoid showing the same hints to the developer?

**Comment by nfrance709** [comment]
@mgol Yes, I assumed something in the jQuery codebase was calling it as I'm not using preventDefault() on the page that is causing the warning. If that's not the case, then I must have missed something and there is some client code calling preventDefault() that I missed.

**Comment by mgol** [comment]
There are rare cases where jQuery invokes `preventDefault()` by itself but I doubt it applies here. You might want to check the full stack trace with unminified jQuery source to see where this call originated.

**Comment by nfrance709** [comment]
Thanks for the suggestion. When I was trying to reproduce the issue earlier today with the unminified version I was getting the follow info from the Reporting API and it was reporting line 5774.

I will investigate further to see where the call originated.

```
    {
        "age": 57534,
        "body": {
            "columnNumber": 6,
            "id": "IgnoredEventCancel",
            "lineNumber": 5774,
            "message": "Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.",
            "sourceFile": "**domain removed**/scripts/jquery/jquery-3.6.js"
        },
        "type": "intervention",
        "url": "**domain removed**",
        "user_agent": "Mozilla/5.0 (Linux; Android 8.0.0; SM-G935F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.87 Mobile Safari/537.36"
    }
```
