### ISSUE TITLE
Selector: Implement `uniqueSort`, a chainable method version of `jQuery.uniqueSort`

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#5166]
### Description ###

Some APIs, like `.prevAll()`, return elements in the reversed order, causing confusing behavior when used with wrapping methods (see gh-5149 for more info). To provide an easy workaround, we need to implement a chainable `uniqueSort` method on jQuery objects, an equivalent of `jQuery.uniqueSort`.

### Link to test case ###

See gh-5149 for more details

**Comment by laijinchang** [comment]
my

**Comment by mgol** [comment]
Landed on `main` in 5266f23cf49c9329bddce4d4af6cb5fbbd1e0383 and on `3.x-stable` in 0acbe6433c2689327a7fff94f64dbee42f801ff8. Closing as completed.
