### ISSUE TITLE
innerHTML usage

### ISSUE THREAD

**Issue by wm6692** [jquery/jquery#5173]
### Description ###
In trying to prevent 3rd party code from destroying my html, I debugged it to find that it was using jquery to 'refresh' my html nodes and wiping out their content. To prevent this I tried to catch the removal of the node, but discovered that it wasn't being removed, it was simply being reassigned via innerHTML in jquery's manipulation.js file. 

` html: function( value ) {
                return access( this, function( value ) {
                        var elem = this[ 0 ] || {},
                                i = 0,
                                l = this.length;

                        if ( value === undefined && elem.nodeType === 1 ) {
                                return elem.innerHTML;
                        }

                        // See if we can take a shortcut and just use innerHTML
                        if ( typeof value === "string" && !rnoInnerhtml.test( value ) &&
                                !wrapMap[ ( rtagName.exec( value ) || [ "", "" ] )[ 1 ].toLowerCase() ] ) {

                                value = jQuery.htmlPrefilter( value );

                                try {
                                        for ( ; i < l; i++ ) {
                                                elem = this[ i ] || {};

                                                // Remove element nodes and prevent memory leaks
                                                if ( elem.nodeType === 1 ) {
                                                        jQuery.cleanData( getAll( elem, false ) );
                                                        elem.innerHTML = value;
                                                }
                                        }

                                        elem = 0;

                                // If using innerHTML throws an exception, use the fallback method
                                } catch ( e ) {}
                        }
`
Given that my search on the net of the use of innerHTML is generally a very bad thing (security risk, etc) it basically shouldn't be used. Is there a legitimate reason that it is still being used here? Have all the security and other concerns been addressed if it is? Is there any way to catch this (interceptor) for my node and have it not do the innerHTML in my special case?

**Comment by mgol** [comment]
As you can see, the assignment happens inside of [jQuery's `.html()` method](https://api.jquery.com/html/#html2), the very purpose of which is to wrap native `innerHTML` getter+setter. You'd use  jQuery's `.html()` in those same situations in which you'd assign to the native `innerHTML` property and you'd avoid both in the same situations as well.

If you want to avoid assigning to `innerHTML`, don't use the jQuery's `.html()` setter.
