### ISSUE TITLE
jQuery.animate works incorrectly with scroll-behavior smooth on chrome

### ISSUE THREAD

**Issue by Xcreen** [jquery/jquery#5174]
### Description ###
If the CSS attribute `scroll-behavior: smooth;` is set, the animate function does not work correctly in Chrome. It looks like the animate is hanging/lagging.
In Firefox it works as expected.

Tested with jQuery 3.6.0/ 3.6.1. / 3.6.2.

### Link to test case ###
https://jsfiddle.net/L0hjorkb/1/

**Comment by timmywil** [comment]
We discussed this in the meeting. The best thing to do here is to separate the two strategies and either use `.animate()` or use the `smooth` behavior, but not both.
