### ISSUE TITLE
jQuery 3.6.3 throws on some invalid selectors accepted in <=3.6.1 in Firefox (it works in Chrome & Safari)

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#5194]
_Originally posted by @khetaramsb in https://github.com/jquery/jquery/issues/5177#issuecomment-1381649144_

After upgrading jQuery from 3.6.0 to3.6.3 pseudo selector :before does not work in selector list with Firefox. Everything works with Chrome.

This worked in 3.6.0
`jQuery(".inline-dialog-content:before").css({'left': 40});`

In 3.6.3 it gives following error:

Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: before

**Comment by mgol** [comment]
@khetaramsb despite using a single colon here, `:before` (and `::before`) are really pseudo-elements, not pseudo-classes. They can neither be selected via jQuery nor via `querySelectorAll`.

I guess there's a behavior difference here because while a selector like `.inline-dialog-content:before` doesn't match anything, it also doesn't throw an error; it just returns an empty collection. The code you pasted was previously effectively a noop and now it throws. The reason for that is `CSS.supports('selector(:before')` returns `true` but `CSS.supports('selector(:is(:before)')` returns `false` as `:is()` doesn't support pseudo-elements inside.

That said, this is invalid input so I don't think we're going to change anything here; I don't see an easy way anyway. I've added it to the items to discuss with the team, though.

**Comment by mgol** [comment]
@timmywil @gibson042 I found what's up with this `:before` handling that we discussed at the team meeting. So, `$('.foo:before,bar')` always throws but `$('.foo:before')`throws only if `$('.foo')` doesn't match anything. The difference is caused by an optimization in:
https://github.com/jquery/jquery/blob/c66d4700dcf98efccb04061d575e242d28741223/src/selector.js#L1575
where 1-elem selector lists are treated differently. Now, `.foo:before` looks like a class + a pseudo-class (just because of those legacy pseudo-elements allowing a single colon as well) and since `.foo` doesn't match anything, there's a bail out at:
https://github.com/jquery/jquery/blob/c66d4700dcf98efccb04061d575e242d28741223/src/selector.js#L1615-L1621
On the other hand, `.foo::before` (with double colons) fails during tokenizing so `$('.foo:before')` does throw regardless of whether `$('.foo')` would match anything or not.

**Comment by mgol** [comment]
(For simplicity, I'm talking exclusively about the non-`qSA` path as that's what's being triggered in Firefox for this invalid selector in jQuery 3.6.3.)

**Comment by noraj** [comment]
After upgrading jQuery from 3.6.0 to 3.6.3, `find()` method does not work properly with some [CSS selectors](https://www.w3schools.com/cssref/css_selectors.php) with Firefox. Everything works with Chromium.

This worked in 3.6.0:

```js
newline.find('label[for=mylabel').prop('for', function() { return $(this).attr('for') + '-' + rand } );
```

In 3.6.3 it gives following error with Firefox 109.0 but works with Chromium 109.0.5414.119:

```
Uncaught Error: Syntax error, unrecognized expression: label[for=input-project-codes
error
tokenize
select
se
find
```

**Comment by noraj** [comment]
> @noraj the selector is invalid, it misses a closing attribute bracket. Try `newline.find('label[for=mylabel]')`.

Yes I was updating my comment, weird it was accepted in 3.6.0 tho.

**Comment by timmywil** [comment]
You are correct. It’s another selector that the is technically invalid but the qsa parser forgives. Using `CSS.supports` seems to not have the same forgiveness in its parser.

**Comment by timmywil** [comment]
We've discussed the options, and jQuery is now as unforgiving as `CSS.supports`. It used to be as forgiving as qSA, but now that the spec has introduced what's ironically called ["forgiving parsing"](https://github.com/jquery/jquery/issues/5098), I'm not sure we have a choice anymore. `CSS.supports` is still the right way to go. It's just unfortunate that we can't really pick and choose which selectors we want to be more forgiving with.

**Comment by timmywil** [comment]
And...we discussed this further in the same meeting and completely reversed. Now that `:has` is going to be unforgiving in the spec, it seems unlikely for that situation to arise again. We're considering going back to the old way now.

**Comment by mgol** [comment]
PRs:
* jQuery `main`: #5206
* jQuery `3.x-stable`: #5207
* Sizzle: https://github.com/jquery/sizzle/pull/493

We'll also need a new Sizzle release and a 4th PR against jQuery `3.6-stable` bumping Sizzle after that.

**Comment by mgol** [comment]
[Sizzle 2.3.10 has been released](https://github.com/jquery/sizzle/releases/tag/2.3.10) and here's a PR updating jQuery's `3.6-stable` branch to that Sizzle version: #5209.

**Comment by mgol** [comment]
All PRs have landed; the issue is fixed.

**Comment by mgol** [comment]
The TestSwarm run for `3.6-stable` after landing #5209 looks good: https://swarm.jquery.org/job/13100.
