### ISSUE TITLE
document.queryselector returning null after updating Jquery version

### ISSUE THREAD

**Issue by bharath1h** [jquery/jquery#5215]
### Description ###
After the update of Jquery version from 3.4.1 to 3.5.0 
Jquery migrate version updated to 3.4.0 from 3.3.2

Split.js version - 1.3.5
the document.queryselector("") inside the split.js  is returning null

Reverting the changes works as expected.

### Link to test case ###
https://jsbin.com/kepituq/3/edit?html,js,console

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by AnuragMishraa** [comment]
Instead of using document.querySelector(""), you could try using jQuery's equivalent method, $(selector), to select the desired elements. This would involve modifying the Split.js code to use jQuery instead of plain JavaScript.

**Comment by mgol** [comment]
@bharath1h I don't see any errors reported in your test case.

**Comment by bharath1h** [comment]
We can close the issue found the root cause
There was a backward compatibility issue in the HTML prefilter which uses Regex to ensure that all closing tags were XHTML-compliant.
