### ISSUE TITLE
More versions other than regular and slim

### ISSUE THREAD

**Issue by MarcoEvasi** [jquery/jquery#5217]
I'd like to ask if in jquery 4 is it possible to have more versions other than regular and slim.
Since even more recent libraries refere to jquery for ajax (es. react), then it may make sense to have something like:
- regular
- slim + ajax
- slim
- ajax

**Comment by mgol** [comment]
Thanks for the report.

Unfortunately, every new configuration is added overhead and there's no way for us to support both. Also, if you add ajax you also need to add deferred which are not planned for the v4 slim build currently.

The complexity will get even higher because we plan to expose ESM builds in addition to the current script ones. You can see how complex it will already be with these two config options at https://github.com/jquery/jquery/pull/5122/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519.

Therefore, I don't think we'll be adding any new custom builds. If you have non-standard needs and you want to fine-tune the build further, you can compile a custom build yourself according to the README instructions. The current two builds - full & slim - are meant to cover the most common scenarios, not all possible use cases.

**Comment by mgol** [comment]
Also, can you elaborate on this?
> Since even more recent libraries refere to jquery for ajax (es. react)

Where does React refer to jQuery for using AJAX? That would surprise me, to be honest.

**Comment by MarcoEvasi** [comment]
Thanks for answering.

React refer here to jQuery for ajax:
https://it.reactjs.org/docs/faq-ajax.html

This page is in Italian and I couldn't find the english version.
Anyway the first question is:

Come posso fare una chiamata AJAX ?
Puoi usare qualsiasi libreria AJAX con React. Le più popolari sono Axios, jQuery AJAX, e l’API window.fetch che è integrata nel browser.

Which means:

How can I make an ajax call?
You can use whatever ajax library with React. The most popular are Axios, jQuery AJAX, and API window.fetch which is integrated in browser.

**Comment by MarcoEvasi** [comment]
anyway the english page is here:
https://reactjs.org/docs/faq-ajax.html

**Comment by mgol** [comment]
Interesting, I didn't see this page before. The beta React docs no longer seem to include this page: https://beta.reactjs.org/

In any case, my original argument stands. The main power of jQuery nowadays is in its composition mechanisms and event handling that allows you to attach handlers on multiple elements without manual looping, supports delegated handlers, etc. The AJAX code is definitely more dated and doesn't get nearly as much love; plus, there are a lot of AJAX libraries nowadays; similarly, for animations there are more actively maintained libraries, there is the Web Animation API, etc. We felt it's worth to create this slim build that cuts out parts of jQuery that dated a bit more than others.

For more fine-grained needs, we maintain the custom compilation pipeline for folks to compile what they need. If there are any problems with this custom builder code, please submit a separate issue with more details.

**Comment by MarcoEvasi** [comment]
Well, I see your point and actually I was speaking on the basis of my personal experience, since I use everything of jQuery but animations. 

I actually think that much of the "jQuery free" attitude that you can read on blogs is just hype.

I think that vanilla + jQuery for missing utilities is the way to go, and in this view it would be optimal if jQuery was modular in such a way that you could pick up just what you need.

**Comment by mgol** [comment]
> and in this view it would be optimal if jQuery was modular in such a way that you could pick up just what you need.

You actually can. 🙂 jQuery 3.z is authored using AMD modules so if your toolchain understands AMD, you can pull individual files from the `src` directory.

In jQuery 4.0 we’re migrating to ECMAScript Modules, keeping AMD ones for compatibility in the `amd` folder.

**Comment by MarcoEvasi** [comment]
As a last consideration against the now popular "jQuery free" attitude, I noticed that many people are starting to ask themself if, for the rendering part,  js templating engines aren't better than react.

I would like to point out to this:
https://www.quora.com/Is-it-really-that-much-better-to-use-Angular-React-over-a-templating-engine-like-EJS
