### ISSUE TITLE
The .html() attribute returns “” when a bad formed html is passed as an argument

### ISSUE THREAD

**Issue by toomsie** [jquery/jquery#5222]
The .html() attribute returns “” when a bad formed html is passed as an argument
    
    Example: 
      <script>
          $(document).ready(() => {
            $('h1').html('<html, hello world');
          });
        </script>

Expected:
     an exception to be thrown warning of badly formed html

Link to test example
https://jsfiddle.net/toomsie/x17jz82a/23/

**Comment by dmethvin** [comment]
jQuery doesn't throw exceptions for bad arguments. In this particular case, parsing of the HTML is done by the browser and jQuery doesn't know whether the browser's output is correct or not. The documentation says: ["To ensure cross-platform compatibility, the snippet must be well-formed."](https://api.jquery.com/jquery/#jQuery2).

**Comment by toomsie** [comment]
I guess so. JQuery should not be the best place to check html,

**Comment by mgol** [comment]
Closing as won't fix per Dave's comment.
