### ISSUE TITLE
problem with CSP

### ISSUE THREAD

**Issue by ammar-Mohamed-elz3eeem** [jquery/jquery#5246]
our website is built using jQuery and we add CSP to it also add nonces to inline scripts but the problem is that we use append everywhere on our codes but this make a problem with us as CSP refuses append of jQuery

![Screenshot 2023-05-06 005002](https://user-images.githubusercontent.com/76789647/236574609-e78a7aac-b4ce-419e-b463-3e3b676382af.png)
![Screenshot 2023-05-06 005012](https://user-images.githubusercontent.com/76789647/236574617-b93d0026-7c31-4a8c-9194-53add7ea3dcd.png)

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

We added support for nonces in https://github.com/jquery/jquery/issues/4323 so it’s hard to guess what’s happening without a test case.

**Comment by ammar-Mohamed-elz3eeem** [comment]
it's hard to provide that because website is built using php as backend but i can tell you the complete process
- the website is built using ajax 
- when you go from page to page ajax request sent with the name of the page 
- we take name of the page via ajax to php and require the file for template for that page
- then we send response back to ajax call with that file we need for frontend using $data var as assosiative array in php with key set to html and value set to the file we required for that page
- we insert the file into the current page using append ( we get that file from step above into $data['html'] and we access it in javascript using objects so will be data.html

every page template on our website have a file for scripts ( inline scripts ) and all of them have nonce 
so when we load specifiec page template we are getting the error on the image i sent above

**Comment by mgol** [comment]
We don’t need to replicate your full setup; I’m just interested in the exact piece of code calling the problematic jQuery API and what exact arguments does it receive. Even better, if you can experiment on your project locally and find a possibility small example.

**Comment by ammar-Mohamed-elz3eeem** [comment]
okay i have provided the code needed on this jSBin https://jsbin.com/gicikedeje/edit?html,css,js

**Comment by mgol** [comment]
The example you provided is not runnable, it crashes on a preflight request.

I don't think you need to call `jQuery.ajax` at all; the error likely comes from the `.html(json_data.page_title)` call - all I need is that line but with a concrete value passed to `.html()` instead of some data from a server. Just to see a concrete example what fails, a very minimal test case.

**Comment by mgol** [comment]
Closing due to insufficient information. We can reopen if we get more data.
