### ISSUE TITLE
Core: Use named exports in `src/`

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#5262]
### Description ###

The code in `src/` on the `main` branch is authored using ECMAScript modules with default exports. Each file exports a single API.

In the `exports` PR (#5255) for 4.0, a concern has been raised by @GeoffreyBooth that [default exports are generally discouraged](https://github.com/jquery/jquery/pull/5255#discussion_r1203188476) so we should ideally provide named `jQuery` & `$` exports in addition, even if we keep the default export as well. There's a link to [a Webpack docs page there](https://webpack.js.org/guides/package-exports/#guidelines) that says:

> Avoid the `default` export. It's handled differently between tooling. Only use named exports.

I just wondered how that affects our approach to jQuery source code. Since we plan to expose the ESM files from `src/`, should we switch them to use named exports as well?

If we switch, this is likely to affect our AMD output published to the `amd` directory. We can either accept it, or tweak the AMD output or maybe even give up on AMD for individual modules and just bet on ESM here.

### Link to test case ###

N/A

**Comment by mgol** [comment]
The code in `src/` on the `main` branch is authored using ECMAScript modules with default exports. Each file exports a single API.

In the `exports` PR (#5255) for 4.0, a concern has been raised by @GeoffreyBooth that [default exports are generally discouraged](https://github.com/jquery/jquery/pull/5255#discussion_r1203188476) so we should ideally provide named `jQuery` & `$` exports in addition, even if we keep the default export as well. There's a link to [a Webpack docs page there](https://webpack.js.org/guides/package-exports/#guidelines) that says:

> Avoid the `default` export. It's handled differently between tooling. Only use named exports.

I just wondered how that affects our approach to jQuery source code. Since we plan to expose the ESM files from `src/`, should we switch them to use named exports as well?

If we switch, this is likely to affect our AMD output published to the `amd` directory. We can either accept it, or tweak the AMD output or maybe even give up on AMD for individual modules and just bet on ESM here.

**Comment by mgol** [comment]
Adding the `4.0.0` milestone and the Blocker label to ensure we make a decision before the release.

**Comment by timmywil** [comment]
Will be using named exports in the `src` folder.

**Comment by truthtahoe** [comment]
tahoe is not very honest these days? Who wants to chat? wanna see what i have to show the community?

**Comment by GeoffreyBooth** [comment]
> In the `exports` PR (#5255) for 4.0, a concern has been raised by @GeoffreyBooth that [default exports are generally discouraged](https://github.com/jquery/jquery/pull/5255#discussion_r1203188476)

https://x.com/kentcdodds/status/1702338292065399179?s=20
