### ISSUE TITLE
Iframes Memory Leak with jQuery and Sizzle

### ISSUE THREAD

**Issue by vamsikrishnach90** [jquery/jquery#5281]
### Description ###
We have a situation where there are 3 levels of nested iframes. The 3rd iframe initializes few heavy size objects, but this iframe is discarded and rebuilt in the DOM whenever user navigates across the application.

A memory leak is noticed where heap size of the application keeps on increasing whenever a new iframe at 3rd level is discarded and constructed.

### Link to test case ###
Goto https://vamsikrishnach90.github.io/ in Chrome. Open developer tools (Hit F12) and navigate to Memory Tab. Pay attention to the JS heap size which is arppox 5 MB.

1. Click on 'Load Child Page' button. A child page is loaded inside the iframe of parent page.
2. Click on 'Bombard the page!' button on the child page. This will initialize 1 global variable of custom type with a huge json. Open devtools and check for the heap which is now 75 MB.
3. Click on 'Remove Child Page' button. The child page (iframe) is removed from the DOM. 

Repeat steps 1 - 3 for about 2 more times. After step 2, note down the heap size. You'll notice that the heap keeps on increasing every time we add a child iframe and bombard it. Even though at step 3, we discard the frame, the heap is not claimed by the garbage collector.
[Usecase demo help (Picture)](https://i.stack.imgur.com/5rUI0.png)

## Observations ##
After repeating above 1-3 steps for 3x times, take a heap snapshot. Notice that the 3 instances of custom class 'Vamsi' that were created every time we added the child page and bombarded it still exist in the heap, even though the corresponding iframes are deleted from the DOM.

Notice in the object graph, that an unloadHandler() has been bound to the Window object belonging to the discarded iframes. [Heap Memory Snapshot](https://i.stack.imgur.com/je59l.png)

## Root Cause ##
The child page has a jquery lookup statement in the parent page:
`$('div.msg-banner', window.parent.document).show();`

This one line statement is causing the issue for memory leak.

> $('div.msg-banner', window.parent.document)

The above part of the statement, calls JQuery find api. This find API is overridden by [Sizzle](https://github.com/jquery/sizzle), a pure-JavaScript CSS selector engine adopted by JQuery. This find api from JQuery calls Sizzle's setDocument function [See Picture](https://i.stack.imgur.com/YEbYk.png) which registers an unloadHandler() with the requested document's(window.parent.document) window object. This is leading in the parent page's unload event bound to unloadHandler() callback function sitting in the child page. Hence, even though the child page iframe is removed from the DOM, the window object is never eligible to be garbage collected and is the reason for memory leak.

Link to **Stackoverflow** thread: https://stackoverflow.com/questions/76579826/iframes-memory-leak-with-jquery-and-sizzle

**Comment by mgol** [comment]
Thanks for the report. The unload handler is needed by IE & Edge Legacy; in jQuery 4 that drops support for the latter, we'll explicitly only set it in IE, avoiding the memory leak outside of IE.

To avoid the leak, IE or not, we'd probably have to add an additional `unload` handler on the document on which jQuery is loaded that would collect all the `unload` handlers attached to other documents and remove them when the main document is unloaded. This might require significant code to pull off, though, which I'm not too happy about.

**Comment by vamsikrishnach90** [comment]
Thanks for responding and acknowledging the problem. Let me know when you have next "Plan of Actions" to fix this issue after your internal meeting and review.

**Comment by mgol** [comment]
jQuery 4.0 code already has this isolated to IE so no changes are required there. So if we make any changes, they will land in jQuery 3.7.1.

**Comment by mgol** [comment]
PR: #5282

**Comment by mgol** [comment]
My workaround from https://github.com/jquery/jquery/issues/5281#issuecomment-1613348177 would require more changes as `setDocument()` should only be called for `subWindow` unload so handlers need to be different. I think for now I prefer to just skip the workaround outside of IE & Edge Legacy and accept the memory leak in those two browsers.

**Comment by mgol** [comment]
Fixes for non-IE non-Edge Legacy browsers in #5282 - and that's all we plan, closing.
