### ISSUE TITLE
Question about $.html()

### ISSUE THREAD

**Issue by fadeli1** [jquery/jquery#5287]
### Description ###
jquery 1.11.0 to 3.7.0
$.html() logic is inconsistent

### Link to test case ###
jquery-1.11.0.js
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>test</title>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.11.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#opener" ).on( "click", function() {
      $( "#dialog" ).dialog({
		modal: false,
		open: function(){
			$("#test").html("<script type='text/javascript'>$(document).ready(function(){console.log(1)})<\/script>");
			console.log(2)
		} 
	  });
    });
  } );
  </script>
</head>
<body>
<div id="dialog" title="Basic dialog" style="display:none;">
  <div id="test"></div>
</div>
<button id="opener">Open Dialog</button>
</body>
</html>
```
jquery-3.7.0
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>test</title>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#opener" ).on( "click", function() {
      $( "#dialog" ).dialog({
		modal: false,
		open: function(){
			$("#test").html("<script type='text/javascript'>$(document).ready(function(){console.log(1)})<\/script>");
			console.log(2)
		} 
	  });
    });
  } );
  </script>
</head>
<body>
<div id="dialog" title="Basic dialog" style="display:none;">
  <div id="test"></div>
</div>
<button id="opener">Open Dialog</button>
</body>
</html>
```
### Observations  ###
jquery-1.11.0.js  -> The printed result is: 1, 2
jquery-3.7.0.js  -> The printed result is: 2, 1

**Comment by mgol** [comment]
jQuery 3.x first fetches the scripts via synchronous XHR but then inserts them into the DOM via script tags which are asynchronous. They execute quickly enough since there's no async XHR involved but yes, they do so after the following synchronous code.

jQuery 2.x already partially had this behavior, but only for scripts starting with the `"use strict"` pragma; jQuery 1.x always just used `eval`. We're not using `eval` in 3.x anymore as it's generally not compatible with CSP.

So yes, this is an intended breaking change. We should perhaps document it in the upgrade guide: https://jquery.com/upgrade-guide/3.0/

**Comment by mgol** [comment]
Ah, no, actually, I was wrong - we only plan to make scripts async but we haven't made the change yet, see #1895. We do use script tags but we copy the value of the `async` property from the node being inserted so it will remain synchronous.

What's happening in your case is wrapping the source in ready callbacks. Timing of those did change in jQuery 3.0 - they are now always asynchronous. This is documented in the upgrade guide already:
https://jquery.com/upgrade-guide/3.0/#breaking-change-document-ready-handlers-are-now-asynchronous
