### ISSUE TITLE
Consider Removing CSS Module from jQuery slim

### ISSUE THREAD

**Issue by WhenJavaAttacks** [jquery/jquery#5301]
### Proposal ###

I would like to propose excluding the css module (and, of course, all dependencies*) from the slim version of jQuery. There are a few reasons I believe this makes more sense than only excluding the ajax and effects modules as the build for slim currently does.

One is that this would make the slim version a more substantial reduction (I see an ~ 8 Kb (uncompressed) reduction from removing it), which I believe would better justify the existence of a "slim" version in the first place and give more reason to consider using it over the normal version (both to save download size and reduce the amount and complexity of code actually parsed and loaded into the browser).

Secondly, I believe that removing the css module in particular also promotes a good programming strategy, one where jQuery no longer manipulates styling directly but instead all styling is defined in CSS and jQuery only manipulates class/attribute values as to match selectors in said CSS so that the desired styles are applied. I don't know of any styling that couldn't be done via CSS anyway so from this point of view jQuery's css module is unnecessary, not to mention that the resulting code should be cleaner too (one less place that styling can come from).

* modules dependent on css: effects, dimensions, offset

**Comment by WhenJavaAttacks** [comment]
On a side note, I actually find the ajax module useful enough that, as a secondary request, I wouldn't mind seeing it included in jQuery slim.

It's not that a good alternative doesn't exist (native JavaScript xhr, obviously), but simply that I find jQuery's syntax more succinct and easy to work with, and it comes already using a promise, all things which IMO justify still including it even in the slim version.

(To reiterate though, this request to consider including ajax module with jQuery slim is definitely secondary to my request to consider removing the css module though, and I didn't feel it was worth creating a separate issue for it.)

**Comment by mgol** [comment]
Thanks for the report.

Different people may need different modules and there's no way to accommodate them all. Maintaining both the full & slim version is complex enough so I don't think we'd like to introduce more versions.

Right now, in jQuery 3.x we exclude ajax & effects modules:
https://github.com/jquery/jquery/blob/ef18fe9af5db5088657d42fde07bb23b19d0c494/build/tasks/lib/slim-build-flags.js#L4-L7
and for jQuery 4.x we plan to also exclude callbacks, deferred & queue:
https://github.com/jquery/jquery/blob/8be4c0e4f89d6c8f780e5937a0534921d8c7815e/build/tasks/lib/slim-build-flags.js#L4-L10

There are good reasons for those choices. Both ajax & effects depend on the deferred module; nowadays, it is more common to depend on native promises. Both ajax & effects have good replacements in today's JS. There are lot of actively developed AJAX libraries that are more modern than the jQuery version and we're not going to keep up on that front. In case of effects, there are CSS transitions & animations, the Web Animations API and many specialized animation libraries that are doing a much better job than jQuery does.

Meanwhile, the core jQuery interface with its wrapper collections & chaining, convenient event handling, much easier & more succinct than native APIs are where jQuery still shines.

I think the validity of our choices for the slim module have been validated by the fact that frameworks relying on jQuery, like Bootstrap 4 or AngularJS work fine with the slim module - but they generally do need the css module. Css is also a requirement of some other modules like dimensions or offset.

If you do need different choices than we made for the slim module, you can compile a version of jQuery you need yourself. Just check out a proper tag on the jQuery repo (`3.7.0` to get the latest stable version as of now) and follow the README instructions for custom compilation.

I'll leave the issue open for some time for other team members to voice their opinion but I don't think we'll make any changes here (except for the ones we already made for jQuery `4.0`).

**Comment by timmywil** [comment]
Discussed in the meeting. mgol's explanation is great.
