### ISSUE TITLE
Animate function mishandles first instance/execution

### ISSUE THREAD

**Issue by SoulEater2022** [jquery/jquery#5315]
### Description ###

When the first instance of animate is executed it goes from transform: rotate(90deg); to transform: rotate(0deg); instantly instead of having a 300 duration. In the CodePen example I change the duration to 3000 to make the issue more obvious.

### Link to test case ###

[CodePen](https://codepen.io/SoulEater2022/pen/xxmEWrW)

**Comment by mgol** [comment]
The first argument to [`.animate()`](https://api.jquery.com/animate/) is supposed to be "An object of CSS properties and values that the animation will move toward". There's no CSS property `deg` so this is not valid API usage.

That's an unfortunate limitation of `.animate()` but we're not really making major changes to the API anymore. It is possible to set step hooks for animations as described at:
https://api.jquery.com/jQuery.cssHooks/#animating
but this is pretty advanced usage.
