### ISSUE TITLE
ESM Version, preview NPM Package

### ISSUE THREAD

**Issue by jogibear9988** [jquery/jquery#5321]
Is a preview of the jquery ESM package anywhere available?
I'm developing an app, wich works completely without a bundler, but it does not work, if jquery is not loaded via esm

**Comment by mgol** [comment]
I published https://www.npmjs.com/package/@mgol/jquery-exports-test-do-not-use-v7 experimentally a while ago to demo https://github.com/jquery/jquery/pull/5255. It does not contain the latest changes from https://github.com/jquery/jquery/pull/5292, though. Also, as its name suggest, we don't guarantee the stability of this package, some things may still change before the final 4.0.0 release.

If you intend to actually use it in a production app, it would be much safer to wait at least for the 4.0.0 beta, though.

**Comment by mgol** [comment]
If you want something right now, with the current stable version of jQuery, you may need to look into community-maintained post-processed versions of jQuery. An example page like that: https://esm.sh/ (I do not guarantee anything about this service).

**Comment by jogibear9988** [comment]
problem is, I need a npm package. I refactor my libs at the moment, and they should be usable from within bundlers and directly from the browser without special code.
Is there a time schedule for the 4.0 release?

**Comment by mgol** [comment]
We cannot promise any release dates.
