### ISSUE TITLE
Avoid unload event listeners

### ISSUE THREAD

**Issue by adrienmaloba** [jquery/jquery#5323]
### Description ###

Hello,

When I run a speed test for my site, I see among the test results this warning of type "Avoid unload event listeners". 

The warning : The unload event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Use `pagehide ` or `visibilitychange ` events instead.

On checking, I found that the warning comes from my jQuery file version v3.6.0 or version v3.7.1. The source of the warning is https://github.com/jquery/jquery/blob/main/src/event.js#L125

Note: https://web.dev/bfcache/?utm_source=devtools#never-use-the-unload-event

**Comment by adrienmaloba** [comment]
> Since #5282, we only attach `unload` handlers in IE & Edge Legacy where they are necessary. This is included in jQuery 3.7.1 so you should see no warnings from that version.

@mgol, thanks for your quick feedback. I've tested the code in version 3.7.1 and when I run the speed test, I still see the warning triggered by the line https://github.com/jquery/jquery/blob/main/src/event.js#L125

I have the impression that this line ( https://github.com/jquery/jquery/blob/main/src/event.js#L125) is not related to IE & Edge Legacy. Am I right?

**Comment by mgol** [comment]
That line is just the definition of the event handler when attached via jQuery. It gets invoked whenever you call `.on( eventName, ... )` for the first time for each `[ node, eventName ]` pair. Pointing to this line doesn't tell you much, the problem happens earlier. Do you have a stack trace for this warning?

You can see by searching for `unload` in https://code.jquery.com/jquery-3.7.1.js that the only place where jQuery attaches an `unload` handler is guarded by a block guarded by a `documentElement.msMatchesSelector` check which only IE & Edge Legacy pass.

**Comment by adrienmaloba** [comment]
No, I don't have a stack trace for this warning.

**Comment by tomslutsky** [comment]
> Since #5282, we only attach `unload` handlers in IE & Edge Legacy where they are necessary. This is included in jQuery 3.7.1 so you should see no warnings from that version.

We are running on jQuery version 2.1.4 and upgrading to 3.7.1 sounds like too big of a risk atm. 
Would patch replacing 'unload' with 'pagehide' be a viable option?

**Comment by mgol** [comment]
@tomslutsky No, but you can apply changes from https://github.com/jquery/jquery/pull/5282 if you’re patching by hand.
