### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'createElement')

### ISSUE THREAD

**Issue by 821938089** [jquery/jquery#5343]
### Description ###

I discovered how to reproduce this problem 100%.
For more information, please see #4308 #3333.
Hopefully it can be fixed soon.

### Link to test case ###

1. Open DevTools.
2. Switch to "Source" Tab.
3. Check this option.
![image](https://github.com/jquery/jquery/assets/8674809/cedcb512-0ef8-498b-b605-5579442b3b19)
4. Refresh the page and wait for the browser to reach a breakpoint.
5. Paste the JQuery source code into the console and run it, you will get this error.

**Comment by mgol** [comment]
I've just tried following your steps and I still didn't get any failure. It's not a great test, though, as the first script will often come from an extension so the behavior here highly depends on your local environment.

I'm going to close this for now but if you have more info that I can reproduce, please provide it here and we can reopen.
