### ISSUE TITLE
Event triggering is being captured incorrectly

### ISSUE THREAD

**Issue by eduardo-mior** [jquery/jquery#5344]
### Description ###
I have a custom element called ```<list-items>``` and I also have a custom element called ```<item>```
I have a custom event called ```"itemChange"```, which is fired when a modification is made to an ```<item>```.

In a specific case I have an ```<item>``` that has another list of ```<list-items>``` inside. When firing an "itemChange" event for a child list ```<item>```, the parent ```<item>``` also listens for this event.

Example:
```
<list-items>
  
   <item id="item-1">
     <list-items>
       <item id="sub-item-1">SubItem 1...</item>
       <item id="sub-item-2">SubItem 2...</item>
     </list-items>
   </item>
  
   <item id="item-2">Item 2 ABC...</item>
  
</list-items>
```
When I fire the ```"itemChange"``` event for #sub-item-2, for some reason #item-1 also listens to it.

### Link to test case ###
https://codepen.io/rushyoutuber/pen/jOXXWBx

### Other informations
My jQuery version is 3.7.1.
I tested this issue on Windows, GoogleChrome and Firefox and Edge. The problem always happens.

**Comment by eduardo-mior** [comment]
Doing some other tests I discovered that this happens with any event and any element. It doesn't need to be custom events or custom elements.

Is this normal expected behavior?

**Comment by dmethvin** [comment]
Yes, that's the way DOM events work (with or without jQuery). They bubble up the DOM tree until they reach `document`. If you don't want them to bubble, you can call `event.stopPropagation()` or use jQuery's `.triggerHandler()` instead of `.trigger()`.

**Comment by eduardo-mior** [comment]
@dmethvin Thank you very much for the explanation. Is this documented in jQuery anywhere? I believe that perhaps there should be examples of this in the jQuery documentation.

Can I change my trigger() to triggerHandler() without any problems, or are there more differences between the functions?

**Comment by dmethvin** [comment]
jQuery is a relatively light wrapper around the DOM, so the jQuery docs don't try to explain the behavior of HTML, CSS, JavaScript, or DOM events. They work the way they are documented to work in the browser. For the exceptions related to `.triggerHandler()` you can refer to the docs: https://api.jquery.com/triggerHandler/

**Comment by eduardo-mior** [comment]
@dmethvin Thanks!
