### ISSUE TITLE
jquery destructuring assignment

### ISSUE THREAD

**Issue by b5414** [jquery/jquery#5352]
### Description ###

```js
const btnsParent = $('center').last();
console.log('jq:', btnsParent);

const [leftBtn1, rightBtn1] = btnsParent.children(); // auto .toArray() ?
const [leftBtn2, rightBtn2] = [btnsParent.children().eq(0), btnsParent.children().eq(1)];

console.log('is not jq:', leftBtn1, rightBtn1);
console.log('is jq:', leftBtn2, rightBtn2);
```

### Link to test case ###

https://www.google.com/ + code above

**Comment by mgol** [comment]
That is expected behavior. The first one relies on jQuery objects being iterable, the second on the fact `.eq()` returns a jQuery object, [as documented](https://api.jquery.com/eq/).

**Comment by b5414** [comment]
@mgol how to return jq object into `[btn1, btn2]` format?

**Comment by mgol** [comment]
It is not recommended to prematurely wrap DOM nodes into jQuery objects; it has performance implications. But if you really need it, you’ll need to write your own loop.
