### ISSUE TITLE
Treeveiw not woking with jquery 3.7.1

### ISSUE THREAD

**Issue by vasuvandla** [jquery/jquery#5370]
Hi Team,

Currently , I'm upgrating jquery 1.9 to 3.7.1 library. After migrated, facing  Uncaught TypeError: Cannot read properties of undefined (reading 'createDocumentFragment')

I'm not sure what is this issue , I spend 3 days on this issue to solve, but no luck .

Kindly advice .

**Comment by mgol** [comment]
Issues with third party libraries built on top of jQuery should be reported to those libraries. Be sure to check their jQuery version compatibility; it's possible you'll need to upgrade that other library as well.

**Comment by vasuvandla** [comment]
Hi ,
I'm trying to call treeview functionality [var current = $("

").attr("id", this.id || "").html("" + this.text + "").appendTo(parent);]
from jquery.treeview.async.js file , But encountered issue with Uncaught TypeError: Cannot read properties of undefined (reading 'createDocumentFragment').
Any advice/help appreciate your help .
Thanks in advance .

Sreenivasulu

**Comment by vasuvandla** [comment]
I'm not using any third party libraries.

**Comment by vasuvandla** [comment]
But it's working very well with jQuery library version 2.0.0 why not with 3.7.1 ?

**Comment by vasuvandla** [comment]
please suggest what is the best and free source plugin for Treeview which works for jQuery 3.7.1 version

**Comment by mgol** [comment]
All I know is https://github.com/jzaefferer/jquery-treeview mentions it’s no longer maintained and suggests https://mbraak.github.io/jqTree/

You’ll need to check on your own whether that’s enough for you.

**Comment by vasuvandla** [comment]
Thanks You so much for quick response . Let me try with https://mbraak.github.io/jqTree/
