### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'createDocumentFragment') in jQuery 3.7.1 

### ISSUE THREAD

**Issue by vasuvandla** [jquery/jquery#5373]
Hi ,
I'm trying to call treeview functionality [var current = $("

").attr("id", this.id || "").html("" + this.text + "").appendTo(parent);]
from jquery.treeview.async.js file , But encountered issue with Uncaught TypeError: Cannot read properties of undefined (reading 'createDocumentFragment').
When I calling 
 "var current = $("<li/>").attr("id", this.id || "").html("<span>" + this.text + "</span>").appendTo(parent); 
from .jquery.treeview.async.js throwing above error.

Current versions .
1. jQuery 3.7.1.
2. jQuery-migrate-3.4.1
3. jquery.treeview.js 
4. jquery.treeview.async.js
5. jquery.treeview.edit.js
6.  jquery-ui.custom.min.js

Thanks in advance and appreciate your help

Sreenivasulu

**Comment by mgol** [comment]
Please don’t open duplicate issues; you already reported it in #5370. I explained there why this is not a good place for such reports.
