### ISSUE TITLE
Content-Security-Policy / nonce error in DOMEval

### ISSUE THREAD

**Issue by vpkg** [jquery/jquery#5374]
### Description ###
Error with CSP enforced with nonce when using struts2-jquery `<sj:datepicker>` or `<sj:autocompleter>`
The script loaded by DOMEval has no nonce value.

![image](https://github.com/jquery/jquery/assets/22842953/1ab6cf8c-1460-4223-a72b-796ee1ad8d1c)

Same issue as described here
https://stackoverflow.com/questions/76893697/how-can-i-fix-jquery-3-7-0-inline-script-violation-with-csp

### Workaround ###
As a workaround, I put that in my local version of DOMEval.js / jquery-3.7.0.js

![image](https://github.com/jquery/jquery/assets/22842953/1ade6c4d-e031-4b00-9cfe-0c8dceaee1a6)

And added the nonce value in the <head> tag of my jsp
```html
<head nonce="${sessionScope.nonce}">
``` 

It works but is it a legit fix ?

**Comment by mgol** [comment]
As you can see in `DOMEval` code, it does copy the `nonce` property from the source node. Whatever issue you’re facing needs to originate in a different part of the code.

The workaround for your issue wouldn’t be correct in general as `document.head` doesn’t have the `nonce` property unless it’s set from JavaScript.

We need a test case that doesn’t involve third-party libraries.

**Comment by vpkg** [comment]
I finally understood why : it was because of the missing `strict-dynamic` in my CSP header
I had this one `script-src 'self' https://www.google.com/ https://www.gstatic.com/ 'nonce-%s'` because I needed self and google.com.
Now I reverted to the standard struts2 CSP `script-src 'nonce-%s' 'strict-dynamic' http: https:` and I will have to change all my `<script>` tags into `<s:script>` even those referring to the .js inside my app.
