### ISSUE TITLE
Facing jQuery Selector issue after upgrading from 1.7.1 to 3.7.1

### ISSUE THREAD

**Issue by jQueryIssues** [jquery/jquery#5375]
### Facing jQuery Selector issue after upgrading from 1.7.1 to 3.7.1

I have upgraded my project with latest jQuery versions 3.7.1 with jQuery migrate 3.4.1.
I was facing few issues, one of the issue as below.
There was jQuery code and testcase written and expected out as below.

## Actual Code
return function () {
        var result = $('a[data-tabfocus="' + $currentTarget.attr('data-shortcut-tabfocus') + '"]');
        return result;
    };
## 
## Test Case
var result = sut();
expect(result.selector).toBe('a[data-tabfocus="vs"]');
## 

The above code perfectly working until the jQuery version 2.2.4, but after with jQuery version 3.0.0 and above was getting failed to generate the selector using the above code.
And I cannot go any other jQuery version to upgrade due to the security reasons since other version has a reported vulnerabilities.

Did not found any solution when I researched, requesting  to help any one to get it resolve with this asap.

Thanks in advance.

Attached below sample screen shot for you references:

![With jQuery 3 7 1 version](https://github.com/jquery/jquery/assets/153486986/19dca11c-14ea-41d0-b079-1d2e9be1431c)

![With jQuery 2 2 4 version](https://github.com/jquery/jquery/assets/153486986/0931863c-8e57-4373-a736-9b0fa114bdba)

**Comment by mgol** [comment]
This is an intended breaking change; see https://jquery.com/upgrade-guide/3.0/#breaking-change-deprecated-context-and-selector-properties-removed
