### ISSUE TITLE
Jquery 4.0 beta?

### ISSUE THREAD

**Issue by nagyimre1980** [jquery/jquery#5376]
4.0 beta announcement? Or a release version?
When will beta 4.0 be released?
Nothing happened with this project in the past six months.
Why? KB stopped all reasonable development.

Internet explorer 11.0 is no longer usable, a non-existent browser, and you want to support it until 5.0.
Jquery 5.0 will be released in at least 3 years, or rather later!!!
To support IE11 in 2025-2026? :( :(

Let's speed this project up a bit.

**Comment by timmywil** [comment]
The jQuery maintainers are volunteers that work on it when they can. Feel free to contribute if you want to see things speed up. Not that it matters, but your timeline is off. The last release was 4 months ago and the last commit on the main branch was 4 weeks ago and the last maintainers meeting was Monday. There's also a large amount of being done on the jQuery infrastructure outside this repo. The [blog post for 4.0 beta](https://github.com/jquery/jquery/issues/5365) is in the works. Once that is ready, we'll have a release. Please do not open issues like this on other projects.
