### ISSUE TITLE
invalid assignment left-hand side in jquery-3.7.1.min.js

### ISSUE THREAD

**Issue by JPRuehmann** [jquery/jquery#5380]
### Description ###
Firefox error Console says that there is an "Uncaught SyntaxError: invalid assignment left-hand side" in "jquery-3.7.1.min.js" at line 50621.

### Link to test case ###
https://jpruehmann.dnshome.de/

**Comment by mgol** [comment]
We cannot debug issues in full apps. Please look for programming help in other venues.

**Comment by JPRuehmann** [comment]
The issue is in your app!

**Comment by mgol** [comment]
The fact that the error points to jQuery doesn’t mean the bug is in jQuery. In the vast majority of cases it is not.

**Comment by JPRuehmann** [comment]
That ma be true but it points to it and there is no way to get more information. If I try to open the File and get to the apointed Line there is only one Line. If I at least know the Function that is there, then maybe I could see if it is the only Java script I am running a Clock. The Google recaptcha script should not using any functions from jquery.

**Comment by mgol** [comment]
> That ma be true but it points to it and there is no way to get more information.

There are many ways. But this is not the place to be learning them. Please try elsewhere.

**Comment by JPRuehmann** [comment]
And that is not the Tone to talk to Customers.
Good Bye.

**Comment by mgol** [comment]
You are not a customer, just a user - there’s no money transfer here. We’re volunteers and we need to manage our limited time. Programming support is not what we can offer for free, that’s too time-consuming.
