### ISSUE TITLE
Update the rules for boolean attributes for 4.0

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#5388]
Our list of boolean attributes is outdated; it is missing several boolean attributes from [HTML Attributes](https://html.spec.whatwg.org/multipage/indices.html#attributes-3), includes a `scoped` that isn't even present there, and treats [`hidden`](https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute) as boolean despite the expansion of that attribute to be an enumeration including "until-found" by https://github.com/whatwg/html/commit/f5def65bda4d01a6a1e105fcf13fe45201b4f48a.

_Originally posted by @gibson042 in https://github.com/jquery/jquery/pull/5384#discussion_r1445103967_

**Comment by mgol** [comment]
Oh, interesting. Perhaps we should update this list for 4.0 as this can be considered a breaking change.

Or we should get rid of this manual normalization, depending on users doing the right thing here. The biggest issue are possibly falsy checks on values since an empty string is also a valid value. This was also raised by @timmywil in a past issue where I proposed a similar simlification: https://github.com/jquery/jquery/issues/2946.

If we're worried about compat for such things, my guess would be we could limit this list to just a few entries like `checked` & `selected`. I feel keeping the list open-ended leads us to the same problems as the logic for auto-appending `px` - the list is never complete and modifying this is both a maintenance burden as well as a potential source of application breakage. (the `px` behavior was change to have a closed list in https://github.com/jquery/jquery/pull/4055)

Our list right now is:
* `checked`
* `selected`
* `async`
* `autofocus`
* `autoplay`
* `controls`
* `defer`
* `disabled`
* `hidden`
* `ismap`
* `loop`
* `multiple`
* `open`
* `readonly`
* `required`
* `scoped`

As Richard mentioned, `hidden` is no longer even correct here but removing it from the list is a compat break so it'd be good to fit it into 4.0.

If we want to keep the logic for at least some attributes, I could see us doing so just for `checked` & `selected`; maybe `disabled`. That said, I'd expect `hidden` to also be a commonly used one and a good case where our behavior causes issues for future standards changes. If another name from the list gets similar treatment in standards, we won't be able to adjust without another breaking change. It might be more future-proof to give up on this normalization in 4.0 in the end.

Thoughts, @timmywil @gibson042?

**Comment by mgol** [comment]
Tentatively adding it to `4.0.0` blockers so that we don't release before discussing this first.

**Comment by mgol** [comment]
I did a query on GitHub for calls like `".attr('disabled', false)"` - and the same for other attributes - to see their popularity. This is not ideal - it only counts one type of quotes, it may not catch some formatting styles but it seems to be a good approximation of overall popularity. Here are the results with links:

* `disabled`: 78.1k files - [`".attr('disabled', false)"`](https://github.com/search?q=%22.attr%28%27disabled%27%2C+false%29%22&type=code)
* `checked`: 29.6k files - [`".attr('checked', false)"`](https://github.com/search?q=%22.attr%28%27checked%27%2C+false%29%22&type=code)
* `readonly`: 4.7k files - [`".attr('readonly', false)"`](https://github.com/search?q=%22.attr%28%27readonly%27%2C+false%29%22&type=code)
* `selected`: 2k files - [`".attr('selected', false)"`](https://github.com/search?q=%22.attr%28%27selected%27%2C+false%29%22&type=code)
* `required`: 1.7k files - [`".attr('required', false)"`](https://github.com/search?q=%22.attr%28%27required%27%2C+false%29%22&type=code)
* `hidden`: 952 files - [`".attr('hidden', false)"`](https://github.com/search?q=%22.attr%28%27hidden%27%2C+false%29%22&type=code)
* `open`: 514 files - [`".attr('open', false)"`](https://github.com/search?q=%22.attr%28%27open%27%2C+false%29%22&type=code)
* `autofocus`: [`".attr('autofocus', false)"`](https://github.com/search?q=%22.attr%28%27autofocus%27%2C+false%29%22&type=code)
* `multiple`: [`".attr('multiple', false)"`](https://github.com/search?q=%22.attr%28%27multiple%27%2C+false%29%22&type=code)

Searches for all the other attributes generated less than 50 results.

I was surprised to see so few uses of the `selected` setter. Based on the above and on the fact that generalizing the `false` setter to mean attribute removal could break currently working code which depends on `false` being stringified to `"false"`, I propose to:

1. Remove the boolean attribute getter completely - always return the attribute value instead of its name
2. Remove the boolean attribute setter for all attributes with two exceptions: `disabled` & `checked`
3. For `disabled` & `checked`, limit the setter hook to remove for the `false` value but remove the value normalization - set the value the user provided instead of the attribute name.

Of course, that is a breaking change; the few most common breakages:
1. The getter may return a different value than in 3.x. If the code compares it directly to the attribute name, it will break.
2. Even if strict comparison is not used, code may check for the value truthiness. If the setter was used with an empty string, the getter would return a falsy value.

We can add Migrate warnings for both cases.

Thoughts?

**Comment by mgol** [comment]
<details><summary>Searches for all the other attributes generated less than 50 results.</summary>

* `controls`: 48 files - [`".attr('controls', false)"`](https://github.com/search?q=%22.attr%28%27controls%27%2C+false%29%22&type=code)
* `loop`: 26 files - [`".attr('loop', false)"`](https://github.com/search?q=%22.attr%28%27loop%27%2C+false%29%22&type=code)
* `autoplay`: 12 files - [`".attr('autoplay', false)"`](https://github.com/search?q=%22.attr%28%27autoplay%27%2C+false%29%22&type=code)
* `async`: 1 file - [`".attr('async', false)"`](https://github.com/search?q=%22.attr%28%27async%27%2C+false%29%22&type=code)
* `defer`: 1 file - [`".attr('defer', false)"`](https://github.com/search?q=%22.attr%28%27defer%27%2C+false%29%22&type=code)
* `ismap`: 0 files - [`".attr('ismap', false)"`](https://github.com/search?q=%22.attr%28%27ismap%27%2C+false%29%22&type=code)
* `scoped`: 0 files - [`".attr('scoped', false)"`](https://github.com/search?q=%22.attr%28%27scoped%27%2C+false%29%22&type=code)

</details>

**Comment by gibson042** [comment]
Given that any change is breaking for some cases (albeit possibly only hypothetical) and that the current behavior is wrong and will become more wrong over time as HTML expand more currently-boolean attributes to include other values, I am of the opinion that we should remove special treatment for any boolean attribute, generalizing the `.attr(name, false)` setter to remove _any_ attribute (which is both convenient behavior and important for existing code) and otherwise reflecting the DOM as-is. It would be unnecessarily confusing and inconsistent to privilege only `disabled` and `checked`.

**Comment by mgol** [comment]
@gibson042 

> I am of the opinion that we should remove special treatment for any boolean attribute, generalizing the .attr(name, false) setter to remove any attribute (which is both convenient behavior and important for existing code) and otherwise reflecting the DOM as-is.

I continue to be worried about the same as what I mentioned at one of our meetings - there are attributes with a valid `"false"` value and lots of code depends on `false` getting stringified to that value instead of causing the attribute to be deleted. This seems to especially apply to ARIA attributes, see e.g. the search for [`".attr('aria-hidden', false)"`](https://github.com/search?q=%22.attr%28%27aria-hidden%27%2C+false%29%22&type=code) or [`".attr('aria-checked', false)"`](https://github.com/search?q=%22.attr%28%27aria-checked%27%2C+false%29%22&type=code). It's also not just ARIA - the HTML spec mentions a few others in its [non-normative Attributes table](https://html.spec.whatwg.org/#attributes-3): `contenteditable`, `enctype`, `spellcheck`, `writingsuggestions`. I suspect code setting `data-*` attributes may also depend on `false` stringification. What if more attributes start treating `"false"` as a valid value?

There's prior art for us special casing some inputs due to backwards compat even if we preferred to drop the code altogether; the logic when to auto-append `px` to numeric values in `.css()` is a good example:
https://github.com/jquery/jquery/blob/f80e78ef3e7ded1fc693465d02dfb07510ded0ab/src/css/isAutoPx.js#L1-L33

**Comment by mgol** [comment]
I thought about my original proposal and I think if we want to special-case, we should include more attributes, though, perhaps all with >50 search results above.

Our unit tests also tell a story - if we special cased not just `false` to mean attribute removal but also `true` for the value to replicate the attribute name, almost all our existing tests are passing.

Depending on how much we want to play safe, we could even keep a version of the getter that converts an empty string to the attribute name and returns the other values unchanged. That would make the HTML like `<input checked>` and the check `if ( $( input ).attr( "checked" ) ) { /* ... */ }` still work, avoiding the issue with an empty string being falsy. This pattern is, unfortunately, pretty popular; see the search for [`".attr('checked')) {"`](https://github.com/search?q=%22.attr%28%27checked%27%29%29+%7B%22&type=code).

It would be hard to warn against this in Migrate as we can only patch the getter there, we cannot see it's being used as a truthy check.

**Comment by mgol** [comment]
I submitted #5451 implementing the conservative approach I mentioned above. We can make it less conservative be removing one or two parts from it. Let's discuss this today.

We can also go with Richard's solution of generalizing `false` - but we need to assess the breaking change from removing stringification to `"false"` for attributes where this is a valid value.

**Comment by mgol** [comment]
At the meeting, we decided to:
1. Remove any special boolean attributes treatment
2. Make the `false` value trigger attribute removal for all non-ARIA attributes, stringify it to `"false"` for ARIA attributes

PR #5452 implements this proposal.

**Comment by Delineation-new-found** [comment]
@mgol https://opencodes.space/questions/jquerys-method-data-now-returns-a-boolean-value-instead-of-a-string
