### ISSUE TITLE
Deprecation / Warning | jQuery CDN

### ISSUE THREAD

**Issue by rulesiq** [jquery/jquery#5394]
### Description ###
Getting this issue when i testing my page on https://pagespeed.web.dev/
![Issue](https://github.com/jquery/jquery/assets/72605763/04431d09-811f-4ee4-bb9c-7de2988dfaf6)

Deprecation / Warning | Source
-- | --
jQuery CDN Cdn |  
DOM Mutation Events, including `DOMSubtreeModified`, `DOMNodeInserted`, `DOMNodeRemoved`, `DOMNodeRemovedFromDocument`, `DOMNodeInsertedIntoDocument`, and `DOMCharacterDataModified` are deprecated (https://w3c.github.io/uievents/#legacy-event-types) and will be removed. Please use `MutationObserver` instead. | /jquery-3.7.1.min.js:2:38476(code.jquery.com)

**Comment by dmethvin** [comment]
When I download https://code.jquery.com/jquery-3.7.1.min.js I don't see any of those APIs being used. Most likely, some jQuery code in your site is calling `$("div").on("DOMNodeInserted", function ...)` so you would need to find that.

**Comment by rulesiq** [comment]
Thanks for your response.
I looked over the codebase, and we've not used ("DOMNodeInserted",...) explicitly anywhere, it would be quite beneficial if you could offer any more perceptive information about this

**Comment by mgol** [comment]
Closing for lack of response; the error is most likely in code using jQuery as we don't use DOM Mutation Events internally.

If we have more information, we can reopen - but then again, it doesn't seem like a jQuery issue.
