### ISSUE TITLE
Invalid links in blog article

### ISSUE THREAD

**Issue by vordgi** [jquery/jquery#5410]
### Description ###

I know that this is not the right place, but unfortunately, I did not find a normal communication channel, so I decided to write here.

You have incorrect links in the blog about the new release

> Changelog
> Full changelog: [3.7.1](https://github.com/jquery/jquery/compare/3.7.0...3.7.1)
>
> 4.0.0-beta ([7e9a94ec](https://github.com/jquery/jquery/commit/7e9a94ec820a6defce541e34dad13bd9669e21c7))

https://github.com/jquery/jquery/commit/7e9a94ec820a6defce541e34dad13bd9669e21c7 doesnt exist. Perhaps the correct link is https://github.com/jquery/jquery/commit/49b55127e2bb6cf6fcfcc32cba8173ad4c1b6012

Full changelog links to another version (3.7.0-3.7.1), I think correct is https://github.com/jquery/jquery/compare/3.7.1...4.0.0-beta (3.7.1-4.0.0)

**Comment by vordgi** [comment]
@timmywil @mgol Judging by the commits, I can tag you.

P.S. Great job!

**Comment by timmywil** [comment]
Thanks! Should be good now
