### ISSUE TITLE
The jquery.factory.js bundle is missing in the npm package in the 4.0.0-beta release

### ISSUE THREAD

**Issue by gdsw** [jquery/jquery#5411]
Congratulations on the release, the changes look good!

### Description ###

According to the [npm package description](https://www.npmjs.com/package/jquery/v/4.0.0-beta#nodejs-pre-requisites), in order to use jQuery with JSDOM, you can now use a Factory:

```javascript
const { JSDOM } = require( "jsdom" );
const { window } = new JSDOM( "" );
const { jQueryFactory } = require( "jquery/factory" );
const $ = jQueryFactory( window );
```

When the library is installed through npm:

```
npm install jquery@4.0.0-beta
````

The following files are available:

![image](https://github.com/jquery/jquery/assets/43776781/9f87b110-ad95-43df-889d-e57cbab24d46)

According to the `package.json`, there should be a factory in the `dist` and `dist-module` folders:

![image](https://github.com/jquery/jquery/assets/43776781/7fb10ea1-2a39-4137-afdc-6942b2aa6f50)

### Link to test case ###

This is an issue with the bundle itself, rather than some particular jQuery functionality, but the test is rather simple:

1. Install the package via NPM.
2. Create a simple `test.js` file with the following contents:
```
const { JSDOM } = require("jsdom");
const { window } = new JSDOM();
const { jQueryFactory } = require("jquery/factory");
const $ = jQuery = jQueryFactory( window );

console.log("success");
```
3. And run it:
`node test.js`

![image](https://github.com/jquery/jquery/assets/43776781/ea0f0b35-2f21-4540-8ad1-439cbd552998)

I am guessing that the following array is the culprit:

https://github.com/jquery/jquery/blob/main/build/release/dist.js#L15

**Comment by mgol** [comment]
We need to ensure all files referenced anywhere in `package.json` (especially somewhere in `exports`) are present in the published package.

**Comment by timmywil** [comment]
Looks like the list [here](https://github.com/jquery/jquery/blob/main/build/release.js#L7) was updated with `dist-module` files, but not factory files.
