### ISSUE TITLE
v4 beta : mottie/tablesorter plugin fails with sort() and trim() missing

### ISSUE THREAD

**Issue by aavmurphy** [jquery/jquery#5417]
https://github.com/Mottie/tablesorter

Using the v4.0.0  beta fails with sort() and trim().

Could be its best not to remove the "depreciated" APIs/methods just yet. Maybe have them do `console.warn()` for now?

**Comment by mgol** [comment]
These APIs have already been deprecated for a couple years.

For projects not ready for removal of those APIs, it'll be possible to load the jQuery Migrate plugin to fill in the removed APIs. We don't plan to bring them back to the core library at this point, though.
