### ISSUE TITLE
Jquery-UI getting Error With  jQuery	 jQuery 4.0.0 BETA! 

### ISSUE THREAD

**Issue by AviHafner** [jquery/jquery#5421]
Jquery Ui get error Getting an error when using **Jquery-UI TAB** when we are working with  **jQuery 4.0.0 BETA!** 

attach 2 file with  errors
1) Uncaught TypeError: Cannot read properties of undefined (reading 'test')
![Jquery-UI-Error](https://github.com/jquery/jquery/assets/9378759/9894cf66-0d57-421f-ae24-bdbc4b1d4dea)
2)  jQuery.Deferred exception TypeError: Cannot read properties of undefined (reading 'test')
![Jquery-UI-Error-2](https://github.com/jquery/jquery/assets/9378759/cfe6a1e7-d9a3-4ed4-a39b-691eac4fbc30)

**Comment by nagyimre1980** [comment]
jquery-migrate version 3.4.1 is incompatible with jquery 4.0.0.
I already reported it, fixed it, next version will fix it.

[https://github.com/jquery/jquery-migrate/issues/495](url)

**Comment by timmywil** [comment]
Thanks @nagyimre1980! I think tracking that in jquery-migrate is sufficient. jQuery 4.0.0 final will come with a migrate release and an upgrade guide.

**Comment by AviHafner** [comment]
Thanks @nagyimre1980!  and @timmywil 
**Jquery Ui** Working with **Jquery-4**
The only thing that doesn't compatible is [jquery-migrate-3.4.1](https://code.jquery.com/jquery-migrate-3.4.1.js)
