### ISSUE TITLE
Memory Leak: OriginAnchor 

### ISSUE THREAD

**Issue by melloware** [jquery/jquery#5457]
### Description ###

Running plain jQuery 3.7.1 and then do a Chrome Heap Snapshot.  You will see the OriginAnchor is detached.

![image](https://github.com/jquery/jquery/assets/4399574/feb18581-e782-4b31-8e02-e2b2bfeff97d)

### Reason ###

You are storing a ref to an anchor and constantly checking it.

```js
// Anchor tag for parsing the document origin
originAnchor = document.createElement( "a" );

originAnchor.href = location.href;

s.crossDomain = originAnchor.protocol + "//" + originAnchor.host !==
					urlAnchor.protocol + "//" + urlAnchor.host;
```

### Solution ###

The solution is to store off the value you need and de-reference the originAnchor.

```js
// Anchor tag for parsing the document origin
originAnchor = document.createElement( "a" );

originAnchor.href = location.href;
var originProtocolHost = originAnchor.protocol + "//" + originAnchor.host;
originAnchor = null;

s.crossDomain = originProtocolHost !== urlAnchor.protocol + "//" + urlAnchor.host;
```

**Comment by mgol** [comment]
Thanks for the report but I don’t understand the issue. Can you elaborate why the current behavior is problematic?

**Comment by melloware** [comment]
Well its a detached unused element reported by Chrome as a leak.   Why keep an anchor around you don't need?  I don't understand what you are asking that you don't understand?

The goal should be to never have detached DOM elements right?

**Comment by mgol** [comment]
It’s a single element, it doesn’t block a lot of memory. By keeping it, we avoid having to recreate one each time we need to normalize the href parts.

I understand you can find it in Chrome memory report but does it really cause any issue for the running website? Just seeing the node in a memory report is not a sufficient reason to change the code IMO.

**Comment by timmywil** [comment]
Thank you for your contribution, but I don't think a change is needed here. This is not a memory leak. See https://github.com/jquery/jquery/issues/5458#issuecomment-2022921263
