### ISSUE TITLE
Issue using JQuery 3.7.1 and CSP

### ISSUE THREAD

**Issue by nalumachurakesh** [jquery/jquery#5476]
Hi

I'm using jquery 3.7.1 and implementing CSP. Earlier I used "unsafe-inline" and "style-src" but when I removed it I'm getting CSP related errors in the jquery file. Below are the attached screenshots.

![image](https://github.com/jquery/jquery/assets/13477420/193551a0-8254-456f-810f-f4a73cce695e)

![image](https://github.com/jquery/jquery/assets/13477420/382fb29d-e22a-4f93-9cc0-450d534f55db)

![image](https://github.com/jquery/jquery/assets/13477420/cc96014e-2b3d-4786-85b2-0310f5262345)

![image](https://github.com/jquery/jquery/assets/13477420/ed2883b2-15df-40f8-9da9-62ec0fe1412f)

I don't want to use "unsafe-inline" in "style-src". Is there a way to resolve this error without "unsafe-inline"?

Thank you.

**Comment by rorymulcahey** [comment]
I'm having a similar issue (with 3.5.1), interesting it was closed immediately by the author.

Was this addressed in 3.6.0?
https://github.com/jquery/jquery/pull/4763#issuecomment-665786118

Or planned in 4.0?
https://github.com/jquery/jquery/issues/4343#issuecomment-480188915

At the bottom of pull 4763 it references pull 4773 which was merged into version 3.6.0, but after seeing this post I am second guessing my observations.
