### ISSUE TITLE
Fix CSS test issues in Firefox coming from CSS zoom support

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#5489]
### Description ###

Firefox implemented CSS zoom in version 126. That version fails our CSS tests.

Snapshot from `main`:
<img width="948" alt="Screenshot 2024-05-20 at 18 56 59" src="https://github.com/jquery/jquery/assets/1758366/0d510c94-1e49-4a36-aefd-d26146de4e16">

Snapshot from `3.x-stable`:
<img width="946" alt="Screenshot 2024-05-20 at 18 58 42" src="https://github.com/jquery/jquery/assets/1758366/f852f8fe-74f9-4493-a8c5-96cd88db6d08">

The `main` version may just need a test tweak but the `3.x-stable` one seems like a genuine failure. We'll need to investigate before the next release.

### Link to test case ###

N/A, our own tests are failing.

**Comment by mgol** [comment]
It looks like in Firefox 126 stable zoom affects `offsetWidth` values. In 127 Developer Edition & 128 Nightly it does not, just like it does not in Chrome.

Fortunately, [Firefox 126 will not be ESR](https://whattrainisitnow.com/calendar/).

**Comment by timmywil** [comment]
I'd like to fix this before beta.2, even if just a test fix.

**Comment by mgol** [comment]
PRs:
* `main`: #5495
* `3.x-stable`: #5496
