### ISSUE TITLE
Upgrade issues for jquery

### ISSUE THREAD

**Issue by jfrew9** [jquery/jquery#5502]
Cannot update jquery from 3.7.0 to 3.7.1

get this information
Unable to resolve dependencies. 'jQuery 3.7.1' is not compatible with 'AspNet.ScriptManager.jQuery 3.7.0 constraint: jQuery (>= 3.7.0 && < 3.7.1)'.

I'm using Visual Studio 2022
There is no update for AspNet.ScriptManager.jQuery

**Comment by mgol** [comment]
This is not an issue with jQuery

**Comment by jfrew9** [comment]
Not sure your answer of not an issue with jQuery when the update message clearly states jQuery is not compatible. If this is not a jQuery issue then where do I look next. I had to go back to version 2.4.1 to get my application to start working again

**Comment by mgol** [comment]
The tool you're using specifies it requires jQuery `>= 3.7.0 && < 3.7.1` - in other words, it explicitly only allows version `3.7.0`. The tool needs an update, there's nothing that jQuery can do here.
