### ISSUE TITLE
Documentation for jQuery.contains()

### ISSUE THREAD

**Issue by oyosoftware** [jquery/jquery#5510]
On page https://api.jquery.com/jQuery.contains/#:~:text=contains()%20method%20returns%20true,text%20or%20comment%20node%2C%20%24. there is a contradiction.
Both description and examples can't be true.
I think the examples are wrong.
An element cannot contain the body, so this must be false.
The body can contain an element, so this must be true.
In the examples it's the other way around.

**Comment by dmethvin** [comment]
Can you provide a code example we can run that shows how the description is incorrect?

**Comment by oyosoftware** [comment]
It’s on your own page.

I tried:

 

var element = document.getElementById("test");

console.log($.contains(element, document.body)); // false

console.log($.contains(document.body, element)); // true

 

Van: Dave Methvin ***@***.***> 
Verzonden: donderdag 13 juni 2024 13:48
Aan: jquery/jquery ***@***.***>
CC: oYoSoftware ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jquery/jquery] Documentation for jQuery.contains() (Issue #5510)

 

Can you provide a code example we can run that shows how the description is incorrect?

**Comment by oyosoftware** [comment]
Also, html is an element too. In that case it’s the other way around.

 

console.log($.contains($("html")[0], document.body)); // true

console.log($.contains(document.body, $("html")[0])); // false

 

Van: Dave Methvin ***@***.***> 
Verzonden: donderdag 13 juni 2024 13:48
Aan: jquery/jquery ***@***.***>
CC: oYoSoftware ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jquery/jquery] Documentation for jQuery.contains() (Issue #5510)

 

Can you provide a code example we can run that shows how the description is incorrect?

**Comment by mgol** [comment]
Not `element` but `documentElement` which is the element represented by the `<html>` tag. It does contain the body. The examples are correct.
