### ISSUE TITLE
.on("compositionstart compositionupdate compositionend") handler are not implemented.

### ISSUE THREAD

**Issue by kipid** [jquery/jquery#5530]
### Description ###

```
$("#textarea-key-test")on("compositionstart compositionupdate compositionend input", (e) => {
	$("#result").prepend(`e.data=${e.data} on e.type=${e.type}<br />`);
});
```

The above code does NOT work properly.

### Link to test case ###

https://kipid.tistory.com/entry/event-keyCode-deprecated-then-event-key-event-code-%EB%8A%94-%EB%AC%B4%EC%8A%A8%EA%B0%92%EC%9D%84-%EA%B0%80%EC%A7%88%EA%B9%8C

Use google translate. Sorry for the language.

I think that you should put "compositionstart compositionupdate compositionend" additionally to the

```
ce.each("blur focus focusin focusout resize scroll click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup contextmenu" ...
```

to become

```
ce.each("blur focus focusin focusout resize scroll click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup contextmenu **compositionstart compositionupdate compositionend**" ...
```

Hope this issue will be resolved ASAP.

p.s. the above solution does NOT help my problems. I need help.

**Comment by timmywil** [comment]
Thanks for your issue. However, this is not enough information for a bug report and it looks like what you're looking for is support. You should find https://stackoverflow.com more helpful for that.
