### ISSUE TITLE
Different behaviour of document ready in Firefox vs Chrome with regards to injecting additional scripts

### ISSUE THREAD

**Issue by vxsx** [jquery/jquery#5533]
### Description ###
This is a bit of a convoluted edge-case but please bear with me. 

Inside `$(document).ready` if I append a script to head of the document the script then loads and executes. However, in Chrome (127.0.6533.100) this script will delay the "load" event and it will only be triggered after the script is executed (which would run any 'load' event handlers added in this new script), but in Firefox (tested in 115.14.0esr and 129.0.1) the load event will fire immediately without waiting for the new script to finish loading and any load handlers declared in it won't fire. 

If I remove the document ready wrapper (and my silly script is at the bottom of the document) - both work the same way, "delaying" the load event. 

### Link to test case ###
Sadly couldn't figure out how to make jsbin work for multifile repro, but here is what I have:

index.html:
```html
<!DOCTYPE html>
<html lang='en'>
 <head>
  <title>document ready bug</title>
  <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
 </head>
 <body>
  <script>
      function embedScript(url) {
        return new Promise(function pr(resolve, reject) {
            var newScript = document.createElement("script");
            newScript.type = "text/javascript";
            newScript.src = url;
            newScript.onload = resolve;
            document.head.appendChild(newScript);
        });
    }


    $(document).ready(function () {
        console.log('ready');
        embedScript('./test-onload.js').then(function() {
            console.log('promise finished');
        })
    });
    window.addEventListener('load', function () { console.log('load event from template'); });
  </script>
 </body>
</html>
```

test-onload.js:
```js
const init = function () {
    console.log('load event from script');
}

window.addEventListener('load', init);
```

in chrome the result is:
```
ready
promise finished
load event from template
load event from script
```

in ff:
```
load event from template 
ready
promise finished
```

**Comment by dmethvin** [comment]
There's no guarantee that the load event in the async-injected script is attached before the document's load event occurs. The document's load event doesn't wait for async-injected scripts. So yes there can be browser differences, and even differences depending on the size of the document and the timing of the async-injected script's arrival.

**Comment by vxsx** [comment]
It is not the behavior to be relied on, _for sure_. The browser behavior was very consistent though and not just in the reduced example. 

I still expected it to be different from `document.addEventListener('DOMContentLoaded', ...)` in the same browser (sorry, I should have mentioned that this behaves the same way as not having document ready wrapper), but fair, I guess.

**Comment by timmywil** [comment]
We discussed this in the meeting and we like Dave's answer. I don't think we'll be making changes here. Order is not necessarily guaranteed to be consistent across browsers. Also, we're hesitant to make those sorts of changes to the ready code, which has gone through so many iterations over the years already.

**Comment by vxsx** [comment]
Fair. Thanks
