### ISSUE TITLE
jquery-latest.min.js URL Serving Outdated Version 1.11.1 Instead of Latest Version 3.7.1

### ISSUE THREAD

**Issue by pkbarbiedoll** [jquery/jquery#5536]
### Description ###

When accessing the URL https://code.jquery.com/jquery-latest.min.js, the file served is version 1.11.1 of jQuery. However, I expected this URL to return the latest stable version of jQuery, which is currently 3.7.1.

**What I expect to happen:**
The URL https://code.jquery.com/jquery-latest.min.js should return the latest version of jQuery, which is 3.7.1.

**What actually happens:**
The URL returns version 1.11.1 of jQuery, which is outdated.

**Browsers affected:**
All browsers are affected by this issue.

### Link to test case ###
You can replicate the issue by visiting https://code.jquery.com/jquery-latest.min.js in any browser.

### Suggestion ###

Disable jquery-latest.* altogether or offer up the latest version.

**Comment by mgol** [comment]
This is expected. The “latest” files were discouraged for a long time and many years ago we finally decided to freeze the version forever.

These files shouldn’t be linked from our sites, where did you get a link? We maintain them only for backwards compatibility.
