### ISSUE TITLE
ESLint should enforce ES 5 in tests

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#5542]
### Description ###

#5523 used a template literal in the test, with GitHub Actions all green. ESLint should catch it and it should not allow ES2015+ syntax in test files.

**Comment by neogy-akash** [comment]
Hey @timmywil  @mgol  is it an inherent problem with eslint or can I give the below  override in the rules defined in **eslint-config-jquery**  https://github.com/jquery/eslint-config-jquery

```
overrides: [
		{
			files: ["test/*", "test/data/**", "test/integration/**", "test/unit/**"],
			excludedFiles: [
				"test/data/badcall.js",
				"test/data/badjson.js",
				"test/data/support/csp.js",
				"test/data/support/getComputedSupport.js",
				"test/data/core/jquery-iterability-transpiled.js",
			],
			rules: {
				quotes: ["error", "single", { "allowTemplateLiterals": false }],
			},
		},
	],
```

**Comment by mgol** [comment]
We just need to configure ESLint to require ES5 for test files, as we already do for source. Mentioning individual ES2015+ language features is not necessary.

**Comment by neogy-akash** [comment]
> We just need to configure ESLint to require ES5 for test files, as we already do for source. Mentioning individual ES2015+ language features is not necessary.

Hey, thanks for the reply....should I change the **ecmaversion** property for test files as '5' from '2015 in the eslint config file ?

```
// Tests
	{
		files: [
			"test/*",
			"test/data/**",
			"test/integration/**",
			"test/unit/**"
		],
		ignores: [
			"test/data/badcall.js",
			"test/data/badjson.js",
			"test/data/support/csp.js",
			"test/data/support/getComputedSupport.js",
			"test/data/core/jquery-iterability-transpiled.js"
		],
		languageOptions: {
			_**ecmaVersion: 2015,**_
			sourceType: "script",
			globals: {
				...globals.browser,
				require: false,
				trustedTypes: false,
				QUnit: false,
				ajaxTest: false,
				testIframe: false,
				createDashboardXML: false,
				createWithFriesXML: false,
				createXMLFragment: false,
				includesModule: false,
				moduleTeardown: false,
				url: false,
				q: false,
```

**Comment by mgol** [comment]
Yes, I think that should be enough, but you'll need to check.

**Comment by neogy-akash** [comment]
> Yes, I think that should be enough, but you'll need to check.

Ok...I'll raise a PR for that...will attach screenshot of running it on a test file with template literals...can you please review it?

**Comment by mgol** [comment]
Someone will review it for sure; please don’t ask for specific time commitments, though! Thanks!

**Comment by neogy-akash** [comment]
Hey @mgol  I checked by running a basic unit test file with template literals and with **ecmaVersion** 2015 it throws error if double quotes are not used...as defined in  **eslint-config-jquery**  rules but if we change it to 5 it will work by not recognizing the character but other tests are failing as ES5 doesn't recognize **promise** and **symbol** . Should I proceed with changing the **ecmaVersion**  to 5 or should I exclude the files it throws these exception in eslint config?
 I am attaching  the screenshots below...

**With version 2015**

![image](https://github.com/user-attachments/assets/31702ac8-e8df-45f4-b8fc-9499d5bcb440)

**With version 5**

<img width="721" alt="image" src="https://github.com/user-attachments/assets/d0a190da-6a29-4c35-b82c-4e974a47f1d2">

**Comment by mgol** [comment]
We should declare ecmaVersion to 5 but still allow Promise by adding it to `globals` - in tests, we already load a polyfill for it.

**Comment by neogy-akash** [comment]
Hey @mgol  I have raised a PR for this issue please review it. Thanks :)
https://github.com/jquery/jquery/pull/5563
