### ISSUE TITLE
adding an avent on('change') or change() and then .off() and again .change() disable selecting the item

### ISSUE THREAD

**Issue by gentuser** [jquery/jquery#5543]
### Description ###

Using jquery v. 3.7.1
Using this code:
```
$('#product_ownership_team_select').change(function(e){                        
                      
                        populate_option_managed_ci(data_set1);
                        
                    });
$('#product_ownership_team_select').off();

$('#product_ownership_team_select').change(function(e){                        
                      
                        populate_option_managed_ci(data_set2);
                        
                    });
```

### Link to test case ###
adding an event on('change') or change()  to a select and then .off() and again change(), it disables the select. The correct value and text are picked, but the text in the select doesn't change.

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by gentuser** [comment]
Many apologies, it seems to work fine. The problem happens with Select2. I will open a new issue on the right channel.
[https://jsbin.com/keqoweteyu/edit?html,js,console,output](url)
