### ISSUE TITLE
Listener added for a 'DOMSubtreeModified' mutation event. Support for this event type has been removed, and this event will no longer be fired.

### ISSUE THREAD

**Issue by mrsjakie** [jquery/jquery#5546]
### Description ###
Use of bootstrap daterangepicker gives this in Chrome Version 128.0.6613.113 (Official Build) (64-bit):
[Deprecation] Listener added for a 'DOMSubtreeModified' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.
jquery-3.7.1.js:4997

**Comment by mgol** [comment]
jQuery doesn't attach a handler for this even by itself, it's either your code or another library using jQuery. There's nothing to change in jQuery here.

**Comment by lelise** [comment]
what  jqyery library can use
