### ISSUE TITLE
Please do not create two situations

### ISSUE THREAD

**Issue by Yasinrabiee** [jquery/jquery#5555]
If possible, please avoid creating two different situations. For example, when we want to use the css function, we have to enclose the properties in single quotes or double quotes. However, in the animate function, we do not need to do this. This can sometimes be confusing. If it's possible, please fix this issue

Thanks.

**Comment by mgol** [comment]
`.css()` allows to provide an object mapping properties into values (https://api.jquery.com/css/#css-properties), but it also has a shortcut version for a single property where the property & the value are two separate string parameters (https://api.jquery.com/css/#css2).

For `.animate()`, this second API would be confusing, as it needs more parameters - at least the duration & the easing function.

The fact that some strings don’t need to be wrapped in quotes when used as keys in an object literal definition has nothing to do with jQuery, it’s just how JavaScript works. You can always wrap strings in quotes if you prefer.

**Comment by Yasinrabiee** [comment]
Ok, Thanks.
