### ISSUE TITLE
The attr method still adds true and false to non-aria attributes

### ISSUE THREAD

**Issue by gdsw** [jquery/jquery#5573]
### Description ###

Hello, I was going through the changes that were introduced with the second beta of jQuery 4.0 and I am not quite sure that I understand the part about `attr` correctly.

The following is stated in the blog post:

> This patch removes any special handling of boolean attributes – the getter returns the value as-is and the setter sets the provided value, with one exception. To maintain backwards compatibility, this patch makes the false boolean value trigger attribute removal for ALL non-ARIA attributes.

If I understand that correctly, the following snippet:

```javascript
 $("#1").attr("disabled", true);
```

Should produce the following output:

```html
<input id="1" disabled />
```

And `$("#1).attr("disabled", false)` should remove the attribute.

However, right now the disabled attribute is being set as `disabled="true"`.

### Link to test case ###

The above can be observed in the following jsbin

https://jsbin.com/dokiqopano/edit?html,output

![image](https://github.com/user-attachments/assets/8730dcb1-7925-479a-92c8-4f2d1ecb93d3)

**Comment by timmywil** [comment]
Thanks for opening an issue. That's how it used to work. However, given that browsers only care whether there is a value for boolean attributes, and not what the value is, we opted to pass through any values untouched. However, passing through `false` would rarely be intended behavior, so we kept the part that removed the attribute when setting to `false`. The behavior is intended and the blog post is correct. 

> the setter sets the provided value

meaning, `true` is passed through

> false boolean value trigger attribute removal

and this still works
