### ISSUE TITLE
A safe way to accept jQuery / Element(s) / Selector, but not HTML?

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#5574]
### Description ###

jQuery UI had an advisory https://github.com/jquery/jquery-ui/security/advisories/GHSA-gpqq-952q-5327 that an option accepting a selector may lead to creation of new DOM elements. The fix was as follows:
```js
// Make sure string options are treated as CSS selectors
target = typeof options.of === "string" ?
	$( document ).find( options.of ) :
	$( options.of ),
```
However, jQuery 4 will support trusted types wrappers. They won't pass a typeof check above, ending up in creation of new elements.

I wanted to fix it, but I was not able to find a clean way for an API to accept existing jQuery objects or DOM element(s) for wrapping, or a CSS selector to find an existing element - but at the same time not allow creation of new DOM nodes. If just a selector is supported, `$( document ).find( selector )` works, but I don't see a safe way to invoke `$( input )` without repeating some of the internal checks jQuery does in `jQuery.fn.init`.

A `nodeType` check is not always enough, as `window` would get excluded at the very least.

Another option is:
```js
$.makeArray( ofOption, $() )
```
which would create a jQuery object of length 1 and the first "element" just being a TrustedHTML wrapper of `<div foo>`. No new elements here, but such an element is not valid and if someone down the line expects sensible data and wraps with `$()`, new elements will get created. Also, it feels a bit hacky.

**Comment by timmywil** [comment]
According to that advisory, the issue was fixed in UI 1.13. Is that wrong?

**Comment by timmywil** [comment]
I see, you're saying the introduction of trusted types throws a wrench in it, but as you commented, I don't know if we need to worry about that. Trusted types are...trusted. At least, it puts the responsibility elsewhere.

**Comment by timmywil** [comment]
We discussed this and landed on the use case being a bit too esoteric. The input would have to be both unsanitized and wrapped in a trusted type. The specific case that the notices warn against have still been addressed.
