### ISSUE TITLE
animate and css function 

### ISSUE THREAD

**Issue by Yasinrabiee** [jquery/jquery#5576]
When we want to use the css method, we have to circle the attributes, but we don't have to for the animate function
This makes the work difficult and sometimes causes mistakes...

```js
  $('#demo').css({
      'color': 'red'
  });
```
```js
  $('#demo').animate({
      color: 'red'
  });
```

**Comment by timmywil** [comment]
Thanks for opening an issue. Please provide a reduced test case from https://jsfiddle.net. Alternatively, close and reopen an issue that follows the bug report template.

**Comment by Yasinrabiee** [comment]
This problem is not something to show
This was just a suggestion from me to improve your library

**Comment by timmywil** [comment]
ok, then I don't quite follow the suggestion. If you're referring to the quotes in the first example, that is not related to jquery.

Closing for now, but feel free to put together a plugin to show off if I missed something and we can reconsider.

Also have a look at https://github.com/jquery/jquery/wiki/Adding-new-features to learn more about how we evaluate new features.

**Comment by mgol** [comment]
Also, you definitely don’t have to put `color` in your `.css()` example in single quotes; just like you didn’t have to for `.animate()`. It’s how JavaScript works.
