### ISSUE TITLE
Also cache resolved CSS property names that are unprefixed

### ISSUE THREAD

**Issue by vlakoff** [jquery/jquery#5582]
Coming from discussion https://github.com/jquery/jquery/discussions/5516, in particular this message: https://github.com/jquery/jquery/discussions/5516#discussioncomment-11270207.

Excerpt:
> However, I noticed that when querying a CSS property name that exists unprefixed, it doesn't get cached into the `vendorProps` map (contrarily to the prefixed names, that get cached).
> 
> Therefore, when querying unprefixed names, each time there is one lookup in the `vendorProps` map then one lookup in the `emptyStyle` object, whereas we could save the latter (after the cache is populated on first access).

Current code: [finalPropName.js](https://github.com/jquery/jquery/blob/d5ebb464debab6ac39fe065e93c8a7ae1de8547e/src/css/finalPropName.js)

Also, I just noticed that previously the unprefixed names were cached at well, but it is no longer the case since commit https://github.com/jquery/jquery/commit/2b5f5d5e90b37f4a735738a6d0b6f22affbea340.

**Comment by timmywil** [comment]
Thanks for opening an issue. I don't know if it would actually make a noticeable difference in performance, but it does seem likely that the change in cache behavior was unintentional.

**Comment by timmywil** [comment]
We discussed this in the meeting. We're leaning towards removing the cache altogether on the main branch as it doesn't seem to add much value.

**Comment by mgol** [comment]
We went in a different direction and in #5583 we removed the cache altogether. See that PR for a more detailed discussion.
