### ISSUE TITLE
use .html() method to set HTML contents raise an error

### ISSUE THREAD

**Issue by htaebi** [jquery/jquery#5591]
### Description ###
jQuery 3.7.1
Chrome Version 131 (131.0.6778.109)

if you want to set a bad html to an element, it raises an unhandled error.
attackers can use this bug for XSS !!!

Code:
` jQuery('#selector').html('test</table><tr>test')`

Thank you

**Comment by mgol** [comment]
Thanks for the report.

If you have a real example of a security bug in jQuery with the XSS demonstrated (this example does not do this), please send it to security@jquery.com, not on GitHub.

jQuery 4.0 will have improved handling of HTML input, making it impossible to escape the table wrapper, BTW.
